### ISSUE TITLE
Doesn't append instance parameters

### ISSUE THREAD

**Issue by marcus-sa** [axios/axios#1000]
#### Summary
I'm trying to create a new axios instance with default params assigned.
The baseURL is appended, but not the params:

I have a **static** HTTP class that I clone with options for an axios instance:
```
static create(options: Object = {}): Object {
    // See comment for class cloning <https://stackoverflow.com/a/41474987>
    const clone = Object.assign(Object.create(this), this)

    return Object.defineProperty(clone, 'axios', {
      enumerable: false,
      configurable: false,
      writable: false,
      value: axios.create(options)
    })
  }
```
And then I have a TMDbProvider class that uses the cloned class from HTTP.
```
constructor(state) {
    this.http = HTTP.create({
      baseURL: `${config.TMDB.API}/3`,
      params: {
        api_key: config.TMDB.KEY,
        language: state.saved.prefs.iso4,
        append_to_response: 'external_ids,videos'
      }
    })
  }
```

Example of a get function in the HTTP class:
```
  static get(url: String, params: Object): Promise {
    return this.axios.get(url, { params })
      .then(res => res.data)
  }
```

As stated above in the summary, the default params doesn't get attached as shown below.
`/home/sentinel/git/venobo-redux/node_modules/axios/lib/adapters/xhr.js:178 GET https://api.themoviedb.org/3/movie/76341 401 (Unauthorized)`

But if I `console.log` the `clone.axios.defaults` object then the params are assigned.

**Comment by marcus-sa** [comment]
Just recoded it all to create a new HTTP instance instead of it being static.
Same error occurs, but when I console.log `this.axios.defaults` before doing a request, it says the params exists in the axios instance, but they don't get appended to the url.

**Comment by cfjedimaster** [comment]
I just ran into this as well and was pretty surprised. Using default params for APIs is pretty common. Any simple workaround (outside of adding it to my get()) call?

**Comment by jurpeedurp** [comment]
A temporary workaround is to use an interceptor:

```
            const client = axios.create()

            client.interceptors.request.use((config) => ({
                ...config,
                params: {
                    ...config.params,
                    api_key: 'xxx'
                }
            }))
```

**Comment by chinesedfan** [comment]
`config.params` is replaced directly, instead of merge. Users can write an interceptor as https://github.com/axios/axios/issues/1000#issuecomment-503765362 mentioned.

**Comment by cfjedimaster** [comment]
Why is this closed though? Just because a workaround exists doesn't mean that the core issue isn't a... well an issue. If it's perhaps me (and others) misreading the docs, then perhaps the real issue is simply a documentation change that should be made to make it clear.

Right now the docs say, "You can specify config defaults that will be applied to every request." which to me makes it VERY clear that I should be able to use it for the case I mentioned above (an api key) and if that is truly not the case, then we should edit the docs to clarify that you can't specify defaults for GET requests.

I'd argue that this should be re-opened until it's clear.

**Comment by chinesedfan** [comment]
@cfjedimaster Opened #2618. Thanks for your feedback.
