### ISSUE TITLE
Axios waits for timeout (when configured) even if nock throws an error

### ISSUE THREAD

**Issue by pbarbiero** [axios/axios#1004]
#### Summary

When using nock and axios on the server side (node environment) to mock requests and responses, I ran into an interesting issue when I have axios configured with a timeout value.

If nock is not configured for a particular request, it throws an error: `Error: Nock: No match for request`.
If axios does NOT have a timeout value set, no thread is left open and hanging and the test suite closes as normal. 
If a timeout value IS set, axios waits the entire duration of the timeout before closing. Whats weird is the promise axios returns is rejected by nock (which is how I found that error above) so I have no idea why axios stays open for the full timeout.

The issue is in test runners (specifically Jest) will remain open until all threads are done. With axios hanging open here, our test times ballooned without any visible reason and it took me several hours to trace it to this change that caused it.

I have a simple workaround, if in the test environment don't set a timeout value (or make sure we nock all requests) but it feels like a bug to me that the axios promise throws but yet it remains running.

#### Context

- axios version: *v0.16.2*
- nock version: *v9.0.13*
- jest version: *v20.0.4*
- Environment: *node v6.10.2*

**Comment by rubennorte** [comment]
You're right. It seems the issue is here: https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L197

If the request is aborted we just return without clearing the timeout.

Would you be interested in creating a PR for this?

**Comment by pbarbiero** [comment]
@rubennorte sure, I need some guidance however. Is it just a matter of clearing the timeout on abort in that error callback if aborting?

**Comment by rubennorte** [comment]
This should be easy to implement as you don't need to modify any tests (this specific use-case is hard to test so we can do it without them).

I'd decorate the `resolve` and `reject` functions in the Promise so when called you always clear the interval. If it was already cleared it won't cause any errors so you don't need to check it before.

E.g.:

```javascript
return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise) {
  var timer;
  var resolve = function resolve(value) {
    clearTimeout(timer);
    resolvePromise(value);
  };
  var reject = function reject(value) {
    clearTimeout(timer);
    rejectPromise(value);
  };
  ...
```

This way you can remove the rest of `clearTimeout` calls in the code.

**Comment by dylburger** [comment]
Forgive my naïveté but is there a specific reason the `clearTimeout` code was removed from the `resolve` and `reject` methods? Current master has:

https://github.com/axios/axios/blob/93e69625a69ef7bbcf14c9bcb2a1cba2d4b5a126/lib/adapters/http.js#L21-L27

So the original issue appears to still be a problem on the latest version of axios.

Let me know if you need any other information from me. Thanks!
