### ISSUE TITLE
Ignoring Proxy Config with React Native

### ISSUE THREAD

**Issue by transifex3** [axios/axios#1058]
#### Summary

When trying to fetch to server with proxy, it just ignores proxy setting and fetch to server.
This problem already mentioned in this issue (https://github.com/mzabriskie/axios/issues/672)
But closed for some reason. and still occurred now.
I am using latest versions of react-native, and axios. 
Here is my code below.

```
let config = {
      proxy: {
        host: '127.0.0.1',
        port: 8118
      }
    }
    axios.get('https://api.ipify.org/', config)
    .then(function (response) {
      console.log("-----------");
      console.log(response.data);
      console.log("-----------");
    })
```

Output: _`Original IP, not proxied one`_

#### Context

- axios version: v0.16.2
- Environment: node v.8.3.0, and react-native-cli 2.0.1

**Comment by robaxelsen** [comment]
Closing, [see duplicate.](https://github.com/axios/axios/issues/648)

**Comment by mrmarktyy** [comment]
I am still having this issue with react-native 0.57.1 (Expo 32.0.0)

**Comment by rishabhbhatia** [comment]
@mrmarktyy Hey Mark how did you manage to solve it? 
I'm trying to call a proxy server from react-native and unable to do so, any help would be really appreciated.
