### ISSUE TITLE
How to solve the compatibility problem of ios9?

### ISSUE THREAD

**Issue by bandow** [axios/axios#1060]
post 取不到值，怎么解决呢？

Post can not get the value, how to solve it?

**Comment by robaxelsen** [comment]
Hi @bandow, and thanks for your issue. Could you please provide us with some more details about the compatibility problem you're facing?

----

@mzabriskie @nickuraltsev @rubennorte in accordance with the [Collaborator Guide](https://github.com/axios/axios/blob/master/COLLABORATOR_GUIDE.md) I propose to close this issue on 16.01.2018 if no response from OP.
