### ISSUE TITLE
Absolute HTTPS error reverts back into an HTTP request, results to an insecure request

### ISSUE THREAD

**Issue by inonbaguio** [axios/axios#1066]
#### Summary

We've tried to experiment using an absolute https url when using Axios. We've noticed that when using an absolute url, it reverts back into an https request. As a workaround, we just a relative url `axios.get('/relativeUrl')...`

```
        axios.get('https://urlSomething/route`)
            .then(response => {
                this.setState({
                    isAdminLoggedIn: response.data.isAuthenticated,
                });
            })
```

#### Context

- axios version: *v0.16.2*
- Environment: *npm v3.10.9, node v6.9.2*

**Comment by Axnyff** [comment]
Hello, did you try to upgrade your axios version? It seems to work fine for me with 0.17.1.

Otherwise, there might be something I am missing, are you able to produce a reproduction of the bug?

**Comment by chinesedfan** [comment]
Closed due to stale.
