### ISSUE TITLE
axios rpc in addition to restful API

### ISSUE THREAD

**Issue by laoshaw** [axios/axios#1069]
this is a newbie question, can Axios do RPC (e.g. json-rpc) in addition to its existing REST calls?

**Comment by robaxelsen** [comment]
Hi @laoshaw, and thanks for posting your question. I am afraid axios does not offer any rpc support, no.

-----

@mzabriskie @nickuraltsev @rubennorte in accordance with the [Collaborator Guide](https://github.com/axios/axios/blob/master/COLLABORATOR_GUIDE.md) I propose to close this issue on 16.01.2018 if no response from OP.

**Comment by doitlikepruett** [comment]
Would you be open to a PR to add support for json RPC 2.0, or should this be an outside library?
