### ISSUE TITLE
cannot no trigger the mothod of 'window.XMLHttpRequest.prototype.send'

### ISSUE THREAD

**Issue by kannieXu** [axios/axios#1071]
when i use window.XMLHttpRequest.prototype.open and window.XMLHttpRequest.prototype.send to get all request,the readyState only 0 and 1.I cannot find the answer for this question.I hope you can answer my question
`      
         var _XMLHttpRequest = window.XMLHttpRequest;
	      if (!_XMLHttpRequest) {
	        return;
	      }

	      var that = this;
	      var _open = window.XMLHttpRequest.prototype.open,
	          _send = window.XMLHttpRequest.prototype.send;
	      that._open = _open;
	      that._send = _send;

	      // mock open()
	      window.XMLHttpRequest.prototype.open = function () {
	        var XMLReq = this;
	        var args = [].slice.call(arguments),
	            method = args[0],
	            url = args[1],
	            id = that.getUniqueID();

	        // may be used by other functions
	        XMLReq._requestID = id;
	        XMLReq._method = method;
	        XMLReq._url = url;
	        // console.log('in', XMLReq.readyState)

	        // mock onreadystatechange
	        var _onreadystatechange = XMLReq.onreadystatechange || function () {};
	        XMLReq.onreadystatechange = function () {

	          var item = that.reqList[id] || {};

	          // update status
	          item.readyState = XMLReq.readyState;
	          // console.log(XMLReq.readyState)
	          item.status = XMLReq.status;
	          item.responseType = XMLReq.responseType;

	          if (XMLReq.readyState == 0) {
	            // UNSENT
	            item.startTime = +new Date();
	          } else if (XMLReq.readyState == 1) {
	            // OPENED
	            item.startTime = +new Date();
	          } else if (XMLReq.readyState == 2) {
	            // HEADERS_RECEIVED
	            item.header = {};
	            var header = XMLReq.getAllResponseHeaders() || '',
	                headerArr = header.split("\n");
	            // extract plain text to key-value format
	            for (var i = 0; i < headerArr.length; i++) {
	              var line = headerArr[i];
	              if (!line) {
	                continue;
	              }
	              var arr = line.split(': ');
	              var key = arr[0],
	                  value = arr.slice(1).join(': ');
	              item.header[key] = value;
	            }
	          } else if (XMLReq.readyState == 3) {
	            // LOADING
	          } else if (XMLReq.readyState == 4) {
	            // DONE
	            item.endTime = +new Date(), item.costTime = item.endTime - (item.startTime || item.endTime);
	            item.response = XMLReq.response;
	          }
	          // console.log('XMLReq._noVConsole', XMLReq._noVConsole)
	          if (!XMLReq._noVConsole) {
	            // that.updateRequest(id, item);
	          }
	          return _onreadystatechange.apply(XMLReq);
	        };

	        return _open.apply(XMLReq, args);
	      };

	      // mock send()
	      window.XMLHttpRequest.prototype.send = function () {
	        var XMLReq = this;
	        var args = [].slice.call(arguments),
	            data = args[0];

	        var item = that.reqList[XMLReq._requestID] || {};
	        item.method = XMLReq._method.toUpperCase();

	        var query = XMLReq._url.split('?'); // a.php?b=c&d=?e => ['a.php', 'b=c&d=', '?e']
	        item.url = query.shift(); // => ['b=c&d=', '?e']
	        if (query.length > 0) {
	          item.getData = {};
	          query = query.join('?'); // => 'b=c&d=?e'
	          query = query.split('&'); // => ['b=c', 'd=?e']
	          var _iteratorNormalCompletion = true;
	          var _didIteratorError = false;
	          var _iteratorError = undefined;

	          try {
	            for (var _iterator = query[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
	              var q = _step.value;

	              q = q.split('=');
	              item.getData[q[0]] = q[1];
	            }
	          } catch (err) {
	            _didIteratorError = true;
	            _iteratorError = err;
	          } finally {
	            try {
	              if (!_iteratorNormalCompletion && _iterator.return) {
	                _iterator.return();
	              }
	            } finally {
	              if (_didIteratorError) {
	                throw _iteratorError;
	              }
	            }
	          }
	        }

	        if (item.method == 'POST') {
	          // save POST data
	          if (tool.isString(data)) {
	            var arr = data.split('&');
	            item.postData = {};
	            var _iteratorNormalCompletion2 = true;
	            var _didIteratorError2 = false;
	            var _iteratorError2 = undefined;

	            try {
	              for (var _iterator2 = arr[Symbol.iterator](), _step2; !(_iteratorNormalCompletion2 = (_step2 = _iterator2.next()).done); _iteratorNormalCompletion2 = true) {
	                var _q = _step2.value;

	                _q = _q.split('=');
	                item.postData[_q[0]] = _q[1];
	              }
	            } catch (err) {
	              _didIteratorError2 = true;
	              _iteratorError2 = err;
	            } finally {
	              try {
	                if (!_iteratorNormalCompletion2 && _iterator2.return) {
	                  _iterator2.return();
	                }
	              } finally {
	                if (_didIteratorError2) {
	                  throw _iteratorError2;
	                }
	              }
	            }
	          } else if (tool.isPlainObject(data)) {
	            item.postData = data;
	          }
	        }

	        if (!XMLReq._noVConsole) {
	          that.updateRequest(XMLReq._requestID, item);
	        }

	        return _send.apply(XMLReq, args);
	      };
`

**Comment by nickuraltsev** [comment]
Closing this as it's not an axios issue.
