### ISSUE TITLE
Break a single request into chunks

### ISSUE THREAD

**Issue by ptums** [axios/axios#1072]
Hello,

I am looking for some guidance. I am making a rather large get request using ``` axios.get ``` and am looking to speed up the response time by breaking up the request into asynchronous chunks. Do you guys have a compatible package that works with axios to execute this or do you have a preferred method on how to get this done.

Any advice would be greatly appreciated.

Thank you,

Peter

**Comment by mikezahno** [comment]
+1

**Comment by jormar** [comment]
+1

**Comment by Marcholio** [comment]
This can maybe be closed since it hasn't been active lately.

**Comment by AllainPL** [comment]
@emilyemorehouse close please :)?

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. Thanks.
