### ISSUE TITLE
should delete pass data

### ISSUE THREAD

**Issue by damonmannion** [axios/axios#1073]
Writing against a rails backend which requires the CRSF token passed, however delete doesn't pass in. So, should this:
```javascript
utils.forEach(['post', 'put', 'patch'], function forEachMethodWithData(method) {
 ```
be this?
```javascript
utils.forEach(['delete', 'post', 'put', 'patch'], function forEachMethodWithData(method) {
 ```
and the corresponding change made a few lines above?

**Comment by robaxelsen** [comment]
Hi @damonmannion. Thanks for posting your question. Did you find an answer to this?
