### ISSUE TITLE
utils.merge not considering/handling the prototype chain

### ISSUE THREAD

**Issue by rupesh1** [axios/axios#1077]
#### Summary
Trying to use Axios on Node with your own http(s)Agent set via the global default triggers the error: `TypeError: self.agent.addRequest is not a function`

For minimal example see: https://runkit.com/rupesh/59b1bcc1efc2f800128b7d54

It seems to be related to utils.merge not considering/handling the prototype chain:
<img width="814" alt="developer_tools_-_node_js" src="https://user-images.githubusercontent.com/3313870/30188235-58af3bd8-9425-11e7-9f99-4bc01ff4bf96.png">

Stack trace:
```
TypeError: self.agent.addRequest is not a function
at new ClientRequest in core _http_client.js — line 160
at http.Agent in core http.js — line 31
at RedirectableRequest._performRequest in follow-redirects/index.js — line 73
at Writable.RedirectableRequest in follow-redirects/index.js — line 57
at wrappedProtocol.request in follow-redirects/index.js — line 229
at dispatchHttpRequest in axios/lib/adapters/http.js — line 131
at httpAdapter in axios/lib/adapters/http.js — line 18
```

#### Context

- axios version: 0.16.2
- Environment: node v4, 6, 7 and 8

**Comment by rupesh1** [comment]
In hindsight this maybe another manifestation of: https://github.com/mzabriskie/axios/issues/812

**Comment by KamiKillertO** [comment]
🤔 it's seems that `utils.merge` erase the httpAgent `prototype`.

**Comment by david4City** [comment]
Anything on this subject ?

**Comment by KamiKillertO** [comment]
There's a pending PR (#1295) that should fix this issue.

**Comment by cybercussion** [comment]
I got this error on a self-signed cert.  Initially I attempted to use `httpsAgent:   { rejectUnauthorized: false }` but then opted to use `httpsAgent:   new https.Agent({ rejectUnauthorized: false })` and the error went away.  Case someone else has that issue.
