### ISSUE TITLE
same http request, works with request module, but do not work in axios

### ISSUE THREAD

**Issue by Gcaufy** [axios/axios#1079]
#### Summary

I wrote a request using `request` module, and it works well.
after I changed it to use `axios`, it doesn't work.
```
request.post(option)
```
changed to 
```
axios.post(option.url, option.form, {headers: option.headers})
```

I checked the source code, request is using `http` module, and axios is using `follow-redirects`
and I tried to add `NODE_DEBUG=request`, it also works for `request`, output nothing for `axios`.

so there must be something different in the http level, but how can I debug the differences between the `request` and `axios`. what I am missing?

#### Context

- axios version: *v0.16.2*
- Environment: *v8.1.4*

**Comment by robaxelsen** [comment]
Hi @Gcaufy, thanks for submitting your question. Are you still having issues with this?

I would suggest an inverse approach where you instead implement the request from scratch with axios, and see if the issue becomes more apparent that way.

**Comment by Gcaufy** [comment]
Sorry, it's a long time, so I should close the issue, will reopen it if I have the issue again.
