### ISSUE TITLE
got error when connecting to server.js running on my machine , i am using axios to connect with server

### ISSUE THREAD

**Issue by Mohammad-Khalid23** [axios/axios#1081]
localhost/:1 Failed to load http://localhost:8000/user: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
bundle.js:45936 Error: Network Error
    at createError (bundle.js:2195)
    at XMLHttpRequest.handleError (bundle.js:1724)

**Comment by sam3k** [comment]
This doesn't seem to be an issue with Axios. You just need to allow localhost:8000 on the server localhost:3000. If you server is Node.js, you would do something like this before you create the server:

```javascript
app.use(function (req, res, next) {
  // Website you wish to allow to connect
  res.setHeader('Access-Control-Allow-Origin', 'https://localhost:4000');

  // Request methods you wish to allow
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');

  // Request headers you wish to allow
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

  // Set to true if you need the website to include cookies in the requests sent
  // to the API (e.g. in case you use sessions)
  res.setHeader('Access-Control-Allow-Credentials', true);

  // Pass to next layer of middleware
  next();
});
```
