### ISSUE TITLE
send POST request return error:Network Error work on IE9-

### ISSUE THREAD

**Issue by lecykx** [axios/axios#1082]
send POST request return error:Network Error work on IE9-;
work on other bower is successed.

code:
return axios({
        url: 'park-auth-service/auth/oauth/token',
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        data: qs.stringify(data)
    });//aixos 0.16.2

**Comment by kobezone** [comment]
sample question

**Comment by hengkx** [comment]
How to resolve?

**Comment by hengkx** [comment]
@nickuraltsev Can you help me?

**Comment by djlxiaoshi** [comment]
i met the same problem

**Comment by landlan** [comment]
same problem, how to resolve?

**Comment by chinesedfan** [comment]
Closed due to lack of enough information. If someone met the similar problem, please open a new issue with the required template and http request/response headers. Thanks.
