### ISSUE TITLE
DELETE strips off content-type header

### ISSUE THREAD

**Issue by tomkis** [axios/axios#1083]
#### Summary

When sending `DELETE` requests, `Content-Type` header is not present even though manually set.

I think it has something to do with two things:

1) https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L121-L123
2) https://github.com/mzabriskie/axios/issues/897 

#### Context

- axios version: *e.g.: v0.15.3*
- Environment: *e.g.: node v7.6.4, chrome 60.0.3112.113, Mac 10.12*

**Comment by ChadTaljaardt** [comment]
Im getting this issue too.

**Comment by stevenhurth** [comment]
Same here.

**Comment by raygesualdo** [comment]
What is the use-case for needing a `Content-Type` header on a `DELETE` request?

**Comment by Ruplahlava** [comment]
Any update here? I have the same issue. 
The rest api i am contacting allows two types of content type and i need to set it.

**Comment by Khaledgarbaya** [comment]
Hey @tomkis can you isolate the problem in a small snippet of code?

**Comment by Ruplahlava** [comment]
If request is send like this, Content-Type header is missing in sent headers.
```
        const params = {a:b}
        const headers = {
            'Content-Type': 'text/plain',
        };
        axios.delete(address, { params, headers })
...
```

Workaround (bypasses if clause here: https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L121-L123):
```
        const params = {a:b}
        const headers = {
            'Content-Type': 'text/plain',
        };
        axios.delete(address, { params, headers, data: params })
```

**Comment by Basaltq** [comment]
Okay I encountered this bug also. It seems like if you are sending json content with axios.delete(), it will strip the content away. You can bypass it also with using:
```
axios({
	method: 'delete',
	url: '/whatever',
	data: content
});

**Comment by johannesnagl** [comment]
Same here! I'm calling a JSONAPI.org conform API and I need to set the content-type of a delete call to `application/vnd.api+json`. This code is not working:

```
axios.defaults.headers.common['Accept'] = 'application/vnd.api+json';
axios.defaults.headers.common['Content-Type'] = 'application/vnd.api+json';

axios
  .delete(`/api/posts/${id}`, {
    withCredentials: true,
  })
  .then(response => {
    // do something here
  });
```

When passing `data: null`, or `data: {}`, it basically works that the `content-type` is set correctly, but then the API is returning another error (no payload allowed for DELETE request).

**Comment by einarjohnson** [comment]
any news on this? having a very similar problem when calling resify endpoints. it expects the content-type to be set to application/json when calling DELETE

**Comment by dlandis** [comment]
@Khaledgarbaya Do you need any more info on this? I noticed it was still tagged as `more-information-needed` ?

**Comment by mbain** [comment]
Also experiencing an issue with this.

**Comment by whiteb38** [comment]
was having this issue also, this works for me:
`.delete(url, {
            headers: {
                "Content-Type": "application/json"
            },
            data: JSON.stringify(data)
        })`

**Comment by spanner28** [comment]
Thanks, worked for me as well @whiteb38 

```javascript
.delete(url, { 
    headers: { "Content-Type": "application/json" }, 
    data: JSON.stringify(data)
})
```

**Comment by Once2012** [comment]
> was having this issue also, this works for me:
> `.delete(url, { headers: { "Content-Type": "application/json" }, data: JSON.stringify(data) })`

I dont know the different between the two way，but the second way is work（ref yours）
export function taskDeleteBatchSubmit(ids) {
  // return Axios({
  //   url: 'http://localhost:8080/tasks',
  //   method: 'delete',
  //   config: {
  //     headers: { 'Content-Type': 'application/json' },
  //     data: JSON.stringify(ids)
  //   }
  // })
  return Axios.delete('http://localhost:8080/tasks', {
    headers: { 'Content-Type': 'application/json' },
    data: JSON.stringify(ids)
  })
}

**Comment by thomaxxl** [comment]
This is really annoying: when data is sent in the HTTP body, axios does set the `Content-Type` header. If no data is sent, axios refuses to set the `Content-Type` header. 

(The logic here is probably that an empty body means there is no content hence no content-type needs to be provided)

**Comment by hexwit** [comment]
Not sure why this issue is closed.
If header is set it should be sent, no?

**Comment by RainOrigami** [comment]
hey, it's been like 7 years and this issue still persists for no reason whatsoever.

the use case is that there are API endpoints that require delete with a specific content type but no data, like mod.io unsubscribe.

isn't this an easy thing to fix?
