### ISSUE TITLE
Time for 1.0?

### ISSUE THREAD

**Issue by Download** [axios/axios#1084]
1.827.904 downloads in the last month can't be wrong right?

**Comment by moos** [comment]
Yes - please commit to 1.0.  When evaluating this for a large project, "0.x" has the wrong optics!

**Comment by natalieytan** [comment]
Fast-forward: to 2019
Axios currently has 4,505,027 weekly downloads
(vs. Isomorphic-fetch has 3,685,685 weekly downloads)

[Semver docs](https://semver.org/#spec-item-4): 
Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Though it is noted on axios readme page:
```
Semver
Until axios reaches a 1.0 release, breaking changes will be released with a new minor version. For example 0.5.1, and 0.5.4 will have the same AP
```

What would constitute a 1.0 release?

**Comment by schmod** [comment]
#2265 is a dupe of this ticket.  

We should cut a 1.0 release.  It's long overdue.

**Comment by yasuf** [comment]
closing duplicate of https://github.com/axios/axios/issues/2265 as per @schmod 's comment, we can discuss there or on the umbrella issue https://github.com/axios/axios/issues/1333
