### ISSUE TITLE
Broken interceptor error response

### ISSUE THREAD

**Issue by padsbanger** [axios/axios#1085]
Hello, I have upgraded `axios` from `0.12` to `0.16.2` and it looks like that interceptors response is quite diffrent:

Interceptor example code:

```
axios.interceptors.response.use(response => Promise.resolve(response), (error) => {
  console.log(error);
  return Promise.reject(error);
});
```
On version `0.12` it returns nice object:

![screenshot 2017-09-14 14 01 29](https://user-images.githubusercontent.com/471029/30429166-c2d7d782-9956-11e7-8094-7501b95176b3.png)

However on version `0.16.2` it seems to return error stack for the request:

 
![screenshot 2017-09-14 13 59 00](https://user-images.githubusercontent.com/471029/30429190-de9fa79c-9956-11e7-9235-275f4f3c040c.png)

Making interceptors in axios quite useless in my project (I am using it to refresh access token for logged user).

**Comment by orangemi** [comment]
Try `error.data` or `error.status` to get all data listed above.

It means the `error` rejected by promise is an `error object` not a `plain object`.

You can traversal this error object by using `Object.keys(error).forEach(key => ...)`

**Comment by fgblomqvist** [comment]
I have the same problem. Logging error.data or error.status just yields undefined as well. Tried both 0.16.2 and 0.17.0.

**Comment by fgblomqvist** [comment]
Had this error with 0.16.2 but just upgraded to 0.17.0 and now the error has the following keys: response, config, and request. So I think the update fixed it.

**Comment by m0ngr31** [comment]
Seems to be broken for me as well. Only keys are config and request. Can't get the status code.

**Comment by shay1989** [comment]
try to get error.response

**Comment by baixiaoji** [comment]
I use the 0.17.2 log the request and config but I want the response status code

**Comment by hoffin** [comment]
Using v0.17.1

Also the same here, error.response is undefined.

Object.keys(error).forEach(key => console.log(key)) returns
config, request, response

but error.response returns undefined.
So it's there but undefined.

**Comment by gankit** [comment]
I have the same issue

**Comment by rizqyhi** [comment]
I've got the same problem. Turns out it was CORS problem from my api server.

**Comment by m0ngr31** [comment]
I fixed the issue with mine. I was only sending back the response code and not any data with it (using Koa). Adding a response body made it work.

**Comment by gutomezencio** [comment]
Try error.config

**Comment by JakeWoki** [comment]
`0.18`
error.response returns undefined.
error.status returns undefined.

**Comment by Tyler-RCSD** [comment]
I have this issue as well.  If my API is unreachable then I would expect to get a error.response and error.status of 404 not found or something to that effect.  Instead error.response and error.status are not defined.  Seeing as the API is turned off I don't expect this to be an API issue.

**Comment by awsp** [comment]
+1 

At version 0.18
Similarly, I had a plain text for the `error` instead of an object. 
So both `error.response` or `error.status` are undefined. 

![image](https://user-images.githubusercontent.com/2015218/51649543-00db4100-1f29-11e9-96a4-b5cf689d75a0.png)

**Comment by chinesedfan** [comment]
Closed as this is an old issue. Though some users agreed that it was solved, and some did not.

If you found more information and confirmed it was still a problem, please feel free to open a new issue.

**Comment by EM-LilianaIturribarria** [comment]
This is still not resolved in lastest axios version.
