### ISSUE TITLE
Async await error message?

### ISSUE THREAD

**Issue by DarrylD** [axios/axios#1086]
When using `.catch()` I get a proper error message with `response`, `stack` and `message`

but when i'm using `async/await` wrapped in a `try/catch` I only get `config`

Example:
```javascript
 try {
  const { data } = await axios.get(forumUrl)
  resolve(data)
} catch (error) {
  console.log(error) //{config:{...}}
  reject(error)
}
```

Any idea why?

- axios version: *e.g.: latest*

**Comment by Axnyff** [comment]
Hello,
Are you using it in the browser or in node?
If I do this 

     try {
      const { data } = await axios.get('http://foo.bar/')
    } catch (error) {
      console.log(Object.keys(error), error.message); 
    }

I get ["config", "request", "response"] "Network Error" so it seems to work properly

**Comment by hanvyj** [comment]
Also facing this issue:

```
 try {
    const location = await axios.get(`https://api.postcodes.io/postcodes/${location}`);
    ...stuff
  } catch (err) {
    errorHandling.onError(err, response);
  }
```

Fails with:

> Error:  { Error: Request failed with status code 404
> [1]     at createError (D:\Projects\Chiron\node_modules\axios\lib\core\createError.js:16:15)

What confuses me is that this isn't caught by the try-catch. Node even says:

> (node:9680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:9680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

It's like the try catch doesn't exist...

**Comment by JustinBeckwith** [comment]
Greetings folks!  Can y'all please share a full code sample that includes the enclosing function?  This totally "works on my machine":

```js
const axios = require('axios');
const nock = require('nock');

nock.disableNetConnect();

const url = 'http://example';
nock(url).get('/').reply(500);

async function main() {
  try {
    const res = await axios.get(url);
    console.log('Success!');
    console.log(r.status);
    console.log(r.data);
  } catch (e) {
    console.error('Failure!');
    console.error(e.response.status);
  }
}

main().catch(console.error);
```

```
beckwith-macbookpro:ax beckwith$ npm start

> ax@1.0.0 start /Users/beckwith/Code/ax
> node server.js

Failure!
500
```

**Comment by vjsingh** [comment]
This happened to me, and I fixed it by catching the error in the enclosing function as @JustinBeckwith noted ("main().catch(console.error);")

**Comment by tedgoddard** [comment]
I have the same issue in my application, but the above test case works fine. Here's the stack trace:

```
(node:99470) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/tmp/server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/tmp/server/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/tmp/server/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

(This is on node 10.4)

**Comment by tedgoddard** [comment]
It seems possible to "cure" this by adding a `.catch()` to axios/lib/core/dispatchRequest.js:85. Perhaps this is the right approach, since the network events are asynchronous?

**Comment by cltsang** [comment]
Having the same problem here.
I'm using node 10.7.0, react-native 0.55.4
A failed request from await axios.request(config) triggers catch block, but error argument is undefined.
Reverting to .catch(error => onError(error)) works as documented.

**Comment by sashahilton00** [comment]
Also having this problem, is there any fix planned? Currently it doesn't seem to be possible to reliably use this library with async/await. A sample snippet that I'm seeing this behaviour on is below. The `console.log(error)` has also been changed to `console.log(JSON.stringify(error, null, 2))` to see what keys are present, with the following response:

```
{
  "config": {
    "transformRequest": {},
    "transformResponse": {},
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "baseURL": "https://example.com/api",
    "method": "get",
    "url": "https://example.com/api/customers"
  },
  "request": {}
}
```
it's as though axios isn't actually waiting for the request to execute, but rather returning the moment the request is fired?


The problematic snippet:
```
async function getCustomers() {
  try {
    return await axios.get('/customers')
  } catch(error) {
    console.log(error)
    //Error logic here
  }
}
```

**Comment by sashahilton00** [comment]
Ignore the above comment; being the smart cookie that I am, I failed to take into account the wonders of CORS when making requests in the dev environment, hence response was not being populated. Have just tested, this is now working fine. Thanks for the great library.

**Comment by skourismanolis** [comment]
It's been two years since this has been created, has it been fixed? I still have the same issue

**Comment by bertero** [comment]
I am having the same issue here. Two years? Seriously guys...

**Comment by sashahilton00** [comment]
@skourismanolis @bertero have you checkeed to make sure your request isn't being denied due to CORS? That was my problem, which was resulting in instant termination of the request with an empty body.

**Comment by manvirgrewal** [comment]
@sashahilton00 How would one adjust CORS to potentially fix this problem like you did?

**Comment by skourismanolis** [comment]
@sashahilton00 I can see the errors getting printed at the console but the catch segment contains only the error message. It's impossible to get the HTTP error code using async/await with try/catch in axios currently.

**Comment by Vlandmist** [comment]
try returning `error.response`, it worked for me

```
 try {
  const { data } = await axios.get(forumUrl)
  resolve(data)
} catch (error) {
  console.log(error.response) // <---- 
  reject(error)
}
```

**Comment by skourismanolis** [comment]
@Vlandmist thanks, that's exactly what I needed. I missed it because simply console.log-ing doesn't show the error object, it's just prints the error message and the stack trace.

**Comment by oluwashemoore** [comment]
I had this same issue and @Vlandmist's solution worked just fine. Thanks

**Comment by chinesedfan** [comment]
Closed due to stale and no one proves with a replicable code sample. If someone persist it is an issue of axios, feel free to open a new issue. Thanks.

**Comment by SuEric** [comment]
Having the same issue, posting an example while I was developing in my local environment.

I added both try-catch and promise.catch, try-catch doesn't but promise.catch does.

Any idea??

```
try {
      const { data: response } = originalAxios.post(`http://localhost:8000/v1/users/${userId}/activate/`, {
        token: '12231',
        password: formValues.password,
        password_confirm: formValues.password,
      }, headers).catch((error) => {
        debugger;
        console.log(error);
      });
    } catch(error) {
      debugger;
      if (error.message !== 'expired link') {
        dispatch(activateAccountFail({ error: 'Something went wrong' }));
      }
    }
  };
```

**Comment by adshin21** [comment]
@Vlandmist  it works like a charm, thank you.
