### ISSUE TITLE
Add XSRF In headers examples into Readme please

### ISSUE THREAD

**Issue by a-x-** [axios/axios#1087]
I tried to understand what axios does when I setup `xsrfHeaderName` 
by reading readme and looking in code.

Documentation describes xsrfCookieName but xsrfHeaderName.

**Comment by HeartUnchange** [comment]
![image](https://user-images.githubusercontent.com/8402502/30684342-66c03736-9ee3-11e7-8bf1-7caccf745d0f.png)

It will extract value named `xsrfCookieName`  from cookie and put it to next request header field, named `xsrfHeaderName`. Is that clear?

**Comment by a-x-** [comment]
Yep

Now I understand.
This note will be useful, I guess.
