### ISSUE TITLE
Which is the correct way to set custom headers on all requests?

### ISSUE THREAD

**Issue by olalonde** [axios/axios#1092]
```javascript
   const client = axios.create({
    headers: { 'Accept': 'text/html' },
  })
```

vs 

```javascript
  const client = axios.create({
    headers: { common: { 'Accept': 'text/html' } },
  })
```

**Comment by HeartUnchange** [comment]
It should be 
`const client = axios.create({
    headers: { 'Accept': 'text/html' },
  })`
refer [config](https://github.com/mzabriskie/axios#axioscreateconfig)

**Comment by davidyell** [comment]
Did this work for you? When I try and set custom headers they are not sent with my request.

**Comment by chinesedfan** [comment]
@olalonde For latest codes, the difference is the precedence.

```
  config.headers = utils.merge(
    config.headers.common || {},
    config.headers[config.method] || {},
    config.headers || {}
  );
```

@davidyell Setting custom headers has a bug until #2207.
