### ISSUE TITLE
If both httpAgent and httpsAgent are defined, axios fails to resolve mixed protocol redirections

### ISSUE THREAD

**Issue by pmarrone** [axios/axios#1094]
When a request is made using http and allowing redirects, if the redirect points to a url with a different protocol (https) AND both custom httpAgent and httpsAgent are defined in axios configuration, follow-redirects will be called in subsequent redirections using the agent corresponding to the protocol of the first request (say httpAgent), even if subsequent requests use a different protocol (https).

follow-redirects detects that there is a mismatch between the protocol the agent can handle, and the protocol requested in the redirection and fails.

This seems to be happenning only when both custom httpAgent and httpsAgent are defined, since when they are not, follow-redirects will choose a suitable default agent for each protocol.

**Comment by pmarrone** [comment]
Seems like this has been solved here https://github.com/axios/axios/pull/959

**Comment by pmarrone** [comment]
#959 seems to be a slightly different case.

**Comment by pmarrone** [comment]
I rebased the PR (https://github.com/axios/axios/pull/1095) fixing this issue to account for the changes in master.

**Comment by jasonsaayman** [comment]
Hi,

Please see #1095 

Please open a new issue or pull request if this issue comes up again.

Thanks
