### ISSUE TITLE
Leaking Document about how to use instance methods

### ISSUE THREAD

**Issue by C0deZLee** [axios/axios#1096]
I would suggest add code snippets to show how axios.create work and how to use it, to prevent new users search around for hours and still don't know how to use it.

**Comment by robaxelsen** [comment]
Hi @C0deZLee, thanks for posting an issue with your suggestion. I checked the documentation, and the [README.md already had a section](https://github.com/axios/axios#creating-an-instance) about this at the time of you posting this issue.

If you find that lacking, could you please come with some concrete suggestions on what type of information you are looking for in the documentation?

-----

@mzabriskie @nickuraltsev @rubennorte I propose to close this issue on 16.01.2018 (7 days) if no response from OP.
