### ISSUE TITLE
XMLHttpRequest withCredentials defaults to "true" in ReactNative

### ISSUE THREAD

**Issue by soulwu** [axios/axios#1101]
https://github.com/mzabriskie/axios/blob/07a7b7c84c3ea82ea3f624330be9e0d3f738ac70/lib/adapters/xhr.js#L132-L134
Only set withCredentials value for config.withCredentials is true

For ReactNative, XMLHttpRequest withCredentials defaults to "true"
https://github.com/facebook/react-native/commit/9b4a644fec94422c2976f11be0ccf66f2715d9bd

So, I can't set XMLHttpRequest withCredentials to false

**Comment by robaxelsen** [comment]
Hi @soulwu, thanks for submitting your issue. If you're still experiencing a need for this feature, please submit PR that handles this.
