### ISSUE TITLE
axios.get() with params object filterout null values

### ISSUE THREAD

**Issue by libbyf** [axios/axios#1104]
I try to send a get request:
const params = {
					profileId: profileId,
						portfolioId: null,
						portfolioName: portfolio.name
				};
				axios.get('api/selfservekpo/validate/portfolioname', {params})
					.then(...)
					.catch(...);

but I get error 400- bed request, because no portfolioId was sent (with null value):
This is what is sent at network: https://localhost/api/selfservekpo/validate/portfolioname?profileId=5013&portfolioName=3
and not: https://localhost/api/selfservekpo/validate/portfolioname?profileId=5013**&portfolioId=**&portfolioName=3

can you please help me?

**Comment by marten-cz** [comment]
@libbyf Did you solved it? I'm now having the same problem.

**Comment by libbyf** [comment]
@marten-cz no:(
It's bug of Axios, I saw that it is built into the code, they filter all elements that are equal to null.
Temporary - I wrote the code for get method:

getDataFetcher(method, path, data) {
		if  (method==="GET") {
			url = path+ getRequestParamData(data)
		}
		return axios[method](url, data);
	};

const getRequestParamData = (data) => {
	let params = '';
	if (data) {
		const keys = Object.keys(data);
		const firstData = `?${keys[0]}=${!isEmpty(data[keys[0]]) ? data[keys[0]] : ''}`;
		const otherKeys = keys.splice(1);
		params = otherKeys.reduce((prev, next) => prev + `&${next}=${!isEmpty(data[next]) ? data[next] : ''}`, firstData);
	}
	return params;
};

It does not work for complex objects - a parameter that is itself an object
for example -it dost not work for profile object:
const params = {
profile: {profileId:5, name:"profile"},
portfolioId: null,
portfolioName: portfolio.name
};

**Comment by fractalf** [comment]
+1
axios should not filter out `null`values by default

**Comment by ftbastler** [comment]
+1

**Comment by chinesedfan** [comment]
Closed in favor of #1139.
