### ISSUE TITLE
Cookies helper issue with Vue.js Async Components

### ISSUE THREAD

**Issue by rbown** [axios/axios#1105]
#### Summary

When using Vue.js Async Components (https://vuejs.org/v2/guide/components.html#Async-Components) that use an Axios GET request it returns an Error "TypeError: cookies.read is not a function".

It appears the cookies helper is not loaded correctly.

#### Possible Solution

Moving line 106;
```
var cookies = require('./../helpers/cookies');
```

Outside of the xhrAdapter function resolves the problem.
```
var utils = require('./../utils');
var settle = require('./../core/settle');
var cookies = require('./../helpers/cookies');
var buildURL = require('./../helpers/buildURL');
var parseHeaders = require('./../helpers/parseHeaders');
var isURLSameOrigin = require('./../helpers/isURLSameOrigin');
var createError = require('../core/createError');
var btoa = (typeof window !== 'undefined' && window.btoa && window.btoa.bind(window)) || require('./../helpers/btoa');
```

#### Context

- axios version: v0.16.2
- Environment: node v6.10.1, Vue.js 2.4.4, chrome 60, OSX 10.12.6

**Comment by robaxelsen** [comment]
Hi @rbown, thanks for reporting this issue. Instead of linking to change in your own fork, could you please submit this as a PR to this repo?
