### ISSUE TITLE
Is there better way to use default transformers with custom?

### ISSUE THREAD

**Issue by m1n0s** [axios/axios#1109]
Hi!
I hadn't find answer in already opened issues so I'm sorry if this question was rise before.

I want to use `transformRequest` while creating new own instance of `axios`. 
When I provide a function or array of functions --- everything working right but in this way I reject the default handler which is really good. In my case I need only change `headers`.

So currently it works in this way: 
```
import axiosLib  from 'axios';

export const axios = axiosLib.create({
    transformRequest: [axiosLib.defaults.transformRequest[0], (data, headers) => {
        
       // mutate headers logic

        return data;
    }],
  });
```

But I don't like to use it with this `axiosLib.defaults.transformRequest[0]`. I think this is not safe.

Maybe I'm using axios#create in wrong way? Or full overriding of `transformRequest` is expected behaviour?

Thanks in advance!

#### Context

- axios version:  v0.16.2*

**Comment by sharplet** [comment]
I'm using something like this in my code:

```js
transformRequest: [...axios.defaults.transformRequest, myCustomTransformer]
```

If you want it to be _really_ safe, there's also this (example in TypeScript):

```typescript
const defaultTransformers = (): AxiosTransformer[] => {
  const { transformRequest } = axios.defaults;
  if (!transformRequest) {
    return [];
  } else if (transformRequest instanceof Array) {
    return transformRequest;
  } else {
    return [transformRequest];
  }
};

// then use it like this
axios.create({
  // ...
  transformRequest: [...defaultTransformers(), myTransformer],
});
```

**Comment by m1n0s** [comment]
`transformRequest: [...axios.defaults.transformRequest, myCustomTransformer]` it's pretty match the same approach as mine :)

I just want to know that using `axios.defaults` is allowed by library author.

**Comment by IlyaSemenov** [comment]
@m1n0s no, it's not, as it's not type safe:

<img width="558" alt="screenshot 2018-10-23 at 14 59 35" src="https://user-images.githubusercontent.com/128121/47345178-4ee76b00-d6d4-11e8-9803-0c59994bbc0a.png">

Relying on the existence of the default transformer and its shape (an array) is unreliable. The type mismatch just makes it apparent.

**Comment by m1n0s** [comment]
@IlyaSemenov thanks for your answer.
Actually, I was looking for [interceptors](https://github.com/axios/axios#interceptors).
