### ISSUE TITLE
Interrupted chunked transfer is not correctly handled in ReactNative.

### ISSUE THREAD

**Issue by skaldo** [axios/axios#1113]
#### Summary

In the ReactNative, an interrupted response resolves the promise. The response.data contains the localizedDescription of the iOS error.

In our application, we're using the chunked transfer, which streams the headers first. In case, that such a request is interrupted any time after the 1st chunk is received, axios does not recognize that response as an error one. This happens, (not only) because the RN passes over a response with 200 status.

Fortunately, there's a simple fix, the request does contain a _hasError property, which is correctly set by the RN. I'll provide a fix in a PR.

Unfortunately, due to the nature and randomness of this issue, I can't provide a stack trace. But if anyone wants to debug this behavior, I'm providing a way to force this behavior.

The behavior can be forced by replacing the error.localizedDescription by some string on this line in RN: https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/Libraries/Network/RCTNetworking.mm#L523.

#### Context

- axios version: v0.16.2
- Environment: ReactNative 0.44.2

**Comment by MeesMaas** [comment]
Update?

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. Should you feel that this issue still exists please submit a new issues.

Thanks
