### ISSUE TITLE
Latest published npm version typings missing request property on AxiosError

### ISSUE THREAD

**Issue by rsimp** [axios/axios#1118]
#### Summary

#1014 Addresses a missing `request` property on `AxiosError`. While this issue was correctly resolved and merged it was never published. Please create a new npm version that includes these changes.

#### Context

- axios version: v0.16.2
- Environment: node v6.9.5, macOS 10.13 High Sierra

**Comment by nickuraltsev** [comment]
The fix was included in 0.17.0.
