### ISSUE TITLE
first request will be delay about 100ms when use Vue

### ISSUE THREAD

**Issue by maingao128** [axios/axios#1119]
#### performance will be influences

In most of projects, we want the request be sent as soon as possible, but when I execute axios.get api, you will invoke Promise.resolve(), and the MicroTask will be invoked when the thread is idle, so the real request will be sent when Vue template compile ready, so there will be 100ms delay

**Comment by Axnyff** [comment]
Hello,
couldn't you pre-compile your vue component with a single file component so you won't lose time for your ajax request?

Otherwise, using the right hook seems like it could help ( beforeCreate ?).

Anyway, do you have a way to reproduce your problem so we could have a look at it?

**Comment by chinesedfan** [comment]
Closed in favor of #2609.
