### ISSUE TITLE
onUploadProgress returns 100% immediately

### ISSUE THREAD

**Issue by decentname** [axios/axios#1127]
onUploadProgess returns 100% as soon as request is sent to server. I have set a timeout of 5 seconds on server . The promise is resolved after 5 seconds but the progressevent is thrown just once immediately as the request reaches server and that too 100% ?

**Comment by yoyo837** [comment]
I have the same problem.
progressEvent.loaded will immediately return the size of progressEvent.total.

**Comment by yoyo837** [comment]
#639 This may be related to the problem, but I am still confused.

**Comment by decentname** [comment]
@yoyo837 This issue is resolved from my end. Just follow their examples and pass parameters only in that manner.

**Comment by AaronKWS** [comment]
what?
