### ISSUE TITLE
Axios sending all request synchronously

### ISSUE THREAD

**Issue by mrkhanakia** [axios/axios#1133]
I have two ajax function and i want them to fire Asynchronously but axios is sending my request synchronously one by one But when i use Jquery Ajax instead of axios my both Ajax request fires at the same time Asynchronously.

So how do i make request Asynchronously at the same time using AXIOS

```js
AXIOS
axios.get('/session_entries', {
	params : {
		session_id: sessionId  				
	}
})

axios.get('/session_entries/session_plinfo', {
	params : {
		session_id: sessionId
	}
})


JQUERY
$.ajax({
	method: "GET",
	url: "/session_entries",
	dataType: "json",
	data: {
		session_id: sessionId  	
	}
});

$.ajax({
	method: "GET",
	url: "/session_entries/session_plinfo",
	dataType: "json",
	data: {
		session_id: sessionId  	
	}
});
```

**Comment by ChrisLahaye** [comment]
You can use axios.all, there is an example at https://github.com/axios/axios/blob/master/README.md

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like this one has been answered.  If you're still running into problems - let us know!

**Comment by jaischetu** [comment]
> Greetings! It looks like this one has been answered. If you're still running into problems - let us know!

This is fine if we have multiple request at a time but what if we don't know what will be next request.
