### ISSUE TITLE
Is there a way to secure credentials?

### ISSUE THREAD

**Issue by TKafassis** [axios/axios#1137]
Hello, I'm pretty new to this stuff and have currently made a SPA with Laravel backend, using axios to communicate with my API. I was thinking about using API authentication but then a question came to mind, can I hide my API credentials that axios has to send along from Developer Tools? Or do people use some other practice?

**Comment by clusteratlas** [comment]
Force HTTPS?
Use of Access Keys & Tokens?

**Comment by leopku** [comment]
two solutions:
1. Each client applicate different credential by himself. By this way, Sever side should add oauth 2.0 like feature.
2. A common credential shared with all clients. The credential could be secured or compressed.

**Comment by nickuraltsev** [comment]
Please use StackOverflow for general questions.
