### ISSUE TITLE
axios stopped working in android suddenly. Live Application

### ISSUE THREAD

**Issue by AkshayKomarla** [axios/axios#1138]
Axios gives network error in android. Works in IOS.

Usage:

axios.post('../manualauth/login', {
        email: this.state.email,
        password: this.state.password,
        remember: ""
      })
        .then(function (response) {
          console.log(response);
          this.validate_response(response);
        }.bind(this))
        .catch(function (error) {
          alert('connection error');
          console.log(error);
          console.log(error.response.data);
          if (error.response) {
          console.log(error.response.data);
          // console.log(error.response.status);
          // console.log(error.response.headers);
        }
        });

`Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)
    at XMLHttpRequest.dispatchEvent (event-target.js:172)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:546)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:381)
    at XMLHttpRequest.js:485
    at RCTDeviceEventEmitter.emit (EventEmitter.js:181)
    at MessageQueue.__callFunction (MessageQueue.js:250)
    at MessageQueue.js:101`

It was working all this time but suddenly its topped working.

**Comment by brianforkan** [comment]
I have seen this issue also. It does not happen on every version of Android

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
