### ISSUE TITLE
Support typed response data shape

### ISSUE THREAD

**Issue by psachs21** [axios/axios#1142]
It would be nice if you could provide the expected response shape for a given request:

Valid:
```ts
axios.get<{ name: string }>(url).then(x => x.data.name)
```

Invalid:
```ts
axios.get<{ name: string }>(url).then(x => x.data.someGarbage)
```

See PR: https://github.com/axios/axios/pull/1141

**Comment by corydeppen** [comment]
See #1061

**Comment by psachs21** [comment]
Ah, I missed that PR. Awesome! And it's merged!
