### ISSUE TITLE
error: window is undefined in web worker

### ISSUE THREAD

**Issue by darosh** [axios/axios#1145]
#### Summary

After upgrade from **0.16.2** to **0.17.0** I got error `window is undefined` when running in web worker at line:

https://github.com/axios/axios/blob/2c0e3183215d9a5fbc2ee8f35f459ac0e4d9f99c/lib/adapters/xhr.js#L27

Changing order of conditions `typeof window !== 'undefined'` and `!window.XMLHttpRequest` fixes the error.

#### Context

- axios version: **0.17.0**
- Environment: **web worker in Chrome**

#### Notes

looking closer ar xhr.js:

- `typeof window` checks could be probably replaced with `typeof XMLHttpRequest` and `typeof btoa` 
- There is `new XMLHttpRequest()` few lines prior `!window.XMLHttpRequest` check. I would expect, in case  `!window.XMLHttpRequest` is true, `new XMLHttpRequest()` will throw error before the check and the check is never performed

**Comment by darosh** [comment]
Duplicated: #1161,  Related: #1160

**Comment by nickuraltsev** [comment]
Fixed via #1160
