### ISSUE TITLE
Typings error: AxiosProxyConfig has no auth field

### ISSUE THREAD

**Issue by votuanphong1983** [axios/axios#1147]
In our typing file index.d.ts, AxiosProxyConfig has not auth field. So i received below error when using typescript

![image](https://user-images.githubusercontent.com/10540791/31925428-c87b5d5a-b8b2-11e7-9577-290a62420b5b.png)

**Comment by nickuraltsev** [comment]
I'd be happy to accept a PR that fixes this.

**Comment by nickuraltsev** [comment]
Fixed via #1177

**Comment by votuanphong1983** [comment]
+1
