### ISSUE TITLE
[Axios] Content-Length is missing on Request Headers

### ISSUE THREAD

**Issue by thiagosanches** [axios/axios#1149]
Hi guys, we are facing an issue in production that the 'Content-Length' header is not being sent, even if we hard-code it in the headers properties, so we are receiving back from the server the **411 Length Required** error.

We are using:
- Axios 0.16.2
- NodeJS 6.10
- **Application deployed inside AWS Lambda environment.**

The code that is causing the issue is the following:

```
let cookieJar;
const postBody = "MyBody=MyBodyContentGoesHere";
const url = "https://my-url.com";
return axios
		.post(url,
			postBody,
			{
				headers: {
					'Content-Type': 'application/x-www-form-urlencoded'
				},
				timeout: 10000,
				jar: cookieJar,
				withCredentials: true
			}
		);
```
Just to let you know, I wrote an application in .NET executing the same steps and it's working perfectly, the Content-Length are sent properly. This application was written just to test, it's not the real application.

I also got the following evidence using the **hookbin.com** tool. I just changed my original URL to one that hookbin generated to me so that I can track the request.

**NodeJS + axios (Content-Length is not sent):**
![image](https://user-images.githubusercontent.com/5191469/32002286-e528b5c4-b97a-11e7-8d03-7dfe7d439eaa.png)

**.NET (Content-Length is sent):**
![image](https://user-images.githubusercontent.com/5191469/32002301-efbdccd6-b97a-11e7-88c2-9a9bb7f2b4f9.png)

Thank you.

**Comment by sabakugaara** [comment]
Are you sure it is running on node.js?    I can't repeat it.  This is my test page: https://hooks.upyun.com/r1ZKpgyRb?inspect=true, all have `content-length`. 

by the way `withCredentials` option only work in browser side

**Comment by sabakugaara** [comment]
`content-length` will auto add by [http adapter](https://github.com/axios/axios/blob/master/lib/adapters/http.js#L45).

**Comment by sabakugaara** [comment]
I create this code snippet: `http://jsbin.com/cofumomezo/edit?html,js,output`, `content-length` work in browser side too.

**Comment by chinesedfan** [comment]
Closed due to no feedbacks.
