### ISSUE TITLE
Not able to escape backslash in json

### ISSUE THREAD

**Issue by boazjohn** [axios/axios#1150]
## Summary

I'm not able to pass backslashes in the payload when using axios. Other libraries are able to process this, either escaped version or sometimes the string itself. 

cURL:
```
curl -v -X POST localhost:9000 -d '{"date":"\/Date(1477384200000)\/"}' -H 'content-type:application/json'
```
Request received:
```
POST / HTTP/1.1
Host: localhost:9000
User-Agent: curl/7.43.0
Accept: */*
content-type:application/json
Content-Length: 39

{"date":"\/Date(1477384200000)\/"}
```
Trying the same with axios. The string here isn't escaped, using same as curl.
Axios POST:

```
axios.post('http://localhost:9000', { dateTime: '\/Date(1477384200000)\/'})
.then(function (response) {
console.log(response);
})
.catch(function (error) {
console.log(error);
});
```
The request object has the following structure:
Object:
```
method: 'post',
url: 'http://localhost:9000,
data: '{"dateTime":"/Date(1477384200000)/"}' },
```
Request as received:
```
POST / HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/x-www-form-urlencoded
User-Agent: axios/0.16.1
Content-Length: 36
Host: localhost:9000
Connection: close

{"dateTime":"/Date(1477384200000)/"}
```
Trying to post the same escaping the backslash.
Axios POST with Escaped backslash:
```
axios.post('http://localhost:9000', { "dateTime": "\\/Date(1477384200000)\\/"})
.then(function (response) {
console.log(response);
})
.catch(function (error) {
console.log(error);
});
```
Here the backslash seems to be again escaped.
Object:
```
method: 'post',
url: 'http://localhost:9000',
data: '{"dateTime":"\\\\/Date(1477384200000)\\\\/"}' }
```

Response received:
```
POST / HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=utf-8
User-Agent: axios/0.16.1
Content-Length: 40
Host: localhost:9000
Connection: close

{"dateTime":"\\/Date(1477384200000)\\/"}
```

To put it in simple terms, I'm not able to post a string like `\/Date(1477384200000)\/` using axios. I was able to do this using other libs and http.

## Context

- axios version: *0.16.1*
- Environment: *Node v6.11.1*

**Comment by voraparth91** [comment]
Seems Axios also takes the string as an argument. This worked for me:

axios.post('http://localhost:9000', "{ dateTime: '\\/Date(1477384200000)\\/'}" );
