### ISSUE TITLE
Error response (302) data unavailable in IE

### ISSUE THREAD

**Issue by michaeldzjap** [axios/axios#1153]
#### Summary

Sending a JSON response with status code 302 and some payload from the server (Laravel 5.5) results in `error.response.data` being `undefined` in error handler on IE only (Chrome, Firefox, Safari, Opera do not seem affected, payload data is available as you would expect). `error.response.request.response` and `error.response.request.responseText` are empty string as well. Seems like IE is notorious for having these kind of [issues](https://github.com/axios/axios/issues/201)

#### Context

- axios version: *v0.17.0*
- Environment: *php v7.0.22, edge 16, windows 10*

**Comment by liuzhen88** [comment]
I have same question

**Comment by audrium** [comment]
When this issue will be resolved? By the way, this happens for me also on FF

**Comment by rsaleri** [comment]
I can confirm the very same issue on Google Chrome 69

**Comment by leandrolimasi** [comment]
+1

**Comment by lyt9304** [comment]
+1 Same issue in Chrome 75

**Comment by sungbine** [comment]
plz resolve this..

**Comment by tgdn** [comment]
Any news on this?
