### ISSUE TITLE
Need a well proxy implementation

### ISSUE THREAD

**Issue by sneko** [axios/axios#1159]
Hi!

I had a lot of issues about using proxy with Axios... I'm just reporting this here because I have some indications to take in account.

There are some issues when requesting HTTPS endpoint over a HTTP proxy. And after some research it seems that this pull request  #959  fixes issues for some people, but just on axios.request(...) and not by axios.create(...).get(...).

I have succeeded in resolving this last issue but there is a strange case where it does not work : 
--> if you request an HTTP endpoint that redirects to an HTTPS endpoint, the proxy fails because SSL tunnel was not opened initially.

Since I'm just reaching an API this case is not present in my projects but it can be annoying for others. So I think contributors should take look deeper because when comparing with "request" lib, it's seems a bit more complex to solve.

If you want to use my fix, here is my fork:
https://github.com/Sneko/axios

Enjoy!

**Comment by zcei** [comment]
The `agent` option is intended to be set by yourself whenever it's applicable for it to be used. Bundling this up with Axios and having its usage deep buried in the adapter doesn't seem like a good solution.

Also your code disallows any `agent` to be set from the outside, as the one specified by the user is set [here](https://github.com/Sneko/axios/blob/05e4f0cfff9e96b5f82b8ee0f3c64d2db6474e4d/lib/adapters/http.js#L73-L84), but [gets overwritten afterwards](https://github.com/Sneko/axios/blob/05e4f0cfff9e96b5f82b8ee0f3c64d2db6474e4d/lib/adapters/http.js#L96).

**Comment by Sneko** [comment]
@zcei I totally agree that using agent property is not a good approach but I tried a lot of different ways and only this one was working for HTTP and HTTPS requests over HTTP proxy, while working with axios.create().get() usage and not only axios.request().

I hope someone will find the right way to do it  :)

**Comment by GoToBoy** [comment]
@Sneko thanks , your fixed is good
