### ISSUE TITLE
window is undefined error using axios in a WebWorker

### ISSUE THREAD

**Issue by owap** [axios/axios#1161]
I created https://github.com/axios/axios/pull/1160 when trying to troubleshoot the axios instance in my webworker.

~~I saw [this tweet](https://twitter.com/mzabriskie/status/648635939955195904) from 2015; is there anything special I need to do to be able to make HTTP requests in the web worker?~~

~~After patching locally with #1160, i'm getting 401s now, which we have overcome in the rest of our (non web-worker'd app) by setting the default axios headers:~~

Regardless, the window bug (addressed in #1160) still needs patching (on my machine) 👍 

Thanks!

Edit: Works great as long as #1160 is merged 👍

**Comment by nickuraltsev** [comment]
Fixed via #1160
