### ISSUE TITLE
How can i save the cookie？ for  the after requests.

### ISSUE THREAD

**Issue by shalldie** [axios/axios#1167]
Sorry for my English.

I've read the api, also searched for a long time.

environment: **Node 8.x**
axios version: **0.17.0**

I neet to get page A to save cookie, then can i post the page B with cookie.
Any object like **request.jar()** ?
How can i save and use the cookie .

**Comment by Naramsim** [comment]
`withCredentials: true`

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/32426836-14e8776e-c2f8-11e7-9cf1-2883ce0d1b93.png)

@Naramsim 
It seems to bring no change  =。=

**Comment by hwen** [comment]
@shalldie 
In the first place, `withCredentials` options is used in the browser env.

Axios use node built-in module `http` and `https` to realize the Request for node side, while it use xhr Object in the browser side.

 so you can set the cookie directly, 

```js
const headers = {
  'cookie': result.headers['set-cookie']
}
await instance.post('/cookie', {mes: 'test'}, headers)
```

By the way, do not forget to set cookie-parser middleware in your server side

```js
const cookieParser = require('cookie-parser')
....
app.use(cookieParser())
```

**Comment by shalldie** [comment]
@hwen 
Thx a lot.
豁然开朗

**Comment by shalldie** [comment]
@hwen 
还是有些问题。
如果只是简单的把字符串这样提取出来不处理，并不能正常识别 expires , path 等信息，也会把他当做cookie的键。

**Comment by hwen** [comment]
@shalldie 
这要看你怎么解析 cookie 串了吧，反正如何传给后台知道了，就看你要怎么解析而已。
或许你可以看看 cookie 这个包。

**Comment by nickuraltsev** [comment]
@shalldie Are you fine with closing it now?

**Comment by shalldie** [comment]
Thx.

**Comment by shangxinbo** [comment]
哈哈，国人人喜欢粘代码，学不会表述问题。另：你的场景推荐你用request，axios无能为力，我有一个爬虫项目和你遇到的问题是一样的，axios和superagent我都试过了，不好使，但是request轻松无压力

**Comment by shalldie** [comment]
@shangxinbo 
 嗯，一直都用的request，当时想前后端统一，所以尝试一下axios
