### ISSUE TITLE
Response does not contain data when it receives 404 response code

### ISSUE THREAD

**Issue by janober** [axios/axios#1168]
I was wondering if it is still possible to get the content of a page even if it returns an error code like 404. Right now I did add to the options the following:
```
validateStatus: function (status) {
  return status < 500;
}
```
it resolves fine but the "data" in the response is then still totally empty instead of containing the content of 
the page. Is there something I can do to "fix" this?

Example URL: https://www.bloomberg.com/news/articles/2015-04-22/xxxx

Thanks!

Context:
- axios version: * v0.16.0.2*
- Environment: node v6.9.5, Ubuntu 16.04

**Comment by chinesedfan** [comment]
@janober If you inspect the sample request in Chrome's network panel, you will see ERR_CONNECTION_RESET, instead of 404. That's means the browser failed to connect the server. So there is no response at all.
