### ISSUE TITLE
OPTIONS forbidden in GET request (MailChimp issue/question)

### ISSUE THREAD

**Issue by Stenvdb** [axios/axios#1169]
I'm trying to get the mailchimp subscribe to work with axios. It works with jQuery, and I understand this has to do with a CORS issue.

MailChimp requires you do a GET request and send data along with it. This [StackOverflow](https://stackoverflow.com/a/15120409/440201) post describes it well. The problem is that my request with axios always sends the OPTIONS prefllight request, and I think that it is being blocked by MailChimp. I have tried several solutions such as passing an empty data property, setting the header to 'application/x-www-form-urlencoded; charset=UTF-8' but nothing works. Any help is much appreciated!

My current code looks like this:
```
axios({
      method: 'get',
      url: form.getAttribute('action'),
      params: {
        EMAIL: form.querySelector('[name="EMAIL"]').value
      },
      data: {},
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
      }
    })
```

I don't quite understand how I could force to disable/skip the preflight request. I understand the current behaviour is correct and intended, but I must be able to fix this in order to work with MailChimp?

**Comment by nickuraltsev** [comment]
Looks like you want to use the `application/x-www-form-urlencoded` format, but use the JSON format instead. Please take a look at this: https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format

Hope it helps!
