### ISSUE TITLE
Axios catch a valid response 201 and treat it as an error 

### ISSUE THREAD

**Issue by bm2ilabs** [axios/axios#1178]
#### Summary

Hello , i am having this weird issue related to axios with laravel , when i submit a form using ajax the status code that i receive from laravel api is 201 or 200 but the axios only catch them as error 

```javascript
axios.post(this.url, formData)
                .then(
                    (response) => {
                        console.log(response.status); // return 201
                        const { data } = response
                        vm.$notify({
                            type: 'success',
                            duration: 10000,
                            speed: 1000,
                            title: $t('labels.' + data.message),
                            text: $t('messages.' + data.message)
                        });
                    }
                )
                .catch(e => {
                    vm.$notify({
                        type: 'error',
                        duration: 10000,
                        speed: 1000,
                        text: e.response
                    });

                    //vm.$emit('form-errors', e.response.data.errors);
                })

```
the return value from the api is 
```
{success: true, message: "created"}
```
with status code of 201 

#### Context

- axios version: *e.g.: v0.17.1*
- Environment: *e.g.: node v8.4.0, macOs, vue 2.5.2

**Comment by robodude** [comment]
What error is being passed to catch handler?

I haven't had this issue with axios so I suppose maybe something else is crashing (in your vm.$notify?)

**Comment by diemah77** [comment]
Same here. 201 status code is caught as error.

**Comment by bm2ilabs** [comment]
@robodude its catching an empty string , it doesn't show anything , it just go to catch instead . i really don't seem to find the issue that causing this bug so far

**Comment by AlexMordred** [comment]
I'm also having this problem

**Comment by travis-w** [comment]
Is that console.log triggering? The catch could be getting triggered because of an exception being thrown inside of then rather than axios failing

**Comment by robodude** [comment]
I don't know about laravel, but I just performed the following test and axios worked correctly:

https://jsfiddle.net/e2n7dzp5/

```
axios.post('https://jsonplaceholder.typicode.com/posts', { "foo": "bar" }).then(x => console.log(x)).catch(error => console.log('error: ' + error))
```

This endpoint returns a 201 and doesn't crash. I suspect there might be an issue with your `vm.$notify`

**Comment by joshuasiegal** [comment]
I also have issue of axios catching a 201 and treating it as an error response.

Note: could be related to something involving the following closed issue, which was closed although the original bug was not addressed.  Note that the original request asked about getting a 201 caught as an error when the Location header was present.

Then another user brought up a different (but related?) issue referencing being able to see the Location response b/c of CORS.

https://github.com/axios/axios/issues/758

In my case, I am making a CORS request, and I can see the Location header when I inspect the response.

Regardless, I don't see why axios being able to access the location header or not would make a difference.  For a 201 response with the default status code settings, this should be treated as a success response and not an error.

**Comment by amazzoccone** [comment]
Is this issue still open? I'm also having the same problem.

**Comment by bm2ilabs** [comment]
this issue happen when your response have an error , for example when the response is correct but in the then response you do something that throw an error , axios then catch that error , even if the response from the server was success, i hope i am making sense

**Comment by selfagency** [comment]
this is happening to me on a 200 response for no explicable reason

```
/* fetch data */
async function fetch (apiCall, type) {
  const response = await axios(encodeURI(apiCall), {
    maxRedirects: 0,
    validateStatus() { return true }
  })

  let out
  if (response.status === 200) {
    if (validJson(type, response.data)) {
      out = response.data
      out.status = 200
    } else {
      out = new Error(`API returned invalid JSON for ${apiCall}.`)
      out.status = 417
    }
  } else {
    out = errorHandler({ status: response.status })
  }

  log.info(`${type} out: ${out.status}`)
  return is.err(out) ? Promise.reject(out) : Promise.resolve(out)
}
```

here's the result, 200s all the way down but still 404s somehow
```
   [2018-03-16T17:24:01.049Z]  INFO: nylon/71301 on selfagency-macpro: API call: https://api.nylon.com/api/v2/article/lcd-soundsystem-and-the-absurd-politics
    [2018-03-16T17:24:04.274Z]  INFO: nylon/71301 on selfagency-macpro: article out: 200
    [2018-03-16T17:24:04.288Z]  INFO: nylon/71301 on selfagency-macpro: article cache out: 200 | bad? false | {"id":38888,"published":"2018-03-16T12:00:00-04:00","updated":"2018-03...
    [2018-03-16T17:24:04.291Z]  INFO: nylon/71301 on selfagency-macpro: API call: https://api.nylon.com/api/v2/author/tanner-howard
    [2018-03-16T17:24:04.292Z]  INFO: nylon/71301 on selfagency-macpro: API call: https://api.nylon.com/api/v2/post/38888/related
    [2018-03-16T17:24:04.476Z]  INFO: nylon/71301 on selfagency-macpro: related out: 200
    [2018-03-16T17:24:04.500Z]  INFO: nylon/71301 on selfagency-macpro: related cache out: 200 | bad? false | {"related":[{"id":38888,"published":"2018-03-16T12:00:00-04:00","updat...
    [2018-03-16T17:24:05.046Z]  INFO: nylon/71301 on selfagency-macpro: author out: 200
    [2018-03-16T17:24:05.049Z]  INFO: nylon/71301 on selfagency-macpro: author cache out: 200 | bad? false | {"type":"author-page","category":"author","author":{"url":"tanner-howa...
    raven@2.4.2 alert: failed to send exception to sentry: HTTP Error (413): undefined
    >> Error: Request failed with status code 404
    >>     at createError (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/core/createError.js:16:15)
    >>     at settle (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/core/settle.js:18:12)
    >>     at IncomingMessage.handleStreamEnd (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/adapters/http.js:201:11)
    >>     at emitNone (events.js:110:20)
    >>     at IncomingMessage.emit (events.js:207:7)
    >>     at endReadableNT (_stream_readable.js:1059:12)
    >>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
    >>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by leorossi** [comment]
Just happened to me. `catch` was fire after `then()` block, this happened because in my `then()` there was an error that threw an Exception.

**Comment by pezholio** [comment]
Having exactly the same problem here. My class is here:

    import axios from 'axios';
    import { UUID } from "../../src/app/utilities/uuid";

    export class ApiCreateCase {

      caseDetail: any
      token: string
      uuid: string
      domain: string
      headers: any

      constructor(caseDetail: any, token: string) {
        this.caseDetail = caseDetail
        this.token = token
        this.uuid = UUID.generateUUID()
        this.domain = 'http://my-domain.com'
        this.headers = {
          headers: {
            'Authorization': this.token,
            'Accept': 'application/json'
          }
        }
      }

      public async run(): Promise<any> {
        return this.createCase()
          .then((response) => {
            return this.addFamilyMembers()
          })
          .then((response) => {
            return this.assignTeamMember()
          })
          .then((response) => {
            return this.uuid;
          })
      }

      private async createCase(): Promise<any> {
        var body = {
          "case":{
            "people":[],
            "team":{
              "members":[]
            },
            "address": this.caseDetail.address,
            "visits":[],
            "summaries":[],
            "id": this.uuid,
            "caseName": this.caseDetail.people[0].lastName,
            "familyName": this.caseDetail.people[0].lastName
          }
        }
        return axios.post(`${this.domain}/cases`, body, this.headers)
      }

      private async addFamilyMembers(): Promise<any> {
        var people = []
        for (let person of this.caseDetail.people) {
          people.push(this.addFamilyMember(person))
        }
        return await axios.all(people);
      }

      private async addFamilyMember(person: any): Promise<any> {
        var body = {
          "person":{
            "dateOfBirth":"1901-01-01T00:00:00.000Z",
            "roles":[],
            "id": UUID.generateUUID(),
            "firstName": person.firstName,
            "lastName": person.lastName,
            "email": person.email,
            "relationship": person.relationship,
            "telephoneNumber": person.telephoneNumber
          }
        }
        return axios.put(`${this.domain}/cases/${this.uuid}/family-member`, body, this.headers)
      }

      private async assignTeamMember(): Promise<any> {
        return this.getUserList().then((response) => {
          var user = response.data.users.find((user) => {
            return user.displayName == 'Dev'
          })
          var body = {
            teamMember: {
              id: user.id
            }
          }
          return axios.put(`${this.domain}/cases/${this.uuid}/team-member`, body, this.headers)
        })
      }

      private async getUserList(): Promise<any> {
        return axios.get(`${this.domain}/users/directory?groups=Social%20Workers;Case%20Managers`, this.headers)
      }

    }

And I use it in a Cucumber step like so:

    Given('I am a family member', function (callback) {
      var world = this;
      world.case = {
        address: {
          streetAddress: address.streetAddress(),
          extendedAddress: '',
          locality: address.city(),
          postalCode: 'SW1A 1AA'
        },
        people: [
          {
            firstName: name.firstName(), 
            lastName: name.lastName(), 
            phoneNumber: phone.phoneNumber(), 
            relationship: 'Dad'
          }
        ]
      }

      mailslurp.createInbox()
        .then((response) => {
          world.emailId = response.id;
          world.case.emailAddress = response.email;
        })
        .then(() => { 
          return login.perform() 
        })
        .then(() => {
          return login.getToken();
        })
        .then((token) => {
          world.token = token;
          var createCase = new ApiCreateCase(world.case, token)
          return createCase.run()
        })
        .then(callback);
    });

And this is the error I get:

    1) Scenario: Listing cases - e2e/features/families/visit-note.feature:7
      Step: Given I am a family member - e2e/features/families/visit-note.feature:4
      Step Definition: node_modules/cucumber/lib/index.js:176
      Message:
        Error: a5489583-4162-4cc4-8923-f89ad2965051
            at Function.<anonymous> (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/cucumber/lib/user_code_runner.js:105:21)
            at Generator.throw (<anonymous>)
            at Generator.tryCatcher (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/util.js:16:23)
            at PromiseSpawn._promiseRejected (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/generators.js:107:10)
            at Promise._settlePromise (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/promise.js:576:26)
            at Promise._settlePromise0 (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/promise.js:614:10)
            at Promise._settlePromises (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/promise.js:689:18)
            at Async._drainQueue (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/async.js:133:16)
            at Async._drainQueues (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/async.js:143:10)
            at Immediate.Async.drainQueues [as _onImmediate] (/Users/stuart/Documents/FamilyStoryUI/fsIonic/node_modules/bluebird/js/release/async.js:17:14)
            at runCallback (timers.js:763:18)
            at tryOnImmediate (timers.js:734:5)
            at processImmediate (timers.js:716:5)

It's _really_ odd

**Comment by bradley-varol** [comment]
Why isn't this fixed? Laravel now returns a 201 after storing an entity.

**Comment by iDVB** [comment]
We're seeing this exact same issue with a simple post call but ONLY in our gatsby site.

**Comment by nicolanilomartinoph** [comment]
I solved mine by not chaining the request, then and catch.
Original code:
`axios.post( '/myPath', {myData : "test"}).then( "THEN BLOCK" ).catch( "CATCH BLOCK" )`

Solved code:
`const test = `axios.post( '/myPath', {myData : "test"})

test..then( "THEN BLOCK" ).catch( "CATCH BLOCK" )`
