### ISSUE TITLE
detect jest and use http adapter instead of XMLhttpRequest

### ISSUE THREAD

**Issue by capaj** [axios/axios#1180]
So I had a peculiar evening. We have an unconventional test suite in Jest. We run it in the regular mode, not with
`"testEnvironment": "node"`
so it has window.
In one test I was trying to fetch something with axios, but it always broke down and showed me a `Network error`.
I was banging my head against the table and had a nice debug session and eventually found out this thread: https://stackoverflow.com/questions/42677387/jest-returns-network-error-when-doing-an-authenticated-request-with-axios
Which was awesome. Using this spectacular hack:
```javascript
if (process.env.LOOOP_ENVIRONMENT === 'test') {
    const path = require('path') 
    const lib = path.join(
      path.dirname(require.resolve('axios')),
      'lib/adapters/http'
    )
    const http = require(lib)
    config.adapter = http
  }
```
I was able resolve the problem. What I want to suggest is-since jest is very popular test runner and a lot of people are running jest in regular mode, not in node they will often bang their heads.

Maybe it would be good to detect when we're running in jest and refrain from using `XMLHttpRequest`? Is that too much to ask?

**Comment by jeremy-moore** [comment]
It bit me too

**Comment by FagnerMartinsBrack** [comment]
Similar problem here. [The code](https://github.com/axios/axios/blob/9a6abd789f91a87d701116c0d86f1cfbc3295d66/lib/defaults.js#L16-L26) is like this:

```javascript
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

From what I can tell, Axios assumes if `XMLHttpRequest` exists then it's running in a browser environment. However, Jest run the tests in an environment where `XmlHttpRequest` is present, even if it's running in node.

My current hack is similar to the one above, but it's requiring the undocumented http adapter file path:

```javascript
axios.get(url, {
  headers: requestIntent.headers,
  adapter: require('axios/lib/adapters/http'),
})
```

I believe Axios should use the same algorithm when making HTTP requests inside the browser and when it's in node. Am I missing something?

**Comment by kmarkow** [comment]
I've had a fun afternoon too. I solved it by adding `testEnvironment: 'node',` to `jest.config.js` [file](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string). 

By default jest runs tests in `jsdom` mode which adds `XmlHttpRequest` to global scope which in turns causes axios to think it's running in a browser and making requests via `XmlHttpRequest` instead of node's native library.

**Comment by duhseekoh** [comment]
Thanks @kmarkow - that does it.

**Comment by dantman** [comment]
Attempting to set `testEnvironment` to `node` didn't work for me, I still get the error.

I guess I'm going to have to make due with a hack.

**Comment by agnelpraveen** [comment]
Make sure you are setting a testURL in your Jest config. The error is typically generated by jsdom when the URL is invalid.

Info from Jest --
testURL [string]
Default: about:blank
This option sets the URL for the jsdom environment. It is reflected in properties such as location.href.

**Comment by barraponto** [comment]
I'm new to Jest and I didn't know `jsdom` was the default environment.
I don't think this needs to be fixed in axios, but rather in jest documentation.
If you're not testing browser (or dom-enabled) code, you *have* to set `testEnvironment: node` in your jest configuration. You can achieve the same by calling jest with `--env node`.

**Comment by mpacary** [comment]
If you need to keep `jsdom` as `testEnvironment` (Vue components testing...), here is [another nice workaround](https://stackoverflow.com/a/43020260/488666):

Add `global.XMLHttpRequest = undefined` in your Jest setup file.

**Comment by jasonsaayman** [comment]
Hi,

Seems this can be mended by jest config changes. Closing for now, please open a new issue if this still persists.

Thanks

**Comment by chasen-bettinger** [comment]
If you need to set up a Jest file, [this documentation](https://create-react-app.dev/docs/running-tests/#initializing-test-environment) was helpful in getting me started with create-react-app.
