### ISSUE TITLE
Memory leak caused by CancelToken

### ISSUE THREAD

**Issue by STLighter** [axios/axios#1181]
#### Summary

 If the token does not cancel, the promise in token will reference to all instances of `XMLHttpRequest` even they are already resolved. So if using same cancel token to get data repeatedly, the token will keep all the request instances, which caused memory leak. 
The reference looks like: `source -> token -> promise -> OnCancel() context -> request`

If someone want to avoid this, he/she need set `source = null` after all the request returned, and may not use interval + single token ( the code below ).

Not sure how to fix it. Maybe should mention it in docs.

#### Steps

check in jsfiddle: [https://jsfiddle.net/ST_Lighter/Lnf8fgws/](https://jsfiddle.net/ST_Lighter/Lnf8fgws/)
1. click `run` button
2. check js heap in developer tools

#### Result

![1](https://user-images.githubusercontent.com/10627202/32831842-8f4de53c-ca34-11e7-84a1-8e113aa6a04f.png)
![2](https://user-images.githubusercontent.com/10627202/32831846-93243e36-ca34-11e7-80fe-c71aff67d891.png)

#### Context
- Environment: chrome

**Comment by STLighter** [comment]
How about try [abort-controller](https://github.com/mysticatea/abort-controller)?

**Comment by binki** [comment]
I think switching to some thing like abort-controller would be great. One issue with `CancelToken` is that its asynchronous notification mechanism uses a `Promise` and it is impossible to unsubscribe from a `Promise` once you have `.then()` it. Thus, there will be at least a memory leak of the callback function itself and its scope. This is an unavoidable problem with `CancelToken`, so users of `CancelToken`—not just users of axios—need to avoid keeping long-lived instances or use their long-lived instances for a very small, fixed number of calls. #1099 seems to be tracking abort controller support.

When I try to run your fiddle and look at it in Chrome developer tools, there are never more than a few `XMLHttpRequest`s sticking around. For example, I have 2 instances after letting it run long enough to have made 500 requests. If you look at the source, all of the possible ways which an XHR can complete will set `request = null`. This removes the XHR from the `CancelToken` promise callback’s scope. So I think that the XHR is being cleaned up correctly. Are you certain that the XHRs are actually uncollectible like you’re claiming?

**Comment by STLighter** [comment]
@binki Thanks a lot. I tried my fiddle again and it's fixed! It seems to be fixed at #1399 recently.
