### ISSUE TITLE
POST fails with Particle.io API, comparable cURL and Python work

### ISSUE THREAD

**Issue by xkortex** [axios/axios#1182]
I'm trying to hit the Particle.io API in order to [call a function](https://docs.particle.io/reference/api/#call-a-function). Generically, that looks like:

curl https://api.particle.io/v1/devices/0123456789abcdef01234567/my_function \
       -d arg="my argument" \
       -d access_token=1234....deadbeef

This works fine in curl:
`curl -X POST https://api.particle.io/v1/devices/$devID/get_temp?access_token=$tok
`
or 

```
curl -X POST https://api.particle.io/v1/devices/$devID/get_output \               
-d access_token=$tok
```

and in python:

```
import requests as rq
x = rq.post(url, data={'access_token':tok})
```

Both of these methods gives totally expected replies. Also, using axios in JS with the URL encoding totally works:
`axios.post("https://api.particle.io/v1/devices/3b....33/get_output?access_token=f0....1a")
`
These all give the Particle API output and everything is good:
`data:{id: "3b....33", last_app: "", connected: true, return_value: 123}
`

When I try 
`axios.post("https://api.particle.io/v1/devices/3b....33/set_output?access_token=f0...1a&arg=1")`

I get unexpected results (seems like it fails to parse the arg). No problem, that's what data is for, right? But when I try to implement using `.post()`, I get 400'd. 
```
let test_url = "https://api.particle.io/v1/devices/3b00...redacted...33/get_output";
let ACCESS_TOKEN = "f09d...redacted..1a"

let settings = {
      url: test_url,
      data: {
          access_token: ACCESS_TOKEN,
          arg: "1"
       },
      method: 'POST',
      headers : {
        "Content-Type" : "application/json"
      },
      transformRequest: [(data) => {
        return JSON.stringify(data);
      }]
  };

axios(settings)
  .then(function (res) {
      console.log(res);
  })
  .catch(function (error) {
    console.log(error);
  });

```

gives 

```
Error: Request failed with status code 400
    at createError (bundle.js:14700)
    at settle (bundle.js:23224)
    at XMLHttpRequest.handleLoad (bundle.js:14573)
```

Similarly, this fails:
```
let payload = {
    access_token: ACCESS_TOKEN,
};
axios.post(test_url, payload)
```

Headers look totally fine. Request payload looks like this:

`{access_token: "f09d...redacted..1a"}
`

I feel like I'm doing things totally by the docs here and cannot figure out why the data payload fails. 

I also tried wrapping it, `axios.post(test_url, JSON.parse(payload))` but that just yells at me. 

axios: "^0.16.2"
node v7.6.0
Chrome 60.0.3112.101 (Official Build) (64-bit)
Ubuntu 16.04
webpack: 3.5.5

**Comment by anderson916** [comment]
same problem here. @xkortex have you found a solution yet?

**Comment by incorvia** [comment]
I was able to get it working with the following format:

  ```
  callFunction(accessToken, deviceId, func, arg) {
    console.log(`Suvie: callFunction ${func}`)

    client = axios.create({
      baseURL: this.baseUrl,
      timeout: 5000,
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
    });

    return client.post(`/devices/${deviceId}/${func}?access_token=${accessToken}`, `arg=${arg}`)
    .then(function (response) {
      console.log(response)
      return JSON.parse(response.data)
    })
    .catch(function (error) {
      console.log(error)
      return null;
    })
  }

```

**Comment by chinesedfan** [comment]
Notice that `access_token` should be url parameter, instead of post data.
