### ISSUE TITLE
err string  "ѕејЂй‚ЈдёЄе¦№зєёпјЊи®©ж€‘жќҐ"

### ISSUE THREAD

**Issue by JXCP** [axios/axios#1184]
#### Summary
i test react-native 0.37 find request response 

{\"announcement\":[\"ж‰‹жњєиЅ®ж’­е…¬е‘Љжµ‹иЇ•\",\"ж”ѕејЂй‚ЈдёЄе¦№зєёпјЊи®©ж€‘жќҐ\",\"3022е№ґеЊ—дє¬е†¬еҐҐдјљењєй¦†е’ЊеџєзЎЂи®ѕж–Ѕе»єи®ѕе·Іе…ЁйќўејЂе·Ґ\",\"иЂЃйј з€±е¤§з±іпјЊзњџзљ„еЏЇд»Ґеђ—\"],\"announcements\":[{\"createTime\":\"2017-11-02 16:27:40\",\"content\":\"ж‰‹жњєиЅ®ж’­е…¬е‘Љжµ‹иЇ•\"},{\"createTime\":\"2017-10-24 16:06:04\",\"content\":\"ж”ѕејЂй‚ЈдёЄе¦№зєёпјЊи®©ж€‘жќҐ\"}

I set  headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
};

#### Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.:  ,IPHONE 6, Xcode 9 ,react-native 0.37

**Comment by Axnyff** [comment]
Hello, would you mind providing the full code and what it's supposed to do?

**Comment by Marcholio** [comment]
I suggest that this could be closed due to inactivity.
