### ISSUE TITLE
Getting 'Access-Control-Allow-Origin' on a GET request (axios.get)

### ISSUE THREAD

**Issue by liuqinqin** [axios/axios#1186]
My server added Access-Control-Allow-Origin header to options request.

still get the error.

And it's strange that axios actually received 200 & the data server returned. Don't know why I still get the error.

This is my code of axios:

     axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
     axios.defaults.withCredentials = true;
     axios.defaults.crossDomain = true;

    // For request
    axios.interceptors.request.use((config) => {
        if (config.method === 'post') {
           config.data = qs.stringify(config.data);
        }
             return config;
     }, () => {
          // Error
          ..........
       });
     });

    // For response
    axios.interceptors.response.use((response) => {
       if (response.data.code === 300) {
          window.location.href = getLoginUrl();
            return false;
         }
         return response.data;
      }, (error) => {
         return Promise.reject(error);
     });

The error is:
Failed to load http://xxxxx.com/api/index/getNotifyTop.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

Response Header:
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:X-Requested-With,Content-Type
Access-Control-Allow-Methods:PUT,GET,POST,OPTIONS
Access-Control-Allow-Origin:http://xxxxxxxx.com
Connection:keep-alive
Content-Length:522
Content-Type:application/json;charset=UTF-8
Date:Fri, 17 Nov 2017 03:56:32 GMT
P3P:CP=NOI ADM DEV PSAi COM NAV OUR OTR STP IND DEM
Server:openresty/1.11.2.1
Set-Cookie:JSESSIONID=142C0F0DA849F2C6332CA92539EBDC6B; Path=/; HttpOnly

Request Header：
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7
Cache-Control:no-cache
Connection:keep-alive
Cookie:xxxxxxxxxxxxxxxx
Host:xxxxxxxxx.com
Origin:http://localhost
Pragma:no-cache
Referer:http://localhost/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

 The first request is that axios actually received 200 & the data server returned, but The next request received 200 , but the the data is ""redirect:https://xxxxxx.com", How do I ...........

**Comment by matthewdordal** [comment]
I've seen the `access-control-allow-origin` issue a few times. Usually this happens to me when I am trying to call an API while I am working on http://localhost and that looks like the case here.

This [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) page has a lot of good information on the CORS and the access-control-allow-origin-header. My first guess looking at the headers is that the server set the access-control-allow-origin header to the `http://xxxxxxxx.com` example domain. But you are trying to hit it from `http://localhost` which is not the same domain.

**Comment by waratah** [comment]
CORS always issues two requests.  The first is NOT the post and it is the Cross Domain request.  This is probably the 200 you are seeing.   The second call is blocked if CORS is not allowed.

**Comment by liuqinqin** [comment]
First, I'm so sorry that I solved this problem many days ago
Next,The reason : Server-side interface to the request has been limited, so I use S w i t

**Comment by liuqinqin** [comment]
First, I'm so sorry that I solved this problem many days ago
Next,The reason : Server-side interface to the request has been limited, so I use SwitchHost to binding the IP, like:" 127.0.0.1  xxxxxxxx.com".

The solution @matthewdordal had been given, Thanks

**Comment by vigneshkvw** [comment]
can you tell me the solution!!

**Comment by waratah** [comment]
This is not an axios issue, it is a server security issue.    You can allow CORS on the server you are communicating with.

Issues you may have:   Running the api on localhost/api but the website is served from localhost:8080.  The port number is different.    Accessing www.xyz.com but calling api.xyz.com,   you are going to a different logical site.

Read up on your back end software how to allow CORS or request your back end provider to allow you to talk to their services.

**Comment by ChiaraSammarco** [comment]
In two words: If you are using expressJS like me.
For solving the problem: 'Access-Control-Allow-Origin' header on a get request just add: 

`app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
`
See here the solution: https://enable-cors.org/server_expressjs.html

**Comment by enisgur** [comment]
> In two words: If you are using expressJS like me.
> For solving the problem: 'Access-Control-Allow-Origin' header on a get request just add:
> 
> `app.use(function(req, res, next) { res.header("Access-Control-Allow-Origin", "*"); res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept"); next(); }); `
> See here the solution: https://enable-cors.org/server_expressjs.html

THANKS A LOT !!
