### ISSUE TITLE
config axios.get  data option,but the service side can't receive the request data?

### ISSUE THREAD

**Issue by secisland** [axios/axios#1189]
#### Summary

axios.get('/api/test',{ data: {"t":1}}).then((res) => {console.log(res);});

why the api server can't receive the request data?  

#### Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v6.9.4, chrome 54, windows 7*

**Comment by liuqinqin** [comment]
My first guess is the url, you can try use "/api/test?t=1&n=...&m=..."

**Comment by iansu** [comment]
I think @liuqinqin is correct and the `get` method does not take a `data` parameter: https://github.com/axios/axios#axiosgeturl-config

That being said, it maybe should take a `data` parameter and turn it into a query string.

**Comment by raygesualdo** [comment]
@secisland Currently, the request data is being included in the config as `data`. If it is instead included as `params`, it will work:

```javascript
axios.get('/api/test', { params: { t: 1 } })
  .then(res => console.log(res))
```

**Comment by secisland** [comment]
@iansu you are right ，thx to everybody!
