### ISSUE TITLE
Bad structure of data object when importing an XML document

### ISSUE THREAD

**Issue by nfigay** [axios/axios#1194]
# Summary
When getting an XML document produced with the Archi tool (https://www.archimatetool.com), in order to be able to parse and process it, the following problem occurs:

1. some of the documents elements are the following
```
    <element xsi:type="archimate:CompositionRelationship" id="b45b49c1-12f0-4d9f-a286-a01c5ef65c91" source="87d5746d-662d-400f-8aed-f757918e07d1" target="51d1599e-58b9-42f9-9d4c-0a595ee13b07"/>
    <element xsi:type="archimate:AssociationRelationship" id="4c292c1a-235f-4ff6-8e41-dccb09c3c03c" source="95a457d4-ac72-4a01-b4d1-80ce476f998a" target="16bbb643-b443-4e3d-8860-dab3277d5aa2"/>
```
2. When processing a DOM response.data.getElementbyId("b45b49c1-12f0-4d9f-a286-a01c5ef65c91"), what is returned is a node with two children, one is text, and the second is the sibling below the requested element
The used code is the following:
`axios({
        method:'get',
        url:'http://www.eads-iw.net/html/archi-axios/test.archimate',
        responseType:'document'
      })
    .then(function (response) {
      console.log(response);
      console.log(response.data.getElementById("a393738a-5e76-4ac5-b8f3-03a4456a5728"));
    })
    .catch(function (error) {
      console.log(error);
    }); `

3. This occurs in Chrome and Firefox (explored with the console of the developer tools), and the behavior seems to be the same in Safari. Here is an extract of what inspection of the data object shows with Firefox (the same with Chrome)
<img width="443" alt="capture d ecran 2017-11-21 a 08 48 42" src="https://user-images.githubusercontent.com/1943633/33060576-fda7d976-ce98-11e7-85ee-fd49add283e0.png">

This was discovered due to strange results when performing DOM and XPATH queries on the model.

# Context

Environments used: 
- axios version: v0.17.1
- firefox 41.0.1
- chrome Version 62.0.3202.94 (Build officiel) (64 bits)
The code is executed in browsers, in a function launched when loading an HTML page.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Testing Axios for AJAX</title>
    <meta name="description" content="Testing Axios for AJAX">
    <meta name="author" content="Dr Nicolas Figay">
  </head>
  <body  onload="loadArchi();">
    <div id="Title">
        <p>Testing AXIOS for reading Archi files</p>
    </div>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.js"></script>
    <script src="./js/axios-archi.js"></script>
  </body>
</html>
```
The axios-archi.js file contains the following:
function loadArchi()
```
{
    axios({
        method:'get',
        url:'http://www.eads-iw.net/html/archi-axios/test.archimate',
        responseType:'document'
      })
    .then(function (response) {
      console.log(response);
      console.log(response.data.getElementById("a393738a-5e76-4ac5-b8f3-03a4456a5728"));
    })
    .catch(function (error) {
      console.log(error);
    });   

}
```

**Comment by chinesedfan** [comment]
Sorry, I don't know what is expected. Closed first due to stale.
