### ISSUE TITLE
Request IE9

### ISSUE THREAD

**Issue by SrTristao** [axios/axios#1196]
Hello guys, how can I make request in IE9?, actually I make request with axios, but in IE 9 dont work =/, response returns with Network Error and using Fetch response returns with Access Denied.

React 16.0

With Axios

```js
async function makeRequest(endpoint, method = 'get', params = null, headers = {}) {
  const request = axios({
    method,
    url: BASE_URL + endpoint,
    data: params,
    headers
  });

  return await request;
}
```

with Fetch

```js
fetch(BASE_URL + endpoint, {
        method: 'POST',
        headers: headers,
        body: JSON.stringify(creds)
      }).then(data => {
        console.log(data);
      }, error => {
        console.log(error);
      })
```

**Comment by victorm95** [comment]
Hi, I think that is not a problem with Axios, maybe a CORS problem?
By the way, you can use instances to improve the request

**Comment by holic-cl** [comment]
I had same issue i configured the CORS in the server side and the error is gone.

I used this config to my axios client:
```
const apiClient = axios.create({
  baseURL: 'http://localhost:8000/',
  timeout: 1000,
   withCredentials: false
})
```

**Comment by corohsnk** [comment]
`Hi, I think that is not a problem with Axios, maybe a CORS problem?
By the way, you can use instances to improve the request`

Hello @victorm95, I think the problem is not in CORS, because axios working others browsers but expecific IE9 not work.

`I had same issue i configured the CORS in the server side and the error is gone.

I used this config to my axios client:

const apiClient = axios.create({
  baseURL: 'http://localhost:8000/',
  timeout: 1000,
   withCredentials: false
})`

Hello @holic-cl not work here =/

**Comment by victorm95** [comment]
Can you share more details?
The log, maybe a screenshot of the request

**Comment by HelloLeeChan** [comment]
I have the same issue

**Comment by HelloLeeChan** [comment]
Did you try do enable Access Data Source Cross Domains 

https://stackoverflow.com/questions/2044684/access-control-for-cross-site-requests-in-internet-explorer

**Comment by ronliruonan** [comment]
XDomainRequest is an implementation of HTTP access control (CORS) that worked in Internet Explorer 8 and 9. It was removed in Internet Explorer 10 in favor of using XMLHttpRequest with proper CORS; 

Axios0.18.0 is support IE9, and I've tried it.

https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest

**Comment by Alanscut** [comment]
See the **browser support** section of reademe.md，[Browser Support](https://github.com/axios/axios/blob/master/README.md#browser-support)。
