### ISSUE TITLE
Mixed content problem from https to http

### ISSUE THREAD

**Issue by fakultetgashi** [axios/axios#1197]
Hi, I am new to axios and I want to know how to do calls from https on http. My website is on https but my client API is on http and I know it is a bit weird. I am trying to do a call from my website and browser blocks the request, the error text is:

> Mixed Content: The page at 'https://me.xxxxxxx.eu/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxxxx.eu/authorize'. This request has been blocked; the content must be served over HTTPS.

Is there any option that I can use on axios to resolve this or not ?

Regards :)

**Comment by victorm95** [comment]
Hi, this is nothing to do with axios.
The browser blocks it because is an insecure request, you need use https in the web too or disable the https in the api but is not recommended.

**Comment by jakkrits** [comment]
@fakultetgashi Have you fixed it?

**Comment by Khaledgarbaya** [comment]
This has nothing to do wit axios, the browser is blocking your request for security reasons

**Comment by mahmed0715** [comment]
how to overcome this?

**Comment by hanbz** [comment]
Get the same problem.
In my code  I use the relative path like "/xxx/xxx/xxx.php"
And the page url is "https://xxx.xxx.xx/"
The axios send the request twice.
One time is the https and the other one is http.
