### ISSUE TITLE
how to find out request timeout reasons

### ISSUE THREAD

**Issue by zvrr** [axios/axios#1200]
we set default time out to 12s，but sometime the request could be timeout, but in the back-end nginx server the log shown alll the requests were ok, the internet were ok, so is there some tool or method could be find out the time resons, thanks. 
Error: timeout of 12000ms exceeded    @ createError

**Comment by chinesedfan** [comment]
It is not an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).
