### ISSUE TITLE
cross-domain in production

### ISSUE THREAD

**Issue by zhoocoo** [axios/axios#1201]
hello , when I use aioxs in vue-cli，I did't set the withCredentials false, the http request is cross-domain. it's my mistake ? but your document white like this,it's default?
// `withCredentials` indicates whether or not cross-site Access-Control requests
  // should be made using credentials
  withCredentials: false, // default

**Comment by Axnyff** [comment]
Hello, I have a hard time understanding what is your problem.
Would you be able to come up with a reproduction if you think it's a bug?

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Good luck!
