### ISSUE TITLE
Add log warning when Axios removes Content-Type header

### ISSUE THREAD

**Issue by magnusart** [axios/axios#1202]
When the header `Content-Type` is added to a get request Axios silently removes it. Please add a warning log message when doing this.

This is the code in place today:
https://github.com/axios/axios/blob/d7f021b8d4cc50bfa0653011bc02452d234d1255/lib/adapters/xhr.js#L121

I don't disagree in principle that one should not use the content-type header for GET requests. But I do think it is odd that Axios is baby sitting me. It is very unintuitive that the header silently is removed. I think that it is bad design and not keeping with the path of least surprise. 

However I've seen at least two previous issues mentioning this that got closed without any change in behaviour, so I'm not fighting that fight today, I just wish a warning message was printed to the console so there is at least a hint that the header was removed along the way. 

Spending 20min debugging and then another 15 min refactoring our backend service because I got `415 unsupported media type` error is not warranted. Especially since it is not illegal to add the header.

**Comment by magnusart** [comment]
So almost one year later I had forgotten about this insanity and ran into it again! This is such a time waster. This time it was for PUT instead and since the content is empty the header get stripped. If I have an error where the content is missing I instead get a _different error_ (unsupported media type) because Axios is now "helping" me by removing the content type. Please remove this feature!

**Comment by magnusart** [comment]
I looked through the blame history and it seems @mzabriskie might be the correct recipient. I'm obviously biased having stumbled upon this twice, but I'm trying to keep an open mind: Why is Axios removing the `Content-Type` header even if it has been explicitly set in the config?

**Comment by jasonsaayman** [comment]
I think this has been mended now, I am closing this issue for now, please open a new issue should this still be a problem.
