### ISSUE TITLE
SSL Pinning Support

### ISSUE THREAD

**Issue by bdipak** [axios/axios#1204]
Hi,
Do you have any plan to support SSL pinning ? Or if it is already supported, could you please point me to the documentation ?

**Comment by anonrig** [comment]
+1

**Comment by raygesualdo** [comment]
A few things:

1. It seems that SSL pinning can only be done by the browser itself on the web. I couldn't find a specific instance where libraries could make use of it.
1. It's being [deprecated pretty quickly](http://www.zdnet.com/article/google-chrome-is-backing-away-from-public-key-pinning-and-heres-why/), at least in Chrome.

Full disclosure: I'm no SSL/TLS expert.

**Comment by PaijoRX** [comment]
Hi, 

SSL pinning is a standart on our mobile app. If I want to use Axios, is it possible to implement SSL pinning?

Thanks

**Comment by gagan-bansal** [comment]
Yes I also want to use SSL pinning with Cordova.

**Comment by gauravds** [comment]
We are using axios inside our React-native apps, and We also want **Public key pinning.**

**Comment by andcosta** [comment]
+1

**Comment by isaaclem** [comment]
currently we are using https://github.com/localz/react-native-pinch but I am hoping axios supporting SSL Pinning too

**Comment by o2genum** [comment]
This should be possible in Node.js (and Electron main process is Node.js).

**Comment by jasonsaayman** [comment]
As mentioned here #1759 I don't think SSL pinning is something that should fall under Axios.
