### ISSUE TITLE
Axios requests with proxy fails to redirect properly

### ISSUE THREAD

**Issue by kidlj** [axios/axios#1207]
### Summary

Axios requests with proxy fails to redirect properly, as described below:

The request:

```
const axios = require('axios')

axios.get('http://testapi.testdomain.com/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10', {
  proxy: {
    host: '127.0.0.1',
    port: 1080
  }
})
.then((response) => {
  console.log(response)
})
.catch((err) => {
  console.log(err)
})
```

The response:

```
$ node axios_promise.js
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.17.1' },
     method: 'get',
     proxy: { host: '127.0.0.1', port: 1080 },
     url: 'http://testapi.testdomain.com/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { maxRedirects: 21,
        protocol: 'http:',
        hostname: '127.0.0.1',
        port: null,
        path: '/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
        method: 'GET',
        headers: [Object],
        agent: undefined,
        auth: null,
        host: '127.0.0.1',
        pathname: '/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc',
        search: '?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
        slashes: true,
        hash: null,
        query: 'page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
        href: 'http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut' },
     _redirectCount: 1,
     _bufferedWrites: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
     _isRedirect: true },
  response: undefined }
```

Please note the error part of response at the top:

```
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1022:11)
``` 

and the response part at the bottom:

```
     _currentUrl: 'http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
     _isRedirect: true },
```

What I got is `http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut`, 

and what I expect should be
`http://testapi.testdomain.com/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut`

### Context

- axios version:  *v0.17.1*
- Environment:  *node vv8.1.4, windows 10*

**Comment by jialixiang** [comment]
have the same issue as @kidlj, axios seems cannot redirect properly when using proxy

**Comment by Tidyzq** [comment]
same issue here, and here is a minified code to reproduce
```javascript
var axios = require('axios');
var http = require('http');
var url = require('url');

var str = 'test response', proxyStr = ' through proxy'

var server = http.createServer(function (req, res) {
  var parsed = url.parse(req.url);

  if (parsed.pathname === '/one') {
    res.setHeader('Location', '/two');
    res.statusCode = 302;
    res.end();
  } else {
    res.end(str);
  }
}).listen(4444, function () {

  var proxy = http.createServer(function (request, response) {
    var parsed = url.parse(request.url);
    var opts = {
      hostname: parsed.hostname,
      port: parsed.port,
      path: parsed.path
    };

    http.get(opts, function (res) {
      var body = '';
      res.on('data', function (data) {
        body += data;
      });
      res.on('end', function () {
        if (res.headers.location) {
          response.setHeader('Location', res.headers.location);
        }
        response.statusCode = res.statusCode;
        response.end(body + proxyStr);
      });
    });

  }).listen(4000, function () {

    axios.get('http://localhost:4444/one', {
      proxy: {
        host: 'localhost',
        port: 4000
      },
    }).then(function (res) {
      console.log(res.data); // should be "test response through proxy"
    });

  })
});
```

**Comment by Druux** [comment]
Any updates on this? Still experiencing the same error.

**Comment by LeoFC97** [comment]
Still getting this here

**Comment by ishansinghal9810** [comment]
Still waiting for the fix

**Comment by hammyofmha** [comment]
> ### Summary
> 
> 
> 
> Axios requests with proxy fails to redirect properly, as described below:
> 
> 
> 
> The request:
> 
> 
> 
> ```
> 
> const axios = require('axios')
> 
> 
> 
> axios.get('http://testapi.testdomain.com/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10', {
> 
>   proxy: {
> 
>     host: '127.0.0.1',
> 
>     port: 1080
> 
>   }
> 
> })
> 
> .then((response) => {
> 
>   console.log(response)
> 
> })
> 
> .catch((err) => {
> 
>   console.log(err)
> 
> })
> 
> ```
> 
> 
> 
> The response:
> 
> 
> 
> ```
> 
> $ node axios_promise.js
> 
> { Error: connect ECONNREFUSED 127.0.0.1:80
> 
>     at Object.exports._errnoException (util.js:1022:11)
> 
>     at exports._exceptionWithHostPort (util.js:1045:20)
> 
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
> 
>   code: 'ECONNREFUSED',
> 
>   errno: 'ECONNREFUSED',
> 
>   syscall: 'connect',
> 
>   address: '127.0.0.1',
> 
>   port: 80,
> 
>   config:
> 
>    { adapter: [Function: httpAdapter],
> 
>      transformRequest: { '0': [Function: transformRequest] },
> 
>      transformResponse: { '0': [Function: transformResponse] },
> 
>      timeout: 0,
> 
>      xsrfCookieName: 'XSRF-TOKEN',
> 
>      xsrfHeaderName: 'X-XSRF-TOKEN',
> 
>      maxContentLength: -1,
> 
>      validateStatus: [Function: validateStatus],
> 
>      headers:
> 
>       { Accept: 'application/json, text/plain, */*',
> 
>         'User-Agent': 'axios/0.17.1' },
> 
>      method: 'get',
> 
>      proxy: { host: '127.0.0.1', port: 1080 },
> 
>      url: 'http://testapi.testdomain.com/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10',
> 
>      data: undefined },
> 
>   request:
> 
>    Writable {
> 
>      _writableState:
> 
>       WritableState {
> 
>         objectMode: false,
> 
>         highWaterMark: 16384,
> 
>         finalCalled: false,
> 
>         needDrain: false,
> 
>         ending: false,
> 
>         ended: false,
> 
>         finished: false,
> 
>         destroyed: false,
> 
>         decodeStrings: true,
> 
>         defaultEncoding: 'utf8',
> 
>         length: 0,
> 
>         writing: false,
> 
>         corked: 0,
> 
>         sync: true,
> 
>         bufferProcessing: false,
> 
>         onwrite: [Function: bound onwrite],
> 
>         writecb: null,
> 
>         writelen: 0,
> 
>         bufferedRequest: null,
> 
>         lastBufferedRequest: null,
> 
>         pendingcb: 0,
> 
>         prefinished: false,
> 
>         errorEmitted: false,
> 
>         bufferedRequestCount: 0,
> 
>         corkedRequestsFree: [Object] },
> 
>      writable: true,
> 
>      domain: null,
> 
>      _events:
> 
>       { response: [Function: handleResponse],
> 
>         error: [Function: handleRequestError] },
> 
>      _eventsCount: 2,
> 
>      _maxListeners: undefined,
> 
>      _options:
> 
>       { maxRedirects: 21,
> 
>         protocol: 'http:',
> 
>         hostname: '127.0.0.1',
> 
>         port: null,
> 
>         path: '/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
> 
>         method: 'GET',
> 
>         headers: [Object],
> 
>         agent: undefined,
> 
>         auth: null,
> 
>         host: '127.0.0.1',
> 
>         pathname: '/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc',
> 
>         search: '?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
> 
>         slashes: true,
> 
>         hash: null,
> 
>         query: 'page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
> 
>         href: 'http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut' },
> 
>      _redirectCount: 1,
> 
>      _bufferedWrites: [],
> 
>      _onNativeResponse: [Function],
> 
>      _currentRequest:
> 
>       ClientRequest {
> 
>         domain: null,
> 
>         _events: [Object],
> 
>         _eventsCount: 5,
> 
>         _maxListeners: undefined,
> 
>         output: [],
> 
>         outputEncodings: [],
> 
>         outputCallbacks: [],
> 
>         outputSize: 0,
> 
>         writable: true,
> 
>         _last: true,
> 
>         upgrading: false,
> 
>         chunkedEncoding: false,
> 
>         shouldKeepAlive: false,
> 
>         useChunkedEncodingByDefault: false,
> 
>         sendDate: false,
> 
>         _removedConnection: false,
> 
>         _removedContLen: false,
> 
>         _removedTE: false,
> 
>         _contentLength: 0,
> 
>         _hasBody: true,
> 
>         _trailer: '',
> 
>         finished: true,
> 
>         _headerSent: true,
> 
>         socket: [Object],
> 
>         connection: [Object],
> 
>         _header: 'GET /api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n',
> 
>         _onPendingData: [Function: noopPendingOutput],
> 
>         agent: [Object],
> 
>         socketPath: undefined,
> 
>         timeout: undefined,
> 
>         method: 'GET',
> 
>         path: '/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
> 
>         _ended: false,
> 
>         res: null,
> 
>         aborted: undefined,
> 
>         timeoutCb: null,
> 
>         upgradeOrConnect: false,
> 
>         parser: null,
> 
>         maxHeadersCount: null,
> 
>         _redirectable: [Circular],
> 
>         [Symbol(outHeadersKey)]: [Object] },
> 
>      _currentUrl: 'http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
> 
>      _isRedirect: true },
> 
>   response: undefined }
> 
> ```
> 
> 
> 
> Please note the error part of response at the top:
> 
> 
> 
> ```
> 
> { Error: connect ECONNREFUSED 127.0.0.1:80
> 
>     at Object.exports._errnoException (util.js:1022:11)
> 
> ``` 
> 
> 
> 
> and the response part at the bottom:
> 
> 
> 
> ```
> 
>      _currentUrl: 'http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut',
> 
>      _isRedirect: true },
> 
> ```
> 
> 
> 
> What I got is `http://127.0.0.1/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut`, 
> 
> 
> 
> and what I expect should be
> 
> `http://testapi.testdomain.com/api/articles/personal/01d76a9844ae4a919f02ddedf11a6fcc?page=2&size=10&uc_param_str=dnvebichntwidsudsvpflameefut`
> 
> 
> 
> 
> 
> 
> 
> ### Context
> 
> 
> 
> - axios version:  *v0.17.1*
> 
> - Environment:  *node vv8.1.4, windows 10*
> 
> 

`_`

**Comment by jasonsaayman** [comment]
Can this please be tested with the latest version of master?

**Comment by mircoianese** [comment]
In my case the problem persists with the latest version of master. Same issue as OP.

**Comment by mircoianese** [comment]
After investigating the issue further I noticed that the protocol gets changed in redirection to https. My proxy is listening on an http port and that caused the issue. 

I've manually fixed it by adding `redirection.protocol = 'http:';` in the `beforeRedirect()` function (`http.js` source code file, right before the call to `setProxy()`).

<img width="523" alt="image" src="https://user-images.githubusercontent.com/22716366/129488984-3e7d253b-f2be-4104-9808-ea6031911abc.png">

Of course this is a temporary fix that works for me, but @jasonsaayman  maybe take a look into this :)
Thanks

**Comment by fraisai** [comment]
anyone find a fix for this?

**Comment by fraisai** [comment]
i found a fix that worked for me: https://stackoverflow.com/questions/48291950/proxy-not-working-for-react-and-node

simply had to delete my package-lock.json file and node_modules folder and reinstall npm packages. then when i restarted my app, requests with proxy was finally working properly

i use webpack so my proxy option for devServer looks like this:

`
devServer: {
   // ...other options
   proxy: {
       "/api/**" : {
            target: "http://localhost:5000/",  // port my server is running on
            parthRewrite: { "^/api": ""}    // if you do NOT rewrite the path then requests to /api will be passed on as localhost:5000/api
        }
   }
}
`

so all of my requests in my frontend get rerouted to localhost 5000 (port my server is running on) when I make requests in my front using the route "api" (ex: axios.get('/api/info') => rerouted to 'http://localhost:5000/info' )
