### ISSUE TITLE
Use webpack 3 for bundling

### ISSUE THREAD

**Issue by pravi** [axios/axios#1209]
#### Summary

We'd like to package axios for debian and use webpack version (3.5.6) shipped in debian for building but axios currently uses webpack 1.x

When using webpack 3, I get the following warning,

```
Running "webpack" task
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "dist/" is not an absolute path! Use --force to continue.
```

#### Context

- axios version: * v0.16.2*
- Environment: *: node v6.12.0, webpack 3.5.6*

axios is a dependency of gitlab 9.5 and we need this to update gitlab from 8.13 currently in debian.

**Comment by emilyemorehouse** [comment]
This has been completed and will be included in the 1.0.0 release, tracked here: #1333
