### ISSUE TITLE
Best place to get request url and request method

### ISSUE THREAD

**Issue by cosmok** [axios/axios#1210]
Hi,

I have a response interceptor in which I am adding context to the user session - so the session with context can be sent to a bug tracker in case of any error.

Interceptor is like this:

```js
this.axiosClient.interceptors.response.use(response => {...})
```

I want to get the url and method within the interceptor. Requests are of type XMLHTTP. I am seeing two places from where to get the details I want:

`response.config or response.request.Z`
See screenshot below of the response obj

I have two questions:

1. Where is the key 'Z' being added from?  I remember this being 'W' at some point - but my memory could be failing me.
2. Which is more reliable: response.config or response.request.Z for my purpose.

![xhr](https://user-images.githubusercontent.com/21658/33426898-880bc98a-d617-11e7-984e-ed5968cf288a.png)

Version:
"axios": "^0.16.2"
Platform:
Browser (mostly Mobile Webviews)

**Comment by chinesedfan** [comment]
> Where is the key 'Z' being added from? I remember this being 'W' at some point - but my memory could be failing me.

I don't know your interceptor logic. So sorry I am not able to answer it.

> Which is more reliable: response.config or response.request.Z for my purpose.

It depends. `response.config` means the config axios maintained internally. And `response.request.Z` means the real request options. If you want to know whether there is something wrong in axios, use the first one. If want to know why your response is not as you expected, use the second one.
