### ISSUE TITLE
Redirects are not available to the response interceptor or the validate Status function

### ISSUE THREAD

**Issue by iamianmiller** [axios/axios#1211]
Redirects are not available to the response interceptor or the validate Status function.  

Background info: I am making requests to a REST API on running on Google App Engine.  When a requests is not properly authenticated it is redirected to the login page.  According to [this issue](https://github.com/axios/axios/issues/980), I should be able to write an interceptor to do that.  However If you try [this fiddle](https://jsfiddle.net/ianmiller/n8m7eoyr/) you'll notice that no status code 302 is ever logged.

## Context

- axios version: *e.g.: v0.17.1*
- Environment: chrome 62, windows 7*

**Comment by TimBeyer** [comment]
The browser uses XHR and as far as I know you cannot override the default follow redirect behavior there.

**Comment by JustinBeckwith** [comment]
Greetings!  This looks like an issue with the built-in behavior of the browser.  I don't think there's a whole lot we can do here.  If you think this should be re-opened...  let us know!
