### ISSUE TITLE
How to prevent catch from changing the promise?

### ISSUE THREAD

**Issue by lzl124631x** [axios/axios#1216]
# Summary

I thought `.catch` is like the `.fail` in jQuery, but contrarily `.catch` changed the promise returned. How can I make `.catch` just handle the error without changing the promise so that I can chain subsequence `.then` and `.catch`?

```
axios.get(...)
.catch(....) // this changes the promise returned.
.then(....) // the input is the one returned by catch, I don't want this 
```

Please find detail in this jsfiddle: https://jsfiddle.net/Richard_Liu/afwzrtpc/

# Context

- axios version: *0.17.1*
- Environment: *jsfiddle*

**Comment by Billy-** [comment]
This is nothing to do with axios... That is how promises work. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Return what you want to pass on in the catch

**Comment by Khaledgarbaya** [comment]
This issue has not had recent activity. It will be closed.
Feel free to open a new one if you still have questions/issues
Thanks

**Comment by TCGV** [comment]
Coming from jQuery promises this wasn't straightforward to me as well. I had to do the following to prevent triggering chained `then` calls after calling `catch`:

```
    var promise = axios.create({ /* config */ }).then(function (response) {
        /* handle response */
    });
    
    promise.catch(function (error) {
      /* handle error */
    });
    
    /* return original promise */
    return promise;
```

The equivalent jQuery ajax structure would be:

```
   return $.ajax({ /* config */ }).done(function (response) {
        /* handle response */
    }).fail(function (error) {
      /* handle error */
    });
```

**Comment by lzl124631x** [comment]
@TCGV Frankly speaking I like the jQuery way since it's more compact  🤦‍♂️  Thanks for your solution.
