### ISSUE TITLE
Add an options to transform request and response with a template

### ISSUE THREAD

**Issue by meirotstein** [axios/axios#1218]
### Summary

 I had in mind that it will be very nice that in addition to the `transformRequest` and `transformResponse` options which requires to implement transformation functions, to also have an option to configure transformation templates which will be compiled by a template engine in the background.

The new options will be called `transformRequestTemplate` and `transformResponseTemplate`.

A possible template engine can be [JavaScript-Templates](https://github.com/blueimp/JavaScript-Templates) which is very lightweight.

For example (based on JavaScript-Templates syntax):

```javascript
axios.get('https://api.github.com/users/mzabriskie', {
          transformResponseTemplate: '{"first": "{%=o.user.firstName%}","last": "{%=o.user.lastName%}"}'
        })
        .then(function (res) { 
          document.getElementById('name').innerHTML = res.data.first; //Michael
          document.getElementById('last').innerHTML = res.data.last; //Jackson
        });
```
Which the actual response is:
```javascript
{"user": {"firstName": "Michael", "lastName": "Jackson"}, ...}
```

**Comment by Khaledgarbaya** [comment]
You can achieve that already if your server returns JSON response. `response.data` will be an object. It's up to your server it shapes the data
