### ISSUE TITLE
axios Converting circular structure to JSON

### ISSUE THREAD

**Issue by DanielWLam** [axios/axios#1220]
I am coming across this problem. Simply use async await and axois for an api. And it give the feed back with 'Converting circular structure to JSON'. Any solution? 
```js
async get (url) {
  const result = await axios.get('https://cnodejs.org/api/v1/topics')
  return result
}
```

BTW, [https://cnodejs.org/api/v1/topics](https://cnodejs.org/api/v1/topics), you can just click this link, the api response find.

**Comment by cameronpickham** [comment]
Try `return result.data`

**Comment by ErenYatkin** [comment]
@cameronpickham I'm getting this error, I tried your solution but still the same.

**Comment by DanielWLam** [comment]
@cameronpickham works for me, thanks~!

**Comment by luscas** [comment]
You can use [destructuring assignment](https://dev.to/sarah_chima/destructuring-assignment---arrays-16f)
```javascript
async get (url) {
  const { data: result } = await axios.get('https://cnodejs.org/api/v1/topics')
  return result
}
```
