### ISSUE TITLE
[ts] cannot find module 'axios'.

### ISSUE THREAD

**Issue by mjbates7** [axios/axios#1221]
**Summary**

When I create a `.ts` file and try to import axios it complains that it cannot find the module 'axios'.

If I create a `.js` file then it works fine.

![image](https://user-images.githubusercontent.com/4522738/33621520-e26125d2-d9e2-11e7-8536-c656e8026bbb.png)

As you can see the `typings` file is in the package folder. Any ideas on why this is happening or what I need to do to make it work?

**Context**

- axios version: *v0.17.1*
- Environment: *node v8.2.1, windows 10, typescript v2.6.1*

**Comment by gs-akhan** [comment]
Same error.  :(

**Comment by gs-akhan** [comment]
I notice this works when you have 
```module : "commonjs"```
and does not work when you have module : esnext or es2015

I wish I could fix this, if someone can help me. 
Thanks

**Comment by gs-akhan** [comment]
try ```"moduleResolution": "node"```
It solved for me 

Thanks

**Comment by nagylzs** [comment]
Same error here. It is not "tsconf.json" but "tsconfig.json". The suggested `moduleResolution` change did not fix it for me.

**Comment by love2dishtech** [comment]
This fixed the problem for me as well. Any idea what's the logic behind the solution.

**Comment by robaxelsen** [comment]
Closing due to solution provided by @gs-akhan. For further questions regarding this I would recommend StackOverflow or a Typescript forum/community.

**Comment by rsmolkin** [comment]
I'm having the same problem in Cloud9 without type script

`const axios = require('axios')`

Response
{
    "errorMessage": "Cannot find module 'axios'",
    "errorType": "Error",
    "stackTrace": [
        "Function.Module._load (module.js:417:25)",
        "Module.require (module.js:497:17)",
        "require (internal/module.js:20:19)",
        "Object.<anonymous> (/var/task/getGroupHolesPlayed/index.js:4:15)",
        "Module._compile (module.js:570:32)",
        "Object.Module._extensions..js (module.js:579:10)",
        "Module.load (module.js:487:32)",
        "tryModuleLoad (module.js:446:12)",
        "Function.Module._load (module.js:438:3)"
    ]
}

**Comment by seanpierce** [comment]
@gs-akhan 's solution did not work for me, still receiving "Cannot find module 'axios'" type error

**Comment by mubarak23** [comment]
Module not found: Can't resolve 'axios' in 'C:\Users\Mubarak  M Aminu\Desktop\ReactClass\Blog\src'
any solution to this problem

**Comment by fireappsAdmin** [comment]
I got it working using this 
`import axios, { AxiosRequestConfig, AxiosPromise, AxiosResponse } from 'axios';`

**Comment by rgstephens** [comment]
Neither @gs-akhan nor @fireappsAdmin solutions worked for me.

**Comment by fireappsAdmin** [comment]
How about `const axios = require('axios');` Have you tried that one? Both this one and the one above work for me.

**Comment by colincmcc** [comment]
If anybody is still having issues with this, copying `node_modules/axios/index.d.ts` to `node_modules/@types/axios/index.d.ts` seemed to work for me.

**Comment by aztack** [comment]
The error remains after adding `"moduleResolution": "node"` to `tsconfig.json` .
But disappeared after restarting VS Code.

**Comment by abisuq** [comment]
just remove the `@types/axios`

**Comment by keyskey** [comment]
copying node_modules/axios/index.d.ts to node_modules/@types/axios/index.d.ts works for me as well, thanks @colincmcc !

**Comment by tncbbthositg** [comment]
Out of habit, I tend to 
```npm i --save module
npm i -D @types/module```

I noticed that axios has its own type declarations so I just executed `npm uninstall @types/axios` and this error went away.

**Comment by pavoltravnik** [comment]
`moduleFileExtensions: ["js", "json", "jsx", "ts", "tsx", "node"]` [docs](https://jestjs.io/docs/en/configuration#modulefileextensions-arraystring)

**Comment by justSteve** [comment]
@aztack Did you try "moduleResolution": "Node",?

**Comment by esdrasdemorais** [comment]
# Yarn
$ yarn add axios

# npm
$ npm install axios --save

**Comment by imrandong** [comment]
> I got it working using this
> `import axios, { AxiosRequestConfig, AxiosPromise, AxiosResponse } from 'axios';`

it work for me

**Comment by imrandong** [comment]
> I got it working using this
> `import axios, { AxiosRequestConfig, AxiosPromise, AxiosResponse } from 'axios';`

it solved my problem
