### ISSUE TITLE
Cross domain request with credentials fails in Safari 11.0.1 

### ISSUE THREAD

**Issue by susannakosic** [axios/axios#1224]
Hi all,
I am experimenting the following issue.

I am using Axios 0.17.1 to send a cross-domain POST request with _withCredentials_.

The request is send correctly to the server, and the response comes back as expected in Firefox and Chrome. Unfortunately in Safari it is failing, the server replies back with HTTP 401. This is due to authorisation cookie not being attached to the request.

These are Chrome request headers:

`
OPTIONS /mkt/games/search?sort=timestampApproved,-1&filters=%7B%7D&offset=0&maxResults=1&brandId=WIN&skinId=winnercasino HTTP/1.1
Host: 0.0.0.0:3000
Connection: keep-alive
Access-Control-Request-Method: GET
Origin: http://localhost:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,es;q=0.9,en;q=0.8,it;q=0.7

GET /mkt/games/search?sort=timestampApproved,-1&filters=%7B%7D&offset=0&maxResults=1&brandId=WIN&skinId=winnercasino HTTP/1.1
Host: 0.0.0.0:3000
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: http://localhost:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Content-Type: application/json;charset=utf-8
Referer: http://localhost:9000/marketplace/games/all
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,es;q=0.9,en;q=0.8,it;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6...AhA
`

These are Safari request headers:

`'http://0.0.0.0:3000/mkt/games/search?sort=timestampApproved,-1&filters=%7B%7D&offset=0&maxResults=1&brandId=WIN&skinId=winnercasino' \
-XOPTIONS \
-H 'Referer: http://localhost:9000/marketplace/games/all' \
-H 'Access-Control-Request-Headers: content-type' \
-H 'Origin: http://localhost:9000' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5' \
-H 'Accept: */*' \
-H 'Access-Control-Request-Method: GET'

'http://0.0.0.0:3000/mkt/games/search?sort=timestampApproved,-1&filters=%7B%7D&offset=0&maxResults=1&brandId=WIN&skinId=winnercasino' \
-XGET \
-H 'Referer: http://localhost:9000/marketplace/games/all' \
-H 'Content-Type: application/json;charset=utf-8' \
-H 'Origin: http://localhost:9000' \
-H 'Host: 0.0.0.0:3000' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Connection: keep-alive' \
-H 'Accept-Language: en-us' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5'
`

Is this a known issue?

**Comment by Axnyff** [comment]
It looks like it's a security thing from safari: http://blog.prowebsoftware.net/2013/08/safari-cors-requests-withcredentials/

**Comment by Khaledgarbaya** [comment]
This issue has not had recent activity. It will be closed.
Feel free to open a new one if you still have questions/issues
Thanks
