### ISSUE TITLE
Multiple response interceptors don't work

### ISSUE THREAD

**Issue by AndreiBru** [axios/axios#1226]
#### Summary

In the case of registering multiple response interceptors (error callback in my case), only the first is taken into consideration.
```

axios.interceptors.response.use(undefined, err => {
  console.log('First');
  return err;
});
axios.interceptors.response.use(undefined, err => {
  console.log('Second');
  return err;
});
```

Output:
`>>First`

Context
- axios version: *v0.16.2*

**Comment by AndreiBru** [comment]
Verified that it behaves the same for multiple success callbacks

**Comment by F-12** [comment]
it seems that multiple interceptors on both global axios object and instance object still don't work.

```javascript
axios.interceptors.response.use(undefined, err => {
  console.log('First');
  return err;
});
var instance = axios.create({})
instance.interceptors.response.use(undefined, err => {
  console.log('Second');
  return err;
});
```

output:
`Second`

**Comment by F-12** [comment]
![axiostest html 2017-12-12 19-27-31](https://user-images.githubusercontent.com/7236630/33882444-1f07e0d0-df73-11e7-9529-dc2d0319e4a7.jpg)



it seems that  multiple interceptors actually appear in handlers list, but only the first works.

**Comment by nassimbenkirane** [comment]
The response interceptors are called in reverse order. This is why you have 'Second' as an output.

In order to have your next interceptor (the first one) fail, you need to `return Promise.reject(error)` from your error handlers.

When you `return error`, it goes through the success handler.

```
axios.interceptors.response.use(undefined, err => {
  console.log('First');
  return Promise.reject(err);
});
var instance = axios.create({})
instance.interceptors.response.use(undefined, err => {
  console.log('Second');
  return Promise.reject(err);
});
```

Could you try and see if that fixes your problem ?

**Comment by unguul** [comment]
Probably worth mentioning for people using axios in the context of vuejs: If you set the interceptors outside of your `Vue` instance they will not get triggered on page refresh (by pressing F5).

I fixed this by moving the setting of interceptors to the `created` function of my `Vue` instance.

**Comment by AuthorProxy** [comment]
I have code like this:

```
axios.interceptors.response.use(undefined, err => {
  console.log('First');
  return Promise.reject(err);
});

let axiosInstance;
axiosInstance = axios.create({ baseURL: BACKEND_SERVICES.SPA_BACKEND });

axiosInstance.interceptors.response.use(undefined, err => {
  console.log('Second');
  return Promise.reject(err);
});
```

And after creating new instance - interceptors has not been copied from default axios, I see only `Second` on console and single interceptor at `console.log`..

**Comment by WeiJieGitHub** [comment]
I think this issue could use `lodash.flow` or anything like it to resolve.

``` javascript
import { flow } from 'lodash';

const axiosInstance = axios.create();

const firstInterceptor = err => {
  console.log('First');
  return err;
};

const secondInterceptor = err => {
  console.log('First');
  return err;
};

axiosInstance.interceptors.response.use(
  undefined, 
  flow([firstInterceptor, secondInterceptor]), // just do it
);
```

**Comment by AuthorProxy** [comment]
It's a workaround, which doesn't resolve a problem, I resolve this problem similar but simpler, but I don't like such solutions. `defaultSettings` should work as expected by design, with interceptors too.

**Comment by chinesedfan** [comment]
> In order to have your next interceptor (the first one) fail, you need to return Promise.reject(error) from your error handlers.

@nassimbenkirane has explained the original issue. But response interceptors are **NOT** called in reverse order.

> it seems that multiple interceptors on both global axios object and instance object still don't work.

@F-12 Interceptors can not be inherited from the global axios object. In fact, the global axios object is a simple instance that created in advance.

```
const respInt = axios.interceptors.response.use
```

@AuthorProxy Your mistake is that `use` will return the interceptor id, instead of the interceptor instance.
