### ISSUE TITLE
Still follows redirects even though maxRedirects is set to 0

### ISSUE THREAD

**Issue by NiklasRosenstein** [axios/axios#1227]
* axios 0.17.1
* webpack 3.10.0
* Chrome 62.0.3202.94

```
    let data = new URLSearchParams()
    data.append('password', this.state.password)
    axios({
      maxRedirects: 0,
      method: 'post',
      url: '/auth/signin',
      data: data
    })
    .then(response => {
      console.log(response)
    })
```

The `/auth/signin` endpoint returns 302, and axios follows that redirect, even though `maxRedirects` is set to 0. The [Request Config](https://www.npmjs.com/package/axios#request-config) states that setting `maxRedirects` to 0 will cause axios to not follow redirects. The response I get back in the `.then()` block is the response from the 200 `GET /` request.

```
127.0.0.1 - - [07/Dec/2017 14:22:11] "POST /auth/signin HTTP/1.1" 302 -
127.0.0.1 - - [07/Dec/2017 14:22:11] "GET / HTTP/1.1" 200 -
```

Am I missing something or is this a bug?

**Comment by cdeutsch** [comment]
Are you using it in a browser? It only works in Node. See #674

**Comment by NiklasRosenstein** [comment]
Yes, I am. Apparently I haven't looked through the existing issues well enough, sorry.

The [second-last comment](https://github.com/axios/axios/issues/674#issuecomment-279225530) states that this info is in the README, but that doesn't seem to be the case (anymore?).

Thanks, I'll have to add a "no redirect" option to the end-point then.
