### ISSUE TITLE
Error when using a local URL on baseURL

### ISSUE THREAD

**Issue by eole1712** [axios/axios#1228]
## Summary

Hi there,

When I create a query directly with axios to call on a local URL, it works perfectly.
```
axios.get('http://localhost:3004/health')
```

But when I create an axios client in a plugin that contains juste the base url :
```
axios.create({ baseURL: 'http://localhost:3004' })
```

and import it and then call `.get('/health')`, I have an error :

```
Error: connect EHOSTUNREACH 0.0.11.184:80 - Local (192.168.1.110:49855)
service-ca |     at Object._errnoException (util.js:1024:11)
service-ca |     at _exceptionWithHostPort (util.js:1046:20)
service-ca |     at internalConnect (net.js:971:16)
service-ca |     at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1106:7)
service-ca |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
```

When I preview the error's stack trace, you can see that the __currentUrl it generates is incorrect since it omits the localhost.

![axios](https://user-images.githubusercontent.com/11462388/33724695-6c18d1c4-db70-11e7-8d6a-06b81acbee88.png)

## Context

- axios version: v0.17.1
- Environment: node v8.9.1, macOS

**Comment by celgra** [comment]
Are you still having this issue?

I looked at the code to merge url configs and there is nothing wrong there. The error you posted a screenshot of I believe is due to your node environment. Axios defers the request to the Node.js http module (when used in Node) all the code between an Axios instantiation and the Node.js http seems correct.

**Comment by tandrewnichols** [comment]
I think this is related (the screen shot looks similar to what I'm seeing). If I use a local baseUrl, the port that axios attempts to use is wrong. That is, I'm create an axios instance with `baseUrl: 'http://localhost:8000'` but all the requests are throwing ECONNREFUSED on `127.0.0.1:80`. Here's part of an error response (I grabbed everything down to baseUrl).

```
{ Error: connect ECONNREFUSED 127.0.0.1:80
              at Object._errnoException (util.js:1024:11)
              at _exceptionWithHostPort (util.js:1046:20)
              at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
            code: 'ECONNREFUSED',
            errno: 'ECONNREFUSED',
            syscall: 'connect',
            address: '127.0.0.1',
            port: 80,
            config: 
             { adapter: [Function: httpAdapter],
               transformRequest: { '0': [Function: transformRequest] },
               transformResponse: { '0': [Function: transformResponse] },
               timeout: 5000,
               xsrfCookieName: 'XSRF-TOKEN',
               xsrfHeaderName: 'X-XSRF-TOKEN',
               maxContentLength: -1,
               validateStatus: [Function: validateStatus],
               headers: 
                { Accept: 'application/json, text/plain, */*',
                  'X-Request-Id': 'no xri header',
                  'User-Agent': 'axios/0.17.1' },
               baseUrl: 'http://localhost:8000/api',
```

**Comment by tandrewnichols** [comment]
The problem is [this line](https://github.com/axios/axios/blob/138108ee56bd689305ae505a66b48d5e9c8aa494/lib/adapters/http.js#L57). It's trying to parse `config.url` before adding `baseUrl` to it, so there's no protocol or domain or anything. In my case - logging right before that line - config.url is just `/v1/members/me`, rather than `http://localhost:8000/api/v1/members/me` as I'd expect.

**Comment by tandrewnichols** [comment]
I only just realized that I'm using `baseUrl` instead of `baseURL`, so I guess this is not an issue. Although . . . maybe it would be nice to warn when that's the case, as it's easy to miss that distinction in the docs.

**Comment by koresar** [comment]
@tandrewnichols this is such a helpful last message mate. I was banging my head for an hour.

Thank you for creating this issue and then posting the solution.

**Comment by Saifu786** [comment]
ERROR	{ Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }

PLEASE HELP ME WITH THIS

**Comment by koresar** [comment]
Looks like you are not running the HTTPS protocol server on your computer. Change the port or host to something which is open and working.

Also, these kind of "help me please" questions without much details are rarely leading to any meaningful answers.
And also, a better place to ask these would be the StackOverflow website. Have your tried it?
