### ISSUE TITLE
Handle empty response from server which sending status code 200

### ISSUE THREAD

**Issue by mikeevstropov** [axios/axios#1235]
Hi. I need to handle empty response from server which sending status code 200, but i dont know how. I think "axios.interceptors.response" will help, but how can i send an error using this example:

``` javascript
axios.interceptors.response.use(function (response) {
    return response.data !== ''
        ? response
        : Promise.reject(???); // here i should reject response
}, function (error) {
    return Promise.reject(error);
});
```

Someone can help? Thank you

**Comment by jcrben** [comment]
Please use Stackoverflow (https://stackoverflow.com/questions/tagged/axios) for general questions, or chat in gitter (https://gitter.im/mzabriskie/axios).

@nickuraltsev can we tag this as question / non-issue and close?

**Comment by rubennorte** [comment]
thanks @jcrben
