### ISSUE TITLE
Error downloading document from AWS S3, using axios / React

### ISSUE THREAD

**Issue by businessnumbertwo** [axios/axios#1236]
Label: Help wanted

I have some fairly simple code that downloads a previously uploaded file from S3. I can see that the file has uploaded correctly, and download it from via the S3 console.

My code is as follows:
     
```
        axios.post(signingURL, attachment) // Get signature
        .then(response =>
        {  
            axios.get(response.data.signedURL) // Try and get file
            .then( response =>
            {
                fileDownload(response.data, attachment.filename);
            })
            .catch(error => props.dispatch(actions.change('error', error.response)))
        })
        .catch(error => props.dispatch(actions.change('error', error.response)))
```

The first axios call is back to the server, to retrieve the signed URL for S3. The second to S3 to get the file. All good.

But I notice that the file format is not correct. All non-printing characters have been wrongly interpreted, and for the life of me I cannot figure out why. Here are two samples from the start of the .pdf document I am working with. Firstly a raw sample, from the start of original file:

```
%PDF-1.3
%ƒÂÚÂÎßÛ†–ƒ∆
4 0 obj
<< /Length 5 0 R /Filter /FlateDecode >>
stream
xÌ]€í«q}ÔØh?X(àAﬂ/z±I§HÒ
+1`ÖË%@¿ƒÇ‡ÓÚÇˇçæ∆ÂìUuN’t˜LœÏÇ4Ï†ˆ6j™≥ÛûYïY›ﬂÁ_‰ﬂÁÂêEë∑ÌòWM~˘$ˇ2ôﬂ{ˇ™ÃœØÚ¬˝wunÛ‹Â]ˇÁ¸"Ô,/∂EQ‘˘Ÿy÷˚˚º-´mY÷u~w�‡≥ã¸ﬁŸYπ-p˜Ÿ”|S
˜ Ú^Uîe^ï®À;˘ŸÊŒ<	¸Ã√TÄZÇ˜∑|Û˛`QÊõÔÓ‰wãmùo.l†…7O‹@ômÆswÖ°ˇ≤ü⁄|£Åµõì©_›…�ø 7/¸Ø	U–^q‰Ötæ˘ ]‡¶◊wÚøÁg{Rø»”õÚF<ÅÈπÿ”÷√∂´∆1ø€4ŸÑÁ‡—C√<˙Êâ·ä›˛ÑÎØß·üïpÕúz$b…ƒ“4S)„âœìÆØS≤Õï
```

And now with what is returned after the download:

```
%PDF-1.3
%���������
4 0 obj
<< /Length 5 0 R /Filter /FlateDecode >>
stream
x�]ے�q}�h?X(�A�/z�I�H�
+1`��%@�Ă��������UuN�t�L��4��6j���Y�Y���_����E���WM~�$�2��{���ϯ���wun���]���"�,/�EQ���y����-�mY�u~w�ೋ���Y�-p���|S
���^U�e^���;����<	���T�Z���|��`Q����w�m�o.l��7O�@�m�sw������|������_�����7/��	U�^q�t���]��w��g{R��ӛ�F<�����ö��1��4ل���C�<���������៕p͜z$b���4S)�����S�͕
```

Any ideas? I've tried downgrading axios to 0.16.2, as I am sure this code used to work. But this hasn't made a difference.

Also instead of using the axios.get inner call I also tried:

   ` window.open(response.data.signedURL)`

And this worked. Thus proving, its not the file stored on the server, but something about the way I am using axios to downloading it.

Many thanks,

Phil

#### Context

- axios version: v0.17.1
- Environment: React 16.1, Chrome Version 62.0.3202.94 (Official Build) (64-bit), Mac 10.13.2*.

**Comment by batjko** [comment]
Looks to me like an encoding issue.
How does your `fileDownload()` function handle the response? I assume that's the output you are looking at?

**Comment by Khaledgarbaya** [comment]
This issue has not had recent activity. It will be closed.
Feel free to open a new one if you still have questions/issues
Thanks

**Comment by JuanmaMenendez** [comment]
any solution?
