### ISSUE TITLE
Headers should be compared with case ignored

### ISSUE THREAD

**Issue by betalb** [axios/axios#1237]
**Summary**

Headers provided in config are merged with defaults without checking for existing value that can be in different case

i.e. when doing below request we can't predict which value will be set from defaults `Accept` or from config `accept`
```javascript
axios.request(url, {
  headers: {
    accept: 'some-accept-value'
  }
});
```

Chrome will set `Accept`, which is not expected

**Context**

- axios version: 0.17.0
- Environment: node v9.2.1, chrome 63, macOS

**Comment by betalb** [comment]
I've created potential fix, if it looks good, I can adopt to contributing guide, and create PR

https://github.com/betalb/axios/commit/09cbfdca0d0ae07bf072a5eea5db1fe892b68524

**Comment by robaxelsen** [comment]
@betalb I would propose you submit your PR directly, as it's easier for the maintainers to notice it and potentially approve it.

**Comment by montogeek** [comment]
@betalb Please submit the PR, What you think about using a `Map`?

**Comment by betalb** [comment]
I've raised PR, anyone interested please review

**Comment by codeclown** [comment]
IMO the most straight-forward way would be to lowercase all header names (a) in defaults, and (b) when headers are passed to instance/request. Only dealing with lowercase header names would remove any fiddling around which case to check.

**Comment by jasonsaayman** [comment]
Hi,

Thank you for this pull request, this is a pretty stale pull request so I am going to close this in favour of #2880 as its a bit fresher and seems to solve the asme issue. If you feel it does not solve this issue please open an issue again.

Thanks
