### ISSUE TITLE
[Question] Any ideas on how to use axios with Flow(types)?

### ISSUE THREAD

**Issue by stefvw93** [axios/axios#1238]
Flow gives me a warning that my returned axios promise is uncovered. Does anybody use axios + Flow and have any idea how to fix this?

<img width="425" alt="schermafbeelding 2017-12-14 om 15 17 35" src="https://user-images.githubusercontent.com/13518365/34000828-a4862538-e0ee-11e7-8abd-245d2601ed3f.png">

**Comment by henrikra** [comment]
Did you get axios typing to work at all with VScode? I have ran `flow-typed install` and then it adds `flow-typed/npm/axios_v0.17.x.js` to root of my project. But still I don't get intellisense for example when writing `axios.`

**Comment by sakoh** [comment]
I'm currently working on adding flow-types to axios on a branch on my fork:
https://github.com/sakoh/axios/tree/flow-types

**Comment by hqthao** [comment]
Have this branch done and ready to merge yet ? Thanks.

**Comment by jmarceli** [comment]
I'm not sure if it is still relevant but in order to add Flow annotations to axios response I use this code:

```
// @flow
import axios from 'axios';
import type { $AxiosXHR } from 'axios';

type RateLimit = {
  limit: number,
  remaining: number,
  reset: number
};
type RateLimitResponse = {
  resources: {
    core: RateLimit,
    search: RateLimit,
    graphql: RateLimit,
  },
  rate: RateLimit,
};

export const getRateLimit = async (): Promise<RateLimitResponse> => {
  const query: Promise<$AxiosXHR<RateLimitResponse>> = axios('https://api.github.com/rate_limit');
  const result = await query;
  return result.data;
};
```

**Comment by datner** [comment]
Is there an update on this? It's quite annoying not being able to reach that elusive 100% flow coverage haha

**Comment by shobishani** [comment]
Is there any update?

**Comment by stefvw93** [comment]
I switched to typescript. Looking back now, after a few years of time and the code example, I'm glad that I did. So no update from me, sorry!

**Comment by chinesedfan** [comment]
Typescript is becoming more and more popular than Flow. Closing until more users require for it.

**Comment by Naveenchandar** [comment]
Any update on this ? :(
