### ISSUE TITLE
How do I send data using axios.delete ?

### ISSUE THREAD

**Issue by sarathsarma** [axios/axios#1242]
axios
        .delete(url, { params: requestData })
        .then(function(response) {
          console.log(response.data));
        })
        .catch(function(error) {
          console.log(error);
        });

Not able to recieve the params that we sent as a request body on the server side... please help .... thanks in advance!!

**Comment by zl810881283** [comment]
same problem, do you solve it?

**Comment by ChadTaljaardt** [comment]
@sarathsarma Do you still need help with this?

**Comment by sarathsarma** [comment]
@ChadTaljaardt no! thanks found a solution a long ago! :)

**Comment by ggggabri** [comment]
@sarathsarma I can't seem to find a fix, do you happen to remember it?

**Comment by ChadTaljaardt** [comment]
@ggggabri https://github.com/axios/axios/issues/897
