### ISSUE TITLE
Error with Proxy

### ISSUE THREAD

**Issue by yovanoc** [axios/axios#1243]
#### Summary

Hello,
I have to set a proxy for a request that blocks ip daily after 3 requests.
So, I'm setting the proxy like said in the readme.

<img width="501" alt="screen shot 2017-12-17 at 13 44 11" src="https://user-images.githubusercontent.com/7302317/34079565-65f4c204-e330-11e7-8ab6-4d6c7d32841b.png">

but  I have this error:

<img width="720" alt="screen shot 2017-12-17 at 13 37 16" src="https://user-images.githubusercontent.com/7302317/34079530-c56c58b0-e32f-11e7-94b1-fd59bc1b8d6c.png">

I searched for issues and I tried the axios-proxy-fix module instead.
but it gives me that:

<img width="718" alt="screen shot 2017-12-17 at 13 35 23" src="https://user-images.githubusercontent.com/7302317/34079536-e12d0310-e32f-11e7-9fdb-825992c913b7.png">

PS: the "Blocked by CloudFront" was a supposition but I'm not sure
... and if it is, there is a way to 'bypass' that ?
<img width="412" alt="screen shot 2017-12-17 at 13 42 47" src="https://user-images.githubusercontent.com/7302317/34079555-45332844-e330-11e7-8097-c1707f7c2c67.png">

but when I work with https module and https-proxy-agent it works fine... but I want to use axios... could you tell me if its a bug or that I have to do something else

thanks

#### Context

- axios version: v0.17.1
- Environment: Node 9.3.0 & macOS High Sierra Version 10.13.3 Beta (17D20a)

**Comment by chinesedfan** [comment]
Closed due to stale. Leave some keywords as searching indexes.

- EPROTO, unknown protocol
- Blocked by CloudFront
