### ISSUE TITLE
odd prob: chrome iOS and axios, known issue?

### ISSUE THREAD

**Issue by nockgish** [axios/axios#1245]
Hi, in attempt to rule out problems with Axios I'm having in chrome on iOS (on iPad Pro) (very particular, I know) - I would like to see if anyone knows if there are existing issues with Axios and Chrome on iOS (latest version). 

I'm not 100% on the device set up, but its at least I do know Chrome on iPad Pro.

**Comment by serenalucasjose** [comment]
I've just replicate this error and i want to shoot my self.
