### ISSUE TITLE
401 throw Error

### ISSUE THREAD

**Issue by tinwinaung** [axios/axios#1246]
![2017-12-19 09_54_55-microsoft store](https://user-images.githubusercontent.com/1169631/34136917-01cd0d8a-e4a3-11e7-8cc9-1baa643dbe27.png)

When I have 401 error, I can always see error in the console. Is it normal?

**Comment by rickysang** [comment]
@tinwinaung By default, Chrome reports network issues. You can suppress this error here: `DevTools` -> `Settings` -> `Console` -> `Hide network messages`. 

[https://developers.google.com/web/tools/chrome-devtools/console/#additional_settings](https://developers.google.com/web/tools/chrome-devtools/console/#additional_settings)

**Comment by Khaledgarbaya** [comment]
This a normal browser behavior, I am closing this issue now. Feel free to open a new one if you have another issue
