### ISSUE TITLE
Add support for multipart/related requests

### ISSUE THREAD

**Issue by JustinBeckwith** [axios/axios#1247]
It would be great if we could add native support for multipart/related data.  
https://tools.ietf.org/html/rfc2387

This is supported out of the box with request:
https://github.com/request/request#multipartrelated

To work around it, I was able to write code like this:
https://github.com/google/google-api-nodejs-client/pull/891/files#diff-e70ec3aed1b9d4ac225b287e3caf1ef6R153

I'd be happy to submit a PR if folks would like to see support.

**Comment by ayushkamadji** [comment]
+1 this

**Comment by montogeek** [comment]
@JustinBeckwith A PR would be amazing!

**Comment by lucasriondel** [comment]
any news about that ?

**Comment by Vinetos** [comment]
I think i'll try to implement this feature

**Comment by Vinetos** [comment]
🤔

**Comment by lucasriondel** [comment]
Why has it been closed ?

**Comment by adamdavies001** [comment]
I would like to see this added. There are still many use cases out there for this feature.
