### ISSUE TITLE
[DOCS] Add instructions to configure Axios when used with Rollup

### ISSUE THREAD

**Issue by AntonioRedondo** [axios/axios#1259]
Rollup will need some tweaks if we want Axios working and bundled successfully. Without the tweaks the Rollup bundle will be interrupted with errors caused by Axios.

Adding a small entry on the Axios `README.md` will spare a few hours of Googling desperate solutions.

We'll need to add the below to the Rollup configuration:
```JavaScript
// package.json
...
"rollup-plugin-node-resolve": "3.0",
"rollup-plugin-json": "2.3"
...

// Rollup configuration
...
plugins: [
    rollupNodeResolve({ jsnext: true, preferBuiltins: true, browser: true }),
    rollupJson(),
    ...
]
```

Please note the two key tweaks maded to the Rollup configuration are the parameter `browser: true` added to the `rollupNodeResolve` plugin, and the addition of the `rollupJson` plugin.

Thanks to this [Rollup issue](https://github.com/rollup/rollup-plugin-commonjs/issues/28) I was able to find out the solution.

#### Context
- axios : 0.17,
- rollup: 0.52,
- rollup-plugin-node-resolve: 3.0,
- rollup-plugin-json: 2.3

**Comment by Ventajou** [comment]
I just ran into that, and I had the additional issue of using `rollup-plugin-commonjs`. I discovered that I should declare that plugin **after** the node-resolve and json plugins in order to avoid getting an error bundling Axios.

**Comment by alcandelario** [comment]
@Ventajou any chance you might have a config file snippet handy to show your setup? I have been coming up empty at any attempt to get axios to build, even with these suggestions. 

here's what gets added to my final bundle

```
module.exports = require('./lib/axios');
```

Here's my config:

```
import vue from 'rollup-plugin-vue'
import buble from 'rollup-plugin-buble'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import gzip from "rollup-plugin-gzip"
import uglify from 'rollup-plugin-uglify'
import replace from 'rollup-plugin-replace'
import livereload from 'rollup-plugin-livereload'
import serve from 'rollup-plugin-serve'
import includePaths from 'rollup-plugin-includepaths'
import CssNano from 'cssnano'
import rollupJson from 'rollup-plugin-json'

const isProduction = process.env.NODE_ENV === `production`
const isDevelopment = process.env.NODE_ENV === `development`
const isWatch = process.env.NODE_ENV === `watch`
const appLoaderSource = __dirname + '/src/app.js'
const appLoaderDest = __dirname + '/dist/app.js'

let includePathOptions = {
    include: { 
        'axios': 'node_modules/axios/index.js'
    },
    paths: ['src/plugins', 'src/plugins/custom'],
    external: [],
    extensions: ['.js', '.json', '.html']
}

let cssNanoConfig = (isProduction) ? {preset: 'default'} : {preset: 'default'} 

let postCssPlugins = [
        CssNano(cssNanoConfig)
    ]
var config = {
    input: 'src/main.js',
    output: {
        file: 'dist/app-bundle.js',
        format: 'iife'
    },
    plugins: [
        replace({
            'process.env.NODE_ENV': JSON.stringify('production')
        }),
        includePaths(includePathOptions),
        nodeResolve({
            module: true,
            jsnext: true,
            main: true,
            browser: true,
            extensions: ['.vue']
        }),
        rollupJson(),
        commonjs({
            include: [ 'node_modules/**']
        }),
        vue({
            css: null,
            compileTemplate: true,
            postcss: postCssPlugins
        }),
        buble(),
        gzip()
    ]
}

if (isProduction) {
    config.plugins.push(uglify())
}

if (isWatch) {
  config.plugins.push(livereload())
  config.plugins.push(serve({
    contentBase: './',
    port: 4040,
    open: true
  }))
}

export default config
```

**Comment by Ventajou** [comment]
@alcandelario I gave up on using Axios in the browser, I'm just using the standard `fetch` API now, browser support is good enoug: https://caniuse.com/#search=fetch

**Comment by pilishen** [comment]
actually, to fully compile axios, we still need another two plugins
`rollup-plugin-node-globals`
`rollup-plugin-node-builtins`
which allow you to do named imports in addition to the default import, otherwise module like http or https, a bunch of other stuff, may be undefined

**Comment by kokujin** [comment]
Is there a working config documented somewhere? I have been struggling with this problem for a while now. Thanks

**Comment by lumixraku** [comment]
Same problem.
[!] Error: Could not load http (imported by /Users/hehe/Sites/node_demo/my-svelte-project/demo_coupon/node_modules/axios/lib/adapters/http.js): ENOENT: no such file or directory, open 'http'

**Comment by blendsdk** [comment]
I was unable to make it work! Is there a documentation for this
+1

**Comment by jl1014171068** [comment]
> 实际上，为了完全编译axios，我们还需要另外两个插件
> `rollup-plugin-node-globals`
> `rollup-plugin-node-builtins`
> ，除了默认导入之外还允许你进行命名导入，否则像http或https这样的模块，其他一些东西，可能是未定义的

请问，我在将使用external: ['axios']后浏览器提示 axios is not undefined如何处理？我是想将axios不打包在业务js文件中

**Comment by grunlowen2** [comment]
worked for me. thanks.

package.json
      "rollup-plugin-json": "^3.1.0",
      "rollup-plugin-node-resolve": "^3.3.0",

rollup.config.json
    import rollupNodeResolve from 'rollup-plugin-node-resolve'
    import rolllupJson from 'rollup-plugin-json'
   //plugins:
    rollupNodeResolve({ jsnext: true, preferBuiltins: true, browser: true }),
    rolllupJson()

**Comment by sabrinaluo** [comment]
@grunlowen2  your solution works for me, thank you

**Comment by SumNeuron** [comment]
@grunlowen2  tried your approach but got: 
```
Error: 'default' is not exported by node_modules/axios/index.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src/scryios/api.js (1:7)
1: import axios from 'axios'
          ^
```

**Comment by houssemFat** [comment]
Same issue here, i tried the config above but it does not working.

**Comment by azz0r** [comment]
Personally fixed this by adding browser: true to the rollup-plugin-node-resolve function

**Comment by jamigibbs** [comment]
The only way I could resolve this was importing the `rollup-plugin-commonjs` plugin:

`import commonjs from 'rollup-plugin-commonjs';`

And including it in the plugin's settings:

```js
 commonjs({
     include: 'node_modules/axios/**'
})
```

**Comment by luojinghui** [comment]
```js
import resolve from '@rollup/plugin-node-resolve';
import json from 'rollup-plugin-json';

	plugins: [
		resolve({ jsnext: true, preferBuiltins: true, browser: true }),
		babel({
			exclude: [ /\/core-js\//, 'src/test/*', 'demo/**/*', 'node_modules/**' ]
		}),
		json({
			compact: true
		})
                ...
	],
```

worked for me.

**Comment by lvlingxiao1** [comment]
```js
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default {
	input: 'src/index.js',
	output: {
		file: 'static/assets/bundle.js',
		format: 'iife',
	},
	plugins: [
		nodeResolve({
			browser: true,
		}),
		commonjs(),
	],
};
```
just using `@rollup/plugin-commonjs` worked for me. Somehow I don't need the json plugin.

**Comment by naecoo** [comment]
> > 实际上，为了完全编译axios，我们还需要另外两个插件
> > `rollup-plugin-node-globals`
> > `rollup-plugin-node-builtins`
> > ，除了默认导入之外还允许你进行命名导入，否则像http或https这样的模块，其他一些东西，可能是未定义的
> 
> 请问，我在将使用external: ['axios']后浏览器提示 axios is not undefined如何处理？我是想将axios不打包在业务js文件中

手动引入

**Comment by bhanu-alapati** [comment]
In my case, I had to use nodeResolve and json plgins before babel and commonjs. but **browser: true** is working for sure.

**Comment by robaguilera** [comment]
Thanks to this issue I was able to get this working, but can someone please explain why we need the `@rollup/plugin-json` in the first place when trying to bundle Axios with rollup? Thanks.

**Comment by seuros** [comment]
@robaguilera axios parse package.json to inline it version.

**Comment by ats1999** [comment]
> worked for me. thanks.
> 
> package.json "rollup-plugin-json": "^3.1.0", "rollup-plugin-node-resolve": "^3.3.0",
> 
> rollup.config.json import rollupNodeResolve from 'rollup-plugin-node-resolve' import rolllupJson from 'rollup-plugin-json' //plugins: rollupNodeResolve({ jsnext: true, preferBuiltins: true, browser: true }), rolllupJson()

Thanks , it worked for me as well

**Comment by kale1d0code** [comment]
the provided instructions do not work
