### ISSUE TITLE
How to convert localhost to server ip

### ISSUE THREAD

**Issue by welkinlan** [axios/axios#1260]
#### Summary

My express api server and my web server are hosted on the same machine. So in my front-end code I could simply call "http://localhost:3000" to make rest calls. For e.g.,
```
formData.append('file', file);
axios.post(`http://localhost:3000/v1/projects/${project.id}/contractFile`, formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    });
```
This all works when I am testing LOCALLY, but after deployed and accessed EXTERNALLY, it shows **net::ERR_CONNECTION_REFUSED** 

**IMO the browser tries to call literally the url "http://localhost:3000/.." instead of converting localhost to my server's ip and call "http://my-server-ip:3000/.."**

I understand this would not be an axios bug, but has anyone ever met this issue and had any workaround?

Thanks, 
Tian

#### Context

- axios version: *e.g.: v0.16.2*
- Server: Ubuntu 16.04 Nginx
- Client Environment: *e.g.: node v8.0, chrome 54, mac*

**Comment by OutThisLife** [comment]
Could use environment variables.

**Comment by batjko** [comment]
@OutThisLife 's suggestion is probably the best and most common way.

Do you build your browser-side code? E.g. with Webpack or some-such?
If so, webpack can pass variables into the built bundle during the build step, which you can take from your environment variables.

If you are not using any build step, you need to hard-code the URL into the code, and potentially replace it during deployment.
For this alone, you should probably have a build step that automates this for you.

**Comment by welkinlan** [comment]
@batjko @OutThisLife Thanks for your suggestions!  I use Webpack to build front-end package. Looks like webpack.DefinePlugin could do the trick. Will try using environment variable, thank you guys
