### ISSUE TITLE
How to loop through response and from certain data make new requests

### ISSUE THREAD

**Issue by adamjw3** [axios/axios#1261]
I'm returning some data in the response that consists of two types (section, episodes).
I'm looping through the data and checking the type. 

if its a episode i'm getting the content_url and that retrieves the episode details. However the issue i'm having is that all episodes are being assigned to the 2nd section. I think this is cause the call is async so not waiting but i thought if i call a function from within the loop it would fix that. very new to react and axios so any advise on improvements to code structure are welcome

Here is my code.

```

import axios from 'axios';

let sections = new Array(),
    section = null,
    episodes = null;

function isSection(data) {
    if (section !== null) {
        section.episodes = episodes;
        sections.push(section);
    }
    section = new Object();
    episodes = new Array();
    section.header = data.heading;
}

function isEpisode(endPoint) {
    console.log('isEpisode');
    var url = `http://feature-code-test.skylark-cms.qa.aws.ostmodern.co.uk:8000${endPoint}`;
    axios
        .get(url)
        .then((response) => {
            var episode = new Object();
            episode.title = response.title;
            episodes.push(episode);
    })
}

const dataService =
axios
    .get('http://feature-code-test.skylark-cms.qa.aws.ostmodern.co.uk:8000/api/sets/coll_e8400ca3aebb4f70baf74a81aefd5a78/items/')
    .then((response) => {

        var data = response.data.objects;

        for (var i = 0; i < data.length; i++) {
            let type = data[i].content_type.toLowerCase();

            if (type !== "episode") {
                isSection(data[i]);
            }

            if (type === "episode") {
                isEpisode(data[i].content_url);
            }
        }

        section.episodes = episodes;
        sections.push(section);

        console.log("sections", sections);

    })

export default dataService

```

**Comment by Axnyff** [comment]
Hello.

There are a couple of problems with your code.
You're relying a lot on global variables as state so it's hard to guess what your code is supposed to do.

Also, you're mixing synchronous code and asynchronous code (in isEpisode) so it won't work properly.

What you could do is use the fact that axios always return promises.

For instance, if isEpisode return the result of axios.get.then you could probably manipulate it easier.

Doing something like that could help convert your initial data and make the additional calls

    function getPromise(object) {
      let type = object.content_type.toLowerCase();
      if (type === "episode") {
        return isEpisode(object.content_url);
      }
      if (type === "episode") {
        return isSection(data);
      }
    }

And then call it something like that:

    var data = response.data.objects;
    promises = data.map(getPromise);
    Promise.all(promises).then(function(arrayOfData) {
        // arrayOfData contains all the data, you can then maybe transform it correctly instead of manipulating global state.
    });

**Comment by Khaledgarbaya** [comment]
I am closing this issue now, feel free to create a new one if you have question
