### ISSUE TITLE
HTTP used when HTTPS URL provided

### ISSUE THREAD

**Issue by benyanke** [axios/axios#1267]
#### Summary

I use Axios for browser apps making ajax calls. However, when I deployed my app to production (HTTPS), Axios continued to make it's requests to the HTTP version of the page provided, despite being given an HTTPS url.

These requests get blocked by chrome, with the following console messages:

```
Mixed Content: The page at '[PAGE-URL]' was loaded over HTTPS, 
but requested an insecure XMLHttpRequest endpoint 
'http://example.com/ajax/endpoint'. This request has been blocked; 
the content must be served over HTTPS.
```

However, I am providing https://example.com/ajax/endpoint as the url I am request.

Is there something I'm missing, or is this a bug?

Here's a code example:

``` js
this.axiosInstance = axios.create({
        timeout: 20000, // 20 sec
});

var request = this.axiosInstance.get(window.location.href + '/actions/timer/status/');

request.then(response => {
  console.log("Returned data: ", response.data);
});

```

Note that this example uses `window.location.href`, but I have also tried hardcoded urls as well, which similarly fail.

#### Context

- axios version: 0.17.1
- Environment: client-side web app, laravel backend.

**Comment by Axnyff** [comment]
Hello, do you have a reproduction of the bug? I tried your snippets but it seems to work fine

**Comment by benyanke** [comment]
Turns out it was an obscure server-side issue with laravel. Upon googling, I found a source that said to try adding/removing a slash from the end of the url string, which fixed it for me.

In case anyone comes across this issue, try adding or removing a trailing slash from your URL. Some frameworks can handle these in unexpected ways.

**Comment by Aftabnack** [comment]
I got the same issue with Django backend. Glad I stumbled upon this! Adding a trailing slash fixed the issue. Just curious if someone could give an explanation as to why it happens.

\cc @mzabriskie
