### ISSUE TITLE
Option to ignore non-http errors?

### ISSUE THREAD

**Issue by jaesung2061** [axios/axios#1269]
## Summary

It is unintuitive that axios handles non-http errors within the catch block. It's really starting to get annoying that I have to check to make sure that an error is an http error, and handle it. If it is a JS error, I have to manually rethrow, otherwise I get no error at all and it takes longer to debug something than is necessary. Is there an option to stop this behavior?

## Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v7.10.0, chrome 63, Mac OSX*

**Comment by jaredmurphy** [comment]
I believe this is just an issue with the fact that any error in the promise chain will bubble up to .catch(). It's not an Axios problem, per say, it's more a feature of promises in general.

**Comment by InvertedX** [comment]
@jaesung2061 are you using async await .because  if you wrap try catch around async await, and if any kind error happening in that block will be thrown(not only http) to catch block. @jaredmurphy as he says its not an Axios problem

**Comment by JustinBeckwith** [comment]
Greetings!  This issue has been hangin' out here for a while.  If you're still running into issues... please do let us know!

**Comment by bipin244** [comment]
@jaesung2061 Can you find any solution for handle http and non-http errors?
