### ISSUE TITLE
follow-redirects 1.3 breaks interaction with nock

### ISSUE THREAD

**Issue by JustinBeckwith** [axios/axios#1271]
Greetings!  This library has a dependency on the follow-redirects npm module. When 1.3 of that module was released (yesterday), all of the sudden my CI for node.js 4 and 6 (which don't have a package-lock.json) started to fail randomly.  After a log of digging, I discovered that this commit:
https://github.com/olalonde/follow-redirects/commit/847a47fb00ea2dcb7a8886ca16d9d82dc6accb5d

Before that commit - I could use axios and nock together in my tests.  After that commit, it causes bizarre behavior where requests just seem to hang or immediately exit.  Here's some code to reproduce the issue:

```js
const axios = require('axios');
const nock = require('nock');
const baseUrl = 'https://accounts.google.com:443';
const path = '/o/oauth2/token';
nock(baseUrl).post(path).reply(200);
axios({
  url: baseUrl + path,
  method: 'POST',
  data: { 'test': true }
}).then(r => {
  console.log("STATUS: " + r.status);
}).catch(e => {
  console.error("ERROR: " + e.message);
});
```

This code will work as expected in follow-redirects 1.2.6, but fails to work with 1.3.0.  It also works fine if I leave nock out of the equation, so I believe at this point it's some interaction with nock and follow-redirects that's causing our issues.  

Until the issue is sorted out, I would suggest changing your dependency on follow-redirects to pin to the patch version:  `~1.2.6`.  
  
I have also filed this issue in the follow-redirects repository:
https://github.com/olalonde/follow-redirects/issues/77

**Comment by RubenVerborgh** [comment]
It's a Nock problem, reported in node-nock/nock#1046 and fixed in node-nock/nock#1047.

**Comment by montogeek** [comment]
@JustinBeckwith Could you please confirm that it is fixed by using latest master from nock?

**Comment by JustinBeckwith** [comment]
Confirmed!  Thanks folks!
