### ISSUE TITLE
how to post with 'Content-Type': 'raw' to work

### ISSUE THREAD

**Issue by Jvaeyhcd** [axios/axios#1277]
Is there anyboady can tell me how to post a request width 'Content-Type': 'raw'

**Comment by Axnyff** [comment]
This seems to work for me:

    axios({
      method: 'post',
      url: '/some/url',
      data: { prop: true },
      headers: {
        'content-type': 'raw'
      }
    });

**Comment by raygesualdo** [comment]
What type of "raw" data are you trying to send? Text? A blob? A file?

**Comment by Jvaeyhcd** [comment]
@raygesualdo I'm trying to send Text type of "raw"

**Comment by Axnyff** [comment]
@Jvaeyhcd Doesn't my example work or am I missing something? You just want to change the header, don't you?

**Comment by Khaledgarbaya** [comment]
this issue will be closed due to inactivity, feel free to create a new one if you have any questions
