### ISSUE TITLE
axios dont accept null as a valid response, should it?

### ISSUE THREAD

**Issue by fractalf** [axios/axios#1278]
According to these
https://stackoverflow.com/questions/8526995/is-null-valid-json-4-bytes-nothing-else
https://tools.ietf.org/html/rfc7159

`null` is valid json so I was surprised to see axios throwing an error when I consciously returned just that.

To me it makes sense to have a resource returning `null`, meaning *"your request was accepted and handled, but we found nothing"*. One alternative is making a "dummy" object ala `{"status":"found"}` and `{"status":"not found"}` which to me just seems like bloat.

You can argue that returning an empty object/array like `{}` or `[]` would solve it, and to a certain degree I agree, but then to check if you receive an answer you would have to check for an empty object, which is not trivial compared to `if (res === null)`. So I still dont see why axios can't accept `null` as a valid response and not an actual *error*. 

Please enlighten me as to why this is not a good idea?
Thanks :)

**Comment by Axnyff** [comment]
It seems to work for me. I have created a simple file with just null in it and then 

    axios.get("http://localhost:3000/foo").then(r => console.log(r.data)); // null

What code is not working for you?

**Comment by montogeek** [comment]
@fractalf Could you please provide a reproducible case?

**Comment by fractalf** [comment]
Sorry for the late reply, I will double check this tomorrow at work. Relieved to hear that it shouldn't be like that. Hopefully I cannot reproduce and find I have a bug somewhere.
