### ISSUE TITLE
In Postman it works, but through axios it throws "unsupported_grant_type"

### ISSUE THREAD

**Issue by srganeshram** [axios/axios#1281]
#### Summary

I am using WEB API Server to get the access token,

Below is my postman call preview.
URL: http://localhost:2002/token
Header: [{"key":"Content-Type","value":"application/x-www-form-urlencoded","description":"","enabled":true}]

In Postman it works perfectly, but through axios it shows "unsupported_grant_type"

#### Preview
![image](https://user-images.githubusercontent.com/4484548/34756395-8fa33068-f5f0-11e7-9f95-cef8fee86a01.png)

#### Axios sample function:

```javascript
function HeaderPostAction(){
  // Send a POST request
  axios({
    method: 'post',
    url: 'http://localhost:2002/token',
    data: {
      "username": "admin",
      "password": "admin123",
      "grant_type": "password"
    },
    headers: { 
      "Content-Type": "application/x-www-form-urlencoded",
      "Cache-Control": "no-cache",
      "Postman-Token": "42e6c291-9a09-c29f-f28f-11872e2490a5"
    }
  }).then(function (response) {
    console.log("Heade With Authentication :" + response);
  })
  .catch(function (error) {
    console.log("Post Error : " +error);
  });
}
```

#### Chrome Browser Developer message
![image](https://user-images.githubusercontent.com/4484548/34756485-33de77fa-f5f1-11e7-9cf7-26a75b79d7c3.png)

![image](https://user-images.githubusercontent.com/4484548/34756497-4bb4afac-f5f1-11e7-9bc4-6050455ac542.png)

#### Error Response
![image](https://user-images.githubusercontent.com/4484548/34756512-5af3c6f6-f5f1-11e7-96b1-29ba0959ab07.png)

Please help me to resolve the issue, or what went wrong.

#### Axios Environment

- axios version: *v0.17.1*
- Environment: *chrome 62, windows 7*

**Comment by Axnyff** [comment]
Hello,
You're using grant_type password in postman but grant_type admin in your axios call, is that normal?

**Comment by srganeshram** [comment]
@Axnyff for testing I have included that, but I changed to "grant_type": "password" still the same issue.

**Comment by Axnyff** [comment]
Is this a cross domain request? If so you might need to add `withCredentials: true` to your options.

**Comment by montogeek** [comment]
Your server does not accept cross domain requests, you have to activate it

**Comment by srganeshram** [comment]
Yes right, I am accessing cross domain request, from localhost:2001 to localhost:2002. I tried with 
but still facing the same issue.

```javascript
function HeaderPostAction(){
  // Send a POST request
  axios({
    method: 'post',
    url: 'http://localhost:2002/token',
    **withCredentials: true,**
    data: {
      "username": "admin",
      "password": "admin123",
      "grant_type": "admin"
    },
    headers: { 
      "Content-Type": "application/x-www-form-urlencoded",
      "Cache-Control": "no-cache",
      "Postman-Token": "42e6c291-9a09-c29f-f28f-11872e2490a5"
    }
  }).then(function (response) {
    console.log("Heade With Authentication :" + response);
  })
  .catch(function (error) {
    console.log("Post Error : " +error);
  });
}
```

**Comment by srganeshram** [comment]
Ok,

I have provided the full code from Jquery as well as Axios, also provided both response from chrome.

Jquery call is success and provided token but Axios returns bad request, please let me know what is the issue on configuration settings of Axios.

JQuery Function:
```javascript
var settings = {
            "async": true,
            "crossDomain": true,
            "url": "http://localhost:54368/token",
            "method": "POST",
            "headers": {
                "Content-Type": "application/x-www-form-urlencoded",
                "Cache-Control": "no-cache"
            },
            "data": {
                "username": "ganesh",
                "password": "123456",
                "grant_type": "password"
            }
        };

        $.ajax(settings).done(function (response) {
            console.log(response);
        });
```

#### Jquery Response
![image](https://user-images.githubusercontent.com/4484548/34863322-d73b7f98-f794-11e7-83f3-30ae7702e628.png)

Axios Function:
```javascript
function HeaderPostAction(){
  // Send a POST request
  axios({
    method: 'post', 
    url: 'http://localhost:54368/token',
    withCredentials: true,
    data: {
      "username": "admin",
      "password": "123456",
      "grant_type": "password"
    },
    headers: { 
      "Content-Type": "application/x-www-form-urlencoded",
      "Cache-Control": "no-cache"
    }
  }).then(function (response) {
    console.log("Heade With Authentication :" + response);
  })
  .catch(function (error) {
    console.log("Post Error : " +error);
  }); 
}
```


#### Axios Response:

![image](https://user-images.githubusercontent.com/4484548/34863357-0d6371f2-f795-11e7-8f65-b8fe68937157.png)


Please let me know

**Comment by srganeshram** [comment]
Hi Guys,
Found what is the issue, axois by default it does not converts data to query string, but Jquery by default it converts to query string. Hence I just changed my previous  function with $.parse(data), and it worked.

#### Working code
```javascript
function HeaderPostAction(){
  // Send a POST request
    var reqData = {
        "username": "admin",
        "password": "admin123",
        "grant_type": "password"
    };
    //var reqData = "username=ganesh&password=123456&grant_type=password";
    axios({
        method: 'post',
        url: 'http://localhost:49359/token',
        withCredentials: true,
        crossdomain: true,
        data: $.param (reqData),    
    headers: { 
      "Content-Type": "application/x-www-form-urlencoded",
      "Cache-Control": "no-cache",
      "Postman-Token": "42e6c291-9a09-c29f-f28f-11872e2490a5"
    }
  }).then(function (response) {
    console.log("Heade With Authentication :" + response);
  })
  .catch(function (error) {
    console.log("Post Error : " +error);
  }); 
}
```

**Comment by mahesh-vidhate** [comment]
@srganeshram  in -> data: $.param (reqData)
what is this $ stands for?
Do I have to import something for '$' ?
because I am getting an error as '$ is not defined'

**Comment by paddykontschak** [comment]
@mahesh-vidhate `$.param()` is a jQuery function.

You can use this instead:
```javascript
Object.keys(reqData).map(function(key) {
    return encodeURIComponent(key) + '=' + encodeURIComponent(reqData[key])
}).join('&')
```

That being said, I'm still in the middle of figuring out how to fix the whole issue in my project. I'll update if I find an answer. (if I don't, assume it was something trivial like a wrong variable or something...)

**Comment by pravin-d** [comment]
Wrt https://github.com/axios/axios/issues/1281#issuecomment-357255541
I was having the same issue. I had done all the withCredentials and cors on server changes suggested by all other post. However the one thing missing in the mix was {crossdomain : true }.
To help anyone coming here with axios issue let me summerize

1) Axios - axios({withCredentials : true, **crossdomain : true**,  .. other options .. })
2) Server (in case running on express) -- app.use(cors({credentials : true, origin : ['your domain where axios is running']}))

**Comment by Prateekjaiiho** [comment]
i faced the same issue because i didnot pass all the required field data..checking the network in chrome fixed the issue for me

**Comment by TicoGitHubII** [comment]
Also read you use  JWT JSON Web Token lib or something

**Comment by mordeccai** [comment]
> Wrt [#1281 (comment)](https://github.com/axios/axios/issues/1281#issuecomment-357255541)
> I was having the same issue. I had done all the withCredentials and cors on server changes suggested by all other post. However the one thing missing in the mix was {crossdomain : true }.
> To help anyone coming here with axios issue let me summerize
> 
> 1. Axios - axios({withCredentials : true, **crossdomain : true**,  .. other options .. })
> 2. Server (in case running on express) -- app.use(cors({credentials : true, origin : ['your domain where axios is running']}))

I finnaly got mine working. Thanks a ton

**Comment by anupammaurya** [comment]
no luck found! facing the same issue here.. 

After flight call 204, nothing returns from the server...

**Comment by zhanggaolei001** [comment]
> Hi Guys,
> Found what is the issue, axois by default it does not converts data to query string, but Jquery by default it converts to query string. Hence I just changed my previous function with $.parse(data), and it worked.
> 
> #### Working code
> ```js
> function HeaderPostAction(){
>   // Send a POST request
>     var reqData = {
>         "username": "admin",
>         "password": "admin123",
>         "grant_type": "password"
>     };
>     //var reqData = "username=ganesh&password=123456&grant_type=password";
>     axios({
>         method: 'post',
>         url: 'http://localhost:49359/token',
>         withCredentials: true,
>         crossdomain: true,
>         data: $.param (reqData),    
>     headers: { 
>       "Content-Type": "application/x-www-form-urlencoded",
>       "Cache-Control": "no-cache",
>       "Postman-Token": "42e6c291-9a09-c29f-f28f-11872e2490a5"
>     }
>   }).then(function (response) {
>     console.log("Heade With Authentication :" + response);
>   })
>   .catch(function (error) {
>     console.log("Post Error : " +error);
>   }); 
> }
> ```

It works for me~Thanks！
