### ISSUE TITLE
Axios does not use the headers that I inputted

### ISSUE THREAD

**Issue by gabrielchase** [axios/axios#1282]
I am facing a very tricky problem and I've been working at it for days.

It's a problem in a react-redux application and I'm using axios to make API calls, the server is written in Django Rest Framework. Essentially, axios is not using the headers I'm passing into it and uses a past headers instead. I explain it with screenshots and comments here: https://imgur.com/a/fB4CY

These are the steps I take:

1. I login using redux-form to the my Django API which returns a JWT. I then store this JWT using `localStorage.setItem('jwt_token', res.data.token)` in my authLogin action.

        async onSubmit(values) {
            await console.log('Submitting values to Login')
            await this.props.authLogin(values)
        
             await console.log('Login done, pushing to /activities')
             await this.props.history.push('/activities')
        }

       export async function authLogin(values) {
           const res = await axios.post(`${ROOT_URL}/login/`, values)
    
           console.log('axios login post response: ', res.data)
    
           await localStorage.setItem('user_id', res.data.user_id)
           await localStorage.setItem('jwt_token', res.data.token)
    
           console.log(`set user_id in localStorage: ${localStorage.getItem('user_id')}`)
           console.log(`set jwt_token in localStorage: ${localStorage.getItem('jwt_token')}`)

           return {
               type: AUTH_LOGIN,
               payload: res
           }
        }

2. After retrieving the JWT, I use `history.push('/activities')` which then triggers a `this.props.fetchUser()` action in `componentDidMount()`. This is all in the ActivityIndex component.

        class ActivityIndex extends Component {
            async componentDidMount() {
                 console.log('ActivityIndex mounted')
                 await this.props.fetchUser()
                 await this.props.fetchActivities()
           }
           ...
        }

3. In this `fetchUser` action, I do `localStorage.getItem('jwt_token')` and pass that to my `getHeaders` which returns `{ headers: { Authorization: `JWT ${jwt_token}`} }` . The localStorage.getItem() returns the correct and new JWT which I got from the Django server.

        export async function fetchUser() {
             console.log('in action fetchUser')
    
             let user_id = localStorage.getItem('user_id')
             let jwt_token = localStorage.getItem('jwt_token')

             console.log(`user_id: ${user_id}`)
             console.log(`jwt_token: ${jwt_token}`)

             let headers = getHeaders(jwt_token)

             console.log(`Headers to axios.get /users/${user_id}: `, headers)
     
             const res = await axios.get(`${ROOT_URL}/users/${user_id}/`, headers)

             console.log(`Result of axios.get /users/${user_id}: `, res)

             return {
                 type: FETCH_USER,
                 payload: res
             }
         }

4. The fetchUser goes into the reducer and then gives me a 403. I check the network requests and see the request headers, it's using a previous jwt and not the one I've set.
![screen shot 2018-01-11 at 1 01 05 am](https://user-images.githubusercontent.com/19620289/34786337-dadac554-f66e-11e7-8c0c-cde7f3108088.png)
![screen shot 2018-01-11 at 1 01 15 am](https://user-images.githubusercontent.com/19620289/34786343-dd65b572-f66e-11e7-8c68-0590f002e5f9.png)

5. I then copy and paste the new JWT into the Django interface and mock a request there, it will give me status code 200 and show the correct info.

![screen shot 2018-01-11 at 1 01 41 am](https://user-images.githubusercontent.com/19620289/34786349-e2f096d8-f66e-11e7-8bc6-10febb569792.png)

6. I then refresh in my react-redux app and the API request calls are fine. As you can see it shows the correct data (oldest first), the response status is 200, the headers are correct.

![screen shot 2018-01-11 at 1 16 47 am](https://user-images.githubusercontent.com/19620289/34786356-eb84ddc2-f66e-11e7-9845-732cef36e17b.png)

You can also check my imgur post here: https://imgur.com/a/fB4CY

**Comment by Axnyff** [comment]
Hello,
Do you have a way to recreate the problem in a couple of lines? It's hard to see where it could come from with so much code?

Also, there is some code missing: what is the code of getHeaders for instance? It seems to return a wring authorization key? Why is it Bearer instead of JWT in the token?

**Comment by JustinBeckwith** [comment]
Greetings!  It's been a while since we heard anything from you.  If you're still running into any issues... please let us know and we'll re-open this!
