### ISSUE TITLE
Axios avoid triggering .then on success?

### ISSUE THREAD

**Issue by cloudbluedigital** [axios/axios#1283]
Hi Guys,

So I have a code like this

```
    onSubmit() {
      var alert = new Global;
      this.form.post(this.hostname + 'auth/login')
        .then(response =>
          this.username = response.name,
          this.sucess = !this.sucess
        )
        .catch(error =>
          this.failure = !this.failure, console.log('hello'),
        )
      alert.alerts();
    }
```

Now what happens is this:

When I send the post, first of all OPTIONS request is being send and returns 200, straight away my .then function triggers. It then sends a POST request which fails and .catch is being triggered. The problem is I then get 2 alerts:

```
      <div v-if="this.sucess" class="alert alert-success" role="alert">
        <strong>Welcome back {{ username }}!</strong> You will be redirected to main page shortly.
      </div>
      <div v-if="this.failure" class="alert alert-danger" role="alert">
        <strong>Oh No!</strong> seems like this user does not exist.
      </div>
```

Because at first options request it was successful therefore it triggered success alert, and 2nd request failed so it triggered failure alert. Is there a way to stop triggering/avoid any output from options request?

**Comment by Axnyff** [comment]
Hello,
Is this normal that you're calling alert.alerts() before the requests has been finished? What is it doing, are you sure it's not link to this?

Anyway, do you have a way to recreate the issue that can be tested by other users?

**Comment by jongrim** [comment]
I'm not sure this is an Axios issue. When making a POST request with CORS, an OPTIONS request is required first as explained [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS). Axios  handles this fine, as can be seen by this [code example](https://codesandbox.io/s/lyo5ykp3m9). It seems likely you're issue is elsewhere.

**Comment by deltaepsilon** [comment]
I'd suggest running an OPTIONS request first and then calling your POST.

I'm closing this to keep the issues queue clean. Let me know if you disagree and we can hash it out in more detail.
