### ISSUE TITLE
Axios should set maxBodyLength on follow-redirects to match maxContentLength

### ISSUE THREAD

**Issue by mividtim** [axios/axios#1286]
#### Summary

`follow-redirects` defaults to a `maxBodyLength` of 10mb.  `axios` does not override this default, even when the config specifies a `maxContentLength` parameter greater than 10mb, thus capping `axios` at a maximum content length of 10mb no matter what is configured, and returning an error that does not make it obvious that `follow-redirects` is the cause.

`axios` should set the `maxBodyLength` option sent to `follow-redirects` to match the `maxContentLength` config property set on the `AxiosOptions` object.

#### Context

- axios version: *v0.17.1*
- Environment: *Electron v1.4.3 or Node v6.5.0 with XHR polyfill, macOS v10.13.2*

#### Status

Pull request: https://github.com/axios/axios/pull/1287

**Comment by chenchengwork** [comment]
same problem

**Comment by mividtim** [comment]
PR: https://github.com/axios/axios/pull/1287

**Comment by mividtim** [comment]
@chenchengwork The PR was merged, in case you care enough to use the Github version of axios - or, I guess, wait for the next release.
