### ISSUE TITLE
HTTPS Connection reuse

### ISSUE THREAD

**Issue by tspecht** [axios/axios#1288]
Hey!

I'm currently trying to make sure that apisauce and axios reuse once opened HTTPS connections to an external API I'm using to make sure that the SSL handshake is only done once per connection and not on every request.

Any idea on how to achieve this? Tried looking for keep-alive and similar in the documentation + code but couldn't find anything ...

**Comment by yoshigev** [comment]
Just came across this question, and possibly found the answer. One of config options of axios is httpsAgent (see https://github.com/axios/axios#request-config).
You can use it like:
```javascript
var https = require('https');
var httpAgent = new https.Agent({ keepAlive: true });
var r = await axios({
            method: 'post',
            httpsAgent: httpsAgent
            ...
           });

**Comment by chinesedfan** [comment]
Close due to stale.
