### ISSUE TITLE
Support header composition

### ISSUE THREAD

**Issue by betalb** [axios/axios#1292]
It will be helpful to support array syntax for header name in xhr adapter. This is currently a feature only for nodejs adapter, which accepts array as header value and does composition.

For xhr adapter this behaviour can be implemented pretty easy too, by calling `setRequestHeader` multiple times.

I would like to raise PR for this, but changes will conflict with https://github.com/axios/axios/pull/1291, so postponing this change until resolution is made on linked PR

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks
