### ISSUE TITLE
Expose Util and Default methods from the Axios module

### ISSUE THREAD

**Issue by darren128** [axios/axios#1298]
#### Feature Request

Would exposing the utils and default method as separate utilities ever be considered?

#### Context

We are using Axios for our http requests, but we are also implementing request batching where a single request will be processed by Axios, but in the request body there is an array of request items. Each request item that has body content needs to be appropriately processed (JSON.stringify, etc) and base64 encoded. The transformRequest basically does the processing work for us, and we could then just base64 encode the result of that call.

**Comment by darren128** [comment]
If there is consensus, I'll submit a PR.

**Comment by chinesedfan** [comment]
They are internal implementations, which may be changed in anytime. We recommend users to import utils from lodash, and don't rely on the default transformRequest to do other things.
