### ISSUE TITLE
axios's response is undefined ONLY WHEN minified by webpack

### ISSUE THREAD

**Issue by Liooo** [axios/axios#1299]
#### Summary
My app works fine normally, but when minified with `webpack -p` option, suddenly the axios response goes empty. The gist of code is simply something like 

    axios.get(url).then((response) => {console.log(response)}

 and the `response` becomes undefined. Couple things I confirmed:

 - I can see in the Network tab that the request is complete and response body is returned correctly from server

 - when attaching `axios` object on window and then send exactly the same request from the console, the `response` is passed correctly.

How could this be?

#### Context
  
- axios version: 0.17.1
- Environment: node v8.6.0

**Comment by Axnyff** [comment]
Hello,
Would you be able to provide a reproduction of the bug?
It seems weird to me that minifiying the javascript would cause the bug but the -p flag of webpack does a lot of stuff so it might be something else.

What webpack version are you using?
Are you comparing a production build to a non-production build or to webpack-dev-server, this might change things also if you have a dev specific settings.

**Comment by deltaepsilon** [comment]
This is unlikely to be an Axios problem, and we haven't had a good reproduction.

Go ahead and re-open if you can reproduce it well.
