### ISSUE TITLE
Cannot stringify error object due to circular references.

### ISSUE THREAD

**Issue by jaredsinclair** [axios/axios#1301]
#### Summary

One cannot stringify a caught error object due to circular references.

#### Steps to Reproduce

1. Make a simple request that you know will fail.
2. `.catch(err => {...})` the error.
3. Try either `JSON.stringify(err)` or `JSON.stringify(err.response)`. Both will fail due to circular references.

#### Context

- axios version: 0.17.0
- Environment: Node.js 8.4, macOS 10.12.6

**Comment by deltaepsilon** [comment]
Consider using something like [circular-json](https://www.npmjs.com/package/circular-json) to serialize that kind of error... or just serialize the part of the error that you care about.

This sort of circular JSON issue is super common in JavaScript and I wouldn't consider it to be a problem with Axios.
