### ISSUE TITLE
Explicit code for timeout

### ISSUE THREAD

**Issue by djensenIncomm** [axios/axios#1302]
When a timeout is specified e.g. **timeout: 5000**, there's not a good way to know if failure was caused by the timeout or something else (such as 400, 401, etc.).   When failure is caused by a 400-type error, it is easy to know this by checking  **error.response.status**.  But when failure is caused by timeout, the response object is undefined. The only clue is by checking the "message" attribute which will say something like "**timout of 5000 ms exceeded**", and also the "code" attribute will say "**ECONNABORTED**".  But neither of these are good solutions.

This makes the code messy.  Below is an example of how **timeout** throws a monkey-wrench in code:

	.catch(function(error) {
		if(error.response) { // Because the "response" might be undefined, we need to guard.
			switch(error.response.status) {
			case 400:
				handle400();
				break;
			case 401:
				handle401();
				break;
			case 404:
				handle404();
				break;
			default:
				handleGenericError();
			}
		}
		else {
			if(error.message.indexOf("timeout") >= 0) {
				handleTimeout();
			}
			else {
				// do something
			}
		}
	});
`
The above "else" block should not be needed at all.
In AngularJS, the $http error response will contain a status less than zero when timeout occurs; this is very convenient.

Can we get an explicit code for timeout?
Thanks.

**Comment by mzabriskie** [comment]
I would be okay with a PR that adds support for this, but it would need to be backwards compatible.

**Comment by alonisser** [comment]
What would you consider backwards compatible? Can you refine that please before I try to write a PR
What about a specific "TimeoutError" type we can check?

**Comment by GuiRitter** [comment]
For me, `error` is undefined, so I can't even know if it's a timeout.
