### ISSUE TITLE
Error ENOENT accessing localhost APIs when network is unplugged 

### ISSUE THREAD

**Issue by mocsharp** [axios/axios#1306]
#### Summary
We're using Axios in nodejs with simple GET/POST API calls.  It works really well.  However, when ever we unplug the network cable, we get the ENOENT error.
Anyway to work with Axios without a network connection?

Note: we are calling a API hosted locally via localhost:12345.

#### Context

- axios version: 0.17.0
- Environment: node 6.11.5

**Comment by deltaepsilon** [comment]
Axios just makes HTTP calls. It can't help with LAN problems.

I'd look for where your API server is trying to call out of your machine. It's likely that your local environment connects to itself just fine but is throwing the error when trying to reach outside of itself.
