### ISSUE TITLE
怎么启动下载的这个文件

### ISSUE THREAD

**Issue by xuwenlongge** [axios/axios#1308]
先 npm install  
然后再 npm install axios  --save 
再 npm run dev   却报错missing script: dev      
我启动这个文件,操作错在哪儿了呢?  求大神指点一下,正确的文件启动的操作方式.

**Comment by montogeek** [comment]
`dev` script should be defined in your `package.json`, like this:
```
"scrips": {
   "dev": "......"
}
```
