### ISSUE TITLE
Failed to load http://js.filatov-nikita.ru/api/products.php: Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by Filatov-Nikita** [axios/axios#1309]
I use laravel and vue with axios for sending request. And i get this error Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers in preflight response. import Axios from 'axios';
Vue.prototype.$http = Axios.create({
    baseURL: 'http://js.filatov-nikita.ru/api/',
    crossDomain:true,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    }
});

**Comment by nickuraltsev** [comment]
Your back-end needs to support CORS. Please see this for details: https://www.html5rocks.com/en/tutorials/cors/
