### ISSUE TITLE
onUploadProgress never fire in RN on Android

### ISSUE THREAD

**Issue by vvusts** [axios/axios#1312]
I tried a few version of rn and on android onUploadProgress is never fired:
example:
```
var axiosInstance = axios.create({
    baseURL: 'https://some-domain.com/api/',
    timeout: 1000,
    headers: {'X-Custom-Header': 'foobar', "Content-type": "application/json; charset=UTF-8"},
    
  });

  axiosInstance.post('https://jsonplaceholder.typicode.com/posts', JSON.stringify({
    title: 'test',
    body: 'test',
    userId: 1
  }), {
    onUploadProgress: function (progressEvent) {
        console.log(Math.floor((progressEvent.loaded * 100) / progressEvent.total));
      }
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
```
On IOS progress fire normally but on android no.
Any idea how this can be fixed?

**Comment by emilyemorehouse** [comment]
@vvusts are you still having this issue, or did you find a solution?

**Comment by vvusts** [comment]
@emilyemorehouse yes I still have this issue. On android progress never fire. I am waiting RN 0.53 because of this https://github.com/facebook/react-native/pull/17312#pullrequestreview-92002633
Maybe this will solve my issue.

**Comment by Boaz-Compie** [comment]
@emilyemorehouse I've also encountered this issue. I'm creating an axios get request on android (react-native) with onDownloadProgress and the progress never fires.

any idea how they can be triggered

**Comment by Marcholio** [comment]
@vvusts RN is at 0.58.4 now, can you check if the issue has been solved?

**Comment by chinesedfan** [comment]
Closed due to https://github.com/facebook/react-native/pull/17312 has been merged.
