### ISSUE TITLE
what does 'common' mean in interceptors?

### ISSUE THREAD

**Issue by lynnic26** [axios/axios#1313]
I need to add custom field in all request header, like this
`config.headers.common['X-CUSTOM'] = 'xxxx'`
when I remove **common**, the code also works fine
so I‘m confused what does **common** mean in here

**Comment by mzabriskie** [comment]
`common` means that it will be sent regardless the request method. As opposed to `config.headers.get['X-CUSTOM']` would only be sent when the request method is `GET`.
