### ISSUE TITLE
Response is undefined on network failure?

### ISSUE THREAD

**Issue by aprilmintacpineda** [axios/axios#1315]
Please see https://github.com/facebook/react-native/issues/10404#issuecomment-359723328

Will it be possible to get more feedback when there is a network error? I'm using it with `redux-saga` when I console log the exception I only get `Error: network error` but I want to find out what happened, i.e., is it because the server can't be reached? something wrong with the SSL certificates? Etcetera.

- axios version: 0.17.1
- Environment: react-native@0.52.0

**Comment by robaxelsen** [comment]
Hi @aprilmintacpineda. This doesn't fall under the scope of axios to handle. For troubleshooting the error message I would suggest StackOverflow or similar. Good luck!
