### ISSUE TITLE
Post method ignores params

### ISSUE THREAD

**Issue by alessandrotesoro** [axios/axios#1316]
#### Summary

Hi there,

I've tried searching but couldn't find an example like mine. I'm sending a post request like this

```
axios.post( ajaxurl , {
        params: {
          action: 'am_send_test'
        },
        data: {
          email: this.email,
          post_id: this.selectedPostID
        }
      })
      .then(response => {
        console.log(response)
      })
      .catch(e => {
        this.error = true;
})
```

The issue is that "params" is being ignored and the url remains untouched. However if I do a "get" request it works fine and the url is properly adjusted. Any reason behind this? Or is my code wrong?

In my case I would have to remove "ajaxurl" and replace it with 

`ajaxurl + '?action=' + 'am_send_test'` but I assumed params would work anyways.

#### Context

- axios version: *0.17.1*
- Environment: *vuejs v2.5.2, Firefox 59.0b2, macOs Sierra*

**Comment by Axnyff** [comment]
It looks like you are not using axios.post correctly: the signature is

    axios.post(url[, data[, config]])

So you are sending your whole object as a payload.

This should work:

axios.post( ajaxurl ,
{
          email: this.email,
          post_id: this.selectedPostID
        },
 {
        params: {
          action: 'am_send_test'
        },
      })
      .then(response => {
        console.log(response)
      })
      .catch(e => {
        this.error = true;
})
