### ISSUE TITLE
validateStatus doesn't work with auth

### ISSUE THREAD

**Issue by jezikk** [axios/axios#1318]
Following is my code
```
try {
        const resToken = await axios({
            method: 'post',
            url: api.loginToken(),
            validateStatus: function(status) {
                return status < 500;
            },
            auth: {
                username: option.username,
                password: option.password
            }
        });
    } catch (error) {
        // some code here
    }
```

Even though the `validateStatus` is set to `< 500`, the following exception is called:
```
POST http://localhost:8000/api/login/token 404 (Not Found)
```

Can you help me please? Is this a bug or am I doing something wrong?

**Comment by robaxelsen** [comment]
Thanks for posting your issue @jezikk!

The validateStatus config does not do anything else than simply check the status code, so this is not a bug with axios. I would have a look at the API endpoint itself, and troubleshoot there. Do you get the expected result with curl/postman/browser?

**Comment by jezikk** [comment]
Thanks for respond.

```
// `validateStatus` defines whether to resolve or reject the promise for a given
  // HTTP response status code. If `validateStatus` returns `true` (or is set to `null`
  // or `undefined`), the promise will be resolved; otherwise, the promise will be
  // rejected.
  validateStatus: function (status) {
    return status >= 200 && status < 300; // default
  },
```

According to the documetation above, the `validateStatus` function has to prevent rejection If `validateStatus` returns `true` (or is set to `null` or `undefined`). In my example I set the condition to `< 500` and despite that the exception is still called. Is that correct?

**Comment by robaxelsen** [comment]
Have you verified that your request works as expected, with curl/API-client/browser?

I am not too familiar with async/await (just promises), I am afraid. But what are you expecting to happen after validateStatus prevents rejection?

I'll reopen this issue for visibility, in the hopes that someone else can offer some help solving your issue.

**Comment by jezikk** [comment]
Yes, api works as expected.

> I am not too familiar with async/await (just promises), I am afraid. But what are you expecting to happen after validateStatus prevents rejection?

-- Exactly, this is what I need and it should be consistent with the documentation too.

**Comment by jezikk** [comment]
Based on my testing, the 'validateStatus' function is called after rejection of promise.

**Comment by Axnyff** [comment]
I've done this:

try {
  a = await axios({
    method: 'post',
    url: '/',
    validateStatus: function(status) {
      return true;
    },
  })
  console.log(a);
} catch(e) {
  console.log('fail');
}

And it seems to work properly ( I'm using a simple http.server in python so this returns a 501).
It console logs fail if I remove the validateStatus method. Could this be linked to auth?

**Comment by jezikk** [comment]
@Axnyff Yes, it works. You need to use `auth` option as you mentioned.

**Comment by Axnyff** [comment]
Oh sorry, I read your post too fast.
It still seems to work with auth though.

I get an error logged to the console but my code never goes to the catch part because of the validateStatus

**Comment by ekaitzht** [comment]
@jezikk  did you figure out your problem? It's happening to me the same issue. And with integration tests is working but not when I deploy to staging.
