### ISSUE TITLE
please add headers["X-Requested-With"] = "XMLHttpRequest" as default value

### ISSUE THREAD

**Issue by yuanzhangliu** [axios/axios#1322]
hi~

in my opinion, axios is ajax library, 
I suggest you should add default head value,(headers["X-Requested-With"] = "XMLHttpRequest") just like jq;

because backend  developer need this flag to distinguish ajax request from request,

in order to do some different request handling; such as error handling;

if there is an ajax request error happening ,we will return  json (including error message)
if there is a http request error happening,we may redirect to other page or others

in some team,some people use jq,some people use axios,.......

so I suggest ......

**Comment by deltaepsilon** [comment]
You can set default headers for Axios on your browser:

https://github.com/axios/axios#custom-instance-defaults

This will accomplish your goal without modifying Axios.

**Comment by yuanzhangliu** [comment]
thanks, ok~

**Comment by davejamesmiller** [comment]
For easy reference:

```js
axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

**Comment by broofa** [comment]
Note that adding the `X-Requested-With` header makes the request "unsafe" (as defined by CORS), and will trigger a preflight request, which may not be desirable.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests for more

**Comment by dorward** [comment]
It *shouldn't* be useful to distinguish between requests made by Ajax and other kinds of request. Pretty much any usecase where you'd want to do that is better served by using the `Accept` header to ask for data in a specific format.
