### ISSUE TITLE
axios post not working with single string param

### ISSUE THREAD

**Issue by ahsanparacha02** [axios/axios#1327]
this is post call where i can post single string param
      
        [HttpPost]
        [Route("joingroup")]
        [ValidateModel]
        public IActionResult JoinGroup([FromBody]string pincode)
        {
            Result result;
            try
            {
                if (string.IsNullOrWhiteSpace(pincode))
                {
                    return Json(new FailedResult(string.Format(Messages.UsersInGroupErrorMessagePincode)));
                }

                var apiModel = _groupService.GetGroupByPincode(pincode);
                if (apiModel != null)
                {
                    var signedInUserId = _userManager.UserId();

                    // this call overwrites the user Id if it exists
                    var addUserToGroupResult = _groupService.AddUserToGroup
                    (
                        new UsersInGroupApiModel
                        {
                            GroupId = apiModel.GroupId,
                            UserId = signedInUserId.GetValueOrDefault(),
                            CharacterId = default(int),
                            IsAdmin = false
                        }
                    );

                    if (addUserToGroupResult)
                    {
                        result = new SuccessResult(string.Format(Messages.UsersInGroupMessage));
                    }
                    else
                    {
                        result = new FailedResult(string.Format(Messages.UsersInGroupExistsErrorMessage));
                    }
                }
                else
                {
                    result = new FailedResult(string.Format(Messages.UsersInGroupErrorMessagePincode));
                }
            }
            catch (Exception ex)
            {
                result = new FailedResult(string.Format(Messages.ErrorMessage, ex.Message));
            }
            return Json(result);
        }

and this is client side call where i send pincode in axios body,but get 422 status code not understand why ?

        export const joinGroup = (code, navigation) => (dispatch) => {
           dispatch({ type: CCJOINCAMPAIGN_LOADING });
            //without querystring post call is not working with data send in body
            axios.post(`${ROOT_URL}${REST_APIs.CreateGroup.JoinGroup}`, { code }).then(response => {
            try {
             const baseModel = response.data;
             if (baseModel.success) {
                dispatch({ type: CCJOINCAMPAIGN_SUCCCESS, payload: baseModel.message });
                navigation.navigate('Campaign');
             } else {
                dispatch({ type: CCJOINCAMPAIGN_FAILURE, payload: baseModel.message });
             }
         } catch (e) {
            dispatch({ type: CCJOINCAMPAIGN_FAILURE, payload: e.message });
        }
         }).catch((e) => {
          dispatch({ type: CCJOINCAMPAIGN_FAILURE, payload: serverError });
     });
    };

**Comment by naxir** [comment]
Axios Version?

**Comment by ahsanparacha02** [comment]
i have test on v 0.17.1 and 0.16.2 but not worked

**Comment by naxir** [comment]
Hey @ahsanparacha02 
Basically  client uses the **application/x-www-form-urlencoded**  by default on the other hand axios uses **application/json by default**

So if you want to make **application/x-www-form-urlencoded** with axios
Then follow below steps 
Steps
1) First install  i.e **npm install querystring** 
2)& here post axios call
    axios.post(REST_API_TEST.Create,querystring({code:123}))

[HttpPost("TestCall")]
public async Task<ObjectResult> TestCall(string code)
{
     try
        {
          return Success("Axios Post Call String Data")
        }
      cath(Exception ex)
       {
          return Fail(ex.Messeage);
       }
}

Cheers
    Happy Coding

**Comment by naxir** [comment]
Basically stringclient uses the application/x-www-form-urlencoded by default on the other hand axios uses application/json by default

So if you want to make application/x-www-form-urlencoded with axios
Then follow below steps
Steps

First install i.e npm install querystring
2)& here post axios call
axios.post(REST_API_TEST.Create,querystring({code:123}))
```
[HttpPost("TestCall")]
public async Task <ObjectResult> TestCall(string code)
{
 try
  {
     return Success("Axios Post Call String Data")
  }
catch(Exception ex)
  {
     return Fail(ex.Messeage);
  }
}
```

Cheers
Happy Coding

**Comment by naxir** [comment]
Basically stringclient uses the application/x-www-form-urlencoded by default on the other hand axios uses application/json by default

So if you want to make application/x-www-form-urlencoded with axios
Then follow below steps
Steps

1)First install i.e npm install querystring
2)& here post axios call
axios.post(REST_API_TEST.Create,querystring({code:123}))

Here is example Code
```
[HttpPost("TestCall")]
public async Task <ObjectResult> TestCall(string code)
{
 try
  {
     return Success("Axios Post Call String Data")
  }
catch(Exception ex)
  {
     return Fail(ex.Messeage);
  }
}
```
Cheers
Happy Coding

**Comment by ahsanparacha02** [comment]
haha if i already use querystring which is working, then why i install new package for querystring ?

**Comment by naxir** [comment]
You cannot understand Leave the world and Rest In Peace Bye Bye

**Comment by naxir** [comment]
![test](https://user-images.githubusercontent.com/17848552/35721587-845ddda8-0814-11e8-80cf-d2a23f4e1cc3.png)

You cannot understand Leave the world and Rest In Peace Bye Bye

**Comment by Khaledgarbaya** [comment]
to use query string you need to pass an object to the `params` inside of the config object.
```
  axios.post(`${ROOT_URL}${REST_APIs.CreateGroup.JoinGroup}`, { params: { code } }).then(response => {

```
you can check how it is done in the documentation
