### ISSUE TITLE
Posting empty array

### ISSUE THREAD

**Issue by kailashjakhar** [axios/axios#1328]
Hi all,
I am trying to upload a excel file using axios and php. 
when I post a file with axios I getting empty post array at php side 
**my code**
```js          
            var formdata = new FormData();
            var filedata = document.getElementById('file-upload').files[0];
            formdata.append('paymentfile',filedata);
            const result = uploadFile(formdata);
            result.then(function(response){
            }


//my uploadFile function is like 
  
 const confi = {
        headers: { 'content-type': 'multipart/form-data' }
    }
    const url = "http://localhost/codeigniter/user/uploadExcel";
   return axios.post(url,data,confi); 

```

**Comment by naxir** [comment]
Hi
@kailashjakhar  Just try 

export const UploadFile = file => {
  var formData = new FormData();
  formData.append("file", file);

  return dispatch => {
    axios
      .post(REST_API.ImportExport.UploadFile, formData, {
        **headers: { "Content-Type": "application/octet-stream" }**
      })
      .then(response => {
        formData.delete("file");
        console.log(response);
        if (response.data.success) {
          customFn.success(response.data.message);
          dispatch({
            type: actionTypes.SHOW_BULK_SUCCESS,
            payload: "File Upload Successfully"
          });
          dispatch({
            type: actionTypes.LOADING_HIDE
          });
        } else {
          customFn.failure(response.data.message);
          dispatch({
            type: actionTypes.SHOW_BULK_ERROR,
            payload: response.data
          });
        }
      })
      .catch(error => {
        customFn.failure(error);
      });
  };
};

Hope it will help in your case

Cheers
Happy Coding

**Comment by naxir** [comment]
@kailashjakhar  Just Try this Hope it will help in your case 
```
export const UploadFile = file => {
  var formData = new FormData();
  formData.append("file", file);

  return dispatch => {
    axios
      .post(REST_API.ImportExport.UploadFile, formData, {
        **headers: { "Content-Type": "application/octet-stream" }**
      })
      .then(response => {
        formData.delete("file");
        console.log(response);
        if (response.data.success) {
          customFn.success(response.data.message);
          dispatch({
            type: actionTypes.SHOW_BULK_SUCCESS,
            payload: "File Upload Successfully"
          });
          dispatch({
            type: actionTypes.LOADING_HIDE
          });
        } else {
          customFn.failure(response.data.message);
          dispatch({
            type: actionTypes.SHOW_BULK_ERROR,
            payload: response.data
          });
        }
      })
      .catch(error => {
        customFn.failure(error);
      });
  };
};

```

Cheers 
Happy Coding

**Comment by kailashjakhar** [comment]
Thanks @naxir for your kind of response. But still i am getting Empty Array

**Comment by naxir** [comment]
Are you using default axios header ?

**Comment by kailashjakhar** [comment]
Yes

**Comment by naxir** [comment]
& have you tried Content-Type": "application/octet-stream in header?

**Comment by naxir** [comment]
@kailashjakhar can you  please take a look at how your requests look like in Chrome Dev Tools Network panel and provide a screenshot if possible?

**Comment by kailashjakhar** [comment]
yes, When i post some string with this file then i array with POSTED string but there is no info about posted file

**Comment by naxir** [comment]
@kailashjakhar is it possible if you take a screenshot to know  how your requests look like in Chrome Dev Tools Network pane

**Comment by kailashjakhar** [comment]
i am sharing my code schema 
 <input
                                        accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
                                        id="file-upload"
                                        name="filenm"
                                        type="file"
                                        onChange={(event) => this.hndlChange(event)}/>
 <div className="uploaddata" onClick={()=>this.uploadRecord()}>UPLOAD FILE</div>




when click on  upload btn

 uploadRecord()
    {
        if(this.state.fileSelected)
        {
            let that  = this;
            var formdata = new FormData();
            var filedata = document.getElementById('file-upload').files[0];
            formdata.append('filenm',filedata);
            const result = uploadFile(filedata);

            result.then(function(response){
                console.log(response.data);
                if(response.data.success)
                {
                      
                }
                else
                {       
                    alert('error
');                    
                    // that.NetworkError();                  
                }
               
            })
            .catch(function(error){
                alert('exception');
                
                // that.NetworkError();
            });

        }






my uploadFile is 

export function uploadFile(data)
{       
    const url = "someurl";
   return axios.post(url,data,{
    headers: { "Content-Type": "application/octet-stream" }
  }); 
}

**Comment by naxir** [comment]
@nickuraltsev  can you please help to @kailashjakhar  , what's going wrong

**Comment by Khaledgarbaya** [comment]
Did you try to pass the file object directly?

```
var filedata = document.getElementById('file-upload').files[0];
const result = uploadFile(filedata);
result.then(function(response) {}
//my uploadFile function is like 
 const confi = {
        headers: { 'content-type': 'multipart/form-data' }
    }
    const url = "http://localhost/codeigniter/user/uploadExcel";
   return axios.post(url,data,confi); 
```

**Comment by phanthehien** [comment]
hi @kailashjakhar, 
I got the same issue like you. 
But noticed that if I use `.request` instead of `.post`, it works for me.

    const fr = new FileReader();
    fr.readAsArrayBuffer(fileData);
    fr.onload = () => {
        const arrayBuffer = fr.result;
        const bytes = new Uint8Array(arrayBuffer);

        return axios.request({
          url: getUrl(uri),
          method: 'POST',
          headers: { 'Content-Type': 'application/octet-stream', },
          data: bytes
        })
      }

**Comment by kailashjakhar** [comment]
@phanthehien 
Thanks.
Actually axios was able to post image to my server but there I was making some mistake to read that Image.

**Comment by videni** [comment]
I also have this problem, I search a lot , almost read all related issues of this library, still  no effective solution found.
