### ISSUE TITLE
An instance doesn't seem to have CancelToken property

### ISSUE THREAD

**Issue by HamsterCoder** [axios/axios#1330]
#### An instance doesn't seem to have CancelToken property

Lately I needed to time some of the requests made by axios, so following the documentation I created and interceptor for an instance of axios (since I do not want to affect all axios requests, only specific ones):

```
var axios = require('axios').create(); // Create new instance of axios, to use interceptors safely

function setAxiosMeta(config, meta) {
    config.meta = config.meta || {};

    config.meta = Object.assign(config.meta, meta);
}

function getAxiosMeta(config) {
    config.meta = config.meta || {};

    return config.meta;
}

axios.interceptors.request.use(function (config) {
    setAxiosMeta(config, {
        requestStartTime: Date.now()
    });

    return config;
}, function (error) {
    return Promise.reject(error);
});

axios.interceptors.response.use(function (response) {
    var meta = getAxiosMeta(response.config);

    setAxiosMeta(response.config, {
        requestTime: Date.now() - meta.requestStartTime,
        requestId: response.headers['x-yt-request-id'],
        proxy: response.headers['x-yt-proxy']
    });

    return response;
}, function (error) {
    return Promise.reject(error);
});
```

We also use request cancellation:

```
var cancellation = axios.CancelToken.source();
```
And this line now throws and error:

```
Uncaught TypeError: Cannot read property 'source' of undefined
    at Object.core._createRequestWithCancellation (yt.js:826)
    ....
```

Is there a known workaround for creating Cancellation when working with and instance of axios? It isn't very clear what an instance is, at least after I encountered this behaviour. At first I thought that instance is the same as axios itself, but can be additionally configured.

#### Context

- axios version: *e.g.: v0.17.1*
- Environment: *e.g.: node v8.9.4, chrome 62, ubuntu Xenial*

**Comment by HamsterCoder** [comment]
I also found a simple way to reproduce this (Browser and Node):

```
var axiosPapa = require('axios');
var axios = axiosPapa.create();
console.log(Object.keys(axios));
```

outputs:

```
[ 'request',
  'delete',
  'get',
  'head',
  'options',
  'post',
  'put',
  'patch',
  'defaults',
  'interceptors' ]

```

Which seems to contradict this https://github.com/axios/axios/blob/d963368960e2e1b3ec6a2eb78ff8fd085e4e229c/test/specs/instance.spec.js#L10

And I tried to run this in a clean environment https://codepen.io/sirinity/pen/XZXMZW

**Comment by raphaelsoul** [comment]
same problem
```
const axios = require('axios')

const request = axios.create({
    // http://xxx.xxx.xxx/api
    baseURL: 'https://api.github.com',
    timeout: 15 * 1000,
    headers: {
        'Content-Type': 'application/json'
    }
})



request.interceptors.request.use(config => {
    //console.log(config)
    return config
})
request.interceptors.request.use(response => {
    //console.log(response)
}, err => {
    return Promise.reject(err)
})

request({
    url: '/user',
    method: 'get'
}).then(res => {
    console.log(res.data)
}).catch(err => {
    console.error(err)
})
```

**Comment by nickuraltsev** [comment]
Yeah, that is by design. There is no need to add all axios helper functions and classes like `CancelToken` to axios instances.

```js
const axios = require('axios');
const source = axios.CancelToken.source();
const instance = axios.create();
instance.get('/foo', { cancelToken: source.token });
```

**Comment by HamsterCoder** [comment]
1) So what is by design the right way to do cancellation for instances requests? The documentation has nothing to say about it, instances neither have the CancelToken, nor isCancel. Do you have to use both instances and axios itself? Or you simply don't use instances when you have cancellation?
2) Ok, then, what about the spec file that says otherwise? Or am I reading it wrong?

**Comment by jesusvpct** [comment]
I have a problem with new instance too. I'm doing:
`var CancelToken = axios.CancelToken;
    var source = CancelToken.source();

    var instance = axios.create({
        cancelToken: source.token
    });

    instance .post('/users')
        .then(function(response){
            console.log(response);
        }).catch(function(error){
            console.log(error);
    });
`
And I have this error:
`TypeError: Cannot read property 'cancelToken' of undefined
    at r (spread.js:25)
    at e.exports (spread.js:25)
    at <anonymous>`

Any help?

**Comment by dlahuta** [comment]
**Hey**
This may be related.

When I use middleware config, it starts throwing this error:

`Cannot read property 'cancelToken' of undefined`

When I remove middleware config, everything is working.

Middleware config is  also pretty simple:
```javascript
const axiosMiddlewareConfig = {
    interceptors: {
        request: [
            function ({ getState, dispatch, getSourceAction }, req) {
                var bearerToken = getState().account.bearerToken;
                if (bearerToken != null) {
                    req.headers['Authorization'] = 'Bearer ' + bearerToken
                }
            }
        ]
    }
};
```

**Comment by adrianbienias** [comment]
If you need to have cancelToken in instance (and probably also isCancel) just add them:

```
const instance = axios.create();
instance.CancelToken = axios.CancelToken;
instance.isCancel = axios.isCancel;
```

**Comment by dingziqi** [comment]
@dlahuta you did not return config in your  request interceptors, this is the reason of `Cannot read property 'cancelToken' of undefined`

**Comment by qiulang** [comment]
@dlahuta if I want to cancel this request what should I return ?

**Comment by waleedarshad** [comment]
@qiulang how did you cancel request?
