### ISSUE TITLE
Dynamic host in axios

### ISSUE THREAD

**Issue by krypton-code** [axios/axios#1331]
Hello everyone!
How I can doing dynamic host in axios?

Example:
```
      const host = location.hostname;
      // axios.defaults.baseURL = 'http://hastore.local';
      axios.defaults.baseURL = host;
      axios.defaults.port = 8080;
      axios.get('api/categories')
        .then((res) => {
          this.categories = res.data;
          console.log(res);
        })
        .catch((err) => {
          console.warn('error during http call', err);
        });
```
String `axios.defaults.baseURL = 'http://hastore.local';` does not fit, because on prodaction don't be work. 

String ` const host = location.hostname;` also not a solution, because I get incorrect port and dublicate host.

![image](https://user-images.githubusercontent.com/6662917/35751304-05751ace-0869-11e8-9202-f66fdae5f0e5.png)

The goal is to get the right host depending on the environment.
I read a lot of articles about this, but I did not find a solution.
Thanks for help!

- axios version: *e.g.: v0.16.2*
- Environment: *e.g.: node v8.9.4, chrome 64.0.3282.119, Ubuntu 16.04*

**Comment by cptrodgers** [comment]
`I get incorrect port and dublicate host.`. I think duplicate host because you using `api/categories`.
Try `/api/categories`
P/S: I recommend you using a proxy server like nginx, HaProxy for mapping request. Dymanic host will make some error you can't fix because have problem with browser policy (chrome, firefox,...)

**Comment by krypton-code** [comment]
**Solution!**
https://stackoverflow.com/questions/48597306/dynamic-host-in-axios/48598061#48598061
