### ISSUE TITLE
Request Minimum Time

### ISSUE THREAD

**Issue by alexbowers** [axios/axios#1332]
#### Summary

A way to specify the minimum amount of time before a request is complete.

I would like to request either documentation on how to do this, if currently possible, or for the feature to be implemented into core.

The use case for this is loading spinners. 

We want a loading spinner to show for a minimum of ~ 600ms to signify something is happening in the application, Currently a request takes ~ 200ms which is too short for a UI change to not look broken, but we cannot guarantee that it will always be that quick, so a loading spinner is necessary
Expected result: minimumTime: 1000 would say that a request that takes ~200ms will wait an additional ~800ms before response happens. A request that takes 1200ms will return immediately upon completing request.

**Comment by axe312ger** [comment]
IMHO this should be implemented into your application logic not into axios itself.

**Comment by alexbowers** [comment]
I don't think this is possible without a axios returning how long the request took, which I believe it does not currently do.

Happy for this to be userland, if we can get that information out of axios.

**Comment by axe312ger** [comment]
I am pretty sure you can do this via https://github.com/axios/axios#interceptors and by measuring yourself how long the promise took

**Comment by axe312ger** [comment]
Here is an issue where sth similar is trying to be achieved:
https://github.com/axios/axios/issues/695

**Comment by Khaledgarbaya** [comment]
This can be solved using interceptors:
1. You intercept the request and add `startTime` to the config
2. You intercept the response and check the time and delay the return, using `setTimeout` or [`Promise.delay`](http://bluebirdjs.com/docs/api/promise.delay.html)

I will close this issue, for now, feel free to create a new one if you have other questions

**Comment by testerez** [comment]
I coud be done in your app with something like:
```js
const [response] = await Promise.all([
  doMyRequest(),
  new Promise(resolve => setTimeout(resolve, 600)),
]);
```

**Comment by ccheney** [comment]
> This can be solved using interceptors:
> 
> 1. You intercept the request and add `startTime` to the config
> 2. You intercept the response and check the time and delay the return, using `setTimeout` or [`Promise.delay`](http://bluebirdjs.com/docs/api/promise.delay.html)
> 
> I will close this issue, for now, feel free to create a new one if you have other questions

Here is an interceptor that does exactly this: https://gist.github.com/ccheney/957481d88a5060ab4bb3401cdee296ac
