### ISSUE TITLE
Handling Attachments from response header

### ISSUE THREAD

**Issue by dahudson88** [axios/axios#1337]
#### Summary

I am trying to access the content of an attachment that is in the response header.  If you take a look at the image below you see that axios is returning the correct information, but I am unsure how to access the data to later display to the app.

![screen shot 2018-02-05 at 4 59 26 pm](https://user-images.githubusercontent.com/31221472/35831121-b469f7be-0a96-11e8-9ac0-033f4f72a770.png)

Any help would be appreciated.

Thanks

#### Context

I am using v0.17.1 of axios with react-native v 0.50.3

**Comment by Khaledgarbaya** [comment]
you can check the axios [API](https://github.com/axios/axios#axios-api) section in the README.
the data is inside `response.data`

**Comment by dahudson88** [comment]
If you take a look at the image, the data field is empty.

Is this an issue with the server not actually returning data or is there a way that I can actually get the file from the header's content.

**Comment by Khaledgarbaya** [comment]
This could be an issue with the server
