### ISSUE TITLE
Update axios tag

### ISSUE THREAD

**Issue by pntgupta** [axios/axios#1340]
I need the latest merged changes so can you please bump the tag version

**Comment by emilyemorehouse** [comment]
I'm going to leave the release schedule to @nickuraltsev, as he's been handling the most recent releases.

For now, you can install directly from GitHub, just replace `<commit-ish>` with the commit id that you need:
`npm install github:axios/axios#<commit-ish>`

As of now, this installs at the most recent commit:
`npm install github:axios/axios#604e8dd `
