### ISSUE TITLE
with maxRedirects: 0, redirects are always followed.

### ISSUE THREAD

**Issue by ghenry** [axios/axios#1341]
Hi all,
I can't seem to get this to work and think it's a bug. Here's my test within vue-router:

```
 router.beforeEach((to, from, next) => {
     axios.get(process.env.SUREVOIP_PORTAL + '/whoami', { 
         maxRedirects: 0,
     })
     .then(response => {
       if ( response.data.includes('Log in') ) {
       // Can't check for 302 at the moment
       //if ( response.data.includes('Log in') && process.env.NODE_ENV === 'production' ) {
         //window.location.href = process.env.SUREVOIP_PORTAL
         console.log(response.status);
         console.log(response.statusText);
         console.log(response.headers);
         console.log(response.config);
       }
       else {
         console.log(response.status);
         next()
       }   
     })
     .catch(error => {
       console.log(error)
     })
     next()
 })
```
The redirect is always followed:

![screenshot from 2018-02-06 18-13-12](https://user-images.githubusercontent.com/159608/35876517-6d6d7fa0-0b6a-11e8-8110-0f8d77847d53.png)
![screenshot from 2018-02-06 18-13-23](https://user-images.githubusercontent.com/159608/35876518-6d8a75e2-0b6a-11e8-8ddf-a452aea437a7.png)

I can see it's tested OK here: https://github.com/axios/axios/blob/07a7b7c84c3ea82ea3f624330be9e0d3f738ac70/test/unit/adapters/http.js#L99

I'm also confused by a 302 not being treated as an error as `validateStatus` says:

`    return status >= 200 && status < 300; // default`

**Comment by sergiusz-roszczyk** [comment]
It looks like your question has been answered here: #932 

Client side redirect is being done before axios ever get any response from XHR.

**Comment by ghenry** [comment]
Yeah agreed. The solution in #932 was what I was actually thinking of using to handle the difference between a browser request and xhr request to the same page so you can serve up different things. For example, your index.html for your vue.js SPA with browser request or JSON is xhr.

Closing.
