### ISSUE TITLE
Promise error message in console on cancellation

### ISSUE THREAD

**Issue by c0debreaker** [axios/axios#1347]
I'm trying Axios' cancellation of network request. It's working great.

I have a question about `return Promise.reject(error)`. When I cancel my http get request, I get `Uncaught (in promise)` in console in color red. Is this normal?

```
export function retrieveInformation() {
    if (cancel !== undefined) {
      cancel();
    }
    return axios.get('http://blah.blah.com', {
      cancelToken: new CancelToken(function executor(c) {
        cancel = c;
      })
    })
    .then(res => res)
    .catch(error => {
      return Promise.reject(error) // <----- When this code is present, I get the error above
    });
}```

**Comment by Khaledgarbaya** [comment]
That's because you are rejecting the promise and if you don't catch somewhere else the error will popup

**Comment by c0debreaker** [comment]
Yup, I got it working last night. Thanks.

**Comment by VCodepp** [comment]
@c0debreaker  Could you tell me how you solved the problem? I am having this problem.
the only difference from your code is that I use 'await'.
