### ISSUE TITLE
Axios sending the wrong response but works well in postman

### ISSUE THREAD

**Issue by brianmituka** [axios/axios#1348]
I'm using axios to send a data to an api. if there are no tickets the response should `tickets sold out` otherwise the response should be `Notification sent to your phone to make payment`. when I make the post request in postman, I get the right response but when I try posting the same data with axios, it returns ticket sold out. Sample response in postman: 
`{
    "status": 200,
    "success": true,
    "message": "Notification sent to your phone to make payment",
    "data": null
}`
In axios, this is the response I get: 
`{ status: 200,
  success: true,
  message: 'Tickets Sold Out',
  data: null }`

here is my code:
``` const axios = require('axios')

const postData = {
OptionChoiceSelectedRegular: 'VIP',
valueRegular: 2,
totalRegular: 400,
OptionChoiceSelectedSeasonal: 'VVIP seasonal',
valueSeasonal: 600,
totalSeasonal: 1,
totalItemNo1: 2,
totalItemNo2: 3,
totalItemNo3: 0,
totalItemNo4: 0,
totalItemNo5: 0,
descriptionItemNo1: 'Quine Cap KES100',
descriptionItemNo2: 'QuineT-shirt KES 200',
descriptionItemNo3: 'Quine Polo KES 300',
descriptionItemNo4: 'Quine Scuff KES 50',
descriptionItemNo5: 'Quine drink KES 70',                                 
totalSum: 5000,
event_id: 7,
event_company: 'Harliquins',
phone_number: '2708512358'
};



let axiosConfig = {
  headers: {
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      "Access-Control-Allow-Origin": "*",

  }
};

axios({
      method: 'post',
      url: '<API-URL>',
      headers: axiosConfig,
      data: postData
  })
  .then((res) => {
      const message = res.data;
      // bot.sendMessage(msg.chat.id, message)
      // console.log(selectedEvent.id);
      console.log(message);
      


  })```


I don't even know how to describe this issue. What is wrong and why is axios sending the wrong message?

**Comment by Khaledgarbaya** [comment]
I don't think this has anything to do with axios.
First you are passing the headers wrong

```js
let axiosConfig = {
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      "Access-Control-Allow-Origin": "*",
}
axios({
      method: 'post',
      url: '<api-url>',
      headers: axiosConfig,
      data: postData
  })
  .then((res) => {
      const message = res.data;
      // bot.sendMessage(msg.chat.id, message)
      // console.log(selectedEvent.id);
      console.log(message);
  })
```
Also I edited your issue to remove your api url, to not get spammed by other users

**Comment by brianmituka** [comment]
@Khaledgarbaya hello it's still not working even after correcting the headers in post the response I'm getting from postman is different from the axios response. what could be the issue?

**Comment by mnirfan** [comment]
Me too. I'm trying to upload file with POST method. The API server tells me there's no file received. but it works well when i'm using Postman.
