### ISSUE TITLE
No Content-Type at post request

### ISSUE THREAD

**Issue by IvanPoida** [axios/axios#1360]
```
        axios({
            method: 'POST',
            url: '...',
            headers: {
                    Authorization: token,
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
            }
        }).then((response) => {
            console.log(response);
        }).catch((error) => {
            console.error(error);
        });
```
will not set up Content-Type.

The only way to make this work, was to set an empty params object. So it look like below.
```
        axios({
            method: 'POST',
            url: '...',
            headers: {
                    Authorization: token,
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
            },
            params: {} // <---
        }).then((response) => {
            console.log(response);
        }).catch((error) => {
            console.error(error);
        });
```
Is it an expected behavior?

*Note: edited by @emilyemorehouse to add code formatting for readability*

**Comment by Axnyff** [comment]
It looks like it's done on purpose:
https://github.com/axios/axios/blob/b7d8d126dad7341addcd7b063f7b261955ec9152/lib/adapters/xhr.js#L121
If config.data is undefined then it will remove the content-type header. If you add data in your config it will work ( it does not seem to work in your example but it works by adding a data key in the config object

**Comment by emilyemorehouse** [comment]
@Axnyff is completely correct -- it's expected that `data` is defined for a POST request to have a `Content-Type`. If there's no data, then there's nothing for the `Content-Type` header to correlate to (since if you use URL params, the type is inferred since you can't pass something like JSON as a URL encoded parameter).
