### ISSUE TITLE
Redirect body larger than maxBodyLength not correctly caught

### ISSUE THREAD

**Issue by albertogasparin** [axios/axios#1362]
#### Summary

Recently #1323 has been fixed, however `follow-redirects` is still not correctly implemented: current version does not handle errors correctly.
Indeed, if `maxBodyLength` is 10MB and the resource fetched after the redirect is bigger, `follow-redirects` will emit an error but that error will occur outside of axios promise chain.

```
Error: Request body larger than maxBodyLength limit
      at RedirectableRequest.write (./node_modules/follow-redirects/index.js:66:24)
      at FormData.CombinedStream.write (./node_modules/combined-stream/lib/combined_stream.js:118:8)
      at FormData.CombinedStream._pipeNext (./node_modules/combined-stream/lib/combined_stream.js:106:8)
      at FormData.CombinedStream._getNext (./node_modules/combined-stream/lib/combined_stream.js:79:10)
      at FormData.CombinedStream._pipeNext (./node_modules/combined-stream/lib/combined_stream.js:107:8)
      at FormData.CombinedStream._getNext (./node_modules/combined-stream/lib/combined_stream.js:79:10)
      at FormData.CombinedStream.resume (./node_modules/combined-stream/lib/combined_stream.js:134:10)
      at FormData.CombinedStream.pipe (./node_modules/combined-stream/lib/combined_stream.js:64:8)
      at dispatchHttpRequest (./node_modules/axios/lib/adapters/http.js:227:12)
      at httpAdapter (./node_modules/axios/lib/adapters/http.js:18:10)
      at dispatchRequest (./node_modules/axios/lib/core/dispatchRequest.js:59:10)
```

Axios should intercept that error and reject the promise

#### Context

- axios version: v0.17.1 + master
- Environment: node v8.4.0

**Comment by emilyemorehouse** [comment]
I'm having trouble duplicating this locally (and I actually went down quite a rabbit-hole of finding cases that get caught by Axios from `maxContentLength` but not follow-redirects `maxBodyLength`). 😅 

Can you share an example that demonstrates the error?

**Comment by scragg0x** [comment]
Keep in mind that follow-redirects's `maxBodyLength` is in bytes and the Axios example on the README can be confusing because it uses an example of `2000` for `maxContentLength`.  No mention of units and 2KB is an odd example, I assumed it was 2MB at first.  `maxContentLength` is assigned directly to `maxBodyLength` whenl specified.

**Comment by albertogasparin** [comment]
I tried to create a reproducible scenario, however the only way I'm able to trigger this error is while downloading images > 10MB from Gettyimages (which is an authenticated endpoint).
My suggestion is that, as a precaution, `axios` should default `follow-redirect` `maxBodyLength` limit to `Infinite`, for the same reason as `maxContentLength` default is `-1`.

Currently, `maxBodyLength` and `maxContentLength` are synched only when `maxContentLength` is explicitly set, leaving the default scenario uncovered (`maxBodyLength` default to 10MB, which is quite low).

**Comment by gordonk** [comment]
For benefit of anyone landing here, @scragg0x is correct, the configuration param is in bytes.
E.g. for 50MB request/response upper limit, 

`maxContentLength: 52428890`

**Comment by shubhi15** [comment]
Facing same issue . Even after adding maxContentLength: 52428890 to axios post request has not fixed it.

**Comment by RikkiGibson** [comment]
Content-Length is pretty ubiquitously understood to be in bytes, but editing the README to 1. note that it is in bytes and 2. note what the default is would be useful

**Comment by amjadalibb** [comment]
Worked for me. I just changed the version in package.json

"axios": "0.18.0",

**Comment by roccomuso** [comment]
axios should default `follow-redirect` `maxBodyLength` limit to `Infinity`

**Comment by goulderb** [comment]
For anyone hitting this who wants the easy "opt-out" to disable body size checks entirely:

Set `maxContentLength` to `Infinity`. This will get passed to follow-redirects, and all the body size checks work as expected.

**Comment by chinesedfan** [comment]
I have made #2695 to confirm that the error is handled, and #2696 to track further plans.

**Comment by tbaustin** [comment]
> For anyone hitting this who wants the easy "opt-out" to disable body size checks entirely:
> 
> Set `maxContentLength` to `Infinity`. This will get passed to follow-redirects, and all the body size checks work as expected.

This did not work for me:

```js
const { data } =	await axios({
			url,
			responseType: 'stream',
			maxContentLength: `Infinity`,
		})
		return new Promise((resolve, reject) => {
			data.pipe(createWriteStream(image_path))
				.on('finish', () => resolve(createReadStream(image_path)))
				.on('error', e => reject(e));
		})
```

**Comment by scragg0x** [comment]
Try Infinity without the quotes
