### ISSUE TITLE
Problem with Proxy

### ISSUE THREAD

**Issue by Fernando-Parise** [axios/axios#1371]
hello guys.

I'm trying to use fetch method to get/post data into a REST server (this is working), but some users of my app need to do this over a network(WiFi) with proxy authentication. I've searched this, I found a few answers, but no one have helped me, some doesn't work 'cause need the Node core modules (that isn't on React-Native packager), e.g: https-proxy-agent.

Here I've found a similar question: react-native-fetch-through-proxy, but axios don't supports proxy with user and password (I tried), and the unique answer doesn't worked for me, 'cause it need Node core modules (again). I tried browserify to implement pieces of Node core, but the https-proxy-agent plugin can't see my JS files.

thank you.

code:
```
  let headers = {
    'Content-Type': 'application/json',
    'Authorization': token
  }

  var config = {
    headers: headers,
    proxy: {
      host: 'IP',
      port: 8000,
      auth: {
        username: 'user',
        password: 'password'
      }
    },
  };

  await axios.post('myurl',
    data,
    config)
    .then((response) => {
      console.log("reactNativeDemo", "response get details:" + response.data);
      console.log( response.data);
    })
    .catch((error) => {
      console.log("axios error:", error);
    });
```
with proxy return Failed to connect to /myurl 

without proxy return connection successfully

*Note: edited by admin to add code formatting*

**Comment by adrienthiery** [comment]
Hi @Fernando-Parise ,

Did you ever manage to have that working? 

I'm trying use axios with a proxy right now and it just does not do anything different than fetching without the proxy...

**Comment by chinesedfan** [comment]
As far as I know, if you are using axios in the browser side, it doesn't support proxy.
