### ISSUE TITLE
Posting a single string doesn't json encode

### ISSUE THREAD

**Issue by half2me** [axios/axios#1379]
#### Summary
Posting a simple string payload like this:
`axios.post(url, "foo");`
posts the string data as `foo` instead of `"foo"`, and as such, is not valid JSON.
Using `axios.post(url, JSON.stringify("foo"));` works just fine.
My bad, if this is the expected behaviour, but all other payloads get converted into perfectly valid JSON data, I don't see why a simple string shouldn't.

#### Context

- axios version: latest stable
- Environment: osx high sierra, chrome

**Comment by Axnyff** [comment]
It seems pretty normal to me,
if you are posting the characters `foo`, you don't want the library to actually send `"foo"`.

If so there wouldn't be any way to post a single string with axios without having the exta `""` characters.

What axios do, on the other hand, is whenever you send an object, it understands you probably don't want to use `.toString` on it ( resulting in "[Object object]") but probably want to JSON stringify it

**Comment by half2me** [comment]
I see, thanks for the clarification!
