### ISSUE TITLE
Not an issue but need help

### ISSUE THREAD

**Issue by c0debreaker** [axios/axios#1382]
I'd like to remove all the headers for a specific request, /healthcheck. I want the size of my request to be as small as possible. Currently, the size of header in every request is big. Our public application needs to check a health of a service every 15 mins and I want to make sure the header doesn't have all the usual headers it usually send.

I can do the code below but I'll have to specify one by one. I'd also like to make sure that other calls will have the normal headers.

```js
transformRequest: [(data, headers) => {
    delete headers.common.Authorization
    delete headers.common.anotherOne
    delete headers.common.thisOneToo
    delete headers.common.andAnotherOne
    delete headers.common.andMoreNotMentioned
    return data
}]
```

**Comment by Axnyff** [comment]
Hello,
Did you try to do something like this:

    headers.common = {};

Or maybe:

   Object.keys(headers.common).forEach(key => {
       delete headers.common[key];
    });

**Comment by c0debreaker** [comment]
I will try that. Thanks

**Comment by JustinBeckwith** [comment]
Greetings!  Looks like a pretty good answer up there.  If you're still running into issues... please do let us know!
