### ISSUE TITLE
Can axios set cookies?

### ISSUE THREAD

**Issue by sebastiaandegeus** [axios/axios#1385]
I'm trying to set a cookie with a response header like so:

```
Set-Cookie:connect.sid=s%3AvidaO7FJ_U-Fx77zGEAozIizc4eddq8P.wkkigPnMdYNo8SttRYplaI1%2FGL56vUVDgUK3UzoI6DI; Domain=subdomain.ofmywebsite.com; Path=/; Expires=Sun, 04 Mar 2018 15:14:18 GMT
```

Client side code:

```
axios.defaults.withCredentials = true;

axios('domain.ofmyserver.com/api/login', {
      method: 'post',
      data:{
        email: this.state.email,
        password: this.state.password
      },

    })
```

But no error is given and no cookie is set. What am I missing here? 
When I go directly with the browser to the server domain it will set a cookie. But with a POST request in axios it simply refuses it without any error.

#### Context

- axios version: 0.17.1
- Environment: Chrome, safari, firefox
- express server with express-session 1.15.6

**Comment by Axnyff** [comment]
Hello,
Are you doing a cross domain request?

If so, you might need an extra header to allow it:
https://stackoverflow.com/a/46412839/4949918

**Comment by dancon** [comment]
maybe you need set cookie path when you set cookie in server side~~

**Comment by Manubi** [comment]
Hi,
@sebastiaandegeus did you find a solution? :)

**Comment by jayudhandha** [comment]
Hi,
I have also similar kind of requirement.
I have cookies in my node js `req.cookies`  object.
Now from my node js application, i am invoking another API (in spring security project) which gives me error: 

> Could not verify the provided CSRF token because your session was not found.

I have tried to pass X-XSRF-TOKEN in header by reading this from cookies. But it seems i have to pass session as well,

So how to pass req.cookies from client side to another API?

**Comment by cqpaul** [comment]
who knows this answer, have this error too..

**Comment by ninaolo** [comment]
If anyone still has this problem and reads this: double check that you're setting `domain` and `path` from the server. I see that the creator of this thread did that, but I hadn't and was going crazy over why it didn't work. With `fetch` instead of `axios`, it worked without setting those properties, but `axios` needed them apparently.

**Comment by chinesedfan** [comment]
In fact, axios doesn't set cookies. It is done by the browser.

I saw the responded `Set-Cookie` had "Domain=subdomain.ofmywebsite.com; Path=/;", which means can't be used for "domain.ofmyserver.com/api/login". Please correct me or open a new issue if I misunderstood something.

**Comment by dspacejs** [comment]
Having tons of trouble with this.  `Domain` and `Path` is being set as @ninaolo said:

```
sessionid=redacted_token; Domain=127.0.0.1; expires=Fri, 10 Apr 2020 07:07:41 GMT; HttpOnly; Max-Age=900; Path=/
```

The `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials` headers have also been set (which can cause issues with CORS). I've also tried disabling CORS on the server, the same issue exists.

The `withCredentials` setting has also been set:

```js
axios.defaults.withCredentials = true;
```

Yet this still doesn't seem to be setting the cookie and I don't know why. The exact same endpoints work in Postman (it sets the cookie from the `Set-Cookie` header), yet in the browser it's not working. I'm not sure if this is a problem with axios or something else.

**Comment by jsindos** [comment]
Can second the issue laid out by @dspacejs, when I use fetch it successfully sets the cookies but when using axios it does not set the cookies.
