### ISSUE TITLE
config.data has been changed in response interceptor

### ISSUE THREAD

**Issue by rosemalejohn** [axios/axios#1386]
I am using axios request and response interceptors but it seems `response.config.data` is not an Object.

Here is my Request interceptor:

`config.data` is an instance of my Form Object

```js
API.interceptors.request.use((config) => {
  if (config.data instanceof Form) {
    config.data.startProcessing()
  }
  return config
})
```

Now going to the response interceptor, it seems it is not a Form anymore when it is a string already.

```js
API.interceptors.response.use((response) => {
  // this response.config.data is now a string not my Form object anymore
  if (response.config.data instanceof Form) {
    response.config.data.finishProcessing()
  }
  return response
})
```

**Comment by Axnyff** [comment]
Hello,

I have created a small reproduction of your problem 

    const axios = require('axios');

    axios.interceptors.request.use((config) => {
      console.log(config.data, typeof config.data); // console.log an object
      return config;
    });

    axios.interceptors.response.use((response) => {
      console.log(response.config.data, typeof response.config.data); // console.log a string
      return response
    });

    axios.get("http://localhost:8000", { data: {foo : true }});

It does seem weird, I don't know if it qualifies as a bug though.

**Comment by Rain1368189893** [comment]
I have the same problem, i also find that if the response.data is no longer, the result of console.log is object, if it's bigger, the result is string. Any way to slove?

**Comment by brunnohofmann** [comment]
@liveKang it works for me. Thank u!

> so just try this in node-module/axios/lib/defaults.js,change this Fun.
> 
> ```
> transformResponse: [function transformResponse(data) {
>     /*eslint no-param-reassign:0*/
>     if (typeof data === 'string') {
>       try {
>         if (!String.prototype.trim) {
>           String.prototype.trim = function () {
>             return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g, '');
>           };
>         }
>         data = JSON.parse(data.trim(''));
>       } catch (e) { 
>         /* Ignore */
>         console.log('can not JSON.parse the response', e)
>       }
>     }
>     return data;
>   }],
> ```
> hope this can help you.

**Comment by 1renhaO** [comment]
same issue, hope to be solved.

**Comment by chinesedfan** [comment]
The reason is that config.data has been changed in response interceptor, as well as my edited issue title. A workaround can be saving the original data in a customized field of the config.

```
API.interceptors.request.use((config) => {
  config.rawData = config.data
  return config
})

API.interceptors.response.use((response) => {
  // read `config.rawData`
  return response
})
```
