### ISSUE TITLE
Error Response Headers

### ISSUE THREAD

**Issue by TonBits** [axios/axios#1388]
#### Summary
I am not able to get all the response headers when when the server response status code other than 200 is returned.

In fact, I can only see 3 of the response headers out of many when looking at chrome debugger.
Here is a snapshot on a request that returns 401, where I have a custom header ***error*** which is what I am trying to get from the catch block.
![image](https://user-images.githubusercontent.com/17241213/36688824-7a9016a2-1ae2-11e8-8aee-5683be075331.png)

I have learned that printing the **error** does not work on chrome (only prints a stringified stack exception).
![image](https://user-images.githubusercontent.com/17241213/36689088-4df5c992-1ae3-11e8-991c-870e58539cf2.png)

So I have to print the **error.response** instead which shows the object hierarchy below.
![image](https://user-images.githubusercontent.com/17241213/36689145-755f7cda-1ae3-11e8-8cc7-82889a2fb049.png)
Note: I am able to see **config, data, headers, request, status, statusText** as top level properties of the object. But when expounding the headers property, it only shows 3 header values (**cache-control, expires and pragma**)

So I tried printing the headers through **console.log(error.response.headers)** and it does render only the 3 response headers.
![image](https://user-images.githubusercontent.com/17241213/36689329-f21f9df4-1ae3-11e8-9f19-8930c823a435.png)

When looking at the network tab in chrome with the actual response headers, it clearly is missing the rest of the headers, along with my custom header named **error**
![image](https://user-images.githubusercontent.com/17241213/36689485-6295f038-1ae4-11e8-84ad-6e49d8854791.png)

#### Context

- axios version: *v0.16.2*
- Environment: *: Spring , chrome 64.0.3282.167, windows 8*

**Comment by Axnyff** [comment]
Hello,
You are doing a cross request domain so by default, unsafe header are not shown.

You need to add `Access-Control-Expose-Headers`: `error` to see that header.
https://stackoverflow.com/a/5837798/4949918

**Comment by TonBits** [comment]
@Axnyff interesting. Let me try both scenarios, cross-origin request where response contains Access-Control-Expose-Headers with the value error (to expose the error header). And similarly, will try same domain (non-cross origin request) and see if all the headers are accessible without Access-Control-Expose-Headers

**Comment by TonBits** [comment]
@Axnyff is correct when doing cross domain request, headers must be granted first via Access-Control-Expose-Headers before it is available. Request on the same domain shows all the headers.
