### ISSUE TITLE
How to return 'onUploadProgress' and 'onDownloadProgress' as a percentage?

### ISSUE THREAD

**Issue by MunMunMiao** [axios/axios#1389]
#### Summary

How to return 'onUploadProgress' and 'onDownloadProgress' as a percentage? 

Because I have a lot of places need it. If every time to calculate, too much trouble

I have a lot of function, I just need a percentage, no other thing. So I want to be able to precalculate the percentage in Axios's custom configuration so that it doesn't need to be calculated again and again when it is used later.

#### Context

- axios version: *0.17.1*
- Environment: *Chomre 64.0.3282.167 (Official Build) (64-bit)*

**Comment by Axnyff** [comment]
Hello,
I think this works to get the percentage of a progress event:

            onUploadProgress: function(progressEvent) {
              var percentCompleted = Math.round( (progressEvent.loaded * 100) / progressEvent.total );
            }

If you want to have a way to avoid doing that computation every time, maybe you should use some kind of wrapper function:

    function withPercentage(fn) {
       return function(progressEvent) {
           var percentCompleted = Math.round( (progressEvent.loaded * 100) / progressEvent.total );
           fn(percentCompleted);
       };
    }

Then
    onUploadProgress: withPercentage(function (percent) {
        console.log(percent)
    }),    

should work

**Comment by MunMunMiao** [comment]
@Axnyff thx Solved

**Comment by Axnyff** [comment]
Can you close this issue please?
