### ISSUE TITLE
formData is empty on serverside

### ISSUE THREAD

**Issue by priyakrishnadev** [axios/axios#1390]
I'm trying upload a zip file along with form data. The data is being sent successfully but the formData is empty on serverside.Since I could not find the answer in the StackOverflow or any forums.I'm posting the issue here.Here is my code.
`var formData = new FormData();
formData.append('modelfile', values.values.modelfile[0]);
return axios.post('http://127.0.0.1:8000/addProduct',formData,
{ headers: {'Content-Type': 'multipart/form-data' }}
)
.then(res=>dispatch({type:'PRODUCT_UPLOADED_SUCCESSFULLY'}))
.catch(error=>dispatch({type:'PRODUCT_UPLOADED_FAILED'}))`
screenshot of send request
![desktopconsole](https://user-images.githubusercontent.com/33567910/36786658-393fbfb4-1cad-11e8-88b5-b4096a4c8aa1.PNG)

[https://stackoverflow.com/questions/48561688/axios-file-post-receiving-empty-array-at-server-side](https://stackoverflow.com/questions/48561688/axios-file-post-receiving-empty-array-at-server-side)

**Comment by ty-me** [comment]
Same problem, the server received an empty object.

**Comment by DerekCrosson** [comment]
Did this ever get solved? I have the same issue.

**Comment by Abdelrahman-Nabil** [comment]
I'm experiencing the same issue

**Comment by videni** [comment]
I also have the same problem, check [here](https://stackoverflow.com/questions/57493231/javascript-file-is-missing-when-upload-file-with-formdata) for more details. I have no idea why this happen.

**Comment by videni** [comment]
@priyakrishnadev ,  a year passed,  I realized this issue is pretty old,  do you find solution?

**Comment by arm092** [comment]
I don't know why, but 'put' method not work. I send file via 'post' method and receive it in controller.

**Comment by chinesedfan** [comment]
Closed due to stale. Feel free to open a new issue if it is still there.
