### ISSUE TITLE
Empty response when responseType is `blob` or  `arraybuffer`.

### ISSUE THREAD

**Issue by sky003** [axios/axios#1392]
#### Summary

Axios can't handle `blob` and `arraybuffer` responseType. It returns empty oject in `response.data`.

For example, downloading of PDF file:
```
axios.get('/file.pdf', {
      responseType: 'arraybuffer',
      headers: {
        'Accept': 'application/pdf'
      }
}).then(response => {
    // response.data is an empty object
    const blob = new Blob([response.data], {
      type: 'application/pdf',
    });
    FileSaver.saveAs(blob, 'file.pdf');
});
```
The contend of downloaded file is:
```
[object Object]
```
Is it a bug?

#### Context

- axios version: *v0.18.0*
- Environment: *node v9.5.0, chrome 64, archlinux*

**Comment by Axnyff** [comment]
Hello,
Are you sure it's not an issue with your server or your original file?
I tried your code and it works perfectly.

**Comment by sky003** [comment]
Hello,
I'm sure that it isn't issue with the server or file. I do the same with Fetch API and it works, but with axios it isn't.

```
fetch(
  '/file.pdf',
  {
    headers: {
      'Accept': 'application/pdf',
    },
    responseType: 'blob',
  }
)
.then(response => {
  if (response.ok) {
    return response.blob();
  }
})
.then(blob => {
  FileSaver.saveAs(blob, 'file.pdf');
});
```

**Comment by Axnyff** [comment]
Here is my full working code:

```
const FileSaver = require('file-saver');
const axios = require('axios');
axios.get('/file.pdf', {
      responseType: 'arraybuffer',
      headers: {
        'Accept': 'application/pdf'
      }
}).then(response => {
    console.log(response);
    // response.data is an empty object
    const blob = new Blob([response.data], {
      type: 'application/pdf',
    });
    FileSaver.saveAs(blob, Math.random());
});
```
I added the Math.random part to make sure I was generating a new pdf.
Can you provide more info on your server, there might be something here that is throwing axios off.

Here are some more picture of what the headers look like and the content of the file:
![screenshot](https://user-images.githubusercontent.com/9498142/37259446-ae3112c8-2586-11e8-8689-2f3ba69c1e80.png)
![screenshot bis](https://user-images.githubusercontent.com/9498142/37259449-b8f46250-2586-11e8-9afe-9c5926f82021.png)

**Comment by molerat619** [comment]
And how do you handle errors? E.g. I would like to return a 422 in some cases. But because axios expects a blob as response, I don't know how to handle this.

**Comment by joeczucha** [comment]
I'm also having the exact same problem.

**Comment by EvanSanderson** [comment]
I was able to get blob responseType working for an axios call using @Axnyff example as a reference. Code looked like:

```
			api
				.getMultipleDownloads(url, headers.multiId)
				.then(response => {
					const blob = new Blob([response.data], { type: 'application/zip' })
... do stuff with blob

				})
				.catch(error => {
					console.error(error)
				})
```

and the actual method looking like:

```
	getMultipleDownloads: (endpoint, docIds) => {
		return axios.get(`${endpoint}`, {
			responseType: 'blob',
			headers: {
				multiId: docIds
			}
		})
	},
```
In this case I'm creating a zip file but the overall process is the same. Hope this helps someone!

**Comment by daxiongz** [comment]
I also have the problem. Axios can't handle blob and arraybuffer responseType. It returns **undefined** value as **response**. For example:
`
let url = 'https://yunxi-material-library.oss-cn-hangzhou.aliyuncs.com/recordImg/1070/pakWKWnPmC.JPG'
axios
    .get(url, {
      responseType: "arraybuffer",
    })
    .then(function (response) {
      console.log(response)   // undefined
    })
    .catch(function (error) {

    })
`
But i use Fetch API, it is success. For example:
`
fetch(url,
    {
      responseType: "arraybuffer"
 })
  .then(function (response) {
    console.log(response);
    let res = response.arrayBuffer();
 
    return res
  })
`

**Comment by sky003** [comment]
Probably, this may be an issue with javascript compiler, like babel, or some other related to the build configuration. For example, I faced this issue by building my environment using `create-react-app` tool.

**Comment by magnus80a** [comment]
I solved it with Axios 0.18.0 with the following code.
```
    private handleDownloadPdf = () => {
        axios.post("/api/pdf",
            {
                bodyData: myData
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/pdf'
                },
                responseType: "blob"
            }).then((response: AxiosResponse) => {
                const blob = new Blob([response.data], { type: 'application/pdf' })
                const objectUrl = window.URL.createObjectURL(blob)
                window.open(objectUrl)
            }).catch((error: any) => { alert(error) })
    }
}
```

**Comment by Gertiozuni** [comment]
This is not working fine for large files, file is downloaded after 1 minute or more depending on file size

**Comment by maleonix** [comment]
`    _downloadWeb(url, api, mimeType) {
        var token = getTokenWeb();
        let data = {
            "siteId": this.state.idSite,
            "location": this.state.location,
            "severity": this.state.severity,
            "riskDomainId": this.props.riskDomainId,
            "userId": this.state.idCreator,
            "processingTypeId": this.props.idProcessingType

        }
        Axios.defaults.headers.common['Authorization'] = `${token}`
        Axios.defaults.headers.common['Accept'] = `${mimeType}`
        Axios.defaults.headers.common['Content-Type'] = `application/json`
        Axios.post(url + api, data, {
            responseType: 'blob',
        })
            .then((response) => {
                let blob = new Blob([response.data], { type: mimeType });
                saveAs(blob, guid() + ".xlsx")
            })
            .catch(function (error) {
                console.log("_downloadWeb", error);
            });;
    }`

**Comment by csalazar** [comment]
Same issue here, it worked for me (the context is a [redux saga](https://github.com/redux-saga/redux-saga)):

```
    const response = yield call(
      axios.get,
      pdfUrl,
      {
        responseType: 'arraybuffer',
      }
    )

    const url = window.URL.createObjectURL(
      new Blob([response.request.response], {
        type: 'application/pdf',
      })
    )
```

**Comment by HarisHashim** [comment]
I have same problem and self learn how to troubleshoot this.

Does bellow image indicate that 

``responseType: 'arraybuffer'

or 

``responseType: 'blob'

is not set? I was thinking that the response should be different between arraybuffer and blob. Yet I am seeing same response. So something must be wrong.

![image](https://user-images.githubusercontent.com/1856131/50578523-39ca4d80-0e76-11e9-8b3c-97e0b32239da.png)

**Comment by HarisHashim** [comment]
My code

``        postReport: function (data) {
          console.log("Data: " + JSON.stringify(data))
          return Promise.all([reportAPI.post("report/", data, {
            responseType: 'arraybuffer',
            headers: {
              'Authorization': reportBasicAuth,
              'Content-Type': 'application/json',
              'Accept': 'application/pdf'
            }
          })]);
        }

Console log for Data in the function above

>  Data: {"template":{"shortid":"rkJTnK2ce"},"data":{"items":[{"name":"Consultancy","price":100},{"name":"Website design","price":300}]}}

**Comment by renetanikolova** [comment]
How do you catch an error if the request fails? 
Since we have: responseType: "blob" - the method expects blob object and if the request fails, that's what I get in the error.response object:
![image](https://user-images.githubusercontent.com/20210656/51465693-1c035080-1d71-11e9-86c5-6654e022f9a4.png)

and there is no error message available there. So, how do you handle the error, or you just throw an error with the same message every time, like "Error occurred while generating the pdf file."?

**Comment by cs-NET** [comment]
Ran into same issue with errors returning ArrayBuffer instead of JSON, here is a quick helper to convert the ArrayBuffer to text and parse it.

``` TypeScript
    static to<T>(ab: ArrayBuffer): T | undefined {
        const text = String.fromCharCode.apply(null, Array.from(new Uint8Array(ab)));
        if (!text) return undefined;
        return JSON.parse(text) as T;
    }
```

I think when request fails error response should not be ArrayBuffer, maybe need errorResponseType.

**Comment by kariokabrs** [comment]
When i changed the responseType: 'arraybuffer' to  responseType: 'stream' ,  it works.

**Comment by umangsavaliya** [comment]
Try this solution it's worked for me https://medium.com/@fakiolinho/handle-blobs-requests-with-axios-the-right-way-bb905bdb1c04

**Comment by chinesedfan** [comment]
Thanks for lots of users sharing their solutions. And close due to not a bug of axios.

**Comment by daniel-butler** [comment]
I'm not sure I am following. What should be done if there is a success `responseType of `arraybuffer` but if there is an error we are sent back json so the `responseType` needs to be `application/json` for example?

**Comment by even42** [comment]
**this working also**

    axios.get('https://myservice.com/api/my-beautiful-id/pdf',
        {
            responseType: 'arraybuffer',
            headers: {
                'Accept': 'application/pdf'
            }
        })
        .then(function (response) {
            res.contentType("application/pdf");
            res.send(new Buffer.from(response.data, 'binary'))
        })
        .catch(function (error) {
            console.log(error);
        });
