### ISSUE TITLE
When I set up the interceptor, there are some exceptions that don't require interceptors. How can I cancel the interceptor for this exceptions?

### ISSUE THREAD

**Issue by lwzhang** [axios/axios#1393]
When I set up the interceptor, there are some exceptions that don't require interceptors. How can I cancel the interceptor for this exceptions?

**Comment by Axnyff** [comment]
It depends on what you want to do with that exceptions.
If you just want to keep it failing, then just reject a promise with that error, without doing anything with it.

**Comment by hans-lizihan** [comment]
i guess it's the best to create seperate axios instances.


```js
const client1 = axios.create();
client1.intercepters.request.use(interceptor1);
client1.intercepters.request.use(interceptor2);
client1.intercepters.request.use(interceptor3);

const client2 = axios.create();
client2.intercepters.request.use(interceptor1);
client2.intercepters.request.use(interceptor3);

```

**Comment by chinesedfan** [comment]
Yes, create different axios instances with different interceptors, or add conditions in your interceptors to skip the interceptor for exceptions.
