### ISSUE TITLE
History support?

### ISSUE THREAD

**Issue by maki10** [axios/axios#1394]
Does axios support history?

```js
                        axios.get("api/stores", this.axiosConfig()).then((res) => {
				this.stores = res.data.data;
			}).catch((error) => {
				this.showErrorMessage(error);
			});
```
And how to incude it? i can't find anywhere.

**Comment by emilyemorehouse** [comment]
I believe [config defaults](https://github.com/axios/axios#config-defaults) is what you are looking for.
