### ISSUE TITLE
Get binary data in a Firefox extension

### ISSUE THREAD

**Issue by aatifbirdeye** [axios/axios#1397]
I am trying to download binary data from Firefox browser. My app is based on react and redux and using axios as my HTTP client.

Below implementation didn't work

      axios({
        url: "http://api.demo6.test.com:8080/resources/v1/2",
        responseType: 'arraybuffer',
        method: 'post',
        data: dObj.payload.filterData,
        headers: {
            "Accept": "application/vnd.ms-excel",
            "Content-Type": "application/json",
            "X-Bazaarify-Session-Token": "cfff-7-07f13399abed" //token
        }
      }).then(function(response) {
        let blob = new Blob([response.data], {type: "application/vnd.ms-excel"});
        let link = document.createElement("a");
        link.href = window.URL.createObjectURL(blob);
        link.download = "test.xls";
        link.click();
        console.log(response);
      });

How can I do it with axios?

**Comment by petromoldovan** [comment]
the same issue. Could someone from maintainers please check it?

**Comment by Bezbran** [comment]
In Firefox you have to use another way to  mimic "click" on a link:
```
               var fileURL = window
                    .URL
                    .createObjectURL(blob);
                var fileLink = document.createElement('a');
                fileLink.href = fileURL;
                fileLink.download = name;
                fileLink.title = fileLink.download;            
                fileLink.dispatchEvent(new MouseEvent("click", {
                    "view": window,
                    "bubbles": true,
                    "cancelable": false
                }));
```

**Comment by chinesedfan** [comment]
You have already got the expected response. And the extra download feature is out of the scope of axios. [stackoverflow](https://stackoverflow.com) or Firefox's forum may be a better place to find answers.
