### ISSUE TITLE
Trailing slash seems to be automatically removed

### ISSUE THREAD

**Issue by zywind** [axios/axios#1405]
When sending requests to urls with a trailing slash, axios seems to automatically remove the slash. Having the trailing slash is import for complying with the REST guidelines for dealing with a collection of resources or posting a new resource to a collection. For example, endpoint for getting a collection of users should be GET: http://host/users/ and that url is considered to be different from http://host/users. So please retain the trailing slash. Thanks.

- axios: v0.18.0
- Environment: chrome 64, mac

**Comment by Axnyff** [comment]
Do you have a reproduction of your bug? It does not seem to happen with that code:

    const axios = require('axios');
    axios.get("http://host/users/");

**Comment by zywind** [comment]
Hmm, my bad, it does appear to be working. Perhaps it was a server issue earlier...
