### ISSUE TITLE
Data is null when Json contains NaN

### ISSUE THREAD

**Issue by bhansenmd** [axios/axios#1409]
When a response object has a `NaN` value in it, axios silently fails and gives a response object with `data: null`.

We understand that `NaN`, `Infinity`, and `-Infinity` [aren't allowed by json](https://github.com/capnproto/capnproto/issues/261), but if that's the case then the library should throw an error saying that the response can't be processed. We just found this bug after a lot of very annoying and mysterious debugging, and it would have been nice to understand right away what the problem was.

Here is a screenshot of the request that failed (sensitive information has been redacted):
![screenshot from 2018-03-12 13-29-43_redacted](https://user-images.githubusercontent.com/33879020/37305507-49f0938c-25fa-11e8-8f4d-3724797d92ee.png)

and here's the shortened response text:
```
[
    {
        "id": 3,
        "date_created": "2018-03-12T17:49:16.260937",
        "date_updated": "2018-03-12T17:49:16.260937",
        "current_value": NaN
    }
]
```

It's interesting to note that the chrome devtools understand and parse this response.

**Comment by Axnyff** [comment]
Can you provide your client side code and your axios version?
It does not seem to do that for me:

    const axios = require('axios');
    axios.get('/foo.json').then(resp => console.log(resp), console.log);

gives me the data as text and not null

**Comment by bhansenmd** [comment]
The Axios  version is 0.18.0. We'll get you the code to reproduce.

**Comment by bhansenmd** [comment]
Our app uses Vue.js and Node (via npm). 

The offending code is the following.
```
import http from 'axios'
// Other imports

const api = {
    
    fetchTests: () => http.get('/tests'),
    // Other endpoints
}
```

In a file called `main.js` we give axios some defaults
```
axios.defaults.baseURL = config.baseURL // localhost:5050 (a Flask server)
axios.defaults.responseType = 'json'
```

If I comment out the `responseType` line, data is the string value of the response.

**Comment by Axnyff** [comment]
It looks like it's the regular behavior of the browser:
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType

var a = new XMLHttpRequest(); a.open('GET', '/yolo.json?'); a.responseType = 'json'; a.send()

axios does nothing, it's the browser which just fails silently

**Comment by bhansenmd** [comment]
That's a bummer. Thanks for your help anyways :)
