### ISSUE TITLE
Cannot completely remove User-Agent header

### ISSUE THREAD

**Issue by KevinEady** [axios/axios#1411]
https://github.com/axios/axios/blob/9a6abd789f91a87d701116c0d86f1cfbc3295d66/lib/adapters/http.js#L34

Is it possible to create a request with absolutely _no_ `User-Agent` header? It doesn't seem possible with the code listed here. 

According to [this Stackoverflow](https://stackoverflow.com/a/24274846/9307267), a `User-Agent` is not a required header, so I imagine axios should allow this type of configuration.

**Comment by Axnyff** [comment]
The User Agent header used to be impossible to modified within an XMLHttpRequest because of the spec.
https://stackoverflow.com/a/5862744/4949918

It looks like the spec has changed on this but browsers don't have all changed on that.

Chrome will throw an error for instance:

     var a = new XMLHttpRequest();
     a.open('GET', '/');
     a.setRequestHeader('User-Agent', ''); // Refused to set unsafe header "User-Agent"

So it looks like this is not something that can be done reliably, and this has nothing to do with axios.

**Comment by KevinEady** [comment]
Ah, interesting. I didn't think about the in-browser usage. I'm using axios in node, testing an API endpoint that behaves differently with different User-Agents, including when one isn't passed at all.

But Chrome throwing that error for setting User-Agent sounds more of a Chrome-enforced protection than the XHR standard. Looking at https://fetch.spec.whatwg.org/#forbidden-header-name, User-Agent is not listed.

**Comment by Axnyff** [comment]
It used to be forbidden by the specification but was removed in 2017

**Comment by Axnyff** [comment]
Anyway for node, it looks like it is set on purpose by axios.

The request works correctly if you remove these lines: https://github.com/axios/axios/blob/master/lib/adapters/http.js#L34

**Comment by JustinBeckwith** [comment]
Greetings!  This appears to be answered.  If you're still having any issues... please do let us know!
