### ISSUE TITLE
Chaining axios call based on array

### ISSUE THREAD

**Issue by jericopulvera** [axios/axios#1413]
How do I do this dynamically
```
var array = [0,1,2];
axios.get('api/' + array[0]).then(response => {
    axios.get('api/' + array[1]).then(response => {
         axios.get('api/' + array[2]).then(response => {
            alert('done');
         });
    });
});
```
how do I chain axios call based on array?

**Comment by Axnyff** [comment]
Something like this should work:

```
const axios = require('axios');
function makeRequestsFromArray(arr) {
    let index = 0;
    function request() {
        return axios.get('http://localhost:3000/api/' + index).then(() => {
            index++;
            if (index >= arr.length) {
                return 'done'
            }
            return request();
        });

    }
    return request();
}

makeRequestsFromArray([0, 1, 2]);
```

**Comment by jericopulvera** [comment]
@Axnyff This solved my problem. Thank you!

**Comment by coder618** [comment]
> Something like this should work:
> 
> ```
> const axios = require('axios');
> function makeRequestsFromArray(arr) {
>     let index = 0;
>     function request() {
>         return axios.get('http://localhost:3000/api/' + index).then(() => {
>             index++;
>             if (index >= arr.length) {
>                 return 'done'
>             }
>             return request();
>         });
> 
>     }
>     return request();
> }
> 
> makeRequestsFromArray([0, 1, 2]);
> ```

Quick Concern, Your code will go below 
index++;
eg:
```
// some action
console.log(index)
index++;
```

**Comment by Axnyff** [comment]
I'm sorry I don't understand what you mean, would you mind elaborating ?

**Comment by coder618** [comment]
> uld you mind elaborating ?

Nothing to worry, 
I am just trying to say if anyone wants to add specific code as per his/her project need then those codes will go above . :)
index++;
