### ISSUE TITLE
AxiosError type for javascript

### ISSUE THREAD

**Issue by cruelbob** [axios/axios#1415]
#### Summary

Axios rejects error with Error type. Adding custom error type will help with distinguishing between axios and other errors. The only way now is to check 'request' field existence which is not always possible. Our internal custom error type has this field too.

#### Example:
``` js
const { axios, AxiosError } = require('axios');
...
try {
  ...
  const response = await axios.get(url);
  ...
} catch (error) {
  if(error instanceof AxiosError) {
    return processAxiosError(error);
  }
  throw error;
}
```

#### Context

- axios version: 0.18.0

Relates to: #24

**Comment by AyushG3112** [comment]
This would be simple enough to do, but would be a breaking change.

**Comment by cruelbob** [comment]
AxiosError has to inherit from Error. This wouldn't breaking change.

**Comment by AyushG3112** [comment]
It would be if someone is checking `error.constructor.name === 'Error'`

**Comment by cruelbob** [comment]
I agree but this is a minor breaking change. Can we sacrifice this for better API?

**Comment by AyushG3112** [comment]
I'm in favor of this, but personally I would prefer, if the maintainers agree ofcourse, that we bump axios to a server, v1.0.0

Axios certainly seems stable enough for that, and following semver-major prevents breakage.

On another note, given the widespread use of axios and the preferred HTTP library of React and Vue.js, a breaking change can have major impacts which need to be considered.

**Comment by AyushG3112** [comment]
Actually, not that I checked, axios is working on a v1.0.0 branch, I might open a PR for this today.

**Comment by cruelbob** [comment]
@mzabriskie, @nickuraltsev

**Comment by cruelbob** [comment]
@JustinBeckwith

**Comment by axe312ger** [comment]
Ohh yes, this would help a lot. Having kinda the same issue in our SDK.

Can we add this to #1333 @Khaledgarbaya?

**Comment by AyushG3112** [comment]
The PR is already there, I added a soft fix for the 0.x versions as a flag in #1419, and the Error type change for the 1.x in #1420, refer the linked PRs

**Comment by AyushG3112** [comment]
@axe312ger  @Khaledgarbaya any updates on this?

**Comment by AyushG3112** [comment]
@axe312ger any update?

**Comment by axe312ger** [comment]
Have to pass on to @Khaledgarbaya 😅

**Comment by nilptr** [comment]
Is there any progress on this issue? It's useful to distinguish axios errors from other errors. And adding isAxiosError flag to errors thrown by axios https://github.com/axios/axios/pull/1419 is a good solution without breaking changes. Consider adding this flag in a patch version please?

**Comment by fractalzombie** [comment]
+1

**Comment by axe312ger** [comment]
I still like this, as we all have jobs, feel free to contribute that as PR

**Comment by cruelbob** [comment]
@axe312ger We already have 2 PRs!
#1420 and #1419

**Comment by axe312ger** [comment]
Oops. Hard to keep track on this repo.

I'd prefer https://github.com/axios/axios/pull/1419 to end up in master since the v1 rewrite currently is kinda frozen due to lack of time on our side.

Can you resolve conflicts and mention some people in there?

**Comment by Khaledgarbaya** [comment]
This is now fixed in https://github.com/axios/axios/pull/1419

**Comment by axe312ger** [comment]
That was fast :)

**Comment by cruelbob** [comment]
That was open source:)

**Comment by AyushG3112** [comment]
@axe312ger @Khaledgarbaya is it too soon to request a release please?

**Comment by Khaledgarbaya** [comment]
@AyushG3112 Unfortunately I don't have npm release rights

**Comment by skaldo** [comment]
@nickuraltsev @emilyemorehouse is there a plan releasing this anytime soon?

**Comment by fractalzombie** [comment]
I think if it is implemented, it will be more practical and clearer than using <Error.isAxiosError>.

**Comment by AyushG3112** [comment]
@axe312ger @Khaledgarbaya @nickuraltsev @emilyemorehouse can any of you please @-mention someone with npm publish rights?

**Comment by rhyek** [comment]
AxiosError would've been nicer... Can someone publish the isAxiosError change, please?

**Comment by ypresto** [comment]
Because at least we need some type-guard-aware function like `function isAxiosError(error: Error): error is AxiosError { return !!error.isAxiosError }`, it might be better to have it in library side.

**Comment by AyushG3112** [comment]
@Khaledgarbaya @axe312ger It's been months, can we have a release please?

**Comment by axe312ger** [comment]
We have no rights to publish axios to npm

**Comment by AyushG3112** [comment]
Could you tag someone who does please?

**Comment by zcei** [comment]
You did yourself last December https://github.com/axios/axios/issues/1415#issuecomment-449578470 - Nick and Emily have publish rights.

**Comment by emilyemorehouse** [comment]
👋 I've been handling all releases for consistency. As soon as CI is green again, I'll release!
