### ISSUE TITLE
Post request becomes a get request in Edge

### ISSUE THREAD

**Issue by SimpleNice** [axios/axios#1417]
I have a problem I do not know how to solve the need help
This is my code

```typescript
import Axios from 'axios'
import Promise from 'es6-promise'
Promise.polyfill()
import qs from 'qs'
const URL= 'http://192.168.0.112/account/login/username'
let params = {
    username:'admin',
    password:'admin',
}
Axios.post(URL,qs.stringify(params))
.then(res=>{
    console.log(res)
    }
)
.catch(error=>{
    console.log(error)
    }
)
```

In the non-Edge browser, the page request is the expected post request, but in the Edge browser, the request is a get request.
I use another computer Edge test, request normal, 

My browser version:
Microsoft Edge 41.16299.15.0
Another browser version:
Microsoft Edge 38.14392.1066.0

**Comment by Axnyff** [comment]
Can you use the devtools in edge to show us the request that is being sent? How do you know it's not a POST request?

**Comment by SimpleNice** [comment]
yse,This is my screenshot.
This is:Microsoft Edge  41.16299.15.0
![tim 20180326165419](https://user-images.githubusercontent.com/12603555/37897161-1b52fc8a-3118-11e8-84a7-6a563eab39e8.png)

This i:Microsoft Edge 
38.14392.1066.0
![default](https://user-images.githubusercontent.com/12603555/37897149-104576ec-3118-11e8-94d5-af94f3d24e9f.PNG)

**Comment by jttjt** [comment]
have you ever solved this problem?  i got this problem too and i can't deal with it

**Comment by SimpleNice** [comment]
I did not solve this problem

**Comment by jttjt** [comment]
so  if you didn't solve it?  your project may not run on Edge?

**Comment by Sweechirly** [comment]
this problem has not been solved

**Comment by lvybriage** [comment]
I also meet the problem.
Edge version: Microsoft Edge 41.16299.402.0

**Comment by davidwincent** [comment]
I have the same problem, works in other browsers but not in MS Edge

`"axios": "^0.18.0"`
`Microsoft Edge 42.17134.1.0`
`Microsoft EdgeHTML 17.17134`

My upload method before babel transpile:
```
import axios from 'axios'

const uploadBase64 = (base64, filename) => {
    const file = dataURLtoFile(base64, filename)
    const data = new FormData()
    data.append('data', file, filename)
    return axios.post(process.env.GRAPHQL_FILE_ENDPOINT, data, {
        headers: {
            'Content-Type': 'multipart/form-data'
        }
    })
}
```

In Edge network tab I see this =>
   Request URL: https://files.graph.cool/cjhhmgaud42cz0195fs7aw02m/cjhuc4pbl02b201631p2bc7oo
   Request Method: GET
   Status Code: 304 / Not Modified

**Comment by Axnyff** [comment]
It looks more like a edge bug, there's already a similar one: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11126248/

I don't see a reason why this would be caused by axios.

**Comment by davidwincent** [comment]
@Axnyff agree. Maybe consider uploading with fetch when it is available?

**Comment by cqpaul** [comment]
So this is just a bug with Edge? not for my code?

**Comment by nachii** [comment]
Same problem here... any news?

**Comment by KiwiNibbler** [comment]
Curious.  Has this been solved yet?  We have the same issue....

**Comment by nachii** [comment]
Really curious. Unfortunately not, no news... it's very annoying and I don't understand if it's a Edge problem or not.

**Comment by cloder** [comment]
Issue reported to Edge Developers: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20685238/

**Comment by sppilka** [comment]
It seems that the bug still persists. Tested on MS Edge version 44.17763.1.0 and axios 0.19.0. But also tested with SuperAgent and same error. Edge always swap POST with GET method...

**Comment by Edward-Li** [comment]
any update on this issue?  i got this issue also. in Microsoft Edge 41.16299.1004.0

**Comment by LazaroOnline** [comment]
I solved it by passing the data in a different format using the "URLSearchParams " class.
I had the same problem with:
Microsoft Edge 44.18362.267.0
Microsoft EdgeHTML 18.18362
Windows 10

I think the problem is that Edge only supports certain data types in post requests.
If you want to [use the content-type 'application/x-www-form-urlencoded' then use URLSearchParams ](https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format)to make it work in Edge and other browsers like Firefox and Chrome.
Passing a querystring seems not to work in Edge even if it does in other browsers.


Modifying the original post source code, the result would be:
```javascript
import Axios from 'axios'
import Promise from 'es6-promise'
Promise.polyfill()
const URL= 'http://192.168.0.112/account/login/username'

// Use URLSearchParams instead:
const dataParams = new URLSearchParams()
dataParams.append('username', 'admin')
dataParams.append('password', 'admin')

Axios.post(URL, dataParams, {
  // if you still have problems try more specific options like:
  // withCredentials: true,
  // crossdomain: true,
  // ...
})
.then(res=>{
    console.log(res)
    }
)
.catch(error=>{
    console.log(error)
    }
)
```

**Comment by sergeycw** [comment]
any news on this issue? have the same problem

**Comment by p666888** [comment]
i have the same problem too.
edge 44.17763.1.0 
axios 0.19.0

**Comment by sergeycw** [comment]
same problem for me

i understand that it is not an axios issue, but maybe somebody know how to fix it and correctly send POST request over https in edge?

**Comment by sergeycw** [comment]
hi! in my case problem was caused by a self-sign certificate. as soon as I started using normal certificate everything began to work.

**Comment by wang-ky** [comment]
when i in dev environment and use LAN address for backend api address, post request becomes a get request and transfer by cache, but when i change api address to public network address, it's ok. i don't why. it's so amazing...unbelievable IE...

**Comment by Thomas080304** [comment]
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363
 still has the same bug
