### ISSUE TITLE
Cross origin null forbidden: Axios tries to make an xhr request in a Node environment, instead of an http request.

### ISSUE THREAD

**Issue by bertho-zero** [axios/axios#1418]
Axios tries to make an xhr request in a Node environment, instead of an http request.

```js
// It doesn't work

import axios from 'axios';

const { data } = await axios.get( 'http://example.com' );


// It work

import axios from 'axios';
import adapter from 'axios/lib/adapters/http';

const { data } = await axios.get( 'http://example.com', { adapter } );
```

**Comment by bertho-zero** [comment]
Related to https://github.com/axios/axios/issues/191

**Comment by bertho-zero** [comment]
It's a issue due to Jest default environment.
https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string
> The test environment that will be used for testing. The default environment in Jest is a browser-like environment through jsdom. If you are building a node service, you can use the node option to use a node-like environment instead.
___
What creates `XMLHttpRequest` and misleads this function:
https://github.com/axios/axios/blob/9a6abd789f91a87d701116c0d86f1cfbc3295d66/lib/defaults.js#L16-L26

___

To fix this I had to add this in my `jest.config.js` file:

```js
{
  // ...
  testEnvironment: 'node'
  // ...
}
```

**Comment by bertho-zero** [comment]
Fixed by https://github.com/axios/axios/pull/1285 !

**Comment by andreshg112** [comment]
How can I do it with Mocha?

**Comment by andreshg112** [comment]
Solved with Mocha (not really Mocha at all but Axios). This is what I did.
https://github.com/jsdom/jsdom/issues/2319#issuecomment-410362266

**Comment by LeoFC97** [comment]
@bertho-zero where i can find this file?
