### ISSUE TITLE
[Question] Change headers dynamically

### ISSUE THREAD

**Issue by FimaTaf** [axios/axios#1421]
#### Summary

Is it possible to change the headers dynamically? Because it seems that after the axios object is being instantiated there is no way to modify some header that has been defined.

#### Context

- axios version:  v0.18.0*
- Environment: node v8.9.4, chrome 64.0.3282.186, windows 10*

**Comment by Axnyff** [comment]
This is definitely possible, this gives me a header test of false:

    const axios = require('axios');
    const inst = axios.create({ headers: {
        test: true,
    }});

    axios.get('/yolo', {headers: { test: false}}).then(console.log);
