### ISSUE TITLE
I can not get the `csrftoken` in the Axios config.

### ISSUE THREAD

**Issue by moonshineBoy** [axios/axios#1423]
#### Summary

I want to get the `csrftoken` and set it to the headers' 'x-csrftoken', but I can not get the `csrftoken` by the `Cookies.get('csrftoken')`.

the related post is <a href="https://stackoverflow.com/questions/49312473/how-can-i-get-the-cookies-csrftoken-in-axios-interceptors-requests-config">there</a>

and you can see this <a href="https://stackoverflow.com/questions/49298250/where-is-the-csrftoken-stored-in-django-database">post</a>:

> AJAX While the above method can be used for AJAX POST requests, it has some inconveniences: you have to remember to pass the CSRF token in as POST data with every POST request. For this reason, there is an alternative method: on each XMLHttpRequest, **set a custom X-CSRFToken header to the value of the CSRF token. This is often easier, because many JavaScript frameworks provide hooks that allow headers to be set on every request.**

#### Context

- axios version:  *axios@0.15.3*
- Environment: *node v8.9.1, chrome 65.0.3325.146, macOS Sierra 10.12.6*

**Comment by svetoslav0625** [comment]
@moonshineBoy , any updates?

**Comment by aranmohyeddin** [comment]
no wonder everyone is telling me I should use fetch...

**Comment by chinesedfan** [comment]
@moonshineBoy Make sure your cookies contained `csrftoken`.
@gerberasa Make sure your server response `csrf-token` in the data.

Anyway, it should not be an issue of axios. Please remind me if I missed something.
