### ISSUE TITLE
Axios not failing on chrome "canceled request".

### ISSUE THREAD

**Issue by AoDev** [axios/axios#1428]
#### Summary

Google Chrome may cancel requests sometimes. Axios does not seem to throw an error when this happens.

#### Context

- axios version: *0.17.1*
- Environment: *Electron / Chrome / Chromium*

For more details about what can cause this situation, here is a stackoverflow link "[What does status=canceled for a resource mean in Chrome Developer Tools?
](https://stackoverflow.com/questions/12009423/what-does-status-canceled-for-a-resource-mean-in-chrome-developer-tools#13459106)". This is also valid in Chromium (Electron apps).

I was expecting axios to fail and throw an error when this happens. But this code does not work:

```
refreshData () {
  this.isFetching = true
  this.fetchingError = false

  return this.fetchData()
    .then(() => {
      this.set('lastUpdated', new Date())
    })
    .catch((err) => {
      this.set('fetchingError', true)
    })
    .finally(() => {
      this.set('isFetching', false)
    })
}
```
Nor `catch`, nor `finally` run.

Is this an expected behaviour?

(In case you don't know about: [finally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally))

**Comment by Axnyff** [comment]
Did you try to see what happens at the XMLHttpRequest level? If that request simply never succeeds nor fails at that level, it could be tricky for axios to detect anything.

Does it work correctly if you add a timeout in your config?

**Comment by AoDev** [comment]
@Axnyff This issue is not easy to reproduce. There is a timeout of 10 sec (10 000) but it is not triggered. Regarding the XMLHttpRequest level, how can I inspect it ?

**Comment by Axnyff** [comment]
What is your fetchData doing? Do you have an easy way to reproduce it natively and check whats happening to the XMLHttpRequest? Otherwise, you could maybe try to make the request object global to see what's happening to it.

How do you reproduce the network cancellation, I don't have an idea of how I should do it

**Comment by AoDev** [comment]
`fetchData` is pulling information from a cryptocurrency exchange called Binance.
Unfortunately, it's hard to reproduce like various people explained in the stackoverflow question I have linked. It works most of the times, but sometimes Chrome cancels the request.

More details about the code of the fetch method:

```
import _axios from 'axios'
import cryptojs from 'crypto-js'
import querystring from 'querystring'

const baseURL = 'https://api.binance.com'

const axios = _axios.create({
  baseURL,
  timeout: 10000,
})

class BinanceApi {
  fetchBalance () {
    const params = {
      timestamp: Date.now(),
    }
    const query = querystring.stringify(params)
    params.signature = this.sign(query).toString(cryptojs.enc.hex)

    const headers = {
      'X-MBX-APIKEY': this.key
    }

    return axios.get('/api/v3/account', {params, headers})
      .then((res) => {
        return transformAccountInfo(res.data)
      })
  }

  sign (queryString) {
    return cryptojs.HmacSHA256(queryString, this.secret)
  }

  constructor () {
    // edited...
  }
}

export default BinanceApi

```

**Comment by AoDev** [comment]
Some user commented the following:

> I have also had horrible problems with this. One thing that I have found that does consistently trigger this if the AJAX response has a status code 301/302 and the redirect URL is on another domain. This is a consistent reproduction of the problem for me. – eb80 Oct 11 '13 at 8:17

**Comment by mattridley** [comment]
I was seeing the same thing with requests chrome cancelled when the machine went into sleep - https://github.com/axios/axios/pull/1399 (which was merged to master) ensures that an error is thrown when the request is aborted so you should start catching these once it is out (not sure when the next release is planned)

**Comment by AoDev** [comment]
@mattridley Awesome. Thank you for your PR. I hope it will be released soon :)

**Comment by kldavis4** [comment]
I think I'm running into a version of this as well. In my case I have basic auth configured on an nginx server and a PUT api request that is updating the basicauth credentials. This seems to be causing nginx to kill the request prematurely resulting in a cancelled request in the browser. I get no error from axios, though.

**Comment by juanr2001** [comment]
![developer_tools_-_http___localhost_8080_](https://user-images.githubusercontent.com/11986307/41413596-8dead45c-6fb1-11e8-9fbb-457209d31f20.png)

I am experiencing the same guys. I would love to know how to fix this... Help!

**Comment by juanr2001** [comment]
Found the solutions issue guys! @AoDev 

Axios documentation has a timeout of 1000
``
axios.create({
  ...,
  timeout: 1000,
  ...
})
``

I increased the timeout to 2000. I think Axios documentation needs to be updated to change the timeout to a higher number to prevent newcomers to go crazy trying to figure out what's going on.

I hope this solutions helps!

**Comment by ZTjack** [comment]
@juanr2001 In my case, my request was be canceled within 4ms.... Sad

**Comment by ZTjack** [comment]
I am using axios-0.18.0, I checked the source file in node_moudles folders, it doesn't got the 'onabort' function ( https://github.com/axios/axios/blob/master/dist/axios.js Here it is). Then I upgrade to axios@0.19.0-beta.1 which contains the code fixing the problem.

**Comment by nobukichi** [comment]
0.19.0-beta.1 fixed a hibernation related problem on Chrome for us.

**Comment by vadymkukhtinOD** [comment]
This problem can be outplayed by setting global axios "timeout" to crazy number like 100000 ms and then request will fail on server side, in my case on Nginx.

**Comment by davidgoate** [comment]
We also have this issue, we want to "gracefully" handle client side timeouts but currently our "success" code is running as out error handlers are not being run when timeouts happen (we have set ours to 30 seconds and want to leave it at that really).

**Comment by zakalwe314** [comment]
A workaround is to use an interceptor with the cancel token.

The example below will add a 30 second timeout on the call.  I've tested this on Chrome (and FF and Edge) and it recovers correctly, by rejecting the promise, after the PC wakes up. 
```javascript
axios.interceptors.request.use(config=>{
    const source = axios.CancelToken.source();
    config.cancelToken = source.token;
    setTimeout(()=>source.cancel('Timed out after 30s'), 30000);
    return config;
});
```

**Comment by zakalwe314** [comment]
Just to add that the solution above may not be compatible with some axios extensions which use interceptors on the response.  For us [axios-retry](https://github.com/softonic/axios-retry) no longer worked with this error because the error object from using the cancel token did not have error.config set (is this a bug?).

To fix this an interceptor can be added on the response as well to catch and fix the lack of the config object which should then allow other interceptors to work.  Note that you need to ensure that these interceptors are added __before__ others such as axios-retry so that the response interceptors are called in the correct order.

```javascript
axios.interceptors.request.use(config=>{
    const source = axios.CancelToken.source();
    config.cancelToken = source.token;
    setTimeout(()=>source.cancel({message:'Timed out after 30s',config}), 30000);
    return config;
});
axios.interceptors.response.use(null,error=>{
    if (!error.config && error.message && error.message.config){
        error.config = error.message.config;
    }
    throw error;
});
```

**Comment by AndyBarron** [comment]
I am also seeing this happen in Axios when Chrome cancels a request due to the machine entering sleep mode. I haven't dug to see if XMLHttpRequest detects this as well.

**Comment by yeyimilk** [comment]
with 0.19.0-beta.1, this error can be captured with 

`ECONNABORTED undefined Error: Request aborted
    at createError (createError.js:16)
    at XMLHttpRequest.handleAbort (xhr.js:71)
10:16:24.016`

**Comment by romankononovich** [comment]
it helped me -> event.preventDefault();

**Comment by ant-peter** [comment]
Hello,

Still the issue exists only in chrome, it works fine in Firefox
