### ISSUE TITLE
How to call method dynamically?

### ISSUE THREAD

**Issue by PhPPgAdminBug** [axios/axios#1430]
I wonder, hot to do something like that

```js
let method = 'post',
   url = 'some_url',
   data = {};
function(method, url, data)
{
   axios[method].(url, data);
}
```

But this gives error, that` method is undefined`.

Thank you.

**Comment by woutrbe** [comment]
Wouldn't it be easier and more readable to do it like this:
```
function(method, url, data) {
    axios({
        method: method,
        url: url,
        data: data
    })

    // or
    axios({ method, url, data })
}
```

**Comment by JustinBeckwith** [comment]
Greetings! This looks like a pretty good answer :)  If you're still having issues... please do let us know!
