### ISSUE TITLE
x-access-token problem

### ISSUE THREAD

**Issue by danielmrd15** [axios/axios#1432]
Hello Team,
I am passing x-access-token in header but it not shows. I am validation the token in backend ,

 Please find me code and attachment. Help me to fix it.

```js

axios({
  method: 'get',
  url: config.API_URL + 'user/permission',
  withCredentials: true,
  headers: {
    'Content-Type': 'application/json',
    'x-access-token': state.tokenid
  }
})
.then(response => {
  if (response.data.status == 200) {
    context.commit('setpermission', { 'permission': response.data.permission })
    resolve(true);
  }
})
.catch(e => {
  console.log(e)
})
```

![screen-error](https://user-images.githubusercontent.com/37148646/37693623-e85814b2-2ce6-11e8-8ffb-7d415ca8953c.png)

**Comment by Axnyff** [comment]
If you're doing a CORS request, only basic headers will be sent, not custom ones. If you want to do that, you'll need to add the header

    Access-Control-Allow-Headers: 'x-access-token'

**Comment by danielmrd15** [comment]
I have added but still its not working..

 axios({
                method: 'get',
                url: config.API_URL+'user/permission',
                headers: {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Headers': 'x-access-token',
                    'x-access-token': state.tokenid
                    }
              })           
              .then(response => {
                  if(response.data.status == 200) {
                    context.commit('setpermission',{'permission':response.data.permission})       
                    resolve(true);    
                  }
              })
              .catch(e => {
                console.log(e)
              })

Can you please share me the sample code..

**Comment by Axnyff** [comment]
Your server needs to send it, currently you're sending Access-Control-Request-Headers, not Access-Control-Allow-Headers, the latter is necessary for CORS requests

**Comment by shahalom** [comment]
Hi, I am also having same issue :(
```
const restURL = '';

const reqData = {
    'params': {
        'posts_per_page': 50,
        'lang': 'bn',
    }
}

const reqHeaders = {
    'headers': {
        'Access-Control-Allow-Headers': 'x-access-token',
        'X-WP-Nonce': 'my-wp-nonce-here',
    }
}

await axios.get(restURL, reqData, reqHeaders)
.then(response => {
    console.log(response.data);
});
```

Anybody please tell me - where I am missing ...

**Comment by Axnyff** [comment]
What are the headers your server is sending?

**Comment by shahalom** [comment]
This issue is solved at https://stackoverflow.com/questions/49680260/axios-does-not-sending-the-header-info-on-get-post-request/

solution is:
```
await axios.get(restURL, Object.assign({}, reqData, reqHeaders))
.then(response => {
    console.log(response.data);
});
```

**Comment by s-kobets** [comment]
Faced the same problem, postman works well, and through localhost it does not work
<img width="612" alt="2018-04-30 11 48 23" src="https://user-images.githubusercontent.com/13196034/39420287-82d71fa2-4c6c-11e8-8178-393dd649b147.png">

**Comment by Axnyff** [comment]
I think you need to specify the origin allowed explicitely, if you're using credentials

**Comment by alenas** [comment]
I had the same problem. It is just misconfiguration with headers or you are not handling OPTIONS request properly. This solved my problem: http://johnzhang.io/options-request-in-express

**Comment by s-kobets** [comment]
Thanks, in my case it was a misconfigured server.
