### ISSUE TITLE
get params problem

### ISSUE THREAD

**Issue by mtdpcs** [axios/axios#1433]
i use axios .get(url, {params: {departmentIds: departmentIds}})
and departmentIds is a Array. 
but it add a [] in the params like below what should i do?
![image](https://user-images.githubusercontent.com/31687990/37702962-25ac5380-2d2f-11e8-93b1-040eac2c94e2.png)

**Comment by woutrbe** [comment]
That's normal behaviour if you're passing an array. What's the format you need to pass it in?
If you need it any other way, like `departmentIds=36,23,28,25`, then you'll need to convert your array to a string.

You can do this, by using `.join`:
```
params: { departmentIds: departmentIds.join(',') }
```

**Comment by JustinBeckwith** [comment]
Greetings!  This is a pretty common issue.  Another way to work around this is to use a different querystring parameterizer, which is actually pretty easy to do!  I use `qs`, which handles arrays quite nicely:
https://github.com/ljharb/qs

Checkout the `paramsSerializer` config option here:
https://github.com/axios/axios#request-config

Please do let us know if you run into any other issues. Good luck!
