### ISSUE TITLE
Content-Type header not being set on Firefox, IE

### ISSUE THREAD

**Issue by johnswu** [axios/axios#1435]
#### Summary
On Chrome, setting Content-Type to 'application/json' is working.  However, in Firefox and IE, Content-Type keeps defaulting back to 'application/x-www-form-urlencoded'.

I've made sure that CORS is opened up on the server all the way.  Here is my code and response and request headers:

```js
let body = JSON.stringify({
  grant_type: 'password',
  username: this.username,
  password: this.password
});

axiosInstance.post('tokens', body, JSON.stringify({
  headers: { 'Content-Type': 'application/json' }
}))
  .then(function (response) {
    console.log("response: " + response);
  })
  .catch(function (error) {
    console.log('An error occurred.' + error);
  });
```

![headers](https://user-images.githubusercontent.com/2731850/37792885-4202d284-2dca-11e8-8740-a458008b7e02.png)

Any help is appreciated, thanks!

#### Context

- axios version: v0.18.0
- Environment: Firefox 58.0.2, IE 11

**Comment by JustinBeckwith** [comment]
Greetings!  By default, Axios will just use `application/json` if you give it the right kind of data.  It looks like you're being a tad overzealous with the JSON.stringify action :)  You don't need to do all that!  Give this a shot:

```js
let body = {
  grant_type: 'password',
  username: this.username,
  password: this.password
};

axiosInstance.post('tokens', body, {
  headers: { 'Content-Type': 'application/json' }
})
  .then(function (response) {
    console.log("response: " + response);
  })
  .catch(function (error) {
    console.log('An error occurred.' + error);
  });
```

If this doesn't work out for you - please do let us know and we'll take another look!
