### ISSUE TITLE
get instead of post

### ISSUE THREAD

**Issue by wowzaaa** [axios/axios#1436]
```javascript
axios({
  method: 'post',
  url: '/finance/operation/'
})
```
this triggers a GET request ... what am i missing? :/

**Comment by Axnyff** [comment]
This does not for me, can you provide some more information : browser / node version, axios version?
What is axios here, directly the imported library ?
Why are you concluding it's a GET request?

**Comment by Axnyff** [comment]
Could it be linked to this : https://stackoverflow.com/a/47209376/4949918

**Comment by JustinBeckwith** [comment]
Greetings!  We're going to need a little more information to help with this one.  Please include:
- A reproducible code sample
- The way you're figuring out this is a get instead of a post :) 

Thanks!
