### ISSUE TITLE
Axios auto cancelled request

### ISSUE THREAD

**Issue by tuananhzippy** [axios/axios#1438]
I'm using Axios in VueJS. I'm having the following problem:

When I call an HTTP Request I get the result is **cancelled**. Although I did not cancel this request.

Please help me !

**Comment by JustinBeckwith** [comment]
Greetings!  Can you please share a snippet of code that reproduces the error? It would be *super* helpful.

**Comment by TranDinhKhang** [comment]
hello, I have the same problems here and don't know why.
I'm using axios with vuejs


![image](https://user-images.githubusercontent.com/17232235/40639106-31d2ee9a-6339-11e8-93e4-dbdd1af4acb2.png)

```
<q-btn
                    v-if="forgotPasswordMode === false"
                    class="q-mr-sm"
                    outline
                    color="secondary"
                    @click.prevent="submitLogin"
                    label="Login"
                  />
```
The button already have @click.event

And the result
![image](https://user-images.githubusercontent.com/17232235/40639118-5690e4d0-6339-11e8-9e66-44e5963da417.png)

**Comment by cyrus3212** [comment]
Try changing axios default timeout from 1000 to 5000

**Comment by biniama** [comment]
Did anyone have an answer to this as I am facing the same issue.

**Comment by biniama** [comment]
> Did anyone have an answer to this as I am facing the same issue.

 I was redirecting to the home page after making `post` api call. The redirecting call was cancelling the previous call. Now, I removed the redirection and it is working perfectly.

**Comment by chinesedfan** [comment]
I think the original problem is that it is timeout, which looks like canceled. For others, please open a new issue to describe your situations, thanks.
