### ISSUE TITLE
catch error when responseType is `arraybuffer` in latest version

### ISSUE THREAD

**Issue by flyher** [axios/axios#1439]
- axios version:  v0.18.0

- Environment:  react-native ,Android

- the code works well and return the right data in v0.16.2, but catch an error in v0.18.0.

```js
axios({
      method: 'post',
      url: url,
      responseType: 'arraybuffer',
      data: postData
    })
   .then((response)=>{
    //todo
   })
  .catch((error)=>{
  //todo
  })
```

link: [#1392](https://github.com/axios/axios/issues/1392)

**Comment by jkunwar** [comment]
hi there, i also have the same problem. Did you find any solution for this.

**Comment by flyher** [comment]
@jkunwar 
I have to keep the old version until the issue be fixed.

**Comment by daton89** [comment]
guys are you sure that you don't generate and error in the then? 

i have a similar problem... 
in my case it go in the then but i don't receive the full arraybuffer i guess.

**Comment by rheinheimer** [comment]
@flyher Thank you!!! I've just spent nearly 12 hours trying to figure out how to download a binary file (Flask + React + Axios + FileSaver). After reading this (starting from #1392) I just went back to 0.16.2 and it works great. So yes, this is an issue.
