### ISSUE TITLE
how can i axios post json data same as jq post json data?

### ISSUE THREAD

**Issue by yyman001** [axios/axios#1440]
#### Instructions

i want to post json string to server,i use jq `post` will sccuess, use axiso `post` will error,
i look this headers content-type and data is differ.

```js
// test data
let sendData = [{"what":"login","when":1522142738820,"who":"drama-material","platform":"web","context":{"browser":{"tz":"+8","lang":"zh-cn","width":1920,"height":1080,"brover":"chrome/65.0.3325.181","os":3,"osver":"Win10","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36","ref":"http://localhost:8080/"},"data":{"rtime":0,"new":0,"lway":0,"c":"drama","sc":"drama","extc":"drama","fc":"drama","cip":"120.236.179.45","uid":"","appv":"","time":1522142738554}}}]

// jq post
        $.post('http://192.168.90.251:8764/common/dotLogController/sendLog', {
          topic: 'topic',
          logs: JSON.stringify(sendData)
        })
          .then((d) => {
          })
          .fail((e) => {
          })
// axios post
        axios.post('http://192.168.90.251:8764/common/dotLogController/sendLog', {
            topic: 'topic',
            logs: JSON.stringify(sendData)
          },
          {
            headers: {
//              'Content-Type': 'application/json'
//            'Content-Type': 'multipart/form-data'
            'Content-Type': 'application/x-www-form-urlencoded'
            }
          }
        )
```
`jq post headers data`
![jquery](https://user-images.githubusercontent.com/5688485/38007411-e098c3a8-327b-11e8-8d98-231529b759a3.png)

`axios post headers data`
this headers data is object ?
![axios](https://user-images.githubusercontent.com/5688485/38007435-fde11564-327b-11e8-9825-6992502ac4ee.png)

i don't know set who content-type ? the send data , when i use content-type need JSON.stringify data ?

`other`
```js
axios.post(this.sendLogUrl, {
      token: this.global.token,
      userId: this.global.userId,
      topic: 'topic',
      logs: sendData
    }, {
      headers: {
        'Content-Type': 'multipart/form-data'
      }
    })
```
![ax2](https://user-images.githubusercontent.com/5688485/38007527-6ee95d70-327c-11e8-80bc-809c22d175ff.png)

Thanks!

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v8.10.0, chrome 64, windows 10*

**Comment by JustinBeckwith** [comment]
Greetings!  At a glance, it looks like you're trying to send a `POST` that contains JSON data, and one of the fields in your JSON is a JSON.stringify-ed string.  That's a little weird to be honest :)  You can probably just `POST` your json without the stringify overhead.  The default content-type with Axios is going to be `application/json`, so this should "just work":

```js
const fakeData = [ { fake: 'data' } ];
const url = 'http://192.168.90.251:8764/common/dotLogController/sendLog';
axios.post(url, {
  topic: 'topic',
  logs: fakeData, // look ma, no JSON.stringify()!
});
```

Of course, that makes the assumption that your server endpoint can handle JSON in the payload instead of `application/x-www-form-urlencoded`.  If your server needs form urlencoded data in the post payload, you could do something like this:

```js
const fakeData = [ { fake: 'data' } ];

const payload = {
  topic: 'topic',
  logs: fakeData,
};

const url = 'http://192.168.90.251:8764/common/dotLogController/sendLog';
axios.post(url, qs.stringify(payload));
```

Hope this helps!
