### ISSUE TITLE
I get duplicate responses on post

### ISSUE THREAD

**Issue by lben** [axios/axios#1442]
I have searched for a while if anyone has experienced this but I haven't found anything on this exact regard.

I have a vue/cordova application where I perform an axios.all post call where _sometimes_ I get duplicated responses. The times this happend I watch the server logs and I can see that the server is sending distinct values but on google's network tab I see that I don't get the same responses the server is returning. In my tests if the server returns 3 different responses _sometimes_ I get two (or even three) duplicate responses. I have tested in chrome and in firefox.

This is a stripped down version of my client code (I only removed unnecessary things):

```js
let solicitudesRequests = []
axios.post(this.endpoint_canal, JSON.stringify(my_object))
      .then((response) => {
        let autorizaciones = response.data
        if (autorizaciones !== undefined) {
          if (!(autorizaciones instanceof Array)) {
            autorizaciones = [autorizaciones]
          }
          autorizaciones.forEach((autorizacion) => {
            let another_object = {
                val1: autorizacion.val1
                val2: autorizacion.val2
            }
            solicitudesRequests.push(another_object)
          })
          return axios.all(solicitudesRequests)
        }
      })
      .then((responses) => {
        responses.forEach((response) => {
          console.log('response obtained: ', JSON.stringify(response.data)) // here I get duplicated data
          let registro = response.data
          if (registro !== undefined) {
            if (!(registro instanceof Array)) {
              registro = [registro]
            }
            this.solicitudes.push(...registro)
          }
        })
      })
      .catch((exception) => {
        console.error(exception)
      })
```

As I said the server is returning different responses but I get duplicated data, what could be the problem here?

Thank you!

**Comment by chinesedfan** [comment]
Closed due to stale and lack of enough information. Please add more codes or screenshots, instead of human descriptions.
