### ISSUE TITLE
New config param: arrayFormat ?

### ISSUE THREAD

**Issue by today-** [axios/axios#1443]
#### Summary

Now when i send an array in GET request 
`axios.get('/url', { id: [1, 2, 3] })`
I receive this path: `/url?id[]=1&id[]=2id[]=3` and it's not configurable.

But some target servers (with strong typed languages) wants another format (without braces after param name): `/url?id=1&id=2id=3`

> https://stackoverflow.com/questions/3061273/send-an-array-with-an-http-get

And now I have to use `paramsSerializer` (right this case is mentioned in README), and even to use another package (Qs).

But I found in `buildURL` function than brackets is added forcibly, and it's quite easy to add options param to handle it.
> https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js#L43

#### Context

- axios version: 0.18.0
- Environment: chrome 65

**Comment by JustinBeckwith** [comment]
FWIW, I needed to swap out the default qs serializer in here for `qs` as well.  This would be a valuable feature IMO.

**Comment by mattsawyer77** [comment]
On node 10.6, I just tried using the built-in `querystring` API for the `paramsSerializer`, and it seems to encode the array correctly. 

https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options

**Comment by pzanitti** [comment]
If there is no standard/RFC that defines this, why was it decided that `[]` should be used? I understand a custom `paramsSerializer` can be implemented, but the current implementation shouldn't be opinionated.

I used this solution, unfortunately it requires an additional package for something that perhaps can be fixed with a simple toggle config.
https://github.com/axios/axios/issues/559#issuecomment-264689998

**Comment by bertho-zero** [comment]
I think I fix it here: https://github.com/axios/axios/pull/1565

**Comment by AuthorProxy** [comment]
up

**Comment by parker789** [comment]
Also would like to see a better solution for this.

**Comment by chinesedfan** [comment]
Really understand that users want everything out-of-box. But axios has its own design principle, which means simple and focused. Hope someone can list where those two formats come from, and let's choose the more standard one.

**Comment by determin1st** [comment]
the better solution is to use JSON array with `application/json` content-type.
Especially, **new servers** (no matter typed or not) should use more advanced (than form enctype) exchange..

**Comment by jasonsaayman** [comment]
On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the qs library:
```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

**Comment by codingyourlife** [comment]
I have a problem with the by @jasonsaayman mentioned approach...

`param=value1&param=value2` on C# backend correctly maps to param[] array. but param=value1 does not!

Not sure yet how to solve this. Anyone?

**Comment by anton-johansson** [comment]
> On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

I'm not sure I fully agree. There is nothing in the specification that says that these parameters should be suffixed with brackets (neither is there anything that says that it shouldn't), which makes this very opinionated (as mentioned previously).

Fixing this by adding the `qs` package works, but it feels like an unnecessary thing to do when it would be a very simple configuration flag in Axios itself. The fewer dependencies the better, in my view.

I could rely on the native Node.js `querystring` package, but there's two issues with that:
* I'm using TypeScript, and the native function does not accept `any`, which is what Axios "provides".
* It's deprecated in favor of the `URLSearchParams` API, which also does not seem to work well with an `any` object.

I could also replicate the entire function [that Axios has by default](https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js#L35-L58), but that also feels like a very inconvenient way of handling this.

Could you consider re-opening this issue? :smiley:

**Comment by julianmarmier** [comment]
For those like me that are just now stumbling upon this thread, the bracketless format can now be configured:
```
axios.defaults.paramsSerializer = {
  indexes: null,
};
```

**Comment by jasonsaayman** [comment]
need to check if this in the docs @DavidJDallas

**Comment by jasonsaayman** [comment]
closing due to being very stale, if this is still relevant please open a new issue
