### ISSUE TITLE
Set-Cookie is not working for cross domain request

### ISSUE THREAD

**Issue by chao00440** [axios/axios#1444]
Set-Cookie is not working properly after deployed my backend code on heroku, it is working fine in local server.   It is sent by server, see the screenshot below
![image](https://user-images.githubusercontent.com/23326144/38138795-a8521b54-33fa-11e8-9fab-7e1458b92ac6.png)

Here is my setting for
server:
res.setHeader('Access-Control-Allow-Origin', 'http://localhost:8080');
res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
res.setHeader('Access-Control-Allow-Credentials', true);

client:
axios.create({
    baseURL: `http://localhost:3000`,
    withCredentials: true
  })

**Comment by fanweiGit** [comment]
我也遇到了这种问题，请问您解决了吗~

**Comment by chao00440** [comment]
@fanweiGit 
you actually need to enable proxy:

...
app.enable('trust proxy'); // optional, not needed for secure cookies
app.use(express.session({
    secret : 'somesecret',
    store : ..., // store works fine, sessions are stored
    key : 'sid',
    proxy : true, // add this when behind a reverse proxy, if you need secure cookies
    cookie : {
        secure : true,
        maxAge: 5184000000 // 2 months
    }
}));
...

more on https://stackoverflow.com/questions/14463972/how-to-set-secure-cookie-using-heroku-node-js-express
