### ISSUE TITLE
Missing properties/functionality  from new instance

### ISSUE THREAD

**Issue by EZarkov** [axios/axios#1445]
#### Summary
After creating new instance with `axios.create()` few properties are missing 
`Cancel`, `CancelToken`, `isCancel`,  `all`, and `spread`

```js
import axios from 'axios';

const instance = axios.create();

instance.defaults.headers.common['Authorization'] = AUTH_TOKEN;

console.log(axios.Cancel === undefined);
console.log(axios.CancelToken === undefined);
console.log(axios.isCancel === undefined);
console.log(axios.all === undefined);
console.log(axios.spread === undefined);

console.log(instance.Cancel === undefined);
console.log(instance.CancelToken === undefined);
console.log(instance.isCancel === undefined);
console.log(instance.all === undefined);
console.log(instance.spread === undefined);

```
I am not sure is this a bug or request for new feature, but it is confusing default instance to have exposed functionality which is missing in new instance.

https://github.com/axios/axios/blob/v0.18.0/lib/axios.js

Maybe exposing `Cancel`, `CancelToken`, `isCancel`,  `all`, and `spread` should be 
placed inside `createInstance` method

#### Context

- axios version: *v0.16.2*

**Comment by EZarkov** [comment]
use strict';

var utils = require('./utils');
var bind = require('./helpers/bind');
var Axios = require('./core/Axios');
var defaults = require('./defaults');

/**
 * Create an instance of Axios
 *
 * @param {Object} defaultConfig The default config for the instance
 * @return {Axios} A new instance of Axios
 */
function createInstance(defaultConfig) {
  var context = new Axios(defaultConfig);
  var instance = bind(Axios.prototype.request, context);

  // Copy axios.prototype to instance
  utils.extend(instance, Axios.prototype, context);

  // Copy context to instance
  utils.extend(instance, context);

  instance.Cancel = require('./cancel/Cancel');
  instance.CancelToken = require('./cancel/CancelToken');
  instance.isCancel = require('./cancel/isCancel');

  return instance;
}

// Create the default instance to be exported
var axios = createInstance(defaults);

// Expose Axios class to allow class inheritance
axios.Axios = Axios;

// Factory for creating new instances
axios.create = function create(instanceConfig) {
  return createInstance(utils.merge(defaults, instanceConfig));
};

// Expose all/spread
axios.all = function all(promises) {
  return Promise.all(promises);
};
axios.spread = require('./helpers/spread');

module.exports = axios;

// Allow use of default import syntax in TypeScript
module.exports.default = axios;

**Comment by EZarkov** [comment]
Sorry it was miss click

**Comment by tungvn** [comment]
I often code like this, maybe instant fix
`instance.isCancel = axios.isCancel`

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios/pull/1482#issuecomment-578027382.
