### ISSUE TITLE
timeout not cleared on error

### ISSUE THREAD

**Issue by cztomsik** [axios/axios#1450]
#### Summary

When request is made and network error occurs, timeout is not cleared. It should be easy to replicate:

```js
// disconnect from network before running
const axios = require('axios')
axios.get('http://github.com', { timeout: 1000 })
```

This script should fail and instantly quit but it will rather fail and hang for 1s

#### Context

- axios version: 0.18.0
- Environment: node

**Comment by JustinBeckwith** [comment]
Greetings!  I just wrote up a little test, and it appears that this is working exactly how I'd expect it to:

```js
const axios = require('axios');
const nock = require('nock');

const url = 'http://funkyfreshyo';

nock.disableNetConnect();

const start = Date.now();
axios.get(url, { timeout: 1000 })
  .then(r => console.log)
  .catch(e => {
    const end = Date.now();
    const diff = (end - start)/1000;
    console.error(e.code);
    console.log(`✨ that request took ${diff} seconds ✨`);``
  });
```

If I run this, I get:

```
beckwith-macbookpro:ax beckwith$ npm start

> ax@1.0.0 start /Users/beckwith/Code/ax
> node server.js

ENETUNREACH
✨ that request took 0.006 seconds ✨
```

It does the same if I get rid of the nock stuff and just disable my network.  Is it possible you have a proxy or something that's not immediately timing out?  What happens if you disconnect your network and try to hit that url in your browser?

Am I misunderstanding what you're trying to do?  Thanks!

**Comment by cztomsik** [comment]
I've simply disabled wifi on my macbook, maybe it is platform specific? Also, I had different error. 

```
node test_axios_disconnect.js 

node:61410) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND github.com github.com:80
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
(node:61410) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:61410) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cztomsik** [comment]
Do you need any additional info? How can I help with this?

**Comment by wholegroup** [comment]
@JustinBeckwith I have the same issue
The issue is that a request is completed in time but then a node process is hanging up during `timeout` before exiting.
I suppose there is some issue with clearTimeout if an exception occurs.

Please re-open this issue.

**Comment by wholegroup** [comment]
@JustinBeckwith I've executed you example with `time` utility:

```
user@dron:~/Projects/scanner$time node src/server.js 
ENETUNREACH
✨ that request took 0.007 seconds ✨

real    0m1.191s
user    0m0.167s
sys     0m0.026s
```

The script was running during about 1 second (like `timeout` value)

**Comment by feaber** [comment]
@cztomsik have right, there is some issue when You set timeout and error occur for node.

Try set: timeout: 300000

In normal situation script in node will pass from begining to end and node exit. But if during execution axios throw error, even if I handle the error and code goes to end - node will not exit until timeout time pass.

You can test more with this: https://github.com/mafintosh/why-is-node-running

**Comment by cantremember** [comment]
i am also seeing this same problem.  i am using `nock` to intentionally go through an Error handling scenario in my code -- using `replyWithError` -- and the Error is dispatched as expected, but as described above, Axios will not allow the Test Suite to terminate until after the full timeout has expired

if i explicitly put a `{ timeout: N }` value into the Axios request, it suspends the Test Suite until N millis have passed even after the Error has been rejected / dispatched back to the caller

`process._getActiveHandles()` tells me there's a pair of suspended `WriteStream`s and a `Timer` during this time period.  that's a bit vague, but it would line up with the theory that the timeout isn't being cleared in this scenario / upon Error
