### ISSUE TITLE
Axios Network error when server responds with 200

### ISSUE THREAD

**Issue by txssseal** [axios/axios#1453]
Currently Axios will error/catch when my server sends back a proper 200 request.  Below is the code snippet.  Note:  I have used both .then and .catch, and the .then callback methods like code below.  Both continue to go to error.

Note: Cors/OPTIONS request and following put request both come back as 200's.

ERROR:
```
Error: Network Error
Stack trace:
FtD3/t.exports@http://localhost:3003/static/js/vendor.c93154f01cb54d35b123.js:6:88982
7GwW/t.exports/</f.onerror@http://localhost:3003/static/js/vendor.c93154f01cb54d35b123.js:6:8668
```

```
  axios.put(`${process.env.API_URL}/login`, {email: this.email, password: this.password})
          .then(resp => { // Success
            console.log(resp)
          }, error => { // Failed
              console.log('there is an error', error);
          });
      }
```

**Comment by B-3PO** [comment]
@txssseal looks like your code is outputting errors from your packages code. If you add source-maps to your build, you might find the actual location of the error.
