### ISSUE TITLE
Error: Request failed with status code 413

### ISSUE THREAD

**Issue by ananth10** [axios/axios#1454]
When i try to upload image as base64 i am getting 413 error code. can anyone help me to resolve this?

**Request** 

```js
axios.post(Constants.BASE_URL + 'funInsertImage', {
  "Token": token,
  "Itemcode": "206",
  "ImageName": "RedShirt",
  "ImageString": this.state.base64String,
}).then(function (response) {
  console.log(response.data)
}).catch(function (error) {
  console.log(error);
});
```

Error:

04-05 10:10:19.188  2894  6313 I ReactNativeJS: { [Error: Request failed with status code 413]
04-05 10:10:19.188  2894  6313 I ReactNativeJS:   config:
04-05 10:10:19.188  2894  6313 I ReactNativeJS:    { adapter: [Function: xhrAdapter],
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      transformRequest: { '0': [Function: transformRequest] },
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      transformResponse: { '0': [Function: transformResponse] },
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      timeout: 0,
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      xsrfCookieName: 'XSRF-TOKEN',
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      xsrfHeaderName: 'X-XSRF-TOKEN',
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      maxContentLength: -1,
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      validateStatus: [Function: validateStatus],
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      headers:
04-05 10:10:19.188  2894  6313 I ReactNativeJS:       { Accept: 'application/json, text/plain, */*',
04-05 10:10:19.188  2894  6313 I ReactNativeJS:         'Content-Type': 'application/json;charset=utf-8' },
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      method: 'post',
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      url: 'http://38.227.378.2:78/api/funInsertImage',
04-05 10:10:19.188  2894  6313 I ReactNativeJS:      data: '{"Token":"YDx45R0toJs=--EmZ1Es5JYLFtdvr/1qbwVw==","Itemcode":"206","ImageName":"RedShirt","ImageString":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJ
ChQODwwQFxQYGBcU\\nFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgo\\nKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCALQAtADASIA\\nAhEBAxEB/8QAHQAAAQUBAQEBAAAAAAAAAAAAAgABAwQFBgcI
Cf/EAFIQAAEDAgQDBQUEBwQGCAYC\\nAwEAAgMEEQUSITEGQVEHEyJhcRQygZGhI0KxwQgVM1JictEkgpLhFiVDU6LwFzRFY3ODsvFEVWR0\\nlMI1hJPS4v/EABsBAAMBAQEBAQAAAAAAAAAAAAABAgMEBQYH/8QAOBEAAgIBBAEDAwEIAQMDBQAA\\nAAECEQMEEiExQQUTUSIyYXEUIzNCgZGhsVIG
JPBTYsEVQ9Hh8f/aAAwDAQACEQMRAD8A6AoSESB1\\n8q8M+6RHuUyexT2uTbZQWCknsQkgBkkkkDEkkkgATe6ZH8ECBoScEJkghoYQukmCdS+GIdJME4TT\\nEOPNPZCE4OqYgt7gpwLJckkhC5pJJckAJJJJACSTXTpgOibcndMNUgVYiWx12TjoU3JOPNQUEN/V\\nEhb9EQQJji19UajRjbVUSx0k
kkhDtKkUY3UgWkCWENl23BTf9WTHrJ+S4kLuuDm2wZx6yFd2jX7w\\n8z1N1gf6m2EXQ/RNci3knABGuw5r1j5wbmnA0udkYsLAfVC/QDZKwoE25JkkkxCT2KZOL8r3QAQF\\nwDdSsJbbVA2yNNDSIauhiqyXssyfryd6rFljdG8skaWuGhBXQg2Q1NOysZZ/hkHuuUtUPo5p7bKM\\nq1UxPhlLJG2c
PqoCy+yTNEzCqf27zuLrg+JsDqMKrRjuAjK9hvNCNiOenRegVA8TtOahGnK4OhB2\\nKwumdrjaMzhrG6fGqBtTTmzh4ZIzux3RbfvC+45hcbJw1UYfxG3FMBmZFBIPt6Z+zvILq4JJT/ss\\nvqU06IcW1ZbhnMTrPNmciVr0oilAklDSxviu4bea5utnpKVgnxKWMRM8WU9fTcrzbj/tYZTRmlwo\\n
aHQdT5noPJWmYTi+z03H6GnqKaSWJjZ6SUFkjLaEcwvn7ibAq3hriSmZhRkkhqZM9HK3duuoJ5Fq\\n9W7Eq2txOhqJal5dQS+N4k+6ebgixeN9ZWT9zGxtG2W8AOrjYWzeV9VjqXsVrk6tJD33tk6DFVUV\\njI5qxwfUljRI4CwcQNSiaLnyUVLDKPBlWhHSyBurV46hOTto+j344LbF9FKVpaHA2sv
J+1WQDCIG\\n31fI42XrtZC9sTnuFg1puvFe1iS0OHRcy0uPzXr6GLUJt/g+Q/6gyKep08F43P8AwecOFhsq6mfo\\noVtI5BxZTNpnVc1NAzVzyGt9SVCFu8Kw9/xLhcYH+1CjyXHo6Wm7I8UlaCXwtuL+8rzOxqvPvTwC\\n/Ur1XFcQqsOkpWUlN7Q1wLpGtNnWFtvmpcGxOtrIMQkqYGxOhfaOMan
3QdT11XanC62r/Iqlt3Hl\\nTexiq51UIKlZ2Myg+Ksj+V16bDjNbFD/AGije54bmc46BvlorJr6qfDoamng8bn5SwXOh56hXx/x\\nRG5nl7Oxn96tb8GqaPsbht4q3/hXocmI4mWTMgoXXbdrXlhN7DeykjqcWja/PSCQXc5rg3lrYeuy\\nXHwv7BbPPWdjlIPeq3H+6po+x3Dh71VIR6LvqmXFXNp
XwUxDmjNKwEAG/JQ1cmOua1rIGAgg5m6A\\n87HXRF/hf2DczjW9kGFfeqJfgApmdkuDN96SV3yXYv8A13qO5idl56C/mNfVBJSYtJRNYCBOXmRx\\nc+xsNhojc/x/ZBZy7eyjAhv3p+KlZ2W4C3dsh+K34WY3VPglOWONsl3tNs2Xy/zWxWR1RgkbTOZ3\\np9wnSye+QWcczsy4fb/sH+t1Mzs54fb
p7Nd3K7l09DS1kQPtEgcSbk3uqfEOGVmItiFFMKd0dyZQ\\n4guH7noeqe9/IjIb2f8AD7W3FG0jnqvnrGYy/H62noWnIJ3NjaOlzZfVjWClw45mBndREloNwLDq\\nvlnBauGLiNtXVuyxCUvcd+axzSbjyFtJtEFTgmK00Jlnp5I4xqXEWWaRM6J0ga90bCA54GgJ816T\\nxnxPhmIYVUQ0UpdJIRu
22gXLYVj1Lh2HNpHUHfDMJXuL/ecHAjTa2lviVgkn5DFOUk7R9GIH+SNA\\n+9l86foCBvoPzTtNwEJuRqETPdCSKHsgd9EZ20QkeabQIH8U1k5/FK3VSMZJJJAxJjsnTFAIFOkE\\n34psoNuTXNe1tLdUI3TBF9QpYhJ0ySlCHG6MfVAnG11YmEb9U42TXvySBukIdJJJACSskkgBJBLc\\nJxoqSAc
bp27lL4omblNiQaSYJ1JQTd7lEhaiQJiUg2UaNu2qZLHSSRcwgQgNUbd7IbJwbG6qJL5J\\nbFd5wmMuCM85HFcI1tx5LvuGwRgsFtiSV6WjX12eV6o/3Nfk1B0RW0vr6hM23NOHaAL1D55BXsNN\\nz1Qu90dEgNdeSJwswJAR7FLdPufzTnZMQwRaDmmvY3siABQA7eqNABZEhOikOnGhQtAAsBYBPv
oq\\nsB6iBlZFkfo8e65c/NC+CZzHixC6DYIKksdE9z2AljCbn0USVDj2cJO3U+qrOIGhVJz3lxu4/NCQ\\nSdSV5MtWr4R9FDQtdsu5wOaWfz+SolvqgkDg3wucElq/lFvRfDIuKMGbjWHvbC7uqto8Lhs8fule\\nYUvZe2KqFVi9THTULneJsh1v0816PUzTsacsrh5hcni9NJiGN4XFNI6RvfBxBN
9lrDU2+EZZND9F\\nyfCO4pZKfDcMjw3CGZKVtg53N/8AkpZGAFoHTZFDTDO1o5laNZSiF1yN+ap3LlnMtuP6YmdTRgTE\\nneytb7KIENJJCRftZCoHZSxx+TDKl2ujCvn/ALWJL4nSxfuQhe7cQVDDh8zA8ZnWaRfzXz32nS95\\nxK8fuMDfouvE/wB2/wBT53XW9fBfEW/7s5CS2VR+iKRCnVlsVj
Zdj2bQ99x1hzSLhviNvRcdu5o9\\nAvQ+x2LPxq55FxFC5Sl9SNL4PfxHC2zntbmGgJGqmhbGb92GAk3NhuqdXW01AYW1DmuqZjZjC4An\\nqddgFcJh

**Comment by JustinBeckwith** [comment]
Greetings!  An `HTTP 413` is a "Payload too large" error:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413

This error is returned from your server when the contents of your post (a big ol' base64 encoded string in this case) is too big.  This is an option that's typically configured on the server, and can't be changed from the client (axios in this case). 

Hope this helps!

**Comment by ananth10** [comment]
@JustinBeckwith .Yes you were right. we have fixed it now . thank yu

**Comment by biranchi2018** [comment]
> @JustinBeckwith .Yes you were right. we have fixed it now . thank yu

Can you plz explain how you have fixed ? I am also facing the same issue.

**Comment by rodriguezmanu** [comment]
+1
