### ISSUE TITLE
axios.get  params  Carry coals to Newcastle

### ISSUE THREAD

**Issue by xingzheone** [axios/axios#1455]
```
axios.get('/yt/resources/tree', {params: {query: this.query, status: this.status}}) 
```
why??  
```
axios.post('/yt/resources/tree',  {query: this.query, status: this.status}) 
```
Why is there one more params 👎

**Comment by JustinBeckwith** [comment]
Greetings!  I'm not entirely sure what you're asking :)  These two pieces of code do very different things.  When you issue an `axios.get`, the second parameter contains the Request Config options you can find here:
https://github.com/axios/axios#request-config

The `params` option will encode data into the querystring, like this:

```js
axios.get('/page', { params: { hello: 'world' } });
```

Will make a `GET` to `/page?hello=world`.

When you issue an `axios.post`, the second parameter in the function is the **data** you want to send in the post payload.  

Hope this helps!
