### ISSUE TITLE
When the auth property is set, the data data is disappearing

### ISSUE THREAD

**Issue by yudan215** [axios/axios#1467]
`return request({
    url: 'http://192.168.2.227:8100/uuas/oauth/token',
    method: 'post',
    data: {
      grant_type: 'password',
      username: 'admin',
      password: 'password'
    },
    auth: {
      username: 'test',
      password: 'XXXXXX'
    }
  })`

As long as the auth is set, the transfer of the data parameter is not valid

**Comment by chinesedfan** [comment]
Closed due to lack of enough information. Maybe you can elaborate "the transfer of the data parameter is not valid".
