### ISSUE TITLE
Need a property similar to textStatus as in Ajax XHR object in jQuery Ajax

### ISSUE THREAD

**Issue by chandarsunderraj** [axios/axios#1468]
Is there any property in axios which returns the textStatus property as in **jQuery Ajax XHR Object**

**Comment by DrewBe121212** [comment]
The full XHR response is available under the 'request' key. 

```js
.then((response) => {
      console.log(response.request.statusText
})
```

**Comment by chandarsunderraj** [comment]
@DrewBe121212  Thanks for the swift reply.

Is this the same textStatus as in ajax Events which returns ("success", "notmodified", "nocontent", "error", "timeout", "abort", or "parsererror").

Reference :  http://api.jquery.com/jquery.ajax/

**Comment by chinesedfan** [comment]
@chandarsunderraj Yes, I think. Because both axios and jQuery are based on XHR.
