### ISSUE TITLE
response something wrong with the github get file content api

### ISSUE THREAD

**Issue by ZEROKISEKI** [axios/axios#1471]
#### Summary

<img width="836" alt="2018-04-10 16 16 47" src="https://user-images.githubusercontent.com/9923459/38545390-8422c84c-3cdc-11e8-87f0-df25b4b02dc2.png">

You can see that the first console url is `https://api.github.com/repos/localForage/localForage/contents/README.md`, and the `data` attr is an object like the github api development document described:

<img width="834" alt="2018-04-10 16 32 55" src="https://user-images.githubusercontent.com/9923459/38545539-d831cce4-3cdc-11e8-848e-64769019d092.png">

The second console url is `https://api.github.com/repos/atatanasov/gijgo/contents/README.md` and the `data` attr is null, firstly I think maybe is github's problem. However, I try to get the `https://api.github.com/repos/atatanasov/gijgo/contents/README.md` in my browser and postman, both they return the correct results like that:

<img width="1137" alt="2018-04-10 16 37 12" src="https://user-images.githubusercontent.com/9923459/38545783-7261b284-3cdd-11e8-8107-d433e0a61e37.png">

<img width="1380" alt="2018-04-10 16 40 53" src="https://user-images.githubusercontent.com/9923459/38545984-f92ae8da-3cdd-11e8-8e2d-196a4963aa6d.png">

And the code using axios to request api is that:

```
return axios.create({
    baseURL: 'https://api.github.com',
}).get(`/repos/${owner}/${repo}/contents/${path}`).then(res => {
    console.log(res)
}, err => err)
```

Could you find out how to solve the problem? And this is the [github get file content api document](https://developer.github.com/v3/repos/contents/#get-contents).

#### Context

- axios version: v0.18.0
- Environment:  electron, macOS

**Comment by castamir** [comment]
@ZEROKISEKI what was the issue?
