### ISSUE TITLE
The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType

### ISSUE THREAD

**Issue by nbcnc** [axios/axios#1474]
#### Summary

I literally copied and pasted the "stream" example and I get the following error:

```
// GET request for remote image
axios({
  method:'get',
  url:'http://bit.ly/2mTM3nY',
  responseType:'stream'
})
  .then(function(response) {
  response.data.pipe(fs.createWriteStream('ada_lovelace.jpg'))
});
```

<img width="825" alt="screen shot 2018-04-10 at 1 44 05 pm" src="https://user-images.githubusercontent.com/27741514/38573850-450e66f0-3cc5-11e8-8aab-8cc6b0e476ea.png">

#### Context

- axios version: v0.17.1
- Environment: node v8.2.1, Electron 1.8.4

**Comment by chadams** [comment]
I'm getting this exact problem.

**Comment by chadams** [comment]
@nbcnc I figured it out, your making an electron app like me. seems you can only get the response.data as a stream in the main thread. What I did to fix this was add
 ```javascript
ipcRenderer.send("download"); // in render thread
```

then in the main thread

```javascript
app.on("ready", async () => {

  mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728
  });
 mainWindow.loadURL(`file://${__dirname}/app.html`);

 ipcMain.on("download", (event, arg) => {
   // axios download code here
 });
```

good luck

**Comment by cgomezmendez** [comment]
I'm getting the same error, I'm using it in a rect-native application.

**Comment by affanshahid** [comment]
Getting this in the browser, compiled using CRA (webpack)

**Comment by bintoll** [comment]
I am getting this in simple node app

**Comment by gcox** [comment]
@bintoll Are you using jest? If so, that's probably the issue...see this comment: https://github.com/axios/axios/issues/1418#issuecomment-373386206

**Comment by zeevl** [comment]
For electron users, try this from the render process:
```
axios.defaults.adapter = require('axios/lib/adapters/http');
```

This forces axios to use the node adapter.   See https://github.com/axios/axios/issues/552

**Comment by GuilhermeAbacherli** [comment]
I'm getting this error in web using Vue.

> The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType.

`      axios.request({
        method: 'POST',
        url: 'http://apilink/endpoint',
        data: form,
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        responseType: 'stream', // HERE
      })
        .then(response => {
          console.log('LOGIN response', response);
        })
        .catch(error => {
          console.log('LOGIN error', error);
        });`

![image](https://user-images.githubusercontent.com/32586058/59456542-f0026d80-8dec-11e9-8656-16805f39b66c.png)

- Axios version in package.json: "axios": "^0.19.0";
- Vue version in package.json: "vue": "^2.6.10";

**Comment by smilexu** [comment]
Got same error in React App
Axios version : 0.19.0

**Comment by Monasha1992** [comment]
For React , try using this in [https://github.com/axios/axios#request-config](here)

```
  // `onDownloadProgress` allows handling of progress events for downloads
  onDownloadProgress: function (progressEvent) {
    // Do whatever you want with the native progress event
  },
```

**Comment by fazulk** [comment]
This issue is still happening, is there any other way to get streams through axios?

**Comment by chinesedfan** [comment]
As far as I know, `responseType=stream` is not supported in the xhr adapter, including browsers and situations that users config it explicitly/implicitly. Closed in favor of #479.

**Comment by wbjqiqi** [comment]
someone may still tips error``

**Comment by janswist** [comment]
I also have exact same error. Two years and no response doesn't look promising.
