### ISSUE TITLE
Failed to load bundle After fresh install of axios

### ISSUE THREAD

**Issue by chathuralakmal** [axios/axios#1477]
i just init react-native project and installed axios.

`+ axios@0.18.0`
`added 2 packages, removed 1099 packages and updated 3 packages in 26.591s`

 in my previous projects it worked fine. but today im getting this error.

`
jest-haste-map: watch error:
  Error: ENOENT: no such file or directory, open '/Users/Mac/Developer/ReactNative/node_modules/metro/node_modules/jest-haste-map/build/worker.js'
`

`error: bundling failed: Error: ENOENT: no such file or directory, open '/Users/Mac/Developer/ReactNative/node_modules/react-native/Libraries/Network/XMLHttpRequest.js'`

**Comment by haithai** [comment]
The same issue with me !!!

**Comment by chinesedfan** [comment]
It is a common error of RN. Just try to clear build files and node_modules and retry.
