### ISSUE TITLE
How to build the latest version of axios manually? ?

### ISSUE THREAD

**Issue by d7laungani** [axios/axios#1481]
#### Summary

Describe your issue here, including as much detail as necessary.
New code was merged in that I want to use. There is not a latest release so how to I build it. Specifically how can I install the master branch in my package.json

#### Context
- Environment: React Native 0.25

**Comment by emilyemorehouse** [comment]
I'm hoping you were able to figure this out.

There's also a new beta release that can be installed using `npm install axios@0.19.0-beta.1` or `npm install axios@next`
