### ISSUE TITLE
Url encoding of backtick ("`") character in query strings

### ISSUE THREAD

**Issue by ethanresnick** [axios/axios#1483]
#### Summary

This issue is the same as https://github.com/visionmedia/superagent/issues/1367, and is driven by the same underlying cause (reliance on the built-in `url.parse`) and has the same basic fix (surfacing the WHATWG URL api). 

Code example is just:

```
axios.get('http://example.com/?test=`value`')
```

Result: backticks around "value" get percent-encoded, arguably improperly and with no way to override. See linked issue for details.

#### Context

- axios version: v0.18.0 
- Environment: node 8, mac osx 10.13.4

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks
