### ISSUE TITLE
How to send as Uint8Array

### ISSUE THREAD

**Issue by r8code** [axios/axios#1486]
#### Summary

Does anyone know anyone know how to send the data as Uint8Array ?
I'm trying to send to server a Uint8Array  , but when i check in chrome form data shown my Uint8Array as String , If I using Jquery ajax it can send as Uint8Array , is there i can do with axios ?

Thanks

#### Context

- axios version:  v0.18.0
- Environment: chrome 65

**Comment by vtkumaresan** [comment]
is that resolved ? can some one give the solution for this.

**Comment by chinesedfan** [comment]
Closed due to lack of enough information. The question is too wide and hope you guys can provide some example codes. The internal API of axios is [XMLHttpRequest send](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send) in browsers.
