### ISSUE TITLE
Network error is not handled

### ISSUE THREAD

**Issue by alesisjoan** [axios/axios#1488]
#### Summary

I tested doing a GET to a server that is **not online** as follows:

`                
        try {
axios.get('http://localhost:8888/hem_auditoria_medica_odoo',
                    {headers: {'Content-Type': 'application/x-www-form-urlencoded'}}
                ).then((response) => {
                    if(response){
                        alert("OK");
                    }else{
                        alert('NOT OK');
                    }
                }).catch(function (error) {
                    alert('NOT OK.');
                });
        } catch (err) {
            alert('NOT OK.');
        }
`

but the error is not handled as expected. It happens an error in createErros.js:16

Full log is:

> xhr.js:178 POST http://localhost:8888/hem_auditoria_medica_odoo net::ERR_CONNECTION_REFUSED
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:59
Promise.then (async)
request @ Axios.js:51
Axios.(anonymous function) @ Axios.js:71
wrap @ bind.js:9
sendAjax @ Result.js:41
boundFunc @ ReactErrorUtils.js:63
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:69
executeDispatch @ EventPluginUtils.js:83
executeDispatchesInOrder @ EventPluginUtils.js:106
executeDispatchesAndRelease @ EventPluginHub.js:41
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:52
forEachAccumulated @ forEachAccumulated.js:22
processEventQueue @ EventPluginHub.js:252
runEventQueueInBatch @ ReactEventEmitterMixin.js:15
handleTopLevel @ ReactEventEmitterMixin.js:25
handleTopLevelImpl @ ReactEventListener.js:70
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v9.10.1, chrome 65, Linux Mint Rosa 17.3*

**Comment by gboxall** [comment]
Same for a request that has been blocked by a CORS policy.

**Comment by memo-rebolledo** [comment]
I've also come across this issue before. In some cases even when I had a server error it showed as if it were blocked by a CORS policy.

**Comment by andrewriveraj** [comment]
I suggest using a CORS Proxy such as crossorigin.me or CORS anywhere. prefix your API call with the CORS proxy. ex.
async function getResults(query) {
    const proxy = https://cors-anywhere.herokuapp.com/
    const result = await axios(`${proxy}FollowedByYourAPIEndPointHere}`);
}

**Comment by chinesedfan** [comment]
A simple `NOT OK` is alerted. It works as expected.

**Comment by rolandin** [comment]
> I suggest using a CORS Proxy https://github.com/Rob--W/cors-anywhere

How do I use that ?  In the read file just says to use a function, where?  can't find a video of somebody using it
