### ISSUE TITLE
Catch Authorization error caused by 307 redirect

### ISSUE THREAD

**Issue by yowzadave** [axios/axios#1490]
#### Summary

I want to make a GET request to an endpoint that
- requires an 'Authorization' header that includes a hash of the endpoint URL
- has a 307 redirect to a different URL (which will require a newly computed 'Authorization' header)

What would be the correct way to detect when this redirect has occurred and update the header accordingly? If I `catch` the error that results (because of the authorization error), I can see that `error.request.res.responseUrl` shows the new URL.

#### Context

- axios version: 0.18.0
- Environment: node v9.4.0

**Comment by chinesedfan** [comment]
Yes, catch directly or use a response interceptor, then check `error.response.status`.
