### ISSUE TITLE
axios auth some error for Authorization: Basic 

### ISSUE THREAD

**Issue by BeanWei** [axios/axios#1496]
I get the half-baked Authorization
such ：
      auth ：{
         name： ‘test’，
         user: '123123'
}
Then make a post request, But I get the  Authorization: Basic OjEyMzEyMw==
OjEyMzEyMw==  is “：123123” ,the name is lost. It's too weird

**Comment by zcei** [comment]
Hej @BeanWei,

where did you get those object keys from? 🤔 
In order to have Basic auth working as expected, the `auth` object needs to look like this:

```js
{
  username: 'test',
  password: '123123'
}
```

**Comment by BeanWei** [comment]
Okay,it's means that the auth object  needs the keys must be username and password,right...?

**Comment by zcei** [comment]
Yes, it's defined [here](https://tools.ietf.org/html/rfc7617) to be a "pair of user-id and password" and axios uses `username` as the identifier for the user-id:

https://github.com/axios/axios/blob/0b3db5d87a60a1ad8b0dce9669dbc10483ec33da/lib/adapters/xhr.js#L39-L43

https://github.com/axios/axios/blob/0b3db5d87a60a1ad8b0dce9669dbc10483ec33da/lib/adapters/http.js#L58-L62

**Comment by BeanWei** [comment]
Okay,Thank you so much! @zcei
