### ISSUE TITLE
POST request not sending data to php script

### ISSUE THREAD

**Issue by kcjob** [axios/axios#1498]
#### Summary
I using the following axios in a vue script to send data to a php script.  I not having any luck 

#### Context
- Environment: *e.g.: vue 2.5, chrome 65, Mac OS 10.13

### Vue Script
``

   url = 'http://localhost/testVue/testVue.php';
   new Vue({
      el: '#app',
      data: {
     name:'',
     psswrd:''
   },
   methods:{
      login: function(){
       axios.post(url, {
           name: "this.name",
           email: "this.psswrd"
        })
         .then(function (response) {
           console.log(response);
         })
         .catch(function (error) {
           console.log(error);
         });
     }
   }
 });
``

### PHP script
``
$data = $_POST;

var_dump($data);
``

**Comment by samuelmattos** [comment]
Thanks, did i have same problems with PHP and twig.
And solved implemented the function:
`
var formData = getFormData($("#cad_evolucao"));
function getFormData($form) {
    var unindexed_array = $form.serializeArray();
    var formdata = new FormData();
    $.map(unindexed_array, function (n, i) {
        formdata.append(n['name'], n['value']);
    });
    return formdata;
}`

**Comment by loclamor** [comment]
I had just now the same problem (cannot get axios post data into php $_POST) and I found the workaround (here https://github.com/axios/axios/issues/1195#issuecomment-356143270)  to use `file_get_contents('php://input')` wich work !

**Comment by geoshar** [comment]
what about JSON.stringify?:) 
just
```
axios.post(url, JSON.stringify({
name: "this.name",
email: "this.psswrd"
}))
```
and in php 
`$_POST = json_decode(array_keys($_POST)[0], true);`
