### ISSUE TITLE
How could I get my custom config inside interceptors when a cancel exception is thrown?

### ISSUE THREAD

**Issue by blooddrunk** [axios/axios#1499]
#### Summary

I've passed some UI specific config when sending requests and hoped to use these configs to do some UI manipulation in interceptors. But the `config` property in an exception which thrown by a cancel operation seems to be undefined. How could I deal with this situation?

#### Context

- axios version: *^0.18.0(nuxt-axios)*

**Comment by chinesedfan** [comment]
Closed due to stale and lack of enough information. If you can provide sample codes, that would be really appreciated.
