### ISSUE TITLE
Issues related to POST requests after Chrome update

### ISSUE THREAD

**Issue by Tadoya** [axios/axios#1504]
#### Summary
Hi,
 I'm using axios in my web application. but, I can't use POST request after Chrome Update (v65 => v66)

I checked it in other browsers(Safari, Firefox) and it's currently only working on Safari(+ Chrome v65)

Full log of Chrome v66 is:
> **General**
Request URL: http://192.168.51.150:8080/
Request Method: OPTIONS
Status Code: 401 Unauthorized
Remote Address: 192.168.51.150:8080
Referrer Policy: no-referrer-when-downgrade

> **Response Headers**
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Cookie, Accept, X-PINGOTHER
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Origin: *
Content-Length: 42
Content-Type: application/json; charset=utf-8
Date: Thu, 26 Apr 2018 02:07:41 GMT
Server: Python/3.6 aiohttp/2.3.9
X-Content-Type-Options: nosniff

> **Request Headers**
Accept: `*/*`
Accept-Encoding: gzip, deflate
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Connection: keep-alive
Host: 192.168.51.150:8080
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

What 's wrong?
Thanks

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v8.9.4, npm v5.6.0, vue v2.5.2, webpack v3.6.0, chrome 66.0.3359.117 (64bit), macOS High Sierra(10.13.4)*

**Comment by yiyizym** [comment]
I've got the same problem.
the 'Referer' is missing in the Request Headers, but seems 'Referrer Policy' is 'no-referrer-when-downgrade', and both request url and the origin url is using 'http', the 'Referer' should be in the Request Headers.

**Comment by 59023g** [comment]
To fix, I found that my Express server was not accepting JSON post bodies:

```
const express = require( 'express' )
const server = express()

server.use( express.json() )
```

See also: https://stackoverflow.com/questions/10005939/how-do-i-consume-the-json-post-data-in-an-express-application

**Comment by chinesedfan** [comment]
> Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *

Don't response them together. See more about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
