### ISSUE TITLE
Safari can't deserialize JSON if Content-Disposition is set on the response headers

### ISSUE THREAD

**Issue by fnando** [axios/axios#1505]
#### Summary

Safari is not able to deserialize JSON payloads if `Content-Disposition` is set on the response headers. If you try to access `response.data` you'll get a string instead. It works just fine under Safari and Chrome.

Looking for solutions, I got to this SO thread, which gives a solution path (but I haven't tested it.)

https://stackoverflow.com/a/23797348/112300

#### Context

- axios version: 0.18.0
- Environment: Safari 11.1

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks
