### ISSUE TITLE
Axios modifies response of GET request for text files

### ISSUE THREAD

**Issue by rogerkerse** [axios/axios#1507]
Latest axios and node 9. I was doing GET request to fetch subtitle file (.srt). Approximately every second time the content was corrupted and unparseable (few corrupted lines in the whole file)
I tested with checksum as well and every single request got different checksum for the file content.

Then switched to fetch and every single time I got same checksum and no corruptions.

**Comment by chinesedfan** [comment]
Maybe similar with #1545.

axios, which is based on xhr, can not handle too large responses.
