### ISSUE TITLE
dist folder is published to npm

### ISSUE THREAD

**Issue by OrKoN** [axios/axios#1512]
#### Summary

I have noticed that npm package includes the `dist` folder which contains both minified and full versions of axios. At the same time, the npm package itself is only using the `lib` folder. Is there a reason to ship pre-built versions via npm in addition to the library itself?  The duplication adds around 200KB and requires a workaround when packaging axios for the AWS Lambda.

#### Context

- axios version: latest

**Comment by fed135** [comment]
Hi, thanks for reporting this issue. It is something that I have been wondering myself. I'll take a look into it.

**Comment by OrKoN** [comment]
@fed135 that would be still helpful. I am still using it but remove the dist folder during the build process

**Comment by OrKoN** [comment]
I guess it's done to support unpkg `<script src="https://unpkg.com/axios/dist/axios.min.js"></script>` so it might not be easily solvable

**Comment by fed135** [comment]
It may also be useful for compatibility with legacy node versions, ex
`var axios = require('axios/dist/axios')`

Hmm, that could be a potential solution to your packaging issue as well. Granted, it's not ideal thought.

**Comment by OrKoN** [comment]
@fed135 I don't apply webpack to my node modules so the node_modules folder gets copied as is. It's common with https://github.com/serverless-heaven/serverless-webpack because node_modules are ready to use and almost never need transformations. I work around the issue by explicitly pruning node modules to remove unneeded files:

```
  webpack:
    includeModules:
      forceExclude: aws-sdk
    packagerOptions:
      scripts:
        - node-prune
        - rm -rf node_modules/axios/dist
```

**Comment by fed135** [comment]
Yikes, I'll admit that I'm not an expert in Front-End development. What would be you recommendation?

**Comment by OrKoN** [comment]
@fed135 this is actually backend for https://aws.amazon.com/lambda

I'd recommend to ship only one code version with the `axios` package suitable for Node (the `lib` + `index.js`). If someone needs the minified and concatenated versions for the browsers, those should be published as separate packages or it could be built by the end users at the build time.

**Comment by jasonsaayman** [comment]
Closing as I will look at this in #3718
