### ISSUE TITLE
sometimes "method: post" is run as a get

### ISSUE THREAD

**Issue by mattwebdev** [axios/axios#1513]
i have run into an interesting situation where my request which is a POST is run as a GET. 

`_post(url, data) {`
    return this.axios({
      url,
      method: 'post',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      data: JSON.stringify(data),
    }).then(r => r.data);
  }`

i found the offending code in axios: 
`config = mergeConfig(this.defaults, config);
  config.method = config.method ? config.method.toLowerCase() : 'get';`

it looks like in "some cases" (still trying to get full repro steps...will post when i have them) config.method gets blown away and it defaults to get.

**Comment by lenghan1991** [comment]
I have the same problem, any solution?

**Comment by ViliusLuneckas** [comment]
Hello, any updates on this one?

**Comment by josechoy** [comment]
hi, I was facing the same issue in my project recently where I have used laravel as my backend.
```
axios.post('api/endpoint/', { 
    // data 
});
```
The code snippet above will actually return the response for an HTTP get request to my API endpoint. The workaround I found is to remove the trailing slash in the url, so it will be `api/endpoint`, then it worked as expected.

**Comment by chinesedfan** [comment]
Closed in favor of #1597.
