### ISSUE TITLE
connect ehostunreach 0.0.31.153:80

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [axios/axios#1514]
Hi, I have a project with restify that sends data to an api with axios. When I start both apis locally the axios shows this message

```sh
{ Error: connect EHOSTUNREACH 0.0.31.153:80 - Local (192.168.2.112:64676)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1106:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '0.0.31.153',
  port: 80
```
I noticed that this post #1228  is similar to mine, but it's closed.
How do you solve this?

### environment
os: macOS
node: v8.9.3
npm: 5.5.1
axios: 0.18.0

**Comment by koresar** [comment]
IP addresses can't start with 0. Thus the `EHOSTUNREACH` error. See here for example: https://superuser.com/questions/665502/why-cant-ip-addresses-start-with-0-or-255

This issue should be closed.

**Comment by carvalhoviniciusluiz** [comment]
but the local ip does not begin with 0. As it is  construction, the project is raised in the local address (localhost or 127.0.0.1)

this message is not making sense because of this

**Comment by koresar** [comment]
You'd need to find why the address is
```
address: '0.0.31.153',
```

**Comment by mapleeit** [comment]
Hi @carvalhoviniciusluiz , I encountered this problem today. By doing debug, I found some reason may cause this problem.

**It's about your system bash/zsh proxy settings**
```bash
export https_proxy=localhost:8888
export http_proxy=localhost:8888
```

`axios` will automatically detect your default proxys and use them. 

`axios/lib/adapters/http.js`

```javascript
var proxy = config.proxy;
    if (!proxy) {
      var proxyEnv = protocol.slice(0, -1) + '_proxy';
      var proxyUrl = process.env[proxyEnv] || process.env[proxyEnv.toUpperCase()];
      if (proxyUrl) {
        var parsedProxyUrl = url.parse(proxyUrl);
        proxy = {
          host: parsedProxyUrl.hostname,
          port: parsedProxyUrl.port
        };

        if (parsedProxyUrl.auth) {
          var proxyUrlAuth = parsedProxyUrl.auth.split(':');
          proxy.auth = {
            username: proxyUrlAuth[0],
            password: proxyUrlAuth[1]
          };
        }
      }
    }
```

the result of `url.parse('localhost:8888')`:

![image](https://user-images.githubusercontent.com/4194287/40637998-109f8376-633b-11e8-9790-fe7c9db79f2f.png)

**get the wrong hostname**

Then your dns will find this hostname, as a result, it returns 0.0.xx.xxx, which throw errors.

** so just remove https_proxy and http_proxy and restart your terminal **

**Comment by GabrieleRomeo** [comment]
> **so just remove https_proxy and http_proxy and restart your terminal**

For the sake of simplicity, you can remove them in the following way:

npm config delete http-proxy
npm config delete https-proxy

**Comment by Kabil-Boutou** [comment]
This error is also fired when you write just the IP @ without the protocol. 
Even with 127.0.0.1 you should add http://. 
Hope that was helpful .

**Comment by jsina** [comment]
I've just  add the ```http://```  before the endpoint url and problem is solved then.
