### ISSUE TITLE
axios put then not working in node environment

### ISSUE THREAD

**Issue by mqliutie** [axios/axios#1515]
```
axios.put(url,data).then(res=>{
    console.log(res)
    // browser logged res but not in node 
},error=>{
    console.log(error)
    // no log
})
```

- axios version: **0.18.0**
- Environment: **node v8.9.4**

**Comment by ShawnCholeva** [comment]
@mqliutie Hey just looking at this, that error callback on the promise returns looks suspicious.  Wouldn't it rather be this?

```
axios.put(url,data)
.then( res => {
    console.log(res);
})
.catch( err => {
    console.log(err);
})
```

**Comment by mqliutie** [comment]
@ShawnCholeva Hi, I found my mistake. I used axios in jest. This is not axios's business.
