### ISSUE TITLE
Using axios.all with a CORS request runs `.then` after the preflight requests return

### ISSUE THREAD

**Issue by comfroels** [axios/axios#1517]
#### Summary

I'm using axios.all to run a lot of requests that go cross-origin. The `.then` of `axios.all` is returning after all the `OPTIONS` request have finished but not after all the _actual_ requests have returned. The bad effect is simply that my then is getting executed before all my `POST`s actually return, causing the data returned in the `GET` to not be accurate.

#### Context

- axios version: v0.18.0
- Environment: chrome 65, MacOS High Sierra

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks
