### ISSUE TITLE
With parallel requests, timeout is not per request

### ISSUE THREAD

**Issue by HunorMarton** [axios/axios#1518]
I recently found this as a pattern in my error log. The request timeout period is starting from the first request even though that one succeeded:
![screen shot 2018-05-04 at 11 47 05](https://user-images.githubusercontent.com/9912279/39622247-b9313470-4f91-11e8-9600-4fd9be40420f.png)

I'm wrapping axios calls into promises and use `Promise.all` to run them in parallel.

I'm also using separate axios instances with `axios.create` for the separate kind of requests and I configure them with different timeout settings. Here the image calls have the 50000 second setting, and the login and update calls have 25000 which means that the the separate axios instances overwrite each others timeout settings.

#### Context
axios version: v0.16.2

**Comment by chinesedfan** [comment]
Can you share the detailed codes?

Closed first due to lack of enough information.
