### ISSUE TITLE
Instance defaults rewrite global defaults

### ISSUE THREAD

**Issue by dimensi** [axios/axios#1522]
Hi, i create new instance and set into headers some cookie and i was surprised, global instance have same cookies.
https://jsfiddle.net/b7fvjavk/1/
![screenshot_20180507_161232](https://user-images.githubusercontent.com/11390039/39703699-a47fd720-5211-11e8-8aa9-fda741cd5627.png)

**Comment by rikuayanokozy** [comment]
https://github.com/axios/axios/commit/82030ae054ba10bbd25ef00b304990632780f11d fixed this, the original `deepMerge` still kept ref to embedded objects, and the commit fixed it.
@emilyemorehouse can you release a new version using master?

**Comment by emilyemorehouse** [comment]
The fix you're referencing is from #385. This actually caused tests to fail for the master branch and therefore isn't stable. As soon as we can get that fixed, I can issue a release.

**Comment by emilyemorehouse** [comment]
Released as part of 0.19.0-beta.1.

This can be installed using `npm install axios@0.19.0-beta.1` or `npm install axios@next`

**Comment by luisfuertes** [comment]
Same issue with `"axios": "^0.19.0-beta.1"`

```
Failed to load https://api.urlmeta.org/?url=https://www.youtube.com/watch?v=LBLsjOHqst0: Request header field Access-Control-Allow-Headers is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by fqborges** [comment]
As a workaround, when you create an instance passing the deep object hierarchy it works.

```js
const apiAxios = axios.create({
  headers: {
    common: {},
  },
});
```

**Comment by patotoma** [comment]
works for me in `0.19.0-beta.1`

**Comment by jakobdo** [comment]
I had the same problem. Setting a custom header in axios global and setting another custom header on the instance. But the header still used the one from the global.

Using the "trick" from @fqborges works.

**Comment by krazyjakee** [comment]
@jakobdo was this issue still with 0.19.0-beta.1?

**Comment by doowb** [comment]
I was having this issue (`Authorization` header was being used in new instances from `.create()`) and updated to `0.19.0-beta.1` for the fix. I can verify that the fix works for me in Node.js v10.14.2.

**Comment by VadymGidulian** [comment]
`0.19.0-beta.1` works for me too
```js
axios.defaults.headers        === axios.create().defaults.headers        // false
axios.defaults.headers.common === axios.create().defaults.headers.common // false
```

@fqborges's method works, but I'd use it like this:
```js
axios.create({
    headers: {
        common: {...axios.defaults.headers.common}
    }
})
```
I believe this is closer to the original intention
