### ISSUE TITLE
Browser vs Node detection with Webpack4

### ISSUE THREAD

**Issue by Ewocker** [axios/axios#1523]
## Problem

The condition for getDefaultAdapter() under lib/default.js
```
(typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]')
```
does not really hold after building with webpack4

```
// Not always true when running node.js
Object.prototype.toString.call(process) === '[object process]'
```

I realize it with my new org used project.

## Reproduction:

I made a repo to show this:
[axios-bug](https://github.com/Ewocker/axios-bug)
with a single line of code to log it.
```
$ git clone https://github.com/Ewocker/axios-bug
$ cd axios-bug
$ npm install
$ npm run build
$ node src/index.js
[object process]
$ node dist/main.js
[object Object]
```

## Suggestion:
Maybe not just auto detect but also allow user to choose the adapter as well. So that this won't be a problem. I have seen couple of browser vs node detection issues in this repo.

The suggestion above is probably a feature request... sorry for putting it here.
I do not know the absolute condition that can assure that it is running on node or browser, so I will leave it to the expert.

**Comment by Ewocker** [comment]
Also, I might be misunderstanding something, but if you go to https://github.com/axios/axios/blob/master/dist/axios.js and find "getDefaultAdapter"
```
        function getDefaultAdapter() {
	  var adapter;
	  if (typeof XMLHttpRequest !== 'undefined') {
	    // For browsers use XHR adapter
	    adapter = __webpack_require__(8);
	  } else if (typeof process !== 'undefined') {
	    // For node use HTTP adapter
	    adapter = __webpack_require__(8);
	  }
	  return adapter;
	}
```
Seems like no matter what condition, the same module is being used... (look for "/* 8 */" it is the packaged xhr.js here) again it might just have been me out of my mind but I am not sure what is going on here.

Please explain me if I am thinking wrong.

**Comment by Ewocker** [comment]
#456 Find similar post

**Comment by Worie** [comment]
was it resolved somehow?
