### ISSUE TITLE
axios can't support headers for 'traditional : true', it's Bug 

### ISSUE THREAD

**Issue by 171563857** [axios/axios#1524]
# Context
- use vue.js
- axios version: *e.g.: v0.18.0*
- vue-axios version: *e.q.: v2.1.1
- Environment: *e.g.: node v8.11.1, chrome 64, windows 7*

# vue's main.js
import axios from 'axios'
import VueAxios from 'vue-axios'
Vue.use(VueAxios, axios)

# vue template script
```javascript
var arr = ['1', '2', '3'];
var params = {
　　classesId: '1',
　　search: '1',
　　labelIds: arr
};
//it's axios
this.$http({
　　method: 'get',
　　url: 'test',
　　headers: {
　　　traditional: true,
　　　dataType: 'json',
　　　contentType: 'application/json;charset=UTF-8',
　　},
　　params: params
　}).then(function (result) {
　　console.info(result);
　});
//it's $.ajax
$.get({
　url: 'yikeos-platform/exam/findQuestion',
　data: params,
　traditional: true,
　dataType: 'json',
　contentType: 'application/json;charset=UTF-8',
}).then(function (result) {
　console.info(result);
});
```

# Question String Parameters
## it's error for axios
![_20180508180937](https://user-images.githubusercontent.com/22027896/39751512-ff618fb0-52ea-11e8-929e-352f670e5641.png)

## it's true for ajax
![_20180508181002](https://user-images.githubusercontent.com/22027896/39751529-0cc02158-52eb-11e8-9c25-788d5a0eda5f.png)
## Compare axios and ajax
parameter 'labelIds' is error 

# MyQuestion
i set headers for attributes 'traditional : true', but ''Query String Parameters" is error

**Comment by Axnyff** [comment]
This is not really a bug,

jQuery ajax method has a feature to add a flag to say that the params need to be tradionally encoded.

Axios does not have that feature.

However, axios lets you use a param serializer so you could probably do:
    this.$http({
　　method: 'get',
　　url: 'test',
　　headers: {
　　　traditional: true,
　　　dataType: 'json',
　　　contentType: 'application/json;charset=UTF-8',
　　},
　　params: params,
        paramsSerializer: function(params) {
            // the second option is the traditional flag
            return $.param(params, true);
        },
　}).then(function (result) {
　　console.info(result);
　});
