### ISSUE TITLE
Axios call Response 200 with data OK but I'm redirected to catch with msg ERRO NETWORK

### ISSUE THREAD

**Issue by felipe-muner** [axios/axios#1525]
#### Summary
I try call a external domain:
https://viacep.com.br/ws/20021040/json/

I received the data I want(I check the request in Chrome console) but the call return in catch function with ERROR NETWORK

This is my call:
```
axios.get('https://viacep.com.br/ws/20021040/json')
      .then((response) => {
        alert(JSON.stringify(response))
      })
      .catch((error) => {
        alert(error)
      })
```
The NETWORK ERROR in console is: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

I also tried with crossdomain and content-type in header but it doesn't work anyway.

In back-end i use app.use(cors()) to enable the call.

#### Context

Front
- axios version: v0.17.1
- vue version: v2.5.3
- webpack: 3.6.0

Back
- node v9.8.0
- express cors 2.8.4

**Comment by ellis2323** [comment]
probably https://github.com/nodejs/node/issues/16196

**Comment by huy-lv** [comment]
Same problem :(

**Comment by chinesedfan** [comment]
Sadly that lots of issues are caused by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues.
