### ISSUE TITLE
Issue Uploading an Image using FormData with Axios (only on Android)

### ISSUE THREAD

**Issue by MaxiBrochon** [axios/axios#1526]
I have a problem uploading an image using axios. This code runs perfect on IOS but on Android throws the error Multipart != Application/JSON.
If someone had the same error and knows how to fix it is welcome.
Thanks

var photo = {
uri: data.image_url,
type: "image/jpeg",
name: "photo.jpg"
};
formData.append("photo", photo);
}

formData.append("route_id", data.gym_id);

  let url = `${config.protocol}://${config.domain}:${
    config.port
  }/webapp/createRoute`;
  
  axios
    .post(url, formData, {
      headers: {
        Accept: "application/json",
        "Content-Type": "multipart/form-data"
      }
    });

**Comment by virtualLast** [comment]
I am still having the same issue on Android with multipart form - debugging I can see that the form has multiple parts
![Screenshot 2019-05-24 at 10 38 23](https://user-images.githubusercontent.com/2872439/58318648-1a759200-7e10-11e9-902d-8291ccd0f2d9.png)
