### ISSUE TITLE
typescript typings for axios as global

### ISSUE THREAD

**Issue by westbrma** [axios/axios#1531]
#### Summary

I am using axios as a global not via an import. It seems the typescript typings only work when importing as a module. I believe its possible for the typings to work both ways.

#### Context

- axios version: all
- Environment: vscode

**Comment by varHarrie** [comment]
add declarations `.d.ts`, see [global-augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#global-augmentation).

**Comment by westbrma** [comment]
@varHarrie thank you for this, it feels like a workaround so I will leave the issue open.

**Comment by chinesedfan** [comment]
By default, we do not want to pollute the global namespace. So users can do that by themselves if necessary.
