### ISSUE TITLE
Re-use Axios Promise

### ISSUE THREAD

**Issue by bnbarak** [axios/axios#1537]
## Re-use axios Instance Issue
I apologize if I use axios in a wrong way.

I trying to use the same axios instance multiple times.

```
const req = axios.get('random numbers api')
req.then(function (response) {
      console.log(response.data.data);
})

req.then(function (response) {
  console.log(response.data.data);
})
```
The api is called **once** and both responses print the same thing.
 [jsfiddle example](https://jsfiddle.net/hb078mx4/)

**Comment by aihaibo** [comment]
axios is base on promise, when axios.get(...) method has results, the state will be solidify.  so when you want diffrent results, use axios.get('random numbers api') twice or more.

**Comment by Niddhogur** [comment]
Hi, @bnbarak . Does [`axios.create`](https://github.com/axios/axios#axioscreateconfig) help you?
```javascript
const api = axios.create({ baseURL: 'random numbers api' });

api.get().then(res => console.log(res.data));
```
Or even better:
```javascript
const api = axios.create({ baseURL: 'actual base url' });

api.get('/random number endpoint').then(res => console.log(res.data));
```
