### ISSUE TITLE
Response loaded from disk storage has status 200

### ISSUE THREAD

**Issue by vinodkolla** [axios/axios#1541]
axios get method return 200 status code for responses that comes disk cache. Shouldn't it return 304 status code? Are there any settings or header changes i need to make it to get 304 as response code for cached response?

**Comment by byr-gdp** [comment]
I also met this question...

**Comment by chinesedfan** [comment]
See https://stackoverflow.com/a/1665097/6501855. In summary, it is the expected behavior.
