### ISSUE TITLE
When is v0.18.0 due for official release?

### ISSUE THREAD

**Issue by rossanthony** [axios/axios#1542]
V0.17.1 is currently tagged as the [latest release](https://github.com/axios/axios/releases), however v0.18.0 has been out there since Feb 19. Is there much work pending before v0.18.0 can be bumped to the latest version?

We seem to be running into an issue using v0.17.1 where it's not honoring the timeout if the headers are send back and there's a delay in the response body being fully transmitted and received. It appears like it's been addressed in this commit: https://github.com/axios/axios/commit/fa3c6d22f7a5e0a963119109fccb8d86ad981c03, however this commit is only present in v0.18.0 which we are hesitant to start using if it's incomplete.

**Comment by emilyemorehouse** [comment]
Sorry I didn't catch this before -- 0.18 should have been tagged as `latest` automatically. Looks like it is now if it wasn't before.
