### ISSUE TITLE
Uses ECONNABORTED for timeouts instead of ETIMEDOUT

### ISSUE THREAD

**Issue by jwbay** [axios/axios#1543]
#### Summary

Axios seems to set a code of ECONNABORTED when a request times out: https://github.com/axios/axios/blob/0b3db5d87a60a1ad8b0dce9669dbc10483ec33da/lib/adapters/xhr.js#L107

This makes it difficult to tell when a request actually timed out vs. being aborted in a different way: https://github.com/axios/axios/blob/0b3db5d87a60a1ad8b0dce9669dbc10483ec33da/lib/adapters/xhr.js#L89
Should ETIMEDOUT be used instead?

#### Context

- axios version: 0.18.0

**Comment by gillib** [comment]
This is very important to us as well.

**Comment by lundn** [comment]
Would be very nice to have!

**Comment by 9-lives** [comment]
how is it going?

**Comment by Kameecoding** [comment]
```
{
  "message": "timeout of 1ms exceeded",
  "name": "Error",
  "stack": "Error: timeout of 1ms exceeded\n at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)\n at XMLHttpRequest.handleTimeout (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:89:14)",
  "config": {
    "url": "/clover/data-app/model/get/example/contact/v",
    "method": "get",
    "headers": { "Accept": "application/json, text/plain, */*" },
    "transformRequest": [null],
    "transformResponse": [null],
    "timeout": 1,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  },
  "code": "ECONNABORTED"
} 
```

as a workaround, you should be able to check the message or stack for timeout

**Comment by leolivier** [comment]
+1

**Comment by eddyson1006** [comment]
+1

**Comment by jasonsaayman** [comment]
Closing in favour of #2710

**Comment by adamtheadmin** [comment]
The `ETIMEDOUT` comes from node internal API's not axios'

**Comment by dvicory** [comment]
I don't see how this is related to #2710, but I do agree this should be closed. For us, this functionality is [covered with `clarifyTimeoutError`](https://github.com/axios/axios/commit/5ad6994da3e97b8ed857faed90955a65a891f459).

**Comment by vaibhavgupta-bst** [comment]
To get ETIMEDOUT status instead of ECONNABORTED, set transitional.clarifyTimeoutError = true in the axios request config. Below is the implementation in axios module
![image](https://user-images.githubusercontent.com/51628840/226793468-6c87e8ae-fe50-4db2-985e-6d7d2d8a884c.png)
