### ISSUE TITLE
android 4.4.4  axios response data is null

### ISSUE THREAD

**Issue by shenhualove** [axios/axios#1545]
android 4.4.4 系统上，我用axios发起请求，后台返回json数据过大的时候，response 为null，后面改用fetch 使用ok，使用环境react native 0.55版本  

- axios version: *e.g.: v0.18.0*

**Comment by wxcchdStar** [comment]
I have the similar issue. On Android 4.4.4，when response body is too big, response body will cut the content and JSON.parse(response) will occur the `SyntaxError: Unexpected token i in JSON at position`.  I print the request body, and this content like this: `{id:1,"name":""isRequired":1}`, the content after `name` lose the `value",`.  The complete content should be `{id:1,"name":"value","isRequired":1}`

I also set `maxContentLength: Number.MAX_VALUE`, but it's not work. 

I using react native v0.55.4 and axioa v0.18.0.

**Comment by chinesedfan** [comment]
XHR really has some limitations compared with fetch. Users can implement an adapter like https://github.com/lifeomic/axios-fetch. Hope axios can include a default fetch adapter one day.
