### ISSUE TITLE
Browser Support: IE

### ISSUE THREAD

**Issue by zibra** [axios/axios#1546]
![image](https://user-images.githubusercontent.com/4493100/40222810-10a119f6-5a81-11e8-91e6-8effef305b5c.png)

What means this red status of tests? Are you going to fix this?

**Comment by christopherfujino** [comment]
I'm also curious: does adopting axios mean punting IE support? I just need 11...

**Comment by allayli** [comment]
I check it on IE. It works fine if I add promise polyfill.

**Comment by ddtch** [comment]
yeah very confusing. Could we get some explanations

**Comment by muzi131313** [comment]
I use `bluebird` as promise polyfill, and fix some error in ie9, publish as a new package, address was here: [axios-ie](https://www.npmjs.com/package/axios-ie)。axios team decide not to support ie9 from `0.18.0` version。
![image](https://user-images.githubusercontent.com/2398149/51451912-9aacbd80-1d72-11e9-88ea-a2c6469e0fe3.png)
commit was here, [go](https://github.com/axios/axios/compare/v0.18.0...master)

**Comment by chinesedfan** [comment]
Apologized for the inconvenience. At least IE11 is supported now.

About promise pollyfill, we have mentioned in [COOKBOOK.md](https://github.com/axios/axios/blob/master/COOKBOOK.md).
