### ISSUE TITLE
How to cancel the other request in Axios.all

### ISSUE THREAD

**Issue by Zhang-Yida** [axios/axios#1547]
Hello
In my page, I want to use Axios.all to send request to the server, if the first request is a bad request, how to cancel the other request.

```javascript
        initAuthInfo() {
            return this.$axios.get('/authInfo')
        },
        initMenuInfo() {
            return this.$axios.get('/menuTree')
        },
        initSystemConfig() {
            Axios.all([this.initAuthInfo(), this.initMenuInfo()])
                .then(Axios.spread((authInfo, menuInfo) => {
                    console.log(authInfo, menuInfo)
                }))
        }
```

**Comment by kuma-guy** [comment]
@Zhang-Yida Is this solved? I'm in the same situation

**Comment by Zhang-Yida** [comment]
@kuma-guy Sorry not. I have split the requests.when one isn‘t ok, cancel the others request.

**Comment by summerkiflain** [comment]
@Zhang-Yida can you share some code example how are you canceling other requests.

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, what you need is some practices about promises. Good luck!

Suppose you have 2 promises/requests, p1 and p2. You can wrap p1 to cancel p2. Say,

```
wrapped = p1.catch(() => p2.cancel)

axios.all([wrapped, p2])
```
