### ISSUE TITLE
Date serialization

### ISSUE THREAD

**Issue by tangmingming** [axios/axios#1548]
By default, Axios serialize Date objects into UTC strings. This will cause great trouble for developers who want to use local time. It is hoped that they can add support for serialization into different time zone strings.

**Comment by agardou** [comment]
I agree, send dates forced with UTC timezone lost precious information on API client timezone

**Comment by HankBass** [comment]
I am experiencing the same problem. The current practice is to change the date  to string when requesting, and to string when return.

**Comment by Tovli** [comment]
This is really annoying. Any plan to change this behavior?

**Comment by qbunia** [comment]
Waiting for this fix too!

**Comment by mezaniella** [comment]
Someone find a solution for this problem?

**Comment by Connect-a** [comment]
I solved this problem with customizing qs (and using [dayjs](https://github.com/iamkun/dayjs)).

e.g. (for TypeScript)
```TypeScript
baseAxios.interceptors.request.use((config) => {
  config.paramsSerializer = (params) => qs.stringify(params, {
    serializeDate: (date: Date) => dayjs(date).format('YYYY-MM-DDTHH:mm:ssZ') });
  return config;
})
```

See also : https://github.com/axios/axios#interceptors

**Comment by agardou** [comment]
Pretty good solution, wasn't aware of `config.paramsSerializer` !
I will keep this solution in mind next time, thank you @Connect-a.

**Comment by chinesedfan** [comment]
As @Connect-a recommended, axios can't handle everything by default, so users need to implement their own `paramsSerializer`.
