### ISSUE TITLE
Access to actual request data (url + serialized params, mostly)

### ISSUE THREAD

**Issue by MonsieurLanza** [axios/axios#1549]
Hello, thanks for sharing your great work.

#### Summary
We need to sign request before they are sent, that is : add a header with an ECDSA signature calculated with full request URL (including parameters) and body, to ensure they are not modified when they reach the server.

In order to verify the signature, server software needs to rebuild data used to calculate the signature, using received request. Hence client (which uses axios and redux-axios-middleware) must sign with actual request data, which leads us in following issue : final url with querystring isn't built before request object construct (here for xhr : https://github.com/axios/axios/blob/0b3db5d87a60a1ad8b0dce9669dbc10483ec33da/lib/adapters/xhr.js#L45)

As for now, I see two options to achieve this, both unsatisfying : 
- pass a custom paramSerializer, build the signature in an interceptor using it, and let axios rebuild the actual request url. Problem here is that url is built 2 times, leading to potential differences, not to mention unnecessary runtime overhead.
- write a whole custom adapter, which handles the signing stuff, which would involve a lot of code duplication since we cannot easily access to axios' core, helpers & utils from outside the lib.

Ideal situation would be an access to final url at interceptor's level (or in transformers ?). 
Do you see a better way to achieve this that I would have missed ?

#### Context
- axios version: v0.18.0
- Environment: whatever

**Comment by iamdey** [comment]
cf. https://github.com/CaliOpen/Caliopen/pull/927

**Comment by jasonsaayman** [comment]
>write a whole custom adapter, which handles the signing stuff, which would involve a lot of code duplication since we cannot easily access to axios' core, helpers & utils from outside the lib.

The above will be the best possible solution for this.

**Comment by boutell** [comment]
Encountering the same issue. It would go a long way if interceptors could inspect what the final URL will be.
