### ISSUE TITLE
Getting 400 Bad Request Error

### ISSUE THREAD

**Issue by muhammad-asad-26** [axios/axios#1552]
#### Issue

Hi, I'm getting 400 when I try to hit my api. The api is working fine. I have validate the API's via postman and already consuming in the nodejs application but in react-native this is not working.

Here is my code
```
axios({
            method: 'post',
            url: 'https://api-helper.azurewebsites.net/token',
            data: {
                username: 'api', 
                password: 'MY_PASSWORD', 
                grant_type: 'MY_GRANT_TYPE'
            },
            headers: {
                    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
            }
          }).then((response) => {
            console.log('token', response);
        })
        .catch((response) => console.log('error', response));
```

**Comment by memo-rebolledo** [comment]
Have you tried using this format?

```
axios.post('https://api-helper.azurewebsites.net/token', {
	username: 'api', 
        password: 'MY_PASSWORD', 
        grant_type: 'MY_GRANT_TYPE'
}, {
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
        }
})
.then(response => { 
	console.log(response)
})
.catch(error => {
    console.log(error.response)
});
```

**Comment by guilhermereis1** [comment]
ghost, It helped me a lot, thanks!

**Comment by williamdarkocode** [comment]
has anyone been able to resolve their 400 bad request error?

**Comment by KBiswas98** [comment]
> This code Work for me.

`.catch((error) => console.log(**error.response.request._response**) );`


> Full code: 

`    await axios
      .post('http://192.168.43.49:3000/user/login', {
        phone_no: this.state.phone_no.value,
        password: this.state.password.value,
      })
      .then(function(response) {
        console.log(response.headers['auth-token']);
        localStorage.setItem(
          'session',
          JSON.stringify({
            login: true,
            token: response.headers['auth-token'],
          }),
        );
      })
      .catch((error) => console.log('error', error.response.request._response)      );
`

**Comment by simsketch** [comment]
adding a try catch helped me see the response and underlying error message.

**Comment by yazok8** [comment]
> > This code Work for me.
> 
> `.catch((error) => console.log( error.response.request._response ) );`
> 
> `

this worked for me! thank you so much

**Comment by namoojaalallee** [comment]
What is wrong with it?
