### ISSUE TITLE
Need To replace  a value in Axios Reponse 

### ISSUE THREAD

**Issue by pvk576** [axios/axios#1554]
I need to replace  a value in the response  , 

My Json format : 
{"Message":"","IsSuccessful":true,"sample2.0com":["data1","data2"],"sample1.0com":["data3","data4","data5","data6"]}}

When i am trying to read the above response , i am facing issue 

let sample2 = response.data.Result.sample2.0com; 

Please give me a solution to read sample2.0com components from the response

**Comment by aquamme** [comment]
"sample2.0com" isn't a valid identifier so you have to use [bracket notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors)
