### ISSUE TITLE
Buffer deprecation warning

### ISSUE THREAD

**Issue by silverbackdan** [axios/axios#1555]
#### Summary

I have looked but I didn't manage to find this issue, it's probably a known issue but `Buffer()` is deprecated in the latest Node version:
https://github.com/axios/axios/blob/master/lib/adapters/http.js#L42
https://github.com/axios/axios/blob/master/lib/adapters/http.js#L44
https://github.com/axios/axios/blob/master/lib/adapters/http.js#L127

Node produces the warning
`[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

Is this as simple as changing the 2 lines I can see to `Buffer.from(...)` instead of `new Buffer(...)` - if so, I'm happy to raise a PR if it's helpful.

#### Context

- axios version: all - including current master branch
- Environment: Node v10.1.0

**Comment by emilyemorehouse** [comment]
This has been fixed and merged!

**Comment by emilyemorehouse** [comment]
This has been fixed and merged!

**Comment by haiemh** [comment]
Why is this closed?

**Comment by jasonsaayman** [comment]
Hi it seems that it has been merged, if you think there is still an issue please open a new issue this one seems pretty busy.
