### ISSUE TITLE
Delay request execution?

### ISSUE THREAD

**Issue by ChadTaljaardt** [axios/axios#1558]
I have a web app that does many network requests using JWT authentication, and I have a global catch on the response if the status is 401 in which you will automatically be redirected to the login screen. I also have a function that runs continuously in the background that will automatically refresh your token if its about to expire and if you have used the system recently. My issue is that if I have several network requests, and the refresh token request is fired, and requests are made before the refresh requests has responded, the following requests have the old JWT token and therefore get a 401 error. 

My solution thus far has been to delete the JWT token from the browser just after the refresh token network request has been made, and then in the request interceptor, I do a check to see if the jwt_token value is null in the browser. If it is null, id like to have the request delayed for 1-2 seconds to wait for the refresh token request to return. 

Does anyone know of a better way to do this and does anyone know how to set the timeout in the request interceptor? 

Sorry if I have not provided a clear description of the issue I'm facing, it's hard to explain. If anyone needs any more information on the issue I can try to explain it better. 

Thanks for any help.

**Comment by Niddhogur** [comment]
Hi. If just setting a delay solve your problem, then you should check [lodash's delay](https://lodash.com/docs#delay).

Other solution that may help you is to make the refresh token function async and wait for it's result.

**Comment by ksankumar** [comment]
@ChadTaljaardt  Can you share your solution for implementing delay

**Comment by chinesedfan** [comment]
What you need is some practices about promises.

```
.use(() => {
    return new Promise((resolve) => setTimeout(resolve, 1000))
})
```
