### ISSUE TITLE
How can integrate the backend server with the axios. 

### ISSUE THREAD

**Issue by nihp** [axios/axios#1559]
I have get and Post call, how the integration will be added in the client side. 

Kindly provide any idea about this. I need some idea how to integrate this with in my client side.

I am new to this. So kindly give your inputs

**Comment by msouidi309** [comment]
Hi, what do you want to do exactly ?
What do you mean by client side ? You want to display data fetched with a GET request ?

**Comment by nihp** [comment]
I have a server side api to fetch the information, I need to integrate with the client side.

**Comment by msouidi309** [comment]
You can use axios for example
[https://github.com/axios/axios](url)
to get, post, put, delete data from your client side.
For example, to get data :

```
axios.get('/user?ID=12345')
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
```
will get the user with the ID 12345
I don't know if it's exactly what you want

**Comment by nihp** [comment]
Thanks @msouidi309

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
