### ISSUE TITLE
Please consider setting X-Requested-With header

### ISSUE THREAD

**Issue by bard** [axios/axios#1560]
Pros:

- would match expectations acquired from other AJAX libraries (jquery, dojo, prototype) and server-side frameworks (express, RoR, Laravel, ...)
- developer wouldn't need to figure out that it isn't set by default
- developer wouldn't risk forgetting that it isn't set by default and have to figure it out again on the next project
- would make useful techniques like https://stackoverflow.com/a/22533680/2103598 a little smoother to implement
- is well tested and should not be providing people with footguns

(I'm aware that it's possible to create an axios instance with custom default values, however by then the time to figure out the situation has already been spent.)

Cons:

- adding something out of spec because "everyone else does" always comes with an unquantifiable yet undeniable degree of suckage. Totally understand that.

**Comment by wuliupo** [comment]
same with https://github.com/axios/axios/issues/1322

**Comment by jasonsaayman** [comment]
Please use the solution mentioned in #1560
