### ISSUE TITLE
charset latin1 not working

### ISSUE THREAD

**Issue by danielsalles** [axios/axios#1561]
#### Summary

I can not make charset work. I am making request for a page that deals with `charset=iso-8859-1`, and even setting `{ charset: 'latin1' }`, correct decoding does not happen.

I'm following this https://github.com/axios/axios/pull/869

I've tried `latin1` and `latin-1`

```javascript
  // url to open bases results
  const url = `http://www.stf.jus.br/portal/jurisprudencia/listarJurisprudencia.asp?s1=%28SAUDE+COMPLEMENTAR%29&base=baseAcordaos&url=http://tinyurl.com/y9e68odp`

  // request first page
  axios.get(url, {}, { charset: 'latin-1' })
    .then(({ data }) => {
      console.log(data)
    })
```

#### Context

- axios version: *v0.18.0*
- Environment: *node v10.1.0*

Thank you

**Comment by chinesedfan** [comment]
I think it should be,

```
axios.get(url, { responseEncoding: 'latin-1' })
```
