### ISSUE TITLE
Axios cannot upload a blob, sends an empty body.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [axios/axios#1569]
I think it may be related to #415...

I'm trying to upload a blob to S3, like so:

```js
await axios.put(
  'https://s3.amazonaws.com/.../foo.jpg',
  { data: blob },
  { headers: { 'x-amz-acl': 'public-read', 'Content-Type': 'image/jpeg' },
})
```

This ends up sending an empty body. Whereas this works easily with fetch:

```js
const stuff = await fetch(
  'https://s3.amazonaws.com/.../foo.jpg',
  {
    method: 'PUT',
    body: blob,
    headers: {
      'Content-Type': 'image/jpeg',
      'x-amz-acl': 'public-read',
    },
  },
)
```

In #415, it mentions needing to change the content-type to `multipart/form-data`, but actually I don't want to submit a form, I just want to upload the blob to S3.

Am I missing something obvious?

#### Context

- axios version: v0.15.3
- Environment: Node v8

**Comment by retyui** [comment]
@AndrewSouthpaw Can you find solving of this problem?

**Comment by AndrewSouthpaw** [comment]
I haven't. We had to resort to using `fetch`. 😞

**Comment by LeeDavidPriest** [comment]
I was having a the same issue with the request body being empty. I managed to get it to work by doing the following:

```
const formData = new FormData();
const extension = value.type.split('/')[1];
const imageFile = new File([value], `${Date.now()}.${extension}`, {
       type: value.type,
});
formData.append('image', imageFile);

axios({
        method: 'post',
        url: '/admin/resources/uploadImage.json',
        headers: {
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-TOKEN': csrfToken,
        },
        data: formData,
      })
        .then(response => {
          console.log(response);
        })
        .catch(err => {
          console.log(err);
        });
```

I'm thinking that Axios may be struggling with the blob for some reason. Converting the blob to a File seemed to fix the issue and the request body was sending the image as a binary.

Hopefully this helps!

**Comment by oliverpool** [comment]
For me this works fine (v0.19.0):

```
axios.put(url, blob, {
      headers: { "content-type": blob.type }
    });
```
Maybe you have to replace `{data: blob}` with `blob`

(I know this thread is quite old, but it appears quite high in search engines: I hope that it will save me some time next time ;-)

**Comment by AndrewSouthpaw** [comment]
Thanks for sharing!

**Comment by AndrewSouthpaw** [comment]
If I ever end up touching that part of the code again, I'll try out your fix. I generally avoid fetch like the plague.

**Comment by raRaRa** [comment]
I'm running into similar issue, using fetch to upload blob works great, but with Axios it doesn't work at all. Shouldn't Axios figure out if the data param is blob or File?

**Comment by zhengfen** [comment]
I solved the issue by adding filename with extension:
```
const extension = blob.type.split('/')[1];  
fmData.append('image', blob, 'filename.'+ extension);
```
inspired by the answer of LeeDavidPriest

**Comment by chinesedfan** [comment]
Closed due to old version of axios. And @oliverpool confirmed it works now. https://github.com/axios/axios/issues/1569#issuecomment-557833903.

If other users met similar problems, feel free to open a new issue with the required template.
