### ISSUE TITLE
The header content contains invalid characters

### ISSUE THREAD

**Issue by mtdpcs** [axios/axios#1570]
nodejs v8.4.0
axios: "^0.18.0"

I use axios in node and set header with Chinese like blow

axios.get(`api/tasks/${params.id || 0}/permissions`, {
        headers: {
          auth: '测试',
        },
      })

and get the error 

TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:492:11)
    at ClientRequest.setHeader (_http_outgoing.js:496:3)
    at new ClientRequest (_http_client.js:171:14)
    at Object.request (http.js:39:10)

what should i do?

**Comment by blairzhao111** [comment]
`auth` is parsed into `Authorization ` for http header and is used for basic authentication, so it should be an object containing your basic auth info ``auth: {
   username: '...', password: '...'
}``

**Comment by mtdpcs** [comment]
no,i just for a example ，this is also get the error

axios.get(api/tasks/${params.id || 0}/permissions, {
headers: {
cookie: '测试',
},
})

**Comment by msouidi309** [comment]
Hi, the URL must be enclosed in quotation marks.
```
axios.get("api/tasks/${params.id || 0}/permissions" ...
```

**Comment by falstack** [comment]
I have same issue

**Comment by AllainPL** [comment]
As per [rfc7230](https://tools.ietf.org/html/rfc7230#section-3.2.4) headers SHOULD not contain non-ASCII characters.

Here is the actual node implementation:
```js
const tokenRegExp = /^[\^_`a-zA-Z\-0-9!#$%&'*+.|~]+$/;
/**
 * Verifies that the given val is a valid HTTP token
 * per the rules defined in RFC 7230
 * See https://tools.ietf.org/html/rfc7230#section-3.2.6
 */
function checkIsHttpToken(val) {
  return tokenRegExp.test(val);
}

const headerCharRegex = /[^\t\x20-\x7e\x80-\xff]/;
/**
 * True if val contains an invalid field-vchar
 *  field-value    = *( field-content / obs-fold )
 *  field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
 *  field-vchar    = VCHAR / obs-text
 */
function checkInvalidHeaderChar(val) {
  return headerCharRegex.test(val);
}
```
source: https://github.com/nodejs/node/blob/master/lib/_http_common.js#L210-L229
