### ISSUE TITLE
Axios.put inside Axios.get

### ISSUE THREAD

**Issue by Jinx59** [axios/axios#1577]
Hello, I want to update status, but when I want to do the 'put' it's not working cause axios in axios.put is not define. Can you help me please.

`getAbsencesByRequestId (reqId) {
      let self = this
      axios.get(REQUESTID_URL + reqId)
      .then((response) => {
        self.collaboId = response.data[0].collabId
        self.beginDate = response.data[0].startDate
        self.finishDate = response.data[0].endDate
        self.reason = response.data[0].type
      }, (error) => {
        console.log(error.response.status)
      })
      axios.put(REQUEST_URL + reqId, {
        collabId: this.collaboId,
        startDate: this.beginDate,
        endDate: this.finishDate,
        status: 'VALIDATED',
        type: this.reason
      })
    },`

**Comment by Jamesking56** [comment]
Can you please put that in a code block instead of inline: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
