### ISSUE TITLE
post(A).then().post(B).catch() -> if an error occurs, axios tried again?

### ISSUE THREAD

**Issue by dan1wang** [axios/axios#1579]
See https://gist.github.com/dan1wang/baf25ff2a45e6c53880e89185b0f29da

I have this code on Firebase:

```
  return getAccessToken(auth_code)
      .then(accessToken => {
          return appscript.run(accessToken, fnName, fnParams)
      })
      .then(res => {
          ...
      })
```

where `getAccessToken(...)` returns an `axios.post().then()` object, and `appscript.run()` also returns an `axios.post().then()` object.

If everything goes well, I will see a log like this:
  

> success message from getAccessToken (got an access token)
>   success message from appscript.run

If something goes wrong, I will see a log like this:
  

> success message from getAccessToken (got an access token)
>   error message from appscript.run
>   error message from getAccessToken (Google says access token was redeemed already)

I just can't understand why axios would do the first post() again if the second post() fails. Why?

(btw, Firebase doesn't support `await`, and I don't know how to make it synchronous)

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
