### ISSUE TITLE
React Native : Failure in SSL library

### ISSUE THREAD

**Issue by safeimuslim** [axios/axios#1583]
Hello, anyone can help me guys?

- Test API via postman OK
- Check SSL trusted OK
- Call api with axios in RN ERROR, see error bellow

`javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8ecbf50: Failure in SSL library, usually a protocol error error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:744 0x9c8087f1:0x00000000)`

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

Please open a new issue, instead of editing the current one.
