### ISSUE TITLE
Failed to load http://localhost:8000/api/details: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.

### ISSUE THREAD

**Issue by 3jFernando** [axios/axios#1585]
# Hola

**Mi servidor (Web Service Rest) esta en Laravel (ultima version)
Mi app cliente este en Ionic 3 (Ultima version)**

**Tengo este problema:**

# _Failed to load http://localhost:8000/api/details: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access._

## Y la cuestion es que las rutas normales funcionan bien, el cors la acepta.
Pero las rutas del Auth Passport  de laravel no funcionan

**Este es el archivo de Cors.php**

```
public function handle($request, Closure $next)
    {
        $response = $next($request)
          ->header('Access-Control-Allow-Origin', '*')
          ->header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE')
          ->header('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

        return $response;   
    }
```

**Este es el archivo de api.php**

```
Route::group(['middleware' => 'cors'], function () {

    Route::group(['middleware' => 'auth:api'], function() {
        Route::post('details', 'PassportAuthController@details');
    });

});
```

Ayuda, gracias.

**Comment by msouidi309** [comment]
Hi, how do you call your GET request ?

**Comment by Snehal1112** [comment]
@3jFernando try to add 'Content-type': 'application/x-www-form-urlencoded header from client side

**Comment by Fractalliter** [comment]
I did that but same error every time
I use http://localhost:3000 for client-side and server-side is an API then I try to make a request with header and body (axios(options)) and take same error then i disable CORs of chrome with extension and server give me this error
`OPTIONS https://gateway.tameemco.ir/uaa/oauth/token 403 (Forbidden)
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:59
Promise.then (async)
request @ Axios.js:51
Axios.(anonymous function) @ Axios.js:71
wrap @ bind.js:9
LoginForm._this.handleSubmit @ login-form.js:41
onClick @ reactstrap.es.js:1139
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:461
executeDispatchesInOrder @ react-dom.development.js:483
executeDispatchesAndRelease @ react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
forEachAccumulated @ react-dom.development.js:562
runEventsInBatch @ react-dom.development.js:723
runExtractedEventsInBatch @ react-dom.development.js:732
handleTopLevel @ react-dom.development.js:4476
batchedUpdates$1 @ react-dom.development.js:16659
batchedUpdates @ react-dom.development.js:2131
dispatchEvent @ react-dom.development.js:4555
interactiveUpdates$1 @ react-dom.development.js:16714
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
Failed to load https://gateway.tameemco.ir/uaa/oauth/token: Response for preflight has invalid HTTP status code 403.`

**Comment by DaruoMatrix** [comment]
download the extension "Allow-Control-Allow-Origin" if you use chrome

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
