### ISSUE TITLE
ReadMe's supported browsers is visually inconsistent

### ISSUE THREAD

**Issue by MeoMix** [axios/axios#1586]
![image](https://user-images.githubusercontent.com/1380995/40934839-f2d69bf4-67ea-11e8-86a4-2a7a26e4983a.png)

Axios does not support Internet Explorer. There is a badge with the text "IE8+" with a green check adjacent to it. This would imply that IE8+ is supported by Axios.

Presumably this is just an oversight? Should the IE badge be removed entirely, or perhaps changed from a green check to a red 'x'?

**Comment by MeoMix** [comment]
Okay, sure. That makes sense. That said, when I look through release tags (such as the most recent 0.17.1) I still see test failures for IE 9/10/11. I suppose that leads me to think that Axios isn't supporting older versions of IE anymore. Are the tests just broken indefinitely?

**Comment by emilyemorehouse** [comment]
We're still supporting older versions. Any release should have all tests passing (if they didn't -- that was an oversight!).

Master is currently failing for IE 7, and the failing tests are actually [a blocker for the next release](https://github.com/axios/axios/projects/3#card-11058724)
