### ISSUE TITLE
Laravel 5.5 + Vue.js -  Adding a dropdown list that can access/view another table

### ISSUE THREAD

**Issue by NoirKurosuKai** [axios/axios#1589]
Hi, I need help in adding a dropdown list that can access my other table (I have 2) which is the inventory  and employees table. I just need a dropdown that displays all the employees in my table and when selected gets displayed along with the inventory info. If you guys could share some tutorials that can help with this issue would also be great. Thanks for the help.

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
