### ISSUE TITLE
Axios doing .then() before .delete request.

### ISSUE THREAD

**Issue by riodw** [axios/axios#1590]
#### Having an issue where the .then(...) executes before the .delete request.
(I don't want to point fingers, it might be Django that's not right)
##### Logs:
![screen shot 2018-06-06 at 2 23 15 pm](https://user-images.githubusercontent.com/10352814/41057474-32c38118-6995-11e8-895b-a29988cc43fb.png)
You can see from the image, some of the "GET" requests are present before the "DELETE" requests. It seems random almost, it's highly inconsistent. Sometimes it executes in the proper order, sometimes not.

##### Code:

```
// app.js

var app = new Vue({
    data: {
        categories: [],
    },
    mounted() {
        this.getCategories();
    },
    methods: {
        getCategories() {
           axios.get('/api/question_bank/categories/')
           .then(response => {
                console.log(response.data);
                this.categories = response.data;
            });
        },
        deleteCategory(catagory_ID) {
            axios.delete('/api/question_bank/categories/' + catagory_ID + '/')
            .then(this.getCategories());
        }
    },
});
```

#### Context

- **Axios:**   
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
- **Vue.js:**
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
- **Environment:**   
  Chrome: Version 67.0.3396.62 (Official Build) (64-bit)
  Django: 1.8.18
  OS: macOS High Sierra Version 10.13.4 (17E199

**Comment by Shogun137** [comment]
You call the getCategories method instead of setting it as a callback.

**Comment by chinesedfan** [comment]
@riodw I think your screenshot is logs in the server side. It is completely possible. Because you can not control sequences of requests in network. They are sent in the right order, but received in any order.

BTW, your codes have problems about `.then(this.getCategories());`, as @Ro37A mentioned.

**Comment by riodw** [comment]
Got it, thanks
