### ISSUE TITLE
About Axios Bug in IE9

### ISSUE THREAD

**Issue by itwenqiang** [axios/axios#1594]
#### Summary

Young man from China who does not understand English. I use Google Translate.Recently used "axios", because the project needs must be compatible with "IE9". However, under "IE9" issued under "post" pass parameters interaction can not be successful, there will be "Promise rejection" error. Read the source code of "axios" and found that the use of "promise" in the source code did not use "catch". So, modified the source code and repackaged the test. It turned out to be useable. Hope that the author can fix this problem as soon as possible. 

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v8.11.2, chrome 67, windows 10*

**Comment by msouidi309** [comment]
Hi @itwenqiang , please show the code

**Comment by itwenqiang** [comment]
@msouidi309 Need to show the test code, or where the axios source code was modified?

**Comment by guoshuke** [comment]
![8](https://user-images.githubusercontent.com/20693126/44837685-d5e80c00-ac6c-11e8-82ab-955c239566a3.png)

**Comment by guoshuke** [comment]
I used es6-promise, babel-polyfill  qs, but it doesn't work.  ie10 ie11 is OK ,

**Comment by itwenqiang** [comment]
It seems to be a question about the usage of Promise
Source code:
`fn.then(() => {}, () => {})`
After modification:
`fn.then(() => {}).catch(() => {})`
After this change, I solved my problem.

**Comment by fed135** [comment]
Hey, thanks for submitting this issue. Since it has been inactive for a while and that our resources for maintaining and triaging are limited, we will be closing this ticket. If the issue persists on your end, please feel free to open a new issue.
