### ISSUE TITLE
method is POST, but sent as 'GET'

### ISSUE THREAD

**Issue by lenghan4real** [axios/axios#1597]
![image](https://user-images.githubusercontent.com/1933236/41212305-797563a0-6d6f-11e8-8311-5a64a49c1656.png)

**Comment by lenghan1991** [comment]
The backend service is based on HTTPS. I correct it  and succeed. However, the stack is quite confusing.

**Comment by chinesedfan** [comment]
Did you have redirections for your first POST request? Because axios saves the last request. That may be the reason.

**Comment by chinesedfan** [comment]
Closed due to no feedback.
