### ISSUE TITLE
in ios version 12.0, Axios Post resquest data ,response status is 0, response is undefind

### ISSUE THREAD

**Issue by falost** [axios/axios#1598]
```
// package.json
"Axios":"^0.16.2"
```

IOS 
version: 12.0 dev

response 

![tim 20180611174156](https://user-images.githubusercontent.com/13709107/41224894-176298b4-6da0-11e8-8fc5-47503f349f9f.png)
![1](https://user-images.githubusercontent.com/13709107/41224891-16bbc138-6da0-11e8-92e0-340c4a839606.png)
![2](https://user-images.githubusercontent.com/13709107/41224892-16f2221e-6da0-11e8-8545-e0595ef30e46.png)
![3](https://user-images.githubusercontent.com/13709107/41224893-1729caca-6da0-11e8-893d-c719be443d06.png)

server Api does not receive link requests ，this request is not sent to the back end

**Comment by stonemakers** [comment]
i have the same error ... axios<0.18.0>

**Comment by falost** [comment]
what OS are you ? @stonemakers

**Comment by MRFCY** [comment]
It happens with axios api and jquery ajax api, I got a response status 0. I think it may be sth wrong with the CORS in wkwebview of iOS 12.  If any one had solved this problem?

**Comment by MRFCY** [comment]
@falost Do you mean I could set only content-type and Accept in my request header ?

**Comment by falost** [comment]
@MRFCY  yeah, i think so. but you can look concept-header-list

**Comment by falost** [comment]
@stonemakers  of course， [demo commit](https://github.com/fedte/alblog/commit/177ba962977f877eaf9c8e6a7110353a1a23c41d)  , I deleted the normal request header, and the reservation was uploaded.
` 'Content-Type': 'multipart/form-data' `

**Comment by stonemakers** [comment]
I have solved my problem. I changed my post method in this way：

```javascript
axios.post( apiUrl, qs.stringify({name: 'testName', pass: 'testPass'}), {
  headers: {
     'Content-Type': 'application/x-www-form-urlencoded'
  }
}).then(//***).catch(//***)
```

``` bash
1. install qs modules, and use qs.stringify(dataObject)
2.add axios config 
{
  headers: {
     'Content-Type': 'application/x-www-form-urlencoded'
  }
}
```

Here are sth comment about axios post: [link](https://stackoverflow.com/questions/50707146/ios-v12-https-requests-errors)

**Comment by Jialufeng** [comment]
ios12  ajax  post的 遇到同样问题  error  status返回0

**Comment by ovaldi** [comment]
http://www.openradar.me/40807782
https://stackoverflow.com/questions/50707146/ios-v12-https-requests-errors

This is iOS beta1 bug, and Apple has fixed it on iOS beta2.

**Comment by arfurs** [comment]
试了一下，IOS12 beta1版本确实是有这个bug

上面有的人说可以把Content-Type修改为application/x-www-form-urlencoded、multipart/form-data或text/plain 可以解决，也确实是这样的，但是这样解决的前提条件为你的HTTP headers中没有额外的header（也就是说不能超过跨域中的简单请求的包含范围 https://developer.mozilla.org/zh-CN/docs/Glossary/Simple_response_header）

注：Content-Type：application/json也被视为了非简单请求

我认为 @cyrecorg 所说的是正确的，在IOS12 beta1版本下，是浏览器内核触发了cors拦截，但仅仅拦截了**非简单跨域请求**，

**Comment by cangyu1993** [comment]
我需要在请求头加token，但是也是加不上，pc和安卓都没事，ios无法设置请求头和token

**Comment by yegeg** [comment]
service.interceptors.request.use(
  config => {
    if (config.method === 'post') {
      config.headers['Content-Type'] = 'application/json;text/plain'
      config.credentials = 'include'
    }
}
)

**Comment by linj0218** [comment]
没人想过在服务器做一些跨域设置吗

**Comment by falost** [comment]
设置了，这是一个 iOS 的 bug 官方已经修复了

**Comment by Sakyaa** [comment]
> 我需要在请求头加token，但是也是加不上，pc和安卓都没事，ios无法设置请求头和token

你解决这个问题了吗？？

**Comment by Abiglemonwang** [comment]
求问各位最终有解决的吗，ios12.4依然存在这个问题

**Comment by Adgeros** [comment]
> 求问各位最终有解决的吗，ios12.4依然存在这个问题

我也一样

**Comment by klhsb** [comment]
io原因是跨域请求会有问题，不支持Access-Control-Allow-Headers : *这种通配符；
解决方式：服务端把需要跨域的请求头设置给Access-Control-Allow-Headers，不用通配符；
参考了：https://blog.csdn.net/biakia0610/article/details/103777597
https://blog.csdn.net/Daijianshi_123/article/details/102853654
