### ISSUE TITLE
Is there a way to define a global error handler?

### ISSUE THREAD

**Issue by chovy** [axios/axios#1600]
Looking for a way to define a global error handler on my axios instance.

I tried this but the error block doesn't ever execute even when I take my backend down.

```
// set a default response handler
axios.interceptors.response.use(res => {
  return res;
}, err => {
  debugger;
  console.error(err);
  return Promise.reject(err);
});
```

**Comment by falost** [comment]
you can test it in ios12 , right or error, here is error

**Comment by chovy** [comment]
huh?

**Comment by BlueAccords** [comment]
hey @chovy did you ever figure this out?

**Comment by chovy** [comment]
No but I ended up just importing it on every api call:

```
import { api, globalErrorHandler } from './api/create-api';

api.get('/users')
    .catch(globalErrorHandler);
```

**Comment by BlueAccords** [comment]
Ah ok, thanks for the update! I'm trying to figure out a clean way to handle certain errors like server errors globally in my client side as well.

**Comment by falost** [comment]
update your os

**Comment by tarekadam** [comment]
I set up global error handling with interceptors.
https://github.com/axios/axios#interceptors

**Comment by AllainPL** [comment]
Apart from mentioned by @tarekadam `interceptors` as a way of doing that, AFAIK there is no such feature in the library.

**Comment by franzmoro** [comment]
> axios.interceptors.response.use(function (response) {
>     // Do something with response data
>     return response;
>   }, function (error) {
>     // Do something with response error
>     return Promise.reject(error);
>   });

Worked, but had to change @tarekadam 's code to use `request` instead of `response`
```js
axios.interceptors.request.use(
  // ...
)
```

**Comment by chinesedfan** [comment]
`interceptors` should be able to do that. If someone still has this kind of problem, feel free to open a new issue.
