### ISSUE TITLE
onUploadProgress is not working with CORS

### ISSUE THREAD

**Issue by Zewkin** [axios/axios#1602]
This works:

```
const res = await axios.post(this.url, body, { 
    headers: this.headersObj 
});
```

This throws error:

```
const res = await axios.post(this.url, body, { 
    headers: this.headersObj, 
    onUploadProgress: progressEvent => console.log(progressEvent.loaded)
})
```

![image](https://user-images.githubusercontent.com/3065426/41354951-fcdc4fc8-6f28-11e8-8142-cb19e03032d3.png)

Bug?

#### Context

- axios version: v0.18.0
- Environment: node v9.6.1, chrome 67, macOS 10.13.4

**Comment by yehoan** [comment]
i  also hava   same problem  and  not know how to solve

**Comment by pynner** [comment]
Having same problem, @Zewkin  @yehoan did you ever find a solution?

**Comment by Zewkin** [comment]
@pynner the problem was actually with the backend. When subscribing to onUploadProgress, browser sends preflight OPTIONS request before POST, but back was not configured properly to handle OPTIONS requests and responded with 400.

**Comment by pynner** [comment]
Ahh ok makes sense. Thanks @Zewkin. 

I might be out of luck then, as this remote server is a third party server not controlled by me.
