### ISSUE TITLE
axios is not fetching the complete API data

### ISSUE THREAD

**Issue by webmastervishal** [axios/axios#1604]
This sounds weird but it's true.

When I hit the API in postman, I get proper data but when I call the same API from axios in my react project I get data but with some missing values.

Data returned by the postman
![postman](https://user-images.githubusercontent.com/15266438/41366226-0beaef6c-6f59-11e8-87a3-0ab1fe2173b9.png)

And the data retured by axios
![axios](https://user-images.githubusercontent.com/15266438/41366243-15d9a306-6f59-11e8-9702-670d844287f6.png)

foodoutlets array is missing in the response returned by the axios.

#### Context
- axios v0.18.0

**Comment by srph** [comment]
Hey there - If you don't mind, can you provide your code?

**Comment by webmastervishal** [comment]
```
axios.get('https://sandboxapi.ampcome.com/api/gokhana/restaurant/categorized', {
        headers: {'Authorization': 'WqQg2jqLWVIO5JBmQ1LYHU8w41FdzLEsCB6yP1Tw2AFHf2w5KWRkMBV8KAgY6Kl5'},
        params: {
            geopoint: {"near":{"lat":12.9699,"lng":77.6499},"maxDistance":50,"unit":"kilometers"},
            categories: ["nearby","popular"],
            outlettypes:["restaurant","foodcourt"],
            clientapp:'gokhanacustomer'
        }
    })
    .then(res => console.log(res));
```
This is working fine when used it inside Postman or ARC.

**Comment by srph** [comment]
Have you tried using a different library to check if axios was the problem? Like `fetch`, for instance, just to check.

**Comment by webmastervishal** [comment]
Sorry, this problem isn't related to axios, I tried with different libraries like fetch and request getting the same results.
