### ISSUE TITLE
get header in GET request with a specific name

### ISSUE THREAD

**Issue by mmor93** [axios/axios#1606]
#### Summary

Hello
i am using axios for a get request and in the response's header there is a key like this:
x-pagination-total-count

i tried to get the value of this key by 'result.headers.x-pagination-total-count' and the result is undefined for this line of code.
how should i get this header?
#### Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v6.9.4, chrome 54, windows 7*

**Comment by msouidi309** [comment]
Hi, try to add 
```
Access-Control-Expose-Headers: 'x-pagination-total-count'
```
in the axios headers

**Comment by unguul** [comment]
@mmor93 Please check if #1901 helps.

**Comment by fed135** [comment]
Hey, thanks for submitting this issue. Since it has been inactive for a while and that our resources for maintaining and triaging are limited, we will be closing this ticket. If the issue persists on your end, please feel free to open a new issue.
