### ISSUE TITLE
dispatchRequest mutates `config` object

### ISSUE THREAD

**Issue by cherniavskii** [axios/axios#1609]
#### Summary

`dispatchRequest` mutates `config` object, which may confuse developers during debugging. 
Also, mutation is not recommended generally.

Consider this example:

```
axios.interceptors.request.use(function(config) {
  console.log(config);
  return config;
});
```

In this case `console.log` will log already mutated config (e.g. `headers` will be flattened object).
But it should log the actual value of `config` before mutation.

I can submit a PR ;)

#### Context

- axios version: v0.18.0
- Environment: node v8.11.2, chrome 65, windows 10

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks
