### ISSUE TITLE
can not make post request ( cross domain )

### ISSUE THREAD

**Issue by gogoIsComing** [axios/axios#1610]
hey:
i am trying to make post request from vue.js  `http://localhost:8080`  to express  `http://localhost:3000` using axios : 

![1](https://user-images.githubusercontent.com/33967218/41504305-6d6a6140-71f3-11e8-8f8c-92129f9af03c.png)

 and i get this error : 

![2](https://user-images.githubusercontent.com/33967218/41504310-7997dc18-71f3-11e8-87fd-a381c061c2a5.png)

server.js : 

![3](https://user-images.githubusercontent.com/33967218/41504312-7b16408e-71f3-11e8-8870-ff9fa5db378f.png)

- axios version: *0.18.0*
- Environment: *node v8.9.4, chrome 67, windows 10*

**Comment by cbuchert** [comment]
What are you using to serve your Vue assets? NginX? Caddy? Apache? Something else?

**Comment by gogoIsComing** [comment]
@cbuchert what do you mean by serving Vue assets !!!

**Comment by cbuchert** [comment]
What web server are you using to serve your Vue app?

**Comment by gogoIsComing** [comment]
@cbuchert i am using vuecli

**Comment by gogoIsComing** [comment]
@cbuchert it is local development using vuecli

**Comment by imatmati** [comment]
You should add to  you client the following headers through config object by example : 
```
 headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, PATCH, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Origin, Content-Type, X-Auth-Token"
  }
```

**Comment by steventurturo** [comment]
What are you using the bundle the assets with vuecli? Also which version of the cli, are you using? I had a similar issue with my Flask backend, but added a proxy table to my index.js in my config folder with a target of my flask api backend.

**Comment by gogoIsComing** [comment]
@imatmati i tried this , and still not working

**Comment by imatmati** [comment]
To be precise, I don't mean in server side but in client side. Here an example : 

```
const instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, PATCH, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Origin, Content-Type, X-Auth-Token"
  }
});
```

**Comment by gogoIsComing** [comment]
@imatmati yes i did this in client side and still not working

**Comment by sakataa** [comment]
We need to use application/x-www-form-urlencoded format and serialize form data with qs or URLSearchParams
Please refer this: https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
