### ISSUE TITLE
Feature Request: convenience methods to get `data` directly from response

### ISSUE THREAD

**Issue by Gaafar** [axios/axios#1614]
#### Add convenience methods to return `data` directly instead of the whole response object

99% of the time I'm using axios, I'm only interested in the `data` part of the response, and I need to do destructuring to get it out of the response object. It'd be great if I can use another method that will return data only. This is more useful especially when you want to use another variable name for `data` and have to use named destructuring. This can be done by adding corresponding methods that return data only, eg:
```
axios(config) -> axios.data(config)
axios.request(config) -> axios.requestData(config)
axios.get(url[, config]) -> axios.getData(url[, config])
axios.post(url[, data[, config]]) -> axios.postData(url[, data[, config]])
```

example for current state:
```
const { data } = await axios.get(url)
// or 
const { data: result } = await axios.get(url)
```

suggested improvement:
```
const data = await axios.getData(url)
// or
const result = await axios.getData(url)
```

P.S. I'd love to help in the implementation if it's approved

**Comment by fed135** [comment]
With your suggestion, how would other users who are interested in the response object get their info ?
The destructuring options are very elegant in my opinion.

**Comment by Gaafar** [comment]
As I suggested, it can be a different function that returns data only like: `axios.getData, postData, ...`, or maybe the same function name with an option like `dataOnly: true`. The assumption is that 90% of the time we're only interested in the response body so we can use the `data` method to avoid the extra destructure, and if we need the headers or other info, we can easily switch to the original method.

data example: `const json = await axios.getData(url)`
full example: `const { data, headers } = await axios.get(url)`

**Comment by chinesedfan** [comment]
Interesting proposal. But we suggest users to achieve similar APIs by interceptors or their own wrapper.

**Comment by LeCoupa** [comment]
What about something like Nuxt is doing with $get, $post or $put?

https://axios.nuxtjs.org/usage.html#shortcuts

**Comment by Gaafar** [comment]
Sounds good as well. The exact naming can be discussed but AFAIK the maintainers are not interested in the idea

**Comment by determin1st** [comment]
the problem with this approach is that it should explicitly state error handling method,
because if the request fails for some reason, it may throw an exception that wont be handled..

**Comment by Gaafar** [comment]
I don't understand why error handling is different for `axios.getData` than it is for `axios.get`. Can you explain with a code example maybe?

**Comment by determin1st** [comment]
well, that's quite obvious
```
data = await axios.getData(url);
```
if this fails, what would be the `data`? it cant be any "legal" value, like `null` so you should return some AxiosError and check it or you should do:
```
try
  data = await axios.getData(url)
catch e
  // error handling here
```
the later makes things more complex, because axios promise throws by default so it's the way of handling errors. check out my repo, ive described all possible paths of handling result with "only data" option.

**Comment by Gaafar** [comment]
If the request fails it should throw an error exactly like `axios.get`, not return null or anything. The only difference is that in the case of success, we return `response.data` instead of `response`

**Comment by determin1st** [comment]
yep, i wrote a try..catch for this case, which is extra stuff you have to do.
