### ISSUE TITLE
Once a request cancels never can be triggered again

### ISSUE THREAD

**Issue by hazzo** [axios/axios#1617]
### Summary

Once a request is canceled I can't trigger it again.

Example: 
I make an http request on component mount (Vue). 
If component destroys I cancel the request.
But on next mount the request gets canceled and never will be triggered again.

How can I resume the previous canceled request on component mount?

#### Context

- axios version: ^0.18.0
- Environment: Vue 2.5.2

**Comment by hazzo** [comment]
Finally I could make it work. But just with the executor function, I wasn't able to do it with the source method.

Closing this issue.

**Comment by DusuWen** [comment]
hi there, how did you make it work again?i have same question
