### ISSUE TITLE
Cross Site OAuth 1.0 With Consumer Key and Secret Using Axios 

### ISSUE THREAD

**Issue by joeljerushan** [axios/axios#1621]
How to Make an OAuth 1.0 with Consumer Key and Secret Using Axios 
is it possible to do something like this check screenshot my back-end response is fine but i wonder how to use Axios to make OAuth

![image](https://user-images.githubusercontent.com/10111309/41733791-a259ae30-75a2-11e8-8a4b-74acf1446d95.png)

**Comment by roylkng** [comment]
can anyone update how to add Consumer Key and Secret with axios request for oauth 1.0.

**Comment by mchampaneri** [comment]
Any updates over this ?

**Comment by chinesedfan** [comment]
I think OAuth is a kind of hash algorithm. It depends on the consumer secret and key to calculate some special http request headers. For someone who is familiar with the algorithm, it is easy to implement a request interceptor of axios.

Please correct me if I am wrong. And glad to add this kind of interceptor to our [ECOSYSTEM.md](https://github.com/axios/axios/blob/master/ECOSYSTEM.md).
