### ISSUE TITLE
Provide a method to get the URI an axios instance would use

### ISSUE THREAD

**Issue by atrauzzi** [axios/axios#1624]
I'd love to be able to configure an axios instance and rather than use it to send a request, simply get back the URI it would generate based on all the defaults.

The main benefit here would be that I could take configured instances and either use them for async communications, or pull the URI out and use them for the `src` attribute in HTML elements, etc...

**Comment by delirius325** [comment]
Hi @atrauzzi,

Sorry for the late response..! I'm not sure what you specifically want to achieve, but from what I gather, I believe the use of interceptors could help you! 

Basically, you could use an interceptor to store the URL of an axios request into a variable, and then use it to populate a ```src```attribute as you mentioned.

See the example below:

```javascript
const axios = require('axios');
let myVars = [];

axios.interceptors.request.use(function(config) {
	console.log(config);
        // Typically, you would "return config" here
        // But for your use case, you could assign the URL to another variable like so :
        myVars.push(config.url);
}, undefined);
```

You could then use the content of ```myVars``` (or any other variable) to populate your ```src```attributes.

**Comment by atrauzzi** [comment]
Does this require that I trigger the request for the interceptor to be called?

**Comment by delirius325** [comment]
Indeed it would, you would have to trigger something like ```axios.get('url')``` for the interceptor to be triggered. 

Could you perhaps elaborate on your use case? I'm not sure I understand why you would like to use axios instances without ever actually making any requests. After all, Axios is a HTTP client so the sole purpose of the tool is for you to make requests.

I might be missing something here.
Cheers 😄 !

**Comment by atrauzzi** [comment]
Yeah, I think that approach while it might _function_, would be a bit unwieldy as I don't want to limit my axios instance.  I'd be stuck adding the interceptor, arbitrarily calling axios, getting the captured URL and then removing the interceptor so that other things could use it for real requests.

Seems like that might be too far into workaround turf.

---

#### Use case...

_All of this is unrelated to axios, so I'm not so much asking you to buy into what I've got going for myself, just that axios is figuratively a millimetre away from being able to help out:_

My use case is that I statically generate my route table from my server side framework as some JS config objects.  If I have a portion of my UI that needs an `<a href` download link, or an image `src`, I want to use the routing table that being turned into axios config already.

---

Again, feel free to just not care about all that.  What I'm really talking about is something axios is already doing internally.  Exposed as a feature, it would be a method on axios that does everything up to but not including sending a `GET` request.  Instead, all it returns is the URI it would have tried to reach out to.

#### The rationale...
Rather than me recursively merging config structures and then clumsily concatenating strings - or taking on another dependency that literally does what axios is already doing internally -- I'm sure somewhere inside of axios, it assembles the scheme, host, port, path, hash and query for a URI before sending a request.

So, given axios is already able to digest its configuration schema into a viable request URI, it would be nice to get access to it too.

Note: I still want axios as an HTTP client, but the neat thing here is that a configurable HTTP client is a superset of a request URI builder.

😄 - hope that all makes sense!

**Comment by delirius325** [comment]
I get it now! Thanks for the in-depth explanation! 

Although, I'm not sure how I personally could help then... So hopefully someone else can jump in and help you with your request 😄 !

Cheers!

**Comment by delirius325** [comment]
Hey there @atrauzzi,

I was just thinking basically what you want is to be able to access the URL of an already created axios instance, right?

Then why not just do something like:

```javascript
import axios from 'axios';

const fakeConfig = {
    adapter: () => { return 'dummy' },
    transformRequest: { '0': () => { return 'dummy' } },
    transformResponse: { '0': () => { return 'dummy' } },
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: () => { return 'dummy' },
    headers: { Accept: 'application/json, text/plain, */*', 'Content-Type': 'application/json;charset=utf-8' },
    method: 'post',
    url: 'http://localhost:7500/',
    data: { dummy: 'data' }
}
const myInstance = axios.create(fakeConfig);
console.log(myInstance.defaults.url);
```
See if you execute this code, you'll get :

```bash
http://localhost:7500/
```

You simply access the config's URL property 😄.

Again, feel free to shut this idea down if this is not explicitly what you're looking for 😃.
Cheers,

**Comment by atrauzzi** [comment]
Haha, well I won't call it shutting down, but the issue is that I don't want the URI of the instance, I want the URI of the result of a call to a configured instance.

So, getting the values from the instance would only get me up to everything but the last step.  I have a utility class that provides my configuration structure and named routes functionality around axios:

```typescript
    public async call<ResponseDataType = any>(name: ConfiguredRouteKey, routeParametersOrConfig?: any|Partial<AxiosRequestConfig>, extraConfiguration?: Partial<AxiosRequestConfig>) {

        const route = this.getRoute(name);

        const configuration = this.createAxiosRequestConfiguration(
            route,
            routeParametersOrConfig,
            extraConfiguration || routeParametersOrConfig
        );

        const request = this.axios.request(configuration);
        const response = await request;

        return response.data;
    }
```

The call to `this.axios.request` receives the value `configuration`, which has information that wouldn't be included if I only used the instance itself.  It would be missing all the _good bits_.

**Comment by delirius325** [comment]
I think I've got an idea of how to implement such a method. I'm working on a little something right now 😄 !

**Comment by delirius325** [comment]
Morning @atrauzzi,

I added a method called ```getUri()```as you suggested. There's a usage/output example in the PR 😄.

Cheers,

**Comment by atrauzzi** [comment]
Whoaoa, thank you so much!

🎉 🎈

**Comment by delirius325** [comment]
No worries, it was really nothing in the end 👍 !
Glad to help 😄 !

**Comment by trushkevich** [comment]
Hi, thanks for the work you do! 
Unless I miss something the `getUri` function seems to misbehave for nested url params:
```javascript
    const config = {
      method: 'get',
      url: 'http://localhost:3000/test',
      params: {
        foo: {
          bar: 1
        }
      }
    }
    axios.getUri(config)
```
this generates the following uri:
```
http://localhost:3000/test?foo=%7B%22bar%22:1%7D
```
while personally I would expect to get
```
http://localhost:3000/test?foo[bar]=1
```

**Comment by delirius325** [comment]
@atrauzzi 	GitHub sent me a notification for this - can't seem to see why though. However, I see that it is still opened, this can be closed right?

Thanks 😄 !

**Comment by atrauzzi** [comment]
Yeah, same!  I'll close it now, I think we're all happy -- hah.
