### ISSUE TITLE
random hang axios.all

### ISSUE THREAD

**Issue by k3341095** [axios/axios#1626]
- axios version: v0.18.0
- Environment: node v8.9.3 windows 10 , linux same problem

            await axios.all(templist.murl.map((l) => {
                console.log('murl in')
                return axios.get(l, {
                        timeout: 3000
                    })
                    .then((response) => {
                        return response
                    })
                    .catch((err) => {
                        console.log(err)
                        return Promise.reject(err)
                    })
            }))

https://github.com/axios/axios/issues/124  -> same problem 

The problem is, even with the timeout settings some of the requests above hang indefinitely

timeout setting ignore... hang indefinitely

                let hurlGetData = templist.hurl.map((l) => {
                    return request({uri:l, method:'GET', resolveWithFullResponse: true})
                        .then((response) => {
                            return response
                        })
                })
                let res = await Promise.all(hurlGetData)

I solved it with the request module. It is no problem. It seems to be a problem with axios.

I'm sorry I did not speak English.
Translated and translated into google translator.

**Comment by jmonster** [comment]
I just ran into this same issue. It literally just hangs and no errors are thrown. I run the same script 10x and 2 of them just hang.

```js
const baseURL = "http://somewhere";

const axios = require('axios').create({
  baseURL,
  timeout: 1000,
  params: { apiKey: someKey }
});

axios
.get(uri)
.then(({ data }) => {
  console.log('this gets called about 5 times and then the entire app just pauses waiting for the rest'); 
  callback(null, data);
  })
.catch((err) => {
  console.error(err); // this doesn't print anything when things are going badly (but it does when a network request legit fails)
});

**Comment by nastycoder** [comment]
We ran into the same problem. As a work around we leveraging a [CancelToken](https://github.com/axios/axios#cancellation) and setTimeout combo.

**Comment by PhilSwift7** [comment]
try using 0.19.0-beta.1, I think #1040 fixed it and it's fixed there.

**Comment by Marcholio** [comment]
@k3341095 can you confirm if this is fixed now?

**Comment by godhar** [comment]
I am experiencing this on `"axios": "^0.19.0"` and `"node": "10.0.0"` just hangs on `axios get.()` with Bearer auth header, no error, no thing. Any good workarounds for this?

**Comment by chinesedfan** [comment]
Closed due to lack of the original author's feedback. If other users have found the same problem, feel free to open a new issues. Thanks.
