### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type object

### ISSUE THREAD

**Issue by Jeesoong** [axios/axios#1627]
#### httpAgent seem doesn't work

my configure

`const Agent = require('agentkeepalive')`
`const keepaliveAgent = new Agent({
  maxSockets: 100,
  maxFreeSockets: 10,
  timeout: 60000,
  freeSocketKeepAliveTimeout: 30000 // free socket keepalive for 30 seconds
})`
`axios.defaults.httpAgent = keepaliveAgent`

then console report error

`TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type object
    at new ClientRequest (_http_client.js:102:11)
    at Object.request (http.js:41:10)`

#### Context

- axios version: v0.18.0
- Environment: node v10.1.0

**Comment by ivan-kleshnin** [comment]
Same error. Tried:

```js
 A.defaults.baseURL = `https://localhost:8080`
 A.defaults.httpsAgent = new HTTPS.Agent({
   keepAlive: true,
   rejectUnauthorized: false,
 })
```

Replaced with:

```js
let axios = A.create({
```

but first is more convenient so I'd like to get this fixed.

**Comment by ashersaupingomez** [comment]
Any possibility of getting this working with defaults as opposed to having to create an instance?

**Comment by eNzyOfficial** [comment]
> Any possibility of getting this working with defaults as opposed to having to create an instance?

Bump

**Comment by yongqiangyue** [comment]
// 创建axios实例
const service = axios.create({
    baseURL: process.env.BASE_API, // api的base_url
    timeout: 15000, // 请求超时时间
    httpsAgent: new https.Agent({
        rejectUnauthorized: false
    })
})
it's ok

**Comment by tigermax139** [comment]
```
const myUri = <you url string>
const protocol = my Uri.startsWith('https') ? https : http;
const agent = new protocol.Agent({
  rejectUnauthorized: false,
});
```

**Comment by juberjj** [comment]
Hi there,

I've tried the suggested by @ivan-kleshnin  but no luck.

I'm importing axios then on my constructor I call ```this.instance = axios.create()``` but i do get the same error. Any other work around?

Thanks.
