### ISSUE TITLE
Interceptor-(Request/Response/Error)-Config-Object: Base Url is included in url. 

### ISSUE THREAD

**Issue by LukasOchmann** [axios/axios#1628]
#### Summary

I create an axios instance with a default baseURL. `axios.defaults.baseURL = '/base/'`;
Then i create an response- interceptor, which should retry the request if the first try resolves as an Error.

In the interceptor i run `axios.request(err.config)`. Tis requests leads in too 404 because it trys to route to `/base/base/Something` instead of routing to `/base/Something`.

The config object of the first try looks like: `{baseURL: '/base', url: '/base/Something'}`. 
In my Opinion `'/base'` should not be included in the `url`.

By now i need to replace the baseUrl by hand before i can do the retry. 

#### Context

- axios version: *v0.16.2*
- Environment: *node v8.9.1, chrome 67.0.3396.79, Ubuntu 16.04*

**Comment by samxcode** [comment]
I have also meet this problem.

**Comment by vasilich6107** [comment]
Hey)
Me too!
If I try to retry the request with `axios(originalRequest)` it will prepend `baseURL` second time

**Comment by kr094** [comment]
This is a pretty major blocker for using axios-retry. Please see https://github.com/nuxt-community/axios-module/issues/114

**Comment by multicolaure** [comment]
The bug was introduced when fixing this issue : https://github.com/axios/axios/issues/949

When fixing this issue, we should pay attention not to restore the original bug.

**Comment by simo-eskalera** [comment]
when will this land?
my current workaround is:
```
...
originalRequest.baseURL = originalRequest.url
originalRequest.url = ''
return axios(originalRequest)
```

**Comment by gitzhangliang** [comment]
when i use webpack build ,this problem disappeared. but not use webpack build , this problem exist.
this is my issue[retry request problem #2833]

**Comment by rafaelgfx** [comment]
I'm using an API to enable [cors-anywhere](https://github.com/Rob--W/cors-anywhere),

So basically I need to join the request url with the CORS API url, I was trying to do like:

```
import axios from 'axios';

const api = axios.create({
  baseURL: 'https://cors.api/',
});

export default api;

...

api.get('https://my-request-url');
```
But I can't do it anymore.

I also tried using interceptors like:

```
api.interceptors.request.use((config) => {
  config.baseURL = 'https://cors.api/';
  return config;
}, (error) => Promise.reject(error));
```

The PR https://github.com/axios/axios/pull/2391 says that the request interceptors should modify the baseURL but doesn't seem to do so.

I don't want to pass both URL on every request. Is there another way to do it?
