### ISSUE TITLE
axios request.upload.addEventListener in not a function

### ISSUE THREAD

**Issue by camelDx** [axios/axios#1630]
axios: request.upload.addEventListener in not a function。

**Comment by junj1e** [comment]
yes，I also meet the problem. when using the axios config onuploadProgress in electron. The error info is below.
`Uncaught (in promise) TypeError: request.upload.addEventListener is not a function
    at dispatchXhrRequest (xhr.js?b50d:156)
    at new Promise (<anonymous>)
    at xhrAdapter (xhr.js?b50d:12)
    at dispatchRequest (D:\pyramid\node_modules\axios\lib\core\dispatchRequest.js:59)`
how to solve it?

**Comment by camelDx** [comment]
I use Mock, It has change XhrRequest this object。And it's new name MockXhrRequest ， it doesn't has upload event. So you could find problem about this way in the electron？Has it change the XhrRequest of object.

At 2019-01-24 17:13:19, "junjie" <notifications@github.com> wrote:


yes，I also meet the problem. when using the axios config onuploadProgress in electron. The error info is below.
Uncaught (in promise) TypeError: request.upload.addEventListener is not a function at dispatchXhrRequest (xhr.js?b50d:156) at new Promise (<anonymous>) at xhrAdapter (xhr.js?b50d:12) at dispatchRequest (D:\pyramid\node_modules\axios\lib\core\dispatchRequest.js:59)
how to solve it?

**Comment by hilanmiao** [comment]
> axios: request.upload.addEventListener in not a function。

Don't use Mock！

**Comment by chinesedfan** [comment]
This problem is caused by the mocked XHR. If you persist, make sure everything is mocked well.
