### ISSUE TITLE
How do I define Headers for only the receiving method?

### ISSUE THREAD

**Issue by VCodepp** [axios/axios#1634]
I am using vue CLI.

We have set up authorization with axios.defaults.headers.common.Authorization with maint.ts . because it is necessary for the post method.

but they have some problems. Get method 'titles' should not be set.

how can i set header for get methodu only.

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
