### ISSUE TITLE
Support for brotli compression

### ISSUE THREAD

**Issue by therealmarv** [axios/axios#1635]
#### Summary

We turned on the brotli compression on our nginx backend and tried to use our nuxt.js frontend on top of this.

After some debugging we figured out we get strange responses and Axios could not handle them on the frontend.

It turned out Axios cannot handle brotli responses yet. It needs to decompress them with a brotli decompressor.

Relevant LOCs are here:
https://github.com/axios/axios/blob/cb630218303095c0075182b542ccb2f72d20dd9d/lib/adapters/http.js#L156-L160

Just some backend Ubuntu Linux example on how to get brotli running easily in nginx without compiling (see ppa in this article): https://certsimple.com/blog/nginx-brotli

#### Context

- axios version: axios@0.18.0
- Environment: nuxtjs/axios@5.3.1, Chrome 68, macOS 10.13.5

**Comment by manniL** [comment]
Second this

**Comment by therealmarv** [comment]
@Mattwmaster58 a brotli JS based decompression could work with "case" handling as I showed in the bug report. So yes, a PR is needed. There are some brotli JS libraries available.

**Comment by jamessawyer** [comment]
I want to use brotli in a react native project. It's a great feature, please add it to axios! thanks

**Comment by chinesedfan** [comment]
#2661 has added an option to disable the default decompress. Then users can decompress data with customized algorithms by themselves, with help of `responseType: stream` and `transformResponse`.

```
axios({
  decompress: false,
  responseType: 'stream',
  transformResponse(data) {
    return data.pipe(zlib.createBrotliDecompress())
  }
})
```
