### ISSUE TITLE
Unhandled Error Handler

### ISSUE THREAD

**Issue by tkrause** [axios/axios#1636]
#### Summary

We would like to add a "catch all" error handler for exceptions that are not caught explicitly by a developer. However, axios does not seem to propagate this error up to the unhandledrejection or error event on window.

```
// API Call
axios.get('/my-400-route').then(r => console.log(r))
```

```
// Error Handlers
window.addEventListener("unhandledrejection", event => {
    event.preventDefault()

    console.log('its k i got ya')

    console.warn("WARNING: Unhandled promise rejection. Shame on you! Reason: "
        + event.reason);
});

window.addEventListener('error', e => {
    e.preventDefault()

    console.log('its k i got ya 2', e)
})
```

![image](https://user-images.githubusercontent.com/1427628/41926994-bbf0a7fa-7925-11e8-91f2-e2f6f4868674.png)

#### Context

- axios version: axios@0.18.0
- Environment: Chrome 67, OS X 10.13.4, Webpack, VueJS 3.0

**Comment by olsonpm** [comment]
I just spent a long time wrestling with this - the issue isn't with axios but how chrome deals with unhandled rejections.

For example, this causes your issue
```
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.js"></script>
  <script src="/unhandled-rejection-code.js"></script>
</head>
```

but if you `wget` that exact resource then serve it locally, your unhandledrejection hook works as expected
```
<head>
  <script src="/axios.js"></script>
  <script src="/unhandled-rejection-code.js"></script>
</head>
```

I think it has something to do [with this](https://stackoverflow.com/questions/40026381/unhandledrejection-not-working-in-chrome), but I'm not sure.

**Comment by githoniel** [comment]
Chrome's CORS protection, error threw from different domain can't be caught.

It can be resolve by using a promise polyfill that support 'unhandledrejection'

**Comment by fed135** [comment]
Hey, thanks for submitting this issue. Since it has been inactive for a while and that our resources for maintaining and triaging are limited, we will be closing this ticket. If the issue persists on your end, please feel free to open a new issue.
