### ISSUE TITLE
I want to rewrite the error message 'network error', bug the function request.onerror don't provide a response

### ISSUE THREAD

**Issue by boxfish-ty** [axios/axios#1637]
This is because the XHR request fails at the browser level (during the OPTIONS call), which is technically a network error. For network errors, axios does not provide a response because one is not provided by the browser.
-----------------------------------------------------
Sometimes, we will intercept the request and return a response with a custom field，it will trigger the function request.onerror, but, it can not return the response.
How can i do to get the custom response.

now:
```
// Handle low level network errors
request.onerror = function handleError() {
  // Real errors are hidden from us by the browser
  // onerror should only fire if it's a network error
  reject(createError('Network Error', config, null, request));
  // Clean up request
  request = null;
};
```
we want:

```
// Handle low level network errors
request.onerror = function handleError(response) {
  // Real errors are hidden from us by the browser
  // onerror should only fire if it's a network error
  reject(createError('Network Error', config, null, request, response));
  // Clean up request
  request = null;
};
```

**Comment by chinesedfan** [comment]
> reject(createError('Network Error', config, null, request, response));

Yes, just as your issue description says, the browser doesn't provide it. There is no response as all, so does axios.

One workaround I can image is that making your server responses a response with other http code, like 5xx.
