### ISSUE TITLE
How the ` promise. All ` capture in the wrong?

### ISSUE THREAD

**Issue by sowork** [axios/axios#1639]
#### Summary
I sent several requests, unified handling errors in the interceptor, when I use a promise.all () to send multiple requests, Multiple error prompts are output, whether can unified processing in the interceptor promise.all () the response?

`
ajax.interceptors.response.use((response) => {
    if (response.data.access_token) {
        Cookies.set('bear', response.data.access_token);
        Cookies.set('refresh_bear', response.data.refresh_token);
        Cookies.set('expires_in', response.data.expires_in);

        ajax.defaults.headers.common['Authorization'] = 'Bearer ' + response.data.access_token;
    }
    if (response.data.code !== undefined) {
        if (response.data.code === '-1') {
            const err = new Error(response.data.msg);
            err.response = response;
            Message.error(response.data.msg);
            throw err;
        } else if (response.data.code === '-2') {
            const err = new Error(response.data.msg);
            err.response = response;
            Message.error(response.data.data[0]);
            throw err;
        }
    }
    return response;
}, (error) => {
    // Do something with response error
    if (error.response) {
        switch (error.response.status) {
            case 400:
                error.message = '404 error!';
                break;
            default:
        }
    }
    Message.error(error.message);
    return Promise.reject(error);
});
`

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
