### ISSUE TITLE
Content-Type application/x-www-form-urlencoded does not encode symbol '+' and '&' correctly

### ISSUE THREAD

**Issue by yuanchenxi95** [axios/axios#1640]
#### Summary
Try 
```javascript
const axios = require('axios')

axios({
  method: 'post',
  url: 'http://localhost:3000/user',
  data: {
    phone: '+8611111+8622222',
  },
  headers: {
    'content-type': 'application/x-www-form-urlencoded;charset=utf-8'
  }
})
```
What server receives is 
```javascript
'{"phone":" 8611111 8622222"}': '' }
```
It seems that '+' is being replaced by ' '.

#### Context

- axios version: v0.18.0
- Environment: node v8.11.1

**Comment by emilyemorehouse** [comment]
Hi @yuanchenxi95,

You'll want to explicitly encode when using `x-www-form-urlencoded`, like this:

```
var axios = require('axios')
var qs = require('qs')

axios({
  method: 'post',
  url: 'http://localhost:3000/user',
  data: qs.stringify({
    phone: '+8611111+8622222',
  }),
  headers: {
    'content-type': 'application/x-www-form-urlencoded;charset=utf-8'
  }
})
```

Check out the [README](https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format) for more info and alternative approaches.

**Comment by VeronicaEms** [comment]
@emilyemorehouse  thank you so much!!!!!!!!!!!!!!!!!!!!

**Comment by donejeh** [comment]
@emilyemorehouse wow you really save me today!!!
