### ISSUE TITLE
Axios overwrite Content-Type when sending a blob/file with type.

### ISSUE THREAD

**Issue by Gerhut** [axios/axios#1643]
Here is the error case: <https://codepen.io/Gerhut/pen/OErpQm?editors=0012>

Browsers will set Content-Type header automatically from `Blob#type` or `File#type` (if exists) when sending a Blob/File through xhr, which is overwritten by `axios.defaults.headers.post`.

Shall we provide a specific behavior about this case, either remove the `Content-Type` and let it be set by the browser (like FormData) or set it as `Blob#type` or `File#type` manually to increase compatibility? (Although I don't know if there is any browser don't set `Blob#type` or `File#type` in xhr.)

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks
