### ISSUE TITLE
why my params unhandled by encodeURI?

### ISSUE THREAD

**Issue by hezhongfeng** [axios/axios#1644]
#### Summary
When I start a get request.My params cant be encoded.

#### Context
- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: nod8 v8.11.1, chrome 65, windows 10*
```
      let params = {
        msg: '[(H)]'
      };
    axios
      .get(urls.customerService.CSList, { params: params })
```
I think ‘[’and ']' will repleased by '%5B' and '%5D'.
In fact the Request URL:  `http://localhost:2347/admin/cs/listMyCSGroup.jhtml?msg=[(H)]`.

**Comment by hiyangguo** [comment]
I have the same problem.[source](https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js#L5) 
```
function encode(val) {
  return encodeURIComponent(val).
    replace(/%40/gi, '@').
    replace(/%3A/gi, ':').
    replace(/%24/g, '$').
    replace(/%2C/gi, ',').
    replace(/%20/g, '+').
    replace(/%5B/gi, '[').
    replace(/%5D/gi, ']');
}
```
How did you resolve it?

**Comment by hezhongfeng** [comment]
@hiyangguo 
I think the encode  func is not be executeed.

**Comment by hiyangguo** [comment]
@hezhongfeng You can [set paramsSerializer](https://github.com/axios/axios/blob/master/README.md#request-config) to resolve it .

**Comment by Abhicoding** [comment]
@hezhongfeng @emilyemorehouse
It looks like a non-issue. The function below is running the `encodeURIComponent` on '[(H)]' and returning `%5B(H)%5D`, but the last two replace functions are changing it back to '[(H)]'


```
function encode(val) {
    return encodeURIComponent(val).
    replace(/%40/gi, '@').
    replace(/%3A/gi, ':').
    replace(/%24/g, '$').
    replace(/%2C/gi, ',').
    replace(/%20/g, '+').
    replace(/%5B/gi, '[').
    replace(/%5D/gi, ']');
}
```

**Comment by ourfeel** [comment]
I don't understand what do this func

**Comment by lili21** [comment]
any update ?

**Comment by lili21** [comment]
Is there any specific reason to do that `replace` job ?

**Comment by cambraca** [comment]
Created PR #2563 to fix this and other similar issues.

**Comment by jasonsaayman** [comment]
On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the qs library:
```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

**Comment by GrahamLea** [comment]
@jasonsaayman (or @mzabriskie, who committed it years ago), do you have an idea why this code is in there? I'm curious because it breaks on some web servers, e.g. any modern version of Tomcat. (https://stackoverflow.com/a/41150474/243104)

**Comment by jasonsaayman** [comment]
@GrahamLea I cannot speak for why it was implemented, I also made that comment a long time ago so I am open for discussion on potentially fixing it or you can open a pull request if you want and add me as a reviewer?

**Comment by GrahamLea** [comment]
Thanks for the reply, @JasonSaayman. I doubt it's something that can be fixed without a huge backwards compat breakage. I was really just wanting to know why it was done. From what I can figure out from reading, it looks like passing small bits of JSON in the query string is something that some people like to do, and this makes it look a little prettier in logs, though technically it's creating invalid URLs. 🤷🏻‍♂️

For what it's worth, I ended up creating the follow `paramsSerializer` that creates a valid URL from a dictionary of string to string (only):
```typescript
// Axios' default param serialisation leaves in "unwise" characters that Tomcat rejects, in an
// attempt to allow some pseudo OGNL-like language to be passed in the URL.
// We don't need anything like that, so we're just doing a vanilla encoding for now.
// If we need anything fancy in future, maybe look into this: https://www.npmjs.com/package/qs#stringifying
// eslint-disable-next-line
axios.defaults.paramsSerializer = (params: any) => {
  if (typeof params !== "object") {
    throw new TypeError("paramsSerializer only handles params as an object");
  }
  const searchParams = new URLSearchParams();
  _.forEach(params, (value, name) => {
    if (typeof name !== "string" || typeof value !== "string") {
      throw new TypeError(
        "paramsSerializer only handles string keys and values"
      );
    }
    searchParams.append(name, value);
  });
  return searchParams.toString();
};
```
