### ISSUE TITLE
https request works with "https.request" but not in axios

### ISSUE THREAD

**Issue by itaied246** [axios/axios#1646]
I am stuck on this issue for hours now,
after going all over the threads I could find here in `github` and `stackoverflow`.

I want to issue an `http` request over `ssl` to a self signed certificate server.
I have created a bundle with the chain of certificate and issue the request like this:

```js
// https.request works
const httpsAgent = new https.Agent({ca})
https.request({
  hostname: 'my-site.com',
  path: '/api/data',
  port: 443,
  method: 'GET',
  agent: httpsAgent
}, (res) => res.on('data', console.log))
```

Where `ca` is just a variable string containing the base64 (`pem`) certificate chain.

```js
// axios throws "Error: unable to verify the first certificate"
const httpsAgent = new https.Agent({ca})
axios.get('https://my-site.com/api/data', {httpsAgent})
```

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.

**Comment by doron-au10tix** [comment]
Its not a support issue. Its seems like a bug. I have encountered the same. using the httpsAgent option for ca / self-signed client certificate doesn't work in axios.
