### ISSUE TITLE
Double quotes get escaped twice

### ISSUE THREAD

**Issue by arivanandan** [axios/axios#1649]
I'm JSON.Stringify-ing an object, putting it in another object and sending.

Stringification gives me a string:
`const post = '{"description":"Hug","title":"Guh","postType":"NEWS","newsId":103450}'`

Request looks something like:
`const data = { post }`
`axios.post(url, data, headers)`

This is what I see as the request:
`data: '{"post":"{\\"description\\":\\"Hug\\",\\"title\\":\\"Guh\\",\\"postType\\":\\"NEWS\\",\\"newsId\\":103450}"}' }`
`'Content-Type': 'application/json;charset=utf-8'`

Axios: 0.18
Env: React Native - 0.55

**Comment by arivanandan** [comment]
I supposed I used it wrong.

Change it to:
`const params = { post }`
`axios.post(url, null, { ...headers, params })`

**Comment by toymachiner62** [comment]
I'm having this same issue.
