### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames even with agentOptions.servername set

### ISSUE THREAD

**Issue by datpham23** [axios/axios#1650]
axios version: 0.18.0
node version: 8.11.2

I'm getting the following this exception:
```
Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not in the cert's altnames: DNS:localhost.company.com"
```
When trying to make the following request:
```
axios({
	method: 'get',
	url: `https://localhost:${API_PORT}`,
	agentOptions: new https.Agent({
		pfx: clientCert,
		passphrase: password,
		ca: ca,
		servername: 'localhost.company.com'
	})
});
```
The altname for the certificate was signed as "localhost.company.com".
When I make the same request w/ request-promise it works, it seems the 'servername' field doesnt get honor.
```
request({
	method: 'GET',
	uri: `https://localhost:${API_PORT}`,
	agentOptions: {
		pfx: clientCert,
		passphrase: password,
		ca: ca,
		servername: 'localhost.company.com'
	}
})
``

**Comment by frangeris** [comment]
Same error, different URL, seems related to the faq that since 0.9.2 (including 0.10.x) node.js now validates certificates by default.

```
Error: Hostname/IP doesn't match certificate's altnames: "Host: .us-east-1.amazonaws.com. is not in the cert's altnames: DNS:apigateway.us-east-2.amazonaws.com"
```

**Comment by b4dnewz** [comment]
what is the fix for that or at least how to turn off this validation?

**Comment by frangeris** [comment]
@b4dnewz If you're using nodejs put this before make the request:

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = false
```

**Comment by iamakshatjain** [comment]
Hey can anyone let me know why does that actually happens. Would be really helpful. Thanks in advance.

**Comment by bjaworski3** [comment]
Is there any way to properly set the `servername` for SNI? Setting `rejectUnauthorized` to false would work, but it isn't the best security practice since it doesn't actually verify the servers identity.

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
