### ISSUE TITLE
getting undefined on chrome and safari

### ISSUE THREAD

**Issue by naveenkumargceb** [axios/axios#1651]
I use axios along with Vue2.0 and webpack.
pathname undefined error from chrome and safari browser. It works fine from Firefox.

I did some debugging and placed the below code which gives me the expected values.
<script>
var a = document.createElement('a');
	a.setAttribute("href","https://testurl.com/testfolder/folder/file.html");
	var m = {href:a.href, pathname: a.pathname}
	console.log("test ",m); // {href: "https://testurl.com/testfolder/folder/file.html", pathname: "/testfolder/folder/file.html"}
</script>

But from the vendor.js, I get this.
{
  hash: "",
  host: undefined,
  hostname: undefined,
  href: undefined,
  pathname: undefined,
  port: undefined,
  protocol: "",
  search: ""
}

Exact error from console is: 
"Uncaught TypeError: Cannot read property 'charAt' of undefined"

https://github.com/axios/axios/blob/7d9a29ee4c597adacd8dcec6a6e3bdfe4983ab09/dist/axios.js#L1112

**Comment by Kepro** [comment]
ehm, can you share your code that is not working?

**Comment by fed135** [comment]
Hey, thanks for submitting this issue. Since it has been inactive for a while and that our resources for maintaining and triaging are limited, we will be closing this ticket. If the issue persists on your end, please feel free to open a new issue.
