### ISSUE TITLE
could you add support for yarn add ?

### ISSUE THREAD

**Issue by talwaserman** [axios/axios#1652]
I think because you don't have yarn enabled in this project, this cause my build flow to crash when i run yarn install.

**Comment by camflan** [comment]
@talwaserman I think we'll need more information. I, and many others, successfully use `yarn` to install this lib. I've never "enabled yarn" in any of my published npm packages and it hasn't caused any issues

**Comment by talwaserman** [comment]
So it must by another configuration in my environment. Thanks for the answer

בתאריך יום ב׳, 9 ביולי 2018, 19:20, מאת Camron Flanders ‏<
notifications@github.com>:

**Comment by delirius325** [comment]
Hi there @talwaserman,

I hope you fixed your issue 😄. If so, would it be possible for you to close this issue?

Cheers,
