### ISSUE TITLE
A better cancellation document

### ISSUE THREAD

**Issue by adeelibr** [axios/axios#1654]
#### Summary
Hi

This isn't a bug just a humble request. Can the Cancellation document be more improved https://github.com/axios/axios#cancellation with a couple more examples.

Mostly we have our API's in a separate folder and then we call those methods using async/await and then update our state in react. Now since the api methods params are in another file. How do we reference that cancel token request.

I am basically looking for an optimal approach on how to unsubscribe API request in componentWillUnmount.

#### Context

- axios version: *e.g.: latest*
- Environment: *e.g.: node v8*

**Comment by camflan** [comment]
@adeelibr I wrote an example of how to get this working a while back. It could be updated or incorporated into the document. Feel free to use it in a PR

https://github.com/axios/axios/issues/647#issuecomment-310204008

**Comment by joseph-animasds** [comment]
I am wondering the same thing as Adeelibr. I have my calls in another file being imported into a component. How do I use the token?

**Comment by adeelibr** [comment]
@joseph-animasds Hi, I wrote an article about it https://medium.freecodecamp.org/how-to-work-with-react-the-right-way-to-avoid-some-common-pitfalls-fc9eb5e34d9e Also if you want a quick intro to it a Kent C Dodds made a video log about it (on my request :)) https://www.youtube.com/watch?v=8BNdxFzMeVg

I hope this helps :) 

Cheers

**Comment by akkis** [comment]
I found [this article](https://medium.com/@selvaganesh93/how-to-clean-up-subscriptions-in-react-components-using-abortcontroller-72335f19b6f7), also useful with live example on codesandbox. It does explain the code in separate components.

**Comment by jasonsaayman** [comment]
Closing, as this is pretty old, please add a PR if you would like to improve the docs.
