### ISSUE TITLE
axios.head on a .gz file: unexpected end of file

### ISSUE THREAD

**Issue by petcarerx** [axios/axios#1658]
#### Summary

`axios.head` called on a .gz file throws an exception, presumably due to attempting to deflate a non-existent response body.

example: 
```javascript
(async function () {
    let res = await axios.head('http://rentitbae.s3.amazonaws.com/account/favourites/favourites-ctrl.js.gz');
})();
```
```javascript
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:142:17)
  errno: -5,
  code: 'Z_BUF_ERROR',
  //...
```

#### Context

- axios version: 0.18.0
- Environment: node v.9.5.0

**Comment by Blackslash333** [comment]
Same issue here

**Comment by tchock** [comment]
We have the same issue. When using a resource on `cloudfront` this wouldn't happen, because it dynamically encodes depending on `accept-encoding: gzip` header.
For resources directly served through s3 this is no option though.
Axios shouldn't try to unzip responses with no body.

**Comment by chinesedfan** [comment]
#1129 should have already fixed it.
