### ISSUE TITLE
response excel file in axios

### ISSUE THREAD

**Issue by damaimrs** [axios/axios#1660]
I have a api that return an excel file from backend, this is my code

`    'downloadErrorDetailBlast': function () {

      let url = '/api/' + auth2.currentUser.get().getBasicProfile().getEmail() + '/blasts/' + this.blastEmailId + '/files'      

      let options = {
        headers: {
          'Authorization': 'Bearer ' + this.$session.get('user').idToken,
          'responseType': 'application/vnd.ms-excel'
        }
      }

      axios.get(url, options)
        .then(this.downloadErrorDetailBlastSuccess)
        .catch(this.downloadErrorDetailBlastFailure)
    },
    'downloadErrorDetailBlastSuccess': function (response) {

        const url = window.URL.createObjectURL(new Blob([response.data], {type:'application/vnd.ms-excel'}));
        const link = document.createElement('a');
        
        link.href = url;
        link.setAttribute('download', 'Detail_Blast.xls');
        document.body.appendChild(link);
        link.click();
        console.log(response.data)
        alert("File Berhasil Didownload!")

    },`
But, when I console.log my response.data, the data seems weird like this

![image](https://user-images.githubusercontent.com/15611415/42409865-717b4d2c-820a-11e8-8eed-cb213e84e1f1.png)

I wanna download my respose.data as an excel file. What should I do?

**Comment by mkardas91** [comment]
try change options from
```
  let options = {
    headers: {
      'Authorization': 'Bearer ' + this.$session.get('user').idToken,
      'responseType': 'application/vnd.ms-excel'
    }
  }
```
to
```
  let options = {
    responseType: 'blob',
    headers: {
      'Authorization': 'Bearer ' + this.$session.get('user').idToken,
    }
  }
```

**Comment by mkardas91** [comment]
Good option is also use https://github.com/kennethjiang/js-file-download
```
const download = require('js-file-download');
axios.get(url, {
  responseType: 'blob',
})
.then(res => {
    download(res.data, 'Detail_Blast.xls');
 })
```

**Comment by Time-merchant** [comment]
hi, do u fix this bug?

**Comment by FlyingPigQAQ** [comment]
How to solve this problem?Someone can help me ?

**Comment by MoonSeeing** [comment]
@damaimrs  have you solve the problem ,can you tell me your solution?

**Comment by Koolile** [comment]
##  你可以用fetch
```
fetch(url, {
  cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
  credentials: 'same-origin', // include, same-origin, *omit
  headers: {
    'user-agent': 'Mozilla/4.0 MDN Example',
    'content-type': 'application/vnd.ms-excel;charset=UTF-8',
    'access_token': 'your_token'
  },
  method: 'GET' // *GET, POST, PUT, DELETE, etc.
})
.then(res => res.blob().then(blob => {
  const filename = decodeURI(res.headers.get('Content-Disposition').split('filename=')[1])  // 获取后端headers里面的文件名
  if (window.navigator.msSaveOrOpenBlob) {
    navigator.msSaveBlob(blob, filename)  // 兼容ie10
  } else {
    const a = document.createElement('a')
    document.body.appendChild(a) // 兼容火狐，将a标签添加到body当中
    a.href = window.URL.createObjectURL(blob)
    a.download = filename
    a.target = '_blank' // a标签增加target属性
    a.click()
    a.remove()  // 移除a标签
    window.URL.revokeObjectURL(url)
  }
}))
```

**Comment by chinesedfan** [comment]
The key point is as @mateuszkardas mentioned, as well as setting `responseType: 'blob'`.
