### ISSUE TITLE
new instance Influence the global instance

### ISSUE THREAD

**Issue by railgun20001** [axios/axios#1664]
i create new instance, and set this
instance.defaults.headers.common['test'] = 'test'
it also Influence the global instance

I find this issue #1522, and update axios to  0.18.0, but useless

- axios version: *e.g.: v0.18.0*
- Environment: *66.0.3359.117 （64）*

**Comment by delirius325** [comment]
Hey there @railgun20001,

Would it be possible for you to supply a quick code example?

Thanks,

**Comment by fqborges** [comment]
Having the same issue here.

Creating a custom instance for use on api calls here:
``` js
import axios from "axios";

const apiAxios = axios.create();

export function configureApiClient({ apiBaseUrl, authToken }) {
  apiAxios.defaults.baseURL = apiBaseUrl;
  apiAxios.defaults.headers.common["Authorization"] = `Bearer ${authToken}`;
}

export default apiAxios;
```

Somewhere else when making a specific call using the global axios:
``` js
import axios from "axios";
export function getSomething({ authToken }) {
  var headers = { AuthToken: authToken };
  return dispatch =>
    axios
      .get(url, { headers })
      .then(function(response) {
        // handle
      })
      .catch(function() {
        // handle
      });
}
``` 

It fails with CORS not allowing 'Authorization' header. Inspecting the call I can see axios is including the 'Authorization' header from the apiAxios instance.

**Comment by fqborges** [comment]
As a workaround, when you create an instance passing the deep object hierarchy it works.

```js
const apiAxios = axios.create({
  headers: {
    common: {},
  },
});
```

**Comment by delirius325** [comment]
@fqborges It might even work with an empty config object. 

```javascript
const apiAxios = axios.create({});
```

**Comment by jeffbaldwinjr** [comment]
I think I have been seeing a similar issue to this. Here is my test code, each instance has the Test header set to test, even if I set headers.common

`'use strict';

const axios = require('axios');

const request1 = axios.create({baseURL: 'http://www.google.com'});

const request2 = axios.create({});

request1.defaults.headers.common.Test = 'Test';

const request3 = axios.create({baseURL: 'http://www.github.com', headers: {common:{}}});

console.log(`Request 1 BaseURL: ${request1.defaults.baseURL} and Headers:`);
console.log(request1.defaults.headers.common);

console.log(`Request 2 BaseURL: ${request2.defaults.baseURL} and Headers:`);
console.log(request2.defaults.headers.common);

console.log(`Request 3 BaseURL: ${request3.defaults.baseURL} and Headers:`);
console.log(request3.defaults.headers.common);
`

**Comment by Mechazawa** [comment]
I'm having the same issue, looking around though this PR claims it fixes it but it doesn't https://github.com/axios/axios/pull/1395

**Comment by hayk94** [comment]
This issue is still not fixed, even with the pr

Suggestion by @fqborges acts as a workaround

**Comment by zcdll** [comment]
This issue is still affected.
And this repo hasn't been updated for a long time.

**Comment by lacockj** [comment]
I also have the issue where  also updates the Axios global default headers outside the instance.

```
// Create API instance during initialization
my.api = axios.create({
  baseURL: my.baseURL,
  timeout: my.timeout
});

// Set Auth Token after Login
my.setAuthToken = function (token) {
  my.api.defaults.headers.common['Authorization'] = "Bearer " + token;
}
```

Until this is fixed "properly", here's a workaround I found: creating a new instance each time you update the defaults.

```
// Set Auth Token after Login
my.setAuthToken = function (token) {
  my.api = axios.create({
    baseURL: my.baseURL,
    timeout: my.timeout,
    withCredentials: true,
    headers: {
      'Authorization': "Bearer " + token
    }
  });
}
```

**Comment by corescript** [comment]
This is a temporary workaround which I found...

`axios({
                url: API,
                method: 'POST',
                transformRequest:[function(data,headers){
                    headers.common = { accept:'application/json' };
                    return data
                }]
            })`

**Comment by chinesedfan** [comment]
Confirmed that for @jeffbaldwinjr's test cases, 0.19.0 has only the first request contains the extra header.
