### ISSUE TITLE
Conccurrent request statment breaks code

### ISSUE THREAD

**Issue by DanJ210** [axios/axios#1665]
This statement here

```
axios.all([saveSelectedItemsAsync(), deleteSelectedItemsAsync()]).then(axios.spread(function (save, delete) { console.log("done"); }));
```

All I'm doing is copying and pasting this code from the docs on the code page of this GitHub. What's weird is that this tells the rest of the code that there's something missing. If I delete the `save, delete` words from within the `axio.spread(function(save, delete)` then everything fixes and throws no syntax errors. So the below code works without those two keywords. Am I doing something wrong? Thanks in advance.

```
axios.all([saveSelectedItemsAsync(), deleteSelectedItemsAsync()]).then(axios.spread(function () { console.log("done"); }));
```

**Comment by OpenGG** [comment]
The below code throws error: `Uncaught SyntaxError: Unexpected token delete`. Because `delete` is a reserved word in js. This issue is not related to axios.

```js
axios.all([saveSelectedItemsAsync(), deleteSelectedItemsAsync()]).then(axios.spread(function (save, delete) { console.log("done"); }));
```
