### ISSUE TITLE
resolve requests immediately on request interceptor?

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [axios/axios#1666]
#### Summary

I'm using a global request interceptor. I want to be able to decide whether to send the request or to resolve them with a particular data immediately from the interceptor (or maybe else where).

###### Snipet

```js
axios.interceptors.request.use(config => {
  if (shouldNotSend) {
    // I don't want to continue sending this request
    // instead I want to resolve this immediately
    return Promise.resolve(data);
  }

  return {
    ...config,
    headers: {
      ...config.headers,
      customHeader: 'custom header value'
    }
  };
});
```

#### Context

- axios version: **0.18.0**
- Environment: **node v10.5.0, chrome 67.0.3396.99, MacOS High Sierra 10.13.5**

**Comment by skbolton** [comment]
This is a rough draft idea (I haven't tried this, also maybe others would have better ideas). You could add a cancellation token to the request config and then immediately cancel it? This means that whoever called it would throw and they could inspect to see if it was cancelled?

https://www.npmjs.com/package/axios#cancellation

**Comment by sprlwrksAprilmintacpineda** [comment]
@skbolton I don't want the caller to throw, I actually want them to be somehow **unaware** of what happened, as if it was a normal call that proceeded normally except it wasn't sent, I want to do this to have a customized caching feature on the app that we are working on.

**Comment by skbolton** [comment]
Gotcha. Well others might come up with something for you. I would say in your case maybe putting a cache layer before the axios call that either resolved with the cached value or calls axios api is best

**Comment by sprlwrksAprilmintacpineda** [comment]
@skbolton Yeah that's what I did for now. Though I'm hoping for a more axios related feature so I don't have to call a custom function I just need to call `axios[method]` anywhere I want. That'll be better..

**Comment by sprlwrksAprilmintacpineda** [comment]
@OpenGG thanks for the tip! I'll try to see if I can make one and maybe publish it to npm for future uses and others who might need similar requirement.

**Comment by nicolasflorth** [comment]
@sprlwrksAprilmintacpineda How did you solved your problem? I am in the same position and I can't find anything that can help. Can you post your solution please?

**Comment by msssk** [comment]
@nicolasflorth the public `adapter` API is working well enough for me. Based on the [docs](https://github.com/axios/axios/blob/master/lib/adapters/README.md) it looks like response transformers and interceptors will be skipped if you don't use the `settle` function, but if you don't need them you can simply pass a function as the `adapter` property on your axios config:

```javascript
function myAdapter (config) {
    // here you can check config.url or anything else
    return Promise.resolve({
        data: someMockDataObject,
        status: 200,
        statusText: 'OK',
        headers: {},
        config: config,
        request: {},
    });
}
```

**Comment by zaklampert** [comment]
I want to conditionally either return custom data (from a redis cache) or perform the request. Do I do this with an interceptor or an adapter?

**Comment by Feaman** [comment]
I made it with adapter. If there is some redis cache - api get cached data, otherwise starts real request.
```js
const self = this
const defaultAdapter = axios.defaults.adapter
axios.defaults.adapter = function (config) {
  return new Promise((resolve, reject) => {
    function fetch () {
      const axiosWithoutAdapter = axios.create(Object.assign(config, { adapter: defaultAdapter }))
      axiosWithoutAdapter.request(config)
        .then(response => {
          resolve(response)
        })
        .catch(error => reject(error))
    }
​
    return self.$apiCache.get(config.url + JSON.stringify(config.params))
      .then(data => {
        if (data) {
          return Promise.resolve({
            data,
            status: 200,
            statusText: 'OK',
            headers: {},
            config: config,
            request: {}
          })
        } else {
          return fetch()
        }
      })
      .catch(fetch)
  })
}

**Comment by chinesedfan** [comment]
Happy to see that you guys solved the problem.

**Comment by wk-cof** [comment]
> I made it with adapter. If there is some redis cache - api get cached data, otherwise starts real request.
> 
> ```js
> const self = this
> const defaultAdapter = axios.defaults.adapter
> axios.defaults.adapter = function (config) {
>   return new Promise((resolve, reject) => {
>     function fetch () {
>       const axiosWithoutAdapter = axios.create(Object.assign(config, { adapter: defaultAdapter }))
>       axiosWithoutAdapter.request(config)
>         .then(response => {
>           resolve(response)
>         })
>         .catch(error => reject(error))
>     }
> ​
>     return self.$apiCache.get(config.url + JSON.stringify(config.params))
>       .then(data => {
>         if (data) {
>           return Promise.resolve({
>             data,
>             status: 200,
>             statusText: 'OK',
>             headers: {},
>             config: config,
>             request: {}
>           })
>         } else {
>           return fetch()
>         }
>       })
>       .catch(fetch)
>   })
> }
> ```

This worked great with one small change. Instead of `return Promise.resolve({` you just need to `resolve({` since you actually need to resolve the promise you are returning. Thanks for the solution!

**Comment by AidanDai** [comment]
```javascript
axios.interceptors.request.use((config) => {
  if (shouldNotSend) {
    // I don't want to continue sending this request
    // instead I want to resolve this immediately
    config.adapter = function (config) {
      return new Promise((resolve, reject) => {
        const res = {
          data: 'custom data',
          status: 200,
          statusText: "OK",
          headers: { "content-type": "text/plain; charset=utf-8" },
          config,
          request: {}
        };

        return resolve(res);
      });
    }
  }

  return {
    ...config,
    headers: {
      ...config.headers,
      customHeader: 'custom header value'
    }
  };
});
```

@sprlwrksAprilmintacpineda @nickuraltsev @Feaman @chinesedfan @wk-cof 

this is onther method solved the problem
