### ISSUE TITLE
GET Request working on POSTMAN and native iOS, but not in React Native+Axios

### ISSUE THREAD

**Issue by jevonch** [axios/axios#1670]
Anyone please help me with this issue. I've already spent 2 days for researching this. I hope I can find the best solution here. I can do POST request in postman, and then I move to GET Request. When I do this Get Request on Postman, everything is working.

GET
URL : 
Headers : 
Content-Type:application/json
authorization:Bearer BuknCYeMkZnPdnvaM7KNRUCb2axWCzpWLDePf8CK_kFMNK28nd6PP776ee96U5ysaSTzQRwZ2sVoFS1VIlH1NM2kTYN0Ai5ZUMB7uKIYAzWXzVE7vvy-JN-72ixAhnEBllDq5pUEtEWjbVayFPRmYwzuvPlyEtV-2oVZ-wN3eJrH_mPZlniUizyBwjS0_Ie5eIrtmRhqQM58DHnd3Xfjp7slapk-k1EWj5Q4CauirDYBER1w1ubxKzykCJmwAyiHXxD_tPPiPut_P7KayiHmMnh9LTIWAtEfqFEeguS2V-qo6-du1ErD90NJWyhyurozZY97I2OOYjzkFUTaflf29RQuIrXFFEsTObyEITaMLv-XVqDt9oa-TVcnO1EGSIzFavxrF6QZ6b9PrpkNWNtPENJvT-62zoM2T-LsZ7dVgq9m7q-0H7KCKIyTk_rKPUJ1kR3_06GNva8FfePVbPg2x71bcGoF0GucZXfllxZnuk6V4v5mJCIRTrZPwuBF8psRz1Dv6wTNRicBVAViBpCyT4k3StuErEvcUjUR1WXmUw1aDYSB0Ock1xgLUe85H2f6
ID:f1ef0392-e545-4f57-a1e2-bd8ceb1f3a60

Everything is going well.

But when i move to react native and axios with this code, it gives the best result. Like there is no header in the request. Here is the code 👍 

axios.get('URLk',
              {
                headers: {
                 'Content-Type': 'application/json',
                 'Authorization':accessToken,
                 'ID':res
                }
              }).then((response) => {
              this.props.endRequesting();
              if (response.data.Code==='Ok00001') {
                console.log(response.data)
              }
            }).catch(error => {
              this.props.endRequesting();
              if (!error.response) {
                console.log('A',error.message)
                alert(error.message)
              }
              else {
                console.log('B',error.response.data.Message)
                alert(error.response.data.Message)
              }
            })
          })

#### Summary
The result always gives me bad authorization. Any solution and input is important for me. 
Thanks

#### Context

- axios: ^0.18.0
- react-native: ^0.56.0

**Comment by delirius325** [comment]
Hey there,

Might sound stupid, but are you sure your accessToken doesn't have any undesired characters? White spaces?

Thanks,

**Comment by darekg11** [comment]
I am having the same issue, happening only on IOS (on Android everything is working fine)
`POST` with headers is working
`GET` with headers behaves like headers were not passed

I can confirm that by wireshark, in case of GET request no headers are added.
React-Native version: 0.55.2
Axios: 0.18

Intresting notes below:  
As soon as I launch `React Native debugger` -  a 3rd party tool for debugging React Native Apps, result is still the same but as soon as I switch on `Network Inspector` headers are added correctly.
Here is the link to the `React Native debugger` -> https://github.com/jhen0409/react-native-debugger/blob/master/docs/network-inspect-of-chrome-devtools.md

**Comment by cmendes0101** [comment]
I'm having the same issue. With RN 0.56.0 and axios 0.18.

Android works as expected then for iOS I have it switching to use Fetch for now.

**Comment by jevonch** [comment]
Hello guys, already solve this.
just set with this way :
**axios.defaults.headers.get['ID']=res;**
it will solve the problem

dont use 
headers: {
'Content-Type': 'application/json',
'Authorization':accessToken,
'ID':res
}
will give different result

**Comment by darekg11** [comment]
Just as follow up - what did not work for us was setting Header "Authorization". As soon as we changed header to be named for example: "X-Authorization", it started to work so we just changed the backend implementation but I guess it is rather workaround than a solution.

**Comment by Sphinxs** [comment]
In my back-end I have allowed the support for credentials and in the Axios request I'm setting the `cross doamin` and `with credentials` to true and it worked. [Reference](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials).

**Comment by lucasluca** [comment]
I changed axios to fetch, and it resolved the issue

**Comment by luatnd** [comment]
> I'm having the same issue. With RN 0.56.0 and axios 0.18.
> 
> Android works as expected then for iOS I have it switching to use Fetch for now.

Hi, did you found the solution, I'm facing it too

**Comment by schumannd** [comment]
Experiencing this issue right now. Get requests through fetch work. post request through axios don't. Only on react native android release builds

**Comment by arifraven** [comment]
In my case post was working and get was not. issue was due to insecure http urls that I used for development. Ended up using ngrok to convert local urls to https and it seems to be working fine.
