### ISSUE TITLE
Delete header 'content-type'

### ISSUE THREAD

**Issue by ihd2911** [axios/axios#1672]
I am trying to remove content-type header from the post request
```
const config = {
                transformRequest: [function (data, headers) {
                    // Do whatever you want to transform the data
                    console.log(headers);
                    delete headers.post['content-Type'];
                    delete headers.get['content-Type'];
                     delete headers.common['content-Type'];
                     console.log(headers);

                    return data;
                }],
            };
            const request1 = axiosObject.post(urlAPI + 'delete/post', post,config);
             request1.then((res)=>{
                console.log(res)
             })`
```

But this is not working.
It sets 'application/json' as default header, when i do this.

If i set header as 
`const config = { headers: { 'Content-Type': ''} };`

it sets header to text/plain.

**Comment by ihd2911** [comment]
When i console log headers, there is no content-type in it,
but when i see request headers, Content-Type: text/plain;charset=UTF-8 is present

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.

**Comment by FreeSoftwareServers** [comment]
Is 24 Down votes enough to re-open? I'm looking to do exactly as OP Title, Delete header 'content-type'

**Comment by DigitalBrainJS** [comment]
@FreeSoftwareServers just set it to `false`

**Comment by FreeSoftwareServers** [comment]
@DigitalBrainJS Setting to `false` did NOT `remove` the header.

**Comment by DigitalBrainJS** [comment]
@FreeSoftwareServers  https://codesandbox.io/p/sandbox/kind-banach-382dwl

**Comment by FreeSoftwareServers** [comment]
@DigitalBrainJS  Appreciate the feedback, I'm working on upgrading my Axios to see if that resolves, but running into problems on that front now.. https://github.com/axios/axios/issues/5765
