### ISSUE TITLE
overlapping recurring requests

### ISSUE THREAD

**Issue by VCodepp** [axios/axios#1675]
how can i avoid repeated requests. some times I send a request again before a request is completed. To prevent this, I need to cancel the ongoing request and start again.

```
// this async function
const list = await axios.post( url , data )
commit('DATA', list.data);
```

here is the first request. it takes a little longer (4-5 seconds)
I call the same request again without the request being answered. the new request is answered shortly (less than 1 second) and my list is displayed as desired.
but when the first request is answered after 4-5 seconds the list view is distorted.

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
