### ISSUE TITLE
My take for a 401/token refresh interceptor

### ISSUE THREAD

**Issue by bragma** [axios/axios#1676]
Hi,
pardon me if this is not the proper place, please redirect me to a better one if needed. After seeing many suggestions for handling 401 and automatic refresh of tokens with interceptors, I've decided to share my take on it. Differently from other implementations which handle only 1 401 at a time and request multiple tokens if 401s happen concurrently, this implementation should just make 1 refresh request and resume pending (failed) requests, using a shared promise. This makes the code very simple and straightforward.
Since I am a JavaScript newbie, I may be missing something obvious so thanks for all suggestions.

https://gist.github.com/bragma/f68391596de71e1bfae066be80c259dc

Thanks!

**Comment by bennnjamin** [comment]
Thanks I had this exact issue with concurrent 401s and I was able to use your solution to fix it

**Comment by fed135** [comment]
Hi @bragma Thank you for the suggestion and the elegant interceptor.
Unfortunately, this is somewhat out of scope for this library.

Feel free to publish this as a standalone plugin, I would star it for sure :)
