### ISSUE TITLE
How to request with socks5? 

### ISSUE THREAD

**Issue by VinceXie** [axios/axios#1677]
i used "[request](https://github.com/request/request)" before and want change to axios. i need to request with socks5 , and there is a project https://github.com/mattcg/socks5-http-client  can do that before.

i try many ways but not work to with socks5 in axios.

please help.

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

Please open a new issue, instead of editing the current one.
