### ISSUE TITLE
Add Proxy support

### ISSUE THREAD

**Issue by Imbuedhush** [axios/axios#1679]
Hello! Is it possible to add support of socks5, socks4, http and https proxies?
something like this:
```
axios({
	method: 'GET',
	url: 'https://google.com',
	proxyurl: 'socks://196.146.157.1:1486',
})
```
or
```
axios({
	method: 'GET',
	url: 'https://google.com',
	proxytype: 'socks5',
	proxy: '196.146.157.1:1486'
})
```

**Comment by gyanrenovite** [comment]
Hi, 

Could you Please help me what changes you have did.

Thanks

**Comment by En0rmous** [comment]
Maybe it`s not in related, but when I use axios proxy to send a request in corporate network, i got an error like this...
![photo_2019-11-11_12-46-35](https://user-images.githubusercontent.com/30603870/68585075-3ccc9c00-0492-11ea-8a38-097374aab093.jpg)

The code that i  used:
```         
response = await axios.post(
              url,
              body,
              {
                headers,
                proxy: {
                  host,
                  port
                }
              }
            )

```
After several hours i have made a decision to make a unirest request and it worked like i expected
```
            const {body, status} = await unirest
              .post(url)
              .headers({
                'Content-Type': 'application/x-www-form-urlencoded;'
              })
              .proxy(`http://${host}:${port}}`)
              .send(body)
            response = body
```

**Comment by dumasss163** [comment]
there is a solution at issure #2072 

```
const HttpsProxyAgent = require('https-proxy-agent');

const const axiosDefaultConfig = {
    baseURL: 'https://jsonplaceholder.typicode.com/posts',
    proxy: false,
    httpsAgent: new HttpsProxyAgent('http://142.93.165.82:8080')
};

const axios = require ('axios').create(axiosDefaultConfig);
axios.get('42')
    .then(function (response) {
        console.log('Response with axios was ok: ' + response.status);
    })
    .catch(function (error) {
        console.log(error);
    });
```

**Comment by jasonsaayman** [comment]
Closing please see #1815 2072

**Comment by victorlcs** [comment]
> there is a solution at issure #2072
> 
> ```
> const HttpsProxyAgent = require('https-proxy-agent');
> 
> const const axiosDefaultConfig = {
>     baseURL: 'https://jsonplaceholder.typicode.com/posts',
>     proxy: false,
>     httpsAgent: new HttpsProxyAgent('http://142.93.165.82:8080')
> };
> 
> const axios = require ('axios').create(axiosDefaultConfig);
> axios.get('42')
>     .then(function (response) {
>         console.log('Response with axios was ok: ' + response.status);
>     })
>     .catch(function (error) {
>         console.log(error);
>     });
> ```

Spend many hours on this problem, and this solution works for me with NestJs.
