### ISSUE TITLE
OPTIONS request is responding with a 307 for non .com url

### ISSUE THREAD

**Issue by andrewrutter** [axios/axios#1682]
#### Summary
I am attempting to connect to some services which are on a domain with a .app extension. When my app attempts to POST the pre flight request in Chrome is failing with a 307.  I have checked and this seems to be happening from within the web app code.

Two test cases were performed:
In /etc/hosts on a developer machine we map api.somehost.app to 127.0.0.1. React app is configured to use that domain for API calls and we issue a POST. Request fails on OPTIONS with a 307

In /etc/hosts on a developer machine we map api.somehost.com to 127.0.0.1. React app is configured to use that domain for API calls and we issue a POST. Request is processed correctly

#### Context

"axios": "^0.18.0"
Environment: Chrome 67.0.3396.99, OSX Sierra

**Comment by OpenGG** [comment]
Pre-flight request is part of CORS spec.

To make the url requested CORS-ready, please configure the target server to handle OPTIONS request properly.

For more information about CORS, please refer to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
