### ISSUE TITLE
Generation client from swagger-api

### ISSUE THREAD

**Issue by mystdeim** [axios/axios#1683]
Does client generator from swagger-api exist?
I found some npm packages but they look outdated and don't support 3.0 spec.
In my point of view it's a good idea to have auto-generated client from spec, especially for facilitate integration with backend, what do think?

**Comment by RikkiGibson** [comment]
https://github.com/azure/autorest.typescript uses axios under the hood when running in nodejs and adapts XMLHttpRequest directly when built for the browser to minimize the size. However AutoRest is limited to Swagger 2.0 as far as I know.

I think swagger-codegen works with Swagger 3.0 and they have an isomorphic `typescript-fetch` generator. Maybe that would work for you?

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
