### ISSUE TITLE
making request just with url domain and not to all path

### ISSUE THREAD

**Issue by OriAmir** [axios/axios#1684]
Hi , I using react-create-app with reacr-touter.
I have a problem with baseUrl in axios.

When i make request from the main page when the path is http://localhost:3000/ so the request is correct. For example, sample request to '/api/getUser' is translated to : http://localhost:3000/api/getUser

The problem is  with another pages, for example if i found in this page http://localhost:3000/testPage/main
and done from there a sample requst so the same endpoint('/api/getUser') then the call going to
http://localhost:3000/testPage/main/api/getUser

When I add BaseUrl:localhost:3000 to axios configuration everything works well , but i don't want it because I care also to production environment.

what can i do about that?
thanks

**Comment by delirius325** [comment]
Hey there,

I'm not sure I understand the part where you don't want to use the BaseURL. Couldn't you have some sort of config file (say "config.js") which, depending on the environment, sets an environment variable with the base URL?

Let's say, something like this:

```javascript
// config.js
if(env === 'development') {
    process.env.BASE_URL = 'localhost-dev:3000';
} else if (env === 'test') {
    process.env.BASE_URL = 'localhost-test:3000';
} else {
    process.env.BASE_URL = 'prod-environment:8080'
}
// add other conditions if needed...

// -----------------------------------------

// app.js
const axios = require('axios');
require('config.js');

let axiosInstance = axios.create({
  baseURL: process.env.BASE_URL
});

axiosInstance.get('/api/getUser')
  // your promises code
```

This is a very basic example and it's not pretty, but it could work.
Let me know what you think 😄 

Thanks,

**Comment by OriAmir** [comment]
@delirius325  **thanks** for the example , i understand the idea..
I try to understand how I add my own enviroments variables to the webpack files
what is exactly 'base_url' because when I console him I see it's empty..

thanks again .

**Comment by delirius325** [comment]
Hi @OriAmir,

Indeed the "BASE_URL" variable is an environment variable that I set myself, that's why when you try to print it to the console it shows as empty. As for initializing other variables depending on the environment, you can simply reproduce the same steps and add your own environment variables in the "config.js" file.

Let me know if that helped you,
Cheers!

**Comment by delirius325** [comment]
Hi again @OriAmir,

Were you able to fix your problem? 😄
If so, could you please close this issue? Otherwise, let me know if my previous comment helped you figure out some stuff.

Thanks,

**Comment by OriAmir** [comment]
@delirius325 thanks for your great help , but I still not understand how to add environment , I use creact-react-app last alpha version and I understand that I can add environment files just in some special way:https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables

but it's not work for me ):

**Comment by delirius325** [comment]
Basically, all you have to do is like I described in my code above. The fact that you're working with React or not shouldn't change your ability to import custom JS files to your React components.

1. Create a file named "config.js"
2. Add the code that will conditionally change your custom environment variable
3. Import that file in your React component and use ```process.env.YOUR_VARIABLE``` to access your variable 😄 

Thanks,

**Comment by delirius325** [comment]
Very true, if your API is hosted on the same machine as your React app then @OpenGG's solution should work perfectly fine 😄

**Comment by OpenGG** [comment]
@OriAmir 

`axios.get('/api/test')` should be resolved to `${location.host}/api/test`, no matter what current page's path is.

This is what all browsers do. I don't see why this doesn't work.

Could you put up an online demo?

**Comment by ajbraus** [comment]
+1

**Comment by OriAmir** [comment]
@OpenGG @delirius325 I back again to this problem..looks what happened , I create  a request when I am on this page: http://localhost:3000/admin/main/recentImages
![screen shot 2018-12-23 at 20 27 43](https://user-images.githubusercontent.com/17565646/50386549-83d26700-06f1-11e9-8832-bfd931f7f798.png)
This is the watch about window.location obj:
![screen shot 2018-12-23 at 20 28 05](https://user-images.githubusercontent.com/17565646/50386552-8f259280-06f1-11e9-8c68-d727a0d68d3b.png)

Then,in network you can see request send to all path and not just to host..
![screen shot 2018-12-23 at 20 28 44](https://user-images.githubusercontent.com/17565646/50386553-9d73ae80-06f1-11e9-9377-1ea53d7fb44b.png)


It's really wired.

**Comment by OpenGG** [comment]
@OriAmir 
Just as expected.

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#Absolute_URLs_vs_relative_URLs

Again, this is not an issue of Axios.

**Comment by OriAmir** [comment]
@OpenGG To what the issue is? can you help me to figure out how to fix that?
tnx!

**Comment by OpenGG** [comment]
@OriAmir See the section about relative url in the given url.

**Comment by OriAmir** [comment]
@OpenGG 
"If the path part of the URL starts with the "/" character, the browser will fetch that resource from the top root of the server, without reference to the context given by the current document."

If I understand right on my example 'pathname' start with '/' so it needs to be ok

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
