### ISSUE TITLE
Server responds with 200 but axios is getting Network error (in specific cases)

### ISSUE THREAD

**Issue by rom1k** [axios/axios#1685]
#### Summary

We have one POST request for uploading a file and one PUT request for pausing the upload. The PUT request should trigger a 200 response from the POST upload request with data { paused: true } and it works for small files < ~12mb but with larger files above 15 mb or so it triggers a network error for some reason. In other words, the server responds with 200 in all cases and with curl there's no problem but axios receives network error with larger files. Below are example scenarios of this problem.

&#x1F535; Scenario 1 (WORKS, file uploaded successfully)
1. POST 10mb file --> OK

&#x1F535; Scenario 2 (WORKS, file uploaded successfully)
1. POST 50mb file --> OK

&#x1F535; Scenario 3 (WORKS, upload paused successfully)
1. POST 10mb file --> _upload in progress_
2. PUT pause --> OK
3. POST 10mb file --> OK _{ paused: true }_

&#x1F534; Scenario 4 (ERROR)
1. POST 50mb file --> _upload in progress_
2. PUT pause --> OK
3. POST 50mb file --> **Network error** 

As you can see, the only difference in scenario 3 and 4 is the file size.
Any idea what can cause the error in scenario 4 and why it doesn't happen with smaller files?

#### Context

- axios version: *v0.18.0*
- Environment: *node v10.0.0, chrome 67, Ubuntu 18.04*

**Comment by OpenGG** [comment]
Is it possible you can make a minimal demo project on Github, including the web files and the HTTP server?

**Comment by fed135** [comment]
Hey, thanks for submitting this issue. Since it has been inactive for a while and that our resources for maintaining and triaging are limited, we will be closing this ticket. If the issue persists on your end, please feel free to open a new issue.
