### ISSUE TITLE
TypeError: Cannot read property 'fd' of undefined

### ISSUE THREAD

**Issue by LalitKushwah** [axios/axios#1692]
Here is my code:

```
import { Component, Prop } from '@stencil/core';
import  'dxp-core';
import axios from 'axios';

@Component({
  tag: 'my-new-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {

  @Prop() first: string;
  @Prop() last: string;
  response:any=[];

  constructor() {

  }

  render() {
    return (
      <div>
        <h1>Root Component</h1>
      </div>
    );
  }

  componentWillLoad() {
    console.log('Component will load works');
    axios.get('https://jsonplaceholder.typicode.com/users').then((response) => {
       this.response = response;
      console.log(response);
    });

  }
}

```
Here is the log messages of the error 
TypeError: Cannot read property 'fd' of undefined
    at Function.useColors (my-new-component.js:9136)
    at createDebug (my-new-component.js:8585)
    at my-new-component.js:9279 "http://localhost:3333/build/mycomponent/my-new-component.js

**Comment by chrisbraddock** [comment]
Try adding this to your `stencil.config.js`:

    nodeResolve: {
      browser: true
    },

**Comment by shallurohilla** [comment]
Added this to config file. Axios call is working now.

**Comment by shallurohilla** [comment]
Added this attribute to stencil.config.js. Axios call is working now.

**Comment by LalitKushwah** [comment]
Thanks @chrisbraddock It worked, 
Can you please explain the mechanism behind this code ? I haven't found such config in stencil official doc.

**Comment by chrisbraddock** [comment]
@LalitKushwah I don't see it in the docs either. See this [PR](https://github.com/ionic-team/stencil/pull/760).

**Comment by emilyemorehouse** [comment]
Looks like y'all figured this out! Closing.
