### ISSUE TITLE
Axios not working in IE11 even after using ES6-promise.

### ISSUE THREAD

**Issue by akankshagore** [axios/axios#1694]
Have included ES6-Promise, as mentioned.
require('es6-promise').polyfill();
But still not working. After request hit, receive response successfully, but nothing shown on UI. After debugging, found response contains 'undefined' inspite of success json. Unable figure out why.

**Comment by RikkiGibson** [comment]
Can you share a page or script which reproduces the problem?

**Comment by 105th** [comment]
Same problem

Code example
```javascript
'use strict'

import Axios from 'axios'
import { parseResponse, handleError } from '@/utils.js'

export default {
  fetchCountries () {
    return new Promise((resolve, reject) => {
      Axios.get('/1.0/countries')
        .then(response => {
             // Here response is already undefined
             resolve(parseResponse(response).data)
        })
        .catch(err => reject(handleError(err)))
    })
  }
}

```

**Comment by akankshagore** [comment]
Whats the solution? Why we receive proper response in other browser and not in IE anything specific? or missed out something??

**Comment by 105th** [comment]
@akankshagore in our case, we remove Promise-wrapper, because Axios already return promise. I didn't know why only this method didn`t work (only for build-version, and only for IE11)

Correct code:
```javascript
'use strict'

import Axios from 'axios'
import { parseResponse, handleError } from '@/utils.js'

export default {
  fetchCountries () {
    return Axios.get('/1.0/countries')
        .then(response => {
             return parseResponse(response).data
        })
        .catch(err => {
             return handleError(err)
         })
  }
}
```

**Comment by hyperking** [comment]
I have ran into the same issue today. I discovered a fix by simply adding the es6 poly-fill for promises

https://www.npmjs.com/package/promise-polyfill

**Comment by akankshagore** [comment]
Still issues is not solve. Unable to view UI elements.

**Comment by OpenGG** [comment]
Not reproduced. Please provide an online demo.

**Comment by frankbolviken** [comment]
Having the same issue. Alot of people are having this issue.
In my case, using react, redux, redux-thunk, axios and this approach:
`
export const fetchSomething = () => {
  return async dispatch => {
    dispatch(actions.fetchRequest());

    try {
      const something = await api.fetchSomething();
      return dispatch(actions.fetchSuccess({ something }));
    } catch (error) {
      return dispatch(actions.fetchError());
    }
  };
};

export const fetchSomething = () => {
  return client.get(`/v1/url`).then(response => response.data);
}
`

I get a infinite refresh loop in IE11 and IE11 only.
Seems like the instant it does client.get the browser reloads and the page re-renders, making it difficult to debug.

**Comment by OpenGG** [comment]
@frankbolviken Can't locate the problem if no working online demo is provided.

**Comment by santeriv** [comment]
I've noticed while using babel/polyfill you need to have some presets (and not just as dev-dependencies, polyfill).

**Comment by dawncold** [comment]
After added this promise polyfill, my axios works fine in IE11

https://github.com/taylorhakes/promise-polyfill

**Comment by florianmartens** [comment]
Hey guys - so here is just a quick tip which could help some folks:

Sometimes it can seem like the promise-polyfill is not working. This is because IE11 defaults to **cache some of the HTTP Requests**. Lets say you make a post request posting a new blog entry and then a get request to fetch this entry. IE11 (unlike all other browsers) will default to cache the get request. Don't forget to disable caching on the client side by setting headers on your request.

```
const headers = {
    "Accept": "*/*",
    "Content-Type": "application/json",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
}
```

This is not 100% related to this topic, but I think this will be the solution for some people finding this topic (it was for me).

**Comment by codingc1** [comment]
I solved it your way when there was a IE11 DOM7011 error.

**Comment by chinesedfan** [comment]
Closed due to lack of enough information that proves it is an issue of axios. If someone still met problems with IE11, feel free to open a new issue following the issue template.

**Comment by SandunHarshana** [comment]
> After added this promise polyfill, my axios works fine in IE11
> 
> https://github.com/taylorhakes/promise-polyfill

This is the answeer
