### ISSUE TITLE
XHR adapter `ontimeout` does not work for cases when the request does not even get through to the server

### ISSUE THREAD

**Issue by tjjjwxzq** [axios/axios#1695]
#### Summary
Axios uses the xhr adapter on the browser or React Native, and handles timeouts by setting the `ontimeout` property of the xhr object. However this property does not seem to be called if the request does not even manage to hit the server (eg. server is down), which has the effect of the timeout property seeming to be ignored. To me this seems to be strange semantics, and is inconsistent with the behaviour of the http adapter which just does a `setTimeout` call for setting the timeout.

Is this intentional, or should the xhr adapter be handling timeouts similar to the http adapter?

#### Context

- axios version: *e.g.: v0.16.2*
- Environment: *e.g.: react-native 0.55.4*

**Comment by OpenGG** [comment]
Tested on Chrome, timeout works like charms.

https://codepen.io/OpenGG/pen/wxEbPe

If the xhr implementation in React Native is not compatible with [the xhr spec](https://xhr.spec.whatwg.org/#the-timeout-attribute), maybe an issue can be filed on RN's repo, instead of axios?

**Comment by tjjjwxzq** [comment]
Not sure, when I try out the code pens with different urls that result in a connection refused (eg. localhost, or a non-existent domain name) the `ontimeout` callback does not seem to be fired. Related: https://github.com/facebook/react-native/issues/11666 (it's marked as resolved, but the solution is hardly satisfactory. Still not clear whether it's an RN-level issue or an axios issue)

**Comment by OpenGG** [comment]
I made a small demo with plain XHR.

RN: https://snack.expo.io/H1OheCGIX
web: https://codepen.io/OpenGG/pen/OweWBe

Tested on:
RN 0.55.4
Chrome 68

Results:
RN on Android:
![RN on Android](https://cdn.pbrd.co/images/HzqrY8H.png "RN on Android")

RN on IOS:
![RN on IOS](https://cdn.pbrd.co/images/HzqtnWNq.png "RN on IOS")

Chrome:
```
Thu Aug 16 2018 18:23:17 GMT+0800 (China Standard Time): start: https://255.255.0.0
Thu Aug 16 2018 18:23:18 GMT+0800 (China Standard Time): onreadystatechange 4,1000
Thu Aug 16 2018 18:23:18 GMT+0800 (China Standard Time): ontimeout 4,1001
```

RN on IOS behaves just like chrome, while RN on Android does not.

**Comment by Marcholio** [comment]
> Anyway this is not an issue of Axios, please check again.

So should this be closed then?
