### ISSUE TITLE
URLSearchParams not working on nodejs (because of check?)

### ISSUE THREAD

**Issue by ayushkamadji** [axios/axios#1699]
https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/lib/utils.js#L154-L156

I was trying to use URLSearchParams for proxying requests on a server using nodejs express. I think the check above causes it to not work as `URLSearchParams` must be imported via `url` module i.e. `require('url').URLSearchParams` in nodejs. 

It should either be fixed or the README should be updated to mention this because it did not categorize URLSearchParams as browser only.

https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/README.md#L261-L271

I'll post an example package to reproduce this later on.

**Comment by ayushkamadji** [comment]
> 
> 
> It looks like the documentation does now say that it's browser-only (since it is explicitly mentioned as a browser option, but not a Node option).
> 
> The question is... is there a reason that we can't use Node's URLSearchParams? I ran into this and have been scratching my head for a while until I re-read the README...

In that case, this should be closed and using URLSearchParams in node can be followed up as feature request.

**Comment by ryuuji3** [comment]
I just wanted to comment that I have a work-around, which is not perfect.
You can simply just pass the URL.toString() as the axios request URL. Or concatenate the URL with URLSearchParams.toString(). 

I didn't see a feature request so I'll just go ahead and make one then.
