### ISSUE TITLE
Can not post when a number is in the URL

### ISSUE THREAD

**Issue by MaximVanhove** [axios/axios#1704]
#### Summary

I'm trying to post some data to my api, but it just sends a GET request to the base URL instead. I found out that it breaks when adding the api version.

This works:

```
const endpoint = '/api/children';
axios.post(endpoint, data);
```

But this does not:

```
const endpoint = '/api/v1/children';
axios.post(endpoint, data);
```

#### Context

- axios version: v0.18.0
- Environment: node v8.11.3, opera 54, OS X 10.11.5

**Comment by danielreiser** [comment]
Is you api endpoint publicly available?
If so, can you edit this stackblitz https://stackblitz.com/edit/js-93xybc to further investigate your issue?

**Comment by MaximVanhove** [comment]
I'm afraid it's still in development. It's weird though, because once I tried with another library it worked again with axios too. So I switched back to axios and some moments later it just broke again...

**Comment by delirius325** [comment]
Could you create an axios instance from a config variable? And print the instance to the console? I'm curious to see what the config's url looks like.

```
const config = {
  url: endpoint;
}
const instance = axios.create(config);
console.log(instance.defaults.url);
```

Thanks!

**Comment by MaximVanhove** [comment]
This showed up in my console: http://project.test/api/v1/children

**Comment by delirius325** [comment]
When you're testing your API, are you testing it through a front-end or are you directly calling it from a client (like Postman)? If it's from a front-end, the behaviour which you described earlier :

> It's weird though, because once I tried with another library it worked again with axios too. So I switched back to axios and some moments later it just broke again...

Sounds like a browser issue to me. If it is, I'd just either try with another browser or empty the cache on your current one (try incognito mode).

Thanks,
