### ISSUE TITLE
proxy setting not work for me

### ISSUE THREAD

**Issue by tradzero** [axios/axios#1706]
#### Summary

proxy setting not working.
when use proxy setting return same result (server print the ip) with not use proxy setting
but use curl -x work fine.
axios with proxy
![image](https://user-images.githubusercontent.com/13845447/43627543-6ca47362-9729-11e8-8f66-6cfa2be68fb3.png)

axios without proxy
![image](https://user-images.githubusercontent.com/13845447/43627558-7a324914-9729-11e8-9dc8-db29e0ab1922.png)

curl with proxy
![image](https://user-images.githubusercontent.com/13845447/43627605-a02a91f8-9729-11e8-9ff4-fe5f17222c45.png)

curl without proxy
![image](https://user-images.githubusercontent.com/13845447/43627579-8d8eee0e-9729-11e8-9373-93afdca967f4.png)

#### Context

- axios version: *v0.18.0*
- Environment: *chrome68 macos 10.12.6*
setting
```js
        var inst = axios.create({
            proxy: {
                host: '127.0.0.1',
                port: 1087
            }
        });
        inst.get('https://test.xxxx.com/test.php').then(function (res) {
            console.log(res);
        });
```

**Comment by OpenGG** [comment]
Are you using axios in browser or Node.js?

Proxy config only works in Node.js.

https://github.com/axios/axios/blob/master/lib/adapters/http.js#L99

The README needs to be more accurate.

**Comment by tradzero** [comment]
@OpenGG yeap i use in browser.  thanks

**Comment by javakishore** [comment]
// 'proxy' defines the hostname and port of the proxy server
  // Use `false` to disable proxies, ignoring environment variables.
  // `auth` indicates that HTTP Basic auth should be used to connect to the proxy, and
  // supplies credentials.
  // This will set an `Proxy-Authorization` header, overwriting any existing
  // `Proxy-Authorization` custom headers you have set using `headers`.
  proxy: {
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
  }
