### ISSUE TITLE
Question: is there a reason the Typescript types for onUploadProgress / onDownlodProgress pass an `any`?

### ISSUE THREAD

**Issue by ekilah** [axios/axios#1708]
The types of the `AxiosRequestConfig` interface 

https://github.com/axios/axios/blob/98080381fa78dcffa91a15e6d25617583d13e533/index.d.ts#L58-L59

say they pass an `any` to the handler, when in fact they pass `ProgressEvent`s ([docs](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/ProgressEvent)) - or, at least it does when tested in Chrome via my React app.

Is there a reason the types are not accurately described? I'm not sure if this is an oversight, or some complication with the way this library tries not to depend on other libraries, or some other issue.

**Comment by RikkiGibson** [comment]
Since ProgressEvent requires “lib”: [“dom”] to be specified in tsconfig, users who compile against these type definitions but aren’t targeting the web would get build errors.

Typescript 3 added the /// <reference lib=“...” /> directive so maybe this can be updated eventually.

**Comment by ekilah** [comment]
@RikkiGibson ah, ok, so it was in fact more complicated. thanks for getting back.

I'll admit I don't know the intricacies of building a library that works in browsers and Node, and similarly don't know if the TS 3.0 references stuff helps enough. but it'd be great if it does 😛

**Comment by RikkiGibson** [comment]
Other libraries solve this by copying the relevant interfaces of lib.dom.ts into their own libraries to provide some helpful type definitions while still preventing errors for non-web users. I’m not 100% sure whether that approach or the aforementioned reference lib directive is preferred now with typescript 3.

**Comment by chinesedfan** [comment]
Closed by #2851.

**Comment by ArnaudBarre** [comment]
Is it possible to have a patch release for that?
