### ISSUE TITLE
GitHub fails with Axios due to OAuth-Token is no longer in the  Access-Control-Allow-Headers of Github

### ISSUE THREAD

**Issue by tevfik6** [axios/axios#1711]
#### Summary

It seems like GitHub removed the OAuth-Token header from Access-Control-Allow-Headers as a result of it, any api calls simply use Authorizations fails due to common.defaults are adding OAuth-Token header by default. 

Simply;
```js
axios.get('https://api.github.com/user', {
    headers:{
        "Authorization": "token "+this.github_token
    }
});
```

Expected Behaviour: 
The user details return with a valid token

Actual Behaviour:
Browser blocks with the following message:

`Failed to load https://api.github.com/user: Request header field OAuth-Token is not allowed by Access-Control-Allow-Headers in preflight response.`

#### Context
- axios version: v0.18.0
- Environment: node v10.7.0, Version 67.0.3396.99 (Official Build) (64-bit), Mac OS 10.13.6 

#### Workaround (Hack)
Removing the OAuth-Token headers from common with following line;
```js
delete axios.defaults.headers.common["OAuth-Token"];
```

**Comment by OpenGG** [comment]
Axios doesn't do OAuth. Find another lib on npm please: https://www.npmjs.com/search?q=keywords:oauth2

**Comment by tevfik6** [comment]
@OpenGG The code above retrieves the current user information using the Access Token in GitHub. 
There is no OAuth happening here. Thank you for referring me to OAuth libs. If you just get the code above and try you will see that OAuth-Token header is being pushed to Headers. So, Axios appending some headers even though I did not specify. 

For the equivalent, curl can be found here: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#3-use-the-access-token-to-access-the-api

**Comment by tevfik6** [comment]
Issue seems like #1522
