### ISSUE TITLE
Axios only respond to Api with "keep-Alive" Connection and not for "close" Connection 

### ISSUE THREAD

**Issue by TobinFrost** [axios/axios#1713]
When i'm trying to request google for example I do not receive any data but if I send a request to my api with express I receive data.
All help will be welcome.

[This do not respond]

`http.get('https://www.google.com').then(({ data }) => {
        commit(types.SET_SITE, data)
        if (data.locale) {
          commit(types.SET_LOCALE, data.locale)
        }
      }).catch((err) =>{
        commit(types.SET_SITE, err)
      })`

[This is working]

`http.get('site').then(({ data }) => {
        // let real_data = data['status']
        commit(types.SET_SITE, data)
        // commit(types.SET_SITE, real_data)
        if (data.locale) {
          commit(types.SET_LOCALE, data.locale)
        }
      }).catch((err) =>{
        commit(types.SET_SITE, err)
      })`

**Comment by OpenGG** [comment]
The URL requested, "https://www.google.com", is not cors-ready.

Maybe the issue is not about "keep-alive" or "close".

https://codepen.io/OpenGG/pen/ZjMwEr

**Comment by TobinFrost** [comment]
I wanted to integrate an external API running with php, but when I make a GET request to access a resource I do not receive any data, the ..catch () method is executed and the object error is empty.
moreover the API has a method of connection: close.
I also wonder if this is not a proxy problem.

**Comment by OpenGG** [comment]
For more information about Cross Origin ajax, please refer to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by TobinFrost** [comment]
the problem came from the External API, the header did not have "Access-Control-Allow-Credentials", or "Access-Control-Allow-Headers", and "Access-Control-Allow-Origin" either .

I will close the issue
