### ISSUE TITLE
Cancel several requests with same CancelToken

### ISSUE THREAD

**Issue by vtni** [axios/axios#1714]
I have different react modules in a view, while each is calling an API via `axios`. When going to another view, all calls should be cancelled. However, when returning to this view, the calls should be started again (those are in `componentDidMount()`).

File `AxiosCancellation.js`:

    import axios from 'axios';
    let cancel;
    export var cancelRequest = (message) => {
      if (cancel) cancel(message);
    };
    export var setCancelToken = (c) => {
      cancel = c;
    };
    export var CancelToken = axios.CancelToken;

File 2:

    import {CancelToken, setCancelToken} from "AxiosCancellation";
    export var get1: () => {
      return axios.get('/get1', {
        cancelToken: new CancelToken(function executor(c) {
          setCancelToken(c);
        })
      }).then(handleResponse);
    }

File 3:

    import {CancelToken, setCancelToken} from "AxiosCancellation";
    export var get2: () => {
      return axios.get('/get2', {
        cancelToken: new CancelToken(function executor(c) {
          setCancelToken(c);
        })
      }).then(handleResponse);
    }

When I now call `cancelRequest()` when clicking a link on the navbar, only one call is cancelled. How can I cancel multiple calls (that are in different files)?

**Comment by mohammadalipak** [comment]
You are generating a `new CancelToken()` for each request & overwriting the global `cancel` in `AxiosCancellation.js`, so when you call `cancel()` it can only cancel the last request as the older one got overwritten.

To cancel all, you need to create an instance of cancel token & use the same instance in both requests:
```js
// File AxiosCancellation.js:
export var source = CancelToken.source();

// File 2:
return axios.get('/get1', {
  cancelToken: source
})

// File 3:
return axios.get('/get2', {
  cancelToken: source
})

// wherever you wanna cancel all
source.cancel();
```
See docs for details: https://github.com/axios/axios#cancellation

**Comment by IndigoHollow** [comment]
@mohammadalipak , greate responce! Maybe you could solve my related issue?

In my case I have several active POST requests at the same time, situated in different instances of one component. And for every request I have a button which triggers `cancel()` method for each particular request.
The problem is when I click on button, cancels only the last request in the list. Not the one for which I clicked the button. Obviously somehow I overwrite `cancel`, but don't know how to fix it.

**Comment by RichardLindhout** [comment]
For functional components:

```
  const cancelSource = useMemo(() => axios.CancelToken.source(), [])

```
