### ISSUE TITLE
The interceptor did not take effect when I refreshed the page

### ISSUE THREAD

**Issue by gongshun** [axios/axios#1716]
#### Summary
I wrote an interceptor in my Vue project，it works normally when the page is not refreshed.When I refresh the page，the request was sended, but the interceptor did not take effect，but at this time I switch the route, and it works again

#### Context
this is my interceptor ,i used vue-router in my Vue project，
`axios.interceptors.request.use(
    config => {
        console.log(1);
        return config;
    }, 
    error => {
        console.log(2);
        return Promise.reject(error);
    }
);
`
- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v8.7.0, chrome 64, windows 7,vue 2.9.6

**Comment by OpenGG** [comment]
Insert `console.log()` statement before every request and before adding interceptor. Refresh and observe console, see if interceptor is added before any request.

```js
console.log("add interceptor");
axios.interceptors.request.use(...);

console.log(url); // log every request
axios.get(url);
```

**Comment by Pyrolistical** [comment]
I'm running into the same issue, `axios.interceptors.request.use` just doesn't get used

**Comment by john-dev** [comment]
Any news on this?
I experience the same problem

**Comment by ericmdantas** [comment]
The work around I did was to move the interceptor initialization to my entry file, in my case `main.ts`.

```ts
// main.ts

import Vue from 'vue'
import App from './app.vue'
import router from './app.router'
import store from './app.store'
import './auth_interceptor'
import './registerServiceWorker'

Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount('#app')
```

```ts
// auth_interceptors.ts

import axios from 'axios'
import authService from '../services/auth_service'

axios.interceptors.request.use((config) => {
	authService.setHeadersFromStorage(config)
	return config
}, (err) => {
	return Promise.reject(err.response)
})

axios.interceptors.response.use((response) => {
	authService.saveHeadersStorage(response)
	return response
}, (err) => {
	return Promise.reject(err.response)
})
```

**Comment by webtobesocial** [comment]
I am experiencing the same issue. This is my relevant code...

```js
app.$axios.interceptors.request.use(
  function(config) {
    if (config.url.includes('/token/refresh')) {
      const refreshToken = Cookie.get('USER_REFRESH_TOKEN')

      if (refreshToken) {
        config.headers.Authorization = 'Bearer ' + refreshToken
      }
    } else {
      const accessToken = Cookie.get('USER_ACCESS_TOKEN')

      if (accessToken) {
        config.headers.Authorization = 'Bearer ' + accessToken
      }
    }

    console.log('CONFIG:\n\n', config)
    return config
  },
  function(error) {
    console.log('ERROR:\n\n', error)
    return Promise.reject(error)
  }
)
```


**Problem**
I am using NuxtJS with VueJS and when I refresh the page in the browser it does not intercept the request. But when I navigate in the menu with `<nuxt-link>` links it works like a charm. Any idea is appreciated.

**Comment by ericmdantas** [comment]
@webtobesocial when is this piece of code being called? In your entry file or in the creation of your app?

**Comment by webtobesocial** [comment]
@ericmdantas thanks for your reply. This piece of code is located in `/middleware/axios.js` and it's called from the middleware in NuxtJS. Does this answer your question? From my research it seems that the middleware does not register page refreshs so I moved it temporarily to `/plugins/axios.js` which seems to work but feels a tiny bit like a hack.

**Comment by ericmdantas** [comment]
@webtobesocial I'm not familiar with NuxtJS, but what ended up working for my web project was initializing the interceptor in the `main.ts` file instead of `App.vue` file.

**Comment by webtobesocial** [comment]
@ericmdantas thanks for your reply. In my Vue project I also had the axios interceptor in the `main.js` but I had to move the whole project to NuxtJS because of server side rendering and there is no concept of a `main.js`. The migration is quite hard to move the project from pure VusJS app to NuxtJS. Is anyone familiar with NuxtJS probably?

**Comment by gokhancetiner** [comment]
Hello,

Is anybody solve this issue? Axios interceptor doesn't affect when refresh the page

Thanks,

**Comment by ericmdantas** [comment]
Hello, @gokhancetiner. When are you registering the interceptor? In the `main.js` or in the `App.vue`?

**Comment by gokhancetiner** [comment]
Hi,

Thanks for the quick response. I am using Nuxt and I registered interceptors in plugins/axios.js. It is working on client-side requests but requests sent from server-side interceptors seem to doesn't work.

Thanks

**Comment by ericmdantas** [comment]
I'm not familiar with Nuxt, so I can't help much, sorry.

Maybe someone more experienced with it might chime in and help you out.

**Comment by chinesedfan** [comment]
Hi, can someone provide a sample repository link? Glad to clone and check what happens.

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
