### ISSUE TITLE
can i do blocking request on execute after another 

### ISSUE THREAD

**Issue by AliBedaer** [axios/axios#1721]
i want to execute a request and execute another after the first finished here the code i tried to implement 
`
     
      login() {
           let data = {
           client_id: 2,
           client_secret: "QF9ibjifzhM5qDCGnqkHVOTO3YxEHN0X1eQbsj3e",
           grant_type: "password",
           username: this.email,
            password: this.password
        };
      this.$http
        .post("http://localhost:8000/oauth/token", data)
        .then(response => { 
          this.$auth.setToken(
            response.data.access_token,
            response.data.expires_in + Date.now()
          );
        }).then(()=>{
          this.$http.get("http://localhost:8000/api/user").then((user)=>{
              this.$auth.setAuthenticatedUser(user.data);
              this.user = user.data;
              this.image = user.data.image;
              this.$bus.$emit('logged_user',user.data);
            
            return this.$http
              .get("http://localhost:8000/api/tpa/provider/status")
          }).then(tpa_provider => {
              localStorage.setItem("tpa_provider", JSON.stringify(tpa_provider.data));
              if(this.$auth.isAuth()){
                this.$router.push({"name":"home"});
              } 
          })
          this.$bus.$emit('logged_user',this.user);
        })
    }`

this i not working and the second request "http://localhost:8000/api/user" not executing after the first how can i do this

**Comment by pandemm** [comment]
This seems to be in the wrong place, as it doesn't look like you're using Axios.

**Comment by giggo1604** [comment]
@pandemm looks like this is a vue application where axios is exposed as $http on vue components

@AliBedaer i can't see why this shouldn't work, considering you don't get an error from /oauth/token

https://codepen.io/giggo1604/pen/MqgRZp?editors=1111

here is a basic working example

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
