### ISSUE TITLE
baseURL prop gets ignored when doing a post request

### ISSUE THREAD

**Issue by deangibson89** [axios/axios#1724]
#### Summary

When I do the following:

```
const root = "http://localhost:3000";
axios.post("/test", {
  baseURL: root; // Goes to localhost:3001
  headers: {
    Authorization: `Bearer ${token}`,
    "content-type: "application/json"
  },
  params: {
    a: "a",
    b: "b"
  },
  data: {
    c: "c"
  }
});
```
My request goes to `localhost:3001` which is where my front-end is running and of course I get a 404. The above works just fine with `GET` requests and it seems this is only a problem with `POST` requests.

The only way I can get past this issue is when I get rid of the `baseURL` prop and define the full path i.e.

`axios.post("http://localhost:3000/test", { ... })`

#### Context

- axios version: *v0.18.0*
- Environment: *node v8.9.0, chrome 67.0.3396.99, macOS 10.13.6*

**Comment by pandemm** [comment]
The signature for the method is axios.post(url[, data[, config]]). 
You might be confusing it with this syntax of sending a request:
// Send a POST request
axios({
  method: 'post',
  url: '/user/12345',
  data: {
    firstName: 'Fred',
    lastName: 'Flintstone'
  }
});

If you move your data to be the second parameter of the post method, it works as you would expect.

**Comment by fed135** [comment]
Hey, thanks for submitting this issue. Since it has been inactive for a while and that our resources for maintaining and triaging are limited, we will be closing this ticket. If the issue persists on your end, please feel free to open a new issue.
