### ISSUE TITLE
How do I set a custom header on an Axios.create() instance?

### ISSUE THREAD

**Issue by chovy** [axios/axios#1725]
```
  login(creds) {
   return api.post('/accounts/login', creds)
      .then(res => {
        debugger
        api.defaults.headers.common.Authorization = res.data.token;

        return res;
      });
  },
```

THis does not appear to work. api is undefined here in the response handler.

**Comment by OpenGG** [comment]
What is `api`? Please provide a smallest demo to produce the issue, with runtime information, e.g. what browser/os/node version.

**Comment by jkirkpatrick** [comment]
Here's something I copied from my code for a POST; I did not include the error handler / interceptors for generating full url / other stuff.

```
this.authorization = '1234';

  generateHeaders(token) {
    const headers = {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    };
    if (token) headers.Authorization = token;
    return headers;
  }

  post (url, data, contentType) {
    const headers = this.generateHeaders(this.authorization);
    if (headers) console.log(headers);
    const cType = contentType || 'application/json'; // application/json; charset=utf-8
    //console.log('imafirin mah post %s %s', url, JSON.stringify(data));
    return axios({ method: 'POST', url, headers, data }).then(response => {
        const typeHeader = response.headers['content-type'] || '';
        if (typeHeader.startsWith(cType)) { 
          return this.parseJsonAsync(url, response)
            .catch(error => {
              const errmsg = (error && error.message) ? error.message : 'Unknown error occurred: \'' + url + '\'';
              return Promise.reject(errmsg);
          });
        }
        return Promise.reject('Invalid content type: \'' + contentType + '\'');
      }).catch(failure => {
        return this.parseErrorAsync(url, failure);
      });
  } 

```

**Comment by OpenGG** [comment]
@jkirkpatrick 

This is too verbose, and not runnable at all. The issue can be a bug inside your code, or inside axios. One just can't tell.

Can you provide a minimal demo, showing the exact problem related to axios.

For general development problem, please consider asking on stackoverflow.com .

But if it turns out to be a bug of axios, feel free to come back.

**Comment by jkirkpatrick** [comment]
@OpenGG - Not a bug, not intended to be runnable, but intended to show how to use custom headers with  poorly documented software.

**Comment by OpenGG** [comment]
Axios with custom headers actually works: https://codepen.io/OpenGG/pen/BPOvVN
But there is a bug when using custom headers with Axios.create(): https://github.com/axios/axios/issues/1522

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios#axioscreateconfig.

**Comment by chovy** [comment]
i switched to fetch.
