### ISSUE TITLE
Default params serialisation behaviour incompatible with recent Tomcat versions.

### ISSUE THREAD

**Issue by matthewlowry** [axios/axios#1727]
#### Summary

Given the default params serialisation behaviour, axios out-of-the-box may fail to work with recent Tomcat versions out-of-the-box.

The problem is the way params are serialised in the absence of a custom params serialiser configuration. The code is using the built-in `encodeURIComponent` function (good), but then proceeds to deliberately de-encode some characters. In particular, it de-encodes `[` and `]` back to raw (problem).

This is a problem with Tomcat because recent versions (_e.g._ 8.5.31+) have started being more pedantic about URI syntax, and by default will reject requests that contain `[` or `]` in the query portion.

I appreciate the motive of making the URLs built by axios more human readable, and not percent-encoding characters if you can get away with it. But blatant and wilful violation of RFC 3986, even if common practice for historical reasons, is a problem with servers that are adopting strict-by-default behaviour.

#### Context

- axios version: v0.18.0
- Tomcat 8.5.32

**Comment by muzea** [comment]
@madebyherzblut `paramsSerializer` can solve this problem

```js
import axios from "axios";
import qs from "qs";

// GET /user?ID%5B%5D=1&ID%5B%5D=2&ID%5B%5D=3
axios
  .get("/user", {
    params: {
      ID: [1, 2, 3]
    },
    paramsSerializer(params) {
      return qs.stringify(params, { arrayFormat: "brackets" });
    }
  })
  .then(function(response) {
    console.log(response);
  })
  .catch(function(error) {
    console.log(error);
  })
  .then(function() {
    // always executed
  });

```

[qa](https://www.npmjs.com/package/qs) uses the RFC3986 serialization parameter by default, or you can choose to use RFC 1738.

**Comment by sutra** [comment]
Because of these 2 lines:
https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js#L12

**Comment by cambraca** [comment]
Created PR #2563 to fix this and other similar issues.

**Comment by jasonsaayman** [comment]
On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the qs library:
```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

**Comment by tfactor2** [comment]
It's unclear why it shouldn't be a default behavior - why not use standard encoding (RFC3986 / RFC1738 as qa does) as expected without the need for doing workarounds?
The problem is that _one doesn't know in advance_ that Axios is working in such a way that might lead to unexpected bugs.

I am requesting for reopening.
