### ISSUE TITLE
Unable to capture options status code

### ISSUE THREAD

**Issue by xcsweb** [axios/axios#1729]
![](https://user-gold-cdn.xitu.io/2018/8/14/16538ea35f9c0a57?w=715&h=490&f=png&s=35768)
![](https://user-gold-cdn.xitu.io/2018/8/14/16538ee6d92be191?w=527&h=389&f=png&s=39542)
- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v8.11, chrome68, windows 7*

**Comment by OpenGG** [comment]
Options requests are transparent to XHR, there is no way axios can get the response status code, i.e. not a bug.

You can try XMLHttpRequest() and see if that's true.
