### ISSUE TITLE
no redirects history

### ISSUE THREAD

**Issue by wholegroup** [axios/axios#1731]
Current Axios version can't track redirects, because of using `follow-redirects` library (see #834).
Since v1.5.0 `follow-redirects` library supports `trackRedirects` pre-request option that stores the redirected response details into the redirects array on the response object

#### Summary

Please add new option `trackRedirects` to request config.

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: node v10.7.0

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks

**Comment by jasonsaayman** [comment]
Merged #1763
