### ISSUE TITLE
axios.all(), is there any possiblity to get this type when using interceptors?

### ISSUE THREAD

**Issue by Sapphire2k** [axios/axios#1734]
#### Summary

By using global interceptors to toggle Loading status, is there any possibility to get this info ?
Or is there any ways to add loading for official solution?

#### Context

- axios version:  v0.16.2
- Environment: node v9, chrome 68, mac OS 10.13.6

**Comment by OpenGG** [comment]
Could you be more specific? What is "this type" or "this info"?

Axios is http request lib, it doesn't handle loading or anything related to UI, and not supposed to.

**Comment by Sapphire2k** [comment]
@OpenGG I mean, can we get this request is from axios.all in the interceptor? Then we can differentiate it is for one or for more request~
What's, is there any possible we can get request params when we use axios.all ?

**Comment by chinesedfan** [comment]
Sorry, there isn't. But you can remember the request params by local or global variables by yourself.
