### ISSUE TITLE
Failing requests with missing protocol in node env

### ISSUE THREAD

**Issue by giggo1604** [axios/axios#1737]
#### Summary

If you create a request without a protocol in a node environment it fails with an 4000 Bad Request error. It looks like a wrong URL is generated if axios is defaulting to http.

I added this unit test for the node http adapter which I expect to pass.

```js
{
  ...,
  testNoProtocol: function (test) {
    var data = {};

    server = http.createServer(function (req, res) {
      res.setHeader('Content-Type', 'application/json;charset=utf-8');
      res.end(JSON.stringify(data));
    }).listen(4444, function () {
      axios.get('localhost:4444/').then(function (res) {
        test.deepEqual(res.data, data);
        test.done();
      });
    });
  }
}
```
But as mentioned, it leads to an error. I noticed this problem in a project of mine and while further looking into it I noticed that the generated url is `http:the.domain.wihtout.protocol` and misses the `//`. 

I might be able to provide a pull request if I can get some guidance on where to handle this issue if it is one. Event thought this isn't a big issue it was kinda hard to debug this issue as I didn't expect the error to be on axios side.

#### Context

- axios version:  *v0.18.0*
- Environment: *v10.9.0*

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. If you feel that this issue still exists please submit a new issues.

Thanks
