### ISSUE TITLE
Making a post request in Browser Environment

### ISSUE THREAD

**Issue by rvsingh011** [axios/axios#1742]
I am using axios for making a post call in browser environment/ Electron App. The data I want to post is two zip files and one name parameter. The problem is the server is saying that he does not found anything in the request body. 
I am using form data for sending the data. 
I am sending data to watson for training.

The curl command for the same is 

`curl -X POST -u "apikey:{apikey}" -F "beagle_positive_examples=@beagle.zip" -F "goldenretriever_positive_examples=@golden-retriever.zip" -F "husky_positive_examples=@husky.zip" -F "negative_examples=@cats.zip" -F "name=dogs" "https://gateway.watsonplatform.net/visual-recognition/api/v3/classifiers?version=2018-03-19"
`

I am making form data like this. 

```
const formData = new FormData();
    payload.watsonTrainingSet.map((data) => {
    console.log(data);
    const resFile = fs.readFileSync(data.zipPath);
    formData.append(`${data.classLabel}_positive_exmaples`, fs.createReadStream(data.zipPath));
    formData.append(`${data.classLabel}_positive_exmaples`, resFile);
    });
    formData.append('name', payload.classifier);
    for (const key of formData.entries()) {
      console.log(`${key[0]}, ${key[1]}`);
    }
```

```
axios({
      method: 'post',
      url: 'https://gateway.watsonplatform.net/visual-recognition/api/v3/classifiers?version=2018-03-19',
      data: formData,
      headers: { 'content-type': ''multipart/form-data" },
      auth: {
        username: 'apikey',
        password: 'mykey for authentication.',
      },
    }).then((response) => {
      console.log(response);
    })
      .catch((error) => {
        console.log(`Error :: ${JSON.stringify(error)}`);
      });
```

The same request is going by postman as well and I am getting response. The postman screenshots are below
<img width="972" alt="screen shot 2018-08-20 at 3 23 37 pm" src="https://user-images.githubusercontent.com/17317582/44333691-31581400-a48d-11e8-84b0-de53182a269e.png">
<img width="943" alt="screen shot 2018-08-20 at 3 24 08 pm" src="https://user-images.githubusercontent.com/17317582/44333692-31f0aa80-a48d-11e8-9a08-130c4c4e2955.png">

In postman the request is done with 200 but in the electron app it gives  400. 

> Did not find any files to process in the POST request body. "

**Comment by OpenGG** [comment]
Setting `content-type` overwrites the default one provided by browser, making it impossible for server to do the right parsing.

Possibly duplated to https://github.com/axios/axios/issues/318

**Comment by chinesedfan** [comment]
Make sure you are using the expected adapter first. See [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios/blob/master/README.md#do-you-use-the-right-adapter).

And if you want to introduce package `form-data`. See https://github.com/axios/axios/issues/2049#issuecomment-503435918.

Closed due to stale. Please correct me if I misunderstood something.
