### ISSUE TITLE
Axios responseType stream returning undefined data

### ISSUE THREAD

**Issue by ThiagoMiranda** [axios/axios#1743]
Hi...
I'm trying to make this code work but the data keeps returning undefined even though I'm using the responseType: 'stream' even though the request returns a 200 status and a responseText with the image itself.

```javascript
async function getImage() {
    const response = await axios({
        url:'https://www.w3schools.com/css/img_forest.jpg',
        responseType: 'stream'
     })
    response.data.pipe(fs.createWriteStream(imagePath)) // error: response.data undefined 
}
await getImage()
```
Axios version: 0.18

Does anybody have the same issue? Thanks

**Comment by gcox** [comment]
@ThiagoMiranda Are you using jest? If so, that's probably the issue...see this comment: https://github.com/axios/axios/issues/1418#issuecomment-373386206

**Comment by Omkaragrawal** [comment]
Does using fs.createWiteStream() inside response.data.pipe closes the stream automatically when the download gets completed?

**Comment by chinesedfan** [comment]
Closed due to stale and not an issue. Friendly remind that `responseType: stream` works only for http adapter, which means in Node.js usually.

**Comment by jmmadsen** [comment]
@chinesedfan can you expand on your last comment? Is it not possible to stream data from Node.js to the browser for download? If not, how would you recommend downloading a large CSV file sent from a Node API?

**Comment by chinesedfan** [comment]
@jmmadsen If you want to download something, please search with keyword `download` and you will see [lots of issues](https://github.com/axios/axios/issues?q=is%3Aissue+is%3Aopen+download) about how to do that.
