### ISSUE TITLE
How to append custom headers to axios request?

### ISSUE THREAD

**Issue by ksairamya** [axios/axios#1744]
I want to add a custom header x-dsi-restful to a get request. But I'm unable to append it through axios. 
Here is what I did
getAppSettings().localRetailVehicleComparablesUrl
    }/k6MRDHbipIsp4BiKcNm66w/local_retail/comparables`,
    {
      method: 'get',
      withCredentials: true,
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'x-dsi-restful': 1
      }

Even though I added it to Header set Access-Control-Allow-Headers "x-dsi-restful, Authorization"
I'm unable to append it to the request.

Only if I hardcode the value in apache conf the its working. Like
RequestHeader append x-dsi-restful "1"

Is there a way to append it from axios?

**Comment by delirius325** [comment]
Hi @ksairamya,

```javascript
axios.get('url', {headers: "x-dsi-restful":1})
```
is not working?

**Comment by OpenGG** [comment]
Not an Axios issue. Axios itself is capable of making CORS requests with custom headers.

https://codepen.io/OpenGG/pen/VGYgYd

For more information about CORS, please refer to the following document:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by Venkatuidevloper** [comment]
axios.get('url', {headers: "x-dsi-restful":1})

-----It's working fine thank you

**Comment by H4midR** [comment]
`axios.get('url', {headers: "x-custom":1})
`will change the Request Method to OPTION.
my request is : 
`Request URL: http://localhost:9090/poster/verify/queue
Request Method: OPTIONS
Status Code: 404 Not Found
Remote Address: [::1]:9090
Referrer Policy: no-referrer-when-downgrade
Content-Length: 9
Content-Type: text/plain; charset=utf-8
Date: Sun, 17 Mar 2019 16:50:02 GMT
Provisional headers are shown
Access-Control-Request-Headers: x-hamid
Access-Control-Request-Method: GET
Origin: http://localhost:8585
Referer: http://localhost:8585/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36`

**Comment by ludbek** [comment]
Did you guys mean `axios.get('url', {headers: {"x-dsi-restful":1}})`?

**Comment by dmitrif** [comment]
Any variation of a `GET` request with a custom header results in axios sending out an `OPTIONS` request instead.

**Comment by AllainPL** [comment]
Probably by now @ksairamya resolved the issue :>?

**Comment by frontport** [comment]
The first request is an automatic OPTIONS method by the browser. It's mandatory, because CORS circumstances. If the server respons an HTTP 200 OK, your next request may be the normalone you originally wanted.

**Comment by RishithPoloju** [comment]
if you want to do a get request with params and headers.

var params = { 
     paramName1: paramValue1,
     paramName2: paramValue2
}

var headers = {
     headerName1: headerValue1,
     headerName2: headerValue2
}

Axios.get(url, {params, headers} ).then(res =>{
         console.log(res.data.representation);
});

**Comment by osafahmad** [comment]
You need create or set new instance for custom header. 
const instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
});

**Comment by tmoney100** [comment]
Check the docs https://github.com/axios/axios#request-config. 
`axios#get(url[, config])`
so you can put `axios.get(url, { headers, params });`

**Comment by Shafran123** [comment]
How to append some thing in middle
Some thing like bootom
https://dog.ceo/api/breed/{name_here}/images/random

**Comment by chinesedfan** [comment]
The original problem should have solved. Looks like due to CORS.

**Comment by TheMangoTrain** [comment]
To OP:

Your request isn't "simple" since you're using a custom header `x-dsi-restful`, so the request is going to receive CORS treatment, including the pre-flight `OPTIONS` request.

As well, double-check if you're also setting an authorization header elsewhere in your app (ie user is logged in. In other words, if it works when you're logged out, but get CORS when you're logged in, then this may be the case: setting an authorization header would make your request "complex".

[Mozilla's page on CORS describes a "simple" request.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests). If the request isn't simple, then you'll get CORS treatment.

Anyways, look into making a proxy server to avoid CORS issues completely, and perhaps it would come with other benefits too (separation of concerns, load balancing, security, etc).

**Comment by astolfivincent** [comment]
This works:
> Did you guys mean `axios.get('url', {headers: {"x-dsi-restful":1}})`?

This Doesn't:
> axios.get('url', {headers: "x-dsi-restful":1})
> 
> -----It's working fine thank you

The second one has a malformated object within object.
