### ISSUE TITLE
Post request to an API unauthorised

### ISSUE THREAD

**Issue by dwerynith** [axios/axios#1746]
Hello,

I am trying to contact an API with axios.
The problem is, with postman or cURL, I can easily do the request.
But my vue app gets 
"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access."

Thank you for your help.

**Comment by matthewlowry** [comment]
This is not an axios problem. This is a CORS problem.

Your page that you are serving from `localhost` is not permitting a cross-origin request to the API. You need to make whatever is serving up your page on `localhost` add the appropriate `Access-Control-Allow-Origin` response header to permit the cross-origin request.

**Comment by dwerynith** [comment]
Thank you for your answer,
my requests are made on a jamf server that i do not own.
Is there a way without having to modify the server itself ?

**Comment by OpenGG** [comment]
Not an axios issue, please refer to CORS documents for more information.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by pjotrsavitski** [comment]
@dwerynith Sorry for proposing a nasty hack, but that could help you. If you do have a backend of your own, then you could create an endpoint and relay the request there. That one would make the request to the third-party server and provide you with the data you need. You could even create a minimalistic middleware service for just doing that. Although it is a nasty hack.

As it is not an issue with axios itself, you should really close the issue to prevent unneeded spamming.
