### ISSUE TITLE
axios autometicaly add quots around integer value in json POST request

### ISSUE THREAD

**Issue by kprasadvnsi** [axios/axios#1748]
i am trying to send a POST request with json as payload
 example:

var payload = { "age": 45 }

axios.post('/api/v1/handleage', payload)
        .then((response) => {
          console.log(response.data)
        }, (err) => {
          console.log(err.response.data)
        })

what axios actually sent is  { "age": "45" }
that create server to failed parsing this field

i have sent the same request via Postman and it sent it correctly  { "age": 45 }

How can i prevent axios to wrapping quotes around Integer ?

**Comment by OpenGG** [comment]
Cant reproduce
https://codepen.io/OpenGG/pen/xaGKEP

**Comment by kprasadvnsi** [comment]
sorry, i was make json object the wrong way. thanks for the quick response tho
