### ISSUE TITLE
Capability to send Booleans as the body of a request

### ISSUE THREAD

**Issue by danilovergara** [axios/axios#1749]
#### Summary
[RFC 8259](https://tools.ietf.org/html/rfc8259) defines JSON as a notation for serializing four basic data types (integer, string, boolean and null) and two structured data types (array and object).

Actually, Axios can't send a boolean as a body. The next example should send a true boolean as body of the request.

```javascript
axios({
    method : 'POST',
    url : '//test.com/api/element',
    data : true,
    headers: {
        'Content-Type': 'application/json'
    }
})
.then(function(response) {
    if (response.status < 400){
        doSomething();
    }
})
```

By the definition of JSON, a primitve data type is a valid JSON. It would be interesting if this capability is implemented in Axios.

**Comment by ronkorving** [comment]
@danilovergara Why did you close this issue?

**Comment by jsdevel** [comment]
is this going to be fixed?
