### ISSUE TITLE
Socket will hang up with low response.

### ISSUE THREAD

**Issue by ryouaki** [axios/axios#1751]
Sometime, the response will be very slow, and does not respond, the connect event will be block by event loop system.

    And timer callback will be fired, and abort() will be invoked before connection, then get "socket hang up" and code ECONNRESET.

    At this time, if we have a large number of request, nodejs will hang up some socket on background. and the number will up and up.

    And then these socket which be hang up will devoring CPU little by little.ClientRequest.setTimeout will be fired on the specify milliseconds, and can make sure that abort() will be fired after connect.

**Comment by chinesedfan** [comment]
Solved by #1752.
