### ISSUE TITLE
Error: Cross origin http://localhost forbidden 

### ISSUE THREAD

**Issue by serverlesspolska** [axios/axios#1754]
Hi All,

I've got lambda function which I access via API Gateway.
This function works ok when I test it via Postman or via this test which uses `request` library:

```
it('shoudl work via request', async () => {
        
        var options = { method: 'POST',
        url: 'https://-----------.execute-api.eu-central-1.amazonaws.com/dev/generate',
        headers: 
         { 
           'Cache-Control': 'no-cache',
           'Content-Type': 'application/json' },
        body: 
         { html: 'PGgxPkhlbGxvIHt7bmFtZX19PC9oMT48aDI+SGVsbG8gd29ybGQhISE8L2gyPg==',
           variables: 'eyJuYW1lIjoiV29ybGQiLCJwYXRoIjoiL2hvbWUvcGF3ZWwvLm52bS92ZXJzaW9ucy9ub2RlL3Y4LjExLjMvYmluOi91c3IvbG9jYWwvc2JpbjovdXNyL2xvY2FsL2JpbjovdXNyL3NiaW46L3Vzci9iaW46L3NiaW46L2JpbjovdXNyL2dhbWVzOi91c3IvbG9jYWwvZ2FtZXM6L3NuYXAvYmluOi91c3IvbGliL2p2bS9qYXZhLTgtb3JhY2xlL2JpbjovdXNyL2xpYi9qdm0vamF2YS04LW9yYWNsZS9kYi9iaW46L3Vzci9saWIvanZtL2phdmEtOC1vcmFjbGUvanJlL2JpbjovdmFyL3Rhc2sifQ==',
           css: 'aDEge2NvbG9yOiByZWR9' },
        json: true };
      
      request(options, function (error, response, body) {
        if (error) throw new Error(error);
        expect(body.generated).toBeTruthy()
        expect(body.pdf).toBeTruthy()
      });
    })
```
### Problem
Unfortunately, when I'm using Axis I get following message **Error: Cross origin http://localhost forbidden**. 

Could you please tell me what am I doing wrong?

My code looks like that:
```
   it('should work via axios', async () => {
        const event = {
            html: "PGgxPkhlbGxvIHt7bmFtZX19PC9oMT48aDI+SGVsbG8gd29ybGQhISE8L2gyPg==",
            variables: "eyJuYW1lIjoiV29ybGQiLCJwYXRoIjoiL2hvbWUvcGF3ZWwvLm52bS92ZXJzaW9ucy9ub2RlL3Y4LjExLjMvYmluOi91c3IvbG9jYWwvc2JpbjovdXNyL2xvY2FsL2JpbjovdXNyL3NiaW46L3Vzci9iaW46L3NiaW46L2JpbjovdXNyL2dhbWVzOi91c3IvbG9jYWwvZ2FtZXM6L3NuYXAvYmluOi91c3IvbGliL2p2bS9qYXZhLTgtb3JhY2xlL2JpbjovdXNyL2xpYi9qdm0vamF2YS04LW9yYWNsZS9kYi9iaW46L3Vzci9saWIvanZtL2phdmEtOC1vcmFjbGUvanJlL2JpbjovdmFyL3Rhc2sifQ==",
            css: "aDEge2NvbG9yOiByZWR9"
        }

        await axios.post(url, event, {
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                },
                responseType: 'json',
                withCredentials: true,
            })
            .then(function (response) {
                console.log(response);
                // console.log('ok')
                expect(response.generated).toBeTruthy()
                expect(response.pdf).toBeTruthy()
            })
            .catch(function (error) {
                console.log(error);
            });
    })
```
### Context

- axios version: v0.18.0
- Environment: node v8.11.3

**Comment by OpenGG** [comment]
Possible duplicated: https://github.com/axios/axios/issues/1418

**Comment by panzupa** [comment]
Thanks @OpenGG . adding `const adapter = require('axios/lib/adapters/http')` to the config solved the problem for me

**Comment by morphatic** [comment]
I also had this problem. This thread led me to [this part of the Jest docs](https://jestjs.io/docs/en/configuration.html#testenvironment-string). I was able to fix the issue by pasting:

```javascript
/**
 * @jest-environment node
 */
```

At the top of my test file.

**Comment by wangdejun** [comment]
> I also had this problem. This thread led me to [this part of the Jest docs](https://jestjs.io/docs/en/configuration.html#testenvironment-string). I was able to fix the issue by pasting:
> 
> ```js
> /**
>  * @jest-environment node
>  */
> ```
> 
> At the top of my test file. FWIW, adding:
> 
> ```js
> {
>   // ...
>   "testEnvironment": "node"
>   //...
> }
> ```
> 
> to either `jest.config.js` or to my `package.json` file did not work for some reason. Not sure why...

really thanks, this solves my problem

**Comment by zlq4863947** [comment]
I solved this problem with the answer in the link below.

https://stackoverflow.com/questions/42677387/jest-returns-network-error-when-doing-an-authenticated-request-with-axios/43020260#43020260

**Comment by dongyuanxin** [comment]
> I also had this problem. This thread led me to [this part of the Jest docs](https://jestjs.io/docs/en/configuration.html#testenvironment-string). I was able to fix the issue by pasting:
> 
> ```js
> /**
>  * @jest-environment node
>  */
> ```
> 
> At the top of my test file. FWIW, adding:
> 
> ```js
> {
>   // ...
>   "testEnvironment": "node"
>   //...
> }
> ```
> 
> to either `jest.config.js` or to my `package.json` file did not work for some reason. Not sure why...

thanks very much!  I use it in `package.json`:
```json
{
  "scripts": {
    "test": "jest  --env=node"
  }
}
```

document: [https://jestjs.io/docs/en/cli#env-environment](https://jestjs.io/docs/en/cli#env-environment)

**Comment by odusseys** [comment]
I don't think the solution above is complete, often you will actually want to run your tests in the jsdom environment, if testing UI

**Comment by chinesedfan** [comment]
If using jest, users can set [testURL](https://jestjs.io/docs/en/configuration#testurl-string) to avoid CORS problem.

**Comment by squalsoft** [comment]
My jest.config.js resolves this issue (note testEnvironment without quotes):
`
module.exports = {
  "transform": {
    "^.+\\.(ts|tsx)$": "ts-jest"
  },
  testEnvironment: 'node'
}`

**Comment by techieanant** [comment]
Adding anything in my jest config was making other tests fail so adding the line below to my beforeAll function in my tests and it fixed the CORS error. 

`axios.defaults.adapter = require('axios/lib/adapters/http');`

**Comment by vidyamore** [comment]
Added testEnvironment variable in the Jest.config file within module.exports 
{
  "testEnvironment": "node"
}
It resolved the issue.
