### ISSUE TITLE
Invalid data response parsing

### ISSUE THREAD

**Issue by wormen** [axios/axios#1756]
I encountered a problem that when a large JSON object comes in response to a query, it does not parse correctly

![image](https://user-images.githubusercontent.com/8462339/44619089-04a46200-a8bc-11e8-89cc-c7ac4f1ca0c4.png)

- axios version: 0.18.0
- node v10.9.0, chrome 68, windows 10 / ubuntu 18.04

**Comment by OpenGG** [comment]
Need demo

**Comment by wormen** [comment]
@OpenGG what should be reflected in the demo?

**Comment by OpenGG** [comment]
@wormen A web page, with an axios request of this issue. As simple as possible.

**Comment by wormen** [comment]
as it turned out, this funny bug does not apply to axios
