### ISSUE TITLE
html2Canvas has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by xinbbbb** [axios/axios#1760]
Access to Image at 'https://xxxxxxxxxxx.com/upload/20180823/60e90eb8b00c4dfb98215286f4ad2d20.jpg' from origin 'http://localhost:8091' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8091' is therefore not allowed access.

this is the code：
Vue.prototype.getJPEG = function (url) {
      debugger
      // var timestamp = Date.parse(new Date());

      html2Canvas(document.getElementById('picDom'), {
        useCORS: true,
      }).then(function(canvas) {
        debugger
        var context = canvas.getContext('2d');
        // 关闭抗锯齿
        context.mozImageSmoothingEnabled = false;
        context.webkitImageSmoothingEnabled = false;
        context.msImageSmoothingEnabled = false;
        context.imageSmoothingEnabled = false;

        // 默认转化的格式为png,也可设置为其他格式
        Canvas2Image.saveAsJPEG(canvas, canvas.width, canvas.height);
      });
    }

How to deal with it？thanks~~

**Comment by OpenGG** [comment]
Not related to axios at all.

**Comment by wduvan** [comment]
Any solution?, in my sorce i have the same error

**Comment by Khaledgarbaya** [comment]
This is not related to axios for security reasons the browser won't let you save an image from a different domain.
You can use this as a workaround https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#Storing_an_image_from_a_foreign_origin
