### ISSUE TITLE
Fail fast if no URL is provided

### ISSUE THREAD

**Issue by ghost** [axios/axios#1765]
#### Summary

Making a request without URL (`config.url` being `undefined`, `null` or an empty string) is very likely bug in the application using axios. It would help finding these if axios could fail fast (before calling the adapter).

This behavior can only be implemented with request interceptors if it can be ensured that the interceptor containing the check

- is the last one (because other request interceptors may set the URL)
- is not removed before a request is being made.
 
I'd like to suggest adding the following code in https://github.com/axios/axios/blob/v0.18.0/lib/core/dispatchRequest.js#L57:

```javascript
if (!config.url) {
  return Promise.reject(createError('Missing request URL', config));
}
```

#### Context

- axios version: 0.17.1
- Environment: any

**Comment by jasonsaayman** [comment]
Closing in favour of #3110
