### ISSUE TITLE
[Help wanted] Navigator is undefined when using with webpack

### ISSUE THREAD

**Issue by aaayushsingh** [axios/axios#1766]
I'm trying to use this library in a non-browser environment and keep getting `navigator is undefined` when using Webpack. It works fine otherwise(without webpack). I saw 2 issues(#79 and #58)  related to this which are already closed but there is no solution provided in either.

I'd like to know how to use this with webpack correctly.

#### Context

- axios version: *v0.17.1*
- Environment: *NativeScript, non-browser enviornment*

**Comment by OpenGG** [comment]
Try adding a [DefinePlugin](https://webpack.js.org/plugins/define-plugin/)?

```js
new webpack.DefinePlugin({
  'typeof navigator': JSON.stringify('object'),
  'navigator.product': JSON.stringify('NativeScript'),
  'navigator.userAgent': JSON.stringify('NativeScript'),
});
```

I agree axios should be more platform neutral.

**Comment by chinesedfan** [comment]
Closed due to no feedback. For later users, make sure you have config your webpack correctly, i.e. target = node or something else.

**Comment by schankam** [comment]
I'm getting the same error today, with no provided solution in a server environment. How are we supposed to handle this ?

**Comment by trblackw** [comment]
Also dealing with this error as well
```
ERROR in TypeError: Cannot read property 'userAgent' of undefined
at eval (webpack:///./node_modules/style-loader/addStyles.js?:14:47)
```
