### ISSUE TITLE
How to See Authorization Header that set by Axios?

### ISSUE THREAD

**Issue by chobo2** [axios/axios#1769]
Hi

How can I see what is actually being sent by axios. I set my authorization header but I cannot see what is being sent to the server. I checked FF and Chrome but I see nothing regarding authorization headers.

Is there away I can print it out?

```
export const axiosInstance = axios.create({
  baseURL: getBaseUrl(),
  timeout: 5000,
  contentType: 'application/json',
  Authorization: 'Bearer 14154151'
});
```

 "axios": "^0.18.0",

**Comment by gcox** [comment]
You can see the raw headers sent by inspecting the response. Here's an example using a response interceptor:

```javascript
axiosInstance.interceptors.response.use(res => {
  console.log(res.request._header)
  return res;
}, error => Promise.reject(error));
```

However, the problem with your setup is that you're using `Authorization` as if it were a config option for `axios`, which it is not. It is an HTTP header that you need to set. Same problem with `contentType`. So, you just need to slightly modify your setup like this:
```javascript
export const axiosInstance = axios.create({
  baseURL: getBaseUrl(),
  timeout: 5000,
  headers: {
    Authorization: 'Bearer 14154151',
    'Content-Type': 'application/json'
  }
});
```

See the [request config](https://github.com/axios/axios#request-config) section of the readme for a list of all the options.

**Comment by chobo2** [comment]
@gcox 

hmm, I updated my code but I still don't see the headers, I would have thought this would be done on request. Maybe because I am getting 401 right now it is not executing the headers code?

**Comment by gcox** [comment]
If you add a complete example that reproduces the problem on [Repl.it](http://repl.it) I can take a look.

**Comment by gcox** [comment]
@chobo2 Catch the error, which will have a request property from which you can obtain the raw headers.

```javascript

const axios = require('axios')

const getBaseUrl = () => {
  return "http://google.com"
}

const axiosInstance = axios.create({
  baseURL: getBaseUrl(),
  timeout: 5000,
  headers: {
    Authorization: 'Bearer 14154151',
    'Content-Type': 'application/json'
  }
});

axiosInstance.get('test')
  .catch(err => {
    console.log(err.request._header)
  })

```
Output...
```
GET /test HTTP/1.1
Accept: application/json, text/plain, */*
Authorization: Bearer 14154151
Content-Type: application/json
User-Agent: axios/0.18.0
Host: google.com
Connection: close
```

**Comment by gcox** [comment]
@chobo2 Did you get past this problem?

**Comment by chobo2** [comment]
@gcox 

I got past the problem that I was trying to solve but without being able to see the headers, but I never got time to try what you posted. Hopefully maybe this weekend I will have time to try.

**Comment by chinesedfan** [comment]
Closed due to stale.
