### ISSUE TITLE
Axios only works using the 'GET' method for cross site requests

### ISSUE THREAD

**Issue by arivera12** [axios/axios#1772]
Hi, 

I know there are tons of issues regarding on the the same subject or title but there is really a bug on this. 

The issues is I have a project where I used jQuery ajax as my http client and everything works out of the box.

I have been using axios for a while and I really wanted to get rid of jQuery as my http client. 

**Axios simply doesn't work to do cross site requests when using the methods 'PUT', 'POST', and 'PATCH'.**

I have dig a little into this problem and this where my results testing all request methods.

I setup the property data: { data } for the methods **'PUT'**, **'POST'**, and **'PATCH'** and **data never gets sent**.

I setup the property params: { data } and I tested it using **'GET'** method and **data gets sent**. 

The server I have been making test is allowed for cross origin request and works with jquery ajax using all methods mentioned above. 

**Axios only works using the 'GET' method for cross site requests.**

Please help me or fix this. I really want to use axios as my http client.

Thanks in advance!

**Comment by OpenGG** [comment]
Demo please.

**Comment by arivera12** [comment]
```
this.$axios({
                method: 'post',
                url: '/usersaccount/login',
                data: this.form.model
            }).then(response => {
                this.form.isSaving = false
                this.validateLogin(response);
            }).catch(response => {
                this.form.isSaving = false
                this.$root.$snackbar(this.$i18n.t("components.login.form.unknownError"), { color: 'error' })
            })
```

**Comment by RikkiGibson** [comment]
Does cross site mean something different than cross origin?

**Comment by RikkiGibson** [comment]
It would be great if you could provide a jsfiddle or something that reproduces the issue.

**Comment by arivera12** [comment]
Can I share some images about the code and the request?

**Comment by arivera12** [comment]
I can't provide a jsfiddle cause the server is on a intranet. Is innacesible from the outside.

**Comment by RikkiGibson** [comment]
That might help, but the most actionable bug report is gonna be something where you've figured out an example that's independent of your project which illustrates the bad behavior in axios.

I created this fiddle which seems to show a cross-origin POST with the data being sent properly. httpbin just echoes the request body back. Maybe you can compare the conditions in this code to what you've got to try and narrow down what causes the bug.
https://jsfiddle.net/n2eoa3ct/11/

**Comment by arivera12** [comment]
I edited some headers on the server side and got this working. Don't know why jQuery worked out of the box without setting some additional headers. But at least I can confirm this issue is fixed for me. Thanks @RikkiGibson and @OpenGG. God bless us all!!!
