### ISSUE TITLE
Adding headers to OPTIONS pre-flight call

### ISSUE THREAD

**Issue by maziarz** [axios/axios#1777]
I am running into an unusual problem where `Authorization` header is necessary in all API calls, including OPTIONS. Since pre-flight is necessary for CORS i would like to hear if there is a way to add the `Authorization` to all calls, including OPTIONS? Is there a work-around for this?

**Comment by RikkiGibson** [comment]
Are you passing `withCredentials: true` in the request config?

**Comment by maziarz** [comment]
@RikkiGibson I tried but it does not seem to make any difference. Also as far as what i can see in chrome devtools network, there is no Authorization header.

```
 axios({
          url,
          withCredentials: true,
          headers: {
            Authorization: 'Bearer ' + this.$store.getters['auth/accessToken'],
            'Content-Type': 'application/json'
          },
          method: 'GET',
          responseType: 'blob',
        }).then((response) => {
          console.log(response)
        }).catch(console.error)
      }).catch(console.error)
```

**Comment by maziarz** [comment]
The authorization header is not in the request, i just confirmed this by manipulating the request and re-sending through Firefox dev tools and it wen't through perfectly. If i can somehow make axios include those headers my problem is solved.

**Comment by RikkiGibson** [comment]
I believe this is a limitation of browsers themselves that can’t be configured in a client side library.

The solution is probably to modify the server to handle OPTIONS requests without requiring authentication. https://stackoverflow.com/questions/15734031/why-does-the-preflight-options-request-of-an-authenticated-cors-request-work-in

**Comment by maziarz** [comment]
I see. It seems to be the only way to get around this. Thanks @RikkiGibson

**Comment by Eksapsy** [comment]
Im having the same issue. But it's more weird.
**Setup**
```ts
const headersCors = {
  'Access-Control-Allow-Origin': 'http://localhost:' + 8082,
}

// Exported for mocking reasons
export const request = axios.create({
  headers: {
    ...headersCors,
  },
  withCredentials: true,
})
```

**This works**
```ts
get: (path) =>
    request
      .get(`${API_ROOT}${path}`)
      .catch(handleErrors)
      .then(responseBody),
```

**This doesn't work**
```
post: (path, body) =>
    axios
      .post(`${API_ROOT}${path}`, body)
      .catch(handleErrors)
      .then(responseBody),
```

What happens, is that on **GET** the 'Access-Control-Allow-Origin' header is present, but on **POST** it is not present.

I think this might be a bug, or my issue. But I presume that this is not a browser's issue, since on GET it works fine.
