### ISSUE TITLE
Still cannot get Authorization to work

### ISSUE THREAD

**Issue by AnnoyedDeveloper** [axios/axios#1778]
I am currently developing a new web application with Vue.js and I am using axios for the REST API communication.

The API is on a server protected by basic auth and I cannot manage to get axios working with the Authorization header.

I tried it the way as described in [https://github.com/axios/axios/issues/1769](https://github.com/axios/axios/issues/1769) and **it did not work**:

```javascript

    const axiosInstance = axios.create({
      //method: 'GET',
      baseURL: process.env.API_BASE_URL,
      'Content-Type': 'application/json'
    });

    console.log(axiosInstance.defaults.headers);

// Alter defaults after instance has been created
    axiosInstance.defaults.headers.common['Authorization'] = 'Basic xxxx';
    axiosInstance.defaults.headers.common['X-ABC'] = "bla bla bla";

    axiosInstance.get(url)
    .then(response => {
      this.groups = response.data
    })
    .catch(e => {
      console.log(e);
      this.errors.push(e)
    });
```

I tried it like this and **it did not work**

```javascript
    axios.get(url, [{
      headers: {
        "Authorization": "Basic xxxx"
      }
    }])
    .then(response => {
      this.groups = response.data
    })
    .catch(e => {
      this.errors.push(e)
    })
```
 

 I tried it like this and **it did not work**

```javascript
    axios({
      "url": url,
      "method": "GET",
      "headers": {
        "Authorization": "Basic xxx"
      }
    })
    .then(response => {
      this.groups = response.data
    })
    .catch(e => {
      this.errors.push(e)
    })
```

They all return 401 HTTP error.

I am hitting my limit frustrated because to what the problem is.

Can anybody help me give me a very clear example and tell me where the problem lies?

Looking at the console, it seems the headers do not get sent out!

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: v6.12.3, Mac OS SX*

**Comment by gcox** [comment]
@AnnoyedDeveloper `axios` has a documented option for basic authentication called `auth`. It is documented in the [request config](https://github.com/axios/axios#request-config) section of the readme.

From the readme:
``` javascript
  // `auth` indicates that HTTP Basic auth should be used, and supplies credentials.
  // This will set an `Authorization` header, overwriting any existing
  // `Authorization` custom headers you have set using `headers`.
  auth: {
    username: 'janedoe',
    password: 's00pers3cret'
  },
```

So, something like this:
``` javascript
axios({
  method: 'get',
  url: url,
  auth: {
    username: 'your username',
    password: 'your password'
  }
})
```

**Comment by AnnoyedDeveloper** [comment]
@gcox Nope that did not work either

**Comment by AnnoyedDeveloper** [comment]
`
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
`
is displayed in the console.

Might this be a problem on the server side, that CORS is not enabled but chrome still prevents?

**Comment by gcox** [comment]
@AnnoyedDeveloper It is a CORS problem, which is controlled by server-side configuration. See [this comment](https://github.com/axios/axios/issues/853#issuecomment-411099028). IOW, it isn't an `axios` problem, and isn't related to authentication.

**Comment by RikkiGibson** [comment]
Yep, you will need to modify the server to pass:
```
Access-Control-Allow-Origin: myhost
Access-Control-Allow-Credentials: true
```
It might be possible to get the server to pass back an Allow-Origin that basically echoes the origin that sent the request. Not sure, and also not sure if that's a secure practice.

You'll also need to change your client code to include the option `withCredentials: true`.

**Comment by bunday** [comment]
Hi, I had this issue a while ago, The main problem is that because your request contains a header, it  converts your request to a Patch with a new origin but on getting to the server, the server is not allowing 'ANY ORIGIN', so you have two options either on your server set the Access-Control-Allow-Origin value to * (meaning all origin are welcome). That should solve the issue.

**Comment by luatnd** [comment]
Preflight request cannot contain any credentials, you're trying to send Authorization with OPTIONS request - which is omitted by the browser, so you didn't send any `Authorization` header => you did not pass the Basic Auth guard on server => your server would return 401

**Comment by jlbrewster** [comment]
Hey, thanks for sharing your troubles here, it really helped me.  I was able to get your code to work.  The one thing I did have to was remove "Basic" from the Auth string.  Once I just passed just 'Authorization: "my-256-bit-encrypted-key"' it worked.

This is what I am using inside of a cucumber step function:

 ` let url = 'https://mytest.tld/api/test/enroll?UserId=testUser';
    let key = '939b4201-d12e-4e9a-9043-e10c38231397';

    // axios.get
    axios({
        "url": url,
        "method": "GET",
        "headers": {
            "Authorization": key
        }
    })
    .then(function (someBoolean) {
            // handle success
            // console.log(response);
            return checkBoolean;
        })
        .catch(function (error) {
            // handle error
            console.log("User not enrolled.", error);
        })
        .then(function () {
            // always executed
        });`
