### ISSUE TITLE
Extending axios nuxt module to catch onResponse error

### ISSUE THREAD

**Issue by MrToxy** [axios/axios#1779]
I was using the axios plugin that came with the boilerplate I'm using, but later decided to go with @nuxt/axios module for ease of access and configuration.

The boilerplate already came with the plugin preconfigured which I tried to pass on to the configurations of the module upon extending it.

It originally came with this response interceptor configuration:

     axios.interceptors.response.use(
            response => response,
            error => {
              const {
                status
              } = error.response || {}
        
              if (status >= 500) {
                swal({
                  type: 'error',
                  title: app.i18n.t('error_alert_title'),
                  text: app.i18n.t('error_alert_text'),
                  reverseButtons: true,
                  confirmButtonText: app.i18n.t('ok'),
                  cancelButtonText: app.i18n.t('cancel')
                })
              }
        
              if (status === 401 && store.getters['auth/check']) {
                swal({
                  type: 'warning',
                  title: app.i18n.t('token_expired_alert_title'),
                  text: app.i18n.t('token_expired_alert_text'),
                  reverseButtons: true,
                  confirmButtonText: app.i18n.t('ok'),
                  cancelButtonText: app.i18n.t('cancel')
                }).then(() => {
                  store.commit('auth/LOGOUT')
        
                  redirect({
                    name: 'homepage'
                  })
                })
              }
        
              return Promise.reject(error)
            }
          )

I thought tha adding an interceptor for onError would do the same as catching the error onResponse but im not sure if its the same thing, but  I did the following:

    $axios.onError(error => {
        const code = parseInt(error.response && error.response.status)
        
        if(code >= 500){
            app.swal({
            type: 'error',
            title: app.i18n.t('error_alert_title'),
            text: app.i18n.t('error_alert_text'),
            reverseButtons: true,
            confirmButtonText: app.i18n.t('ok'),
            cancelButtonText: app.i18n.t('cancel')
            })
        }
    
        if (code === 401 && store.getters['auth/check']) {
            app.swal({
                type: 'warning',
                title: app.i18n.t('token_expired_alert_title'),
                text: app.i18n.t('token_expired_alert_text'),
                reverseButtons: true,
                confirmButtonText: app.i18n.t('ok'),
                cancelButtonText: app.i18n.t('cancel')
            }).then(() => {
            store.commit('auth/LOGOUT')
    
            redirect({
                name: 'homepage'
            })
            })
      }
    })

I'm currently extending my module like this:

    export default ({$axios,store,app,redirect}) => {
        $axios.onRequest(config => {
          console.log('axios request made')
         const token = store.getters['auth/token']
    
         if (token) {
          config.headers.common['Authorization'] = `Bearer ${token}`
         }
    
         const locale = store.getters['lang/locale']
         if (locale) {
          config.headers.common['Accept-Language'] = locale
         }
        })
    }

and was able to pass on the same configuration used by the plugin to the module onRequest interceptor but I can't do the same with the onResponse.

I can't understand if it's working or not, I want to know if using the onError is the right aproach (an if it is how can I return the reject like the first configuration) or if not how can I extend my module to use the same configuration for the response interceptor as the above used for the plugin.

best regards

**Comment by sschadwick** [comment]
This is better suited in the nuxt-specific axios repo: [nuxt-community/axios-module](https://github.com/nuxt-community/axios-module).
FWIW, I am also using the response interceptor instead of onError.
Lastly, @nuxt/axios should attach your token to the request headers for you 😃
