### ISSUE TITLE
How to mock Axios as default export with Jest?

### ISSUE THREAD

**Issue by NERDYLIZARD** [axios/axios#1785]
How do I mock `axios` that export as default function?

I have the api helper that generalizes api request with `axios()`

**api.js**

    export const callApi = (endpoint, method, data = {}) => {
    
      return axios({
        url: endpoint,
        method,
        data
      })
      .then((response) => // handle response)
      .catch((error) => // handle error)
    };

**api.spec.js**

    import axios from 'axios';
    import { callApi } from './api';
    
    describe('callApi()', () => {
      it('calls `axios()` with `endpoint`, `method` and `body`', () => {
    
      	// mock axios()
        jest.spyOn(axios, 'default');
    
      	const endpoint = '/endpoint';
      	const method = 'post';
      	const data = { foo: 'bar' };
    
      	// call function
      	callApi(endpoint, method, data);
    
      	// assert axios()
        expect(axios.default).toBeCalledWith({ url: endpoint, method, data});
      });
    });	

**result**

    Expected mock function to have been called with:
      [{"data": {"foo": "bar"}, "method": "post", "url": "/endpoint"}]
    But it was not called.

The call works fine if I mock `axios.get()` or other methods, but not for just `axios()`. I don't want to change the definition of the `callApi()` function.

How do I mock default `axios()`? What did I miss?

**Comment by bkd705** [comment]
Have you tried mocking it rather than spying on it?

Downside to mocking is you have to require the library _after_ you mock it, so you'd have to require `callApi` after you do the mock.

For this, I believe you could do something like:

```js
describe('callApi()', () => {
  it('...', () => {
    jest.doMock('axios', () => {
      return jest.fn()
    })

    const { callApi } = require('./api)

    // ... constants

    callApi(endpoint, method, data)

    expect(axios).toBeCalledWith({ url: endpoint, method, data })
  })
})
```

Used `doMock` here so that it is scoped to this specific test.

**Comment by NERDYLIZARD** [comment]
Thank you very much. Problem solved by the method similar to yours. [StackOverflow](https://stackoverflow.com/questions/52275312/how-to-mock-axios-as-default-export-with-jest).

**Comment by yanlee26** [comment]
Well， it's really hard to mock ！！！
