### ISSUE TITLE
axios detached element can't be garb collected

### ISSUE THREAD

**Issue by miecio1212** [axios/axios#1786]
#### Summary

I've found that you create a element and it stay in memory as detached element 
axios/lib/helpers/isURLSameOrigin.js

Take heep snap shot and find detached dom elements

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v8.11.3, chrome latest, ubuntu 16 lts*

**Comment by janewang** [comment]
+1 I've seen the same thing as well in chrome memory profiler. Please fix.

**Comment by chinesedfan** [comment]
Closed in favor of #2489.
