### ISSUE TITLE
Missing Origin header on IE11

### ISSUE THREAD

**Issue by nilobarp** [axios/axios#1790]
#### Summary

The server I am connecting to rejects request in absence of **Origin** header, all other browsers I have tested so far works but IE11 does not add the Origin header.

A minimal repro can be achieved using express and cors middleware like so

** Server **
```js
const app = express();
const domainWhitelist = ['http://localhost', 'http://localhost:8080']
const cors = corsMiddleware({
  origin: (origin, callback) => {
    if (domainWhitelist.indexOf(origin) !== -1) {
      callback(null, true);
    } else {
      callback(new Error('CORS check failed'));
    }
  }
});

app.use(cors);

app.get('/users', function(req, res) {
  res.send('list of users');
});
```

** Client **
```js
const client = axios.create({
  baseURL: 'https://api.remote.com'
});

client.interceptors.request.use((config: any) => {
  const authHeaderKey = 'Authorization';
  config.headers[authHeaderKey] = `Bearer access_token`;
  return config;
});
```

Now,

`client.get('/users')` from `http://localhost:8080` works on all browsers except IE11.

Server rejects the request because **Origin header** is missing.

#### Context

- axios version: *v0.16.2*
- Environment: *IE11 on Windows 7*

**Comment by RikkiGibson** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

docs indicate this is a forbidden header, i.e. client libraries like axios can't set it directly. It's unlikely that this issue can be solved by making changes to axios.

https://stackoverflow.com/questions/20784209/internet-explorer-11-does-not-add-the-origin-header-on-a-cors-request

Looks like IE considers a request to a different port on the same host to be "same origin" when the spec considers it to be cross-origin. Maybe that's related to the problem?

**Comment by nilobarp** [comment]
@RikkiGibson thanks for saving my Monday. In my case it was the trusted sites that made IE to exclude the header.

**Comment by gomezmark** [comment]
@nilobarp 

How did you solve this?
Ex. im working on a localhost the im using IE.

TIA

**Comment by nilobarp** [comment]
@gomezmark i removed the domain form IE's trusted site list.
