### ISSUE TITLE
[Question/Enhancement]: dynamic host, variable port - baseUrl

### ISSUE THREAD

**Issue by justinhelmer** [axios/axios#1794]
#### Summary

I have found other issues on this topic that have been resolved and closed, but wanted to pose a slightly different perspective to see how the contributors feel about this.

The challenge is, I want one piece of universal (isomorphic) code that works whether I'm in a local environment or production without having knowledge of what host the application is running. 

Consider the following use-case:

```js
const api = axios.create({ baseURL: 'http://localhost:3000' });

api
  .get('/api/items')
  .then(({ data: items }) => {
    commit('setItems', { items });
  })
```

`PORT` is something that is configured per-environment, so that's easy to handle using webpack's `DefinePlugin`:

```js
const api = axios.create({ baseURL: `http://localhost:${process.env.PORT || 80}` });

// api.get()...
```

However, `HOST` is something that would ideally be automatic so that I don't have to use `DefinePlugin` to set something that would otherwise not need to be defined. In other words, I want to specify `PORT` without specifying `HOST`:

```js
// notice HOST is not specified and thus doesn't need to be configured/defined.
// however PORT is non-standard
axios
  .get(':${process.env.PORT || 80}/api/items')
  .then(({ data: items }) => {
    commit('setItems', { items });
  })
```

This is useful for heroku & other cloud environments

Can you provide a suggestion? Thanks.

#### Context

- axios version: v0.18.0
- Environment: node v8.9.4, chrome 68, OSX 10.12

**Comment by justinhelmer** [comment]
This similar issue was closed, which even provided a few suggested solutions: https://github.com/axios/axios/issues/187

However I am reopening as the need has not gone away. Many cloud providers use dynamic port binding, in which case this becomes a necessity as I cannot see any way around it.

**Comment by justinhelmer** [comment]
No reply in over 4 months. Is this project still active?

**Comment by Shawak** [comment]
It's a joke that u can't specifiy the port

**Comment by chinesedfan** [comment]
Sorry, it is out of the scope of axios. You need specify the host and port. axios can't detect the host automatically.
