### ISSUE TITLE
Sends Content-Type: json when there is no payload on Nodejs

### ISSUE THREAD

**Issue by faztp12** [axios/axios#1796]
#### Summary
axios sends `content-type: application/json` when sending data as `params` (query string) and when no data at all for other http methods like `DELETE`

All api calls were of the form
```
axios({
    method: "delete"..
}
```

The fix was to manually set `headers["content-type"]=""` for such requests.

#### Context
This happens in node only and works fine in browser.

- axios version: v0.18.0
- Environment: node v8.10.0, windows 10

**Comment by delirius325** [comment]
Hi @faztp12 ,

According to this, the default Content-Type is `application/x-www-form-urlencoded`. Are you using a custom axios instance or just the default one?

https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L6-L8

Cheers 😄 ,

**Comment by RikkiGibson** [comment]
It doesn't look like that `DEFAULT_CONTENT_TYPE` gets applied to DELETE requests.

It would be useful to know if this line of code gets hit in the debugger
https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L52

**Comment by delirius325** [comment]
> It doesn't look like that `DEFAULT_CONTENT_TYPE` gets applied to DELETE requests.
> 
> It would be useful to know if this line of code gets hit in the debugger
> [axios/lib/defaults.js](https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L52)
> 
> Line 52 in [b4c5d35](/axios/axios/commit/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f)
> 
>  setContentTypeIfUnset(headers, 'application/json;charset=utf-8');

You're right, it's probably what's happening. I can't see how anything else would set the `Content-Type` header to `application/json`. I'll take a deeper look at it.

**Comment by dotboris** [comment]
I've tested this, and it only seems to be reproduced in the browser. Is probably has to do with the way the XHR request is sent

**Comment by dotboris** [comment]
I've tried this on the master version of `axios` and I can't reproduce this.

I tried in node 10 and in chromium. Both don't have a content type when doing a `DELETE` request.

**Comment by faztp12** [comment]
If you look at the `_header` property of `ClientRequest` you could see that `Content-Type: application/json` is set.
```
ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'DELETE /api/resource/Item/ITEM%20CD HTTP/1.1\r\nAccept: */*\r\nAccept: application/json\r\nCookie: __cfduid=d8e4a4b1cd47534f72f567dfc66200c2e1538560426;user_image=;user_id=Administrator;system_user=yes;full_name=Administrator;sid=362ba7e0aa0df024302e5962edc0efcec4769411e078f16ae51708d8;\r\nContent-Type: application/json\r\nUser-Agent: axios/0.18.0\r\nHost: test-erp.leam.ae\r\nConnection: close\r\n\r\n',        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'DELETE',
        path: '/api/resource/Item/ITEM%20CD',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] }
```


> Hi @faztp12 ,
> 
> According to this, the default Content-Type is `application/x-www-form-urlencoded`. Are you using a custom axios instance or just the default one?
> 
> [axios/lib/defaults.js](https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L6-L8)
> 
> Lines 6 to 8 in [b4c5d35](/axios/axios/commit/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f)
> 
>  var DEFAULT_CONTENT_TYPE = { 
>    'Content-Type': 'application/x-www-form-urlencoded' 
>  }; 
> Cheers 😄 ,

I am using the default one.
Searching for the keyword in my entire project brings up only 3 occurrences:
```
import axios from "axios";
axios({
    ... options ...
})
```

Axios: 0.18.0
Node: 8.10
All fine in browser

Hope it helps :)

**Comment by chinesedfan** [comment]
Closed due to too old. If you still have this problem, feel free to open a new one with detailed information. Thanks.
