### ISSUE TITLE
Facing browser issues while running in linux

### ISSUE THREAD

**Issue by ossdev07** [axios/axios#1797]
Running in docker with debian ubuntu with below version:
Linux 3169d0bf41ed 4.9.93-boot2docker #1 SMP Thu Jul 19 18:29:50 UTC 2018 x86_64
 x86_64 x86_64 GNU/Linux

node version : 8.10.0

Getting below issues after running npm install-test:
20 09 2018 06:51:15.375:ERROR [launcher]: No binary for Safari browser on your p
latform.

20 09 2018 06:51:15.955:ERROR [launcher]: Cannot start Opera
        [8813:8813:0920/065115.950618:ERROR:zygote_host_impl_linux.cc(89)] Runni
ng as root without --no-sandbox is not supported. See https://crbug.com/638180.

20 09 2018 06:51:16.135:ERROR [launcher]: Cannot start Chrome
        [8799:8799:0920/065116.129995:ERROR:zygote_host_impl_linux.cc(89)] Runni
ng as root without --no-sandbox is not supported. See https://crbug.com/638180.

20 09 2018 06:51:24.421:INFO [Firefox 62.0.0 (Ubuntu 0.0.0)]: Connected on socke
t wpZN0o194rlhEW0OAAAA with id 45684525
................................................................................
.........................................................
Firefox 62.0.0 (Ubuntu 0.0.0) requests should reject on network errors FAILED
        Error: Timeout - Async callback was not invoked within timeout specified
 by jasmine.DEFAULT_TIMEOUT_INTERVAL. in node_modules/jasmine-core/lib/jasmine-c
ore/jasmine.js (line 4470)

Please suggest me on executing test cases in all browsers or conditional execution according to platform.

Thanks in advance.

**Comment by anubhavsrivastava** [comment]
Probably not a axios issue. No traceback line suggest any of axios involvement.
