### ISSUE TITLE
Response with an object with a "type" property not handled correctly

### ISSUE THREAD

**Issue by birdy247** [axios/axios#1803]
#### Summary

Response as per Chrome dev tools:

Look the the property "type"

123: {identifier: 123, type: "occasion", name: "Thames Meander", currency: "GBP", timezone: "Europe/London",…}
456: {identifier: 456, type: "something_else",....}

Code:

`     axios.get('/api/v3/occasions/' + id, {
                    headers: {
                        'Accept': 'application/json'
                    }
                }).then(function(response) {
                    console.log(response);
					});`

Result of console.log

123: {identifier: 123, type: "occasion", name: "Thames Meander", currency: "GBP", timezone: "Europe/London",…}
456: {identifier: 456, type: "occasion",....}

Expected: 456 should have a type of "something_else"

If I change the property name from "type" to "types" this works, so the property "type" must be causing an issue

#### Context

- axios version: v0.17.1
- Environment:  node v8.11.4, Chrome Version 69.0.3497.100 (Official Build) (64-bit), windows 10

**Comment by chinesedfan** [comment]
Closed due to stale. If you still have the problem, feel free to remind me with detailed information.
