### ISSUE TITLE
Basic auth with axios returns 404 (not found)

### ISSUE THREAD

**Issue by BnMouad** [axios/axios#1806]
Hi, I've been trying using axios with basic auth but it always return not found.
### Here is my code:

```
const ROOT_URL='http://localhost/b2b_ecom/b2b-api/index.php/api/';

export function login () {


    return function(dispatch)
    {

        const api = axios.create({
            mode: 'no-cors',
            credentials:'include',
            redirect: 'follow',
            auth: {
                username: 'mouad@b2b.dz',
                password: '123456'
            },
            headers: {
                'Content-Type': 'application/json',
            }
        });

        api.post(`${ROOT_URL}site/login `).then(function(response)
        {
            dispatch({LOGIN,payload:response.data});
            return true;

        }).catch(function(error)
        {
            return error;
        });

    } ;

}
```
### Error message:
`OPTIONS http://localhost/b2b_ecom/b2b-api/index.php/api/site/login 404 (Not Found)`
`Failed to load http://localhost/b2b_ecom/b2b-api/index.php/api/site/login: Response for preflight does not have HTTP ok status.`

![axios](https://user-images.githubusercontent.com/22756265/45947615-d914b480-bfec-11e8-86ca-a86471565989.png)

any help ?

**Comment by anubhavsrivastava** [comment]
Your server (http api endpoint) needs to support OPTIONS http verb, these is not axios issue per se, but `preflight` calls are not carried out completely. This is CORS flow breakage.

Read: [MDN ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) for CORS
[MDN Preflight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)
[stackoverflow question](https://stackoverflow.com/questions/29954037/why-is-an-options-request-sent-and-can-i-disable-it) for complete understanding

**Comment by spacedawwwg** [comment]
I know this is an old thread but...

Is the endpoint expecting a GET and not a POST?

I had the same issue as I also wasn't posting a body the API devs only set it up as a GET

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
