### ISSUE TITLE
undefined is not an object (evaluating 'e.method.toLowerCase') on axios(requestConfig).then(...);

### ISSUE THREAD

**Issue by schumannd** [axios/axios#1808]
I have been getting this error reported from my clients, but don't yet know exactly how to reproduce it. 

I guess that the error comes from `lib/core/Axios.js, line 38` when something broken is passed as config.

Either way, this should be handled differently, e.g. config should be checked, and an apropriate error should be thrown.

**Comment by Marcholio** [comment]
Can this be reproduced with the current version?

**Comment by chinesedfan** [comment]
Closed due to stale and lack of enough information.
