### ISSUE TITLE
Maybe typescript definition about `AxiosInterceptorManager` is too strict？

### ISSUE THREAD

**Issue by TomIsion** [axios/axios#1809]
#### Summary

During my using with axios, I always use `axios.create()` create a new axios instance, and then change the new instance interceptors to handle all response from server.

By the interceptor, I can intercept all the errors and minimize the response payload.

Following response data maybe too big for me:

``` typescript
{
  data: {
    code: number;
    message: string;
    data: any;
  };
  status: number;
  statusText: string;
  headers: any;
  config: AxiosRequestConfig;
  request?: any;
}
```

so, I used to use interceptor to minimize & format the response.

Lately, I begin use TypeScript. axios provide typescript support. But I find the interface of interceptor function maybe too strict, during the interceptor transform function, I should return the before data structure or Promise wrapper?

``` typescript
export interface AxiosInterceptorManager<V> {
  use(onFulfilled?: (value: V) => V | Promise<V>, onRejected?: (error: any) => any): number;
  eject(id: number): void;
}
```

So, maybe the interface return may like **any**?

Thank you for share your viewpoint.

#### Context

- axios version: current
- Environment: typescript

**Comment by jasonsaayman** [comment]
Closing as we will look at this in the ESM release version.
