### ISSUE TITLE
Convert project to use Babel for ES6 support

### ISSUE THREAD

**Issue by mzabriskie** [axios/axios#181]
It's easy enough to add babel to webpack build, but requires updating release process so that only built files are published to npm.

**Comment by nickuraltsev** [comment]
I would be interested in working on this. Let me know if you would like my help.

**Comment by Ma27** [comment]
hmm the downside of such projects is always that I cannot really debug the code of foreign libraries having such a syntax when testing with mocha as there's just auto-generated code.q

**Comment by jtangelder** [comment]
You can also drop most of utils.js then. CoreJS/Babel will add polyfills for them.

**Comment by yanivefraim** [comment]
@mzabriskie @nickuraltsev  - Is someone working on this? I would be happy to take this!

**Comment by djyde** [comment]
Is there a plan to rewrite some code to ES6(`class Axios ()`, e.g.)?

**Comment by TheLarkInn** [comment]
Just stumbled across this, @mzabriskie were you hoping to also publish the loose es6 as well via the "modules" field in package.json? webpack users can benefit from this as it can "natively" read and understand the esm harmony import statements.

**Comment by RikkiGibson** [comment]
It would be great to make this happen as it could help with tree shaking in webpack (if I'm understanding the mechanics of it properly). I'd be happy to help in any way possible.

**Comment by ChristianMurphy** [comment]
The babel team wrote a blog post on their recommended approach https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

**Comment by ardalanamini** [comment]
I'd be happy to help with the rewriting in es6 or even typescript
