### ISSUE TITLE
how to post data using axios with orderBy and with params (here I am using param for authentication to access firebase)

### ISSUE THREAD

**Issue by manojkumawat003** [axios/axios#1810]
I used this code, please tell me how to use in right way-

export function sendRequest(RECEIVERUID, senderUid,TOKEN) {
    const request = axios.post(`${FIREBASE}/coordinates.json?orderBy=\"uid\"&equalTo=\"${RECEIVERUID}\"`,{
  params:{
            auth : `${TOKEN}`,
           },
         data:{
            req: senderUid
         }
    }).then(response => {
        console.log(['request_AddMember', response.data])
        return response.data
    }).catch(error => {
        console.log(error.message)
    })
    return {
        type: "REQUEST_ADDMEMBER",
        payload: request
    }
}

this method is not working. I showing error- 
Request failed with status code 400

Thanks,

**Comment by manojkumawat003** [comment]
Hi, fabiokiatkowski ,,

Post Url is right. If i use only one code between
 "params:{
auth : ${TOKEN},
},"
//and//
"data:{
req: senderUid
}",
 it works. If i use both together, it gives error. This is the problem. I hope you understood.

**Comment by fabiokiatkowski** [comment]
If I understand your problem, you can use, as the docs [Interfaces Methods](https://github.com/axios/axios#instance-methods), the POST with URL, DATA and CONFIGs.
In the CONFIGs you can pass your parameters as needed.

`axios.post(http://foo.bar/api/user, { "username" : "Foobar" } , { params: { "UID": "AA11" })`

With the code above you'll get your url like **http://foo.bar/api/user?UID=AA11** and the body request will be **{ "username" : "Foobar" }**

**Comment by manojkumawat003** [comment]
this below code is working for method:'GET' correctly.
But if i use this for method:'PATCH'

this shows Error: Request failed with status code 400.
Please tell me how to solve this.

export function acceptRequest(EMAIL,TOKEN,members){
     
    const request =   axios({
          method:'GET',
       //   url:`https://findmyfamily-b8505.firebaseio.com/coordinates.json?orderBy="email"&equalTo=${EMAIL}`,
          url:`${FIREBASE}/coordinates.json?orderBy=\"email\"&equalTo=\"${EMAIL}\"`,  
          params:{
            auth:TOKEN,
          },
          data:{
            approvedMembers:members
          }         
    }).then(response=>{
        console.log(['approvedMembers',response.data])
        return response.data
    }).catch(error=>console.log(error))

    return {
        type:'ACCEPTED_REQUEST',
        payload:request
    }
}

**Comment by fabiokiatkowski** [comment]
@manojkumawat003 

Do you using then *PATCH* method to update an specific attribute from document in Firebase?
Your `approvedMembers:members` exists?

And last, but not least, are you trying to update using *orderBy*?

**Comment by manojkumawat003** [comment]
Hey fabiokiatkowski,
thanks for supporting me.
Yes, I want to use PATCH method in above code.  And `approvedMembers:members`  is correct. I have checked it. 
And last, but not least, are you trying to update using orderBy?
ans.  yes

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking final **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
