### ISSUE TITLE
Axios is not resolving its promise and updating the state variables in reactjs

### ISSUE THREAD

**Issue by gauravsood1991** [axios/axios#1811]
what is the correct way to resolve axios promise for post method ??? Because when I try to resolve it always gives me undefined Promise Value.

 axios
      .post(buildLogin('confirmation'), {
        Email: username,
        Password: password,
      })
      .then(resolve => {
        this.setState({ authentication: resolve.data.Success });
      })
      .catch(error => {
        this.setState({ authentication: false });
        return error;
      });

is this the correct way ?

**Comment by Zhastreaus** [comment]
You don't. It's the Axios's concern to resolve a Promise.

Your role is to receive the data that was passed by Axios from a resolved/rejected promise.

Instead of
```
.then(resolve => {
  this.setState({ authentication: resolve.data.Success });
})
```

It should be
```
.then(response => { // <---- Axios will pass response data, not resolve function.
  // Do what you will with the response object.
})
```

**Comment by sagar-gavhane** [comment]
As you said you have received 

> undefined promise value

If possible, Can you show the response of post method?
Example,
```javascript
axios.post("https://jsonplaceholder.typicode.com/users/1", {
  username: "johndoe@domain.com",
  password: "123456"
})
.then(response => {
  this.setState(prevState => {
    return {
      authentication: response.data.Success
    };
  });
})
.catch(error => {
  this.setState(prevState => {
    return {
      authentication: false
    };
  });
});
```

**Comment by Annshuk** [comment]
hi,
i am also getting the same things 
my action 
export const getFields = () => {
  return (dispatch) =>{
    return axios.get(`${apiUrl}/formtype`).then(response=> dispatch(getFormFields(response.data))
    ).catch(error => {
      throw(error)
    });
  }
}

const getFormFields = (response) => {
  return {
    type: GET_FIELDS,
    payload: response
  }
}

const mapDispatchToProps = dispatch => {
  return {
    onAddUser : users => dispatch(createUser(users)),
    inputFields: dispatch(getFields())
  };
};

**Comment by chinesedfan** [comment]
Closed due to stale and not an issue of axios.
