### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined - Laravel Vue JS

### ISSUE THREAD

**Issue by mr-twady** [axios/axios#1815]
Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined
    at isURLSameOrigin (app.js:35633)
    at dispatchXhrRequest (app.js:13746)
    at new Promise (<anonymous>)
    at xhrAdapter (app.js:13649)
    at dispatchRequest (app.js:35872)

**Comment by zicong-zhang** [comment]
me too

**Comment by zhoutengshen** [comment]
i also have this problem

**Comment by zhoutengshen** [comment]
i also have this problem in react

**Comment by zhoutengshen** [comment]
I solved this problem, my fault. Because my URL path is undefined.

**Comment by huiyiwanan** [comment]
> 
> 
> I solved this problem, my fault. Because my URL path is undefined.



> 
> 
> I solved this problem, my fault. Because my URL path is undefined.

oh my god, i am so sad,bacause of URL,it`s also spend amount three hours in handling with it;
in fact,it`s a little problem    
think you for your answer!

**Comment by alonesuperman** [comment]
Perhaps check `fullpath` is a good feature request

> https://github.com/axios/axios/blob/dc4bc49673943e35280e5df831f5c3d0347a9393/lib/adapters/xhr.js#L29

change above code to

```javascript
var fullPath = buildFullPath(config.baseURL, config.url);
if (fullPath === undefined || fullPath === null) {
    return reject(createError("invaildURL", config, null, request))
}
```

will be more graceful to detect error
