### ISSUE TITLE
[function request] .catch() could not obtain the original response value

### ISSUE THREAD

**Issue by baijunjie** [axios/axios#1818]
#### Summary

The original return value of the request error cannot be obtained in the `catch`。

Example, the return value of the server is as follows when an error is requested
```
{
    "errors": [
    {
        "errorId": 25002,
        "domain": "API_INVENTORY",
        "subdomain": "Selling",
        "category": "REQUEST",
        "message": "A user error has occurred. eBay security policy only allows HTTPS resources in listings, not HTTP. Please update or remove any HTTP resources.",
        "parameters": [
        {
            "name": "0",
            "value": "Description"
        },
        {
            "name": "1",
            "value": "https://www.ebay.com/secure-listings"
        }]
    }]
}
```

But I can only get a 400 error text
```js
axios.interceptors.response.use(function (response) {
    return response;
}, function (error) {
    console.error('Response error: ', error); //=> Request failed with status code 400
    return Promise.reject(error);
});

axios.post('example.com', data)
    .catch(err => {
        console.log(err); //=> Request failed with status code 400
    });
```
It's confusing to me, I don't know what to do with this error.

After several attempts, I found that I could get the original value of the response in `transformResponse`.

I want to get the original value of the response in `.catch()`

#### Context

- axios version: v0.18.0
- Environment: node v10.6.0

**Comment by PhilSwift7** [comment]
Depending on the error you can access the response object on the .response property of the error object:

```
axios.post('example.com/404', data)
    .catch(err => {
        console.log(err.response.data);
    });
```

err is https://github.com/axios/axios/blob/d59c70fdfd35106130e9f783d0dbdcddd145b58f/lib/core/enhanceError.js#L18

**Comment by baijunjie** [comment]
Thanks
