### ISSUE TITLE
Type error in StencilJS application.

### ISSUE THREAD

**Issue by matteobortolazzo** [axios/axios#1820]
I was using the contentful cms JS SDK and it gave me the error.
Then I uninstalled the SDK and installed Axios and it gave me the same error.
So I searched in the SDK dependencies and there was Axios.

## Expected Behavior

It should work.

## Actual Behavior

Gives an error at startup: 
Failed to resolve module specifier "supports-color". Relative references must start with either "/", "./", or "../".

## Steps to Reproduce

1. npm init stencil ionic-pwa <project-name>
2. npm i --save axios
3. axios.get('some URL');
4. npm start

## Context

I'm trying to build a StencilJS client for contentful.
I also tryed to install 'supports-color' but It gives
Cannot read property 'fd' of undefined  at Function.useColors 

## Environment

-   **Language Version**: v8.11.3
-   **Package Manager Version**: 6.4.1
-   **Browser Version**: Chrome 69.0.3497.100
-   **Operating System**: Windows 10 Pro 64bit October Update
-   **Package Version**: 0.18.0
-   **Which API are you using?**: //

**Comment by chinesedfan** [comment]
`axios` doesn't depends on `supports-color`. Please check again.
