### ISSUE TITLE
Add .always support

### ISSUE THREAD

**Issue by acidjazz** [axios/axios#1823]
I know that this somewhat exists using two `.then()`'s as specified in #792 but:

*  The second `.then()` won't fire if a `.catch()` is not specified, which does not make a solid alternative
*  Ultimately I think a `.always()` would be a better readable solution, syntactic sugar.

**Comment by aljopro** [comment]
Since axios is using the built in promises, what you probably want is `.finally()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

This does mean if you want Edge support you will need to shim it.

**Comment by acidjazz** [comment]
@aljopro `.finally` sounds just as good as `.always` !

**Comment by turigeza** [comment]
I would like to have this as well. I would prefer always over finally. And no I would rather not have to shim to have Edge support. Thank you!

**Comment by chinesedfan** [comment]
It is something belong to Promise specifications, which is out of the scope of axios. See https://github.com/axios/axios/pull/2305#pullrequestreview-266978437. Thanks.
