### ISSUE TITLE
MacOS - Safari: throwing console warning "ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead"

### ISSUE THREAD

**Issue by karthik93r** [axios/axios#1825]
While uploading images into AWS/S3 we are getting following console warning **"ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead."**
We are facing this warning only on Mac Safari
In our scenario, we are converting images from base64 to ArrayBuffer (Uint8Array)

- axios version: v5.6.0
- Environment: node v8.11.1, Mac Safari

**Comment by lee1994522** [comment]
I have met this warning too.But we got it on the webView of Android 4.4.
Is there any news about it?

**Comment by chinesedfan** [comment]
See https://github.com/weixiyen/jquery-filedrop/issues/85 and https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/sendAsBinary.
