### ISSUE TITLE
Content-type json-ld

### ISSUE THREAD

**Issue by Hedin244** [axios/axios#1826]
Hey, I'm looking everywhere for answers and I cant find any.
How do I pass 'application/ld+json' as a 'Content-type'?

```
axios({
            method: 'post',
            url: API_URL,
            data: {
                "value": "data"
            },
            header: {
                'Content-Type': 'application/ld+json'
            },
});
```

**Comment by chinesedfan** [comment]
Your codes look good. If you met some problem, feel free to open another issue with detailed information.
