### ISSUE TITLE
Request defaults 

### ISSUE THREAD

**Issue by ddor254** [axios/axios#1828]
#### Summary
There is no way of knowing the defaults of request , i've searched `baseURL` default everywhere in the code and there is no way of knowing that, it is also does not mentioned in the Docs or COOKBOOK. 

from sending a relative request i see that the baseURL is 127.0.0.1 but from where `axios` retrieve that information ? and how does it build the `url` assuming i did not passed a `config` when creating a axios instance? 

#### Context

- axios version: 0.18.0
- Environment: node : v8.10.0 Ubuntu 16.04

**Comment by chinesedfan** [comment]
> There is no way of knowing the defaults of request

lib/defaults.js

> from sending a relative request i see that the baseURL is 127.0.0.1 but from where axios retrieve that information ?

Relative requests means relative to your current host. And 127.0.0.1 is the current machine.

> and how does it build the url assuming i did not passed a config when creating a axios instance?

Reading codes is the best way. :)
