### ISSUE TITLE
On a PUT reuqest, Axios resend request when the server response with 302

### ISSUE THREAD

**Issue by YannikG** [axios/axios#1829]
#### Summary

When I send a PUT request and the server redirects me, Axios resend the same request again.

I found this "Bug" while asking on Stackoverflow. For the full summary and context, read my [question ](https://stackoverflow.com/q/52609326/6383213 )please.

#### Context

- axios version: 0.18.0 - 0.19 Beta
- Environment: any Browser, Windows 10, .NET Core, VueJS

**Comment by chinesedfan** [comment]
Make sure your server returns a different url in the Location header. If not, it will result in infinite redirections.
