### ISSUE TITLE
[React native] Android onDownloadProgress event.loaded always 0

### ISSUE THREAD

**Issue by maphongba008** [axios/axios#1832]
- axios version: 0.18.0
- RN version: 0.56.1, android 6.0.
Here's my code:
```
axios.get(<link_to_file>, {
  onDownloadProgress: (event) => {
    console.log(event.loaded + ' --- ' + event.total);
  }
})
```
On iOS, it works well and I can get the `loaded` and `total`, but on Android, only `total` has value, `loaded` is always 0.
Any solution or suggest here? Thanks.

**Comment by jureczkyb** [comment]
I have exactly the same issue. 
- RN 0.55.4
- Axios: 0.18.0
The progress event fires multiple times with 0 loaded and correct total value, but loaded is never increased.

**Comment by jureczkyb** [comment]
Seems to be realted to [this react-native isse](https://github.com/facebook/react-native/pull/16371).
Unfortunately the pull request is not merged.

From there the following workaround could be used also in Axios on Android:
```
axios.get(<link_to_url>, {
  onDownloadProgress: (event) => {
    console.log("correctLoadedOnAndroid", event.target._response.length); 
    console.log("alwaysZeroLoaded", event.loaded);  }
})
```

**Comment by jureczkyb** [comment]
Seems to be realted to [this react-native isse](https://github.com/facebook/react-native/pull/16371).
Unfortunately the pull request is not merged.

From there the following workaround could be used also in Axios on Android:
```
axios.get(<link_to_url>, {
  onDownloadProgress: (event) => {
    console.log("correctLoadedOnAndroid", event.target._response.length); 
    console.log("alwaysZeroLoaded", event.loaded);  }
})
```

**Comment by sheva007** [comment]
thanks @jureczkyb for the hint.
for other people, my workaround depends on "Content-Length" header which can be added easily from the API side to the response header:
`
let { data } = await Axios.get(EaseConfig.URL_COURSES(appVersion), {
                onDownloadProgress: (progressEvent) => {
                    if (Platform.OS === 'android'){
                    console.log('loaded', progressEvent.target._response.length);
                    console.log('total', progressEvent.target.responseHeaders['Content-Length']);
                    } else {
                    console.log('loaded', progressEvent.loaded);
                    console.log('total', progressEvent.total);
                    }
                },
            });
`

**Comment by chinesedfan** [comment]
It depends on RN's implementation. Better to open an issue to RN. Closed due to nothing can be done in axios.
