### ISSUE TITLE
axios.interceptors.response has  a problem

### ISSUE THREAD

**Issue by bigGoodMan** [axios/axios#1833]
#### Summary

```
axios.interceptors.response.use(res => {
return res.data 
},err => {console.log(err)})
axios.post(...data).then(res => {
console.log(res)   //  undefined      why is not res.data? I can't understand.
 }
```
`
axios.interceptors.response.use(res => {
return res
},err => {console.log(err)})
axios.post(...data).then(res => {
console.log(res)   //  It's  object  and It's true.
 }`

#### Context

- axios version: *e.g.: v0.18.0*
-vue version: *e.g.:v2.5.17*
- Environment: *e.g.: node v10.7.0 , chrome 69.0.3497.100, mac Os  10.13.6*

**Comment by chinesedfan** [comment]
```
axios.interceptors.response.use(res => {
return res.data // the keypoint is here
},err => {console.log(err)})
```
