### ISSUE TITLE
No Content-Range in retrieved header...

### ISSUE THREAD

**Issue by tentelemed** [axios/axios#1834]
#### Summary

I have a server which returns a Content-Range (eg "0-3/4") in the http header of a Get rest endpoint. When I test this using Postman it works fine, however using Axios within my Vue.js app, I can't find any mention of Content-Range in the returned json object.

My client looks like : 

````
import axios from './axios';
import router from '@/router/index';

import store from '@/store';
import { types } from '@/store/types';

axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

const verbs = ['get', 'head', 'post', 'patch', 'delete'];

const client = {
  auth: false,
  withAuth() {
    client.auth = true;
    return client;
  },
  withoutAuth() {
    client.auth = false;
    return client;
  },
};

verbs.forEach(verb => {
  client[verb] = async (url, data = {}, headers = {}) => {
    try {
      const token = store.state.token;
      if (client.auth && token) {
        headers = Object.assign({}, { Authorization: `Bearer ${token}` }, headers);
      }
      const response = await axios({ method: verb, url, data, headers });
      client.auth = false;

      if (response.status !== 401) {
        return response;
      } else {
        store.dispatch(types.actions.LOGOUT);
        router.push('/login');
      }
    } catch (error) { // todo - never called  ? - refactor client

      client.auth = false;
      if (error.response.status === 401) {
        //router.push('auth/logout')
      }
      throw new Error(error.response.data);
    }
  }
});

export default client;
````

#### Context

- axios version: 0.18.0
- Environment: Vue.Js CLI (Webpack/Node) running on chrome 69, windows 10

**Comment by EpicKiwi** [comment]
If your request is a CORS request check the value of `Access-Control-Expose-Headers` header. It's must contain `Content-Range` to access to the value of the header from XHR and Axios API.

It's defined in [CORS specs](https://www.w3.org/TR/cors/#access-control-expose-headers-response-header) and there is more information on the [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers). Only 6 simple header types are exposed by default and the response must contains this header to expose other headers to your Javascript code.

**Comment by chinesedfan** [comment]
Closed due to stale.
