### ISSUE TITLE
When i pass params to axio.get  not found (404) url API 

### ISSUE THREAD

**Issue by lindsayct** [axios/axios#1836]
Hi, 
I pass params to axios.get, but when i pass my params, not found url API.
If i try pass this params in browser, its work!

Somebody help me???

user = {page: 1, limit: 5, search: "", order: "ascending"}

Vuex:

```
    const actions = {
      [TIPO_REQUEST]: ({commit, dispatch}, user) => {
        return new Promise((resolve, reject) => {
          commit(TIPO_REQUEST)
          axios({
            method: 'get',
            url: ENDPOINT,
            params: user,
            crossDomain: true
          })
    .....

```

Error Console:
OPTIONS http://localhost:5005/v1/componentType/componentTypeSelect?page=1&limit=5&search=&order=ascending 404 (NOT FOUND)

API(Flask):

   ```
 @api.route('/componentType/componentTypeSelect', methods=['GET'])
    def get_list():
    
       
        print[request.args.get('page')]
        return 'ok'


```

**Comment by heyamykate** [comment]
Have you tried the request in a tool like Postman? That will help you better isolate where the error is. You may want to remove the empty `search` query param as well.

**Comment by chinesedfan** [comment]
It looks like you have triggered CORS so that an OPTION request is send. But your server doesn't support OPTION request. See more about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by Number77asa** [comment]
See axios official documentation or atleast this guide worked for me:
https://codingthesmartway.com/getting-started-with-axios/


axios
        .get('http://localhost:8000/api/leads/', {
            params: {
                id: id
            }
        })
