### ISSUE TITLE
Can't trigger X-XSRF-TOKEN header to be sent with a POST

### ISSUE THREAD

**Issue by ghenry** [axios/axios#1838]
#### Summary

Can't trigger `X-XSRF-TOKEN` header to be sent with a `POST`:

https://stackoverflow.com/questions/52863990/x-xsrf-token-header-with-axios

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: axios with vue.js

**Comment by ghenry** [comment]
Do I have to set anything to send X-XSRF-TOKEN header if I set a XSRF-TOKEN cookie server side?

https://github.com/axios/axios/blob/master/lib/defaults.js#L74 https://github.com/axios/axios/blob/master/dist/axios.js#L1072

It reads like I don't, but I'm not seeing one go out.

I'll add that I have set withCredentials to true, so I do meet the first check in the OR:

```
var xsrfValue = (config.withCredentials || isURLSameOrigin(config.url)) && config.xsrfCookieName ?
            cookies.read(config.xsrfCookieName) :
            undefined;

          if (xsrfValue) {
            requestHeaders[config.xsrfHeaderName] = xsrfValue;
}
```

so if config.xsrfCookieName is a default.....

Update:

So, my OPTIONS preflight CORS is working, as is the POST now, but no X-XSRF-TOKEN being sent.

```
methods: {
    onSubmit(e) {
      this.axios
        .post(
          e.target.action,
          { data: this.form },
          {
            withCredentials: true,
            xsrfCookieName: "XSRF-TOKEN",
            xsrfHeaderName: "X-XSRF-TOKEN"
          }
        )
        .then(res => {
          console.log(res)
        })
        .catch(err => {
          this.errors.push(err)
        })
    }
  }
```

Thanks.

**Comment by ghenry** [comment]
Should I have to set these config items if they are already default?

**Comment by ghenry** [comment]
Any one have any ideas?

**Comment by seonixx** [comment]
Did you end up resolving this?

**Comment by ghenry** [comment]
Not yet. Will be back on this soon when we make https://www.surevoip.co.uk/mobile live.

**Comment by Tu-Szu-Chi** [comment]
Got the same issue too.

> axios v.0.18
> use Vue

**Comment by ghenry** [comment]
So this only works with https?

**Comment by ghenry** [comment]
Still got this issue.

**Comment by pascalboucher** [comment]
Hi @ghenry 

For me, that solved it. 

https://github.com/axios/axios/issues/876#issuecomment-309871930

Hope it can help!

**Comment by chinesedfan** [comment]
Besides of `withCredentials` as @pascalboucher mentioned, you may check whether they are [HttpOnly or Secure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies), and scopes of cookies. Read more in MDN about which kind of cookies can be Javascript accessed. Closed due to not an issue of axios.
