### ISSUE TITLE
why escape + to '%20'

### ISSUE THREAD

**Issue by initialdmg** [axios/axios#1839]
https://github.com/axios/axios/blob/75c8b3f146aaa8a71f7dca0263686fb1799f8f31/lib/helpers/buildURL.js#L11
Isn't it should be `%2B`

**Comment by hanzhangyu** [comment]
https://github.com/axios/axios/blob/75c8b3f146aaa8a71f7dca0263686fb1799f8f31/lib/helpers/buildURL.js#L5-L13

Does the encodeURIComponent function is not enough?

**Comment by meteorlxy** [comment]
+1 question here.

It's escaping `'%20'` to `'+'`, which should be `' '`.

![image](https://user-images.githubusercontent.com/18205362/58866574-729f7480-86eb-11e9-848b-805e255a24d3.png)

**Comment by initialdmg** [comment]
> https://github.com/axios/axios/blob/75c8b3f146aaa8a71f7dca0263686fb1799f8f31/lib/helpers/buildURL.js#L11
> 
> 
> Isn't it should be `%2B`

Sorry for submitting this issue. I  know this only happens in query params to encode space ` ` to `+` according to W3C.
