### ISSUE TITLE
Downloading with percentage

### ISSUE THREAD

**Issue by mirik999** [axios/axios#1840]
Hi people, i have an issue , i tried to implement downloading with percentage but it didnt work. 
When my page is render i am getting from database 17000 items and it takes time. I want to show loading with percentage 

`
const items = await axios.get('/api/get-items', {
	  		onDownloadProgress: e => console.log('progess', Math.round(e.loaded * 100 / e.total))
	  	}).then(res => res.data.items)
`

i tried with post request too , but i am getting in console only -   progess Infinity
if i will change progressEvent in my case e i will get : 
![screenshot_1](https://user-images.githubusercontent.com/29675733/47217122-65ca4c80-d3b8-11e8-866e-4288bf3b414b.png)

**Comment by RikkiGibson** [comment]
This usually means you're downloading with a chunked encoding. The server isn't telling you the content length up front so you'll have to figure it out somehow.

**Comment by mirik999** [comment]
and it is impossible to show downloading percentage ?

**Comment by RikkiGibson** [comment]
You can try specifying an [Accept-Encoding header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)

**Comment by sinkz** [comment]
I have the same problem, but only in Chrome. 

Chrome:
<img width="391" alt="Captura de Tela 2019-10-22 às 10 13 07" src="https://user-images.githubusercontent.com/12355312/67296466-dff74a80-f4be-11e9-85a2-ba946951e1e9.png">

Safari:
<img width="362" alt="Captura de Tela 2019-10-22 às 10 14 13" src="https://user-images.githubusercontent.com/12355312/67296492-e71e5880-f4be-11e9-8d22-84ce0602a6b5.png">

**Comment by chinesedfan** [comment]
Closed in favor of #1591.
