### ISSUE TITLE
POST requests cause DOM Exception 12 in Safari 9.0

### ISSUE THREAD

**Issue by c4ss** [axios/axios#1841]
Bit a niche one.

Found an annoying bug with Safari 9.0 where post requests throw a DOM Exception 12 error if headers are formatted with a space between the header key and value.

**e.g.**
will error:
`headers = 'Content-Type: application/x-www-form-urlencoded';`
won't error:
`headers = 'Content-Type:application/x-www-form-urlencoded';`

Anyone else experienced this?

**Comment by camflan** [comment]
@c4ss Yep, I just hit this as well - did you get something working?

**Comment by camflan** [comment]
@c4ss nevermind, mine was actually whitespace _after_ the header value

**Comment by chinesedfan** [comment]
@c4ss Maybe there are some invisible characters. If it is still there, feel free to remind me to reopen, with detailed & reproducible codes will be better.
