### ISSUE TITLE
xhr.upload?

### ISSUE THREAD

**Issue by Thstone37** [axios/axios#1847]
// Not all browsers support upload events
    if (typeof config.onUploadProgress === 'function' && request.upload) {
      request.upload.addEventListener('progress', config.onUploadProgress);
    }

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v8.11.3, chrome 68, windows 7*

**Comment by junj1e** [comment]
[https://github.com/axios/axios/issues/1630](url)
