### ISSUE TITLE
How to stream response and set state every second

### ISSUE THREAD

**Issue by gowdruNikhil** [axios/axios#1849]
I have a situation where i am getting base64 response from the API, but its keep on getting. no end point to set state and pass it to img src attribute.

help me to pass this continues response and set state

thank you

below is my code:     

    componentDidMount() {
        this.videoRenderingHandler();
    }
    getAxiosInstance = (temporaryToken, robotCamID, suffixCam2URL) => {

        return axios.create({
            baseURL: BASE_URL,
            headers: {
                'Content-Type': 'image/jpeg',
                'token': temporaryToken,
                'id': robotCamID,
                'urlSuffix': suffixCam2URL
            }
        });

    };

    videoRenderingHandler() {
        //const secondCameraURL = camera2URL;
        const temporaryToken = localStorage.getItem('token');
        const robotCamID = this.props.match.params.robotId;
        const suffixCam2URL = '/front_zed/depth/depth_registered';
        this.getAxiosInstance(temporaryToken, robotCamID, suffixCam2URL).get(camera2URL)
            .then((response) => {
                console.log("Image Streaming Res");
                console.log(response); //nothing is logged to console
                // this.setState({
                //     camera2Url: response
                // })
            })

            .catch(error => {

            });

    }

**Comment by vedmant** [comment]
I have the same issue, couldn't make it work with axios, so I just ended up with fetch:

```
fetch('/test', {
        method: 'POST',
        headers: {'X-CSRF-TOKEN': this.token},
        body: formData,
      }).then(response => {
        const reader = response.body.getReader()

        reader.read().then(function processResult(result) {
          if (result.done) {
            that.loading = false

            return
          }
          const string = String.fromCharCode.apply(null, new Uint16Array(result.value))
          that.log += string
          return reader.read().then(processResult)
        })
      }).catch(err => {
        alert(err)
      })
```

**Comment by chinesedfan** [comment]
axios is based on xhr and node module `http`. As far as I know, it really has no similar ability like fetch provided.

It is an experimental way as @vedmant mentioned. See more from https://developer.mozilla.org/en-US/docs/Web/API/Body/body.
