### ISSUE TITLE
Web scraping, can't get a server response

### ISSUE THREAD

**Issue by PetitCookie** [axios/axios#1850]
As you could see in the title, I have an issue with axios (Nodejs). I try to scrape an url but the timeout answers is everytime exceed. I've also tried with wget, same result but with curl I get the body like I want. I'm lost about it, if you have any idea, I'm listening. Thanks by advance.

Here is my code :

let axios = require('axios');
let cheerio = require('cheerio');

const A = axios.create({
    headers: {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7',
        'Cache-Control': 'max-age=0',
        'Connection': 'keep-alive',
        'Host': 'www.logic-immo.com',
        'Referer': 'http://www.logic-immo.com',
        'Upgrade-Insecure-Requests': '1',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
    },
    timeout : 10000
});

A.get('http://www.logic-immo.com')
    .then((response) => {
        if(response.status === 200) {
        const html = response.data;
            const $ = cheerio.load(html); 
    }
    }, (error) => console.log(err) );

**Comment by lite2210** [comment]
![screen shot 2018-11-03 at 11 04 20](https://user-images.githubusercontent.com/5634055/47947907-6803dd80-df58-11e8-93c3-36d1424ee7d8.png)
Check your internet connection and make sure request allowed if you're using VPS. Just copy n paste your code, it's working on axios v0.18.0

**Comment by PetitCookie** [comment]
I've solve my problem, i've replace the user-agent by the curl user-agent and it's work.
