### ISSUE TITLE
Implements AxiosInstance in order to make a decorator. Problem with index.d.ts file and lambdas exposed in it

### ISSUE THREAD

**Issue by lgaudez** [axios/axios#1853]
Hello,

I'm facing a problem with typescript about lambda function exposed in index.d.ts file. What I am trying to do is to decorate AxiosInstance in order to cancel pending requests when I want to. 

Here is the index.d.ts file : 

    export interface AxiosInstance {

      (config: AxiosRequestConfig): AxiosPromise; // How to override this lambda ?
      (url: string, config?: AxiosRequestConfig): AxiosPromise; // How to override this lambda ?

      // Omit the rest because ther is no problem with it
    }

Here is my implementation of AxiosInstance

    export default class CancelableAxiosInstance implements AxiosInstance {
    
        private axiosInstance: AxiosInstance;
    
        constructor(axiosInstance: AxiosInstance){
            this.axiosInstance = axiosInstance;
        }
        
        // Another function that I want to expose on CancelableAxiosInstance
        cancelRequests() {
           // Omit implementation
        }

        // How do I override (config: AxiosRequestConfig): AxiosPromise; declared in index.d.ts file ?
     }

Anybody could help me please ? 

Thanks a lot

**Comment by chinesedfan** [comment]
Right. We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues.
