### ISSUE TITLE
Add a typeguard for discriminating AxiosError type from Error type

### ISSUE THREAD

**Issue by luisnaranjo733** [axios/axios#1863]
#### Summary

It would be nice to export a typeguard from Axios' index.d.ts.
This way, consumers trying to do error handling can check in a type-safe way if the error is an AxiosError, or some other kind of error.

It's easy enough to do this as a consumer, but it would be nicer if this was included in the actual Axios library.

**Comment by luisnaranjo733** [comment]
Actually I think this will be more work than I expected. I forked and tried to make a PR myself, but Typescript gives a warning "An implementation cannot be declared in an ambient context". This basically means that defining a typeguard in a definition (*.d.ts) file is not supported.

I guess Axios would have to define its own .tsconfig and actually transpile code. If Axios were to start doing this, then Axios might as well start porting over to TS, which is a much larger scope conversation than I intended.

I think it would be awesome if Axios were written in TS, but I definitely don't have that kind of time right now. I suggest closing this issue if no one else is willing to take it on :)

**Comment by edgarjrg** [comment]
But the function can be implemented in the actual code and just add the type definition in the .d.ts file, like the rest of the code, isn't that possible? 

@luisnaranjo733  Could you point to your code?

**Comment by estorski** [comment]
Typeguard is a real runtime code (this is how it ensures the type at runtime) and thus could not be placed in `d.ts`.

I hope this feature gets implemented eventually

**Comment by rudxde** [comment]
Here my implementation:

```
import type { AxiosError } from 'axios';

export function isAxiosError(something: unknown): something is AxiosError {
    if (
        !something
        || typeof something !== 'object'
        || !('isAxiosError' in something)
        || typeof something[<keyof typeof something>'isAxiosError'] !== 'boolean'
    ) {
        return false;
    }
    return something[<keyof typeof something>'isAxiosError'];
}


```
