### ISSUE TITLE
IE11 throwed an error with Axios

### ISSUE THREAD

**Issue by knighthuj** [axios/axios#1865]
I used Vue & Vue-cli to build my program, I used Axios for ajax request. It worked fine in Chrome & Firefox but throwed an error in IE:Unhandled promise rejection SyntaxError, evin in IE11.
I have little experience in Vue and Axios, I've no idea why this error occured, who can tell me how to handle it please? Thx!
![image](https://user-images.githubusercontent.com/13588364/47947696-49074a80-df5c-11e8-9a89-5c17d49d31e5.png)

**Comment by ptmono** [comment]
I have same problem.
