### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by RemiVillien** [axios/axios#1869]
#### Summary

I'm trying to send a POST request from my frontend at http://localhost:80 to my backend at http://localhost:3000

But I get this message 
```
Access to XMLHttpRequest at 'http://localhost:3000/users/unique/' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Here is how my request looks like
```javascript
try {
      const response = await axios.post('http://localhost:3000/users/unique/',
            {
                  headers:{
                        "Content-Type": "application/json"
                  },
                  body: {
                        "email": this.signEmail,
                        "username": this.signUsername
                  }
            });
            console.log(response);
      } catch (error) {
             console.error(error);
      }

```

and my backend, I'm using Express

```js
const app = express()

// Middlewares
app.use(morgan("dev"))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app.use(cors({
    origin: 'http://localhost',
    allowedHeaders: ["Content-Type", "Authorization"]
}));

app.options('*', cors())


app.all('', function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "http://localhost");
    res.header('Access-Control-Allow-Methods', 'PUT, GET, POST, DELETE, OPTIONS');
    res.header('Access-Control-Allow-Headers', "Origin, X-Requested-With, Content-Type, Accept, Authorization");
    //Auth Each API Request created by user.
    next();
});
// Routes
app.use("/users", require("./routes/users"))
```

Has you can see I tried manualy adding the response header and also I tried the cors middleware.

#### Context

- axios version: *v0.18.0*
- Environment: *node: 8.12; express: 4.16.4; cors: 2,8,4*

Also, my frontend is running on a Docker container.

**Comment by RemiVillien** [comment]
Resolved, it was a very weird cache issue, I had to completely restart my computer and I installed `express-cache-controller`

**Comment by elmorgan3** [comment]
@RemiVillien Hi, I have the same error in my console. Can you explain more, what do you do, to fix that? Please

**Comment by RemiVillien** [comment]
It was an issue from nodemon which wasn't refreshing my code so the old code was always run.

Just install cors on your express server.

**Comment by RemiVillien** [comment]
If you need it, here is my cors config:

```js
const corsOptions = {
    origin: ['http://localhost'],
    allowedHeaders: ["Content-Type", "Authorization", "Access-Control-Allow-Methods", "Access-Control-Request-Headers"],
    credentials: true,
    enablePreflight: true
}

app.use(cors(corsOptions));
app.options('*', cors(corsOptions))
```

It must be place before all others middlewares

**Comment by smelike** [comment]
> If you need it, here is my cors config:
> 
> ```js
> const corsOptions = {
>     origin: ['http://localhost'],
>     allowedHeaders: ["Content-Type", "Authorization", "Access-Control-Allow-Methods", "Access-Control-Request-Headers"],
>     credentials: true,
>     enablePreflight: true
> }
> 
> app.use(cors(corsOptions));
> app.options('*', cors(corsOptions))
> ```
> 
> It must be place before all others middlewares

> **allowedHeaders: ["Content-Type", "Authorization", "Access-Control-Allow-Methods", "Access-Control-Request-Headers"],**

It seems like the server-side cors-configuration must allow headers include 'Content-Type'.
Otherwise, It will happen the same error again.

**Comment by ianquar** [comment]
**Install this package `cors` by running this commands**
```
npm i cors
```

after that add this 
```js
app.use(cors())
```

to your code after
```js 
const app = express()
```

It should look like this
```js
const express = require('express')
const cors = require('cors')
const app = express()
 
app.use(cors())
```

**I Hope this help**
