### ISSUE TITLE
想要实现获取token请求接口之后再给axios添加请求头，但是程序无法执行？getToken方法都不执行，不知道问题出在哪？求助大神指点

### ISSUE THREAD

**Issue by Leeehuixian** [axios/axios#1875]
//api/index.js
import axios from 'axios';
import CONST from '@/constant.js'
import {decode,storage} from '@/util/utils.js' 

// axios 配置
axios.defaults.timeout = 5000;
axios.defaults.baseURL = CONST.ApiBaseUrl; //这是调用数据接口
axios.defaults.withCredentials = true; 

//获取token
function getToken(){
    return axios.get('token',{
        headers:{'X-Requested-with':'XMLHttpRequest'}
    })
    
    // .then(function(res){
    //     console.log(res);
    //     var data = res.data;
    //     storage.set('token',{'AppId':data.AppId,'OpenId':data.OpenId,'VpnCode':data.Store[0].VpnCode});
    // }).catch(function(err){
    //     console.log(err);
    // });
}

//axios配置
axios.defaults.headers.common = {
    'X-Requested-with':'XMLHttpRequest',
    "Accept":"application/json",
    "Content-Type": "application/json"
};

// http request 拦截器，通过这个，我们就可以把Cookie传到后台
axios.interceptors.request.use(
    config => {
        // const token =  storage.get('token');
        return getToken().then((res)=>{
            console.log(res);
            var data = res.data;
            config.data = JSON.stringify(config.data);  
            config.headers["Crm-Api-PublicKey"] = data.AppId;
            config.headers["Crm-Api-Vpn"] = data.Store[0].VpnCode;
            return config; 
        }).catch((res) => {
            console.log(res);
        });
    },

    err => {  
        return Promise.reject(err);  
    }  
);  
   
// http response 拦截器  
axios.interceptors.response.use( 
    response => {  
        console.log(response);
        
        return response;  
    },  
    error => { 
        console.log(error);
        //Errmsg接口返回的错误信息，如果值为2，说明Cookie丢失，需要重新请求token,如果值为X， 
        var Errmsg = decode(error.response.headers("Crm-Api-Error"));
        if(Errmsg == 'vpncode error') {// 说明token过期，需要重新请求token 
            storage.remove('token');
            getToken();
        }else if(Errmsg === "mobileserviceerror"){//服务配置错误
            //页面跳转至错误页面service_error.html
        }  
        return Promise.reject(error.response.data) 
    }
);   

/** 
 * get方法，对应get请求 
 *param {String} url [请求的url地址] 
 * param {Object} params [请求时携带的参数] 
 */
export function get(url, params){ 
    return new Promise((resolve, reject) =>{  
        axios.get(url, {   
            params: params  
        })  
        .then(res => {   
            resolve(res.data);  
        })  
        .catch(err => {   
            reject(err.data)  
        }) 
    });
}

/** 
 * post方法，对应post请求 
 * param {String} url [请求的url地址] 
 * param {Object} params [请求时携带的参数] 
 */
export function post(url, params) { 
    return new Promise((resolve, reject) => {   
        axios.post(url, JSON.stringify(params))  
        .then(res => {   
            resolve(res.data);  
        })  
        .catch(err => {   
            reject(err.data)  
        }) 
     });
}

export default axios

**Comment by starInEcust** [comment]
用中文问不方便其他国家的人查找类似的问题呀，而且看不懂中文的就不会理你了。还有说实话你这个标题太长了，可以放在内容里，标题要说重点。英语不好可以用google translate~ 能看得懂就行啦。你的问题我也不会，就能帮你到这了

**Comment by yoyo837** [comment]
社区请使用国际语言哦，这样才更多人参与 English please 😊

**Comment by saileifeng** [comment]
can you desc in english

**Comment by AuthorProxy** [comment]
на английском можно?
