### ISSUE TITLE
DNS cache

### ISSUE THREAD

**Issue by roccomuso** [axios/axios#1878]
I do understand that mabe it's not the purpose of this lib (feel free to close in case).
But would be useful adding a dns cache layer.
It's one of the common problem nowadays with huge number of requests. It doesn't cache dns lookups or anything. Maybe it's worth just mentioning this in Readme.

**Comment by nachogarcia** [comment]
We were having dns lookup issues in our server, greatly explained in https://medium.com/@amirilovic/how-to-fix-node-dns-issues-5d4ec2e12e95 and we didn't have access to setup dns cache on the nodes, so being able to enable caching in axios would have been great.
Something like https://www.npmjs.com/package/axios-cached-dns-resolve

**Comment by chinesedfan** [comment]
Feel free to open a PR to update the document. And glad to see axios-cached-dns-resolve be added in ECOSYSTEM.md.
