### ISSUE TITLE
response needs time, and if i have to handle the response.data out of axios, error!

### ISSUE THREAD

**Issue by dujinyu** [axios/axios#1883]
`      axios.post('http://39.107.121.203:8888/printQRCode',qs.stringify({"DeviceSNList":deviceSNdata}))
      .then((res) => {
        //console.log(res.data);
        deviceSNToImgPath = res.data;
        console.log("deviceSNToImgPath in axios");
        console.log(deviceSNToImgPath);
`

      })
      .catch((err) => {
        console.log("网络错误！");
      })
      this.multipleSelectionAll.forEach((item, index) => {
        var toPushItem = item;
        console.log("deviceSNToImgPath");
        console.log(deviceSNToImgPath);
        var tempDeviceSN = toPushItem.deviceSN;
        //console.log(deviceSNToImgPath.tempDeviceSN);
        toPushItem.imgPath = deviceSNToImgPath.tempDeviceSN;
        this.$store.commit("notPrintToPrinting", toPushItem);
        this.tableData.filter((x, i) => {
          if (x.DeviceSN == item.DeviceSN) {
            this.tableData.splice(i, 1);
          }
        })
      })`

`toPushItem.imgPath = deviceSNToImgPath.tempDeviceSN;`cannot be run correctly. I guess that axios needs time, but i do not know how to handle this problem

**Comment by chinesedfan** [comment]
You can write the set statement in the callback of axios.
