### ISSUE TITLE
userData in axios request objects

### ISSUE THREAD

**Issue by Flyrell** [axios/axios#1890]
Hi. I've just published [axios-auth-refresh](https://github.com/Flyrell/axios-auth-refresh) yesterday and I have some more ideas in mind that might be implemented in the future releases of my package. I'd like to ask you if there's a possibility to add some `userData` to request objects (like for example in [Three.js - Object3D](https://threejs.org/docs/#api/en/core/Object3D.userData))? 

If there's not, wouldn't it be good to implement something similar?

There's lots of use cases for it: calls differentiation, dynamic request's params binding, etc.

Take a look at this example:
```javascript
axios.interceptors.request.use(req => {
  if (req.userData.token) {
    return req.headers['Authorization'] = req.userData.token;
  }
  return req;
});

const exampleToken = localStorage.get('exampleToken');
axios.get('https://www.example.com/restricted/area', {
  userData: {
    token: exampleToken
  }
}).then(/* ... */).catch(/* ... */);

const apiToken = localStorage.get('apiToken');
axios.get('https://www.api.com/restricted/area', {
  userData: {
    token: apiToken
  }
}).then(/* ... */).catch(/* ... */);
```

I'd be happy to contribute if anyone feels like it might be nice to have this possibility onboard.

**Comment by sbimochan** [comment]
Yeah. I'm up.

**Comment by Kamahl19** [comment]
Why would you need to create a `userData` field? You can just easily pass any data into config and consume it in both request & response interceptors. When using typescript, you can also extend the `AxiosRequestConfig` interface like this

```
declare module 'axios' {
  interface AxiosRequestConfig {
    apiCallId?: string;
  }
}
```

**Comment by chinesedfan** [comment]
I think what you need is custom configs. It is last supported in 0.18. And #2207 has fixed it again.
