### ISSUE TITLE
Catch being called by react error

### ISSUE THREAD

**Issue by davidfarina** [axios/axios#1893]
#### Summary

Hi, I've discovered something very strange today. Im using react and use axios for multiple service calls to our backend, every few seconds to poll data. This is done via a recursive setTimeout. Every axios call definition has a catch function to handle errors. Now, I have one component in react that does fail to render because I try to iterate and map over an undefined object, which I surely should not do. But upon inspecting, when this react error (Cannot read property 'map' of undefined) is thrown, it triggers the catch of this axios call definition.

I mean this is basically a non-issue since I should check against the undefined data I want to iterate over, but I found this so strange that I think that axios is doing something not quite right when handling errors. Correct me if I'm wrong, but the axios catch function should throw when the call was not successful. In my case the catch is called by something that is not related to axios.

#### Context

- axios version: v0.16.2
- react version: v15.6.2

**Comment by sbimochan** [comment]
You need to use Promise or async await.
```javascript
export async function doSomething() {
  const url = 'https://google.com';
  const response = await axios.get(url);
  /** Now response will not get undefined since there is await.
  * Now you can use map to response.data
  */
  const mappedData = response.data.something.map(el => el.key)
  return mappedData;
}
```
