### ISSUE TITLE
Docs confusion: issue with using querystring with axios

### ISSUE THREAD

**Issue by airs0urce** [axios/axios#1894]
In docs for axios I see this:

> In node.js, you can use the querystring module as follows:

> > var querystring = require('querystring');
> > axios.post('http://something.com/', querystring.stringify({ foo: 'bar' }));

I tried this and it didn't work for me.
Later I found this ticket which still open:
https://github.com/axios/axios/issues/362

And I think I know why it's still open...

"querystring.stringify" works different from "qs.stringify". See this ticket: https://github.com/nodejs/node-v0.x-archive/issues/1665

See:

first querystring:
> `$ node -e "console.log(require('querystring').stringify({a:{b: 1, c: 2}}));"`
> `$ a=`

then qs:
> `$ node -e "console.log(require('qs').stringify({a:{b: 1, c: 2}}));"`
> `$ a%5Bb%5D=1&a%5Bc%5D=2`

querystring doesn't support nested objects.

What I suggest:
1) Make a note in axios documentation to explicitly let people know that "querystring.stringify" doesn't stringify nested objects.
2) After that I think you can close this ticket: https://github.com/axios/axios/issues/362

**Comment by wasnlosdu** [comment]
How would you propose nested object should look like when _stringified_ ?

However I think this should not be noted in the `axios` documentation but rather in the `querystring`docs.

**Comment by airs0urce** [comment]
@wasnlosdu they should look like this:

a%5Bb%5D=1&a%5Bc%5D=2

Or like this without escape:
a[b]=1&a[c]=2

Sure, it should be documented in querystring docs. But to make it more clear that there is difference between two libs I think it makes sense to make a note in axios docs where it’s suggested to ise any of those libs, because result of using different libs is not equal and loks like handling nested objects is most common mistake people do

**Comment by wasnlosdu** [comment]
Oh, I see. Maybe you can open a pull request for that change?

You would have my 👍 for sure.

**Comment by airs0urce** [comment]
@wasnlosdu Sure. Will do it

**Comment by airs0urce** [comment]
Done
