### ISSUE TITLE
How to send dynamic key ,value pair while calling POST api in react native

### ISSUE THREAD

**Issue by renishdeveloper** [axios/axios#1895]
I'm calling the API like this
const data = await axios.post(url, {
            **key** : **value**,
        })
        .then(function (response) {
            console.warn(response);
          })
        .catch(function (error) {
            console.log('exios erro=>', error);
        });
It works fine ,but I want to assign the **key** from the state ,when i going to write **this.state.key** instead of key it shows error **"Unhandled Promise Rejection"**.
How to assign the dynamic key while calling API using Axios.

**Comment by wasnlosdu** [comment]
This is really not a bug related with `axios` but rather with block scoping in JS.
Maybe try reading and understanding [this](https://edgecoders.com/function-scopes-and-block-scopes-in-javascript-25bbd7f293d7).

[Here](https://stackblitz.com/edit/js-ur7hne) is a demo on how I would do it.

**Comment by renishdeveloper** [comment]
I have searched at many places including Stackoverflow ,but I can't get the solution for my solution.
Thanks in advance.

**Comment by sbimochan** [comment]
Create a function called interpolate first.
```javascript
/**
 * Build supplied string by interpolating properties inside delimiters('{ }') with the given parameters.
 *
 * @example
 * interpolate(':name is here.', {name: 'Barbara'})
 * => 'Barbaba is here.'
 *
 * @param {string} str
 * @param {object} params
 * @returns {string}
 */
export function interpolate(str, params) {
  let formattedString = str;

  for (const [key, value] of Object.entries(params)) {
    const val = value || '';

    formattedString = formattedString.replace(new RegExp(':' + key, 'gi'), val.toString());
  }

  return formattedString;
}
```
Now call this function where you need params.
```javascript
export async function updateSomething(id, editedData) {
  const url = 'http://something.com/:id' // It must contain :id

  const interpolatedUrl = interpolate(url, { id });
  const data = await http.patch(interpolatedUrl, editedData);

  return data;
}

```

**Comment by wasnlosdu** [comment]
@sbimochan This really seems to solve a totally different problem.

Look [here](https://stackblitz.com/edit/js-i9d5v7?file=ApiHelper.js).
The solution is to use:

```JavaScript
const data = await axios.post(url, {
  [key] : value,
}).then(function (response) {
  console.warn(response);
}).catch(function (error) {
  console.log('axios error => ', error);
});
```

Note the `[]`around the key.

Did this solve it?

**Comment by renishdeveloper** [comment]
No, the error is gone, but when the API calls the **null** data is inserted I think this is because of the API can't find the key passed like this **[Object.keys(parameters)[0]]**

**Comment by chinesedfan** [comment]
It is not an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).
