### ISSUE TITLE
No error if the request being sent is failed in IE

### ISSUE THREAD

**Issue by viswesh146** [axios/axios#1897]
#### Summary

When the ad blocker plugin is installed in an IE browser, plugin blocks the ad request being sent.
when the request is done through axios,  axios does not throw any error if the request is blocked. Timeout option works only if the request is sent successfully, but in this case the request itself is blocked.

Sample code:

 let adpromise = axios.get('/ads/skins/car').catch((error)=>{
      if (error.response) {
        // The request was made and the server responded with a status code
        // that falls out of the range of 2xx
        return false
      } else if (error.request) {
        // The request was made but no response was received
        // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
        // http.ClientRequest in node.js
        return true
      } else {
        // Something happened in setting up the request that triggered an Error
        return true;
      }
    })

In the above code, the catch block would never get executed in case of an IE browser, it works fine with chrome.

#### Context

OS: Windows 10 Enterprise edition
Browser: Internet Explorer 11

Additional Requirement: Need an adblocker installed and enabled in IE
- axios version: v0.18.0
- node version: v9.11.1

**Comment by chinesedfan** [comment]
@viswesh146 Which adblocker did you installed? And can you test with the latest version of axios again?
