### ISSUE TITLE
axios interceptors last request

### ISSUE THREAD

**Issue by michaelAkrawi** [axios/axios#1902]
I have my vue.js app & web api REST service using JWT authentication. the problem starts when i call some action on my api but i get 401 from it saying the token has been expired.

so i used axios interceptors to catch all this response on my app.vue component:

```
let refreshTokenPromise;
function getRefreshedToken() {
  if (!refreshTokenPromise) {
    refreshTokenPromise = userService.refresh();
    refreshTokenPromise.then(
      resetRefreshTokenPromise,
      resetRefreshTokenPromise
    );
  }

  return refreshTokenPromise;
}

function resetRefreshTokenPromise() {
  refreshTokenPromise = null;
}

Axios.interceptors.response.use(null, error => {
  if (error.config && error.response && error.response.status === 401) {
    return getRefreshedToken().then(response => {
      store.dispatch("refresh", response.data).then(response => {
        error.config.headers = authHeader();
        error.config.baseURL = undefined;
        return Axios.request(error.config);
      });
    });
  }

  return Promise.reject(error);
});

```
then when im trying to call the original request i made to the api (fetching/updating some data), the original request has been called but the response.data object is undefined for some reason.

for the example let's say this is the original call :

```
fetchUserData() {
      var vm = this;
      userService
        .get()
        .then(response => {
          if (response.data) {
            vm.profile.firstName = response.data.firstName;
            vm.profile.lastName = response.data.lastName;
            vm.profile.cityID = response.data.cityID;
            vm.profile.address = response.data.address;
            vm.profile.cellPhoneNumber = response.data.cellPhoneNumber;
            vm.profile.birthDate = response.data.birthDate;
          }
        })
        .catch(error => {
          console.log(error);
        });

```

**Comment by marcelogarbin** [comment]
@michaelAkrawi any news? I tried to do the refresh token inside the interceptors response, however it goes into a loop =/

**Comment by michaelAkrawi** [comment]
@marcelogarbin  i don't have a loop problem with this solution

**Comment by bennnjamin** [comment]
Hello, my implementation is different but I can confirm it works. Call ```setupAxios(axios)``` before you use it to make authenticated requests. In order to test, you will have to clear your JWT before making a request. If you use redux you'll need a special action for this. I use Session Storage so I can clear it use Debug Console in a browser.

I have another issue with Axios you should be aware of and I'll open an issue for. If you ```dispatch``` multiple requests and they all return 401, then the token will be refreshed once for every single request that returned a 401


```javascript
export function setupAxios(axios) {
  setJwtIfExists();
  axios.interceptors.response.use(function(response) {
    return response;
  }, function(error) {

    const originalRequest = error.config;

    if (error.response.status === 401) {

      originalRequest._retry = true;

      return refreshJwt().then(({data}) => {
        originalRequest.headers['Authorization'] = 'Bearer ' + String(data.token);
        return axios(originalRequest);
      }).catch((resp) => {
        store.dispatch(logout(1)) //logout on failure to authenticate (e.g. expired refresh token)
        return Promise.reject(resp)
      });
    }
    return Promise.reject(error);
  })

}

export function refreshJwt() {
  const refreshToken = window.localStorage.getItem('refresh_token');
  return axios.post('/tokens/refresh', {token: refreshToken}).then((resp) => {
    window.sessionStorage.setItem('token', resp.data.token);
    setJwtIfExists();
    return resp
  })
}

function setJwtIfExists() {
  const token = window.sessionStorage.getItem('token');
  if (token) {
    axios.defaults.headers.common['Authorization'] = 'Bearer ' + token;
  } else {
    axios.defaults.headers.common['Authorization'] = null;
  }
}

```

**Comment by hamzahayat** [comment]
I have an issue where `error.config.data` is coming in as a `string`, is this the expected behaviour? The previous request was a `POST` and the body was an object. 

Has anyone else seen an issue like this?

**Comment by chinesedfan** [comment]
Closed due to nothing axios needs to do. Usually the problem is that users didn't connect promises well.

@michaelAkrawi I think `refreshTokenPromise` should be updated if you want to call `then`.

```
     refreshTokenPromise = refreshTokenPromise.then(
      resetRefreshTokenPromise,
      resetRefreshTokenPromise
    );
```
