### ISSUE TITLE
i need Axios.post pass Requestbody 

### ISSUE THREAD

**Issue by Toshihiro2010** [axios/axios#1903]
My Sample Code

try{
   let strBase64 = 'qwqejfavvasdcoqenorfhhotastastj'
   let response = await Axios.post(url, strBase64 )
   console.log("Response => " + JSON.stringify(response));
}catch(error){
   console.log("Error => " + error)
}

return is error 
"Error => Error: Request failed with status code 500"

i need how to edit Code,Please.

PS. test with PostMan Success.
![cats](https://user-images.githubusercontent.com/19641939/49213884-e76dbb00-f3f7-11e8-8122-6ab7375540f3.jpg)

**Comment by wasnlosdu** [comment]
Hey, maybe it's something with your headers? Have you set them right?

What I can see from your code it should be like this:

```Javascript
try{
  let strBase64 = 'qwqejfavvasdcoqenorfhhotastastj'
  let response = await Axios.post(url, strBase64, { headers: { 'Content-Type': 'text/plain' } } )
  console.log("Response => " + JSON.stringify(response));
}catch(error){
  console.log("Error => " + error)
}
```

**Comment by chinesedfan** [comment]
Please check whether request headers are as you expected, especially `Content-Type`.

Closed first and feel free to remind me to reopen if it is really a problem caused by axios.
