### ISSUE TITLE
Axios sending multiple requests

### ISSUE THREAD

**Issue by bhautik11** [axios/axios#1905]
Every api call sending two time by axios. First Axios sending OPTIONS request method and then it will send actual request method (GET/POST/PUT/DELETE).

### (i) First API request
**General** ==>
Request URL: *************
Request Method: **_OPTIONS_**
Status Code: 200 OK
Remote Address: ******
Referrer Policy: no-referrer-when-downgrade

**Request Headers** ==>
Provisional headers are shown
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

### (II)Second API request
**General** ==> 
Request URL: *********
Request Method: **_GET_**
Status Code: 200 OK
Remote Address: **********
Referrer Policy: no-referrer-when-downgrade

**Request Headers** ==>
Provisional headers are shown
Accept: application/json, text/plain, */*
Authorization: **************
Origin: http://localhost:3000
Referer: http://localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

#### Context

- Axios version: *v0.18.0*
- Environment: *node v10.10.0, chrome v70.0.3538.110 (Official Build) (64-bit), OS Macintosh; Intel Mac OS X 10_14_1

**Comment by wasnlosdu** [comment]
These so called *preflight request* are there for security purposes. The client (e.g. axios) send them to the server to ensure their next request is allowed.
You can read this for more in-depth information:
https://stackoverflow.com/questions/15381105/cors-what-is-the-motivation-behind-introducing-preflight-requests

**Comment by bhautik11** [comment]
I don't want to send two different request...I want to send only one request so Api request take less time.

**Comment by cloudhary** [comment]
I don't believe there's any way around CORS. But if you made it a [simple request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests) they won't preflight your request, which is what you seem to be looking for?

**Comment by itstrive** [comment]
@wasnlosdu is right.
If you want one request. 
**Do not cross domain** OR **Setting Agent for it**

**Comment by xiaokk06** [comment]
so why Provisional headers ?  As the  request is correctly responded.

**Comment by YoungLights** [comment]
### ### ### ### 

> 

> 

> 

> **__**

**Comment by chinesedfan** [comment]
[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) problem, instead of Github issues.

**Comment by apanagar** [comment]
> @wasnlosdu is right.
> If you want one request.
> **Do not cross domain** OR **Setting Agent for it**

Sorry, I did not understand this. Did you meant to say Set Agent or Remove Agent? I am having the same problem
