### ISSUE TITLE
POST firing twice, no OPTIONS

### ISSUE THREAD

**Issue by Clomez** [axios/axios#1906]
#### Summary

Im using Axios and react for my front-end client and after long time of debugging i found out that something is triggering my Spring RestController method, always twice, always about two minutes in (it's very long response with huge amount of data)

Network tab does not show this second POST, but when ran from Postman, everything works as expected (no random double calls)

` showCurrent = (dateA, dateB) => {

    console.log("whaaaaat")

    axios.post("api/allData", {

        params: {

            date_a: dateA,

            date_b: dateB

        }})

        //successful fetch

        .then(res => this.setState({

            Data: res.data,

            isLoading: false,

            showPage: true,

            home: false,

        }))

        .catch(function (error) {

            //handle errors here

            alert(error.message);

        })

};`

This will print "whaaat" only once, despite below axios request happening twice.

#### Context

- axios version: v0.18.0
- Environment: Ubuntu / windows 8
- Browsers: Firefox

**Comment by wasnlosdu** [comment]
On what hook do you call the method?

**Comment by balumuriraj** [comment]
I am seeing the same issue with "GET" as-well. After 2 minutes, the request is called again.

**Comment by balumuriraj** [comment]
My Bad. Found the issue. "Node.js has a default timeout on all incoming requests, and if you don't change the timeout (as you did in your update), then Node.js will kill the TCP connection if you don't respond to the client in that amount of time." - https://github.com/expressjs/express/issues/2512

Worked fine after fixing my request timeout in node.js

**Comment by jkonze** [comment]
@balumuriraj can you please close the issue?

**Comment by balumuriraj** [comment]
@jkonze - I don't have the access to close the issue.
