### ISSUE TITLE
Cross domain in production config

### ISSUE THREAD

**Issue by zhangxuchuan827** [axios/axios#1907]
Dear bro: 
    How do I configure in a Production environment  ？
    I just set up proxyTable ， It's worked at localhost .  but when I  `` npm  run build ``  and deploy to the server, the request  display 404 。

- axios version:  the last version
- Nginx, Ubuntu 16.04

**Comment by wasnlosdu** [comment]
Would you be so kind and explain in more details what your problem is?
Maybe show the proxyTable and write what you want to achieve.

**Comment by zhangxuchuan827** [comment]
the complete URL :  https://www.apiopen.top/journalismApi
```
this.http.get('/api/journalismApi')
                .then((res) => {
                    console.log(res.data)
                    this.$toast('success')
                })
                .catch((error) => {
                    console.log(error)
                })
```
```
proxyTable: {
        '/api': {
      	target: 'https://www.apiopen.top',
      	changeOrigin: true,
      	pathRewrite: {
      		'^/api': ''
      	}
      }
    },
```
It is accessible in my local development environment, but not on the server. 
Do I need set up  other configuration ？？ for project or Nginx ?

**Comment by zhangxuchuan827** [comment]
server => host

**Comment by dimboyNew** [comment]
> the complete URL : https://www.apiopen.top/journalismApi
> 
> ```
> this.http.get('/api/journalismApi')
>                 .then((res) => {
>                     console.log(res.data)
>                     this.$toast('success')
>                 })
>                 .catch((error) => {
>                     console.log(error)
>                 })
> ```
> 
> ```
> proxyTable: {
>         '/api': {
>       	target: 'https://www.apiopen.top',
>       	changeOrigin: true,
>       	pathRewrite: {
>       		'^/api': ''
>       	}
>       }
>     },
> ```
> 
> It is accessible in my local development environment, but not on the server.
> Do I need set up other configuration ？？ for project or Nginx ?


i Understand from  pathRewrite the path  ,how can we fix problem for rewriting  different targets host to the server host itself? (including port part.)  So what is the real part working for this and the logical, thanks to anyone who can help explain this .

**Comment by zhangxuchuan827** [comment]
proxyTable is serve for local debugging。
Our web page is running on Nginx, so we use Nginx set pathRewrite.

If you webpage also run on Nginx , And your web pages production environment Host is different from your API Host. Then you can modify the Nginx config file.  

```
   // your web server config
    server {
        listen      80;
        root   /home/webapps/webpage/;

        location / {
            try_files $uri $uri/ /index.html;
            index  index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # if you access to http://yourhost/wxlogin/ , It will forward to https://open.weixin.qq.com/;
        location /wxlogin/ {
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Nginx-Proxy true;
		proxy_set_header Connection "";
		proxy_pass https://open.weixin.qq.com/;
	}
         location /lo/ {
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Nginx-Proxy true;
		proxy_set_header Connection "";
		proxy_pass https://localhost:9999/;
	}
    }
```
