### ISSUE TITLE
执行axios时，使用catch报错，Uncaught SyntaxError: Unexpected token catch

### ISSUE THREAD

**Issue by chht511** [axios/axios#1909]
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>axios</title>
	<script type="text/javascript" src="vue.js"></script>
	<script type="text/javascript" src="axios.js"></script>
	<script type="text/javascript" src="jquery.min.js"></script>
	<script type="text/javascript">
		$(function(){
			new Vue({
				el:'#my',
				data:{
					currentTime:Date.now(),
					user:{
						name:'XXXX',
						age:12
					}
				},
				methods:{
					send(){
						axios({
							methods:'get',
							url:'http://localhost:3000/info'
						}),then(function(response){
							console.log(response.data)
						}),catch(resp=>{console.log('请求失败:'+resp);});
					},
					sendGet(){
						axios.get('http://localhost:3000/info',{
							//params:{
							//name:'aa',
							//age:22
							//}
							params:this.user
						})
						.then(resp=>{
							cosole.log(resp);
						}).catch(err=>{
							console.log(err);
						})
					},
					sendPost(){
						//方式一 JSON方式传参
						//axios.post('http://localhost:3000/info',this.user)
						//方式二表单方式传参  Form Data
						axios.post('http://localhost:3000/info',this.user,{
							transformRequest:[//转换请求数据的格式
								function(data){
									let str='';
									for(let index in data){
										console.log(index);
										//name=sss&age=22&
										str+=index+'='+data[index]+'&';
									}
									str=str.substring(0,str.length-1);//截取最后一个
									//return "name=ss&age=22";
									return str;
								}
							]
						})
						.then(resp=>{
							console.log(resp);
						})
						.catch(err=>{
							console.log(resp);
						})
					}
				}
			});
		})
	</script>
</head>
<body>
	<div id="my">	
		<button @click="send">发送ajax</button>
		<button @click="sendGet">GET方式发送ajax</button>
		<button @click="sendPost">POST方式发送ajax</button>
	</div>
</body>
</html>

**Comment by chht511** [comment]
-

**Comment by wasnlosdu** [comment]
Yes, that is because you have a `,` before the catch. Replace it with a `.`

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/49560102-2053e580-f94c-11e8-88ee-3e40a0c6f98f.png)
