### ISSUE TITLE
transformResponse docs misleading

### ISSUE THREAD

**Issue by sandroden** [axios/axios#1910]
I've recently used transformRequest to get rid of the Authorization header.
It took me a while to get the correct way to pass on the data. Documentation says:

```
 // `transformResponse` allows changes to the response data to be made before
 // it is passed to then/catch
 transformResponse: [function (data) {
    // Do whatever you want to transform the data
    return data;
 }],
```
but if you use this exact code the data are passed in a wrong format (a list with an object).
At last I used:

 ```
 transformResponse: [function (data) {
       delete headers.common.Authorization
       return JSON.stringify(data)
       return data;
  }],
```
I'm definitely a beginner in this specific field but I found the documentation misleading and if what I ended up doing is correct I'd appreciate the documentation to be updated.

**Comment by cloudhary** [comment]
Based on the default transformResponse that this library has used, it seems most likely that the documentation is correct. Here's the relevant code snippet:
https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L58-L66

It's up to you on how you want to wrangle the data that you get back from the http call and I don't think the docs should be any more prescriptive than this?

**Comment by sandroden** [comment]
I've prepared this [codesandbox](https://codesandbox.io/s/l7kjnjr1om)  where not even the solution I proposed works. It's a simple login form (It's in vue, but I consider it very straightforward), my original data is a simple object with username and password. In the example I don't even touch nor data nor headers:
  `return data`
the result is that instead of sending an object axios sends a list containing an object, and that brakes the api that expects an object...
Analizing with firefox network inspector I get for the simple (working) situation, the body:

```
password: secret
username: sandro
```
for the ` return data`:

` [object Object]:`

and when using JSON.stringify (that is working in my real case and not working in this sample):

`{"username":"sandro","password":"secret"}:`

What am I doing wrong?

**Comment by salixrosa** [comment]
The issue you're having is down to the `Content-Type` header. The default transformResponse function does this for you: https://github.com/axios/axios/blob/master/lib/defaults.js#L52

But you aren't using the default transformResponse function. You can write your own functionality to add the header (and it does work; I tried it with your sandbox above), but my preferred method is to still use their default function!

Maybe there's an easier way of doing this, but we do something along these lines:
 ```
import axiosDefaults from 'axios/lib/defaults';
let conf = {
        transformRequest: axiosDefaults.transformRequest.concat(
          (data, headers) => {
            // delete headers.common.Authorization
            return data;
          }
        )
      };
```
This way Axios will perform that default transform function AND your function. You don't have to do anything to `data`, since it is already taking care of that for you (though you do still have to return it).

**Comment by mspiderv** [comment]
@sandroden The following code **overrides** default axios `transformResponse` array of functions.

```javascript
transformResponse: [function (data) {
  // something here ...
}],
```

If you want to add your own `transformResponse` function, then **do not** override the whole array. Just preppend your function to that array using this code:

```javascript
transformRequest: [(data, headers) => {
  // Do whatever you want here, for example headers.Authorization = `Bearer ${jwt}`
  return data
}, ...axios.defaults.transformRequest]
```

The whole magic is in `...axios.defaults.transformRequest`

**Comment by revmischa** [comment]
> @sandroden The following code **overrides** default axios `transformResponse` array of functions.
> 
> ```js
> transformResponse: [function (data) {
>   // something here ...
> }],
> ```
> 
> If you want to add your own `transformResponse` function, then **do not** override the whole array. Just preppend your function to that array using this code:
> 
> ```js
> transformRequest: [(data, headers) => {
>   // Do whatever you want here, for example headers.Authorization = `Bearer ${jwt}`
>   return data
> }, ...axios.defaults.transformRequest]
> ```
> 
> The whole magic is in `...axios.defaults.transformRequest`

How can one do this in TypeScript? I get the following error:
```
Type 'AxiosTransformer | AxiosTransformer[] | undefined' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.ts(2569)
```
According to Axios types it doesn't have to be an array.

**Comment by stefanozanini** [comment]
> > @sandroden The following code **overrides** default axios `transformResponse` array of functions.
> > ```js
> > transformResponse: [function (data) {
> >   // something here ...
> > }],
> > ```
> > 
> > 
> > If you want to add your own `transformResponse` function, then **do not** override the whole array. Just preppend your function to that array using this code:
> > ```js
> > transformRequest: [(data, headers) => {
> >   // Do whatever you want here, for example headers.Authorization = `Bearer ${jwt}`
> >   return data
> > }, ...axios.defaults.transformRequest]
> > ```
> > 
> > 
> > The whole magic is in `...axios.defaults.transformRequest`
> 
> How can one do this in TypeScript? I get the following error:
> 
> ```
> Type 'AxiosTransformer | AxiosTransformer[] | undefined' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.ts(2569)
> ```
> 
> According to Axios types it doesn't have to be an array.

Not the perfect solution, but i managed to bypass the error doing something like this:
`transformRequest: [(data, headers) => {
  // Do whatever you want here, for example headers.Authorization = `Bearer ${jwt}`
  return data
}, ...(axios.defaults.transformRequest as AxiosTransformer[])]`

**Comment by jspark-gigworks** [comment]
I think this solution should be specified in docs.

**Comment by webknjaz** [comment]
FTR I've found it useful to reorder the transformers so that the default one would parse JSON and my custom one would get a proper object input already.

```typescript
interface SomeModel {
  created: Date;
}
```

```typescript
transformRequest: [
  ...axios.defaults.transformRequest as AxiosTransformer[],
  (data: any): SomeModel => {
    // Do conversions like string to date AFTER data is turned
    // from string into an object.
    if (data.created) {
      data.created = Date.parse(data.created);
    }
    return data;
  },
],
```

**Comment by jasonsaayman** [comment]
Closed as this does not seem to directly be an issue with the repository.
