### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by bazteam2018** [axios/axios#1917]
Is there any performance comparison between `axios` and other libraries?
What about the native `http` module?

From simple tests that I have executed, `axios` is much inferior than the native `http` module for simple `GET` requests.

**Comment by chinesedfan** [comment]
It's a tradeoff between performance with convenience. Compared them directly are not fair. For example, assembly codes should be much "performance better" than C/C++/Javascript, but it's hard for people to write. In fact,  `axios` is a wrapper of `http`. But if you really care about performance, you can try to use native modules without any other libraries' help.
