### ISSUE TITLE
[QUESTION] Does Axios have a character limit per parameter?

### ISSUE THREAD

**Issue by xcesaralejandro** [axios/axios#1921]
I'm trying to send a key that is a stringify of a JSON, it's a bit long and when I send it, it does not arrive on the server but the rest of the parameters.
How many is the limit of characters that supports axios per parameter?

**Comment by mrgurdeep** [comment]
Try it with postman or some other tool. If it works, it should work with axios. I don't think there is any limit.

**Comment by heyamykate** [comment]
Closing - this isn't an issue with axios itself.
