### ISSUE TITLE
Can't find variable: process in 0.18

### ISSUE THREAD

**Issue by LinusU** [axios/axios#1922]
#### Summary

The following line is trying to access `process.env.NODE_ENV` in a browser environment, and thus triggers an error when `process` isn't defined.

https://github.com/axios/axios/blob/v0.18.0/lib/adapters/xhr.js#L27

My guess is that many users don't notice this since browserify/webpack replaces/can replace `process.env` access. I'm using a very simple rollup setup that doesn't do that though.

This problem is no longer present in master because of #1689, and thus won't be a problem in 0.19.0. Would it be possible to release a version 0.18.1 with a hotfix for this?

I tried sending a PR but there doesn't seem to be a branch for the 0.18 release line?

Proposed patch:

```diff
-    if (process.env.NODE_ENV !== 'test' &&
+    if ((typeof process !== 'object' || process.env.NODE_ENV !== 'test') &&
```

Thank you!

#### Context

- axios version: v0.18.0
- Environment: Safari 12

**Comment by LinusU** [comment]
If anyone needs a workaround asap while waiting for upstream, you can install my patch as such:

```sh
npm install LinusU/axios#0.18-hotfix
```

Would love to get an official **0.18.1** out though ❤️

**Comment by LinusU** [comment]
ping @rootsher

**Comment by rootsher** [comment]
@LinusU sorry for the delay - I created a branch from version 0.18 - please do the appropriate pull request https://github.com/axios/axios/tree/hotfix/process-env-node-env :)
