### ISSUE TITLE
Accept header doesn't pass

### ISSUE THREAD

**Issue by buzzpsych** [axios/axios#1932]
The format of the response is incorrect when making this request with the following criteria. I suspect it has something to do with the headers not being passed correctly with axios.

The request: 
`https://api.github.com/repos/:owner/:repo/contents/package.json`
Headers: 
`Accept: 'application/vnd.github.v3.raw',`

This exact criteria works on POSTMAN and other HTTP Clients. As in "Works" I mean get's the right format of the response which should be `application/vnd.github.v3.raw`

Please reference here for this specific use case https://developer.github.com/v3/repos/contents/

**Comment by rm-hull** [comment]
Likely same cause as #1819

**Comment by chinesedfan** [comment]
Closed in favor of #1819. Would you mind adding a reproducible example there?
