### ISSUE TITLE
the config param has been change since v0.19.0-beta.1

### ISSUE THREAD

**Issue by imshenshen** [axios/axios#1934]
#### Summary

the `config` param has been change since v0.19.0-beta.1

#### Context
```javascript
// request config
instance.interceptors.response.use(undefined,function(error){
  // in v0.19.0-beta.1 ,the custom/extra params are lost
  console.log(error.config.showError)
}))
```

```javascript
// caller
instance({
  url:'http://test.com',
    showError:{
      type: 'alert'
  }
})
```

- axios version: *e.g.: v0.19.0-beta.1*

**Comment by imshenshen** [comment]
oh , i see this https://github.com/axios/axios/pull/1831
but that is also a ***breaking change*** to 0.18
can you update the `changelog.md`?

**Comment by chinesedfan** [comment]
Fixed in #2207. And released in 0.19.1.

**Comment by jtrainaldi** [comment]
I tried the custom parameters with 0.19.2 and it does not work.

`await axios({
    method: 'get',
    url: 'v1/userDetails', 
    params: { userName: userName },
    showGlobalDialogError: true,
  })`

I am unable to read the showGlobalDialogError in the interceptors

**Comment by chinesedfan** [comment]
@jtrainaldi Confirmed again it works. If you insisted, please open a new issue with required sample Runkit link. Thanks.

**Comment by jtrainaldi** [comment]
@chinesedfan 
Seems like I am not the only one who is experiencing this issue.  Maybe the documentation is not complete but if I add a custom attribute to the config object where can I retrieve it from the interceptor.


https://github.com/axios/axios/issues/2203#issuecomment-578612164

**Comment by jtrainaldi** [comment]
@chinesedfan I confirmed it is working now.  The issue was with my cached docker image.  'docker system prune' fixed it.
