### ISSUE TITLE
transformRequest appears not to be working in simple example pasted from docs

### ISSUE THREAD

**Issue by pkellner** [axios/axios#1936]
#### Summary

In very simple case (all cases I tried), transformRequest does not get called on a put. You can see simple example here where I expect that console.log should be processed.

https://stackblitz.com/edit/axios-api-transformrequest-problem

#### Context

- axios version: *e.g.: "axios": "0.16.2",
see stackblitz

**Comment by glenndevenish** [comment]
related? https://github.com/axios/axios/issues/1910

**Comment by lmiller1990** [comment]
The second argument to PUT is the data. The third is options. This should be written as:

```js
axios.put('https://599d6a620a785b0011f4f6c8.mockapi.io/users/101', {}, { 
      transformRequest: [function (data, headers) {
        console.log("this never gets called.  transformRequest")
        return data;
      }]
    })
```
