### ISSUE TITLE
Remove dependency of is-buffer, inlining instead

### ISSUE THREAD

**Issue by jacksonStone** [axios/axios#1941]
#### Summary

Considering the is-buffer library exports about two lines of code (https://github.com/feross/is-buffer/blob/master/index.js) it may be nice to just inline it into a file included in the project, rather than requiring it as a dependency. Cut Axios's number of dependencies by 50% in a snap!

#### Context

- axios version: 0.18.0

**Comment by chinesedfan** [comment]
Landed in #1816.
