### ISSUE TITLE
为什么get、post、put、delete的传参方式不封装成一样的？

### ISSUE THREAD

**Issue by my3188** [axios/axios#1942]
let url = '/api/login';
let mydata = {name:'jam'}
axios.get(url,{params:mydata})
axios.post(url,params:mydata)
axios.put(url,params:mydata)
axios.delete(url,{data:mydata})

为什么不把get的params和delete的data封装在里面，这样就和post、put一致了，使用起来也方便啊

**Comment by SeanKChan** [comment]
delete请求是不能设置data的
