### ISSUE TITLE
Can not upload an image using axios

### ISSUE THREAD

**Issue by begueradj** [axios/axios#1943]
#### Summary

I want to upload an image to my AdonisJS REST API using axios from a Nuxt.js client application.
I noticed that data is always transferred successfully as long as it is not an image or any other file.

#### Client code:

```
async submit() {
  console.log(this.photo) // this is fine
  let data = new FormData()
  data.append('file', this.photo)
  let url = 'http://127.0.0.1:3333/upload'
  let options = {
    headers: {
      'content-type': 'multipart/form-data'
    }
  }
  await this.$axios.$post(url, data, options)
}
```
#### Server code:
```
async upload( {request, response} ) {                                                                                             
  console.log(request.all())    
}
```

#### Server output
I always get this in case of a file: `{}`

#### Context

- axios version: current release
- Environment.: node v10.13.0 chrome 71, Ubuntu 18.04*

Thank you for any suggestions, 
Billal BEGUERADJ

**Comment by begueradj** [comment]
This was not an axios issue, sorry, I close this.

**Comment by videni** [comment]
@begueradj , how do you solve this? I also have this problem.
