### ISSUE TITLE
 i call an api several times,i get network error

### ISSUE THREAD

**Issue by alvandyhamed** [axios/axios#1944]
hi, when i use axios ,and i call an api several times,i get network error

My request 
export const singleHozor=(studentId,statusId,presenceStatusId,username)=> {
    let Students=[]
   
    let data = JSON.stringify({
        "studentId":studentId,
        "statusId":statusId,
        "presenceStatusId":presenceStatusId,
        "username":username

    })
 
    return axios.post(apies.ChangeStatiseStudentInService,data
        ,{

            headers: {
                'Pass': 123,
                'Content-Type':'application/json'

            },
            timeout: 5000
        }

    )
        .then((response) => {
            console.log('YASA',response)

                if(response.ok){

                    return response.data

                }else {

                }
                return response.data

            }
        ).catch(error=>{
            console.log('singleHozor',error,error.status)
            if (error.response) {
                // The request was made and the server responded with a status code
                // that falls out of the range of 2xx
                console.log(error.response.data);
                console.log(error.response.status);
                console.log(error.response.headers);
            } else if (error.request) {
                // The request was made but no response was received
                // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
                // http.ClientRequest in node.js
                console.log(error.request);
            } else {
                // Something happened in setting up the request that triggered an Error
                console.log('Error', error.message);
            }
            console.log(error.config);

            ToastAndroid.show(I18n.t('timeout'), ToastAndroid.SHORT);
           /* this.setState({
                loade:false
            })*/
            return {response:false,message:'Network Problem'}
        })
        .then((responseJson) => {
            console.log("ASsaaaa",responseJson)

            return responseJson

        })
        .catch(error => {
            console.log('Sarina',error)
            ToastAndroid.show(error, ToastAndroid.SHORT);

            return {response:false,message:'Network Problem'}

        });

}

and i get below error
singleHozor Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)
    at XMLHttpRequest.dispatchEvent (event-target.js:172)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:567)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:397)
    at XMLHttpRequest.js:503
    at RCTDeviceEventEmitter.emit (EventEmitter.js:179)
    at MessageQueue.__callFunction (MessageQueue.js:351)
    at MessageQueue.js:116
    at MessageQueue.__guardSafe (MessageQueue.js:314)

**Comment by abraaobarros** [comment]
I am having the same problem.

**Comment by Alanscut** [comment]
@alvandyhamed What is the type and size of the returned data? I  tested in your code which response data's size is serveral kb, and it's ok.
I suggest you use the `debounce` to prevent continuous request.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

If you confirm that axios sends wrong headers, feel free to remind me to reopen.
