### ISSUE TITLE
Failed to execute 'setRequestHeader' on 'XMLHttpRequest': Value is not a valid ByteString

### ISSUE THREAD

**Issue by tomatojacky** [axios/axios#1945]
return axios({
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    method: 'post',
    url: BASE_URL + API_ROOT + '/account/login',
    data: {
      user_name: data.username,
      password: data.pwd
    }
  })

when data.user_name is chinese like “汤姆”,
throw error **### Failed to execute 'setRequestHeader' on 'XMLHttpRequest': Value is not a valid ByteString**

but data.user_name = 'tom' no error

**Comment by tomatojacky** [comment]
> return axios({
> headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
> method: 'post',
> url: BASE_URL + API_ROOT + '/account/login',
> data: {
> user_name: data.username,
> password: data.pwd
> }
> })
> 
> when data.user_name is chinese like “汤姆”,
> throw error **### Failed to execute 'setRequestHeader' on 'XMLHttpRequest': Value is not a valid ByteString**
> 
> but data.user_name = 'tom' no error

**please close it ，the erro msg is next ajax ,when i change content-type ,then request the next ajax ,I should change content-type to default .**

**Comment by mdrahiem** [comment]
I am still facing this issue. Sometimes some how its getting resolved automatically. But sometimes it does exist. I am not sure what is the reason. Can anyone please help?

**Comment by SergeyKurdyukov** [comment]
I get this error if  `Authorization` header of a request contains non-ASCII symbols.
