### ISSUE TITLE
Axios not giving me access to custom headers

### ISSUE THREAD

**Issue by kevinseabourne** [axios/axios#1946]

**Comment by kevinseabourne** [comment]
Axios is not giving me access to a custom made header, its blacklisting it
this code is written in node

.header("x-auth-token", token)
.header("Access-Control-Expose-Headers", "x-auth-token") 

this should allow me to see x-auth-token but it is not, the token is there but axios is not allowing me to see it.  

Axios V0.18

**Comment by adanilev** [comment]
I'm having a similar issue. 

I can see all my headers if I call my API with [node-fetch](https://github.com/bitinn/node-fetch) or curl but axios seems to drop them and put in defaults: `{"content-type": "text/plain; charset=UTF-8"}`

I went down a long CORS rabbit hole to no avail so now switching to node-fetch ☹️

**Comment by AritraSengupta** [comment]
I have a very similar problem as well. The response headers in browser is showing up properly but axios is dropping them:

Response Headers From Browser:
<img width="543" alt="screen shot 2019-01-29 at 6 11 59 am" src="https://user-images.githubusercontent.com/17586348/51914190-1c14d900-238d-11e9-9ab7-5b003bb8c1ff.png">

Response Header in Axios:
<img width="644" alt="screen shot 2019-01-29 at 6 10 11 am" src="https://user-images.githubusercontent.com/17586348/51914172-11f2da80-238d-11e9-97b4-428d636adbd7.png">

**Comment by nicolkill** [comment]
Same problem here, i want get custom headers from response and i only have the content type header

**Comment by nicolkill** [comment]
Hey there, i found [this stackoverflow post](https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields) that help me to solve this problem

**Comment by miszmaniac** [comment]
I'm not using browser.
I installed Axios on Google Cloud node.js project and can't read custom headers.
I don't think it should be blocked while communicating between servers?

**Comment by agegeneral** [comment]
I think it maybe a bug.
I set header("Access-Control-Expose-Headers", "custom-header") in Server.
I can get custom-header by jQuery Ajax.

If I use Axios, I can see response custom-header through Chrome developer tool.
But Axios can't get custom-header.

**Comment by tecnauta** [comment]
This worked for me.

`api.post,
      'sessions',
      {
        email,
        password,
      },
      {
        validateStatus: false,
      },`

Then

`const responseStatus = response.status;
if (responseStatus < 200 || responseStatus >= 300) throw response;`

In response.headers I have ALL my headers!

**Comment by JulianG-TW** [comment]
**2021 Update:**

I'm still unable to access my custom response headers using **axios@0.21.1**.

While I can perfectly access them in other projects using **fetch**.

**Comment by fdoperezr** [comment]
Hello, any solution?. I currently using axios 0.21.1

**Comment by dimmedcrow** [comment]
Access-Control-Expose-Headers on the server worked for me, axios started to show them 
Like ("Access-Control-Expose-Headers", "my-header")

**Comment by LFDMCreations** [comment]
> Hey there, i found [this stackoverflow post](https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields) that help me to solve this problem

I had seen it but still doesn't work for me.

**Comment by JulianG-TW** [comment]
> ~I'm still unable to access my custom response headers using axios@0.21.1.~
> ~While I can perfectly access them in other projects using fetch.~

It turns out the problem was CORS. I was making my requests with Axios to a different origin, and using fetch to the same origin. So my comparison was incorrect.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

> Only the [CORS-safelisted response headers](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header) are exposed by default. For clients to be able to access other headers, the server must list them using the Access-Control-Expose-Headers header.
> 
> The Access-Control-Expose-Headers response header allows a server to indicate which response headers should be made available to scripts running in the browser, in response to a cross-origin request.

**Comment by angelhtml** [comment]
If you are using Express js server, just use this line before setting your custom header

``` javascript
res.header("Access-Control-Expose-Headers", "*")
```

for example:

``` javascript
const CustomHeader = async (req, res) => {
    try{
        var token = await jwt.sign(req.body, secret);

        //full access for getting the header in client side
        res.header("Access-Control-Expose-Headers", "*")

        //set your custom header
        res.set("header_token", token)

        res.send("CustomHeader")
    } 
    catch(err){ console.log(err)}
}

app.post("/CustomHeader ", CustomHeader );

```

**Comment by bublikOff** [comment]
The header "Access-Control-Expose-Headers" must be sent along with the actual server's answer not as CORS answer
