### ISSUE TITLE
Errors always echo out to console on Chrome

### ISSUE THREAD

**Issue by TseWaiHo** [axios/axios#1947]
#### Summary
I am using axios in Vue component just like common official examples. I find that axios always echo out the error to console in red color. I have tried the traditional `axios.get('/url').catch(function (error) {` and the async one, both have same issue.
```
try {
    const response = await axios.get('/uri');
  } catch (error) {
    console.error(error.response.status);
  }
```

I eliminate all other possibilities by just using plain html and js. plain axios.min.js.
Problem still exist.
```
    <script>
	axios.get('https://somethingnotexistssssss.com')
	  .then(function (response) {
	    console.log('handle success');
	  })
	  .catch(function (error) {
	    console.log('error catched');
	  })



      async function submitForm() {
        try {
          const response = await axios.get(
            'https://somethingnotexistssssss.com'
          );
        } catch (error) {
          console.log('catched');
        }
      }

      submitForm();
    </script>
```

Then I tried to test it on Firefox, both vue component and plain vanilla js works normal.

I have google about this problem before opening this issue, cannot find a solution, some other related issues are still in open state. 
I am opening this issue to state that Firefox don't have this problem. 
Could somebody help to test it on a mac to find whether it exist on safari ?
One more discovery, after I encounter this problem, I wanted to switch to another library - superagent.
It have exactly some issue, on Chrome only.

#### Context

- axios version: v0.18.0
- Environment: 
Chromium 71.0.3578.80
Firefox 64.0

**Comment by itstrive** [comment]
I think your `url` has problem. Check you Server API.

See This demo: https://codesandbox.io/s/l9vj1j7w2m

**Comment by TseWaiHo** [comment]
> I think your `url` has problem. Check you Server API.
> 
> See This demo: https://codesandbox.io/s/l9vj1j7w2m

Finally, I realize that this is just a specific behavior on Chrome, the error is actually caught, but chrome will always echo it out, and I can't find a way to mute it.
It is not axios problem, both traditional pattern and async pattern are correct, it is just that chrome make it ugly.

Chrome will echo out all request fail to console in red color, include the advertisements blocked by ADBLOCK.
