### ISSUE TITLE
Authorization cookie won't be sent using post method alias

### ISSUE THREAD

**Issue by gustavoaca1997** [axios/axios#1948]
#### Summary

Using request method alias `axios.post(url[, data[, config]])` won't send Authorization cookie to server. Instead, using axios API will do.

The server has CORS enabled.

#### Details
So if my axios request is like this:

```javascript
axios.post(
      `${constants.MY_SERVER_URL}/api/auth/logout`,
      {withCredentials: true}
)
```
The cookies sent to the server will be this (I'm using cookie-parser in the express server):
```json
{}
```

But if my request is:
```javascript
axios(`${constants.MY_SERVER_URL}/api/auth/logout`, {
        method: "post",
        withCredentials: true
})
```
The `cookies` object of the request will have Authorization cookie as expected.

#### Context

- axios version: v0.18.0
- express version (of the server): v4.0.36
- cookie-parser version (of the server): v1.4.1
- Environment: node v8.15.0, chrome  71.0.3578.98 (Official Build) (64-bit), Ubuntu 18.04

**Comment by wasnlosdu** [comment]
Hey @gustavoaca1997 , you have the answer right in your comment

> Using request method alias `axios.post(url[, data[, config]])` won't send Authorization cookie to server. Instead, using axios API will do.

Try to send it like that: 
```Javascript

axios.post(
      `${constants.MY_SERVER_URL}/api/auth/logout`,
        {}, // EMPTY OBJECT AS data
        {withCredentials: true}
)```

**Comment by dipunj** [comment]
@jkonze, Thanks you just saved my day!
