### ISSUE TITLE
Vue & ExpressJS Csrf Token forbidden 403

### ISSUE THREAD

**Issue by webspecialist** [axios/axios#1950]
- axios version: v0.18.0*
- Environment: node v8.9.1, chrome 71.0.3578.98 (Official version) (64-bit), windows 8.1*

I use VueJS (cli 3) & axios, and NodeJS - ExpressJS in the back-end. I am trying to secure my post user edit using CSRF token.

Vue View (edit user - focus to mySubmitEd):

````
<template>
  <div class="one-user">
    <h1>this user</h1>
    <h2>{{name}} - {{surname}} - {{ perm }}</h2>
    <h2>Edit</h2>
    <input type="text" v-model="name">
    <input type="text" v-model="surname">
    <input type="text" v-model="perm">
    <button @click="mySubmitEd">Edit</button>
    <button @click="mySubmit">Delete</button>
  </div>
</template>

<script>
import axios from 'axios'
import io from 'socket.io-client'
export default {
  name: 'one-user',
  data () {
    return {
      name: '',
      surname: '',
      perm: '',
      csrf: '',
      id: this.$route.params.id,
      socket: io('localhost:7000')
    }
  },
  mounted () {
    axios.get('http://localhost:7000/api/get-user/' + this.id)
      .then(res => {
        const data = res.data.user
        this.name = data.name
        this.surname = data.last_name
        this.perm = data.permalink
        this.csrf = res.data.csrfToken
        axios.defaults.headers.common['X-CSRF-TOKEN'] = this.csrf
      })
      .catch(error => console.log(error))
  },
  methods: {
    mySubmit () {
      const formData = {
        _id: this.id
      }
      axios.post('http://localhost:7000/api/delete-user', formData)
        .then(this.$router.push({ name: 'get-user' }))
        .catch(error => console.log(error))
    },
    mySubmitEd () {
      const formData = {
        _id: this.id,
        name: this.name,
        last_name: this.surname,
        permalink: this.perm,
        _csrf: this.csrf
      }
      console.log(formData._csrf)
      axios.post('http://localhost:7000/api/update-user', formData)
        .catch(error => console.log(error))
    }
  }
}
</script>
````

server.js file:

`...
const cookieParser  = require('cookie-parser');
const csurf         = require('csurf');
...
app.use(cookieParser());
const csrfProtection = csurf({ cookie: true });
app.use(csrfProtection);
...`

back-end controller which get the user:

`controller.getOneUser = function(req, res) {
  User.findOne({ _id: req.params.userId }).exec(function(err, user) {
    res.json({user, csrfToken: req.csrfToken()});
  });
};`

My errors in NodeJS-exress console:
`ForbiddenError: invalid csrf token`

My errors in browser:
`POST http://localhost:7000/api/update-user 403 (Forbidden)`

I don't know what is happened because I see in network tab(chrome) the csrf token is the same in the headers and what I send (example):

![csrf](https://user-images.githubusercontent.com/16546251/50757290-8099b800-1267-11e9-983c-5478ac241f78.jpg)

X-CSRF-TOKEN: PddyOZrf-AdHppP3lMuWA2n7AuD8QWFG3ta0
_csrf: "PddyOZrf-AdHppP3lMuWA2n7AuD8QWFG3ta0"

I don't know what I have miss here. I can't find where is the problem.

If you want more information please asked me to help you. I put here because I guess is axios problem, what do you think (what do to for debugging)?

**Comment by webspecialist** [comment]
I found that I need to pass the cookie but it fails. 
I put `withcredentials: true` but then I have cors problem. What can I do?

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Good luck!
