### ISSUE TITLE
`should support max redirects` mocha test fails

### ISSUE THREAD

**Issue by Flyrell** [axios/axios#1953]
Seems like the `should support max redirect` mocha test is failing right away.

The checks are done in follow-redirects dep. that has been updated 6 days ago. Might have something to do with that maybe? See recent [commits](https://github.com/follow-redirects/follow-redirects/commits/master) to follow-redirects

**Comment by jufemaiz** [comment]
Should this have been closed given the ongoing breakage may require reconsideration?
