### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by seewhy17** [axios/axios#1956]
I am using axios to send a post request in a Laravel 5.7 application. everything works well until for errors but as soon as response contains not error, I started getting:
**Uncaught (in promise) TypeError: Cannot read property 'data' of undefined**
on the line indicated in the cope snippet

```.catch( function (error) {
        console.log(error);
        const errs = error.response.data.errors; // on this line
   ...
}```

by the way am using webpack.js to compile

**Comment by seewhy17** [comment]
Sorry this isn't a Axios issue, the catch block caught some other logic error. Thanks

**Comment by IsidroMar95** [comment]
hey man, i have same problem, how did you solved it?

**Comment by seewhy17** [comment]
@IsidroMar95 Hi, that so long ago but my error was from someplace else within my code(the response block). try wrapping your code within a try..catch block to find the error. In my own case, I did something like so
```
axios.post('/user', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  })
  .then(function (response) {
    try{ // your own try...catch block to catch the error before axios ..catch
    console.log(response);
    catch(e) {} // your catch block
  })
  .catch(function (error) {
    console.log(error);
  });
```
I had my try..catch wrapping my cod within the response block.
I hope this helps you

**Comment by IsidroMar95** [comment]
Yes i realized that in the "then" block i was doing something wrong so i fixed it and everthing work fine.
thanks man, regards
