### ISSUE TITLE
Handling redirects

### ISSUE THREAD

**Issue by abhijithvijayan** [axios/axios#1969]
#### Summary

How to handle redirects to get the redirected URL?
I need to get the url after redirection using GET
#### Context

![](https://i.imgur.com/ef3hTpr.png)

- axios version: 0.18.0
- Environment: *: chrome 71, windows 10 Pro*

**Comment by yekver** [comment]
I think this may help you: https://github.com/axios/axios/issues/390

**Comment by abhijithvijayan** [comment]
@yekver I tried that. the value of the variable doesn't exist.
I'm running this on browser btw.

**Comment by chinesedfan** [comment]
> There is no library that **could** prevent the redirect. What you need to do on your server-side is distinguish between XHR requests and normal browser navigation requests

@abhijithvijayan Check https://github.com/axios/axios/issues/932#issuecomment-307390761.
