### ISSUE TITLE
Corrupted request url if baseUrl is relative

### ISSUE THREAD

**Issue by yekver** [axios/axios#1970]
#### Summary

```javascript
import axios from 'axios'
import MockAdapter from 'axios-mock-adapter';

const mock = new MockAdapter(axios);
const api = axios.create({ baseURL: '/api' });
axios.get('/method');
```

Request url will be `/api/api/method` instead of `/api/method`.

This is because of two reasons:
1. Function parameters mutation [here](https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/lib/core/dispatchRequest.js#L30) 
2. Twice call of `dispatchRequest()` (first is [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter/blob/ae6d72571c995592c5090f0429a609eb1b422dd5/src/handle_request.js#L42), second is [default adapter](https://github.com/axios/axios/blob/4f98acc57860721c639f94f5772138b2af273301/lib/core/Axios.js#L68))

As a result we will run  ```config.url = combineURLs(config.baseURL, config.url)``` twice and get wrong result.

#### Context

- axios version: *0.18.0*
- Environment: *node v11.6.0, chrome 71, macOS 10.14.2*

**Comment by yekver** [comment]
@emilyemorehouse can you look through this bug?

**Comment by chinesedfan** [comment]
It is a bug of axios-mock-adapter, https://github.com/ctimmerm/axios-mock-adapter/issues/185.

**Comment by leonardfactory** [comment]
Mh I think this is an axios bug, since this corrupts even request replay if using an interceptor in order to retry after getting a new accessToken with refreshToken. Cannot share the code right now, but simply `axios(config)` (with an error handler calling then `axios(error.config)` produces an error if `baseURL` is not absolute

**Comment by Alanscut** [comment]
@yekver could you provide complete test code? although I don't think this issue is related to axios.  and maybe https://github.com/ctimmerm/axios-mock-adapter/issues/185#issuecomment-507752627 has fixed this issue in axios-mock-adapter. Please try it.
