### ISSUE TITLE
Cannot consume axios typescript types using CommonJS

### ISSUE THREAD

**Issue by glenjamin** [axios/axios#1975]
#### Summary

There's a chance I'm doing something wrong here, but this seemed to be the best place to post.

I'm using the following typescript config to typecheck my NodeJS code in `.js` files without transforming it (and also to typecheck my browser code with `.ts` and transforms).

```json
{
  "compilerOptions": {
    "strict": true,
    "jsx": "preserve",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "target": "ES2017",
    "module": "CommonJS",
    "allowJs": true,
    "checkJs": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "typings/*"]
    }
  }
}
```

Given the following code in `app.js`
```js
const axios = require("axios");

const client = axios.create({
  timeout: 1000
});
```
I get this type error:
```
server/app.js:10:22 - error TS2339: Property 'create' does not exist on type 'typeof import(".../node_modules/axios/index")'.

10 const client = axios.create({
                        ~~~~~~
```

However with this code (which is wrong), I get no type errors
```js
const axios = require("axios").default;

const client = axios.create({
  baseURL: config.stravaBaseURL,
  timeout: 1000
});
```

#### Context

- axios version: 0.18.0
- Environment: Node 10.13.0, Typescript 3.2.4

**Comment by glenjamin** [comment]
Based on https://github.com/Microsoft/TypeScript/issues/2719 the solution appears to be to modify the typescript definition using `export =` syntax so that typescript knows it's really a commonjs module.

```diff
diff --git a/node_modules/axios/index.d.ts b/typings/axios/index.d.ts
index 403fd1a..a9848a9 100644
--- a/node_modules/axios/index.d.ts
+++ b/typings/axios/index.d.ts
@@ -1,3 +1,5 @@
+declare namespace Axios {
+
 export interface AxiosTransformer {
   (data: any, headers?: any): any;
 }
@@ -126,6 +128,8 @@ export interface AxiosStatic extends AxiosInstance {
   spread<T, R>(callback: (...args: T[]) => R): (array: T[]) => R;
 }
 
-declare const Axios: AxiosStatic;
+}
+
+declare const Axios: Axios.AxiosStatic;
 
-export default Axios;
+export = Axios;
```

**Comment by seth-seikosoft** [comment]
I'm running into this same issue.  Is this going to get bundled in/fixed/merged in soon?

**Comment by Nitive** [comment]
As far as I know after this change all import have to be changed from `import axios from 'axios'` to `import * as axios from 'axios'`. It will be breaking change for all users who don't have `allowSyntheticDefaultImports: true`

**Comment by dcsan** [comment]
I also hit this issue, and have to google these obscure and closed tickets to find a way to use axios with typescript. It seems the below is the wrong but works way to do it for now.

```
const axios = require('axios'); // no typings but everything still works

const axios = require('axios').default; // has typings and everything works
```

**Comment by mohd-akram** [comment]
A workaround is to add the following to a declaration file, eg. `declarations.d.ts`:

```typescript
declare module 'axios' {
  import Axios from 'axios/index';
  export = Axios;
}
```

**Comment by jasonsaayman** [comment]
Closing as I think the workaround mentioned above suffice for now. If this is still an issue please open a new issue.

**Comment by Jakemangan** [comment]
> import * as axios from 'axios'

Can you please update your NPM docs with this, I often forget this is required and have to Google how to get the typing's as require doesn't provide them. Can imagine its confusing for others also.

**Comment by NBreedlove** [comment]
I think I'm experiencing same issue (can't seem to just import/use axios).

I'm trying to implement the workaround, but I'm having problems doing so.

Do you just use this declaration file and import it?
