### ISSUE TITLE
Axios, https and self-signed certificates

### ISSUE THREAD

**Issue by andy194** [axios/axios#1976]
Hi,  I'm using axios from vue typescript over https to a web api that returns a self signed cert, but I can't get axios to ignore cert errors that are then reported by the browser.  I have tried suggestions from other posts (that have now been closed) as follows below but just get cert errors reported in the console and nothing on the page until I accept the cert from the console (chrome and FF, Edge won't do anything and needs Fiddler).

Here is the a snippet from main.ts...
```
axios.interceptors.request.use((config) => {
    const https = require('https');
    // https.globalAgent.options.rejectUnauthorized = false;  // doesn't work, options is undefined.
    config.httpsAgent = new https.Agent({ rejectUnauthorised: false }); 
    config.baseURL = 'https://addr/';
    return config;
},
    (err) =>
    {
        console.log('AXIOS Interceptor: Error returned: ' + err);
    });
```
This is from home.vue because the main,ts interceptor code doesn't work...
```
	async getInfo(siteCode: string): Promise<any> {

                const infoEndpoint = 'site-by-code/' + siteCode;
                const https = require('https');
                try
                {
                    const agent = new https.Agent({
                        rejectUnauthorized: false,
                    });
                    const response = await this.$http.get(this.serviceBase + infoEndpoint, { httpsAgent: agent });
                    return response.data;
                } catch (err) {
                    console.log(err);
                }
                return null;
           },
```
Cheers.

**Comment by jhfoo** [comment]
Same problem. Code works as-is in FF and not in Chrome and Edge.

**Comment by wasnlosdu** [comment]
Are you running your application on localhost or on some other domain?

You could try to disable cert errors on a Chrome level and not on your application level. The same works for edge.

Just google _{browsername} XMLHttpRequest ignore certificate errors_

This is not a good practice for production - so please watch out for that.

**Comment by getty23** [comment]
I've a very similar problem: I'd like to do a https request with self-signed certificates from my reactjs browser application. It works if I add the certificate to the browser certificate store but this is not the desired solution. I'd like to either pass the certificate directly in the request or ignore the security at all.

From what I've read so far I have the feeling that this is not possible in browser pages but just from node.js. Could you help here, please? Thanks

**Comment by jhfoo** [comment]
The problem is not with axios but with the certificate. Make sure your self signed has SAN included to make it work across browsers without needing to update the certificate store.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by getty23** [comment]
Thanks for your comment. Good point, I’ve not yet included SAN in my certificates, I’ll try it. 
Still I am wondering how to do the request with axios and the self signed certificate. As described above with an https agent and rejectUnauthorized or attach the certificate to the request? Or is there any other best practice? 
It is just no option to attach the certificate manual to the certificate store, it must work automatically from my reactjs web app. 
Thanks for your support

**Comment by jhfoo** [comment]
Once your browser accepts the self-signed cert and loads the initial page axios should not complain. IIRC rejectUnauthorized is a node.js thing, not available on the browser.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by getty23** [comment]
Though the point is that the user needs to accept the self-signed certificate manually in the browser, right? Or is there a way to ignore or pass a self-signed certificate automatically with a request? This is the crucial question for me ;). Thanks

**Comment by jhfoo** [comment]
It is by design that the user manually - and is made to jump through hoops - to proceed through self-signed certs. Self-signed certs give users a false sense of security and should only be used in dev environments.

You should be asking yourself why you are bypassing a security measure.
________________________________

**Comment by jasonsaayman** [comment]
I doubt we should be removing the need to validate SSL or have a bypass for this. When developing locally and using a self-signed certificate you would only need to add this certificate to the browser once and it will be remembered for all future requests.

Should you be using a self-signed certificate on your web host I would suggest you look into a good free SSL provider, else your users will also need to whitelist the SSL certificate. Either way, this is not an Axios issues.

**Comment by getty23** [comment]
Thanks for your replies. This was exactly what I was expecting and it helps me to clarify things.
