### ISSUE TITLE
Get nice loggable data on error

### ISSUE THREAD

**Issue by alisherafat01** [axios/axios#1977]
Hi, i want to log the request and response data but log data are too long including binary data of uploading file and it's making crash log files in my project.
is there any short loggable data (summary of request and response)?

any way, how can i figure out which error is thrown by axios?  is there any flag for error objects?
i'm catching all errors in my app in one place and i want to figure out which one is thrown by axios.
Thanks.

**Comment by chinesedfan** [comment]
> is there any short loggable data (summary of request and response)?

Logging is out of the scope of axios. But you can find some useful logger [here](https://github.com/axios/axios/blob/master/ECOSYSTEM.md) or write by yourself.

> how can i figure out which error is thrown by axios? is there any flag for error objects?

`error.isAxiosError`. Refer to the source file, enhanceError.js, of axios.
