### ISSUE TITLE
Losing context inside interceptor callback

### ISSUE THREAD

**Issue by super2ni** [axios/axios#1978]
#### Summary
Hello, I have trouble using Axios interceptors. I am creating an instance of Axios and try to raise some code when I encounter a 401 error.

Sadly, in the reject callback, I'm losing all my context. In the lower code, the "store" variable is undefined. "this" is also undefined. Could anyone help me and tell me what have I done wrong?

Thank you,
Denis

```
import axios from 'axios';
import AuthService from "@/services/auth.service";
import store from '@/store';

const msalAuthService = new AuthService();
const axiosForGraph = axios.create({
    baseURL: 'https://graph.microsoft.com/v1.0'
});

const errorInterceptor = axiosForGraph.interceptors.response.use(response => response, (error) => {
    debugger;
    if (error.response.status === 401) {
        store.commit("graph/setAccessToken", null);
    }

    return Promise.reject(error);
});
```

#### Context

- axios version: 0.18.0
- Environment: VueJS SPA + VueX

**Comment by chinesedfan** [comment]
Have you printed by `console.log`? If debugging with Chrome, it is normal that can't see variables belong to upper context. Refer [stackoverflow.com](https://stackoverflow.com/questions/28388530/why-does-chrome-debugger-think-closed-local-variable-is-undefined).
