### ISSUE TITLE
how to execute the jsonp callback?for example : https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/?wd=a

### ISSUE THREAD

**Issue by PineappleLB** [axios/axios#1980]
`jsonp(`https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/?wd=${queryString}`,{}, (err, data) => {
        if(err){
          console.error(err)
          return;
        }
        console.log(data);
      })`
the exception is 
Uncaught TypeError: Cannot read property 'sug' of undefined

**Comment by fabioricali** [comment]
https://github.com/AdonisLau/axios-jsonp
