### ISSUE TITLE
httpsAgent does not work in combination with an HTTP-proxy.

### ISSUE THREAD

**Issue by Borewit** [axios/axios#1981]
#### Description
I try to setup HTTPS-session using Axios which works fine through Fiddler.
This fails by the way on the current stable release [v0.18.0](https://github.com/axios/axios/releases/tag/v0.18.0), I guess this is issue #925, fixed in #959.

As soon as I remove Fiddle, it no longer works. I suspect that it is, because the connection is pooled by Fiddler. So in order to make it work without the Fiddler proxy, I inject httpsAgent to keep the connection alive e.g.:
```JavaScript
import * as http from 'https';
import * as https from 'https';

const Fiddler = {
  host: '127.0.0.1',
  port: 8888
};

this.axios = Axios.create({
   proxy: Fiddler
   httpAgent: new http.Agent({keepAlive: true}),
   httpsAgent: new https.Agent({keepAlive: true, rejectUnauthorized: false})
````

I can't get it work with the https-agent assigned, not with a proxy:

#### Stacktrace:
```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new ClientRequest (_http_client.js:118:11)
    at Object.request (http.js:41:10)
    at RedirectableRequest._performRequest (node_modules\follow-redirects\index.js:186:24)
    at new RedirectableRequest (node_modules\follow-redirects\index.js:69:8)
    at Object.wrappedProtocol.request (node_modules\follow-redirects\index.js:363:14)
    at dispatchHttpRequest (node_modules\axios\lib\adapters\http.js:180:25)
    at new Promise (<anonymous>)
    at httpAdapter (node_modules\axios\lib\adapters\http.js:20:10)
    at dispatchRequest (node_modules\axios\lib\core\dispatchRequest.js:59:10)
```

Not without a proxy.

#### Context
- axios version: *e.g.: (v0.19.0-beta.1)[https://github.com/axios/axios/releases/tag/v0.19.0-beta.1]*
- Environment: *e.g.: node v10.13.0, Windows 10*

#### Related issues
* #1885 (that one using a socks proxy, therefor I consider this one to be different)

**Comment by jasonswearingen** [comment]
I got here by searching for a fix on https proxy failures (```EPROTO``` error) 

I'm not sure if it's related, but but i know there are/were bugs with setting your own httpsAgent too (to do things like setting keepalive)

**Comment by JitixPhotobox** [comment]
I have opened a PR to fix this issue : https://github.com/axios/axios/pull/2426

**Comment by JitixPhotobox** [comment]
The PR has been merged. Waiting for a new release.

**Comment by elegisandi** [comment]
waiting for the new release :)

**Comment by arpitjain-in** [comment]
Is this issue resolved and available in latest release? Please share some update on this.

**Comment by alilland** [comment]
same :(

**Comment by yasuf** [comment]
see https://github.com/axios/axios/pull/2502, this will be fixed once that version is out, thank you for your patience

**Comment by chinesedfan** [comment]
Closed as released.
