### ISSUE TITLE
Content-Type wont change

### ISSUE THREAD

**Issue by razdahan** [axios/axios#1982]
Hi i have this code 
**      return axios.get(`${config.url}/rides/search?access_token=`+Vue.prototype.$store.state.data.token,queryString.stringify({
        destination:"word1"
      }),{
        headers:{
          'Content-Type':'application/x-www-form-urlencoded'
        }
      }).then(response => {
        console.log(response.data)
        return response.data
      }).catch(err=>
      {
        console.log(err.response.data)
      }
      );**

and the content type is not changing,
i did change him in 'Content-Type':'application/x-www-form-urlencoded'
please help me!

**Comment by mayank-mittal** [comment]
Hi, There are 2 ways to go about it.
1. ```
axios.get(`${config.url}/rides/search`,{
params: {
access_token: Vue.prototype.$store.state.data.token,
destination:"word1"
},
headers:{
'Content-Type':'application/x-www-form-urlencoded'
}
})
``` - The second parameter should be config not the data parameters

2. axios({
 method: 'GET',
url: `${config.url}/rides/search`,
params: {
access_token: Vue.prototype.$store.state.data.token,
destination:"word1"
},
headers:{
'Content-Type':'application/x-www-form-urlencoded'
}
})

**Comment by razdahan** [comment]
Hi thnx u helped me very much!

**Comment by mayank-mittal** [comment]
Close this issue, if it resolved the issue.
