### ISSUE TITLE
Request Authorization Header Doesn't Match On Backend Log

### ISSUE THREAD

**Issue by firmantr3** [axios/axios#1988]
#### Summary

I'm making simple get request from my vuejs app that includes Authorization header token, if i check on the chrome devtools, the token is right, but when i log it on the backend API (Laravel), the request Authorization header is completely different. The problem doesn't occur when i'm using Postman.

Here is my axios config:

```javascript
// Request interceptor
axios.interceptors.request.use(request => {
  request.baseURL = API_URL

  const token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcXl0YW5leHRhcGkudGVzdFwvY2hlY2tsaXN0LWFwaVwvbG9naW4iLCJpYXQiOjE1NDkxOTkyNDEsImV4cCI6MTU1MTc5MTI0MSwibmJmIjoxNTQ5MTk5MjQxLCJqdGkiOiJxb2V0dHl4VzQ0ZnJSeFBsIiwic3ViIjoiMTYwNDUzNTMiLCJwcnYiOiI4OTlmOGRmYjQzOWMxMDUyNmVhYzU1YThmM2I4OGMxNjVmMGNmNmQ0In0.gKPjwJkBUesgJT5spB-tIzjMZeviWryZyxICmm89AfY'
  request.headers.common['Authorization'] = `Bearer ${token}`

  const locale = APP_LOCALE
  if (locale) {
    request.headers.common['Accept-Language'] = locale
  }

  return request
})
```

The request code:

```javascript

  async fetchUser () {
    try {
      const { data } = await axios.get('/user')
      console.log(data)
    } catch (e) {
      console.log(e)
    }
  },
```

Chrome devtools network debug:
```
Request URL: https://qytanextapi.test/checklist-api/user
Request Method: GET
Status Code: 403 
Remote Address: 127.0.0.1:443
Referrer Policy: no-referrer-when-downgrade
access-control-allow-credentials: true
access-control-allow-origin: http://localhost:8080
cache-control: no-cache, private
content-encoding: gzip
content-type: application/json
date: Sun, 03 Feb 2019 13:33:25 GMT
server: nginx/1.14.2
status: 403
vary: Accept-Encoding, Origin
x-powered-by: PHP/7.3.1
x-ratelimit-limit: 60
x-ratelimit-remaining: 58
Provisional headers are shown
Accept: application/json, text/plain, */*
Accept-Language: id
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcXl0YW5leHRhcGkudGVzdFwvY2hlY2tsaXN0LWFwaVwvbG9naW4iLCJpYXQiOjE1NDkxOTkyNDEsImV4cCI6MTU1MTc5MTI0MSwibmJmIjoxNTQ5MTk5MjQxLCJqdGkiOiJxb2V0dHl4VzQ0ZnJSeFBsIiwic3ViIjoiMTYwNDUzNTMiLCJwcnYiOiI4OTlmOGRmYjQzOWMxMDUyNmVhYzU1YThmM2I4OGMxNjVmMGNmNmQ0In0.gKPjwJkBUesgJT5spB-tIzjMZeviWryZyxICmm89AfY
Origin: http://localhost:8080
Referer: http://localhost:8080/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
```

The API debug output:

```php
<?php
array(
    'method' => 'GET',
    'header' => array(
        'accept-encoding' => array(
            0 => 'gzip, deflate, br'
        ),
        'referer' => array(
            0 => 'http://localhost:8080/'
        ),
        'user-agent' => array(
            0 => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36'
        ),
        'accept-language' => array(
            0 => 'id'
        ),
        'authorization' => array(
            0 => 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcXl0YW5leHRhcGkudGVzdFwvaW50ZXJuYWwtYXBpXC9sb2dpbiIsImlhdCI6MTU0Mzc2ODQxMCwiZXhwIjoxNTQ2MzYwNDEwLCJuYmYiOjE1NDM3Njg0MTAsImp0aSI6InhrQlB5d0h2OWd4VzZ3dGwiLCJzdWIiOiIxNjA0NTM1MyIsInBydiI6IjY2NDgyYjZkNjMzOTdiYjkyZjQ3NzQwNDMyN2RlNTE5ZGYzZmNlZmEifQ.z29P75imDTTmtdiBV6LEuXIW2h_sAW1eDt_PhHRtJ-k'
        ),
        'origin' => array(
            0 => 'http://localhost:8080'
        ),
        'accept' => array(
            0 => 'application/json, text/plain, */*'
        ),
        'host' => array(
            0 => 'qytanextapi.test'
        ),
        'content-length' => array(
            0 => ''
        ),
        'content-type' => array(
            0 => ''
        )
    ),
    'url' => 'https://qytanextapi.test/checklist-api/user'
);
```

The API always getting that same token even when i change the Authorization header on the axios. Please help, is it axios bug, or am i doing it wrong?

#### Context

- axios version: 0.18.0
- Environment: node v11.6.0, Laravel 5.5, chrome 72.0.3626.81 (Official Build) (64-bit), Manjaro Linux 18

**Comment by grumblerchester** [comment]
The issue does not seem to be related to axios.
What headers are required (by your server) to be presented in a request?
Can you please perform curl request below and provide results.

```
curl -X GET \
  https://qytanextapi.test/checklist-api/user \
  -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcXl0YW5leHRhcGkudGVzdFwvY2hlY2tsaXN0LWFwaVwvbG9naW4iLCJpYXQiOjE1NDkxOTkyNDEsImV4cCI6MTU1MTc5MTI0MSwibmJmIjoxNTQ5MTk5MjQxLCJqdGkiOiJxb2V0dHl4VzQ0ZnJSeFBsIiwic3ViIjoiMTYwNDUzNTMiLCJwcnYiOiI4OTlmOGRmYjQzOWMxMDUyNmVhYzU1YThmM2I4OGMxNjVmMGNmNmQ0In0.gKPjwJkBUesgJT5spB-tIzjMZeviWryZyxICmm89AfY' \
  -H 'cache-control: no-cache'
```

**Comment by firmantr3** [comment]
> What headers are required (by your server) to be presented in a request?

Hi, the headers required by my server is just authorization

> Can you please perform curl request below and provide results.
> 
> ```
> curl -X GET \
>   https://qytanextapi.test/checklist-api/user \
>   -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcXl0YW5leHRhcGkudGVzdFwvY2hlY2tsaXN0LWFwaVwvbG9naW4iLCJpYXQiOjE1NDkxOTkyNDEsImV4cCI6MTU1MTc5MTI0MSwibmJmIjoxNTQ5MTk5MjQxLCJqdGkiOiJxb2V0dHl4VzQ0ZnJSeFBsIiwic3ViIjoiMTYwNDUzNTMiLCJwcnYiOiI4OTlmOGRmYjQzOWMxMDUyNmVhYzU1YThmM2I4OGMxNjVmMGNmNmQ0In0.gKPjwJkBUesgJT5spB-tIzjMZeviWryZyxICmm89AfY' \
>   -H 'cache-control: no-cache'
> ```

Heres myy API response:

```
{"nik":"16045353","nama":"FIRMAN TARUNA NUGRAHA (FIRMAN)","email":"firmantr3@gmail.com"}
```

That means the authorization header is successfully verified

**Comment by SubashManian** [comment]
In my code Authorization Header is not Working 

`var data = new FormData() 
    data.append("userId",'833')
    data.append("newPassword","zxcvbnm")
    data.append("confirmPassword","zxcvbnm")
    axios.post('url',data,{
      headers:{
        Authorization:"lGzKd4TJqN",
      },
    }).then((res)=>{
      console.log(res)
    }).catch((err)=>{
      console.log(err)
    })`

**Comment by grumblerchester** [comment]
@firmantr3 As I understand the issue is 
>when i log it on the backend API (Laravel), the request Authorization header is completely different
Does your backed accepts auth header (and return result) when you perform axios request from your original post?
What is in your logs when you do request by curl?

**Comment by firmantr3** [comment]
> @firmantr3 As I understand the issue is
> 
> > when i log it on the backend API (Laravel), the request Authorization header is completely different
> 
> Does your backed accepts auth header (and return result) when you perform axios request from your original post?

yes, my backend accepts all header and return result when i perform axios request, but the authorization header value is not equal between axios request and backend, causing the authentication fails. Is it CORS problem? I'm using [laravel-cors](https://github.com/barryvdh/laravel-cors) package with this configuration:

```php
return [
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedOriginsPatterns' => [],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
];
```

> What is in your logs when you do request by curl?

the curl command:

```
curl -X GET \
  https://qytanextapi.test/checklist-api/user \
  -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcXl0YW5leHRhcGkudGVzdFwvY2hlY2tsaXN0LWFwaVwvbG9naW4iLCJpYXQiOjE1NDk2OTM3OTIsImV4cCI6MTU1MjI4NTc5MiwibmJmIjoxNTQ5NjkzNzkyLCJqdGkiOiI5aUVmMWtKRnlSVUJnZTJiIiwic3ViIjoiMTYwNDUzNTMiLCJwcnYiOiI2NjQ4MmI2ZDYzMzk3YmI5MmY0Nzc0MDQzMjdkZTUxOWRmM2ZjZWZhIn0.-PtCLxyX7HRJ08v36LBgIW--rCYNCOjX1HVAScsupho' \
  -H 'cache-control: no-cache' -k
```

then i got this on my log:

```php
array(
    'method' => 'GET',
    'header' => array (
        'cache-control' => array (
            0 => 'no-cache',
        ),
        'authorization' => array (
            0 => 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcXl0YW5leHRhcGkudGVzdFwvY2hlY2tsaXN0LWFwaVwvbG9naW4iLCJpYXQiOjE1NDk2OTM3OTIsImV4cCI6MTU1MjI4NTc5MiwibmJmIjoxNTQ5NjkzNzkyLCJqdGkiOiI5aUVmMWtKRnlSVUJnZTJiIiwic3ViIjoiMTYwNDUzNTMiLCJwcnYiOiI2NjQ4MmI2ZDYzMzk3YmI5MmY0Nzc0MDQzMjdkZTUxOWRmM2ZjZWZhIn0.-PtCLxyX7HRJ08v36LBgIW--rCYNCOjX1HVAScsupho',
        ),
        'accept' => array (
            0 => '*/*',
        ),
        'user-agent' => array (
            0 => 'curl/7.63.0',
        ),
        'host' => array (
            0 => 'qytanextapi.test',
        ),
        'content-length' => array (
            0 => '',
        ),
        'content-type' => array (
            0 => '',
        ),
    ),
    'url' => 'https://qytanextapi.test/checklist-api/user',
)
```

The authorization header is equal between curl and backend.

**Comment by chinesedfan** [comment]
@firmantr3 Because in Chrome dev tools, the token is right. It seems more like a backend problem. Sorry I am not a Laravel expert. Maybe you can replace the token with a simple word and try to find out the cause.
