### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by ESASAH** [axios/axios#1989]
Hi,
When I try 
```
axios.get(this.$server+'/transco/gettable/COREPDMINTERVALTYPO_INPUT')
      .then(function (response) {
        // handle success
        console.log(response);
      })
      .catch(function (error) {
        // handle error
        console.log(error);
      })
      .then(function () {
        // always executed
      });
```
I get error 500 :  
GET http://localhost:8081/transco/gettable/TABLE_TEST 500 (Internal Server Error)

But if I do it directly (http://localhost:8081/transco/gettable/TABLE_TEST) in my browser it works.

I don't know why can you help me ?
thx

**Comment by thib92** [comment]
This is not an issue with Axios.
When entering the URL directly in the browser, your browser adds a bunch of headers. To see them, open your browser dev tools, under the "network" tab, refresh and the first request will be the one you are interested in. I'd recommend checking the logic and the logs for your backend to see where it could fail.

**Comment by ESASAH** [comment]
thx for your help.

With my browser I have this Request header : 
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost:8081
Save-Data: on
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```

With the code : 
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost:8081
Origin: http://localhost:8080
Referer: http://localhost:8080/
Save-Data: on
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```
My backend : 
```
routertransco.get('/gettable/:tablename', function(req, res, next){
  let table = []
  let returnValue = {}
  let inputTable = "TRANSCO."+req.params.tablename
  console.dir( )
  sql.connect(config).then(pool =>{
    return pool.request()
    .query('SELECT * FROM '+inputTable)
  }).then(result =>{
    console.dir(result)
    sql.close()
    result.recordsets.forEach((tab)=>{
      tab.forEach((elms)=>{
        table.push(elms)
      })
    })
    res.status(200).json(table)
  }).catch(err =>{
    console.dir(err)
    sql.close()
    returnValue["Response"] = "error"
    res.status(500).json(returnValue)
  })
})
```

I don't see what causes error 500 with the browser.
thx

**Comment by josemazu** [comment]
I read other pages, and the problem is the Controller, not axios or anything, is only the controller, but i ca't solve the error.

**Comment by agamyrat301** [comment]
dwqdqdwq

**Comment by agamyrat301** [comment]
i also have same problem

**Comment by thib92** [comment]
Once again, if you’re getting a 5xx error code, it’s due to your backend code. If it’s different from typing the URL by hand in the browser, check your backend code regarding request headers, cookies, etc.
This has nothing to do with Axios.

**Comment by MohAbdelhamed** [comment]
The below **worked** with me:
const deptsURL = "http://localhost:8099/ords/hr/hrm/depts";
var vAttributes = {};
            vAttributes = {
              departmentid: model.attributes[model.idAttribute]
              , departmentname: $("#newDepartName").val()
              , managerid: 100
              , locationid: 1700
            };
const ops = {
              method: 'POST',
              headers: { 'content-type': 'application/json' },
              data:  JSON.stringify(vAttributes) ,
              url: deptsURL
            };
axios( ops).then((res) => {
              console.log("post response: " + res);
            }).catch(function (error) {
              console.log("post error: " + error);
            });
