### ISSUE TITLE
TypeError: rows.map is not a function 

### ISSUE THREAD

**Issue by scheung38** [axios/axios#1991]
Using within React componentDidMount() lifecycle at localhost:3001: 

```
  componentDidMount() {
        axios.get('http://localhost:3000/client')
            .then(res => {
                const rows = res.data
                this.setState({rows})
                console.log("res.data is: ", this.state.rows)
            })
            .catch(err => {
                console.error("client error : ", err)
            })
    }
```

This is my example data from backend http://localhost:3000/client

{
    "status": 200,
    "statusText": "OK",
    "data": [
        {
            "id": 1,
            "name": "Mr CHESA",
            "shortName": "CHES",
            "disabled": false,
            "creationDate": "2018/01/10",
            "subscriptionStart": "2018/01/10",

Not sure why

   ```
  9 | var rowIdGetter = function rowIdGetter(getRowId, rows) {
     10 |   if (!getRowId) {
> 11 |     var map = new Map(rows.map(function (row, rowIndex) {
   12 |       return [row, rowIndex];
   13 |     }));
   14 |     return function (row) 
```

I am also using https://devexpress.github.io/devextreme-reactive/react/grid/ to render tables.

Anyone?

**Comment by mapolin** [comment]
This is probably because react does a render before the componentDidMount lifecycle method is called.

Your questions seems better fit for stackoverflow, no the axios issues board.

**Comment by grumblerchester** [comment]
Another reason may be the fact that you do _the async request_ in your `componentDidMount`. So the expected data is not received yet in the moment when you try to access it.
Anyway the answer cannot be provided without [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve).
Please consider updating the question or closing the issue.
