### ISSUE TITLE
How can I use the statusCode from data instead of response? 

### ISSUE THREAD

**Issue by ChunAllen** [axios/axios#1995]
I'm calling an API that defines the statusCode from data instead of the response code:
```
{
  data: {
     statusCode: 422,
     message: "User's not found"
  }, 
 status: 200
}
```

In my axios get request it's getting the status code from the status instead in data. 
```
return axios.get(`${process.env.BASE_URL}/users`)
      .then(response => {
        console.log(response);
      }).catch(err => {
        console.log(err.message);
      });
```

I'm getting the response but it should go to catch since it's 422.

**Comment by dpopp07** [comment]
That seems like an issue with the API. They should be sending an actual HTTP status code, not just setting it in the body. It's not the job of `axios` to parse the body and look for a status code under an arbitrary key.

**Comment by heyamykate** [comment]
Closing this since it's not an issue with axios itself.
