### ISSUE TITLE
missing token ‘x-auth’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel

### ISSUE THREAD

**Issue by hamyarwoo** [axios/axios#1998]
i want to get data with post method from axios package and xampp sever, i have an error when work with firefox :

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1/aftab/inventory3/v1/repository/all. (Reason: missing token ‘x-auth’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).[Learn More] Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1/aftab/inventory3/v1/repository/all. (Reason: CORS request did not succeed)

but when test it in chrome it work correctly and i don't have any error ,

my axios request code is:

console.log("iman");
        let page = 1;
        let config =
            {
                'Content-Type': 'application/x-www-form-urlencoded',
                'x-auth': localStorage.getItem("token"),
                'Access-Control-Allow-Origin': '*'
            };
        let data = {page: page};
        if (localStorage.getItem("token")) {
            await axios({
                method: "post",
                url: "http://127.0.0.1/aftab/inventory3/v1/repository/all",
                data: data,
                headers: config
            }).then(function (response) {
                console.log(response);
            }).catch(function (error) {
                if (error.response) {
                    // The request was made and the server responded with a status code
                    // that falls out of the range of 2xx
                    console.log(error.response.data);
                    console.log(error.response.status);
                    console.log(error.response.headers);
                } else if (error.request) {
                    // The request was made but no response was received
                    // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
                    // http.ClientRequest in node.js
                    console.log(error.request);
                } else {
                    // Something happened in setting up the request that triggered an Error
                    console.log('Error', error.message);
                }
                console.log(error.config);
            });
        } else {
            localStorage.removeItem("token");
            // this.history.push('/log/in');
        }

in firefox console network, only option method was sent and after it we dont have any request but in the chrome it work correct and we have a post method request after option method

**Comment by bkawan** [comment]
Try this beta version of axios 
https://github.com/axios/axios/tree/v0.19.0-beta.1
It fixes in my case.

```
 "axios": "0.19.0-beta.1",
```

**Comment by hamyarwoo** [comment]
> 
> 
> Try this beta version of axios
> https://github.com/axios/axios/tree/v0.19.0-beta.1
> It fixes in my case.
> 
> ```
>  "axios": "0.19.0-beta.1",
> ```

this is not worked for me

**Comment by chinesedfan** [comment]
> Reason: missing token ‘x-auth’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel

It should not a bug of axios. I suggest you check why http://127.0.0.1/aftab/inventory3/v1/repository/all didn't return x-auth in FF, but return in Chrome. Maybe localstorage data are different.

**Comment by AllainPL** [comment]
Could you show us your response headers from the `OPTIONS` request? Or maybe you solved it on your own :)?

btw `Access-Control-Allow-Origin` is a header that server returns to the browser, you should not be sending it TO the server ;)

**Comment by Kshopper93** [comment]
Did you fix this issue? Had the same error on.

Firefox v. 66.05
axios v. 0.18.0
OS: Windows 10

Server allowed all Origin and Headers for testing

<customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
        <add name="Access-Control-Allow-Headers" value="*" />
        <add name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS" />
</customHeaders>

**Comment by hamyarwoo** [comment]
when you build your project this problem is solved

**Comment by Kshopper93** [comment]
I build my app with 'npm run serve' and run it on a iis server. Still the same error. 
![image](https://user-images.githubusercontent.com/7681603/57832023-e5859180-77b6-11e9-91ef-7705db359c22.png)

**Comment by Kshopper93** [comment]
Found the error but how can i fix this? 
I have a custom header variable named Api-Key when i remove this all works fine but i need this key :/

![image](https://user-images.githubusercontent.com/7681603/57837343-eb816f80-77c2-11e9-8a16-f2fae8b57928.png)

**Comment by chinesedfan** [comment]
@Kshopper93 Don't set `Access-Control-Allow-Methods/Access-Control-Allow-Headers` to `*` simply. In your case, use a certain value, `Access-Control-Allow-Headers: Api-Key`. Refer [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Headers).

**Comment by Kshopper93** [comment]
@chinesedfan Dammm you saved my day :D Changed my Access-Control-Allow-Headers on server to->

`<add name="Access-Control-Allow-Headers" value="*,Api-Key" />`

and it works
