### ISSUE TITLE
Sending POST request catches error but no error occured

### ISSUE THREAD

**Issue by MaTToX3** [axios/axios#1999]
I have an application in production, which is used by multiple users - they always access the app from the mobile phone (in this case it's from **Android 6.0.1 with Chrome Mobile 71.0.3578**). Inside the app, they have to take a photo of specific thing and upload it. I created a Vue component with simple INPUT which on click launches Photo app or opens gallery to pick image. After that, the image is being processed and stored on the server with AXIOS. And here is where AXIOS catches me an error but no error has occurred.

```
axios.post('/stations/' + this.controlPoint.station_id + '/controls/' + this.controlPoint.id + '/entries', {
       point: this.controlPoint,
       image: image,
       imageDate: lastChanged,
       entry: this.controlPoint.this_week_entry
}, {timeout: 999999}).then(res => {
      this.controlPoint.entry_id = res.data.entry.id;
      this.controlPoint.entryStatus = res.data.entry.status;
      this.uploading = false;
}).catch(err => {
      this.uploading = false;
      console.log(err);
      alert("Napaka pri nalaganju slike - prosimo, poskusite ponovno");

      // TODO: Probably not needed?
       axios.post('/api/log-error', {
            message: 'Error uploading entry Image',
            exception: err,
            station: this.controlPoint.station_id,
            file: 'ControlPoint.vue'
       });
});
```

And the error that is logged with separate POST request from catch block:

```
Message
Error uploading entry Image

Level
ERROR

exception
[]  <--- What is this ???

file
ControlPoint.vue

station
21
```

The problem is I am unable to reproduce the error in any way so it is really hard to debug it. The backend is laravel and nothing is shown in laravel.log. 

I have read that if an error occurs in "then" block, it would also catch an error inside catch block but I have such a simple code in "then" block that is almost impossible that anything happens.

The user just refreshes the page after each upload and of course, the image is safely and correctly stored on the server.

What else to check? :) 

Thank you in advance!

**Expected behavior, if applicable**
Should not catch an error - I lock the image upload button after the success but in this case user has to reload the page to see that image is actually succesfully stored on the server.

**Environment:**
 - Axios Version 0.18.0
 - OS: Android 6.0.1
 - Browser Chrome Mobile 
 - Browser Version 71.0.3578
 - Additional Library Versions Vue 2.5.17

**Comment by MaTToX3** [comment]
Bonus:
Same App on my device works fine:
    * Browser Version 71.0.3578 (same version)
    * OS: Android 8.0.0

**Comment by adamasantares** [comment]
I have similar problem, I'm getting exception by the catch method, but error is empty object {}.
What does it mean? I have no idea
