### ISSUE TITLE
Not work on ios devices, different behavior on android and ios.

### ISSUE THREAD

**Issue by Eggplant-Cui** [axios/axios#2001]
React navive app ,using webview to visit vue project
Works well on android devices,
on ios device, request was rejected,  reject is:
{ "line": 16, "column": 24, "config": { "transformRequest": {}, "transformResponse": {}, "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "headers": { "Accept": "application/json, text/plain, */*", "X-Zlhy-Authorization": "$2y$10$8GRK7RbKbXh9MjANBHJ4l.AmVVIszRyVav7yJ9.D2TQVKdLheYFPK" }, "method": "get", "url": "http://api.zlhuiyun.com/statis/statistic/index" }, "request": {} }

在ios的rn项目里，用webview访问vue写的页面，请求被reject，同样的代码在androd设备上运行良好。
reject信息如上。

anyone knows why?

code:

this.axios({
        method: 'get',
        headers:{"X-Zlhy-Authorization":token,'Access-Control-Allow-Headers': 'X-Zlhy-Authorization'},
        url: 'http://api.zlhuiyun.com/statis/statistic/index'
      }).then(function (response) {
        console.log('res:',response);
        ...},(reject)=>{
       console.log('reject:',reject);
       }

**Environment:**
 - Axios Version [0.18.0]
 - OS: [iOS 11.0]
 - Browser [Chrome, Safari]
 - Browser Version [unkown]
 - Additional Library Versions [React Native 0.58.0]

**Comment by chinesedfan** [comment]
Looks like due to ATS(App Transport Security). Because your endpoint(http://api.zlhuiyun.com/statis/statistic/index) doesn't support HTTPS.

**Comment by Alanscut** [comment]
hi @Eggplant-Cui ， have you solved this issue?

**Comment by Eggplant-Cui** [comment]
change url to https

**Comment by Alanscut** [comment]
Thanks!

**Comment by chinesedfan** [comment]
@Alanscut Glad to see that finally axios has an active maintainer. You closed so many issues I commented. If possible, you can also invite me as a collaborator.
