### ISSUE TITLE
How to upload file + form data?

### ISSUE THREAD

**Issue by itsGabriel** [axios/axios#2002]
I have this code that works perfectly to send the file to the server, but I'm trying to send all form with his fields contents. 
Example: in the same form there is a field with a **name** and of course with this form file. How could I send the **name** and the **formdata** in the same request?
```
            this.axios.post(process.env.API_URL+'/buys/xml', this.selectedFile, { headers: { 'Authorization': 'Bearer ' + localStorage.getItem('token'), 'content-type': 'multipart/form-data boundary=' + Math.random().toString().substr(2)}})
            .then((response) => {
                console.log(this.selectedFile.xml)
            })
            .catch(function (error) {
                console.log(error);
            });
```
The input field:
`<input type="text" class="form-control" v-model="name" placeholder="Ex: Name">`

when i try to send the `this.selectedFile, this.name ` doesn't work properly

**Comment by heyamykate** [comment]
When you tried to send `this.selectedFile` and `this.name`, did you put it in an object? 
Typically I would post data to an API formatted as follows:
`{ file: this.selectedFile, name: this.name }`
This assumes that your API endpoint is expecting input data with those field names.

**Comment by urosran** [comment]
@itsGabriel 
Form data is just a dict where you can store a key and a value thus: 
On client: 
```
const photoFormData = new FormData();
    // dict of all elements
    photoFormData.append("avatar", file);
    photoFormData.append("email", this.state.email);
    photoFormData.append("name", this.state.name);
```

axios request: 
```
axios({
      method: "POST",
      url: "http://localhost:5001/photo",
      data: photoFormData,
      headers: {
        'Content-Type': 'multipart/form-data; boundary=${form._boundary}'
      }
    })
```
On the server: 
```
app.post("/photo", function(req, res, next) {
  console.log(req.body.email)
```
