### ISSUE TITLE
Data is undefined

### ISSUE THREAD

**Issue by Bradzer** [axios/axios#2004]
**Describe the bug**
After creating an axios request `apiCall` with the property `data` set with a plain object, and then logging `apiCall.defaults`, the property `data` is still `undefined`.

**To Reproduce**
```js
let apiCall = axios.create({
    baseURL: 'https://gateway-lon.watsonplatform.net/text-to-speech/api/v1/synthesize/',
    headers: {
        'Accept': 'audio/wav',
        'Content-Type': 'application/json'
    },
    data: {"text": "hello world"}
})
console.log(apiCall.defaults)
```

**Expected behavior**
I expected to see my plain object `{"text": "hello world"}` in data instead of `undefined`.

**Environment:**
 - Axios Version [0.18.0]
 - OS: [Linux Mint 19.1 Tessa]
 - Additional Library Versions [React 16.6.3, React Native 0.58.4]

**Comment by ccpdouglas** [comment]
I tried recreating your issue, the data property was correct in my instance.
Could you provide more detail and context? Is it running in browser or node?

Example of it working:
https://jsbin.com/dolakeqite/1/edit?html,js,console,output

**Comment by Bradzer** [comment]
Thank you for your reply @ccpdouglas.
It is running in node. I'm developing in React Native.

**Comment by Bradzer** [comment]
I just tried again with no changes and it just worked.
