### ISSUE TITLE
making batch request contentType: multipart/batch

### ISSUE THREAD

**Issue by apanchati** [axios/axios#2009]
Does Axios allow batch rest api calls? rest api is implemented to parses the requests, runs them sequentially, and returns the responses back in a multipart batch response. [See example](https://bradwilson.typepad.com/blog/2012/06/batching-handler-for-web-api.html). 

Thanks!

**Comment by apanchati** [comment]
Does Axios allow batch rest api calls? rest api is implemented to parses the requests, runs them sequentially, and returns the responses back in a multipart batch response. [See example](https://bradwilson.typepad.com/blog/2012/06/batching-handler-for-web-api.html). 

Thanks!

**Comment by chinesedfan** [comment]
It should be. Because axios is a client, as long as the required headers are sent. The server will be able to response batched data.

**Comment by sauldeleon** [comment]
Hi!

Thanks for the answer @chinesedfan . Is there any example of how to launch a batch request?

I havent found anything in the docs (yet)

Many thanks!

**Comment by chinesedfan** [comment]
@sauldeleon Sorry, it is not one of key features of axios, so we have no documents for it. But you can find out what headers, data and data format need to be sent, then use axios as usual.

**Comment by apanchati** [comment]
@sauldeleon below is the sample code. Hope this helps.

public async getBatch(): Promise<any> {
 return new Promise((resolve, reject) => {
   try {
	 let batchContents = new Array()
	 const changeSetId = '3bc5bd67-3517-4cd0-bcdd-9d23f3850402'

	 batchContents.push('--' + changeSetId)
	 batchContents.push('Content-Type: application/http; msgtype=request')
	 batchContents.push('')
	 batchContents.push('GET /api/YOUR_ENDPOINT HTTP/1.1')
	 batchContents.push('Host: localhost:44300')
	 batchContents.push('')
	 batchContents.push('')
	 batchContents.push('--' + changeSetId + '--')

	 let batchBody = batchContents.join('\r\n')

	 const headers = {
	   headers:
		 { 'Content-Type': 'multipart/parallel; boundary="' + changeSetId + '"' }
	 }

	 AxiosService.post('batch', batchBody, headers).then((response) => {
	   resolve(response)
	 })
   } catch {
	 reject('Error trying to get data from ' + AxiosService.defaults.baseURL)
   }
 })
}
