### ISSUE TITLE
Getting blob from local file doesn't work on Android, but on iOS (React Native)

### ISSUE THREAD

**Issue by minimaluminium** [axios/axios#2010]
**Describe the issue**
I'm getting a blob from a local image on iOS successfully, however, it does nothing on Android. It doesn't even throw an error. I confirm that the images exist on both platform by showing the images in `<Image />` component.

Is Axios supposed to be work with local data, or is this some kind of glitch, because it works on iOS, but Android?

**Example Code**
Code snippet to illustrate your question

```js
const filePath = 'file:///data/user/0/com.app/cache/1550792341483.JPEG';
axios.get(filePath, {responseType: 'blob'})
  .then(res => console.log(res))
  .catch(err => console.log(err));
```

**Expected behavior, if applicable**
On iOS, it outputs the blob data (attached screenshot), but it doesn't output anything on Android, even no error.

**Environment:**
 - Axios Version [0.18.0]
 - OS: [iOS 12.1, Android 9.0]
 - Additional Library Versions [React Native 0.57.4]

**Additional context/Screenshots**
This is the response on iOS.
![screenshot 2019-02-22 09 17 25](https://user-images.githubusercontent.com/1418797/53213135-b9101c80-3682-11e9-8b2c-4d8d5d05765a.png)

**Comment by oleduc** [comment]
Reading local files using XHR is not supported by most browser as it is a serious security risk. You should use the File Api instead.

The fact that this even  works on IOS is curious enough but I know for sure that you cannot do this on chrome unless you start it with the "--allow-file-access-from-files" option enabled.
