### ISSUE TITLE
Axios POST cannot change Content-Type or POST to API (but works in POSTMAN)

### ISSUE THREAD

**Issue by patrickcuagan** [axios/axios#2011]
I'm trying to POST to an API hosted in AWS. However, with the sample post below, it does not even log the "success" or "error". The URL exists because after awhile, the following text logs to the console.

```js
xhr.js:173 OPTIONS <AWS_API_LINK> net::ERR_EMPTY_RESPONSE
Error: Network Error
    at createError (createError.js:17)
    at XMLHttpRequest.handleError (xhr.js:87)
```

```js
console.log("get all owners")
var url = ""
var data = {
  query: {
     role: "Partner"
  }
}		  

var config = {
  headers: {
    "x-authorization": "token"
  }
}

axios.post(url, data, config)
.then(function(res){
  console.log("success")
  console.log(res)
}).catch(error => {
  console.log("error")
  console.log(error)
});
		
console.log("end get all owners")
```

For some odd reason, it works whenever I try to use the **qs** package to stringify the data and config. However, the x-authorization header would not be part of the post header. I have tried adding **Content-Type** to **application/json**, but it results in the same console.log as above.

**Expected behavior, if applicable**
What I expect to happen is that it'll post and return the success. 

**Environment:**
- OS: Mac
 - Browser: Safari
 - Additional Library Versions: ReactJS

**Comment by chinesedfan** [comment]
> For some odd reason, it works whenever I try to use the **qs** package to stringify the data and config. However, the x-authorization header would not be part of the post header.

Only stringify the data, but don't stringify the config. That's why your header is failed to be set.

> I have tried adding **Content-Type** to **application/json**, but it results in the same console.log as above.

Maybe the server only accepts `application/x-www-form-urlencoded`. That's why it works when you use qs.
