### ISSUE TITLE
Add AxiosException class

### ISSUE THREAD

**Issue by ruscon** [axios/axios#2013]
**Is your feature request related to a problem? Please describe.**
I use typescript.
How to verify that I received exactly axios error?

**Describe the solution you'd like**
Add custom error class: AxiosException, which is inherited from the standard Error class

**Example**
```
try {
  axios.get('...')
}
catch(err) {
  if (err instanceof AxiosException) {
      console.error(err.response);
  }
}
```

**Comment by chinesedfan** [comment]
How about checking `error.isAxiosError` directly?

**Comment by ruscon** [comment]
@chinesedfan 
Typescript needs typing.
The typification of the class Error does not know anything about this property.
and the interface in this case also does not work normally.
Those, the only option is a class

**Comment by chinesedfan** [comment]
@ruscon I think you can use type assertion.

```
import axios, {AxiosError} from 'axios';

try {
  axios.get('...')
}
catch(err) {
  if ((<any>err).isAxiosError) { // check to make sure type assertion is right
      const e = <AxiosError>error;
      console.error(e.response);
  }
}

```

**Comment by ruscon** [comment]
@chinesedfan So you can do something like this:

```typescript
import axios, {AxiosError} from 'axios';

try {
    axios.get('...')
}
catch(err) {
    if (err.isAxiosError) { // check to make sure type assertion is right
        const e: AxiosError = error;
        console.error(e.response);
    }
}
```

But this is a bad approach for both js and ts.

**Comment by ruscon** [comment]
@chinesedfan https://medium.com/@xjamundx/custom-javascript-errors-in-es6-aa891b173f87

**Comment by chinesedfan** [comment]
> But this is a bad approach for both js and ts.

@ruscon I agree a bit in ts, but not in js. There are so many duck types in js. I think that's why ts designs type assertion. Your `AxiosException` approach is a standard but heavy way. If someday axios were totally refactored, I will stand in your side. Good luck!

**Comment by ruscon** [comment]
@chinesedfan heavy way ?

**Comment by chinesedfan** [comment]
@ruscon `heavy` means extra changes. I am not a native speaker and don't know whether it has strange meanings in English.

**Comment by ruscon** [comment]
@chinesedfan, me too, no problems.

I made all the changes, as you can see, is nothing heavy there.
If classes can be used, then I would even more logic here
https://github.com/axios/axios/pull/2014/commits/e8ddb60f4b61e34699c1ba811b5b3684950d76a7#diff-c08f94705d80a1dab0bdb72bbdd83daa

It will be something like this
```javascript

export class AxiosException extends Error {   
    constructor(error) {
        var json = error.toJSON();
        json.name = AxiosException.name;

        super(JSON.stringify(json, undefined, 2));

        Object.assign(this, error);
    }
}
```

**Comment by AyushG3112** [comment]
I think this was sorted with https://github.com/axios/axios/issues/1415 but a release is pending

**Comment by Kunamatata** [comment]
What's the state of having `AxiosError` be a class as well as an interface in order to be able to use `instanceof` ?

**Comment by sammy007** [comment]
OMG. 1 year of jerking with it.

**Comment by fubar** [comment]
Is there any progress on this? `AxiosError` is useless as it is in Typescript.

**Comment by Klemensas** [comment]
Having a specific exception would be nice but `AxiosError` is definitely not useless.
You can write a helper around it, something like:
```ts
export function isAxiosError<T>(error: AxiosError | any): error is AxiosError<T> {
  return error && error.isAxiosError
}
```

And then use it like this:
```ts
  catch (exception) {
    if (isAxiosError<apiTypes.ResponseError>(exception) && exception.response) {
       ...
    }
  }
```

**Comment by jasonsaayman** [comment]
Resolved in #2014

**Comment by aeharding** [comment]
@darkbasic I don't think so. I have to add the sha to my package.json:

```
"axios": "https://github.com/axios/axios.git#58112e137e316c7154e77a3b3777d6788de869b9",
```

I ran into this issue because Typescript 4.4 defaults `catch {}` error type to `unknown` instead of `any` now, and checking `error instanceof AxiosException` is the cleanest way to fix it.

**Comment by darkbasic** [comment]
Me either.

**Comment by CatsMiaow** [comment]
You can apply type guards with the `isAxiosError` helper function.

https://github.com/axios/axios/blob/f3ca6371caa738ba5308d413433d9f676f2e0138/index.d.ts#L168

https://github.com/axios/axios/blob/f3ca6371caa738ba5308d413433d9f676f2e0138/test/typescript/axios.ts#L369-L372

```ts
import axios from 'axios';

if (axios.isAxiosError(error)) {
  // error.response?.data ...
}
```

**Comment by darkbasic** [comment]
That's what I did, but having to write your own type guard sucks :)
