### ISSUE TITLE
Axios GET with MessagePack format

### ISSUE THREAD

**Issue by shaotime** [axios/axios#2015]
**Describe the issue**
I'm trying to make a GET on my backend which sends back data in MessagePack format. The resulting data that I'm getting from Axios, however, is an entire string with {}, %, and \n in it. See example code. When using isomorphic-unfetch, on the other hand, I get back a result where I can access its Buffer with the MessagePack data. Axios for some reason pre-decodes the received data but it's in an incorrect form. I'm unable to parse or access any of the Axios data afterwards. I've tried to use transformResponse: undefined to attempt to stop Axios from autoparsing it into anything else, but it doesn't work. I've also tried to define the responseType to string, JSON, etc. all of the options. I've tried to replace all the weird things in the Axios data string with interceptors, which makes the data "look" like a JavaScript object, but JSON.parse on it fails with "Unexpected token at xxx in position 4" as it thinks it's trying to parse an array? Not sure...

**Example Code**
Code snippet to illustrate your question

Axios gives back this:
```js
data:
`%{\n  matches: [\n    %{\n      attendance: nil,\n      away_team: %{\n        age_group: nil,\n...
```

While isomorphic-unfetch gives back this:
```js
<Buffer 81 a7 6d 61 74 63 68 65 73 dc 00 95 de 00 11 aa 61 74 74 65 6e 64 61 6e 63 65 c0 a9 61 77 61 79 5f 74 65 61 6d 87 a9 61 67 65 5f 67 72 6f 75 70 c0 a2 ... 16334 more bytes>,
```

**Expected behavior, if applicable**
I'm expecting Axios to simply return some data in MessagePack format or where I can access the Buffer of the response (which holds the MessagePack format data). 

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: OSX 10.14.1]
 - Browser: Chrome
 - Browser Version 72.0.3626.109
 - Additional Library Versions: axios 0.18.0, isomorphic-unfetch 3.0.0, react 16.8.2

**Comment by chinesedfan** [comment]
Show your codes, instead of descriptions. You tried a lot of things. Make a table to conclude every case, or it's hard to help you.

**Comment by Alanscut** [comment]
suggest to use `transformResponse` to handle the data returned from backend.
