### ISSUE TITLE
FormData POST request get status code 0 on Android

### ISSUE THREAD

**Issue by isaaclem** [axios/axios#2016]
The very same post request is working fine on iOS, but on Android it's getting status code 0 instead. 

```
const formData = createFormData({ body });

    // Configure HTTP request
    const ax = axios.create({
      timeout: TIMEOUT_CONNECT,
      headers: { 'Content-Type': 'multipart/form-data' }
    });

    ax.post('API-Endpoint', formData)

const createFormData = ({ body }) => {
  const data = new FormData();
  Object.keys(body.body).forEach(key => {
    data.append(key, body.body[key]);
  });

  return data;
};
```

**Expected behavior**
To fire request successfully

**Environment:**
 - "axios": "^0.18.0"
 - "react": "16.6.1",
 - "react-native": "^0.57.5",

**Comment by maedox** [comment]
Try this: https://www.npmjs.com/package/axios#handling-errors

**Comment by Zohaad97** [comment]
@isaaclem Status code 0 means client is cancelling request somehow.
