### ISSUE TITLE
is it possible use self signed ssl without agent? as request

### ISSUE THREAD

**Issue by creatxrgithub** [axios/axios#2018]
is it possible use self signed ssl without agent? 

in request, i can do it as below:

request.post('https://localhost/login', {
				form: {
					username: name,
					password: pass,
				},
				rejectUnauthorized: false,
			requestCert: true,
			agent: false,
			}, function (err, res, body) {
			});

**Comment by varijkapil13** [comment]
I am using it with success without any problems everyday at work. Did not have any problems until now.

**Comment by creatxrgithub** [comment]
how to translate above code to use axios? thanks.

i tried several times in the code below

https://github.com/axios/axios/issues/2024

**Comment by gaoqiang19514** [comment]
try this:
https://github.com/axios/axios/issues/2024#issuecomment-473578684
