### ISSUE TITLE
Why replace the empty string in parmas with '+'

### ISSUE THREAD

**Issue by CoalYa** [axios/axios#2023]
https://github.com/axios/axios/blob/d59c70fdfd35106130e9f783d0dbdcddd145b58f/lib/helpers/buildURL.js#L11

**Example Code**
```js
axios.get('/user', { params: { name: 'Fred Flintstone' }})
```
and then request to `/user?name=Fred+Flintstone`

**Environment:**
 - Axios Version [e.g. 0.18.0]

**Comment by maedox** [comment]
Because URL's can't contain un-encoded whitespace. Please use a search engine.
