### ISSUE TITLE
how to use csrf-token with axios?

### ISSUE THREAD

**Issue by creatxrgithub** [axios/axios#2024]
i want to use axios to replace request

async function authLogin(name,pass) {
	let jar = request.jar();
	let instance = await axios.create({ headers:{ jar:jar, json:true}, httpsAgent: new https.Agent({ rejectUnauthorized: false, requestCert: true, })});  //it seems that using instance is better than using config while request
	let res = await instance.get('https://172.16.220.133/api/config');
	console.log(res.data.csrf_token);  //got csrf token
	instance.defaults.headers['x-csrf-token'] = res.data.csrf_token;
	res = await instance.post('https://172.16.220.133/login',{username:name,password:pass});
	console.log(res.statusCode);  //failed with code 403 err
}

below with request is success:

function login(name,pass) {
	let jar = request.jar();
	let res = request({
		url: 'https://172.16.220.133/api/config',
		json: true,
		jar: jar,
		rejectUnauthorized: false,
			requestCert: true,
			agent: false,
	}, function(err,res,body) {
		if(err) {
			console.log(err);
		}
		request.post('https://172.16.220.133/login', {
				form: {
					username: name,
					password: pass,
				},
				json: true,
				jar: jar,
				rejectUnauthorized: false,
			requestCert: true,
			agent: false,
				headers: {
					'x-csrf-token': body.csrf_token,
				},
			}, function (err, res, body) {
				try {
					console.log(body.header.user);
				} catch(err) {
					console.log(err.code === Error.ERR_NAPI_TSFN_GET_UNDEFINED );
				}
		console.log(res.statusCode);
			});
	});
}

**Comment by jamesst20** [comment]
Hi,

To include the CSRF token in all your request just do that :

`Axios.defaults.headers.common['X-CSRF-TOKEN'] = token;`

**Comment by creatxrgithub** [comment]
> Hi,
> 
> To include the CSRF token in all your request just do that :
> 
> `Axios.defaults.headers.common['X-CSRF-TOKEN'] = token;`

i tried in the code above:

instance.defaults.headers['x-csrf-token'] = res.data.csrf_token;
or
instance.defaults.headers.common['x-csrf-token'] = res.data.csrf_token;

it 's not work.
always get 403 err

**Comment by creatxrgithub** [comment]
or, i cannot use request.jar() for axios?
i'll try later with axios-cookiejar-support

**Comment by creatxrgithub** [comment]
now, the code below is success.

const axiosCookieJarSupport = require('axios-cookiejar-support').default;
const tough = require('tough-cookie');
axiosCookieJarSupport(axios);

async function authNodeBB(name,pass) {
	let cookieJar = new tough.CookieJar();

	let instance = await axios.create({
		jar:cookieJar,
		withCredentials: true,
		httpsAgent: new https.Agent({ rejectUnauthorized: false, requestCert: true, keepAlive: true})
	});
	let res = await instance.get('https://172.16.220.133/api/config');
	console.log(res.data.csrf_token);

	instance.defaults.headers['x-csrf-token'] = res.data.csrf_token;

	res = await instance.post('https://172.16.220.133/login',{username:name,password:pass});

	console.log(res.statusCode);
	console.log(res);
}

**Comment by AllainPL** [comment]
@emilyemorehouse looks like self-resolved and ready to close :)

**Comment by MukeshNegi7579** [comment]
try this
axios.defaults.headers.post['X-CSRF-Token'] = response.data._csrf;

**Comment by gaoqiang19514** [comment]
> new https.Agent({ rejectUnauthorized: false, requestCert: true, keepAlive: true})

Perfect! That solved my problem

**Comment by nextwebb** [comment]
> try this
> axios.defaults.headers.post['X-CSRF-Token'] = response.data._csrf;

thanks. this still works in Dec 2019

**Comment by LocalHeroPro** [comment]
When I use:
```javascript
$('form#fancy-id').on('submit', function (e) {
    e.preventDefault();
    let form = $(this);
    let data = form.serialize();

    axios.put('/some-url', data)
        .then(response => {
            // do something
        })
        .catch(error => {
            console.log(error);
        });
});
```
I don't need to deal with Laravel 
```javascript
axios.defaults.headers.common['X-CSRF-TOKEN'] = $('meta[name="csrf-token"]').attr('content');
```
