### ISSUE TITLE
Can we set cookies in Axios ?

### ISSUE THREAD

**Issue by jamesst20** [axios/axios#2026]
Hi,

I must be missing something, I've been trying to set my session cookie in Axios request for the past hours and I have gotten no success.

Settings my XCSRF token this way works fine fine
`Axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;`

However, Cookies sent looks like this :

```
Cookie: io=PHE6Pt47_eplaOZIAAAC; XSRF-TOKEN=eyJpdiI6IkZEK2RmdlFjeTFIYVBmMVU5VUR4Tnc9PSIsInZhbHVlIjoiQmpDSFdVYUFEUGZzRXQxbHg4SEwwYWFrNWVkUm1BdU5ZOHlGRFVudFJtMTc1emxkdVhra1daTTcxSUNjRXFuOSIsIm1hYyI6ImYwMjQ0ZDAyNTQzNWFmNmI4NzdlY2NkMjhkNDIxYTRlZDQyM2FlNzQ2ZmE1YTI5ZGRhZDAyNzAwODAxYTY1NGQifQ%3D%3D; myapp_session=eyJpdiI6InhudFZJd1hZNWlzRkJPSHR2VHNnT3c9PSIsInZhbHVlIjoiN3FEXC9ySlU5XC9yU2Nrd3I0UWFXVjV6R2R5NzFPd3VhVE9lKysrK0xaOVJESlE3MnpSV2VUOUMrU2wreXdyWSthIiwibWFjIjoiMjZmZTU1OTJmNGEwMTE5OTZkNmYxZTJiYWUwZmY2NTUxM2M2ZTM0ZWUyOTk3NmYyN2QwMDQ4OGNmYjkyNGVlOCJ9
```

and I would like to replace the cookie `myapp_session` with the session id provided by the backend (Laravel 5.7) since myapp_session keeps changing every page load.

Thank you

**Comment by saileifeng** [comment]
me too...
how can i get set-cookie and set a cookie send to server in Axios.

**Comment by jamesst20** [comment]
To answer my own question : 

Cookies must be edited using the localStorage API in Javascript.
`myapp_session` cannot be edited at all because it is managed by the browser itself.

I ended up figuring out that it was an issue in my Laravel Middleware that was causing my issue and by fixing it I figured out I had no reason to set myself the Cookie token.

**Comment by Imperiali** [comment]
If you want to send the session, you must insert `withCredentials: true` inside the `headers` object. 
Something like that:
```
axios.post(url, {
headers: {
    withCredentials: true,
  },
}
```

**Comment by markjackson02** [comment]
what if we want to pass cookies along? For example client sends request to server, and server needs to make an API call with the client's cookie? How to inject that cookie into axios?

**Comment by namoojaalallee** [comment]
First we contact support center and then take the instructions from them and continue to solve it
