### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by tpakhoa1996** [axios/axios#2028]
I cant find the exact information about the lowest support on each browser. I mean does it support all version of all browsers and if not then from which version of each browser does it support? Thank you.

**Comment by luciano7** [comment]
<img width="618" alt="Screen Shot 2019-03-29 at 11 16 30 AM" src="https://user-images.githubusercontent.com/4147895/55242714-3267d580-5214-11e9-869b-44436ff0ac2b.png">
Those are the tested browser versions.

**Comment by NeliHarbuzava** [comment]
@luciano7 We need info about minimum supported version. Does this table mean that axios does not support Chrome lower than version 72? Which is lowest supported version? Where to find this info?

**Comment by victorst79** [comment]
any information about this?

**Comment by Alanscut** [comment]
will be update later.

**Comment by wirekang** [comment]
Where can I find the updated information?
