### ISSUE TITLE
axios throw OOM  in RN 

### ISSUE THREAD

**Issue by Dante-dan** [axios/axios#2031]
**Describe the bug**
I use `axios` and `redux`  in `RN 0.57` to subscribe the request status.  The response is ok , but throw Error Warn `Possible Unhandled Promise Rejection(id:0): Error: Out of memory`

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
let instance = axiosInit();
let userInfo = {};   // from native sdk
// instance init
function axiosInit() {
  return axios.create({
    baseURL: baseUrl,
    timeout: timeout,
    headers: headerInit(),
  })
}

// interceptor Init to dispatch state
function interceptorsInit() {
  instance.interceptors.request.use(function (config) {
    // todo... before request
    store.dispatch(LOADING);
    return config;
  }, function (error) {
    // todo... error request
    store.dispatch(ERR_LOADING);
    return Promise.reject(error);
  });

// 添加响应拦截器
  instance.interceptors.response.use(function (response) {
    // todo... response
    console.log('responseSuccess', response);
    store.dispatch(NO_LOADING);
    return response;
  }, function (error) {
    //  todo... error response
    console.log('responseErr', error);
    store.dispatch(ERR_LOADING);
    return Promise.reject(error);
  });
}

// serviceInit . it use to set header by login 
function serviceInit(config) {
  userInfo = config;
  headerInit();
  instance = axiosInit();
  interceptorsInit();
}

```

**Expected behavior**
when I axios.get(url), the app is Crash and out of memory

**Environment:**
 - Axios Version [0.18.0]
 - OS: [android 5.1]
 - Additional Library Versions [e.g. React 16.6, React Native 0.57.0]

**Additional context/Screenshots**
![z q jock5 sg ziw0 0nsd](https://user-images.githubusercontent.com/19773791/53795757-9a0c6700-3f6d-11e9-96e1-04066737deaf.png)

```bash
# logcat
03-05 15:22:22.184 4930-5393/com.d.app A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 5393 (mqt_js)
03-05 15:22:22.499 4930-4945/com.d.app W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
03-05 15:22:22.499 4930-4945/com.d.app E/libutils.threads: androidCreateRawThreadEtc failed (entry=0xb748c100, res=11, errno=0)
```

**Comment by chinesedfan** [comment]
You'd better check handler logic. Only with small and re-produceable demo, we can help find the root reason.

**Comment by chinesedfan** [comment]
Closed due to no updates with more information after a long time.
