### ISSUE TITLE
Axios 0.18.0 Vulnerabilities

### ISSUE THREAD

**Issue by tylorkolbeck** [axios/axios#2033]
When installing axios 0.18.0 in my react app I am receiving a warning about 65 vulnerabilities - (63 low, 2 high).  I have never received this error before. Is there a dependency I need to remove? I have not found anything about this online. 

I am afraid to run npm audit fix.  WIll this break anything? Thank you.

**Comment by chinesedfan** [comment]
Please follow the issue template. And paste vulnerabilities out, or some of them.

**Comment by naytun** [comment]
A Denial of Service vulnerability discovered in the Axios JavaScript package – affecting all versions of the popular HTTP client
Ref: https://snyk.io/blog/a-denial-of-service-vulnerability-discovered-in-the-axios-javascript-package-affecting-all-versions-of-the-popular-http-client/
