### ISSUE TITLE
CORs error when making get requests Github API

### ISSUE THREAD

**Issue by Schachte** [axios/axios#2034]
**Describe the issue**
I'm trying to authenticate over OAUTH API using Axios. The initial request is just a simple GET to get the auth token.

> ...from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I can use an href link and it works totally fine. What could be the issue here?

**Example Code**

```
  axios.get(
    "https://github.com/login/oauth/authorize?client_id=$ID"
  ).then((res) => { console.log(res) })

```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version 0.19beta
 - OS: OSX 10.13.4]
 - Browser chrome
 - Browser Version latest
 - Additional Library Versions react
**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by rkzhap123** [comment]
if you use your server with Express, 

```
app.all('/*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With");
  next();
});
```

use this way or

install cors library with npm

```
var cors = require('cors');
app.use(cors());
```

**Comment by Zohaad97** [comment]
Try to set headers in your HTTP request. See the example code

```
axios.get('https://google.com', {
 headers: {
   "Access-Control-Allow-Origin": "*"
 }
});
```

**Comment by AlexxBoro** [comment]
when getting data from Github API try this as the root endpoint: [](https://api.github.com)
worked for me, this link might be helpful too: ([](https://developer.github.com/v3/))

**Comment by AlexxBoro** [comment]
when making get requests to Github API try to use this as the root endpoint: https://api.github.com
this link might also be helpful: https://developer.github.com/v3/

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by moyid** [comment]
I'm running into this issue was well, and I tried @AlexxBoro 's solution by using the v3 endpoint. I found, however, that while most of v3 endpoints support CORS, the endpoints for OAuth post requests do not. You can find more information in [this issue](https://github.com/isaacs/github/issues/330) which was unfortunately first opened in Jan 2015, and remains open.

**Comment by snawaz** [comment]
@moyid :

>However, the OAuth request can work as a link, it would return the code by appending it to the current URL, and then you can get the code from the URL by using regex -- this can be one of the few hacky solutions to this problem!

Could you please elaborate on this a bit more? Or url to an example would be great help. 😄
