### ISSUE TITLE
can not get response when post on server

### ISSUE THREAD

**Issue by Talkwondo** [axios/axios#2035]
**Describe the issue**
when using in localhost it works fine. when use it with domain server I get timeout.

**Example Code**
axios({
        method: 'post',
        url: 'http://localhost:3000/models',
        timeout: 1000 * 5, // Wait for 5 seconds
        data: jsonContent
      })

and serverside:
const express = require('express');
const fs = require('fs');
const app = express();
const port = 3000;
const bodyParser = require('body-parser');

app.use(bodyParser.json());

app.post('/models', (req, res) => {
    fs.writeFileSync('./data/' + new Date().getTime() + '.json', JSON.stringify(req.body));
    res.send('Saved');
})

app.listen(port, () => console.log(`Example app listening on port ${port}!`));

**Comment by rkzhap123** [comment]
you need to use url as your server's ip address

**Comment by Talkwondo** [comment]
Hi,
no. i uploaded to the server and there are many domains. now i tried to reach and response was 404.
to this address:
serverip/home/admin/web/domain.com/public_html which is where the location is listening 

Thank you for your reply

**Comment by Talkwondo** [comment]
Hello again,
I changed address to ip and set default domain to my code node.js
Now again it still timeout.

axios({
        method: 'post',
        url: 'http://IPADDRESS:3000/models',
        timeout: 1000 * 5, // Wait for 5 seconds
        data: jsonContent
      })

and node js side:
const express = require('express');
const fs = require('fs');
const app = express();
const port = 3000;
const bodyParser = require('body-parser');

app.use(bodyParser.json());

app.post('/models', (req, res) => {
    fs.writeFileSync('./data/' + new Date().getTime() + '.json', JSON.stringify(req.body));
    res.send('Saved');
})


app.listen(port, () => console.log(`Example app listening on port ${port}!`));

**Comment by rkzhap123** [comment]
I think you need to open your server's port.
you can check your server's port open from this website

https://www.yougetsignal.com/tools/open-ports/

**Comment by Talkwondo** [comment]
Thank you,
I can see that my port is closed but i don't understand why.
I added firewall rule with TCP protocol and add port 3000 on my control panel with ip 0.0.0.0/0 and also on my server. still can not open the port. any idea?

**Comment by Talkwondo** [comment]
OK i Made it!
Just node the js file and that's it!
the link you sent helped me a lot.
Thank you very much!!
