### ISSUE TITLE
Setting up PHP api to work with Axios

### ISSUE THREAD

**Issue by SNOWGUM** [axios/axios#2039]
So I’m trying to make my own API to use in my Axios Node app. But I’m running into problems…
I’m using PHP to put together the JSON. Here’s my code;

```
<?php
header('Content-Type: application/json');
error_reporting(E_ALL);
ini_set("display_errors", 0);
$user = "SnowGum"
$json = array
(
  "user" => $user
);
  echo json_encode($json);
?>
```
this returns the following `{"user":"SnowGum"}`
When I try and GET this with axios it returns undefined :disappointed_relieved:
Heres my JS code;

```
axios.get(url)
  .then(response => {
    var value = response.user;
    console.log(value);
  })
  .catch(error => {
    console.log(error);
  });
```
I hope we can get this to work, I just spent 1 hour writing the PHP for the application :joy:

**Comment by cesar18pena** [comment]
In Axios the information is store inside `response.data`.
``` js
// Change this line 
var value = response.user;
// For this one
var value = response.data.user;
```
In the newest versions of Axios, you are returned a response object containing the data or an error object containing an error object. `response.data` gives you the information you are looking for along with response.status or response.statusText. 

The return object consists of:
``` js
{
  // `data` is the response that was provided by the server
  data: {},

  // `status` is the HTTP status code from the server response
  status: 200,

  // `statusText` is the HTTP status message from the server response
  statusText: 'OK',

  // `headers` the headers that the server responded with
  headers: {},

  // `config` is the config that was provided to `axios` for the request
  config: {}
}
```

**Comment by SNOWGUM** [comment]
Oh wow thanks, :) legend

**Comment by wasnlosdu** [comment]
@SNOWGUM would you mind closing this issue then? 🥇

**Comment by SNOWGUM** [comment]
Oh yea sorry
