### ISSUE TITLE
Axios.GET working but Axios.POST is getting 401 Unauthorized with Self hosted WCF

### ISSUE THREAD

**Issue by spider58** [axios/axios#2041]
I'm developing a react application which using axios for send and receive data with **self hosted wcf service**.

I have to use withCredentials:true option for axios.

**GET method is working good**

```
axios({
   withCredentials: true,
   url: 'blabla/myGetMethod?val1=aaa&val2=bbb'
}).then (result => {
     // DO SOMETHING
})
```

**WCF code for GET Method**

```
<OperationContract, WebInvoke(Method:="GET", ResponseFormat:=WebMessageFormat.Json)
Public Function myGetMethod (byval val1 as string, byval val2 as string)
    //DO SOMETHING
end function
```

**But POST METHOD IS GETTING 401 on same WCF Service**

**Error: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present ........**

As you can see my below code i defined request's header code

```
axios({
     headers: {
         'Access-Control-Allow-Origin':'http://localhost:8080'
     },
     method: 'POST',
     withCredentials: true
     url: 'blabla/myPostMethod',
     data: {
          val1: "Hurray",
           val2: "Is it worked"
     }
}).then (result => {
    //DO SOMETHING
       })
```

**WCF code for POST Method**

```
<OperationContract, WebInvoke(Method:="POST", ResponseFormat:=WebMessageFormat.Json, UriTemplate:="/myPostMethod")
Public Function myPostMethod (byval val1 as string, byval val2 as string)
    //DO SOMETHING
end function
```

I have no iade why get is working and post is not.

I configured WCF for CORS enabled

https://enable-cors.org/server_wcf.html

WCF server has below configuration

```
<customheaders>
        <add name="Access-Control-Allow-Origin" value="http://localhost:8080" />
        <add name="Access-Control-Allow-Methods" value="POST,GET,PUT,DELETE,OPTIONS" />
        <add name="Access-Control-Allow-Headers" value="Origin, X-Requested-With, Content-Type, Accept" />
      </customheaders>
```

**Comment by spider58** [comment]
i'm stuck on POST request. Can't do anything, searching since days for solve POST problem. Can anyone help me please.

My self hosted WCF service is CORS configured. So allowing GET requests from http://localhost:8080 already. But why doesn't allow POST requests. No idea, Tried many things in my react app and wcf service but no chance.

I tried to log error in console with below code.

```
axios({
     headers: {
         'Access-Control-Allow-Origin':'http://localhost:8080'
     },
     method: 'POST',
     withCredentials: true
     url: 'blabla/myPostMethod',
     data: {
          val1: "Hurray",
           val2: "Is it worked"
     }
}).then (result => {
    //DO SOMETHING
       }).catch(error => {
            let errObj = JSON.parse(JSON.stringify(error));
            console.log(errObj)
});
```
in my console i seeing errObj as below

> config:
>     data: "{"name":"John"}"
>     headers: {Accept: "application/json", Content-Type:"application/json", Access-Control-Allow-Origin:"http://localhost:8080"}
>     maxContentLength: -1
>     method: "post"
>     timeout: 0
>     transformRequest: {}
>     transformResponse: {}
>     url: "https://myserver/myservice/myPostMethod"
>     withCredentials:true
>     xsrfCookieName: "XSRF-TOKEN"
>     xsrfJHeaderName: "X-XSRF-TOKEN"
>

**Comment by xgui3783** [comment]
It is unlikely an issue with axios, and more likely to be your server config. Although it is strange that your GET request retrieves data no issue. 

Which origin is your react app being deployed/developed? (I guess the backend is at localhost:8080)

Incidentally, the access control allow origin header needs to be set by the server, not the client. So 

```
axios({
     headers: {
         'Access-Control-Allow-Origin':'http://localhost:8080'
     }
})
```

would not do what you want it to do

**Comment by spider58** [comment]
@xgui3783 thanks for reply.

I tested with Fetch api. GET worked but POST same. I using NTLM authentication and SSL

so my wcf service adress is "https://myserver/myservice"

I Implemented CORS support code into my WCF service from this link

https://enable-cors.org/server_wcf.html

as you can see they added required headers.

   ```
requiredHeaders.Add("Access-Control-Allow-Origin", "*");
                    requiredHeaders.Add("Access-Control-Request-Method", "POST,GET,PUT,DELETE,OPTIONS");
                    requiredHeaders.Add("Access-Control-Allow-Headers", "X-Requested-With,Content-Type");

```
I just changed origin with http://localhost:8080

  ```
 requiredHeaders.Add("Access-Control-Allow-Origin", "http://localhost:8080");
                    requiredHeaders.Add("Access-Control-Request-Method", "POST,GET,PUT,DELETE,OPTIONS");
                    requiredHeaders.Add("Access-Control-Allow-Headers", "X-Requested-With,Content-Type");

```

**Comment by spider58** [comment]
@xgui3783 i tried with postman now but same. 401 Unauthorized.

**Comment by xgui3783** [comment]
definitely your server then. 

It seems you have configured your GET method this way:
```
<OperationContract, WebInvoke(Method:="GET", ResponseFormat:=WebMessageFormat.Json)
Public Function myGetMethod (byval val1 as string, byval val2 as string)
    //DO SOMETHING
end function
```

have you done something similar for the POST endpoint?

**Comment by khullah** [comment]
@spider58 is the auth NTLM?

**Comment by reubert22** [comment]
Is it getting `OPTIONS` on `Request Method` ?
If yes, try something like that:
```
headers: {
     'Access-Control-Allow-Origin': '*',
     Accept: "application/json",
    "Content-Type": "application/json"
 }
```
And remember to allow CORS on API

**Comment by cristuballa** [comment]
> @xgui3783 thanks for reply.
> 
> I tested with Fetch api. GET worked but POST same. I using NTLM authentication and SSL
> 
> so my wcf service adress is "https://myserver/myservice"
> 
> I Implemented CORS support code into my WCF service from this link
> 
> https://enable-cors.org/server_wcf.html
> 
> as you can see they added required headers.
> 
> ```
> requiredHeaders.Add("Access-Control-Allow-Origin", "*");
>                  requiredHeaders.Add("Access-Control-Request-Method", "POST,GET,PUT,DELETE,OPTIONS");
>                  requiredHeaders.Add("Access-Control-Allow-Headers", "X-Requested-With,Content-Type");
> ```
> 
> I just changed origin with http://localhost:8080
> 
> ```
> requiredHeaders.Add("Access-Control-Allow-Origin", "http://localhost:8080");
>                   requiredHeaders.Add("Access-Control-Request-Method", "POST,GET,PUT,DELETE,OPTIONS");
>                   requiredHeaders.Add("Access-Control-Allow-Headers", "X-Requested-With,Content-Type");
> ```

I got same issue. we're you able solve this problem?

**Comment by chinesedfan** [comment]
>  withCredentials: true

> requiredHeaders.Add("Access-Control-Allow-Origin", "*");

Don't set them together. See more about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by Supertramplee** [comment]
> @spider58 is the auth NTLM?

i'm working with NTLM auth and suffer similiar issue.... server side was build by IIS.. do you suffer same issue ?

**Comment by bernardoadc** [comment]
> > @spider58 is the auth NTLM?
> 
> i'm working with NTLM auth and suffer similiar issue.... server side was build by IIS.. do you suffer same issue ?

Exactly the same. Ended up using [ntlm-webapi](https://www.npmjs.com/package/ntlm-webapi)
