### ISSUE TITLE
No error when max number of redirects is reached in NodeJS

### ISSUE THREAD

**Issue by fedebertolini** [axios/axios#2042]
**Description**
When I define a `maxRedirect` value higher than 0 and I send a `GET` request that ends up in more redirections than `maxRedirect`, the returned promise doesn't resolve nor reject.

**Example Code**
```js
const axios = require('axios');

axios.get('http://instagram.com/puppyglobe', {
    maxRedirects: 1,
}).then(response => {
    console.log(response.status);
}).catch(error => {
    console.error(error.response);
});
```

There are 3 redirections happening when sending a request to `http://instagram.com/puppyglobe`:
- `http://instagram.com/puppyglobe` -> `https://instagram.com/puppyglobe` (307)
- `https://instagram.com/puppyglobe` -> `https://www.instagram.com/puppyglobe` (301)
- `https://www.instagram.com/puppyglobe` -> `https://www.instagram.com/puppyglobe/` (301)

Defining `maxRedirects` with values 1 or 2 results on the promise never being resolved nor rejected, so in the example nothing is printed in the console.

**Expected behavior**
The returned promise should be rejected.

**Environment:**
 - Axios Version: 0.18.0
 - OS: maxOS High Sierra - v10.13.6
 - NodeJS Version: 10.15.2

**Additional Info:**
I debugged the code in axios and got to this line in the `http` adapter: https://github.com/axios/axios/blob/master/lib/adapters/http.js#L243

```
// Handle errors
req.on('error', function handleRequestError(err) {
  if (req.aborted) return;
  reject(enhanceError(err, config, null, req));
});
```

When the max number of redirects is reached `req.aborted` has a Number, so the promise is not rejected. I can see `err` has a `message` property with value `Max redirects exceeded.`

**Comment by ambroselittle** [comment]
I ran into this same behavior. Even the interceptor is not called in this case.

**Comment by hkcedricw** [comment]
Faced the same problem and it's gone after updating to version 0.19.0. I saw the `follow-redirects` module has been updated

**Comment by sebasaenz** [comment]
I'm currently using version 0.19.0 and this is still happening. In fact the Mocha test that checks `maxRedirects > 0` is failing.

I found something interesting though: if you use `https` instead of `http` for the url in the test, it actually gets passed.

```javascript
it('should support max redirects', function (done) {
    var i = 1;
    server = http.createServer(function (req, res) {
      res.setHeader('Location', '/' + i);
      res.statusCode = 302;
      res.end();
    }).listen(4444, function () {
      axios.get('https://localhost:4444/', {
        maxRedirects: 3
      })
      .catch(function (error) {
        done();
      });
    });
  });
```
