### ISSUE TITLE
Set the axios method to POST but in Network axios send GET method

### ISSUE THREAD

**Issue by mirukusheki** [axios/axios#2044]
**Describe the bug**
I work on a form to send via the API using the POST method. But through the Chrome Browser Tab network, the method changes to GET even though it's clearly written in the code.

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
try {
      let data = new FormData();
      data.append('title', title);
      data.append('description', description);
      data.append('job_title', job_title);
      data.append('salary', salary);
      data.append('experience', experience);
      data.append('location_id', location_id);
      data.append('category_id', category_id);
      data.append('picture', picture);
      data.append('user_id', user_id);
      console.log(data);
      let res = await axios({
        method: 'POST',
        url   : '/thisjob',
        data  : data,
        config: {
          headers: {
            'Content-Type': 'mutipart/form-data'
          }
        }
      });
    } catch (e) {
      console.log(e.response.data)
    }
```

**Expected behavior**
I want to send data with the POST method, not GET.

**Environment:**
 - Axios Version  v0.18.0
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 72.0.3626.121
 - Additional Library Versions: React 16.7

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/41565025/54426277-ffb8da00-4749-11e9-9640-d912ced1acae.png)

**Comment by mirukusheki** [comment]
The problem was clear itself. Probably because the babel problem

**Comment by xgui3783** [comment]
not sure if related, but
```
        config: {
          headers: {
            'Content-Type': 'mutipart/form-data'
          }
        }
```
typo in content-type?

**Comment by regchiu** [comment]
I have same problem. How to solve it?
