### ISSUE TITLE
Axios fails on poylfilled URLSearchParams in IE11

### ISSUE THREAD

**Issue by nirazul** [axios/axios#2045]
**Describe the bug**
I'm working on a project with IE11 support and Axios. As I also need some advanced URLSearchParams support, so I'm using [@ungap/url-search-params](https://github.com/ungap/url-search-params) to implement it.

https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/lib/utils.js#L154-L156

**To Reproduce**
I couldn't try out the code in IE11 because runkit doesn't work in IE, but this should be able to reproduce the error.

```js
var axios = require("axios")
var URLSearchParamsPolyfill = require('@ungap/url-search-params')

window.URLSearchParams = URLSearchParamsPolyfill

axios.request({ url: 'https://example.com' });
```

**Expected behavior**
I expect to be able to use Axios with a URLSearchParams polyfill.

**Environment:**
 - Axios: 0.18.0
 - OS: Any OS
 - Browser: Internet Explorer
 - Browser Version: 11
 - Additional Library Versions: `@ungap/url-search-params`

**Additional context/Screenshots**
I'm not 100% sure where the place would be to fix this. Maybe there's also something to be don on the polyfill's side. I've filed the bug report here because axios supports IE11.

**Comment by jonnypolite** [comment]
It seems more likely that there is an issue with the polyfill that you're using than with axios.

What happens when you run `typeof URLSearchParams !== 'undefined'` yourself in the IE console?

What is `val` when you hit the `isURLSearchParams` function and what does `val instanceof URLSearchParams` evaluate to?

Does this type of thing work?
```
var paramsString = "q=URLUtils.searchParams&topic=api";
var searchParams = new URLSearchParams(paramsString);

searchParams.has("topic") === true; // true
searchParams.get("topic") === "api"; // true
```

**Comment by nirazul** [comment]
Hey @jonnypolite, thanks for your response. I've digged a bit more and it looks like it doesn't fail with an earlier version of the polyfill. I guess you're right and it's indeed a problem with the polyfill.

Indeed: 
`new URLSearchParams("q=URLUtils.searchParams&topic=api");` 
throws with 
`Object doesn't support this action` 
for [@ungap/url-search-params](https://github.com/ungap/url-search-params)

Just for the sake of completeness:
`URLSearchParams` returns `function URLSearchParams(query) { ... }` for [@ungap/url-search-params](https://github.com/ungap/url-search-params) (fails)
`URLSearchParams` returns `[object Object]` for [url-search-params](https://github.com/WebReflection/url-search-params) (works)

**Comment by jonnypolite** [comment]
Glad to hear you have a work around! Sorry to hear you have to work with IE!  Would you mind closing this issue?

**Comment by nirazul** [comment]
sure!
