### ISSUE TITLE
When used baseName and url without protocol ,axios dont add slashes

### ISSUE THREAD

**Issue by rodrigocipriani** [axios/axios#2047]
Example:

const test = axios({
  method : 'get',
  baseURL: 'my.domain.com',
  url    : '/user/test',
});

console.log(test); // ... currentUrl: "http:my.domain.com/user/test" ...

**Comment by sohailashraf003** [comment]
I would like to work on this if no one is working on this.

**Comment by rodrigocipriani** [comment]
@sohailashraf003 are you working on that?

**Comment by sohailashraf003** [comment]
> @sohailashraf003 are you working on that?

Yes.

**Comment by sohailashraf003** [comment]
> const test = axios({
> method : 'get',
> baseURL: 'my.domain.com',
> url : '/user/test',
> });

![axios](https://user-images.githubusercontent.com/7263382/55272425-813a6b80-52f7-11e9-81ef-f248cd5458b3.png)

I have tried the same example to reproduce the issue, but in case if you don't mention the protocol then it will take the url as relative. Please refer teh screenshot for more detail. 

Please provide the step to replicate this issue if you are still facing this issue.

**Comment by chinesedfan** [comment]
Sorry, `baseURL` requires to include protocol and slashes. We want to keep axios as simple.

**Comment by rodrigocipriani** [comment]
Thanks for your answer.
The problem is, in the example, I didn't put http on baseUrl, but axios put it to me. 
So, if it is necessary to include protocol and slashes, axios should not put protocol, because it leads to confusion.

**Comment by chinesedfan** [comment]
> console.log(test); // ... currentUrl: "http:my.domain.com/user/test" ...

@rodrigocipriani How did you print out the `currentUrl`? In fact, `test` is a promise, so the current code example is not runnable. And I can't find some codes in axios that appends the protocol.

**Comment by gianniskarmas** [comment]
I'm using axios with nuxt and a middleware that runs under /api in production but under localhost:1337 when in dev.
Before I used to have:
```
serverMiddleware: process.env.NODE_ENV !== 'production' ? [] : [{ path: '/api', handler: '~/api/index.js' }],
```
Now the only way I can think of solving it is to create functions on each and every call. 

Being able to use just '/api' in baseUrl would solve all this mess.
Why did you change it? What was the issue?

**Comment by sohailashraf003** [comment]
@gianniskarmas this PR was not merged into the main branch and rejected.

So no change in the Axios with respect to this PR.

**Comment by chinesedfan** [comment]
> Why did you change it? What was the issue?

@gianniskarmas Did you meet another problem? Can you elaborate the problem and explain what has been changed?
