### ISSUE TITLE
Catching Axios Result is Undefined

### ISSUE THREAD

**Issue by DanJ210** [axios/axios#2050]
**Describe the issue**
Having an issue which I don't know if I'm trying to use axios wrong or not but it looks like I've got the same syntax as shown in documentation. When using `axios.get()` I'll get the result I'm looking for.

I'm calling `IActionResult` controller endpoints using `axios` and I'm intentionally returning `BadRequest("Test Message");` to see if I can send back any message I want. With the code below I catch the error but the variable `err` is undefined when using `axios.post()`. I do the same thing below with `axios.get()` and I'm catching the error which does get populated correctly. Does this same thing not happen with `axios.post()`?

If I look in dev tools and view the errored network call I can see my returned message in the response so it is getting sent back. But It doesn't seem to be getting picked up when catching it.

**Example Code**
```js
axios
            .post('/Form/SavePersonData', _this.donation)
            .then(function(res) {
            })
            .catch(function(err) {
              alert(err);
              console.log(err);
            });
```

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by varnitchauhan** [comment]
I'm having the same issue. if someone have any solution please share the solution.

**Comment by varnitchauhan** [comment]
Reject the axios promise in axios interceptors using Promise.reject(error.response).

**Comment by DanJ210** [comment]
@varnitchauhan can you show what that would look like in the code above please? I'm not familiar with your suggestion.

**Comment by ahood12** [comment]
@DanJ210 I believe the above comment is referring to something along the lines of this - https://github.com/axios/axios/issues/960#issuecomment-320659373

**Comment by DanJ210** [comment]
@ahood12 Ok thanks I can try that.

**Comment by chinesedfan** [comment]
@DanJ210 I am not familiar with IActionResult controller endpoints. But did you support POST method in the server side? Anyway, we suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. Thanks.
