### ISSUE TITLE
HTTPS Proxy with Mitmproxy fails with ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by ncjones** [axios/axios#2051]
Is it possible to proxy HTTPS traffic through Mitm proxy (cross posted from https://discourse.mitmproxy.org/t/proxy-https-traffic-from-nodejs-10-x/1485)?

Requests from the Axios library with NodeJS 10 fails with ERR_TLS_CERT_ALTNAME_INVALID when proxied through Mitmproxy:

```
⇒  NODE_EXTRA_CA_CERTS=~/.mitmproxy/mitmproxy-ca-cert.pem node -e "require('axios').create().get('https://www.google.com').then(r => console.log(r.status))"                   
(node:1207) UnhandledPromiseRejectionWarning: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Cert is empty
    at Object.checkServerIdentity (tls.js:235:17)
```

I cut out Axios and used the Node https module directly and I still get the error:

```
⇒  NODE_EXTRA_CA_CERTS=~/.mitmproxy/mitmproxy-ca-cert.pem node -e "require('https').get({ hostname: 'localhost', port: '8888', path: 'https://www.google.com/'}, res => { console.log(res.statusCode) })" 
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Cert is empty
    at Object.checkServerIdentity (tls.js:235:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1061:27)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)

```

As a workaround I tried ignoring invalid certs but I am getting "bad request" from the mitm server:

```
⇒  NODE_TLS_REJECT_UNAUTHORIZED=0 node -e "require('axios').create().get('https://www.google.com').then(r => console.log(r.status)).catch(e => console.log(e.response.status, e.response.headers.server))"
400 'mitmproxy 4.0.4'
```

I can't tell if this is an issue with Mitmproxy of if it is an issue with the way the HTTP request is being crafted in Axios. Any ideas?

**Environment:**
 - Axios: 0.18.0
 - OS: Ubuntu 18.04
 - Node: 10.15.2

**Comment by ncjones** [comment]
Charles Proxy also doesn't work. I'm pretty sure the issue is within the Node https module.

A workaround is to force the Axios transport to http:
```
const axiosClient = axios.create({
  proxy: {             
    host: 'localhost',
    port: 8888,      
  },
  transport: require('http'),
});
```

**Comment by ncjones** [comment]
This is the same issue: https://github.com/axios/axios/issues/2072

**Comment by chinesedfan** [comment]
> I cut out Axios and used the Node https module directly and I still get the error
> Charles Proxy also doesn't work. I'm pretty sure the issue is within the Node https module.

Closed due to stale and not a bug of axios.
