### ISSUE TITLE
Arithmetic results exceed 32 bits.

### ISSUE THREAD

**Issue by voggen** [axios/axios#2053]
Ie compatible mode requests data, JavaScript error: calculation results exceed 32 bits

**Comment by Zohaad97** [comment]
Can you make a fiddle to reproduce this error?

**Comment by chinesedfan** [comment]
Closed due to lack of information.

**Comment by wangshsion** [comment]
same proplem with v0.19.0, user v0.19.2 instead of v0.19.0 resolve my prolem
用v0.19.2解决了搜狗浏览器在兼容模式下，“计算结果超出32位”的问题
