### ISSUE TITLE
Custom get/post function to avoid repetition

### ISSUE THREAD

**Issue by ShRyDeR** [axios/axios#2056]
**Describe the issue**
I realized that on every axios request i check if the response's status is success or fail so i was wondering if there is a way to do it by default on all requests so i dont have to do it over and over every time

**Example Code**
```js
axios.get('api/data').then((data) => {
    if(data.data.status == 'success'){
           // 
    }else{
          Notification.show('Something wrong happened on our side, please try again later!');
    }
});
```

**Expected behavior, if applicable**
N/A

**Environment:**
 - Axios Version (latest)
 - OS: doesnt matter
 - Browser doesnt matter
 - Browser Version doesnt matter

**Additional context/Screenshots**
NONE

**Comment by chinesedfan** [comment]
You can use a response [interceptor](https://github.com/axios/axios#interceptors).
