### ISSUE TITLE
Axios vs request - preflight status code error in only Axios

### ISSUE THREAD

**Issue by Francesco-Lanciana** [axios/axios#2061]
**The issue/Question**
When sending a post request with axios in a **Nodejs environment** I get the error:
‘Response for preflight has invalid HTTP status code 401’ 

This seems to be related to CORS and the OPTIONS preflight request. I noticed Postman didn't send this request (because it isn't a browser and doesn't care about CORS) and as such the request was successful. I grabbed the code snippet postman gives for NodeJs which uses the request npm module. I then ran it using Node and it worked without a problem.

Is there a way to disable this preflight request since I am running axios in a Node environment? I would also really appreciate if someone happened to know what the actual difference is in the libraries that is causing one to work while the other doesn't.

**Example Code**
The axios version:
```js
var bodyFormData = new FormData();
var data = { x: 1, y: 'D' };
for (var k in data) {
    bodyFormData.append(k, data[k]);
}

axios({
    method: "POST",
    url: url,
    baseURL: this.baseURL,
    data: bodyFormData,
    headers: {
        ...bodyFormData.getHeaders(),
        Authorization: `Bearer ${bearerToken}`
    },
});
```

The request version:
```js
var data = { x: 1, y: 'D' };

var options = {
    method: "POST",
    url,
    headers: {
        "cache-control": "no-cache",
        Authorization: `Bearer ${bearerToken}`,
        "Content-Type": "application/x-www-form-urlencoded"
    },
    form: data
};

request(options);
```

Let me know if there is any other information needed, and thanks for your time in advance.

**Comment by Siilwyn** [comment]
I am guessing this is a feature: having the same behaviour in both environments, since Axios is made for isomorphic usage.

If you're only running in Node.js I can recommend the `got` package.

**Comment by tylerzey** [comment]
This also is an issue for me. I'm consuming an external vendor api from nodejs and axios seems to be sending a preflight options call as if I was using it in the browser.

Going to use request or got now instead of axios.

**Comment by chinesedfan** [comment]
@Francesco-Lanciana Did you really run it in Node.js, or a fake jsdom environment like jest?

**Comment by Francesco-Lanciana** [comment]
It was definitely NodeJs. I more or less wrote a library for testing security permissions around API endpoints that was built on top of Mocha for it's test runner & reporter capabilities (it also has a programmatic API which I needed and Jest lacks). 

It was a while ago but I'm pretty sure I also would have written small nodejs scripts hitting the same endpoint, one with axios and the other with request, in order to try and figure out what was going on.

Unfortunately this was all work done for my previous employer so I don't have access to any of it anymore.

**Comment by chinesedfan** [comment]
@Francesco-Lanciana So is the issue still there? You can also debug internally to check which adapter(xhr or http) is called. Sorry for the late response because axios has been lack of maintainers for a long time.

**Comment by chinesedfan** [comment]
@Francesco-Lanciana So is the issue still there? You can also debug internally to check which adapter(xhr or http) is called. Sorry for the late response because axios has been lack of maintainers for a long time.

**Comment by chinesedfan** [comment]
Closed due to stale. I wrote a [note](https://github.com/chinesedfan/You-Dont-Know-Axios/blob/master/README.md#do-you-use-the-right-adapter) about how to check the adapter. Feel free to remind me if you have further discoveries.
