### ISSUE TITLE
NETWORK_ERR: XMLHttpRequest Exception 101

### ISSUE THREAD

**Issue by javakishore** [axios/axios#2063]
Here is my code, I am calling an ajax call and getting the error. 
SCRIPT_ERROR ERROR: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests

```
const options = {
      headers: {
        "Access-Control-Allow-Origin": "*",       
        "X-Auth-Username": instanceData.username,
        "X-Auth-Password": instanceData.password
      }
    };

    const data = {
      "tenant": instanceData.tenant,
      "startDate": instanceData.startDt,
      "endDate": instanceData.endDt,
      "deviceList": instanceData.series[0]
    };

   
    axios.post(instanceData.url, data, options)
      .then(function (response) {
        instanceData.series = response.data;       
      });
  };
```

**Comment by jonnypolite** [comment]
Check out this [SO conversation](https://stackoverflow.com/questions/2235929/network-error-xmlhttprequest-exception-101).

This error looks to be a CORS issue, and not a bug in Axios. There certainly doesn't seem to be anything wrong with the way you're calling `axios.post`. Can this issue be closed?

**Comment by Alanscut** [comment]
CORS issue, try the following:
* 1.set `axios.defaults.withCredentials = false`
* 2.use the proxy server
* 3.make sure your server is the same origin as your local one and the server settings allow cross-domain request headers.
