### ISSUE TITLE
get json with onDownloadProgress

### ISSUE THREAD

**Issue by alainib** [axios/axios#2065]
I'm trying to make a GET request for JSON data and use onDownloadProgress because the JSON can be huge ( 5mb )

    var instance = axios.create();
    const response = await instance.get(url, {
        onDownloadProgress: function(progressEvent) {
          console.log("download", progressEvent.loaded, progressEvent.total);
         // print "downloading -1 -1 "
        }
      });

any way to make it work or it's only for file download ?
Thanks 

"axios": "^0.18.0",
"react-native" : "0.59.1"

**Comment by DavitVosk** [comment]
Is there any progress for this bug?

**Comment by chinesedfan** [comment]
It depends on RN's implementation. Better to open an issue to RN. Closed due to nothing can be done in axios.
