### ISSUE TITLE
Getting stack trace in interceptor

### ISSUE THREAD

**Issue by stevenmusumeche** [axios/axios#2069]
I am using a response interceptor to convert Axios errors into my own errors.  The stack for the error thrown by Axios is something like this:

```
Error: getaddrinfo ENOTFOUEND uc1a-ecomdev-mlb01.redacted.com uc1a-ecomde
v-mlb01.redacted.com:30005
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
```

Notice that the stack trace does not contain any reference to the calling code.

**Example Code**
Code snippet to illustrate your question

```js
// caller.js

try {
  const result = await axios.get('example.com')
} catch (e) {
  console.log(e.stack)
}
```

Is it possible to get a stack trace that INCLUDES the calling file?

**Comment by Oleg-Arkhipov** [comment]
Any information? That seems pretty important for me. I am using interceptor for throwing custom app exceptions too and get almost useless error logs.

**Comment by Alanscut** [comment]
please try it as follow code:
```
error.toJSON().stack
```
