### ISSUE TITLE
Timeout ignored on Android devices

### ISSUE THREAD

**Issue by TRutte** [axios/axios#2073]
**Describe the bug**
Trying to send a request (no matter what) the timeout will be ignored and is alway 5000ms. The corresponding error gives the correct value in console e.g. "timeout of 30000ms exceeded" but it was actually 5000ms. On IOs everything is working fine. Try to set the timeout for default config and for each request. Same behavior.

```js
const header = {
  Authorization: myToken,
};

const defaultConfig = {
  baseURL: url,
  timeout: 30000,
  headers: header,
};

return axios.create(defaultConfig);
```

**Expected behavior**
The Timeout will be thrown after the defined timeout on Android devices

**Environment:**
 - Axios Version [0.18.0]
 - Android Version [9.0, 8.0]
 - React Native Version [0.59.1]

**Comment by elf9237** [comment]
Where is this paragraph added? how to add？

**Comment by maphongba008** [comment]
+1, same for me, RN 0.59.5 and axios 0.19.0, works on iOS but not on android

**Comment by navata** [comment]
I have executed request about 14000ms. But I have received error message "timeout of 90000ms exceeded" (timeout = 90000).
This issue only display in Android but IOS is normal.

**Comment by fayeah** [comment]
Same for me too, RN 0.60.0 and axios 0.19.0.
Timeout always works on iOS devices but not on Android. 

Hope there's a fix for this soon.

**Comment by MirFahad58** [comment]
Same for me too, RN 0.59.8 and axios 0.18.0.
Timeout is not working on Android. default timeout of 1 mint is there.

Hope there's a fix for this soon.

**Comment by joekeyel** [comment]
same with me too RN 0.59.9 and axios 0.19.0

**Comment by Bashamd455** [comment]
same for me too, RN 0.61.5 and axios 0.19.2

**Comment by arfa123** [comment]
I solved the problem by adding timeout into the axios configuration before data parameter. For some reason, timeout parameter will not work if placed after the data parameter.
```
axios({
      method: 'post',
      timeout: 1000,
      url: 'http://192.168.0.1:5000/download',
      data: {
          access: data.token
      }
})
.then(function (response) {
    alert(response.data);
})
.catch(function (error) {
    alert("There was an error in communicating to server");
});
```

**Comment by teckel12** [comment]
Is it really possible this is still a bug a year later?  I'm still experiencing this as well on Android (React Native) only.

**Comment by teckel12** [comment]
I've been forced to use cancelToken and a JavaScript timeout as a replacement to defaults.timeout which doesn't work on all platforms.  Here's sample code for those who are still having this problem a year after it was reported like myself:

```
        let axiosCall = $axios.CancelToken.source();
        setTimeout(() => { axiosCall.cancel(`Timeout of 3000ms exceeded`) }, 3000);
        $axios({
                method: 'post',
                cancelToken: axiosCall.token,
                url: 'https://blablabla.com/route',
                data: {
                    // Your data to send here
                }
            })
            .then(({ data }) => {
                // Success
            })
            .catch((err) => {
                console.log(err.message);
            });
```

**Comment by jenskuhrjorgensen** [comment]
@teckel12 Thanks for the nice and easy solution to the problem! 👍 Sad that it is at all needed to make timeout work on Android though.

**Comment by jenskuhrjorgensen** [comment]
@mzabriskie I can see that you have previously been very active in this repo: Do you know if there is a primary maintainer of this library today? :)

**Comment by camillaferreri** [comment]
I was experiencing the same problem on Android using RN. 
I solved the problem by adding:
```
<application
  ...
  // add this
  android:usesCleartextTraffic="true">
``` 
in my AndroidManifest.xml

Seems like from Android 9 it blocks any call not in https.
[Here's more info.](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic)

**Comment by paritosh-yadav** [comment]
Hi @jasonsaayman , any update on this?

**Comment by jasonsaayman** [comment]
Hi @paritosh-yadav I am adding it to axios-next so that we can look at it in the next version after the 0.22

**Comment by p-boloor** [comment]
Facing the same issue. @jasonsaayman any update?

**Comment by MuhammadUsman786786** [comment]
I have used the `promise` with `race condition` to solve this problem

**Comment by kylebake** [comment]
To add some extra context on this issue, I've been digging into this for the past week on our own project. Android uses [okhttp](https://github.com/square/okhttp) for its networking library, which offers a few different ways to set a timeout on a request.

React-native uses the ['connectTimeout'](https://github.com/facebook/react-native/blob/6c19dc3266b84f47a076b647a1c93b3c3b69d2c5/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L354) method for its timeout. Which means if the request can't initially hit the endpoint within the timeout, the timeout will fire. However, if the server initially gets the request and just takes a long time to respond, react-native's android code will not apply any kind of timeout. 

One possible fix would be to patch react-native's code to instead use `callTimeout`, from OkHttp's docs:

> The call timeout spans the entire call: resolving DNS, connecting, writing the request body, server processing, and reading the response body. If the call requires redirects or retries all must complete within one timeout period.

My current plan for a workaround is to implement a retry + timeout system on the JS side that uses cancel tokens to cancel requests that aren't completing in time, since our use case requires retries.

**Comment by Uzef1997** [comment]
> setTimeout(() => { axiosCall.cancel(`Timeout of 3000ms exceeded`) }, 3000);

@teckel12 Tried your solution but it is like just returning something something after 3 sec but api is still getting processed on the server and after sometime i got response from the api. it simply means that timeout doesnt work and my api got processed and request is not getting cancelled anyway

**Comment by troZee** [comment]
Thank you @kylebake for providing an explanation. 

Here you can find a PR, which fixes the above issue https://github.com/facebook/react-native/pull/29471/files but for some reason, it has been merged yet 

To workaround it I used axios interceptor as follows: 

```
axiosInstance.interceptors.request.use((config) => {
  const abortController = new AbortController();
  config.signal = abortController.signal;
  setTimeout(() => {
    if (!abortController.signal.aborted) {
      abortController.abort();
    }
  }, HTTP_REQUEST_TIMEOUT);
  return config;
});
```

**Comment by troZee** [comment]
This issue has been fixed here https://github.com/facebook/react-native/pull/38953. Can you retest it and close this issue?

**Comment by jasonsaayman** [comment]
closing as this is stale and seems to have been fixed as above
