### ISSUE TITLE
What is the difference between timeout and cancelToken?

### ISSUE THREAD

**Issue by xiaobitipao** [axios/axios#2074]
**Describe the issue**
What is the difference between timeout and cancelToken? Does it mean that I only need to use one of them?

**Example Code**
use CancelToken

```js
let source = CancelToken.source();
setTimeout(() => {
    source.cancel();
}, 3000);
return axios.get(ip + '/config', {cancelToken: source.token}).then((result) => {
    // My logic
})
```

use timeout

```
return axios.get(ip + '/config', {timeout: 3000}).then((result) => {
    // My logic
})
```

**Expected behavior, if applicable**
I think the results of the above two pieces of code are the same. Is that so?

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**

**Comment by TheNoim** [comment]
Timeout and canceltoken have different use cases. Timeout is really just for request timeouts. Canceltoken is used for any other reasone to cancel a request, like an user interaction.

**Comment by VigneshRamamoorthy1992** [comment]
@TheNoim @xiaobitipao 
Can you share an example on how to cancel a service request on user interaction.

scenario:
user'll be calling the same service asynchronously when a new request for the service is triggered the existing service request should cancel and returns only the new response 
Thanks!

**Comment by TheNoim** [comment]
Simple example. Hopefully it helps https://jsfiddle.net/thenoim/049nfae8/18/

**Comment by VigneshRamamoorthy1992** [comment]
@TheNoim 
Thanks a lot 
it worked !
