### ISSUE TITLE
Same 401 CORS problem in OPTIONS with basic Auth in a GET request 

### ISSUE THREAD

**Issue by atsoares** [axios/axios#2076]
Hi, I've already read all issues about this problem and nothing worked for me. I'm trying to use Basic Auth with username and password but it always get 401 Unauthorized.

So I have this axios.js file, referenced in the main.js, to call it just using this.$http.
```

import Vue from 'vue'
import axios from 'axios'

Vue.use({
  install(Vue) {
    Vue.prototype.$http = axios.create({
      baseURL: 'https://b2b.crednosso.com.br/wsservicos/atm/',
      timeout: 1000,
      auth: {
        username:'username',
        password:'password'
      },
      headers: {'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Credentials':'true',
              },
      withCredentials : true,
      crossDomain: true
    });
  }
})
```

I consume this api in another app using php and it works with no problem, but using axios with vuejs I get this 

> Access to XMLHttpRequest at 'https://b2b.crednosso.com.br/wsservicos/atm/listarAtmEstadoCidade' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

In my server I already have 
  ```
responseBuilder.header("Access-Control-Allow-Origin", "*");
responseBuilder.header("Access-Control-Allow-Credentials", "true");
responseBuilder.header("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS,POST,PUT");
responseBuilder.header("Access-Control-Allow-Headers", "Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization");
```

Someone can help me? The only solution that I've found is integrating with express or another framework.

**Comment by khamnh** [comment]
same here. +1

**Comment by xgui3783** [comment]
do you control b2b.crednosso.com.br ? because the `Access-Control-Allow-Origin` header needs to be set by the server, not the client. 

Since your GET request is [not a simple fetch request](https://stackoverflow.com/a/39067898/6059235) it will trigger preflight, and the browser will block the response unless the response header has suitable cors headers

Your php backend worked because CORS is typically only enforced by the browser. 

If you have the login credential, you may be able to craft a reverse proxy, which makes the same request server to server, and pass back the result.

**Comment by atsoares** [comment]
Yeah, as I showed I have `Access-Control-Allow-Origin` in the server side. So to better explain, I want to update an website, the original is in php, and I use httpful package to call the api and everything works. The new project I'm using vue js, only it, but when I use axios I can't call the api.

**Comment by xgui3783** [comment]
So old website used php, new website uses vue?

**Comment by atsoares** [comment]
Exactly, but the new website is a total new project. I just want to use the service that I already had and used on this project. There's no backend in here, just vue. Guess that I have to use express or something, to let axios work, right?

**Comment by xgui3783** [comment]
IMHO, there lies you problem. PHP is a backend technology, and it does not respect CORS origin headers. VueJS is a frontend technology, and the javascript is run in the browser. Browser enforces CORS origin headers, and will obfuscate responses unless correct headers are shown. 

You have a few options here:
1/ if you control b2b.crednosso.com.br, modify its backend, and add `Access-Control-Allow-Origin` header
2/ if you don't control the above endpoint, or you are unwilling to do that, you will need your own backend, acting as a proxy. You used php before, maybe reuse the code?

**Comment by atsoares** [comment]
Okay, in the backend of b2b.crednosso.com,br I already have this. 

`responseBuilder.header("Access-Control-Allow-Origin", "*");`
`responseBuilder.header("Access-Control-Allow-Credentials", "true");`
`responseBuilder.header("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS,POST,PUT");`
`responseBuilder.header("Access-Control-Allow-Headers", "Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization");`

So, this is not a server problem. As I guessed I just need to use a backend like express to use axios, because axios can't be used only with vue.

**Comment by xgui3783** [comment]
hmm, does plain js work? At least we can determine if it's an issue with VueJS/Axios

**Comment by atsoares** [comment]
nops, I tried to do by ajax only and I couldn't. Do you know if its possible to use axios only with vue? or do I really need to have a backend side? 

In my server I already have a CORSFilter lib, and it works in php, postman and also with ionic.

```
public class CORSFilter implements ContainerResponseFilter
{
	@Override
	public ContainerResponse filter(ContainerRequest containerRequest, ContainerResponse containerResponse)
	{
		ResponseBuilder responseBuilder = Response.fromResponse(containerResponse.getResponse());
			
		responseBuilder.header("Access-Control-Allow-Origin", "*");
		responseBuilder.header("Access-Control-Allow-Credentials", "true");
		responseBuilder.header("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS,POST,PUT");
		responseBuilder.header("Access-Control-Allow-Headers", "Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization");
		
		containerResponse.setResponse(responseBuilder.build());
		
		return containerResponse;
	}
}
```

**Comment by xgui3783** [comment]
hmm, can you inspect the network tab of chrome/FF tab? it might give you more info on why your requests are failing. 

FWIW, php is a server side language, and does not abide by CORS restrictions. IIRC, ionic builds target mobile? I have not used it, but perhaps it does not abide by CORS either.

**Comment by joshuaboltzmc** [comment]
I am currenrtly fighting these same issues.
It's my understanding that if you are passing an Authentication header, which you are in the `auth` section of the Axios call, that you cannot set the wildcard for Access-Control-Allow-Origin. It needs to be an explicit URL.

Here is my Axios call:
```
const getOptions = {
        method: 'get',
        url: `/${endpoint}`,
        auth: {
          username: process.env.BASIC_AUTH_USER,
          password: process.env.BASIC_AUTH_PWD,
        },
        withCredentials : true,
        crossDomain: true,
      }
      const { data } = await this.httpClient(getOptions)
```
this.httpClient is basically Axios.

I am doing pretty much the same type of response building technique, but in PHP, and have had no luck with it on a remote server. It does work locally, so I'm thinking there may be an issue with the OPTIONS method being disabled or something.

What i'm noticing is that my GET request gets turned into a 2 part process:
1) The preflight request (OPTIONS), which is where i encounter the 401 unauthorized. I think this is because I've read that OPTIONS strips out some headers, including the Authentication header, so without that, it can't authenticate
2) The "real" GET that actually returns the JSON from the API

**Comment by chasdevs** [comment]
Hitting this with the `fetch` API as well. Looking for a workaround that doesn't involve setting up a proxy server but may have to resort to that.

**Comment by chinesedfan** [comment]
> responseBuilder.header("Access-Control-Allow-Origin", "*");
responseBuilder.header("Access-Control-Allow-Credentials", "true");

Don't set them at the same time. See more about CORS in [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
