### ISSUE TITLE
formData limitation?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [axios/axios#2079]
Is there a limit on the number of formData parameters? Currently 211 is handled fine but 215 is crashing before the request is even sent.

**Comment by Alanscut** [comment]
post request has no limitation to request data in theory. I put 2000 key-values to formData and the request is successful.
```
  var data = new FormData();
  for(let i = 0; i < 2200; i++) {
    data.append("key-" + i, "value-" + i);
  }

  const instance = axios.create({
    baseURL: "http://localhost:3002",

  instance.post("/user/12345", data).then(response => {
    console.log("response -> ", response.data);
  });
```
