### ISSUE TITLE
React native - use fetch instead of XMLHttpRequest

### ISSUE THREAD

**Issue by cristianoccazinsp** [axios/axios#2081]
Would it be possible? 

I'm trying to download a very large JSON, and when using axios it is about 10 times slower than when using a plain old fetch + .json(). Furthermore, the whole UI freezes when using axios, while using fetch still allows the UI to behave smoothly.

I'm still trying to pinpoint the issue, but I'm suspecting that XMLHttpRequest and the whole response handling is very bad when compared to fetch.

**Comment by zmen** [comment]
I think you can try to write a custom `adaper` to switch to `fetch` if you want. The `adapter` is just the widget which defines how to send requests.
```javascript
import axios from 'axios'
// ... other configurations
if (shouldUseFetch) {
  axios.defaults.adapter = YOUR_CUSTOM_ADAPTER
}
// ... other configurations
export default axios
```

**Comment by gitlab-winnie** [comment]
@cristianoccazinsp There is already https://github.com/axios/axios/issues/1219.
