### ISSUE TITLE
`require('axios')` throws module not found when using AWS Lambda

### ISSUE THREAD

**Issue by krgutierrez** [axios/axios#2082]
**Describe the issue**
I am working on a AWS Lambda using NodeJs. On an existing repository, I added axios as dependency.

When importing axios, I encountered Module not found but when importing old dependency (tested it by importing aws-sdk), it doesn't encounter the issue.

I previously encountered the same issue when I was working on a different project (still AWS Lambda) but I encounter it when importing speakeasy.

Checking the node_modules directory, the axios directory exists.

NOTE: 
- Encountered same issue with yarn and npm 
- Tried adding lodash and I didn't encounter the issue. 
- Visual Studio Code and WebStorm detects axios 
- node-fetch encounters the same issue.

**Example Code**
`require('axios')`

**Expected behavior, if applicable**
axios should be retrieved/found and should not throw an error 

**Environment:**
 - Axios Version 0.18.0
 - OS: MacOS 10.14.3
 - Browser N/A
 - Browser Version N/A

**Comment by krgutierrez** [comment]
I found a solution and put it on the question I asked on `Stackoverflow`
https://stackoverflow.com/questions/55558502/module-not-found-when-new-dependency-is-installed/55612124#55612124

**Comment by annjawn** [comment]
@krgutierrez slightly off topic here, but you should be using Lambda Layers for managing node dependencies (node_modules) instead of uploading them with the function. https://medium.com/@anjanava.biswas/nodejs-runtime-environment-with-aws-lambda-layers-f3914613e20e

**Comment by krgutierrez** [comment]
> @krgutierrez slightly off topic here, but you should be using Lambda Layers for managing node dependencies (node_modules) instead of uploading them with the function. https://medium.com/@anjanava.biswas/nodejs-runtime-environment-with-aws-lambda-layers-f3914613e20e

I am using AWS SAM CLI for this so I don't upload them to the `Function`.

**Comment by annjawn** [comment]
> > @krgutierrez slightly off topic here, but you should be using Lambda Layers for managing node dependencies (node_modules) instead of uploading them with the function. https://medium.com/@anjanava.biswas/nodejs-runtime-environment-with-aws-lambda-layers-f3914613e20e
> 
> I am using AWS SAM CLI for this so I don't upload them to the `Function`.

Even with SAM CLI if you do not have `Type: AWS::Serverless::LayerVersion` resource in your SAM template, SAM Deploy will bundle up the node_modules directory with every function and deploy to Lambda.
