### ISSUE TITLE
 I request POST and axios request OPTION. The server give me 405 error.

### ISSUE THREAD

**Issue by mpadula1990** [axios/axios#2083]
i have a web API in .net core working. This waiting for a post request with a body in json and returns another json. This works correctly. I tried it with POSTMAN. I'm trying to do from react to the library axios to be able to make that request. But this for more than I is specifying a request of type POST sent by OPTIONS and the WEB API sent me an error 405.

I have a configuration file in JSON format and then I use it from a service.

JSON FILE:

```
{
    "API_PATH": "https://localhost:44320",
    "LOGIN_API": "/api/Auth"
}
```
INSTANCE:

```
this.instance = axios.create(
            {
                baseURL: config.API_PATH,
                withCredentials:true,
                timeout: 10000,
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json',
                }
            }
        );
        axiosRetry(this.instance, { retries: 2, retryDelay: (retryCount) => 500 });
    }
```
INSTANCE USE:

```
login(user) {
    return this.instance.post(config.LOGIN_API, user);
  }
```
Error: 405
The react app run in localhost:3000 and the WEB api run in localhost 4430

I am looking for the WEBAPI to send me its answer correctly. Sory for my bad english.

**Comment by zmen** [comment]
Seems you just encounter a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) problem, you can check this article [Preflight Request - MDN](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request).

**Comment by satanbaby** [comment]
Maybe the problem with the .net core
https://stackoverflow.com/questions/31942037/how-to-enable-cors-in-asp-net-core

**Comment by chinesedfan** [comment]
> Seems you just encounter a CORS problem, you can check this article Preflight Request - MDN.

Yes, please check @zmen's answer.
