### ISSUE TITLE
Post request returns empty data with 200 code, but Postman sends data

### ISSUE THREAD

**Issue by Jakuubzmeko** [axios/axios#2084]
**Issue**
When I make POST request through Postman, I get normal data as I need. But when using axios for react native, I get empty data but request says 200. Also when using fetch, it returns data but not in axios. 

```
var data = {
      username: "mail@mail.com",
      password: "123456",
    };

 axios({
      url: "https://api.scrumdesk.com/auth?15",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      data: data
    }).then(response => {
      console.log(response)
    }).catch(error => {
      console.log(error);
    });
```

It returns this:
![Snímka obrazovky 2019-04-08 o 14 01 45](https://user-images.githubusercontent.com/49398874/55722540-dfa5cf00-5a06-11e9-8084-bbaa80f9c33b.png)

**Environment:**
 - Axios Version [ 0.18.0]
 - OS: [iOS 12.1.0]
 - Browser [React Native]
 - Browser Version [e.g. 22]
 - Additional Library Versions [React 16.6.3, React Native 0.58.6]

**Comment by Jakuubzmeko** [comment]
Problem was that eventhough I set ```headers: {
        "Content-Type": "application/json",
      },``` but server was not reading json. I changed my url from ```https://examplek.com/auth``` to ```https://examplek.com/auth.json```

**Comment by krakzk** [comment]
I am facing the same issue when i try a post call. I generate a token using O2Authentication and then use the token to post a request using my RN app. This returns 200 with all info but the data is empty. Checked server side and it shows that the complete response was sent back from server. Also the response is complete and success while trying with postman.
Used with RN-0.59.3
O2Auth was with react-native-ms-adal

**Comment by jasonsaayman** [comment]
This seems to be server side, you could test it with something like postman and see if the same behaviour presents.
