### ISSUE TITLE
Unable to send file streams correctly or readable streams created from existing buffer

### ISSUE THREAD

**Issue by Zebirdman** [axios/axios#2089]
**Describe the issue**
I am trying to use axios to upload a file stream to the bullhorn api. I have looked through the many examples on your site to try and get this working but no matter what i do the best i can get is either a 400 bad file uploaded with stream ended unexpectedly or a 400 no file uploaded (see examples below)

**Example Code 1**
I have tried to upload using my file stream like this. The reason i am using the formData object like this is that it seems to do a nice job of creating the content type header for me (plus i was playing around trying to use it directly as you will see below). Sending the request this way results in a 400 no file uploaded error. According to some examples here https://github.com/axios/axios/issues/961 this should work.

```js
async function parseToHtml(url, token) {
  const readStream = fs.createReadStream("file.docx");
  const { size } = fs.statSync("file.docx");
  
  const data = new FormData();
  const head = data.getHeaders();
  head["Content-Length"] = size;

    try {
      const result = await axios({
        url: `${url}resume/convertToHtml?BhRestToken=${token}&format=docx`, 
        method: "POST",
        data: readStream, 
        maxRedirects: 0,
        headers: {
          "Content-Type": head["content-type"],
          "Content-Length": size
        }
      });
      return result;
    } catch (err) {
      return err;
    }
}
```

**Example Code 2**
Following on from some other examples and from what i can see here https://github.com/axios/axios/pull/296 this should also work. However this results in a 400 stream ended unexpectedly error. I add the content length to my header object as if i leave it out i get a length required 411 response instead.

```js
async function parseToHtml(url, token) {
  const { size } = fs.statSync("file.docx");
  const data = new FormData();
  data.append("file", fs.createReadStream("file.docx"), "file.docx");
  const head = data.getHeaders();
  head["Content-Length"] = size;

    try {
            const result = await axios.post(`${url}resume/convertToHtml?BhRestToken=${token}&format=docx`, data, { headers: head });
        }
      });
      return result;
    } catch (err) {
      return err;
    }
}
```

**Example Code 3**
More importantly what i actually want but havent been able to even get close to is to use a existing buffer as my input. I tried the example at https://github.com/axios/axios/issues/2049 with no luck with a buffer created from a base 64 encoded string sent to our api and decoded like this.

```js
  const decodedBuffer = Buffer.from(fileContent, "base64");
```

**Example Code 4**
I have also tried using query string as that apparently is a solution that has worked for some people see https://github.com/axios/axios/issues/1006.

```js
   const result = await axios.post(`${url}resume/convertToHtml?BhRestToken=${token}&format=docx`, queryString.stringify(data), { headers: head });
```

My colleague has had success with the older request library and i have been able to use bhttp to easily send and receive file streams. If there is no easy solution for this is anyone able to point me to a good resource for handling js readable streams in http requests? it seems every resource i can find shows sending file streams or simply piping around readable streams to stdin and stdout yet there seems to be a real lack of resources for creating streams from buffers, sending via http and then buffering and streaming the response to another api endpoint. Thankyou

**Expected behavior, if applicable**
file read stream is uploaded correctly, or even better a readable stream can be handled directly by axios.

**Environment:**
 - Axios Version: 0.18.0,
 - OS: windows 10
 - Node version: 11.1.0

**Comment by Zebirdman** [comment]
also doing this using straight buffers with request is a piece of cake. You can easily 
```  js
async function parseToCandidate(restToken, buffer) {
  const formData = {
    file: {
      value: buffer,
      options: {
        filename: "resume.html"
      }
    }
  };
  return new Promise( async(resolve, reject) => {
    request.post({ url: `${restToken.restUrl}resume/parseToCandidate?format=html&BhRestToken=${restToken.BhRestToken}`, formData: formData }, function(err, res, body) {
      if (err) {
        reject(err);
      }
      resolve(res);
    });
  });
}

async function parseToHtml(restToken, buffer) {
  const formData = {
    file: {
      value: buffer,
      options: {
        filename: "resume.docx"
      }
    }
  };
  return new Promise( async(resolve, reject) => {
    request.post({ url: `${restToken.restUrl}resume/convertToHtml?format=docx&BhRestToken=${restToken.BhRestToken}`, formData: formData }, function(err, res, body) {
      if (err) {
        reject(err);
      }
      resolve(body);
    });
  });
}
(async () => {
  const bitmap = fs.readFileSync(file);
  const buffer = new Buffer(bitmap).toString('base64');
  const decodedBuffer = Buffer.from(fileContent, "base64");

  const restToken = await authenticateBullhorn();
  const body = await parseToHtml(restToken, decodedBuffer);
  const result = await parseToCandidate(restToken, Buffer.from(body, "utf8"));
}();
```

**Comment by JBtje** [comment]
Example 3 works... please provide the full code you used, so I can see whats going wrong.

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
