### ISSUE TITLE
chrome how to forbidden webpack axios sourcemap 

### ISSUE THREAD

**Issue by jackieli123723** [axios/axios#2091]
**Describe the issue**
A clear and concise description of what the issue is.

**Example Code**
Code snippet to illustrate your question

```js
// chrome how to forbidden webpack axios sourcemap ？ 
```
![axios](https://user-images.githubusercontent.com/10346511/55866975-1705ae80-5bb4-11e9-859c-fdc998344fc0.png)

**Expected behavior, if applicable**

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It is not an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).
