### ISSUE TITLE
GET API CALL data sometimes empty

### ISSUE THREAD

**Issue by LarsVlyminckx** [axios/axios#2093]
When I'm doing a GET API call, the body is sometimes empty (1/15 chance). The data has been send from the server but when I did the call the response data was empty. 

```js
function getBasicSuccessFactorsAPI(endpoint = "", expand = "", filter = "", select = "", timeout = 0) {
    var fullURL = `${config.SUCCESSFACTORS.API_URL}/${endpoint}?$format=JSON`
    if (expand !== "") {
        fullURL += `&$expand=` + expand
    }
    if (filter !== "") {
        fullURL += `&$filter=` + filter
    }
    if (select !== "") {
        fullURL += `&$select=` + select
    }
    return axios.get(fullURL + '&$top=10', {
            auth: {
                username: `${config.SUCCESSFACTORS.USERNAME}@${config.SUCCESSFACTORS.COMPANY}`,
                password: config.SUCCESSFACTORS.PASSWORD
            },
            timeout: timeout,
        })
        .then(response => {
            return response;
        })
        .catch(error => {
            logger.error(error);
            throw error;
        })
}
```

**Expected behavior, if applicable**
Not empty data response. 

**Environment:**
 - Axios Version 0.18.0
 - OS: Windows 10

**Comment by Zohaad97** [comment]
@LarsVlyminckx I also faced this issue. I think its CORS or CORB issue. Not sure but in my case it was CORB

**Comment by LarsVlyminckx** [comment]
How can I fix this? Do I need to ADD something?

**Comment by Zohaad97** [comment]
@LarsVlyminckx you can set headers in your request. See the example

```
axios.get('http://www.google.com', {headers: {'Content-Type':'application/json','Access-Control-Allow-Origin': '*'}})
  .then(function(res) {
    console.log(res);
  }).catch(function(err) {
    console.log(err);
  });
```
You can use a dirty hack using "Moesif Origins & CORS Chrome extension".

**Comment by LarsVlyminckx** [comment]
Thanks! I will try it. I'll keep you informed.

**Comment by LarsVlyminckx** [comment]
It still happens sometimes but less frequently.

**Comment by jakebolam** [comment]
We're also seeing this. Responses are from a Google Cloud Load Balancer, talking to GKE.

@shiny, @LarsVlyminckx just to rule out backend servers, what are you running on?
