### ISSUE TITLE
GET request is returning 'undefined' for some properties while having a value in XHR response

### ISSUE THREAD

**Issue by SDVII** [axios/axios#2095]
**Description**
When making a GET request, the XHR response inspected in the browser's developer tools has a value of '0' for a certain property, but when logged inside the Nuxt application, the same property is returned as 'undefined'

**To Reproduce**
The code is summarized as the following
```js
import client from '~/services/client'
import Cookies from 'js-cookie'
export default class Me {
  constructor(token = Cookies.get('token')) {
    this.config = {
      headers: { Authorization: 'Bearer ' + token },
    }
  }

 getOrders(params) {
    return new Promise((resolve, reject) => {
      client
        .get(`/me/orders`, {
          headers: this.config.headers,
          params,
        })
        .then(result => {
          resolve(result)
        })
        .catch(err => {
          reject(err.response)
        })
    })
  }
}
```
In Chrome's Dev Tools:
```js
{
  ...
  remainingVolume:0
}
```
However, when logging it:
```js
mounted: async function() {
    const me = new Me()

    this.orders = (await me.getOrders({
      status: this.isFiltered ? 'history' : 'open',
    })).data

    console.log(this.orders);
  }
```
the logged result is returned like this (Only in Firefox):
```js
{
  ...
  remainingVolume: undefined
}
```
All the other properties are matching

**Expected behavior**
All the properties returned in the XHR response should be the same as the one Axios is returning the response object 

**Environment:**
 - Axios Version 0.18.0
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 66.0.3 (64-bit)
 - Additional Library Versions: Nuxt 2.0

**Comment by jonnypolite** [comment]
Just to be clear, `import client from '~/services/client'` is importing Axios?

**Comment by SDVII** [comment]
Yes

**Comment by doepkec** [comment]
We encountered the same issue and found out, if you check the console.log it showed undefined instead of "0" and "false" values, but when you check the vue developer tool it shows the right values. So we think that console.log just prints the wrong values

**Comment by reki630** [comment]
Same question in React,I can't get the value I need

**Comment by chinesedfan** [comment]
@SDVII @doepkec @reki630 Can someone provide screenshots?

**Comment by SDVII** [comment]
I am afraid the code regarding this issue has long been replaced, but I'll see if I can reproduce it.

**Comment by chinesedfan** [comment]
Closed due to not reproducible. Feed free to open a new one if someone met again.
