### ISSUE TITLE
Please fix this bug: "Content-Type application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by kickgod** [axios/axios#2097]
Please fix this bug: "Content-Type application/x-www-form-urlencoded"   

It's 2019 now.  

This greatly reduces the user experience.

Post request parameters need to be resolved

**Comment by fasalir** [comment]
hello, do you already have solution about this?

**Comment by chinesedfan** [comment]
Closed due to lack of enough information. If it is still there, feel free to open a new issue with the required template.
