### ISSUE TITLE
Documentation Request: typescript example for axios instance and async await

### ISSUE THREAD

**Issue by SumNeuron** [axios/axios#2098]
**Section/Content To Improve**
in the readme there is an example of how to set up an instance:
```js
axios.create({
  ...
})
```

as well as how to use async/await with axios

```js
async fetch() {

  try {
    await axios.get(...)
  }
  catch (error) {
    //...
  }
}
```

It would be nice to have a typescript example as well

**Suggested Improvement**
I do not see any typescript documentation on how to do this.

**Relevant File(s)**: [e.g. README.md]

**Comment by rrdlpl** [comment]
```
public async find(...): Promise<MyType> {
    try {
      const response = await this.axios.get<{ result: MyType }>(
...
      );
      return response.data.result;
    } catch (error) {

    }
  }
```

**Comment by mshez** [comment]
Wow this issue open since last year. No input at all.
