### ISSUE TITLE
Can not set Content-Type with Authorization header

### ISSUE THREAD

**Issue by max-eb** [axios/axios#2099]
**Describe the bug**
I want to send a post request to back-end service with custom 'Content-Type': text/plain. But I find something strange. If I wasn't in logged-in state, the post request without a Authorization header, it worked as expected. If I logged in the application, every request had a Authorization header and the Content-Type would always be 'application/x-www-form-urlencoded' even if I set header 'Content-Type: text/plain' explicitly.

```js
This is my post request method:
export function createResource(resource, payload) {
  let options = {
    url: getUrl(resource),
    method: 'POST',
    data: payload,
    headers: {
      'Content-Type': ((typeof payload) === 'string') ? 'text/plain' : 'application/json',
    },
    withCredentials: true,
  };
  options = addTokenIfExists(options);
  return axios(options)
    .then(response => processResponse(response))
    .catch(exception => processException(exception));
}
```
And the addTokenIfExists method:
```
const addTokenIfExists = (options) => {
  const idToken = getIdToken();
  if (idToken) {
    return {
      ...options,
      headers: {
        Authorization: `Bearer ${idToken}`,
      },
    };
  }
  return options;
};
```
This is the full request header with Authorization header. In this situation, the 'Content-Type' header will always be 'application/x-www-form-urlencoded' even if I set 'Content-Type: text/plain' explicitly.
```
:authority: HOST
:method: POST
:path: PATH
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: Bearer JWT_TOKEN
cache-control: no-cache
content-length: 24
content-type: application/x-www-form-urlencoded
cookie: _vwo_uuid_v2=DB313821DEFE9682C6701C78A2893AD6E|493aa92b705308c45a8f28c87bd16bc4; _vwo_uuid=DB313821DEFE9682C6701C78A2893AD6E; _ga=GA1.2.385205587.1548185494; _vis_opt_s=21%7C; _vwo_ds=3%3Aa_1%2Ct_1%3A0%241554172480%3A77.26003484%3A%3A%3A3_1%2C2_1; JSESSIONID=5E012F6A9AC29FCFC70B0EF63EEB1318
dnt: 1
origin: ORIGIN
pragma: no-cache
referer: REFER
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
```

**Expected behavior**
The 'Content-Type' header should always be what I set.

**Environment:**
 - Axios Version: 0.18.0
 - OS:Linux maxh 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Browser Chrome
 - Browser Version: 68.0.3440.84 (Official Build) (64-bit)
 - Additional Library Versions: React 16.8.2

**Comment by Gerigot** [comment]
I think it's not a bug but you're overriding all the headers with your function addTokenIfExists.

Try this:

const addTokenIfExists = (options) => {
  const idToken = getIdToken();
  if (idToken) {
    return {
      ...options,
      headers: {
        ...options.headers,
        Authorization: `Bearer ${idToken}`,
      },
    };
  }
  return options;
};

**Comment by max-eb** [comment]
@Gerigot Thanks, it's my fault, sorry.
