### ISSUE TITLE
How to execute api calls completely in a queue even get error?

### ISSUE THREAD

**Issue by imakou** [axios/axios#2100]
Hi all,
I have a question:
How to execute API calls completely in a queue even get error??

For example. I have to POST 5 users' data to the server by using Axios.
Let assume that there is a potential format issue on 3rd user's data and the server will return 400 for this request.

In reality, axios won't continue to execute the rest of API calls (4, 5 users posting tasks).
How to make sure axios can complete the rest of posting tasks?

Thanks.

**Comment by blnk-space** [comment]
Hey!  This isn't an issue with axios in itself.

You could use async...await in the following fashion (just a frivolous example)

`
// array of returned promises running in paraller
const reqArray = [axios.post(...), axios.post(...), axios.post(...)];

const resultArray = await reqArray.map(async (item) => {
  const result = await item;
  return result;
});
`

**Comment by imakou** [comment]
update:
I define a function to handle async/ await and run it in a try catch block.
So, that makes sure even if an error happened won't cut the whole process.
