### ISSUE TITLE
Add entire response as 2nd param of validateStatus

### ISSUE THREAD

**Issue by marceloadsj** [axios/axios#2109]
**Is your feature request related to a problem? Please describe.**
The backend we are using now don't trigger errors using response.status, just using response.data.status, then I would like to check this information in axios to throw errors on frontend.

**Describe the solution you'd like**
```javascript
validateStatus: (status, response) => {
// passing down the entire response object as the second param can solve the problems like this
// then we can use response.data (or even another field) to throw
}
```

**Describe alternatives you've considered**
For now I created a wrapper function that throw errors validating the response.data.status

**Additional context**
An example of validateStatus implementation could be:
```javascript
validateStatus: (status, response) => {
  return !response.data || (response.data.status >= 200 && response.data.status < 300);
}
```
This throw errors based on body.status, not header.status field!

PS: I think it's better to pass as second arg to not have a Breaking Change!

**Comment by sergioregueira** [comment]
I think [interceptors](https://github.com/axios/axios#interceptors) is what you are looking for.

**Comment by marceloadsj** [comment]
Great, I didn't know about that, I will take a look.

I will close for now, and if don't manage to use interceptor by any reason, I can reopen or comment here!
