### ISSUE TITLE
How get error certificate instead netwirk error

### ISSUE THREAD

**Issue by KonovalovaKV** [axios/axios#2110]
**Describe the issue**
How to get a certificate error instead of a general network error in interceptors response error?

**Environment:**
 - Axios Version 0.18.x
 - OS: -

**Comment by KonovalovaKV** [comment]
Any news?

**Comment by chinesedfan** [comment]
You can try to print the error message. If there was no special pattern, I am afraid hard to get a certificate error.

Closed due to it is not an issue of axios, but feel free to remind me if you got further discoveries in Google or stackoverflow or anywhere else.
