### ISSUE TITLE
utils.isFormData() has bug in NWJS

### ISSUE THREAD

**Issue by phpjungle** [axios/axios#2114]
```
/**
 * Determine if a value is a FormData
 *
 * @param {Object} val The value to test
 * @returns {boolean} True if value is an FormData, otherwise false
 */
function isFormData(val) {
  // return (typeof FormData !== 'undefined') && (val instanceof FormData); // there is a bug in NWJS
  return "[object FormData]" === Object.prototype.toString.call(val);; // this will okay in NWJS

}
```
![WeChatWorkScreenshot_77c83259-e54a-49ac-85e9-0ad7f0391d72](https://user-images.githubusercontent.com/8136745/56790968-8d531380-6838-11e9-99ad-5c4cce1672f4.png)

**Comment by Alanscut** [comment]
I tested it in nwjs-sdk-v0.42.6-win-x64 and don't found this bug. Please check whether it has been fixed in the new version.

BTW, your updating for `isFormData` looks good to me :+1:
