### ISSUE TITLE
Axios njson

### ISSUE THREAD

**Issue by Olegars** [axios/axios#2116]
Hi
is there a way to get request by type njson?
for instance:
Request Body
*{"index":"shopping","type":"_doc"}
{"query":{"bool":{"must":[[{"match":{"term.id":2}}]]}},"aggs":{"brand":{"terms":{"field":"brand"}},"male":{"terms":{"field":"male"}},"color":{"terms":{"field":"variation.color.hex"}},"size":{"terms":{"field":"variation.attributes.size"}}},"size":24}
{"index":"catalog","type":"_doc"}
{"query":{"match":{"parent":2}},"from":0,"size":50}*

**Comment by Alanscut** [comment]
Do you mean the request parameters are nested json?  Could you decribe the issue more clearly?
