### ISSUE TITLE
error not wrapped by createError in some case

### ISSUE THREAD

**Issue by zengjialuo** [axios/axios#2117]
**Describe the issue**
so sometimes error.config is lost

**Example Code**
Code snippet to illustrate your question

```js
http.interceptors.response.use(null, function (error) {
    // can i expect error.config is not undefined?
}
```

**Comment by chinesedfan** [comment]
It depends on which kind of error is thrown. If it is an unexpected error that is not thrown by axios, it will not be wrapped.
