### ISSUE TITLE
What is the proper way to debounce/throttle axios request ?

### ISSUE THREAD

**Issue by qiulang** [axios/axios#2118]
Say I have this simple requirement that a user is only allowed to make 1 request per n second. What is proper/simple to debounce/throttle a axios request.

I saw this question has been raised a couple of times but without a clear answer.  

https://github.com/axios/axios/issues/230 suggested to do it with interceptors
https://github.com/axios/axios/pull/1135 talking about https://github.com/kuitos/axios-extensions, but no further action.

The similar questions were asked at stackoverflow, but also without good answers in my opinion, e.g
https://stackoverflow.com/questions/43482639/throttling-axios-requests
https://stackoverflow.com/questions/39809844/using-lodashs-debounce-on-axios-request-produces-unexpected-result

I can come up with some home-made solution but I would like to see what is the recommended way to do that ?

Thanks!

**Comment by AWR14** [comment]
I'm looking for a solution to this i currently have calls like this

```
fetch = async loaderType => {
    try {
      const response = await axios.post(this.props.apiUrl, {
        limit: this.state.limit,
        skip: this.state.skip
      });

      this.setState({
        data: response.data.items
      });
    } catch (error) {
      message.error(`${error}`);
    }
  };
```

@qiulang did you find away of using debounce or throttle?

**Comment by qiulang** [comment]
I had a discussion at SO https://stackoverflow.com/questions/55919714/my-implementation-of-debounce-axios-request-left-the-promise-in-pending-state-fo
See if that works for you.

**Comment by chinesedfan** [comment]
Yes, we suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues.
