### ISSUE TITLE
axios.put method is not working with async/await 

### ISSUE THREAD

**Issue by yilmazbingo** [axios/axios#2122]
`import React, { Component } from "react";
import "./App.css";
import axios from "axios";

const apiEndpoint = "http://localhost:5000/api/customers";

class App extends Component {
  state = {
    posts: []
  };
  async componentDidMount() {
    const { data: posts } = await axios.get(apiEndpoint);
    this.setState({ posts });
  }

  handleAdd = async () => {
    const obj = { name: "lese", isGold: false, phone: "345-456-4555" };
    const { data: post } = await axios.post(apiEndpoint, obj);
    console.log("urry");
    const posts = [post, ...this.state.posts];

    this.setState({ posts });
  };

  handleUpdate = async post => {
    post.name = "zero";
    //for some reason async/await is not working with put method
    await axios.put(`${apiEndpoint}/${post._id}`, post);

    const posts = [...this.state.posts];
    const index = posts.indexOf(post);

    posts[index] = { ...post };

    this.setState({ posts });
  };

  handleDelete = async post => {
    await axios.delete(`${apiEndpoint}/${post._id}`);
    const posts = this.state.posts.filter(p => p._id !== post._id);
    this.setState({ posts });
  };

  render() {
    return (
      <React.Fragment>
        <button className="btn btn-primary" onClick={this.handleAdd}>
          Add
        </button>
        <table className="table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
            {this.state.posts.map(post => (
              <tr key={post._id}>
                <td>{post.name}</td>
                <td>
                  <button
                    className="btn btn-info btn-sm"
                    onClick={() => this.handleUpdate(post)}
                  >
                    Update
                  </button>
                </td>
                <td>
                  <button
                    className="btn btn-danger btn-sm"
                    onClick={() => this.handleDelete(post)}
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </React.Fragment>
    );
  }
}

export default App;
`
In handleUpdate function, using the "async\await"  is not working. However if I write the function:
`handleUpdate = post => {
    post.name = "zero";
    //for some reason async/await is not working with put method
    axios.put(`${apiEndpoint}/${post._id}`, post);

    const posts = [...this.state.posts];
    const index = posts.indexOf(post);

    posts[index] = { ...post };

    this.setState({ posts });
  }; 
update button in the table is working..
`

**Comment by chinesedfan** [comment]
@yilmazbingo Change your `onClick` handle as an async function, too.
