### ISSUE TITLE
Allow disable cookies

### ISSUE THREAD

**Issue by abenfica** [axios/axios#2125]
I am trying to send a request without forwarding cookies and I can't do it with axios.
I did it with fetch where cookies are disabled by default.

Using axios 0.18 with React

Is it possible to completely disable cookies or specify exactly the ones I want to forward in a request?

**Comment by shirshendubhowmick** [comment]
@abenfica There is a feature called `withCredentails`, which allow or restrict cookies. Is it possible to share your code ? Will help us to understand what you are trying to achieve

**Comment by kevilen** [comment]
I use axios.create({ withCredentials: true })  some where, but when I use axios.create({ withCredentials: false })  does not work...

**Comment by Alanscut** [comment]
hi @kevilen , I found that `axios.create({ withCredentials: false }) ` take effect in my server https://github.com/axios/axios/issues/2455#issuecomment-551056138 , could you provide more information? so I could do futher investigation.

**Comment by yasuf** [comment]
closing stale issue, let's reopen if we get more info on this

**Comment by zyd** [comment]
https://github.com/axios/axios/issues/2472
