### ISSUE TITLE
Cannot run tests locally

### ISSUE THREAD

**Issue by tskimmett** [axios/axios#2127]
If we want to contribute, are expected to be able to run tests locally? I tried for quite some time to get karma to work but it did nothing except fail to open any browsers.

```bash
03 05 2019 13:34:32.910:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
03 05 2019 13:34:32.912:INFO [launcher]: Launching browsers Firefox, Chrome, Safari, Opera with unlimited concurrency
03 05 2019 13:34:32.921:INFO [launcher]: Starting browser Firefox
03 05 2019 13:34:33.144:INFO [launcher]: Starting browser Chrome
03 05 2019 13:34:33.166:INFO [launcher]: Starting browser Safari
03 05 2019 13:34:33.167:INFO [launcher]: Starting browser Opera
03 05 2019 13:34:33.211:ERROR [launcher]: No binary for Safari browser on your platform.
  Please, set "SAFARI_BIN" env variable.
```

`CHROME_BIN` is set to my chrome executable.

**Comment by jasonsaayman** [comment]
@tskimmett can you let us know what OS you are testing on, this will help me to start seeing how I can assist.

Thanks

**Comment by tskimmett** [comment]
I was trying to run on Windows 10. It looked like the hosted CI was failing at the time too, so it may have been fixed by now.

**Comment by jasonsaayman** [comment]
@tskimmett please, can you run it again and then let me know? I don't currently have access to a Windows 10 machine, so I would only be able to run this tomorrow.

**Comment by chinesedfan** [comment]
> Please, set "SAFARI_BIN" env variable.

Closed due to stale.
