### ISSUE TITLE
[Community Contest] A logo for Axios

### ISSUE THREAD

**Issue by richiksc** [axios/axios#2130]
Axios has grown to become a popular library with over 3 million weekly downloads on npm. I think it's time axios has its own logo, just like many other major libraries out there. I've designed a concept for the logo, and I hope you guys like it.

![Page 1](https://user-images.githubusercontent.com/8939680/57233882-20344080-6fe5-11e9-9086-d20a955bed59.png)
![Page 2](https://user-images.githubusercontent.com/8939680/57233883-20344080-6fe5-11e9-8169-1eeb4c782683.png)
![Page 3](https://user-images.githubusercontent.com/8939680/57233884-20344080-6fe5-11e9-8df3-0df1282e1574.png)

The logo is based on the concept of request and response. The first one is a square icon/profile picture. The second and third are full logos. These images are not full size, so if you do like them and plan to use them, I can send you the full sized files.

**Edit:** Should we count 👍 reactions to this parent comment as votes for this logo submission, or just people in favor of a new logo in general? I can make a a second comment for votes for this submission, or we can do a proper poll with strawpoll later when people are done submitting their ideas.

**Comment by Leomv55** [comment]
The last one is pretty neat.. :1st_place_medal:

**Comment by pchaganti** [comment]
The last one!

**Comment by richiksc** [comment]
Here is a Google Drive link to the full-size files of the last one and a square version for the GitHub organization icon:

https://drive.google.com/drive/folders/1MeVI0ThgZ99BFBBxYmboI1rVKjKR9U3o?usp=sharing

**Comment by borisBelloc** [comment]
still no official logo ? 😕
I like the last one you made

**Comment by man0s** [comment]
The last one is 🔥

**Comment by jasonsaayman** [comment]
@richiksc do we have your express permission to use these? We would like to get branding up on the repo and some other places.

**Comment by richiksc** [comment]
@jasonsaayman Yes you have my permission. If there's any where contributors are listed, is it ok if I am mentioned?

**Comment by jasonsaayman** [comment]
Thanks @richiksc we will add something like this to the repo's readme or the new site we have in the pipeline. Can you tell me which font you used?

**Comment by richiksc** [comment]
I used D-DIN Regular from https://www.fontsquirrel.com/fonts/d-din, which is licensed under the SIL Open Font License v1.1.

**Comment by jasonsaayman** [comment]
Thanks :)

**Comment by NotMoni** [comment]
Hey guys. Is this logo finalized or can I sumbit a design ?

**Comment by jasonsaayman** [comment]
@NotMoni sure please submit one :)

**Comment by NotMoni** [comment]
Here is my first sketch. 

![Artboard 1](https://user-images.githubusercontent.com/40552237/85735357-9608d900-b6cb-11ea-98ea-93deeccfb455.png)


I want to incorperate a rocket somewhere here, which symbolizes speed.

**Comment by jasonsaayman** [comment]
I like it. Can you give a version with the 'rocket' would be cool to see cause that would give a fuller idea of what it would look also if you had a icon with just the rocket which is square that would be awesome.

Exited to see what it looks like.

**Comment by NotMoni** [comment]
@jasonsaayman I will make 3 designs.

1.) Just the rocket.
2.) replace the `I` in `A X I O S` with the 🚀 
3.) Place the rocket with the name.

**Comment by Leomv55** [comment]
> Here is my first sketch.
> 
> I am trying to make it very minimal...
> 
> ![Artboard 1](https://user-images.githubusercontent.com/40552237/85735357-9608d900-b6cb-11ea-98ea-93deeccfb455.png)
> 
> I want to incorporate a rocket somewhere here, which symbolizes speed.
> 
> Any feedback will be appreciated.



> @jasonsaayman I will make 3 designs.
> 
> 1.) Just the rocket.
> 2.) replace the `I` in `A X I O S` with the 
> 3.) Place the rocket with the name.

Maybe option 2 will make more sense than the other two.

**Comment by richiksc** [comment]
@jasonsaayman Should we make it an 'official' contest, open it up to community submissions for logos, and then hold a community vote to see which logo wins? I'd love to see more people's ideas for an axios logo.

**Comment by NotMoni** [comment]
Yep, that I am more inclined to do that.

**Comment by NotMoni** [comment]
> @jasonsaayman Should we make it an 'official' contest, open it up to community submissions for logos, and then hold a community vote to see which logo wins? I'd love to see more people's ideas for an Axios logo.

We should pin this issue to have a contest.

**Comment by NotMoni** [comment]
The picture with the most 👍 wins?

**Comment by borisBelloc** [comment]
> Here is my first sketch.
> 
> I am trying to make it very minimal...
> 
> ![Artboard 1](https://user-images.githubusercontent.com/40552237/85735357-9608d900-b6cb-11ea-98ea-93deeccfb455.png)
> 
> I want to incorporate a rocket somewhere here, which symbolizes speed.
> 
> Any feedback will be appreciated.

it make me think of VALVe logo 😥

![valve logo](
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Valve-logo.jpg/1200px-Valve-logo.jpg)

**Comment by NotMoni** [comment]
> > Here is my first sketch.
> > I am trying to make it very minimal...
> > ![Artboard 1](https://user-images.githubusercontent.com/40552237/85735357-9608d900-b6cb-11ea-98ea-93deeccfb455.png)
> > I want to incorporate a rocket somewhere here, which symbolizes speed.
> > Any feedback will be appreciated.
> 
> it make me think too much of VALVe logo 😥
> 
> ![valve logo](https://camo.githubusercontent.com/c56e08861d0112f479ab93edcde10dab69d3b58b/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f362f36632f56616c76652d6c6f676f2e6a70672f3132303070782d56616c76652d6c6f676f2e6a7067)

Wow. I didn't know a logo like that existed.

**Comment by NotMoni** [comment]
Here are the two versions. 

**I think I should make a better rocket.**

![Artboard 1f](https://user-images.githubusercontent.com/40552237/85750411-acb52d00-b6d7-11ea-996d-26e6836a4478.png)

** Rocket Straight Up **
![forwardArtboard 1f](https://user-images.githubusercontent.com/40552237/85750419-ade65a00-b6d7-11ea-9c9a-05e60771cd0f.png)

**Comment by jasonsaayman** [comment]
> @jasonsaayman Should we make it an 'official' contest, open it up to community submissions for logos, and then hold a community vote to see which logo wins? I'd love to see more people's ideas for an axios logo.

Ok cool lets do this. Issue is pinned.

**Comment by richiksc** [comment]
@NotMoni apologies for the unsolicited feedback, but if you don't mind, I would try bringing down the crossbar of the uppercase 'A' more to open up the letter (I'm assuming the typeface is hand-drawn, but it might not be), and trying a single stroke instead of a double stroke on the rocket icon. And it might be just me, please, correct me if others don't experience the same thing, but it's hard to read it as 'Axios' with the rocket in the center replacing the I since the rocket doesn't really read as an 'I' that much (at least the current icon). You could try the rocket off to the side.

**Comment by NotMoni** [comment]
@richiksc Hey. Thanks for the feedback. Could you contact me on discord if you have it, 'I would love to talk to you about your and logo and some design stuff' ?

`M O N I#1410`

**Comment by borisBelloc** [comment]
the rocket is fun but people won't understand that it mean 'AXIOS"

**Comment by sudomann** [comment]
I agree @borisBelloc, perhaps the rocket ought to be a slimmer tube, without the fins/skirt at the bottom

**Comment by NotMoni** [comment]
I will work on that :D

**Comment by 4o4forbidden** [comment]
Both logos with rockets are beautifull, i suggest adding a related touch someting near to arrows or something explains data requests / responses. 
Cheers !

**Comment by NotMoni** [comment]
Sure, Mate. I just need a few more days and will have the update ready.

**Comment by richiksc** [comment]
@jasonsaayman Sorry, I gave you the wrong font. I actually used Bahnschrift which is a system installed font on Windows machines, however, I don't know the license for that. The design will probably work in D-DIN if Banschrift presents licensing issues.

**Comment by marsnebulasoup** [comment]
You can replace the "I" in the B&W logo with the arrow from the first logo (but maybe a different color?):

![Logo](https://user-images.githubusercontent.com/52974834/87588020-98e26280-c6a8-11ea-92c9-c3a48789e2c7.png)

**Comment by marsnebulasoup** [comment]
There is also this:

![Logo](https://user-images.githubusercontent.com/52974834/87589912-99c8c380-c6ab-11ea-9fab-59f6e7eae427.png)

I used [Mulish](https://fonts.google.com/specimen/Mulish?preview.text=axios&preview.text_type=custom) for the font

**Comment by richiksc** [comment]
@marsnebulasoup I think the "I as arrows concept" could be interesting to explore further but for me, the second logo is really hard to read as "axios"

**Comment by marsnebulasoup** [comment]
Yeah, I was thinking the request arrows would look better if they are closer together, but I just put this together quickly

**Comment by richiksc** [comment]
Here's my take on the rocket idea:

![axios-rocket](https://user-images.githubusercontent.com/8939680/87706826-c4775280-c765-11ea-881b-534dce5f5305.png)

There's two different typeface options: I used [Poppins](https://fonts.google.com/specimen/Poppins) for the top one and [Inter](https://fonts.google.com/specimen/Inter) for the bottom one. You could keep the logo black and white or use the same purple color from my previous submission, but instead you could also use a shade of "hot orange" to tie in with the rocket flames and "speed."

**Comment by marsnebulasoup** [comment]
I like the first font better than the second.I think that italics and streak lines on the rocket would further emphasize speed. I found this icon on flaticon and I'm thinking that two way "fire arrows" could also work, but vertically, instead of horizontally.

[Icon](https://image.flaticon.com/icons/svg/2455/2455914.svg)

**Comment by marsnebulasoup** [comment]
I like the first font better than the second.I think that italics and streak lines on the rocket would further emphasize speed. I found this icon on flaticon and I'm thinking that two way "fire arrows" could also work, but vertically, instead of horizontally.

[Icon](https://image.flaticon.com/icons/svg/2455/2455914.svg)

**Comment by marsnebulasoup** [comment]
Maybe like this?

![image](https://user-images.githubusercontent.com/52974834/87711318-bb3db400-c76c-11ea-96d1-9f72617e398c.png)

**Comment by NotMoni** [comment]
@madebyherzblut Can you send a link to download these https://github.com/axios/axios/issues/2130#issuecomment-659591555.

I would like to add them to the original axios logo I had.

**Comment by richiksc** [comment]
@marsnebulasoup In my humble opinion the streak lines make the logo too cluttered, and would be difficult to reproduce at smaller sizes. It might just be me, but I prefer keeping logos minimal and unadorned. Another thing we have to think about (and this includes my rocket submission) is the brand positioning of Axios. Is Axios "the fast http client for node" or is Axios "the node http client for humans." Axios is pretty performant, but I don't know how it compares to other "competitors" and whether the maintainers want to explicitly position it as fast/"the fastest." Many developers choose Axios because of its abstracted simple API that's easy to understand and use, and that it's also universal across Node and the browser.

I think we could all benefit from some "brandstorming" here - everyone feel free to chime in. What are the adjectives that best describe Axios?

Is Axios...

- Fast?
- Simple?
- Intuitive/developer-friendly/"human"?
- Powerful/feature-rich?
- Universal?

Please suggest your own adjectives as well... I think understanding Axios' "brand positioning" will help all of us submitting logos design a logo better suited to Axios.

**Comment by marsnebulasoup** [comment]
I think that axios is better described by "the node http client for humans," rather than "the fast http client for node." The main reason for my choosing axios is that it is simple, easy to use, and has the ability to create custom instances with different parameters. This last one is especially useful, at least to me, because I can create an instance of axios with API headers and other parameters that would be tedious and confusing to rewrite over and over otherwise. Axios is intuitive; calling axios.get(url) or axios.post(url) seems natural, and I think when I first used it I didn't even have to look at the docs to see how to make a simple get request. 

I agree with @richiksc that minimalistic logos are probably the best. I see many logos nowadays with just the first letter, like Vue for example, or an icon, then the name, like Bulma, or just an icon without the name, like React (although there are some versions of the logo with the name). 

As for the structure of the logo, I think that the word axios would have to be written horizontally without being broken up, because there are five letters, so if you break it up, it will be an uneven split of letters.

Axios is fast, but as @richiksc said, simplicity and features are the main reason developers use axios, not because it is the fastest.

So, in my opinion, _simple_ and _intuitive_ are adjectives that describe axios well. And going by that, I thought up another logo design which is simple, as it only has three parts, and intuitive: the arrows symbolize, as @richiksc said, the "concept of request and response."

![axioslogo](https://user-images.githubusercontent.com/52974834/87746768-0c729580-c7b7-11ea-92a0-6082bb60c4fb.png)

A color scheme besides B&W would look better, but that can be changed also. Going with the orange and purple theme, here is a variation of the B&W logo

![axioslogo](https://user-images.githubusercontent.com/52974834/87747510-27460980-c7b9-11ea-941d-eebd027153a2.png)

Also, slanting on the ends of the arrows make them fit in more:

![axioslogo](https://user-images.githubusercontent.com/52974834/87748080-94a66a00-c7ba-11ea-9706-b3a15cb66165.png)

I used [Mulish](https://fonts.google.com/specimen/Mulish?preview.text=axios&preview.text_type=custom) as the font, but I think that [Poppins Light 300 Italic](https://fonts.google.com/specimen/Poppins?preview.text=axios&preview.text_type=custom) would look better.

**Comment by richiksc** [comment]
@marsnebulasoup I love your new logo idea and your reasoning behind it! I definitely agree, Axios is intuitive, easy to use, and powerful.

**Comment by marsnebulasoup** [comment]
@NotMoni You referenced my comment but mentioned someone else, and I am not sure if that was a typo. Anyways, here are the arrow icons if that's what you wanted:

[Normal](https://www.flaticon.com/free-icon/high-speed_2455914)
[Colored](https://www.flaticon.com/free-icon/high-speed_2455905)

**Comment by marsnebulasoup** [comment]
@richiksc Thanks! I think that axios needs to have its own theme colors, like Vue has green and grey, or Electron has dark grey and powder blue. orange and purple are nice, but we should look into other options also.

**Comment by richiksc** [comment]
@marsnebulasoup For sure! We don't even have to use orange and purple! I wasn't even originally suggesting using them together, but instead as two different options. I find that blue is used a lot in the tech/OSS world, so I was trying to think of some other colors that would work. If you don't mind, I have a couple ideas for tweaks you could make to your logo. One would be to match the slant angle of the arrows and the rear of the arrow head to the angle of the italics in the font. The other would be to match the thickness of the line of the arrow to the thickness of the "i". Again, these are just suggestions, the idea is looking great! I wonder if axios has enabled the GitHub discussions feature to discuss the logo and color schemes like you suggested.

**Comment by NotMoni** [comment]
Can we see the last logo with the poppins ?

https://github.com/axios/axios/issues/2130#issuecomment-659837110

**Comment by marsnebulasoup** [comment]
@NotMoni Sure! @richiksc I swapped the directions of the arrows because it was easier to slant them that way. Here is what I have:

![axioslogo2](https://user-images.githubusercontent.com/52974834/87818770-c3f7be00-c830-11ea-88e9-df655d321834.png)

I can't seem to get the arrows just right. 😠

---

I also was experimenting with this idea:

![image](https://user-images.githubusercontent.com/52974834/87808337-28118680-c81f-11ea-91e7-f147ed24a030.png)

Let me know what you think

**Comment by marsnebulasoup** [comment]
Also one-letter logos could work also because they are easier to read in smaller formats:

![axios2](https://user-images.githubusercontent.com/52974834/87965012-b33d8700-ca80-11ea-831f-e341e565b16e.png)

![axios2 (1)](https://user-images.githubusercontent.com/52974834/87964991-acaf0f80-ca80-11ea-8c09-83db0c080d78.png)

**Comment by NotMoni** [comment]
nice !

**Comment by marsnebulasoup** [comment]
Lol it's been like 2 months. I'd almost forgotten about this.

**Comment by NotMoni** [comment]
haha

**Comment by 9mm** [comment]
![image](https://user-images.githubusercontent.com/1386207/93847557-105de080-fc5c-11ea-81e4-24e7fe4dacf6.png)

**Comment by marsnebulasoup** [comment]
I think we should think of a logo that will fit within a circle or square (or something with a 1x1 ratio), so it can be used in multiple formats without being cropped.

**Comment by NotMoni** [comment]
^

**Comment by X7Becka** [comment]
![axios-1](https://user-images.githubusercontent.com/51074290/95618180-cfa4fa80-0a96-11eb-89f7-8fa2ec701c8f.png)
![axios-2](https://user-images.githubusercontent.com/51074290/95618183-d03d9100-0a96-11eb-8925-d82d58ea0441.png)
![axios-3](https://user-images.githubusercontent.com/51074290/95618185-d03d9100-0a96-11eb-937f-3250938b5b9c.png)
![axios-4](https://user-images.githubusercontent.com/51074290/95618187-d0d62780-0a96-11eb-9e45-fc000f962c94.png)
![axios-5](https://user-images.githubusercontent.com/51074290/95618188-d16ebe00-0a96-11eb-8c16-f163e919314a.png)
![axios-6](https://user-images.githubusercontent.com/51074290/95618190-d16ebe00-0a96-11eb-9975-89cf17f1138a.png)
![axios-7](https://user-images.githubusercontent.com/51074290/95618192-d2075480-0a96-11eb-9684-150b44cf2c33.png)
![axios-8](https://user-images.githubusercontent.com/51074290/95618195-d2075480-0a96-11eb-851a-26cd2b75eb54.png)
Some variants.

**Comment by marsnebulasoup** [comment]
Nice! But maybe the arrow in place of the "I" should be upward facing, because it kind of looks like a "j" now. Also, does it make sense to have the arrow _and_ loop? Maybe it'd be better to just stick with one.

**Comment by X7Becka** [comment]
@marsnebulasoup - something like that.
I guess colors should be another.
![axios-9](https://user-images.githubusercontent.com/51074290/95626038-bd7d8900-0aa3-11eb-87bc-34f23ebaf215.png)
![axios-10](https://user-images.githubusercontent.com/51074290/95626040-beaeb600-0aa3-11eb-8db4-2191adb76a96.png)
![axios-11](https://user-images.githubusercontent.com/51074290/95626041-beaeb600-0aa3-11eb-8002-6c2e9fc8bf33.png)

**Comment by marsnebulasoup** [comment]
@X7Becka - That looks better, IMHO, but for the first two, doesn't the "I" sort of look like a "1" now? 🙂

Maybe if you flip the "I" so that it's like you're looking at a mirror image of a "1" that'll fix this issue.

**Comment by X7Becka** [comment]
@marsnebulasoup - another four variants has arrived.
![axios-12](https://user-images.githubusercontent.com/51074290/95657621-a12f2a00-0b3f-11eb-864e-850aa48b3493.png)
![axios-13](https://user-images.githubusercontent.com/51074290/95657623-a2605700-0b3f-11eb-9448-8c5314538de8.png)
![axios-14](https://user-images.githubusercontent.com/51074290/95657624-a2605700-0b3f-11eb-94f8-81876e07848a.png)
![axios-15](https://user-images.githubusercontent.com/51074290/95657626-a2f8ed80-0b3f-11eb-851f-9ff54330daa1.png)

**Comment by richiksc** [comment]
@jasonsaayman Should we set a deadline for final submissions and then eventually hold a vote on strawpoll or something? How many maintainers are on the Axios team? Do you think they'll all be able to vote?

**Comment by marsnebulasoup** [comment]
What if we have a contest that _anyone_ can participate in, not just maintainers, and announce it on the README, so it'll be seen by the most amount of people possible? I, myself, was wondering if axios had a logo, and that's how I found this very long thread, but I had to look for it. It's not obvious that axios is looking for a logo.

It'd seem to me that allowing submissions from anyone, then having everyone vote would be a good way to find a logo people will identify with easily.

**Comment by richiksc** [comment]
@marsnebulasoup Sorry, I should have been more clear in my comment. I agree with you, we need to get as many votes as possible, and I agree that the vote should be open to the public. I just wanted to make sure that all of the maintainers voted as well.

**Comment by marsnebulasoup** [comment]
@richiksc - Ah yes, that makes more sense. But I meant a contest that anyone can submit their logo ideas, because we here don't seem to have any bright ideas 😐, and it seems like we're stuck repeating various iterations of the "axios with the I as an arrow" idea, or some such. If we set some rules and accept submissions till a certain date, then have people vote on them, maybe we'll end up some better ideas.

**Comment by richiksc** [comment]
Yes for sure. This issue was supposed to be a contest open to anyone but we
are just a few people all doing "axios with arrows".

**Comment by jasonsaayman** [comment]
@richiksc I will work on something for us, this is a good time too since it's hacktober and more people are on GH. I will try to get to it tonight and set it up so that we can do a proper competition with a good voting system. Your question on maintainers, I think actively there is 3 maybe 4.

**Comment by Leomv55** [comment]
> Here's my take on the rocket idea:
> 
> ![axios-rocket](https://user-images.githubusercontent.com/8939680/87706826-c4775280-c765-11ea-881b-534dce5f5305.png)
> 
> There's two different typeface options: I used [Poppins](https://fonts.google.com/specimen/Poppins) for the top one and [Inter](https://fonts.google.com/specimen/Inter) for the bottom one. You could keep the logo black and white or use the same purple color from my previous submission, but instead you could also use a shade of "hot orange" to tie in with the rocket flames and "speed."

@richiksc 
  - The rocket symbolizes the rocket speed right?. Can we symbolize the speed other than using rockets in logo . Like arrows shown in first post?
  - The 'a' change is not making much an impact IMO .

**Comment by marsnebulasoup** [comment]
I'm not sure if speed is the right message to send, because, as mentioned above, axios isn't necessary the fastest, but rather, in my opinion, the easiest to use. I'm not sure how "ease-of-use" can be symbolized by an icon though.

**Comment by laxman-patel** [comment]
Hey, here's my take on axios logo which represents **minimalism and modernism.**

![Group 22](https://user-images.githubusercontent.com/42996258/96428475-6bfc9900-121d-11eb-909a-f7cab7145fea.png)


share your thoughts on this. any criticism is appreciated.

**Comment by marsnebulasoup** [comment]
@laxman-patel - Nice! I especially like the arrows. But I'm thinking that since arrows are in a sort of rounded, shouldn't the text be in a similar style--just to maintain consistency?

Also, since the logo will be displayed in a 1×1 aspect ratio in some cases, how would that work? Would it just be the arrows?

**Comment by laxman-patel** [comment]
> @laxman-patel - Nice! I especially like the arrows. But I'm thinking that since arrows are in a sort of rounded, shouldn't the text be in a similar style--just to maintain consistency?

thanks, I will change the font to something more rounded and experiment with it.

> Also, since the logo will be displayed in a 1×1 aspect ratio in some cases, how would that work? Would it just be the arrows?

yes. arrows only for small sizes.

**Comment by laxman-patel** [comment]
@marsnebulasoup  
We all are developers and kinda suck at logo design.

**Comment by Geek-JCY** [comment]
talents men

**Comment by wowistudio** [comment]
Hi guys. Cool ideas. I felt the urge to also hand in a quick sketch. Let me know what you think!
<img width="228" alt="logo1" src="https://user-images.githubusercontent.com/64492987/97858152-05887800-1cff-11eb-89bf-732e3d55d599.png">
<img width="301" alt="logo2" src="https://user-images.githubusercontent.com/64492987/97858154-06210e80-1cff-11eb-81fd-55fa42fe0988.png">

**Comment by marsnebulasoup** [comment]
@wowistudio - Nice, finally some fresh takes on the arrows 👍. But what's with the `nuxt` part? Shouldn't the logo for axios focus on just axios?

**Comment by wowistudio** [comment]
@marsnebulasoup yeah agree. I'm not really into typography, so that's why I took the text of the current logo as an example :).

**Comment by dennisfrijlink** [comment]
> Here are the two versions.
> 
> **I think I should make a better rocket.**
> 
> ![Artboard 1f](https://user-images.githubusercontent.com/40552237/85750411-acb52d00-b6d7-11ea-996d-26e6836a4478.png)
> 
> ** Rocket Straight Up **
> ![forwardArtboard 1f](https://user-images.githubusercontent.com/40552237/85750419-ade65a00-b6d7-11ea-9c9a-05e60771cd0f.png)

Maybe a higher font-weight?

**Comment by laxman-patel** [comment]
love that! higher font-weight could help.

**Comment by arcturus-prime** [comment]
What about something like this, following the whole "request/response" theme? (probably with some adjustments, particularly the color)
![AxiosLogo](https://user-images.githubusercontent.com/16843090/101181820-f3a63780-3612-11eb-9d3a-05452f2b0ad8.png)

**Comment by marsnebulasoup** [comment]
Interesting...it gives me sort of Microsoft vibes though, but maybe that's the font family?

**Comment by arcturus-prime** [comment]
I thought so as well. It reminds me of Visual Studio Code. Hence, I thought a change in color might make a difference.

**Comment by rajanbajaj** [comment]
![axios](https://user-images.githubusercontent.com/24255458/103125747-1f688a80-46b2-11eb-9ecf-5d20db843e19.png)

feedback are appriciated! thanks

**Comment by codemaster138** [comment]
Hi everyone! I may be a bit late to the party, but here's my design:

<img width="413" alt="axios_logos" src="https://user-images.githubusercontent.com/43313420/103477110-a8bb4380-4dbb-11eb-9878-a8b54133f7d7.png">

**Comment by richiksc** [comment]
> Hi everyone! I may be a bit late to the party, but here's my design:
> 
> <img width="413" alt="axios_logos" src="https://user-images.githubusercontent.com/43313420/103477110-a8bb4380-4dbb-11eb-9878-a8b54133f7d7.png">
> 

I love these! Especially the third and the last one!

**Comment by codemaster138** [comment]
Since the last one seemed kind of janky, I created a revamped version:

![axios_logo_circle](https://user-images.githubusercontent.com/43313420/103489418-b3ee8d80-4e14-11eb-99c2-e5a0576f3fcb.png)

**Comment by malishahi** [comment]
Hi, which logo can I use in my presentation to show that I am using Axios? thanks.

**Comment by codemaster138** [comment]
> Hi, which logo can I use in my presentation to show that I am using Axios? thanks.

@malishahi Hey Mehdi, there is currently no official Axios logo, but since it looks like my Website with the logos I posted above is becoming Official, maybe use this one for now:

![axios_logo](https://user-images.githubusercontent.com/43313420/105883616-57dbeb00-6007-11eb-9df2-de0e2a42655c.png)

If you need an icon, you can use the following:

![axios_favicon](https://user-images.githubusercontent.com/43313420/105883661-64604380-6007-11eb-8cfa-45ff66b37fdb.png)

**Comment by malishahi** [comment]
hey @codemaster138, thanks for providing logos. Do you have transparent version of these?
cheers, Mehdi

**Comment by codemaster138** [comment]
@malishahi Yes!

![axios_logo_transparent](https://user-images.githubusercontent.com/43313420/105893154-0afe1180-6013-11eb-941d-19a96ebe3c0b.png)

![axios_favi_transparent](https://user-images.githubusercontent.com/43313420/105893220-1bae8780-6013-11eb-87be-eeac845ecc6f.png)

**Comment by malishahi** [comment]
@codemaster138 thanks.

**Comment by agnelnieves** [comment]
A different take on the axios arrows

![Group 16](https://user-images.githubusercontent.com/5799157/108106971-9f7cf200-705c-11eb-9211-fcca2b7f1796.png)

**Comment by parth7676** [comment]
Some ideas...

![Capture](https://user-images.githubusercontent.com/14904762/108138154-6019ca00-708b-11eb-8fa4-cad42e435c22.PNG)
![Capture2](https://user-images.githubusercontent.com/14904762/108138157-6019ca00-708b-11eb-88e8-009d9ccc72ca.PNG)

**Comment by codemaster138** [comment]
@agnelnieves Wow those look amazing! Do you have some transparent background ones so I can see how they go with the website?

**Comment by codemaster138** [comment]
@parth7676 Those are cool too, but what do they look like on a white background? I think that desaturated yellow is not quite the right background color for modern projects like axios, as it symbolizes yellowed paper, which would only be cool if you‘re going for a classical vibe, and I (personally; I am _not_ part of the axios team) think that doesn‘t really fit axios as a project

**Comment by agnelnieves** [comment]
> @agnelnieves Wow those look amazing! Do you have some transparent background ones so I can see how they go with the website?

Hey @codemaster138 sure thing, here they are

[axios-logo-an.zip](https://github.com/axios/axios/files/6010917/axios-logo-an.zip)

**Comment by jasonsaayman** [comment]
Closing as we have a new site and a new logo. Thanks to everyone involved in creating logos and thank you for the time you put in for Axios to have a good brand identity, this is much appreciated!

**Comment by mubashirjamali101** [comment]
# Final it guys!
