### ISSUE TITLE
Denial of Service

### ISSUE THREAD

**Issue by Ryuno-Ki** [axios/axios#2131]
As already mentioned in https://github.com/axios/axios/issues/1965#issuecomment-489307023 @snyk discovered a vulnerability and provided a patch:
https://snyk.io/vuln/SNYK-JS-AXIOS-174505

Leaving this here for others to stay secure, since the maintainer is currently overwhelmed with other topics (if you want to help, look into #1965).

**Comment by watadarkstar** [comment]
Following!

**Comment by Ryuno-Ki** [comment]
@watadarkstar Did you know that [you can subscribe to a conversation without adding a comment](https://help.github.com/en/articles/subscribing-to-and-unsubscribing-from-notifications)? :-)

**Comment by watadarkstar** [comment]
@Ryuno-Ki Ah right! Thanks 😄

**Comment by mhuggins** [comment]
@Ryuno-Ki Is a fix going to be released for this anytime soon?

**Comment by emilyemorehouse** [comment]
0.19.0 has a fix and has been released

**Comment by purplelady105** [comment]
> @Ryuno-Ki Is a fix going to be released for this anytime soon?

Version 0.19.0 has been released which should fix the vulnerability. See this post: https://github.com/axios/axios/issues/2183#issuecomment-497391903

**Comment by kunalnagar** [comment]
@emilyemorehouse @purplelady105 0.19.0 does not actually fix the Denial of Service vulnerability according to Snyk. I think the fix has been pushed to master but not actually published. More info [here](https://snyk.io/vuln/SNYK-JS-AXIOS-174505)

![image](https://user-images.githubusercontent.com/2741371/58656778-88ebb000-833a-11e9-9a86-917d6ae34838.png)

**Comment by emilyemorehouse** [comment]
@kunalnagar It doesn't seem like Synk recognized the release - everything on master has been published. Perhaps it needs to be manually changed or it didn't recognize the minor version?

**Comment by kunalnagar** [comment]
> Perhaps it needs to be manually changed or it didn't recognize the minor version?

@emilyemorehouse I see 0.19.0 as the latest version. What's the minor version you mentioned?

**Comment by dominik-zen** [comment]
@kunalnagar snyk just updated the report and now says there are no vulnerabilities for 0.19.0.
