### ISSUE TITLE
Cannot read property 'cancelToken' of null 

### ISSUE THREAD

**Issue by FourLeafClover** [axios/axios#2132]
TypeError: Cannot read property 'cancelToken' of null
    at throwIfCancellationRequested (app.js:sourcemap:4099)
    at dispatchRequest (app.js:sourcemap:4111)

**notice:** 
 1.   I have required the config in the interceptors.request。
 2.   Some of my post request have this error. but others are ok.

**Comment by waleedarshad** [comment]
@FourLeafClover what solution did you try? what was your findings?
