### ISSUE TITLE
Delete redirect occuring after DELETE request

### ISSUE THREAD

**Issue by jammy-git** [axios/axios#2133]
I'm performing a DELETE request, then a promise in which I redirect the user back to an index page:

```js
                axios.delete(this.end_point)
                    .then(response => {
                        window.location.href = this.loopback;
                    })
```

I expected the redirect to be just a simple get request, but when looking at the Network Inspector in DevTools it seems axios sends the request as a DELETE request again.

Is this the default behaviour? Will the promise send the same request type in subsequent promise functions as the first request?

**Environment:**
 - Axios Version [0.18.0]
 - Browser [Chrome]
 - Additional Library Versions [Laravel 5.8, VueJS]

**Comment by rocramer** [comment]
Same setup and weird behavior for me, too.

**Comment by kevin-smartpatients** [comment]
My case is slightly different:

I send a DELETE request to the server which send back a redirect to /home. 
Axios then does a DELETE request to /home. This should be a GET request.

**Comment by chinesedfan** [comment]
Check the response of your first DELETE request in the browser's network panel. Did a redirect status code (like 302) there? With the response header "Location"?

**Comment by rodrigopedra** [comment]
Browser follows the redirect before handling to axios. When using PUT, PATCH and DELETE methods the redirect should return a 303 (see other) status so the browser follows the redirect using a GET request.

From this MDN page:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303

>  The method used to display this redirected page is always GET.

**Comment by rodrigopedra** [comment]
More info here: https://github.com/axios/axios/issues/932#issuecomment-307390761

**Comment by chinesedfan** [comment]
Closed due to stale and no updates.
