### ISSUE TITLE
Axios. All + Spread to get two different API data

### ISSUE THREAD

**Issue by hfurtadob** [axios/axios#2136]
Hello! I'm kinda new in this world, used to work with Mainframes (Cobol + CA7) and now in love with React.
My question is,how to get data from a second page using axios? I can get data from the first page but not from the second. 

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      nave: []
    };
    this.getNave = this.getNave.bind(this);
  }
  getNave() {
    return Axios.all([
      Axios.get("https://swapi.co/api/starships/"),
      Axios.get("https://swapi.co/api/starships/?page=2")
    ]).then(
      Axios.spread(response => {
        console.log(response.data.results);
        this.setState({ nave: response.data.results });
      })
    );
  }

  componentDidMount() {
    this.getNave();
  }
  render() {
    const { nave } = this.state;
    return (
      <div className="App">
        <List nave={nave} />
      </div>
    );
  }
}

export default App;

**Comment by chinesedfan** [comment]
In fact, I suggest users to use the ES6 Promise methods and spread grammer directly.

```
Promise.all([
  Axios.get("https://swapi.co/api/starships/"),
  Axios.get("https://swapi.co/api/starships/?page=2")
]).then(([page1Data, page2Data]) => {
  // do as you wish
})
```

If you persist,

```
Axios.all([
  Axios.get("https://swapi.co/api/starships/"),
  Axios.get("https://swapi.co/api/starships/?page=2")
]).then(
Axios.spread((page1Data, page2Data)=> {
  console.log(response.data.results);
  this.setState({ nave: response.data.results });
})
```
