### ISSUE TITLE
How to handle gzip and why there is some format problem of response

### ISSUE THREAD

**Issue by Tonysmark** [axios/axios#2137]
**Describe the issue**
I'm recently using axios for web scrapy and the response is an jsonp , and tha's not the main problem , the problem is that some chinese font. How to fix this problem ??? 
It looks like this 
![image](https://user-images.githubusercontent.com/22767695/57355572-e9a32500-71a0-11e9-913c-1b42535e41e2.png)

**Example Code**

```js
const axios = require("axios");
(async () => {
  const productId = "100002928171";
  axios.interceptors.response.use(response => {
    response.headers = {
      age: 0,
      "content-encoding": "gzip",
      "content-type": "application/json;charset=GBK",
      date: "Tue, 07 May 2019 15:17:52 GMT",
      server: "JDWS/2.0",
      status: 200,
      via: "BJ-Y-NX-112(MISS), http/1.1 JN-UNI-1-JCS-32 ( [cMsSf ])"
    };
    return response;
  });
  await axios({
    method: "GET",
    url: `https://sclub.jd.com/comment/productPageComments.action`,
    params: {
      productId,
      score: 0,
      sortType: 5,
      page: 0,
      pageSize: 10,
      isShadowSku: 0,
      fold: 1
    },
    headers: {
      DNT: 1,
      Referer: `https://item.jd.com/${productId}.html`,
      "sec-ch-ua": "Google Chrome 74",
      "Sec-Fetch-Dest": "script",
      "Sec-Fetch-Mode": "no-cors",
      "Sec-Fetch-Site": "same-site",
      "Sec-Fetch-User": "?F",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
    }
  }).then(res => console.log(res.data));
})();

```

**Environment:**
 - Axios Version [0.18.0]
 - OS: [windows10 1903]

**Additional context/Screenshots**
I've also use postman to test this url and I got exactlly what I want
![image](https://user-images.githubusercontent.com/22767695/57355759-574f5100-71a1-11e9-97a4-b390237e674b.png)

**Comment by chinesedfan** [comment]
See https://stackoverflow.com/questions/23143231/gbk-encode-decode-charset. You need decode your response data as it is gbk.
