### ISSUE TITLE
How to mock CancelToken in jest test case

### ISSUE THREAD

**Issue by praveennetcity** [axios/axios#2139]
**Describe the issue**
TypeError: CancelToken is not a constructor

**Example Code**

```js
// Example code here
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mickatron** [comment]
I'm wondering how to do this as well. Any comments would be appreciated

**Comment by mickatron** [comment]
I wound up using `jest-mock-axios` which worked well for me and saved me writing my own manual mock.

https://www.npmjs.com/package/jest-mock-axios#additional-examples

**Comment by philgruneich** [comment]
`jest-mock-axios` has an incomplete implementation of CancelToken: [](https://www.npmjs.com/package/jest-mock-axios#missing-features)

> AxiosMock covers the most popular parts of Axios API, meaning that some of the features are missing or only partially implemented (i.e. interceptors). AxiosMock provides the axios.CancelToken interface, but with an empty implementation.

**Comment by chinesedfan** [comment]
For further related request, we can open an issue to https://github.com/knee-cola/jest-mock-axios.

**Comment by ezra-m** [comment]
Does anyone have an example implementation of a test case with CancelToken that they could share?
