### ISSUE TITLE
Axios Request with Auth

### ISSUE THREAD

**Issue by OK-girl** [axios/axios#2144]
In the parameter processing of XMLHttpRequest.open(), only three commonly used parameters are processed in the project.
      Actually,this processing is open(method, url, async, username, password).When I access an API that requires authentication, but I don't want the browser to make popovers,The username and password parameters come in handy.
      The service request is flawed because these two parameters are discarded in Axios

**Comment by michaelvdnet** [comment]
There is an `auth` object in the request config which enables basic authentication.

E.g:
```js
const config = {
  auth: {
    username: 'myusername',
    password: 'mypassword',
  },
};

axios.get('/my/url', config)
  .then(...);
```

Could this be what you're looking for?

**Comment by murphman300** [comment]
Im using feature, but for some reason, the request being made is not hashing the auth values into a proper ASCII Basic Authorization value.

The value being passed on in the request is the actual JSON object i pass to the auth key.. with the password in plain text....

**Comment by murphman300** [comment]
let resp = await Axios.post(`${_this._baseURL}/login`, {}, {
                //headers: {Authorization:  basic}
                auth: {
                    username: username,
                    password
                }
            });

`config:
   { url: 'https://url.../login',
     method: 'post',
     data: '{}',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.19.0',
        'Content-Length': 2 },
     auth: { username: 'user', password: 'somepassword' },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] }`

code:

`
let resp = await Axios.post(`${_this._baseURL}/login`, {}, {
                auth: {
                    username: username,
                    password: password
                }
            });
`



... Don't understand why that's not working properly...

**Comment by CodyMorris** [comment]
I'm seeing the same thing.

Requests are being made with username:password in the request path rather than being set as a header

**Comment by jasonsaayman** [comment]
Is this still happening? If so please let me know so I can have a look

**Comment by juanpumpkinpie** [comment]
This issue in gitHub with ⌁Axios is not fixed. Converting user:token or email_user:token to Base64 doesn't change nothing, neither placing the data into 
const API = {
    method: "get",
    url: `https://api.github.com/search/users?q=${user}`,
    headers: {
      Authorization:
        "Basic  **here** ",
    },
  };
  
  or by the config options in the url, nothing works with Axios. Only by the cURL directly on postMan
