### ISSUE TITLE
property post does not exist on type 'typeof axios'

### ISSUE THREAD

**Issue by bryanrasmussen** [axios/axios#2145]
**Describe the bug**
This is in a project where I am slowly moving old react.jsx code to typescript .tsx. 
The bug is in a tsx file imported into a js file that uses react. 
This seems very close to https://github.com/axios/axios/issues/734 however I am doing import axios from 'axios';  and it still doesn't work*

**To Reproduce**
This is in a react process with JSX set to preserve, it is a tsx file imported by a js.**

```js

import React, { Component } from 'react';
import axios from 'axios';

const LoggedIn = React.createContext({});

interface IState {
    isLoggedIn: boolean;
    errorMessage: string,
    token?: string,
    refreshToken?: string
}

interface IProps {}

class LoginProvider extends Component<IProps, IState> {

    
    constructor(props?) {
        super(props);
        this.state = { isLoggedIn: false, errorMessage: '' };
        this.login = this.login.bind(this);
        this.logout = this.logout.bind(this);
    }
    
    login(u, p) {
        if (!u.validity.valid || !p.validity.valid) {
            this.setState({errorMessage: 'You Need to provide both a valid email and a valid password'});
            return;
        }
        const data = JSON.stringify({
            password: p._valueTracker.getValue(),
            username: u._valueTracker.getValue()
        });
        axios.post("URL to post to here", data, {
        headers: {
            'Content-Type': 'application/json',
            'accept': 'application/json'
        }})
        .then((response) => {
            const data = response.data;
            this.setState({isLoggedIn: true, token: data.token, refreshToken: data.refresh_token})
        })
        .catch((error) => {
            this.setState({errorMessage: error.message});
        });
        return true;
    }

    logout() {
        this.setState({ isLoggedIn: false })
    }

	render() {
        const localstate = this.state;
        const obj = { isLoggedIn: localstate.isLoggedIn, login: this.login, errorMessage: localstate.errorMessage, token: localstate.token, refreshToken: localstate.refreshToken};
		return (
            <LoggedIn.Provider value={obj}>
			     {this.props.children}
            </LoggedIn.Provider>
		);
	}
}
const LoginConsumer = LoggedIn.Consumer;

export {LoginProvider, LoginConsumer};

```

**Expected behavior**
Well before it was turned into jsx the axios.post was working now it is not. I was hoping it would continue working. However barring that is there some type I have to set somewhere?

**Environment:**
 - axios@0.18.0"
 -  OSX Mojave
 - browser - at compilation time so before it hits the browser
 - Additional Library Versions "react": "^16.8.6"

**Comment by bryanrasmussen** [comment]
Ok I found that changing my code as follows:

`
import React, { Component } from 'react';
import Axios , {AxiosResponse, AxiosError} from 'axios';


const LoggedIn = React.createContext({});

interface IState {
    isLoggedIn: boolean;
    errorMessage: string,
    token?: string,
    refreshToken?: string
}

interface IProps {}

class LoginProvider extends Component<IProps, IState> {

    
    constructor(props?) {
        super(props);
        this.state = { isLoggedIn: false, errorMessage: '' };
        this.login = this.login.bind(this);
        this.logout = this.logout.bind(this);
    }
    
    login(u, p) {
        if (!u.validity.valid || !p.validity.valid) {
            this.setState({errorMessage: 'You Need to provide both a valid email and a valid password'});
            return;
        }
        const data = JSON.stringify({
            password: p._valueTracker.getValue(),
            username: u._valueTracker.getValue()
        });
        Axios.post('https://dev.documenthandler.aarhof.eu/api/security/login', data, {
        headers: {
            'Content-Type': 'application/json',
            'accept': 'application/json'
        }})
        .then((response: AxiosResponse) => {
            const data = response.data;
            this.setState({isLoggedIn: true, token: data.token, refreshToken: data.refresh_token})
        })
        .catch((error: AxiosError) => {
            this.setState({errorMessage: error.message});
        });
        return true;
    }

    logout() {
        this.setState({ isLoggedIn: false })
    }

	render() {
        const localstate = this.state;
        const obj = { isLoggedIn: localstate.isLoggedIn, login: this.login, errorMessage: localstate.errorMessage, token: localstate.token, refreshToken: localstate.refreshToken};
		return (
            <LoggedIn.Provider value={obj}>
			     {this.props.children}
            </LoggedIn.Provider>
		);
	}
}
const LoginConsumer = LoggedIn.Consumer;

export {LoginProvider, LoginConsumer};
`

worked out. So that was uppercase Axios instead of axios. and declaring my types AxiosError and AxiosResponse. I also found I had to restart Vsual studio code at one because it was giving me syntax errors, when I restarted they went away and I could compile Seems magical and annoying but thats what happened.

**Comment by NonPolynomial** [comment]
does not work with `--checkJs` flag
you have then to import axios like this
```js
const { default: axios } = require('axios');
```
