### ISSUE TITLE
axios isn't give properly 401 error response

### ISSUE THREAD

**Issue by UrielZohar** [axios/axios#2146]
I make a http request with axios , the request return a 401 response (I can see it in the F12 network)  , 
I want to catch it in the reject section of the promise of the axios but I can't see any information about the response error status (should be 401) .
Ho can I see it properly from the axios response argument ? 

**Here is the code:**
```js
axios.get('https://blablabla.com')
.then( (res) => {
    ...
}).catch(error => {
    console.log(error.response) // undefined
});
```

**Expected behavior**
to see the 401 error on the response in the reject section of the axios response

**Environment:**
 - "axios": "^0.18.0"

**Comment by verzac** [comment]
401 isn't thrown as errors; only network-level errors are thrown (e.g. connection refused or something like that).

You'd have to check the statuscode of the response in your then() and throw an error accordingly.

**Comment by Alanscut** [comment]
you could get the error information with `error.toJSON()` in v0.19.0.
