### ISSUE TITLE
Axios unexpected end of stream in post when query params is too large

### ISSUE THREAD

**Issue by hamsddxn** [axios/axios#2147]
hello everyone
i have an issue, i've spent a day of searching results in google.

these are my two url
**domain.api/v1/me/edit?access_token=ej.............** (access_token length is 331)
**domain.api/v1/me/security?access_token=ej.............** (access_token length is 331)

The first result success, but for the second i'll always have an error message if the access_token length is 331

> unexpected end of stream on Connection{domain.api, proxy=DIRECT hostAddress=/domain.api cipherSuite=none protocol=http/1.1}

if the access_token length is less than 331, the request succeed.
Can anyone help me?

**Comment by a7urag** [comment]
Can please share code snippet?

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
