### ISSUE TITLE
Params get stripped from requests on redirect

### ISSUE THREAD

**Issue by alessbelli** [axios/axios#2148]
An endpoint I'm hitting is in the format `example.com/t/-/{id}`, which redirects to `example.com/t/{name}/{id}`. However, the location header on the 301 response does not add back any params I initially had.

This behavior is probably intended as a sane default for security purposes, however I'd like it to be possible to pass params to redirected locations.

A workaround is to handle the redirect manually, ie to split into two requests, less convenient as a whole.

```js
const actualLocation = await axios.get(initialLocation, {
  maxRedirects: 0,
  validateStatus: status => status < 400
}).then(response => response.headers.location);
const response = await axios.get(initialLocation, {params});
```

**Comment by jasonsaayman** [comment]
I don't think we would be supporting this any time soon, I think the above is the best solution for now.
