### ISSUE TITLE
Axios interceptors response undefined

### ISSUE THREAD

**Issue by jvinhit** [axios/axios#2150]
Summary
In the case of registering multiple response interceptors (error callback in my case), only the first is taken into consideration.

axios.interceptors.response.use( response => response, err => {
  // err.response undefined => can't handle case http error ( status !== 200)

  return Promise.reject(err);
});

axios version: v0.18.0

**Comment by chinesedfan** [comment]
@jvinhit Can you elaborate your problem?

**Comment by jvinhit** [comment]
> @jvinhit Can you elaborate your problem?

Hi @chinesedfan I found my problem when request is blocking by CORS => response in iterceptors can't parse error code. I think my issue is closed! 
Thank u!
