### ISSUE TITLE
Add option to not auto decompress resp

### ISSUE THREAD

**Issue by hnry** [axios/axios#2153]
**Is your feature request related to a problem? Please describe.**
It's frustrating there's no option to turn off decompress. There are situations where you want to do this. Ex: having a service that collects data, but doesn't analyze it. which then passes to another service immediately/eventually.

While data is waiting or in traffic to next stop, it should stay compressed. The difference in byte size is huge (for me, 60MB vs 1-2MB). 

**Describe the solution you'd like**
Add an option to the request to not automatically decompress for me. I'm a big boy, I can handle it myself later.

**Describe alternatives you've considered**
There are none except user another lib or write own http req (which is ridiculous just to turn off a auto feature).

I can submit a PR if no one else wants to do it (it's not hard to add). But let me know how you'd like the option to be passed in? An extra options key? `axios({ url: ..., method: ..., decompress: false })` , or adding option to an existing option?

**Comment by michaelvdnet** [comment]
I think Axios is trying to be as platform agnostic (browser/node) as possible, with just a single API.

XHR has no support for disabling decompression so this would break that agnosticity.

**Comment by sazzy4o** [comment]
I created a PR to add this feature. In the mean time, before it gets merged/rejected you can fork off my repo and install by adding this to your package.json (This should not be used for a production environment):
```
	"dependencies": {
		"axios": "git://github.com/sazzy4o/axios.git#master"
	}
```
