### ISSUE TITLE
Content-type header for application/json should not contain charset field, according do RFC 8259

### ISSUE THREAD

**Issue by OJezu** [axios/axios#2154]
**Describe the bug**
According to [RFC 8259 - The JavaScript Object Notation (JSON) Data Interchange Format](https://tools.ietf.org/html/rfc7159) content-type `application/json` does not have any charset defined, as it must be utf-8 encoded. Older specifications allowed other unicode encodings, and parsers were detecting exact encoding used by first four bytes, still not by charset param.

Axios defaults to header `Content-Type: application/json;charset=utf-8` for some types of sent data.

This breaks some HTTP servers and applications, who are not recognizing the content-type.

**To Reproduce**
```js
axios.post("http://example.com", {an: "object"});
// Content-Type: application/json;charset=utf-8 header will be set
```

**Expected behavior**
`Content-Type: application/json` header should be set as default for object data, without charset parameter.

**Environment:**
 - Axios Version - 0.18.0, I've also checked master branch source - it is still there.
https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L52

**Additional context/Screenshots**
This breaks some parts of the rabbitmq-management API.

Related issues:
https://github.com/axios/axios/issues/859

**Comment by mpark86** [comment]
Is there any update on this issue? I'd like to try creating a PR for this.

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios/pull/2603#issuecomment-565743178. Thanks for @mpark86' pull request anyway.

And if you don't like it, you can replace it easily by configuring `transformRequest`.

**Comment by OJezu** [comment]
@chinesedfan just Ctrl+F the RFC referenced in that comment and in this issue.

> Note:  No "charset" parameter is defined for this registration.
>       Adding one really has no effect on compliant recipients.

>    o  Added a note to the "IANA Considerations" clarifying the absence
>       of a "charset" parameter for the application/json media type.

**Comment by chinesedfan** [comment]
@OJezu I am not sure I get what you means. I guess you are proving your point. According to RFC 8259, the charset is not required and some servers are not supported to parse it.

Never mind, at least [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) includes the charset. More servers work well with it. And as I said, if you don't like it, you can replace it easily by configuring `transformRequest`. Thanks for understanding.

**Comment by OJezu** [comment]
@chinesedfan what I'm proving, is that application/json type does not have "charset" defined. Providing it is non-standard, no matter what the servers do with it. 

Axios is behaving in a way not specified in standard, and this is what the issue is about. Common errors alone in other software are not a reason to break RFC.

**Comment by chinesedfan** [comment]
@OJezu After read more carefully, I think they are 2 things.

- You mentioned RFC8259, which requires JSON should be UTF-8 encoded.
- And I pasted a MDN link, which includes [RFC7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.5).

`Content-Type` is defined in RFC7231, instead of RFC8259. So axios doesn't break any BFCs.

**Comment by OJezu** [comment]
@chinesedfan where in RFC7231 is charset parameter defined for application/json? It's not, because parameter names are defined for concrete media-types in appropriate RFCs. `charset` parameter is neither declared for all headers nor for all media-types. `application/json` media-type does not have "charset" parameter defined.

From RFC7231
> The presence or absence of a
> parameter might be significant to the processing of a media-type,
> depending on its definition within the media type registry.

See IANA media type registry for `application/json`:
https://www.iana.org/assignments/media-types/application/json

And compare to `plain/html` entry which has `charset` parameter explicitly defined:
https://www.iana.org/assignments/media-types/text/html

**Comment by chinesedfan** [comment]
@OJezu I see. Now you have persuaded me. `application/json` is different with other media types.

**Comment by alexandr2110pro** [comment]
Any progress on that?

**Comment by OJezu** [comment]
There was a pull request done #2603, but @mpark86 did not change the expected header in tests, so they are failing. Until somebody fixes tests I expect no progress. I switched to node-fetch, so I lost interest anyway. If you can't switch out, tough luck, I suggest fixing the PR and hoping someone will merge and release.

**Comment by jasonsaayman** [comment]
We should try mend this in 0.20.0 I will look at the pull request.
