### ISSUE TITLE
Axios post request with codeigniter API CORS blocked in Firefox but work in Chrome

### ISSUE THREAD

**Issue by harshan89** [axios/axios#2155]
**Describe the issue**
My axios request is working fine on google chrome but not in firefox i have no idea why, please help

**Code**

Server has set to:
```php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: *');
```

Client request:
```js

const config = {
    headers: {
      'Content-Type': 'application/json'
    }
  }

axios.post(V12_FINANCE_FORM_SUBMITION_URL, data, config).then(res => res.data).catch(err => console.log(err))
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version [0.18.0]
 - OS: [Windows 10]
 - Browser [Firefoxi]
 - Browser Version [66.0.5 (64-bit)]
 - Additional Library Versions [create-react-app]

**Additional context/Screenshots**
![WhatFirefoxSays](https://user-images.githubusercontent.com/9652826/57766220-9c84fd00-7724-11e9-8753-f2efb80fc1b8.PNG)

**Comment by chinesedfan** [comment]
Looks like similar with https://github.com/axios/axios/issues/1998#issuecomment-492972843.

**Comment by harshan89** [comment]
> Looks like similar with [#1998 (comment)](https://github.com/axios/axios/issues/1998#issuecomment-492972843).

I saw that mate but it didn't help me.

**Comment by chinesedfan** [comment]
@harshan89 According to your screenshot, it must be a problem related to CORS. Check the field `Access-Control-Allow-Headers` in response, please.

**Comment by harshan89** [comment]
@chinesedfan **Access-Control-Allow-Headers** has set to "*" mate

**Comment by chinesedfan** [comment]
@harshan89 The server config is not the final result. Inspect network by browser, and check that header.

**Comment by harshan89** [comment]
> @harshan89 The server config is not the final result. Inspect network by browser, and check that header.

Usually OPTION request is fire with 200 and POST request not firing

**Comment by chinesedfan** [comment]
> Usually OPTION request is fire with 200 and POST request not firing

That is due to OPTION request failed in CORS check. You can diff response headers between Firefox  and Chrome. And without accessible endpoint, I am afraid I can't help you further.

**Comment by harshan89** [comment]
> > Usually OPTION request is fire with 200 and POST request not firing
> 
> That is due to OPTION request failed in CORS check. You can diff response headers between Firefox and Chrome. And without accessible endpoint, I am afraid I can't help you further.

**My end point is just a php file is print data which submit.**

```php
header('Access-Control-Allow-Headers: *');
header("Access-Control-Allow-Origin: *");

$rest_json = file_get_contents("php://input");
$_POST = json_decode($rest_json, true);

echo json_encode(array("sent" => true));

exit();
```

**Firefox Request.**
![firefox_request](https://user-images.githubusercontent.com/9652826/58108748-052f1680-7c0a-11e9-90ad-36e49cf35443.PNG)

**Chrome Request.**
![chrome_request](https://user-images.githubusercontent.com/9652826/58108784-12e49c00-7c0a-11e9-8008-0956b5406f42.PNG)

**Comment by chinesedfan** [comment]
Hmm, I still think it shares the same problem with https://github.com/axios/axios/issues/1998#issuecomment-492972843. In your case, the solution is setting `Access-Control-Allow-Headers: Content-Type` because I saw you used `Content-Type: application/json`.

**Comment by harshan89** [comment]
@chinesedfan thanks mate sorted the issue.
