### ISSUE TITLE
Clarification: Only Basic auth 

### ISSUE THREAD

**Issue by xinton** [axios/axios#2158]
**Section/Content To Improve**
[Request Config](https://github.com/axios/axios#request-config)

**Suggested Improvement**
On the 'auth' option are said:

> `auth` indicates that HTTP Basic auth should be used, and supplies credentials.
>   This will set an `Authorization` header, overwriting any existing
>   `Authorization` custom headers you have set using `headers`.

I think that need more clarification that bearer token auth, for example, will don't work

**Comment by xlaguna** [comment]
I'd like to tackle this
