### ISSUE TITLE
`foo.bar.domain.com` shouldn't be proxied if no_proxy has `.domain.com` item

### ISSUE THREAD

**Issue by mapleeit** [axios/axios#2160]
**Describe the bug**

`foo.bar.domain.com` would still be proxied if `no_proxy` env has `.domain.com` item.

Related code is here: https://github.com/axios/axios/blob/fd0c959355e85afa76d1728b7c7bd93a05e004a4/lib/adapters/http.js#L122

`foo.bar.domain.com` has 3 dots. On the contrary, `.domain.com` has 2 dots. So it will not match.

[request](https://github.com/request/request) uses `indexOf`, which supports this.

```js
var isMatchedAt = hostname.indexOf(noProxyZone.hostname)
var hostnameMatched = (
  isMatchedAt > -1 &&
    (isMatchedAt === hostname.length - noProxyZone.hostname.length)
)
```

Wondering that is this a but or it's a original designing. If it's a bug, I'm willing to make a PR.

**To Reproduce**

set system envariable: 
```shell
export HTTP_PROXY=http://test.proxy.com
export http_proxy=http://test.proxy.com
export HTTPS_PROXY=http://test.proxy.com
export https_proxy=http://test.proxy.com
export NO_PROXY=.domain.com
export no_proxy=.domain.com
```

```js
axios.get("http://foo.bar.domain.com")
.then(data => console.log(data))
.catch(e => console.log(e))
```

**Expected behavior**
Shouldn't proxied.

**Environment:**
 - Axios Version [e.g. 0.19.0-beta.1]

**Comment by mapleeit** [comment]
I just found that there is already a PR to solve this. #1880

**Comment by rjoaopereira** [comment]
I would like to ask the original author (@chancedickson ) for the rationale behind this comparison.

**Comment by cawoodm** [comment]
We also noticed today that Axios will proxy `127.0.0.1` even if we have `NO_PROXY=127.0.0.*`. It seems Axios (unlike fetch) does not understand wildcards.

**Comment by cawoodm** [comment]
So Axios understands suffixes (without *) - `NO_PROXY=.mydomain.com` will match `myhost.mydomain.com` but you cant get a prefix like `NO_PROXY=127.0.0.` to work no matter which way you turn it.

**Comment by nabeelamirch** [comment]
Yes it doesn't work with wildcard e.g. `*.domain.com` will not match `foo.domain.com`. Could we do something like this:
```
if (proxyElement.includes("*")) {
   return new RegExp("^" + rule.replace("*","[a-zA-Z_0-9]")+ "$")).test(str);
}
```
Over here:
https://github.com/axios/axios/blob/42eb9dfabc85ed029462da1c503f8b414b08ffd0/lib/adapters/http.js#L113

**Comment by mapleeit** [comment]
0.19.1 already solved this problem, I'm closing this issue.

**Comment by nabeelamirch** [comment]
I agree with the above, so I will raise another one with the wildcard issue

**Comment by nabeelamirch** [comment]
I have raised https://github.com/axios/axios/issues/2864
