### ISSUE TITLE
The results of the console are inconsistent with those of the request

### ISSUE THREAD

**Issue by sujianqingfeng** [axios/axios#2163]
**Describe the bug**
The results of the console are inconsistent with those of the request. Fetch module request is correct, Axios is wrong.

**To Reproduce**

```js

// axios
 axios.get('xxxx',{responseType:'text'}).then(res=>{
                    console.log(111)
                    console.log(res)
                })



// fetch
                fetch('xxxx',{method:'GET',credentials:'include'}).then(res=>{
                    console.log(111)
                    console.log(res)
                    return res.text()
                }).then(text=>{
                    console.log(222)
                    console.log(text)
                })
```

**Expected behavior**

**Environment:**
 - Axios Version 0.18.0
 - OS: win10
 - Browser Chrome
 - Browser Version 74

**Additional context/Screenshots**
- axios
![V3JAS(IB31)C@ 4}C6$YHO8](https://user-images.githubusercontent.com/16167459/58109698-af199d80-7c20-11e9-9af4-d2d58b3b315a.png)
![OG_GD@HW`6@YR{6MTGJX EW](https://user-images.githubusercontent.com/16167459/58109715-b345bb00-7c20-11e9-92c1-752889e96137.png)
- fetch
![A(9BT0NVH6W3N794NF_J 7M](https://user-images.githubusercontent.com/16167459/58109840-eee08500-7c20-11e9-951e-eb5effb2c8e6.png)
![@GY519 LJMLY%P03H {9T`2](https://user-images.githubusercontent.com/16167459/58109847-f3a53900-7c20-11e9-86ff-355aecc6f78e.png)

**Comment by Alanscut** [comment]
Has your problem been solved? It is correct in my local verification.

**Comment by chinesedfan** [comment]
Closed due to no feedbacks.
