### ISSUE TITLE
Broken URL encoding

### ISSUE THREAD

**Issue by Gilead** [axios/axios#2168]
encode() function in lib/helpers/buildURL.js reverses percent-encoding done by encodeURIComponent in a way that explicitly breaks Spring backends which treat square bracket characters [ ] as delimiters.

This makes it impossible to use Axios to request URLs with some of the reserved (as per https://tools.ietf.org/html/rfc3986#section-2.2) characters.

I understand client apps may rely on the current behaviour so I suggest to add a sibling property to config.params to handle such situation.

I see two options (not mutually exclusive):

* a property called config.rawParams that would NOT perform any URL encoding at all, leaving it to the calling code to do whatever it pleases.
This would also enable a workaround for issues like #1483 which describes a problem which is an opposite of what I am dealing with.

* a property called config.safeParams that would perform a strict percent-encoding (actually preferred by me but I appreciate there are different needs).
This could implement the encode function as

encode (str) => str.split('').map(c => /[0-9a-zA-Z-._~]/.test(c) ? c : '%' + c.charCodeAt(0).toString(16).toUpperCase()).join('');

to encode all but Unreserved (https://tools.ietf.org/html/rfc3986#section-2.3) charactes.

**Comment by asingh04** [comment]
Hi, I am new in this open source development, but i have worked with axios. 
Can i take this up as a starting issue for me?

**Comment by Gilead** [comment]
Thinking of it, it would be even better to keep the current property name and add a property called 'paramEncoding' with possible values of 'default', 'none' and 'safe'.

**Comment by asingh04** [comment]
So can it be taken up? Who can give the greenlight to work on it?
