### ISSUE TITLE
Cannot set Host header

### ISSUE THREAD

**Issue by HarryCaveMan** [axios/axios#2171]
Not sure if this is a bug, feature request, or a support/usage request, probably one of the latter. I have an API that is in a private subnet that can only be accessed by a shared endpoint. This requires me to set the header `Host: <private_endpoint_in_subnet>` with the request url as the shared endpoint. Here is an example curl request (which I know works):

```sh
curl \
    -v \
    https://<shared_endpoint_url>/<api_route> \
    -H Host: <private_endpoint_in_subnet> \
    -H Content-Type: application/json \
    -POST \
    -d <body>
```
## What want to do:
Axios for ajax in a static react front end, back end service is located at `<private_endpoint_in_subnet>` with a `<shared_endpoint_url>` that forwards using the `Host` header. All requests must be sent to `<shared_endpoint_url>` with the header `Host: <private_endpoint_in_subnet>` to reach the service.

## What I tried:
I have tried both:

 ```js
axios.defaults.common.baseURL = "<shared_endpoint_url>";
axios.defaults.common.headers["Host"] = "<private_endpoint_in_subnet>";
let data = <body>;
axios.post("https://<shared_endpoint_url>/<api_route>",data);
``` 
and manually creating a header object like so:
```js
axios.defaults.common.baseURL = "<shared_endpoint_url>";
let hostHeader = {Host:"<private_endpoint_in_subnet>"};
let data = <body>;
axios.post("https://<shared_endpoint_url>/<api_route>",data,{headers:hostHeader});
``` 

## What I expected:
My requests are sent to `<shared_endpoint_url>` with the header `Host: <private_endpoint_in_subnet>`.

## What actually happened:
My requests are sent to `<shared_endpoint_url>` with the header `Host: <shared_endpoint_url>`.

Axios seems to always change my `Host` header back to whatever is stored in `axios.defaults.common.baseURL`, no matter when/how I try to change it. I did try to just use this fact to set the host there, but that unfortunately has the following side effect: 

My requests are sent to `<private_endpoint_in_subnet>` with the header `Host: <private_endpoint_in_subnet>`

, which also won't do in my case.

## My question:
Is there any way to set the `Host` header to be my internal endpoint?

**Comment by HarryCaveMan** [comment]
Just checking in, it's been about a month since I posted this.

**Comment by Alanscut** [comment]
tested in v0.18.0 and v0.19.0 and that's ok. Please check the way you defined a global header.
Priority ordering: request level > instance level > global level.
**global level:**
```
axios.defaults.headers.common["Host"] = "<xxxxx>";  // axios.defaults.common.headers["Host"]  will report an undefined property error
```
**instance level:**
```
const instance = axios.create(...);
instance.defaults.headers.common['Host'] = "yyyyy";  // will override 'xxxxx'
```
**request level:**
```
let hostHeader = { Host: "zzzzz" };  // will override `xxxxx` and `yyyyyy`
instance.post("/user/12345", data, { headers: hostHeader }).then(...);
```

**Comment by HarryCaveMan** [comment]
This ended up being a browser issue rather than an axios issue, turns out most browsers to not allow you to override the `Host` header.
