### ISSUE TITLE
IPv6 host support?

### ISSUE THREAD

**Issue by boxsnake** [axios/axios#2172]
Anyway to use IPv6 hostnames?

I did something like this:
```js
const Axios = require('axios');
Axios
    .get('https://[some_ipv6_host]/')
    .then(res => console.log(res.data))
    .catch(err => console.error(err));
```

However, the IPv6 host, for example `1234:abcd:ffff::1234` is rendered as `1234:abcd/:ffff::1234`, rather than an IPv6 host.

Anyway to solve this? Thanks.

**Comment by jasonsaayman** [comment]
@boxsnake I'm going to try to give this a test on my local machine. Will update you if I find where the issue is occurring and then put in a pull request.

**Comment by zemse** [comment]
Is there anyway to use ipv6 as host with axios?
