### ISSUE TITLE
listen to upload progress event, every 10% onUploadProgress

### ISSUE THREAD

**Issue by liamm12** [axios/axios#2175]
**Describe the question**
How can I set a interval count to `onUploadProgress`

**Example Code**

```js
 axios.request( {
                 method: "post",
                 url: URL",
                 data: data,
                 responseType:'json',
                 onUploadProgress: (p) => {
                     this.setState({
                         progress: p.loaded  / p.total
                     })
                 }
```

**Expected behavior, if applicable**
Should listen to download progress event, every 10% 

**Environment:**
 - Axios Version [^0.18.0]
 - Additional Library Versions [e.g. React 16.8.3, React Native 0.59.5]

**Comment by jasonsaayman** [comment]
@liamm12 if you are looking for download progress then the example given above should rather be using:

```js
// `onDownloadProgress` allows handling of progress events for downloads
  onDownloadProgress: function (progressEvent) {
    // Do whatever you want with the native progress event
  },
```

Let me know if this is what you may have been looking for?

**Comment by liamm12** [comment]
Hey @jasonsaayman, I'm looking for upload progress will emit every 10% or 5% ...

**Why do I want to do that?**
Because in ReactJS I'm using `setState` API which will re-render the component on each state update so using that in `onUploadProgress` event will cause component leaks.

I can fix that with a different way but I'm asking if there's a build in way in Axios to specify an object as the first argument which contains for example `count` or `interval` to the frequency of progress event, so I can put a custom interval number

Like so
```
.onUploadProgress({ interval : 250 },(written, total) => {
        console.log('uploaded', written / total)
    })
```

**Comment by jasonsaayman** [comment]
@liamm12 I had a look at the source and there is currently no native way of doing what you would like to within axios however I'm certain that you could intercept the native progress event and then handle that via an interval.

**Comment by ComputerCarl** [comment]
Listen to all the events but only respond to them using modulus `Math.floor(written/total) % 10 === 0`.
Since this may happen many times, also use a flag to check if event was emitted already?

**Comment by rxicon** [comment]
> Hey @jasonsaayman, I'm looking for upload progress will emit every 10% or 5% ...
> 
> **Why do I want to do that?**
> Because in ReactJS I'm using `setState` API which will re-render the component on each state update so using that in `onUploadProgress` event will cause slow performance.
> 
> I can fix that with a different way but I'm asking if there's a build in way in Axios to specify an object as the first argument which contains for example `count` or `interval` to the frequency of progress event, so I can put a custom interval number
> 
> Like so
> 
> ```
> .onUploadProgress({ interval : 250 },(written, total) => {
>         console.log('uploaded', written / total)
>     })
> ```

hi，How do you fix the problem ，thx
