### ISSUE TITLE
API IN EDGE OR CLOUDFLARE DENIED ME

### ISSUE THREAD

**Issue by cheerly** [axios/axios#2181]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jasonsaayman** [comment]
@cheerly Please, can you fill out the request correctly? We cannot help should you not follow the guidelines correctly.

**Comment by emilyemorehouse** [comment]
Closing since this doesn't have information on the issue
