### ISSUE TITLE
Vulnerability found

### ISSUE THREAD

**Issue by paOol** [axios/axios#2183]
*High severity*

![image](https://user-images.githubusercontent.com/5941389/58590100-30bc8d00-8218-11e9-9434-6883c702a5a3.png)

**Comment by jalleyne** [comment]
+1 on this, got this today and will need to roll out a fix for compliance asap. If nobody has bandwidth i can try to jump on this next week.

**Comment by vincentleekp** [comment]
+1 here, would like to get this fix.

**Comment by jordandc1** [comment]
+1 here, any solutions?

**Comment by aazcast** [comment]
+1, solutions?

**Comment by spilist** [comment]
It is merged https://github.com/axios/axios/pull/1485 not not released yet. You may refer to https://snyk.io/vuln/SNYK-JS-AXIOS-174505.

**Comment by sfryffdc** [comment]
Is there a plan to make a release including this? Is there anything we can do to help speed this?

**Comment by soundstep** [comment]
I'd like to also know if there is a plan to release a version with the patch.

**Comment by nvbach91** [comment]
big +1

**Comment by johnsmera** [comment]
up +1

**Comment by pxgamer** [comment]
As I mentioned in #1485, it might be better to click the `Subscribe` button for this issue instead of commenting with a `+1` 🙂 That way you'll be notified without creating notifications or emails for everyone else. I know this is going to be popping up for a lot of GitHub repositories.

![Subscribe button screenshot](https://image.prntscr.com/image/-gY3jeYiR6OBY8NO9SL3Dw.png)

**Comment by ErKiran** [comment]
When will this issue be fixed? I have received tons of mail from github regarding axios.

**Comment by tarikool** [comment]
I'm also having this issue. I don't know nothing about it :'( someone pls help!!

**Comment by limonte** [comment]
Pressing the "Subscribe" button means the spam-attack because of people like ^ ^

Oh, wait a moment, now I'm one of them :)

--- 

Fellas, please click this button instead of leaving useless comments

![image](https://user-images.githubusercontent.com/6059356/58633214-81071e00-82f0-11e9-84f7-28ea2314844f.png)

**Comment by Zu3zz** [comment]
when will version 0.19.0 be released?

**Comment by anulman** [comment]
Pinging @nickuraltsev & @mzabriskie, seeing that @emilyemorehouse is no longer listed [on npm](https://npmjs.org/package/axios) as a collaborator.

Per @spilist's [comment](https://github.com/axios/axios/issues/2183#issuecomment-497164793), it seems the fix is already merged (#1485). Can we please get an 0.19.0 or 0.18.0.patch release?

**Comment by mfrobben** [comment]
If you really have to get a fix out for your IT team and you're ok taking what's on tip: `npm install --save git://github.com/axios/axios.git#f28ff93`

**Comment by emilyemorehouse** [comment]
0.19.0 has a fix and has been released!

**Comment by tybro0103** [comment]
Since this repo is pre-v1, this change (and only this change) really should have been published as a patch bump (`0.18.1`) so that apps which have the dependency set to `^0.18.0` can get the patch automatically.

**Comment by emilyemorehouse** [comment]
@tybro0103 agreed - I plan on releasing an 0.18.1 as well but need to get a branch set up to cherry-pick the fix since this project always released from `master`

**Comment by ritou11** [comment]
@emilyemorehouse It seems that once you release a version on npm, you cannot roll it back. So if it's true, maybe you should keep 0.19.0 or it would cause more trouble later.

**Comment by brandon-pereira** [comment]
> @emilyemorehouse It seems that once you release a version on npm, you cannot roll it back. So if it's true, maybe you should keep 0.19.0 or it would cause more trouble later.

They can deploy both `0.19.0` and `0.18.1`.

**Comment by ngl4** [comment]
Thank you @emilyemorehouse and everyone! Problem fixed!

**Comment by culanag** [comment]
Got it fixed from the update, thanks @emilyemorehouse and everyone! For my mates to see just run `npm install axios@latest --save`

**Comment by soundstep** [comment]
Thanks for the release!

**Comment by lukewhitehouse** [comment]
Just to confirm, is a patch release going to be published, or do we need to use the`0.19.0` release for the fix?

**Comment by Robdel12** [comment]
Don't want to pile on (sorry!) but I'm also curious about `0.18.1`. Looks like `0.19.0` carries some breaking changes for us. We're looking to wait for the patch rather than trying to upgrade & fix the break.

**Comment by emilyemorehouse** [comment]
I'm actively working on `0.18.1` — hoping to have it released sometime today!

**Comment by Robdel12** [comment]
You're the best! Thank you for all the work on this 🤗

**Comment by FerCruzBanegas** [comment]
Hello forgiveness for my ignorance, I have in my project installed axios 0.18 and when I uploaded my project to github I receive the alert: "[We found a potential security vulnerability in one of your dependencies](url)." what is the solution that you managed to find here?

**Comment by vesper8** [comment]
with `"axios": "^0.18"` you should already be pulling 0.18.1 which has the vulnerability patched.

If you want to make sure you can change it to `"axios": "^0.18.1",` in your package.json file. That should make the warning go away

**Comment by FerCruzBanegas** [comment]
@vesper8 thank you very much now I will update my dependence

**Comment by tarikool** [comment]
dude someone pls tell me how do I update my "Axios! 13 days n I still have noqlue!"

**Comment by zackseuberling** [comment]
> dude someone pls tell me how do I update my "Axios! 13 days n I still have noqlue!"

the easiest way to resolve the vulnerability without changing functionality is to upgrade from `0.18.0` to `0.18.1`.

```npm install axios@0.18.1```

or

```yarn add axios@0.18.1```
