### ISSUE TITLE
GET all file names (readdir) by URL?

### ISSUE THREAD

**Issue by igoriok1994** [axios/axios#2185]
Hi,

Is there any way to get all file names by URL?

Eg.

I can get specific file:

```
axios.get("localhost:8080/folder/text.txt").then((res) => {
      something
});
```

But how can I get folder content?

```
axios.get("localhost:8080/folder").then((res) => {
      where res - array of files / file names
});
```

**Comment by ikesau** [comment]
This is more of a server configuration issue, and has nothing to do with axios. Whatever server is listening on port 8000 needs to have a rule configured for that type of request at that route.

**Comment by jasonsaayman** [comment]
@igoriok1994 I don't know what the end goal that you would like to achieve is however I think you are looking for a different type of tool. Axios is an HTTP client, which is not used to list the contents of a foler.

**Comment by emilyemorehouse** [comment]
Closing as this isn't an issue with Axios
