### ISSUE TITLE
Github security alert

### ISSUE THREAD

**Issue by rafaeltokyo** [axios/axios#2187]
I have a security alert in github with axios.

<img width="770" alt="Screen Shot 2019-05-30 at 10 13 53 AM" src="https://user-images.githubusercontent.com/38796439/58635378-1cce6500-82c4-11e9-8339-4e8caa01d21b.png">

**Comment by kallard1** [comment]
Duplicate #2183

**Comment by emilyemorehouse** [comment]
0.19.0 has a fix and has been released!
