### ISSUE TITLE
Request params are not getting merged with instance params

### ISSUE THREAD

**Issue by zackseuberling** [axios/axios#2190]
**Describe the bug**

Specific request params do not get merged with the instance default params. 

**To Reproduce**

```js
const instance = axios.create({
    baseURL: "http://www.example.com",
    params: {
      q: "question",
    }
  });
```

```js
instance.get("/page", 
  { 
    params: { 
      page: 2 
    }
  }
)
```

What happens is that the request param object overrides the instance default param object. The instance no longer has a query param of `q`. 

**Expected behavior**

According to the docs, all configuration options are *merged*. https://github.com/axios/axios#instance-methods

I expected request to contain both `q` and `page` params. This is also how it was working in version 0.18.0, which is how I noticed.

**Environment:**
 - Axios Version: 0.19.0
 - OS: 10.14.5 (18F132)
 - Browser: Node Express, and Chrome 
 - Browser: Node 10.15.0, Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by philipbjorge** [comment]
Here's a running example -- https://runkit.com/philipbjorge/axios-regression

**Comment by kylane** [comment]
Having a similar issue with our session based auth tokens not being merged either.

**Comment by zackseuberling** [comment]
I _believe_ the fix is as simple as moving `params` to the property to the `deepMergeProperties` section

https://github.com/axios/axios/compare/master...zackseuberling:zs-fix-merge-params

**Comment by jasonsaayman** [comment]
@zackseuberling would you like to put in a pull request for this or should I?

**Comment by jasonsaayman** [comment]
@zackseuberling could you put in a pull request for this?

**Comment by wphestiraid** [comment]
I have a same issue.

**Comment by zackseuberling** [comment]
@jasonsaayman tests are now passing (for what I assume the correct behavior is) in #2196

**Comment by JennerChen** [comment]
hope release soon , the issue made me pretty annoying

**Comment by CloudPower97** [comment]
Having the same issue. When is it going to be fixed?

**Comment by serranoarevalo** [comment]
Same here @wphestiraid  😬

**Comment by Vpr99** [comment]
Downgrading to `0.18.1` fixed it for me as a workaround! That has the security vulnerability fixed.

**Comment by wphestiraid** [comment]
@serranoarevalo I think we can use `0.18.1` :smile:

**Comment by alex-at-cascade** [comment]
This seems to also happen with `method`, if it's only specified in the `create` call and not the `request`.  Took me all day to figure that out, definitely a breaking change.  (Should this be a separate issue, or is it part of the same general problem?)

**Comment by oussemamzoughi** [comment]
any news about this one ? when it will be fixed ?

**Comment by techouse** [comment]
> any news about this one ? when it will be fixed ?

Just use `v0.18.1` for the time being. ✈️

**Comment by oussemamzoughi** [comment]
that's what i'm using, but i need to upgrade to `v0.19.0` once this is fixed due to securtiy issues

**Comment by techouse** [comment]
> that's what i'm using, but i need to upgrade to `v0.19.0` once this is fixed due to securtiy issues

What kind of security issues? `v0.18.0` had security issues, `v0.18.1` is fine.

**Comment by kylane** [comment]
NPM is still flagging 0.18.1 as vulnerable during an audit - likely a red herring.

**Comment by filippoitaliano** [comment]
If you need to use axios `0.19` like me, you can managing the parameters like this and it should work fine for now as a **workaround**.
```
// Pass to create only these params
const instance = axios.create({
  headers,
  baseURL,
  timeout,
});

// Pass others to the instance request
instance.request({
  method,
  url,
  data,
  ...options,
});
```

**Comment by nghiepit** [comment]
Waiting for an official fix 😭

**Comment by Disorrder** [comment]
Same, upgraded from 0.18. Downgrade it back :D

**Comment by KahunaCode** [comment]
upvote. just spent the afternoon chasing down this bug and came here to write an issue.

**Comment by egel** [comment]
Is there any progress to provide a fixup?

**Comment by magicdawn** [comment]
https://github.com/axios/axios/blob/v0.19.0/lib/core/mergeConfig.js#L18-L22

```js
module.exports = function mergeConfig(config1, config2) {
  // eslint-disable-next-line no-param-reassign
  config2 = config2 || {};
  var config = {};

  utils.forEach(['url', 'method', 'params', 'data'], function valueFromConfig2(prop) {
    if (typeof config2[prop] !== 'undefined') {
      config[prop] = config2[prop];
    }
  });
```

the v0.19.0 code shows that `mergeConfig(axios_instance.defaults, config)`
only the request config.params get used.

Why a minor version not compitable with previous version?
No test for this?
I have to ask.

**Comment by filippoitaliano** [comment]
@magicdawn I think they messed up. I don't get what they are waiting for to merge the fix. Pls @emilyemorehouse, help us with https://github.com/axios/axios/pull/2196 🙏!

**Comment by mahnunchik** [comment]
Any news? I got the same error then upgrade to latest version.

**Comment by bdrtsky** [comment]
Amazing. 63500 stargazers.

**Comment by jonathanalberghini** [comment]
What is the problem is this ever going to get fixed!!

**Comment by igimanaloto** [comment]
Might be a hack, but you can also patch the get method for a created axios instance:

```
const client = axios.create({
  baseURL: YOUR_URL,
})
client.originalGet = client.get
client.get = (url, { params, ...config }) =>
  client.originalGet(url, {
    ...config,
    params: {
      key: YOUR_API_KEY,
      ...params,
    },
  })
```

**Comment by CarsonF** [comment]
I wrapped the create instance and patched all the methods like this:
```ts
export const createInstance = (config?: AxiosRequestConfig): AxiosInstance => {
  const instance = axios.create(config);

  // Patch methods to merge default params into each request.
  // https://github.com/axios/axios/issues/2190
  for (const [method, configIndex] of methodsToPatch as Array<[keyof AxiosInstance, number]>) {
    const orig = instance[method] as Function;
    // @ts-ignore
    instance[method] = (...args: any[]) => {
      if (!args[configIndex]) {
        args[configIndex] = {};
      }
      args[configIndex].params = {
        ...(instance.defaults.params || {}),
        ...(args[configIndex].params || {}),
      };
      return orig.apply(instance, args);
    };
  }

  return instance;
};

const methodsToPatch = [
  ['getUri', 0],
  ['request', 0],
  ['get', 1],
  ['delete', 1],
  ['head', 1],
  ['post', 2],
  ['put', 2],
  ['patch', 2],
];
```

**Comment by janpantel** [comment]
I posted another possible workaround to the PR if anyone is interested: https://github.com/axios/axios/pull/2196#issuecomment-536060066

**Comment by janpantel** [comment]
For everyone looking for a workaround you could use mine (might not apply to all):

`npm i qs`

```
axios.interceptors.request.use(config => {
    config.paramsSerializer = params => qs.stringify({ ...params, myValue: 'foo' });
    return config;
}
```

**Comment by yasuf** [comment]
can you add specs to this?

**Comment by yasuf** [comment]
thanks for the work by the way, we just need specs and I can merge this to go out with 0.19.1

**Comment by cheelahim** [comment]
@janpantel I'm curious, why not just modify the params?
```
axios.interceptors.request.use(config => {
    config.params.myValue = 'foo';
    return config;
}
```

**Comment by cdiaz-sophilabs** [comment]
@janpantel thanks i think it works that way

**Comment by AndyOGo** [comment]
We have a very similar error.

In fact we can't even specify any instance `params` with `axios.create()`.

**Comment by michaelleone** [comment]
Same for me. Drove me nuts today! All was working fine. Then suddenly I was getting Authentication issues and CORS issues?! Yargh...

I worked out that I have updated from v18 to v19 and then inherited this bug I guess. It appears that the 'default' parameters that I defined in the instance definition (an old school authkey parameter) were not getting merged when I called that instance later on with new params, the new params killed the defaults :(.

Downgraded to version 18 solved it. Hope they fix it soon though, I like all my modules up-to-date! :P

**Comment by magicdawn** [comment]
I  turn to use umi-request in node & browser now.
so far so good. 😄

**Comment by Yalhu** [comment]
The same problem is still exit since 2020. 
Does it run as designed or when can this issue be resolved?

Axios Version: 0.19.0

Thanks for providing such a useful lib!

**Comment by techouse** [comment]
`v0.19.1` still has this bug 😞

**Comment by sumitkr003** [comment]
Fix this already. this is really annoying. took me 15 minutes to figure this bug.

**Comment by tukno** [comment]
Same problem here using `axios@0.19.2`. Using interceptors as a workaround.

**Comment by xyphers101** [comment]
Still getting same issue with  axios@0.19.2. Downgrade axios to make it work.

npm install --save axios@0.18.1

**Comment by DPOLocalAaronO** [comment]
Having this issue as well. Please fix

**Comment by miroshnik** [comment]
some kind of endless drama

**Comment by renestalder** [comment]
It's not even that the instance parameters wouldn't be merged with the call parameters. The instance parameters are not going into the parameters for the request at all. If I create an instance and define params, they are never be found in one of my get requests.

Downgrading was the easier option than defining the parameters with every get call.

**Comment by AndreSilva1993** [comment]
> It's not even that the instance parameters wouldn't be merged with the call parameters. The instance parameters are not going into the parameters for the request at all. If I create an instance and define params, they are never be found in one of my get requests.
> 
> Downgrading was the easier option than defining the parameters with every get call.

Can confirm this.

**Comment by AndreSilva1993** [comment]
Why is this issue closed? As @renestalder mentioned, in the last version, none of the instance parameters appear in any request which renders the `create` method somewhat pointless.

**Comment by elboletaire** [comment]
It's closed because it's fixed in #2656, but there's still no version for it.

**Comment by betopompolo** [comment]
I used interceptor as a workaround too, something like @cheelahim suggested:
```ts
axios.interceptors.request.use(config => {
  config.params. = {
    myValue1: 'foo',
    myValue2: 'bar',
    ...config.params,        
  }
    return config;
}
```

But still waiting for a new version to fix this bug.

**Comment by xgqfrms** [comment]
https://stackoverflow.com/questions/40947650/axios-get-in-url-works-but-with-second-parameter-as-object-it-doesnt

**Comment by slavajacobson** [comment]
woah! almost 1 year later!

**Comment by Haley-Zhu** [comment]
The bug still exist! Can't believe......

**Comment by ranjan-purbey** [comment]
The fix has been merged in #2656 but a version for it has not been cut yet

**Comment by bismarkstoney** [comment]
Just downgrade to 0.18.0

**Comment by mahnunchik** [comment]
Why it is closed?

**Comment by bdrtsky** [comment]
Just don't use `axios` instead of downgrade, use modern solutions like fetch, `got`, `ky` etc.

**Comment by AndyOGo** [comment]
Unfortunately `fetch` is out as soon as you need progress events or cancelation support.

**Comment by techouse** [comment]
Just pin your version to `^0.18.1`.

**Comment by mahnunchik** [comment]
@techouse moving to alternatives is better solution.

**Comment by jonathanalberghini** [comment]
I have always liked using axios. But the idea that this fix has been there for this long and no one can manage to assign it to a version is just a joke it's time to move on. Or get someone to manage this that actually wants to progress the product.


Jon Alberghini
Director of Technology
jon@legacyresearch.com
o. 802-323-4558 | c. 802-323-4558 | www.legacyresearch.com<http://www.legacyresearch.com>

________________________________

**Comment by ranjan-purbey** [comment]
I think it's closed because a [fix](https://github.com/axios/axios/pull/2656) has been merged and is supposed to be released in v0.20.0 . See [here](https://github.com/axios/axios/projects/4#column-7783168)

**Comment by raphaelbadawi** [comment]
Same issue here, hoping it will be fixed soon!

**Comment by khastation** [comment]
+1. downgrading for now. smh.

**Comment by mahnunchik** [comment]
@khastation @raphaelbadawi @jonathanalberghini @techouse @AndyOGo

Alternatives:

* [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) and polyfill [whatwg-fetch](https://github.com/github/fetch)
* [got](https://github.com/sindresorhus/got)
* [ky](https://github.com/sindresorhus/ky)
* [node-fetch](https://github.com/node-fetch/node-fetch)

**Comment by AndyOGo** [comment]
@mahnunchik 
Unfortunately `fetch` is out as soon as you need **progress** events or **cancelation** support.

**Comment by mahnunchik** [comment]
@AndyOGo It can be implemented like https://javascript.info/fetch-progress

**Comment by raphaelbadawi** [comment]
I found my way out using some deconstructing to separate the key param. Temporary code for sure, but since the merge is already done and 0.20.0 is underway, I'm really confident. Axios is still my way to go, even if I am experienced with fetch(). Things are usually so lean with Axios ;-)

**Comment by AndyOGo** [comment]
Thanks @mahnunchik 
Though I'm speaking about [progress events](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent) for [download and upload](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress)!

**Comment by bdrtsky** [comment]
@AndyOGo **no one needs** your **progress** events or **cancelation** support in like 99.99%, why you keeps repeating that?

**Comment by AndyOGo** [comment]
Thank you for your @bdrtsky 
Mainly for these reasons:
- `fetch` specifies several regressions compared to `XMLHttpRequest`
- **cancelation** becomes important as soon as you build large scale services
- I built a file uploader, so I need more sophisticated **progress** handling

**Comment by bdrtsky** [comment]
Exactly, everyone here are building file uploaders on the daily basics.

**Comment by jasonsaayman** [comment]
This is closed due to the fix already being assigned to 0.20 release. We are currently working on that release the point of 0.20 is to get regressions fixed and release a stable Axios again.

This is work in progress, for updates check the 0.20 project.

**Comment by paztis** [comment]
Is it possible to put it in 0.19.3 patch version ? Defect cannot be closed if it is not fixed in the same minor release...

**Comment by jasonsaayman** [comment]
I have re-opened but we wont be releasing a 0.19.3. We would like to gain stability in a 0.20 release that removes all the regression from 0.18.0 to 0.19.2.

**Comment by ProgaPanda** [comment]
Seems the only possible solution rn is to downgrade.

**Comment by adamreisnz** [comment]
When can we expect this elusive 0.20 release? Is there a beta version we can use in the mean time?

**Comment by jasonsaayman** [comment]
@adamreisnz I am working on the 0.20 release but there is still about 60 odd pull requests (brought this down from 121), with some being very old and varied amount of work in checking and making sure these pull request either are still relevant, don't present a breaking change, have tests, don't include compiled files etc etc it is a labour. I endeavour to try get it into a pre-release by July at best. We would love help testing this release as we really want to get it right before we work on a v1.

**Comment by OctupleSakura** [comment]
It is an annoying problem, hope it can be fixed, is maintained for a long time.

**Comment by markcarver** [comment]
> want to get it right before we work on a v1

There's plenty of room in `0.x` to make additional releases before `1.0.0`; you don't have to cram everything into the next release. In fact, one could argue that would just make potential new bugs just harder to track down.

**Comment by jasonsaayman** [comment]
@markcarver Sure we could however Axios is seen as pre-release currently as without a v1 it looks to most people that Axios has not released a public API see [SemVer PublicAPI](https://semver.org/#spec-item-5). With v0.20.0 we would like to bring stability and fix most regressions from the 0.19.x branch as some problems presented in this branch as well as work on errors that are easy wins.

We also do need to clear the backlog of pull requests at the same time. It is very difficult to deal with 120 odd pull request where some of them were from as far back as 2017. I promise we will get to this issue, I am going nowhere and will be supporting and working on Axios as much as I can.

Thanks

**Comment by adamreisnz** [comment]
I think there's just a lot of frustration building up, because we can't use certain plugins (e.g. axios cache adapter) unless we downgrade and lock in Axios at v0.18, or roll our own (unmaintained) version and apply the fix there.

This has been the case for quite a few months now, and I think everyone is just keen to see at least some fixes released.

Is it not possible to port some of the currently applied fixes and release a 0.19.x so that at least we can use the latest codebase? If you intend to go through another 120 pull requests, I am afraid we'll be waiting a long time until we see a 0.20 or v1.

I would personally opt for a more incremental approach, if possible.

**Comment by jasonsaayman** [comment]
@adamreisnz sure I would opt for increments too but there was alot broken from 0.18.x to 0.19.x and the idea was to try make a 0.20.0 release stable with some of the most pressing stuff in that release. We only have 60 pull requests left, I have already worked through the rest and some of those 60 are either tagged as `wip` or `v1`.

I know it has been a long time but I would like to get it right this time and not just release and break more things cause at this point that is largely possible. Also the build will need wide spread testing before it goes public. I get the frustration but if we don't get it stable and fix a ton of regressions we could release any number of increments, and still sit with over 200~ issues and 60~ pull requests that just sit there getting stale, as well as a still very broken Axios, maybe even more broken.

In addition I don't control releases at the moment and when I started helping I promised to get together a build that would fix regressions and the most pressing issues as well as not breaking anything else that worked previously. I take this pretty serious and would like to do that.

I can however try and get a 0.18.x release with any security issues etc fixed if that is something that would help?

**Comment by techouse** [comment]
> I can however try and get a 0.18.x release with any security issues etc fixed if that is something that would help?

That would be awesome.

P.S.:  We all appreciate the hard work you're doing by maintaining a package that is intricate to so many web projects. 😊

**Comment by adamreisnz** [comment]
> I can however try and get a 0.18.x release with any security issues etc fixed if that is something that would help?

Yes I concur, that would definitely be appreciated. 

If you need any help testing some of the new stuff let me know I'd be open to doing that.

**Comment by adamreisnz** [comment]
I can yes, will try to switch to that branch this weekend for one of our projects.

**Comment by adamreisnz** [comment]
@jasonsaayman so far so good, seems to be working well 👍

**Comment by wolframdeus** [comment]
It seems, issue can be closed now

**Comment by jasonsaayman** [comment]
Closing after receiving feedback that this is now working as it should under the new release.

**Comment by kallezz** [comment]
Still having this issue in 0.24.0.

`const api = axios.create({
  baseURL: url,
  params: {
    api_key,
  },
});`

` api(`/xxxxx`, {
        method: "GET",
        params: config.query,
});`

config.query contains page param. It does not get merged with the instance params.

**Comment by linchen5913** [comment]
Still having this issue in 0.27.2
I've created an instance with existed query `{slug:"foo"}`
Then have another api call `https://xxx/?randomQuery=ZZZZZZ`
The only param is passed is `{slug:"foo"}`. 
And I cannot downgrade to 0.20.0 since I'm using AbortController.
Any advice?

**Comment by simoneb** [comment]
@linchen5913 can you provide a repro please?

**Comment by linchen5913** [comment]
> @linchen5913 can you provide a repro please?

@simoneb Oops, I happened to replace the whole params with
`axios.interceptors.request.use(config=>{config.params={query:"foo"}})`
I should be using the following code instead:
`axios.interceptors.request.use(config=>{config.params={query:"foo", ...config.params}})`
which solved the problem

Thank you so much for your time and response, I made a mistake here.

**Comment by johncmunson** [comment]
> Closing after receiving feedback that this is now working as it should under the new release.

Was the intent to *merge* params with the default instance params? Because I can definitively say say that this is not happening. The default params are being completely overridden. I'm using ^1.4.0.
