### ISSUE TITLE
Axios throws "Network error" even when the API response is valid

### ISSUE THREAD

**Issue by knkbga** [axios/axios#2194]
In vuex store, I have defined an action as below:
```javascript
  actions: {
    register({commit}, user){
      return new Promise((resolve, reject) => {
        commit('auth_request')
        axios({
          url: 'http://localhost:3000/user/register',
          data: qs.stringify({
            userName: user.userName,
            email: user.email,
            password: user.password
          }), 
          method: 'POST',
          headers: {
            'content-type': 'application/x-www-form-urlencoded'
          }
        })
        .then(resp => {
          ...
        })
        .catch(err => {
          ...
        })
      })
    }
  }
```

The API is working and the response is having status 201, but then also it is throwing error every time.
Even when there is nothing in the `.then` block, then also the same issue is happening.

Can someone please let me know what the issue might be.

Thanks

**Comment by jasonsaayman** [comment]
@knkbga I don't see anything wrong with the way you have formed the request. This is going to be pretty hard to replicate. Please, could you try setting up an example on runkit, this would greatly assist in trying to get to the bottom of your issue.

**Comment by knkbga** [comment]
I just read an article online, telling that to resolve CORS issue we have to make changes on the backend as well. As my server was written in node.js, I added a middleware as follows:
```javascript
app.use(function(req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Allow-Credentials', true);  
  next();
});

Its working now. I am just curious to know if this was the issue or the issue can be solved by not making any changes to the server.

Thanks
```

**Comment by jasonsaayman** [comment]
@knkbga ok great I'm going to close this issue as it seems to not have been Axios related.
