### ISSUE TITLE
"utils.deepMerge is not a function" in version 0.19.0

### ISSUE THREAD

**Issue by Tony4469** [axios/axios#2197]
Hi,

I just updated to axios 0.19.0 and I have a breaking bug I don't manage to solve :
> Uncaught TypeError: utils.deepMerge is not a function
    at mergeDeepProperties (mergeConfig.js:26)
    at Object.forEach (utils.js:234)
    at mergeConfig (mergeConfig.js:23)
    at Axios.request (Axios.js:43)
    at Axios.<computed> [as post] (Axios.js:80)
    at Function.wrap [as post] (bind.js:11)

It seems that the deepMerge function is not exported from "utils", although I see it defined in the file. When I log the "utils" import I get the following : 
> extend: ƒ extend(a, b, thisArg)
forEach: ƒ forEach(obj, fn)
isArray: ƒ isArray(val)
isArrayBuffer: ƒ isArrayBuffer(val)
isArrayBufferView: ƒ isArrayBufferView(val)
isBlob: ƒ isBlob(val)
isBuffer: ƒ (obj)
isDate: ƒ isDate(val)
isFile: ƒ isFile(val)
isFormData: ƒ isFormData(val)
isFunction: ƒ isFunction(val)
isNumber: ƒ isNumber(val)
isObject: ƒ isObject(val)
isStandardBrowserEnv: ƒ isStandardBrowserEnv()
isStream: ƒ isStream(val)
isString: ƒ isString(val)
isURLSearchParams: ƒ isURLSearchParams(val)
isUndefined: ƒ isUndefined(val)
merge: ƒ merge() /* obj1, obj2, obj3, ... */ { var result = {}; function assignValue(val, key)
trim: ƒ trim(str)
__proto__: Object

Can you please help me with this issue ?

Thanks

**Environment:**
 - Axios Version : 0.19.0
 - Browser :  Chrome
 - Browser Version : 74.0.3729.169
 - React 16.8.0

**Additional context/Screenshots**
<img width="631" alt="image" src="https://user-images.githubusercontent.com/18621959/58721665-065c0280-83c5-11e9-8af7-04f574038179.png">

**Comment by AvishekSingha01** [comment]
I faced same problem, I just revert axios version 0.0.19 to 0.0.18(Published One Year Ago), its worked perfectly.

**Comment by Tony4469** [comment]
Hi Avishek, unfortunately v0.18.0 has a major security vulnerability, that's why I have to update to v19

**Comment by jasonsaayman** [comment]
@Tony4469 you can use version 0.18.1, this is a patched release that mends the security issue.

**Comment by chinesedfan** [comment]
@Tony4469 @AvishekSingha01 Can you provide a full reproducible example?

**Comment by andynguy3n** [comment]
I got the same issue. have to go back 0.18.1

**Comment by akopchinskiy** [comment]
Still broken (v0.19.2)
```
at forEach (node_modules\axios\lib\utils.js:238:12)
at deepMerge (node_modules\axios\lib\utils.js:298:5)
```

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
