### ISSUE TITLE
Default Authorization header no longer working in 0.19.0

### ISSUE THREAD

**Issue by kris2kris** [axios/axios#2199]
**Describe the bug**
Since axios 0.19.0, the default Authorization header is no longer set in query. It works in 0.18.X.

**To Reproduce**
Create an axios adapter and set to it a default Authorization header, nothing is sent in the query.

```js
axios.defaults.headers.common.Authorization = 'Bearer ANY SECURITY TOKEN';
```

**Comment by vserpokryl** [comment]
It works for me

```JS
const axios = require('axios');
const { version } = require('axios/package');

console.log(`Axios version: ${version}`);

axios.defaults.headers.common['Authorization'] = 'Bearer test';

axios.get('https://api.ipify.org?format=json')
  .then(({ data, config }) => {
    console.log({
      data,
      headers: config.headers,
    });
  });

axios.get('http://api.ipify.org?format=json')
  .then(({ data, config }) => {
    console.log({
      data,
      headers: config.headers,
    });
  });
```

Result:
```
Axios version: 0.19.0

{ data: { ip: '91.201.73.197' },
  headers:
   { Accept: 'application/json, text/plain, */*',
     Authorization: 'Bearer test',
     'User-Agent': 'axios/0.19.0' } }

{ data: { ip: '91.201.73.197' },
  headers:
   { Accept: 'application/json, text/plain, */*',
     Authorization: 'Bearer test',
     'User-Agent': 'axios/0.19.0' } }
```

**Comment by kris2kris** [comment]
Hello @vserpokryl ,

I understand the problem,
I set axios default header and then, I do this 
`const adapter = axios.create({
    baseURL: `http://localhost:8080/my-api`,
    headers: {
        Accept: 'application/json;charset=UTF-8',
    },
});
`

In 0.18.X, it use axios default headers but not in 0.19.0

**Comment by vserpokryl** [comment]
Heelo @kris2kris , I think everything works

1 version:
```JS
const axios = require('axios');
const { version } = require('axios/package');

console.log(`Axios version: ${version}`);

const adapter = axios.create({
  baseURL: `https://api.ipify.org`,
  headers: {
    Authorization: 'Bearer test',
    Referer: 'https://api.ipify.org',
  },
});

adapter.get('/?format=json')
  .then(({ data, config }) => {
    console.log({
      data,
      headers: config.headers,
    });
  });
```

```
Axios version: 0.19.0

{ data: { ip: '91.201.71.191' },
  headers:
   { Accept: 'application/json, text/plain, */*',
     Authorization: 'Bearer test',
     Referer: 'https://api.ipify.org',
     'User-Agent': 'axios/0.19.0' } }
```

2 version:
```JS
const axios = require('axios');
const { version } = require('axios/package');

console.log(`Axios version: ${version}`);

axios.defaults.headers.common['Authorization'] = 'Bearer test';

const adapter = axios.create({
  baseURL: `https://api.ipify.org`,
  headers: {
    Referer: 'https://api.ipify.org',
  },
});

adapter.get('/?format=json')
  .then(({ data, config }) => {
    console.log({
      data,
      headers: config.headers,
    });
  });
```

```
Axios version: 0.19.0

{ data: { ip: '91.201.71.191' },
  headers:
   { Accept: 'application/json, text/plain, */*',
     Authorization: 'Bearer test',
     Referer: 'https://api.ipify.org',
     'User-Agent': 'axios/0.19.0' } }
```

**Comment by kris2kris** [comment]
@vserpokryl I think I made a mistake when I explained the problem.

I set default headers **AFTER** adapter creation...

**Comment by vserpokryl** [comment]
@kris2kris do you set default settings for the adapter?

```JS
const axios = require('axios');
const { version } = require('axios/package');

console.log(`Axios version: ${version}`);

const adapter = axios.create({
  baseURL: `https://api.ipify.org`,
  headers: {
    Referer: 'https://api.ipify.org',
  },
});

adapter.defaults.headers.common['Authorization'] = 'Bearer test';

adapter.get('/?format=json')
  .then(({ data, config }) => {
    console.log({
      data,
      headers: config.headers,
    });
  });
```

```
Axios version: 0.19.0

{ data: { ip: '91.201.71.191' },
  headers:
   { Accept: 'application/json, text/plain, */*',
     Authorization: 'Bearer test',
     Referer: 'https://api.ipify.org',
     'User-Agent': 'axios/0.19.0' } }
```

**Comment by kris2kris** [comment]
@vserpokryl I do this to set header for all my "adapters"
```
const adapter = axios.create({
    baseURL: 'http://localhost:8080/my-api',
    headers: {
        Accept: 'application/json;charset=UTF-8',
    },
});

axios.defaults.headers.common['Authorization'] = 'Bearer test';

adapter.get(....);
```

Adapter send Authorization header in 0.18 but not in 0.19.0

**Comment by glebtv** [comment]
axios global defaults (```axios.defaults.headers```) seem to no longer affect prevoiusly-created  axios client instances. Is this an intended change?

Example:
0.18 - header is sent https://codesandbox.io/s/axios018-8fg9d
0.19 - header is not sent https://codesandbox.io/s/axios019-5ddn8

**Comment by glebtv** [comment]
This seems to be intended - https://github.com/axios/axios/pull/1395

**Comment by jasonsaayman** [comment]
@glebtv this seems to in fact be intended. The documentation might need a bit of adjustment for this, I will have a look at it, however, it seems you may need to implement this:

```js
instance.defaults.headers.common['Authorization'] = AUTH_TOKEN;
```

This will change the instance defaults rather than the global default. This makes sense especially in this example.

**Comment by mrkhanakia** [comment]
Same issue not working for me also after updating to 0.19.0

**Comment by mrkhanakia** [comment]
> axios global defaults (`axios.defaults.headers`) seem to no longer affect prevoiusly-created axios client instances. Is this an intended change?
> 
> Example:
> 0.18 - header is sent https://codesandbox.io/s/axios018-8fg9d
> 0.19 - header is not sent https://codesandbox.io/s/axios019-5ddn8

Not working for me also

**Comment by Vikas2408** [comment]
this.http.defaults.headers.common['Authorization'] = 'Bearer TOKEN' ;

**Comment by jasonsaayman** [comment]
@mrkhanakia this is an intended change in 0.19.

**Comment by ramonitor** [comment]
Had the same issue after upgrading to 0.19, but after changing the default headers of the axios instance, the problem is solved.

**Comment by DarrenClyde** [comment]
@glebtv have the same problem

**Comment by slatqh** [comment]
same problem here, cant send headers from a client. From postman it's works fine. 
axios.post('URL', 
{
 headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
})
