### ISSUE TITLE
url param is ignored in axios.create in version 0.19

### ISSUE THREAD

**Issue by filippoitaliano** [axios/axios#2200]
**Section/Content To Improve**
https://github.com/axios/axios#axioscreateconfig

**Suggested Improvement**
_Shouldn't the doc be clearer about which parameters are intended to be used with axios.create?_

Until version 0.19 I used to pass the request url to axios.create without using baseURL:

```
const instance = axios.create({
  data,
  headers,
  method,
  url: derivedUrl,
  ...omit(options, 'resource', 'headers', 'customErrorInterceptor'),
});

instance.interceptors.response.use(
  response => response,
  (error) => {
    if (options.customErrorInterceptor) {
      if (typeof options.customErrorInterceptor === 'function') {
        options.customErrorInterceptor(error);
      }
    } else globalXHRErrorHandling(error);
    return Promise.reject(error);
  },
);

return instance.request();
```
The reason of this strange choice is I want a global interceptor that sometimes is overridden by a specific one.

With 0.19 release the url param is totally ignored by axios.create. I have to pass it to instance.request.

Thanks!

**Comment by jasonsaayman** [comment]
@filippoitaliano is this happening on post requests? If so this is a known issue, can you check if #2196 fixes this?

**Comment by filippoitaliano** [comment]
Yes! This is a duplicate of #2190.
