### ISSUE TITLE
Custom properties for config

### ISSUE THREAD

**Issue by someden** [axios/axios#2203]
So, if I understand it right, in 0.19.0 you've added `mergeConfig`
And this function filter config and remove custom properties from it.
It broke my solution for cancellation:

How it works:
```js
const requestManager = new RequestManager();
const instance = axios.create();
requestManager.patchAxiosInstance(instance);

const search = q =>
  instance.get('/search', {
    cancelable: true, // this is no longer possible in 0.19.0
    params: { q },
  });
```
![Screenshot 2019-06-05 at 16 30 01](https://user-images.githubusercontent.com/7009699/58960132-2ddd1180-87af-11e9-8eb1-3542c4d0b1c1.png)

The solution:
```js
class RequestManager {
  constructor() {
    this.pendingRequests = new Map();
  }

  patchAxiosInstance(instance) {
    instance.interceptors.request.use(config => {
      if (!config.cancelable) return config; // this is no longer possible in 0.19.0

      const source = axios.CancelToken.source();
      const requestId = `${config.method}_${config.url}`;
      const cancelToken = source.token;
      this.addRequest(requestId, source.cancel);
      return { ...config, cancelToken, requestId };
    });

    instance.interceptors.response.use(response => {
      const { requestId } = response.config; // this is no longer possible in 0.19.0
      if (requestId) {
        this.removeRequest(requestId);
      }
      return response;
    });
  }

  addRequest(requestId, cancelFn) {
    this.cancelRequest(requestId);
    this.pendingRequests.set(requestId, cancelFn);
  }

  removeRequest(requestId) {
    this.pendingRequests.delete(requestId);
  }

  cancelRequest(requestId) {
    if (this.pendingRequests.has(requestId)) {
      const cancelFn = this.pendingRequests.get(requestId);
      cancelFn();
      this.removeRequest(requestId);
    }
  }
}
```

So, is it possible to relax filter in `mergeConfig` for custom properties? Because sometimes it is needed and very helpful in interceptors or somewhere else.

**Comment by someden** [comment]
And packages like `axios-cancel` or `axios-cancelable` is not compatible with 0.19.0, because they have the same solution

**Comment by rafaelrenanpacheco** [comment]
There is a PR to enable custom configs again: #2006

**Comment by LeeRayno** [comment]
the same issue
```js
I wanna add the custom config like this

// custom options
const DEFAULT_OPTIONS = {
  isLoading: true, // show loading
  isAutoMsg: true, // show err msg
  isApiHost: true, // prefix api url
  isApiMock: false, // prefix /api/mock to mock data
  isRemoveField: true, // remove all empty params
  removeFields: [] // manual remove empty params
}

// add the custom options to the method(get, post, etc)
export function get (url = '', params = {}, config = {}) {
  const opts = { ...DEFAULT_OPTIONS, ...config }
  opts.params = _getParams(params, opts)
  return instance.get(_getUrl(url, opts), opts)
}

this is not working @0.19.0, but working less than 0.18.0
```

**Comment by thekiwi** [comment]
This also impacts us - we use https://github.com/softonic/axios-retry but with `axios@0.19.0` the retry module loses it's config and causes Axios to retry **forever**. 

We've reverted to 0.18.1 for now, but it would be great if there was a way forward with the newest Axios.

**Comment by GFwer** [comment]
Same issue with me
```
instance[method](url, {
  params,
  headers,
  ...customOption
})


instance.interceptors.response.use(
  res => {
	console.log(res.config); // custom option is not exist here
  }
)
```

**Comment by balliegojr** [comment]
I am having the same problem, I have a custom property for my loader screen interceptor.

@someden Nice solution with the cancelable

**Comment by ansonhorse** [comment]
I just found my app behaviors wired, and It turned out to be because of upgrading to v0.19.0.
Now I downgrade to v0.18.0, all things come back to life😁

**Comment by redredredredredred** [comment]
I made a hook that worked for me. This fixes the problem
```
let retries = 0
axiosRetry(axios, {
    retries: 3,
    retryCondition:(error)=>{
      let config = error.config;
      if (!config) {
        return false;
      }
      retries = retries + 1
      if(retries>= 3){
        retries = 0
        return false
      }
      return true
      
      // do something 
      // axiosRetry.isNetworkError
      // axiosRetry.isRetryableError
      //axiosRetry.isSafeRequestError
      // axiosRetry.isIdempotentRequestError
      // axiosRetry.isNetworkOrIdempotentRequestError
      // axiosRetry.exponentialDelay
    }
  });
```

**Comment by iwaszko** [comment]
This was also discussed in #1718.

**Comment by xsteadybcgo** [comment]
> There is a PR to enable custom configs again: #2006

branch has conflicts that must be resolved

**Comment by someden** [comment]
I think it is better to close issue only when some fixes will be merged and the new version will be pushed to npm.
So, @felipewmartins maybe reopen?

**Comment by crobinson42** [comment]
This is still very much a bug/issue that should remain open, I agree with @someden - until this is released to npm, it is not useful for any consumers of the package to have this ticket closed.

**Comment by shiny** [comment]
it refusing me too, this bug still exists since axios stays at version 0.19.0.

**Comment by kordeviant** [comment]
please reopen exists in 0.19.2
