### ISSUE TITLE
overwrite/delete headers from axios.create instance

### ISSUE THREAD

**Issue by webdesignberlin** [axios/axios#2204]
Hi there, is the follow behavior a bug or not intend:

if i create a axios instance with a header like this 
```js
const HTTP = axios.create({
  baseURL: 'test.test',
  headers: {
    'X-Foo': 'value',
  },
});
```
it is no longer possible to overwrite/delete the header like

`HTTP({ url: 'other', baseURL: null, headers: null })`

baseUrl and url can be overwritten, headers not. why. respectively how i can?

**Environment:**
 - Axios Version latest

<3 axios

**Comment by jasonsaayman** [comment]
@webdesignberlin this is due to parameters now being deep merged, though I do like the idea of being able to overwrite the whole headers object in one go. There is actually no workaround, you could set the property ```headers.X-Foo``` to null. However, once the header has been added to the instance it seems to not be possible to clear it completely. I will see if there is a way to have both deep merge as well as a way to completely clear the headers.

**Comment by Alanscut** [comment]
hi @webdesignberlin , I tested it using your code in v0.19.0, and the result shows I can overwrite the headers by setting it to `null` or  `{'X-Foo': 'new'}`.
```
HTTP({url:'/api', baseURL:null,headers:{'X-Foo': 'new'}});  // then change headers to "X-Foo:new"
HTTP({url:'/api', baseURL:null,headers:null});  // then headers cleared
```

**Comment by webdesignberlin** [comment]
hi @Alanscut 

jup, seems like it work with
`HTTP({url:'/api', baseURL:null,headers:null});  // then headers cleared`

but if i use the post method

`HTTP.post('/api', {
            content1: 'blubb1',
            content2: 'blubb2',
          }, { headers: null })`

it doesnt work. Currently i use:

`
HTTP({
          url: '/api',
          method: 'post',
          headers: null,
          data: {
            content1: 'blubb1',
            content2: 'blubb2',
          },
        });
`

and this works fine. (0.19.0)

**Comment by chinesedfan** [comment]
@webdesignberlin Do you confirm that case3 works for you? I tested with following script,

```
var axios = require('axios')
var adapter = function(config) {
  console.log(config.headers)
  return Promise.resolve({data: 12})
}

// set the log adapter
axios(({url:'/api', baseURL:null,headers:null, adapter}))
axios.post('/api', { content1: 'blubb1', content2: 'blubb2', }, { headers: null, adapter })
axios({ url: '/api', method: 'post', headers: null, data: { content1: 'blubb1', content2: 'blubb2', }, adapter})
```

Both v0.19.0 and v0.21.1 have the same output. The config merging is working as expected. The reason why post method will still have headers is due to the default `transformRequest` adds for object data.

```
{}
{ 'Content-Type': 'application/json;charset=utf-8' }
{ 'Content-Type': 'application/json;charset=utf-8' }
```
