### ISSUE TITLE
 when give a relative baseURL, url must be end with '/'

### ISSUE THREAD

**Issue by wangjiancn** [axios/axios#2213]
**request.js** :
```js
import Axios from 'axios'

const axiosInstance = Axios.create({
  baseURL: '/django',
  timeout: 60 * 1000,
})

export default axiosInstance

```

**api.js**:
```js
import request from './request'

export function fetchTags(query) {
  return request({
    method: 'get',
    url: '/tag',
    params: query,
  })
}

export function fetchCategorys(query) {
  return request({
    method: 'get',
    url: '/cat/',
    params: query,
  })
}
```

In one vue page,the request like this:
```
# fetchCategorys
Request URL: http://localhost:8080/django/cat/

# fetchTags
Request URL: http://localhost:8080/tag/

```

**Environment:**
 - Axios Version  0.18.0
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Browser Version  75.0.3770.80
 - Additional Library Versions Vue2.6.10

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/37948697/59160228-509c5c80-8b06-11e9-9cdf-78278bc0af4c.png)
![image](https://user-images.githubusercontent.com/37948697/59160236-5db94b80-8b06-11e9-8016-b059d2886d9b.png)

**Comment by jasonsaayman** [comment]
@wangjiancn I don't think this is an axios issue. This is normally how URI's are parsed by the browser, any time you reference `/something` the browser clears the URI back to the root and then appends the URI.

**Comment by alexanderkjeldaas** [comment]
Then both URLs whould resolve to a 404 page.  The first should be http://localhost:8080/cat/
