### ISSUE TITLE
axios Cross-domain approach

### ISSUE THREAD

**Issue by mhxy13867806343** [axios/axios#2215]
Hello
**Is your feature request related to a problem? Please describe.**
I am a front-end developer and have been plagued by the cross-domain problem, because cross-domain needs (such as background plus header information) or use node.js, nginx way (I am just a pure front-end), for not Cross-domain, I also need to ask the background colleagues or node.js nginx to solve this problem.
**Describe the solution you'd like**
For cross-domain, I came up with a way: by the background colleagues to provide an encryption protocol (you can also customize this protocol), and tell the front-end colleagues how to decrypt the protocol, and write this protocol in the headers header , plus (all: true) means cross-domain success
**Describe alternatives you've considered**

**Additional context**

**Comment by jasonsaayman** [comment]
@mhxy13867806343 I do not really understand your issue?

**Comment by mhxy13867806343** [comment]
> @mhxy13867806343 I do not really understand your issue, please could you possibly elaborate?

Means this
There is no header field in axios. The front end writes the following code in the header.
Headers:{
All: true, / / to indicate that cross-domain processing is possible
}, after the current end is written, the background provides an encrypted (contracted) data in the interface [encrypted background can be customized], the front end needs to be decrypted, and the cross-domain problem is solved.

**Comment by jasonsaayman** [comment]
@mhxy13867806343 there is a way to set headers in Axios, please see the doc's [here](https://github.com/axios/axios#request-config).

```javascript
// `headers` are custom headers to be sent
headers: {'X-Requested-With': 'XMLHttpRequest'},
```

As for the CORS issue, you are describing it seems that there is some encryption that you need, that being said the encryption would fall outside of the scope of Axios.
