### ISSUE TITLE
baseURL merge not as expected

### ISSUE THREAD

**Issue by bluelovers** [axios/axios#2217]
**Describe the bug**

baseURL merge not as expected

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```ts
// @ts-ignore
import combineURLs from 'axios/lib/helpers/combineURLs';
// @ts-ignore
import LazyURL from 'lazy-url';

let a1 = 'https://gitee.com/api/v5/';
let a2 = '/api/v5/repos/xxxx/xxxx/contents';

let u = new LazyURL(a2, a1)

console.dir(u.toRealString());

// @ts-ignore
u = new URL(a2, a1)

console.dir(u.toString());

u = combineURLs(a1, a2)

console.dir(u.toString());
```

**Expected behavior**

> 'https://gitee.com/api/v5/repos/xxxx/xxxx/contents'

**Actual behavior:**

> 'https://gitee.com/api/v5/api/v5/repos/xxxx/xxxx/contents'

**Comment by JerryYuanJ** [comment]
I don't think this is an issue, the codes shows well how the base URL and relative URL works. Just following the rules is fine. BTW, in this case, what if there's the url and value has duplicated sub-paths like 
'http://you-never-know/v5/v5/' ?

**Comment by bluelovers** [comment]
some sever is 

http://host/oauth/xxx
http://host/api/v1/xxx

and in html url with `/` at start is mean root path

**Comment by JerryYuanJ** [comment]
anyway ... still nonsense I think.

**Comment by jasonsaayman** [comment]
@bluelovers the behavior you are getting is correct and not a bug.
