### ISSUE TITLE
Is there a way to limit post/patch request size? 

### ISSUE THREAD

**Issue by ketysek** [axios/axios#2219]
Hi there, I would like to know if there exists a way to limit post/patch request size or content-length?

**Comment by Cess18** [comment]
`request({params:{limit: 10}})`

**Comment by jasonsaayman** [comment]
@ketysek I think you may be looking for this `maxContentLength` check out the docs here: [Request Config](https://github.com/axios/axios#request-config)

**Comment by ketysek** [comment]
@jasonsaayman have you tried it? it doesn't work as the request is processed normally - it seems to be ignored or sth
