### ISSUE TITLE
No MKCOL Request

### ISSUE THREAD

**Issue by PunkOnWheels** [axios/axios#2220]
Since updating to 0.19.0 I can't use MKCOL requests anymore. I see the method is hard typed now, so how can I perform older webdav requests?

**Comment by jasonsaayman** [comment]
@PunkOnWheels please can you provide some more information on this issue? Please use one of the appropriate issue templates if possible.

**Comment by PunkOnWheels** [comment]
WEBDAV method types are excluded from the index.d.ts file. Examples MKCOL, PROPFIND, MOVE, COPY, etc.
`export type Method =
  | 'get' | 'GET'
  | 'delete' | 'DELETE'
  | 'head' | 'HEAD'
  | 'options' | 'OPTIONS'
  | 'post' | 'POST'
  | 'put' | 'PUT'
  | 'patch' | 'PATCH'`

**Comment by chinesedfan** [comment]
@PunkOnWheels So your problem is the method type definitions don't allow you to use WEBDAV method types?

**Comment by NateScarlet** [comment]
Workaround for this issue:
```typescript
import axios, { Method } from 'axios';
const resp = await axios.request({
  url,
  method: 'MKCOL' as Method,
});
```

I think method should just use `string` type, because common http methods already have shortcuts.
There is no benefit in maintaining a list of all possible http methods.

**Comment by BigOsvaap** [comment]
Can I work on this? Should I add the methods for WEBDAV (COPY, LOCK, MKCOL, MOVE, PROPFIND, PROPPATCH, UNLOCK) or just use a string type?  should add aliases as well for WEBDAV?
