### ISSUE TITLE
[BREAKING on 0.19.0] Header null value becomes [Object object]

### ISSUE THREAD

**Issue by rkdmen** [axios/axios#2223]
After upgrading to 0.19.0, when header value was `null` in 0.18.1, now it becomes `[object Object]` unless it is String(null).

It breaks all behavior.

**Comment by jasonsaayman** [comment]
@rkdmen please can you provide some more information on this issue? Please use one of the appropriate issue templates if possible.

**Comment by rkdmen** [comment]
@jasonsaayman 
if request header looked like `{"some-key": null}` in previous version, it would send as `{"some-key": "null"}`.

After Upgrading to 0.19.0, it transform request header from `{"some-key": null}` to `{"some-key": [object Object]}`

Work around is, fix my code to `{"some-key": String(null)}`

**Comment by jasonsaayman** [comment]
@rkdmen cool I will attempt to replicate, this seems rather odd.

**Comment by rkdmen** [comment]
**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.14.5]
 - Browser [Chrome]
 - Browser Version [Latest]
 - Additional Library Versions [React 16.8.6]

**Comment by rkdmen** [comment]
![Screen Shot 2019-06-11 at 4 16 41 PM](https://user-images.githubusercontent.com/16869691/59303507-590aa980-8c64-11e9-9a00-17a8bc991969.png)

**Comment by woodb** [comment]
It could be from these lines in the new `mergeConfig` utility:
https://github.com/axios/axios/blob/2ee3b482456cd2a09ccbd3a4b0c20f3d0c5a5644/lib/core/mergeConfig.js#L25-L26

Since `null` is an Object

**Comment by Alanscut** [comment]
@rkdmen This is related to #2567 , PR #2568  has fixed this issue，If you have other suggestions, please feel free to update and remind me to reopen this issue.

**Comment by AlphaGeek** [comment]
I am using 0.19.2 and am still seeing this issue

**Comment by rkdmen** [comment]
@Alanscut might want to reopen this issue.

**Comment by rkdmen** [comment]
Reopened #2701
