### ISSUE TITLE
Stop when reaching 307 (maxRedirects)

### ISSUE THREAD

**Issue by PlayMa256** [axios/axios#2224]
**Describe the issue**
On docs it states that setting `maxRedirects:0` it would not follow any redirect. When i set it, sending a post request to my endpoint that returns 307, it follows the redirect, which is not supposed to happen.

**Expected behavior, if applicable**
setting `maxRedirects: 0` when receiving 307, it would not follow the redirect.

**Environment:**
 - Axios Version 0.18.1
 - OS: ubuntu 17
 - Browser chrome
 - Browser Version 74.0

**Comment by JerryYuanJ** [comment]
The `maxRedirects` seems only works in node env since it only appears in http.js(/lib/adapters/http.js), maybe try the `validateStatus` config to see if it can stop the redirect request.

**Comment by PlayMa256** [comment]
No =/
I set 
```
validateStatus: (status) => status < 307
```

But all requests still going through receiving 307

**Comment by jasonsaayman** [comment]
@PlayMa256 could you give me a runkit example for this? I can then try to replicate it an put in a pull request.

**Comment by PlayMa256** [comment]
Of course i can! I'll build one and add in here!

**Comment by chinesedfan** [comment]
Redirections are handled by browsers. I think axios can't stop that. Please correct me if I misunderstood something and remind to reopen.
