### ISSUE TITLE
BREAKING 0.19  API Errors not populating correctly

### ISSUE THREAD

**Issue by larlew** [axios/axios#2225]
API Error breaks existing code.  The error object is no longer populated. 

**To Reproduce**
catch an error from an api. 

**Expected behavior**
I didn't expect a minor version change to break existing code. 

Is there any further guidance or documentation regarding these changes?
 - Makes Axios error generic to use AxiosResponse (#1738) - Suman Lama
- Adding isAxiosError flag to errors thrown by axios (#1419) - Ayush Gupta

**Environment:**
 - Axios Version [0.19.0]
 - OS: [Windows 10 ]
 - Browser [ Chrome ]
 - Browser Version [75.0.3770.80 (Official Build) (64-bit)]
 - Additional Library Versions [React 16.8.6]

**Additional context/Screenshots**
const apirequest = (options) => {
  return authService.fetchAccessToken()
    .then((accessToken) => {
      if (!options.headers)
        options.headers = {};

      options.headers['Authorization'] = `bearer ${accessToken}`;

      return client(options)
        .then(response => {
          return response.data;
        })
        .catch(error => { console.error(error); });
    });
}

**Comment by zymawy** [comment]
Hi @larlew, Having The Same Here

**Comment by rafaelrenanpacheco** [comment]
On RunKit error is populating just fine:

![image](https://user-images.githubusercontent.com/12160864/59447541-c68c1680-8dd9-11e9-94c1-b4cacc954280.png)

**Comment by danielmcq** [comment]
Not trying to be pedantic, but you should never expect a module with a major version "0" to have a stable API. Until the author(s) put it at 1, it's not considered stable. https://semver.org/#spec-item-4

**Comment by larlew** [comment]
Fair enough.  I did not know that. Thank you.  
I do appreciate all the efforts of all the axios contributors.  I'm sorry If I came off a bit snarky.  
I don't mind adapting my code but I couldn't find any docs on the change.

**Comment by danielmcq** [comment]
@larlew No worries. Thank you for submitting detailed bug reports!

The whole major version 0 thing probably gets lots of developers. It’s something I look at closely now whenever my team wants to use a new module in any of our projects. It’s usually not worth the time and effort to use a pre-1.0.0 module in production.

0.19.0 of axios broke a plug-in we use for it. It seems that part of the changes made to errors (like what you reported) is related to the plug-in breaking with this version.

**Comment by jasonsaayman** [comment]
@larlew can you give an example of this? I use Axios in a number of projects and am yet to have this issue?

**Comment by schmod** [comment]
This appears to be a regression rather than a deliberate change, so the versioning conversation doesn't seem like applies here...

**Comment by chinesedfan** [comment]
Closed due to lack of enough information and stale. Nobody gives a reproducible code example.
