### ISSUE TITLE
axios commonjs correct way to import to gain typings? [vscode intellisense]

### ISSUE THREAD

**Issue by the-vampiire** [axios/axios#2226]
**Describe the issue**
what is the correct way to import `axios` in node using CommonJS in order to use the typings? i am not using typescript unlike [this issue](https://github.com/axios/axios/issues/1975)

**Example Code**
```js
const axios = require('axios'); // no typings but everything still works

const axios = require('axios').default; // has typings and everything works
```

**Expected behavior, if applicable**
i expected to have typings for vscode intellisense when importing `axios` using CommonJS `require()` syntax described in the documentation. 

i did not see any information about having to append `.default` to the import. maybe worth including this in the docs? for the record the import still works (`axios.get()` etc) but there is no typing intellisense. 

**Environment:**
 - Axios Version: 0.19.0
 - OS: OSX 10.14.5
 - node: 10.15.3
 - vscode: 1.34.0

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**basic import**
<img width="746" alt="Screen Shot 2019-06-13 at 12 29 23 AM" src="https://user-images.githubusercontent.com/25523682/59403834-61e9a100-8d72-11e9-9c53-0dd50a14e38e.png">

**import with `.default`**
<img width="747" alt="Screen Shot 2019-06-13 at 12 29 34 AM" src="https://user-images.githubusercontent.com/25523682/59403848-68781880-8d72-11e9-8d96-c8acabd56a2b.png">

**Comment by jasonsaayman** [comment]
@the-vampiire seems like a good idea to look into adding this into the doc's. Can you edit the docs and then put in a pull request?

**Comment by the-vampiire** [comment]
@jasonsaayman where would be a good spot for it? in the first example of the docs?

just out of curiosity why does it behave this way? i looked at the source and couldnt figure it out. hadnt seen other libs require `.default` at the end. would it be possible to fix the problem itself rather than update the docs?

**Comment by the-vampiire** [comment]
@jasonsaayman PR is up. if you want it in another location let me know.

**Comment by jasonsaayman** [comment]
@the-vampiire I actually don't know, now that you mention it that is very odd behavior. I will have a look and let you know. Thanks for the Doc's.

**Comment by the-vampiire** [comment]
@jasonsaayman cool man. if you figure out why its behaving that way id be curious to know / how it can be fixed
