### ISSUE TITLE
README.md docs error

### ISSUE THREAD

**Issue by RocMark** [axios/axios#2231]
the second then isn't that should be finally ??

Example
Performing a GET request
```
// Optionally the request above could also be done as
axios.get('/user', {
    params: {
      ID: 12345
    }
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })

  // isn't this should be .finally  ??
  .then(function () {
    // always executed
  });  
```

**Comment by jasonsaayman** [comment]
@RocMark no, finally is usually used for processing or cleanup once the promise has settled. The above section of code is just illustrating that you could perform a call, catch an error and then continue to run code afterward as with any promise.
