### ISSUE TITLE
It is not possible to use the HttpAdapter with electron, vue and webpack

### ISSUE THREAD

**Issue by GustavoEdny** [axios/axios#2232]
**Describe the issue**
First of all, sorry for bad English.

I am building a desktop application that uses electron and vuejs. I need to communicate with some third-party APIs. As I'm using webpack to compile my vue code for both production and test environment, XHRAdapter is always selected, this is the default behavior. But how can I select the HttpAdapter in this environment? Although the axios have been designed for both the browser and the node, in hybrid environments like the one I'm working on it does not seem to be flexible.

**Example Code**

```js
// Always replaced by XHRAdapter
axios.defaults.adapter = require('axios/lib/adapters/http')

// Also using the create method
const client = axios.create({
  baseURL.'https://xyz.com/some/api/',
  adapter: require('axios/lib/adapters/http')
})
```

**Expected behavior, if applicable**
I know this replacement by XHRAdapter is expected. But how can I say this using electron? I've seen other issues like this one, but none have come up with a definitive solution. I've researched a lot and tried a few different approaches but it did not work for me. I would like to continue using Axios as my standard communication tool, in previous versions I used the [Request](http://github.com/request/request) but it does not seem to be as fast as Axios.

**Environment:**
 - Axios Version [0.19.0]
 - OS: elementaryOS
 - Browser [Electron]
 - Browser Version [4.2.4]
 - Additional Library Versions [Vue 2.6.10]

**Comment by mx2323** [comment]
im having this same issue - i think this might be related - https://github.com/axios/axios/issues/456

**Comment by mx2323** [comment]
i wasn't able to get this working but the axios library relies on the 'browser' key in package.json to tell webpack to override the adapter to be XHR. 

there's a separate issue where if you specify target:'electron-renderer' in your webpack config,  it will still not include the http adapter because it uses the 'browser' alias override feature of webpack. https://github.com/webpack/webpack/issues/7953#issuecomment-467765695

**Comment by esperantic** [comment]
Please look at my comment, I believe it will help you

https://github.com/webpack/webpack/issues/7953#issuecomment-538353252

**Comment by zeevl** [comment]
I couldn't get @esperantic's solution working; webpack 4 [seems to be ignoring mainFields](https://github.com/webpack/webpack/issues/6796).

What finally seems to have worked is setting `target: node` and adding `electron` to the `externals` list.

**Comment by paul321** [comment]
I have the same issue here, we cannot use axios with Webpack because it's always replacing the httpAdapter with xhrAdapter, some of the websites that we are accessing with axios need httpAdapter in Electron render process and right now we cannot do that.

**Comment by lakxtxue** [comment]
I have the same problem, I solved it by adding this configuration to webpack.
`module: {
      rules: [
        {
          test: /node_modules\/axios/,
          resolve: { aliasFields: ["axios"] }
        }
      ]
    }`
At least everything is ok now.

**Comment by chinesedfan** [comment]
I can say the answer is yes, as long as your webpack is config correctly.

More help can be seek from webpack's community or stackoverflow. Closed due to not an issue of axios.

**Comment by ArnaudValensi** [comment]
You can see my solution here https://github.com/axios/axios/issues/552#issuecomment-604468438
