### ISSUE TITLE
Post request ended with 401 unauthorized after update to 0.19.0

### ISSUE THREAD

**Issue by roigreenberg** [axios/axios#2236]
**Describe the bug**
We are using axios in a docker that running node in VM and make post request to proccess that run in the VM.
After update axios to 0.19.0, the post request start to recieve 401 unauthorized.

Downgrade back to 0.18.0 solve the issue.

**To Reproduce**
I can't reproduce it outside the work VM..

Since it's work code I prefer not upload anything, but I will write specific code if neccesarry 

**Expected behavior**
Post request to work of course :) 

**Environment:**
 - Axios Version 0.19.0
 - OS: alpine docker

**Comment by waiaan** [comment]
```js
var instance = axios.create({
  //you should not add 'method' option here
});
```

**Comment by roigreenberg** [comment]
We have no such function.

We are using "app = express()"
