### ISSUE TITLE
Cancellation of All as well as  Particular API

### ISSUE THREAD

**Issue by sumitkale-zymr** [axios/axios#2237]
1) In my react native app I have one home screen in which  I have 3 to 4  API getting called now when I move to next screen I want to cancel all pending request as well as requests which will execute after pending request in axios. I have tried using executer of axios which cancels only one request and after that remaining two requests get called. I have also tried cancel token it cancels all requests and after that any other API call of next screen not getting called.

2) I Want to cancel particular 3 API call from 5 API call.

**Environment:**
 - Axios Version [0.18.0]
 - Additional Library Versions [ React Native 0.59.8]

**Comment by rafaelrenanpacheco** [comment]
Take a look at:
- https://www.npmjs.com/package/axios-cancel
- https://www.npmjs.com/package/axios-cancelable

**Comment by chinesedfan** [comment]
It depends on users to maintain different cancel tokens for different requests. Or try other 3rd libraries wrapped on axios.
