### ISSUE TITLE
unexpected end of stream when fetching large amount of data (JSON)

### ISSUE THREAD

**Issue by AustinZuniga** [axios/axios#2238]
I received the following error in fetching large amount of data(JSON) using axios in react native.

Error: unexpected end of stream

Here is my code:

`
axios.post('http://192.168.0.1:5000/download', {
      access: data.tokens
    })
    .then(function (response) {
       alert(response.data);
    })
    .catch(function (error) {
      alert("There was an error in communicating to server");
});
`

I tried to limit the result returned by the REST API (100 rows) and it returned some data.

How can I fetch large amount of data in Axios?

**Comment by Alanscut** [comment]
I tested a post request and it returns a 2M json data successfully. version v0.18.0 & v0.19.0.
your issue seems to have been solved by https://stackoverflow.com/questions/56659365/axios-unexpected-end-of-stream
