### ISSUE TITLE
Breaking change in validateStatus parameter

### ISSUE THREAD

**Issue by sergioregueira** [axios/axios#2239]
**Problem:**

This is what [README.md](https://github.com/axios/axios/blob/master/README.md) says about `validateStatus` parameter:

> `validateStatus` defines whether to resolve or reject the promise for a given HTTP response status code. If `validateStatus` returns `true` (or is set to `null` or `undefined`), the promise will be resolved; otherwise, the promise will be rejected.

This parameter supports (as specified) `undefined` in 0.18.x but it does not work properly in 0.19.0 despite the documentation does not warn about this change.

**Affects version:**
0.19.0 (latest)

**Steps to reproduce it:**
Set `validateStatus` property to `undefined` value and request anything that returns `404 Not Found`.

**Current behavior:**
It uses the standard validation function (that only accepts 2XX status codes); rejecting any non successful response.

**Expected behavior:**
It should accept any status code received from server as `null` value does.

**Reproducible scenario:**

```javascript
const axios = require('axios'); // v0.19.0

axios
  .get('https://example.com/404', { validateStatus: undefined })
  .catch(console.error);

// output: axios error due to 404 not found
```

**Solution:**

Analyze where the bug has been added and fix it.

**Comment by sergioregueira** [comment]
As clarification, axios works properly with `null` value:

```javascript
const axios = require('axios');

axios
  .get('https://example.com/404', { validateStatus: null })
  .then(console.log);

// output: axios response containing a 404 not found
```

**Comment by jphilipstevens** [comment]
Judging by this line: https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js#L40

undefined is resulting in the default being used: https://github.com/axios/axios/blob/master/lib/defaults.js#L79

Likley the result of the addition of mergeConfig. 0.18 appears to not have this

**Comment by Alanscut** [comment]
fixed by #2545

**Comment by sergioregueira** [comment]
I do not agree #2545 fixes this problem. The behavior for `validateStatus` was modified from `0.18.x` to `0.19.x` without any warning ([release notes](https://github.com/axios/axios/releases/tag/v0.19.0)), so  this should be the procedure:
1. Restore the previous behavior releasing a patch version (`0.19.x`) to maintain backward compatibility.
1. Change the behavior to the new one in next minor version (`0.20.x`) informing the user about this breaking change.

**Comment by sergioregueira** [comment]
Indeed, the `README.md` still says `undefined` is a valid value for that parameter.
