### ISSUE TITLE
error.response undefined (Catch) 422 Error

### ISSUE THREAD

**Issue by ruhulwebdev** [axios/axios#2241]
## On 422 error, error.response is undefined even though I can see the error object in the network tab

**Here's codesandbox working example**
[https://codesandbox.io/s/blue-dream-umibe](https://codesandbox.io/s/blue-dream-umibe)

I have this code

```js
login(user) {
    return axios({
      method: "post",
      responseType: "json",
      url: `${root}/users/login`,
      data: {
        user: {
          email: "jakelasjfflsf@jake.jake",
          password: "jake"
        }
      }
    }).catch(err=> {
        // err.response is undefined
    });
  }
```

**Expected behavior, if applicable**
It should return an error object containing server errors

**Comment by ruhulwebdev** [comment]
sorry I had this code at the top that was causing the issue.

`axios.interceptors.response.use(null, function(error) {
  if (error.response.status === 404) {
    return window.location.replace("#/")
  } else if (error.response.status === 401) {
    return window.location.replace("#/login")
  }
})
`

**Comment by seaskyways** [comment]
I had the same issue !! Was beating my head to the table for the last hour.
