### ISSUE TITLE
Axios seems to be breaking koa

### ISSUE THREAD

**Issue by jrgleason** [axios/axios#2242]
**Describe the issue**
I am trying to use axios to send oauth requests. In a koa-route I do the following...

     // 404
     router.get("/callback",(ctx)=>{
         ...
         return axios(options).then((response)=>{
             console.log("Made it here " + JSON.stringify(jwtDecode(response.data.id_token)));
             ctx.cookies.set("foo", "bar", {httpOnly: false});
             ctx.body = "Test"
        })
    })

Even though the console log seems to be correct the route returns a 404. When I remove Axios and just use a generic Promise to simulate everything seems to work...

    // No 404
     router.get("/callback",(ctx)=>{
         ...
         return Promise.resolve("").then((response)=>{
             ctx.cookies.set("foo", "bar", {httpOnly: false});
             ctx.body = "Test"
        })
    })

**Expected behavior, if applicable**
I would like to be able to use Koa with Axios

**Environment:**
 - Axios Version ^0.19.0
 - OS: OSX
 - Browser Chrome
 - Additional Library Versions Node v12, koa latest

https://github.com/koajs/koa/issues/1344

**Comment by jrgleason** [comment]
Looks like I need to use finally to get it to work, which still feels like something is broke....

            return axios(options).then((response)=>{
                console.log("Made it here " + JSON.stringify(jwtDecode(response.data.id_token)));
                ctx.cookies.set("Authorization", JSON.stringify(response.data), {httpOnly: false})
            }).finally(()=>{
                ctx.redirect("/");
                return next();
            })

**Comment by jphilipstevens** [comment]
I am not too sure this would be an Axios issue. 

I've been getting into the axios code and it uses native promises. finally is not part of that so i can only assume that somewhere in your server is was added?

I think a sample project would be needed for more info

**Comment by yyfearth** [comment]
Because you did not use `.catch()` for the axios call?
Seems you only have `axios().then` for the success case, and it will cause rejection if it failed. And you directly returned the rejection to the koa, is that expected?

I think you just need to replace the `.finally` to `.catch` should work.

**Comment by chinesedfan** [comment]
> Because you did not use .catch() for the axios call?

Yes, please make sure the axios call will not throw an error.
