### ISSUE TITLE
onDownloadProgress gets specific data, because I don’t just want to know the length, I also want to know the specific content.

### ISSUE THREAD

**Issue by joeyer** [axios/axios#2244]
onDownloadProgress gets specific data, because I don’t just want to know the length, I also want to know the specific content.

**Comment by jasonsaayman** [comment]
@joeyer please can you give a better explanation of what your issue is? Could you possibly include a code example so that we can test and try to reproduce the error you are experiencing?

**Comment by jasonsaayman** [comment]
Since there has been no response here for a long time I am going to close this issue.
