### ISSUE TITLE
v0.18.1 remove xDomainRequest is a disruptive update

### ISSUE THREAD

**Issue by gyh9457** [axios/axios#2248]
**Describe the bug**
The version 0.18.1 remove xDmainRequest support by this commit

https://github.com/axios/axios/commit/5c754e6e07b536826d0a3b4e010d839482f3dd2c

I need to support it. And i want to know why remove it ? 

Do I have another way to fix it or I have to lock the 0.18.0 version?

@RikkiGibson @Khaledgarbaya 

**To Reproduce**
send a Cross-domain requests with axios in IE9

**Expected behavior**
A way to support xDomainRequest. or must lock the version ?

**Environment:**
 - Browser Version IE9

**Comment by RikkiGibson** [comment]
This breaking change was meant to go into version 0.19. I’m guessing that 0.18.1 was based off of the wrong commit and that’s how this snuck in.

For now I think you’ll need to lock the version.

**Comment by RikkiGibson** [comment]
Please consider reopening the issue as there is action needed by the maintainers to ship a new patch release of 0.18 which doesn’t include the breaking changes.

**Comment by chinesedfan** [comment]
@Alanscut Do we only support IE 11 now? Can you find some document link?
