### ISSUE TITLE
jsdoc is missing in bind.js

### ISSUE THREAD

**Issue by satheler** [axios/axios#2249]
**Section/Content To Improve**
Don't have anything description that to do the bind method

**Suggested Improvement**
Is an obscure method? What does it do?

**Relevant File(s)**: [e.g. README.md]
[./lib/helpers/bind.js](https://github.com/axios/axios/blob/master/lib/helpers/bind.js)

**Comment by Alanscut** [comment]
> **Section/Content To Improve**
> Don't have anything description that to do the bind method
> 
> **Suggested Improvement**
> Is an obscure method? What does it do?

@satheler   See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
