### ISSUE TITLE
Unable to get set-cookie value from header with axios reactjs

### ISSUE THREAD

**Issue by asmakhalfallah2018** [axios/axios#2253]
I am using react js and i have an axios.get function which is supposed to return me a value of set-cookie . Before axios i tried fetch but when running response.headers.get("set-cookie") it gives null . For axios , response.headers["set-cookie"] gives undefined  . Why headers don't contain set-cookie ? 

```

 axios.get(server + '/QryIsapi.dll?Login&login=' + username + '&password=' + password + '&action=login' + '&Expire=' + !stay_connected, {
      headers: new Headers({
        "Content-Type": 'text/plain',
        "Accept": "text/plain",
        "Accept-Language": accept_language
      }),
      withCredentials: true
    }).then(response => {
      
      
      console.log(response.headers["set-cookies"])  //gives undefined
    
    
    }).catch(function (data) {

      console.log("Login : ", data)

    })

```

**Comment by jaredramirez** [comment]
Not sure if this will solve it, but you're trying to get `set-cookies` instead of `set-cookie`. The first is plural and the second is singular.

**Comment by DonaldN92** [comment]
try with **response.headers.map["set-cookie"]**

**Comment by chinesedfan** [comment]
Closed due to no feedback. Looks like a typo problem.

**Comment by stevehind** [comment]
I don't think this is a typo problem.

I'm also using axios.post, and have confirmed (chrome dev tools, insominia) that the server is sending a cookie. However printing response.header shows no set-cookies header, and printing document.cookie shows "".

**Comment by rohanshar** [comment]
I have the same issue

**Comment by linnnruoo** [comment]
I'm having the same issue too. Not sure if it is an issue with axios.
