### ISSUE TITLE
getUri doesn't work before request is sent

### ISSUE THREAD

**Issue by adam-mccormick** [axios/axios#2254]
**Describe the bug**
The `getUri` method only returns the supplied `url` parameter and not the full request URL. However, using this method in a response interceptor seems to work correctly

This might be a duplicate or related to #2190 but I'm not sure so just throwing this out there anyway.

**To Reproduce**
Runkit [example](https://runkit.com/adam-mccormick/5d1660c39720a3001aeace48)

The example shows that the `getUri` method only returns the `url` parameter in the request interceptor but in the response interceptor the full URL is returned.

**Expected behavior**
The `getUri` method always returns the full URL of the request config

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.13.4]
- Environment [node >= 10]

**Comment by JiaboHou** [comment]
Looks like there's a PR for it: #2128

**Comment by Alanscut** [comment]
hi @adam-mccormick , the `url` before sent to request doesn't include the `baseURL` is a [**breaking change**](https://github.com/axios/axios/blob/master/CHANGELOG.md#0170-oct-21-2017) since v0.17.0. This change introduced by PR #950 which makes the baseURL work in the `interceptor`.
