### ISSUE TITLE
Axios 0.19.0 not Connecting to localhost:8080 without internet

### ISSUE THREAD

**Issue by anoopmb** [axios/axios#2257]
I am developing API based Vue JS application. Server serves its endpoints on http://localhost:8080/api

my configuration of axios is
``` 
const service = axios.create({
  baseURL: 'http://localhost:8080/api', 
  timeout: 10000
})
service.interceptors.request.use(
  config => {
    config.headers['Accept'] = 'application/json'
    config.headers['Content-Type'] = 'application/json'
     if (store.getters.token) {
       config.headers['x-api-cftoken'] = getToken() 
     }
    return config
  },
  error => {
    console.log(error)
    Promise.reject(error)
  }
)
service.interceptors.response.use(response => {
  console.log('Response:', response)
  return response
}) 
export default service

```
But in offline (without internet) endpoints not working and throwing error as
>  errError: getaddrinfo ENOENT localhost:8080

on postman its working in offline mode
and finally its worked when I downgraded my axios to 0.18.1
Please help me how to configure  axios 0.19.0

**Comment by krishnaclouds** [comment]
Couldn't replicate the issue. It is working fine with 0.19.0 

Env
Machine : Linux
Axios Version: 0.19.0
Backend Server on Node and Front End on React. 

Can you please provide the details of your response headers, so as to do possible debugging. Thanks

**Comment by anoopmb** [comment]
i tried by removing node modules and package-lock.json
its not working

and i am not getting response its instantly throwing this error on request

and  its a electron vue application

**Comment by chinesedfan** [comment]
> Can you please provide the details of your response headers, so as to do possible debugging.

In Electron, make sure you are using the right adapter: xhr or http. Closed first due to lack of enough information.
