### ISSUE TITLE
Consuming eBay API with NodeJS and Axios don't work - what I make false

### ISSUE THREAD

**Issue by sm-a** [axios/axios#2258]
**Describe the issue**
When I consuming the eBay API to get a token then I get followed error:
"grant type in request is not supported by the authorization server"

**Example Code**

`
axios.request({
  url: '/identity/v1/oauth2/token',
  method: "post",
  baseURL: "https://api.sandbox.ebay.com/",
  auth: {
    username: "", // eBay client id
    password: "" // eBay client secret
  },
  data: {
    grant_type: 'client_credentials',
    //you may need to define the oauth scope
    scope: 'https://api.ebay.com/oauth/api_scope' 
  }
}).then(res => {
  console.log(res);  
}).catch(error => {
    console.log(error)
 })

`

**Environment:**
 - Axios Version 0.19
 - NodeJS 10.16.0

**Comment by krishnaclouds** [comment]
It feels the issue is not related to Axios. Please note that you have to specify the string value in scope as `https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope` as indicated in the [documentation](https://developer.ebay.com/api-docs/static/oauth-scopes.html) -

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com). Thanks.
