### ISSUE TITLE
Remove `axios.all` and `axios.spread` from documentation

### ISSUE THREAD

**Issue by crhistianramirez** [axios/axios#2260]
**Section/Content To Improve**
Section in main readme around performing multiple concurrent requests

**Suggested Improvement**
There is a request to remove `axios.all` and `axios.spread` (https://github.com/axios/axios/issues/1042)

Although the functionality has not yet been removed, we can at least stop advertising it if there is intent (with good reason) to remove it.  We can still keep the section on concurrent requests and talk about how to do it with the native features.

I would be happy to update the documentation if approved.

**Relevant File(s)**: [e.g. README.md]
[Main Readme](https://github.com/axios/axios/blob/master/README.md)

**Comment by ohtaeg** [comment]
If there is not working person, I would like to solve this.

**Comment by DConstantine9** [comment]
Hello! If you still need a help I can help you.

**Comment by ohtaeg** [comment]
I was too busy to continue.
Thanks for asking, but would you mind if I try it on my own for the experience? 
Thank you for your kindness, Please don't be offended :)

**Comment by DConstantine9** [comment]
Yes, everything's ok. Good luck

**Comment by jasonsaayman** [comment]
Resolved by #2727
