### ISSUE TITLE
firefox XML 解析错误:格式不佳

### ISSUE THREAD

**Issue by zb-0819** [axios/axios#2262]
**Describe the issue**
A clear and concise description of what the issue is.

**Example Code**
Code snippet to illustrate your question

```js
// Example code here
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Hi, please can you explain this issue by logging the issue correctly? For now, I am going to close this issue.
