### ISSUE TITLE
Want to hit api in new window something like window.open(URL)

### ISSUE THREAD

**Issue by karanshah10** [axios/axios#2266]
Hello..
I just want to open api in new window on button click.

**Comment by yasuf** [comment]
are you hosting the new window? If so you'll need to run that on a script as soon as the page loads, depending on the library you're using this will vary, you can start by taking a look at react and react router:
https://reactjs.org
https://reacttraining.com/react-router/

**Comment by yasuf** [comment]
the most simple way is to just have a server running on localhost and have a `script` tag that loads axios and your own script that makes the request, this could be via node https://nodejs.org/en/

**Comment by yasuf** [comment]
closing, issue unrelated to axios
