### ISSUE TITLE
Request happen unexpected end of file

### ISSUE THREAD

**Issue by AaronChengHao** [axios/axios#2267]
**Describe the bug**
Requests for certain addresses occur `unexpected end of file`

**I found that would solve my problem**
![image](https://user-images.githubusercontent.com/20119217/60599069-61c44a80-9de0-11e9-8700-5ffab2a28e5a.png)

**Environment:**
 - Axios Version [e.g. 0.19.0]
 - OS: [win10]
 - node: [8.9.3]

**Comment by chinesedfan** [comment]
#2153 will add an option to disable the default decompress. Then users can decompress with options by themselves.
