### ISSUE TITLE
Google Api My Business | CORS policy - Network Error

### ISSUE THREAD

**Issue by MwSpaceLLC** [axios/axios#2269]
**Describe the issue**
Request with api in google my business return error only when used with axios. if i use XMLHttpRequest Class i do not have any errors.

**Example Code XMLHttpRequest** ✔
```js
	let xhr = new XMLHttpRequest();
	xhr.responseType = 'json';

	xhr.open('GET', 'https://mybusiness.googleapis.com/v4/accounts');
	xhr.setRequestHeader('Authorization', 'Bearer ' + token);

	xhr.onload = function () {
		if (xhr.status !== 200) {
			return false;
		}
        console.log(xhr.response)
         }

	xhr.send();
```
**Example Code Axios** 💥
```js
    import axios from "axios";

        const GoogleInstance = axios.create({
            baseURL: 'https://mybusiness.googleapis.com/v4/',
            headers: {'Authorization': `Bearer ${token}`},
            responseType: 'json',
            timeout: 1000,
        });
    
        GoogleInstance.get('/accounts')
            .then((response) => {
    
                console.log(response);
            });
```
**Expected behavior, if applicable**
return list of accounts in google my business

**Errors Returned With Axios/Screenshots**
![image](https://user-images.githubusercontent.com/29952045/60729299-a7008d80-9f42-11e9-8fd8-b0d5aa0b8b6b.png)

**Environment:**
 - Axios Version [axios@0.18.1]
 - OS: [Windows Wamp]
 - Browser [Chrome]
 - Additional Library Versions [VUEJS/LARAVEL]

**Additional context**
I use vue-axios for laravel native authentication for users and Jason web token. Maybe the classes are overwritten and there is some default headers problem

**Comment by starkovsky** [comment]
Hi, you can find all request headers on Network tab in Browser Dev Tools

**Comment by chinesedfan** [comment]
> Maybe the classes are overwritten and there is some default headers problem

@MwSpaceLLC Yeah, please check that. It is a CORS problem instead of an issue. If you confirm that axios sends wrong headers, feel free to remind me to reopen.
