### ISSUE TITLE
nested call and last id insert

### ISSUE THREAD

**Issue by spham** [axios/axios#2272]
I try insert into database, and retrieve last id for next call.
I dont find a best way to make it work. and best practice.

1. there have a smart ways to make nested call in axios for this, by pass data directly ?

      var histo = new FormData();
      histo.append('id_booking', this.last_id);
      histo.append('name', this.name);
      histo.append('email', this.email);

      axios.all([
          axios.post("domain.com/api/v1/booking").then(response => (this.last_id = response.data['last_id'])),
          axios.post("domain.com/api/v1/savefiles", histo), // 
        ])

when insert, i have a shift in last_id (because it not use new last_id fetch from first call)

**Comment by Alanscut** [comment]
You can call it with `async` and `await` or ` promise` chain
```
async function executor (fn) {
  try {
    let res = await fn();
    return [null, res];
  } catch (e) {
    return [e, null];
  }
}

let [err, res] = await executor(axios.post("domain.com/api/v1/booking"));
if (!err) {
  this.last_id = res.data['last_id']
}
var histo = new FormData();
histo.append('id_booking', this.last_id);
histo.append('name', this.name);
histo.append('email', this.email);
let [err2, res2] = await executor(axios.post("domain.com/api/v1/savefiles", histo));
```
