### ISSUE TITLE
Form data unexpected structure

### ISSUE THREAD

**Issue by rusinowiczjakub** [axios/axios#2273]
While doing post request with set Header Content-type as `application/x-www-form-urlencoded'`
I'm getting unexpected structure of Form Data which is being sent to api

I'm doing request like:
```js
    const formData = new FormData();

    formData.append('username', 'xxxxxxx');
    formData.append('password', 'xxxxxxxx');

    await axios.post(ConfigApi.loginUrl,
      formData,
      {headers: this.headers}
    ).then((resp) => {
      loginResponse = resp;
    }).catch((e) => {
      console.log(e);
    });
```
and what i receive in my API looks like:

```

----------------------------424403790562698502779428  Content-Disposition:_form-data;_name | "username"    XXXXXXXX  ----------------------------424403790562698502779428  Content-Disposition: form-data; name="password"    XXXXXXXXX  ----------------------------424403790562698502779428--
-- | --

```

I have tried also adding raw json except FormData Object like: 
```json
{username: "xxxxx", password: "xxxxx"}
```
and request looked like:

```
key | value
{"username":"xxxxxxx","password":"xxxxxx"} | (empty)
-- | --
```

Same request with identical headers looks good with other http clients.

**Comment by lxfire** [comment]
hi ~! @rusinowiczjakub  do you resolve this issue?  I have it too, any way can solve it.  thx~

**Comment by rusinowiczjakub** [comment]
@lxfire nope I switched to another http client (https://github.com/request/request).

**Comment by chinesedfan** [comment]
Can someone paste the expected format?

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
