### ISSUE TITLE
Can't set Content-Type when data is FormData

### ISSUE THREAD

**Issue by hiyangguo** [axios/axios#2276]
**Describe the bug**

I can't set `Content-Type` to headers when data is `FormData`.

**To Reproduce**
```js
const formData = new FormData();
const blob = new Blob(['test'],{type:'text/plain'});
formData.append('file',blob,'test.txt');
axios.request('/api/test',{
    headers:{
       'Test-Header':'test',
       'Content-Type':'text/plain'
    },
	data:formData
});
```

**Expected behavior**
`Test-Header` is useful , but `Content-Type` is ignored.

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.14.5]
 - Browser [Chrome]
 - Browser Version [74]
 - UA [`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36`]

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/15609339/60861883-707e8780-a24e-11e9-88f4-ae99d883a65b.png)

**Comment by logicool** [comment]
I am just facing the same issue.
And I think this is probably the cause.
https://github.com/axios/axios/blob/2ee3b482456cd2a09ccbd3a4b0c20f3d0c5a5644/lib/adapters/xhr.js#L16
Try to perform request with aliases, like this:
```js
const config = {
  headers:{
       'Test-Header':'test',
       'Content-Type':'text/plain'
    }
}
axios.post('/api/test', formdata, config)
```

**Comment by hiyangguo** [comment]
@logicool So why will delete the `requestHeaders['Content-Type']` ? And if I want to use `axios.request()`, what should I do?

**Comment by younes0** [comment]
So library isn't usable with formData

**Comment by hiyangguo** [comment]
Hello, anyone there?

**Comment by Disorrder** [comment]
See #2190 and downgrade to 0.18

**Comment by chinesedfan** [comment]
@hiyangguo `axios.request` means `GET` method by default, please send FormData by `POST`.
