### ISSUE TITLE
Handling onUploadProgress on network failure

### ISSUE THREAD

**Issue by sirajulm** [axios/axios#2277]
**Describe the issue**
When using `onUploadProgress` to get the progress of the file uploads, it looks fine as long as the network is working. But in case the network goes down while uploading, the property `loaded` still keeps ticking forward.
Please suggest, if there is a way to stop the progress when network is down?

**Example Code**
Code snippet to illustrate your question

```js
axios({
  method: 'post',
  url: 'sample/url',
  data: payload,
  onUploadProgress: ({loaded, total}) => console.log(Math.floor((loaded * 100) / total))
})
```
**Steps to reproduce**
1. Upload a large file 
2. Turn off the network
OR
set `Throttle ` to offline, in Chrome Network panel
OR
if server running in `localhost`, exit the server

**Expected behavior, if applicable**
When the network is down the `loaded` property should not change ideally.

**Environment:**
 - Axios Version [0.18.0]
 - OS: [OSX 10.14.5]
 - Browser [Chrome]
 - Browser Version [75]
 - Additional Library Versions [React 16.8.6]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by otomeskhy** [comment]
I am expecting same issue.

As of expected behaviour, since after network reconnect it starts from 0 again, I guess loaded should get reset to 0.

**Comment by HaiYoungs** [comment]
It is recommended to check whether the agent is enabled. If the network is disconnected, local services can also be accessed. I have encountered this problem when I started the agent @otomeskhy 
建议检查一下有没有开启代理，如果断网，本地的服务也是能访问的，我开启代理的时候也遇到过这种问题https://www.jianshu.com/p/7e8ccc0d682d

**Comment by otomeskhy** [comment]
Thanks @HaiYoungs , but it's been more than 2 years, we ditched axios in favor of native requests.
