### ISSUE TITLE
Does axios support subset imports?

### ISSUE THREAD

**Issue by bluetidepro** [axios/axios#2278]
**Describe the issue**

I've been using `webpack-bundle-analyzer` to try to reduce the size of our js bundles, and was wondering if axios supported subset imports, and if you can shake off some of the import for things you don't need? This is a nice way to make the bundle sizes smaller, if possible. It seems like a common feature for bigger util libraries like this. Wasn't sure if axios support it or not.

**Example Code**
Currently you have to do:

```js
import axios from 'axios'; // full lib
...
axios.get();
...
```

Is it possible to do:

```js
import get from 'axios/get'; // subset with only stuff for a "get"
...
get();
...
```

**Expected behavior, if applicable**

Thus, getting a smaller import/bundle size once compiled?

**Environment:**
 - Axios Version: `^0.19.0`

**Additional context/Screenshots**

- http://bluetide.pro/eFpziI

**Comment by yasuf** [comment]
not as of right now, as there's just one Axios object that we export, we can consider adding this later on but there seems to be other high priority items (http/2 support)
