### ISSUE TITLE
Axios.post.then causes url to come back 404

### ISSUE THREAD

**Issue by developdeez** [axios/axios#2280]
I've tried to use Axios to allert my user if they need to fill out a captcha. It works fine until I tried to add a condition. Suddenly it responded with "404" thoguh nothing changed then my then(window.reload()) changing to then(()=>window.reload())

I've been able to work around it by putting my condition in another function and setting it as I did in the beginning but this seems like something I shouldn't have to do

Code snippet:
````
function onChange(value) {
  axios
    .post(
     "http://localhost:4444/allowIp",
      { capToken: value }
    )
    .then(go());
}

const go = () => {
  if (window.location.pathname === "/captcha") {
    window.location.replace("/");
  } else {
    window.location.reload();
  }
};
````

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. What you need is some practices about promises. Good luck!
