### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by mikelibg** [axios/axios#2281]
General:

Although the error popped up in a different library, I think there might be a problem with axios giving a proper information regarding the error. After reviewing the code of the error I did not see a reason why createError should fail at that line.

Environment details:

OS: AWS hosted Linux version 4.15.0-1032-aws (buildd@lcy01-amd64-025) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019
Node.js version: v10.16.0
npm version: 6.9.0
googleapis version: "^32.0.0" using axios 

Steps to reproduce

Started getting this error at 2019-07-10T19:01:06.497Z and then after about two hours the error stopped and everything got back to normal again, receiving proper response with subscription data.

During a call:

```
var { google } = require('googleapis');
var pub = google.androidpublisher('v3')

authClient.authorize()
        .then(function (tokens) {
            return pub.purchases.subscriptions.get({
                auth: authClient,
                packageName: "my.app.package",
                subscriptionId: subscription_id,
                token: purchase_token
            })
        })
        .then(function (resp) {
            return Promise.resolve(resp)
        })

```
Getting error:

> Error: null\n at createError (/app_dir/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/app_dir/node_modules/axios/lib/core/settle.js:18:12)\n at Unzip.handleStreamEnd (/app_dir/node_modules/axios/lib/adapters/http.js:202:11)\n at Unzip.emit (events.js:203:15)\n at Unzip.EventEmitter.emit (domain.js:448:20)\n at endReadableNT (_stream_readable.js:1129:12)\n at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios.

If you confirm that axios sends wrong headers, feel free to remind me to reopen.
