### ISSUE TITLE
Concurrent requests made by axios is mixing up the responses

### ISSUE THREAD

**Issue by KevinMarioGerard** [axios/axios#2282]
I make multiple concurrent requests using axios. The responses for the requests is getting mixed up or it is not the response for that specific request.

version: 0.18.0
Description:
A shared instance of axios object is used to make multiple requests. The responses are getting mixed up.

**Comment by dguzman-ort** [comment]
Hello! I ran into this exactly situation... Do you guys know how to prevent this issue? 

@KevinMarioGerard

**Comment by dguzman1012** [comment]
Hello! I ran into this exact situation... Do you guys know how to prevent this issue?

@KevinMarioGerard
