### ISSUE TITLE
Version 0.19 does not transform a JSON response anymore

### ISSUE THREAD

**Issue by technicallyfeasible** [axios/axios#2283]
**Describe the bug**
The bug appeared when I upgraded from version 0.18 to 0.19. Response data now comes back as a string even though responseType: 'json' and content-type: 'application/json'

I believe the problem is this changed line in core/Axios.js:

0.18:
 config = utils.merge(defaults, {method: 'get'}, this.defaults, config);

0.19:
 config = mergeConfig(this.defaults, config);

I could not find any reference to the "defaults" import in the new merged config and the transformResponse function is part of the default config.

As a result a JSON payload is not transformed anymore.

**To Reproduce**
Any request that returns a response with content-type: 'application/json'.

typeof response.data === 'string'

**Expected behavior**
The json response should be parsed and returned as typeof response.data === 'object' (or whatever the response was)

**Environment:**
 - Axios Version 0.19.0
 - OS: Windows 10
 - NodeJS 8.15.1

**Comment by tjk** [comment]
Bump! Was just affected by this -- not sure if it's a problem with how we are using axios but either way, quite a breaking change in 0.19 (from 0.18).

**Comment by chinesedfan** [comment]
Can you show the reproducible codes?

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
