### ISSUE TITLE
Axios auto cancelled request

### ISSUE THREAD

**Issue by ghoroubi** [axios/axios#2286]
**Describe the issue**
I'm using Axios in ReactJS. I'm having the following problem:

When I call an HTTP Request I get the result is cancelled. Although I did not cancel this request.

![93eb5be3-5cfb-455c-9fb7-130cddf234a3](https://user-images.githubusercontent.com/12492150/61222165-687f8580-a72f-11e9-8ce7-7cf979411933.jpeg)
![fc4bd664-fe5d-41cb-acfa-4bbb9e646fb2](https://user-images.githubusercontent.com/12492150/61222174-6b7a7600-a72f-11e9-884c-4a14bb076bb3.jpeg)

as you see in images, I expect to sign in but cancel request occurs at first try, but in other tries, it works fine.

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [ OSX 10.14.5]
 - Browser [Chrome]

**Comment by chinesedfan** [comment]
Sorry, codes in your images are not very clear. Can you paste again, with the detailed request/response headers and related codes?

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
