### ISSUE TITLE
axios retry on error code response with delay

### ISSUE THREAD

**Issue by DMamak** [axios/axios#2287]
I'm receiving data from api using axios, and i want to add error handling to it, i have different messages on different error codes received(401,400,503 etc), but i also want to set timeout of 1 min on 401 errors 2min on error code 500 etc.is that possible using axios without importing axios retry ? I tried coming up with a solution by using interceptors but then spread.js which is imported with axios spams the error in console log and causes browser freeze.I used the following code for timeout in interceptors

 axios.interceptors.response.use(function (response) {
                    // Do something with response data
                    console.log(response);
                    return response;
                }, function (error) {
                    // Do something with response error
                    if(error.response.status===401){
                        setTimeout(function (){
                            console.log(error.response.status===401);
                            return Promise.reject(error);
                        },10000);
                    }
                    if(error.response.status===503){
                        setTimeout(function (){
                            console.log(error.response.status===503);
                            return Promise.reject(error);
                        },30000);
                    }
                    if(error.response.status===500){
                        setTimeout(function (){
                            console.log(error.response.status===401);
                            return Promise.reject(error);
                        },50000);
                    }
                });

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. What you need is some practices about promises. Good luck!
