### ISSUE TITLE
 TypeError: Cannot assign to read only property 'toJSON' of object Error..

### ISSUE THREAD

**Issue by VladimirShestakov** [axios/axios#2288]
Simple GET request with server status code 4xx, 5xxx throw error

```
Uncaught TypeError: Cannot assign to read only property 'toJSON' of object 'Error: Request failed with status code 403'
    at enhanceError (enhanceError.js:23)
    at createError (createError.js:17)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:59)
```
axios v19.0, 18.0
last Chrome, Firefox. On Windows, Mac
with react 16.8.6, babel 7.5

![image](https://user-images.githubusercontent.com/614740/61298649-46493e80-a7e7-11e9-942f-c70953d68fda.png)

![image](https://user-images.githubusercontent.com/614740/61298958-df785500-a7e7-11e9-973c-c522851b7e10.png)

**Comment by VladimirShestakov** [comment]
External lib defineProperty Error.prototype.toJSON

**Comment by polyglotm** [comment]
@VladimirShestakov hey I'm just curious. what was the issue?

**Comment by chriseyre2000** [comment]
Please can we have more details on how to fix this.

**Comment by polyglotm** [comment]
@chriseyre2000 in our case the problem was some 3rd party library was override `toJSON`.
we eliminate that library
