### ISSUE TITLE
how to do when I use typescript to defined type the return value

### ISSUE THREAD

**Issue by Cuixote** [axios/axios#2291]
**Describe the issue**
when I use typescript to define the type of the returns, it throws error.
**Example Code**

```js
import { AxiosPromise } from 'axios'
import { SwaggerData } from 'types/swagger'

export function getApiDocsApi (): AxiosPromise<SwaggerData> {
    return Request.get('v2/api-docs')
}
...
async foo () {
    const data = await getApiDocsApi()
   // I expect the return value `data` to be of type `SwaggerData`, but `AxiosResponse<SwaggerData>`
    const { mainData, menuData } = formatSwaggerData(data)
}

```

**Expected behavior, if applicable**

I expect the return value `data` to be of type `SwaggerData`, but `AxiosResponse<SwaggerData>`. What should I do?

**Environment:**
 - Axios Version [ 0.19.0]
 - OS: [OSX 10.14.5]
 - Browser [Chrome]
 - Browser Version [75.0.3770.100]

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/10526614/61435424-fc896100-a96a-11e9-8ffd-2e9bcde99ba0.png)

**Comment by vladimirjegorov** [comment]
try
`const { data }= await getApiDocsApi()`
