### ISSUE TITLE
Method specific defaults are not set for patch and post.

### ISSUE THREAD

**Issue by Dark-Passenger** [axios/axios#2292]
**Describe the bug**
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

when setting header `Content-Type` to custom type 'application/json+patch-json'
for method patch via.

instance.defaults.headers.patch['Content-Type'] = 'application/json+patch-json';

the instance.patch method does not set the content type as 'application/json+patch-json'

instead having header 'Content-Type': 'application/json;charset=utf-8'

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

**Expected behavior**

the method specific headers should be merged in with the headers before setting content-type if not set.

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
Closed in favor of #2623.
