### ISSUE TITLE
AWS rekognition API with  Axios 0.19 request failes where Axios 0.17.0 works fine 

### ISSUE THREAD

**Issue by thekrol01** [axios/axios#2294]
**Describe the issue**
I use the AWS API to call the amazon rekogition endpoint. Which worked fine with axios 0.17..0. 
With Axios 0.19 the request fails with statuscode 400. 

**Example Code**
Code snippet to illustrate your question

```js
// Example code here
```

**Expected behavior, if applicable**
Same behaviour as with Axios 17.0

**Environment:**
 - Axios Version [ 0.19.0]
 - Additional Library Versions [e.g. React 16.78.6 React Native 0.59.9]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jkonze** [comment]
Hey @thekrol01, can you show us the code that is responsible for the 400 response? That would really help!

**Comment by thekrol01** [comment]
Hi @jkonze thank you for your response. Recently I just updates my project and all dependencies to React > 0.60 and the API call works fine again.  Perhaps some underlaying dependancy that caused the behaviour? For me it works fine now.
