### ISSUE TITLE
Could not find a declaration file for module 'axios/lib/adapters/http'

### ISSUE THREAD

**Issue by asnaseer-resilient** [axios/axios#2296]
**Describe the bug**
Importing the axios **HttpAdapter** in a unit test fails.

**To Reproduce**
Create a simple test file containing this at the start:
```
import axios from 'axios';
import httpAdapter from 'axios/lib/adapters/http';
import nock from 'nock';

axios.defaults.url = 'https://localhost';
axios.defaults.adapter = httpAdapter;
...
```
This produces the following error:
```
TS7016: Could not find a declaration file for module 'axios/lib/adapters/http'. 'C:/Users/<user>/<project>/node_modules/axios/lib/adapters/http.js' implicitly has an 'any' type.
  Try `npm install @types/axios` if it exists or add a new declaration (.d.ts) file containing `declare module 'axios';`
```

**Expected behavior**
I expected the import to work. I found a stackoverflow question related to this here: https://stackoverflow.com/questions/50954167/how-to-add-type-definitions-for-module-in-subdirectory

Following this I created `src/types/axios.d.ts` with the following contents:
```
declare module 'axios/lib/adapters/http' {
  import { Adapter } from 'axios';

  const HttpAdapter: Adapter;

  export default HttpAdapter;
}
```
and this seems to fix the issue but I consider it a workaround and it would be nice to have axios contain Typescript type definitions for all the types it defines.

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.14.5 (18F203)]
 - Browser [N/A]
 - Browser Version [N/A]
 - Additional Library Versions
  - Typescript [3.5.3]

**Additional context/Screenshots**
N/A

**Comment by haideralsh** [comment]
Any updates on this?

**Comment by chinesedfan** [comment]
We have no plan to rewrite the whole repository in TypeScript. But you can keep an eye on it. The main task now is cleaning issues and pull requests. Thanks!
