### ISSUE TITLE
Regression: Default proxy detection stopped working for Electron apps in axios 0.19.0

### ISSUE THREAD

**Issue by nikolami** [axios/axios#2297]
**Describe the bug**
`axios.post()` stopped detecting the default OS proxy on Windows in version 0.19.0.
Works OK in previous version 0.18.0.

**To Reproduce**
1. Install [Fiddler](https://www.telerik.com/fiddler) (will act as proxy for testing) or set a proxy on Windows
2. Start Fiddler and capture network traffic. Make sure to capture https traffic from Tools | Options | HTTPs. This will create a temporary proxy, for testing.
2. Create new Electron hello world app
3.. Call from Electron renderer process (the website code part):
```js
axios.post("https://somewhere.com", { data: "anything" });
```

**Expected behavior**
Fiddler shows a request to https://somewhere.com

**Actual behavior**
Fiddler shows no request to https://somewhere.com.
Note: reverting to 0.18.0 axios works OK.

**Environment:**
 - Axios Version **0.19.0**
 - OS: **Windows 10** 10.0.18362.239
 - Browser **Electron**
 - Browser Version **Electron 3.19.0**

**Additional context/Screenshots**

Axios 0.18.0 screenshot from Fiddler:
![image](https://user-images.githubusercontent.com/18406914/61489868-867ffc80-a960-11e9-9f02-c3e87fbf3819.png)

Axios 0.19.0 screenshot: (it's empty, nothing is detected):
![image](https://user-images.githubusercontent.com/18406914/61489910-a4e5f800-a960-11e9-8df6-893df552581c.png)

**Comment by chinesedfan** [comment]
Similar with https://github.com/axios/axios/issues/2654#issuecomment-573461498.
