### ISSUE TITLE
cURL to axios

### ISSUE THREAD

**Issue by aymeneCasino** [axios/axios#2298]
I have this cURL which work fine,

$ curl -X POST --insecure --header "Content-Type: application/json" --header "Accept: application/json"  --header "Authorization: Basic Y21lc3ZtOnZQfCsrNXBNQmxibTkl" -d "{
 \"filter\": \"\",
 \"kind\": \"cluster\",
 \"sort_order\": \"ASCENDING\",
 \"offset\": 0,
 \"length\": 10,
 \"sort_attribute\": \"\"
}" "my_url"

I would like to perform the same post request, i have a bad request error

note that i have to bypass the ssl certificate (done in curl with --insecure and in axios by rejectUnauthorized: false)
the problem is in the data 
someone have an idea ?

**Comment by jkonze** [comment]
Are Hey @aymeneCasino are you working the a browser context or from within node?

**Comment by aymeneCasino** [comment]
never mind i solved it :) 
it was body : {...} instead of data: {...}
