### ISSUE TITLE
why not "finally"?

### ISSUE THREAD

**Issue by biubiubiubalabala** [axios/axios#2299]
**why not "finally"?**
![image](https://user-images.githubusercontent.com/33502578/61536737-e9a88680-aa67-11e9-86b9-bf3ff18ea249.png)
The pic above was cropped from the documentation,I wonder why the last step is "then",shouldn't it be "finally”?

**Comment by blinkcat** [comment]
promise finally is only available on new versions of JavaScript. [mdn finally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally#Specifications).

the then after catch works like  finally.
