### ISSUE TITLE
Implement timeout support on browsers with support for XHR but not for timeout

### ISSUE THREAD

**Issue by markelarizaga** [axios/axios#2301]
**Is your feature request related to a problem? Please describe.**
Some browsers do support XmlHttpRequest but do not support it's timeout feature. This means it's not possible to use the onTimeout callback which Axios relays on in order to provide the timeout config option to Axios users.
This causes that Axios just ignores the timeout feature entirely in those browsers. An example of these browsers is the WebKit based PlayStation browser for PS4 web apps, which is relatively new.

**Describe the solution you'd like**
When the browser shows the behavior described above, the timeout property of the xhr objects is undefined. The suggestion is to use this fact to detect lack of support for the timeout feature of XmlHttpRequest and fallback to a setTimeout done internally to still abort the request when specified by config.timeout.

**Comment by jasonsaayman** [comment]
Closing, please see #2302
