### ISSUE TITLE
Some response data object values are undefind but in request response same values have some values..

### ISSUE THREAD

**Issue by iyashpal** [axios/axios#2304]
The Request Response.
![image](https://user-images.githubusercontent.com/19922707/61761262-d0973100-adeb-11e9-9fdd-600a9cc1a555.png)

Console Log
![image](https://user-images.githubusercontent.com/19922707/61761377-2c61ba00-adec-11e9-8226-873df9359116.png)

**Expected behavior**
Should print the **byMonth** object with it's value but got undefined.

**Environment:**
 - Axios Version:  0.18.0
 - OS: Windows 10 Pro
 - Browser Chrome, Firefox
 - Browser Version [e.g. 22]
 - Additional Library Versions: Vue 2.5.17

**Comment by NSiggel** [comment]
I've been getting the same type of problems w/ simple true/false values in a JSON object in my response.data

Ironically all the true values are fine, however all my false values are being interpreted as undefined
For example:
> enableSearch: undefined
All my other use cases from Chrome / Edge / PostMan all return the proper values for same object
> enableSearch: false

Any suggestions ? I realize FF represents a smaller percentage of my user base but think I need a fix here...

**Comment by qyb** [comment]
In my enviroment,  integer 0 will be parsed as undefined, but 1 and -1 is ok

**Comment by qyb** [comment]
console.log isn't realtime. Would you try console.log the property directly ?  Maybe your framework modify response.data

**Comment by chinesedfan** [comment]
Closed due to stale.
