### ISSUE TITLE
Can I use ssr proxy in axios? but I can use in request.js

### ISSUE THREAD

**Issue by skyh24** [axios/axios#2306]
I have try many ways to cross the local internet. and I find a way using ssr of request, but I can't see any method of axios. can I ask how to use it?

```
request({'url':'https://www.google.com',
        'proxy':'http://127.0.0.1:1087'}, function (error, response, body) {
    if (!error && response.statusCode == 200) {
        console.log(body);
    }
 })
```

but the following doesn't work 
```
const res = await axios.get('https://www.okex.com/api/spot/v3/instruments', {
        proxy: {
            host: '127.0.0.1',
            port: 1087
         }
    })
```

**Comment by skyh24** [comment]
or sock5 proxy

**Comment by qiujinyuan** [comment]
node-tunnal can fix this.
`const tunnelProxy = tunnel.httpsOverHttp({
  proxy: {
    host: "127.0.0.1",
    port: "10887"
  }
});

axios
  .get("https://classroom.googleapis.com/v1/courses", {
    proxy: false,
    httpsAgent: tunnelProxy,
  })`
