### ISSUE TITLE
Using onUploadProgress with electron

### ISSUE THREAD

**Issue by JBtje** [axios/axios#2309]
**Describe the issue**
Using onUploadProgress one should get a status regarding the upload progress. However, when using this in my Electron-vue project, it is not being triggered. Do I do something wrong, or is it somehow not supported?

**Example Code**
```js
async uploadData() {
    let path         = 'c:\\Path\\To\\File\\binaryfile.bin';
    this.data.buffer = await fs.readFileSync( path );

    const FormData = require( 'form-data' );
    let formData = new FormData();
    formData.append( 'file', this.data.buffer, {
        filename:    'binaryfile.bin',
        contentType: 'application/octet-stream',
    } );

    return await axios.post( 'https://www.example.com/upload/binary/file',
        formData.getBuffer(), {
            onUploadProgress:   function( progressEvent ) {
                var percentCompleted = Math.round( (progressEvent.loaded * 100) / progressEvent.total );
                console.log( percentCompleted );
            },
            maxContentLength:   41943040, // Set upload limit to 40 MiB
            headers:            {
                Accept:            'application/json',
                'Content-Type':    formData.getHeaders()['content-type'],
            },
        } )
                      .then( result => {
                          console.log( result );
                          return true;
                      } )
                      .catch( err => {
                          console.log( err );
                          return false;
                      } );
}
```

**Expected behavior**
I expect to see the progress in the console log. However, I see nothing.

**Environment:**
 - OS: Windows 10, x64
 - Browser: Electron (Chromium)

- Axios: 0.19.0
- form-data: 2.5.0
- devtron: 1.4.0

**Comment by JBtje** [comment]
Anyone ?

**Comment by dnewh** [comment]
I recently had an issue using axios to make a POST request with application/octet-stream as well. I had to switch to the request library to make it work.

**Comment by JBtje** [comment]
I started with request, however on some Mac's it did not upload, nor give any error.... switched to Axios on which all works fine (on both Mac and windows). So, can't go back to Request..

**Comment by xinyang3** [comment]
in web environment
I get the problem too, if axios request add a onUploadProgress config, it's not work, but I remove the onUploadProgress config, it's ok.who can tell me why?
this is my code:

const formData = new FormData();
  formData.append('category', category);
  files.forEach(file => {
    formData.append('files', file);
  });

   request.post(urls.upload, formData, {
    onUploadProgress: (e) => {console.log(e)} // error request not send
    headers: {
      "Content-Type": "multipart/form-data"
    },
  });

**Comment by xinyang3** [comment]
I know it, because I used a mock HttpXmlRequest, it has not a process eventListener;

if (typeof config.onUploadProgress === 'function' && request.upload) {
      request.upload.addEventListener('progress', config.onUploadProgress);
    }

**Comment by chinesedfan** [comment]
See #1793. `onUploadProgress` is browser only.
