### ISSUE TITLE
Not all response headers available to .then?

### ISSUE THREAD

**Issue by rconstantine** [axios/axios#2311]
Most of my POST requests work just fine. I post JSON and get JSON back. I'm now trying to POST JSON and get a PDF back.

When I make a POST, it first sends an OPTIONS preflight request, then the regular request, like it always does. Both are returned as successful to the browser with code 200. However in the case of the PDF blob being returned, the ```.then``` only sees a part of the response headers for the POST request (the data). Why aren't all of the POST headers available? The specific header I'm looking for, which is shown on the Network tab of Developer Tools in Chrome is Content-Disposition. There are no errors. This is a client application (Quasar/VueJS). See the code below for where I'm trying to look for Content-Disposition.

On the Network tab, I see two network entries, both named 'download'. The first is the preflight OPTIONS request. The second is the POST request. The data of the POST is what I'm able to grab as a new Blob. I see that some of the headers that get set by ExpressJS's download function are set, such as the Content-Type, which is application/pdf. But Content-Disposition isn't among those seen by axios.

I don't think it matters, but the payload is {path: filePathOnServer} where filePathOnServer is a string of a UNC.

```js
this.$axios.post('/inpatientPDFs/snr/download', payload, { responseType: 'blob'
          /* headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Access-Control-Allow-Origin': '*'
          } */
        }).then(res => {
          console.log('am i downloading?', res)
          const blob = new Blob([res.data], { type: res.data.type })
          const url = window.URL.createObjectURL(blob)
          const link = document.createElement('a')
          link.href = url
          const contentDisposition = res.headers['content-disposition']
          let fileName = 'unknown'
          if (contentDisposition) {
            const fileNameMatch = contentDisposition.match(/filename="(.+)"/)
            if (fileNameMatch.length === 2) {
              fileName = fileNameMatch[1]
            }
          }
          link.setAttribute('download', fileName)
          document.body.appendChild(link)
          link.click()
          link.remove()
          window.URL.revokeObjectURL(url)
        }).catch(err => {
          console.log('or do i have an error?', err)
        })
```
Browser: Chrome
Quasar: 1.0 (VueJS)
Axios: 0.18.0

Any ideas?

**Comment by JaminFarr** [comment]
Sounds like an expose headers issue.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

The server response also needs this header to allow the browser to pass the Content-Disposition to javascript.
`Access-Control-Expose-Headers: Content-Disposition`

It's a browser thing not an axios issue, you wouldn't get the header with fetch or XMLHttpRequest either.

**Comment by rconstantine** [comment]
Thanks, man. Nobody can know everything, so I appreciate the straightforward answer without an undertone of annoyance - particularly since it wasn't specific to Axios. When I stop and think about everything I DO know, it seems like a lot until I think about what I don't know!

**Comment by chinesedfan** [comment]
@meistermuka The CORS problem only occurs when sending from the browser. In fact, you can learn almost everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Good luck!
