### ISSUE TITLE
 axios(config) does not return the promise in   Electron app 

### ISSUE THREAD

**Issue by Praveer1981** [axios/axios#2312]
Hi,
Recently, I upgraded the axios version 0.16.0 to 0,19.0  and my code stopped working.
Electron Version : `5.0.7` -- This version of electron uses chromium 73. 

I found that `axios(config)` never returns promise. also I am not able to capture any kind of error.

**Comment by G07cha** [comment]
Could you please provide an example repository where this issue occurs?

**Comment by Praveer1981** [comment]
Thanks for your response. When I investigated further I found that `axios-retry` is in infinite loop.  I noticed that there are many people encountered  the same issue with axios[0.19.0], For the time being I am using 0.18.1 
FYI, here is the exactly code which caused problem
const r = await axios(config);

**Comment by G07cha** [comment]
@Praveer1981 glad that your problem is solved, thanks for sharing the details, I guess https://github.com/softonic/axios-retry/issues/83 is related to your issue.

**Comment by Praveer1981** [comment]
Yes, you are right. But we can not upgrade until this issue gets resolved into new release.
