### ISSUE TITLE
Can I force axios to run its browser APIs, even if I'm in node?

### ISSUE THREAD

**Issue by samselikoff** [axios/axios#2313]
I'm running a Jest test that verifies my library can properly intercept browser requests made with XMLHttpRequest. I wanted to use axios to initiate a request, and then verify my library can intercept it.

When I run the test in Jest, the axios calls detect we're in node, and use `http` to make the actual request.

I'm wondering if there's a way to force axios to use its browser APIs. Jest is using the jsdom environment, but I'm guessing from isStandardBrowserEnv [here](https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/lib/utils.js#L183) is still returning false.

Running the test gives me this:

![image](https://user-images.githubusercontent.com/2922250/61977449-7e593a00-afbc-11e9-9731-d5b7bf54fc16.png)

**Comment by codingride** [comment]
As far as I know, NodeJS doesn't provide XMLHttpRequest natively.

**Comment by samselikoff** [comment]
No but jsdom does

**Comment by chinesedfan** [comment]
@samselikoff In fact, axios determines the default adapter in `lib/default.js`. If you don't like the provided way, set `config.adapter` explicitly please.

```
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

**Comment by samselikoff** [comment]
That should do it, thanks @chinesedfan !
