### ISSUE TITLE
what's the alternative of  --projectRoot in react native version 0.60.4?

### ISSUE THREAD

**Issue by asmakhalfallah2018** [axios/axios#2319]
with react native @0.59.8 we were able to process like this to launch variants of react native app 

`node node_modules/react-native/local-cli/cli.js start --projectRoot  %~dp0\variant\%1 `

but when upgrading to react native @0.60.4 --projectRoot is no more supported . So how can we replace it ?

**Comment by G07cha** [comment]
I don't think this issue is related to axios library
