### ISSUE TITLE
maxContentLength impact on request content size not mentioned

### ISSUE THREAD

**Issue by Heimschmiede** [axios/axios#2320]
**Section/Content To Improve**
https://github.com/axios/axios#request-config

```
// `maxContentLength` defines the max size of the http response content in bytes allowed
maxContentLength: 2000,
```

**Suggested Improvement**
Due to issue https://github.com/axios/axios/issues/1286
and merged PR https://github.com/axios/axios/pull/1287

the option `maxContentLength` has an impact as well on the **request** content size.
I propose the following wording:
```
`maxContentLength` defines the max size of the http request and response content in bytes allowed
```
**Relevant File(s)**: README.md

**Comment by chinesedfan** [comment]
Closed in favor of #2696.
