### ISSUE TITLE
Triage and maintain roles

### ISSUE THREAD

**Issue by chinesedfan** [axios/axios#2322]
@mzabriskie @emilyemorehouse It is hard to find new maintainers. But how about adding some users with triage roles?

Check links,
- https://github.blog/changelog/2019-05-23-triage-and-maintain-roles-beta/
- https://help.github.com/en/articles/repository-permission-levels-for-an-organization

**Comment by G07cha** [comment]
There are also lots of issues looking like "my code doesn't work, help!", those could be asked on StackOverflow instead with [axios](https://stackoverflow.com/questions/tagged/axios) tag.

**Comment by fed135** [comment]
@G07cha Yeah, that's always been a problem in large OSS. I've been trying to get in contact with the owners for over a month, offering to help/ join as a maintainer. I'm at that point where I think I'll just fork it. Any ideas for a new name ?

**Comment by G07cha** [comment]
@fed135, that would be awesome, but does it needs a new name? Why not just fork it as `axios` and take it from there? 🙂

**Comment by fed135** [comment]
@G07cha My idea was to show that there is new development happening, enable larger changes to take place and capture some attention- kind of like io.js did.

I'm planning to modernize the codebase completely, make the source bleeding edge and export transpiled versions for larger support. I'm very much open to discussion, if you're interested by the idea.

**Comment by G07cha** [comment]
Sounds exciting @fed135, I'd be glad to help!

**Comment by fed135** [comment]
@G07cha https://github.com/fed135/soixa/projects/1
:)

**Comment by avindra** [comment]
Just surfacing the fact that [gaxios](https://github.com/googleapis/gaxios) is trying a similar approach, but even more radical (it's a ground up rewrite). I found that the API in Gaxios isn't 100% match (yet?), for example there is no `.post` method.

**Comment by fed135** [comment]
@avindra that's pretty cool, though it moves away from some of the core principles of Axios imo, being as lightweight as possible:

https://bundlephobia.com/result?p=axios@0.19.0 (12.6Kb)
https://bundlephobia.com/result?p=gaxios@2.0.1 (23.1Kb)

https://npm.anvaka.com/#/view/2d/axios (5 nodes)
https://npm.anvaka.com/#/view/2d/gaxios (11 nodes)

With https://github.com/fed135/soixa, I'm hoping that we can make the bundle even much lighter than Axios by simply modernising some of the code.

---

On a separate topic, as I was just awarded a Triage role for Axios, I'll be closing this issue.
Wish me luck in tidying the backlog of PRs and issues and feel free to poke me if you see me slacking!

**Comment by avindra** [comment]
GL HF. I think there are definitely more bytes to be shaved here, especially in `mergeConfig`

if you want a pair of eyes feel free to tag me in a review
