### ISSUE TITLE
What's the minimum version of nodejs that axios supports?

### ISSUE THREAD

**Issue by crhistianramirez** [axios/axios#2323]
I'm building an SDK and the only dependency is axios. It would be very helpful for me to be able to communicate this information to my users.

I couldn't find an engines field in package.json. I found a similar question from two years ago but cant be confident its accurate

**Comment by fed135** [comment]
To ensure compatibility with all versions you could import the transpiled bundle:

const axios = require('axios/dist/axios');

Otherwise, if you really need an answer, I'd have to defer to other Maintainers.
Personally, I recommend staying on the latest LTS versions.

**Comment by crhistianramirez** [comment]
Even assuming I get the transpiled bundle there will definitely be a lower threshold for node features that don't work in current node.

**Comment by jasonsaayman** [comment]
We build for the lowest of v10, any lower than that is not guaranteed to work.

**Comment by madhubabu-sureify** [comment]
do axios version 0.25.0 is compatible with node 12?
