### ISSUE TITLE
0.19.0会将所有的method全部转为get

### ISSUE THREAD

**Issue by GIn-Liu** [axios/axios#2324]
axios.create中定义method：'post'条件下，在lib/core/Axios.js中，在 config.method.toLowerCase（）前，console.log（config.method）输出为undefined

**Comment by zrqabc** [comment]
I have the same problem,0.18.0 is ok,but 0.19.0 is wrong;

**Comment by zrqabc** [comment]
我也遇到同样的问题了，在0.18.0的时候是可以的，0.19.0在axios.create实例里面设置 post方式，不起作用，浏览器显示还是get
![533d5bbf2c97cd53f62e067aafbf213](https://user-images.githubusercontent.com/28049725/64694701-e3191700-d4cc-11e9-82be-cd5f99046710.png)
