### ISSUE TITLE
the axios instance in loop did not post correct params

### ISSUE THREAD

**Issue by waiaan** [axios/axios#2328]
**Describe the issue**
A clear and concise description of what the issue is.

**Example Code**
Code snippet to illustrate your question

```js
<template>
  <div id="app">
    <ul>
      <li v-for="(item,index) in data" :key="index" @click="handleClick(index)">{{item}}</li>
    </ul>
  </div>
</template>
<script>
  import Vue from 'vue';
  import axios from 'axios';
  import qs from 'qs';

  var instance = axios.create({
    transformRequest: [
      data => {
        data = qs.stringify(data);
        return data;
      }
    ],
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded;'
    }
  });

  let params = {
    method: 'post',
    url: 'http://127.0.0.1:1119',
    data: {
      body: 0
    }
  };

  export default {
    data() {
      return {
        show: true,
        data: ['00000', '11111', '22222222', '33333333', '444444']
      };
    },
    methods: {
      handleClick(index) {
        for (let i = 0; i < 3; i++) {
          params.data.body = i;
          instance(params);
        }
      }
    }
  };
</script>
<style scoped>
</style>


```

**Expected behavior, if applicable**
when the list item is clicked , it should send http request as params.data.body=0 | params.data.body=1|params.data.body=2 as it looped. however it sent params.data.body=2 three times. 

**Environment:**
 - Axios Version [e.g. 0.18.0]
0.18.0
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
win10
 - Browser [e.g. Chrome, Safari]
chrome
 - Browser Version [e.g. 22]
75
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]
vue

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by G07cha** [comment]
Because `params` is an object it's always being passed as a reference and since you are modifying property of that reference you are modifying original object which is being reflected in all `instance` calls. To avoid this you need to make a copy of `params` object for each call:

```javascript
for (let i = 0; i < 3; i++) {
  instance({
    ...params,
    data: {
      body: i
  });
}
```

Or if you can't use destructuring:

```javascript
for (let i = 0; i < 3; i++) {
  const newParams = Object.assign({}, params, { data: { body: i }})
  instance({
    ...params,
    data: {
      body: i
  });
}

**Comment by waiaan** [comment]
> Because `params` is an object it's always being passed as a reference and since you are modifying property of that reference you are modifying original object which is being reflected in all `instance` calls. To avoid this you need to make a copy of `params` object for each call:
> 
> ```js
> for (let i = 0; i < 3; i++) {
>   instance({
>     ...params,
>     data: {
>       body: i
>   });
> }
> ```
> 
> Or if you can't use destructuring:
> 
> ```js
> for (let i = 0; i < 3; i++) {
>   const newParams = Object.assign({}, params, { data: { body: i }})
>   instance({
>     ...params,
>     data: {
>       body: i
>   });
> }
> ```

thank you .
so instance is not sent request immediately in every loop?

**Comment by G07cha** [comment]
> thank you .
> so instance is not sent request immediately in every loop?

Yes, if you look at [Axios.request](https://github.com/axios/axios/blob/master/lib/core/Axios.js#L40-L56) method, it puts configuration in promise which means it's going to be executed in the next event loop cycle the earliest

**Comment by waiaan** [comment]
> > thank you .
> > so instance is not sent request immediately in every loop?
> 
> Yes, if you look at [Axios.request](https://github.com/axios/axios/blob/master/lib/core/Axios.js#L40-L56) method, it puts configuration in promise which means it's going to be executed in the next event loop cycle the earliest

thanks
