### ISSUE TITLE
adding interceptor on an axios.create() instance is adding them statically to all other axios

### ISSUE THREAD

**Issue by jeffthompson1971** [axios/axios#2329]
I'm needed to have stand-alone axios INSTANCES that have their own list of interceptors.   But when I do this:

const myAxios = axios.create();
 myAxios.interceptors.response.use(undefined, function (result) {
            if (result && result.config && result.config.globalErrorHandling === false) {
                return Promise.reject(result);
            }
...
}

I only want this ONE myAxios instance to have this interceptor.  But now every single other axios instance in my service is using the interceptor??

How can I get a PROPER axios INSTANCE that does not share interceptors statically with every single other axios used in the app?

**Comment by G07cha** [comment]
Seems to be working for me with following code:

```javascript
const axios = require("axios")

const instance1 = axios.create();
instance1.interceptors.request.use(function (response) {
    console.log('interceptor')
    return response;
  }, function (error) {
    console.log('interceptor error')
    return Promise.reject(error);
  });

const instance2 = axios.create();

instance1.get('http://www.example.com').then(() => console.log('instance1 done'))

instance2.get('http://www.example.com').then(() => console.log('instance2 done'))
```

How do you create other instances?
