### ISSUE TITLE
posting with axios does nothing

### ISSUE THREAD

**Issue by lRoberth** [axios/axios#2330]
**Describe the issue**
The library is being included successfully, but at the moment of trying to do the post, nothing happens.

**Example Code**
post.js - this is where i create the posturl function, called by api.js
```js
console.log("Loaded post.js");
const axios = require('axios');

function postURL(url, json){
    console.log("Called function, posting " + url);

    axios.post(url, json)
    .then(function (res) {
        console.log("result: " + res);
        return res;
    })
    .catch(function (error) {
        console.log("error: " + error);
        return error;
    });
}

module.exports = {
    postURL : postURL
}
```

api.js - where i call the postURL function
```js
console.log("Loaded API.js");

Post = require('./post.js');

console.log("Post: " + Post.postURL("http://localhost/d.php", {
    info: "hey"
}));
```
d.php - where the POST is being sent to
```php
<?php
if(isset($_POST['info'])){
	echo "hello";
	print_r($_POST);
}
?>
```

**Expected behavior, if applicable**
should print to the console the result of the post

**Environment:**
 - Axios Version 0.19.0
 - OS: Windows 10
 - Browser 
 - Browser Version 
 - Additional Library Versions 

**Additional context/Screenshots**
Currently coding a gamemode for RageMP, and I need to make a POST request to a web server in order to get, update and create information on a InnoDB database. Found this Axios library, to make POST requests a lot more easier. Tried to use it, but it just won't work. The library is being required successfully by RageMP, but it just won't run the function (no errors in console)

This is the full console output:
```
        MaxPlayers:             100
        Sync rate:              40ms
        Name:                   RAGE:MP Unofficial server
        Gamemode:               freeroam
        Streaming distance:     500
        Announcement:           enabled
        Voice chat:             disabled
        Address:                127.0.0.1:22005
        Connection limits:      disabled
        Encryption:             disabled
        NodeJS:                 enabled
        C#:                     disabled

[=========================================================]


[N] Starting network... - OK: (IPv4-only) at 127.0.0.1:22005
(node:18092) ExperimentalWarning: The ESM module loader is experimental.
Loading packages
        "newbournerp" loaded
Loaded post.js
Loaded API.js
Called function, posting http://localhost/d.php
Post: undefined
[P] Plugin bridge.dll loaded!
Started HTTP server at 22006 port.
[M] Announcing into master server...
[M] Connected to master list.
```

**Comment by G07cha** [comment]
axios sends POST requests in JSON format by default but [`$_POST`](https://www.php.net/manual/en/reserved.variables.post.php) works with `application/x-www-form-urlencoded` and `multipart/form-data`. You can convert axios request to former format like so:

```javascript
const querystring = require('querystring');
const axios = require('axios');

function postURL(url, json) {
    axios.post(url, querystring.stringify(json))

   //...
}
```

**Comment by sinahwz** [comment]
Axios is using Promises, so you need to wait for the response.
post.js
`function postURL(url, json) {
  console.log("Called function, posting " + url);
  return new Promise((resolve, reject) => {
    axios.post(url, json)
      .then(function(res) {
        console.log("result: " + res);
        resolve(res);
      })
      .catch(function(error) {
        console.log("error: " + error);
        reject(error);
      });
  });`

api.js : 
`console.log("Loaded API.js");

Post = require('./post.js');

Post.postURL("http://localhost/d.php", {
    info: "hey"
})
.then(function(result) {
    console.log("Post: " + result);
})
.catch(function(err) {
    console.log("ERR: " + err);
});
 `

**Comment by Alanscut** [comment]
As @G07cha did, we could get the correct result after processing `json` parameter with `querystring.stringfy`.
