### ISSUE TITLE
Some response data object values are undefind but in request response same values have values

### ISSUE THREAD

**Issue by reki630** [axios/axios#2334]
![image](https://user-images.githubusercontent.com/43027045/62407159-6b5eef00-b5e6-11e9-9319-84c84db019bc.png)

![image](https://user-images.githubusercontent.com/43027045/62407160-74e85700-b5e6-11e9-9a95-b1d551cc3174.png)

Expected behavior
Should print the companyId with it's value but got undefined.

Environment:

Axios Version: 0.19.0
OS: Windows 10
Browser Chrome
Browser Version 75.0.3770.142
Additional Library Versions: React 16.8.6

**Comment by G07cha** [comment]
Can you post code that sends the request?

**Comment by reki630** [comment]
> Can you post code that sends the request?

![image](https://user-images.githubusercontent.com/43027045/62418695-28fae800-b6a2-11e9-94d8-1d0c3f6b3725.png)

**Comment by G07cha** [comment]
Looks good to me, where are you logging resulting data? Can you try logging like this -`console.log(JSON.stringify(data))` right before assigning to `res`?

**Comment by reki630** [comment]
> Looks good to me, where are you logging resulting data? Can you try logging like this -`console.log(JSON.stringify(data))` right before assigning to `res`?

![image](https://user-images.githubusercontent.com/43027045/62421438-4a74c780-b6d4-11e9-84fc-9aafa5b6ca81.png)

If I console.log(JSON.stringify(data)),it has value

**Comment by G07cha** [comment]
Then my best guess is that `res` is being modified somewhere outside, that causes `companyId` to become undefined. Keep in mind, when you logging objects as-is using `console.log` it's being evaluated real-time in Chrome Devtools as you expand the object.

I would check your code for places where you modify properties of `res`. I'm almost certain, it's not related to axios.

**Comment by reki630** [comment]
> Then my best guess is that `res` is being modified somewhere outside, that causes `companyId` to become undefined. Keep in mind, when you logging objects as-is using `console.log` it's being evaluated real-time in Chrome Devtools as you expand the object.
> 
> I would check your code for places where you modify properties of `res`. I'm almost certain, it's not related to axios.

![image](https://user-images.githubusercontent.com/43027045/62421989-95dfa380-b6dd-11e9-9b0d-300658da3a79.png)

But if I console.log(data) before assigning to res, companyId is still undefined

**Comment by G07cha** [comment]
You are assigning `data` to `res`, which means you are not copying the object but a reference to that object and all changes made to `res` will be reflected in `data`.

Here is an example of such behaviour:

```javascript
const firstObj = { foo: 'bar' };
const secondObj = firstObj;
secondObj.foo = 'baz';
console.log(firstObj); // { foo: 'baz' }
```

If you do `res = JSON.parse(JSON.stringify(data))`, then `data` should remain as is regardles of what you are doing to `res`.

**Comment by reki630** [comment]
Thank you!I know why it's become undefined

**Comment by G07cha** [comment]
@reki630 you are welcome, feel free to close this issue if your problem is resolved 🙂
