### ISSUE TITLE
Numeric Request Headers

### ISSUE THREAD

**Issue by teapejon** [axios/axios#2339]
**Describe the issue**
Axios allows a header values to be a numeric in the json collection, however in .NET it only allows strings. Do you do any reformatting in the request to have the numeric value of the header identified by the receiver?

**Example Code**
Code snippet to illustrate your question

```js
var headervaluestring = `${new Date().getTime()}`;
var headervaluenumeric = new Date().getTime();
```

**Expected behavior, if applicable**
What is the format in the request from node?

**Environment:**
 "axios": "0.18.0",
    "es6-promise": "4.2.5",
    "express": "4.16.4",
    "helmet": "3.15.0",
    "https-proxy-agent": "^2.2.2",
    "js-base64": "2.5.0",
    "morgan": "1.9.1",
    "node-rsa": "1.0.2"
"node >= 8.9.4"

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by yasuf** [comment]
that referenced PR doesn' thave to do with this issue?

**Comment by Alanscut** [comment]
embarrassing... typo, should be `#2239`

**Comment by chinesedfan** [comment]
Non-string values will be converted to strings for network transmission. It is not done by axios' adapters, like XHR or Node.js http package.
