### ISSUE TITLE
'Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.' in a POST Request

### ISSUE THREAD

**Issue by SASFMONTOYA** [axios/axios#2345]
**Describe the issue**
I'm try to consume an POST method from my API (Web API C#), I have two problems, the first was that Axios get the error `'Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.'` and this was solved add to the controller api a default code for Options:

```c#
[HttpOptions]
public IHttpActionResult Options()
{
    return Ok();
}
```

And I use the code to consume:
```js
let data = {
       Nit_ID: '899999284',
       UserName: 'sasfdm',
       Password: btoa('123456789'),
       Public_IP: '123.456.789.123',
       Private_IP: '987.654.321.987'
 };
 //
let resultApi = await axios.post(
           "https://localhost:44377/api/usuario",
           data
 };
```

Now, I want to send a header and I get the same error `Access to XMLHttpRequest at 'https://localhost:44377/api/usuario/verifydoublefactorcode' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

**Example Code**
I get the error when I use the next sintax:
```js
let data = {
       Nit_ID: "899999284",
       UserName: "sasfdm",
       Code: "1eb16ac5"
};
console.log(localStorage.getItem("DoubleFactorToken"));
let headers = {
       'Authorization': localStorage.getItem("DoubleFactorToken")
};
let resultApi = await axios.post(
     this.apiSeguridad + "usuario/verifydoublefactorcode",
     data,
     {
         headers: headers
     }
);
```

But If I use Ajax to send the request, I get the answer that I wait:

```js
let data = {
       Nit_ID: "899999284",
       UserName: "sasfdm",
       Code: "1eb16ac5"
};
console.log(localStorage.getItem("DoubleFactorToken"));
let headers = {
     Authorization: localStorage.getItem("DoubleFactorToken")
};
let resultApi = await $.ajax({
          cache: false,
          type: "POST",
          url:  "https://localhost:44377/api/usuario/verifydoublefactorcode",
          headers: headers,
          data: data
 });
console.log(resultAPI);
```
![image](https://user-images.githubusercontent.com/22794697/62710398-d892cb80-b9bc-11e9-9520-028e18514de8.png)

**Expected behavior, if applicable**
I used Posman to send the request, and I wait the next answer:
```json
{
    "Nit_ID": "899999284",
    "UserName": "sasfdm",
    "FullName": "Fabian Dario Montoya",
    "CorreoEncrypt": null,
    "Token": null,
    "Option": 1,
    "Error": true,
    "Mensaje": "El código de verificación no coincide con el autorizado. Favor validar."
}
```
![image](https://user-images.githubusercontent.com/22794697/62710497-0d068780-b9bd-11e9-89d6-50f052622a23.png)

**Environment:**
 - Axios Version 0.19.0
- Vue-Axios: 2.1.4 
 - OS: [Win 10 v. 1903]
 - Browser: Google Chrome
 - Browser Version 76.0.3809.87
 - Additional Library Versions: Vue: 3.9.3

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by YakovL** [comment]
I have a similar issue, may be [this](https://stackoverflow.com/q/58009309/3995261) will be helpful for debugging, but I'm not sure

**Comment by SASFMONTOYA** [comment]
I resolved it adding 
```c#
var corsAttr = new EnableCorsAttribute("*", "*", "*");
config.EnableCors(corsAttr);
```
into 
```c#
public static void Register(HttpConfiguration config)
``` 
in `Global.asax.cs` in my web api project:

```c#
public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Configuración y servicios de API web

            //Configuración para verificar la seguridad del CORS
            var corsAttr = new EnableCorsAttribute("*", "*", "*");
            config.EnableCors(corsAttr);

            // Rutas de API web
            config.MapHttpAttributeRoutes();

            //Validación de headers
            config.MessageHandlers.Add(new TokenValidationHandler());

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }
```

**Comment by sergx** [comment]
This worked out for me:
``` js
axios({
  method: 'post',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  url: 'http://my-api-site.ru/ajax.php',
  data: { user_data : true }
}).then(function (response) {
  console.log(response.data);
});
```
And on server side (PHP):
``` php
header('Access-Control-Allow-Origin: *');
```

**Comment by asad041** [comment]
You must indicate what type of `Access-Control-Allow-Headers` are acceptable at your server end. In your case it is `Authorization` so it would be like this;
 
server-side (PHP):
```
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
header("Access-Control-Allow-Headers: Authorization");
```
client side:
```
const headers = { "Authorization" : `Bearer ${token}` };
const response = await axios.get(url, { headers: headers });
```
For the cross-origin policy spec about this see [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests )

**Comment by chinesedfan** [comment]
Looks like this issue is a CORS problem and has been resolved.
