### ISSUE TITLE
Axios does not return the desired data type correctly

### ISSUE THREAD

**Issue by lzw1604748707** [axios/axios#2348]
**Describe the bug**
When I try to configure the **responseType** to be **blob** or **json** in nodejs, I don't get the data type I want, the return value is all string type, see the source code found, only distinguish between **arraybuffer** and  **stream**  in the http.js file , the rest of the situation will be converted to a String to return
...
Then I found that there is no merge configuration of **responseEncoding** in mergeConfig.js.
...
The axios module was obtained from npm.

**To Reproduce**
I tried to write a crawler to crawl the Chinese website and then transcode it.
. . .

```js
  axios({
    url: 'http://desk.zol.com.cn/pc/',
    responseType: 'blob',
   // responseEncoding: 'GBK'
    transformResponse: [
      function(data) {
        var html = iconvLite.decode(data, 'gb2312')
        return html
      }
    ]
  }).then(data=>{
  ...do someing
})
```

**Expected behavior**
Can return the desired data correctly

**Environment:**
 - Axios Version 0.19.0
 - OS:  OSX 10.14.4
 - Browser Chrome
 - Browser Version 75.0.3770.142
 - Additional Library Versions node 12.8.0

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It should have been fixed by #2207. Please check 0.19.1 again.
