### ISSUE TITLE
multiple axios request simultaneously

### ISSUE THREAD

**Issue by iteniasim** [axios/axios#2355]
**Describe the issue**
i am sending an axios request to post something(reply in my case-i am building a forum to learn coding) which will initiate a notification posting through a queue which will take a lot of time depending on the number of users in the database (takes almost a minute in my test db and there is supposed to be a lot more data in reality which might take hours to process) and although the posting is done instantly the response is returned after a long time.

**Example Code**
Code snippet to illustrate your question

```js
    addReply() {
      axios
        .post(location.pathname + "/replies", { body: this.body })
        .catch(error => {
          flash(error.response.data, "danger");
        })
        .then(({ data }) => {
          this.body = "";
          flash("Your Reply Has Been Posted.");
          this.$emit("created", data);
        });
    }

// this is my code right now

```

**Expected behavior, if applicable**
I need to send an axios get request right after the post request where the actual posting will be done almost instantly but the response of the post request will be delayed due to the queue processing linked to it.

So i am trying to send another axios get request to get the data just posted with the first axios post request so the app can do its thing while all the notifications queues are being processed and i dont have to wait for the axios.post response

**Environment:**
 - Axios Version 0.18.1
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 76.0.3809.100
 - Additional Library Versions vue 2.5.17 laravel 5.8

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by iteniasim** [comment]
Apparently i had to change the queue driver in .env in laravel for queue to work.... So i might be able to work this out soon..

But still is the above mentioned feature available in axios?

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
