### ISSUE TITLE
Can't catch error response

### ISSUE THREAD

**Issue by wangfpp** [axios/axios#2358]
**Describe the bug**
use interceptors but can't catch nothing error message 
my network is working
**To Reproduce**

```javascript
instance.interceptors.response.use( response => {
    return response;
}, error => {
    return Promise.reject(error);
   // i can't get nothing  just Error NetWork error
});

axios.post(url).then(res => {

}, err => {
// i can't get nothing  just Error NetWork error
})
```

**Expected behavior**

**Environment:**
 - Axios Version 0.19.0
 - OS: Ununtu 18.04
 - Browser  Chrome
 - Browser Version  76.0.3809.87
 - Additional Library Versions  React 16.9.0

**Comment by Lorchelio** [comment]
@wangfpp try get response inside `.catch` function, it works for me.

**Comment by cesar18pena** [comment]
@wangfpp that problem happens in general or only with `post` method? I tried to replicate the problem and the interceptor is working correctly for me (only tested `GET` request). You can see the code of React I use below:

``` js
import React from 'react';
import axios from 'axios';

class App extends React.Component {

  state = {
    users: [],
    errorMessage: null
  };

  componentDidMount() {

    const instance = axios.create({
      baseURL: 'http://localhost:3000/api',
    });
    
    instance.interceptors.response.use(response => {
      return response;
    }, error => {
      console.log('Full rejected promise using interceptors');
      return Promise.reject({'errorMessage': error});
    });
    
    instance.get('/users')
      .then(response => {
        console.log('Everything is good', response.data);
        this.setState({users: response.data});
      })
      .catch(error => {
        console.log('There is a error', error);
        this.setState({errorMessage: error});
    });
    
  }

  render() {
    const { errorMessage } = this.state;

    if(errorMessage) {
      return (
        <div>{errorMessage.errorMessage}</div>
      )
    } else {
      return (
        <div>
          Waiting for request to process
        </div>
      )
    }
   
  }
}
export default App;
```

**Environment use to replicate error**:

| Technology  | Version  | 
| :------------- | :----------: |
|  Axios | 0.19.0   |
| OS  | macOS Mojave 10.14.6  |
| Browser  | Google Chrome |
| Browser Version  | 76.0.3809.100  |
| React  | 16.9.0 |

**Comment by chinesedfan** [comment]
I think you have caught it. `Error NetWork error` is the error.
