### ISSUE TITLE
Media blob response is being serialised to a string 

### ISSUE THREAD

**Issue by rnmalone** [axios/axios#2359]
**Describe the issue**
Sending a GET request to our media server to receive an audio file will cause axios to transform the body to a string, rather than an expected Blob object that is received when we used  `window.fetch()`. 

Note that trying to instantiate a new blob from this received string results in an invalid object and we cannot use `URL.createObjectUrl` to play the file.

**Example Code**
Code snippet to illustrate your question

```js
try {
  // Sending header `Accept: */*'
  const response = await axios(url, {
	url,
	method,
	headers,
	data: body
  });

   return response;
} catch (error) {
   throw (error);
	}
}
```

**Expected behavior, if applicable**
A response with a binary body should be preserved as a javascript Blob object

**Environment:**
 - Axios Version: 0.19
 - Browser Chrome 76

**Additional context/Screenshots**
![Screen Shot 2019-08-16 at 13 46 48](https://user-images.githubusercontent.com/5717779/63168702-c6ec9c00-c02c-11e9-8e7c-c2a79894f8c2.png)

**Comment by JBtje** [comment]
Make sure to set the responseType to blob...
```javascript
axios.get( '/some/url/to/somewhere/', {
    responseType: 'blob', // Very important!
} )
     .then( ( response ) => {
         let filename = response.headers['content-disposition'].replace( /attachment; filename=/, '' ).replace( /"/, '' );
         let url      = window.URL.createObjectURL( new Blob( [response.data] ) );
         let link     = document.createElement( 'a' );
         link.href    = url;
         link.setAttribute( 'download', filename );
         document.body.appendChild( link );
         link.click();
     } )
     .catch( ( error ) => {
         this.handleErrorResponse( error );
     } );
```
