### ISSUE TITLE
Requesting with OPTIONS method

### ISSUE THREAD

**Issue by tbhaxor** [axios/axios#2361]
**Describe the issue**
For every `POST` request Axios is requesting with OPTIONS method

**Example Code**
Code snippet to illustrate your question

```js
Axios.post(
            "http://localhost:3000/api.v1/author/login",
            doc,
            {
              withCredentials: true,
              headers: { "Content-Type": "application/json" }
            }
          );
```

**Expected behavior, if applicable**
Should do what is asked to. ONLY POST

**Environment:**
 - Axios Version: 0.19.0
 - OS: Manjaro
 - Browser: Mozilla Firefox
 - Browser Version: 68.0.1
 - Additional Library Versions: VueJS

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/28386721/63243933-9ea5ad00-c279-11e9-84d3-5fe79cce1096.png)

**Comment by jasonsaayman** [comment]
This is correct, this is a pre-flight check. Refer to #475 to see more.
