### ISSUE TITLE
Axios.all recently slow

### ISSUE THREAD

**Issue by npham20489** [axios/axios#2363]
**Describe the issue**
My react native app using axios.all, it recently slow by waiting for one api to response. For example, the app try to fetch data by invoke 3 apis. Then, one of 3 apis take a bit more time to wait for response. I try with reactjs and found it not happen.

**Example Code**
Code snippet to illustrate your question

```
axios.all([
      ApiService.post(API_01, params),
      ApiService.post(API_02, params),
      ApiService.post(API_03, params),
    ]).then(axios.spread(function (reps01, resp02, resp03) {
      dispatch(fetchAllListSuccess({
        object01: reps01.data,
        object02: reps02.data,
        object03: reps03.data
      }));
    })).catch(error => {
      dispatch(fetchAllListFailed(error));
    });
```

**Expected behavior, if applicable**
Is there any problem between axios and react native, or is there any mistake from my side?

**Environment:**
 - Axios Version [0.18.0]
 - OS: [iOS 12]
 - Additional Library Versions [React 16.3.0-alpha.1, React Native 0.54.4]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Hi, I think this question relates more to your internal servers, or how you are calling, or possibly just general network latency. I think this question is better suited to StackOverflow or similar.
