### ISSUE TITLE
CDN import: loading from unpkg fails

### ISSUE THREAD

**Issue by maritaria** [axios/axios#2370]
**Describe the bug**
Importing axios through unpkg loads a non-browser compatible nodejs file.

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

Code:
```html
<script type="text/javascript" src="https://unpkg.com/axios@0.19.0"></script>
```
Result (browser console)
```
ReferenceError: module is not defined
```

**Expected behavior**
Loading from cdn loads the `dist/axios.js` or `dist/axios.min.js` file.

**Environment:**
 - Axios Version [0.19.0]
 - Browser [Firefox]
 - Browser Version [68]
 - Additional Library Versions []

**Additional context/Screenshots**

**Comment by chinesedfan** [comment]
Try `https://unpkg.com/axios@0.19.0/dist/axios.js` or `https://unpkg.com/axios@0.19.0/dist/axios.min.js` please.
