### ISSUE TITLE
IE11及以下发送OPTION请求的时候说列表找不到请求头

### ISSUE THREAD

**Issue by liudid** [axios/axios#2371]
在有带token请求的情况下，IE11及以下发送OPTION请求的时候说列表找不到请求头，尝试了各种办法，比如降低浏览器阻止脚本、使用es6-primise、使用babel-polyfill都尝试了依然不行，除了IE浏览器其他浏览器都正常，求大家的帮助帮看看是什么原因啊，谢谢。
![DIOX$EM@O0E$YJ5B30$QSYU](https://user-images.githubusercontent.com/31311845/63649078-c1e5c600-c76b-11e9-9aad-66685995a719.png)

**Comment by ryouaki** [comment]
后端问题。

**Comment by shclu** [comment]
请问一下，这个项目clone下来install之后，应该怎么起服务呢，直接npm start不可以

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Good luck!
