### ISSUE TITLE
Network error in axios and react-native after bundle release

### ISSUE THREAD

**Issue by yang200258** [axios/axios#2373]
**Is your feature request related to a problem? Please describe.**
         I'm using react-native and axios to request,in debug model,everything is fine,but when bundle release,it occurs to the 'Network error' in my phone.

![image](https://user-images.githubusercontent.com/38518538/63661710-4842ec00-c7ee-11e9-9db1-bd7bcabbc5c8.png)

**Describe the solution you'd like**
         I wnt it request nomal in bundle release.

**Comment by shalevmo** [comment]
Same issue here

**Comment by shalevmo** [comment]
> **Is your feature request related to a problem? Please describe.**
> I'm using react-native and axios to request,in debug model,everything is fine,but when bundle release,it occurs to the 'Network error' in my phone.
> 
> ![image](https://user-images.githubusercontent.com/38518538/63661710-4842ec00-c7ee-11e9-9db1-bd7bcabbc5c8.png)
> 
> **Describe the solution you'd like**
> I wnt it request nomal in bundle release.

Found the answer here:
 https://github.com/facebook/react-native/issues/24039#issuecomment-518687649
