### ISSUE TITLE
[merge options] Inconsistent behavior between 0.18.1 and 0.19.0

### ISSUE THREAD

**Issue by liyuanqiu** [axios/axios#2374]
**Describe the bug**
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**
```plaintext
v0.19.0 changes the source code of merging default options and request options.
But the merging behavior wasn't kept same with v0.18.1.

For example, if default options is:

{
  baseUrl: 'some_url',
  params: {
    foo: 'bar',
  },
}

In v0.18.1, the merged options will contain `params`, but in v0.19.0, the merged options won't contain `params`.
```

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
const instance = axios.create({
  params: {
    foo: 'bar',
  },
});
instance({
  url: 'some_url',
  method: 'get',
});

// in v0.18.1
// GET some_url?foo=bar
// https://codesandbox.io/s/charming-wilson-9wkge

// in v0.19.0
// GET some_url
// https://codesandbox.io/s/nifty-fire-yhhth
```

**Expected behavior**
```plaintext
I think v0.19.0 shouldn't change the merging behavior.
```

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.14.6]
 - Browser [Chrome]
 - Browser Version [Version 76.0.3809.100 (Official Build) (64-bit)]
 - Additional Library Versions [React 16.9]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by G-Rath** [comment]
I've just hit this, and found it very surprising. It goes against the use-case of `create`:

```
const axios = Axios.create({
  baseURL: url.resolve(process.env.API_URL, '/api'),
  params: { token: process.env.API_TOKEN }
});
```

**Comment by willxy** [comment]
possibly related to:
https://github.com/axios/axios/issues/2190

**Comment by elboletaire** [comment]
> possibly related to: #2190

It is indeed the same issue described in #2190

**Comment by chinesedfan** [comment]
So let's track in #2190. Hope someone can merge and release that soon.
