### ISSUE TITLE
Promise is not rejected after upgrade to 0.19.0

### ISSUE THREAD

**Issue by ntelkedzhiev** [axios/axios#2377]
**Describe the bug**
The response has a status code 500 and the promise is resolved instead of being rejected.

**Environment:**
 - Axios Version: 0.19.0

**Comment by cesar18pena** [comment]
@ntelkedzhiev Could you the example you are running? I tried to replicate your error using Axios 0.19.0, but the promise gets rejected like should be.

You can see I had a simple API to return a 500 status code with a error message
<img width="684" alt="Screen Shot 2019-08-28 at 9 54 38 PM" src="https://user-images.githubusercontent.com/31670740/63904294-771fb480-c9de-11e9-9216-3f75dc773b1d.png">

I use Axios 0.19.0 to make the request and print in the console the error, you can see in the picture that I get the error message from the server
<img width="998" alt="Screen Shot 2019-08-28 at 9 52 35 PM" src="https://user-images.githubusercontent.com/31670740/63904275-64a57b00-c9de-11e9-94ae-b7485a8aa300.png">

**Comment by ntelkedzhiev** [comment]
Sorry to bother. I found the problem elsewhere. Thanks!
