### ISSUE TITLE
Axios results in 413, other libraries don't

### ISSUE THREAD

**Issue by ktalebian** [axios/axios#2379]
I'm trying to upload a source map to rollbar (docs found [here](https://docs.rollbar.com/reference)). 

Here is the code sample I am using:

```js
const fs = require('fs');
const FormData = require('form-data');
const axios = require('axios');

const stream = fs.readFileSync('/path/to/sourcemap', 'utf8');
const config = {
  filename: 'sourcemap',
  contentType: 'application/json',
}

const formData = new FormData();
formData.append('access_token', 'the-token');
formData.append('version', '1.2.3');
formData.append('minified_url', 'https://example.com/1.2.3/minified.js');
formData.append('source_map', stream, config);

axios.post('https://api.rollbar.com/api/1/sourcemap', formData, {
  headers: formData.getHeaders(),
});
```

This request fails with:

```
Error: Request failed with status code 413: Request entity too large.
```

However, `curl` works fine, so does spawning a process and doing a `curl`, and so does the  use of `node-fetch`:

```sh
curl https://api.rollbar.com/api/1/sourcemap \
        -F access_token=${ACCESS_TOKEN} \
        -F version=${VERSION} \
        -F minified_url=${1} \
        -F source_map=@${SOURCE_MAP_PATH}
```

```js
// this is spawning process

const execaArgs = [
    'https://api.rollbar.com/api/1/sourcemap',
    '-F',
    'access_token=abc',
    '-F',
    'version=1.2.3',
    '-F',
    'minified_url='https://example.com/1.2.3/minified.js',
    '-F',
    `source_map=@${filePath}`
  ]
  const {stdout, stderr} = await execa('curl', execaArgs);
```

```js
// here the data is exactly the same as the Axios example

fetch('https://api.rollbar.com/api/1/sourcemap', {
    method: 'POST',
    body: formData
  })
    .then(res => res.json())
    .then(json => console.log(json));
```

All of these examples do work, it's only Axios that is having the issue. I've tried to inspect the request to see what is happening, but couldn't really find anything useful.

**Comment by cesar18pena** [comment]
@ktalebian In the documentation of [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) I don't see any method called `getHeaders()` and you are using it in the example of Axios. Could you pass the necessary headers directly instead of using `getHeaders()` to see what happens?

**Comment by GitCHQL** [comment]
seem axios 1.9 have this  issue ,i try it on 1.80.1 it work

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios/issues/2049#issuecomment-503435918, which requires `formData.getBuffer()`.
