### ISSUE TITLE
how to post a huge javascript object

### ISSUE THREAD

**Issue by boborua** [axios/axios#2382]
**Describe the issue**
When posting a large object through axios post method, the browser will crash

**Example Code**

```js
// Example code here
// this object will be very large;
const data = {........};
// JSON.stringify(data).length will be 550000000 which means nearly 550MB!
axios.post('http://xxx.yy.com/api/', importData, {
      headers: { 'content-type': 'application/json' },
    }).then(msg => window.console.log('success:', msg))
    .catch(err => window.console.log('error: ', err));
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version 0.17.0
 - OS: Win10
 - Browser Chrome
 - Browser Version 76
 - Additional Library Versions React.16.8

**Additional context/Screenshots**
chrome page will crash and showing this picture...
![image](https://user-images.githubusercontent.com/31718063/63991850-e5b65c80-cb1b-11e9-9af6-05f7788e5606.png)

**Comment by pavinduLakshan** [comment]
You can break data into chunks and send while keeping track of number of chunks sent.

**Comment by boborua** [comment]
You mean that setting the header Transfer-Encoding to "chunked"?

**Comment by dimonchoo** [comment]
Are you sure, that is correct way to done task?
Maybe would be correct way to do task in the background? Server -> server? sorry for eng

**Comment by pavinduLakshan** [comment]
@dimonchoo but will it prevent browser from getting stuck? I mean, it's still happening in the browser.

**Comment by chinesedfan** [comment]
Maybe you can try [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers).

Anyway, it is not an issue of axios. We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com). Good luck!
