### ISSUE TITLE
HERE geocoder-autocomplete with ReactJS suddenly returning Network Error on Firefox

### ISSUE THREAD

**Issue by rfdc** [axios/axios#2388]
Hi there,

**Describe the bug**
I've implemented the solution from the [HERE tutorial ](https://developer.here.com/blog/street-address-validation-with-reactjs-and-here-geocoder-autocomplete) and it worked well on **Firefox** and **Chrome**.  However, few weeks ago it stopped working on **Firefox** and started returning `Network Error`. **_The request doesn't even show on my network log._**

I've tested the [API EndPoint](https://developer.here.com/documentation/geocoder-autocomplete/topics/quick-start-get-suggestions.html) w/ my credentials and it worked. 

I've tried to hardcode the credential and also via `.env` and neither approach worked on firefox

**To Reproduce**
Follow this [tutorial](https://developer.here.com/blog/street-address-validation-with-reactjs-and-here-geocoder-autocomplete)

```js
    try {
      const address = await axios.get(`https://autocomplete.geocoder.api.here.com/6.2/suggest.json`,{
        params: {
          app_id: APP_ID_HERE,
          app_code: APP_CODE_HERE,
          query,
          maxresults: 1
        }
      });    
      console.log('address:',address);
    } catch (error) {
      console.log('address-error:',error);
    }
```

**Expected behavior**
Return address suggestion:

**Environment:**
```
"dependencies": {
     ....
      "axios": "^0.19.0",
      "react": "^16.8.6",
    ...
 }
```
Hope you can point me to the right direction.
Thanks

**Comment by rfdc** [comment]
I'm getting Error: `Request failed with status code 401` -> AutoComplete is being used on the `Company Address` field -> This is my test url: http://rybwclientwebapp20-20190819141120-hostingbucket-clientwapp.s3-website-ap-southeast-2.amazonaws.com/signup

**Comment by CloudPower97** [comment]
Hey @rfdc, I was having the same issues.
Make sure you are not using any of the `Authorization` headers.
This was the problem for me, and I spent several hours trying to figure this out.
Hope this helps you out!

**Comment by chinesedfan** [comment]
@rfdc If you confirm that axios sends wrong headers, instead of usage problem, feel free to remind me to reopen.
