### ISSUE TITLE
IE 9 XMLHttpRequest don't have property reponse, and only responseText

### ISSUE THREAD

**Issue by sunkeysun** [axios/axios#2390]
**Describe the bug**
response.data always undefined on ie9, because XMLHttpRequest object not have property response

**To Reproduce**
just run axios on ie9 and set responseType to 'json'

```js
var responseData = !config.responseType || config.responseType === 'text' ? request.responseText : request.response;
```
reponseData always undefined on ie9

**Expected behavior**
judge whether request object have reponse property, and set responseData to reponseText if response property not exist

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g.windows7]
 - Browser [e.g. ie9]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.8]

**Comment by zzwfe** [comment]
i also have a trouble with axiso's problem.and the devtools displays "无法获取未定义或 null 引用的属性“code”"

**Comment by chinesedfan** [comment]
It seems to be a problem that the server can't response correctly, instead of an issue of axios. Closed due to lack of enough information.
