### ISSUE TITLE
401 error while sending POST request

### ISSUE THREAD

**Issue by samaysimantbarik** [axios/axios#2392]
Hello Team,

Bug Description: I am trying to generate a token from Stripe. I am able to generate from postman, however, I am getting 401 when trying the same from AXIOS.

**My Code:**
 const onSubmit = async e => {
        e.preventDefault();

        try {
            const config = {
                header: {
                    Content_type: "application/x-www-form-urlencoded"                    
                },
                auth:{
                    username:"pk_test_JuubZR3TKlomGDeBAPWlEEMQ00sQXUAhcW",
                    password:""
                },
            }
            const params = new URLSearchParams();
            params.append('card[number]', 4242424242424242);
            params.append('card[exp_month]', 12);
            params.append('card[exp_year]', 2020);
            params.append('card[cvc]', 123);
        
            let res = await axios.post("https://api.stripe.com/v1/tokens", params, config);
         
            console.log("Token:");
        
        } catch (error) {
            console.log(error);
        }

        console.log("Submitted..")
    }

**Postman:**
![image](https://user-images.githubusercontent.com/44022711/64332099-4ad7e980-d017-11e9-90b7-24d88ac097d4.png)

![image](https://user-images.githubusercontent.com/44022711/64332413-e23d3c80-d017-11e9-9891-70bc27b76c11.png)

**My Code Output**
![image](https://user-images.githubusercontent.com/44022711/64332474-fd0fb100-d017-11e9-839e-bc251070c182.png)

![image](https://user-images.githubusercontent.com/44022711/64332215-7e1a7880-d017-11e9-9ce0-feca8446094f.png)

Note: The key I have published are the test keys available on Stripe website, so there is no issue sharing here publicly.

Kindly help.

**Comment by pavinduLakshan** [comment]
`Content_type` should be `Content-Type`. and you send a token as Authorization header in POSTman but you didn't in axios. The following request will do the job.

``` 
const onSubmit = async e => {
      e.preventDefault();
      try {
        const config = {
            headers: {
                Content-Type: "application/x-www-form-urlencoded"                    
                Authorization: "Basic <token>" 
           }
        }
        const params = new URLSearchParams();
        params.append('card[number]', 4242424242424242);
        params.append('card[exp_month]', 12);
        params.append('card[exp_year]', 2020);
        params.append('card[cvc]', 123);
    
        let res = await axios.post("https://api.stripe.com/v1/tokens", params, config);
    
        } catch (error) {
            console.log(error);
        }
         console.log("Submitted..")
}
```
