### ISSUE TITLE
Axios 0.19.0 issue

### ISSUE THREAD

**Issue by sm2017** [axios/axios#2397]
**Describe the bug**
I have problem with axios 0.19.0 , my code works well with axios 0.18.0 , I think axios 19 has issue with baseUrl  config

**To Reproduce**

https://runkit.com/sm2017/5d748f34dda96b001a60f5d0

```js
var axios = require("axios")

const instance = axios.create({
  baseUrl:'https://github.com/axios',
});

await instance.get('/axios');
```

```
Error: connect ECONNREFUSED 127.0.0.1:80
A stack trace for this error could not be retrieved because stack was already called.
```

**Expected behavior**
It must load axios github page

**Environment:**
 - Axios Version [e.g. 0.18.0] 0.0.19
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4] ,  windows 10
 - Browser [e.g. Chrome, Safari] nodejs
 - Browser Version [e.g. 22] v10.15.3
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0] I test in react native 0.60.5 too

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by sm2017** [comment]
Reply please

**Comment by dingziqi** [comment]
It's a case problem.Use `baseURL`。

**Comment by cesar18pena** [comment]
@sm2017 it is just a typo error, should be:
``` js
const instance = axios.create({
  baseURL:'https://github.com/axios',
});
```
instead of 
``` js
const instance = axios.create({
  baseUrl:'https://github.com/axios',
});
```

**Comment by sm2017** [comment]
@dingziqi , @cesar18pena what do you think about the following codes


```js
var axios = require("axios@0.18.0")

const instance = axios.create({
  baseURL:'https://postman-echo.com/',
  url:'/get',
  params:{
    "foo1": "bar1",
    "foo2": "bar2"
  }
});

const {data} = await instance.request();

console.log(data)
```


```
var axios = require("axios")

const instance = axios.create({
  baseURL:'https://postman-echo.com/',
  url:'/get',
  params:{
    "foo1": "bar1",
    "foo2": "bar2"
  }
});

const {data} = await instance.request();

console.log(data)
```



https://runkit.com/embed/nzbzdjc4auv7/clone works well but https://runkit.com/embed/lro4kcp7w8ir/clone not

**Comment by sm2017** [comment]
Any idea?

**Comment by dingziqi** [comment]
The rule of `merge config` is changed in 0.19.0,(see `https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js`), the `params` in axios is dropped.

**Comment by sm2017** [comment]
So it is a brwaking change

**Comment by yasuf** [comment]
I think I figured out why, there was a change with defaults inside `.request` that makes it so that the default headers aren't set, I'll try to push a PR to fix this whenever I get a chance, relevant lines:

0.18 version https://github.com/axios/axios/blob/face0165de613696d10b1fd2a0e2f7b3852fa018/lib/core/Axios.js#L35

0.19 version
https://github.com/axios/axios/blob/bbfd5b1395699ae6290a01f51e0e1b66897099fd/lib/core/Axios.js#L37

good catch

**Comment by yasuf** [comment]
@sm2017 can you test if the request works with this change? https://github.com/axios/axios/pull/2516

**Comment by chinesedfan** [comment]
Tested with 0.19.1, and it works.
