### ISSUE TITLE
axios.create() is sending unexpected get request to baseURL

### ISSUE THREAD

**Issue by aloiki** [axios/axios#2398]
**Describe the issue**
In my vueJs app I am defining axios as a plugin. I use axios.create() and pass the baseURL for all of my API calls. Axios instance is created and an unexpected GET call is requested to my defined baseURL.

**Example Code**
```js
// plugins/axios.js
import Vue from 'vue';
import axios from 'axios';
/**
 * create our configuartion for axios
 * all requests are defined by axios
 * */
const instance = axios.create({
  baseURL: process.env.swApiBasePath,
  crossDomain: true,
});

export default instance;

// store/action.js for e.g

/** defining here my expected requests*/
import axios from '../plugins/axios';

async fetchPosts({ commit }) {
    const { data } = await axios.get('/posts');

    return commit('SET_POSTS, data);
 },
```

**Expected behavior, if applicable**
The expected behavior would be that only defined GET requests in my actions would be requested by axios but also the defined baseURL in axios.create is called.
Is there any good solution for this behavior? Because I do not want to load the full API response at the initial request.

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.14.5]
 - Browser [all]
 - Additional Library Versions [nuxt ^2.4.0]

**Screenshot:**
![Bildschirmfoto 2019-09-10 um 15 22 42](https://user-images.githubusercontent.com/41948154/64618576-ce5f5500-d3e0-11e9-9610-631c13ec6c5f.png)

**Comment by pavinduLakshan** [comment]
Can you show us the response of the `GET` request?

**Comment by aloiki** [comment]
Sure, my **baseURL** in axios.create() with the unexpected call is like myexample.com/view/api.
I am getting back all data unfiltered for the `GET` request for the baseURL:

```
success: true
data: [
{id: 1, size: {sm: 12, md: 12, lg: 12, xl: 4}, name: "overview", showTitle: false, nested: true,…},
{id: 2, size: {sm: 12, md: 12, lg: 12, xl: 4}, name: "trainingSessions", showTitle: true,…},
{id: 3, size: {sm: 12, md: 12, lg: 6, xl: 4}, name: "factor", showTitle: true,…}
{id: 4, size: {sm: 12, md: 12, lg: 6, xl: 4}, name: "newsFeed", showTitle: true, icon: "newspaper",…}],
```
(and even more data just want to shorten it ;) )

**Comment by estephinson** [comment]
I know an OPTIONS request is fired off when calls are made to an end-point, can you see the type of request it is?

**Comment by sm2017** [comment]
I think it is same as https://github.com/axios/axios/issues/2397#issuecomment-531465583

**Comment by Modulo216** [comment]
I'm seeing the same thing from axios.create().  It seems to be related to manipulating state in the same function that you call create().

**Comment by chinesedfan** [comment]
Closed due to lack of enough information. The provided code example didn't match the screenshot. Sorry, I saw lots of `/view/api` but didn't know which line of codes did that.
