### ISSUE TITLE
how to send data in body with get request

### ISSUE THREAD

**Issue by a641390597** [axios/axios#2400]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
send get request can use data
Get request more consistent with the semantics of getting data,e.g. in elastic search,recommend fetch data by get else not post
**Describe alternatives you've considered**

**Additional context**

**Comment by G07cha** [comment]
It's not possible with current implementation, but even if you could, you really shouldn't do that, here is a great answer on StackOverflow about this - https://stackoverflow.com/a/983458

**Comment by danidre14** [comment]
The only way I send data with a get request is in the parameters.
axios('/user?ID=12345');
or
axios.get('/user', {
    params: {
        ID:12345
    }
});
And access them as req.query.ID in NodeJS

Not sure if I interpreted your question clearly, sorry.

**Comment by G07cha** [comment]
@danidre14 this will append params to URL when @a641390597 asked about appending in body, plus, query params may not be suited for some cases due to their limitiations

**Comment by danidre14** [comment]
Ah, yes I understand.
In that case, I do not believe it is possible to add data to a body when using GET, as he main purpose of POST vs GET, was to make the data being sent private.
