### ISSUE TITLE
Extra colon shows up while doing axios post

### ISSUE THREAD

**Issue by priyankagupta34** [axios/axios#2401]
I am trying to do post using axios in Node.js backend. While 'get' requests are working fine.r. As soon as i try 'post' method, this fails.

Below, i am trying to do a login whose backend in running as well (i have tested it all in postman). 

```
const host = `http://localhost:6800/`;
function loginAdmin(email, password){
    return axios.post(`${host}admin/login`,JSON.stringify({email, password}));
}
```
As soon as this code runs, i find that i am trying to send 
``` {"email":"admin2@always.com","password":"1234"}: ```

![a](https://user-images.githubusercontent.com/28778484/64597923-6440b300-d3d4-11e9-8d90-714f458fba6f.png)

You can see that extra ':' here, which added i don't know how.

Then i checked backend that what exactly i am receiving there, and i found:
```
 { '{"email":"admin2@always.com","password":"1234"}': '' }
```
Which means backend is receiving the data so cors problem does not exist, yet i am not able to understand the reason behind.

**Comment by priyankagupta34** [comment]
However this works:
```
function loginAdmin(email, password) {
    const params = new URLSearchParams();
    params.append('email', email);
    params.append('password', password);
    return axios.post(`${host}admin/login`, params);
}
```
Is it because the request-header contains ? :
`Content-Type: application/x-www-form-urlencoded;charset=UTF-8`

**Comment by pavinduLakshan** [comment]
`JSON.stringify()` expects a JSON ( JavaScript Object ) as argument. In the first you are not providing a valid JavaScript object. But in the second comment, you initialize a variable and set `email` and `password` attributes and give them values which eventually make `params` a JSON like this.

`{"email": your_email, "password": your_password}`

If you want to make the code in the first comment work, try the following.

`
const host = `http://localhost:6800/`;
function loginAdmin(email, password){
    return axios.post(`${host}admin/login`,JSON.stringify({email: email, password: password}));
}
`

**Comment by priyankagupta34** [comment]
I am providing valid javascript only. Latest ECMA script allows you to perform this way that if key and value variable is same in javascript, then we can use it this way. 
`{email: email, password: password}` can be written as `{email, password}`, why don't you give it a shot in browser console :)
However this is not the problem. It has got something to do with `Content-Type: application/x-www-form-urlencoded;charset=UTF-8`, as when i am doing urlendcoding, it then works. Still i don't know what is this problem, am i suppose to continue like this `const params = new URLSearchParams();` or not.

**Comment by pavinduLakshan** [comment]
Thank you for pointing that out. I was not aware of that. Maybe setting `Content-Type: application/json` will solve the issue.

**Comment by SunGuoQiang123** [comment]
if `Content-Type: application/x-www-form-urlencoded;charset=UTF-8` , read the doc  https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format

**Comment by priyankagupta34** [comment]
This URL shared by you is what i used to solve my problem. But i want to use the standard JSON.toString() function instead of `new URLSearchParams();` which i am not able to do. JSON.toString() takes entire data at once while by using  `new URLSearchParams();` I am forced to attach each and every parameter in params in order to get the result which is frustrating.

**Comment by SunGuoQiang123** [comment]
@priyankagupta34  you can use  `qs` library, it can take entire data and convert the data to urlencoded format 
```
const qs = require('qs');
const data = {age: 19, name: 'xxx'};
const params = qs.stringfy(data);
// params = age=19&name=xxx
axios({
params,
url: '/yyy'
})
```

**Comment by priyankagupta34** [comment]
This seems to be a server side problem, which when fixed, it started accepting body data and i did'nt have to use URLENCODED.
