### ISSUE TITLE
is there any way to access loacal html file using axios 

### ISSUE THREAD

**Issue by raghuv9** [axios/axios#2402]
here i'm trying to access a local html file and then creating a component in vue but i'm not getting anything while logging the response in console

 created()
        {
            Vue.component('loaded-content', function(resolve, reject){
                axios.get('userpage/index.html').then(response => {
                    console.log(response);
                    resolve({template: response.data})
                })
               })
           
        },

**Comment by danidre14** [comment]
What is your html? I do not think the html will be able to send a response if that html does not have a way to receive that data. I use axios for routes with NodeJS, so it's easy to handle requests using express, but that is server-side code.

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. Good luck!
