### ISSUE TITLE
can I use more interceptors to handle err

### ISSUE THREAD

**Issue by Z-HNAN** [axios/axios#2408]
**Describe the issue**
I want to handle different err in different interceptor, but only first interceptor work

**Example Code**
response -> handle401 -> hadnle500 -> ....

```js
const instance = axios.create({ ... })

/* only handle 401 */
instance.interceptors.response.use(response => {
  return response
}, err => {
  if (err.response.status === 401) {
    console.log(401)
    // handle 401....
  }
  return err.response
})

/* only handle 500 */
instance.interceptors.response.use(response => {
  return response
}, err => {
  if (err.response.status === 500) {
    console.log(500)
    // handle 500....
  }
  return err.response
})
```

**Expected behavior, if applicable**
if response401: response -> handle401 -x->
if response500: response -> handle401 --> handle500 -x->
...
or, I'm using it incorrectly😲

**Environment:**
 - Axios Version 0.19.0

**Comment by betgar** [comment]
You should **reject the promise** in the error handler.
```javascript
instance.interceptors.response.use(response => {
  return response
}, err => {
  if (err.response.status === 401) {
    console.log(401)
    // handle 401....
  }
  return Promise.reject(err) // reject
})

/* only handle 500 */
instance.interceptors.response.use(response => {
  return response
}, err => {
  if (err.response.status === 500) {
    console.log(500)
    // handle 500....
  }
  return Promise.reject(err) // reject
})

```

**Comment by Alanscut** [comment]
`return err.response` int the first intercepor's err handle block means return successfully, so the program won't enter the next interceptor's error handle block.
As betgar says, you should **reject the promise** in the error handler.
