### ISSUE TITLE
How send an array in DELETE method? 

### ISSUE THREAD

**Issue by iliakut** [axios/axios#2409]
**Describe the issue**
I need to send an array with DELETE method: 
like: 
{
"data": [{ "type": tag", "id": "1" }]
}
instead of an Array axios sends: data[]{ "type": tag", "id": "1" }
axios puts an object outside of an array. 

**Example Code**
```js
DELETE(_empty, { url, data }) {
            return new Promise((resolve, reject) => {
                axios
                    .delete(url, { params: data })
                    .then(resp => {
                        resolve(resp.data);
                    })
                    .catch(resp => {
                        reject(resp);
                    });
            });
        },
```

**Expected behavior, if applicable**
send an Array.

**Environment:**
 - Browser Chrome
 - Browser Version 76

**Comment by avindra** [comment]
```
                    .delete(url, { params: data })
```

Have you instead tried:

```
                    .delete(url, { data })
```

**Comment by iliakut** [comment]
Yes, it's helped
