### ISSUE TITLE
I have an issue in Axios with function on then

### ISSUE THREAD

**Issue by pc-mon** [axios/axios#2411]
I have an issue in Axios with function on then
this is my code 
the issue "this.loans[key].steps.push(r.data);" key is not defined
```
newStepInput: function(key){
        axios.post('api/Finance/Loan/storeStep',{
            'finance_loan_id': this.loans[key].id,
            'amount': this.loans[key].new_step
        }).then((key,r) => {
            console.log(r);
            // TODO here
            // this.loans[key].steps.push(r.data);
            this.$q.notify({
                message: 'Saved',
                color: 'purple'
            })
          });
      },
```

**Comment by cesar18pena** [comment]
@pc-mon you already have a variable called `key` when you declare the `function (key)` could you change your code to something like this:

``` js
newStepInput: function(key){
        axios.post('api/Finance/Loan/storeStep',{
            'finance_loan_id': this.loans[key].id,
            'amount': this.loans[key].new_step
        }).then((keys,r) => {
            console.log(r);
            // TODO here
            this.loans[keys].steps.push(r.data);
            this.$q.notify({
                message: 'Saved',
                color: 'purple'
            })
          });
      },
```
Also, in your `then` where the promise is used, I see you have `key` and `r`, as far as I know, you only get a response object from Axios. Maybe the `key` it inside the data object in the response.

**Comment by pavinduLakshan** [comment]
```js
 newStepInput: function(key){
         axios.post('api/Finance/Loan/storeStep',{
             'finance_loan_id': this.loans[key].id,
             'amount': this.loans[key].new_step
         }).then(response => {
             console.log(response.data.r);
             // TODO here
             this.loans[response.data.key].steps.push(response.data.r.data);
             this.$q.notify({
                 message: 'Saved',
                 color: 'purple'
             })
           });
       },
```

**Comment by pc-mon** [comment]
I'm sorry I tried it a lot but doesn't work

**Comment by pc-mon** [comment]
I just fixed it by
`
newStepInput: function(key){
        axios.post('api/Finance/Loan/storeStep',{
            'finance_loan_id': this.loans[key].id,
            'amount': this.loans[key].new_step
        }).then((r) => {
            console.log(r);
            // TODO here
            if(this.loans[key].steps)
                this.loans[key].steps.push(r.data);
            else{
                this.loans[key].steps = [r.data];
            }
            this.$q.notify({
                message: 'Saved',
                color: 'purple'
            })
          });
      },
`

I just removed key from parameters in method 
thank you guys I love you all
