### ISSUE TITLE
Add Support for Observable (as opposed to Promise)

### ISSUE THREAD

**Issue by zhaosiyang** [axios/axios#2412]
**Feature Description**
Axios is currently promise based library. It would be great that if it also support observable.
Two great benefits of using observables:
1. leveraging rxjs operator
2. cancel http request through `unsubscribe` (as opposed to cancel token)

**Existing Solutions**
I have implemented a library `axios-observable`(https://www.npmjs.com/package/axios-observable). It's basically a thin wrapper around `axios` with almost the same API as `axios`.
It also enables cancelling http request through unsubscribe - a more straightforward way than using cancel token.

**Proposals**
I am thinking if we can incorporate `axios-observable` into `axios` to make observable officially supported. If you guys are very positive about this idea, I will be very happy to make an PR.

Happy to discuss.

**Comment by yasuf** [comment]
Interesting idea and concept. To be completely honest, I don't see axios implementing observables in the short run at least, your library seems pretty cool and I think the best way for us to move forward is with separate libraries to keep each one small and let developers decide which pattern to follow.

Open to other ideas, these are just my first impressions, I'll let others share their opinions as well

**Comment by stavalfi** [comment]
support for observables will do great to this library.

**Comment by JWess** [comment]
I just moved from Angular to React. My React mentor recommended that I use Axios. Due to my Angular background, I know the power of RxJS and would love Axios support for Observables!

**Comment by jasonsaayman** [comment]
HI,

Thanks for submitting this I don't think that this is something that Axios will implement any time soon.

Thanks

**Comment by breezefeng** [comment]
This is my solution，github url is : https://github.com/breezefeng/axios-for-observable.
The Api is same as axios, axios returned Promise, then axios-for-observable returned Observable.
