### ISSUE TITLE
Handle response headers to avoid HPE_INVALID_HEADER_TOKEN in Node 12

### ISSUE THREAD

**Issue by micksatana** [axios/axios#2415]
First of all, I put this in Feature Request because I believe it's not Axios bug. However, it would be nice, if Axios may be able to help handling this issue. As it related to Node.js 12 strict behavior, Axios users may not have able to fix the external servers/API services.

**The current problem**
When sending a request and get malformed headers, Axios will throw an error `HPE_INVALID_HEADER_TOKEN` code with `Invalid header value char` reason. This only happen in Node.js 12. If I downgrade to Node 10, it will works.

**Similar issue**
From what I searched around, I've found similar issue.
https://www.gitmemory.com/issue/nodejs/node/27711/494019298

So it might be after getting back the response headers it will throw the error on Node.js 12 if the response headers is malformed.

**To Reproduce**
Create the following script in Node.js 12.6.0 and run
```
Axios.get('https://apigw1.bot.or.th/bot/public/Stat-ExchangeRate/v2/DAILY_AVG_EXG_RATE/', {
  params: {
    start_period: '2019-09-15',
    end_period: '2019-09-15',
    currency: 'EUR'
  },
  headers: {
    'X-IBM-Client-Id': 'xxxxxxxxxxxxx'
  }
});
```
**Expected behavior**
If sent with correct client id, expected behavior is to response with 200

**Current behavior**
Always throw `Invalid header value char` error. 

**Possible feature to fix the problem**
In Node 12, Axios parse the response headers the same way Node 10 or 11 doing instead.

**Alternative solution**
Allow some hook function to handle response headers for developers to parse the headers before Axios does, so we can do the fix ourselves.

**Environment:**
 - Axios Version: 0.19.0
 - OS: OSX 10.14.6
 - Node.js: **12.6.0**

**Comment by mwood23** [comment]
This appears to be an issue in Node 12. Relevant thread here: https://github.com/nodejs/node/issues/27711
