### ISSUE TITLE
Getting local files (file://) fail after upgrading from 0.18.0 to 0.19.0

### ISSUE THREAD

**Issue by firstfeb** [axios/axios#2416]
**Describe the bug**
When using axios to get a local file (`file://...`) I get status code 0 as if there's a CORS issue. This didn't happen using version 0.18.0 so I assume that this is a bug?

**To Reproduce**
Get a local file. In my case I wanted to get a PDF as an array buffer.

```js
axios("file://...", {
    responseType: 'arraybuffer'
    headers: {
        Accept: 'application/pdf'
    }
}).then(..)
```

**Expected behavior**
Just like in version 0.18.0 version I should get a 200 response.

**Environment:**
 - Axios Version 0.19.0
 - OS: Windows 10
 - Browser: EO Webbrowser (Chromium)
 - Browser Version: 19.1.95 (Chromium ~70)
 - Additional Library Versions:  React 16.8.6

**Additional context/Screenshots**
Need to build and run index.html locally so you're making the request from file:// as well.

**Comment by Alanscut** [comment]
The success status code of the file:// protocol is 0, and the default success status code of axios is 200~300. You can customize the validateStatus function to change the success status code to access the local file.
```js
validateStatus: function (status) {
    return status ===0 || (status >= 200 && status < 300); 
  }
```
