### ISSUE TITLE
Axios continues making OPTION requests when the server is unreachable

### ISSUE THREAD

**Issue by domcorvasce** [axios/axios#2417]
**Describe the issue**

Whenever the server that I am trying to connect to is **down**, and CORS is enabled, **axios** continues to send OPTION requests.

**Example Code**

```js
  return new Promise((resolve, reject) => {
    axios({
      method: 'get',
      url: `${apiUrl}/challenges`,
      headers: customHeaders,
    })
      .then((response) => {
        const { data } = response;
        resolve(data);
      })
      .catch((error) => reject(error));
  });
```

**Expected behavior, if applicable**

I should be able to catch the error, and manage it. Currently, I can only catch errors from the main request (GET, POST, etc...).

**Environment:**
 - Axios Version: 0.19
 - OS: macOS Mojave
 - Browser: Brave
 - Browser Version: 0.68.132

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![Schermata 2019-09-17 alle 16 45 57](https://user-images.githubusercontent.com/20912806/65052763-3aa30100-d96b-11e9-8d7b-f9b183cb1218.png)

**Comment by rohankulshreshtha** [comment]
It is not a library issue exactly. You can do a little tuning to the backend server to make it work.

A browser sends an OPTIONS request before a GET request, essentially to check with the server that it's allowed to send the GET request.

You need a method in your server that catches OPTIONS requests, and responds with the correct headers (you need to make sure Access-Control-Allow-Methods is sent). If the right answer comes back (200), the browser follows up by sending the GET request.

You can refer to a similar issue #1473. Hope it helps.

**Comment by domcorvasce** [comment]
@rohankulshreshtha it happens when the server is down, so there is no way to manage it via the server itself.
