### ISSUE TITLE
Axios Cancel - is it immediate?

### ISSUE THREAD

**Issue by zfrisch** [axios/axios#2418]
**Describe the issue**
I've been looking over the Axios library. I really enjoy it but the cancellation of requests seemed a little bit verbose for what it was trying to accomplish. 

I browsed the code from there, and now I can understand why the cancellation add-ons were written the way they were.  Since Axios should return a Promise there isn't any way to provide the cancelToken object back without having to play with a kind-of "context injection".  

While looking over the code in [dispatchRequest](https://github.com/axios/axios/blob/master/lib/core/dispatchRequest.js)  I was a bit surprised because it seems like `cancel` is only looked for when the request is **made**, when the xhr or http  request **resolves** or when the request **fails** - and then at _that point_ the actual request is cancelled. I may have misread or misunderstood but I don't see where it would continuously check for the token being set?

This leads to my question:

_Is the actual request **cancelled** when calling the `cancel` method on the `cancelToken`, or does it only setup a flag to be checked at the resolution of the initial request ?_

**Comment by rohankulshreshtha** [comment]
@zfrisch Yes Axios Cancel is immediate.

If the request has already been sent to the server then the server will process the request even if we abort the request but the client will not wait for/handle the response.

As soon as you call the `cancel` method , `onAdapterRejection` is immediatelhy called from [dispatchRequest](https://github.com/axios/axios/blob/master/lib/core/dispatchRequest.js) and the request is aborted.

Check the following code snippet from [http.js](https://github.com/axios/axios/blob/master/lib/adapters/http.js) where cancellation is handled.

```
if (config.cancelToken) {
      // Handle cancellation
      config.cancelToken.promise.then(function onCanceled(cancel) {
        if (req.aborted) return;

        req.abort();
        reject(cancel);
      });
 }
```

**Comment by zfrisch** [comment]
> @zfrisch Yes Axios Cancel is immediate.
> 
> If the request has already been sent to the server then the server will process the request even if we abort the request but the client will not wait for/handle the response.
> 
> As soon as you call the `cancel` method , `onAdapterRejection` is immediately called from [dispatchRequest](https://github.com/axios/axios/blob/master/lib/core/dispatchRequest.js) and the request is aborted.
> 
> Check the following code snippet from [http.js](https://github.com/axios/axios/blob/master/lib/adapters/http.js) where cancellation is handled.
> 
> ```
> if (config.cancelToken) {
>       // Handle cancellation
>       config.cancelToken.promise.then(function onCanceled(cancel) {
>         if (req.aborted) return;
> 
>         req.abort();
>         reject(cancel);
>       });
>  }
> ```

Excellent! Thanks for your response!

**Comment by josephpung** [comment]
@zfrisch if this has been resolved, please close the issue, thank you!
