### ISSUE TITLE
Axios sends authorization header on preflight requests when using basic auth

### ISSUE THREAD

**Issue by micbra** [axios/axios#2420]
When I try to get data from a 3rd party API with authentication via basic auth, axios adds an `Authorization` Header to the preflights `OPTIONS` Request.
As the [fetch spec](https://fetch.spec.whatwg.org/#http-responses) clearly states, any credentials should be omitted from preflight requests.

I don't have access to the server because the API is a 3rd party one, so adding `Access-Control-Allow-Headers: Authorization` is neither an option nor should it be necessary for preflight requests.

```js
async function getData() {
  await axios.get( 'https://example.com', {
    auth: {
      user: 'username',
      password: 'password'
    }
  })
}
```

Response from Server
```
Access to XMLHttpRequest at 'https://example.com' from origin 'https://localhost' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Expected behavior**
Omitting the `Authorization` header from all preflight requests

**Environment:**
 - Axios Version 0.19.0
 - OS: OSX 10.14.6
 - Browser: Chrome
 - Browser Version: 76.0.3809.132

**Comment by pavinduLakshan** [comment]
See if #1835 helps

**Comment by micbra** [comment]
Hi @pavinduLakshan, this issue doesn't provide a solution to my problem, since allowing the header on server side is not an option.

**Comment by farisT** [comment]
Hi @micbra, maybe this could help? https://github.com/axios/axios/issues/382#issuecomment-281309372 :)

**Comment by micbra** [comment]
Hi @farisT, unfortunately this didn't help because even if I remove the `Authorization` header before doing the request, it's getting re-added by axios through the `auth` option.
For the `GET` request this is expected behavior since I must authorize against the API, but for the `OPTIONS` preflight this is unnecessary (even more wrong!)

**Comment by farisT** [comment]
Ah ok, maybe you can try axios.create and have a custom config where you can add your own custom headers and settings.

```
const instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
});
```

**Comment by micbra** [comment]
No, this is still not working as my problem is not caused by misconfiguration of axios. But I figured out that even the `fetch()`implementation works the same and it must be a problem with the API vendor.
I will get in touch with the owner and ask him to allow the `Authorization` header on preflight requests.

**Comment by federicovezzoli** [comment]
I have the same problem, can't find a solution.
Axios send the credentials in the preflight call, when it shouldn't, is there someway to avoid it? 
I cannot make any rest api modification, it's not my code.

thanks
