### ISSUE TITLE
can't customeize defaults; example: axios.defaults.retry = 4; retry is undefined

### ISSUE THREAD

**Issue by webpig** [axios/axios#2425]
show the code:
```js
axios.defaults.retry = 4;

axios.interceptors.response.use(undefined, (err) => {
  console.log(err.config)
});
```
result: 

![image](https://user-images.githubusercontent.com/24989439/65499868-e8288e00-def0-11e9-8071-1dffdc10b84e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/24989439/65500182-7a309680-def1-11e9-8cac-f1edd736fca9.png)

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.12.6]
 - Browser [Chrome]
 - Browser Version [77.0.3865.90]

**Comment by 7Flow** [comment]
Duplicate of #2203 
In version 0.19, axios remove config properties that aren't part of the lib default config, so you can't add your own custom properties anymore. Rollback to 0.18.x.

**Comment by webpig** [comment]
Thinks! But I don't understand why removed; Now we can use 0.18.x, but after, how to do it?

**Comment by 7Flow** [comment]
A lot of plugins (like axios-retry) needs custom config, so I'm confident that there will be a release that fix this soon. But I don't know the objective and purpose of the change, neither if a fix will be release in the next days or the next month.

**Comment by webpig** [comment]
OK! Thanks! Just waiting for that.
