### ISSUE TITLE
Add the version of axios to the axios object.

### ISSUE THREAD

**Issue by matthewdordal** [axios/axios#2428]
**Is your feature request related to a problem? Please describe.**
I do not know of a fast way to determine which version of axios I am using when it is provided by another dependency.

**Describe the solution you'd like**
Add the version of axios to the axios object.

**Describe alternatives you've considered**
The alternative is to search the node_modules directory and hope that there is not competing versions of axios from different dependencies.

**Additional context**

**Comment by yasuf** [comment]
I guess we could add the version to the axios object, not sure how common that is in other libraries, at the same time I don't want to bloat this library if it's not necessary to do this since axios is meant to be a lightweight http client

**Comment by yasuf** [comment]
do you have an example of another library that does this?

**Comment by matthewdordal** [comment]
@yasuf I discovered a feature in npm that helped me achieve what I needed. `npm ls axios` helped me solve my problem. [React does do this though](https://github.com/facebook/react/blob/master/packages/react/src/React.js#L105) and it can be helpful when it is unclear which version is being added due to unfamiliarity with a projects build

**Comment by Alanscut** [comment]
fixed by #2520
