### ISSUE TITLE
307 redirect is not followed in browser

### ISSUE THREAD

**Issue by C-Higgins** [axios/axios#2429]
I make a POST request to endpoint A. It responds with 307 and the endpoint B in the Location header. The promise is rejected with message "Network Error" and response undefined. Nothing else happens; no further request is made to endpoint B.

All seems to work fine if endpoint A responds with 301, or if I make the request with native Fetch.

**Comment by yasuf** [comment]
Can you elaborate? Is there a way to reproduce this isssue? Which version of axios are you using? What happens on the endpoints? Why are there 2 endpoints?

**Comment by C-Higgins** [comment]
Latest version.
Have an endpoint respond with 307. The correct behavior is that the browser should resend the request to the URL specified in the response's Location header. This is the same behavior as 301, which works correctly. However, when using Axios, the 307 behavior is simply handled as an error, not as a redirect. I have tested this with Axios, Fetch, and XMLHTTPRequest. Axios is the only one where the request is not repeated in the case of 307.

**Comment by gnarea** [comment]
Neither 307 or 308 seem to be supported indeed, although I don't get a Network Error. I'm working around this by using `maxRedirects: 0` and doing the retry myself when an exception is thrown because the status code was 307:

```js
> axios.get('https://httpstat.us/307').then(r => console.log('Success', r.status)).catch(e => console.log('Failure', e.response.status))
Promise { <pending> }
> Success 200

> axios.get('https://httpstat.us/307', {maxRedirects: 0}).then(r => console.log('Success', r.status)).catch(e => console.log('Failure', e.response.status))
Promise { <pending> }
> Failure 307
```

**Comment by chinesedfan** [comment]
@C-Higgins For errors, make sure you have allowed 3xx in `config.validateStatus`. And better to provide a reproducible sample like @gnarea.

@gnarea This issue is discussing requests in browser. But `maxRedirects` only works in Node.js. Please open a new issue if you met similar problem.

**Comment by determin1st** [comment]
Manual redirects dont work with browser's fetch api.
Spec writers screwed this bolt because of "security reasons".

It worked for some time with http status 300,
but now, in newer browsers it spits opaque (unreadable) response.

Auto-redirects will work but apis dont have a control over it.
So it's non-fixable at this level (browser's xhr/fetch).

**Comment by chinesedfan** [comment]
Tested with @gnarea's sample in Chrome 80 and worked as expected. Closed first and feel free to remind me if there has something requires axios to change.
