### ISSUE TITLE
Aborted Request

### ISSUE THREAD

**Issue by niallmc** [axios/axios#2430]
**Summary**
Axios is aborting my requests on mobile. Axios gives me the following error: 

```
Uncaught (in promise) Error: Request aborted
```

**Example Code**
I apply an authorization header to Axios as follows:

```js
axios.defaults.baseURL = API_ENDPOINT;

axios.interceptors.request.use(async req => {
  req.headers["Authorization"] = `Bearer ${await getTokenSilently()}`;
  return req;
});

getTokenSilently = async () => {
  // returns access token
}

axios.get('/example');
```

**Expected behavior, if applicable**
I expect that the requests are called successfully.

**Environment:**
 - Axios Version 0.19.0
 - OS: Android 
 - Browser Chrome
 - Browser Version 77.0.3865
 - Additional Library Versions React 16.7

**Additional Context**
I have a React app that uses Axios to make requests. When I access the app from a desktop browser it works correctly but if I access it from an Android device or through React-Native via a WebView it will not make any successful requests and the error will occur.

**Comment by laurohen** [comment]
I have the same problem. Got a solution?

**Comment by mssct-1999** [comment]
Same problem for me too...
