### ISSUE TITLE
Need two responseTypes: One for success and one for error

### ISSUE THREAD

**Issue by TorRanfelt** [axios/axios#2434]
Right now responseType = "arraybuffer" means that the response data is an ArrayBuffer whether the request succeeded or not, but in case of failure the response type probably needs to be text or json for the error message.

**Comment by fr-ser** [comment]
I also experience this issue and simply converting the Arraybuffer response does not result in a usable string for me...

**Comment by fr-ser** [comment]
I guess those issues are all connected:
https://github.com/axios/axios/issues/1500
https://github.com/axios/axios/issues/1439
https://github.com/axios/axios/issues/1392

**Comment by TorRanfelt** [comment]
@fr-ser Kotlin code but I hacked my way around it like this:

            ```
            // We are inside a function that handle error-responses.
            @Suppress("UNCHECKED_CAST_TO_EXTERNAL_INTERFACE")
            val response = error.asDynamic().response as AxiosResponse<*>

            val responseBodyStr: String =
                when (response.config.responseType) {
                    "text" -> {
                        response.data as String
                    }
                    "blob" -> {
                        blob2String(response.data as Blob).await()
                    }
                    else -> {
                        throw IllegalArgumentException(
                            "Response-type must be 'text' or 'blob' for debugging to work " +
                                    "but was '${response.config.responseType}'"
                        )
                    }
                }
```

```
    private fun blob2String(requestData: Blob): Promise<String> {
        return Promise { resolve, reject ->
            val fileReader = FileReader()

            fileReader.onerror = {
                fileReader.abort()
                reject(Error("Problem parsing request blob."))
            }
            fileReader.onload = {
                resolve(fileReader.result as String)
            }

            fileReader.readAsText(requestData, "UTF-8")
        }
    }
```

**Comment by pitops** [comment]
any news on this?

**Comment by chenjianjx** [comment]
+1

**Comment by manmanbuyfed** [comment]
same issues.
want blob and json

**Comment by h0jeZvgoxFepBQ2C** [comment]
@jasonsaayman why was this closed, this is still needed?

**Comment by ZiperRom1** [comment]
Same problem here.

```typescript
const loadImage = async (windowsName: string) => {
    try {
        const response = await axios.get("/screenshot", {
            params: {
                windows_name: windowsName
            },
            responseType: 'arraybuffer'
        });

        const imageData = btoa(
            new Uint8Array(response.data).reduce((data, byte) => data + String.fromCharCode(byte), '')
        );

        const image = imgPreviewRef.value as HTMLImageElement;

        image.src = `data:image/jpeg;base64,${imageData}`;
    } catch (error) {
        // response.config.responseType = 'plainText';
        console.log('error', error);
    }
}
```

Why can't we define the `responseType` dynamicaly ?

I will have to convert `arrayBuffer` to plain text to use the response string ...

**Comment by nycgavin** [comment]
why is this an issue in 2024?

**Comment by nycgavin** [comment]
I was able to get different response types by following this post:

https://medium.com/@fakiolinho/handle-blobs-requests-with-axios-the-right-way-bb905bdb1c04

`
 try {
    const response = await axios.post<Blob>(
      `pdf-reports`,
      parameterValues,
      { responseType: 'blob' },
    );
    //Open the URL on new Window
    window.open(URL.createObjectURL(response.data));
  } catch (error) {
    await throwErrorResponseInJson(error);
  }

export const throwErrorResponseInJson = async (
  error: unknown,
): Promise<void> => {
  if (axios.isAxiosError(error) && error.response) {
    error.response.data = JSON.parse(await fileReader(error.response.data));
  }
  throw error; //rethrow the error in json format
};

export const fileReader = (file: any): Promise<string> => {
  const fileReader = new FileReader();

  return new Promise((resolve, reject) => {
    fileReader.onerror = () => {
      fileReader.abort();
      reject(new Error('Problem parsing file'));
    };

    fileReader.onload = () => {
      resolve(fileReader.result as string);
    };

    fileReader.readAsText(file);
  });
};
`
