### ISSUE TITLE
Support for custom attributes

### ISSUE THREAD

**Issue by songyuanlu** [axios/axios#2438]
Support for custom attributes

I want to set a custom property.
  {
showLoading: true,
isFilter: false
}
Use these attributes to do public interception.
If it shows loading
Whether to intercept the exception

**Comment by xsteadybcgo** [comment]
in v0.18.0, it works well , but in v0.19.0 fail， i search the source code and git commit history. find that this repo had a refactor about deepMerge and ony these configs are supported. 
I wonder if it's a bug or limit ?
![image](https://user-images.githubusercontent.com/19681921/65844015-0b2ac600-e367-11e9-96ef-03eef0246ebd.png)

**Comment by songyuanlu** [comment]
I think it's a limit.
Because in business, I can't set custom properties anymore.
So many things can't be done.
I'll try to see if v0.18.0 is OK.

**Comment by Drider** [comment]
@songyuanlu I think here #2295 you can find additional information.

**Comment by xiaoyouyu** [comment]
the axios.get can't set custom properties in v0.18.0
  
![1570042146(1)](https://user-images.githubusercontent.com/23133668/66072834-6a1b5580-e588-11e9-899f-8cae3e034357.jpg)
![1570042146](https://user-images.githubusercontent.com/23133668/66072835-6ab3ec00-e588-11e9-88b8-4c05c63f92b0.jpg)

**Comment by songyuanlu** [comment]
> @songyuanlu I think here #2295 you can find additional information.

Well
It helps me.

**Comment by yasuf** [comment]
So I just tested this on master and it has been fixed already, it's just that the `dist` hasn't been updated, so we'll probably just have to update it and bump the version on NPM.
See https://github.com/axios/axios/pull/2502

**Comment by emilyemorehouse** [comment]
This has been fixed in the recent 0.19.1 release
