### ISSUE TITLE
axios network error in react native when run in android 9

### ISSUE THREAD

**Issue by pravin-maan** [axios/axios#2439]
this error on devices redmi note 7 $ honor 9n    

im also use this code

AndroidManifest.xml
<application ...
      android:usesCleartextTraffic="true"
/>

 axios({
            method: 'POST',
            url: "https:/...com/api/forgot_password",
            data: {id:1},
            config: {
                headers: {  
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Accept": "application/json"
                     }
            }
        }).then((response) => {})
       .catch((error) => {
           error is   Network error
  })

**Environment:**
 - Axios Version   ["^0.19.0",]
 - OS: [android 9.0]
 - Additional Library Versions [ React 16.8.6, React Native 0.60.4.]

**Comment by Adizbek** [comment]
Can you provide some information about error ?

**Comment by luco** [comment]
Getting this as well. Sometimes it throws a Network Error. Happens in Android 8 & 9

**Comment by manhthepixta** [comment]
Me same. Not working on android 8.
If I turn on Network inspector in Debugger then it works.
So any workaround for this?

**Comment by pravin-maan** [comment]
thanks all it's working 
the error is generated by my server

**Comment by KBiswas98** [comment]
1. change from **localhost** to your **ip**
2. add **http://** 

http://192.168.43.49:3000/user/

**Comment by Vitorjpr** [comment]
> 1. change from **localhost** to your **ip**
> 2. add **http://**
> 
> http://192.168.43.49:3000/user/

I have changed to my IP Address, but not yet works :c

**Comment by PritishSawant** [comment]
Has anybody figured out solution to this problem?
