### ISSUE TITLE
window is not defined (aws lambda)

### ISSUE THREAD

**Issue by tj** [axios/axios#244]
It would be awesome to great to use `this` instead of window so Axios can be used in AWS Lambda via Browserify

**Comment by psulek** [comment]
Same issue but for usage in mocha unit tests

**Comment by rubennorte** [comment]
AFAIK axios will detect as Node.js any environment without `window` so it should work fine in AWS Lambda. If it doesn't maybe it's for some other reason. Could you check?

**Comment by TylorShin** [comment]
Nice idea.

In my case, I should have turned on the { target: "node" } option at Webpack config.
I guess Browserify has the same option too.

**Comment by chinesedfan** [comment]
> I should have turned on the { target: "node" } option at Webpack config.

Yes, make sure your bundle tools are config correctly. axios supports to be used in both the browser and the server side.
