### ISSUE TITLE
request with DNS SRV

### ISSUE THREAD

**Issue by SrTristao** [axios/axios#2441]
Hello Guys,

I need to send request with dns srv in my AWS ECS, but axios dont understand service discovery endpoint (DNS SRV).

I tried with command dig srv {dns srv} and worked. 

I searched this page https://containersonaws.com/architecture/private-service-discovery/ and in this page The writter use 2 libs (service-agent and request).

My question is: Axios accept request with DNS SRV?

Att,
Tristão

**Comment by contactyash** [comment]
your can provide a custom SRV compatible httpAgent in axios configs like serve-agent.
try this and close the issue if it helps.
