### ISSUE TITLE
Setting axios base url dynamically

### ISSUE THREAD

**Issue by RameshAmzur** [axios/axios#2448]
i am getting base url from asyncstorage and i want to set it as base url for axios instance.

currently iam following below code but it is not working

```
const axiosInstance = axios.create({
 // baseURL: API_END_POINTS.BASE_URL+AsyncStorage.getItem('dealerNo'),
});
axiosInstance.defaults.timeout = 10000000;
axiosInstance.interceptors.request.use(
  async config => {
axiosInstance.defaults.baseURL=await getBaseUrl();
    return config;
  },
  error => Promise.reject(error)
);

  export async  function getBaseUrl() {
    var No = await AsyncStorage.getItem('dealerNo')
    var value =API_END_POINTS.BASE_URL+  No;
    return value;
  }


axiosInstance.defaults.headers.post['Content-Type'] = 'application/json';
export default axiosInstance;

```
iam importing the above axiosInstance to make get or post calls.

**Comment by contactyash** [comment]
do like this 
`js
axiosInstance.interceptors.request.use(
  async config => {
    config.baseURL=await getBaseUrl();
    return config;
  },
  error => Promise.reject(error)
);
`

and please close the issue.

**Comment by HelioSilva** [comment]
@contactyash  Perfect!  I had the same problem and it worked normally.

**Comment by yasuf** [comment]
Closing, issue has been resolved!

**Comment by gautam-patadiya** [comment]
@contactyash You saves my day! Thanks A lot
