### ISSUE TITLE
Error: status code 501 when using proxy

### ISSUE THREAD

**Issue by Jasoonkuah** [axios/axios#2452]
I'm using axios 0.19, just a simple axios request with proxy
<pre>axios.get('[URL]', {
proxy:{
    host: 'HOST',
    port: 3128,
    auth: {
        username: '[USERNAME]',
        password: '[PASSWORD]'
    }    
}})</pre>

and get this error
<pre>{
    "error": {
        "message": "Request failed with status code 501",
        "name": "Error",
        "stack": "Error: Request failed with status code 501\n    at createError (/srv/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/srv/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/srv/node_modules/axios/lib/adapters/http.js:237:11)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)",
        "config": {
            "url": "[TARGET_URL]",
            "method": "get",
            "headers": {
                "Accept": "application/json, text/plain, */*",
                "User-Agent": "axios/0.19.0",
                "host": "[TARGET_URL]",
                "Proxy-Authorization": "[SENSITIVE]"
            },
            "proxy": {
                "host": "[PROXY_HOST]",
                "port": 3128,
                "auth": {
                    "username": "[PROXY_USERNAME]",
                    "password": "[PROXY_PASSWORD]"
                }
            },
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1
        }
    }
}</pre>

proxy I'm used is live and tested with no problem, but not work in axios

**Comment by yasuf** [comment]
That seems like a server error since it's in the 500s, where either the proxy server or the final server of the request is returning an error (betting on the final server). This seems outside of the scope of the library but I'd recommend testing with another library (https://github.com/request/request) and see if you still get the same error, if so, there's something wrong with the server, otherwise we can start investigating if the proxy configuration of axios isn't working.

**Comment by BannerBomb** [comment]
I would like to say, I also keep getting a 501 when using a proxy. But with the same proxy when I use it with unirest it works perfectly fine.

**Comment by chinesedfan** [comment]
Closed due to have been stale for a period of time. Users can locate problem reasons as @yasuf recommended.
