### ISSUE TITLE
how can retrive multer errors with axios when uploading an image? when I console.log(res.respnonse) in the catch block the result does not contain any errors  

### ISSUE THREAD

**Issue by seif1000** [axios/axios#2454]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yasuf** [comment]
@seif1000 would you mind closing this issue or adding the appropriate context to it?

**Comment by yasuf** [comment]
I just saw your description is in the title, can you provide a code example of this? It's easier that way for me to see what you're trying to accomplish
