### ISSUE TITLE
How to request anonymously via Axios?

### ISSUE THREAD

**Issue by geongeorge** [axios/axios#2455]
I want to send a GET request to a url via axios.

It seems the website can recognize me via cookies and is redirecting the url to a page where logged in users are moved to.

**I want to send a request as if I were doing it from an incognito tab**

I have tried using `withCredentials: false` config.

This does not seem to have any effect with `true` or `false` in my case.

```js
 axios({
        url : url,
        method: 'get',
        maxRedirects: 15,
        headers: {
          'Content-Type': 'text/html',
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods':'GET',
        },
        withCredentials: false, // without cookies so no login
      })
      .then((res) => {
         console.log("Response", res.data)
      })
      .catch((err) => {
         console.log("Error with fetch: ", err)
      })
    });

```

- Axios version: 0.19.0
- Environment: Browser

**Comment by geongeorge** [comment]
I just tried to do the same with fetch and
I got the perfect output without previous cookies or login
```js
fetch(url, { 
        credentials: 'omit',
      }).then((response)=>{
        return response.text();
      }).then((data)=>{
        console.log(data);
      }).catch(err=>{
        console.log(err);
      })
```


is `credentials: 'omit',` same as `withCredentials: false` in axios?
if not how can I achieve the same?

**Comment by Alanscut** [comment]
hi @geongeorge , the `credentials: 'omit` is same as `withCredentials: false ` indeed. And I have tested your case in my server, when I set `withCredentials` to `false` or omit it, the cross-domain request does not carry the cookie. And if I set `withCredentials` to `true`, then the server will get the cookie. Could you provide more infomation?

BTW, when I set the headers same as you in front-end, the program will report an error:
```
Access to XMLHttpRequest at 'http://localhost:3002/api/addWithCredentials' from origin 'http://localhost:3001' has been blocked by CORS policy
```

so I remove it and set the headers in backend like this:
```
"Access-Control-Allow-Origin": "http://localhost:3001",
"Access-Control-Allow-Credentials": true,
"Access-Control-Allow-Methods": "GET",
"Access-Control-Allow-Headers": "Content-Type"
```

**Comment by geongeorge** [comment]
Forget the headers part. `withCredentials` was not working for me. 
I tried several times and the page data returned seems to be as if I had logged into the website. I guess the cookies were passed.

Fetch seemed to work out of the box with `credentials: 'omit'` property

**Comment by Alanscut** [comment]
@geongeorge Are you using axios with React, #1852 may solve your problem.

**Comment by geongeorge** [comment]
> @geongeorge Are you using axios with React, #1852 may solve your problem.

I was using this with nuxt js (vue)

**Comment by Doogiemuc** [comment]
Had the same problem and found out something new:
Axios seems to **always** add the "Cookie" header when the request goes to the same origin. But it does **not** automatically add the "Cookie" header when you do a valid CORS request.

Which is strange.  And yes the withCredentials configuration variable doesn't seem to have any effect on this at all.

**Comment by maciej-trebacz** [comment]
Bumping this, since I'm observing the same problem @Doogiemuc mentioned - same origin requests ignore `withCredentials` flag. When I used plain `fetch(url, {credentials: 'omit'})` it correctly sent a request without cookies.

**Comment by rdebeasi** [comment]
It sounds like this problem may be a limitation of [XMLHttpRequest.withCredentials property](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials). 

The Axios readme implies that this feature only works cross-site:

```js
// `withCredentials` indicates whether or not cross-site Access-Control requests
// should be made using credentials
withCredentials: false, // default
```

Would it be worth updating the docs to make this limitation clearer and/or throwing a warning when this feature is used outside of a cross-site request?

(Also, thanks to @hetzbr for the heads-up on this issue! 😄 )

**Comment by juliofalbo** [comment]
Any news about it? Having the same issue.

**Comment by forefy** [comment]
Any solution? experiencing the same issue under a nuxt project

**Comment by Gacmat** [comment]
Still nothing? :c
I have the same issue. When my ReactApp tries to `axios.post(url, data, { withCredentials:true})` my Express.js backend won't send Cookie with Token back to React. 
Funny thing is that everything is working good, and token is generated and i have it in response, but i really want a cookie :c

**Comment by akvashi24** [comment]
This seems to be working as expected for me.

```
const api = Axios.create()

api.defaults.xsrfCookieName =
  process.env.VUE_APP_CSRF_COOKIE_NAME || 'csrftoken'
api.defaults.xsrfHeaderName = 'X-CSRFToken'
api.defaults.withCredentials = true // most requests need auth

api.get(url, { withCredentials: false }) // no CORS issues
```
axios version: 0.21.1

**Comment by mamsoudi** [comment]
Any updates on the issue, I'm in the same situation, and it's quite annoying, because fetch worked perfectly. We have two applications under the same origin, which one uses JWT and the other authenticates using `Cookies`, and we don't want to include Cookies in the one with JWT but it just simply doesn't work.

**Comment by creinelt** [comment]
It doesn't work for me either with the current version (0.27.2).
I don't want any cookies to be sent, but that doesn't seem to be possible at all.

**Comment by Arandolph543** [comment]
Axios is tricky but I have solved this problem in the large code bases. There is a best way that solves it but needs then a network protocols security system usually for the application AJAX to avoid DoD problems but if you are familiar with SOAP or REST API's it's like these. What you do is write a service call to customers created index in the DOM it will see it as a null cookie. This is then sessioned in to the Axios API call in pattern is decorated (I've also had an engineer propagate this although not safe for end to end testing trying to reference MVC which takes really steep math proofs to get truthful in making that simplified into that pattern form.) It's a matter of getting a simple model around to view both your active object while maintaining a connection to the network session, foreboding http protocol standards and setting the flags also will work but the relationships to provocation of issues in your network exponentially increases.

**Comment by rin4ik** [comment]
@creinelt @eduardotrzan @mamsoudi @maciej-trebacz guys did you find any solution to this problem ????

Experiencing the same problem and cant fix it for long time 😔
**withCredentials: false** doesn't help on the same domain

**Comment by geongeorge** [comment]
> @geongeorge @creinelt @eduardotrzan @mamsoudi @maciej-trebacz guys did you find any solution to this problem ????
> 
> Experiencing the same problem and cant fix it for long time 😔
> **withCredentials: false** doesn't help on the same domain

I think I used fetch instead of axios at the time to solve this.

**Comment by kyranjamie** [comment]
Noticing same problem. No way to remove cookies in a request. You can't delete cookies, override header, to `withCredentials:false`.

**Comment by rafaelgramoschi** [comment]
I want to remove Cookie header using axios for a front-end served on same IP:PORT as back-end, is there no way??

**Comment by sKopheK** [comment]
reopen please
