### ISSUE TITLE
Error uploading files using FormData in axios 0.19.0

### ISSUE THREAD

**Issue by umbrella22** [axios/axios#2459]
**Describe the bug**
When I uploaded files using fromdata, Axios0.19.0 gave me this error message:Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream.
But this problem does not arise in Axios 0.18.1,It works normally.

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
// There is a file object in UploadData
console.log(UploadData)
let data = new FormData();
data.append("file_type", `${this.fileName}`);
// UploadData.file represents the content of the file
data.append("file", UploadData.file);
axios({
    method: 'post',
    url: `${base}${url}`,
    data,
    headers: {
      'Content-Type': 'multipart/form-data'
    },
    timeout: 5000
  })
```

**Expected behavior**

**Environment:**
 - Axios Version 0.19.0
 - OS: windows 10
 - Browser Chrome
 - Browser Version 78
 - Additional Library Versions Vue 2.6.10

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

in the 0.19.0
![axios0 19 0](https://user-images.githubusercontent.com/19886152/66622315-bf570700-ec19-11e9-9a73-83d3b451d7e1.png)
---
in the 0.18.1
![axios0 18 0](https://user-images.githubusercontent.com/19886152/66622353-d4339a80-ec19-11e9-91fd-f445198f0243.png)

**Comment by yasuf** [comment]
I just tested this scenario using 19.0 here https://codepen.io/carlosyasu91/pen/jOOqZEQ

It's weird since it looks like your use of version 19.0 is using the node server adapter and not the browser adapter, which causes that error. In the codepen I notice I just get a 404, which makes it seem like the FormData would be sent correctly if the endpoint was there. The data is in the request as expected, let me know if this example helps or if you find anything else with this

**Comment by yasuf** [comment]
I don't know see `-S` in the documentation https://docs.npmjs.com/cli/install but you might be using a different version of NPM than the one documented there, I would normally use `--save`.

**Comment by umbrella22** [comment]
Thank you for your reminding. I guess there is something wrong with my code. Thank you for your reply.

**Comment by mdmc187** [comment]
hi @umbrella22 

im having the same problem, did you find a solution ? My laravel method simply returns the request im sending to the server. While the request i send seems to hold the file, the response is always empty.
```

var data = new FormData();
data.append('file', this.$refs.file.files[0]);
```

```
const config = 
{ 
headers: {     
'Content-Type': multipart/form-data;boundary='+${data._boundary
} } }
```

            axios.post('/api/user/settings', data, config).then(response => {
                console.log(response);
            }).catch(err => {
                console.log(err.response)
            });`

Thank you 

regards

**Comment by umbrella22** [comment]
hi @mdmc187 Emm, my problem is that I used axios in the electron, and axios mistakenly used the node adapter, which caused the file upload failure;your code appears to have encountered this problem in the browser, and you need to ask your server developer for more information
