### ISSUE TITLE
POST request magically transformed to GET request when POST endpoint is redirected

### ISSUE THREAD

**Issue by vitalyster** [axios/axios#2460]
My steps:
1) Do `axios.post(...)` to `http://example.com/api/post_endpoint`
2) server responds 301 with `http*s*://example.com/api/post_endpoint` location
3) axios sends `GET`(!) request after redirection

**Comment by makc** [comment]
you have been warned:
![Screen Shot 2019-10-12 at 2 21 06 ](https://user-images.githubusercontent.com/242577/66691477-07683f00-ec97-11e9-86d6-e7037da8e6a8.png)

**Comment by yasuf** [comment]
I believe this can now be closed?

**Comment by vitalyster** [comment]
No, axios should not act erroneously as http/1.0 user agent

**Comment by pdath** [comment]
I've been using this project:
https://github.com/tejashah88/node-meraki-dashboard/
with the Cisco Meraki API (which uses axios).  The Cisco Meraki API has a global URL you start with and then it redirects you to a specific shard to handle your request.

I've probably spent a whole day on trying to figure out why GET requests work and POST requests don't.

After seeing this bug I tried creating code in just axios to do the request and low and behold axios changes the POST to a GET after the redirect.

So +1 to people affected by this bug.

**Comment by pdath** [comment]
It seems that the module follow-redirects deliberate limits the use of http methods to "read" types.  It doesn't consider POST to be "safe" as it is a "write" method so is changing it on purpose.

var SAFE_METHODS = { GET: true, HEAD: true, OPTIONS: true, TRACE: true };

**Comment by yasuf** [comment]
should this be an issue in `follow-redirects`? that way we can close this one and get help from the maintainers of that library and we just upgrade our dependency when it's ready

**Comment by yasuf** [comment]
closing to have issue migrated to `follow-redirects` dependency

**Comment by yasuf** [comment]
closing to have issue migrated to `follow-redirects` dependency

**Comment by RubenVerborgh** [comment]
Note that @makc [above](https://github.com/axios/axios/issues/2460#issuecomment-541262749) cites the obsolete version of the HTTP1/1 spec, RFC2616, whereas the latest versions states that:

> > Automatic redirection needs to done with
   care for methods not known to be safe, as defined in Section 4.2.1,
   since the user might not wish to redirect an unsafe request.

—https://tools.ietf.org/html/rfc7231#section-6.4

> >  For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.

—https://tools.ietf.org/html/rfc7231#section-6.4.2

That spec test is cited in the source code referred to above.
