### ISSUE TITLE
why don't set default method

### ISSUE THREAD

**Issue by mohamadresaaa** [axios/axios#2461]
i using axios for post request
this is my code:
`const request = axios.create({
    method: 'POST',
    baseURL: process.env.SERVER_URL || 'google.com',
    headers: {
        'X-Parse-Application-Id': process.env.APP_ID || '',
        'X-Parse-Master-key': process.env.MASTER_KEY || ''
    }
})`

but i send request axios method is 'get'
![Capture](https://user-images.githubusercontent.com/41260098/66698246-0e1fa200-ece9-11e9-9236-a2902c2b311d.PNG)

**Comment by yasuf** [comment]
You don't specify the method when creating an axios instance, after creating the instance you can do `instance.get('/users')` for instance, you can check this part of the docs: https://github.com/axios/axios#axioscreateconfig
