### ISSUE TITLE
How to config the default headers

### ISSUE THREAD

**Issue by dthtien** [axios/axios#2462]
I have configured the headers like this and made the HTTP request.
```js
const httpClient = () => {
  const instance = axios.create({
    baseURL: "https://api.giphy.com/v1/gifs",
    headers: {
      api_key: "thisisapikey"
    }
  });

  return instance;
};
export const getTrending = (options = {}) => {
  const params = options;
  params.limit = 20;
  return httpClient()
    .get("trending", { params })
    .then(response => response.data)
    .catch(err => {
      throw err.response;
    });
};
getTrending();
```
My axios version `0.19.0`
But I have got the request header like below:
![image](https://user-images.githubusercontent.com/20236616/66701037-8609be80-ed21-11e9-8748-4cf59e891104.png)
Could anyone please tell me the reason the header was set wrong?

**Comment by yasuf** [comment]
Is it the OPTIONS request? I'm testing your code in a local html file and I'm getting a CORS error when testing it, it might be an issue with CORS and not axios itself. Let me know if that helps or if I can help further investigate this issue

**Comment by dthtien** [comment]
@yasuf Yes, it is OPTIONS request. I have changed to another server and it works properly.

**Comment by yasuf** [comment]
would you mind closing the issue @dthtien ? glad it worked!
