### ISSUE TITLE
SRCCLR-SID-21679: Veracode scan reporting "Cross-Site Scripting (XSS) Vulnerability in the axios library"

### ISSUE THREAD

**Issue by tpag26** [axios/axios#2463]
Veracode is reporting that all versions of axios (up to and including 0.19.0-beta.1) contain a XSS vulnerability. (CVSSv3: 6.1) 

Very limited details available:
https://www.sourceclear.com/vulnerability-database/security/sca/vulnerability/sid-21679/summary

I suspect it is a false positive based on comments [here](https://github.com/axios/axios/issues/2447). Would value any thoughts / input

Thanks

**Comment by yasuf** [comment]
I just made a PR, the last PR (https://github.com/axios/axios/pull/2451) I believe just wasn't returning or throwing an error when it detected a script in the URL, thanks for the heads up!

**Comment by yasuf** [comment]
@tpag26 can you close this issue, since this is a duplicate of https://github.com/axios/axios/issues/2447 ? I'll link the PR to that issue

**Comment by tpag26** [comment]
Thanks @yasuf
