### ISSUE TITLE
toJSON() function not documented in readme

### ISSUE THREAD

**Issue by pavel-john** [axios/axios#2465]
**Section/Content To Improve**
https://github.com/axios/axios#handling-errors

**Suggested Improvement**
Axios error has `toJSON()` method which is very useful, but not documented. Please add reference to error handling section.

**Relevant File(s)**: README.md

**Comment by yasuf** [comment]
Thanks for the suggestion, I added an example for that

**Comment by felipewmartins** [comment]
@yasuf added the new documentation.
