### ISSUE TITLE
DeprecationWarning for OutgoingMessage.prototype._headers

### ISSUE THREAD

**Issue by msudgh** [axios/axios#2469]
**Describe the bug**
According to [Node.js Deprecated APIs](https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames), `OutgoingMessage.prototype._headers` in `v12` has been deprecated and on the other hand i see some deprecation logs while using Axios.

```bash
(node:89822) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

**To Reproduce**
Calling an endpoint in Node.js v12

**Expected behavior**
A patch for this deprecation.

**Environment:**
 - Axios Version: `0.19.0`
 - OS: OSX 10.15

**Related Links:**
- https://stackoverflow.com/questions/56697360/how-to-fix-node12388-dep0066-deprecationwarning-outgoingmessage-prototype
- https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames
- https://github.com/http-party/http-server/issues/537

**Comment by yasuf** [comment]
We'll have to update some of our dependencies, I don't see either of those in the codebase but I see `._headers` in a few of the libraries that axios uses

**Comment by rancerun** [comment]
@msudgh 

I'm interested in taking a look but I'm having trouble reproducing this.

Can you share the code you used?

**Comment by msudgh** [comment]
the snippet is like a simple Axios request, I tried to reproduce it but it seems gone.

> @msudgh
> 
> I'm interested in taking a look but I'm having trouble reproducing this.
> 
> Can you share the code you used?

**Comment by iw-jway** [comment]
@rancerun I seem to get it on GETs

**Comment by lucgauer** [comment]
It's still happening 😕

**Comment by jkthinksmart** [comment]
Still happening on version 0.27.2 as well

`[2022-05-17T11:57:52.228Z]  "HEAD /" "axios/0.27.2"
(node:669) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`
