### ISSUE TITLE
Default headers for authorization not working on 0.19.0

### ISSUE THREAD

**Issue by iranmarcius** [axios/axios#2476]
I'm using several axios instances to send requests to different endpoints but I'm setting an access token authorization header in axios defaults like this:

`axios.defaults.headers['Authorization'] = 'Bearer ' + myToken`

In version 0.18.1 everything works fine and the token is sent on every request. After update to version 0.19.0 it stopped working.

I read in the documentation that I should set default headers like this: `axios.defaults.headers.common['Authorization'] = 'Bearer ' + myToken`, but it doesn't work. No authorization header is sent.

I even throw a `console.log(axios.defaults.headers.common['Authorization'])` before one of my requests and the token is there in axios defaults, but it seems to ignore it.

Couldn't find anything in documentation telling if something changed from the previous version. So either it's a bug or I'm doing something wrong. I would like you to clarify me.

Thanks in advance.

**Comment by yasuf** [comment]
hmm weird, a few more people are reporting bugs with `0.19`, most likely this will need investigation, thanks for the heads up

**Comment by mjhea0** [comment]
I'm seeing similar issues as well. Difficult to flesh out and recreate.

**Comment by migueldaipre** [comment]
+1

**Comment by maxparelius** [comment]
Seeing issues as well. When trying to add `Authorization` header to axios Get request it appears the header never actually gets attached. Had to switch back to the `fetch` api for now.

**Comment by PasinduDew** [comment]
I'm having the same problem. Default Authorization Headers are not working in Axios version 0.19.0

**Comment by solo-framework** [comment]
Check whether your http server sends header 'Access-Control-Allow-Headers: Authorization' for requests sent with OPTIONS method.

for example:

```
if ($request_method = 'OPTIONS') {
	add_header 'Access-Control-Allow-Headers' 'Authorization';
}
```

**Comment by iranmarcius** [comment]
@solo-framework, I think that's not the issue. Axios isn't even sending headers that are set in axios.defaults.headers in this version. It works in the previous version.

In my case, specifically, the server is sending Access-Control-Allow-Headers with the Authorization header included.

**Comment by ricky11** [comment]
Any update on this is this a bug or by design or?

**Comment by chinesedfan** [comment]
@iranmarcius Can you provide a reproducible code sample? Words may lead to misunderstandings.

**Comment by iranmarcius** [comment]
I think my description of the problem was pretty straightforward. When you set common headers it simpy isn't sent with the request like it happens on version 0.18.1.

``axios.defaults.headers.common['Authorization'] = 'Bearer ' + myToken``

The code above has no effect in version 0.19.1.

Thanks for the reply.

**Comment by chinesedfan** [comment]
> I think my description of the problem was pretty straightforward.

@iranmarcius Didn't reproduce your problem. Anything different may free the bug away. And a reproducible sample can make maintainers easy to help you, saving time to write a test script even though it is very simple.

**Comment by iranmarcius** [comment]
@chinesedfan Ok, let's save time then.

I just saw that axios is at 0.19.2 version. The problem I described relates to version 0.19.0.

Common headers are working fine in the latest version, so I think it's sufice to update it in my project to solve the problem.

By the time I posted this issue 0.19.0 was the latest version.

Thanks for the help.
