### ISSUE TITLE
Behaviour of Axios causing 400

### ISSUE THREAD

**Issue by JustJarethB** [axios/axios#2477]
#### Summary
I am having an error with a Yii2 based application where a `fetch` call successfully submits but switching out for `axios` returns a 400. I have been unsuccessful in fixing this issue. My current code is as follows, where `form` is the DOM element.
``` js
 var args = { method: 'POST', body: new FormData(form), data:{}, config: { headers: {'Content-Type': 'multipart/form-data' } } }

  // Submit form and update previousState
  fetch("/", args).then(()=>setContent(form));
  // axios("/", args).then(()=>setContent(form));
```
I have tried playing around with the args and such, but didn't fix it.

The result from the server when `fetch` is used is `200 OK` and when `axios` is used it returns `400 Bad Request`
The follow stack traces
```
Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:59)
```

```
dispatchXhrRequest | @ | xhr.js:172
-- | -- | --
  | xhrAdapter | @ | xhr.js:11
  | dispatchRequest | @ | dispatchRequest.js:59
  | Promise.then (async) |   |  
  | request | @ | Axios.js:53
  | wrap | @ | bind.js:9
  | _callee2$ | @ | autosave.js:162
  | tryCatch | @ | runtime.js:45
  | invoke | @ | runtime.js:271
  | prototype.<computed> | @ | runtime.js:97
  | asyncGeneratorStep | @ | asyncToGenerator.js:3
  | _next | @ | asyncToGenerator.js:25
  | Promise.then (async) |   |  
  | asyncGeneratorStep | @ | asyncToGenerator.js:13
  | _next | @ | asyncToGenerator.js:25
  | eval | @ | asyncToGenerator.js:32
  | eval | @ | asyncToGenerator.js:21
  | submit | @ | autosave.js:91
```
(autosave.js is my file)

#### Context

axios@^0.19.0: version "0.19.0"
node v10.16.0
Mac OS 10.14.6 running mamp PRO 5.3

**Comment by smilledge** [comment]
Axios and fetch have different apis, and the same set of args wont be compatible between them. 

Eg, this fetch request;

```
fetch('/', {
  method: 'POST', 
  body: new FormData(form),
  headers: {
    'Content-Type': 'multipart/form-data' 
  }
})
```

Would look like this in Axios;

```
axois.post('/', new FormData(form), {
  headers: {
    'Content-Type': 'multipart/form-data' 
  }
})
```

If you're still having issues check the network tab to see if the request body is being sent correctly. Also, StackOverflow is more suitable for questions like this as it's not an issue with Axios.

**Comment by JustJarethB** [comment]
Thanks @smilledge, I will check this later. From what I could tell from the readme https://github.com/axios/axios it is possible to combine all parameters into an object, such as this:
```
// Send a POST request
axios({
  method: 'post',
  url: '/user/12345',
  data: {
    firstName: 'Fred',
    lastName: 'Flintstone'
  }
});
``` 
Why does this not work in the same manner?

**Comment by Troy1b4** [comment]
I have tried to send a post in the manner mentioned in JustJarethB and it will not work for me.

**Comment by JustJarethB** [comment]
I do not know if you are suffering the same issue @Troy1b4 but my issue was resolved by switching to the format `axios.post(uri, body, config)` so maybe try that. Also data and body are not quite the same so make sure the server accepts JSON data

**Comment by Akiren** [comment]
I had this same exact issue, its an axios issue when hitting certain API's like AWS cloudfront lambda... Spent hours debugging.. Examples all over the internet have you thinking you can always pass json directly to data without JSON Stringify which appears to be needed to correctly post to certain apis

What was even more confusing is when I pass it directly I get an incorrect error of CORS which has nothing to do with the actual problem.

** FAIL **
Axios({
  method: "post",
  url: "https://localhost:44394/Threshold/AddThreshold/",
  data: threshold,
  headers: { "Content-Type": "application/json" }
})

** SUCCESS **
Axios({
  method: "post",
  url: "https://localhost:44394/Threshold/AddThreshold/",
  data: JSON.Stringify(threshold),
  headers: { "Content-Type": "application/json" }
})

**Comment by aman79** [comment]
getting error for get request
