### ISSUE TITLE
Cannot call dockerized REST API in a dockerized environnement with axios

### ISSUE THREAD

**Issue by hvalette** [axios/axios#2480]
Hi all, 

**Here is the situation :** 

_All is happening in a local envirronement._ 
My first docker container with API **A** want to call my second container with API **B** with a GET HTTP request using axios. Using docker service name, i call the URL i want but i got : 
`Error: Request failed with status code 503`
But, when I go inside the container **A** with `docker exec -it my_container_A /bin/sh `, the GET request works with cURL that is why I guess the problem is related to axios.

My two containers are built with docker-compose.

**Do you have any ideas to solve this ?** I've tried with localhost, docker service name, pc's ip

**Comment by yasuf** [comment]
which version of axios are you using?

**Comment by yasuf** [comment]
is there a way that you could inspect the request to see that the headers are correct?

**Comment by hvalette** [comment]
Sorry I completly forgot about this issue, i was using axios v0.19.0 but i don't need axios anymore in the project so i can't give you more details. I'll reopen this when i'll have more informations. Thank you :)

**Comment by jimlundblad** [comment]
I'm having issues with docker and axios as well, my docker containers are:
wordpress and nginx reverse proxy, and a express.js app,

but when axios is trying to call /wp-json from the wordpress or nginx container it get's ECONNREFUSED and resolves 127.0.0.1 instead of the container IP

`{
  Error: connect ECONNREFUSED 127.0.0.1:443
  at TCPConnectWrap.afterConnect[as oncomplete](net.js: 1107: 14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443,
  config: {
    url: 'http://172.20.0.212/multisite/wp-json/wp/v2/pages',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [
      [Function: transformRequest]
    ],
    transformResponse: [
      [Function: transformResponse]
    ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    domain: null,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: null,
      hostname: 'wordpress.local',
      port: null,
      nativeProtocols: [Object],
      pathname: '/',
      search: null,
      slashes: true,
      host: 'wordpress.local',
      hash: null,
      query: null,
      href: 'https://wordpress.local/'
    },
    _redirectCount: 1,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET / HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.2\r\nHost: wordpress.local\r\nConnection: close\r\n\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      timeout: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/',
      _ended: false,
      res: null,
      aborted: undefined,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Circular],
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object]
    },
    _currentUrl: 'https://wordpress.local/',
    _isRedirect: true
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}`
