### ISSUE TITLE
axios return javascript error 

### ISSUE THREAD

**Issue by baonguyen93** [axios/axios#2481]
I got an error when I execute the axios post method. 
The code in catch method executed but it still throw another error.
I just want to prevent it. 
I tried some way like interceptor but it not working.
Thanks

This is my code
```js
axios.post('/api/profile/save', this.obj)
                    .then(result => {
                        console.log(result);
                        this.message = 'Save profile success!';
                        this.showMessage = true;
                        this.typeMessage = 'success';
                    })
                    .catch(error => {
                      // It will jump in and execute
                        this.message = 'Save profile failed!';
                        this.showMessage = true;
                        this.typeMessage = 'danger';
                        // console.log('error', error.response);
                    })
                    .finally(res => {
                        this.loading = false;
                    });
```
**Additional context/Screenshots**
![axios22](https://user-images.githubusercontent.com/49013423/67282840-c543c680-f4fc-11e9-85d3-0d055795bb78.png)

**Environment:**
 - Axios Version: 0.19.0
 - Browser: Chrome
 - Vuejs

**Comment by rdamian3** [comment]
Seems like that's not an Axios issue...

**Comment by yasuf** [comment]
Error outside of the scope of axios, closing this issue unless there's more an issue related to axios. @baonguyen93 you might want to check your server logic and the logs there to see if there are any issues on that end!
