### ISSUE TITLE
Update doc on 0.19.0

### ISSUE THREAD

**Issue by Fantaztig** [axios/axios#2484]
**Section/Content To Improve**
Changelog 0.19.0

**Suggested Improvement**
We are using axios in our application and had the problem that the no_proxy environment variable was not correctly used.
I saw this was fixed in 0.19.0-beta.1 back in august 2018.
Howevern in the change and release notes of 0.19.0 there was no mention of those fixes, they were still only mentioned for the beta release.
Therefore it was hard for me to decide whether I should use 0.19.0 or the beta version.

**Relevant File(s)**: [Changelog](https://github.com/axios/axios/blob/master/CHANGELOG.md)

**Comment by yasuf** [comment]
do you know the PR where that was fixed? was it this one https://github.com/axios/axios/pull/1693/files ? What message do you think it's appropriate?

**Comment by Fantaztig** [comment]
Yes it was #1693, the message is understandable as well.
It was just unclear to me wether the current version 0.19.0 includes this PR or not as the PR is not listed in the changelog for version 0.19.0.
The PR is however included in the changelog for 0.19.0-beta.1, but the beta was released Aug 9, 2018, while 0.19.0 was released May 30, 2019.
Therefore I would expect all PRs from 0.19.0-beta.1 to be included in 0.19.0 as well, which I think should reflect in the changelog.
