### ISSUE TITLE
Add retry functionality

### ISSUE THREAD

**Issue by Zyles** [axios/axios#2486]
**Is your feature request related to a problem? Please describe.**

When requests fail I want to retry them.

**Describe the solution you'd like**

Ability to retry a failed request X amount of times with a delay.

**Describe alternatives you've considered**

Tried using third party axios adapters which are outdated and broken.

**Additional context**

This functionality should be in core.

**Comment by genie-youn** [comment]
I think it's good to try an interceptor

https://github.com/axios/axios/issues/934#partial-timeline

**Comment by yasuf** [comment]
Closing, functionality can be achieved with an interceptor as mentioned in #934  @Zyles I've heard rxjs can be good for that as well https://rxjs-dev.firebaseapp.com
