### ISSUE TITLE
Memory leak in isURLSameOrigin

### ISSUE THREAD

**Issue by xinpingwang** [axios/axios#2489]
**Describe the bug**
On standard browser env, the axios lib will create an `<a>` element, and set the `href` attribute to `requestURL`, then get the `resolvedURL`, and compare it with `originURL` to determine whether `requestURL` is under same origin.
But, the `urlParsingNode` is defined out of the `resolveURL` function, this cause the browser cannot release the memory of this element.

**To Reproduce**
I create a simple vue app just import axios, and defined a simple component in https://jsfiddle.net/5f37g4t1/2/
in actually project, the component defined in it's file, and maybe used in some page, but when leave the page, all memory should be collected.

**Expected behavior**

after click `Toggle Show Context Input` button, the element created by axios should be collected.

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.14.6]
 - Browser [Chrome]
 - Browser Version [77]
 - Additional Library Versions [Vue 2.16.10]

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/41824968/67477415-9a887800-f68c-11e9-8ad4-e0f683c2c2ef.png)

**Solution**

I found a solution is to move those code
```
var msie = /(msie|trident)/i.test(navigator.userAgent);
var urlParsingNode = document.createElement('a');
var originURL;
```
into `resolveURL` function, but this may cause the axios to create `<a>` element every time, maybe there is a trade off.

**Comment by xinpingwang** [comment]
I create a pull request to solve this problem using the URL API, which support  nearly all popular browser except IE(?-11) according to https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by yasuf** [comment]
IE11 seems to have a [3% market share](https://www.stetic.com/market-share/browser/), is there an alternative to fix this memory leak?

**Comment by xinpingwang** [comment]
After some search, I found that there is a polyfill https://github.com/lifaon74/url-polyfill, it also using   `<a>` element to parsing url. So I reverse the original method to make it work on IE, and use the `URL` API on other browsers. Also, I defined the `urlParsingNode` inner `resolveURL` to avoid memory leak.

See my new push on #2491 for the details

**Comment by xinpingwang** [comment]
I found that [`core-js`](https://github.com/zloirock/core-js) has implement the `URL` API: [URL and URLSearchParam](https://github.com/zloirock/core-js#url-and-urlsearchparams) in pure javascript, it will check whether the browser support `URL` api before do polyfill. And I think that this is a good solution for browsers that not support `URL` api, and will fix this issue. How do you (@yasuf) think about this?

**Comment by jasonsaayman** [comment]
Hi,

Closing as it seems this is a fix for MSIE and this browser is replaced by edge, seems not worth fixing something that should in theory not be an issue anymore.

Please feel free to open a new issue if you believe this was closed in error.

**Comment by xinpingwang** [comment]
Hi, @jasonsaayman 

The purpose for this issue(also see #1786) is that there is a memory leak in `resolveURL`. After some investigation, there are two way to solve this problem:

1. Use `URL` API, but need polyfill for IE(?-11)
2. Create `<a>` element **every time** when calling `resolveURL` and then release it, but this may be cause some cost than just create **once**

In #2491, I made a solution:  keep using `<a>` element in resolveURL for MSIE(still create once as current implementation), and `URL` API for other browsers.  

As you said, MSIE will be replaced by Edge, and polyfill for `URL` seems not worth. I think #2491 is a good solution for this issue.
