### ISSUE TITLE
Custom attribute cannot be obtained in the config of interceptors

### ISSUE THREAD

**Issue by zhuwenqi001** [axios/axios#2490]
**Is your feature request related to a problem? Please describe.**
For a request, it is necessary to record the status of the request. I want to add a loadkey parameter to each request, process it centrally in the Axios instance, and modify the value corresponding to the loadkey in the interceptors, but I can't get this custom parameter now. Previous versions of 0.17 were available

**Describe the solution you'd like**
Custom attribute can be obtained in the config of interceptors

**Comment by yasuf** [comment]
See https://github.com/axios/axios/issues/2438, let's have the discussion there, do you mind adding your comments there?

**Comment by yasuf** [comment]
and closing this issue
