### ISSUE TITLE
about create instance

### ISSUE THREAD

**Issue by lt978613** [axios/axios#2492]
```
var instance =  axios.create({
	params:{
		a:1,
		b:2
	}
});
console.log(instance.defaults)
instance.get('http://www.ablesky.com/api.json')
```

The request send by the instcance will missing the configration of params why?

**Comment by yasuf** [comment]
params are per request, they cannot be set at the instance level, you'll have to either send them in the URL or add a config param to the `.get` that has those params

**Comment by yasuf** [comment]
there's an example in this section https://github.com/axios/axios#example, closing this issue
