### ISSUE TITLE
Create and advertise income channels

### ISSUE THREAD

**Issue by unguul** [axios/axios#2493]
**Is your feature request related to a problem? Please describe.**
The project is currently under pressure from the community due to the high number of issues and pull requests. A solution to this would be to provide appropriate permissions to more people so the project keeps moving forward. Unfortunately, the primary maintainers (currently 4) are busy with other commitments.

**Describe the solution you'd like**
Create and advertise potential income channels. I think Tidelift and Open Collective would work best due to their distributed nature but there might be others. This should, in theory, enable the primary contributors to justify a resource expenditure towards unblocking this project.

There's currently ~190 USD waiting to be claimed via https://opencollective.com/axios and https://tidelift.com/lifter/search/npm/axios

Potential income channels:

1. Tidelift;
1. Opencollective;
1. Github Sponsors;

**Comment by yasuf** [comment]
Emily responded to me yesterday, she will add me to the contributors so that I can at least merge PRs and address issues and maybe later on create new builds. About those dollars, I'm not sure who's to claim them 🤷‍♂️

**Comment by yasuf** [comment]
now github has https://github.com/sponsors, maybe that could help

**Comment by chinesedfan** [comment]
I joined axios for interests. And I played those websites for a while. But I think only the owner of axios (@mzabriskie) should reclaim the money. :)

**Comment by phated** [comment]
It'd be great to get Axios to join Tidelift! There is [already $64.75/month available](https://tidelift.com/lifter/search/npm/axios) to be claimed by the maintainers of this project.

When you sign up, there are a few requirements for the project that we outline at https://tidelift.com/about/lifter-tasks. It looks like Axios already does most of them!

I'm happy to answer any questions you might have.

**Comment by chinesedfan** [comment]
@phated I have read more introductions about Tidelift and find there may be a little gap between us.

> Our first goal is more contributors, instead of income.

In my words, Tidelift sells axios to commercial customers with higher requirements (which will increase burdens of axios), but doesn't help axios with new contributors. Apology if I misunderstood something. Do you still think Tidelift suitable for axios?

**Comment by phated** [comment]
@chinesedfan Unfortunately, we don't currently have a way to help you recruit more maintainers. We have been hearing this request a lot, so it's something we'd like to do in the future. Sorry 😞

**Comment by unguul** [comment]
@chinesedfan You're making some excellent points. People should contribute to the project for the love of the craft rather than x USD per month.

However, I wouldn't dismiss the impact this can have on the project reputation. I'm sure many people/companies have dismissed axios as a viable library for their project due to the high number of open issues and pull requests which suggests the project is *abandoned*.

Perhaps Tidelift is not the best platform to join at the moment due to the increased pressure it would bring but github sponsors and opencollective might be.

**Comment by chinesedfan** [comment]
Closed due to the author is not active. And thanks for your kind suggestions all the same.
