### ISSUE TITLE
Axios Post request Error responses are mishandled

### ISSUE THREAD

**Issue by BrandonCopley** [axios/axios#2497]
If you make an Axios Post request and the request fails with an error: ex: 401, invalid login. If the error message is sent as a string the error message will fail being parsed by json and be returned at "null". The correct operation would be to, if json parsing fails, return the string itself.

**Comment by yasuf** [comment]
can you provide an example to reproduce this issue?

**Comment by BrandonCopley** [comment]
The example can be found by running "examples" and clicking on postStringResponse

https://github.com/BrandonCopley/axios

**Comment by BrandonCopley** [comment]
The issue is the error message returned is: "Request failed with status code 500" This is because the response is NOT JSON, but a string. When this happens the actual string error message gets lost because Axios attempts to decode it as a JSON object and when that fails it just ignores it. I believe if JSON decoding fails then the error message should be decrypted as a string and displayed.

**Comment by BrandonCopley** [comment]
After some digging, it appears this may be related to how https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response handles response types

**Comment by Alanscut** [comment]
I think the Axios object's err object already contains enough information,including the correct error message that your server gives you;
```
lib/core/enhanceError.js

error.config = config;
  if (code) {
    error.code = code;
  }

  error.request = request;
  error.response = response;   
  error.isAxiosError = true;
```

**Comment by BrandonCopley** [comment]
The data object on the response will be "null". This appears to be an
XMLHTTPRequest bug. If you run the sample code you won't ever see the
string message, but in your console if you trace the network request you
will see the string message.

-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by yasuf** [comment]
nothing to do on axios' end
