### ISSUE TITLE
Losing cusomize property value when I add some customize property of AxiosRequestConfig

### ISSUE THREAD

**Issue by zl7261** [axios/axios#2500]
Axios  version is  ^0.19.0

I wanna add some customize filed in RequestConfig to control the HTTP request of Axios show loading gif or not.

But I found those customize filed is not found in the interceptor of Axios.

Here is my code.
``` javascript
interface RequestConfig extends AxiosRequestConfig {
    hideLoading?: boolean
    loadingText?: string
    warnType?: string
    hideWarn?: boolean
}


const service = axios.create({ 
})

export default {
get: (url: string, data: object, config: RequestConfig) => {
        let realConfig = {params: config, ...DEFAULT_CONFIG, config_flag: config};
        return service.get(url, realConfig)
    },
}

service.interceptors.request.use((request: RequestConfig) => {
    let url = request.url;
    if (!url) throw new Error('url is empty')
    if (!url.startsWith('/')) url = '/' + url;
    console.time(request.baseURL + url)
    if (!request.params.hideLoading) {  
// I can  only get propert's value which defined in AxiosRequestConfig, 
// not in my customized ReuqestConfig
        startLoading(request);
    }
    return request
}, (err: any) => {
    return Promise.reject(err);
});
```

In the interceptor's scope, the request doesn't contain any filed of RequestConfig.
But when I put my customized config in the filed of AxiosRequestConfig such as 'params'
It does works.

Does Axios ban the operate of customizing AxiosRequestConfig, such as add property, only return the pure properties of AxiosRequestConfig?

**Comment by yasuf** [comment]
I'll take a look at this whenever I get a chance, we have https://github.com/axios/axios/issues/2438 and https://github.com/axios/axios/issues/2490 as well

**Comment by yasuf** [comment]
See https://github.com/axios/axios/pull/2502 once that goes live this should work

**Comment by zl7261** [comment]
ty, waiting for release.
Already revert to 18.1 to fix it.
