### ISSUE TITLE
Whether to support specifying a MIME type to replace the serve specified type?

### ISSUE THREAD

**Issue by Alanscut** [axios/axios#2503]
**Describe the issue**
Whether to support specifying a MIME type to replace the serve specified type?
example it is used when forceing the stream mode to be processed as "text/xml" type,even if the server does not specify this in the response header.

**Comment by yasuf** [comment]
isn't that a header? or what kind of support are you referring to?

**Comment by Alanscut** [comment]
XMLHttpRequest.overrideMimeType()

**Comment by yasuf** [comment]
what's the use case for this? I'd prefer not to do this since that can be specified in the server, unless the use case is pretty strong or common but at the seam time sort of open to considering it depending on how many people ask for this and the type of use case

**Comment by herrKlein** [comment]
I just ran into this issue, I have a simple dev server ( rollup-server ) setup which doesn't know how to serve or config mime types. I need to grab an XML file from the folder, which the browser Interpretes as an HTML document. Except when I override the mime-type, which is not possible in Axios unfortunate. So for XML I use the following. Would be nice to have it as an option.

`function getXML(url) {
			const request = new XMLHttpRequest();
			request.overrideMimeType('text/xml');

			return new Promise(function (resolve, reject) {
				request.onreadystatechange = () => {
					if (request.readyState !== 4) return;
					resolve(request.responseXML);
				};
				request.open('GET', url, true);
				request.send();
			});
		}`
