### ISSUE TITLE
Get requests giving "Network Error" for react native 0.59.10 built with xcode 11 for devices with iOS 13

### ISSUE THREAD

**Issue by RogerParis** [axios/axios#2505]
**Describe the bug**
After upgrading to xcode 11, in my react native application builds, all GET requests get "Network Error" for devices with iOS 13

**To Reproduce**
This is happening with all react native applications built with xcode 11 for devices with iOS 13.
For devices with iOS 12 everything works as expected.
And builds with xcode 10.3 works for devices with iOS 13 too.
It's the combination of axios with xcode 11 for iOS 13 devices only.
Apps with fetch instead of axios work for iOS 13 devices. So we will have to unfortunately switch to fetch if we don't find a solution.

**Expected behavior**
I expect that the GET requests work and don't always send "Network Error" for apps with devices with iOS 13 built with xcode 11

**Environment:**
 - Axios Version 0.19.0
 - XCODE Version 11
 - react native Version 0.59.10

**Comment by yasuf** [comment]
can you try using axios version 0.18.0? I see that low level errors are caught by that `Network Error` but if 0.18.0 works, that can help us debug this by seeing the diff between versions

**Comment by whhlulu** [comment]
There is the same phenomenon. Would you like to solve it?
Axios Version 0.18.0
XCODE Version 11
react native Version 0.59.10

**Comment by yasuf** [comment]
it would help if I can have an example project to see the error and try a few fixes on the axios end, is the error happening on any request?

**Comment by whhlulu** [comment]
I can't give an example, it's too much trouble, I don't know how to provide.
Get request I gave the ’data‘ property in ’options‘, then, I got a very clear error: 'GET method must not have a body', after deleting ’data‘, it's all right

**Comment by RogerParis** [comment]
Thanks @yasuf . Let me know if you find something. I don't send any data so I don't think is the same problem as whhlulu

**Comment by RogerParis** [comment]
@yasuf Did you have the chance to check it?

**Comment by mspitzenberg** [comment]
@yasuf Would be awesome to get an update as well

**Comment by StevieWag** [comment]
Same problem here.

**Comment by imdanielpiva** [comment]
Having the same problem, I've commented more about it here https://github.com/axios/axios/issues/2580#issuecomment-568592598

**Comment by RogerParis** [comment]
Still not working with 0.19.1

**Comment by Duduzera1997** [comment]
Same problem here. With Fetch(GET) everything works normal, with axios it always gives Network error in the GET Method.
Axios: 19.0.2

**Comment by Volekss** [comment]
@whhlulu solution helped me. This seems to be a bug which needs to be fixed

**Comment by anhdevit** [comment]
> There is the same phenomenon. Would you like to solve it?
> 
> I'm trying to do this, and I can fix it.
> 
> ```js
>   if (method === 'get') {
>     delete options['data']
>   }
> ```

You safe my life

**Comment by TheTrunk** [comment]
Facing same issue. 
Can you please provide an example how to integrate 
```

**Comment by anhdevit** [comment]
> Facing same issue.
> Can you please provide an example how to integrate this advice?
> 
> ```
>   if (method === 'get') {
>     delete options['data']
>   }
> ```
> 
> @anhdevit @whhlulu

This issue because when you using get you don't need data in options
```
  const options = {
    url: BASE_URL + endPoint,
    method,
    headers,
    data,
    timeout: 18000,
  }

  if (method === 'get') {
    delete options['data']
  }
```

**Comment by callmemonky** [comment]
Hi, facing same issues NETWORK ERROR. Any updates on this?

**Comment by TheTrunk** [comment]
@callmemonky
What I have ended up using in our cordova project is ios xhr plugin https://github.com/landsbankinn/cordova-plugin-ios-xhr
You may want to research into how it works in the background or in case you have cordova project, just straight up use it.

**Comment by aniket-dalvi** [comment]
Hi, remove the data key from the request body object while making a GET request. In my case, this solved my issue.
