### ISSUE TITLE
I create an instance and execute a non-triggered request

### ISSUE THREAD

**Issue by carlosmajimo** [axios/axios#2506]
I am creating an instance of axios in my project, but when using the method: .create (), an option type request is made, why does this happen?

```ts
    import axios, { AxiosInstance } from 'axios';
    import { url_base } from '../../_constants/api_keys';

    function createInstance(): AxiosInstance {
        const headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        };

        return axios.create({
            baseURL: url_base,
            responseType: 'json',
            headers
        });
    }

    const instance: AxiosInstance = createInstance();
```
When executing my project, this happens:

![Captura de Pantalla 2019-10-30 a la(s) 5 30 04 p  m](https://user-images.githubusercontent.com/22925684/67904070-52110480-fb3b-11e9-9d16-621c20e69813.png)

**Environment:**
 - Axios Version: 0.19.0

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by carlosmajimo** [comment]
Update my console: 
![image](https://user-images.githubusercontent.com/22925684/67904550-acf72b80-fb3c-11e9-9166-4af0e1a4a938.png)

**Comment by Alanscut** [comment]
I am normal in project verification, and viewing the source code under normal circumstances will not cause this problem, I suggest you breakpoint debugging.

**Comment by yasuf** [comment]
I only see a GET request being made in your screenshot

**Comment by yasuf** [comment]
sometimes preflight requests are made when doing a POST request, https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#Preflighted_requests_in_CORS, closing as it seems like a server configuration error
