### ISSUE TITLE
DefaultAdapter returns unknown/undefined by default

### ISSUE THREAD

**Issue by ryanmalesic** [axios/axios#2507]
**Describe the bug**
The Default Adapter returns with out being set if the if/elseif isn't met. This means an axios call (through AWS Amplify API) in nextJS getInitialProps throws  because "Adapter is not a function"

**To Reproduce**
Make a next js project with amplify and init with api. GraphQL uses axios to make the calls. Tracing the stack shows that the axios defaults module does not set the adapter.

**Expected behavior**
The adapter should be set.

**Environment:**
 - Axios Version 0.19.0
 - OS: MacOs
 - Browser Chrome
 - Additional Library Versions Next 9.1.1

**Additional context/Screenshots**

```js
function getDefaultAdapter() {
  var adapter;
  // Only Node.JS has a process variable that is of [[Class]] process
  if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  } else if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  }
  return adapter;
}
```

This is the method. The "Object.prototype.toString.call(process) === '[object process]'" is false because the process in nextJS is "'[object Object]'"

This isn't just an issue with nextJS. An if/elseif should never, imo, fall-through and return a variable that hasn't been set. Throw from there or set a default in an else block.

**Comment by yasuf** [comment]
that's true, I'll push something for this whenever I get a chance

**Comment by ryanmalesic** [comment]
If you give me the default adapter i can just do a PR with an else using the adapter if you want

**Comment by Alanscut** [comment]
hey, maybe this pr #2508 works,what do you think @yasuf ? :)

**Comment by yasuf** [comment]
what's does `nextJS` run on? to me `XMLHttpRequest` worked well just because it's a very specific class that's needed on `axios`, compared to window, where someone else can have a global variable called `window` in their code (not that it's a good practice). I'd rather investigate why `XMLHttpRequest` is undefined in nextJS (I believe this is because it's SSR) or add an `||` conditional that returns true for a process in `nextJS`, that process probably has something useful

**Comment by ryanmalesic** [comment]
nextJS getInitialProps is on the server

**Comment by omkar-joshi** [comment]
@ryanmalesic @yasuf Can I take this?

**Comment by yasuf** [comment]
I just ran `examples/with-react-with-styles` and did:
```
    console.log("Process prototype toString()")
    console.log(Object.prototype.toString.call(process))
```
inside `getInitialProps` and it correctly logged `[object process]`, can you help sharing what node version and nextjs version you're using? I'm on the `canary` branch. We should probably fix still this but just wondering if this unblocks you and we can throw an error in case none of the conditions pass. Maybe it's another dependency that's loading and overriding `process`?

**Comment by yasuf** [comment]
@omkar-joshi, @Alanscut already made a PR, but your help can be great for other issues!

**Comment by ryanmalesic** [comment]
@yasuf It must be AWS amplify modifying the process because I get the same result as you with console.log. Unfortunate that amplify doesn’t support SSR for some reason

**Comment by yasuf** [comment]
@omkar-joshi https://github.com/axios/axios/issues/2485 could be an good one if you can help

**Comment by omkar-joshi** [comment]
Sure. Thanks @yasuf

**Comment by flatherskevin** [comment]
Any reason this issue is closed with the PR still open? I am experiencing the same issue with the adapter not being set while using AWS Amplify

**Comment by ryanmalesic** [comment]
@flatherskevin its an aws issue, not axios

**Comment by MickL** [comment]
Having the same problem within Cloudflare worker: `(t.adapter || a.adapter) is not a function`. Problem is that not just Axios does not work, but also modules that use Axios like `contentful/contentful-management.js` for example.

**Comment by aliankarali** [comment]
Still having this issue with `@aws-amplify/api@2.1.1` on server side.

**Comment by simpleshadow** [comment]
+1 Getting the `GraphQLError: adapter is not a function` error as well in next.js.

**Comment by sgammon** [comment]
@MickL I'm in the same environment as you. did you ever get this solved on CF workers?

**Comment by sgammon** [comment]
this is still broken in 2020 on CloudFlare workers

**Comment by MickL** [comment]
No it is not possible to use axios in a Cloudflare worker
