### ISSUE TITLE
array query params aren't serialized properly

### ISSUE THREAD

**Issue by mmkal** [axios/axios#2510]
**The bug**

When passing an array to a property in the `params` object of a request (which by default translates to a querystring), the serializer adds `[]` brackets to the param name.

**To Reproduce**

```js
$ node
> require('axios').default.get('https://postman-echo.com/get', {params:{tag:['a','b']}}).then(r => console.log(r.data))
Promise { <pending> }
> {
  args: { tag: [ 'a', 'b' ] },
  headers: {
    'x-forwarded-proto': 'https',
    host: 'postman-echo.com',
    accept: 'application/json, text/plain, */*',
    'user-agent': 'axios/0.19.0',
    'x-forwarded-port': '443'
  },
  url: 'https://postman-echo.com/get?tag[]=a&tag[]=b'
}
```

Note that the url at the end there is `https://postman-echo.com/get?tag[]=a&tag[]=b'`

**Expected behavior**

`https://postman-echo.com/get?tag=a&tag=b'`
`require('querystring').stringify(...)` gets this right, so maybe the implementation should just use that?

**Environment:**

 - Axios Version 0.19.0
 - MacOS 10.14.5
 - Node v12.12.0

**Comment by yasuf** [comment]
having `tag[]=a&tag[]=b` is the way I've seen rails take arrays as arguments on GET requests, but this is framework specific it looks like, to customize this you can indeed use `query-string` by using the `paramsSerializer` config

**Comment by yasuf** [comment]
the current solution seems fine to me, as it offers both something out of the box and the option to customize serialization and we keep the dependencies list small

**Comment by mmkal** [comment]
Fair enough, it's a little surprising to me that it works this way since most other javascript libraries (express, querystring etc.) use the `tag=1&tag=2` format, but it'd be disruptive to make a breaking change given there is some precedent for the `[]` style.
