### ISSUE TITLE
Bug: X-XSRF-TOKEN duplication in header request.

### ISSUE THREAD

**Issue by DiHuang1986** [axios/axios#2511]
**Describe the bug**
When using custom request interceptor to add `X-XSRF-Token`, if the header name is not all uppercase, server side will receive a header
```text
X-XSRF-Token=${token}, ${token}
```
and will cause the csrf validation fail.

**To Reproduce**
create a request interceptor as follows:

```js
const X_XSRF_TOKEN = "X-XSRF-Token";

axios.interceptors.request.use(attachCsrfToken);

function attachCsrfToken(config) {
  if (
    document.cookie &&
    document.cookie.length &&
    document.cookie.match(new RegExp(`XSRF-TOKEN=([^;]+)`)).length > 1
  ) {
    let CSRF_TOKEN = document.cookie.match(new RegExp(`XSRF-TOKEN=([^;]+)`))[1];
    config.headers.common[X_XSRF_TOKEN] = CSRF_TOKEN;
  }
  return config;
}
```
and make a request, then view the request in chrome dev tool `network` section. in headers you can see the header
![image](https://user-images.githubusercontent.com/1582003/68043206-20b74680-fcab-11e9-86f9-3ed5fd3ce826.png)

**Expected behavior**
the header shall be 
```text
X-XSRF-Token=${token}
```

**Environment:**
 - Axios Version: 0.17.1
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 77.0.3865.120

**Why it happens:**
in `axios/lib/adapters/xhr.js` at line 102, master branch
axios handle the csrf token by itself. and use the default csrf token name as `X-XSRF-TOKEN`, which is all in uppercase. 
so, in axios is collecting the `requestHeaders`, there will be two tokens exists in the `requestHeaders`, with same name but different case.
```js
// example requestHeaders
{
  "X-XSRF-Token": ${token},
  "X-XSRF-TOKEN": ${token}
} 
```
then, when this `requestHeaders` are used to assign `XMLHttpRequest` header, the 
```js
request.setRequestHeader(key, val); // line 126
```
will ignore the case and consider there are two `x-xsrf-token` exists, then the `XMLHttpRequest` will join them by `, `. 
From https://chromium.googlesource.com/chromium/blink.git/+/99b8c9800ac123eddc3e199088d22569c5294b22/Source/core/xml/XMLHttpRequest.cpp
```cpp
void XMLHttpRequest::setRequestHeaderInternal(const AtomicString& name, const String& value)
{
  HTTPHeaderMap::AddResult result = m_requestHeaders.add(name, value);
  if (!result.isNewEntry)
  result.iterator->value = result.iterator->value + ", " + value;
}
```

**Solution**
1. simple remove the custom interceptor, while the axios handle csrf token for you automatically.
2. use the `X-XSRF-TOKEN` as header name in your custom interceptor, and will avoid the header name duplication.

**Suggestion**
when collecting headers, it is recommended to check existing attribute in the `requestHeaders` and ignore the case, or if some header names are same except case difference, throw a warning is more appropriate.

**Comment by yasuf** [comment]
we have the `xsrfHeaderName` config setting, have you tried using that one? Documentation section https://github.com/axios/axios#request-config

**Comment by DiHuang1986** [comment]
> we have the `xsrfHeaderName` config setting, have you tried using that one? Documentation section https://github.com/axios/axios#request-config

I saw that, and that really help. 
However the little problem here is that:
`requestHeaders` treats headers in **case-sensitive** way, while `XMLHttpRequest` treats headers in **case-insensitive** way. and that might cause problems sometime.

In my case, i already solved the problem, and thanks for help.

**Comment by yasuf** [comment]
I'll create another issue for the case sensitiveness and we'll track the fix there
