### ISSUE TITLE
ECONNECTION Reset error on server side but not on client side

### ISSUE THREAD

**Issue by mnksingh1996** [axios/axios#2512]
Hi, I am getting ECONNECTION Reset Error on requesting the below api from nodejs and on client side I am not getting any error.
And this is a weird behaviour but sometimes 1 time out of 10 times. It works on page refresh as I am using nextjs for server side rendering and using this api on server.

API - https://stagecore.mentorz.com:8443/mentorz/api/v3/user/0/trendingmentors?offset=0&limit=10

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

**Expected behavior**

**Environment:**
 - Axios Version: 0.19
 - OS: Macos Mojave 10.14.5 Beta (18F131a)
 - Browser: Chrome
 - Browser Version:  78.0.3904.70
 - Additional Library Versions - React/React-DOM(16.11.0), Nextjs(9.1.2), express(4.16.4)

**Comment by yasuf** [comment]
It takes a long time to load that data, your request might be timing out, where are you seeing that error?

**Comment by yasuf** [comment]
I would investigate why the error is happening on the server side and try to catch it on axios to see what you get back, do you have a code example to share?

**Comment by mnksingh** [comment]
@yasuf  Its's not timing out. I have tried increasing the timeout interval as well.
On catching the error it just says EConnection Reset, call : system , read and that's it.
I am not getting this error on browser or postman. Only on server. Please find an example for the same below.

```
const express = require("express");

const app = express();

const axios = require("axios");

const instance = axios.create({
  baseURL: "https://stagecore.mentorz.com:8443/mentorz/api"
});

app.use(express.json());

app.get("*", async (req, res) => {
  try {
    const { data } = await instance.get(
      "/v3/user/0/trendingmentors?offset=0&limit=10"
    );

    res.send(data);
  } catch (error) {
    console.log(error);

    res.send(error);
  }
});

app.listen(3333);

```

**Comment by chinesedfan** [comment]
It may be a problem that the server can't response correctly, instead of an issue of axios. Please check the sent request headers and compare the browser's with the server's.

**Comment by chinesedfan** [comment]
Closed due to stale.
