### ISSUE TITLE
Forbidden header name

### ISSUE THREAD

**Issue by Alanscut** [axios/axios#2515]
**Describe the issue**
we could set the HTTP header in `XMLHttpRequest.setRequestHeader()`, however some specified HTTP header can only be set by the user agent for security reasons [Forbidden header name specification](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name). I found that Axios does not limit these request headers, when user set a limited header, such as `Accept-Encoding`, then the browser will response an error like this:
```
xhr.js:124 Refused to set unsafe header "Accept-Encoding"
```

**Example Code**
when we set the header to `Accept-Encoding`, the browser will report an error.  
```js
 var url = 'http://localhost:xxx'
  axios.defaults.headers['Accept-Encoding'] = 'compress';
  axios.get(url).then((res) => {
    console.log(res)
  }).catch(err => {
    console.log(err)
  })
```

**Expected behavior, if applicable**
In my opinion, the program should remote the un-allowed headers, so that the browser wouldn't report errors.

And I have prepared a PR, if you will accept this, then I will submit it later.

**Environment:**
 - Axios Version 0.18.1
 - OS:  win7
 - Browser Chrome
 - Node 10.16.3

**Comment by yasuf** [comment]
do we need to handle this even if browsers already handle this error an accurately describe the issue?
