### ISSUE TITLE
Why would I receive IncomingMessage object?

### ISSUE THREAD

**Issue by DaveStein** [axios/axios#2517]
**Describe the issue**
I have an interceptor to handle all my Axios errors. It's worked fine for about a year but am now seeing weird behavior. Not sure if it's a bug or a feature. When I got a 404 on an API endpoint, the error's `response.data` came in as an `IncomingMessage` object. This meant when I did `JSON.stringify` on the error, I would have a circular reference error. Not sure if there is some way where `IncomingMessage` is expected behavior for 400 errors or anything like that... couldn't find that phrase in issue search or Google.

**Example Code**
Code snippet to illustrate your question

```js
// This is the interceptor I use
const responseError = e => {
  const { config, response } = e;
  const context = {
    request: {
      headers: sanitizeKeys(config.headers),
      method: config.method,
      data: config.data,
      url: config.url
    },
    response: {
      headers: response.headers,
      status: response.status,
      statusText: response.statusText,
      data: response.data // this is not the actual response of the API we hit
    }
  };

  // custom error object that handles context property
  const axiosError = new AxiosError(e.message, context);

  return Promise.reject(axiosError);
};
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version: 0.18.0
 - OS: Alpine Node container - reproduced on Macs & Linux
 - Browser: NodeJS
 - Browser Version: N/A
 - Additional Library Versions:  N/A

**Additional context/Screenshots**
Attaching the JSON of `response.data`. Doing `console.log` on it was fine to print this, but you can see `Circular` a few times.

[axios response data.txt](https://github.com/axios/axios/files/3809819/axios.response.data.txt)

**Comment by chinesedfan** [comment]
@DaveStein Did you use other response interceptors at the same time? Check who throws the error. There may be an interceptor changed the original response.

**Comment by DaveStein** [comment]
No other response interceptors were being used on that axios instance at that time. Nowadays I do have a response success interceptor, but 28 days ago. I've had a request success interceptor the whole time as well.

```js
const requestSuccess = config => {
  config.metadata = {
    ...config.metadata,
    start: new Date()
  };

  return config;
};

const responseSuccess = response => {
  response.config.metadata = {
    ...response.config.metadata,
    end: Date.now()
  };
  response.duration = response.config.metadata.end - response.config.metadata.start;

  const logger = requestLogger();
  if (logger) {
    logger.info(CHANNEL_EXTERNAL_RESPONSE_TIMES, 'Response time logged', {
      url: response.config.url,
      method: response.config.method,
      duration: response.duration
    });
  }

  return response;
};
```

**Comment by jennynju** [comment]
@DaveStein, for your information, I'm trying to reproduce your problem but I got my body as response.data as expected. This is the code I'm using: 
``` 
        var axiosInstance = axios.create(axiosConfig);
        axiosInstance.interceptors.request.use(requestSuccess);
        axiosInstance.interceptors.response.use(responseSuccess, responseError); // Your interceptors 
        axiosInstance.get(url, data)
            .then(function (res) { ...
            })
            .catch(function (err) { ...
            });
        };
```

**Comment by chinesedfan** [comment]
Closed due to stale.
