### ISSUE TITLE
Axios Needs Debug Mode for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by rudiw** [axios/axios#2518]
I want to share about using last version of `Axios`, it is `0.19.0`. When I hit as `POST` using `application/x-www-form-urlencoded` as `content-type`, it must be **Debug Mode**.  So, I downgrade to `0.16.2`, it **doesn't** need Debug Mode

**Environment:**
 - Axios Version 0.19.0
 - OS: Windows 10 64 bit
 - React Native 0.61.2
 - Emulator Android SDK 25
 - React 16.11.0

**Comment by chinesedfan** [comment]
@rudiw Can you provide more details about the unexpected response data or error messages?

**Comment by chinesedfan** [comment]
@rudiw Then can you revert to 0.16 to check again? Without enough information, I am afraid that I can not help you find the reason. You can compare request headers between axios and postman.

**Comment by chinesedfan** [comment]
Closed due to stale.
