### ISSUE TITLE
Unable to make a POST request

### ISSUE THREAD

**Issue by stoplion** [axios/axios#2519]
We've switched from fetch to axios we are unable to make a POST request. 

The options for `Axios`:
```
const options = {
  "withCredentials": true,
  "method": "post",
   "data": FormData
  "headers": {
    "content-type": "multipart/form-data",
    "csrf-token": "5uD5mZqO-BKqeC-GjNnGZ2Qp_H2-iTzElYvo"
  }
}
```

```
return axios({
    url,
    options
  });
```

Always results in a `GET` request. 

I've inspected the options being set on Axios and it is correctly getting it to `POST`  and the FormData object is not empty.

**Comment by donkasun** [comment]
what was the issue? Kinda facing the same problem
