### ISSUE TITLE
Could you explain the use case for flattening request headers?

### ISSUE THREAD

**Issue by czajkowski** [axios/axios#2523]
dispatchRequest() method has a functionality for flattening request headers:

```js
  config.headers = utils.merge(
    config.headers.common || {},
    config.headers[config.method] || {},
    config.headers || {}
  );
```

Could you please explain what is the use case here? Especially the **config.headers[config.method]** part.

I am trying to make a LINK. When I add a 'link' header its value is also added to the header object under a '0' property key.

```js
axios.request({url:'/', method:'LINK', headers: {'link':123}})
```

Makes a request with headers:
```
0: 123
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
link: 123
...
```

**Comment by yasuf** [comment]
the 0 part I don't think should be there, not sure why that's being added but the logic there takes in headers from 3 different parts and the last ones override the first ones:
1.  `common` which come from `defaults.js`, you can check that fore more info
2.  the second one `config.headers[config.method]` also takes headers from the defaults depending on which verb is being used
3. the headers you specify on the request

**Comment by yasuf** [comment]
closing until we get more info on this
