### ISSUE TITLE
Post cascading objects

### ISSUE THREAD

**Issue by alex-pouivet** [axios/axios#2524]
**Describe the issue**
Hi, 
For my project I use NuxtJs with Laravel, and the axios module.
Every time I tried to post my data with cascading objects, the request is ok, but my information never changes, I think it's because I don't use the right indentation.
This is how I write it, can you help me please ?

```
const returnData = {
  "name": this.store.name,
  "description": this.store.description,
  "quote": this.store.quote,
  "address": [
    {
      "address": this.store.address.address,
      "city": this.store.address.city,
      "zip_code": this.store.address.zip_code,
    },
  ]
}
console.log(this.store.address.address)
 await this.$axios.post(`/store/update/${this.$route.params.id}`, returnData)
 .then(res => {
 console.log(res)
})
.catch(error => {
     console.log(error)
})
```

**Comment by Alanscut** [comment]
hey, I think the `res` has nothing to do with indentation, and the usage of cascaing objects is correct. Could you provide the log of `this.store.address.address` and `res` or more information? maybe the problem is with the backend program.

**Comment by alex-pouivet** [comment]
Hi, yes you were right it was a problem with the backend. Thank you about that, now it's working perfectly with the cascaing objects.
