### ISSUE TITLE
"Network Error" for valid HTTPS request on Android

### ISSUE THREAD

**Issue by p3v9d5ui** [axios/axios#2526]
Hi Everyone,

My Cordova app on Android using Axios 0.17.1 and 0.19.0 is now not able to make requests (HTTPS). I always get a "Network Error". The only think I've changed recently is that I've set minSdkVersion to 26.  

Everything works fine on iOS 13

Any ideas?

**Environment:**
 - Axios Version 0.17.1 and 0.19.0 
 - OS: Android 8
 - Browser wkwebview 1.1.4
 - Additional Library Version: Cordova 9.0.1, Android platform 8.1.0

**Comment by bmcn99** [comment]
Did you find a solution for this? I am in the same boat, HTTP works fine and HTTPS comes back with a generic network error every time.

**Comment by p3v9d5ui** [comment]
This was unrelated to Axios. Another plugin was intefering with the network connection.
