### ISSUE TITLE
axios.get() hangs indefinitely

### ISSUE THREAD

**Issue by jpavlick** [axios/axios#2527]
**Describe the issue**
I have a Node application that consumes from a Kafka stream, transforms some data, and then makes a `GET` request to an internal API. I am running into an issue where the `axios.get()` request is hanging indefinitely. It doesn't ever time out, it just sits there until I kill the program. This seems to be an issue specific to Axios, as I replaced it with `request-promise-native` and was able to successfully make requests. I don't have much other information currently, but if there is a way to get more debug information I would be happy to do that and post the results here.

**Example Code**
Code snippet to illustrate your question

```js
function update(id, revision, organizationId, text) {
    let organization;

    try {
      organization = organizationLookup(organizationId, environment, logger);
    } catch (err) {
      logger.error(err, `Failed to look up organization ${organizationId}`);
      return;
    }

    const { slug } = organization;
    const apiHostname = organization.metadata.api.stringValue;

    const endpoint = `https://${apiHostname}/photos/${id}`;

    try {
      return await axios.get(endpoint); // <-- Code gets here and just stops
    } catch (err) {
      logger.error(err);
      throw err;
    }
}
```

**Expected behavior, if applicable**
I would expect to get a response from the API that I make a request to and for my code to continue.

**Environment:**
 - Axios Version: 0.19.0
 - OS: OSX 10.12.6, centos:7.6.1810
 - Browser N/A (in node)
 - Browser Version N/A (in node)
 - Additional Library Versions: koa 2.7.0, node-rdkafka 2.6.1, async-retry 1.2.3

**Additional context/Screenshots**
I am using `async-retry` in my code, but to test this I removed that, and the problem persisted, so I do not think it is due to that library's use.

**Comment by chinesedfan** [comment]
@jpavlick First of all, I am a little curious that your `await` statement is not in an `async` function.

**Comment by dennismphil** [comment]
I noticed for a specific private url axios hangs(the promise remains pending and never resolves) with Node 13.x and works with Node 12.x. I can do HTTP GET to the same url with other clients like postman with no issues.

This is an issue only with one particular internal url.

## Node v13
```
node -v
v13.9.0
```

```
axios({
    url: 'https://example.com/internal/url', 
    headers: {authorization: 'Bearer token'}, 
    params: {
        key: 'value'
    }
})
.then((data) => console.log(data))

// Promise { <pending> }
```

## Node v12
```
node -v
v13.9.0
```

```
axios({
    url: 'https://example.com/internal/url', 
    headers: {authorization: 'Bearer token'}, 
    params: {
        key: 'value'
    }
})
.then((data) => console.log(data))

// Promise { <resolves> }
```


This is really strange. For anyone with the same issue, try downgrading node to v12.

**Comment by chinesedfan** [comment]
@dennismphil Thanks for your update and forgive me closing this issue as the original author didn't give feedbacks. Many things can result in hanging infinitely. Node.js 13.9 is just released, so you are facing another problem.

You can comparing the sent url and headers in axios/lib/adapters/http.js and try to reproduce by a pure `require('http')` example. And open an issue to Node.js if the http example still has the problem.
