### ISSUE TITLE
Axios adapter is never get the value not inside the default and neither inside requestDispatcher its always undefined

### ISSUE THREAD

**Issue by jadzeino** [axios/axios#2528]
**Describe the bug**
the adapter is never assigned even in the init class where its supposed to be init by either http adapter or hxr one
**

**To Reproduce**
looks like aws-amplify library is using Axios when it call sub library
import API from '@aws-amplify/api'
and after setting  API.configure and run test you will find that the adapter  is never set 
and will show axios adapter not a function
i even tried to set it manually just to see if its ganna work or not but it looks like the way its imported it not working at all
please check the setDefaultAdapter
**

```js
// Example code here
import API from '@aws-amplify/api'

await API.configure({
        endpoints: [
            {
                 name: 'cap',
                endpoint: process.env.REACT_APP_API_URL,
                 region: process.env.REACT_APP_REGION,
                 custom_header: async () => {
                     return {
                         Authorization: (await Auth.currentSession()).idToken
                            .jwtToken
                     }
                 }
             }
        ]
     })

and  later in thetest
test.serial('GET List of Campaigns ', async t => {
    const {data, headers} = await API.get('cmt', '/campaigns', {
        response: true, // returns the entire Axios response, not only data, so that we can test custom headers
        queryStringParameters: {            
            filter: '{}',
            range: `[0, ${LIMIT}]`,
            sort: '["id", "DESC"]'
        }
    }).catch(error => {        
        return error
    })
    t.true(Array.isArray(data))
    t.is(data.length, PAGINATION_SIZE)    
})



```

**Expected behavior**
Adapter should be set either by default or if its include in the configuration

**Environment:**
 - Axios Version [ 0.19.0]
 - OS: [iOS 12.1.0, OSX 10.13.4]
 - Browser [ Chrome]
 - Browser Version [latest]
 - Additional Library Versions [React 16.7, aws-amplify ,ava]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
Sorry I don't know how @aws-amplify/api uses axios. The better way is to open an issue to maintainers of that package.
