### ISSUE TITLE
is axios still actively maintained?

### ISSUE THREAD

**Issue by DanielRuf** [axios/axios#2531]
It seems there is currently not much happening.

Is axios still actively maintained and supported? Because the amount of open issues shows a different picture.

**Comment by Alanscut** [comment]
hi Daniel, @yasuf is actively maintaining this project currently, he is the new maintainer. I think he will handle many of them in the near future, and I will solve some issues as much as possible.

**Comment by DanielRuf** [comment]
> hi Daniel, @yasuf is actively maintaining this project currently, he is the new maintainer. I think he will handle many of them in the near future, and I will solve some issues as much as possible.

Well, there is no clear communication and I don't think one person alone can handle all of this.

**Comment by DanielRuf** [comment]
The main problem stays, there are not many active maintainers or contributors who work more on axios.

In the short- and longterm it makes more sense to consider the alternative solutions. 600 open issues and 140 open PRs is much. Even I could not handle this (and here is more activity than on projects like foundation-sites).

**Comment by yasuf** [comment]
what's your proposal @DanielRuf ? I'm trying my best to decrease the amount of issues and start merging PRs for future releases, duplicate of https://github.com/axios/axios/issues/1965

**Comment by yasuf** [comment]
contributions are welcome @DanielRuf !
