### ISSUE TITLE
confusion regarding best practice for using transformResponse in request for running in nodejs (e.g. jest tests) and browser environments

### ISSUE THREAD

**Issue by dcs3spp** [axios/axios#2532]
Hi,

I am familiarising myself with _axios_ and so far finding it great...
- no installing pollyfills for running jest tests :)
- correct and explicit reporting of NetworkError.

I have experienced difficulty and confusion transforming the response from the library. I found that I had to use two transform functions to allow transformation correctly in a nodejs environment.

1. (data: string) => // this seems to be applicable in a nodejs environment only. I had to use ```JSON.parse``` here to convert response data into a typed object.
2. (data: MyEntityType[]) => // transform typed object from response.data to another object type.

Initially when running in a NodeJS environment, e.g. (for running jest tests) ...I only included a single transform function as: (data: MyEntityType[]): MyTransformedEntity[]. I was using ```Array map``` function to perform transformation and an exception was thrown by runtime to indicate that map is not a function. This was because the type of data for the transform function was a string when running jest tests in nodejs environment. Consequently, I had to use ```JSON.parse``` to transform response data into a typed object.
 
An example is included in the code snippet below.....

``` typescript
const url = `${APP_CONF.apiBaseURL}/course`;

    const config: AxiosRequestConfig = {
      method: 'get',
      url: url,
      responseType: 'json',
      transformResponse: [
        (data: string) => {
          if (typeof data === 'string') {
            const s: string = typeof data;
            console.log(`transformation string = > response type for ${s}`);
            try {
              const parsed: CourseJSON[] = JSON.parse(data);
              return parsed;
            } catch (e) {}
          }
          return data;
        },
        (data: CourseJSON[]) => {
          const s: string = typeof data;
          console.log(`transformation response type CourseJSON ${s}`);
          return data.map(item => ({
            courseID: item.CourseID,
            courseName: item.CourseName,
          }));
        },
      ],
    };

    const request: Promise<AxiosResponse<Course[]>> = axios.request<Course[]>(
      config,
    ); 
```
Is this assumption correct?

**Comment by yasuf** [comment]
you seem to be doing a lot on your `transformResponse`, that seems pretty specific to that endpoint and could just be inside the `.then` callback, since `axios` is promise based in that way you could take advantage of its features, unless `CourseJSON` is a class that you'll use for all responses, maybe you can just `JSON.parse` the response in `transformResponse` and do the `map` in the `.then`. Let me know if this helps!

**Comment by chinesedfan** [comment]
Whether you need 1 or 2 transform functions depends on what your server returns. It is usually a string. And nothing related Node.js or browser environment.

This issue will be closed first unless you have further questions.
