### ISSUE TITLE
Nested params option not works as expected

### ISSUE THREAD

**Issue by mahnunchik** [axios/axios#2534]
**Describe the bug**

Nested `params` option not works as expected.

**To Reproduce**

```js
axios.post('/user', {
    params: {
      ID: 12345
    }
  })
```

**Expected behavior**

Send request to `/user?ID=12345`

**Actual behavior**

Send `{"params": {  "ID": 12345 }}`

**Environment:**
 - Axios Version: 0.19.0
 - OS: OSX 10.14.6

**Additional context/Screenshots**
NodeJS v10.16.3

**Comment by yasuf** [comment]
you're doing a `post` request, URL parameters are used in GET requests and a few other methods. POST requests take in the data on the body, `data` in axios' config

**Comment by mahnunchik** [comment]
@yasuf You **may** use URL parameters with `POST` request. Example: Trello API https://developers.trello.com/reference#cards-2

**Comment by antonkomarev** [comment]
`POST` requests allowed to have parameters too. For example when you want to specify related resources required to be in response: `POST /articles?include=author,comments`
