### ISSUE TITLE
Network Error" for valid HTTPS request on Android

### ISSUE THREAD

**Issue by NareshNama** [axios/axios#2539]
it is not working in android (react native app)

**Comment by ngocdh383** [comment]
the same problem

**Comment by rodgomesc** [comment]
same problem

**Comment by NareshNama** [comment]
any solution ?

**Comment by bmcn99** [comment]
Just ran into this, we were using the same code pointed to few different http servers without issue. Today I pointed it at our final https location and am now getting the same generic "Network error". I read here: https://github.com/axios/axios/issues/973#issuecomment-329967881 that android https is not supported by axios but that is for the emulator only.. right? My error is on a Samsung A5 android physical device.

**Comment by chinesedfan** [comment]
Duplicate of #973. Let's track in there.

**Comment by a728384698** [comment]
https://www.jianshu.com/p/5d67e719606a

**Comment by a728384698** [comment]
https://www.jianshu.com/p/5d67e719606a

**Comment by magic990619** [comment]
same here
