### ISSUE TITLE
http(s)Agent not sent properly to follow-redirects

### ISSUE THREAD

**Issue by mhassan1** [axios/axios#2546]
**Describe the bug**
In https://github.com/axios/axios/pull/2426, `axios` started passing `agents` to `follow-redirects`; however, the documentation for `follow-redirects` shows the shape of `agents` differently than what `axios` is passing. It means that an alternative agent is not correctly resolved by `follow-redirects`.

**To Reproduce**
Pass in an `httpsAgent` with an invalid configuration, which should cause `axios.request` to reject. In `0.19.0`, it rejects; on `master`, it does not. See code snippet below.

```js
require('axios')({
  url: 'https://postman-echo.com/get',
  httpsAgent: new require('https').Agent({
    ciphers: 'does-not-exist'
  })
}).catch(err => console.error(err.message))
```

**Expected behavior**
httpsAgent should be passed to `follow-redirects`

**Environment:**
 - Axios Version: master (unreleased 0.19.1)
 - OS: OSX 10.15
 - Node 8

**Comment by chinesedfan** [comment]
Solved by #1904 and released to 0.19.1 yet.
