### ISSUE TITLE
ZIP file corrupted . Using Axios POST method .

### ISSUE THREAD

**Issue by gmumdzhiev** [axios/axios#2548]
Hey guys , 
I think that i am doing something wrong , but when i click on my button i get an zip file , but it says that is corrupted when i try to open it . What am i doing wrong ? 

`getZip = () => {

        let postZipData = {
            customerNumber: this.state.customerNumber,
            docList: this.state.docList,

        }

        const token = localStorage.getItem('token');
        const axiosConfig = {

            responseType: 'arraybuffer',
            header: {
                'Content-Type': 'multipart/form-data',
                'Access-Control-Allow-Origin': '*',
                'Authorization': 'Bearer ' + token
            }
        };

        axios.post(SERVER_URL + '/api/user/bills/zip', postZipData, axiosConfig)

            .then((response) => {
                const url = new Blob([response.data],{
                    type:'application/zip'
                });
                const link = document.createElement('a');
                link.href = url;
                link.setAttribute('download', 'file.zip');
                document.body.appendChild(link);
                link.click();
            })
        console.log('get the zip')
    }`

**Comment by Alanscut** [comment]
try to config:
```
headers:{
           'Content-Type': 'application/json; application/octet-stream'
},
 responseType: 'blob'
```

**Comment by gmumdzhiev** [comment]
@Alanscut  . The same ... the problem is that the response body coming from the BE is in binary 
This is an response when button is clicked to download , but file is not selected : 
![json2](https://user-images.githubusercontent.com/32012354/68775747-4fc8a300-062f-11ea-9995-7d0d552c68e0.jpg)
This is an response when button is clicked to download and a file is selected : 
![json](https://user-images.githubusercontent.com/32012354/68775816-6242dc80-062f-11ea-91bd-76fad0ee8f8e.jpg)

Maybe some how i should use base64 ? I don't know , i don't have any idea how to fix that .

**Comment by lednhatkhanh** [comment]
I got the same error trying to download a `zip` file using axios, has the `responseType: arraybuffer` set correctly and still got the corrupted file error

**Comment by tung83** [comment]
I got the same issue of this. You can try my working around from my code to use XMLHttpRequest straight away!
 var xhr = new XMLHttpRequest();
    //xhr.responseType = 'arraybuffer';
    const { accessToken } = useState('Auth', ['accessToken'])
    xhr.open('GET', baseAddress + url, true);
    xhr.responseType = "blob"; // changed this to arraybuffer but did not work as well
    //xhr.withCredentials = true;
    // xhr.setRequestHeader('Authorization', 'Bearer ' + accessToken.value); open if you have jwt
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4) {
        var blob = xhr.response
        // var filename = defaultFileName
        // var disposition = xhr.getResponseHeader('Content-Disposition')
        // if (disposition) {
        //   var filenameRegex = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/
        //   var matches = filenameRegex.exec(disposition)
        //   if (matches != null && matches[1]) {
        //     filename = matches[1].replace(/['"]/g, '')
        //   }
        // }
        FileSaver.saveAs(blob, 'filename.zip')
      }
    }
    xhr.send()
        FileSaver.saveAs(blob, filename);
      }
    };
    xhr.send();

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
