### ISSUE TITLE
Multiform File Upload Not Working (!)

### ISSUE THREAD

**Issue by patientplatypus** [axios/axios#2549]
Here is the stackoverflow question (not reproducing here but in depth): https://stackoverflow.com/questions/58842311/play-framework-file-upload-not-working-react-scala. 

Please fix this, I've wasted hours on this nonsense.

**Comment by patientplatypus** [comment]
Did this https://github.com/axios/axios/issues/318 *ever* get resolved?

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

Please open a new issue, instead of editing the current one.
