### ISSUE TITLE
Adding Request and Response interceptors adds 500+ms to the timing of the request

### ISSUE THREAD

**Issue by DMCApps** [axios/axios#2550]
Hello,

I'm using axios to perform my networking requests but I've noticed that adding in the request and response interceptors is adding 500ms to my requests. I'm making a mobile responsive website that I'm attempting to optimize and noticed this extra time addition.

I am using the request interceptor to check the health of my access token, update the token when needed, and add the token to the header then proceed with the request. I've trimmed this down to only adding the token to the header and it looks like this adds 500ms delay still with minimal processing on my end.

The time without the request and response interceptors is doing the same pre/post processing manually before calling `axios.get()` and using the `Promise` to perform post processing.

Note: These times are the average of 10 requests to ensure it is not a varience of the server itself.

```
// Request with request and response interceptors
[API] - Response /endpoint 1123
// Request without request and response interceptors
[API] - Response /endpoint 616
```

**Comment by yasuf** [comment]
I'd need to know what's happening in the interceptor to really know why it's adding so that much delay, seems very noticeable, is it a hashing function or something similar? is there a way you could provide an example?

**Comment by DMCApps** [comment]
Closing I'm not sure what was going on when I initially had this but seems like I fixed up whatever was causing the delay.
