### ISSUE TITLE
Add allSettled method for axios

### ISSUE THREAD

**Issue by thomaslwq** [axios/axios#2556]
We sometimes need wait until all promises have settled (each may resolve, or reject).
So I wonther whether there is a mothed like [allSettled](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) ,that means a promise that resolves after all of the given promises have either resolved or rejected, with an array of objects that each describe the outcome of each promise.

**Comment by G07cha** [comment]
How would you expect it to look like?

Since axios calls return promises you can do this(given your environment supports `allSettled`):

```
Promise.allSettled([
  axios.get('/sample-get'),
  axios.post('/sample-post')
]).then((result) => {
  // `result` should contain an array of either http responses or errors
})
```

**Comment by thomaslwq** [comment]
Thanks for your reply,you are right.What Promise can do,so can axios :).But I think axios is a promise based HTTP client for the browser and node.js,it is a wrapper of promise,so if axios could provide directly API to support it,it will more intuitive. For example :)
```js
axios.allSettled([
   promise1,promise2
]).then((result) => {
  // `result` should contain an array of either http responses or errors
})
```

**Comment by thomaslwq** [comment]
Thanks for your reply,you are right.What Promise can do,so can axios :).But I think axios is a promise based HTTP client for the browser and node.js,it is a wrapper of promise,so if axios could provide directly API to support it,it will more intuitive. For example :)
```js
axios.allSettled([
   promise1,promise2
]).then((result) => {
  // `result` should contain an array of either http responses or errors
})
```

**Comment by thomaslwq** [comment]
> How would you expect it to look like?
> 
> Since axios calls return promises you can do this(given your environment supports `allSettled`):
> 
> ```
> Promise.allSettled([
>   axios.get('/sample-get'),
>   axios.post('/sample-post')
> ]).then((result) => {
>   // `result` should contain an array of either http responses or errors
> })
> ```
Thanks for your reply,you are right.What Promise can do,so can axios :).But I think axios is a promise based HTTP client for the browser and node.js,it is a wrapper of promise,so if axios could provide directly API to support it,it will more intuitive. For example :)
```js
axios.allSettled([
   promise1,promise2
]).then((result) => {
  // `result` should contain an array of either http responses or errors
})
```

**Comment by G07cha** [comment]
Well, there are two kinds of "Promises" we're talking about, "Promise" as an object/class(`Promise.allSettled`, `Promise.all`, `Promise.race`, Promise constructor) and an instance of a Promise(e.g. result of `new Promise()`). Axios uses available Promise object/class to create instances of it and return them. Because of that it's very flexible and lightweight, imagine if axios shipped with their own implementation of promises? That would increase the bundle size by a lot! Also, the maintenance aspect of it, axios currently has ton of issues in backlog, having to maintain implementation of promises very likely will be out of scope for library developers.

All in all, I'd suggest using native `Promise.allSettled` or a [polyfill](https://www.npmjs.com/package/promise.allsettled), you wouldn't notice a difference! 🙂

**Comment by thomaslwq** [comment]
> Well, there are two kinds of "Promises" we're talking about, "Promise" as an object/class(`Promise.allSettled`, `Promise.all`, `Promise.race`, Promise constructor) and an instance of a Promise(e.g. result of `new Promise()`). Axios uses available Promise object/class to create instances of it and return them. Because of that it's very flexible and lightweight, imagine if axios shipped with their own implementation of promises? That would increase the bundle size by a lot! Also, the maintenance aspect of it, axios currently has ton of issues in backlog, having to maintain implementation of promises very likely will be out of scope for library developers.
> 
> All in all, I'd suggest using native `Promise.allSettled` or a [polyfill](https://www.npmjs.com/package/promise.allsettled), you wouldn't notice a difference! 🙂

Thanks for your reply :).  A  polyfill is a "too heavy" way to implement it. As you said Axios uses available Promise object/class to create instances of it and return them. So I think `axios.allSettled` is just a wrapper of native `Promise`. This will not take of much time to add it to the library,but make it more convenient for the API caller.🙂

**Comment by G07cha** [comment]
Indeed, but what if there is no native method available? And even then, you're right, it would take much effort to add own implementation of `allSettled` but what about other static methods, do we need to implement all of them? In case if your environment does provide `allSettled` method you can monkey-patch axios like so:

```
axios.allSettled = Promise.allSettled
```

I would personally discourage from such practice but you are free to do so if it makes it more convenient for you.

**Comment by thomaslwq** [comment]
> Indeed, but what if there is no native method available? And even then, you're right, it would take much effort to add own implementation of `allSettled` but what about other static methods, do we need to implement all of them? In case if your environment does provide `allSettled` method you can monkey-patch axios like so:
> 
> ```
> axios.allSettled = Promise.allSettled
> ```
> 
> I would personally discourage from such practice but you are free to do so if it makes it more convenient for you.

Thanks for your reply. `axios.allSettled = Promise.allSettled` is way to solve this issue but it is a unappealing method. Indeed,there is a slightly difference between [Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) and [Promise.allSettled](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)
