### ISSUE TITLE
file schema

### ISSUE THREAD

**Issue by mairasala** [axios/axios#2558]
When loading a file, the `settle` method doesn't resolve the promise properly on v0.19.0, as the validation is done against the response.status, which is 0.

This has been changed in this commit:
https://github.com/axios/axios/commit/503418718f669fcc674719fd862b355605d7b41f#diff-b19c56bc1192e2f4840a79ffebfe1d7bR14

perhaps more information should be sent to the validation method? So it is possible to validate the response by checking something else.

**Comment by Alanscut** [comment]
https://github.com/axios/axios/issues/2416#issuecomment-543033567 could solve your issue.
