### ISSUE TITLE
Standard function signatures across all methods

### ISSUE THREAD

**Issue by lonewarrior556** [axios/axios#2565]
**Is your feature request related to a problem? Please describe.**

I am trying to type out our api using typescript. It looks something like this

```
post1: (config?: Config1) => axios.post<RespType1>('url1', null, config)
post2: (data: Data2, config?: Config2) => axios.post<RespType2>('url2', data, config)
get1(config: Config3) => axios.get<RespType3>('url3', config)
get2(config?: Config4) => axios.get<RespTyp4e>('url4', config) 
```
^^ aka it looks crappy ^^ 

It's hard keeping track of when I need to pass in data, the order, and  when there is no data to pass in and when it's optional, 
Also I am forced to import sometimes 3 sometime 2 Types to get the signature right.. 

---------------------

#### Why can't we standardize axios calls to have only one data argument?
ie. the  `AxiosRequestConfig` could have `body: any` same as it has `params: any`?
(some people use get's with body, some use post with params so this isn't that weird)

Anyway with that small change I never have to worry about getting it right. 
It would look like this..
```
post1: (config: Config1) => axios.post<RespType1>('url1', config)
post2: (config: Config2) => axios.post<RespType2>('url2', config)
get3(config: Config3) => axios.get<RespType4>('url3', config)
get4(config: Config4) => axios.get<RespType4>('url4', config)
```

Then I can modify anything I need with only types
```
export interface Config1 extends AxiosRequestConfig {
  params?: never;
  body?: string[]
}
export interface Config2 extends AxiosRequestConfig {
  params?: never;
  body: Record<string, number>;
}
export interface Config3 extends AxiosRequestConfig {
  params: {id: string, count?: number};
  body?: never
}
export interface Config4 extends AxiosRequestConfig {
  params?: {mock?: boolean};
  body?: never
}
```

**Comment by yasuf** [comment]
is there a reason why you need post1 and post2? couldn't it just be 1 type of post and you pass null do `data`? maybe I'm missing something but it would help me understand this better

**Comment by lonewarrior556** [comment]
you could, It's not the worst thing, and any reason alone isn't worth it.. 
But things have been stacking where it would solve a lot of "tiny" issues

1. 'null is required' is not a pleasant error to get when the body is not required. 

2. 'I'm using the method in the name.. The functions name are actually
```
SearchForProperty()  // a get
RenewReservation() //  a post
ListAlphaResources()  // a get
SearchForResource()  // a post
...
and now If you need to start passing a config into all off them it's alot of manual labor
```
SearchForProperty({timeout: 5000}):  // a get
RenewReservation(null, {timeout: 5000): // a post
ListAlphaResources({timeout: 5000}):  // a get
SearchForResource(null, {timeout: 5000}):  // a post
...continued
```

3. we've gone with this approach and it had introduced a lot of errors...
```
const SearchForProperty = (...args: [AxiosRequestConfig?]) => api.get('url', ...args)
const RenewReservation = (...args: [any, AxiosRequestConfig?]) => api.post('url', ...args)
const ListAlphaResources = (...args: [AxiosRequestConfig?]) =>  api.get('url', ...args)
const SearchForResource = (...args: [any, AxiosRequestConfig?]) =>  api.post('url', ...args)

const config: AxiosRequestConfig = {
  timeout: 3000
}

SearchForProperty(config)
RenewReservation(config) // not expected, no error
ListAlphaResources(config)
SearchForResource(config) // not expected, no error
```

I can prob list more minor annoyances.. 
But what are the drawbacks?

**Comment by chinesedfan** [comment]
> Why can't we standardize axios calls to have only one data argument?

I think we already have the function, `axios.request`.

```
request<T = any, R = AxiosResponse<T>> (config: AxiosRequestConfig): Promise<R>;
```
