### ISSUE TITLE
Attachment file gets currupted 

### ISSUE THREAD

**Issue by vkiranmaniya** [axios/axios#2569]
**Describe the bug**
Attachment downloaded by Axios get courrupted when the server is using gzip compression.

**To Reproduce**
```js
function restoreDatabase(PATH , UID , TOKEN , URL){
return new Promise((resolve , reject) => {
        axios({
            URL,
            method: 'POST',
            responseType: 'document',
            headers: {
                'Authorization': TOKEN
            },
            data: {
                uid: UID
            }
        }).then(response => {
            console.log(response);
            fs.writeFile(PATH , response.data , (err) => {
                if(err){
                    console.log(err);
                    reject(err);
                }
                resolve();
            })
        }).catch(e => {
            console.log(e);
        })
    });
}
```

**Expected behavior**
File should be downloaded as is, here i'm downloading the file having .sqlite3 (Content-Type application/x-sqlite-3) and it gets courrupted.

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: MacOS 10.13.6
 - Browser Chromium (Using Electron)
 - Browser Version Electron Specified

**Additional context/Screenshots**
The Complete issue is being discussed over [https://stackoverflow.com/questions/59027946/axios-post-request-returns-attachment-storing-it-gives-mulformed-file-exception](url)

**Comment by Tusko** [comment]
responseType: "arraybuffer",

will be better

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Keep tracking in your stackoverflow questions.

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
