### ISSUE TITLE
Docs Website

### ISSUE THREAD

**Issue by mzabriskie** [axios/axios#257]
[README](https://github.com/mzabriskie/axios/blob/master/README.md) is getting cluttered and difficult to read. Would be great to transition to a proper documentation site.
- Documentation of features
- [Examples](https://github.com/mzabriskie/axios/tree/master/examples)
- [Cook book](https://github.com/mzabriskie/axios/blob/master/COOKBOOK.md) recipes
- [Upgrade Guide](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md)
- Modules that are related (e.g., [axios-response-logger](https://github.com/srph/axios-response-logger))

This could be done rather easily using gh-pages and [gatsby](https://github.com/gatsbyjs/gatsby).

**Comment by mzabriskie** [comment]
Another option for this would be to use GH wiki

**Comment by nickuraltsev** [comment]
GH wiki doesn't support pull requests as far as I understand. It's a separate git repository. So when someone submits a PR that adds a new feature, they won't be able to update the documentation in the same PR.

**Comment by rubennorte** [comment]
I'd use a `docs` directory with markdown files and any static site generator as [MKDocs](http://www.mkdocs.org/).

**Comment by Cameron-C-Chapman** [comment]
@rubennorte would you be open to using [Docusaurus](https://github.com/facebook/Docusaurus) instead of MKDocs? It is pretty similar but doesn't require Python to build, just an npm package.

**Comment by jasonsaayman** [comment]
I don't think this is going to get done any time soon. The issue is also stale so for now, I think its best we close this and then re-open it when there is a possibility of this being completed.
