### ISSUE TITLE
403 every time using Amplify

### ISSUE THREAD

**Issue by SavedByZero** [axios/axios#2571]
I’m getting a 403 every time I make a call to post to Twitter using axios. What I don’t understand is that the login / callback through twitter works fine, but the post doesn’t, and I have all the credentials it asks for but they’re being ignored. 

I’m using AWS amplify for my server. Is that a problem?

I ask that because I *think* our axios call was successfully posting when the project was on a regular AWS EC2 server and not Amplify.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

If you confirm that axios sends wrong headers, feel free to remind me to reopen.
