### ISSUE TITLE
Error: Request failed with status code 422, at createError (createError.js:17)

### ISSUE THREAD

**Issue by BlackMG27** [axios/axios#2572]
I am having trouble with my routes. the react front end keeps giving me `POST http://localhost:3000/api/review/ 422 (Unprocessable Entity)` when I try to submit reviews, and   `GET http://localhost:3000/api/review/movie/tt1825683 422 (Unprocessable Entity` when I try to get reviews by imdbID. 

Axios code
```js
createReview: review => {
        const data = {
            data: review
        }
        return axios.post('/api/review/', data);
    },

    showMovieReviews: id => {
        return axios.get('/api/review/movie/' + id);
    }
showCommentsByReview: id => {
        return axios.get('/api/comment/review/' + id);
    }
```
Movie.jsx
```js
componentDidMount() {
        API.showMovieReviews(this.props.location.state.imdbID).then((reviews => {
            API.showCommentsByReview(reviews.reviewId).then(comment => console.log("Success", comment)).catch(err => console.log(err));
        })).catch(err => console.log(err));
    }
```

**Expected behavior, if applicable**
The routes should go the backend without issue.

**Environment:**
 - Axios Version 0.19.0
 - Browser: Google Chrome 
 - React 16.12.0

Thanks in advance

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

If you confirm that axios sends wrong headers, feel free to remind me to reopen.

**Comment by GhayoorUlHaq** [comment]
API in post man works fine but getting same error in react-native using redux (createError.js:16)

**Comment by ZiedHf** [comment]
@chinesedfan Please before closing take a look into the issue.
I don't think stackoverflow will help.
I confirm this issue and I changed axios in my react native app.
![image](https://user-images.githubusercontent.com/7974028/74688891-50964580-51d9-11ea-8eec-e70baa9431b2.png)
