### ISSUE TITLE
merge defaults.data use Object.assign

### ISSUE THREAD

**Issue by idler8** [axios/axios#2573]
**Is your feature request related to a problem? Please describe.**
Such as the title

**Describe the solution you'd like**
Such as the title

**Describe alternatives you've considered**
A common configuration
Merge to params on get
Merge to data at post

**Additional context**
empty

**Comment by Alanscut** [comment]
'Axios does not currently support the syntax of 'ES6'

**Comment by idler8** [comment]
This is a metaphor.
I need to bring the `defaults.data` with each request.

**Comment by idler8** [comment]
@Alanscut

**Comment by Alanscut** [comment]
That's embarrassing... I don't think global data configuration is a univeral requirement, but you still could do it by configuring a global `request interceptor`
