### ISSUE TITLE
Post request, part of JSON data missing

### ISSUE THREAD

**Issue by 423967mv** [axios/axios#2575]
#### Summary

When I post a nested object, a part of the object is not put on the request body.

#### Context

- axios version: "^0.19.0"
- Environment: Node v10.16.0, React application, Chrome v78.0.3904.108, Windows 10 64-bit

#### Code

Requestconfig:

` let axiosConfig: AxiosRequestConfig = {
        method,
        url,
        headers,
        data
      };`

The config console logged:
![image](https://user-images.githubusercontent.com/10938112/69710370-8efef580-10ff-11ea-96c4-1985a315948a.png)

The part in the green box vanishes when the actual call happens, as can be seen in the image below.

Call code:

` result = (await axios(axiosConfig)).data;`

Request body in Chrome:

![image](https://user-images.githubusercontent.com/10938112/69710997-9b378280-1100-11ea-8f56-12c3a6d6055e.png)

Any ideas as to why this happens?

Thanks in advance,
Michael

**Comment by e3bmo3ty** [comment]
same problem here :(

**Comment by 423967mv** [comment]
After a refactor in our code, the issue dissappeared. Looks like it was something on our end.
