### ISSUE TITLE
Possible to proxy pass-through a remote PDF link then return back client from express api?

### ISSUE THREAD

**Issue by kwongkz** [axios/axios#2576]
**Describe the issue**
Need to proxy a pdf link pass to Client A from my express API with using axios fetching remote PDF link.

**Expected behavior, if applicable**
1. Client A able to download pdf through my express API.
2. My Express API will read from the original PDF link with axios.get then proxy pass-through back to Client A.

**Environment:**
 - Axios Version 0.18.0
 - Additional Library Versions - Express

**Comment by yasuf** [comment]
I'd recommend you pass in a URL for the PDF and not the whole file through the HTTP calls, unless you have a specification that requires you to do that, not sure what we need to do on the axios side, closing unless we have to address a change, feel free to reopen!
