### ISSUE TITLE
How can I correctly use "Content-Encoding" header?

### ISSUE THREAD

**Issue by Alex-Consentio** [axios/axios#2578]
**Description of the issue**

My team and I are trying to implement a post method that zips data we send. In order to tell back-end the content is encoded we intend to add a "Content-Encoding" header. But, for some reason, this header never makes it to back-end. Any other header we send is correctly done, but this one specifically not.
We tried searching for this issue, but it was nowhere to be found. We came across a way of changing the data in the request called "transformRequest". But in the end, we still can't send properly this header.

Is this issue something relating axios behaviour with this header, or you believe is something else?
If it is so, how can we correctly upload this header along with the data?

Thank you in advance for the time and help.

**Expected behavior**

The objective is to send the header in the way is displayed on the following example:
<img width="947" alt="Screenshot 2019-11-28 at 12 25 18" src="https://user-images.githubusercontent.com/54800820/69802583-29336c00-11da-11ea-8ad5-1fb5dda1233f.png">

**Environment:**

 - Axios Version [0.19.0]
 - OS: [OSX 10.15.1]
 - Additional Library Versions [Pako 1.0.10]

**Comment by Alanscut** [comment]
This "Content-Encoding" is the response header, you should use "Accept-Encoding".

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding](url)
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding](url)

```
headers: {
   "Accept-Encoding": "gzip" 
}
```

**Comment by jkonze** [comment]
Just a shot into the blue - but does the server receive other headers?
I don't know about the complexity of your setup but maybe there is some loadbalancer stripping away the header.

**Comment by Alex-Consentio** [comment]
Thanks for the suggestion. To clarify a little bit, the server does recieve other headers, the issue is that it recieves any header except for "content-encoding" no matter the value we give it.
We took on the loadbalancer approach and used postman for testing. When using postman the server recieves the header so we can say is not a loadbalancer issue.

**Comment by jkonze** [comment]
This might be related to #858 and / or #891 .
Since you are using an already created instance can you try it with axios directly? I know this is not right for production but could help to narrow down the issue.

**Comment by vinceve** [comment]
@Alex-Consentio Could it be that in the backend `Access-Control-Allow-Headers` is configured? This preflight header defines what headers can be used on the backend. More information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

**Comment by Alex-Consentio** [comment]
Thank you kindly for both your answers @jkonze @vinceve . I've tried them both but unfortunately none of them seem to solve the issue. When creating my own axios instance and sending the header I wish thorugh it the header still doesn't reach backend. And if send the `Access-Control-Allow-Headers` before the request the header still doesn't reach.

The thing I have noticed is the following. This is a mobile app I'm testing, so when I enter in debug mode to look out for headers, the `Content-Encoding` does send to backend. But if I try to send it in normal mode the header is not found. Does this help in anyway?

**Comment by chinesedfan** [comment]
> It lets the client know how to decode in order to obtain the media-type referenced by the Content-Type header.

[Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) is a kind of **response header**. Don't send it as **request headers** by axios. Invalid request headers will not send from the browser side.

**Comment by Alex-Consentio** [comment]
Thanks a lot for helping us solving the issue @chinesedfan , we didn't notice this detail. Using any other header will suffice then. Thank you all for your time.

**Comment by kenklin** [comment]
@Alex-Consentio, Aside - I had the same question and a search lead me to this issue.

After some more investigation, I found that it's apparently dicey for web servers to unzip files.  Apparently there are [zip bombs](https://en.wikipedia.org/wiki/Zip_bomb)!
