### ISSUE TITLE
Axios and https Apache CloudStack API: Works well on Android and does not work on iOS

### ISSUE THREAD

**Issue by radetsky** [axios/axios#2580]
**Describe the issue**
I have a code that works well on Android and does not work on iOS.
Same code. Same version of Axios. I can't find the reason. 
I ask for help. 

**Example Code**
```js
// Example code here
        axios.defaults.headers.common['Cookie'] = setCookie(loginResponse, cookie) // Cookie magic after lucky authentication.
        axios.defaults.headers.common['Host'] = "cloud.tucha.ua"
        axios.defaults.headers.common['Referer'] = "https://cloud.tucha.ua/client/"
        axios.defaults.headers.common['User-Agent'] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
        axios.defaults.headers.common["X-Requested-With"] = "XMLHttpRequest"
        axios.defaults.headers.common["Accept"] = "application/json, text/javascript, */*; q=0.01"

        axios.get(APIURL + `command=listVirtualMachines&listAll=true`)
```

**Expected behavior, if applicable**
With the Android environment, code works well. I can read resolved promise and get the required data. But the same code does not work with iOS. The server returns HTTP 401 error. The documentation said that the client does not send credentials correctly. When I tried to use interceptors to see configuration before it will be sent I see the same output on both mobile platforms. All OK.  

But when Android client works well, iOS client is failing. 

**Environment:**
 - Axios Version : "^0.19.0",
 - OS: iOS 13.0
 - iPhone: 11 Max Pro Simulator 
 - Additional Library Versions: React 16.9, React Native 0.61.4

**Comment by chinesedfan** [comment]
> When I tried to use interceptors to see configuration before it will be sent I see the same output on both mobile platforms. All OK.

@radetsky Did you compare them carefully? It is better to check headers by Chrome network panel. There must be something key differences between them.

**Comment by radetsky** [comment]
Thank you. I will re-check it ASAP.

**Comment by imdanielpiva** [comment]
I'm facing the exact same problem, but instead of 401 I'm getting a 412. The exactly same code with the same Headers and parameters fails on iOS.

Some dependency info:

```json
{
    "axios": "^0.19.0",
    "react": "16.10.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
}
```
