### ISSUE TITLE
Add download method for downloading files

### ISSUE THREAD

**Issue by Yegorich555** [axios/axios#2581]
**Is your feature request related to a problem? Please describe.**
I would like to see ```axios.download(url, options)``` for downloading files

**Describe the solution you'd like**
Right now millions people use the similar implementation:
```js
 axios.get(url, { responseType: "blob" }).then(res => {
      const headerContentDisp = res.headers["content-disposition"];
      const filename =
        headerContentDisp &&
        headerContentDisp.split("filename=")[1].replace(/["']/g, ""); // TODO improve parcing
      const contentType = res.headers["content-type"];

      const blob = new Blob([res.data], { contentType });
      const href = window.URL.createObjectURL(blob);

      const el = document.createElement("a");
      el.setAttribute("href", href);
      el.setAttribute(
        "download",
        filename || (config && config.filename) || "someFile"
      );
      el.click();

      window.URL.revokeObjectURL(blob);
      return res;
    });
  }
```

**Describe alternatives you've considered**
I guess such code can be improved and integrated into axios without breaking changes. It will be really helpful

**Comment by yasuf** [comment]
to me that's sort of outside of the realm of what axios provides, so maybe we should keep axios light and write a separate dependency that adds that functionality inside the `.then(res => {})` callback, something like:
```
 axios.get(url, { responseType: "blob" }).then(res => {
  downloader.createFile(res, 'myFile.pdf')
})
```
what do you think?

**Comment by Yegorich555** [comment]
I would like to avoid such dependencies. Right now I'm using custom http implementation which is wrapper of axios and provides the mentioned download method. I'm going to improve this and publish into npm, but maybe I do useless effort if it can be implemented into axios directly and can be used without wrapping...

**Comment by chinesedfan** [comment]
Sorry, axios should be focused on basic request functionalities. Don't be afraid that your work will become useless, because we add your npm package in ECOSYSTEM.md to make more people use it.

**Comment by Yegorich555** [comment]
Ok. Thank you for your attention.
