### ISSUE TITLE
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.

### ISSUE THREAD

**Issue by j4nos** [axios/axios#2583]
Calling from a react app the BE with axios and got this error:

```
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.
```
 Do you have any idea what is wrong?

```
axios.defaults.headers.post['Content-Type'] = 'application/json';
axios({
  method: 'post',
  url: url,
  data: pages
}).then(function (response) {
  this.setState({
    pages: response.data
  });
}).catch(function (error) {
  console.log(error);
});
```

<img width="691" alt="Képernyőfotó 2019-12-02 - 13 58 09" src="https://user-images.githubusercontent.com/11924475/69961266-cf011680-150b-11ea-975f-c129c822cb82.png">
<img width="782" alt="Képernyőfotó 2019-12-02 - 13 57 52" src="https://user-images.githubusercontent.com/11924475/69961267-cf011680-150b-11ea-9633-f46366a63b2a.png">

**Comment by chinesedfan** [comment]
It is not an issue of axios. Please check your url endpoint. We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com).
