### ISSUE TITLE
how can get the body like the package "request"

### ISSUE THREAD

**Issue by cieldon32** [axios/axios#2585]
Use "request", like this:
```
request({
    url: '...',
    method: 'POST',
    body: JSON.stringify({}),
    headers: {...}
  }, (error, response, body) => {.
    console.log(body);
  });
```

use axios, like this:
```
axios.post('...',  {}, {
    headers: {... }
  }).then(response => {
    res.send({
      status: response.status
    });
    next();
  }).catch(error => {
    const response = error.response
    res.send({
      status: response.status,
      message: response.statusText,
      data: response.data
    });
    next();
  });
```
axios'  response.data is less useful than request's body

**Comment by cieldon32** [comment]
I fond these code:
https://github.com/axios/axios/blob/master/lib/adapters/http.js#L238

Corresponding code in request：
https://github.com/request/request/blob/master/request.js#L1126

same url, different result.

**Comment by Alanscut** [comment]
I verified that there is no difference between the two response data. Could you provide your response or more other information?

**Comment by cieldon32** [comment]
Please believe me very much. I did not get useful data when I used axios yesterday, so I switched to request, only to find that the data on the two sides are different. But currently, I get the same. I don't know exactly what happened because I didn't make any changes related to it. Anyway, please forgive me for wasting your time.

**Comment by chinesedfan** [comment]
@cieldon32 Never mind. If you find the reason someday, feel free to update and remind me reopen this issue.
