### ISSUE TITLE
Custom default params not persised to each request

### ISSUE THREAD

**Issue by DavidTanner** [axios/axios#2587]
**Describe the bug**
Custom settings are not persisted to each request

**To Reproduce**
```js

var axios = require('axios')
var axios2 = axios.create({retry: true});
// should log "Retry is true"
axios2.interceptors.request.use(request => console.log('Retry is ' + request.retry));
axios2.get('http://www.blankwebsite.com/');

```

**Expected behavior**
Custom default parameters should be persisted to each request.

**Environment:**
 - Axios Version [hash a17c70cb5ae4acd7aa307b7f7dc869953dea22c4]

**Comment by Alanscut** [comment]
@DavidTanner Thanks for reporting and fixing this issue :+1:

**Comment by JustinBeckwith** [comment]
Greetings folks!  Just adding a little more data - we're getting customer reported issues on this in [retry-axios](https://github.com/JustinBeckwith/retry-axios/pull/91) as well.

**Comment by comphonia** [comment]
Any plans for resolving this? I can't use custom configs in my interceptors unless I reverted to 0.18.1

**Comment by pfftdammitchris** [comment]
reverting to 0.18.1 works for now as @comphonia  suggested
