### ISSUE TITLE
Status "304 Not modified" error Network

### ISSUE THREAD

**Issue by johan-Rm** [axios/axios#2592]
I'm working on a Nuxt JS project, I'm using Axios for the API (Symfony 4), I'm having a big problem right now I'm getting the error "Error: Network Error" after receiving the status code "304" ( API: options => get), I use Axios' validateStatus configuration option but that does not seem to work.

Some code...

     await this.$axios.get('/web_pages/' + slug
      , { 
        params,
        validateStatus: function (status) {
            return status >= 200 && status < 500
        } 
      })
      .then((response) => {
        commit('setItem', response.data)
      }).catch(error => {
        console.log(error)
        console.log('error store pages getListBy')
      })

These problems we start after switching my server to HTTP / 2

I do not know where to look, I do not know if I should look in the configuration server pache / php or if there is an option Axios to change, can you help me?

thank you in advance for your information

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/cgkKY.png

**Comment by chinesedfan** [comment]
@johan-Rm Hi, can you paste the request and response headers for the network request? And if possible, you can send request by other libraries, like jQuery/fetch, then compare results and http headers.

**Comment by johan-Rm** [comment]
here already for axios

`XHROPTIONShttps://immobiliere-essaouira-cms.graines-digitales.fr/api/articles?itemsPerPage=3&order[id]=desc&isActive=true
[HTTP/2.0 200 OK 95ms]

XHRGEThttps://immobiliere-essaouira-cms.graines-digitales.fr/api/articles?itemsPerPage=3&order[id]=desc&isActive=true
[HTTP/2.0 304 Not Modified 171ms]

URL de la requête :https://immobiliere-essaouira-cms.graines-digitales.fr/api/articles?itemsPerPage=3&order[id]=desc&isActive=true
Méthode de la requête :GET
Adresse distante :51.38.237.233:443
Code d’état :
304
Version :HTTP/2.0
	
En-têtes de la réponse (215 o)	
En-têtes bruts
HTTP/2.0 304 Not Modified
date: Sat, 07 Dec 2019 16:53:15 GMT
server: Apache/2.4.25 (Debian)
etag: "d7b0c20020ccca8b5fd680ae1546599e"
cache-control: private, must-revalidate
vary: Accept
X-Firefox-Spdy: h2
En-têtes de la requête (540 o)	
En-têtes bruts
Host: immobiliere-essaouira-cms.graines-digitales.fr
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
Accept: application/json, text/plain, */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Origin: https://immobiliere-essaouira.graines-digitales.fr
Connection: keep-alive
Referer: https://immobiliere-essaouira.graines-digitales.fr/
If-None-Match: "d7b0c20020ccca8b5fd680ae1546599e"
TE: Trailers`

**Comment by chinesedfan** [comment]
@johan-Rm I am not very understand your update. But I am afraid that you are facing the CORS problem. I noticed `Origin` request header, and didn't see correct response headers. See more from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by johan-Rm** [comment]
actually it came from CORS, thank you for your help
