### ISSUE TITLE
Revert changes about `finally`

### ISSUE THREAD

**Issue by chinesedfan** [axios/axios#2593]
**Section/Content To Improve**
https://github.com/axios/axios/blob/master/README.md#note-commonjs-usage

**Suggested Improvement**
See https://github.com/axios/axios/pull/2305#pullrequestreview-266978437. Revert #2189 and #2090.

**Relevant File(s)**: README.md

**Comment by yasuf** [comment]
what do we need to do here? replace the `.finally` with then right? as a shim is needed for that to work

**Comment by chinesedfan** [comment]
> replace the .finally with then right

@yasuf Yes, don't make users think every Promise implementation has a `finally` method already. It is still on draft stage. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally).
