### ISSUE TITLE
Unit test fails when excuting the unit test in Windows OS

### ISSUE THREAD

**Issue by jennynju** [axios/axios#2594]
**Describe the bug**
Unit test case failed :
  1) supports http with nodejs
       should pass errors for a failed stream:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (***************...

**To Reproduce**
Use VS Code internal terminal to excute the unit test .

**Expected behavior**
UT should be excuted correctly.

**Environment:**
 - Axios Version: latest master
 - OS Version: Window 10

**Additional context/Screenshots**
![Capture](https://user-images.githubusercontent.com/46782518/70436361-136c5380-1ac4-11ea-87b5-203b2e46ebbf.PNG)

**Comment by chinesedfan** [comment]
@jennynju Find why your test case didn't finished before timeout. And in your screenshot, there is a "no such file" error. Please provide the detailed codes of your test case.

**Comment by jennynju** [comment]
The failure happens when I excute ```npm run test``` and the failed test case is : 'should pass errors for a failed stream' in \unit\adapters\http.js.

```
 it('should pass errors for a failed stream', function (done) {
    server = http.createServer(function (req, res) {
      req.pipe(res);
    }).listen(4444, function () {
      axios.post('http://localhost:4444/',
        fs.createReadStream('/does/not/exist')
      ).then(function (res) {
        assert.fail();
      }).catch(function (err) {
        assert.equal(err.message, 'ENOENT: no such file or directory, open \'/does/not/exist\'');
        done();
      });
    });
  });
```

It failed at the assertion:
AssertionError [ERR_ASSERTION]: 'ENOENT: no such file or directory, open \'C:\\does\\not\\exist\'' == 'ENOENT: no such file or directory, open \'/does/not/exist\''.

I think the reason is the NODE PATH format various in different environment. I'd prefer use the default node path for this test in order to escape from different environment factors.

**Comment by chinesedfan** [comment]
@jennynju I just noticed that you are running our unit tests. In fact, the CI is passed. So there should be some problem in your local environment. The `ENOENT` is generated as expected. The most possible reason is that port 4444 is in use by other programs. Try to use another port.

**Comment by jennynju** [comment]
@chinesedfan, FYI, actually the issue is caused by the difference between OS system. In Windows, path does use '/' as delimiter.
As a result, this unit test will only pass in linux-like OS system.

**Comment by chinesedfan** [comment]
@jennynju I see. We can only check the beginning part of the error message and ignore the file path. PR welcome.

**Comment by jennynju** [comment]
@chinesedfan , thanks for your comments.
I was thinking about using "__dirname" to construct the 'do not exist' folder to keep consistency between different OS systems. PR was submitted.
