### ISSUE TITLE
then() and catch() ignored

### ISSUE THREAD

**Issue by leonheess** [axios/axios#2595]
Copy-Paste of [my SO-question](https://stackoverflow.com/q/59250567/7910454): 

I have the following code but I get no console output. It seems like no matter what I do it doesn't enter the `then()` or `catch()`.

    axios
      .post(url, {test: "0"})
      .then(console.log)       
      .catch(console.error);

Interestingly enough the request gets posted and is received on the other end. I can also verify by mocking with postman that the endpoint is responding correctly. Where could this fail?

**EDIT**: It is getting even weirder: I tried the following and it instantly prints the promise:

    console.log(await axios.post(url, {test: "0"}));

Unfortunately I am forced to use Node v8.11.1 - could this be the issue?

**EDIT 2**:  I went to the [official doc][1] and tried the recommend way as well:

    axios
      .post(url, {test: "0"})
      .then(function (response) {
        console.log(response);
      })
      .catch(function (error) {
        console.log(error);
      });

The problem persists.

  [1]: https://github.com/axios/axios/blob/master/README.md

**Environment:**
 - Axios Version: 0.18.1
 - OS: Azure Function
 - Node: 8.11.1 / 10.17.0

**Comment by lyqline** [comment]
I also met this problem. I use get method, axios only enter finally.  
axios.get(url).then(resp => {
        alert(JSON.stringify(resp))
      }).catch(err => {
        alrt(err);
      }).finally(() => {
        alert("finally");
      })

**Comment by chinesedfan** [comment]
@leonheess I am afraid the Promise implementation in your platform(Azure Function) has something different with the Promise specification. Can you add a Promise polyfill to replace the native Promise? And if possible, add some debug codes in the axios lib(like adapters/https.js or adapters/xhr.js) to see where it runs into.

**Comment by leonheess** [comment]
Not a problem of Axios at all. Azure killed my process immediately after the POST and didn't wait for the Promise to resolve. In case someone has a similar problem, see https://stackoverflow.com/questions/54347873/promise-is-not-working-in-azure-function-app-javascript
