### ISSUE TITLE
download excel file using axios

### ISSUE THREAD

**Issue by SevymolSebastian** [axios/axios#2597]
**Describe the bug**
I have a api that return an excel file from backend (laravel maatwebsite/excel). I want to download my respose.data as an excel file. But i get an zip file. What should I do?

```js
// Example code here
         axios
          .get(this.$hostname + "export", {
            responseType: "blob"
          })
          .then(response => {
            let blob = new Blob([response.data], {
                type:
                  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
              }),
              url = window.URL.createObjectURL(blob);
            window.open(url);
          });
```

**Expected behavior**
I want to download my respose.data as an excel file.

**Environment:**
 - Axios Version [0.18.0]
 - Vue Version [2.6.10]

**Additional context/Screenshots**
When I console.log my response.data, the data seems weird like this

PKÂQOGD²Xð[Content_Types].xml­MNÃ0÷"ò%nY vAa	(0ö¤±êØgúw{&i@ÕnbEö{ßøyìÑdÛ¸l
	mð¥×ÁX¿(ÅÛü)¿òF¹à¡;@1_æ»±Øc)j¢x/%êEày¦
©QÄ¿i!£ÒKµy3ÜJ<§Z1½0?YÙL%zV
cäÖIb7Øûìa/lÙ¥P1:«qáríÍjªÊj0A¯Íuë""íàÙ(	ÁWìMä)Tjå({Ü²û>óOãÂ,XÙ­ÁÚÆ>Bÿ~×­ÏõÓ¤6ÜJ=¡oBZ¾°¼tìíX4Êú¾Cgñ,QgmrLÙÙ¯cïeëàtø±	Zõ?´»hPvÃðÂ±úÿuÕjÀ¼Râæ¸øûî}¬CvÖøPKÂQO¶78éK_rels/.rels­ÍjÃ0ï{
£{£´1F^Ê ·2²Ðlå$±½-}ûy±ºÒÃ¥OvûyÕ;ØÓ°.JPìØÞµ^ê§Õ¨ÈYÅ±3GØWw»g)åØõ>ªqQCD¦ãb!]þi$Lò3´èÉÔ2nÊòÃoT¦:Z
áh· ê³ç[ØÒ4½á·]ºÐyNì,Û¹>¤>£j
-'
VÌ)#÷EF^6ÚÜnô÷´8q"KÐHàë>_×Öÿ¹¢eÆÍ<âáUdøvÁÅ
TPKÂQO$±Vé¹xl/_rels/workbook.xml.rels­ÁjÃ0Dïý
±÷ZvZJ)s)\[÷´¶LlIh7mý÷UH¡Ä¬ØÇHëÍ÷8OLÔ¯ *JèM°½ï|4ÛûgÄÚ[=
&$ØÔwë74çr}$M<)pÌñEJ2GMEèóMÒ¨9ËÔÉ¨Í^w(Weù$ÓÜêO±³
ÒÎV )â¼CÛö_9èùJ$Ì/:dG]d×ãWKÆsÞÅsú<«[VàtBûÎ)?ð¼ùøÌã0_!íÉ!òä4úEÍÇ©yñãêPKÂQO×Íê;docProps/app.xmlSÁnÛ0½ï+Ý9Á0¬bH7ôÐb¶gN¦c¡¶$¬ìë';°ë´=Õ§ÇÇ§'V7Ç¶É:d½+Ärñ¥uB<î_]\	wX¸ÑßÔ6ú-R¢fk)ÉÔØ-RÛ¥NåcÊx¾ª¬Á[o^[t,WyþCâÑX^ÉP×Õ´ô¦ÏGOûSH~Zý¡±8]R?X=ù³_Gó¦JF;4¯ÑòIçJÎKµ3Ðà&ë
B%ßuÐÏl6V¯;4ìcFö_ÚJd°S¢Çâ,;nqÔÏ>¾PÈ¤äDp®cû]/AB9Iø2âÞrô§ÚBäO/çâ³"½³ßø6;Í¿ñ1ø8L]É±­ÀÁ{	Ý[÷Baïoqü%©v5D,ÓcM/3ê.]!6½~S;`9j>6ú=y:ÿz¹ZäéÖcä|[{ýPKÂQOûC?qdocProps/core.xml¥QOÃ ßý
¯¦65Út5Qã&&Îè+ÂuÃµ@àjí¿Ò­sº7Ósø¸÷òò«©³OðA[3'|ÂHFZ¥ÍrN·ù9É
£Dm
ÌI\VG¥t´¼uàQCÈ"ÈBº9Y!ºÒ WÐ0	Í7ëQú%uB®Åè±3Ú
%PÐ»H6H%G¤ûðu(I¡Ê'î²¾	$çG²ÑØ98Ýcú+è1Ø¶í¤¥hÓû»Ç´j®M_RJÒ@ë«'³6¶5Ùõ KúÃë{¬EÀûØøuÕýÿ5¨,WËlçÙõÍâTSÆ/r>Í9[pVð³ÓbÆú1ö ;j³¹éØ-%uk«¥¯Ê]¼S¦:»*Òkñ9VÉÚûuøx}9ØÑºÖzªÔØNõ/5î·´¾¬_jïWßPKÂQOs{Y³¦xl/theme/theme1.xmlíYOoÛ6¿ïSº·²lÉu:EìØëÖ¦
·C´DK¬)Q é¤¾
íqÀaÝ°ËÝv¶h]ºO­ÃÖý
{úcé6iSlCë-¿÷ïñQ¾|å^ÌÐ!ò¤k9"Ï]ëÖhx¡c!©p`ÆÒµæDZW¶>¸7UDb<¸kEJ¥¶-}Æò"OIk.b¬`(B;øØÆÌn6m;Æ4±Pcàzs2¡>A£¥µµ`>`ð(MøLø¹D"ÇS'ûsÙgbÖµ@NÀFä²ÃRÁB×jäËÞºl/ZC«Ñ
óOIWÓfN'ÂñÐºvüÿUÜ`0è%¿},uV°î°ãô<5Pñ¸Ê»ßðn¯ño­à7z½·QÃ·*¼»ï4Úîv³w+¼·ªo»ßo×ð^o¯à6Ún"Fé
:ç22KÈ³«FxàÅ¨P¶¶»
úD­Ûk1¾ËÅyp±¢	RóL°¸>ÇâLÞ$X[)¦|¹2ÉBÒ4U]ëãCFTO|ñô1zñôÑñý'Ç÷9~ðàøþÏÂ«8	uÂçßñ÷·¢¿÷üáWf¼Ôñ¿ÿôÙo¿~i*øìëG<yôìÏÿüá¡¾-ðXhL$ºAÐ>Á62g£EÖ(pHp ¢ðÆ3®GêÎ»- ÎîÖt=ÄLQðZ×»³Fs®e²tsfIh.f:nãCìþÐf)ìdjbÙHMÍ=ÑÆ!IBÙb »CiÍ¯»Ô\òBw(êajtÉè*!.sluÍ7»·Q3ûrXGBB`fbIXÍâÂ±Qc3y«È¤äÁ\ø5K	ãh)M47Å¼¦î5Èö]6ëH¡èÔ¼9×;|Úpu¦I¤c?SØ¢íqeT×3$Cp²6Ü·)QgKë[4Ì$[	SJ^ÏÇ9`õ½V©c¼¬l3
uû}Ù^À·ác§(ÖëpÿÃ½gÉ¬x_¡ßWèw±B¯Ëåó¯ËU)¶õ^;g¯m¼'±5gäºÌ¸ó!LæhÙç§<âj¸Pàü	®>¡*:p
b\B(KÖ¡D)p»°ÖòÎ¯¨lÎç¼Å½ÐXíò né÷Í%|J]P+cpZa­Ko&Ì)§æxfiÞK¥Ù7!oÎ^&8íf!6
f$Èü^0XåÜC$#2FÑ§uJ·u^í5MÚFëÍ¤&Hº8w8ï¢ÔX½,©Ðhå5=ù8íZè¹à1NÌJfaÒµ|UòÊd>i°y[:µ×D¤Bª,£*_Z¼I*ýùá|°_WVÇùµ°OL&ÄWkfªa¹Æg(8Bc6ûôvÝP	GEs1¡n¹ñê_fÁÉ×>ev`F¸¬I-ö<^ê4õì5º¿¦)­s4Å{wMÉv.4¸­ ¿zA 0Êöh×âBEªPQ( qÈe^Ò"S	±ìv¦+9¬êVÁ£(ra¤öiJ§"AÈ*í|3§©¯FeYª+ÓâwL	eÙÛÎì·P´¨&¥#rÜÉ Ù¦ìÃÿpçã6^§=¨¹géE\­èkGÁÆ©pÆ£¶i¶¸éú¨Má²/(ÜTø¬êoG|¢%x¡S¦ßrr:w4ã2Vo·ªBÐi¼ýæSsvk³·ãlÏàkïå®¶WSÔÖ.2ùhåÏ,>¾²wà~4cJïîÁ¥´¿øøØéÖ?PKÂQOxèxl/sharedStrings.xml
ËAÂ @Ñ½§ ³· cLi&@@ÊXHÊ@ÁèíeùóòÇù6õÁÊ1Ó`@!-ÙGZ-¼ã#ï¶LháótEõØB)7­y	¹ uyçô¬«æRÑy6}6æ¢ªQÜÞs#±`@OPKÂQOâ_Þùh
xl/styles.xmlËn0÷}
ËûÃRµ5ºhT5TêÖÀV|Aöp
yúÚÃE6Ìü>?ûQ
rc¹V)oNªtÍUÒ?Eþù+%ªÐ
R:¥÷Ù§Äâ$à¹@âw¶g[í
X0 ^T6¥bE¶ê@2{£{Pn¥ÑF2t©i#ëaµõ$)¢óéô%+%j¹DK*=(LéFYÒhµ)1
BäÂÄRÂw±EÃ_`'!Vî]æõ×Ç±Ï*-´!¦-Sç§ùò²brA<2ÁKÃ½çump!Ö¾Î4YÒ3D0*w	Yâbêak 
uT·MñùÖcÛÇ}áò ò¸°uí¨ë~óÍµ]jS»o¿74HþÁeÑùB<ûïý·9
	ßèGíí%ÞkèøK0!ñØ=-°ßbÇæ-ò¸Õû|Âú^L¹ç%dO,ÁäóÛÕ8À=Ì-ÿ.x«$L°kJ:mø«ÃûÓÐÃõã¼òR©µ¤aÄßÎSå¨ÿë'¦´aÂºù°áê¥Ð9_5oÎØ,­æÌVüYUâOfJü«¹6VÓÊäêË³ãH!+Ý$]jhØ °X¥nñO¨ù ¿ÑkÕ/~Ñ¸TÍñV:S´ý#²ÿPKÂQOJY(È«õxl/workbook.xmlRÛNÛ@}ïWXû^l 6T ©TRx¬ÇxÄÞ´³N¯ïì:i)Oøeö¹ñüìÉjÉ»V4ªB§}Gî¡U¿WËTÅ	\Æ;lÕ3²:[|o}|\{ÿXIþhñq*[5¤fuÍz@|à:ñô>ZHãCÍÉú¨iNkävfñ=5|ßÆ¯G.ME"H²X-æ=¼¶¬ `eÞ'£*.;JØµêX ßâDÃL'Íª7¿èS©Õ@|¿sä lï·ü/>Ã
t¢
®`Ý*QÆädÆHxýî)"bOÓm¦[rdé%ÏÕa	àÁo¿úH/Þ%0·:zcöÉÙWr¥¿&EDúmxõ¯,X«Néµ!¦5JÏ­*oy«úÕZåf{[¹¢BV àÜJÌµÌz(ÎHñº;.Eööä°Ë²ð2ÎÉyË§
þ.:·*«5ásoÁr"¶9ö§ûæaê(¿ÆåÏLî»?ÄâPKÂQOù;w×Ùxl/worksheets/sheet1.xml¥UËnÛ0¼÷+Þc9múa;Hº	"AÍWk«÷ë»¤ãôäÝ!w8»ÊÓ³R³5X§ÐÌøñhÌ¥2ù?=.¾pæ¼0Rh40ã[pülþnºA»rgD0qHi±²àÀ®Ð¸/¼¯&IâÒJáFX¡m)<¥6OÕJ¼?%¥P¦eØ·p`©.1­K0¾!± §\¡*×±½È7ñI+6Ô§g ñ²YéùOøJZtùQe+í°ËÓät¯Ï2}°RØU]qEÍ-V~5rV¦ëÜ KMAÂD:P)ÒÿÐILóiÄîì|µ×ÊÀe®.IÐö+hÜuxÜ«¼ðHæÓ¤¯.'¸YÈfüüxrwÄ
?lÜ f^,@CêAFê`·%â*,^D6un¾[%oH
YÍÛð7¨¯¨²u¨&âÈô³Ð:h ß­ÚpÆ0î-âMPã2QkOç\AÛëÉè³v47°}f2ÞÇHUÀº¦/I?Yô­ÂÏx&´£pùp×ç.#¬ÂÒ$tt¡®Kó%e;Hz°ô¯¶Xêgµ[4Z¯t¡¹LW ÷Õ:´»Eíq¡´ÛCZ£Î~Íödô!Í´²ÊøÛ*~X¾3I[Ü#aÒÑ9¡HäðCØZe2Z>sf+±Ç*F9[¢÷XvYÝ²aÎè»¤å¥êUÆ÷ þ@ô4ZE«øñÖSáExÁÇc2O¦ü#ökóg%}Ñ>¯æØE<Ie`òVÊok0»ËèÊ:?°ô¬|A_Îîý­r°v-NÏ^ÊæEÑËÄ6§7pÛM¿}¸/&YÖìe1éö³á(íÿæPKÂQOÍKR"x#xl/worksheets/_rels/sheet1.xml.relsM1!{_A¶÷@cÌq×ù£Øp+a!,1ú{)-'yýä¤ÞÔ$¶p(bW¶ÈÞÂã~ÝAIGÞ0&_XÝ|£}4b5&,Bïõ¢µ¸@e*xgiûÀæuE÷BOúhÌI·ÿèåPK?ÂQOGD²Xð¶[Content_Types].xmlPK?ÂQO¶78éK¶_rels/.relsPK?ÂQO$±Vé¹¶xl/_rels/workbook.xml.relsPK?ÂQO×Íê;¶¼docProps/app.xmlPK?ÂQOûC?q¶pdocProps/core.xmlPK?ÂQOs{Y³¦¶xl/theme/theme1.xmlPK?ÂQOxè¶ôxl/sharedStrings.xmlPK?ÂQOâ_Þùh
¶¥
xl/styles.xmlPK?ÂQOJY(È«õ¶Éxl/workbook.xmlPK?ÂQOù;w×Ù¶¡xl/worksheets/sheet1.xmlPK?ÂQOÍKR"x#¶®xl/worksheets/_rels/sheet1.xml.relsPKÑg

**Comment by chinesedfan** [comment]
Hope #2581 can help you. Closing due to it is not an issue of axios. We suggest users to look for help in [stackoverflow](https://stackoverflow.com). Thanks.
