### ISSUE TITLE
how to send data use http get method 

### ISSUE THREAD

**Issue by danerlt** [axios/axios#2598]
**I want to send params and data use http get methods**

I want get http params and data at backend.
**Example Code**

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>vue get send data demo</title>
</head>
<body>
<div id="app">
    this is app info: {{info}}
</div>

<script src="https://cdn.staticfile.org/axios/0.18.0/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
<script>
data = {"name": "danerlt", "age": 23}
index = 1
count = 15
url = `http://localhost:5000/get_body?index=${index}&count=${count}`
console.log(url)
console.log(data)
new Vue({
  el: '#app',
  data () {
    return {
      info: null
    }
  },
  mounted () {
    axios.get(url, body=data).then(response => (this.info = response))
  }
})

</script>
</body>
</html>
```

my backend code use python flask 
```python
# -*- coding: utf-8 -*-

import json
from flask import Flask, request, jsonify
from flask_cors import CORS
app = Flask(__name__)

CORS(app, resources=r'/*')


@app.route('/get_body', methods=["GET"])
def get_http_body():
    args = request.args
    print('get_http_body args: %s' % [args])
    try:
        body = request.data.decode()
        print('get_http_body body: %s' % body)
        # data = json.loads(body)
    except Exception as e:
        print(e)
        return jsonify(status='error', msg=str(e))
    else:
        return jsonify(status='ok', data=body)
```

**Environment:**
 - Axios Version  0.18.0
 - OS: Windows 10
 - Browser : Chrome

**Additional context/Screenshots**
In my python code, the http data is empty string, When I use poseman like this:
![image](https://user-images.githubusercontent.com/14197717/70503367-33e8ec00-1b5e-11ea-94cc-2fc6dff11055.png)
It return the right result, How can I resove this probleam?

**Comment by chinesedfan** [comment]
> mounted () {
    axios.get(url, body=data).then(response => (this.info = response))
  }

Try `axios.get(url, { params: data }` instead of above usage.

**Comment by danerlt** [comment]
i means i want get thte http body,not param,i know params can use `params` to get

**Comment by danerlt** [comment]
@chinesedfan 还是回复中文好理解点，就是我定义了一个http get的接口，这个接口可以传查询字符串，可以传body，我需要在后端获取到查询字符串和body，但是axios好像并不支持这种用法，我想同时传递查询字符串和body用axios要怎么实现。

**Comment by chinesedfan** [comment]
我理解是http协议本身限制的，否则你只能使用post请求。如果你在别的地方找到可行方案，例如原生的xhr对象，可以提醒我再打开这个issue，谢谢。

**Comment by danerlt** [comment]
http应该是没有这个限制的，用postman都可以发送出去，就axios好像不行

**Comment by chinesedfan** [comment]
Refer: https://stackoverflow.com/a/10299780/6501855

@danerlt Postman截图可以给下吗，尽量让我能够复现。

**Comment by danerlt** [comment]
@chinesedfan postman的截图在最后一张，后端的代码见Python哪里

**Comment by chinesedfan** [comment]
@danerlt 通过一些网上的查找，准确的描述见更新后的https://github.com/axios/axios/issues/2598#issuecomment-563965172.

- 调研参考：[https://www.jianshu.com/p/c025273d78db](https://www.jianshu.com/p/c025273d78db)，# 新版postman已新增支持，见文章评论
- 因为axios是基于xhr的，所以不支持，见：https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send
- 建议改用post请求，如果你坚持要get，可以自行实现一个adapter作为参数设置到axios中
