### ISSUE TITLE
axios.get() inside Vue's created() method leads to "Network error" in Firefox (but not in Chrome)

### ISSUE THREAD

**Issue by j0hannes** [axios/axios#2600]
**Describe the bug**
When using axios.get() inside Vue.created(), an exception is raised. When I print this exception inside catch(), I only see
> Error: "Network Error"

This only happens when the page is forcefully reloaded, otherwise the GET request is skipped and the result from cache is used instead.

**To Reproduce**
```js
const app = new Vue({
  ...
  methods: {
    ...
    created() {
       axios.get('some/api')
         .then(...)
         .catch(function (error) {
            console.log(error)
         })
    }
  }
})
```

**Expected behavior**
The then() part should be executed with the result of the GET request.

**Environment:**
 - Axios Version: latest (https://unpkg.com/axios/dist/axios.min.js)
 - OS: Arch
 - Browser: Firefox
 - Browser Version: 71.0
 - Additional Library Versions: Vue: latest (https://unpkg.com/vue/dist/vue.js)

**Comment by Alanscut** [comment]
this seems to relate to #2058 #2076 #2063 ,  it should be caused by **CORS**, I set the following code on the server and the request was successful, Hope it helps you.
```
res.header('Access-Control-Allow-Origin', '*');  // '*' or 'http://****'
res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
```

**Comment by j0hannes** [comment]
I figured out it was due to uBlock Origin's blacklist. Renaming the api endpoint and/or whitelisting the domain helped.
