### ISSUE TITLE
Axios errors leak sensitive content - by default this content should not be returned

### ISSUE THREAD

**Issue by tobalsgithub** [axios/axios#2602]
**Is your feature request related to a problem? Please describe.**

Errors thrown by axios have the full request body (and response body if a response was received before the error was thrown). The shape of errors thrown by axios is shown here: https://github.com/axios/axios/blob/master/index.d.ts#L82

There's no doubt that having this information can be incredibly useful. Especially if using interceptors to do retries or otherwise respond to errors, having access to the original request is incredibly useful. 

Unfortunately, this also means that if the original request contained sensitive content, that sensitive content is now on the error being thrown / rejected. This puts the onus on the developer to remember to properly cleanse the error before allowing it to be thrown or logged. And this certainly doesn't always happen. I cringe a little bit thinking about all the usernames / passwords that are being logged to browser consoles around the world when login requests fail, for example.

**Describe the solution you'd like**

I'm a big believer in doing the safe thing by default, and allowing that behavior to be overridden intentionally by developers if so desired. What I would prefer here is that axios automatically cleanse the error of the request and response content by default, but allow the developer to pass in a flag to override this behavior.

One possible way this could be achieved is by adding a final response interceptor at the end of any user defined interceptors, that essentially just looks like so

```ts
ax.interceptors.response.use(
    (response) => response,
    (error) => Promise.reject(new Error(error.message))
);
```

This interceptor could be disabled by the configuration flag. 

I believe this would allow developers to utilize the full error object as it is today in any interceptors they define, but would prevent the final error from containing any sensitive content by default. 

**Describe alternatives you've considered**

The proposed solution is a breaking change. As an alternative, we could keep the existing behavior as the default, and allow a flag to enable the "clean" errors functionality described above. This would at least allow developers an easy way to make sure any errors are sensitive content free. But it still requires the developer to know about the flag and set it to be safe.

**Additional context**

**Comment by vinceve** [comment]
In my opinion it is kind of weird to introduce this behaviour. Sure you can clean out the data from your error object and see less, but it won't stop developers putting console.log in their code. Plus when you're developing, it will be a nightmare to debug. 

The same logic can be applied if the request worked btw: if someone puts a console log in their success handler logging the request, you are still leaking it. 

I think it is ultimately the developers responsability to see if his code doesn't leak any sensitive ninformation.

**Comment by chinesedfan** [comment]
Yes, we recommend users to use a customized interceptor to handle that.

**Comment by tobalsgithub** [comment]
Apologies for the delayed response here, the holidays really threw me off. 

I'm aware that we can use customized interceptors to handle this, and that that is the current recommendation. My concern here is that the default behavior is not safe. For example, a developer needs to be really thinking to realize that their simple post request to sign a user in could result in that users credentials getting logged to the browser console. This goes for any type of put or post that contains confidential data.

At my company, we've wrapped axios and provided that wrapped version to developers rather than using axios directly. Developers can still opt in to getting request info in their errors, but they have to choose to do this, rather than it being the default behavior.

At the very least, it feels like we could add some better documentation around this that calls out this concern so users are better aware of it.

**Comment by vinceve** [comment]
@tobalsgithub I would argue that the wrapping is overkill (at least if you are only using it for that feature). If you look into the network tab, you will see the data also as browsers do not encrypt that information. So it does not protect anything as the data is easy viewable in another tab.

Where it would make sense is a serverside environment. As requests could leak into logs on the server.

**Comment by tobalsgithub** [comment]
@vinceve You're right. In our case, everything we use axios for is serverside, so it's that exact scenario that we're trying to avoid.
