### ISSUE TITLE
How to send an object in POST method?

### ISSUE THREAD

**Issue by farshidrezaei** [axios/axios#2604]
### Client Side :
```es6
axios.post ( 'index.php', data )
    .then( res =>  console.log( res.data ) )
    .catch( e => console.log( e ) );
```

### Server Side : 
```php
return print_r($_POST);
```
but i get empty array !

**Comment by MrVine** [comment]
First of all ensure that your `index.php` script works. Then, include information of `node` and `axios` versions which you use, and write what in your `data` object.

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. Thanks.

**Comment by farshidrezaei** [comment]
@MrVine 
I use axios latest version(v0.19.0).
and data object is:
```jsx
{
	materials:['m1', 'm2' ], 
	types:['t1', 't2' ] 
} 
```

**Comment by MrVine** [comment]
@farshidrezaei , it looks like the problem was in your PHP code. Following code works fine:

JS:
```js
const axios = require('axios');
axios.post('http://localhost/index.php', {foo: 'bar'})
    .then(r => console.log(`response: '${JSON.stringify(r.data)}'`))
    .catch(e => console.log(`error: '${e.message}'`))
;
```

PHP code:
```php
<?php
$entityBody = file_get_contents('php://input');
echo $entityBody;
```

returns us `response: '{"foo":"bar"}'` in the console.
