### ISSUE TITLE
How to handle downloading files in React-native

### ISSUE THREAD

**Issue by rxicon** [axios/axios#2605]
**Describe the issue**
In my project，need to download files,but I don't know how to get the file and handle the response.

**Example Code**
return the axiosPromise,how to handle file in .then()

```js
const options = {
        responseType: 'blob'
    };
    return axios.request({
        method: 'get',
        url: "http://192.168.0.117/Voice_001.m4a",
        ...options,
        onDownloadProgress: progressEvent => {
            let complete = progressEvent.loaded / progressEvent.total;
            ...
        }
    });
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version [0.18.0]
 - Additional Library Versions [React 16.6.3, React Native 0.57.8]

**Additional context/Screenshots**

**Comment by chinesedfan** [comment]
#2581 may help you.
