### ISSUE TITLE
Is there has UrlFormat

### ISSUE THREAD

**Issue by IrvingZhao** [axios/axios#2607]
When I use RESTful Api, there has some api like `GET /user/:id`, I use axios like `axios.get("/user/{id}",{params:{id:1}})`, but it's not work.
I wanna format the url `/user/{id}` with param `{id:1}` to `/user/1`, is there has some guidelines can do that or I must write a request interceptor to make it work.

**Comment by chinesedfan** [comment]
Use a template function by yourself, or from lodash.

```
// Use custom template delimiters.
_.templateSettings.interpolate = /{([\s\S]+?)}/g;
var compiled = _.template('/user/{ id }');
compiled({ 'id': 1 });
// => '/user/1'
```
