### ISSUE TITLE
Docs: Note that entire request body is held in memory when maxRedirects !== 0

### ISSUE THREAD

**Issue by cdhowie** [axios/axios#2610]
**Section/Content To Improve**
[Request Config](https://github.com/axios/axios#request-config)

**Suggested Improvement**
I have been working on a project that moves data between servers. The details are not that important, but the basic process is:

* make an `axios.get()` request with `{ responseType: 'stream' }`
* then an `axios.post()` request with `{ data: response.data }` to stream the data to the destination.

Being naive, I assumed this would be extremely efficient. However, since axios is actually rather smart and tries to follow redirects by default, this results in the entire request body being buffered in memory in case the response code is 307 or 308.  In my case, this caused excessive memory usage (peak was 6.1GB) since many of these requests were several hundred MBs. I spent several hours in `--inspect` mode with Chrome's devtools trying to figure out where all this memory was going.

Digging into the code, I found that a regular, non-following agent is used if `maxRedirects` is set to 0. This indeed fixed the problem and peak memory usage is now around 300MB (most of which is the list of requests my script needs to make).

Anyway, the tl;dr is that a note about how request bodies are held in memory unless `maxRedirects === 0` could help avoid others running down this rabbit trail for hours as I did.

I am willing to provide a PR for this if this change would be welcome.

**Relevant File(s)**: `README.md`

**Comment by yasuf** [comment]
this could be good in a TROUBLESHOOTING file or something like that in a separate file that's not the README.md, not sure what the standard is

**Comment by yasuf** [comment]
closing for now, feel free to make PR to add troubleshooting documentation about this

**Comment by chinesedfan** [comment]
User can also keep an eye on #1045.
