### ISSUE TITLE
Axios post return No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by xavimartz** [axios/axios#2612]
**Issue**
I want to do a request to another page and return data, but response with:
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Code**
Code snippet to illustrate your question

```js
// 
const axios2 = axios.create({
  headers: { "Content-Type": "application/json; charset=utf-8" }
});
```
I created this axios method, but I don´t know how to add the Access Control

**Comment by chinesedfan** [comment]
See everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). You need set `Access-Control-Allow-Origin` in your server codes.

**Comment by xavimartz** [comment]
I don´t have access to server, the request is from another API
