### ISSUE TITLE
Ejecting an interceptor

### ISSUE THREAD

**Issue by georgeben** [axios/axios#2615]
**Describe the issue**
I am using axios interceptors to set the authorization header of a request. Once a user is logged out, I eject that interceptor. Setting the interceptor works as expected, however when I eject the interceptor, I log the axios instance before and after ejecting. After ejecting, it authorization interceptor is still part of the axios instance, so I don't know if it is really ejected.

**Example Code**
Code snippet to illustrate your question

```js
// Sample code
const httpClient = axios.create({
  baseURL,
  headers: {
    'Content-Type': 'application/json',
  },
});

const authInterceptor = config => {
  let token = storage.loadState(constants.TOKEN)
  config.headers['authorization'] = token;
  return config;
}

function setAuthHeader() {
  httpClient.interceptors.request.use(authInterceptor)
}

function removeAuthHeader() {
  console.log('Removing auth header', {httpClient})
  httpClient.interceptors.request.eject(authInterceptor)
  console.log('After', {httpClient})
}
```

**Expected behavior, if applicable**
I am not sure. I think the ejected interceptor should no longer be on the axios instance.

**Environment:**
 - Axios Version [0.19.0]
 - OS: [Mac OS 10.13.4 ]
 - Browser [e.g. Chrome]
 - Browser Version [79.0.3945.88]
 - Additional Library Versions [Vue 2.6.10]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
Screen shot out output before ejecting
<img width="676" alt="Screen Shot 2019-12-20 at 1 34 22 PM" src="https://user-images.githubusercontent.com/40215996/71255278-c8590880-232d-11ea-966f-e8e4db4f3948.png">

Screenshot of output after ejecting
<img width="895" alt="Screen Shot 2019-12-20 at 1 34 12 PM" src="https://user-images.githubusercontent.com/40215996/71255330-e7f03100-232d-11ea-8b32-da19c3390a25.png">

Thanks! I would appreciate any feedback

**Comment by chinesedfan** [comment]
Please save the returned id and `eject` with that as the parameter.

```js
const myInterceptor = axios.interceptors.request.use(function () {/*...*/});
axios.interceptors.request.eject(myInterceptor);
```
