### ISSUE TITLE
CORS policy(spring oauth2 integrated sso) 

### ISSUE THREAD

**Issue by lewis-ing** [axios/axios#2616]
This is error info（please）:
Access to XMLHttpRequest at 'http://192.168.3.99:8001/oauth2/authorization/demo' (redirected from 'http://192.168.3.99:9080/sitianjian/auth/user-info') from origin 'http://192.168.3.99:9080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by chinesedfan** [comment]
See everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). What you need is to make your server supports CORS.
