### ISSUE TITLE
Mention different merge mechanisms for config fields

### ISSUE THREAD

**Issue by chinesedfan** [axios/axios#2618]
**Section/Content To Improve**
Section "Config order of precedence".

**Suggested Improvement**
The current implementation of `mergeConfig` use different merge mechanisms depends on different fields. Sometimes users felt confused, like #1000.

We should mention detailed fields in the document, or at least provide a link to the source code.

**Relevant File(s)**: README.md

**Comment by nyitnyitnet** [comment]
Jack tk j":

**Comment by jasonsaayman** [comment]
Hi

Axios docs have now been moved to a new repo [https://github.com/axios/axios-docs](https://github.com/axios/axios-docs). We have decided on a new repo with a website that is built to handle this. Please can you add a pull request to that repo.

Thanks
