### ISSUE TITLE
axios load error. 429

### ISSUE THREAD

**Issue by serendipity1004** [axios/axios#2620]
I am loading axios like below

`<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
`

and below error is caused.

<img width="737" alt="Screen Shot 2019-12-24 at 1 21 57 PM" src="https://user-images.githubusercontent.com/20388249/71393570-80e5bb80-2650-11ea-8320-209e432e7e5e.png">

I didn't have this issue until just few hours ago. Is there a bug in the update?

**Comment by doolri1276** [comment]
Try downloading the actual .js file.

**Comment by cyrilxx** [comment]
me too, hope this can be fix

**Comment by serendipity1004** [comment]
confirmation that it is the statics server problem. yarn is still able to download the package so I ended up serving my own. Close the issue when it's fixed. Thanks.

**Comment by osydoo** [comment]
me too....we service not work;;;;

**Comment by Shumpei0111** [comment]
me too.
Though, I download the js file( npm install axios ) now.
It's working now.

**Comment by flyingSquirrel-dev** [comment]
You are able to resolve this issue by installing axios module with npm (like **npm install axios**).
however, for me(or if you can't use npm or something),
I just have inserted a raw js file into <head></head> to fix this issue immediately.
https://github.com/axios/axios/blob/master/dist/axios.min.js
It is not a best choice but hope this can be helpful!

**Comment by cyrilxx** [comment]
i fix it using another cdn https://cdnjs.com/libraries/axios

**Comment by yasuf** [comment]
looks like it's fixed and it's an issue with unpkg, thank you everyone!
