### ISSUE TITLE
Form Data with file and JSON

### ISSUE THREAD

**Issue by binubadarudeen** [axios/axios#2621]
**Describe the issue**
How to send multipart-form-data request with a file and JSON ?
When we are trying to send file and JSON, JSON is treated as text/plain. Where and how to set the content-type of the sub parts.

**Example Code**

```js
  const formData = new FormData();
  formData.append('fileName', fileName[0]); //text
  formData.append('attachment', file[0]); //bytes
  formData.append('jsondataRequest', JSON.stringify(jsondata)); //JSON
  return axios
    .post('/upload', formData)
    .then(response => response.data);
};
```

**Expected behavior, if applicable**
We are able to send a file and JSON data together to REST end point, Content-Type of each of the parts are maintained.

**Environment:**
 - Axios Version [0.19.0]
 - Browser [Chrome]
 - Additional Library Versions [React 16.9]

**Additional context/Screenshots**
Tried different workarounds, but not working.

**Comment by yasuf** [comment]
You can change the defaults of the request, https://github.com/axios/axios#global-axios-defaults or use interceptors to set the headers as well, https://github.com/axios/axios#interceptors. Let me know if that helps, closing for now, feel free to reopen if there are issues after this

**Comment by binubadarudeen** [comment]
Thank you @yasuf for the reply. Using interceptors is not going to solve the issue, at least not easily. We are now splitting the process of uploading file and JSON data to avoid this issue. Thanks for the support.
