### ISSUE TITLE
custom key in config

### ISSUE THREAD

**Issue by ijandc** [axios/axios#2622]
In the old version
I can add custom key to config
But the newest version cant due to this [modify](https://github.com/axios/axios/blob/master/dist/axios.js#L1502)
Could you resolve it please?

**Comment by xwwLmm** [comment]
I have met same problem. How can I add custom key in config now?

**Comment by ligouhai** [comment]
I have also encountered the same problem, which is currently solved by backtracking @0.18.1, but it is not a long-term solution

**Comment by chinesedfan** [comment]
Fixed by #2207 but has not released yet.

**Comment by ijandc** [comment]
@chinesedfan 
中国范，什么时候发布啊？

**Comment by ijandc** [comment]
so,when will  #2207 be released?

**Comment by chinesedfan** [comment]
@ijandc v0.19.1 has been just released yesterday.
