### ISSUE TITLE
Error objects unreasonably large when JSON-serialized

### ISSUE THREAD

**Issue by cdhowie** [axios/axios#2624]
**Describe the issue**
This isn't so much an issue with axios as it is a very bad interaction between axios and any kind of logging that does error serialization (e.g. bunyan). The error objects generated by axios contain references to all kinds of potentially gigantic state, some of which isn't even related to the current request:

* `request.socket` can contain large buffers of request data that is mostly redundant.
* `request.agent` can contain sockets for _every active HTTP connection_ which means large buffers for potentially many unrelated requests.
* These values could be accessible from other paths (`config.agent` and `response.agent` are two that I noticed).

This is a tricky problem because it's not really an axios issue, nor is it a bunyan issue per se. However, JSON-serializing error objects is not that uncommon and, unfortunately, JSON-serializing axios' error objects can in fact exhaust the available JS heap memory and terminate the node instance.

Considering how much of the detail provided by axios' error objects could be considered internal, it would be helpful if axios could assist in resolving this issue as it's non-trivial for a developer using both libraries to fix in each program where they are both in use.  Specific attributes must be erased from the error object graph, and this requires some very specific and unusual code gymnastics. For example, erasing attributes can damage the agent object. One effectively has to copy the error object graph but omit specific nested attributes. This is a very high burden for a developer who just wants to log some information about an HTTP error.

I would suggest that, if possible, neither an HTTP agent object nor a socket object should be accessible by traversing an object's own properties along the error object graph, perhaps "hiding" these objects from `JSON.stringify()` behind attributes that are configured to be non-enumerable.

**Example code:**
```js
const axios = require('axios');
const bunyan = require('bunyan');

const log = bunyan.createLogger({ ... });

axios.get(...)
.then(undefined, err => {
  // This line can trigger an OOM condition and bring down node.
  log.warn(err);
});
```

This example is obviously very simplified; in the case I'm running into, there are hundreds of concurrent HTTP requests, which is why the agent is holding so much state.

**Environment:**
 - Axios Version: 0.19.0
 - OS: Debian 10 "Buster"
 - Node version: v12.13.0
 - Additional Library Versions: bunyan 1.8.12

**Comment by chinesedfan** [comment]
Similar with https://github.com/axios/axios/issues/2602#issuecomment-573010904. That's why axios allows users to write interceptors I think.
