### ISSUE TITLE
Unable to catch err_connection_refused network error

### ISSUE THREAD

**Issue by yelinag** [axios/axios#2628]
I am trying to handle error case when server is down or not available so that I can display proper message to users.

I am able to catch error if it's 400 or 500 server errors. It's only when I test without starting servers, I am unable to catch the error in any way.

```
export const healthCheck = ({auth}) => dispatch => {
  dispatch({type: GET_HEALTH_API_TRIGGERED});
  try {
    axios
      .get('http://127.0.0.1:8080/api/health', {
        headers: {
          Authorization: getTokenFromAuth(auth),
          Accept: 'application/json',
        },
      })
      .then(response => {
        console.log('success tokenization');
        dispatch({type: GET_HEALTH_API_SUCCESS, payload: response});
      })
      .catch(error => {
        console.log('health check error');
        catchApiError(dispatch, error);
      });
  } catch (error) {
    console.log('health check error');
  }
};
```
In above code, none of the console log got triggered when no servers are running. Only GET_HEALTH_API_TRIGGERED event got triggered from react-redux.

In console, warning is printed as such:
```
Possible Unhandled Promise Rejection (id: 1):
TypeError: Network request failed
TypeError: Network request failed
    at XMLHttpRequest.a.onerror (file:///Applications/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js:2:77521)
```
  
In react native debugger network tab, error is as follows:
```
status: failed (net::ERR_CONNECTION_REFUSED)
Type: xhr
Size: 0B
```

react-native: "0.61.5"
axios: "^0.19.0"

I am testing in android emulator and ios simulator, it doesn't work in both of them.

**Comment by chinesedfan** [comment]
@yelinag I can see `health check error` printed in the browser. Not sure it is an issue in ReactNative.

**Comment by yelinag** [comment]
Thank you. Yeah, it could be a react native bug as well.

**Comment by yelinag** [comment]
Bug is in [react-native-axios](https://www.npmjs.com/package/react-native-axios) project which is no longer active. Referencing axios directly from `import` command resolved the issue.
