### ISSUE TITLE
axios doesn't encode single quotes in Node enviroment

### ISSUE THREAD

**Issue by cqq626** [axios/axios#2629]
**Describe the bug**
axios will encode single quotes from config.params in Browser enviroment by XMLHttpRequest according to [XMLHttpRequest spec](https://xhr.spec.whatwg.org/#the-open()-method) and [URL spec](https://url.spec.whatwg.org/#query-state). However, in Node enviroment, axios use [encodeURIComponent to encode params](https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js#L5) which doesn't encode single quote.

**Expected behavior**
axios will encode single quotes from config.params in Node enviroment as same as Browser enviroment

**Environment:**
 - Axios Version [0.19.0]
 - OS: [OSX 10.14.6]
 - Browser [Chrome]
 - Browser Version [78]

**Comment by chinesedfan** [comment]
Hi, I don't see any differences between them. Because they use the same codes, lib/helpers/buildURL.js. Can you provide a sample test code?

**Comment by cqq626** [comment]
`axios({
        method: 'get',
        url: 'http://127.0.0.1:8080',
        params: {
          data: "'test'"
        }
      });`
In Node enviroment, url will be `http://127.0.0.1:8080/?data='test'`.
In Broswer enviroment, url will be `http://127.0.0.1:8080/?data=%27test%27`.
XMLHttpRequest will do the transition automaticlly, while node http module won't.

**Comment by chinesedfan** [comment]
@cqq626 OK. Where did you check those urls? Did them cause your server failed to parse?

**Comment by cqq626** [comment]
@chinesedfan In Node enviroment, I use Charles to check. In Broswer enviroment, I use Chrome develop tools. My server got failed in Node enviroment, but the reason should be my own server codes. It just tooks my too much time to locate this problem as my codes works well in Broswer enviroment.

**Comment by chinesedfan** [comment]
You'd better check them by the same tool, like Charles. If there is nothing wrong in axios, I will close this issue now.
