### ISSUE TITLE
Passing greater than or lower than in params

### ISSUE THREAD

**Issue by Mangosteen-Yang** [axios/axios#2635]
Now I am using:

```
axios.get('/user', {
    params: {
      ID: 12345
    }
})
```

to make a request and I will get `/user?ID=12345`
However, I need `/user?ID>12345`
How can I set my params?

I tried { ID: '>12345' }, what I got is `/user?ID=%3E12345`

**Comment by alajfit** [comment]
This happens to make the URL valid, you can read more about this here - https://perishablepress.com/how-to-write-valid-url-query-string-parameters/

this could be closed now
