### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by zeroidentidad** [axios/axios#2638]
**Bug**
I try to install axios dependencie on a React project but each time got npm ERR! messages as follow:

> npm ERR! Unexpected end of JSON input while parsing near '...f7KM8n6NFojyJ5xwyHZY5'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/chucho/.npm/_logs/2020-01-04T16_27_08_882Z-debug.log

Image:
![captura](https://user-images.githubusercontent.com/2924638/71768876-27974b00-2ee0-11ea-9769-e7451639d733.png)

**To Reproduce**
npm install --save axios

**Expected behavior**
A axios installation without npm ERR! messages

**Environment:**
 - OS: Ubuntu 18.04.3 LTS
 - Additional Library: React 16.12.0

*Log file:*
[2020-01-04T16_27_08_882Z-debug.log](https://github.com/axios/axios/files/4022154/2020-01-04T16_27_08_882Z-debug.log)

**Comment by zeroidentidad** [comment]
using yarn add axios it works but I infer is trying with a cache previous installation, maybe, I dont know

**Comment by AssetKid** [comment]
First link when I searched for `npm ERR! Unexpected end of JSON input while parsing near` .

https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack

`npm cache clean --force` is the suggested solution

Always important to search online first.

**Comment by chinesedfan** [comment]
It looks more like an issue of `npm`, instead of `axios`. And seems solved by cleaning the cache.
