### ISSUE TITLE
exceptions in interceptor definition are silently swallowed

### ISSUE THREAD

**Issue by barroudjo** [axios/axios#2640]
**Describe the bug**
Throw an error in an interceptor definition. It won't show up in the console.

**To Reproduce**

```js
axios.interceptors.request.use(
  function (config) {
    throw new Error('an error');
  }
);
```

**Expected behavior**
I would expect the error to appear in the console.

**Environment:**
 - Axios 0.19.0
 - OS: win10
 - Browser chrome 79, ie11
 - React 16.12

**Comment by chinesedfan** [comment]
Remember to catch it. Remind me with your detailed codes if not solved.

```
axios.get(url).catch(console.log);
```

**Comment by barroudjo** [comment]
Since the error hasn't been generated by axios, or by a request with a HTTP error code, shouldn't that instead result in log in the console such as this one ?
````
Uncaught (in promise) Error: an error
```

**Comment by chinesedfan** [comment]
Tested locally and output "Uncaught (in promise) Error: an error" as expected. I am afraid that you need provide a full runnable example.

**Comment by barroudjo** [comment]
Here is jsbin: https://jsbin.com/pofeladavo/edit?html,css,js,console,output

**Comment by chinesedfan** [comment]
@barroudjo Do you mean jsbin didn't show the correct output? In fact, it is there but I don't know why jsbin didn't show in its output tab.

![image](https://user-images.githubusercontent.com/1736154/72215837-ab41df00-3553-11ea-9fe7-e59f021affec.png)

**Comment by barroudjo** [comment]
It would appear you are right and the problem is not directly caused by axios, as copy pasting the following code does give the "Uncaught (in promise) Error: an error":
```javascript
function addScript(src, callback) {
  var s = document.createElement('script');
  s.setAttribute('src', src);
  s.onload = callback;
  document.body.appendChild(s);
}

addScript('https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.1/axios.js', () => {
  axios.interceptors.request.use(
    function (config) {
      throw new Error('an error');
    }
  );
  
  axios.get('https://httpbin.org/get')
    .then(function(res) {
      console.log(res);
    });
});
```
