### ISSUE TITLE
XSS detection breaking react app (still too loose)

### ISSUE THREAD

**Issue by fraywing** [axios/axios#2644]
**Describe the bug**
Just upgraded to 19.1, and getting an XSS issue on the new XSS detection changes. (The regex is still too loose)

**To Reproduce**
Test this URL `http://localhost:3000/login?redirect=/work/gigs?onboardingComplete=true` with the regex

**Expected behavior**
Not to pass

**Environment:**
 - Axios Version [e.g. 0.19.1]

**Additional context/Screenshots**

**Comment by vipzhicheng** [comment]
Same here, my case is ?online=0, trigger the error.

**Comment by paradite** [comment]
FYI, offending PRs: https://github.com/axios/axios/pull/2464 https://github.com/axios/axios/pull/2529
offending code: https://github.com/axios/axios/blob/v0.19.1/lib/helpers/isValidXss.js

**Comment by chinesedfan** [comment]
Let's track in #2646. Forgive me even though this issue is opened first.
