### ISSUE TITLE
Requests to urls containing 'javascript' are failing 

### ISSUE THREAD

**Issue by arunas-stonis** [axios/axios#2646]
It seems that axios v0.19.1 introduced a new bug. 

The bug comes from https://github.com/axios/axios/pull/2464

All urls containing `javascript`keyword is throwing XSS error.  So, all following urls cannot be used in axios any more:

- https://www.javascript.com
- https://stackoverflow.com/questions/tagged/javascript
- https://www.google.com/search?q=javascript

Here is a link to regexp: https://regexr.com/4rsst

Expected behavior: axios should accept `javascript` in urls

**Comment by StefanOfigo** [comment]
In addtion, all Urls containing parameter starting with on... are failing.

Expected behavior: axios should accept parameter starting with on

**Comment by fvandenbulcke** [comment]
In addtion, my case:

A static html file loading a bundled script.
The error is thrown when the file absolute path containing "javascript"
Ex: file:///my-path/some-thing-javascript/index.html

**Comment by Kolobok12309** [comment]
+1 have problem with path `/?online=true`

**Comment by bstream** [comment]
I have the same problem with `?onlyInStock=true`

**Comment by fitravel** [comment]
I have the same issue with ?onlyWithFlights=true

**Comment by Sayid1** [comment]
A new version is urgently needed to solve this problem

**Comment by AlexandreBourdeaudhui** [comment]
Same here with an internal url which contain `javascript`

**Comment by jonathanbardo** [comment]
I honestly would deprecated 0.19.1 as soon as possible. This can cause major problem on production apps.

**Comment by flakesrc** [comment]
I have the same error when the url contains `javascript`

**Comment by baconcheese113** [comment]
![image](https://user-images.githubusercontent.com/1386713/73129120-c40db400-3f99-11ea-92bd-c641ed3452e7.png)
I get this error after upgrading from `0.19.1` to `0.19.2`
`Unable to resolve module ./isValidXss from node_modules\axios\lib\helpers\isURLSameOrigin.js`

**Comment by chinesedfan** [comment]
@baconcheese113 It's a common error occurs in RN. Please reinstall all dependencies in node_modules and do some clean cache operations. If you think even a simple Node.js script will thrown such error, feel free to open a new issue with detailed information.

**Comment by arjdev69** [comment]
> ![image](https://user-images.githubusercontent.com/1386713/73129120-c40db400-3f99-11ea-92bd-c641ed3452e7.png)
> I get this error after upgrading from `0.19.1` to `0.19.2`
> `Unable to resolve module ./isValidXss from node_modules\axios\lib\helpers\isURLSameOrigin.js`

Just add isValidXss a folder helpers of axios.

Link: https://github.com/axios/axios/blob/351cf290f0478d6e47e74c6da2f3ad8fe8f29887/lib/helpers/isValidXss.js

**Comment by Andrfas** [comment]
Isn't this a braking change for the library? I got my application crashed because in my package.json I had `^0.19.1`, and npm updated axios to 0.19.2, and one of the libraries was using isValidXss.

I thought such changes got released with Minor number updated, not patch. What do you think?
