### ISSUE TITLE
When responseType is set to json, then response.data is undefined (only in IE9)

### ISSUE THREAD

**Issue by msevera** [axios/axios#265]
I've set responseType property to 'json'. In all browsers except IE9 this works ok. Only in IE9 the response.data is undefined. I've debugged it a bit and found file called xhr.js which has handler for ready state. So there is code which works in next way:
If the responseType is not set to 'text' or '' then for responseData you use request.response property.
The issue here that in IE9 there is no such property. 
![image](https://cloud.githubusercontent.com/assets/2269852/13728869/e63bf82c-e92e-11e5-8106-411179ba15b6.png)

**Comment by nickuraltsev** [comment]
Yes, looks like `XMLHttpRequest.response` is supported in IE 10+. This needs to be fixed.

**Comment by adamredwards** [comment]
I am also seeing this behaviour in IE 9 with the axios library. Can we expect the fix in @yp's fork to make it's way into release?

**Comment by Teddy-Schmitz** [comment]
We are also seeing this in Android Versions < 4.4.4 which don't support json as a responseType.  Is there any hope of getting @yp's fork into release to fix this issue?

**Comment by wang7x** [comment]
We are also seeing this in IE8, we use this temporary solution
```js
axios.interceptors.response.use(
  response => {
    // IE 8-9 
    if (response.data == null && response.config.responseType === 'json' && response.request.responseText != null) {
      try {
        // eslint-disable-next-line no-param-reassign
        response.data = JSON.parse(response.request.responseText);
      } catch (e) {
        // ignored
      }
    }
    return response;
  }
```

**Comment by jasonsaayman** [comment]
Thanks for logging this issue, however, I think this is now stale. I am going to close this for now as IE9 has lost official support since March 31, 2017.
