### ISSUE TITLE
Moxios not working in 0.19.1

### ISSUE THREAD

**Issue by neomedeiros** [axios/axios#2650]
Moxios last version (0.4.0)  just stopped working with Axios 0.19.1.

I just changed back Axios version in my project (0.19.0) and it's working fine.

Any idea why?

**Comment by chinesedfan** [comment]
@neomedeiros Can you provide detailed code examples or error messages, as the issue template required?

**Comment by DanielRuf** [comment]
https://github.com/axios/moxios/issues/71

https://github.com/axios/axios/compare/v0.19.0...v0.19.1

Maybe you can find the culprit with `git bisect` by cloning axios into your node_modules or using `axios/axios`.

**Comment by neomedeiros** [comment]
I've got no message in my real-world project, the stubRequest() function simply did not stub a given request. I've just tried to create a minimal project in order to reproduce the error, but no luck:

https://github.com/neomedeiros/axios-2650

I will try to get more details about the issue in the real-world project and post it here.

**Comment by brandon-leapyear** [comment]
@neomedeiros I think the issue is if you change `todos.js` in your repro project to use
```js
axios.get('/todos', { baseURL: 'https://...' })
```

I'm finding that if I do `stubRequest` with just the path instead of the full path, it works

**Comment by brandon-leapyear** [comment]
It broke here: https://github.com/brandon-leapyear/axios/commit/6fe506fda290ba935c2641f68f1fcba7f4a16cd3

Will try to put up a PR soon

**Comment by brandon-leapyear** [comment]
this issue still has open PRs against it

**Comment by chinesedfan** [comment]
@brandon-leapyear See https://github.com/axios/axios/pull/2751#issuecomment-642223008. Can you check for that?

**Comment by fraywing** [comment]
@brandon-leapyear @chinesedfan have you all not achieved consensus on a fix for this?
