### ISSUE TITLE
How to pass the url I am getting with axios as a prop in VueJS?

### ISSUE THREAD

**Issue by N1Mirzo** [axios/axios#2657]
**Described the issue**
I have a JSON data coming from so many urls like this one https://api.myjson.com/bins/188hw8 .
And I used them for a carousel. Just all the data coming from the API is being rendered.

![image](https://user-images.githubusercontent.com/55438076/72235761-b8afa580-35f5-11ea-8a16-b26762b2413a.png)

But I wanted to use the carousel in so many places. That's way, I make a global component called PrimaryCarousel.vue. And make the carousel dynamic. But there is a problem. In every carousel, I had to render another data. And it shouldn't like the carousels in the above picture. I must render the second carousel with another data. So I know I have to use another API or the second data in an API. So I have to make the URL of this axios get request dynamic. How I can?
**Example Code**
```
    <swiper-slide v-for="(user, index) in userInfo" :key="index" class="row justify-evenly">
      <q-card class="my-card">
        <img class="product-pic" :src="user.pic" alt="not found" />
        <q-card-section>
          <div class="text-subtitle2">Posted by {{ user.author }}</div>
          <div class="text-h6">{{ user.name }}</div>
        </q-card-section>
        <q-card-section class="row justify-between">
          <p class="text-subtitle2">Now {{ user.nowprice }}</p>
          <p class="text-subtitle2">Was{{ user.oldprice }}$</p>
        </q-card-section>
      </q-card>
    </swiper-slide>
```
```
import axios from "axios";
<script>
export default {
  created() {
    axios.get("https://api.myjson.com/bins/188hw8").then(response => {
      this.userInfo = response.data;
    });
  },
  data() {
    return {
      userInfo: [],
    }
}
}
</script>

```
**Expected behavior, if applicable**
Expected to see different data in every carousel namely passing the axios get request url as a prop.

**Environment:**
 - Axios Version [latest]
 - OS: [Windows, Mac]
 - Browser [Chrome, Mozilla Firefox]
 - Browser Version [79.0.3945.117 (Official Build) (64-bit) (cohort: Stable), Mozilla browser is in the  latest version]
 - Additional Library Versions [Vue awesome swiper bu Surmon China]

**Comment by chinesedfan** [comment]
Sorry, it is not an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).
