### ISSUE TITLE
Incorrectly caught XSS injection attempt

### ISSUE THREAD

**Issue by CammyMurrie** [axios/axios#2660]
**Describe the bug**
applying a query string parameter ("onlyApproved=true" in this instance), is throwing `URL contains XSS injection attempt`.

**To Reproduce**
perform an `axios.get` request (not tried any other methods) with any query string parameter beginning with `on`.

```js
https://randomdomain.com/api/endpoint?onlyRandomThings=true
```

**Expected behavior**
This should not be caught as valid XSS.

**Environment:**
 - Axios Version [0.19.1]
 - OS: [Windows 10 Professional]
 - Browser [all]
 - Browser Version [all]
 - Additional Library Versions [React 16.12]

**Comment by fsubal** [comment]
> Axios Version [0.19.0]

Isn't 0.19.1 ? I also had the same issue after updating from 0.19.0 to 0.19.1

**Comment by CammyMurrie** [comment]
@fsubal you're right it's 0.19.1
updated issue 👍

**Comment by dson** [comment]
Same issue here. Seems to be introduced by https://github.com/axios/axios/pull/2464, that no longer ignores the return value of `isValidXss`, but throws an error when a url is considered an XSS attempt. The actual problem is the regex in `isValidXss`:

```javascript
/(\b)(on\S+)(\s*)=|javascript|(<\s*)(\/*)script/
```

that also matches valid urls:

```javascript
isValidXss("/projects?onlyActive=true"); // true
```

**Comment by chinesedfan** [comment]
Duplicate of #2646. And sorry for this stupid bug. Hope maintainers who have publish permission like @emilyemorehouse can fix it soon.
