### ISSUE TITLE
Identify 127.0.0.1 as localhost when processing NO_PROXY

### ISSUE THREAD

**Issue by bjowes** [axios/axios#2667]
**Is your feature request related to a problem? Please describe.**
I am using axios in my own project cypress-ntlm-auth, and I need to support environments where corporate proxies are used. I found it very confusing that setting NO_PROXY to localhost didn't work for requests to 127.0.0.1. I had to review the axois source code to find that no such check is performed.
 
**Describe the solution you'd like**
Add a comparison [close to this line](https://github.com/axios/axios/blob/03e6f4bf4c1eced613cf60d59ef50b0e18b31907/lib/adapters/http.js#L125) that checks the special case when hostname is localhost or 127.0.0.1

**Describe alternatives you've considered**
Setting NO_PROXY to localhost,127.0.0.1 seems a bit redundant and node supports this check natively.

**Additional context**
If the feature request is accepted I would be happy to provide the PR for it.

**Comment by bjowes** [comment]
A possibly even better solution would be to implement this [like cypress](https://github.com/cypress-io/cypress/issues/4780), where localhost and 127.0.0.1 are presumed to be included in NO_PROXY unless they are explicitly excluded with a <-loopback> setting.

**Comment by jasonsaayman** [comment]
I don't think this is something we would support in Axios. I would suggest looking at using the env to decide programmatically if you need to proxy or not.

**Comment by bjowes** [comment]
Could you explain your reasoning a bit further? 

Node provides three environment variables to configure proxy behaviour: HTTP_PROXY, HTTPS_PROXY and NO_PROXY. All of these are already supported by axios. I am just requesting that the way they axios support the NO_PROXY variable should mimic the way Node uses it (or how cypress uses it).

**Comment by jasonsaayman** [comment]
Ok cool, please open a pull request to add the feature and tag me to review.
