### ISSUE TITLE
Allow baseURL to contain GET query parameters

### ISSUE THREAD

**Issue by mmomtchev** [axios/axios#2668]
I am using an old API from the HTTP GET query parameters era (NCEP NOAA) and my 4KB HTTP GET contains tons of query parameters.

I would like to be able to set a baseURL and then just add the parameters that change at every request.

Please consider this pull request.
#2669

**Comment by mmomtchev** [comment]
https://github.com/axios/axios/pull/2669

**Comment by mmomtchev** [comment]
#2669 https://github.com/axios/axios/pull/2669

**Comment by textbook** [comment]
If #2656 gets merged you'd be able to put the params that don't change in as the defaults. As a workaround you can merge with the defaults yourself, e.g. `axios.get("/some/path", { params: { ...defaultParams, variable: "params" } })`

**Comment by jasonsaayman** [comment]
#2656 was merged please use the above solution.
