### ISSUE TITLE
isValidXss helper works incorrectly

### ISSUE THREAD

**Issue by mspiderv** [axios/axios#2670]
**Describe the bug**
Function [`isValidXss`](https://github.com/axios/axios/blob/master/lib/helpers/isValidXss.js) works incorrectly.

**To Reproduce**
```js
// I just copy & paste the function declaration
function isValidXss(requestURL) {
  var xssRegex = /(\b)(on\w+)=|javascript|(<\s*)(\/*)script/gi;
  return xssRegex.test(requestURL);
};

// Calling this will result in `true`
isValidXss('https://www.somedomain.com?only=true')
```

**Expected behavior**
I expect the previous function call to result in false. I see no XSS attack in there.

**Environment:**
 - Axios Version 0.19.1

**Comment by Larsrdev** [comment]
Yea sir you are right! I also saw this yesterday. We now have problems with some URL params like this:

`files=&names=&onlyMarkedOnes=false&batchSize=20&offset=0`

Im not deep into XSS. Why is there the "(on\S+)" in the regex?

**Comment by Larsrdev** [comment]
https://github.com/axios/axios/issues/2663

https://github.com/axios/axios/issues/2646

https://github.com/axios/axios/issues/2645

**Comment by chinesedfan** [comment]
Duplicate of #2646.
