### ISSUE TITLE
has axios 'http session'?

### ISSUE THREAD

**Issue by creatxrgithub** [axios/axios#2672]
i use headless (e.g. puppeteer-core) or python 's requests could get the result (result code 200)

with axios, 

`
let cookieJar = new tough.CookieJar();
let instance = await axios.create({
	jar:cookieJar,
	withCredentials: true,
	httpsAgent: new https.Agent({ rejectUnauthorized: false, requestCert: true, keepAlive: true }),
	headers: {
		"user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
	}
});

let res = await instance.get(baseUri);

instance.defaults.headers['referer'] = 
.........//set the headers
instance.defaults.headers.Cookie = res.headers['set-cookie'];

res = await instance.post(`${baseUri}/${postUrl}`, ....

`

the result always get 404

after compare the results that i successed with python code, different session has a different token value. 

so i question is: is instance simulate to http 's session?

if not, the token must be change when i invoke instance.post()

thanks

**Comment by mr47** [comment]
I think you should use `instance.defaults.headers.common` NOT `instance.defaults.headers`.
Example same problem -> https://github.com/axios/axios/issues/1346

**Comment by creatxrgithub** [comment]
@mr47 

i've tried. it's not work.

other case, i make a 3rd-party authentication with nodebb, i use `instance.defaults.headers['x-csrf-token'] = res.data.csrf_token` that is a cookie based authentication.

in this case, it must have session based authentication, cause in the python 's code, i find there are some headers changed if i make a new request, and it also request cookie

**Comment by chinesedfan** [comment]
@creatxrgithub I don't think axios has the same session thing. And your problem seems to be similar with #2623.

Well, the key point is to find out what headers you expect and what headers axios sends actually. If possible, provide a tiny reproducible example would be better.

**Comment by chinesedfan** [comment]
> so i question is: is instance simulate to http 's session?

No. And closed due to stale and seems not like an issue of axios.
