### ISSUE TITLE
status: 400,   statusText: 'Bad Request'

### ISSUE THREAD

**Issue by rlee1990** [axios/axios#2675]
I keep getting this response when using Axios to get an access token from Instagram.

My Code:
`async function mintAuthToken(req: any): Promise<string> {
    const base = 'https://api.instagram.com/oauth/access_token';

    const queryParams = { 
      client_id: app_id,
      client_secret: app_secret,
      grant_type: 'authorization_code',
      redirect_uri: redirect_uri,
      code: req.query.code
  }

  const endpoint = base + qs.stringify( queryParams )

    const login = await axios.post(endpoint, {},{headers: {'content-type': 'application/json'}}
    );
    console.log(login);
    const accessToken = login.data.access_token;
    const instagramUserID = login.data.user.id;
    const profilePic = login.data.user.profile_picture;
    const userName = login.data.user.full_name;
    console.log(userName);
    const firebaseToken = await createFirebaseAccount(instagramUserID, userName, profilePic, accessToken);

    return firebaseToken;

};`

The full error:
`{ status: 400,
  statusText: 'Bad Request',
  headers: 
   { 'content-type': 'text/html; charset=utf-8',
     vary: 'Accept-Language',
     'content-language': 'en',
     date: 'Fri, 17 Jan 2020 22:16:38 GMT, Fri, 17 Jan 2020 22:16:38 GMT',
     'strict-transport-security': 'max-age=31536000',
     'cache-control': 'private, no-cache, no-store, must-revalidate',
     pragma: 'no-cache',
     expires: 'Sat, 01 Jan 2000 00:00:00 GMT',
     'x-frame-options': 'SAMEORIGIN',
     'content-security-policy': 'report-uri https://www.instagram.com/security/csp_report/; default-src \'self\' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src \'self\' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src \'self\' https://www.instagram.com; script-src \'self\' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net \'unsafe-inline\' \'unsafe-eval\' blob:; style-src \'self\' https://*.www.instagram.com https://www.instagram.com \'unsafe-inline\'; connect-src \'self\' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src \'self\' blob: https://www.instagram.com; frame-src \'self\' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src \'none\'; upgrade-insecure-requests',
     'x-content-type-options': 'nosniff',
     'x-xss-protection': '0',
     'x-aed': '15',
     'access-control-expose-headers': 'X-IG-Set-WWW-Claim',
     'set-cookie': 
      [ 'ig_did=D9E1610B-B50C-4A35-9B7B-6BF0C06AE976; Domain=.instagram.com; expires=Mon, 14-Jan-2030 22:16:38 GMT; HttpOnly; Max-Age=315360000; Path=/; Secure',
        'rur=FTW; Domain=.instagram.com; HttpOnly; Path=/; Secure' ],
     'x-fb-trip-id': '917726464',
     connection: 'close',
     'content-length': '11' },
  config: 
   { url: 'https://api.instagram.com/oauth/access_tokenclient_id=client id&client_secret=secret&grant_type=authorization_code&redirect_uri=redirect&code=somecode',
     method: 'post',
     data: '{}',
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'axios/0.19.0',
        'Content-Length': 2 },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] },
  request: 
   ClientRequest {
     domain: 
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [Array] },
     _events: 
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.instagram.com',
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api.instagram.com',
        _readableState: [Object],
        readable: true,
        domain: [Object],}`

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong headers, feel free to remind me to reopen.

**Comment by rlee1990** [comment]
I have checked with Instagram it works when I send a curl request it works but when I send it using axios in firebase cloud functions I am using stringify to string it all in the url

**Comment by rlee1990** [comment]
@chinesedfan

**Comment by chinesedfan** [comment]
I am afraid that you need a `?` to concat `base` and query parameters.

```
const endpoint = base + qs.stringify( queryParams )
```

**Comment by rlee1990** [comment]
@chinesedfan i already do that. I tried with ? And without it each time I get the same thing. It looks like the content type keeps getting changed no matter if I change it or not

**Comment by chinesedfan** [comment]
Can you paste the working curl script?

**Comment by rlee1990** [comment]
So this is the curl that I followed from Instagrams docs and just replace the options with my own
`curl -X POST \
  https://api.instagram.com/oauth/access_token \
  -F client_id=684477648739411 \
  -F client_secret=eb8c7... \
  -F grant_type=authorization_code \
  -F redirect_uri=https://socialsizzle.herokuapp.com/auth/ \
  -F code=AQDp3TtBQQ... `

**Comment by chinesedfan** [comment]
`-F` means the form data. So maybe you should send by `axios.post(url, data)`, instead of pending as url query parameters.

**Comment by rlee1990** [comment]
I can try that again @chinesedfan should I use the form data package with this ? When I didn’t it without it a got a bad header error but I’ll try it with the form data package

**Comment by rlee1990** [comment]
@chinesedfan it still didn't work with me adding the items as form-data. I still get the same error.

**Comment by rlee1990** [comment]
@chinesedfan nvm I used a different package to get it to work.

**Comment by chinesedfan** [comment]
@rlee1990 Sure. In fact, it should be able to work with axios, but please understand that I have no time to help step by step.

```
axios.post(url, {
    client_id: xx,
    client_secret: xx,
    ...
})
```

**Comment by NinoSoles** [comment]
> @chinesedfan nvm I used a different package to get it to work.

what package did you use? im having trouble posting form data, i get 404 when i post regular and 400 when i qs.stringify(myData)

**Comment by rlee1990** [comment]
@NinoSoles I used [https://www.npmjs.com/package/node-libcurl](url) since curl request worked and this worked.

**Comment by b02505048** [comment]
I also have the same problem with Axios and solved by using [curl-request](https://www.npmjs.com/package/curl-request).

There're a ton of problems with calling Instagram API using Axios on StackOverflow. 

However, I still believe that Axios should be able to behave like cURL. Let's see who could provide an equivalent solution in the short future...

**Comment by kemicofa** [comment]
Hello, I was getting a similar issue with communications between my microservice. It would appear that `axios` is sending the wrong `content-length` value.

The express middleware `bodyParser` noticed a mismatch and simply responded with a 400 "connection closed".
