### ISSUE TITLE
axios with 0.19.0 vresion, set axios.default.retry param invalid,but with0.16.0 is valid

### ISSUE THREAD

**Issue by linglingyun10** [axios/axios#2676]
**Describe the bug**
set axios.default.retry = 4 is not valid

```js
axios.defaults.retry = 4
axios.defaults.retryDelay = 2000
```

**Expected behavior**
axios.defaults.retry =4; axios.defaults.retryDelay = 2000   is in config object.

**Environment:**
 - Axios Version [0.19.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
Seems that `config.retry/retryDelay` are your custom configs. It may be related to #2207, which was fixed in v0.19.1.

**Comment by linglingyun10** [comment]
> Seems that `config.retry/retryDelay` are your custom configs. It may be related to #2207, which was fixed in v0.19.1.

I just tried version 0.19.1, which is still invalid

**Comment by chinesedfan** [comment]
You can try other request libraries and compare with axios to find out what the differences are. Without a reproducible code example, I am sorry that I can't help you more.
