### ISSUE TITLE
Support for React Native blob

### ISSUE THREAD

**Issue by raRaRa** [axios/axios#2677]
I've seen many people complaining about issues when uploading files with React Native. The best solution today is to use `fetch()` which supports the blob generated in React Native, but it lacks progress. Libs such as `rn-fetch-blob` can't be used in Expo since you'd need to eject.

Many libraries for React Native such as Firebase have upload method that has support for the React Native blob and it would be a great addition to Axios as well.

What I'd like to do is basically:

`await Axios.post(url, reactNativeBlob, ...)`

I've tried different methods with Axios, e.g. by creating FormData with the file details, such as uri, name and type, but then Axios tries to convert the file to base64 and upload it that way, which isn't what I want.

I don't know how React Native blobs are different from web blobs, but I'm really hoping that this could be supported in Axios.

**Comment by zusinShinpei** [comment]
did it wrap with FormData?

**Comment by piotrponikowski** [comment]
Any plans for supporting RN blob?

**Comment by chinesedfan** [comment]
Axios won't support it directly. But if someone finished it in a wrapper package, we can record it in our ECOSYSTEM.md.

**Comment by jamesaucode** [comment]
If anyone is still having trouble with working with React Native's blob and axios, here's a temporary work around that I have.

```javascript
class RNBlob extends Blob {
  get [Symbol.toStringTag]() {
    return 'Blob';
  }
}

// then on the blob that you want to work with
axios.post('api', {
  data: new RNBlob([blob])
});
```

Because of how Axios determine whether an object is a blob (see: [utils#147](https://github.com/axios/axios/blob/3958e9fbc8ebc0f72a8ce568cbf86f391d6869f3/lib/utils.js#L147)), it does a `Object.prototype.call` on the request body, but on React Native, calling `Object.prototype.call` on `Blob` returns `[object Object]` instead of `[object Blob]`, so axios will simply `JSON.stringify` as if it's a generic javascript object. The above snippet will 'trick' axios into thinking it's a Blob (which it is), and process it correctly.

**Comment by jasonsaayman** [comment]
@jamesaucode thanks that is amazing, I am going to aff it to the docs

**Comment by jamesaucode** [comment]
> @jamesaucode thanks that is amazing, I am going to aff it to the docs

Thanks, that would be helpful for React Native devs! I think it's also worth noting that the work around I posted above won't work if you are targeting ES5 or earlier (which unfortunately is the case for my project). There's still a less hacky way to get around this by changing the way `transformRequest` identifies `Blob`.

```typescript
const reactNativeBlobTransformer = [(data, headers) => {
  // it's a blob
  if (typeof Blob !== 'undefined' && data instanceof Blob) {
    return data;
  }
  // else just let the default transformer do it's thing, 
  // the default transformer is an array of function of length 1, 
  // see: https://github.com/axios/axios/blob/master/lib/defaults.js#L39
  return axios.defaults.transformRequest[0].call(null, data, headers);
}]

const rnAxiosInstance = axios.create({
  transformRequest: reactNativeBlobTransformer,
});

await axios.post({
  url: 'api',
  data: blob
});
```
You can probably change the default to just use the modified transformer instead, but I prefer to not mutate it.

You do lose these two lines for normalizing headers though
```javascript
normalizeHeaderName(headers, 'Accept');
normalizeHeaderName(headers, 'Content-Type');
```
But it's just a short util function that you can probably just copy and paste it to your code base
[normalizeHeaderName](https://github.com/axios/axios/blob/dbc634cf700595845abc43604e1fb6cea903b97f/lib/helpers/normalizeHeaderName.js#L5)
```javascript
const normalizeHeaders = (headers, normalizedName) => {
  for (const [value, name] of Object.entries(headers)) {
    if (name !== normalizedName && name.toUpperCase() === normalizedName.toUpperCase()) {
      headers[normalizedName] = value;
      delete headers[name];
    }
  }
}
```
