### ISSUE TITLE
Set name for blob upload in Edge

### ISSUE THREAD

**Issue by Wildhoney** [axios/axios#2678]
IE Edge doesn't support the `File` constructor, so I'm having immense difficulty in being able to set the name of my blob for upload.

First I used the third parameter of the `FormData`:

```javascript
const a = new FormData();
a.append('photo', photoBlob, 'photo.png');
```

However it turns out that Edge ignores the third parameter as that simply attempts to convert the `Blob` into a `File` like so:

```javascript
const b = new File([photoBlob], 'photo.png');
```

I've tried all sorts of dubious approaches &ndash; such as assigning `name` to the `Blob` object, but no approaches change the `name` unless the object is **literally** a `File` object.

How have other people tackled this issue?

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. Should you feel that this issue still exists please submit a new issue.

Thanks
