### ISSUE TITLE
 Axios query does not respond back

### ISSUE THREAD

**Issue by frtlec** [axios/axios#2680]
I am using the axios library with React native.

I've never had a problem on Android before, but I have this problem for ios:

**Axios does not return any errors or results. Timed out.**

I don't think there is a problem on the API side. API side works for Postman or axios get / post (android).

` const config = {
          headers: {
            accept: "application/json",
            Authorization: "bearer " + AuthStore.token
          },
          data: {}
        };
        const { data } = await axios.get(
          `${API_BASE}x/x`,
          config
        );`

` React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 33.89 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.6.0 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1`

**Comment by chinesedfan** [comment]
If your endpoint has an invalid https certificate, iOS will have so-called ATS(App Transport Security) problem.

Please checking **request headers** and comparing with in Android where you can get the right response. If you confirm that axios sends wrong headers, feel free to remind me to reopen.

**Comment by frtlec** [comment]
No https certificate, api answers other queries.

There are similar requests in the app, they work correctly. I can not understand why this request is not working properly. Could there be a size limit.

**Comment by chinesedfan** [comment]
You can try other request libraries and compare with axios to find out what the differences are. Without a reproducible code example, I am sorry that I can't help you more.

**Comment by 2xSamurai** [comment]
+1 I am facing this issue in Android. 

I am using Axios in react native.

I am facing this issue only in android 8 and lower versions. I also noticed something strange. In react native debugger. If you enable 'network inspect' then I get the response back. Otherwise, it gets timed out. 

I have been banging my head around this for quite some time.

Can somebody please help.

PS: Also I even tried a production build, but it also showed similar behavior.

@frtlec did you find any fix for this?
