### ISSUE TITLE
Parallel request electron

### ISSUE THREAD

**Issue by nemozar** [axios/axios#2682]
**Describe the issue**
i'm use axios in electron app. Need send many request from aelectron to server. All request send step by step (no parallels).

![Снимок экрана от 2020-01-20 23-13-21](https://user-images.githubusercontent.com/4721820/72755068-a5df3700-3bda-11ea-9307-4479c1955171.png)

Half of the requests are for a single user. The second for another.

the second user starts receiving messages only after the first user completes sending them.

When there are many users, requests will be queued and the last user will wait a very long time for the first message.

When i use async/await requests are sent in parallel to two users. But this is much longer than without await
```
let sendUser = async (user, postDataList) => {
for (const item of postDataList) {
    await axios.post('http://api.photo/api/albums/access/send/' + command.data.access_uuid, item)
}
      
await axios.all(postDataList.map(data => axios.post('http://api.photo/api/albums/access/send/' + command.data.access_uuid, data)))
}

sendUser('user1', [{},{}, ...{}])
sendUser('user2', [{},{}, ...{}])
```

work parallel only when send axios request in for of, but this so slow. When using await axios.all request send step by step

**Comment by chinesedfan** [comment]
Yes, `await` means waiting for completion. I didn't see what things axios can do. Please remind me if I misunderstood something.
