### ISSUE TITLE
Error when validate Xss 

### ISSUE THREAD

**Issue by lesterpascua** [axios/axios#2685]
**Describe the bug**
When set url: 

1.  https://localhost:44302/api/v1/contract?order%5B0%5D.ascendant=false&order%5B0%5D.name=id&pagging.page=0&pagging.pageSize=9&filter.code9=222&filter.onlyAgency=true

2. https://localhost:44302/api/v1/contract?code9=222&onlyAgency=true 

Fail function isValidXss
line: 1464                    var xssRegex = /(\b)(on\w+)=|javascript|(<\s*)(\/*)script/gi;

**To Reproduce**
Open devTools (F12) in chrome
```js
var xssRegex = /(\b)(on\w+)=|javascript|(<\s*)(\/*)script/gi;
xssRegex.test('https://localhost:44302/api/v1/contract?code9=222&onlyAgency=true')
```

**Expected behavior**
must print false

**Solution**
Fix regular expression

**Environment:**
 - Axios Version: 0.19.1
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 79
 - Additional Library Versions: React 16.12

**Comment by chinesedfan** [comment]
Duplicate of #2646. And fixed in 0.19.2.
