### ISSUE TITLE
Impossible to send an insecure request

### ISSUE THREAD

**Issue by xGuIInE** [axios/axios#2686]
I want to send a POST request from a VUE PWA web app to an esp32 iot device with a https server runing. I use a custom https agent:
```js
const agent = new https.Agent({
          rejectUnauthorized: false,
        });
this.axios.get('https://192.168.4.1/hello', {httpsAgent: agent}).then(() => {
          ...
        }).catch(...)
```
The esp32 server has a self signed ssl certificate
I´m having this problem since 6 months ago... I have tried 100000 different solutions and impossible... 
When someone ask something like me, no answers always... (ex: https://forum.vuejs.org/t/cant-make-vue-axios-or-vue-request-to-work-with-https-self-signed-certificate/17851)

Please help... I´m desesperated with this... my product is ready waiting for this fucking shit...

**Environment:**
 - Axios Version = 0.19.1
 - OS: Tried in IOS, Android, Windows, Mac...
 - Browser Chrome, Firefox, Safari

**Comment by textbook** [comment]
That's down to the _browser_, surely? That's what's actually making the request, I don't think Axios has any control over that. Also please edit the profanity out of your issue, just outline the actual _problem_.

**Comment by xGuIInE** [comment]
Yeah... exactly... it´s impossible to make the request throught the browser...
So I have to create a native android app only for send that request... haha
Thank you!
