### ISSUE TITLE
Axios not posting correctly even tho form data and url is correct

### ISSUE THREAD

**Issue by NinoSoles** [axios/axios#2687]
**Describe the issue**
Im trying to post form data to a url and it gives me a 400 status code. However, the post seems to go through as i get the desired landing url page in the error config. Im not sure if axios is unable to handle the redirect as the url in the error config is the desired url. If I don't put querystring.stringify(shippingInfo) it gives me a 404 Status Code. I double checked to make sure my form data is correct as well. If you would like to replicate the error you can use that same url in my shippingInfoOptions and check the networks tab under dev mode in your browser.

**Example Code**
Code snippet to illustrate your question

```js
let notLoaded = true
    while (notLoaded){
       let shippingInfoOptions = {
            method : 'post',
            url : 'https://shopnicekicks.com/2192362/checkouts/76bd298006aad2f8ae6ec1e460ccfccal',
            data: querystring.stringify(shippingInfo), 
            headers : {'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'},
            jar: cookieJar,
            withCredentials: true}
        
        try {
            var checkoutGenResponse = await axios(checkoutGenOptions)
        } catch (error) {
            console.log(error)
        }
        if (checkoutGenResponse.status == 200){
            notLoaded = false}


```

**Expected behavior, if applicable**
When I post the data it should give a 200 Status Code and my final URL should contain 
**?previous_step=contact_information&step=shipping_method'**. 

**Environment:**
 - Axios Version 0.19.1
 - Mac OS 10.15.2 
 - Node JS
 - Axios-cookiejar-support@0.5.1
 - tough-cookie@3.0.1

**Additional context/Screenshots**
I believe the post is going through successfully but Axios is not redircting properly, In the screenshot below you can see that my url contains **previous_step=contact_information&step=shipping_method**
but its making a Get request when I put my method as Post. I did the same request with Python using the same form data and it worked with a 200 Status Code. 
![Image from iOS (1)](https://user-images.githubusercontent.com/49324619/73033709-d6101b00-3e10-11ea-807e-0a3b62e41f73.jpg)

**Comment by NinoSoles** [comment]
Seems to be a axios issue, I did the same process with requests-promise and it works. Not sure what the issue is on axios

**Comment by chinesedfan** [comment]
Please check **url** and **request headers** and comparing with other ways when you can get the right response. You can get them from Chrome's network panel.

**Comment by chinesedfan** [comment]
Closed due to stale.
