### ISSUE TITLE
ns.GetCommandSrc is not a function

### ISSUE THREAD

**Issue by maifeeulasad** [axios/axios#2692]
**Describe the bug**

When I'm connected to the internet, I get error saying `ns.GetCommandSrc is not a function`, but when I disconnect from the internet, everything works just fine.

**Expected behavior**
It should have worked when connected to internet 

**Environment:**
 - Axios Version : ^0.19.0
 - OS : Win10
 - Browser : Chrome
 - Browser Version : 79
 - Additional Library Versions : "react": "^16.12.0"

**Additional context/Screenshots**

![Screenshot (119)](https://user-images.githubusercontent.com/29339330/73131197-f9191580-4030-11ea-9379-af6437a60f3a.png)
![Screenshot (118)](https://user-images.githubusercontent.com/29339330/73131199-f9191580-4030-11ea-8aa9-966a35531071.png)

**Comment by chinesedfan** [comment]
Can you paste your source codes that related to axios?

**Comment by maifeeulasad** [comment]
@chinesedfan the code below is responsible for fetching and loading this component...
```
componentWillMount() {
        this.setState({assignmentID:this.props.assignmentID},()=>
            {
                console.log("Loading assignment : "+this.state.assignmentID);
                let url=constants.serverURL+"assignment/"+this.state.assignmentID;
                console.log(url);
                let user=localStorage.getItem('user');
                let data=
                    {
                        "userDTO":JSON.parse(user)
                    };
                //console.log(data);
                axios.post(url,data)
                    .then((res)=>{
                        console.log(res.data);
                        this.setState({problemStatement:res.data.problemStatement});
                        this.setState({lastTime:res.data.lastTime});
                        this.parseList(res.data.userDetDTO);
                        this.setState({loading:false});
                    })
                    .catch((err)=>console.log(err));
            }
        );
    }
```

**Comment by chinesedfan** [comment]
> This function is coming from Kaspersky javascript injection. Solved it by disabling Inject scripts into web traffic to interact with web pages

See more from https://stackoverflow.com/questions/59893809/axios-post-request-not-sent-to-external-url-typeerror-ns-getcommandsrc-is-not.
