### ISSUE TITLE
Interceptors stopped using axios.defaults.headers

### ISSUE THREAD

**Issue by dollock** [axios/axios#2694]
We update axios from 0.18.1 to 0.19.1 and axios interceptors stopped using correctly axios.default.headers, we had to set it for interceptors manually.

For 0.18.1:

```
axios.defaults.headers.common[‘AUTHORIZATION’] = `Bearer ${token}`;
axiosInstance.interceptors.request.use(config => {
  const newConfig = { …config };
  ...
});
```

For 0.19.1:

```
axios.defaults.headers.common[‘AUTHORIZATION’] = `Bearer ${token}`;
axiosInstance.interceptors.request.use(config => {
  const newConfig = { …config };
  newConfig.headers[‘AUTHORIZATION’] = axios.defaults.headers.common[‘AUTHORIZATION’];
  ...
});
```

In 0.19.1 version after refresh token interceptors doesn’t use updated axios.default.headers and continue using previous token

**Comment by ayophanz** [comment]
Hi, I have the same problem, to solve please terminate your npm watch and re-run again.
https://github.com/axios/axios/issues/2693

**Comment by dollock** [comment]
I terminate npm run watch and restart again, but it didn't solve the problem

**Comment by chinesedfan** [comment]
@dollock Can you follow the issue template with actual/expected? A reproducible code script is better.

**Comment by AuthorProxy** [comment]
Same problem, after upgrading to ^19, interceptor use first setted default header, and doesn't overwrite it again.

**Comment by chinesedfan** [comment]
@AuthorProxy Your problem seems to the same with #2623. Friendly remind, show me the code. :P

**Comment by chinesedfan** [comment]
Closed due to stale. And hope [this guide](https://github.com/chinesedfan/You-Dont-Know-Axios) can help you guys.
