### ISSUE TITLE
interceptor.response never triggered

### ISSUE THREAD

**Issue by T00rk** [axios/axios#2697]
I've set an interceptor on response. It is supposed to be triggered whenever there is a response or an error. The aim is to be able to catch the API error message and show it to the user.
It seems to not work.

**To Reproduce**

Create an `HTTPService.js` file as below. Have an Express server that returns a status code which is different from 200 and call it using `HTTPService.get` or `HTTPService.post`.

**HTTPService.js**

    const instance = axios.create
    ({
        baseURL: 'http://localhost:8080/,
        timeout: 1000,
        headers: {
            'Content-Type': 'application/json'
        }
    });

    instance.interceptors.response.use(function(response)
    {
        console.log(response);
        return response;
    }, function (error)
    {
        console.log(error);
        return Promise.reject(error);
    });

    export default
    {
        get: instance.get,
        post: instance.post,
        put: instance.put,
        delete: instance.delete,
    }

**Expected behavior**

This service is used in `AuthService.js`. There is a `login` function that is using post.
It works great when I provide the correct login and password. But, when it's not the case, the server responds with a 404 error code which is supposed to trigger the error interceptor and log the error in the console.

**Server Request / Response Headers**
![image](https://user-images.githubusercontent.com/593708/73204759-d45f9380-413f-11ea-8918-4d2a6f781559.png)

**Server Response Body**
![image](https://user-images.githubusercontent.com/593708/73204663-a11d0480-413f-11ea-8d95-310d6837e8c8.png)

**Console Output**
![image](https://user-images.githubusercontent.com/593708/73204959-46d07380-4140-11ea-9d9e-84fa911ac97b.png)

**Environment:**
 - Axios Version [0.19.2]
 - OS: [Ubuntu 18.04]
 - Browser [Brave]
 - Browser Version [1.2.43]

**Comment by chinesedfan** [comment]
Please try to customize `config.validateStatus` to consider 404 as valid status code.
