### ISSUE TITLE
way to get request/response header's cookie? 

### ISSUE THREAD

**Issue by dotorimook** [axios/axios#2698]
**Describe the issue**
I want to get cookie information from request/response.
I had tried to use request/response interceptor, but the value of `headers['Cookie']`  or `headers['set-cookie']` is `undefined`.
`document.cookie` is also `undefined`.
I can find a cookie in request header with browser like this though:
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ko,en-US;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Cookie: SESSION=c6716a93-ab28-4986-88a5-4263fe8045f0
Host: localhost:8080
Origin: http://localhost:3000
Pragma: no-cache
Referer: http://localhost:3000/
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
```
Is there any way to get cookie with request/response header?

**Example Code**
Code snippet to illustrate your question

```js
instance.interceptors.request.use((config) => {
    console.log(document.cookie, config.headers.Cookie); //undefined
}
instance.interceptors.response.use((res)=>{
    console.log(res.headers['set-cookie']);  //undefined
    return res;
});
```

**Expected behavior, if applicable**
```
{
"SESSION":"c6716a93-ab28-4986-88a5-4263fe8045f0"
}
```

**Environment:**
 - Axios Version ^0.18.0
 - OS:  Windows 7
 - Browser Chrome 
 - Browser Version 79.0
 - Additional Library Versions React ^16.8.6

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
> document.cookie is also undefined

It seems that your cookie is HttpOnly, which means can't be visited by Javascript. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies). You can confirm that by Chrome's Application panel: Storage -> Cookies.
