### ISSUE TITLE
axios and array parameters

### ISSUE THREAD

**Issue by Amosss** [axios/axios#2700]
I'm using axios with quasar/vue.
`axios.post(this.serverUrl, null, {params: {blah: "test"}}`
params are 3rd parameter. I saw it should be 2nd but when it was, I got the following: 
> Access to XMLHttpRequest at 'https://example.com' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

When it's the 3rd parameter all was good.

All was good until I needed to pass an array of jsons, for example:
`var info = [{name: "test", age: 40},{name: "tester", age: 50}]`
No matter what I tried, including using qs: `axios.post(this.serverUrl, null, {params: {dataToSend: info},paramsSerializer: params => { return qs.stringify(params)}` and another parsing method
```
parseParams(params) {
      const keys = Object.keys(params);
      let options = '';
      keys.forEach((key) => {
        const isParamTypeObject = typeof params[key] === 'object';
        const isParamTypeArray = isParamTypeObject && (params[key].length >= 0);
        if (!isParamTypeObject) {
          options += `${key}=${params[key]}&`;
        }
        if (isParamTypeObject && isParamTypeArray) {      
          params[key].forEach((element) => {
            options += `${key}=${element}&`;
          });
        }      
      });
      return options ? options.slice(0, -1) : options;
    },
```
I started receiving the above error of CORS.

My guess is that the parsing is wrong but I couldn't figure out how to overcome this, even after reading the so many examples on the web. My server expects to receive an array of jsons like the above `[{name: "test", age: 40},{name: "tester", age: 50}]` so I need the client to send it as such. I'm using axios 0.19.1

What am I missing? Thanks!

**Comment by chinesedfan** [comment]
CORS problem. If you are not familiar with it, you can read something from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

It is not an issue of axios, so I will close it.

**Comment by Amosss** [comment]
If it's CORS related, how come other requests are working fine?
I think it's something to do with the parsing of the array.
Either a something to fix or something I should know how to do better, thus my question.
I opened this ticket as usage question, I hope this will be re-opened.

**Comment by chinesedfan** [comment]
Sorry, it's impossible for maintainers to ask every usage question, unless users proved that really something wrong in axios. We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. Thanks.

**Comment by Amosss** [comment]
Thank you for replying. 

As I wrote in my original post (+relevant code) I did use qs (which is axios) and even used a parsing method and still something is broken. I didn't develop axios so I don't know whether it's because axios is broken or because I did something wrong. That's why I put my question here, so people who actually know axios will tell me - hey man, you broke it because X Y Z, just put a tape on this and this and all is good...

**Comment by chinesedfan** [comment]
Really understand. I can point some directions for you, but can't guarantee covering everything and giving you the exact answer. Hope they can help you.

- CORS. Make sure you know what it is and how to solve it.
- params vs data. What are differences between these 2 config options?

**Comment by Amosss** [comment]
Thanks!! 
Just one more hint for me to explore: 
params is the second parameter of axios (after url)
data is the 3rd one?
Please explain me this and I'll go my way...
Again, thanks a lot! I appreciate it!

**Comment by chinesedfan** [comment]
```
axios.post(url[, data[, config]])
```

Seems that you make them the wrong order. Params are in the config, which is the 3rd. And data is the 2nd.

But I think your biggest problem is CORS. Forgive me I can't explain it clearly for you and hope you can learn it by yourself. And really do not push you away at all.

**Comment by Amosss** [comment]
Thanks, I'll continue from here and I appreciate your help. 

I was just wondering how come the params work from the 3rd parameter while from the 2nd it didn't. I'd expect it to fail from the 3rd parameter as well.

Anyway, I will look into CORS now...

**Comment by Amosss** [comment]
There's a twist in the story. I fixed the CORS, changed the params to the 2nd parameter and this is what happened:
https://github.com/axios/axios/issues/1195

Pasting it here as well:
axios.post("api", { API: 1, version: "0.1b"...})....
Results with empty API and version when reaching my Java rest server.
When sending it as the 3rd paramter, ie
axios.post("api", null, { params: {API: 1, version: "0.1b"...}})....
It works as expected

Is this a prove that axios is broken or am I still doing something wrong?
Thanks

**Comment by chinesedfan** [comment]
> axios.post("api", { API: 1, version: "0.1b"...})
> axios.post("api", null, { params: {API: 1, version: "0.1b"...}})

From the axios side, both of your usages are valid. So it depends on which one your server expects. Looks like it is the second one. As I said from the beginning, nothing wrong is in axios.

**Comment by Amosss** [comment]
You told me that my problem is CORS and now it seems that CORS was never my problem.
So now I'm back to square one: How can I send my array information? When sending simple values {name: "test"} it works, when sending 
```
var info = [{name: "test", age: 40},{name: "tester", age: 50}]
axios.post(this.serverUrl, null, {params: {dataToSend: info},paramsSerializer: params => { return qs.stringify(params)}
```
I get CORS. If my problem was CORS, I'd get an error also with the first/simple send...

**Comment by Amosss** [comment]
OK, as I thought, the problem was not CORS. The following is working except for the array param but this time it is related to the parsing of the array

`axios.post(this.serverUrl, null, {data: {version: "0.1b", command: "test", data: this.user.info}, transformRequest: [(data, headers) => {return qs.stringify(data);}], headers: { 'Content-Type': 'application/x-www-form-urlencoded' }}
`

this.user.info = [{name: "blah", age: 30}, {name: "blah2", age: 50}]
The above arrives null to the server and the reason is, by looking in the network:

> version: 0.1b
> command: test
> data[0][name]: blah
> data[0][age]: 30
> data[1][name]: blah2
> data[1][age]: 50

No surprise that the array arrives as null, it is sent in an unexpected format.
I tried with and without headers: `{ 'Content-Type': 'application/x-www-form-urlencoded' }` but the same happened.

Any idea how to send an array like an array suppose to be?
