### ISSUE TITLE
[BREAKING @ 0.19.2] Header null value becomes [object Object]

### ISSUE THREAD

**Issue by rkdmen** [axios/axios#2701]
**Describe the bug**
sending header with null value becomes [object Object].

This wasn't an issue before 19.0.

**To Reproduce**
Should send as null.

**Expected behavior**

**Environment:**
 - Axios Version [0.19.2]
 - OS: [ OSX 10.15.2]
 - Browser [Chrome]
 - Browser Version [79.0.3945.130] Latest
 - Additional Library Versions [React 16.12.0]

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/16869691/73281456-03b4e580-41be-11ea-8798-db197c16f634.png)

Reopening issue #2223 because this is still an issue.

**Comment by chinesedfan** [comment]
Yes, it is still there. Closed in favor of #2567.
