### ISSUE TITLE
Support for `last-modified` header?

### ISSUE THREAD

**Issue by quantumlink** [axios/axios#2704]
I'm not seeing anything in the code-base that would indicate `last-modified` is implemented, but I'm not sure. If not then I suppose this is more of a feature request.

Things like https://tools.ietf.org/html/rfc7232#section-3.3 `if-modified-since` from the client and handling `last-modified` from the server to short-cut the view-processing.

Or is this just expected to be done manually?

Thanks for the wonderful library.

**Comment by chinesedfan** [comment]
That is implemented by the browser. If you are expected in the server side, it requires users to handle the cache manually.
