### ISSUE TITLE
Headers response is empty (how read value from custom header response)

### ISSUE THREAD

**Issue by nicotp80** [axios/axios#2705]
I to all. i'm new with axios worl, i'll try to use to consume an asp net core API. So for example i need to call a route that with appropriate parameter send in response header property "X-Token" the token for next api call.

axios({               
                headers: {
                    'Content-Type': 'application/json'
                },
                method: 'post',
                url: 'myUrl',
                xsrfHeaderName : 'X-Token',
                data: {  "property1": "value", "property2": "value"  }
            }).then(res => {
                alert('Successfully submitted feedback form ');
                console.log(res.headers['X-Token']);
                console.log(res.xsrfHeaderName);
                this.$refs.SubmitButton.setAttribute("disabled", "disabled");
            }).catch(err => {
                alert(`There was an error submitting your form. See details: ${err}`);
            });

But in console i see that nothing return : 

outputundefined
undefined

I test call with postman and i can see that all is ok and token is on X-Token property. So i don't undestand how i can access to this property with axios.

**Comment by chinesedfan** [comment]
Which side did you run your codes? The browser or in Node.js? If you are using CORS, make sure the server responded with Access-Control-Expose-Headers. See more in #1946.

```
console.log(res.headers['X-Token']);
console.log(res.xsrfHeaderName); // try res.config.xsrfHeaderName
```
