### ISSUE TITLE
axios.isCancel() not recognizing cancelation error

### ISSUE THREAD

**Issue by cvalmonte** [axios/axios#2707]
**Describe the issue**
I have a component that initiates multiple requests to an API. If the user makes any subsequent requests to the same API before the server replies, previous calls are canceled. This works as expected. However, once a request gets canceled, an error is thrown, and axios doesn't correctly detect it is a cancel error (via `axios.isCancel(error)`)

EXAMPLE:
1. Make API request, `requestA`, to '/api/does-stuff'
2. Before there is a response from `requestA`, make another API request, `requestB`, to '/api/does-stuff'
3. `requestA` gets canceled and throws an error
4. When handling the error, check if it is an axios cancelation error (via `axios.isCancel(error)`)
5. `axios.isCancel(error)` always returns false 😭 

**Example Code**
Code snippet to illustrate your question

```js
// Custom helper in my app to build a cancelable request
function buildCancelableRequest() {
  let call

  return requestOptions => {
    if (call) call.cancel()
    call = axios.CancelToken.source()

    return axios({ cancelToken: call.token, ...requestOptions })
      .then(() => {
        console.log('success')
      })
      .catch(error => {
        console.log(axios.isCancel(error)) // This is always false, even when the request cancels
      })
  }
}

...

// Usage
const myService = buildCancelableRequest()
myService({
  method: 'get',
  url: '/api/my-custom-api'
})
```

**Expected behavior, if applicable**
axios.isCancel() should return true when the request cancels

**Environment:**
 - Axios Version: 0.19.2
 - Browser: Chrome
 - Browser Version: 79
 - Additional Library Versions: React 16.12.0

**Comment by chinesedfan** [comment]
Hi, what `error` did you get? And how did you know the request was cancelled before sending? Can you see the request in the browser's network panel?

**Comment by cvalmonte** [comment]
Ahh the error was coming from my axios interceptors.. works now! closing the issue

**Comment by Phil-Barber** [comment]
Hey sort of just jumping on this because I'm likely missing something silly:

have a util that keeps track of requests and cancels a request if a request with that slug already exists:
```
  // Called before each axios.post and the config passed as an argument
  static _getConfig(data) {
    const config = {};

    if (data.slug) {
      config.cancelToken = Restaurant._setCancelToken(data.slug);
    }
    return config;
  }

  static _setCancelToken(slug) {
    if (requests[slug] && requests[slug].cancel) {
      requests[slug].cancel('DUPLICATE_SLUG');
    }

    requests[slug] = {};
    const source = CancelToken.source();
    requests[slug].cancel = source.cancel;

    return source.token;
  }
```

Then in my code I have:
```
      .catch(e => {
        if (!axios.isCancel(e)) {
          throw e;
        }
     })
```

And I still appear to be getting the error thrown:
```
UnhandledRejection
Non-Error promise rejection captured with keys: message
```
```
{
message: DUPLICATE_SLUG
}
```

As far as I can tell I'm following exactly the docs example - https://github.com/axios/axios#cancellation
Any ideas where I'm going wrong?

**Comment by ichi404gh** [comment]
@Phil-Barber seems like you throw from catch handler, but there is no next catch in your promise chain. In general, you cannot throw from promise like from synchronous code, you need to handle error with `onRejected` aka `catch` callback.

**Comment by Phil-Barber** [comment]
> @Phil-Barber seems like you throw from catch handler, but there is no next catch in your promise chain. In general, you cannot throw from promise like from synchronous code, you need to handle error with `onRejected` aka `catch` callback.

I only throw if the error isn't a cancelled request - but it's throwing even when it is cancelled.

Its probably just bad code handling the cancelation

**Comment by marqroldan** [comment]
Hi @Phil-Barber, for some weird reason axios is rejecting the promise twice 

I think it's something related to this comment: https://github.com/axios/axios/pull/1399#commitcomment-33028936

I did try adding another .catch in the promise sequence but I still can't catch it for some reason, have you figured out your problem?

Thanks!

**Comment by Phil-Barber** [comment]
> Hi @Phil-Barber, for some weird reason axios is rejecting the promise twice
> 
> I think it's something related to this comment: [#1399 (comment)](https://github.com/axios/axios/pull/1399#commitcomment-33028936)
> 
> I did try adding another .catch in the promise sequence but I still can't catch it for some reason, have you figured out your problem?
> 
> Thanks!

That's really interesting, thanks for the clue!
No I haven't had an opportunity to dig deeper into this for some time. If I solve it I will be sure to update 👍
