### ISSUE TITLE
Add interceptors to config

### ISSUE THREAD

**Issue by mmkal** [axios/axios#2708]
**Is your feature request related to a problem? Please describe.**

Include `interceptors` as part of the config for an `AxiosInstance`.

**Describe the solution you'd like**
Make it so this works.

```js
const client1 = axios.create({
  headers: { 'x-foo': 'bar' }
})

client1.interceptors.request.use(config => {
  console.log(config)
  return config
})

const client2 = axios.create({ ...client1.defaults })

client1.get('http://example.com') // logs config
client2.get('http://example.com') // doesn't log
```

`client2` should have the interceptors from `client1`.

**Describe alternatives you've considered**

Right now, it's possible to copy interceptors manually, but it's non-intuitive and the types try to stop you:

```js
const client1 = axios.create({
  headers: { 'x-foo': 'bar' }
})

client1.interceptors.request.use(config => {
  console.log(config)
  return config
})

const client2 = axios.create({ ...client1.defaults })

client2.request.interceptors.handlers = client1.request.interceptors.handlers
```

**Additional context**

Some sort of `instance.create(...)` or `.clone(...)` or `.child(...)` or `.extend(...)` method would be ideal - the sub-instance should receive config from the parent, including interceptors.

If implemented this way all of these could likely be closed:

* https://github.com/axios/axios/pull/2040
* https://github.com/axios/axios/pull/2285
* https://github.com/axios/axios/pull/2389

(potentially either #2040 or #2389 could be used to implement this)

**Comment by mmkal** [comment]
@jasonsaayman could you share why this was closed? Was it done?

**Comment by jasonsaayman** [comment]
>You can add interceptors to a custom instance of axios.

const instance = axios.create();
instance.interceptors.request.use(function () {/*...*/});

Yip it should be working as you waned now.
