### ISSUE TITLE
onUploadProgress (almost) immediately reports 100%

### ISSUE THREAD

**Issue by thany** [axios/axios#2709]
**Describe the bug**
`onUploadProgress` event reports (almost) complete immediately, even though the file is clearly still uploading. I've already tried throttling the network in devtools. It's uploading to my local machine, but the browser shouldn't know that. It's a domain name that's linked to 127.0.0.1. 

Im uploading a 9MB file that takes well over 20 seconds (throttled). Immediately after uploading begins, an `onUploadProgress` reports 7MB of progress. And immediately after that, it reports the full 9MB uploaded. On the network tab, I can see the request is still uploading. It's not waiting for the server to respond or anything like that, it really is still uploading.

**To Reproduce**
Can't really give a isolated example, as you'll need a server that accepts the upload. But it goes a little something like this:

```javascript
const formData = new FormData();
const blob = new File([file.data], file.name, { type: file.type, lastModified: file.lastModified || Date.now() }); // `file.data` is an ArrayBuffer
formData.append(file.name, blob);

const config = {
  onUploadProgress: event => {
      console.log(event.loaded, event.total);
  }
};

return await axios.post('/api/postfile', formData, config);
```
We're not doing any abstraction (yet). The code literally looks like that. I've just stripped away some irrelevant parts, like where the file data is coming from. Of course, this code is wrapped in a function, hence the return statement.

**Expected behavior**
As long as the upload is truly in progress, emit `onUploadProgress` events leading from 0 up to the body size, and only emit 100% progress when the upload is truly complete.

**Environment:**
 - Axios Version 0.19.0
 - OS: Windows 10
 - Browser Firefox
 - Browser Version 72
 - Additional Library Versions: React 16.8.6, Styled-components 4.4.0, Redux 4.0.4, Redux-form 8.2.6 (and a couple more, but these are the most relevant ones)

**Additional context/Screenshots**
I've checked the changelogs, and I didn't see any fixes concerning progress events, so I'm assuming it hasn't been fixed yet.
Issue #639 handles this problem in more detail, but has been closed (but not fixed, as far as I can tell). I've tried every suggestion from that issue that applies to me.

It might help to know that it does work in Chrome. I couldn't test Edge because it doesn't have an option to throttle network.

**Comment by alec-joy** [comment]
I'm also experiencing this issue but I am not sure if it's an axios problem, it happens in chrome and firefox but it started happening after a recent windows update where I didnt update my js packages. I've tried downgrading all the way to version 17.0 and the bug is still happening but that version is older than the product I'm working on at the moment and progress events were working just fine until this week when our Org ran updates on my computer.

**Comment by alec-joy** [comment]
@thany are you by any chance uploading files to box.com?

**Comment by alec-joy** [comment]
Something weird to note, if I use the chrome developer tools to manually throttle my network connection the progress events happen at the expected rate. It's only on an unthrottled network connection that it returns all the progress events at once.

**Comment by thany** [comment]
@alec-joy My files are going to a service running locally.

**Comment by yoyo837** [comment]
same here.

**Comment by jaynsuthar** [comment]
I'm having same issue. onUploadProgress should emit continuous events until it completes the request but instead I get 100 percents right away. I've my server running on localhost and I also tried to hit some test https external endpoint, still seeing the issue. It will be great if anyone can post a work around on this issue?

**Comment by dillingham** [comment]
https://github.com/axios/axios/issues/1591

**Comment by codebykenny** [comment]
We're experiencing the same exact problem, `onUploadProgress` emits events all the way up to 100% in a couple of seconds even in large 500mb+ uploads. It's emitting the event before the chunk has actually been uploaded.

Is there a version of axios in which this isn't broken?

Also "throttling" the network tab does seemingly fix the issue as @alec-joy pointed out.

**Comment by jasonsaayman** [comment]
@codebykenny it seems the issue is with Chrome itself, check #1591
