### ISSUE TITLE
can I have requset config in error if I cancel an axios request?

### ISSUE THREAD

**Issue by mosijava** [axios/axios#2712]
**Is your feature request related to a problem? Please describe.**
the reason that I want this behavior is I have a react app which when a request intercepted by axios I'll show loadingBar in top of the page. and if the request is resolved or has an error the loading bar should disappear.

            reqMade = (conf) => {
                if (conf.headers.clientConfig.sendAuth) {
                    conf.headers['Authorization'] = getAccessToken();
                }
                if (mounted && conf.headers.clientConfig.loading) {
                    setLoadingBar(loadBar + 1);
                }
            },

            reqFail = (err) => {
                if (mounted && err.config.headers.clientConfig.loading) {
                    setLoadingBar(loadBar - 1);
                }
            },

            resMade = (res) => {
                if (mounted && res.config.headers.clientConfig.loading) {
                    setLoadingBar(loadBar - 1);
                }
            },

            resFail = (err) => {
                if (mounted && err.config.headers.clientConfig.loading) {
                    setLoadingBar(loadBar - 1);
                }
            },
        ssoReqInterceptor = ssoInstance.interceptors.request.use(config => {
            reqMade(config);
            return config;
        }, err => {
            reqFail(err);
            return Promise.reject(err);
        });

        ssoResInterceptor = ssoInstance.interceptors.response.use(resp => {
            resMade(resp);
            return resp;
        }, err => {
            resFail(err);
            return Promise.reject(err);
        });

the problem is if I cancel a request I can't check for `err.config` in `resFail` function  because `err` object only contain a message. therefor I can't check if the request has loading property to handle showing loading bar.

**Describe the solution you'd like**
It will be great if I can somehow access to request config in the error object that comes up with canceling an axios request.

**Comment by trisys3** [comment]
Has this been looked at? It's been a couple months now. I'm getting the same issue and I have just about the exact same use case.

Until this gets added, you can use an object in the original `cancel` call, instead of a string or nothing, and then add some property to it. You could also do string parsing, but yuck. The problem with both of these approaches is if the `cancel` is in a different place from the interceptor and you can only change one of them.

For example, you could have an interceptor like (I only need the URL in my use case):

```
import {interceptors, cancel} from 'axios';

let loads = 0;

interceptors.request.use(request => {
    loads++;

    if(urlIsOurs(request.url)) {
        console.log('Request initiated from our server.');
        forceProgressBarShowing();
    } else {
        console.log('Request initiated from someone else's server.');
    }

    return request;
});

interceptors.response.use(() => {}, error => {
    const {request, response} = error || {};
    const config = response?.config || request?.config || error?.config;

    if(!urlIsUsable()) {
        console.log('Response errored from someone else's server.');
        return error;
    }

    console.log('Response errored from someone else's server.');

    loads--;
    // sanity check
    if(loads < 0) {
        loads = 0;
    }

    if(!loads) {
        forceHideProgressBar();
    }

    return response;

    function urlIsUsable() {
        return urlIsOurs(config.url) || config.message.ourUrl;
    }
});
```

and then a call & canceler like:

```
import axios, {cancel as cancelRequest, CancelToken} from 'axios';

const ourCanceler = CancelToken.source();
const notOurCanceler = CancelToken.source();

axios(ourUrl);
axios(notOurUrl);

axios(ourUrl, {cancelToken: ourCanceler.token});
axios(notOurUrl, {cancelToken: notOurCanceler.token});

// later, but not too much later or the fetches will complete before they're canceled

ourCanceler.cancel({
    message: 'Hey, you canceled me!',
    ourUrl: true,
});

notOurCanceler.cancel('Ooooh, you canceled someone else, I'm gonna tell Mom!');
```

The progress bar will start going when the first request starts, and go away when it gets canceled. You'll get:

'Request initiated to our server.'
'Request initiated to someone else's server.'
'Response errored from our server.'
'Response errored from someone else's server.'
'Response errored from our server.'
'Response errored from someone else's server.'

**Comment by liuxinqiong** [comment]
I have the same problem when I need to judge whether should i hide the loading state. Hope to be resolved.

**Comment by Xeno8888** [comment]
Same here - I just set the request config on the cancel object for the reject promise in axios.js. Works for me, but a clean way would be nice.
Probably something like:
`reject(createCancel(cancel, config))`

**Comment by SMichalet** [comment]
I have the same issue when trying to retry a cancelled request (with the axios-retry package).
The axios-retry package use the config object to be able to retry the request

Axios never timeout on the response (see https://github.com/axios/axios/issues/459), so you will need to cancel it manually.

To be able to cancel and retry the request I'm using the same logic as @Xeno8888.
I'm setting the request config object in the cancel action and use an other error interceptor to reject the request with the config if it's coming from the cancel token.

Is there a cleaner way to manage this ?

**Comment by jasonsaayman** [comment]
Closing in favour of #459
