### ISSUE TITLE
module.exports incompatibility with webpack

### ISSUE THREAD

**Issue by thedamon** [axios/axios#2713]
When adding axios 0.19.2 to a component in our project (vue storybook.js built via webpack), the build works but on all pages are seeing the error:

`Cannot assign to read only property 'exports' of object '#<Object>'`
It is coming from the axios export code:

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (utils.js:322)
    at Module../packages/components/icon/vue/node_modules/axios/lib/utils.js (utils.js:322)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module.<anonymous> (axios.js:3)
    at Module../packages/components/icon/vue/node_modules/axios/lib/axios.js (axios.js:53)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Object../packages/components/icon/vue/node_modules/axios/index.js (index.js:1)
    at __webpack_require__ (bootstrap:790)
```

Inside component:

```js
import axios from 'axios'
```

Downgrading to axios 0.19.0 fixes the issue

Since the previous minor version works, I would expect a patch version to function the same way

**Comment by chinesedfan** [comment]
@thedamon Can you try 0.19.1 to help us limit the scope? And a reproducible webpack config is more appreciated.

**Comment by thedamon** [comment]
I tried to reproduce and cannot even with 0.19.2... (i did have to rebuild my entire yarn.lock since then) so I'm not sure what went on, but it seems to be just some weird compatibility.

**Comment by thedamon** [comment]
This showed up again in our compiled storybook code. It may be related to this: https://github.com/storybookjs/storybook/issues/5298 (though there is not really a distinct solution on this ticket). It said something about mixing module.exports and import syntax potentially causing issues. Will update if we find out more.

**Comment by thedamon** [comment]
We have since tried 0.19.1 and are also getting the error there.

**Comment by dunky11** [comment]
I fixed it by changing:

`module.exports = { default: someClass };
`
to

`module.exports = someClass;`

It looks like default is not a valid key to the object you assign to module.exports.

**Comment by chinesedfan** [comment]
@thedamon Can you provide a demo project?
