### ISSUE TITLE
Axios ignores set-cookies from version 0.19.1

### ISSUE THREAD

**Issue by akirilyuk** [axios/axios#2714]
**Describe the bug**
Since axios 0.19.1 all set-cookies headers are ignored.

**To Reproduce**
Perform a request that sets cookies. 

If using curl or Axios v0.19.0, you should get all headers, including set-cookies headers.

**Expected behavior**
You should get ALL headers of the response.

**Actual behaviour**
All set-cookie headers are lost.

**Environment:**
 - Axios Version from 0.19.1 
 - OS: linux alpine
-  Node: 12.13.0

**Comment by chinesedfan** [comment]
@akirilyuk Can you provide a code example to show how you read cookies?

**Comment by akirilyuk** [comment]
@chinesedfan sure:

```js
const nock = require('nock');
const axios = require('axios').default;

describe('test set-cookie headers', () => {
  it('should get the cookies from request', async () => {
    const domain = 'https://test-cookies.com';
    const path = '/api/account/test-account';
    const exampleCookieString = `session_id=e16a938e-bc95-41a4-96f7-e7bc853c2ad4; path=${path}; domain=${domain}; secure; httponly`;
    nock(domain)
      .post(path)
      .reply(
        200,
        {},
        {
          'set-cookie': [exampleCookieString],
          'access-control-expose-headers': 'set-cookie, expires'
        }
      );

    const { data, headers } = await axios.post(`${domain}${path}`);
    expect(data).toEqual({});
    expect(headers['set-cookie'][0]).toEqual(exampleCookieString);
  });
});
```

this is an example code, however it passes with both 0.19.0 and > 0.19.1.

Maybe I can share the request response which is returned by our endpoint for data and headers:

```js
// response returned for headers in 0.19.0
const headers = {
  "date": "Mon, 10 Feb 2020 12:25:28 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "9431",
  "connection": "close",
  "set-cookie": [
    "session_id=2db8e275-3962-4dfa-ad78-771e9a4b1a0f; path=/api/account/le61911979; domain=lp-agentvep-qa.dev.lprnd.net; secure; httponly"
  ],
  "etag": "W/\"24d7-TTzUTeRChZYG2U/mf8yq2qpjCKY\"",
  "server": "ws",
  "access-control-allow-methods": "GET, POST, PATCH",
  "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, Authorization, X-HTTP-Method-Override, LP-DOMAIN-REFERER, LP-URL, ETag, ac-revision, X-LP-Last-Modified, If-Match, Authentication-Method, Credit-Card-Ref, Automation-Secret, Email-Token",
  "access-control-expose-headers": "X-Requested-With, X-HTTP-Method-Override, LP-DOMAIN-REFERER, LP-URL, ETag, ac-revision, X-LP-Last-Modified, If-Match, Authentication-Method, Credit-Card-Ref, Automation-Secret, Email-Token, x-lp-host, Lp-Req-Time, date, x-application-context, strict-transport-security, x-content-type-options, x-download-options, x-xss-protection, x-cache-status, x-amz-id-2, x-amz-request-id, expires, last-modified, set-cookie, content-security-policy, x-frame-options",
  "access-control-allow-credentials": "true"
}

// response returned for headers on v > 0.19.1

const headers = {
  "date": "Mon, 10 Feb 2020 12:23:51 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "9432",
  "connection": "keep-alive",
  "etag": "W/\"24d8-mw6dSHql7VEV2yH5n+EwlnBlxic\"",
  "server": "ws",
  "access-control-allow-methods": "GET, POST, PATCH",
  "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, Authorization, X-HTTP-Method-Override, LP-DOMAIN-REFERER, LP-URL, ETag, ac-revision, X-LP-Last-Modified, If-Match, Authentication-Method, Credit-Card-Ref, Automation-Secret, Email-Token",
  "access-control-expose-headers": "X-Requested-With, X-HTTP-Method-Override, LP-DOMAIN-REFERER, LP-URL, ETag, ac-revision, X-LP-Last-Modified, If-Match, Authentication-Method, Credit-Card-Ref, Automation-Secret, Email-Token, x-lp-host, Lp-Req-Time, date, x-application-context, strict-transport-security, x-content-type-options, x-download-options, x-xss-protection, x-cache-status, x-amz-id-2, x-amz-request-id, expires, last-modified, set-cookie, content-security-policy, x-frame-options",
  "access-control-allow-credentials": "true"
}
```

The same request with postman yields even more set cookie headers which remove the headers:


Date
Mon, 10 Feb 2020 12:26:52 GMT
Content-Type
application/json; charset=utf-8
Transfer-Encoding
chunked
Connection
keep-alive
Set-Cookie
WSHumanClickSiteNumber=le61911979; path=/hc/s-le61911979/web; domain=lp-agentvep-qa.dev.lprnd.net; secure; httponly
Set-Cookie
idpLastSiteId=le61911979; path=/; domain=lp-agentvep-qa.dev.lprnd.net; secure; httponly
Set-Cookie
idpLastDomain=le2-qa.dev.lprnd.net; path=/; domain=lp-agentvep-qa.dev.lprnd.net; secure; httponly
Set-Cookie
WSHumanClickWebSession=bf7eab082116f4a03165d91b8c32a2aa; path=/hc/s-le61911979/web; domain=lp-agentvep-qa.dev.lprnd.net; secure; httponly
Set-Cookie
WSHumanClickServer=qtor-app50; path=/hc/web; domain=lp-agentvep-qa.dev.lprnd.net; secure; httponly
Set-Cookie
session_id=55b1d75e-0f0f-45b3-9df0-2636499b6ed2; path=/api/account/le61911979; domain=lp-agentvep-qa.dev.lprnd.net; secure; httponly
ETag
W/"27e7-SEYdf1H+wCfBACjrqbXWY96Ws3U"
Server
ws
Access-Control-Allow-Methods
GET, POST, PATCH
Access-Control-Allow-Headers
Origin, X-Requested-With, Content-Type, Accept, Authorization, X-HTTP-Method-Override, LP-DOMAIN-REFERER, LP-URL, ETag, ac-revision, X-LP-Last-Modified, If-Match, Authentication-Method, Credit-Card-Ref, Automation-Secret, Email-Token
Access-Control-Expose-Headers
X-Requested-With, X-HTTP-Method-Override, LP-DOMAIN-REFERER, LP-URL, ETag, ac-revision, X-LP-Last-Modified, If-Match, Authentication-Method, Credit-Card-Ref, Automation-Secret, Email-Token, x-lp-host, Lp-Req-Time, date, x-application-context, strict-transport-security, x-content-type-options, x-download-options, x-xss-protection, x-cache-status, x-amz-id-2, x-amz-request-id, expires, last-modified, set-cookie, content-security-policy, x-frame-options
Access-Control-Allow-Credentials
true

**Comment by chinesedfan** [comment]
> however it passes with both 0.19.0 and > 0.19.1.

I am a little confused that why > 0.19.1 passed. And please confirm the table.

| version | set-cookie | test result                        |
| --- |:--------:| -------------------------------:|
|  0.19.0  |  all     | passed                      |
|  0.19.1  |  only one     | failed                      |
|  >0.19.1  |   none    | passed                      |

I also noticed that you used `nock`, and am not sure whether it is related to #2654. Can you confirm which adapter(xhr or http) you really used?

**Comment by akirilyuk** [comment]
@chinesedfan 


version | set-cookie | test result
-- | -- | --
0.19.0 | only one | passed
0.19.1 | none | passed
>0.19.1 | none | passed


So i have no idea why the tests are passing, but when using axios for a real request they are failing.

The headers which contained all set-cookie headers are actually from a response executed via postman to the same endpoint. This means, even in axios 0.19.0 many set-cookie headers are removed by default, however we never noticed because we had the one we needed.

Can you confirm which adapter(xhr or http) you really used? How to find this out?

**Comment by chinesedfan** [comment]
> Can you confirm which adapter(xhr or http) you really used?

```
console.log(axios.defaults.adapter);
```

Every your `set-cookie` is `httponly`. That makes sense. Before 0.19.1, the default adapter is http, and #2201 changed it as xhr.

As for why axios@0.19.0 has less headers than postman, please compare their **request** headers in your server codes.

**Comment by akirilyuk** [comment]
> As for why axios@0.19.0 has less headers than postman, please compare their request headers in your server codes.

Only header is Content-Type: application/json.

Additionally, you can see that the connection header is returned as closed in 0.19.0 but as keep-alive in 0.19.1. 

I checked the default adapter and indeeed it is now xhr instead of http. So the #2201 actually broke it for node? Since from the code it should still use http adapter on node. Apparently this was not reviewed/tested but just directly merged to the master branch ....

From 0.19.1:
[Function: xhrAdapter]
On 0.19.0:
[Function: httpAdapter]

**Comment by chinesedfan** [comment]
So that's the problem. Closed in favor of #2654.

And hope we can find an ideal solution to fit with jest/nock. As a workaround, config your test environment to node or set config.adapter to http explicitly.

**Comment by akirilyuk** [comment]
@chinesedfan I think you do not understand. Axios is using xhr when running on node in a production environment... Thats why I opened this issue. The code above is just an example....

**Comment by akirilyuk** [comment]
@chinesedfan can you please tell me how to explicitly set the adapter to http in order to fix the current bug introduced with axios 0.19.1? I cannot find anything in the documentation...

**Comment by chinesedfan** [comment]
> Axios is using xhr when running on node in a production environment.

Then I am afraid that you need do some debugging to find out why it happens. You can check the two if-conditions in your environment. Or give a reproducible code example to me.

```
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

About how to explicitly set the adapter, try as following,

```
axios({
  adapter: require('axios/lib/adapters/http')
})
```

**Comment by akirilyuk** [comment]
@chinesedfan So,

here is a screenshot, you can see i am on NODE, still it returns me the xhr adapter. 

![Screenshot 2020-02-11 at 10 00 49](https://user-images.githubusercontent.com/45361199/74222992-ff0c2900-4cb5-11ea-832b-4e86fce9c8c3.png)

**Comment by chinesedfan** [comment]
The reason is as you described in #2731, because `global.XMLHttpRequest` is defined. If you got an ideal solution that handles every cases, please reply in there.
