### ISSUE TITLE
Axios doesn't work with HTTPS when used within app.get() in server.js

### ISSUE THREAD

**Issue by monal-sharma** [axios/axios#2717]
Issue:
I'm using my node server.js as a proxy to deal with CORS issues. I also want to it to perform GET request to another API. This API works on SSL certificates. This functionality does not work with axios. 

**To Reproduce**
```
const express = require('express');
const app = express();
const fs = require('fs');
const https = require('https');
const port = process.env.PORT || 3001;

app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", process.env.ORIGIN || "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

app.get("/", (req, res) => {
  const axios = require('axios');
  const url = 'https://api-url/version';
  const httpsAgent = new https.Agent({
    cacert: fs.readFileSync('./ca.pem', 'utf8'),
    key: fs.readFileSync('./key.pem', 'utf8'),
    cert: fs.readFileSync('./cert.pem', 'utf8'),
    keepAlive: false
  });
  axios.get(url, {httpsAgent})
  .then(response => {
  console.log('Response:', response);
  }).catch(error => console.log('Error:', `${error}`));
  res.send(response);
});
app.listen(port, () => console.log(`https://localhost:${port}`));

```

**Expected behavior**
I am looking for my react app to do an axios.get('http://localhost:3001'), which would add the CORS headers to the request and then run an axios.get('API') to the external API along with the certificates. The response from the external API is passed back to the react app's axios.get('https://localhost:3001') request.

**Environment:**
"axios": "^0.19.0"
"react": "^16.11.0"

**Comment by chinesedfan** [comment]
Can you elaborate "not work"? Were some errors thrown or something wrong else?

**Comment by monal-sharma** [comment]
@chinesedfan : Thanks for the response. The flow is like this: React App does an axios.get('localhost:3001'), this then hits my server.js app.get(), which then calls axios.get('external-api') providing it certs to authenticate. The response from the external-api needs to be relayed back to the React App. Here's the error message:
GET https://localhost:3001/ net::ERR_SSL_PROTOCOL_ERROR
dispatchXhrRequest @ xhr.js:166
xhrAdapter @ xhr.js:16
dispatchRequest @ dispatchRequest.js:49
Promise.then (async)
request @ Axios.js:56
Axios.<computed> @ Axios.js:71
wrap @ bind.js:11
Version._this.getDBVersion @ Version.js:28
Version._this.onSubmitStats @ Version.js:21
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:439
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:454
executeDispatch @ react-dom.development.js:585
executeDispatchesInOrder @ react-dom.development.js:610
executeDispatchesAndRelease @ react-dom.development.js:713
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:722
forEachAccumulated @ react-dom.development.js:694
runEventsInBatch @ react-dom.development.js:739
runExtractedPluginEventsInBatch @ react-dom.development.js:881
handleTopLevel @ react-dom.development.js:5832
batchedEventUpdates$1 @ react-dom.development.js:24387
batchedEventUpdates @ react-dom.development.js:1414
dispatchEventForPluginEventSystem @ react-dom.development.js:5928
attemptToDispatchEvent @ react-dom.development.js:6045
dispatchEvent @ react-dom.development.js:5948
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
discreteUpdates$1 @ react-dom.development.js:24404
discreteUpdates @ react-dom.development.js:1439
dispatchDiscreteEvent @ react-dom.development.js:5915
createError.js:17 Uncaught (in promise) Error: Network Error
    at createError (createError.js:17)
    at XMLHttpRequest.handleError (xhr.js:80)

**Comment by chinesedfan** [comment]
Then you can Google search for ERR_SSL_PROTOCOL_ERROR to make sure your proxy really works. I am not a proxy expert, so apologize for can't help you locate the root reason. But if you or someone else find out something requires axios to support, glad to accept a PR to fix that.

**Comment by chinesedfan** [comment]
Closed due to stale and nothing can be done in axios. About ERR_SSL_PROTOCOL_ERROR, see https://aboutssl.org/fix-google-chrome-error-err_ssl_protocol_error/.
