### ISSUE TITLE
Is there a way to directly set response IP

### ISSUE THREAD

**Issue by christian-hess-94** [axios/axios#2718]
**Describe the issue**
I'm using axios to execute several request to a glassfish server running a java EE web service. The problem is that when the request is made from a mobile phone and it's made using a 4g connection that has ipv6 configured, the request takes a long time to return (around 3 minutes for about 1kb of data being transmitted). If it is done in an ipv4 environment, the response arrives almost instantly.

I want to know if there is a way to directly set the ipv4 as being the response target. So the request is made using the ipv4 of the device and not the ipv6.
**Example Code**
Code snippet to illustrate your question

```js
axios.get('myipv4address.com/some_route')
.then(res => console.log(JSON.stringify(res.data))
.catch(err => console.log(JSON.stringify(err))

//This happens with all routes
```

**Expected behavior, if applicable**
I wish the response arrives instantly even when connected to an ipv6 network

**Environment:**
 - Axios Version ^0.19.0
 - OS: This was only tested on Android devices
 - Browser: it happens on Chrome and also when using axios with an React Native app
 - Browser Version 80.0.3987.87 
 - Additional Library Versions Standard React and React Native libraries

**Additional context/Screenshots**
- If I disable the IPV6 setting on the phone making the request, the response arrives instantly.
- The request does arrive at the server, but the response takes a long time to arrive. This confirm the actual problem is with the Java EE web service but the technology does not allow us to update it and there is no official support to IPV6
- This also happens on wifi networks that have IPV6 enabled. It is not only applicable to 4g connections

**Comment by chinesedfan** [comment]
I guess it depends on your DNS resolving and is out-of-scope. However, I will leave it open weeks for others users to help.
