### ISSUE TITLE
axios.delete still working after canceltoken triggered

### ISSUE THREAD

**Issue by Leoguedesm1** [axios/axios#2720]
**Describe the bug**

time of setTimeout ends and it aborts delete axios call that triggers catch, but the data in database is deleted the same way.

**To Reproduce**

```js 
 export async function axiosDelete(url, config) {

    const abort = axios.CancelToken.source();
   
    setTimeout(() => {
        abort.cancel();
    }, 2);

    config.cancelToken = abort.token;
    let res = await axios.delete(getApiUrl() + url, config)
    .catch(err => {
    
        let data = {};

        if(err.code == 'ECONNABORTED' || err.code == undefined) {
            data.timeout = true;
            data.error = false;
        } else {
            data.timeout = false;
            data.error = true;
        }

        data.success = false;
        data.message = err;

        return { data };
    
    });

    return res;
}
```

**Expected behavior**
data in database is not deleted

**Environment:**
 - Axios Version [0.19.2]
 - expo [36.0.0]
 - expo-cli [3.11.7]
 - React [16.9] 
 - React Native [sdk-36.0.1]

**Comment by WofWca** [comment]
Even if we can call it an issue, I doubt it has to do with axios, rather with the server.

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios/issues/2707#issuecomment-581012933.

**Comment by Leoguedesm1** [comment]
> See [#2707 (comment)](https://github.com/axios/axios/issues/2707#issuecomment-581012933).
console.log (err) in catch:
Cancel: {
   message: undefined
}
I believe the undefined is because I did not assign anything to the variable in CancelToken.

but I know that the call from axios was canceled because the error itself is from CancelToken

**Comment by Leoguedesm1** [comment]
> See [#2707 (comment)](https://github.com/axios/axios/issues/2707#issuecomment-581012933).

console.log (err) in catch:
Cancel: {
   message: undefined
}
I believe the undefined is because I did not assign anything to the variable in CancelToken.

but I know that the call from axios was canceled because the error itself is from CancelToken

**Comment by Leoguedesm1** [comment]
> Even if we can call it an issue, I doubt it has to do with axios, rather with the server.

I can paste the delete code of server here, If you want it.
The problem only appears with the delete call.
Canceltoken Works, but the delete call too.

**Comment by chinesedfan** [comment]
@Leoguedesm1 I think you need do some debugging to find out why the request is send.

- The request must have reached your server side. Can you log in the server to check?
- If you didn't customize the adapter, use "console.log(axios.defaults.adapter);" to check your real used adapter(xhr or http).

**Comment by Leoguedesm1** [comment]
> @Leoguedesm1 I think you need do some debugging to find out why the request is send.
> 
> * The request must have reached your server side. Can you log in the server to check?
> * If you didn't customize the adapter, use "console.log(axios.defaults.adapter);" to check your real used adapter(xhr or http).

First: 

Ok, now sometimes it is reaching the server side and sometimes not.

But every time I make the calls, the canceltoken error message appears.

I put a success log on the server side.
I also put a log when the token is aborted and a log in the then of the call, but then is never called.

And I think 2ms is too fast for any connection, the problem is that the canceltoken is activated even though the axios call is being completed.

The code of delete function on server side:

`router.delete('/notification', (req, res, next) => {

	var _id = req.query._id;

	config.verifyToken(req, res, () => {
		Notification.findOneAndDelete({ "_id" : _id }, function(err){
			console.log('Success!');
			return res.json({ success: true });

		});

	});

})`

Second:

The console.log(axios.defaults.adapter) shows in console: Adapter:  [Function xhrAdapter]

**Comment by chinesedfan** [comment]
> I think 2ms is too fast for any connection

If you were familiar with event loops, `setTimeout(fn, 2)` doesn't mean `fn` will be executed in 2ms exactly.

I can finish the story now, but can't guarantee everything is true.
- The request reaches your server sometimes, because `setTimeout` is not stable.
- And the `onreadystatechange` callback is called asynchronously. So `request` is not cleaned up even thought the request has been send. See more in `lib/adapters/xhr.js`.
- When the timeout happenes, `abort.cancel` is called. That triggeres the cancelToken promise and throws an error.

We can pray that an XHR expert will see this issue. That's what I can do now.

**Comment by Leoguedesm1** [comment]
@chinesedfan  Thanks for the help. I will wait for the xhr expert
