### ISSUE TITLE
What is the difference about 'amd' and 'get' in examples file?

### ISSUE THREAD

**Issue by Syeong2** [axios/axios#2721]
**Describe the issue**
I am new to the axios. I wonder what is the difference about 'amd' and 'get' in examples file. Thinking about the difference, I found 'requirejs' command in 'amd'. I think 'requirejs' is the major difference. But I don't know why we use it.
In a nutshell, what is the main function of 'amd' and why we use 'requirejs'? Main function and command 'requirejs' is related each other? @mzabriskie 

**Example Code**
Here are links about code.
https://github.com/axios/axios/blob/master/examples/amd/index.html#L20-L30
https://github.com/axios/axios/blob/master/examples/get/index.html#L11-L14

amd code
```js
// Example code here
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.16/require.min.js"></script>
    <script>
      requirejs.config({
        paths: {
          axios: '/axios.min'
        }
      });


      requirejs(['axios'], function (axios) {
        axios.get('https://api.github.com/users/mzabriskie')
          .then(function (user) {
```

get code
```js
    <script src="/axios.min.js"></script>
    <script>
      axios.get('/get/server')
        .then(function (response) {
```

**Environment:**
 - Axios Version [0.19.2]
 - OS: [Windows 10.0.1]
 - Browser [Chrome]
 - Browser Version [79]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
Read more from https://requirejs.org/. Especially the differences between AMD and CommonJS, in https://requirejs.org/docs/whyamd.html.
