### ISSUE TITLE
Is there options to set up karma test environment?

### ISSUE THREAD

**Issue by codingnoye** [axios/axios#2722]
**Describe the issue**
I tried to set up test enviroment, but an error always occured.
```bash
Chrome 79.0.3945 (Linux 0.0.0): Executed 199 of 199 SUCCESS (2.548 secs / 2.408 secs)
09 02 2020 12:13:00.445:WARN [launcher]: Firefox have not captured in 240000 ms, killing.
09 02 2020 12:13:00.447:WARN [launcher]: Opera have not captured in 240000 ms, killing.
09 02 2020 12:13:02.449:WARN [launcher]: Firefox was not killed in 2000 ms, sending SIGKILL.
09 02 2020 12:13:02.449:WARN [launcher]: Opera was not killed in 2000 ms, sending SIGKILL.
09 02 2020 12:13:04.452:WARN [launcher]: Firefox was not killed by SIGKILL in 2000 ms, continuing.
09 02 2020 12:13:04.455:WARN [launcher]: Opera was not killed by SIGKILL in 2000 ms, continuing.
Warning: Task "karma:single" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```
I think it is because there is no browser used for karma.
I manually changed `karma.conf.js:119` and it works fine. But I think it's better to have options.
Is there an option to choose a browser to use for testing?
**Example Code**
[https://github.com/axios/axios/blob/master/karma.conf.js#L110-L119](https://github.com/axios/axios/blob/master/karma.conf.js#L110-L119)
```diff
diff --git a/karma.conf.js b/karma.conf.js
index 5525421..b34046d 100644
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -115,7 +115,7 @@ module.exports = function(config) {
     browsers = ['Firefox'];
   } else {
     console.log('Running locally since SAUCE_USERNAME and SAUCE_ACCESS_KEY environment variables are not set.');
-    browsers = ['Firefox', 'Chrome', 'Safari', 'Opera'];
+    browsers = ['Chrome'];
   }
```

**Environment:**
 - Axios Version [e.g. 0.19.2]
 - OS: [Ubuntu 19.04]
 - Browser [Chrome]
 - Browser Version [79.0.3945.130]
 - Additional Library Versions []

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
> Is there an option to choose a browser to use for testing?

Try to set `process.env`. Say `SAUCE_USERNAME=test SAUCE_CHROME=1`. More details can be found in `karma.config.js`.
