### ISSUE TITLE
Cannot read property 'stderr' of undefined

### ISSUE THREAD

**Issue by ohtaeg** [axios/axios#2723]
**Describe the bug**
An error occurred during the test.

**Error Log**
Uncaught TypeError: Cannot read property 'stderr' of undefined
```
webpack: Compiled successfully.
09 02 2020 14:35:00.753:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
09 02 2020 14:35:00.755:INFO [launcher]: Launching browsers Firefox, Chrome, Safari, Opera with unlimited concurrency
09 02 2020 14:35:00.758:INFO [launcher]: Starting browser Firefox
09 02 2020 14:35:00.759:ERROR [launcher]: No binary for Firefox browser on your platform.
  Please, set "FIREFOX_BIN" env variable.
Fatal error: Cannot read property 'stderr' of undefined
npm ERR! Test failed.  See above for more details.
```

I understood the error that occurs without `Firefox`.
However, there is a difference between standard input and output errors for each OS.
There was no problem when testing Ubuntu OS 18.04.
However, an error occurred when testing with Mac OS X 10.10.1

I tried to test it the way below.
<pre>
<code>npm test</code>
</pre>
Is there any other way to test it?
Does each OS have a different standard I/O approach?

**Environment:**
 - Axios Version: 0.19.2
 - OS: Mac OS X 10.10.1
 - Browser: n/a
 - Browser Version: n/a
 - Node version: any

**Comment by chinesedfan** [comment]
The error comes from karma. If you want to run the only installed browser, see https://github.com/axios/axios/issues/2722.
