### ISSUE TITLE
Not able to get all the headers in Axios

### ISSUE THREAD

**Issue by jashan05** [axios/axios#2730]
**Describe the bug**
I am not able to get all the headers, already tried setting 

**To Reproduce**
Please follow the below code.

```js
this.client = axios.default.create({
            baseURL: this.rootUrl,
            timeout: 10000,
            responseType: 'json',
            headers: { 'access-control-expose-headers': '*' },
            auth: {
                username: 'aegon-nl',
                password: this.pat,
            },
            validateStatus: function (status) {
                return status >= 200 && status < 300; // default
            },
        });

var response = await this.client.get(uri)
console.log(response.headers)
```

**Expected behavior**
Should be able to get all the headers, I get all these headers while testing it via **Postman**

**Environment:**
 - Axios Version  - axios/0.19.1
 
Expected headers as per screenshot.

<img width="925" alt="Screenshot 2020-02-10 at 20 14 27" src="https://user-images.githubusercontent.com/20592130/74181722-0f82bc00-4c42-11ea-91f3-0851f98294a8.png">

** Actual headers I am getting **

{
  'cache-control': 'no-cache, no-store, must-revalidate',
  pragma: 'no-cache',
  'content-length': '73825',
  'content-type': 'application/json; charset=utf-8; api-version=5.1-preview.1',
  expires: '-1',
  p3p: 'CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"',
  'set-cookie': [
    'VstsSession=#####################################
  ],
  'x-tfs-processid': ',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  activityid: '#####################################',
  'x-tfs-session': '#####################################,
  'x-vss-e2eid': '#####################################',
  'x-vss-userdata': '#####################################',
  'x-frame-options': 'SAMEORIGIN',
  'request-context': '#####################################',
  'access-control-expose-headers': 'Request-Context',
  'x-content-type-options': '#####################################',
  'x-msedge-ref': '#####################################',
  date: 'Mon, 10 Feb 2020 19:16:23 GMT',
  connection: 'close'
}

**Comment by chinesedfan** [comment]
- Make sure it is not due to `httponly`. See https://github.com/axios/axios/issues/2698#issuecomment-579070588.
- And confirm the right adapter is used. See https://github.com/axios/axios/issues/2714.

**Comment by jashan05** [comment]
@chinesedfan If you look at the code which i mentioned i am already adding *access-control-expose-headers*

**Comment by jashan05** [comment]
Also i tried - console.log(axios.default.defaults.adapter) and i got the response **[Function: httpAdapter]**, it seems correct adapter is being used but still not all the headers are available in response

**Comment by chinesedfan** [comment]
> which is a response header, instead of request header.

@jashan05 Don't set in axios call, please set in your server codes.

**Comment by jashan05** [comment]
@chinesedfan , server is a SAAS solution and we dont have control in that. On a side note , i am able to get the header if i am using JS and using Requests library.

**Comment by chinesedfan** [comment]
@jashan05 So what are the differences? Compare request headers, response headers and everything you can think. That's all what I can do for you now. Good luck!
