### ISSUE TITLE
axios 0.19.1 returns xhr adapter if used on Node

### ISSUE THREAD

**Issue by akirilyuk** [axios/axios#2731]
**Describe the bug**
When using axios on Node.js, it returns a xhr adapter instead of the http for node

**To Reproduce**
Install some lib which also installs XHRRequest, then axios will return xhr adapter on Node.js.
Else just defined global.XMLHttpRequest ={} and see how axios will try to use this instead of http adapter

**Expected behavior**

**Environment:**
 - Axios Version 0.19.1
 - OS: linux alpine
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
![Screenshot 2020-02-11 at 10 00 49](https://user-images.githubusercontent.com/45361199/74225621-5e206c80-4cbb-11ea-9d11-3f034ae4450a.png)

**Comment by zerrol** [comment]
in node_modules/package.json 
```
  "browser": {
    "./lib/adapters/http.js": "./lib/adapters/xhr.js"
  }
```
that's why get xhr.js in code. 
It's beyond me why did such thing. 

we cannot config adapter in code any more. 
```
axios.defaults.adpater = require('axios/lib/adapters/http')   // not valid
axios.create({
  adapter: require('axios/lib/adapters/http')  // not valid
})
```

**Comment by kepikoi** [comment]
I've added a simple repro https://github.com/kepikoi/axios-repro-319-2731

**Comment by jasonsaayman** [comment]
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. Should you feel that this issue still exists please submit a new issue.

Thanks

**Comment by kepikoi** [comment]
Just checked my repro and it is still an issue in 21.1
![image](https://user-images.githubusercontent.com/12378498/118448578-72d78580-b6f2-11eb-8322-7f6b1c120194.png)

**Comment by iongion** [comment]
Have you managed to find a solution to this ?

I am building a frontend project that runs in electron, I do need unix sockets support and they are available, but I am unable due to axios `package.json` specifying

```
  "browser": {
    "./lib/adapters/http.js": "./lib/adapters/xhr.js"
  },
```

Do you have any idea ? (as a mitigation I expose the function and pass it using expose abilities of electron, but is very cumbersome and I loose the ability to have logging)
