### ISSUE TITLE
hi, i'm trying to use axios interceptors in react

### ISSUE THREAD

**Issue by jensysantana** [axios/axios#2732]
import axios from "axios";

const restApi = axios.create({
    baseURL:'http://localhost:3901'
});

restApi.interceptors.request.use(function (config) {

    // Do something before request is sent
   return config;

  }, function (error) {
    // Do something with request error
   
    return Promise.reject(error);
  });

  export default { restApi };

i try to import it like \<restApi\ /> in my App.js but i have an error please i would like to know how to use my interceptor globally.

thanks for any help

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

Please open a new issue, instead of editing the current one.
