### ISSUE TITLE
getaddrinfo EMFILE localhost Error

### ISSUE THREAD

**Issue by SajjadSM** [axios/axios#2736]
I have two different nodejs project which working with each other by an API. in the first project after receiving GPS data and some instructions, call API from the second project (localhost:2020).

It works well most of the time but, Sometimes it ran into a problem.

```js
var res = await axios.post(`http://localhost:2020/api/mp/show/`, {
     carState: gpsDataObj
});
```

`
Error: getaddrinfo EMFILE localhost   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
`

**Environment:**
 - Axios Version: 0.19.0
 - OS: Ubuntu 16.0.4

**Comment by chinesedfan** [comment]
Closed due to not an issue of axios. See https://stackoverflow.com/questions/10355501/connect-emfile-error-in-node-js.
