### ISSUE TITLE
url encoding 

### ISSUE THREAD

**Issue by beldebala** [axios/axios#2740]
**Describe the issue**
built api url by appending query params to the base url
axios.get is not encoding the request url as result the charecters after # are ignored in the request url

**Example Code**
expected : http://localhost:6387/codes?search=test #23434 & page = 1& pagesize =10 & token=xxxxxx

actual : http://localhost:6387/codes?search=test 

```js
// Example code here
```

**Expected behavior, if applicable**
 request url should be encoded 

**Environment:**
 - axios": "^0.17.1
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser : chrom
 - Browser Version [e.g. 22]
 - Additional Library Versions [react: "^16.1.1"]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
You can write your own `config.paramsSerializer`. The default one doesn't handle everything.
