### ISSUE TITLE
Decode params

### ISSUE THREAD

**Issue by micheilsgrey** [axios/axios#2742]
**Describe the issue**
Noob in javascript, wat to get some data in json from Twitch API. The problem is that i need add params to request. And i need params with '+' insted of '%2B'. How can i get right version of parameters? I know i can just put evrything in the sting variable by myself but is there any way i can actualy use `params: ` option in request method?

**Example Code**

```js
 const response = await axios.get(
        `${GLOBAL.TWITCH_API_ENDPOINT}streams/`,
        {
            headers: {
                'Accept': GLOBAL.TWITCH_ACCEPT_HEADER,
                'Client-ID': GLOBAL.TWITCH_CLIENT_ID_HEADER,
            },
            params: {
                game: 'Some+random+game' // in uri i having ?game=Some%2Brandom%2Bgame and i need ?game=Some+random+game
            }
        }
    );
    console.log(response.data);`
```

**Comment by chinesedfan** [comment]
Yes, you can write your own `config.paramsSerializer`.
