### ISSUE TITLE
transformRequest being called for GET requests

### ISSUE THREAD

**Issue by rmainseas** [axios/axios#2744]
**Describe the bug**
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

According to the README, functions specified in `transformRequest` should only be executed for `PUT`, `POST` and `DELETE`. However, it appears that they are also run for `GET` methods.

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
import { create } from "axios";

const api = create({
  baseUrl: `https://api.github.com/`,
  transformRequest: [data => alert(data)]
});

(async () => {
  await api.get("repos/facebook/react");
})();

```

A running reproduction can be found [here](https://codesandbox.io/s/javascript-4ow2t)

**Expected behavior**
The `transformRequest` functions should not be called for `GET` methods.

**Environment:**
 - Axios Version 0.19.2
 - OS: Debian 9
 - Browser Chrome
 - Browser Version 80
 - Additional Library Versions n/a

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by namoojaalallee** [comment]
It's very helpful

**Comment by rmainseas** [comment]
> It's very helpful

Not sure I follow... What's very helpful?

**Comment by jasonsaayman** [comment]
Is this still occurring with the latest version of Axios? If so please open a new issue for this.
