### ISSUE TITLE
Axios + Bolt + Confluence APIs + Basic Authorization header issues

### ISSUE THREAD

**Issue by bennythejudge** [axios/axios#2752]
**Describe the issue**
- writing a slack bot using Bolt and Glitch and I decided to use Axios to execute an HTTP GET to the Confluence API using Basic Authorization (email + API token).
I tried many variations found in the documentation and in the general posts about Axios, but for me eventually only one worked.

**Example Code**
- examples that did not work:

- this got `403`:

```js
  const config = {
    auth: {
      user: process.env.CONFLUENCE_API_USERNAME,
      password: process.env.CONFLUENCE_API_SECRET,
    },
  };
  const url = 'https://' + myConfluenceUser + '.atlassian.net/wiki/rest/api/content/' + myConfluencePage + '?expand=body.storage,version'
  const headers = {
      "Content-Type": "application/json",
    }
  axios.get(url, headers, config)
    .then(response => {
      console.log(response);
      say(`I connected with Confluence, <@${event.user}>!`);
    })
    .catch(error => {
      console.log("ERROR!!!");
      console.log(error);
      say(`Ooops, something went wrong when trying to connect to Confluence, <@${event.user}>`);
      });
});
```

- this one gets `401`

```js
  const url = 'https://' + myConfluenceUser + '.atlassian.net/wiki/rest/api/content/' + myConfluencePage + '?expand=body.storage,version'
  const headers = {
      "Content-Type": "application/json",
  }
  axios({
    "url": url,
    "method": "GET",
    headers,
    "auth": {
      "user": process.env.CONFLUENCE_API_USERNAME,
      password: process.env.CONFLUENCE_API_SECRET,
    }
  })
      .then(response => {
      console.log(response);
      say(`I connected with Confluence, <@${event.user}>!`);
    })
    .catch(error => {
      console.log("ERROR!!!");
      console.log(error);
      say(`Ooops, something went wrong when trying to connect to Confluence, <@${event.user}>`);
      });
});
```

- this one gets `403`:

```js
  const user = process.env.CONFLUENCE_API_USERNAME;
  const password = process.env.CONFLUENCE_API_SECRET;
  const token = Buffer.from(`${user}:${password}`, 'utf8').toString('base64')
  const url = 'https://' + myConfluenceUser + '.atlassian.net/wiki/rest/api/content/' + myConfluencePage + '?expand=body.storage,version'
  const headers = {
      "Content-Type": "application/json",
      "Authorization": "Basic " + token,
  }
  axios.get(
    url,
    headers
  )
      .then(response => {
      console.log(response);
      say(`I connected with Confluence, <@${event.user}>!`);
    })
    .catch(error => {
      console.log("ERROR!!!");
      console.log(error);
      say(`Ooops, something went wrong when trying to connect to Confluence, <@${event.user}>`);
      });
```

- Finally the only one that has worked for me is this:
```js
  const user = process.env.CONFLUENCE_API_USERNAME;
  const password = process.env.CONFLUENCE_API_SECRET;
  const token = Buffer.from(`${user}:${password}`, 'utf8').toString('base64')
  const url = 'https://' + myConfluenceUser + '.atlassian.net/wiki/rest/api/content/' + myConfluencePage + '?expand=body.storage,version'
  const headers = {
      "Content-Type": "application/json",
      "Authorization": "Basic " + token,
  }
  axios({
    "url": url,
    "method": "GET",
    headers
  })
      .then(response => {
      console.log(response);
      say(`I connected with Confluence, <@${event.user}>!`);
    })
    .catch(error => {
      console.log("ERROR!!!");
      console.log(error);
      say(`Ooops, something went wrong when trying to connect to Confluence, <@${event.user}>`);
      });
```

**Expected behavior, if applicable**
All the snippet appear to be valid according to documentation and posts, but only one works and it requires to calculate the `base64` encoding of the `user:password` string on my own. 
Have I misread the documentation and/or misunderstood anything?

**Environment:**
 - Axios Version [e.g. 0.18.0]
`"axios": "^0.19.2"`

 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
```
$ uname -a 
Linux 209c8d5f8ee1 4.4.0-1085-aws #96-Ubuntu SMP Tue Jun 11 09:08:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

 - Browser [e.g. Chrome, Safari]
n/a

 - Browser Version [e.g. 22]
n/a

 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]
`"@slack/bolt": "^1.5.0",`

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ma-zal** [comment]
Same issue with `auth` option, also with Confluence API.
But somewhere else (to other web service) the `auth` option works in my app. I do not know yet, what is so special in Confluence API.

Axios version: 0.20.0

**Comment by ma-zal** [comment]
Same issue.

**Investigation**

There is library `follow-redirects` used in `axios`. My API responded `HTTP 301` (redirection from HTTP to HTTPS). Therefore lib follows it. But the `auth` credentials was not used anymore on destination location.

When I changed URL to avoid redirection, auth works.

**Root cause**

Axios does not send `Authorization` header (based on `auth` parameter) on second request, when a `HTTP 301 Moved Permanently` is response of first request.

_Note: In my case I am using proxy configuration (not sure, if it cares or not): `{ proxy: false, httpAgent: tunnel.httpOverHttp(...), httpsAgent: tunnel.httpsOverHttp(...) }`._

Axios version: 0.20.0

**Comment by ClarkMiaguo** [comment]
> Same issue.
> 
> **Investigation**
> 
> There is library `follow-redirects` used in `axios`. My API responded `HTTP 301` (redirection from HTTP to HTTPS). Therefore lib follows it. But the `auth` credentials was not used anymore on destination location.
> 
> When I changed URL to avoid redirection, auth works.
> 
> **Root cause**
> 
> Axios does not send `Authorization` header (based on `auth` parameter) on second request, when a `HTTP 301 Moved Permanently` is response of first request.
> 
> _Note: In my case I am using proxy configuration (not sure, if it cares or not): `{ proxy: false, httpAgent: tunnel.httpOverHttp(...), httpsAgent: tunnel.httpsOverHttp(...) }`._
> 
> Axios version: 0.20.0, NodeJS: 12.18.3

same issue found.
There is library follow-redirects used in axios.
```
    var redirectUrl = url.resolve(this._currentUrl, location);
    debug("redirecting to", redirectUrl);
    Object.assign(this._options, url.parse(redirectUrl));
```
the **auth** parameter will be replace by the url.parse(redirectUrl), normally null, as a result, the authentication will fail

**Comment by ClarkMiaguo** [comment]
`beforeRedirect` of module **follow-redirects@1.13** provide the possible to add the **auth** again when redirect.

**Comment by jasonsaayman** [comment]
We have updated follow-redirects to the latest possible versions. Please check with the latest Axios version, should this issue still be present please open a new issue.
