### ISSUE TITLE
Readme.me Interceptor config

### ISSUE THREAD

**Issue by LeonAlexanderBartz** [axios/axios#2754]
**Section/Content To Improve**
https://github.com/axios/axios#interceptors
from
```javascript
return config;
```
to
```javascript
config.headers.example = 'example';
return config;
```

**Suggested Improvement**
Make clear that config is an editable object.

**Relevant File**:
README.md

**Comment by mubarak23** [comment]
I will work on this by adding the above change to the documentation.
