### ISSUE TITLE
createError.js:16 Uncaught (in promise) Error: Network Error     at createError (createError.js:16)     at XMLHttpRequest.handleError (xhr.js:69)

### ISSUE THREAD

**Issue by ggmo** [axios/axios#2755]
Hello, when i use axios get somedata from api , ERROR occurs and i cannot fix it , plz help .
createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:69)

with chrome debug can get data from api with crud method, but with axios in vue caught error;

**Comment by ggmo** [comment]
my vue config:

import axios from 'axios'
import router from '@/router/routers'
import { Notification, MessageBox } from 'element-ui'
import store from '../store'
import { getToken } from '@/utils/auth'
import Config from '@/settings'

// 创建axios实例
const service = axios.create({
  baseURL: process.env.NODE_ENV === 'production' ? process.env.VUE_APP_BASE_API : '/', // api 的 base_url
  timeout: Config.timeout // 请求超时时间
})

// request拦截器
service.interceptors.request.use(
  config => {
    if (getToken()) {
      config.headers['Authorization'] = getToken() // 让每个请求携带自定义token 请根据实际情况自行修改
    }
    // 数据交互走JSON
    config.headers['Content-Type'] = 'application/json'
    return config
  },
  error => {
    // Do something with request error
    console.log(error) // for debug
    Promise.reject(error)
  }
)

// response 拦截器
service.interceptors.response.use(
  response => {
    const code = response.status
    if (code < 200 || code > 300) {
      Notification.error({
        title: response.message
      })
      return Promise.reject('error')
    } else {
      return response.data
    }
  },
  error => {
    let code = 0
    try {
      code = error.response.data.status
    } catch (e) {
      if (error.toString().indexOf('Error: timeout') !== -1) {
        Notification.error({
          title: '网络请求超时',
          duration: 5000
        })
        return Promise.reject(error)
      }
    }
    if (code) {
      if (code === 401) {
        MessageBox.confirm(
          '登录状态已过期，您可以继续留在该页面，或者重新登录',
          '系统提示',
          {
            confirmButtonText: '重新登录',
            cancelButtonText: '取消',
            type: 'warning'
          }
        ).then(() => {
          store.dispatch('LogOut').then(() => {
            location.reload() // 为了重新实例化vue-router对象 避免bug
          })
        })
      } else if (code === 403) {
        router.push({ path: '/401' })
      } else {
        const errorMsg = error.response.data.message
        if (errorMsg !== undefined) {
          Notification.error({
            title: errorMsg,
            duration: 5000
          })
        }
      }
    } else {
      Notification.error({
        title: '接口请求失败',
        duration: 5000
      })
    }
    return Promise.reject(error)
  }
)
export default service

**Comment by ggmo** [comment]
my api defined with axios(mojo):

import request from '@/utils/mojo'

export function add(data) {
  return request({
    url: 'http://192.168.100.100:8080/devices',
    method: 'post',
    data
  })
}

export function del(ids) {
  return request({
    url: 'http://192.168.100.100:8080/devices',
    method: 'delete',
    data: ids
}

export function edit(data) {
  return request({
    url: 'http://192.168.100.100:8080/devices',
    method: 'put',
    data
  })
}

export default { add, edit, del }

**Comment by ggmo** [comment]
and the request is not sending to server, chrome debug info :

Request URL: http://127.0.0.1:8002/devices?page=0&size=10&sort=id%2Cdesc
Referrer Policy: no-referrer-when-downgrade

there have no method

**Comment by ggmo** [comment]
but with server side it work fine 

[2020-02-17 21:15:17.44329] [2492] [info] Creating Routes for resource 'Device' (controller => Device)
[2020-02-17 21:15:17.44358] [2492] [debug]  GET /devices  (api_get)
[2020-02-17 21:15:17.44372] [2492] [debug]  POST /devices  (api_create)
[2020-02-17 21:15:17.44385] [2492] [debug]  DELETE /devices/  (api_delete)
[2020-02-17 21:15:17.44401] [2492] [debug]  PUT /devices/  (api_update)
[2020-02-17 21:15:17.44420] [2492] [debug]  GET /devices/download  (api_download)
[2020-02-17 21:15:17.44449] [2492] [info] Creating Routes for resource 'Firewall' (controller => Firewall)
[2020-02-17 21:15:17.44463] [2492] [debug]  GET /firewalls  (api_get)
[2020-02-17 21:15:17.44476] [2492] [debug]  POST /firewalls  (api_create)
[2020-02-17 21:15:17.44487] [2492] [debug]  DELETE /firewalls/  (api_delete)
[2020-02-17 21:15:17.44495] [2492] [debug]  PUT /firewalls/  (api_update)
[2020-02-17 21:15:17.44512] [2492] [debug]  GET /firewalls/download  (api_download)
[2020-02-17 21:15:17.44751] [2492] [info] Listening at "http://0.0.0.0:8002"
Server available at http://0.0.0.0:8002
[2020-02-17 21:15:21.82063] [2492] [debug] [b3ad801b] GET "/devices"
[2020-02-17 21:15:21.82514] [2492] [debug] [b3ad801b] Routing to controller "FirewallManager::Controller::Device" and action "get"
$VAR1 = bless( {
                 'headers' => {
                                'access-control-allow-origin' => [
                                                                   '*'
                                                                 ],
                                'server' => [
                                              'WENWU YAN'
                                            ]
                              }
               }, 'Mojo::Headers' );

[2020-02-17 21:15:21.82694] [2492] [debug] [b3ad801b] 200 OK (0.006289s, 159.008/s)

**Comment by ggmo** [comment]
and in server side headers info as below:

Access-Control-Allow-Origin: *
Content-Length: 3262
Date: Mon, 17 Feb 2020 13:56:10 GMT
Server: PERL
-Type: application/json;charset=UTF-8

**Comment by ggmo** [comment]
server side headers info:

Access-Control-Allow-Origin: *
Content-Length: 3262
Date: Mon, 17 Feb 2020 13:56:10 GMT
Server: PERL
Content-Type: application/json;charset=UTF-8

**Comment by ggmo** [comment]
also axios timeout is 10 mins

**Comment by ggmo** [comment]
with curl -v also works :

* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080(#0)
> GET /devices?page=0 HTTP/1.1
> Host: 127.0.0.1:8002
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Length: 3262
< Date: Mon, 17 Feb 2020 14:02:18 GMT
< Server: PERL
< Content-Type: application/json;charset=UTF-8
< 
{"content":[{"create_time":"2020-02-17 17:19:46","id":1,"ip":"1.1.1.100","name":"CC-DC1-NZX-S1","pwd":"cisco","type":"switch","user_name":"cisco"},{"create_time":"2020-02-17 17:19:53","id":2,"ip":"1.1.1.1","name":"CC-DC1-NZX-S1","pwd":"cisco","type":"switch","user_name":"cisco"}],"totalElements":24}

**Comment by Maconzhang** [comment]
i have same question

**Comment by 2xSamurai** [comment]
+1 same issue. Response is Error: Network Error.

Does anyone have any sikutions?

Thank you.

**Comment by ggmo** [comment]
Solved ！！！
Because of the limitation of the CORS policy, the above problem is caused CORS. After the PROXY policy configured in VUE can be accessed normally, the OPTIONS response needs to be supported on the server side.

**Comment by ggmo** [comment]
with vue_dev env need the server side support options method

[2020-02-18 19:07:35.58702] [2511] [debug] [69f30b6c] 200 OK (0.001815s, 550.964/s)
[2020-02-18 19:07:36.19296] [2511] [debug] [f4101b49] OPTIONS "/mojo/devices"
[2020-02-18 19:07:36.19325] [2511] [debug] [f4101b49] Routing to controller "FirewallManager::Controller::Device" and action "options"
[2020-02-18 19:07:36.19351] [2511] [debug] [f4101b49] 200 OK (0.000547s, 1828.154/s)
[2020-02-18 19:07:36.19753] [2511] [debug] [54488097] GET "/mojo/devices"
[2020-02-18 19:07:36.19791] [2511] [debug] [54488097] Routing to controller "FirewallManager::Controller::Device" and action "get"
$VAR1 = 'SELECT * FROM device_info ORDER BY id desc LIMIT 10, 10';
