### ISSUE TITLE
Can't request with cors, and why axios is different from native fetch().

### ISSUE THREAD

**Issue by zicjin** [axios/axios#2762]
**Describe the issue**
my netlify app has been configured with Access-Control-Allow-Origin headers. And the native fetch() function can easily access resource. But axios cannot succeed.

**Example Code**
I used both axios and fetch requests and got different results.

```js
  try {
    const resp = await fetch(`${config.dochost()}/docs.json`)
    if (!resp.ok) {
      throw new Error(`HTTP error ${resp.status}`)
    }

    const resp2 = await axios.get<DevDocMeta[]>(`${config.dochost()}/docs.json`, {
      headers: {
        'Access-Control-Allow-Origin': '*',
      },
    })

    return resp.json()
  } catch (error) {
    console.error(error)
  }
```
![捕获](https://user-images.githubusercontent.com/199482/74713429-88e26600-5263-11ea-8fd4-d6081a474381.PNG)
![捕获2](https://user-images.githubusercontent.com/199482/74713433-8b44c000-5263-11ea-80e8-f167f258fd49.PNG)
![捕获3](https://user-images.githubusercontent.com/199482/74713434-8bdd5680-5263-11ea-9afe-8845dca5c492.PNG)

**Environment:**
 - Axios Version [e.g. 0.19.1]
 - OS: [e.g. windows 10]
 - Browser [e.g. Chrome]
 - Browser Version [e.g. 80]

**Comment by chinesedfan** [comment]
`headers` in axios are request headers, not response headers. Please compare the requested url and headers with fetch and find out why.
