### ISSUE TITLE
Hi, I'm trying to get cookie from a response

### ISSUE THREAD

**Issue by game-libgdx-unity** [axios/axios#2765]
I'm trying to find a way to get cookie from response after I post to a url

![Image](https://i.imgur.com/NK0FeCw.png)

What I need is  "ksession" which I got in postman, please look at 'cookies' section in response
Thanks!

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

And we suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. Good luck!
