### ISSUE TITLE
Error: Network Error

### ISSUE THREAD

**Issue by 2xSamurai** [axios/axios#2766]
**Describe the bug**
I have a react native app.
All my Axios requests are failing on anrdoid 7.
**It works flawlessly on iOS and newer Android versions.**
I am calling a serverside API. And no I am not using localhost.
I think CORS are also setup correctly.
![image](https://user-images.githubusercontent.com/8579190/74826183-2d7ea980-5331-11ea-82d2-f34d6984e8b5.png)

**This is what I am getting as a response.**
Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:83)
    at XMLHttpRequest.dispatchEvent (event-target-shim.js:818)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:574)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:388)
    at XMLHttpRequest.js:501
    at RCTDeviceEventEmitter.emit (EventEmitter.js:189)
    at MessageQueue.__callFunction (MessageQueue.js:436)
    at MessageQueue.js:111
    at MessageQueue.__guard (MessageQueue.js:384)

**To Reproduce**
Try an axios request in Android 7

```js
axios
    .get(url)
    .then(response => {
      return response;
    })
    .catch(error => {
      throw error;
    });
```

**Expected behavior**
Not to fail I guess.

**Environment:**
 - Axios Version 0.19.2
 - OS: Android 7
 - Additional Library Versions [React 16.9.0, React Native 0.61.5]

**Additional context/Screenshots**

These are there in the Manifest file in Android. 

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<application  android:usesCleartextTraffic="true"
```

**Comment by chinesedfan** [comment]
See #973. If it can't solve the problem, requires someone to find the reason.

**Comment by usuf16** [comment]
i got this issue after updating from react-native 0.59.1 to 0.59.10 

the problem persists only in android 7.0, not in other subversions.

added  android:usesCleartextTraffic="true" as referred in stackoverflow, etc., but no luck
