### ISSUE TITLE
TLS 1.2 only, disable TLS 1.0

### ISSUE THREAD

**Issue by KevinDenys** [axios/axios#2767]
I am wondering if there is a way of forcing Axios requests to only use outbound TLS 1.2 protocol. Due security issues with TLS Protocol version 1.0 and version 1.1.

If someone could point me in the the right direction.

**Comment by Rohitsaxena** [comment]
Did you find any solution for the above.

**Comment by recursivefunk** [comment]
I'm also looking for an answer to this.

**Comment by Elliot128** [comment]
Did anyone find a workaround for this?

**Comment by Rohitsaxena** [comment]
Not Yet.

**Comment by jermitval** [comment]
```javascript
const axios = require("axios");
const https = require("https");
const httpsAgent = new https.Agent({
  maxVersion: "TLSv1.2",
  minVersion: "TLSv1.2"
});
axios({ method: "get", url: null, data: null, httpsAgent })
```

**Comment by KevinDenys** [comment]
We fixed this issue by updating our node version from 8 to 11. And using @jermitval his code example
