### ISSUE TITLE
use interceptors.response,it change my data value from string to int 0

### ISSUE THREAD

**Issue by X-H-siwan** [axios/axios#2770]
![image](https://user-images.githubusercontent.com/49404984/75088167-a32e8380-5584-11ea-82a0-3dcc536fc4a6.png)

this time i do not use a respones interceptors,so i got the data value right as a string;
![image](https://user-images.githubusercontent.com/49404984/75088191-f43e7780-5584-11ea-88ad-69b26a30b8c0.png)

this time i use respones interceptors,so i got this,what happened i don't know and also i googled but find no relative stuff for me to solve my proplem

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

And we suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. Good luck!
