### ISSUE TITLE
Why axios sends POST data to redirected GET request

### ISSUE THREAD

**Issue by ciricc** [axios/axios#2772]
I send a POST request and get redirected to GET. 
And when this happens, the axios sends data from the POST request to GET in data, which is why I getting the error 413 (too big data).

How can one do this to avoid?

P.S Redirect is 302

```javascript
let config = {
  url: loginURL,
  jar: this._authjar,
  data: { email: login,  pass},
  httpsAgent: this._agent,
  method: "POST",
  cache: false
}

return axios(config).catch(e => console.log(e.message))
```

Firstly, sending request to this url.

![image](https://user-images.githubusercontent.com/20687373/75119718-81bdbc80-5696-11ea-8b59-4af7006ca3a6.png)

And getting this

![image](https://user-images.githubusercontent.com/20687373/75119580-3525b180-5695-11ea-8c31-a67e47a61368.png)

This is from error

![image](https://user-images.githubusercontent.com/20687373/75119641-ce54c800-5695-11ea-8023-8bd2d4b66e03.png)

**Comment by namoojaalallee** [comment]
This is good

**Comment by ciricc** [comment]
@namoojaalallee Maybe, but in `request` lib it worked fine

**Comment by My-Name-Is-Jeff** [comment]
Have the same issue with a different URL for logging into a different site.
POSTing to different endpoints works fine, only those endpoints that result in a 302.
