### ISSUE TITLE
Posting using an instance ignores setting method with config

### ISSUE THREAD

**Issue by kclonts** [axios/axios#2779]
**Describe the bug**
When creating an instance with `const a = axios.create(configObject)`, axios ignores the method param. This occurs when setting with the _configObject_ and when making a call with the returned instance, a({ method: 'post' });

**To Reproduce**

```js
const Axios = require('axios');

const axios = Axios.create({ headers: { 'Private-Token': 'abc123' } });

axios({ method: 'post', url: 'https://google.com', data: { foo: 'bar' } })
  .then(r => console.log(r.request.method)) // should output 'GET', as it did not actually post
  .catch(e => console.log('google does not let you post, so it was most likely a success'))
```

**Expected behavior**
it should post when setting method to post

**Environment:**
 - Axios Version [0.19.2]
 - OS: [OSX 10.15.x]
 - NodeJS: [12.16.1]

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios/pull/1395#discussion_r179828155.

**Comment by kclonts** [comment]
@chinesedfan 

I'm currently using 0.19.2, and the referenced issue specifies the fix was made in 0.19.1.

Additionally, the config provided to an instance directly `axiosInstance({ method: 'post' })` the method param is still ignored.

**Comment by chinesedfan** [comment]
> When creating an instance with const a = axios.create(configObject), axios ignores the method param.

The linked PR explains why above happens. Can you organize your problem again? I got confused now. Your reproduce code example prints "google does not let you post, so it was most likely a success".

- Why does your comment say "// should output 'GET'"?
- And expected behavior is "it should post when setting method to post"?

**Comment by kclonts** [comment]
If it helps, my issue is not that the global config and the instance configs are intertwined, but that individual instances are ignoring parameters being explicitly set -- they're not working correctly. 

I can take a look later today and see if I can find offending code.
