### ISSUE TITLE
Support async interceptors

### ISSUE THREAD

**Issue by cdhowie** [axios/axios#2780]
**Is your feature request related to a problem? Please describe.**
Interceptors do not support async functions currently (axios proceeds immediately with the request when the async interceptor function returns its promise).

**Describe the solution you'd like**
Axios could support async interceptor functions. `InterceptorManager.prototype.forEach` would need to be made async and any consumers of this function would need to be adjusted appropriately to await the returned promise.

**Describe alternatives you've considered**
A workaround is to imperatively invoke an interceptor function everywhere a request is made.

```js
async function anInterceptor(config) {
  config.url = await someAsyncFunction(config.url);
}

// For this to work we can't add anInterceptor as an interceptor, we have to do this.
async function makeSomeRequest() {
  const config = { /* ... */ };
  await anInterceptor(config);
  const { data } = await axios.request(config);
  // Use data
}
```

This could be made a bit simpler by creating a request function:

```js
async function request(config) {
  await anInterceptor(config);
  return axios.request(config);
}
```

This is still a bit of a hack.

**Comment by chinesedfan** [comment]
> Interceptors do not support async functions currently (axios proceeds immediately with the request when the async interceptor function returns its promise).

It should have been supported. Can you give test codes example?

**Comment by cdhowie** [comment]
You are right, not sure how I came to this conclusion. There must have been some bug on my side.
