### ISSUE TITLE
iterate though result data objects and child

### ISSUE THREAD

**Issue by eyabmohero** [axios/axios#2782]
Hi;

I'm using react axios to get results from url

results look like :

question is how do i loop through result data and display key and value of "Midnight" in my react ?

HTTP/1.1 200 OK
{
   "code": 200,
   "status": "OK",
   "data": [{
       "timings": {
           "Fa": "03:57",
           "Su": "05:46",
           "D": "12:59",
           "Asr": "16:55",
           "Sun": "20:12",
           "Ma": "20:12",
           "Is": "22:02",
           "Ims": "03:47",
           "Midnight": "00:59"
       },
       "date": {
           "readable": "24 Apr 2014",
           "timestamp": "1398332113",
           "greg": {
               "date": "15-05-2018",
               "format": "DD-MM-YYYY",
               "day": "15",
               "weekday": {
                   "en": "Tuesday"
               },

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

If it is something like the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).
