### ISSUE TITLE
blob and arraybuffer lead to different data

### ISSUE THREAD

**Issue by lhk** [axios/axios#2786]
**Describe the bug**
I'm trying to download a zip file with axios. Depending on whether I specify `blob` or `arraybuffer` as `responseType`, the returned data is different.

A `blob` is automatically converted to a string. With a given encoding, this can be converted to a Buffer. Using the `crypto` module from node.js I've looked at the md5 hashes of both the original blob and the decoded buffer. When the string is converted to a buffer with encoding `utf8`, the hashes are identical.
I assume this means that axios implicitly encodes the blob in a `utf8` string?

When requesting an `arraybuffer`, the `response.data` is already a buffer. It has a different hash than the blob. Encoding this buffer as a utf8 string leads to a visibly different string.

**To Reproduce**
Here is my code to reproduce the issue.
I'm hosting a small zipped folder on localhost with npm serve.
This is used as test data:
```

import axios from 'axios';
import * as crypto from 'crypto';


axios.get(
    "http://localhost:5000/folder.zip",
    { responseType: 'blob' })
    .then((response) => {
        // first hash the response itself
        console.log('blob hashed', crypto.createHash('md5').update(response.data).digest('hex'));

        // then convert to a buffer and hash again
        // replace 'utf8' with any valid encoding name
        let buffer = Buffer.from(response.data, 'utf8');
        console.log('buffer decoded from blob, hashed:', crypto.createHash('md5').update(buffer).digest('hex'));
    })

axios.get(
    "http://localhost:5000/folder.zip",
    { responseType: 'arraybuffer' })
    .then((response) => {
        // hash of buffer response
        console.log('buffer hashed', crypto.createHash('md5').update(response.data).digest('hex'));
    })
```

**Expected behavior**
I expect to be able to recover the same "raw" data, regardless of a blob or arraybuffer responseType.

**Environment:**
 - Axios Version  "0.19.2",
 - OS: Ubuntu 19.10
 - Browser NodeJs
 - Browser Version v13.9.0

**Additional ressources**
I've also created a question on SO: https://stackoverflow.com/questions/60454048/how-does-axios-handle-blob-vs-arraybuffer-as-responsetype

**Comment by chinesedfan** [comment]
@lhk Would you mind give test results for your problems? Like for what conditions,

```
// actually
hash1 !== hash2

// expected
hash1 === hash2
```

**Comment by chinesedfan** [comment]
Closed due to stale.
