### ISSUE TITLE
Request from email user returning null

### ISSUE THREAD

**Issue by williamtorres1** [axios/axios#2789]
**Description**
Hi, the emails request on axios api are returning null, anyone else are getting this same problem?

**To Reproduce**
```js
console.log(reponse.data.email) // null
```

**Expected behavior**
the expected response was a string with the email, but it is returning null

**Additional context/Screenshots**

The user profile info:
![image](https://user-images.githubusercontent.com/39351781/75618570-2df81b00-5b4f-11ea-854d-436e56c966f9.png)

The api response from the same user:
![image](https://user-images.githubusercontent.com/39351781/75618591-71528980-5b4f-11ea-8a29-dc658fcea5b2.png)

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please contact Github Support.
