### ISSUE TITLE
blank pdf is downloaded

### ISSUE THREAD

**Issue by ashishgupta2505** [axios/axios#2792]
If I am directly calling a third perty api( looker api) from postman I am getting the pdf as download with data.
But When I am calling through my api consuming looker api it is downloading only blank pdf.
But I can see the binary data in my response.

PFB code I am using.

export async function downloadPDF(
req: express.Request,
res: express.Response
): Promise {
const response = await createPdf(TaskID, lookerToken.access_token);
res.set({ 'Content-Type': 'application/pdf', 'Access-Control-Allow-Origin': '*' });
res.status(200).send(response.body);
return res;
}

export async function createPdf(TaskID, lookerToken): Promise {
return new Promise((resolve) => {
const url = "someurl" + TaskID + '/results';
const headers = {
'Authorization': 'token ' + lookerToken
};
axios({
headers,
method: 'get',
url: url,
responseType: 'blob'
}).then((response: any) => {
resolve({
body: response.data
//statusCode: response.status,
});
})
});

PFB the response header:
{ 'access-control-allow-headers':
'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range',
'access-control-allow-methods': 'GET, POST, OPTIONS',
'access-control-allow-origin': '*',
'access-control-expose-headers': 'Content-Length,Content-Range',
'content-type': 'application/pdf',
date: 'Tue, 03 Mar 2020 06:04:20 GMT',
server: 'nginx/1.14.0 (Ubuntu)',
vary: 'Accept-Encoding',
'x-content-type-options': 'nosniff',
'content-length': '72654',
'cache-control': 'proxy-revalidate',
connection: 'close',
age: '0' }

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
