### ISSUE TITLE
Handle iOS error while sending a get request with body!

### ISSUE THREAD

**Issue by ramyareye** [axios/axios#2793]
**Describe the bug**
As it's written [here (iOS 13 Release Notes)](https://developer.apple.com/documentation/ios_ipados_release_notes/ios_13_release_notes) :
**All URLSessionTask instances with a GET HTTP method that contain a body now produce the error NSURLErrorDataLengthExceedsMaximum. (46025234)**

It made me crazy until I could finally find out what's happening!

**To Reproduce**
I want to send a pr to run a message or a flag while user is trying to send a get request with body on iOS (React Native in my case)! is it possible? anyway it's working well on Android!

Thanks

**Comment by ipk2015** [comment]
I have the same problem in iOS, my case is React Native,too. I solve the problem by making the code :_config.data = null
