### ISSUE TITLE
KaiOS support

### ISSUE THREAD

**Issue by preet-dabre** [axios/axios#2794]
**Is your feature request related to a problem? Please describe.**
For allowing cross-origin requests from an app for [KaiOS](https://www.kaiostech.com/) non-standard XMLHttpRequest parameters need be set on XMLHttpRequest object.
Parameters: 
- XMLHttpRequest.mozAnon
- XMLHttpRequest.mozSystem
There isn't any way to set these parameters via config object in the XMLHttpRequest object.

**Describe the solution you'd like**
Please provide a way to set these properties on the Request object from the config passed by user like other standard parameters.

**Describe alternatives you've considered**
An alternative solution could be to modify axios source code.

**Additional context**
[XMLHttpRequest Parameters](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)

**Comment by chinesedfan** [comment]
The suggested solution is to implement your own xhr adapter. Because it is not a common request, forgive axios will not include in the default xhr adapter.
