### ISSUE TITLE
Axios always time out on AWS Lambda for a particular API

### ISSUE THREAD

**Issue by vietbui** [axios/axios#2796]
**Describe the issue**
I'm not really sure if this is an Axios issue or not. The following code runs successfully on my local development machine but always time out whenever I run it from the cloud (e.g. AWS Lambda). Same thing happens when I run on repl.it.

I can confirm that AWS Lambda has internet access and it works for any other API but this:

https://www.target.com.au/ws-api/v1/target/products/search?category=W95362

**Example Code**
https://repl.it/repls/AdeptFluidSpreadsheet

```js
const axios = require('axios');

const handler = async () => {
  const url = 'https://www.target.com.au/ws-api/v1/target/products/search?category=W95362';

  const response = await axios.get(url, { timeout: 10000 });

  console.log(response.data.data.productDataList);
}

handler();
```

**Environment:**
 - Axios Version: 0.19.2
 - Runtime: nodejs12x

**Comment by achillesoo7** [comment]
Hello @vietbui 

This is happening because www.target.com has a cors policy and is not allowing any host other than localhost.

Please read this for more information: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by chinesedfan** [comment]
It is a problem related to network. Can you try the native `require('http')` and test on your cloud server?

**Comment by vietbui** [comment]
@achillesoo7 Thanks for the suggestion. I couldn't see any cors related header in the response when running it from my localhost.

@chinesedfan I tried the native `require('https')` and it times out on by localhost and cloud server. Please find sample code here: https://repl.it/repls/TerribleViolentVolume

```
const https = require('https');

const url = 'https://www.target.com.au/ws-api/v1/target/products/search?category=W95362';

https.get(url, res => {
  var body = '';

  res.on('data', chunk => {
    body += chunk;
  });

  res.on('end', () => {
    var response = JSON.parse(body);
    console.log("Got a response: ", response);
  });
}).on('error', e => {
  console.log("Got an error: ", e);
});
```

Again, I can confirm that same code works on any other API.

Thanks for looking in this.

**Comment by chinesedfan** [comment]
@vietbui So the root reason is that `https://www.target.com.au/` behaves strangely. I am afraid that nothing can be done from the side of axios now. Hope you can contact administrators of the website or someone else to solve it.

**Comment by vietbui** [comment]
@chinesedfan That's what I suspect as well as it also behaves very weirdly with curl.
- curl from local -> 403 access denied
- curl from local with User-Agent header -> success
- curl from cloud server -> 403 access denied

It must be server side validation, something related to AkamaiGHost.

As it has nothing to do with axios, I'll close the ticket.
