### ISSUE TITLE
axios.get  error on laravel 6 / vue js project

### ISSUE THREAD

**Issue by akhmadcoder** [axios/axios#2803]
Hi there, I am developing a project using vue js / laravel 6.  The problem is, when try to use api, it is trying to get from root directory on ubuntu server. On our server has multiple projects in one ip address, so it is like http://ip_address/project1, http://ip_address/project2  etc.  The api working on local server fine, when upload to ubuntu server, it is requesting  http://ip_address/api/users, it should request http://ip_address/project1/public/api/users.  I tried to set default base url for axios, but not worked, so please help me. here is my code in vue js:   
```
loadUsers(){
                axios.get('api/users')
                .then(({ data }) => (this.users = data.users))
                .catch(function(error){
                    swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Qandaydir Xatolik Boldi!',
                        footer: 'Xato: '+response.data.message
                      })
                })
            },      
```

**Comment by chinesedfan** [comment]
> I tried to set default base url for axios, but not worked

How did you do that? Codes are better than words. :)

By the way, please follow the issue template next time.

**Comment by akhmadcoder** [comment]
problem solved, I put the following code to header and problem solved. 

`<base href="{{ asset('http://ip_address/project1/public/') }}" target="_blank">`
