### ISSUE TITLE
Axios missing headers when adding custom header

### ISSUE THREAD

**Issue by danivalls** [axios/axios#2804]
Hello!
I'm trying to add a custom header in axios using an interceptor, but when I do, requests are missing other headers. This is how I add the header:

```js
const { API_IP, API_PORT } = process.env;
const user = LocalStorage.getItem("ASN_user");
const token = user ? user.token : undefined;

const api= axios.create({
  baseURL: `http://${API_IP}:${API_PORT}/`
});

api.interceptors.request.use(
  function(config) {
    config.headers.Authorization = `Bearer ${token}`
    return config;
  },
  function(error) {
    return Promise.reject(error);
  }
);

export default api;
```

Then  I do the request: 

```js
function get(endpoint, params) {
  return api.get(endpoint, { params });
}
```

When I don't add the Authorization header, the headers sent are the following:
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,es;q=0.9,en;q=0.8
Connection: keep-alive
Host: XXX.XXX.XXX.XX:XXXX
Origin: http://localhost:8080
Referer: http://localhost:8080/login
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
```

But when I add the Authorization token, the headers are:

```
Accept: application/json, text/plain, */*
Authorization: Bearer Mjg4NSw4Mjc0ODM=
Referer: http://localhost:8080/login
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
```

When those headers are missing my request is denied by the server because of CORS, which is not happening if I don't set the Authorization token.

I've also tried adding the Authorization header on each request individually instead of using an interceptor, but I got the same results.

**Environment:**
 - Axios Version 0.18.1
 - Node: 12.16.1
 - OS: Win10
 - Browser: Chrome
 - Browser Version 80.0.3987.132

**Comment by sagar-gavhane** [comment]
@danivalls Thanks for creating an issue. Can you double-check that you're using `LocalStorage` on line number 2 instead localStorage? 

```javascript
const user = LocalStorage.getItem("ASN_user");
```

**Comment by chinesedfan** [comment]
> When those headers are missing my request is denied by the server because of CORS, which is not happening if I don't set the Authorization token.

@danivalls It doesn't make sense. Did you reverse the order? I think adding `Authorization` header will result in CORS problem, while without it should be ok. If possible, can you provide the screenshot of the network panel?

**Comment by danivalls** [comment]
> @danivalls Thanks for creating an issue. Can you double-check that you're using `LocalStorage` on line number 2 instead `localStorage`?
> 
> also, add a console log statement to cross-verify that you're getting authorization token.
> 
> ```js
> const user = LocalStorage.getItem("ASN_user");
> ```

Hello and thanks for the help! Yes, the access to ``LocalStorage`` is correct. (I'm using Quasar Framework, so localStorage management is done through the ``LocalStorage`` that quasar provides).

I double checked that the token is correctly being sent on the request.

**Comment by danivalls** [comment]
> > When those headers are missing my request is denied by the server because of CORS, which is not happening if I don't set the Authorization token.
> 
> @danivalls It doesn't make sense. Did you reverse the order? I think adding `Authorization` header will result in CORS problem, while without it should be ok. If possible, can you provide the screenshot of the network panel?

Thanks for your help! No, the order isn't reversed. It happens as I described. 

>> If possible, can you provide the screenshot of the network panel?

Of Course!

![image](https://i.imgur.com/g6O768B.png)

This is the info of the request failed with the bearer token attached.
Message on the console: 

``Access to XMLHttpRequest at 'http://-----------/----' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.``


And just to make sure, this is a request without the bearer token present, resolved with a 200 OK:

![image](https://i.imgur.com/akiT4hC.png)

**Comment by danivalls** [comment]
Hey! thank you both for your help!

I was talking with the backend guys this morning and they found this is due to a bug on the server-side and they should fix it soon. 

Closing the issue since it's not axios related! 

Thanks a lot for your help! 😄
