### ISSUE TITLE
More flexible ways to customize adapters

### ISSUE THREAD

**Issue by chinesedfan** [axios/axios#2808]
**Is your feature request related to a problem? Please describe.**

Users may want to set different options for native `http` module, or do something with the request object. axios only supports some of them, but doesn't want to add more and more options. For example,

- #974, to set `req.setNoDelay` for http adapter
- #3498, to set `request.open(...., synchronous)` for xhr adapter
- #3422, to set `req.on('socket', cb)`
- #2233, to set `options.localAddress`
- #2498, to set `options.checkServerIdentity`
- #2930, to set `options.insecureHTTPParser`
- #3138, to set `options.dns`
- #3845, to set `options.createConnection`

**Describe the solution you'd like**

Abstract the adapter as more detailed lifecycles, like beforeSend, afterSend. I just have the basic idea, but no detailed solution.

**Describe alternatives you've considered**

If only consider the options, we can add an extra config called `adapterOptions`. Otherwise, users must implement their own adapters.

**Additional context**

Should consider both xhr and http adapters to form a fixed pattern.

**Comment by rhorning** [comment]
@chinesedfan, I don't really have a suggestion, but I also need #2233 (or an alternative to set the local address).

**Comment by seahindeniz** [comment]
What about having something like beforeSend and transportOptions to avoid creating new and different options for each library?

Something like this usage:
```js
/**
 * @param {import("http").ClientRequest | XMLHttpRequest} req 
 */
let beforeSend = (req) => {
  if (req instanceof XMLHttpRequest) {
    req.setRequestHeader("foo", "bar");
    onprogress = () => {};
  } else {
    req.setNoDelay(true);
    req.setHeader("foo", "bar");
  }
};

/**
 * @type {import("http").RequestOptions}
 */
let transportOptions = {
  localAddress: "127.0.0.1",
};

let instance = axios.create({
  // ...
  beforeSend,
  transportOptions,  // Node only
});
```

beforeSend will be called before these lines:
https://github.com/axios/axios/blob/885ada6d9b87801a57fe1d19f57304c315703079/lib/adapters/xhr.js#L177-L178
or this
https://github.com/axios/axios/blob/885ada6d9b87801a57fe1d19f57304c315703079/lib/adapters/http.js#L275-L282

Since transportOptions can only be applied on Node side, it can be destructed in here
https://github.com/axios/axios/blob/885ada6d9b87801a57fe1d19f57304c315703079/lib/adapters/http.js#L83-L90

Wdyt @chinesedfan?

**Comment by chinesedfan** [comment]
@seahindeniz Yes, you shared most of idea with me. Maybe we can learn something from other libraries first, like `got` or `request`. It's not easy to design an ideal solution.

**Comment by Dramex** [comment]
so right now we can't use localAddress with axios ? o.o

**Comment by carlchan1994** [comment]
@Poyoman39 Poyoman39 I have tried your sample code to set up the localAddress but it does not work.
I have tried  'eth1' or private ip for the localAddress field.

**Comment by carlchan1994** [comment]
@Poyoman39 Sorry I forgot this feature is not launched yet.

**Comment by Poyoman39** [comment]
@carlchan1994 my sample should work with an IP. I tried it on a local server, and it seemed to work well. Be sure your outbound IP address is available => `ip addr`
Also be sure to user http or https based on what type of request you make

**Comment by carlchan1994** [comment]
@Poyoman39 I tried again and success this time. Thanks a lot. Here is my code:

`const axios = require('axios').default
const http = require('http')

function create_axios(ip){
  const wrappedHttp = {
    ...http,
    request: (options, callback) => http.request({
      ...options,
      localAddress: ip,
    }, callback),
  }

  return axios.create({
    transport: wrappedHttp,
  })
}

const eth0 = create_axios('10.180.60.82')
const eth1 = create_axios('10.180.60.83')
const eth2 = create_axios('10.180.60.84')
const eth3 = create_axios('10.180.60.85')

eth0.get('https://ifconfig.co/ip').then(res => { console.info(res.data) })
eth1.get('https://ifconfig.co/ip').then(res => { console.info(res.data) })
eth2.get('https://ifconfig.co/ip').then(res => { console.info(res.data) })
eth3.get('https://ifconfig.co/ip').then(res => { console.info(res.data) })`

**Comment by carlchan1994** [comment]
In case of accessing webpage with HTTPS, you may need to use "wrappedHttps" instead of "wrappedHttp" 

`const axios = require('axios').default
const https = require('https')

function create_axios(ip){
  let wrappedHttps = {
    ...https,
    request: (options, callback) => https.request({
      ...options,
      localAddress: ip,
    }, callback),
  }

  return axios.create({
    transport: wrappedHttps,
  })
}`

**Comment by Turbine1991** [comment]
Any solution for IPv6 addresses? The above workaround gives me `Error: bind EINVAL 2307:1000:3c83:ca00:2000::`

**Comment by Poyoman39** [comment]
Here is my solution working both with https and IPV6

```
const https = require('https');

module.exports = ({
  localAddress,
  ...forceOptions
} = {}) => ({
  ...https,
  request: (options, callback) => https.request({
    ...options,
    ...forceOptions,
    ...localAddress && {
      localAddress,
      family: localAddress.includes(':') ? 6 : 4,
    },
  }, callback),
});
```

**Comment by jasonsaayman** [comment]
Closing this issue due to it's age, stale state or due to a loss of momentum surrounding the issue. Please open a new issue should this problem still be relevant.
