### ISSUE TITLE
Axios Using Stale Authorization Header

### ISSUE THREAD

**Issue by dhruvg** [axios/axios#2809]
**Describe the issue**
I set the `Authorization` header manually before making a GET request using Axios. However, the `Authorization` header value in the network request (seen via Chrome Dev Tools) is something different. It is always some stale old value which never changes. Incognito mode works as expected. But, clearing cookies, cache, and local storage in normal Chrome does not solve the problem. Restarting Chrome does not solve the problem. It is like the `Authorization` header is hardcoded just for my Chrome app. I have checked that the value being sent is not hardcoded anywhere in my code. I have also upgraded Axios to the latest version to no avail. So I am perplexed as to where Axios keeps getting that value from despite clearing site data. Is there some Axios cache I don't know about?

**Example Code**
```js
export async function getUser(options) {
  const requestOptions = apiRequestOptions(options);
  console.log(requestOptions);
  return axios.get(baseApiRequestUrl('/user'), requestOptions);
}
```
`requestOptions` value is:
```
{"headers": {"Authorization": "the value I want"}}
```

**Expected behavior, if applicable**
Expected behavior is that the network request I see in Chrome Dev Tools should have the `Authorization` header value set to "the value i want". However, it is a different value.

**Environment:**
 - Axios Version: 0.19.2
 - OS: OSX 10.13.4
 - Browser: Chrome
 - Browser Version: Version 80.0.3987.132 (Official Build) (64-bit)
 - Additional Library Versions: React 16.3.2

**Comment by determin1st** [comment]
server should return allowed headers in CORS OPTIONS response and better with the request itself.
so, dump your errors, I assume they are CORS related.
it goes like `accepted-....-headers: authorization, ...`
