### ISSUE TITLE
Redirection failure is not properly handled

### ISSUE THREAD

**Issue by iradul** [axios/axios#2811]
**Describe the bug**
Current version `0.19.2` has a bug that can't be easily workaround.
The bug comes from `follow-redirects@1.5.10` dependency. It's fixed in the latest version of `follow-redirects` (https://github.com/follow-redirects/follow-redirects/commit/137c8cf467c52c0583502bb611aab7e65704a929) and the master branch is using it (https://github.com/axios/axios/commit/56b72bbd2c2924ff6d89a7004282142d86ead8fa) ~~so you just need to release a new version~~.

~~Please release a new version!~~

**To Reproduce**
Start this server server:
```
const PORT = 8080;
new require('http').Server((req, res) => {
    res.socket.write("HTTP/1.1 301 Moved Permanently\n");
    res.socket.write("Location: http://смольный-институт.рф\n");
    res.socket.write("\n");
    res.socket.end();
}).listen(PORT, () => console.log(`Server is listening on port ${PORT}`));
```

Start this client with latest `axios@0.19.2`:
```
const axios = require('axios');

try {
    axios.get('http://localhost:8080')
        .then(() => console.log('ok'))
        .catch(e => console.log('error handled 1'))
} catch (e) {
    console.log('error handled 2');
}
```

This will throw unrecoverable error.

**Expected behavior**
User should be able to catch the error.

**Environment:**
 - Axios Version 0.19.2
 - OS: any
 - NodeJS

**Comment by iradul** [comment]
Actually current master will just swallow the exception so it's not really fixed! I'll make PR to fix this soon.

**Comment by jasonsaayman** [comment]
Can you please check with the latest Axios version and let me know for now I am closing
