### ISSUE TITLE
JSON Post with arrays

### ISSUE THREAD

**Issue by yamifr07** [axios/axios#2813]
When sending a POST with data that includes an array, it's being convert to an object.
Eg:
axios.post('/endpoint', {names: ['a', 'b', 'c']}, {
    headers: {'Content-Type': 'application/json'}
})

It's sending {names: {0: 'a', 1: 'b', 2: 'c'}} instead of {names: ['a', 'b', 'c']}.

What should i do?

**Comment by chinesedfan** [comment]
Yes, this is a stupid bug but not fixed yet. Closed in favor of #2567.

A workaround is converting the data as string by `JSON.stringily` if you are sending with `application/json`.

```
axios.post('/endpoint', JSON.stringily({names: ['a', 'b', 'c']}), {
headers: {'Content-Type': 'application/json'}
})
```
