### ISSUE TITLE
I need HELP with this issue. I am getting error 400 when i console logged data

### ISSUE THREAD

**Issue by mcbryan1** [axios/axios#2814]
constructor (props){
        super(props);

        this.state ={
            coords:{
                latitude: 0,
                longitude: 0
            },
            
        }
    }

    
    componentDidMount(){
    //Device Location Here
    try{
        if(navigator.geolocation){
            navigator.geolocation.getCurrentPosition(position => {
                let newCoords = {
                   latitude: position.coords.latitude,
                   longitude: position.coords.longitude  
                }
    
                this.setState({
                    coords:newCoords
                });
            
        
            const proxy = "http://cors-anywhere.herokuapp.com/";
        //Api Call
            const api = `${proxy}https://api.darksky.net/forecast/7aebfa9c94eb43be600a971165c63230/
                        ${this.state.coords.latitude},${this.state.coords.longitude}`;
            fetch(api)
                .then(response =>{
                   return response.json();
                })
                .then(data =>{
                    console.log(data);
                })
                .catch((error) => console.log( error.response.request._response ) );
            })
            
        }
    }catch(error){

    }

    
}

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by mcbryan1** [comment]
I tried using a different Api (Weatherbit.io) and it worked
