### ISSUE TITLE
CSRF token from header.

### ISSUE THREAD

**Issue by rachitpant** [axios/axios#2815]
I am working on a vue project with a spring boot backend. Axios `get` requests to the server work fine and I get response with the csrf token in the header. 
From the chrome devtools, I can see the token in the get response header.
![image](https://user-images.githubusercontent.com/1474415/76432143-f0826180-6388-11ea-8a4d-d6beeadd137d.png)

I now want axios to read this and automatically attach this token in subsequent post requests.

I followed the documentation and in my `main.js` file , added this `config` , so that axios would read the token from get requests and automatically add it in the post requests.

`axios.defaults.xsrfHeaderName = 'X-CSRF-TOKEN'`

But I dont see it getting automatically getting attached on subsequent  post requests. 
![image](https://user-images.githubusercontent.com/1474415/76432689-b2d20880-6389-11ea-9415-884558ea3eb0.png)

While making the above post request , I have withCredtials set to true as follows:
```
 axios
        .post('searchPeople', { search }, { withCredentials: true })
        .then(res => {
```

What am I doing wrong. Axios can improve its documentation regarding cors requests especially since virtually every app needs to make this.
Version: 0.19.2

**Comment by chinesedfan** [comment]
You have to save the value in cookies by yourself and set as `xsrfCookieName`. See [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios/blob/master/README.md#more-stories-about-headers).

> Why not amend axios official document directly? This personal repository can be updated sooner, and affects axios reputations less.

And you can also read common Q&A about [CORS](https://github.com/chinesedfan/You-Dont-Know-Axios/blob/master/README.md#nightmares-of-headers-cors-cookies-and-auth) there.
