### ISSUE TITLE
Wrong version for a dependency

### ISSUE THREAD

**Issue by aseprano** [axios/axios#2821]
Your package.json on github requires the follow-redirects: ^1.10.0 library, whereas the package.json in the npm bundle (https://registry.npmjs.org/axios/-/axios-0.19.2.tgz) refers to the older 1.5.10 version of follow-redirects.
Can you fix this depencency issue since the latest version of follow-redirects has a better redirect management, pls?

Please, don't close the issue if you don't fix the problem. It makes no sense to close an issue without actually doing something to fix it.

**Comment by chinesedfan** [comment]
Sure, reopened #2818 and closed this one. If you think an issue should not be closed, you can comment directly there to remind, instead of a new one.

**Comment by aseprano** [comment]
ok thanks :)
sorry for the duplicate
