### ISSUE TITLE
Automatic JSON stringifycation replacer parameter

### ISSUE THREAD

**Issue by aetonsi** [axios/axios#2822]
**Describe the issue**
I'd like to have every key of my objects in the data i send to my backend, but `JSON.stringify` removes the properties with `undefined` value.
`JSON.stringify` has a second parameter `replacer` which allows the altering of the data before stringyfication.
I see in your docs that there's a `paramsSerializer` but not a `dataSerializer` or `jsonStringifyReplacer`  or similar.
So I ended up calling `JSON.parse` on a `JSON.stringify` with my data and the replacer function.
This is ugly because the JSON functions get called 3 times (2 by me and 1 by axios) instead of just the 1 by axios.

I also tried with `transformRequest`, but if i use it to perform the `JSON.stringify` call with my `replacer` function, the data is sent as `FormData` and my backend has to handle it differently.

Is there any way to do it?

**Example Code**
```js
  // THIS REQUIRES ADDITIONAL CALLS TO THE JSON FUNCTIONS
  let data = {a: undefined, b: 123};
  data = JSON.stringify(data, (k, v) => v === void 0 ? null : v);
  data = JSON.parse(data);
  new Axios({
    url: '...',
    method: '...',
    data,
  })
```
or
```js
  // THIS BREAKS MY BACKEND IF I DON'T MANAGE THE DATA DIFFERENTLY
  let data = {a: undefined, b: 123};
  new Axios({
    url: '...',
    method: '...',
    data,
    transformRequest: [data => JSON.stringify(data, (k, v) => v === void 0 ? null : v)],
  })
```

**Expected behavior, if applicable**
I'd like to alter the `JSON.stringify` serialization of `data` without having to manipulate it before the `new axios` call OR having to manage it differently on my backend.
```js
  let data = {a: undefined, b: 123};
  new Axios({
    url: '...',
    method: '...',
    data,
    jsonStringifyReplacer: (k, v) => v === void 0 ? null : v,
  })
```

**Environment:**
 - Axios Version: 0.19.2
 - OS: win 10 1909
 - Browser: Chrome
 - Browser: Version 80.0.3987.116 (Official Build) (32-bit)
 - Additional Library Versions: /

**Additional context/Screenshots**
Correct request payload:
![image](https://user-images.githubusercontent.com/18366087/76624896-742d8100-6536-11ea-92cd-573e13d18c30.png)

Request payload with `transformRequest`:
![image](https://user-images.githubusercontent.com/18366087/76624941-890a1480-6536-11ea-8963-0283122e080b.png)

**Comment by chinesedfan** [comment]
> I also tried with transformRequest, but if i use it to perform the JSON.stringify call with my replacer function, the data is sent as FormData and my backend has to handle it differently.

You should set 'Content-Type' manually. See more in my [personal notes](https://github.com/chinesedfan/You-Dont-Know-Axios#submit-data-successfully).

```
  let data = {a: undefined, b: 123};
  new Axios({
    url: '...',
    method: '...',
+   headers: {
+     'Content-Type': 'application/json;charset=utf-8'
+   },
    data,
    transformRequest: [data => JSON.stringify(data, (k, v) => v === void 0 ? null : v],
  })
```

**Comment by aetonsi** [comment]
Hi, thanks for the reply.
I can confirm that setting the `content-type` header and transforming the request indeed solves the problem without the need for any additional parameter.
For future reference, i resorted to the following code (for the sake of my own clarity, i am changing the headers within the transformer function so that i know what is the purpose of that header):
```js
new Axios({
  url: '...',
  method: '...',
  data: '...',
  transformRequest: [function (data, headers) {
    // force json content type
    headers['Content-Type'] = 'application/json';
    // stringify data replacing undefined values with null
    return JSON.stringify(data, (k, v) => v === void 0 ? null : v);
  }],
})
```

I'm closing the issue.
Thanks again, have a nice day.
