### ISSUE TITLE
431 Request Headers Too Large ONLY LOCALLY

### ISSUE THREAD

**Issue by TheGreekCuban** [axios/axios#2823]
I have a deployed application and I am experiencing an issue with my contact form. This is a React.js app with a node, express and mongoDB backend. It is deployed on Heroku.

On the deployed version everything works great. When a user enters their information into the contact form it runs ```API.saveLead()``` which runs a ```axios.post()``` hits the ```contact/lead``` route. The data is saved to the database. Then ```API.sendMail()``` is called which runs a ```axios.post()``` to the ```contact/lead``` route. The data is packaged and appropriately sent to the desired email address using the nodemailer package.

Although everything is functioning appropriately on on the deployed version, when I click submit on the contact form ON THE LOCAL VERSION, I get a 431 Request headers too large error. It doesn't clear the form, nothing is saved to the local db (I don't think) and the nodemailer module is never even fired.

Here is the error:
```
xhr.js:155 POST http://localhost:3000/contact/lead 431 (Request Header Fields Too Large)
```
Below is the code related to the form submission, its routes and interaction with the mongoose.js model and controller in the backend. 

The handleFormSubmit() calls the saveLead method on the API module which returns the axios routes. The axios route hits the backend where express router handles the routes which then use mongoose.js for the models and controller (leadController.js).

React Component handleFormSubmit API Call:
```
  handleFormSubmit = event => {
      event.preventDefault();

      let options = {
        Name: this.state.fullName,
        Email: this.state.email,
        Phone: this.state.phone,
        Message: this.state.message
      }

      if (this.state.fullName && this.state.email) {
        this.saveLead(options)
      }
    };

  //saveLead function
  saveLead = options => {
      API.saveLead(options)        
        .then(res => {
          this.sendMail(options)
          console.log("RES: ", res)
        })
        .then(res => {
          this.setState({ fullName: "", phone: "", email: "", message: "", 
          prevState: res})
        })
        .catch(err => {
          console.log("[1]err happening here", err)
        });
    }
``` 
API Axios Call To Backend:
```
  // Saves a contact info and messaege to the database
  saveLead: function(leadData) {
    return axios.post("/contact/lead", leadData);
  },

  sendMail: function(mailData) {
    return axios.post("/contact/mail", mailData);
  },
```
API Routes (backend):
```
// API Routes
router.use("/contact", contactRoutes);
```

Lead route (/contact/): 
```
//Lead route
router.use("/lead", leadRoutes);
```

Lead Route (/contact/lead):
```
// Matches with "/contact/lead"
router.route("/")
.get(leadController.findAll)
.post(leadController.create);
```
leadController.js:
```
  create: function(req, res) {
    db.Lead
      .create(req.body)
      .then(response => res.send(response))
      .catch(err => res.status(422).json(err));
  },
  findAll: function(req, res) {
    db.Lead
      .find({})
      .sort({ date: -1 })
      .then(dbModel => res.json(dbModel))
      .catch(err => res.status(422).json(err));
  }
```
Lead Model (db.Lead is used above). This is the mongoose model:
```
const leadSchema = new Schema({
  Name: { type: String, required: true },
  Email: { type: String, required: true },
  Phone: String,
  Message: String,
  Date: { type: Date, default: Date.now }
});

const Lead = mongoose.model("Lead", leadSchema);
```
The link to my gitHub can be found here: https://github.com/TheGreekCuban/agavepv                          
The link to the deployed site can be found here: https://www.agavepv.com

**Environment:**
 - Axios Version ^0.18.1
 - OS: OSX 10.14.6
 - Browser: Chrome (80.0.3987.132), Brave(1.4.96)
 - Additional Library Versions: React 16.12.0, Express ^4.16.3, Mongoose: ^5.3.16,

**Comment by chinesedfan** [comment]
@TheGreekCuban It is a problem that the server can't response correctly, instead of an issue of axios. A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response.

**Comment by TheGreekCuban** [comment]
@chinesedfan Thank you for responding back to me so promptly. I am so confused though, I went through all documentation and my routes seem good, that is why I thought maybe I am doing something wrong with axios.

If you have any idea what I am doing wrong based on the information below I would really appreciate the assistance, this has been driving me nuts.

My request headers for this type of request is: 
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 87
Content-Type: application/json;charset=UTF-8
Host: localhost:3000
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin

General:
Request URL: http://localhost:3000/contact/lead
Request Method: POST
Status Code: 431 Request Header Fields Too Large
Remote Address: 127.0.0.1:3000
Referrer Policy: no-referrer-when-downgrade

Response headers:
connection: close
date: Tue, 17 Mar 2020 15:26:01 GMT
transfer-encoding: chunked
x-powered-by: Express

**Comment by Sami-Shafi** [comment]
anyone fixed the issue? cause i am on the same problem

**Comment by TheGreekCuban** [comment]
Yes, if you are using a full-stack application make sure you are running your backend on a separate server than the React frontend. My issue was that I was making a request to the backend but never had a separate server running. Also, you may need to look into using a proxy if that first solution doesn't fix it.

**Comment by chinesedfan** [comment]
@TheGreekCuban So this is not an issue of axios and you have solved it, right?

**Comment by TheGreekCuban** [comment]
@chinesedfan Correct

**Comment by sujeewakabeysinghe** [comment]
I did nothing but closed all the tabs and rerun the app,
It worked.

**Comment by kAutoman** [comment]
Sometimes it's working and sometimes not working.
what problem?
