### ISSUE TITLE
Post problem in Node.js API - TypeError: utf-8 is not a function

### ISSUE THREAD

**Issue by ellafo** [axios/axios#2826]
In my Node.js API I try to use axios module latest version (0.19.2) to post data to a third server. It works fine when I run it on my local machine, but after deployment to the server 'then' is not executed but 'catch' and I encounter this error:

TypeError: utf-8 is not a function

In the logs I see that apiClient [the variable in the code below] is empty {} on the server while it has value on my local machine:  Promise { <pending> }

I use Advanced REST client v10.0.12 to call the Node.js API.

my local machine:
OS: Windows 10 Enterprise
node version: v4.5.0 
npm version: 2.15.9

Server:
OS: Red Hat Enterprise Linux Server release 6.7 (Santiago)
node version:  v5.8.0
npm version: 3.7.3

Code:
var requestBody = {
          offerActivation: {
            subscriber: {
              msisdn: '123456789123'
            },
            offer: {
              code: '1111ABCD',
              renew: 'false'
            },
            payment: {
              type: 'IP',
              channelTransactionId: '123412345123456',
              price: '1000'
            },
            userDetails: {
              userName: 'ella.fo'
            }
          }
        };
		
var options = {
                  method: 'post',
                  url: 'myURL',
                  data: requestBody,
                  headers: {
                        'Authorization': 'Basic ' + 'XYZ'
                      }
                };

var apiClient = axios(options);

**Comment by chinesedfan** [comment]
Did your server use the wrong adapter? See my personal notes to learn [how to check](https://github.com/chinesedfan/You-Dont-Know-Axios#do-you-use-the-right-adapter) and [try to triage](https://github.com/chinesedfan/You-Dont-Know-Axios#learn-to-triage-issues-first) by yourself.

**Comment by ellafo** [comment]
Thanks,
The value of axios.defaults.adapter is the same in both local machine and server, [Function: httpAdapter]. 
However, I added 'adapter: require('axios/lib/adapters/http')' but got the same error: TypeError: utf-8 is not a function

**Comment by chinesedfan** [comment]
> Codes are better than words.

Can you provide the full sample codes or error stacks?

**Comment by ellafo** [comment]
Here is the relevant part, There is no error stacks, error.message is: utf-8 is not a function

axios(options).then((activationResponse) => {
                  //my code 
                })
                .catch((error) => {
                    if (error.response) {
                      log.write(new Date() + '-ERR:: ERROR while activation, response: ' + error.response);
                    } else if (error.request) {
                      log.write(new Date() + '-ERR:: ERROR while activation, request: ' + error.request);
                    } else {
                      log.write(new Date() + '-ERR:: ERROR while activation, else: ' + error.message);
                    }
                })

**Comment by chinesedfan** [comment]
@ellafo Sorry, we can't help much more unless you can confirm the error position. Because at least your local environment works well, hope you can find the differences.

This issue will be kept open for weeks, but will be closed if no further evidences point to axios bugs. Thanks for understanding.

**Comment by ellafo** [comment]
Thanks @chinesedfan,

Actually I try to find the difference between them, 
As we can see on the logs of the server and my local machine,
while both of them recognize axios module, my local machine returns a promise, but server returns empty value. I think that is why I get the error 'utf-8 is not a function'  

Local log:
console.log('axios ', axios);
console.log('axios(boltonActivationRequest) ', axios(boltonActivationRequest));

axios  function wrap() {
    var args = new Array(arguments.length);
    for (var i = 0; i < args.length; i++) {
      args[i] = arguments[i];
    }
    return fn.apply(thisArg, args);
  }
axios(boltonActivationRequest)  Promise { <pending> }


Server log:
log.write('axios '+ axios);
log.write('axios(boltonActivationRequest) '+ JSON.stringify(axios(boltonActivationRequest)));
axios function wrap() {
    var args = new Array(arguments.length);
    for (var i = 0; i < args.length; i++) {
      args[i] = arguments[i];
    }
    return fn.apply(thisArg, args);
  }
axios(boltonActivationRequest) {}

**Comment by chinesedfan** [comment]
> both of them recognize axios module, my local machine returns a promise, but server returns empty value

Good. Please go ahead and find out why.

**Comment by ellafo** [comment]
The issue seems to be related to the one below
https://github.com/axios/axios/issues/2312

I was able to make it work by downgrading to 0.18.1.

**Comment by chinesedfan** [comment]
> I was able to make it work by downgrading to 0.18.1.

@ellafo So there must be something changed in axios, can you help us find out that?

**Comment by ellafo** [comment]
Sure, how can I help you do that?

**Comment by chinesedfan** [comment]
> Sure, how can I help you do that?

@ellafo Find the reason why only in your server, axios 0.19 returns empty value. Thanks.

**Comment by ellafo** [comment]
I investigated and found that it works fine on the server by reverting the change in the following lines, to the 0.18.1 version:

axios\lib\adapters\http.js (lines 42, 44)

latest version (0.19.2): 
        data = Buffer.from(new Uint8Array(data));
        data = Buffer.from(data, 'utf-8');

version 0.18.1
        data = new Buffer(new Uint8Array(data));
        data = new Buffer(data, 'utf-8');

from the documentation, it looks like, the TypeError I get is because the data type is not string. 
https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding

**Comment by chinesedfan** [comment]
@ellafo Really appreciated for finding out the key changes. According to https://github.com/realm/realm-js/issues/947, it is related to Node.js versions, instead of your data is not string type.
