### ISSUE TITLE
maxContentLength configuration could slowdown request

### ISSUE THREAD

**Issue by akhilstanis** [axios/axios#2829]
**Describe the bug**
Large chunked responses from servers could be slow to finish when `maxContentLength` option is set.

**To Reproduce**
The following code snippet creates an http endpoint which serves huge chunked content. It then fetches the content from the endpooint with and without using `maxContentLength`. It then logs the times taken for each request to finish.

```js
const http = require('http');
const axios = require('axios').default;

const generateChunks = (chunkSize, totalChunks) => {
  let chunks = [];
  for (let i = 0; i < totalChunks; i++) {
    let chunk = ''
    for (let j = 0; j < chunkSize; j++) {
      chunk += String(j);
    }
    chunks.push(chunk);
  }
  return chunks;
}

const CHUNKS = generateChunks(5000, 1000);

const fetchChunks = (done, maxContentLength, chunksUrl = 'http://localhost:8080/chunks') => {
  const [startTime] = process.hrtime();
  axios
    .get(chunksUrl, { maxContentLength })
    .then((r) => done(`Success in ${process.hrtime()[0] - startTime} seconds.`))
    .catch(() => done(`Failure in ${process.hrtime()[0] - startTime} seconds.`))
}

const requestListener = function (req, res) {
  CHUNKS.forEach(chunk => res.write(chunk));
  res.end();
}

const server = http.createServer(requestListener);
server.listen(8080, () => {
  console.log('Running benchmarks...');
  fetchChunks((m) => {
    console.log(`withMaxContentLength => ${m}`);
    
    fetchChunks((msg) => console.log(`withoutMaxContentLength => ${msg}`), -1);
  }, 300000 * 1000);
});
```

**Expected behavior**
Fetching time for requests with and without `maxContentLength` should be about the same.

**Actual behavior**
Fetching time for requests with and without `maxContentLength` are drastically different.
```
Running benchmarks...
withMaxContentLength => Success in 10 seconds.
withoutMaxContentLength => Success in 0 seconds.
```

**Environment:**
 - Axios Version: 0.19.2
 - OS: OSX 10.14
 - Node version: 12.13.0

**Comment by akhilstanis** [comment]
The bug here is that axios is calling `Buffer.concat(responseBuffer).length` everytime it gets a chunk to make sure that total content length is not more than `maxContentLength`. `Buffer.concat` gets more and more expensive as the number of chunks grow. Eventually it all adds up making the request slower.

https://github.com/axios/axios/blob/5189afff38dc0689ac0c1b1bfa51626bb8541709/lib/adapters/http.js#L217-L227

It only checks for this when `maxContentLength > -1` and hence requests are faster when `maxContentLength` is set to -1. 

A simple fix here would be to tack the `contentLength` separately in a variable and compare it to `maxContentLength`. I have PR with the fix here.

The benchmarks shows how well it is improved after the fix.
```
Running benchmarks...
withMaxContentLength => Success in 1 seconds.
withoutMaxContentLength => Success in 0 seconds.
```

**Comment by SupernaviX** [comment]
@akhilstanis good catch! I can confirm that this is slowing down requests significantly at my org.

**Comment by jasonsaayman** [comment]
Please check the latest version of Axios, this problem has been solved.
