### ISSUE TITLE
generated axios.min.js file shows v0.18.0 even though installed v0.19.2

### ISSUE THREAD

**Issue by elyazinho** [axios/axios#2832]
hi my axios.min.js file showing this version even though i installed v0.19.2
how do i update this min file as security check is showing some vulnerability for this version ?
/* axios v0.18.0 | (c) 2018 by Matt Zabriskie */

**Comment by chinesedfan** [comment]
What do you mean `my axios.min.js file`? I have checked node_modules/axios/dist/axios.min.js with the right version.
