### ISSUE TITLE
retry request problem

### ISSUE THREAD

**Issue by gitzhangliang** [axios/axios#2833]
when i use axios.interceptors.response ,when check  code of backserver return is 401, I refresh token and i retry  the previous request. the code like this:
`
axios.interceptors.response.use(
  response => {
    const { data } = response;
    switch (parseInt(data.code)) {
      case 401:
              var newToken = ...;
              response.config.Authentication =newToken ;
              return axios.request(response.config)
        break;
      default:
        break;
    }
    return response;
  },
  error => {
  ....
    }
  }
);
`
and i have a setting:   axios.defaults.baseURL = "/api"
 one correct like this [/api/listUser]，but when i retry request. the url is [/api/api/listUser], i  do not know why [/api] appear twice . so the response is 404.

**Comment by gitzhangliang** [comment]
i us e#1628 way. it works 。 like this:       
response.config.baseURL = response.config.url;
 response.config.url = '';
 response.config.Authentication = res.data.token;
return axios.request(response.config)

**Comment by gitzhangliang** [comment]
before webpack build:
    response.config.baseUrl = "/api", response.config.url = "/api/getUser"   
    whole url = "/api/api/getUser",it is error. 
   i use #1628 way. it works.  whole url = "/api/getUser",it is right
after webpack build：
   response. config.baseUrl = "/api", response.config.url = "/getUser"   
   whole url = "/api/getUser",it is right. 
   when i use #1628 way. it  don`t works.  whole url = "/getUser",it is error.

so it is incompatible about before webpack build and after webpack build.

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

Please open a new issue, instead of editing the current one. Maybe you can read [chinesedfan/You-Dont-Know-Axios](https://github.com/chinesedfan/You-Dont-Know-Axios#understand-how-baseurl-concats-with-url) first.
