### ISSUE TITLE
Logging error in Winston 2.x causes lots of spam 

### ISSUE THREAD

**Issue by kyle2000yt** [axios/axios#2834]
I'm using axios with await/async, and I use try/catch blocks to catch errors and log them using Winston 2.x. It does work, but it spits out a bunch of useless code and is extremely annoying.

[Picture](https://i.kyle2000.com/wT4wV.png)

Node.js v13.9.0

Axios version: ^0.19.2 according to package.json.

**Comment by chinesedfan** [comment]
Please follow the issue template with reproducible code samples.
