### ISSUE TITLE
axios returning http 400 passing query parameter with unicode character %C2%9F

### ISSUE THREAD

**Issue by javheroli** [axios/axios#2837]
I'm trying to fetch a endpoint via GET method passing query parameters encoded as content-type x-www-form-urlencoded. One of the parameters has the decoded value: "eny_ScheeÃeler MÃ¼hle" which contains a special character.

The url encoded parameter string is like: eny_Schee%C3%83%C2%9Feler%20M%C3%83%C2%BChle

So the special character utf-8 encoded version is %C2%9F.
Axios returns http 400 Bad Request without trying to send the request. The endpoint is implemented correctly, it returns propertly results when there are no special characters in parameters

**Comment by chinesedfan** [comment]
Please follow the issue template. I guess you don't like the default params encoding algorithm, you may need to set `paramsSerializer`.
