### ISSUE TITLE
Get request array type parameter will cause the array field name to change

### ISSUE THREAD

**Issue by 24min** [axios/axios#2840]
**Describe the bug**
When using params in the axios get method, the default operation for the parameters of the js array type is strange, which will cause the parameter name to be followed by a '[]' string and a 400 will occur.（Of course, this is based on the fact that I did not make any corrections to the array type parameters when passing parameters.）
In the `dist / axios.js` file, I found the following processing code, but I don’t know why to do this.
```js
if (utils.isArray(val)) {
    key = key + '[]';
} else {
    val = [val];
}
```

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
const url='example/url'
const params = {arr:['1']}
axios.get(url,params).then(res=>{console.log(res)})
```

**Expected behavior**

**Environment:**
 - Axios Version [0.19.2]
 - Browser [Chrome]
 - Browser Version [80.0.3987.149]
 - Additional Library Versions [vue 2.6.11]

**Additional context/Screenshots**
![axios-get](https://user-images.githubusercontent.com/32154293/77379996-09d9d380-6db5-11ea-8cea-061c2496ce95.png)

**Comment by Alanscut** [comment]
@24min You can require "querystring" to parse "params" and this will achieve your purpose.

```javascript
var querystring = require('querystring');

axios.get(url, {
 params: params,
 paramsSerializer: function (params) {
    return querystring.stringify(params)
  },
}).then(res=>{console.log(res)})
```

@mzabriskie Could you please explain why ``key`` is  spliced ``[]``?  ``encodeURIComponent ('+') `` should be transcoded to ``% 2B``, but it is ``% 20`` in the code, which is very confusing. thanks.

```javascript
// buildURL.js

if (utils.isArray(val)) {
    key = key + '[]';
} else {
    val = [val];
}

function encode(val) {
  return encodeURIComponent(val).
    replace(/%40/gi, '@').
    replace(/%3A/gi, ':').
    replace(/%24/g, '$').
    replace(/%2C/gi, ',').
    replace(/%20/g, '+').
    replace(/%5B/gi, '[').
    replace(/%5D/gi, ']');
}

// encodeURIComponent('+') === '%2B'
```

**Comment by biddwan09** [comment]
Hi can I take a look into this issue

**Comment by jasonsaayman** [comment]
Closing this issue due to it's age, stale state or due to a loss of momentum surrounding the issue. Please open a new issue should this problem still be relevant.
