### ISSUE TITLE
Use request inteceptor to modify request headers

### ISSUE THREAD

**Issue by jcalfee** [axios/axios#2843]
**Is your feature request related to a problem? Please describe.**
I need to add authentication parameters in a generic way.  So, I would like to add headers to each request.  

**Describe the solution you'd like**
Can you include a reference to the request object in the inteceptor's use callback function?
```js
// Add a request interceptor
axios.interceptors.request.use(function (config, request) {
// or
axios.interceptors.request.use(function (config, {request}) {
```

**Describe alternatives you've considered**
Wrapping axios.

**Comment by chinesedfan** [comment]
You can add headers by `config`.

```
axios.interceptors.request.use((config) => {
  config.headers = {xx: yy}
  return config
})
```
