### ISSUE TITLE
How does a cancelToken determine cancellation

### ISSUE THREAD

**Issue by wanxue0804** [axios/axios#2845]
My code
```
const CancelToken = axios.CancelToken;
let source = CancelToken.source();
let prevRequestUrl = '';

let cancelRequest = () => {
  if(typeof source === 'function'){
    source('stop request');
  }
}
......
axios.interceptors.request.use(config => {
  cancelRequest();
  config.cancelToken = new CancelToken((c) => {
      // If I don't write a judgment here, the page can only complete the first request
      if (prevRequestUrl === config.url) {
        source = c;
      }
      prevRequestUrl = config.url;
    })
  ......
})
```
This code can execute the same request several times in succession, canceling any unfinished requests and executing the last one. If the same request is not executed continuously in a very short period of time, it will not be canceled, which is what I want but what I am confused about
Can the CancelToken automatically recognize a short period of continuous execution or is there something wrong with my operation

please help me, thanks

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [80.0.3987.149]
 - Additional Library Versions [vue 2.6.10]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
> Can the CancelToken automatically recognize a short period of continuous execution

I think the answer is no. And [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios#cancellation) may help you understand axios cancellation more.
