### ISSUE TITLE
Axios return CORS policy error instead of status 401

### ISSUE THREAD

**Issue by TarasKryvko** [axios/axios#2852]
Hello I am using axios interceptors in my vuejs project. 
I SET CORS POLICIES ON MY SERVER TO ALLOW EVERYTHIG
This is my asp .net core web api
```


 services.AddCors(options => options.AddPolicy(MyAllowSpecificOrigins, builder =>
    {
        builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader();
     })); 
```

   When I request data from my api with an JWT access token I get it and everything is ok. 

```
     getTestData() {  
        return axios.get(API_URL + 'getposts', {  headers: AuthHeader.authHeader() });
     } 
```

But when the token expires I want to use the interceptor to get refresh token.
```
  axios.interceptors.response.use( (response) => {
      // Return a successful response back to the calling service
      return response;
    }, (error) => { 
      console.log(error);   // here I want to get status 401 but get CORS error
    if (error.response.status !== 401) {
      return new Promise((resolve, reject) => {
        reject(error);
      });
    }  
    // Try request again with new token
    return TokenStorage.getNewToken() 
...
```

What I mean is that when server returns 401 axios returns "Access to XMLHttpRequest at 'https://localhost:44369/testdata/getposts' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." . 

If I do the same request in postman I'm getting 401 unauthorized. 
If I have a working access token I can easily get any data with axios, so there is no problem with my server.  Also if I use fetch everything is ok too.

**Comment by determin1st** [comment]
this is purely the CORS restriction stuff implemented inside your browser.
to get rid of that, one should change satisfy all browser warnings - in this case, error state should also pass those headers with 401 status.

**Comment by chinesedfan** [comment]
> If I do the same request in postman I'm getting 401 unauthorized.

Postman will never have CORS problem, because it is not a browser.

> If I have a working access token I can easily get any data with axios, so there is no problem with my server. Also if I use fetch everything is ok too.

If without access token, fetch will have the same CORS problem I think. Feel free to remind me to reopen if there has something wrong in axios really.

**Comment by arfaWong** [comment]
I have the same issue. Both fetch/jQuery.ajax getting 401 unauthorized, but axios return CORS policy error.

**Comment by TarasKryvko** [comment]
I found the problem. So it's not Axios. It is ASP Core. As I remember it was because of wrong sequence of calls.  My app.UseCors() call was before UseEndPoints() then I swapped them and it started to work. 

        public void Configure(
            IApplicationBuilder app,
            IWebHostEnvironment env,
            ApplicationDbContext dbContext,
            UserManager<ApplicationUser> userManager,
            RoleManager<UserRole> roleManager,
            AppConfigs appConfigs
        )
        {  
            if (env.IsDevelopment())
            {
                app.UseExceptionHandler("/error-local-development");
            }
            else
            {
                app.UseExceptionHandler("/error");
            } 

            app.UseRouting();

            app.UseCors(MyAllowSpecificOrigins);
             
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseStaticFiles();

            // ===== Create tables ====== 
            DataInitializer.SeedData(dbContext, userManager, roleManager, appConfigs);

        }
