### ISSUE TITLE
Connection Timings: dns, tcp, tls, firstByte... 

### ISSUE THREAD

**Issue by tiagonapoli** [axios/axios#2853]
**Is your feature request related to a problem? Please describe.**
So, I'm instrumenting some clients for distributed tracing using jaeger and I'm very frustrated that there's no way (at least I don't know :cry:) to get request timings statistics from axios, like: `dnsLookup`, `tcp`, `tls`, ...

Some other clients implement this feature, like `request` (now deprecated) and [`got`](https://github.com/sindresorhus/got#timings).

I think these statistics may be very valuable when trying to find bottlenecks in a distributed context. Is there a plan to implement this on the roadmap? :pray: 

**Describe the solution you'd like**
`got` implements a solution that seems good enough for me - in the response object there will be a `timings` object (https://github.com/sindresorhus/got#timings):
```
- start - Time when the request started.
- socket - Time when a socket was assigned to the request.
- lookup - Time when the DNS lookup finished.
- connect - Time when the socket successfully connected.
- secureConnect - Time when the socket securely connected.
- upload - Time when the request finished uploading.
- response - Time when the request fired response event.
- end - Time when the response fired end event.
- error - Time when the request fired error event.
- abort - Time when the request fired abort event.
- phases
  - wait - timings.socket - timings.start
  - dns - timings.lookup - timings.socket
  - tcp - timings.connect - timings.lookup
  - tls - timings.secureConnect - timings.connect
  - request - timings.upload - (timings.secureConnect || timings.connect)
  - firstByte - timings.response - timings.upload
  - download - timings.end - timings.response
  - total - (timings.end || timings.error || timings.abort) - timings.start
```

**Comment by determin1st** [comment]
dont do that, those timings are useless. there is only 3 phases with TCP:

- parse input
- request/response
- parse output

you may measure them with `performance.now` yourself but still,
it doesnt really matter if you get 500ms or 600ms at requese/response or measuring the whole api timing.

Timings may be useful with streams (download/upload progress).
Bring some interesting the use-case otherwise.

**Comment by tiagonapoli** [comment]
How can we debug socket issues without it these timings? In a distributed context there may be TCP handshaking, TLS performance optimizations, doesn't it? If all we see is that the request took `X ms` we may think the problem is that the service requested is taking too much, bug this may be connection issues.

Yesterday I got an example - A request took 800ms, we first assumed the service requested was taking too long but using the `got` client and investigating timings we discovered that the connection was takin 650ms, the response itself took 150ms - isn't it important?

**Comment by determin1st** [comment]
Yep, but what will happen if the server does a random sleep (schedule operation) in code before returning the first byte of your response? Will it be considered a connection time or TTFB?

sockets are different here (it's more about udp), so you may probably get those numbers with a lower-level socket apis. If you stick with socket wrapper, then good, it may probably distinguish that, but with http request/response wrapper that's a tricky idea to relay on, i doubt it will improve the usage as it will spawn more questions and bugs. You either have to write every protocol in sockets or put some stubs (zeros) when it's not ruled by sockets.

**Comment by tiagonapoli** [comment]
Well, in that case I will try to implement a wrapper for axios, just found something that might help:
https://blog.risingstack.com/measuring-http-timings-node-js/

**Comment by determin1st** [comment]
You may also use `ping` or similar tools to test the connection..
I still doubt that those timings are very useful..
Maybe "some" of them, like TTFB..

**Comment by aakashthakkar** [comment]
In a large org with multiple apps communication with each other, and not having to do a tcp dump each and every time you run into an upstream timing out, these kind of logs are very helpful. Especially when request npm package is deprecated which provided this out of the box.

**Comment by tiagonapoli** [comment]
@aakashthakkar I made a shim wrapping http so that we can have the timings information even when using axios, you can fork or use it if you want:
https://github.com/tiagonapoli/node-http-timer-shim

**Comment by rupesh1** [comment]
@tiagonapoli thanks for raising this, your package made me think how difficult would it be to build this in to axios - when looking through https://github.com/axios/axios/blob/master/lib/adapters/http.js I noticed the `transport` config option https://github.com/axios/axios/blob/master/lib/adapters/http.js#L163, using this we can integrate https://github.com/szmarczak/http-timer quite easily without any shimming:

```
const https = require('https');
const axios = require('axios');
const timer = require('@szmarczak/http-timer');


const transport = {
    request: function httpsWithTimer(...args) {
        const request = https.request.apply(null, args)
        timer(request);
        return request;
    }
};

// find timings in response.request.timings
const response = await axios('http://httpbin.org/anything', {method: 'get', transport});
return response;
```

From my basic testing it seems to work well, demo: https://runkit.com/rupesh/5f7f8eb64c26c0001cf9d7f0

The same pattern could be used "natively" inside http.js although I don't think its possible with xhr.js so maybe the maintainers would not feel good about adding it.

Your package may still be better for some use cases this is just an alternative approach.

**Comment by Xairoo** [comment]
I am also looking for this. [got ](https://github.com/sindresorhus/got) is just too slow.

**Comment by jasonsaayman** [comment]
Closing this issue due to it's age, stale state or due to a loss of momentum surrounding the issue. Please open a new issue should this problem still be relevant.

**Comment by maxming2333** [comment]
This issue should not be silenced or ignored. Please support this Feature
