### ISSUE TITLE
Authorization header is passed on redirect, redirect adds additional authentication = Two Auth methods provided 

### ISSUE THREAD

**Issue by iyerusad** [axios/axios#2855]
**Describe the bug**
1. GET http://www.saasserviceprovider.com/notpublicapi with header of `Authorization: Bearer mytoken`

2. Redirects to AWS S3 endpoint. _Redirect URL has a query string:_ `X-Amz-Signature=blahblahblah` appended.

3. AWS S3 rejects call because two Authentication:
  - Header: `Authorization bearer token`
  - Query string: `X-Amz-Signature=blahblahblah`

Same call with request api/postman/etc works.

**To Reproduce**
See above - I currently don't have a public endpoint for this.

**Expected behavior**
The request goes through successfully with no transforms required by user. The fix might mean dropping authorization header if host changes for redirect. Or dropping bearer token if `X-Amz-Signature` provided.

**Environment:**
 - Axios Version: Latest -  0.19.2
 - OS: Windows 10 Latest
 - Browser: n/a - node
 - Browser Version: node version v10.18.0
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Can't use `transformRequest` because initial request is a GET:
> ```
> transformRequest: [(data, headers) => {
>     delete headers.common.Authorization
>     return data
> }]
> ```

From axios documentation:
> This is only applicable for request methods 'PUT', 'POST', 'PATCH' and 'DELETE'
----

Neither `transformRequest`, `transformResponse`, `axios.interceptors.request`, `axios.interceptors.response` appears to be able to allow me to inject myself into the process and temporarily remove the Authorization Header when hitting the redirection to AWS S3 - presumably if I could get in after a redirect I could do something to effect of `delete headers.Authorization`.

**"Workaround":**
This is an ugly inefficent steaming POS... but but it "works™".
```
  let retry = false;
  await axios({
    method: 'get',
    url: "http://www.saasserviceprovider.com/notpublicapi",
    headers: {
      'Authorization': "Bearer mytoken",
    }
  })
  .then((r) => {
    //return successful
  })
  .catch ((e) => {
    if (e.request.res.responseUrl.match(/s3.amazonaws.com/)) {
      retry = e.request.res.responseUrl;
    } else {
          //log error
    }
  })

  //Retry
  if (retry) {
    await axios.get(retry)
    .then((r) => {
        //return successful
      }
    })
    .catch((e) => {
       //log error
    })
  }
```

**Comment by chinesedfan** [comment]
@iyerusad Are you facing this problem in Node.js? Please upgrade your local `follow-redirect` to the latest version (axios fixed in #2689 but has not released yet). If the problem is still there, maybe @RubenVerborgh can help you.

**Comment by RubenVerborgh** [comment]
The functionality to drop `Authorization` headers upon redirect is now present in `follow-redirects`, starting version 1.11.0.

I unfortunately did not find any direct advice on this topic in the HTTP specifications, but it seems wise to drop the header when redirecting to a different host.

**Comment by iyerusad** [comment]
Updated package.json:

>     "axios": "^0.19.2",
>     "follow-redirects": "^1.11.0",

Did a `npm i`, validated follow-redirects is upto latest versions.

Attempt axios call again (no workaround), still fails:
```...Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization...```

**Comment by RubenVerborgh** [comment]
> Attempt axios call again (no workaround), still fails:
> `...Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization...`

That's weird, because we're very clearly dropping it now: https://github.com/follow-redirects/follow-redirects/commit/724087d696c0bcd55c13ee0f3560c4558138e422#diff-168726dbe96b3ce427e7fedce31bb0bcR350

Reproducible example welcome at https://github.com/follow-redirects/follow-redirects/issues/new; private code can be sent to me by email.

**Comment by iyerusad** [comment]
Ok I went ahead and did a clean slate.

**Follow http call:** Success
**Axios http call:** Failure (`Only one auth mechanism allowed;...`)

See below for my code. I want to provide actual repo endpoint, but the endpoint I am testing against is a SaaS provider that has some PII stuff and they issue a single hardcoded oauth token for years.....

----
1. `rm -rf node_modules`
2. package.json:
> "axios": "^0.19.2",
> "follow-redirects": "^1.11.0",
3. `npm i`
4. Tested Follow, **SUCCESS**.
```js
const { https } = require('follow-redirects');
function follow() {
  return new Promise((resolve, reject) => {
    const options = {
      method: 'GET',
      hostname: 'www.fakefakefakefake.com',
      port: 443,
      path: '/api/file',
      headers: {
        'Authorization': `Bearer ${process.env.ACCESS_TOKEN}`,
      }
    }

    const call = https.request(options, res => {
      let data = [];
      res.on('data', function(chunk) {
        data.push(chunk);
      }).on('end', function() {
        resolve(Buffer.concat(data))
      });
    })

    call.on('error', error => reject(error))
    call.end()
  })
}

await follow()
.then(r => {
  context.res = {body: r}
})
.catch(e => {
  context.res = {body: e}
})
```
5. Tested Axios, **FAILED**: `Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified`
```js
const axios = require('axios');
await axios({
  method: 'get',
  url: `https://www.fakefakefake.com/api/file`,
  responseType: 'arraybuffer',
  headers: {
    'Authorization': `Bearer ${process.env.ACCESS_TOKEN}`,
  }
})
.then(r => {
  context.res = {body: Buffer.from(r.data, 'binary')}
})
.catch(e => {
  if (e.response.data) {
    context.res = {body: Buffer.from(e.response.data, 'binary')}
  } else {
    context.res = {body: e}
  }
})
```

**Comment by chinesedfan** [comment]
@iyerusad Remember that `axios` has defined `follow-redirects@1.5.10` as a dependency. So it will always use that version, even if another version of `follow-redirects` were specified in your package.json.

If using yarn, you can force the version by [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/). But I don't know how to solve it with npm.

@RubenVerborgh By the way, #2689 has changed the dependency as `^1.10.0`, which mean 1.x if no lockfile is there. Then #2859 is not necessary I think.

**Comment by mikhoq** [comment]
@iyerusad I think that even if you specify a version (eg 1.11.0) of `follow-redirects` in your project, that doesn't force your dependencies (eg `axios`) to use that version. I'm thinking you'd have to pull down the `axios` project, update it to use the latest `follow-redirects`, link `axios` to your project (using `yarn link`), and then see if that works.

**Comment by iyerusad** [comment]
> @iyerusad Remember that `axios` has defined `follow-redirects@1.5.10` as a dependency. So it will always use that version, even if another version of `follow-redirects` were specified in your package.json.

Ahh! Makes sense. Looks like this would be a potentially simple close out once dependency gets updated (which sounds like it is incoming).

**Comment by rognales** [comment]
Any update on the PR?

**Comment by westhom** [comment]
I stumbled on this issue because the security bug is still present with the latest version of axios published to npm. 

But 0.20.0 will fix it, which is still in pre-release.

As a temporary work around I changed the dependency to: `"axios": "git+https://github.com/axios/axios.git#semver:0.20.0-0"`

**Comment by chrisella** [comment]
Any updates on this? I'm experiencing the same issue when using with AWS S3 Presigned URLs as a redirect.

**Comment by chinesedfan** [comment]
@chrisella Check the version of installed follow-redirects, especially when you have a lock file like package-lock.json or yarn.lock.

**Comment by chrisella** [comment]
I've just being going through the package lock double checking bits, is it right that axios 0.20.0 only depends on follow-redirects 1.10.0, I thought follow-redirects only implemented the drop auth header in 1.11.0

**Comment by bbrinx** [comment]
I'm using axios 0.20.0 and set follow-redirects to 1.13.0 in the package.json resolutions. The redirected request still contained the authorization header. 

I also agree with @chrisella, setting follow-redirects to ^0.10.0 is not sufficient, as this fix was implemented in 0.11.0. 

It seems like there is an obvious solution here, what's preventing axios from upgrading to 0.11.0? Feedback would be much appreciated.

**Comment by chinesedfan** [comment]
@chrisella As mentioned in https://github.com/axios/axios/issues/2855#issuecomment-608213279, axios@0.20.0 limits follow-redirect with a caret range, so ^1.10.0 will allow 1.x be installed.

@bbrinx You mistook the version as ^0.10.0. If you still thought you couldn't get the right version of follow-redirect, please provide a sample repository with only axios installed. Thanks

**Comment by jplatte** [comment]
I'm also hitting this, first with axios 0.19, now I upgraded to 0.21 (`follow-redirects` being resolved to 1.13.0 in `yarn.lock`) and it still happens :confused:

**Comment by jplatte** [comment]
Maybe I should mention that this happens in the browser for me, not in node. follow-redirects says that the browser already does redirects (as I was expecting, honestly) and recommends to not use it all for that environment, see [follow-redirects/README.md](https://github.com/follow-redirects/follow-redirects#browser-usage). It doesn't look like axios does this, but I'm not very experienced with the JS ecosystem. Can somebody check this and write a patch that makes axios do this if I am right that it's not currently implemented that way?

**Comment by jplatte** [comment]
So apparently this is just the default behaviour in browsers (see [related StackOverflow question](https://stackoverflow.com/q/49253245)), follow-redirects is not at fault here.

AFAICT, there is no truly useful workaround axios could implement here. I think this issue can just be closed :slightly_frowning_face:

**Comment by eikeon** [comment]
This remains an issue with the latest version of axios and follow-redirects. So far setting maxRedirects to 0 and handling the redirect manually is the only path I’ve found to get around this. It’d be nice to be able to add a `beforeRedirect` Like axios does in the case of proxy to make things work, I believe. Perhaps there’s a way I can already add my own beforeRedirect; if so, I was not able to find it.

**Comment by iyerusad** [comment]
Tested this today using `"axios": "^0.21.1"`, appears to be resolved. Thank you.

**Comment by DemonICOLI** [comment]
Tested on `"axios": "^0.27.2"`, the issue is still present, altought it seems to be browser related as i got the same behaviour using fetch

**Comment by spuyet** [comment]
Indeed this issue seems related the browser implementation. That's really weird that on redirect the browser is able to drop the `Origin` header (to avoid CSRF) but not to drop the `Authorization` header, some sensitive content can be stored in this header (like a JWT) and should not be leaked to an attacker.
