### ISSUE TITLE
Axios instance errors during request if 404 received as response status

### ISSUE THREAD

**Issue by atomboulian** [axios/axios#2862]
**Describe the bug**
When using an axios instance for a GET request, 404 response status causes a request error and rejected promise. Using axios directly for the same request results in no request errors and Promise is successful.

**To Reproduce**

```js
import axios from "axios";

const apiRootUrl = process.env.VUE_APP_API_ROOT_URL;

const camelcaseAPIClient = axios.create({
  baseURL: apiRootUrl,
  headers: { "x-camelcase": 1 }
});

const key = 'foo';
camelcaseAPIClient.get(
        `/api/org-members/${window.localStorage.getItem(
          'orgMemberId'
        )}/preferences/${key}/`
      ).then(response => {
          // move on
        })
        .catch(e => {
          if (e.response.status === 404) {
            // whatever, nbd
          }
        });
```

**Expected behavior**
Network response gives 404 and we continue forward with no errors.

**Environment:**
 - Axios Version: 0.19.2
 - OS: OSX 10.15.2
 - Browser: Chrome
 - Browser Version: 80.0.3987.132
 - Additional Library Versions: Vue 2.6.11

**Additional context/Screenshots**
Output from Axios itself (axios.get):

![Screen Shot 2020-03-30 at 2 00 56 PM](https://user-images.githubusercontent.com/5349946/77961930-7eb67d00-728f-11ea-80ed-ef7baad85330.png)

Output from using axios instance (camelcaseAPIClient.get(...):

![Screen Shot 2020-03-30 at 1 59 41 PM](https://user-images.githubusercontent.com/5349946/77962011-a6a5e080-728f-11ea-99e9-d1bca8b4ebd1.png)

```
GET http://vue.localhost/api/org-members/50411171-c8ab-47af-ba03-8b5831f32025/preferences/itemsColumns/ 404 (Not Found)
Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js?2d83:16)
    at settle (settle.js?467f:18)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:59)
createError	@	createError.js?2d83:16
settle	@	settle.js?467f:18
handleLoad	@	xhr.js?b50d:59
```

**Comment by determin1st** [comment]
So, you expect that response handler will jump into `.then` not into `.catch`, right?

**Comment by atomboulian** [comment]
Correct. You can see the response.status is erroring since response is undefined as well.

**Comment by atomboulian** [comment]
Sorry, I removed the code for the `.then` that was originally running.

**Comment by determin1st** [comment]
I just want to say, that 404 status is considered unsuccessful response, so there may be two options:

- change how promise acts - it may resolve with any result (haskell way) even with error, but then you need to check it anyway

- change backend response, it may be http status 200 ok, but will contain error flag/details.

**Comment by atomboulian** [comment]
My frontend code is going to check the response code and do what is necessary, for sure. I hear you, and it's also important to note that 404's have many uses - for concealment and for communicating that a resource hasn't been set up yet, and should not break the promise's populated response and be a show-stopper.

The particular use case submitted here is to check the user preferences if they have been made and apply them. If there are none (which is a reasonable response), then use the default view in the application.

The problem is that the instance of axios does not behave in the same way as the default axios client is it not? And they are supposed to have identical methods - the only difference is their configs.

At least I have a response object to work with if there is a 404 when using the default client. So that means by default, axios is able to receive a 404 and not reject the promise (for the same exact call).

So how do we make sure that it follows the same behavior when using the instance?

**Comment by matthew-terazo** [comment]
@atomboulian Are you using async / await? I am seeing a similar set of issues when using axios instances. If I batch the requests using Promise.all or don't await the response I get a massive amount of false status codes and garbled response bodies.

**Comment by atomboulian** [comment]
@matthew-terazo I'm using `.catch` and `.then` methods for all the promises.
