### ISSUE TITLE
about index.d.ts

### ISSUE THREAD

**Issue by LiuLHui** [axios/axios#2863]
hey,Administrator  
I want to axios Act as a third party plug-in library for egret,But when you declare Axios,index.d.ts a syntax error has occurred,Is there a problem with my typescript version,like that 

 get<T = any, R = AxiosResponse<T>>(url: string, config?: AxiosRequestConfig): Promise<R>;
  delete<T = any, R = AxiosResponse<T>>(url: string, config?: AxiosRequestConfig): Promise<R>;
  head<T = any, R = AxiosResponse<T>>(url: string, config?: AxiosRequestConfig): Promise<R>;
  options<T = any, R = AxiosResponse<T>>(url: string, config?: AxiosRequestConfig): Promise<R>;
  post<T = any, R = AxiosResponse<T>>(url: string, data?: any, config?: AxiosRequestConfig): Promise<R>;
  put<T = any, R = AxiosResponse<T>>(url: string, data?: any, config?: AxiosRequestConfig): Promise<R>;
  patch<T = any, R = AxiosResponse<T>>(url: string, data?: any, config?: AxiosRequestConfig): Promise<R>;

ts tips is 👍 [ts] 'AxiosResponse' only refers to a type, but is being used as a value here.
please help me  ~

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

Please open a new issue, instead of editing the current one.
