### ISSUE TITLE
`foo.domain.com` should not be proxied if no_proxy has `*.domain.com`

### ISSUE THREAD

**Issue by nabeelamirch** [axios/axios#2864]
**Describe the bug**
foo.domain.com is proxied if no_proxy env has *.domain.com item.

**To Reproduce**
set system env variable:
```
export NO_PROXY=*.domain.com
export no_proxy=*.domain.com
```

```js
axios.get("http://foo.domain.com")
.then(data => console.log(data))
.catch(e => console.log(e))
```

**Expected behavior**
Shouldn't Proxy

**Environment:**
 - Axios Version 0.19.2

**Comment by sovattha** [comment]
Axios seems to use another format for the `no_proxy` string. Try without the star.

`export no_proxy=.domain.com`
