### ISSUE TITLE
Vue.js(Browser) https SSL ignore

### ISSUE THREAD

**Issue by ljlm0402** [axios/axios#2868]
**Describe the issue**
How to ignore https SSL using axios in vue.js

**Example Code**
Code snippet to illustrate your question

```js
import axios from 'axios'
import https from 'https'

axios.create({
  baseURL: (function() {
    return 'https://...'
  })(),
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Content-Type': 'application/json;charset=UTF-8'
  },
   httpsAgent: new https.Agent({
    rejectUnauthorized: false
  })
})
```

**Expected behavior, if applicable**
Browser --> Net::ERR_CERT_INVALID

**Environment:**
 - Axios Version [0.19.2]
 - OS: [Windows10]
 - Browser [Chrome, IE11, Edge]
 - Browser Version [?]
 - Additional Library Versions [Vue 2.6.11]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
Don't think you can use `httpsAgent` with Vue.js, unless you are in Node.js server side.
