### ISSUE TITLE
Send 20 requests at the same time in safari but backend only received 2 requests

### ISSUE THREAD

**Issue by TomScavo** [axios/axios#2869]
**Describe the bug**
Twenty requests were sent simultaneously in safari, but only two were received in the back end

index.html
```js
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <title>Document</title>
</head>
<body>
  <script>
    for(let i = 0; i < 20; i++) {
      console.log('send request')
      axios.get('/app');
    }
  </script>
</body>
</html>
```
app.js
```js
const express = require('express')
const app = express()
const port = 5500

app.get('/app', (req, res) => {
  console.log('request');
  res.json({});
})

app.listen(port, '127.0.0.1', () => console.log(`Example app listening at http://127.0.0.1:${port}`));
```

**Expected behavior**
send 20 requests

**Environment:**
 - Browser Safari
 - Browser Version 13.0.5

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by TomScavo** [comment]
![f242083a5dec42e393989f9377a7d302_99d724dd9e713d976f3970862407c234](https://user-images.githubusercontent.com/29599601/78246343-930eaa00-751b-11ea-9d42-71b869d94dbd.jpg)
![popo_2020-04-02  19-52-02](https://user-images.githubusercontent.com/29599601/78246360-986bf480-751b-11ea-98cc-9f620b0e4ace.jpg)

**Comment by chinesedfan** [comment]
axios is a client, and you have got the right 20 logs in front end. Please check your network/server and remind me to reopen the issue if there is really something wrong in axios.
