### ISSUE TITLE
Installing axios package is causing application to break in winston start

### ISSUE THREAD

**Issue by gpradeepjain** [axios/axios#2870]
I have a node application.

Node v: v10.11.0

We use winston and winston-elasticsearch. Code work fine. As soon as i install axios(0.19.2) package, it starts to break throwing out error. I am clue less as to why the error is thrown.

```
transports.push.apply(transports, [new _winstonElasticsearch2.default({
                                                   ^

TypeError: _winstonElasticsearch2.default is not a constructor
```

**Comment by chinesedfan** [comment]
Better to open an issue to winston and winston-elasticsearch.
