### ISSUE TITLE
response.config.url - different behaviour in different browsers

### ISSUE THREAD

**Issue by pravdinalex** [axios/axios#2873]
**Describe the bug**
We have baseURL set when axios instance created. 
At interceptor, <interceptor argument>.response.config.url contains baseURL in Safari (and older versions of Chrome) and not contains baseURL in current Chrome / Firefox.

**To Reproduce**

```js
const myAxios = axios.create({
    baseURL: 'https://speech-box/api',
    withCredentials: true,
    headers: {
        'Content-Type': 'application/json'
    }
});

function onErrorInterceptor(error) {
	...
	if (error.response) {
		console.warn(error.response.config);
		...
	} 
	...
}

myAxios.interceptors.response.use(
    response => response,
    onErrorInterceptor
);



```

**Expected behavior**
Url should always contain or should never contain baseUrl: behaviour shouldn't differ in browsers.

**Environment:**
 - Axios Version: 0.19.2
 - OS: windows 8.1, macOS 10.15
 - Browser: Chrome 80, Safari 13.1, Firefox 74

**Additional context/Screenshots**

firefox / windows: no baseURL in url
![image](https://user-images.githubusercontent.com/2210640/78291138-8c892e00-752d-11ea-80d0-71a499f4cce0.png)

chrome / windows: no baseURL in url
![image](https://user-images.githubusercontent.com/2210640/78292003-08d04100-752f-11ea-89e9-4f126e208b80.png)

chrome / macos: baseURL included
![image](https://user-images.githubusercontent.com/2210640/78294846-b80f1700-7533-11ea-9ff5-3555e104ed30.png)

safari / macos: baseURL included
![image](https://user-images.githubusercontent.com/2210640/78291868-d1619480-752e-11ea-960c-7ef1cdd2ed3f.png)

**Comment by chinesedfan** [comment]
Interesting. Better to provide a full reproducible sample. Hope you or someone else can find the real reason. It requires little debugging in lib/adapters/xhr.js. That's what suggestions I can give now.

**Comment by pravdinalex** [comment]
@jasonsaayman  bot says the task is going to be closed... I think that if error exists it should be fixed. You marked it as "more info needed". You expect me to add some info? What kind of?

**Comment by chinesedfan** [comment]
As I [commented](https://github.com/axios/axios/issues/2873#issuecomment-609043098), a full reproducible sample is expected, thanks.

**Comment by jasonsaayman** [comment]
I agree with @chinesedfan we need a example we can reproduce, thanks.
