### ISSUE TITLE
form post with file attach throws network error

### ISSUE THREAD

**Issue by cullsin** [axios/axios#2875]
**Describe the bug**
File upload is not working and the proble is with formdata. It throws network error.  I am doing with react Native, Android platform.

```js
// Example code here
```
      export const postImage = async state => {  
        
        let formData = new FormData();

        formData.append('image', {
          uri : state.photo.uri,
          type: state.photo.type,
          name : state.photo.fileName
        });

        const config = {
          headers: {
            'Content-Type': 'multipart/form-data',
            Accept: "application/x-www-form-urlencoded",
            'Accept': 'application/json'
          },
        };

        try {
        return $http.post('/image/save', formData, config)
        .then(response => response)
        .catch(error => error)
        } catch(error) {
            console.log(error)
        }
      }

**Expected behavior**
It should upload the file.

**Environment:**
 - Axios Version ^0.19.2
 - Additional Library Versions [React 16.11.0, React Native 0.62.1]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
If it is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by cullsin** [comment]
Hi, 

Sorry to say that, it shows network error which means that the connection with the backend not at all established.  Is it possible to get an actual error message in the react-native to 
debug what axios is trying ?

**Comment by NMahendroo** [comment]
Same issue @cullsin @chinesedfan 

The request isn't even reaching the backend, It is throwing network error. We generally get this error whenever our data format is wrong or there is a network connectivity issue.

React Native Version: 0.62.0
Axios Version: 0.19.2, tried with 0.19 as well but no luck

It is working fine on iOS

But on Android it is giving Network Error whenever I am trying to send Image in Form Data in a Patch Request.
