### ISSUE TITLE
About mergeConfig.js

### ISSUE THREAD

**Issue by l1shu** [axios/axios#2878]
**Describe the bug**

In the file 【axios/lib/core/mergeConfig.js】. the 'url ' has existed in 'valueFromConfig2Keys' and 'defaultToConfig2Keys'

By the way, I think the 'params' shoud exist in 'valueFromConfig2Keys'  BUT NOT IN 'mergeDeepPropertiesKeys'

```js
var valueFromConfig2Keys = ['url', 'method', 'data'];
var mergeDeepPropertiesKeys = ['headers', 'auth', 'proxy', 'params'];
var defaultToConfig2Keys = [
    'baseURL', 'url', 'transformRequest', 'transformResponse', 'paramsSerializer',
    'timeout', 'withCredentials', 'adapter', 'responseType', 'xsrfCookieName',
    'xsrfHeaderName', 'onUploadProgress', 'onDownloadProgress',
    'maxContentLength', 'maxBodyLength', 'validateStatus', 'maxRedirects', 'httpAgent',
    'httpsAgent', 'cancelToken', 'socketPath', 'responseEncoding'
];
```

**Comment by chinesedfan** [comment]
The duplicated `url` should have been fixed in #2844.

And please share your detailed reasons for `params`. It was in `valueFromConfig2Keys`, but lots for users complained in #2170. If considers `params` as part of url, that is reasonable to be inherited.

**Comment by MLuminary** [comment]
Maybe can remove the 'url' from `valueFromConfig2Keys` ?

**Comment by joebowbeer** [comment]
I wonder about the `validateStatus` handling. The doc defines a behavior for `undefined` yet if opts contains an explicit `validateStatus: undefined` entry it will be removed by mergeConfig.

**Comment by jorisvergeer** [comment]
Arrays in the `params` are converted to objects.

**Comment by jasonsaayman** [comment]
See #2844
