### ISSUE TITLE
Is there a way to remove connection: keep-alive from axios?

### ISSUE THREAD

**Issue by krave1986** [axios/axios#2882]
Axios is assigned to Vue.prototype which is directly imported from node_modules like:

import axios from "axios";
import Vue from "vue"
Vue.prototype.axios = axios;

Every time the browser sends a request, connection: keep-alive is available.

Is there a way to remove the header?

**Comment by chinesedfan** [comment]
No, it is in the forbidden header list. See https://xhr.spec.whatwg.org/#the-setrequestheader()-method.
