### ISSUE TITLE
Header "Content-Type" not setting even with "data" set

### ISSUE THREAD

**Issue by EizFeren** [axios/axios#2884]
**Describe the bug**
Axios isn't setting "Content-Type" header on POST request when "data" is set.

**To Reproduce**
Endpoint I'm interesting requires header "Content-Type" with value "application/json", otherwise it responds about empty request body (`'product' is empty` in my case).

I've tested same case with Postman, and it nicely works (correct content type is set).

```js
const
  axios = require(
    "axios"
  );

axios
  .post(
    "someUrl",
    {
      email: "email@domain.com",
      password: "somePassword",
      product: "someProduct"
    }
  )
  .then(
    console.log
  )
  .catch(
    console.error
  );
```

I also set headers directly by `headers` option in request config, but there was no "Content-Type" header on axios request set at all. The result was 422 error with description below.

There is request config description from error log:

```
config: {
    url: 'someUrl',
    method: 'post',
    data: '{"product":"someProduct","email":"email@domain.com","password":"somepassword"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    }
}
```

And there is response data from endpoint:

```
{
  data: { message: "'product' is empty" }
}
```

As I said before, I've tested same request with Postman JSON request body, and it was successfully done.

**Expected behavior**
I'm expecting correct setting of "Content-Type" header with value "application/json".

**Environment:**
 - Axios Version: 0.19.2
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Browser Version: 81
 - Additional Library Versions: NodeJS V13.11.0

**Comment by chinesedfan** [comment]
> I also set headers directly by headers option in request config, but there was no "Content-Type" header on axios request set at all.

I didn't see it in your provided codes. And it should be working. Please give a reproducible example.

**Comment by EizFeren** [comment]
> > I also set headers directly by headers option in request config, but there was no "Content-Type" header on axios request set at all.
> 
> I didn't see it in your provided codes. And it should be working. Please give a reproducible example.

Case with headers has same results

```js
const
  axios = require(
    "axios"
  );

axios
  .post(
    "someUrl",
    {
      email: "email@domain.com",
      password: "somePassword",
      product: "someProduct"
    }, {
      headers: {
        "Content-Type": "application/json"
      }
    }
  )
  .then(
    console.log
  )
  .catch(
    console.error
  );
```

**Comment by chinesedfan** [comment]
Not reproducible. `Content-Type` is there.

**Comment by epinsbv** [comment]
I have the same issue, after upgrading from 0.61.5 to react-native 0.62.2.

**Comment by yasasn86** [comment]
I have the same issue, after upgrading from 0.61.5 to react-native 0.62.2.

**Comment by EizFeren** [comment]
There was my bad, sorry guys, now it works. Problem was in using http `instead` of `https.

Who would have thought... Anyway sorry for troubles, now it's working fine
