### ISSUE TITLE
All method is not recognized when Vue.prototype is used.

### ISSUE THREAD

**Issue by adsonvinicius** [axios/axios#2885]
I will try to explaing what is happening:

I'm using VueJS, and in my index.js I have

_...
Vue.prototype.$http = Axios.create({
    baseURL: 'http://localhost/myapi/',  
    headers: { "Content-Type": "application/json" }
});_

So I'm using **this.$http** variable for all supported methods (in different vue files), however when I tried to do this.$http.all(...) is raised an error saying **all** is undefined. 

Things I've done:

Checked **this** variable (is ok for GET, POST, PUT...)
Inserted _import axios from 'axios';_ on my script and used axios.all (It works fine)

My question is: Why _this.$http.all()_ fails while _axios.all()_ (from import) works fine.

**Comment by Alanscut** [comment]
@adsonvinicius The `create ()` function returns an instance object of `Axios`, and there is no `all` method on the prototype of `Axios`. If you are very interested in this issue, I suggest you can look at the source code.

```javascript
// axios.js
// Create the default instance to be exported
var axios = createInstance(defaults);
axios.create = function create(instanceConfig) {
  return createInstance(mergeConfig(axios.defaults, instanceConfig));
};
// Expose all/spread
axios.all = function all(promises) {
  return Promise.all(promises);
};
```
```javascript
// Axios.js
utils.forEach(['post', 'put', 'patch'], function forEachMethodWithData(method) {
  /*eslint func-names:0*/
  Axios.prototype[method] = function(url, data, config) {
    return this.request(utils.merge(config || {}, {
      method: method,
      url: url,
      data: data
    }));
  };
});
```
