### ISSUE TITLE
'get' request doesn't work with 'data'

### ISSUE THREAD

**Issue by shaimo** [axios/axios#2886]
The following curl works without an issue:
```
curl "https://api.pchain.org/getFullBalance" -d '{"chainId":0,"address":"0xd027aa40af2230d0ca4a0dfa3629084c7c5a5c28"}' -H "Content-Type: application/json"
```
I think the equivalent axios call is:
```  
  const options = {
    method: 'get',    
    url: "https://api.pchain.org/getFullBalance",
    data: {
      'chainId': 0,
      'address': "0xd027aa40af2230d0ca4a0dfa3629084c7c5a5c28"  
    }
  };
  return axios(options).then(result => {
```
I tried many different ways including params, stringifying the data, etc. Nothing seems to work and I'm unable to make this request work. Always getting some error.

**Comment by Alanscut** [comment]
@shaimo This should be a `POST` request, you can try the following code.
```javascript
const options = {
      method: 'POST',    
      url: "https://api.pchain.org/getFullBalance",
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      data: {
        'chainId': 0,
        'address': "0xd027aa40af2230d0ca4a0dfa3629084c7c5a5c28"  
      }
    };

    axios(options)
      .then(function (response) {
        console.log(response);
      })
      .catch(function (error) {
        console.log(error);
      });
```

**Comment by Rolanddoda** [comment]
With `params` it should work:
```js
    const API_URL = "https://reqres.in/api/users";

    const options = {
      method: "get",
      url: API_URL,
      params: {
        delay: 2
      }
    };
    axios(options).then(console.log);
```
So in the end it access this request:
`Request URL: https://reqres.in/api/users?delay=2`

**Comment by shaimo** [comment]
@Alanscut i found out later that ‘post’ works here. But the curl example uses ‘get’, and the dev of the server actually instructed me to use get, so I’m still wondering how to get it working with axios and ‘get’...

**Comment by shaimo** [comment]
@Rolanddoda it doesn’t work with params. I posted a live example that you can try for youself

**Comment by Rolanddoda** [comment]
@shaimo I don't see where the live example is.
However, I made a [JSFiddle](https://jsfiddle.net/hmkxd69g/) so you can clearly see that get request works with params.

**Comment by shaimo** [comment]
@Rolanddoda I think you may be looking at the wrong post. My post above contains a different url that doesn't work with params. Here it is again for you. The curl command I'm trying to run the equivalent of is:
```
curl "https://api.pchain.org/getFullBalance" -d '{"chainId":0,"address":"0xd027aa40af2230d0ca4a0dfa3629084c7c5a5c28"}' -H "Content-Type: application/json"
```

And here is how I'm trying to run it:
```
  const options = {
    method: 'get',    
    url: "https://api.pchain.org/getFullBalance",
    data: {
      'chainId': 0,
      'address': "0xd027aa40af2230d0ca4a0dfa3629084c7c5a5c28"  
    }
  };
  return axios(options).then(result => {
```

Tried also with params but am getting errors from the server either way.

**Comment by Rolanddoda** [comment]
@shaimo as @Alanscut pointed out the BE wants a POST method request and not a GET one.
The issue you created says `'get' request doesn't work with 'data'`. So my response to that issue is that with get request, you have to use `params` instead of `data` in order to work. Of course BE should be configured correctly.

**Comment by shaimo** [comment]
@Rolanddoda the curl uses get and data, not params, and it works, doesn’t it? I know that post happens to work too, but that’s not the point. The point is that get should work with axios too and it simply doesn’t. It doesn’t work with data and it doesn’t work with params.

**Comment by Rolanddoda** [comment]
@shaimo the curl sends a POST request not a GET.

Go here -> https://reqbin.com/curl and test your curl. Observe that it sends a POST request.

To try a GET request try this
```curl
curl -X GET "https://api.pchain.org/getFullBalance" -d '{"chainId":0,"address":"0xd027aa40af2230d0ca4a0dfa3629084c7c5a5c28"}' -H "Content-Type: application/json"
```

and see it fail

**Comment by shaimo** [comment]
@Rolanddoda Thanks - I didn't realize curl changes the default request type according to the other arguments. So 'get' here never worked with data (neither with params) to start with. I will go ahead and close the case. Thanks
