### ISSUE TITLE
The bug about axios operation cookie being scanned out

### ISSUE THREAD

**Issue by zmhweb** [axios/axios#2894]
In addition to modifying the source code, is there any solution that can be packaged without the operation of cookie code？

question

客户端(JavaScript)Cookie 引用
--
严重性:  							 							 								参考
CVSS 分数: 0.0
URL: http://ip/static/js/main.6911f183.js
实体: !function(I){function g(e){if(n[e])return n[e].exports;var t=n[e]={i:e,l:!1,exports:{}};return I[e].... (Page)
风险: 此攻击的最坏情形取决于在客户端所创建的 cookie 的上下文和角色
原因: Cookie 是在客户端创建的
固定值: 除去客户端中的业务逻辑和安全逻辑

code:
`__webpack_require__){
"use strict";eval("\n\nvar utils = __webpack_require__(36);\n\nmodule.exports =
(\n utils.isStandardBrowserEnv() ?\n\n // Standard browser envs support document.cookie\n (function standardBrowserEnv() {\n return {\n write: function write(name, value, expires, 
path, domain, secure) {\n var cookie = [];\n cookie.push(name + '=' + encodeURIComponent(value));\n\n if (utils.isNumber(expires)) {\n
cookie.push('expires=' + new Date(expires).toGMTString());\n }\n\n
if
}\n\n if
(utils.isString(path)) {\n
(utils.isString(domain)) {\n
(secure === true) {\n
cookie.join('; ');\n },\n\n read: function read(name) {\n
document.cookie.match(new RegExp('(^|;\\\\s*)(' + name + ')=([^;]*)'));\n decodeURIComponent(match[3]) : null);\n },\n\n remove: function remove(name) {\n this.write(name, '', Date.now() - 86400000);\n }\n };\n })() :\n\n // Non standard browser env (web workers, react-native) lack needed support.\n (function nonStandardBrowserEnv() {\n return {\n write: function write() {},\n read: function read() { return null; },\n remove: function remove() {}\n };\n })()\n);\n//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf- 8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL25vZGVfbW9kdWxlcy9heGlvcy9saWIvaGVscGVycy9jb29raWVz LmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFhOztBQUViLFlBQVksbUJBQU8sQ0FBQyxFQUFZOztBQUVoQztBQUNBO ztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QU`

I find the function **standardBrowserEnv** is root in axios

![1](https://user-images.githubusercontent.com/16442336/79214936-a99ef480-7e7d-11ea-80e4-f8b55e7fc15a.png)
![2](https://user-images.githubusercontent.com/16442336/79214999-b58ab680-7e7d-11ea-95c6-aa8239271358.png)

**Comment by chinesedfan** [comment]
> In addition to modifying the source code, is there any solution that can be packaged without the operation of cookie code？

The answer is NO. And in fact, I think axios doesn't require cookies.write and cookies.remove.

**Comment by zmhweb** [comment]
> > In addition to modifying the source code, is there any solution that can be packaged without the operation of cookie code？
> 
> The answer is NO. And in fact, I think axios doesn't require cookies.write and cookies.remove.

So to avoid this problem, only to modify the source code?

**Comment by acegank** [comment]
@zmhweb 哈哈哈哈，这问题我也遇到，兄弟你怎么搞的还记得吗
