### ISSUE TITLE
Axios not catching error but rather outputs .then()

### ISSUE THREAD

**Issue by nanaaikinson** [axios/axios#2896]
I am trying to catch errors from the server but it seems axios is not catching it
```
const formData = {
 current_password,
 password,
password_confirmation
}
Axios.put("/api/users/" + mask + "/password", formData)
  .then(response => {
    console.log(response.data); 
  })
  .catch(err => {
    console.log(err.response);
  });
```
The browser console prints "undefined"
Reponse from server is :
    Header Status Code: 422
    Response: {"code":422,"status":"error","data":null,"message":"The current password you entered is incorrect"}

**Comment by aligoren** [comment]
You can `validateStatus` function to handle catch server responses. For example;

```js
async function catchError() {
	axios.get('https://httpbin.org/status/422', {
		validateStatus: function(status) {
			return status < 300
		}
	})
	.then(resp => {
		console.log(resp.data)
	})
	.catch(error => {
		console.log('error', error.response)
	})
}

catchError()
```

**Comment by 209** [comment]
Issue actually for me. 
validateStatus doesn't help.

**Comment by mayank-mittal** [comment]
Actually axios is working fine i.e. If the server responds back with something (it can be undefined or null as well), it can be caught in err.response, but if the server doesn't send anything you'll have to catch the error in err.request

It is descsribed here nicely,
> https://github.com/axios/axios#handling-errors

**E.g. 1** Server responds but with empty body 
```
axios.get('https://httpbin.org/status/422')
	.then((r) => {
		console.log('Success', r.data);
	})
	.catch((e) => {
		console.error('Error', e.response.data); // Prints `Error`
	});
```

**E.g. 2** Server responds but with data in the body 
```
axios.get('https://postman-echo.com/status/422')
	.then((r) => {
		console.log('Success', r.data);
	})
	.catch((e) => {
                console.error('Error', e.response.data); // Prints `Error { status: 400 }`	
	});
```
**E.g. 3** Server doesn't respond
```
axios.get('/https://httpbin.org/status/422') //Mind the initial `/` to make a invalid url
	.then((r) => {
		console.log('Success', r.data);
	})
	.catch((e) => {
		console.error('Error', e.response ? e.response.data : e.code) //Prints `Error ECONNREFUSED`
	});
```

P.S. It depends on the server how is it responding.

**Comment by MohitDeshwal** [comment]
@mayank-mittal don't you think `validateStatus` should work independent of that?
no matter what server responds, if `validateStatus =>returns false`, it should trigger catch. **Any thoughts?**

**Comment by anschwa** [comment]
I'm running into a similar issue, where my `axios.post` call is getting a `502` back from the server and `.catch()` is never called.

```
axios.post('/api/badnews', { id: 42, name: 'foo' })
  .then((response) => {
    console.log('response:', repsonse);
  })
  .catch((error) => {
    console.log('error:', error);
  });

// >>> response: undefined
```

**Comment by abnud1** [comment]
I'm running into a similar issue as @anschwa . the version I'm using is 0.20.0, not only the catch isn't called but also the response is undefined although Network tab shows server response to be 401 with no body
