### ISSUE TITLE
axios upload file and form data, how to use request payload

### ISSUE THREAD

**Issue by LiXunGuan** [axios/axios#2898]
I hope to use `request payload` to request parameters instead of` form data`

```javascript
            const data = new FormData();

            data.append('is_login', true);
            data.append('param', 0);
            data.append('secondParam', 0);
            data.append('file', new Blob(['test payload'], { type: 'text/csv' }));

            axios.post('http://httpbin.org/post', data);
```
![image](https://user-images.githubusercontent.com/7980846/79344433-69fe0880-7f62-11ea-8faf-371e8fbf8c3c.png)
 
- Axios Version [e.g. 0.18.0]
 - OS: [e.g. windows10]
 - Browser [e.g. Chrome,]
 - Browser Version [e.g. 80.0.3987.163]

**Comment by chinesedfan** [comment]
Then use `axios.post(url,{is_login: true})` directly.

**Comment by LiXunGuan** [comment]
Thank you very much for your answer,I want to pass json data at the same time when uploading files
