### ISSUE TITLE
Get download progress using Node.JS

### ISSUE THREAD

**Issue by BlueskyFR** [axios/axios#2899]
**Describe the issue**
I cannot find a way to get download progress using axios on Node.JS:
I am trying to download a zip file or an mp4 file using `responseType: "stream"`, and I cannot find the content-length and/or more generally a way to have a progress of the download.

**Example Code**
Code snippet to illustrate your question

```js
let { data, headers } = await axios({
  url: url,
  method: "GET",
  responseType: "stream",
});
```

**Environment:**
I am using Axios v0.19.2 and Node.JS 13.13.0.

**Comment by aligoren** [comment]
Have you tried this?

```js
const contentLength = headers['content-length'];
```

My script just like that;

```js
const fs = require('fs');
const axios = require('axios').default


async function downloadFile() {
    const { data, headers } = await axios({
        url: "http://ipv4.download.thinkbroadband.com/200MB.zip",
        method: "GET",
        responseType: "stream",
    });

    const contentLength = headers['content-length'];

    console.log(contentLength)

    data.on('data', (chunk) => {
        console.log(chunk)
    })

    data.pipe(fs.createWriteStream('./200MB.zip'))
}

downloadFile()
```

You can handle download progress using **data** event. If you print the output, it should be like that;

```bin
<Buffer eb 04 ae 84 7d 6c 58 3e f2 10 f0 76 c4 ad 77 71 61 b1 0e eb df e6 f2 80 b0 a5 c2 59 71 1a c1 1d 5d 54 92 80 c5 11 81 be 08 2a 50 40 e2 d3 c5 06 85 94 ... 16950 more bytes>
<Buffer aa 98 5d e4 72 51 d1 f9 68 9c 2d 00 5c a7 f2 0f 72 a0 29 34 88 38 44 79 2a 93 33 8f 9f e4 6a a2 c9 03 f1 f8 85 4c b4 fc f9 a5 fa d9 19 76 78 9d 89 6b ... 20222 more bytes>
<Buffer d1 4e ea 7d 95 dd e3 ef f6 63 64 55 5a c9 2b 47 be 51 ac a4 d0 56 05 3a b3 13 45 69 59 42 e7 20 ad 9e 55 4d cb fb e5 cd 36 e4 ce e7 bc 99 84 a5 84 f8 ... 1398 more bytes>
```

**Comment by BlueskyFR** [comment]
Yeah, I did the same but `headers["content-length"]` is not defined for me!

**Comment by aligoren** [comment]
Can you show us your output?

Thanks.

**Comment by BlueskyFR** [comment]
Sure!

Here is my code:
```ts
let { data, headers } = await axios({
          url: http://example.com/myFile.zip,
          method: "GET",
          responseType: "stream",
        });
```
And here is the output of `console.log(headers)`:
```json
{
  server: 'nginx/1.12.1',
  date: 'Thu, 16 Apr 2020 12:34:54 GMT',
  'content-type': 'application/zip',
  'transfer-encoding': 'chunked',
  connection: 'close',
  'x-powered-by': 'Express',
  'access-control-allow-origin': '*',
  'content-disposition': 'myFile.zip'
}
```

**Comment by aligoren** [comment]
I think the express server doesn't return content-length by default for download file.

You can try to set content-length value manually. [#res.set](https://expressjs.com/en/api.html#res.set)

Are you using the [#res.download](https://expressjs.com/en/api.html#res.download) method?

**Comment by BlueskyFR** [comment]
I do not own the Express server unfortunataly.

**Comment by BlueskyFR** [comment]
I do not own the Express server unfortunately.

Is there another way to get the content-length? I though axios was setting it.

**Comment by aligoren** [comment]
Actually I don't know :/

**Comment by capndave** [comment]
The content-length is set by the sender, not (your instance of) Axios. I don't think there's any way to get it if it's not provided by in the response header, and if there's no alternative header with that kind of information.

**Comment by BlueskyFR** [comment]
okay thanks for your answers! However, I feel like we should really add this to the docs for future users.

**Comment by jasonsaayman** [comment]
HI @BlueskyFR,

Could you put in a pull request for this? Please add me as a reviewer.

Thanks

**Comment by dropsonic** [comment]
I have the same issue. The 3rd-party server that I query uses chunked transfer encoding so it doesn't return `content-length` header. Knowing the progress is quite important because the payload with chunked transfer encoding can be extremely large.

**Comment by jasonsaayman** [comment]
This seems to be more an issue on the sender's side rather than that of Axios. If the sender does not return the content-length then Axios cannot report it.
