### ISSUE TITLE
Data limit of axios post method

### ISSUE THREAD

**Issue by liew789** [axios/axios#2900]
I'm using axios in React Native. I need to upload some base64 encoded photos to server (probably around 5 photos, each photo around 3MB) but seems like the process will failed when the files is too large. So far i able to upload up to 2 photos at each time only. Is it possible to make the limitation higher for axios post request?

```js
            axios.request( {
                method: "post", 
                url: my_url, 
                data: qs.stringify({
                    'm':'upload_photos',
                    'all_photo':photo_json
                  })
            })
            .then((responseData) => {
             //something else
             })
```

**Comment by chinesedfan** [comment]
It depends on the server, and axios doesn't limit the body size.
