### ISSUE TITLE
React Native -> Navigator.product returning "undefined" causing cookie errors.

### ISSUE THREAD

**Issue by Quach90** [axios/axios#2902]
**Describe the bug**
I have struggled with an on React Native causing an error that was only there when "Debug" mode was off for RN. I posted on Stackoverflow ([question](https://stackoverflow.com/questions/61235552/react-native-axios-cookie-issue-when-not-running-debug)) without any responses, but the error can be seen below:

`[TypeError: undefined is not an object (evaluating 'document.cookie.match')]`

After digging around, I found the only place that `document.cookie.match` is run in Axios, which is run only when _isStandardBrowserEnv()_ is true. I looked into this function and found that it should not be true when running ReactNative, but the check that is used `navigator.product === 'ReactNative'` is returning undefined for `navigator.product`. Therefore running the code as if it is a _isStandardBrowserEnv()_ and in the end causing the above error. I do not know whether this is an issue with Axios or React Native, but will try to post here.

**To Reproduce**
Is simply added two logs to the library in my React Native project, which then responded with (see comment after log), it is important that the React Native is not in "debug" mode as that works:
```
function isStandardBrowserEnv() {
  console.log("navigator", navigator) // navigator {"userAgent": ""}
  console.log("navigator.product", navigator.product) // navigator.product undefined
  if (typeof navigator !== 'undefined' && (navigator.product === 'ReactNative' ||
                                           navigator.product === 'NativeScript' ||
                                           navigator.product === 'NS')) {
    return false;
  }
  return (
    typeof window !== 'undefined' &&
    typeof document !== 'undefined'
  );
}
```

**Expected behavior**
Would expect that React Native would return false in `function isStandardBrowserEnv()`, which would fix the issue.

**Environment:**
 - Axios Version 0.19.0
 - Additional Library Versions [React Native 0.61.1]

**Comment by jasonsaayman** [comment]
https://github.com/sindresorhus/got

**Comment by jasonsaayman** [comment]
Closing this issue due to it's age, stale state or due to a loss of momentum surrounding the issue. Please open a new issue should this problem still be relevant.
