### ISSUE TITLE
Uploading a File via FormData - Response always empty

### ISSUE THREAD

**Issue by lowbird187** [axios/axios#2904]
**Describe the issue**
Im trying to send a file (selected with an HTML input type=file) to Laravel backend using "FormData". This is not working with all the solutions i could find through google.
I've been thinking about this problem for two days now ... and im going to get crazy.

**Example Code**

My **VUEJS Component** looks like this:

If im using the header (**multipart/form-data**) in my request im getting this response:
if im not using the header in my request the Response is just empty.

```
"<br />
<b>Warning</b>:  Missing boundary in multipart/form-data POST data in <b>Unknown</b> on line <b>0</b><br />
"
```
 ```
 <form @submit.prevent="uploadImage()">
<input type="file" @change="onFileChange"/>
</form>

data: function () {

            return {
                logo: null,
            }
},

onFileChange(e) {
                let files = e.target.files || e.dataTransfer.files;
                if (!files.length)
                    return;
                this.createImage(files[0]);
            },

createImage(file) {
                let reader = new FileReader();
                let me = this;

                reader.onload = (e) => {
                    me.logo= e.target.result;
                };
                reader.readAsDataURL(file);
            },

uploadImage(){

         let formData = new FormData();

         //Using this config in my request, the response gives me the mentioned waring of missing boundary
         const config = {
                    headers:{
                        'Content-Type' : 'multipart/form-data',
                    }
         };

         formData.append('logo', this.logo);
        
         axios.post('/api/user/settings', formData, config).then(response => {
                      console.log(response)
                }).catch(error => {
                      console.log(error)
                })
            },
```

My **Laravel Controller** looks like:

```
Route::post('/user/settings', 'UserSettingsController@update');

public function update(Request $request)
{
        return $request;
}
```

**Expected behavior**
console.log(response) should give me the whole request, as im only returning the request directly. But the Response is always empty. If im not using FormData and only use a normal object with Key/Value pairs, its working as expected.

**Environment:**
 - Axios Version: 0.19.2
 - Laravel 7.6.1
 - Vue 3.10.0
 - OSX with MAMP (localhost and phpmyadmin)
 - Browser [Chrome]
 - Browser Version [80.0.3987.149]
 - Additional Library Versions:
```
  "devDependencies": {
        "axios": "^0.19.2",
        "bootstrap": "^4.0.0",
        "browser-sync": "^2.26.7",
        "browser-sync-webpack-plugin": "^2.2.2",
        "cross-env": "^7.0",
        "datatables.net": "^1.10.20",
        "datatables.net-dt": "^1.10.20",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.13",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.20.1",
        "sass-loader": "^8.0.0",
        "vue": "^2.5.17",
        "vue-router": "^3.1.6",
        "vue-template-compiler": "^2.6.10",
        "vue-wrapped-component": "^1.0.0",
        "vuejs-paginate": "^2.1.0"
    },
    "dependencies": {
        "@fullcalendar/core": "^4.4.0",
        "@fullcalendar/daygrid": "^4.4.0",
        "@fullcalendar/vue": "^4.4.0",
        "@svgdotjs/svg.js": "^3.0.16",
        "admin-lte": "^3.0.4",
        "form-data": "^3.0.0",
        "fs": "0.0.1-security",
        "html2canvas": "^1.0.0-rc.5",
        "jquery": "^3.4.1",
        "moment": "^2.24.0",
        "sweetalert2": "^9.10.12"
    }
```

**Comment by larviz** [comment]
Try to append the file this way:
`formData.append('logo', this.logo, this.logo.name);`

**Comment by Panda33ren** [comment]
> Try to append the file this way:
> `formData.append('logo', this.logo, this.logo.name);`

Having the same issue and the formData.append is not working.

My code:
`
 var formData = new FormData();
formData.append('de_arquivo', this.notificacao.de_arquivo);
formData.append('nu_arrolado', this.arrolado.nu_arrolado);`

**Comment by larviz** [comment]
Hi, 
I have installed  PHP PECL "apfd" package on my server and finally been able to receive PUT with header multipart/form-data.
hope it helps!

**Comment by Panda33ren** [comment]
I checked my code again and saw an error. I was sending the formData variable inside a object. 
Before:
`this.axios.post('path', {formData})`

Now:
`this.axios.post('path', formData)`

**Comment by zhoufanglu** [comment]
> I checked my code again and saw an error. I was sending the formData variable inside a object.
> Before:
> `this.axios.post('path', {formData})`
> 
> Now:
> `this.axios.post('path', formData)`



> I checked my code again and saw an error. I was sending the formData variable inside a object.
> Before:
> `this.axios.post('path', {formData})`
> 
> Now:
> `this.axios.post('path', formData)`

Thank you for helping me!!!

**Comment by Shahzaibmalik55** [comment]
Starting from v0.27.0, Axios supports automatic object serialization to a FormData object if the request Content-Type header is set to multipart/form-data. see the [documentation](https://www.npmjs.com/package/axios#formdata)!

**Comment by TOcvfan** [comment]
I'm also having problems with this and formData set all other data to default and request.files is still empty
