### ISSUE TITLE
Getting api's original error object instead of axios's

### ISSUE THREAD

**Issue by AldeonMoriak** [axios/axios#2906]
**Describe the issue**
I am trying to get the original error message using axios but the response is always axios's which is a general message.
I used interceptors but the same happened and I received axios's error object.

**Example Code**

This is the api's response object
```json
{"IsSuccess":false,"StatusCode":7,"Message":"User has been registered before"}
```

And I receive axios's:
```json
{
  "message": "Request failed with status code 500",
  "name": "Error",
  "fileName": "http://localhost:8080/js/chunk-vendors.js line 508 > eval",
  "lineNumber": 16,
  "columnNumber": 15,
  "stack": "createError@webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15\nsettle@webpack-internal:///./node_modules/axios/lib/core/settle.js:17:12\nhandleLoad@webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:61:13\n",
  "config": {
    "url": "http://*******.***/api/v1/User/Create",
    "method": "post",
    "data": "{\"fullName\":\"aldeonaldeon\",\"email\":\"aldeon@aldj.caljkf\",\"mobile\":\"lkj;adsf;lk\",\"userName\":\"aldeon\",\"password\":\"lk;ajdfs;\"}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
```

**Expected behavior, if applicable**
I wanted to receive the api's message and handle it accordingly.

**Environment:**
 - Axios Version 0.19.2
 - OS: Lubuntu 19.10
 - Browser Firefox
 - Browser Version 75.0
 - Additional Library Versions Vue 2.16.11

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
You may expect to get a response when non-2XX status code returns. Remind that `validateStatus` checks status code first.
