### ISSUE TITLE
Cannot send "auth" and "params" in the same get request

### ISSUE THREAD

**Issue by hajdun** [axios/axios#2908]
**Describe the bug**
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**
```
const PARAMS={ params: { key: value } }
const AUTH ={auth: { username: 'uname', password: 'pass' }}
 const products = await axios.get(PATH, PARAMS, AUTH);
```
responds with 401 unauthorized
```
const products = await axios.get(PATH,  AUTH, PARAMS);
```
does not send params

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
const PARAMS={ params: { key: value } }
const AUTH ={auth: { username: 'uname', password: 'pass' }}
 const products = await axios.get(PATH, PARAMS, AUTH);
```
responds with 401 unauthorized
```js
const products = await axios.get(PATH,  AUTH, PARAMS);
```
does not send params
**Expected behavior**

**Environment:**
 - Axios Version [ 0.19.2]
 - OS: [Ubuntu 18.04.4 LTS]
 - Browser [all] (Checked with Firefox and Chrome latest)
 - Additional Library Versions [React 16.13.1,]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
Please either clarify documentation or fix the issue.
I need params and auth in the same request.
Thank you!

**Comment by chinesedfan** [comment]
Please read documents carefully.

```
const products = await axios.get(PATH, {...PARAMS, ...AUTH});
```
