### ISSUE TITLE
400 respoonse invoking .then() instead of .catch()!!!!!!! 

### ISSUE THREAD

**Issue by Maheswae** [axios/axios#2909]
**Describe the issue**
I am invoking a API using post method which is returing 400 bad request through post man. But when I am calling through axios, it's invoking .then() instead of .catch(). I hope this behaviour is wrong or I am missing some configuiration stuff which is forcefully invoking .then() instead of .catch(). Is there any configuration regarding that?

**Example Code**
Code snippet to illustrate your question

```js
// Example code here
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
