### ISSUE TITLE
Streaming is actually NOT provided despite being in documentation

### ISSUE THREAD

**Issue by janswist** [axios/axios#2910]
[This](https://github.com/axios/axios#axiosconfig) section is wrong. Not only type is not supported, but also stream function is not recognized. Can I ask for example that actually shows it's working? If not it shouldn't be in docs because it's misleading.

![image](https://user-images.githubusercontent.com/5583954/79699624-f1b08380-8290-11ea-8fe0-66e518f6bc8b.png)

Also, bit.ly link is blocked by CORS.
![image](https://user-images.githubusercontent.com/5583954/79699699-5bc92880-8291-11ea-949b-56c6152e9daf.png)

```
axios({
  method: 'get',
  url: 'http://bit.ly/2mTM3nY',
  responseType: 'stream'
})
.then(function (response) {
  response.data.pipe(fs.createWriteStream('ada_lovelace.jpg'))
});
```

**Comment by akx** [comment]
That example works when using Axios in Node.js, not in the browser.

Browsers don't have `fs.createWriteStream` either.

**Comment by jasonsaayman** [comment]
@janswist as @akx and @chinesedfan have stated this does not work within the browser, I will update the docs and reference this on the pull request.

**Comment by chinesedfan** [comment]
@jasonsaayman Better to leave it open util your pull request has been merged.

**Comment by jasonsaayman** [comment]
In pull request reference #2928
