### ISSUE TITLE
await in sequential functions does not work, requests are received simultaneously in a mess

### ISSUE THREAD

**Issue by novikovrabota433** [axios/axios#2913]
How to use the serial call function on different urls? I can’t understand how to properly scrap 2 sites, because it returns data in a mess.

I create 2 functions in which I specify a different url, but the result is output to the console at the same time.

const s1 = async () => {
  const html = await axios.get(url_benzinga);

  const $ = await cheerio.load(html.data);

const s2 = async () => {
  const html = await axios.get(url_benzinga1);

  const $ = await cheerio.load(html.data);
![Безымянный](https://user-images.githubusercontent.com/32838534/79750151-20723c80-8319-11ea-99a0-860a24893533.png)

How to make the first function wait so that until it is fully executed 2 is not executed in parallel.

Completed not in parts, but in full. Until all the code in the first function is fully implemented, the second did not start work

**Comment by chinesedfan** [comment]
Your sample codes are not complete. And please follow the issue template.

**Comment by novikovrabota433** [comment]
https://jsfiddle.net/novikov433/ceks2af3/3/
I get promises through .spread, then I want to save the data to another variable for parsing via cheerio. When using const html = await axios.get (url) everything works fine and cheerio returns everything as needed, but if I want to move the data outside the function to the beginning of the file, promise is added and cheerio does not read the information.

I need to do sequential actions via return in order to save data for further processing through the translation module @ vitalets / google-translate-api, if used without axios.all -> .spread just const html = await axios.get (url) then all the data shuffle and async / await not working.


When trying to save data - url11, url12, url13 in the file, [object Object] appears and casting toString () will not help.

**Comment by chinesedfan** [comment]
axios.all/spread are deprecated. See https://github.com/axios/axios#concurrency-deprecated.
