### ISSUE TITLE
onDownloadProgress function event can't get loaded and total

### ISSUE THREAD

**Issue by ZHONGJIAFENG7** [axios/axios#2915]
```js
axios({
    method: 'get',
    url: 'xxxx'
    onDownloadProgress: (progressEvent) => {
        var percentCompleted = Math.round((progressEvent.loaded * 100) / progressEvent.total);
    },
})
```
I use a link to download，and response is blob data，the response header is following:

![image](https://user-images.githubusercontent.com/23742908/79839664-6bf31c00-83e7-11ea-91a5-53328800af63.png)

But I got undefine, here is the consloe info:

![image](https://user-images.githubusercontent.com/23742908/79835797-e5880b80-83e1-11ea-9181-c949d71473c2.png)

**Environment:**
 - Axios Version: 0.18.0
 - OS: OSX 10.13.4
 - Browser: Chrome
 - Browser Version: 79
 - Additional Library Versions: Vue 2.6.10

**Comment by chinesedfan** [comment]
It depends on whether the browser is supported and the server returns required headers. Closed in favor of #1591.

**Comment by BeerHope** [comment]
Have you resolved the problem？

**Comment by roy2651** [comment]
Have you resolved the problem？

**Comment by manuel-delaiglesia** [comment]
No they have not

**Comment by jinjunss** [comment]
may be you can close your mock

**Comment by zhubixia** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
