### ISSUE TITLE
Hi change  my request url on runtime, how to fix this bug.

### ISSUE THREAD

**Issue by abdullahcel1k** [axios/axios#2916]
For example my url : 

> http://www.myapi.com/api/v1/question/getQuestions

but change my url : 

>  http://www.myapi.com/api/v1/question%E2%80%8B/getQuestions

after that return not found req error.
why change my url and how to fix this url ?

**Comment by jasonsaayman** [comment]
The URL is being encoded to URL encoding are you copying this URL from somewhere as this is normally how this occurs? Try copying the URL into a plain text editor before copying it into the code you are working on.
