### ISSUE TITLE
The adapter's config.url of axios 0.19.1 and above dosn't include baseURL, but axios 0.19.0 and below includes baseURL.

### ISSUE THREAD

**Issue by yujihu** [axios/axios#2917]
**Describe the bug**
The adapter's config.url of axios 0.19.1 and above dosn't include baseURL, but axios 0.19.0 and below includes baseURL.

**To Reproduce**
I provide an example of running online: [https://jsfiddle.net/r70u4wfs/](https://jsfiddle.net/r70u4wfs/), just change the axios's version, see the log of adapter config.
```js
const newAxios = axios.create({
  baseURL: 'https://httpbin.org/get'
})

newAxios({
	url: '/test',
  adapter: config => {
  	console.log(config)
    return new Promise((resolve, reject) => {
    	resolve({data: {}})
    })
  }
}).then(res => {
	// console.log(res)
}).catch(err => {
	console.log(err)
})
```

**Expected behavior**
Different versions should have the same performance. Version 0.19.1 and above should also contain baseURL.

**Environment:**
 - Axios Version [0.19.1+]
 - OS: [windows 10]
 - Browser [Chrome]
 - Browser Version [80.0.3987.163]

**Additional context/Screenshots**
Version 0.19.1 and above: dosn't include baseURL
![image](https://user-images.githubusercontent.com/11382807/79948279-25b0c200-84a6-11ea-8a73-851897dcd6c6.png)

Version 0.19.0 and below:  includes baseURL
![image](https://user-images.githubusercontent.com/11382807/79948337-411bcd00-84a6-11ea-82d2-ddba8b614610.png)

**Comment by jasonsaayman** [comment]
Hi JihuYu,

I am looking into it, I have validated that this does happen. Interesting to note is that if one is to do it like this:

```js
const axios = require("axios");

const instance = axios({
    baseURL: "https://httpbin.org"
});

instance.get("/get")
    .then((response) => {
        console.log("axios@0.19.1: ", response.data);
    });
```

You do end up with the call working successfully. I will look into the issue further and let you know.

**Comment by chinesedfan** [comment]
See discussions in #2751.

**Comment by yujihu** [comment]
> Hi JihuYu,
> 
> I am looking into it, I have validated that this does happen. Interesting to note is that if one is to do it like this:
> 
> 
> const axios = require("axios");
> 
> const instance = axios({
>     baseURL: "https://httpbin.org"
> });
> 
> instance.get("/get")
>     .then((response) => {
>         console.log("axios@0.19.1: ", response.data);
>     });
> You do end up with the call working successfully. I will look into the issue further and let you know.

I think it should be consistent because many adapters rely on `config.url`. I hope you find out the reason as soon as possible.

**Comment by jasonsaayman** [comment]
Hi @yujihu,

Did you have a look at #2751? I think that might help as there is a lengthy discussion over there about this and similar issues. Please have a look and comment over on that issue if you have additional comments.

Thanks

**Comment by jasonsaayman** [comment]
@yujihu I am going to close this for now so that we can rather maintain the discussion over on #2751
