### ISSUE TITLE
Cancel error should be isAxiosError

### ISSUE THREAD

**Issue by dreyks** [axios/axios#2918]
**Is your feature request related to a problem? Please describe.**
I'm usually filtering axios errors on a high level with checking if it's `isAxiosError`. However, this check returns false for when a request is canceled via a CancelToken. 

This forces me to check for `axios.isCancel` first, which leaks logic outside of a "axios check" code region
```js
if (e.isAxiosError || axios.isCancel(e)) { // yes, this is axios
  handleAxiosError(e)
} else { // nope, other handlers
}
```

**Describe the solution you'd like**
Would be cool if Cancel would be enhanced in the same way as the generic error

**Comment by jasonsaayman** [comment]
This should be fixed please check v1 beta
