### ISSUE TITLE
The return value of the request is a string of pure numbers. The received return value will round the last three digits.

### ISSUE THREAD

**Issue by XiaoJianPeng** [axios/axios#2919]
The return value of the request is a string of pure numbers. The received return value will round the last three digits.

I use the postman call to return normal results

The test code is as follows:
### java server code 
```
@PostMapping("/test")
  @ApiRange(route=RouteConst.WORK, remark = "发布群公告")
  public String publish1(@RequestBody @Valid SysGroupNoticeAddParam param){
    String id = "6658699678403662022";
    return id;
  }
```
### js code
const axios = require('axios');

const instance = axios.create({
  timeout: 10000,
})
```

const post = async (url, data, config) =>{
  const result = await instance.post(url, data, {
  headers: config
  })
  return result
}

const publishNotice = async () => {
 let result = await post(url, {
   conversationId: "123213213224141231421",
   content: "budiasdia"
 }, header_config)
 console.log(result.data) // The output here is: 6658699678403662000
}
```

**Comment by XiaoJianPeng** [comment]
The version number is 0.19.2

**Comment by jacobpgn** [comment]
axios parses responses using `JSON.parse` [by default](https://github.com/axios/axios/blob/16b5718954d88fbefe17f0b91101d742b63209c7/lib/defaults.js#L57-L65).

When the whole given value is a string containing a number, `JSON.parse` tries to make the value a `Number`:
```js
> const response = "6658699678403662022"
> JSON.parse(response)
6658699678403662000
```
and [JS doesn't like very large numbers](https://stackoverflow.com/questions/1379934/large-numbers-erroneously-rounded-in-javascript)! 

Maybe it'll help you if you prevent the default `transformResponse` function from being used? e.g.

```js
await instance.post(url, data, {
  headers: config,
  transformResponse: null
})
```

**Comment by XiaoJianPeng** [comment]
[It solves my problem.](https://github.com/axios/axios/issues/2919#issuecomment-618312833)
Thank you so much
