### ISSUE TITLE
(only ios safari) Axios only send options while add Authorization at (interceptors/request/config)

### ISSUE THREAD

**Issue by stewForAni** [axios/axios#2920]
only happen on ios safari
ios: 13.4
axios: 0.19.2

when i do post api ,only send options but no post ;
But it works when i delete (config.headers.Authorization = VueCookies.get('token')) at (interceptors/request/config)

**Comment by jasonsaayman** [comment]
Hi Stew,

Please can you use the issue templates provided when creating an issue, as well as provide some code examples?

**Comment by stewForAni** [comment]
> Hi Stew,
> 
> Please can you use the issue templates provided when creating an issue, as well as provide some code examples?

Hi,jasonsaayman. When i do post api,i only found potions but no post and can not get the response.
And it works when i delete "Authorization" setting.  The code like these:
`const Axios = axios.create({
  baseURL: Common.base_url,
  timeout: 5000,
  responseType: 'json',
})

Axios.interceptors.request.use(
  config => {

      if (config.method === 'post') {
      config.data = qs.stringify(config.data)
      }

    // if (VueCookies.isKey("token")) {
    //   config.headers.Authorization = VueCookies.get('token')
    // }

    return config
  },
  error => {
    return Promise.reject(error.data.error.message)
  }
)`

**Comment by chinesedfan** [comment]
We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Search for OPTIONS.

**Comment by stewForAni** [comment]
> We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Search for OPTIONS.

这是axios和safari兼容性问题，不找axios提问还能找谁？而且这个问题确实存在，只发生在ios的safari。你不帮忙解答就算了，还让我这个小白去 stackoverflow浪费时间嘛？我的chinese哥

**Comment by jasonsaayman** [comment]
Hi Stew,

This seems to be similar to #2751, can you have a look? If so then there is a long discussion going on in that issue about how to solve this problem. Also try moving back to 0.19.0 and see if what you are trying works with 0.19.0.

Thanks

**Comment by jasonsaayman** [comment]
@stewForAni I am going to close for now as I think it will be more appropriate to work on #2571 and keep all comments aggregated over there.

**Comment by stewForAni** [comment]
> Hi Stew,
> 
> This seems to be similar to #2751, can you have a look? If so then there is a long discussion going on in that issue about how to solve this problem. Also try moving back to 0.19.0 and see if what you are trying works with 0.19.0.
> 
> Thanks

sorry，0.19.0 also not work

**Comment by stewForAni** [comment]
> @stewForAni I am going to close for now as I think it will be more appropriate to work on #2571 and keep all comments aggregated over there.

cool man, 2751 or 2571 ???

**Comment by jasonsaayman** [comment]
Sorry man slipped up while typing #2751

**Comment by stewForAni** [comment]
> Sorry man slipped up while typing #2751

cool man, Can we chat with some app? Im from China. I will send you some image to show the bug.
