### ISSUE TITLE
POST returns empty data but status 200

### ISSUE THREAD

**Issue by krakzk** [axios/axios#2924]
I am facing the issue when i try a post call. I generate a token using O2Authentication and then use the token to post a request using my RN app. This returns 200 with all info but the data is empty. Checked server side and it shows that the complete response was sent back from server. Also the response is complete and success while trying with postman.
The whole action occurs in one flow in componentDidMount
Used with RN-0.59.3
O2Auth was with react-native-ms-adal

**Comment by jasonsaayman** [comment]
Please can you fill out the issue template to log this issues also if possible can you provider me with a runkit example?

**Comment by jasonsaayman** [comment]
Closed and locked due to inactivity
