### ISSUE TITLE
Check 'Content-Encoding' response header in unit test

### ISSUE THREAD

**Issue by kingsimba** [axios/axios#2925]
I use chai-http to check a response:

```typescript
    it('transfers as GZIP stream', async () => {
        const res = await request.get('https://...');
        expect(res).to.have.status(200);
        expect(res).have.header('X-Content-Encoding', 'gzip');
        expect(res.data.results).exist.
    });
```
I know the data is decompressed and hence the header is removed.
But can I suggest to leave some traces like this?

```typescript
        // leave some trace of the previous content-encoding
        res.headers['axios-content-encoding'] = res.headers['content-encoding'];
        
        // remove the content-encoding in order to not confuse downstream operations
        delete res.headers['content-encoding'];
```

**Comment by jasonsaayman** [comment]
@kingsimba as stated in the pull request I would not see this as being useful to most people. I also struggle to see how it would be useful.

**Comment by kingsimba** [comment]
> @kingsimba as stated in the pull request I would not see this as being useful to most people. I also struggle to see how it would be useful.

Can you give suggestions about how to do the following test?
I want to make sure the server really have data compressed.

```TypeScript
expect(res).have.header('Content-Encoding', 'gzip'); // failed because axios removed it
```

**Comment by jasonsaayman** [comment]
I think you could try using an interceptor to change the way this works.
