### ISSUE TITLE
Quality factor for wildcard content type in default Accept header

### ISSUE THREAD

**Issue by jaapromijn** [axios/axios#2927]
The default `Accept` header is as follows:

``` js
defaults.headers = {
  common: {
    'Accept': 'application/json, text/plain, */*'
  }
};
```

If a server endpoint is eager to return `text/html` over `application/json`, using a wildcard without quality factor will result in a html response. I think the wildcard is meant to be a fallback instead, and so it should have a lower quality factor as follows. If this is not the case, ignore this proposal.

``` js
defaults.headers = {
  common: {
    'Accept': 'application/json, text/plain, */*;q=0.9'
  }
};
```

https://github.com/axios/axios/compare/master...jaapromijn:patch-1

**Comment by jasonsaayman** [comment]
A server endpoint should never be returning two different `Content-Type` encodings at the same time on the same URI. Please refer to the docs on this at [MDN - Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) and you will see that there should only be one encoding in the return.

**Comment by jaapromijn** [comment]
Thank you for your response and time.

I don't think you understood my description of the issue. I am not talking about _mixed_ content types, but about content negotiation.

If you look at the docs of the [`Accept`-header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept), it states:
```
*/*
Any MIME type
```
Meaning that your user agent indicates it will accept any MIME type.

```
defaults.headers = {
  common: {
    'Accept': 'application/json, text/plain, */*'
  }
};
```
And because there isn't any factor weighting in de defaults of Axios, it means that the wildcard has equal weight to `application/json`.



```
;q= (q-factor weighting)
Any value used is placed in an order of preference expressed using relative quality value called the weight.
```

Endpoints can serve different mime types on the same URI, that's the whole point of content negotiation. And if this wasn't true it would only be more reason to not use multiple (equally weighted) types.

**Comment by jasonsaayman** [comment]
Hi thanks this makes more sense, have a look at #2623 you should be able to override the defaults when instantiating a instance of Axios. For now I would suggest doing that, I think the defaults should be removed in the future as it does not make sense for Axios to be this opinionated about things.

**Comment by jaapromijn** [comment]
Thanks again for your time, and your solution. While not optimal, it's something we can work with. 👍

**Comment by jasonsaayman** [comment]
No worries, as soon as the pull request that resolves this comes out you should be able to create a better solution.
