### ISSUE TITLE
When the axios response data is in the adapter, the 19-bit data is complemented

### ISSUE THREAD

**Issue by HuiShaoWei** [axios/axios#2931]
Hello, I need help. When I request response data, there are 19 whole lines of data, for example, 1255045690950746112 is converted to 1255045690950746000 after executing 50 lines in axios / lib / adapters / xhr.js

I do n’t know why uploading pictures on Github is unsuccessful, so I can only use text description method, sorry

**Comment by HuiShaoWei** [comment]
I need help, friends

**Comment by jasonsaayman** [comment]
Please check out #2919 this explains the issue.

**Comment by HuiShaoWei** [comment]
I found a better solution, share as follows:
 /**
     * 订单id
     */
    @ApiModelProperty(value = "订单id(唯一id)",dataType = "Long")
    @Id
    @JsonSerialize(using= ToStringSerializer.class)
    private Long orderId;
