### ISSUE TITLE
Axios, form-data, POST request, status code 400

### ISSUE THREAD

**Issue by Alex-Connect** [axios/axios#2932]
Trying to upload an image from React Native to a server with Axios. I've attached a screenshot of both the code that I'm using and the Postman form-data view so you can see what the server expects to receive (uploading via postman works perfectly so server is all good). Every time I try to upload an image I get either a status code 400 (promise rejection) error or a network error.

Here is what the image prop contains - it is directly coming from react-native-image-crop-picker :
{"cropRect": {"height": 399, "width": 221, "x": 39, "y": 0}, "height": 1949, "mime": "image/jpeg", "modificationDate": "1588072959000", "path": "file:///storage/emulated/0/Pictures/bf28f71b-86e9-485d-ae27-d2edcd07d78d.jpg", "size": 495417, "width": 1080}

Any help would be amazing! I've been stuck on this for days now and I haven't found an existing support thread with this issue, apologies though if I have managed to duplicate a query.
![1](https://user-images.githubusercontent.com/45561476/80496189-c00a7d00-8960-11ea-8943-a9822b0678dc.png)
![2](https://user-images.githubusercontent.com/45561476/80496190-c13baa00-8960-11ea-8008-c53134cbd149.png)

**Comment by jasonsaayman** [comment]
Hi @Alex-Connect,

I think you need to add an `await` before `axios` so `await axios`. It also seems you are not doing anything with the response? Either way this is more a support issue than an Axios issues.

Thanks

**Comment by victorwpbastos** [comment]
I'm having the exact same problem.

**Comment by victorwpbastos** [comment]
Solution: https://github.com/facebook/react-native/issues/28551#issuecomment-624347067
