### ISSUE TITLE
Socket hang up on long requests

### ISSUE THREAD

**Issue by hnafar** [axios/axios#2936]
**Describe the bug**

When  sending a request from inside a docker container to an endpoint that takes a long time before responding (more than 10 muinutes), I get the following error:

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at Socket.socketOnEnd (_http_client.js:435:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
 ...
```

setting the timeout on axios does not help. This does not happen when I run the client code directly on  my machine, only when it is run inside a docker container.

**To Reproduce**

create a node server that takes a long time to respond:

```javascript
const http = require('http')

const server = http.createServer(function (request, response) {
    request.on('close ', () => {
        console.log('request closed');
    });

    if (request.method == 'POST') {
        console.log('POST')
        var body = ''
        request.on('data', function (data) {
            body += data
            console.log('Partial body: ' + body)
        })

        request.on('end', function () {
            setTimeout(() => {
                console.log('sending respones now');
                response.writeHead(200, { 'Content-Type': 'text/html' })
                response.end('post received')
            }, 1000 * 60 * 10);
            console.log('Body: ' + body);
        });
    } else {
        console.log('GET');
        response.writeHead(200, { 'Content-Type': 'text/plain' });
        response.end('Ok');
    }
})

const port = 5000
const host = '10.0.0.50'
server.setTimeout(1000 * 60 * 30);
server.listen(port, host)
console.log(`Listening at http://${host}:${port}`)
```

Create a node script like below and run it inside a docker container, sending a request to server created above:

```
let axios = require('axios');

async function run () {

    const axiosInstance = axios.create({
        baseURL: 'http://livedoc.transmissionmedia.ca/',
        headers: { 'X-Custom-Header': 'foobar' },
        // `timeout` specifies the number of milliseconds before the request times out.
        // If the request takes longer than `timeout`, the request will be aborted.
        timeout: (1000 * 60 * 30)

        // `maxContentLength` defines the max size of the http response content allowed
        // maxContentLength: 2000,
        // see https://kapeli.com/cheat_sheets/Axios.docset/Contents/Resources/Documents/index for all axiosoptions.
    });
    axiosInstance.defaults.timeout = (1000 * 60 * 30);

    console.log(`${new Date().toISOString()} - start`);
    const resp = await axiosInstance.post(`http://10.0.0.50:5000/weatherforecast`);
    console.log(`${new Date().toISOString()} - end`);
}

// do something when app is closing
process.on('exit', () => { console.log('Process - exit'); });
process.on('SIGINT', () => { console.log('Process - SIGINT'); });
process.on('SIGUSR1', () => { console.log('Process - SIGUSR1'); });
process.on('SIGUSR2', () => { console.log('Process - SIGUSR2'); });
process.on('uncaughtException', () => { console.log('Process - uncaughtException'); });

run()
    .then(() => {  console.error('Succeeded!');  process.exit(0); })
    .catch(err => { console.error('Failed!'); console.error(err); process.exit(-1); });
```

**Expected behavior**

Wait for the response and not throw an error.

**Environment:**
 - Axios Version [e.g. 0.19.2]
 - Docker desktop for windows, node:10 base image

**Comment by airtonix** [comment]
Not the Author or a maintainer, but some things that will get asked are:

- version of node you used on your windows workstation
- did you use powershell or cmd.exe? 
- what's the output of `env` from powershell or conversly `dir env:` (you can clean it of sensitive stuff)
- can you provide a reproduction repository (like how I do here for a vscode bug: https://github.com/airtonix/vscode-bug-with-remote-containers-and-environment-variables)
  - ideally the repro repo should use npm scripts that work on windows and within the docker container (so use things like npm-run-all, onchange, cross-var, cross-env)

**Comment by padaliya-Kapil** [comment]
I'm also getting same issue .
To reproduce 
`
router.get('/github/:username', async (req, res) => {
  try {
    const fetchData = async () => {
      const { data } = await axios.get(
        `      https://api.github.com/users/${
          req.params.username
        }/repos?client_id=4${config.get(
          'gitHubClientId'
        )}&client_secret=${config.get(
          'gitHubSecret'
        )}&perpage=5&sort=created:asc
`
      )
      res.json(data)
    }
    fetchData()
  } catch (error) {
    console.log(error.message)
    res.status(500).send('Server Error')
  }
})
export default router
`
node -v 
v15.0.1

npm version

{
  devconnector: '1.0.0',
  npm: '6.14.8',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '88',
  napi: '7',
  nghttp2: '1.41.0',
  node: '15.0.1',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.6.395.17-node.15',
  zlib: '1.2.11'
}

Whenever I pass 'username' that does not exist on github it is throwing **Error: socket hang up**
It works fine with correct username

**Comment by JoorgeFerrari** [comment]
Watching issue, looking for fix

**Comment by cazuzaneto** [comment]
I recently got this `Socket hang up` problem. I researched for a few days until I found a solution that worked for me. My scenario was different from the one presented above, however, maybe this can help.

It worked for me to add the `httpsAgent` property with `keepAlive: true` in creating the http client. Here's an example of what it might look like:
```
axios.create({
            httpsAgent: new https.Agent({keepAlive: true}),
        });
```
This property is responsible for managing the sockets for client-side http connections. The justification for using this property can be found [here](https://nodejs.org/api/http.html#http_class_http_agent).

I also found an answer on the stackoverflow that also covers the subject, [here](https://stackoverflow.com/questions/44649566/difference-between-nodejs-new-agent-and-http-keep-alive-header/58332910#58332910 ).
So, I hope this helps.

**Comment by jvmonteiro** [comment]
Hey, I faced this problem recently and managed to solve the issue. I had a back-end `A` communicating with an API `B` through axios requests to send emails (using nodemailer) to an SMTP relay. Some requests took longer for "B" to process (2~3 minutes), throwing the `socket hang up` error in "A". However, "B" still managed to send the email, so I knew something was wrong.

When you create an HTTP(S) server in node, it [sets the socket timeout](https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback) to 0 (no timeout). Nonetheless, the socket still closed and threw a "socket hang up" error; setting the `keepAlive` option HTTP(S) agent also didn't work. After looking dozens of issues, tutorials, questions and stackoverflow, I found [something](https://stackoverflow.com/questions/12651466/how-to-set-the-http-keep-alive-timeout-in-a-nodejs-server) that helped me.

In both servers, I set the socket timeout to `10 * 60 * 1000` (10 minutes) and wrapped the send email handler on "B" inside a 5 minutes timeout. You can choose smaller much values such as 10 and 20 secs, as long as `socketTimeout(server) > setTimeout(handler)`, but you'd also have to consider the time it'd take to execute the handler.


```javascript
// Servers A and B
https
    .createServer(/*server params go here*/)
    .on('secureConnection', (socket) => {
      // HTTPS: secureConnection
      // HTTP: connection
      socket.setTimeout(10 * 60 * 1000); // 10 minutes
    })
    .listen(port)
```

```javascript
// Server B Express.js handler
function sendEmail(req,res) {

/* logic to build email... */
  setTimeout(() => {
    this.transporter.sendMail(email, (err, response) => {
      if (err) {
        return res.status(502).json({ ok: false, message: 'Email not sent' });
      }
        return res.status(200).json({ ok: true, message: 'Email sent' });
    });
  }, 5 * 60 * 1000); // 5 minutes
}
```

Then, I sent a request from "A" to "B":

```javascript
// Server A
function sendEmailToB(email) {

  /* more logic to build email... */
  return new Promise((resolve, reject) => {      
    axios
      .post(endpointB, email)
      .then((result) => resolve(result))
      .catch((err) => reject(err));
  });
}
```
And alas, the **request was a success**. No more socket hangup errors!!
I'd like to note that I'm not sure if it's good to keep the socket open for larger amounts of time, but in our case we needed just **a few more seconds** to process the requests successfully, so I don't think it'll be that bad. As always YMMV, so be careful if adopting this solution. 

Hope this helps someone!

**Comment by jasonsaayman** [comment]
It seems this error is not directly related to axios, should this still be occurring please open a new issue.

**Comment by chentao1006** [comment]
https://stackoverflow.com/a/43439886/1989083

I fixed my same issue by adding these lines into axios.js:
`delete process.env['http_proxy'];`
`delete process.env['HTTP_PROXY'];`
`delete process.env['https_proxy'];`
`delete process.env['HTTPS_PROXY'];`

**Comment by tanmaymishu** [comment]
I ran into the same issue. What did eventually work for you? @hnafar

**Comment by jkomoda** [comment]
@tanmaymishu @hnafar  Currently running into similar issue... got anything working on your end?

**Comment by voncay** [comment]
Had the same issue.
Turns out I didn't return a response in my request controller, so it timeout.
See https://stackoverflow.com/questions/64888841/socket-hang-up-when-using-axios
Hope it helps.

**Comment by RichardTMiles** [comment]
Note the default config file has these commented out 

```
    // `httpAgent` and `httpsAgent` define a custom agent to be used when performing http
    // and https requests, respectively, in node.js. This allows options to be added like
    // `keepAlive` that are not enabled by default.


    httpAgent: new http.Agent({ keepAlive: true }),
    httpsAgent: new https.Agent({ keepAlive: true }),
    
```

**Comment by abnerwei** [comment]
same problem


<html>
<body>

Error: socket hang up     <br>
at handleException (/usr/local/app/webpack:/src/core/request/interceptors/exception-handler/response-interceptor.ts:27:17)   <br>  
at processTicksAndRejections (node:internal/process/task_queues:95:5)    <br>
at Axios.request (/usr/local/app/node_modules/axios/lib/core/Axios.js:40:14)     <br>
at Axios.request (/usr/local/app/node_modules/axios/lib/core/Axios.js:45:41)     <br>
at processTicksAndRejections (node:internal/process/task_queues:95:5)
--



</body>
</html>

**Comment by kyungseopk1m** [comment]
Thanks to you, the problem was solved.
Instead of using the default axios instance, the solution was to use a custom axios instance with keepAlive set to true.
