### ISSUE TITLE
Setting the Interval for certain call/API refresh

### ISSUE THREAD

**Issue by Manikanta-20** [axios/axios#2938]
**Is your feature request related to a problem? Please describe.**

If user submitting a form in between he is  having 5 GET calls,internally one/ two GET call data has been updated.
when user  refresh page he will get data, but problem is user  refreshing  entire page he will lost entire page data.he has to fill this the form starting on wards.

**Describe alternatives you've considered**
Already timeout option is there,like that if you implement interval for certain call. interval will be milli seconds.

**Comment by chinesedfan** [comment]
axios won't support it directly. But users can wrap axios with auto refresh functionalities.

**Comment by Manikanta-20** [comment]
@chinesedfan can you provide any example?
