### ISSUE TITLE
Validate params or body

### ISSUE THREAD

**Issue by doong-jo** [axios/axios#2940]
**Is your feature request related to a problem? Please describe.**
```javascript
axios.get('/users', { params: { nae : 'sam' } }); // wrong parameter name, maybe response 500.
```
I thought it would be nice to have a request validator that could prevent the above.

**Describe the solution you'd like**
```javascript
function myParamsValidator(params) {
  const { name } = params;
  return name && typeof name === 'string';
}
const params = { nae: 'sam' };
axios.get('/users', { params, paramsValidator: myParamsValidator } ; // about params or body

// If validator fail, do not request.
```

Is there already a function that can perform the above functions? If not, I wonder if you have any intentions to add. If it's okay, I'd like to make a request for PR.

**Comment by jasonsaayman** [comment]
I think that this is outside of the scope of Axios, this should rather be added as a separate package or as code within your own code base.

**Comment by doong-jo** [comment]
thnaks your reply.
