### ISSUE TITLE
Error In IE:Request header content-type was not present in the Access-Control-Allow-Headers list

### ISSUE THREAD

**Issue by sumitmoga** [axios/axios#2944]
I'm getting axios post error in IE browser it working fine on other browsers. Its throw above error when i try to send post data. after comparing with chrome i found in request headers there is no content-type and Method show type OPTION . how to fix this.

**Expected Behaviour:**
Request URL: https://domain/api/v1/home-page-jobs
Request Method: POST
Status Code: 200 OK
Remote Address: 
Referrer Policy: no-referrer-when-downgrade
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 12
Content-Type: application/json;charset=UTF-8

**Behaviour on IE11**
![image](https://user-images.githubusercontent.com/49942821/80937811-3f320200-8df4-11ea-884c-198680def133.png)

**PS**=> Please look in IE headers methods is OPTIONS and no content-type

**To reproduce:**
axios.post('/endpoint', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  })

Environment:
Axios Version [0.19.0]
Browser [ IE11]
Additional Library Versions [React 16.12]

**Comment by masbaehr** [comment]
Does a solution exist for this ? Stumbled across this error now

**Comment by masbaehr** [comment]
It seems the reason for this is that IE will not work if on server-side you have "*".

Therefore you need to explicitly set the headers:

![image](https://user-images.githubusercontent.com/38694044/84486472-bed9a900-ac9d-11ea-82ba-17aa21d1cdb9.png)
