### ISSUE TITLE
Status code is missing in toJSON method of axios error

### ISSUE THREAD

**Issue by tsachis** [axios/axios#2947]
**Description**
When calling the `toJSON` method on an axios error (inside a `catch` clause), the returned object does not include the error status code. 
`toJSON` is useful for extracting the main error details, and the status code should be part of it as well.

**To Reproduce**
Run the below code. No status code field in the output. 
The only place status code appears in the `toJSON` object is in the message: "Request failed with status code **404**"

There's a `status` field (which is always `undefined` btw), but according to the code, it is a connection error string (for example, 'ECONNABORTED'), not the response numeric status code.

```js
const axios = require('axios');

axios.get('http://google.com/404')
  .catch(function (error) {
    console.log(error.toJSON());
  })
```

**Expected behavior**
A numeric `statusCode` field should be part of the `toJSON` returned object.

**Environment:**
 - Axios Version 0.19.2
 - OS: OSX 10.14.6
 - Node v12.16.1

**Comment by jasonsaayman** [comment]
Fixed with #2956 2956
