### ISSUE TITLE
Axios TS Import code is not transpiled to JS , throws error : exports is not defined

### ISSUE THREAD

**Issue by PriyaranjanKS** [axios/axios#2948]
**Describe the issue**
I am trying to create a basic Typescript application that can call REST API using Axios. However on running TSC and transpiling the TS to JS, the Axios import code is not getting transpiled to JS and instead it add the below line to the JS File 
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```
As a result , while running the application, in browser we get the below error : 
```js
 Uncaught ReferenceError: exports is not defined
```
**Example Code**
The Axios module is installed using NPM as : npm install axios . In TS file, it is loaded using the below snippet : 

```js
import axios  from 'axios';
```
On transpilin to JS, however it converts the above code to : 
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```
**Expected behavior, if applicable**
Ideally, On transpiling the import axios TS code, equivalent JS code should be generated. However, it does not happen and in browser we get the below error : 
![TSError](https://user-images.githubusercontent.com/29351010/81093005-15292e80-8f1f-11ea-9a6b-9b31134b0cde.PNG)

**Environment:**
 - Axios Version : In package.json the entry is -   "axios": "^0.19.2"
 - OS: Windows 10
 - Browser : Chrome
 - Browser Version :  81.0.4044.129 
 - Additional Library Versions : None

**Additional context/Screenshots**

Visual Studio Code TS/JS Files : 
 
![Error](https://user-images.githubusercontent.com/29351010/81094168-bfee1c80-8f20-11ea-9d4c-429e103fb342.PNG)

Browser Source Error : 
![Exports not defined](https://user-images.githubusercontent.com/29351010/81093623-0131fc80-8f20-11ea-8fb4-421c08fa8be0.png)

**Comment by akozdev** [comment]
I guess you'll need to add Webpack (or other bundler) to your project to be able to import and export modules. You can find how to configure webpack with ts at https://webpack.js.org/guides/typescript/.
Also, I made this sample repo [WebpackTypeScriptSetup](https://github.com/akozdev/WebpackTypeScriptSetup)

**Comment by chinesedfan** [comment]
@PriyaranjanKS Note tsc only compiles your source codes, instead of bundling with imported files. And it does something called tree-shaking, which will remove codes that imported but not used. You can switch axios with any other npm packages and will get the same result. As @akozdev mentions, you need webpack.
