### ISSUE TITLE
onUploadProgress delay (urgently)

### ISSUE THREAD

**Issue by CanVeeD** [axios/axios#2951]
Hello,
Uploading formData with video and some user's info appended. It is config of POST request:

```javascript
const config = {
      headers: {
        'content-type': 'multipart/form-data'
      },
      onUploadProgress: ({ loaded, total }) => {
        const percentage = Math.round(loaded / total * 100);
        console.log(`UPLOADING STATUS: loaded ${loaded} of total ${total}`)
        dispatch({ type: SETUP_PERCENTAGE, percentage });
      }
    };
```
Problem happened, when i've noticed huge delay in upload progress. Approximately on 30% of progress, backend (nodejs, express, multer) receives full formData with video and info (checked, it is valid), while axios still uploading formData.
I really don't understand how it works, it fully uploads whole formData on ~30% and still doing something (UPLOADING STATUS returns appropriate data).

Maybe i've made some mistake?
Thanks :)

**Comment by determin1st** [comment]
how do you know it's 30%?

**Comment by CanVeeD** [comment]
It shows percentage. Ive noticed that in production build, problem disappears. Looks like dispatching many times and then logging to console slow down speed
