### ISSUE TITLE
Https request using Axios

### ISSUE THREAD

**Issue by Zero-007** [axios/axios#2952]
Hi , 
I am making https request using axios and I am using below code.

---------------------------------------------------------------
export const orderFetchInit = (token)=>{
    return dispatch => {
        dispatch(orderFetchingStart());
        axios.get( '/orders.json?auth='+token )
            .then( (res) => {
                if(res)
                console.log('inside the res block of order fetching')
                const fetchedOrders = [];
                for ( let key in res.data ) {
                    fetchedOrders.push( {
                        ...res.data[key],
                        id: key
                    } );
                }
                dispatch(orderFetchingSuccess(fetchedOrders));
            } )
            .catch( (err) => {
                console.log('inside the err block of order fetching')
                dispatch(orderFetchingFail(err));
            } );
    };

}
---------------------------------------------------------------------------------------------

If my request is failed.then block should not be executed and directly comes to catch block instead 
Its going inside then block first and then it is coming to catch block.I am attaching screen shot for more details
---------------------------------------------------------------------------------------------------
![httpsFail](https://user-images.githubusercontent.com/37119127/81264923-d8b11c00-905f-11ea-9908-3972956efe37.jpg)

**Comment by chinesedfan** [comment]
What you need is some practices about promises. Note that errors, maybe "dispatch(orderFetchingSuccess(fetchedOrders));", in then block will trigger catch block. And please follow the issue template next time. Thanks.
