### ISSUE TITLE
status 414

### ISSUE THREAD

**Issue by wk989898** [axios/axios#2953]
code 
``` js
await axios({
      url,
      method: 'post',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      params: {
        access_token,
        image   //base64
      }
    })
```
response: `Error: Request failed with status code 414`
is server error?

**Comment by chinesedfan** [comment]
Yes, a quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
