### ISSUE TITLE
Support HEADERS_RECEIVED for onreadystatechanged and dispatch to callback

### ISSUE THREAD

**Issue by Glandos** [axios/axios#2954]
**Is your feature request related to a problem? Please describe.**
I have an API that provides images as JPEG, and useful metadata in HTTP response headers. Images can be slow to download on some networks, and I'd like to be able to make a change as soon as headers are received.

**Describe the solution you'd like**
Add `onHeadersReceived(headers)` in config, and call it when `readyState === 2` which is `HEADERS_RECEIVED`.

**Describe alternatives you've considered**
I'm currently using `onDownloadProgress`, since the target of the `ProgressEvent` is the XHR instance, and I can call `getResponseHeader` on it. But a proper solution that goes through `parseHeaders` from Axios would be better.

**Comment by jasonsaayman** [comment]
I think this is an issue that should be asked on StackOverflow or an alternative platform. If I am wrong please open a new issue.
