### ISSUE TITLE
Access to XMLHttpRequest ... has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by isaacSolano** [axios/axios#2955]
So, I'm trying to use axios to make a request to another server, then I got this error message described on the title

This is how I'm trying to use it

```
axios.get(url, {
     headers: {'Access-Control-Allow-Origin': '*'}
})
.then(res => {
     console.log(res);
})
.catch(err => {
     console.log(err);
});
```
This is happening on all browsers, I'm using React last version on this project

Thanks for any info can be provided

**Comment by chinesedfan** [comment]
We suggest you learn something about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) first. You mistake is that "Access-Control-Allow-Origin" is one of response headers returned by the server, instead of request headers send by axios. Good luck!

**Comment by isaacSolano** [comment]
Exactly, I'm familiar with the reason of the response, but what I need is exact information about the way to fix to this issue.

All I found are extense blogs, documentation and large chuncks of code that did nothing towards the problem, MDN was great source of explanation, however I need a way to fix this ASAP

**Comment by chinesedfan** [comment]
Contact the backend developer to response the right header, instead of setting in axios.

**Comment by rudymarca** [comment]
> Exactly, I'm familiar with the reason of the response, but what I need is exact information about the way to fix to this issue.
> 
> All I found are extense blogs, documentation and large chuncks of code that did nothing towards the problem, MDN was great source of explanation, however I need a way to fix this ASAP

Si utilizar PHP en el Backend tienes que agregar header('Access-Control-Allow-Origin: *');
