### ISSUE TITLE
Stream closed/ Cant able to send image in form data

### ISSUE THREAD

**Issue by ali8404** [axios/axios#2960]
var data = new FormData();
    data.append('FirstName', firstNameValue);
    data.append('ProfilePicture', {
        uri: imageDetails.path,
        name: `${new Date().getMilliseconds()}-ProfilePic.jpg`,
        type: "image/jpeg",
    });
    data.append('DateOfBirth', DOB.toISOString());
    data.append('DeathDateTime', new Date(deathDate).toISOString());
axios.post(
            '.../api/' + Register,
            data,
            {
                headers: {
                    'Authorization': `Bearer ${token}`,
                    "Content-Type": "multipart/form-data",
                }
            }
        ).then(function (response) {
            console.warn(response);
            debugger;
        }).catch((error) => {

            debugger;
            console.log(error);
        });

Response: 
  Error: Network Error

  Error.request
![image](https://user-images.githubusercontent.com/64311721/81498417-4d918980-92de-11ea-8a0e-8f3801347173.png)
![image](https://user-images.githubusercontent.com/64311721/81498556-05bf3200-92df-11ea-8dae-f0a3cd24d937.png)

**Comment by Ghost-str** [comment]
See [docs](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append) 
Example paragraph

**Comment by hungtrn75** [comment]
@ali8404 https://github.com/facebook/react-native/issues/28551#issuecomment-610652110

**Comment by ali8404** [comment]
> @ali8404 [facebook/react-native#28551 (comment)](https://github.com/facebook/react-native/issues/28551#issuecomment-610652110)

Thanks @hungtrn75 I will verify this solution 
as for now, I am sending base64 to the server as a workaround
