### ISSUE TITLE
Trouble with axios  ( pending all the time ) 

### ISSUE THREAD

**Issue by karol-1** [axios/axios#2961]
Hello. I have trouble with axios. I  used  axios in order to send data on server. 
req.body is send correctly and app almost work but there is a problem.  axios is pending in network some long time and after that activate catch() instead of then() . I will be  grateful if someone spend little of his time and help with this. :) 
(MERN app)      
  
(frontend)
```javascript
import React, {Component} from 'react';
import axios from 'axios';
class App extends Component {
 state={
   title:"",
   body:"",
   post:[]
 }
handleChange=(e)=>{
  this.setState({
    [e.target.name]:e.target.value,
  })
  
}
handleSubmit=(e)=>{
  e.preventDefault()
  const payload ={
    title:this.state.title,
    body: this.state.body
  }
  axios({
    url:"/api/save",
    method:"POST",
    data:payload,
   
  })
  .then(()=>{
    console.log("wysłane poprawnie")
  })
  .catch((err)=>{
     console.log(err)
  })
}


  render() { 
    return ( 
<>

<h1>Witam na stronie</h1>
<form onSubmit={this.handleSubmit} >
  <input onChange={this.handleChange} type="text" name="title" value={this.state.title} placeholder="title"/>
  <textarea onChange={this.handleChange} name="body" placeholder="body" value={this.state.body} cols="30" rows="10"></textarea>
  <button >Submit</button>
</form>

</>

     );
  }
}
 
export default App;


```
(package.json  react-app)(proxy)
```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "proxy": "http://localhost:8080"
}

```
(server node)
```javascript
const express = require("express");
const morgan = require("morgan");
const axios = require("axios");
const concurrently = require("concurrently");
const mongoose = require("mongoose");
 
const app = express();
const PORT = process.env.PORT || 8080;
mongoose.connect('mongodb://localhost/baza_danych',{
    useNewUrlParser:true,
    useUnifiedTopology:true
} )

mongoose.connection.on("connected", (error)=>{
    if(error){
        console.log("cos poszło nie tak")
    } else{
        console.log("wszystko jest okay")
    }
})

app.use(express.json());
app.use(express.urlencoded({extended:false}));
app.use(morgan("tiny"));
const Schema = mongoose.Schema
const schemaBlogPost = new Schema({
    title:String,
    body:String,
    date:{
        type:String,
        default: Date.now()
    }
})
const BlogPost = mongoose.model('baza_danych', schemaBlogPost)

app.post('/api/save',(req,res)=>{
    const data = req.body
const newBlogPost = new BlogPost(data)
newBlogPost.save((error)=>{
    if(error){
        console.log("nie odebrano")
    }else{
        console.log("odebrano prawidłowo")
    }
})
})







app.listen(PORT, ()=>{
    console.log("server nasłuchuje");
})
```
![96802599_2907513845963498_952929341765844992_n](https://user-images.githubusercontent.com/65115435/81498654-79087a00-92c6-11ea-8cad-f25ce669f733.png)
![97211102_240446973846131_6064808784788717568_n](https://user-images.githubusercontent.com/65115435/81498656-7a39a700-92c6-11ea-8730-56d5d79e84f8.png)

**Comment by EmmyMay** [comment]
I can't actually see where you are using axios on the server file. 

In your react where you made the post request with axios, what is payload pointing to? It doesn't look like you are actually sending any data to the server.

**Comment by EmmyMay** [comment]
I can't find why or where you are using axios on the server. You only required it.

**Comment by karol-1** [comment]
maybe I'm doing something wrong. I used axios in my frontend to send value from imput on url api/save. On server I used  get with this url and  save this in database. And it's work but I     then()   don't work in axios because is still pending.

**Comment by jasonsaayman** [comment]
Try using `await`?

**Comment by EmmyMay** [comment]
You don't need axios on the server. Use express to save it into your database. There's no need for axios

**Comment by Ghost-str** [comment]
> maybe I'm doing something wrong. I used axios in my frontend to send value from imput on url api/save. On server I used get with this url and save this in database. And it's work but I then() don't work in axios because is still pending.


you must answer the request and close the connection.
see http://expressjs.com/en/api.html#res

**Comment by karol-1** [comment]
Ghost-str thank you a lot. It works perfectly  well. I'm also grateful to everyone that tried to help and spent some time. :)  I will read more express documentation and check  await. Thanks!
