### ISSUE TITLE
Do I use multiple interceptors or one interceptor for everything?

### ISSUE THREAD

**Issue by SevenOutman** [axios/axios#2962]
In my case I have several processing work to do before a request is sent, e.g. authentication, cancel conditions. I split the logic into different functions for cleanness.

```javascript
function authenticate(config) {
  // do something with Authorization header
}

function cancelOnSameKey(config) {
  // call cancel() on cancelToken source for corresponding config.key
}

function trimParingParams(config) {
  // delete params which should be paring with another param but only appeared itself
}
```

The question is should I use each of these functions as separate interceptors, or call them in a single interceptor?

```javascript
axios.interceptors.request.use(authenticate)
axios.interceptors.request.use(cancelOnSameKey)
axios.interceptors.request.use(trimParingParams)

// or

axios.interceptors.request.use(config => {
  authenticate(config)
  cancelOnSameKey(config)
  trimParingParams(config)

  return config
})
```

Suppose I don't need to eject my interceptors, what's the difference between these two approaches? And which one is recommended?

### To be accurate
The problem I'm facing is that, the first approach makes more sense for me until I have one error handler.
```javascript
axios.interceptors.request.use(authenticate, errorHandler) // should I put it here?
axios.interceptors.request.use(cancelOnSameKey /*, or here? */)
axios.interceptors.request.use(trimParingParams /*, or here? */)
```
It doesn't make any sense that an errorHandler should be paring with any of the three interceptors. It just doesn't look...balanced.

**Comment by chinesedfan** [comment]
> should I use each of these functions as separate interceptors, or call them in a single interceptor?

[My notes](https://github.com/chinesedfan/You-Dont-Know-Axios#interceptors) may help you. In fact, I think both of ways can achieve good and clear codes.

> until I have one error handler

If your error handler is handling a precise kind of error, then you need 3 handlers. If you have a powerful common handler, you can add at the last `use`.

**Comment by SevenOutman** [comment]
@chinesedfan Thank you for answering. Your tutorial does help me figure out the interceptor API design. 

But I got confused with `transformResponse` according to the design. What’s the difference between a response interceptor (on fulfilled) and a transformResponse function?

**Comment by chinesedfan** [comment]
> Without transformers we can also achieve features by interceptors. But transformers focuse on request or response data, and are closer to adapters.

I am not the original author of axios, but only share my understanding [here](https://github.com/chinesedfan/You-Dont-Know-Axios/blob/master/README.md#make-things-precisely-transformrequest-and-transformresponse).
