### ISSUE TITLE
Does axios automatically set xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN' by default on every type of request?

### ISSUE THREAD

**Issue by 1kvnlee** [axios/axios#2966]
## Usage Question
Hi, does axios automatically set xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN' by default on every type of request?

**Comment by jasonsaayman** [comment]
Hi,

No it does not you should attach that to your request.

**Comment by 1kvnlee** [comment]
@jasonsaayman Thanks
