### ISSUE TITLE
 axios.create cant take params

### ISSUE THREAD

**Issue by gaoyike** [axios/axios#2967]
```
const videoCount = axios.create({
    baseURL: videosCountURL,
    timeout: 1000,
    params: {
        'part': 'contentDetails',
        'id' : youtubePlayListId,
        'key' : youtubeAPIKey
    }
});
```
The code above is getting 400. but I tried with just adding params in the URL, it works fine

**Comment by jasonsaayman** [comment]
Hi,

Thanks you for submitting this issue, however more information is needed. To help us in debugging please could you use an issue template provided by the repository?

Thanks
