### ISSUE TITLE
adapter is not a function (EDIT: after 1st request)

### ISSUE THREAD

**Issue by tincho** [axios/axios#2968]
Edit:

I originally thought this was only happening in the DELETE request. 
It turns out that _any_ request after the first request fails . So if I send the POST and then the POST again, the 2nd time it fails. 

```
TypeError: adapter is not a function
    at dispatchRequest (dispatchRequest.js:52)
    at async http:/localhost:3004/launchpad/static/js/205.chunk.js:537
```

-- 

Hi there

In the same page we have several calls to `axios.get`, `axios.post` and those work fine.

But using `axios.delete` I'm getting a weird error

`adapter is not a function`

I inspected into axios' code and found that effectively, `defaults.adapter` is undefined

![image (20)](https://user-images.githubusercontent.com/178681/81855378-aad34800-9535-11ea-816a-89427b716b6d.png)

Weird thing is that in other verbs (get, post), adapter is a function (I think is xhrAdapter or something like that)

**Comment by tincho** [comment]
I kind of worked around this with this hack:

```javascript
import axiosOriginal from 'axios'
import adapter from 'axios/lib/adapters/xhr'

const axios = axiosOriginal.create({ adapter })

```

**Comment by chinesedfan** [comment]
> It turns out that any request after the first request fails

Maybe your interceptors did something special to the default config. Please check for that.

**Comment by tincho** [comment]
Hello, thanks for the reply!
Indeed, we have a few logger interceptors, that I disabled in order to be able tu debug the issue until reaching the "adapter is not a function" point

The interceptors are these:
```javascript
import * as AxiosLogger from 'axios-logger'
axios.interceptors.request.use(
  AxiosLogger.requestLogger,
  AxiosLogger.errorLogger
)
axios.interceptors.response.use(
  AxiosLogger.responseLogger,
  AxiosLogger.errorLogger
)
```

but again, those were commented out and the error persisted

**Comment by chinesedfan** [comment]
Can you provide a sample and reproducible repo? With limited information, I am sorry that can't find the reason.

**Comment by softmarshmallow** [comment]
https://github.com/axios/axios/issues/3366

Still having the issue. Please re-open

**Comment by softmarshmallow** [comment]
> ```js
> import axiosOriginal from 'axios'
> import adapter from 'axios/lib/adapters/xhr'
> 
> const axios = axiosOriginal.create({ adapter })
> ```

`XMLHttpRequest is not defined`

**Comment by yennor** [comment]
I've had the same problem. 
But my problem was, that I tried to use Axios inside of a service worker. Unfortunately that doesn't work since axios can't work inside of a worker, because of: https://github.com/axios/axios/issues/1219
So the above solution didn't work (obviously)

**Comment by stefanoriva-xs** [comment]
Having same problem but only with my Webpack release.
I've tried different webpack config solutions and i get 2 different errors now:

If i set minimize to false, i get 
_TypeError: adapter is not a function_

If i toogle the minimize to true, i get
_TypeError: (config.adapter || defaults.adapter) is not a function_

Runs without issues on development, as soon as i bundle it just won't work..

**Comment by suhostv** [comment]
@softmarshmallow, @tincho were you guys able to resolve this issue?
tried a lot of things, but nothing seem to help

**Comment by softmarshmallow** [comment]
Wasn't able to. In my case fetch just wasn't allowed in my js environment. (I'm developing a [figma plugin](https://github.com/bridgedxyz/assistant))

**Comment by shunjizhan** [comment]
Had similar issue, in my case I was using some polyfill plugin with webpack, which made the production code somehow browser like, so 
```js
Object.prototype.toString.call(process) === '[object object]'
``` 

Then I ran the code in Node, and `axios` can't pick any adaptor by this code:
```js
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

not sure why we need to check `Object.prototype.toString.call(process) === '[object process]`, isn't `typeof process !== 'undefined'` enough to determine it is a Node environment?

To solve this, turns out I don't actually need the polyfill plugin to build the production code... so I just removed that plugin from webpack, and it worked...

**Comment by tkodev** [comment]
> Had similar issue, in my case I was using some polyfill plugin with webpack, which made the production code somehow browser like, so
> 
> ```js
> Object.prototype.toString.call(process) === '[object object]'
> ```
> 
> Then I ran the code in Node, and `axios` can't pick any adaptor by this code:
> 
> ```js
> function getDefaultAdapter() {
>   var adapter;
>   if (typeof XMLHttpRequest !== 'undefined') {
>     // For browsers use XHR adapter
>     adapter = require('./adapters/xhr');
>   } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
>     // For node use HTTP adapter
>     adapter = require('./adapters/http');
>   }
>   return adapter;
> }
> ```
> 
> not sure why we need to check `Object.prototype.toString.call(process) === '[object process]`, isn't `typeof process !== 'undefined'` enough to determine it is a Node environment?
> 
> To solve this, turns out I don't actually need the polyfill plugin to build the production code... so I just removed that plugin from webpack, and it worked...

what polyfill plugin were you using?

**Comment by MakarovAV** [comment]
I've encountered the same issue recently with a basic webpack+babel+typescript configuration.
For whatever reason, webpack refused to add httpAdapter to the bundle. Even if I required it explicitly, it was replaced by the adapter. I still have not figured out exactly why.

What worked for me: `target: 'node'` in the webpack config (https://webpack.js.org/concepts/targets/#usage). If you need the code working in both browser and node you might need two separate webpack configs.

**Comment by qiankunxienb** [comment]
I have encountered the same issue when I use axios in chrome extension background.js.

**Comment by evanb2** [comment]
Also landed here after getting this error trying to use `axios` in a Chrome extension background file. Sad face.

**Comment by mehimanshupatil** [comment]
@qiankunxienb @evanb2 what workaround did you applied to resolve

**Comment by aadarshp31** [comment]
I found the solution here: https://github.com/spatie/laravel-server-side-rendering/issues/53#issuecomment-791480669
Thanks to @SerhiyP 

```import adapter from 'axios/lib/adapters/http'

axios(URL, {
adapter: adapter
})
```

**MY USE CASE**
I am working on a vscode web extension which I want to work in desktop (nodejs) environment. Axios was throwing the exact same error for me. This fix helped me resolve this issue.

**Comment by tktcorporation** [comment]
I have encountered the same issue when I use axios in chrome extension background.js.
And I resolved this problem.

My extension is made by forking https://github.com/antfu/vitesse-webext/tree/369fc0386970c77e35d401a2deb4d2ef71768aea .

```bash
pnpm add -D @vespaiach/axios-fetch-adapter@0.3.1 axios@0.26.1
```

```ts
import axios from 'axios'
import fetchAdapter from "@vespaiach/axios-fetch-adapter";

const service = axios.create({ adapter: fetchAdapter })
```

ref: https://zenn.dev/nicopin/articles/5dc87c27bd08de

**Comment by MingyuJeon** [comment]
> ```ts
> import axios from 'axios'
> import fetchAdapter from '@vespaiach/axios-fetch-adapter';
> 
> const service = axios.create({ adapter: fetchAdapter })
> ```

This works perfect!

**Comment by aadarshp31** [comment]
Does anyone have a solution for the same with XMLHttpResquest adapter? I needed it for node environment.

**Comment by PedroFolego** [comment]
```
import axios from 'axios'
import fetchAdapter from '@vespaiach/axios-fetch-adapter';

api.defaults.adapter = fetchAdapter;
const user = await api.get('/users');
```
This worked for me. 
I removed it from the axios.create and put it with the request.

**Comment by PedroS11** [comment]
Updating the axios version helped me, according to this merged MR (https://github.com/axios/axios/pull/5277), you can now specify the adapter you want.

`axios.create({
			adapter: "xhr"
		})`
		
This now works for me with axios and a custom interceptor

**Comment by marcusjwhelan** [comment]
@PedroFolego @tktcorporation @MakarovAV Has anyone been able to solve this when they aren't using axios directly but axios is being used by another library? Sendgrid is getting this error but I don't have access to axios through that

**Comment by Dejan-Teofilovic** [comment]
I have very similar issue. How to fix it
![Capture1](https://github.com/axios/axios/assets/146126493/acdc0dd5-67df-4db5-aa5a-96398cabc3e6)
?
![Capture](https://github.com/axios/axios/assets/146126493/21edcf7d-2257-47ae-80c5-18f1d526a3c4)
