### ISSUE TITLE
Axios form-data POST request issue

### ISSUE THREAD

**Issue by essivision** [axios/axios#2969]
**Describe the issue**
I wanna to send form-data Post request (not file) to 3rd-party application server, but get error from server. 

**Example Code**
```js
const axios = require('axios');
  const FormData = require('form-data');
  const form = new FormData();
  let obj = {
    request: {
      subject: 'sample title'
    }
  };

  form.append('input_data', JSON.stringify(obj));

  axios({
    method: 'post',
    url: `http://localhost:8080/api/v3/requests`,
    data: form,
    headers: {
      'content-type': `multipart/form-data`,
      'TECHNICIAN_KEY':'sampleKey***'
    }
  }).then(function (response) {
          // handle success
          console.log(response.data);

      })
```

**Expected behavior, if applicable**
Now I wanna to try post data with axios and configure like above, but I get error from server. I think miss somethings. What should I do?

**Environment:**
 - Axios Version [0.19.2]
 - OS: [Widows 10]
 - Additional Library Versions [form-data v3.0.0]

**Additional context/Screenshots**
There is API call tester in this API documentation. When I use this tester in browser every things is okay and report like this:
![api-call](https://user-images.githubusercontent.com/7271330/81894013-19f77d80-95c4-11ea-91a0-541be12b0c60.jpg)
![api-postman](https://user-images.githubusercontent.com/7271330/81894032-21b72200-95c4-11ea-925b-4fdaa088172a.jpg)

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
