### ISSUE TITLE
Axios making 2 calls to rest api (firebase cloud function) and the POST data is available only in the 2nd call

### ISSUE THREAD

**Issue by JerryGoyal** [axios/axios#2970]
Axios is somehow making 2 calls to rest api (firebase cloud function) and the POST data is available only in the 2nd call. However when I see in the chrome network call only 2nd call is shown. I'm testing it locally.
```

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
axios({
      method: "post",
      url: "http://localhost:5001/firebase-project/asia-east2/createOrder",
      data: {
        orderName: "Finn",
        quantity: "1"
      },
    })
      .then(function (response) {
      })
      .catch(function (error) {
      });
```

First Call:
in first call POST data is empty.

Request headers in cloud function:
![image](https://user-images.githubusercontent.com/7106086/82093013-ed547a80-9717-11ea-843c-bc0555e609d6.png)

Second Call:
in second call POST data is received.

Request headers in cloud function:

![image](https://user-images.githubusercontent.com/7106086/82093120-25f45400-9718-11ea-9b1b-8ab15161bdc0.png)

To verify that the issue is with Axios, I called that rest api  using $.ajax method and it was called only once with the proper POST data. I also tested with postman and that also called it once.

**Comment by SolomoN-ua** [comment]
Looks like CORS for me.
Check in browser network tab if the first request method is OPTIONS.

**Comment by chinesedfan** [comment]
> To verify that the issue is with Axios, I called that rest api using $.ajax method and it was called only once with the proper POST data. I also tested with postman and that also called it once.

Did you call $.ajax after axios? The preflight request will not be fired before a previous preflight call. And Postman will never have CORS problem.

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
