### ISSUE TITLE
axios.create does not use params key

### ISSUE THREAD

**Issue by isaacl** [axios/axios#2972]
Params specified using axios.create are ignored. Here's a test case:

```js
const axios = require('axios');

const agent = axios.create({
  baseURL: 'https://www.test.com',
  params: {
    test: 'test',
  },
});

Promise.all([
  agent.get('/'),
  agent.get('/', { params: { foobar: 'foo' } }),
]).then((arr) => arr.map(({ request: { path } }) => console.log(path)));
```

EXPECTED OUTPUT:
/?test=test
/?test=test&foobar=foo

ACTUAL OUTPUT
/
/?foobar=foo

**Comment by davidnewcomb** [comment]
Duplicate of #2190,  I'll save you hours of reading:
1) it's been broken for a year and is scheduled for release in 0.20.0
2) there is no plan to release 0.19.3 with the fix

No one seems to know when 0.20.0 will be released. They are some way off but you can check the progress here
https://github.com/axios/axios/projects/4#card-32115568

There is a test here that demos the bug.
https://runkit.com/5ec536f15ef071001ee0323d/5ec5370123a109001afb27a9

The general advise is to pin your version to 0.18.1 and wait for 0.20.0

**Comment by isaacl** [comment]
dupe of #2190
