### ISSUE TITLE
be able to load local JSON file

### ISSUE THREAD

**Issue by sammysium** [axios/axios#2974]
**Is your feature request related to a problem? Please describe.**
Today we are told axios can't read local JSON files in react-native neither can fetch for that matter and we should move to more native languages. Given we are so much into the app and this feature of reading some data from JSON came now, it is a huge loss to move to a native app just cos Axios returns network error.

**Describe the solution you'd like**
Be able to load local JSON files that are in the project.

**Describe alternatives you've considered**
Moving to or java is being suggested by senior developer

**Additional context**
None

**Comment by jasonsaayman** [comment]
Hi,

Can you maybe give me an example?

Thanks

**Comment by mustaphee** [comment]
> **Is your feature request related to a problem? Please describe.**
> Today we are told axios can't read local JSON files in react-native neither can fetch for that matter and we should move to more native languages. Given we are so much into the app and this feature of reading some data from JSON came now, it is a huge loss to move to a native app just cos Axios returns network error.
> 
> **Describe the solution you'd like**
> Be able to load local JSON files that are in the project.
> 
> **Describe alternatives you've considered**
> Moving to or java is being suggested by senior developer
> 
> **Additional context**
> None

Load JSON file? What are you trying to do. You can simply convert your JSON to object with JSON.parse() without any issue.
