### ISSUE TITLE
I executed the command "npm i axios" and I had errors

### ISSUE THREAD

**Issue by dd2424** [axios/axios#2978]
Hello,

I am a video tutorial, I need axios, I executed the command **npm i axios** and I had errors, I don't know why exactly. I do not understand. I checked the folder **node_modules** contains the **axios** folder.

How to do it please?

Thank you.

> λ npm i axios
> npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
> npm ERR! path C:\wamp64\www\oppiafr\node_modules\.node-sass.DELETE\vendor\win32-x64-64\binding.node
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall unlink
> npm ERR! Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\oppiafr\node_modules\.node-sass.DELETE\vendor\win32-x64-64\binding.node'
> npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\oppiafr\node_modules\.node-sass.DELETE\vendor\win32-x64-64\binding.node']
> npm ERR!   cause:
> npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\oppiafr\node_modules\.node-sass.DELETE\vendor\win32-x64-64\binding.node'
> npm ERR!      errno: -4048,
> npm ERR!      code: 'EPERM',
> npm ERR!      syscall: 'unlink',
> npm ERR!      path:
> npm ERR!       'C:\\wamp64\\www\\oppiafr\\node_modules\\.node-sass.DELETE\\vendor\\win32-x64-64\\binding.node' },
> npm ERR!   stack:
> npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\wamp64\\www\\oppiafr\\node_modules\\.node-sass.DELETE\\vendor\\win32-x64-64\\binding.node\'',
> npm ERR!   errno: -4048,
> npm ERR!   code: 'EPERM',
> npm ERR!   syscall: 'unlink',
> npm ERR!   path:
> npm ERR!    'C:\\wamp64\\www\\oppiafr\\node_modules\\.node-sass.DELETE\\vendor\\win32-x64-64\\binding.node' }
> npm ERR!
> npm ERR! The operation was rejected by your operating system.
> npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
> npm ERR! or that you lack permissions to access it.
> npm ERR!
> npm ERR! If you believe this might be a permissions issue, please double-check the
> npm ERR! permissions of the file and its containing directories, or try running
> npm ERR! the command again as root/Administrator (though this is not recommended).
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2020-05-23T16_58_38_593Z-debug.log

**Comment by vighnesh153** [comment]
This is not related to `Axios`. There is probably some problem with your installation of `node` and `npm`. The simplest way to fix them would be to do a clean re-install of `node`.

**Comment by chinesedfan** [comment]
Closed as @vighnesh153 commented.
