### ISSUE TITLE
how to cancel file upload when the server respond 400 status

### ISSUE THREAD

**Issue by jianchengwang** [axios/axios#2979]
My server config max file upload size, so when I upload a big file, it will respond 400 status, Axios not catch this error response immediately but do it when the request sent completed. I hope Axios can do it immediately then cancel this request.  When I use postman to request, it works well.

**Comment by jasonsaayman** [comment]
Hi,

Thanks you for submitting this issue, however more information is needed. To help us in debugging please could you use an issue template provided by the repository?

Thanks
