### ISSUE TITLE
Axios with TypeScript usage. Mismatch types between AxiosResponse and custom Interface

### ISSUE THREAD

**Issue by force-push-master** [axios/axios#2980]
**I have a get request and need to extract needed data from response:** 
`async getDataFunction(url: string) {
  try {
    return http.get({ url: url })
    .then((res) => this.extractNeededData(res))  //  <<<---  Argument of type 'AxiosResponse<unknown>' is not assignable to parameter of type 'myInterface'
    .catch((error) => Promise.reject(error));
  } catch (err) {
    throw new Error(err);
  }
}`

**Here the function and interface for extracting data from response:**
`interface myInterface {
  prop1: string;
  prop2: string;
  prop3: string;
  prop4: Array<{
    prop5: {
      prop6: Array<{
        prop7: Array<{
          prop8: string;
        }>;
      }>;
    };
  }>;
}`

`extractNeededData(data: myInterface) {
  return {
    prop1: data.prop1,
    prop2: data.prop2,
    prop3: data.prop3,
    someProp: data.prop4[0].prop5.prop6[0].prop7[0].prop8,
    anotherProp: data.prop4[0].prop5.prop6[0].prop7[1].prop8,
  };
}`

And I faced with an error that told me of type mismatch between AxiosResponse and Interface I've created(mark the place in code as a comment: **Argument of type 'AxiosResponse<unknown>' is not assignable to parameter of type 'myInterface'** ). I googled and found info how to convert AxiosResponse  to string only. May be I'm doing smth. wrong?

**Comment by jasonsaayman** [comment]
Hi,

Thanks you for submitting this issue, however more information is needed. To help us in debugging please could you use an issue template provided by the repository?

Thanks
