### ISSUE TITLE
Response on a get request is not as expected 

### ISSUE THREAD

**Issue by harishcs12287** [axios/axios#2981]
OS: Mac Mojave 10.14.6

When the  below URL was passed as a get request on post man:
https://abc.com/services/data/v42.0/query/?q=SELECT+name+from+Order__c+Where+id+='a2F3D0000TLetUAG'

The below result was obtained:
{
    "totalSize": 1,
    "done": true,
    "records": [
        {
            "attributes": {
                "type": "Order__c",
                "url": "/services/data/v42.0/sobjects/Order__c/a2F3D0000TLeUUAW"
            },
            "Name": "WO-00037151"
        }
    ]
}

When I do the same thing on Axios the response is as below:
  data: { totalSize: 1, done: true, records: [ [Object] ] }

I expect a json after records as obtained on postman, here on Axios it just says Object.

Please help me to resolve this issue

Please Note the URL rendered by Axios looks like below:

https://abc.com/services/data/v42.0/query/?q=SELECT+name+from+Order__c+Where+id+=%27a2F3D0000TLetUAG%27', (Quotes replaced by %27) is this the cause of problem or is it something else?

**Comment by jasonsaayman** [comment]
This is not an Axios problem the data return is an object you can convert it to json by doing the following:

```js
JSON.stringify(obj);
```
