### ISSUE TITLE
XSS problem in axios

### ISSUE THREAD

**Issue by hilmanrdn** [axios/axios#2983]
Hi,

i've read similar issues that mentioned this problem

when there is any "javascript" word on URL, the axios will stop run, and 
unfortunately it stopped my other script too.

not sure what's the solution for this.
i've upgraded axios to 0.19.2 today and the problem still occured

here is my url test.local/tag/javascript

thanks

**Comment by mayank-mittal** [comment]
Provide a sample url

**Comment by chinesedfan** [comment]
It shouldn't be there. Please follow the issue template with required error output or reproducible codebox link.

**Comment by hilmanrdn** [comment]
sorry for the confusion. This issue didn't show anymore.
