### ISSUE TITLE
How to Get the BaseURL from axios.create({baseURL})?

### ISSUE THREAD

**Issue by LxKev** [axios/axios#2985]
I'm trying to get the baseURL from `customApi.js` axios that is created using `export default axios.create()`configuration.

customApi.js file
```
import axios from 'axios';

export default axios.create({
    baseURL: 'http://123.123.123.123:5000'
});
```
I tried the following, but it console logs `undefined`. 
```
import api from 'customApi.js';

console.log(api.baseURL);
```
What is the correct way to get the base url in a custom configured axios?

**Comment by mayank-mittal** [comment]
_`api.defaults.baseURL`_

> https://github.com/axios/axios#config-defaults

**Sample Code**
```
const axios = require('axios');

const api = axios.create({
	baseURL: "http://www.google.co.in"
});

console.log(api.defaults.baseURL)
```

**Comment by LxKev** [comment]
@mayank-mittal Thanks
