### ISSUE TITLE
How to Check if Axios Call Fails due to No Internet Connection?

### ISSUE THREAD

**Issue by LxKev** [axios/axios#2986]
I'm trying to figure out an accurate way to detect axios call failure due to no internet connection. 

Does axios call failure return a specific response object or specific response status code or throw a specific error details for the no internet connection scenario?

Example of what i will use the "**detection of axios failure due to no internet connection**" for
```
try {
    const res = await server.get('/auth/user?', {
            params: {
                refreshToken: refreshToken,            
                userID: userID
            }
        }
    );

    if(res.user.data){
        dispatch({type: LOGIN_USER_SUCCESS, payload: res.data.user});
    } else {
        if(res.axiosFailsDueToNoInternetConnection){
            alert('no internet connection');
            dispatch({type: RELOAD});
        }
    }

} catch (error) {
    if(error.dueToNoInternetConnection){
        alert('no internet connection');
        dispatch({type: RELOAD});
    }
}
```

**Comment by mayank-mittal** [comment]
You shouldn't rely on axios or any http library to determine the internet connectivity, cause it can't distinguish between `No Internet` and `Server not reachable`.

If you don't care about the difference between the 2 states, refer
> https://github.com/axios/axios#handling-errors

If you want to check the network connectivity on browser, refer
> https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

**Comment by LxKev** [comment]
@mayank-mittal Thanks

**Comment by AidanHak** [comment]
If you're using Expo with React Native, there's a [Network API](https://docs.expo.io/versions/latest/sdk/network/).

**Comment by dozsolti** [comment]
Well, you kinda can't, at least not with axios, you have to use another library because:
>  axios timeout is response timeout, not connection timeout. 
arthankamal - https://stackoverflow.com/a/54573024

But there is a workaround to wait some time and if there isn't a response it means that it will be an internet problem.
Check out here for an example: https://stackoverflow.com/a/70390385

**Comment by SeyedHossein-Hosseini** [comment]
```
axiosInstance.interceptors.request.use((response) => response, (error) => {
  if(!navigator.onLine) { Promise.reject(new Error('No internet connection')) }
 // you can add error-handling logics here. 
})
```
