### ISSUE TITLE
Axios HTTP Adapter fails to include

### ISSUE THREAD

**Issue by H1X4Dev** [axios/axios#2987]
**Describe the bug**
When attempting to include HTTP adapter for an Electron application, it will always attempt including XHR one instead.

Copying the adapter to the project and then including it works fine.
![image](https://user-images.githubusercontent.com/10332146/83155061-23730080-a101-11ea-88f1-5ea28d4be570.png)

You can also spot the issue in the repository dist files: https://github.com/axios/axios/blob/master/dist/axios.js#L861 . As you can see it tries to include XHR library (`__webpack_require__(12);`) for both conditions rather than being XHR first and HTTP the second.

**To Reproduce**
Will show that it included XHR instead of HTTP.
```js
console.log('axios:', require('axios/lib/adapters/http'));
```

**Expected behavior**
HTTP adapter included rather than XHR.

**Environment:**
 - Axios Version 0.19.2
 - OS: Windows 10 x64
 - Browser Electron + Webpack
 - Browser Version 9.0.0

**Comment by chinesedfan** [comment]
If you want to set `adapter` explicitly, note that axios makes an alias from http adapter to xhr adapter in browser. Therefore, remember to configure your bundler properly. Refer to Webpack's [target](https://webpack.js.org/configuration/target/) or [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias).
