### ISSUE TITLE
send image with formdata and axios

### ISSUE THREAD

**Issue by quaestum1** [axios/axios#2988]
Hi, in de last version when i try send image with FormData and axios , dont´t work return this problem

Error: Network Error at createError (C:\project\project\node_modules\axios\lib\core\createError.js:16) at EventTarget.handleError (C:\project\project\node_modules\axios\lib\adapters\xhr.js:83) at EventTarget.dispatchEvent (C:\project\project\node_modules\event-target-shim\dist\event-target-shim.js:818) at EventTarget.setReadyState (C:\project\project\node_modules\react-native\Libraries\Network\XMLHttpRequest.js:575) at EventTarget.__didCompleteResponse (C:\project\project\node_modules\react-native\Libraries\Network\XMLHttpRequest.js:389) at C:\project\project\node_modules\react-native\Libraries\Network\XMLHttpRequest.js:502 at RCTDeviceEventEmitter.emit (C:\project\project\node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:189) at MessageQueue.__callFunction (C:\project\project\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:425) at C:\project\project\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:112 at MessageQueue.__guard (C:\project\project\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:373)

but create project with version 0.61.5 of react native and worked

**Comment by chinesedfan** [comment]
> but create project with version 0.61.5 of react native and worked

So looks like an issue of RN. A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
