### ISSUE TITLE
What is the phonetic alphabet of 'axios'

### ISSUE THREAD

**Issue by Vinsea** [axios/axios#2989]
**Describe the issue**
What is the phonetic alphabet of 'axios'?

I didn't find it in the README.md or issue list or dictionary

**Comment by EvanK** [comment]
If you're asking for the NATO phonetic form, it'd be: `Alpha X-ray India Oscar Sierra`

**Comment by Vinsea** [comment]
> If you're asking for the NATO phonetic form, it'd be: `Alpha X-ray India Oscar Sierra`

@EvanK  thanx!!  But  how to pronounce If it's an abbreviation  😃

**Comment by jasonsaayman** [comment]
I think the pronunciation is something like this: [pronounce axios](https://www.howtopronounce.com/axios)
