### ISSUE TITLE
It seems that axios don't support auto serilizer config {params:} in node environment

### ISSUE THREAD

**Issue by tianyingchun** [axios/axios#2991]
in web, we can pass query parameters in config.params object but it can not work correctly in `node`

in XHR we can 

```
axios.get('/user', {
    params: {
      ID: 12345
    }
  })
  .then(function (response) {
    console.log(response);
  })
```
but in node, it can't serizlier params into url parameters automatically.

**Comment by carloschida** [comment]
In `axios@0.19.2` it works as expected:

```js
var axios = require("axios");

axios
  .get("https://jsonplaceholder.typicode.com/posts", {
    params: {
      userId: 1
    }
  })
  .then(function(response) {
    console.debug(response.request._header);
  });
```

Prints:
```
GET /posts?userId=1 HTTP/1.1
Accept: application/json, text/plain, */*
User-Agent: axios/0.19.2
Host: jsonplaceholder.typicode.com
Connection: close
```

Can you try to replicate this? And if it's not the same output, could you provide us with some more details about your setup and/or a sandbox?

**Comment by tianyingchun** [comment]
this issue is wrong report, it works fine, :)
