### ISSUE TITLE
 Error: Network Error

### ISSUE THREAD

**Issue by vikil143** [axios/axios#2998]
In my react native app getting this error on catch same **API** working fine in web as well as postman
i m fetch some data from backend using below code 

axios('URL',{
data,
method:"POST",
headers:headers
})
.then(response => {
console.log('Response, response);
// code

})
.catch(error => {
 console.log('ERROR ', error);
 // code

    });

It not even getting any data on error.response(it undefined) some code working fine for other api

Backend: Node js,
Mobile Tech: React Native

Please help 

Thanks in advance

**Comment by lugodchristian** [comment]
Edit file in project/android/app/src/main/java/com/{your_app}/MainApplication.java

```
@Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    // initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); <- comment this
  }
```

**Comment by catmans1** [comment]
> Edit file in project/android/app/src/main/java/com/{your_app}/MainApplication.java
> 
> ```
> @Override
>   public void onCreate() {
>     super.onCreate();
>     SoLoader.init(this, /* native exopackage */ false);
>     // initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); <- comment this
>   }
> ```

It still happen Network Error, any other solutions?

**Comment by lugodchristian** [comment]
> > Edit file in project/android/app/src/main/java/com/{your_app}/MainApplication.java
> > ```
> > @Override
> >   public void onCreate() {
> >     super.onCreate();
> >     SoLoader.init(this, /* native exopackage */ false);
> >     // initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); <- comment this
> >   }
> > ```
> 
> It still happen Network Error, any other solutions?

use https

**Comment by catmans1** [comment]
if use https it will better. but the server side still use http, so do you have any idea for that?

**Comment by vikil143** [comment]
> Edit file in project/android/app/src/main/java/com/{your_app}/MainApplication.java
> 
> ```
> @Override
>   public void onCreate() {
>     super.onCreate();
>     SoLoader.init(this, /* native exopackage */ false);
>     // initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); <- comment this
>   }
> ```

i commented this line still getting error and also i was using https still getting this error

**Comment by lugodchristian** [comment]
> > Edit file in project/android/app/src/main/java/com/{your_app}/MainApplication.java
> > ```
> > @Override
> >   public void onCreate() {
> >     super.onCreate();
> >     SoLoader.init(this, /* native exopackage */ false);
> >     // initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); <- comment this
> >   }
> > ```
> 
> i commented this line still getting error and also i was using https still getting this error

check the data that you are sending, the last time that was causing my error

**Comment by vikil143** [comment]
> > > Edit file in project/android/app/src/main/java/com/{your_app}/MainApplication.java
> > > ```
> > > @Override
> > >   public void onCreate() {
> > >     super.onCreate();
> > >     SoLoader.init(this, /* native exopackage */ false);
> > >     // initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); <- comment this
> > >   }
> > > ```
> > 
> > 
> > i commented this line still getting error and also i was using https still getting this error
> 
> check the data that you are sending, the last time that was causing my error

your right it was data sending issue i was solve by JSON.stringfy(data)

**Comment by vikil143** [comment]
actually i m  pass array of values convert that into JSON.stringfy

**Comment by vauruk** [comment]
I have the same problem, i dont know what to do  in 3 days ! 
my error is: [Error: Network Error] in Android , my path rest é HTTPS, 
Anybody any solution, i dont know to do ! 

tks
