### ISSUE TITLE
Certificate Transparency Implementation Support

### ISSUE THREAD

**Issue by KPS250** [axios/axios#2999]
I went through the filed issues regarding SSL/Certificate pinning but its doesn't indicate any help on how to implement it using axios.

I am using axios in my React Native App and need to implement SSL/TLS Security mechanism to prevent of man in the middle attacks. Going through the blogs and google documentation I got to know that Certificate Transparency is way better than SSL Pinning. Want to check if axios support Certificate transparency or SSL Pinning.

Certificate Transparency Reference: [http://www.certificate-transparency.org/](url)

**Comment by jasonsaayman** [comment]
Hi,

I don't think this is related to Axios, you don't implement SSL in Axios.

Thanks
