### ISSUE TITLE
http not posting data in node

### ISSUE THREAD

**Issue by geddski** [axios/axios#3]
``` js
axios({ 
  url: 'http://requestb.in/ubgv1aub',
  data: { test: true }
})
```

successfully posts but the request body is empty. Probably missing some headers, but setting Content-Type and Content-Length manually cause axios to hang for some reason.

**Comment by faztp12** [comment]
@mzabriskie 
Everything works fine on browser,
but do not have POST payload on node

It started working once i manually specified `Content-Type: application/json`
Please have this documented / fixed for future devs :)
