### ISSUE TITLE
Types: export Axios class

### ISSUE THREAD

**Issue by gi** [axios/axios#3000]
**Is your feature request related to a problem? Please describe.**
The type definitions do not include the Axios class, yet it is exported/exposed:
https://github.com/axios/axios/blob/487941663b791a4a5273d456aab24c6ddd10eb0e/lib/axios.js#L32

**Describe the solution you'd like**
Update the type definitions to expose the Axios class on the AxiosStatic object type.

**Describe alternatives you've considered**
Manual definition is an option but always a work-around.

**Additional context**
none

**Comment by ArrayKnight** [comment]
https://github.com/axios/axios/pull/2872
