### ISSUE TITLE
CancelToken causes memory leak if re-used for multiple requests

### ISSUE THREAD

**Issue by barryspearce** [axios/axios#3001]
Obtaining a cancel token (as per the Axios documentation on github) and re-using it across many requests results in a major memory leak as the payload for each request is not freed.

I am transferring large files - from 3 GB to 100GB using a chunked protocol and 20MB requests. The memory fills and remains until the cancel token reference is removed. Using the same code but not setting the cancel token in the config resolved the issue.

Creating a cancel token for each and every single request individually and removing the reference to the cancel token achieves the expected behaviour and frees the request payload memory.

Simple use of chrome dev tools and memory profile shows the cancel token as holding the memory, also reflect in process stats using top.

This is not using the global axios but an instance.

Previously reported in #1118 but it is unclear if this was properly resolved. 

Axios 0.19.2
OS Linux
Browsers: Firefox 76.0, Opera 68.0.3618.63, Chromium 81.0.4044.129

**Comment by jasonsaayman** [comment]
Hi,

I think #1118 is possibly the wrong issue? Other than that I think we should have a look at this.

Thanks

**Comment by barryspearce** [comment]
You are right Jason - Sorry it was #1181

**Comment by gegana** [comment]
I recently encountered this issue as well on my React Native application. Our application downloads pages of data sequentially because it is an offline first app. Our findings indicate that as long as the cancel token source (even if you construct a new one each time) lives within a scope of an object or function that is long lived, the GC will have trouble releasing the memory handles from axios request & response.

With cancel token, notice the cliff towards the end, that is because the React component re-rendered.
![image](https://user-images.githubusercontent.com/1734059/89057128-1fdf3e00-d32b-11ea-83f5-1bd7a531600d.png)


Without cancel token, notice how GC is doing its job.
![image](https://user-images.githubusercontent.com/1734059/89057160-338aa480-d32b-11ea-98aa-6e23ea9280d9.png)

**Axios 0.19.2**
**OS**: iOS 13.6, Android 6 to 10

**Comment by yizhengfeng-jj** [comment]
Hello, according to your method seems to be useless, is my writing wrong, hope to get a reply, thank you very much

```javascript
// request
config.cancelToken = new cancelToken(cancel => {
  source[request] = cancel;
})

// resonse
interceptors.response.use(response => {
 source[request] = null
})
```

**Comment by yizhengfeng-jj** [comment]
> Obtaining a cancel token (as per the Axios documentation on github) and re-using it across many requests results in a major memory leak as the payload for each request is not freed.
> 
> I am transferring large files - from 3 GB to 100GB using a chunked protocol and 20MB requests. The memory fills and remains until the cancel token reference is removed. Using the same code but not setting the cancel token in the config resolved the issue.
> 
> Creating a cancel token for each and every single request individually and removing the reference to the cancel token achieves the expected behaviour and frees the request payload memory.
> 
> Simple use of chrome dev tools and memory profile shows the cancel token as holding the memory, also reflect in process stats using top.
> 
> This is not using the global axios but an instance.
> 
> Previously reported in #1118 but it is unclear if this was properly resolved.
> 
> Axios 0.19.2
> OS Linux
> Browsers: Firefox 76.0, Opera 68.0.3618.63, Chromium 81.0.4044.129

Hello, according to your method seems to be useless, is my writing wrong, hope to get a reply, thank you very much

```javascript
// request
config.cancelToken = new cancelToken(cancel => {
  source[request] = cancel;
})

// resonse
interceptors.response.use(response => {
 source[request] = null
})
```

**Comment by r3c** [comment]
This issue also causes leak of the entire memory used for request & response when assigning a default `CancelToken` to config defaults, which makes this API quite error-prone:
```typescript
instance.defaults.cancelToken = new axios.CancelToken((canceler) => { /* anything */ });

// Now every request sent through `instance` will leak memory because of the unique token (unless they override it)
```
It seems @DigitalBrainJS's #3305 nicely fixes the issue. Is there any chance to get it accepted & released? 🙏
