### ISSUE TITLE
How to measure the response size in bytes?

### ISSUE THREAD

**Issue by Legi0n1138** [axios/axios#3003]
Hello!

I need to measure the:
1) total response size (payload, headers, etc)
2) payload size

The server doesn't send the 'content-length' header.
Environment: React Native app.

How can I achieve this with axios?

**Comment by chinesedfan** [comment]
Users can measure by themselves. Once you got the payload/response, just use APIs like `str.length`.

**Comment by Lambo-555** [comment]
@chinesedfan headers can contain field called **'content-length'**.

You can get it and convert to number:
`const resSize = +result?.headers?.['content-length'];`
