### ISSUE TITLE
Is there any way of making a request with allow-script enabled?

### ISSUE THREAD

**Issue by markito12** [axios/axios#3007]
**Describe the issue**
Enabling allow-script (allow javascript) when fetching an external url

**Example Code**
Code snippet to illustrate your question

```js
await axios.get('https://www.site.domain/user..')
```

**Expected behavior, if applicable**
not getting "enable javascript".

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. Windows 10]
 - Browser [Chrome]
 - Browser Version [83.0.4103.97]
 - Additional Library Versions [..]

**Comment by chinesedfan** [comment]
Can you give a screenshot of the response panel?
