### ISSUE TITLE
HttpsProxyAgent not working on version 0.19.2

### ISSUE THREAD

**Issue by bswhb** [axios/axios#3008]
**Describe the bug**
In an Electron based app, we're using [HttpsProxyAgent](https://github.com/TooTallNate/node-https-proxy-agent) v4.0.0 with Axios to implement proxy mechanism. It used to work on Axios v0.19.0, but right now failed after upgraded to v0.19.2. No network data is re-directed to the proxy as defined.

All the codes and configurations are the same, except the Axios version upgrade. We found it seems the proxy settings are ignored by Axios, no matter the settings are correct or not. We've also tested against both http proxy and https proxy, with the same results.

**To Reproduce**
```js
    const agent = new HttpsProxyAgent(
      {
        host: store.state.Settings.connection.proxy.host,
        port: store.state.Settings.connection.proxy.port,
        auth: `${store.state.Settings.connection.proxy.username}:${store.state.Settings.connection.proxy.password}`,
        rejectUnauthorized: false
      }
    )
    options.httpAgent = agent
    options.httpsAgent = agent

    const response = await axios(options)
```

**Expected behavior**
HttpsProxyAgent can work as before.

**Environment:**
 - Axios Version: 0.19.2
 - OS: Windows 10 & macOS 10.15
 - Electon: 8.2.2

**Comment by hyurl** [comment]
I think the proper usage would be

```js
    const agent = new HttpsProxyAgent(
      {
        host: store.state.Settings.connection.proxy.host,
        port: store.state.Settings.connection.proxy.port,
        rejectUnauthorized: false
      }
    )
    options.httpAgent = agent
    options.httpsAgent = agent
    
    if (store.state.Settings.connection.proxy.auth) {
         let { username, password } = store.state.Settings.connection.proxy.auth;
         let base64 = Buffer.from(username + ":" + password, "utf8")
             .toString("base64");
         (options.headers || (options.headers = {}))["Proxy-Authorization"] = "Basic " + base64;
   }
```

Hoping Axios can ship **HttpsProxyAgent** internally in the next version.

**Comment by rbcMatt** [comment]
Same here, burp suite is throwing an error 

```1595861414296 | Error | Proxy | [52]  Invalid client request received: First line of request did not contain an absolute URL - try enabling invisible proxy support.
-- | -- | -- | --
```

**Comment by dinojs** [comment]
Facing similar issues

**Comment by mychenjun** [comment]
Facing similar issues

Environment:
Axios Version: 0.21.1
HttpsProxyAgent Version: 4.0.1
OS: Windows 10
Electon: v11.4.2

**Comment by knownasilya** [comment]
Seeing similar things with the native node http/https agent when using `axios.create` in 0.21.1.

The created instance doesn't seem to use the agent, I still have to set the `httpsAgent` on each request instead.
