### ISSUE TITLE
I am trying to send a report using HTTP post request. But am not able to do it

### ISSUE THREAD

**Issue by VinothArasu** [axios/axios#3010]
**Below is my code**

var FormData = require('form-data');
var fs = require('fs');

var form = new FormData();
form.append('photo', fs.createReadStream("../../data/ExistingKpiUpload.xlsx"));

var abc = await HTTP.get('https://sta.qdk.dev.aws.renault.com/api/qlc/hello/Vinoth')
console.log(abc)

HTTP.post("https://sta.qdk.dev.aws.renault.com/api/qlc/posttestfile" , form);
console.log(form.getHeaders());

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios#form-data. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
