### ISSUE TITLE
Axios returns 404 for live, valid URL

### ISSUE THREAD

**Issue by asklar** [axios/axios#3011]
**Describe the bug**
Axios returns 404 for a valid URL. The error/promise rejection contains a data field with what seems to be the webpage. The URL is valid and can be reached via a browser or PostMan.

**To Reproduce**
```js
const axios = require('axios').default;
const url = 'https://mybuild.microsoft.com/sessions/b1306a79-b43b-43be-bd59-460b8db0c7a8';
axios.get(url).then((e) => { console.log(e) }).catch((e) => { console.log(e) })
```

**Expected behavior**
No 404 error, request succeeds

**Environment:**
 - Axios Version "^0.19.2"
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 83.0.4103.97
 - Additional Library Versions: none

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/22989529/84317787-3da9d700-ab22-11ea-982b-b53dc29f8c83.png)

![image](https://user-images.githubusercontent.com/22989529/84317833-4e5a4d00-ab22-11ea-9d1d-94247c8d30e5.png)

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by asklar** [comment]
@chinesedfan this really seems like an Axios issue, as `request` can get fetch this URL without any problems:

Axios (fails):
```js
var axios = require('axios');

var config = {
  method: 'get',
  url: 'https://mybuild.microsoft.com/sessions/b1306a79-b43b-43be-bd59-460b8db0c7a8 ',
  headers: { }
};

axios(config).then(function (response) {
  console.log(JSON.stringify(response.data));
}).catch(function (error) {
  console.log(error);
});
```

using request (succeeds):
```js
var request = require('request');
var options = {
  'method': 'GET',
  'url': 'https://mybuild.microsoft.com/sessions/b1306a79-b43b-43be-bd59-460b8db0c7a8 ',
  'headers': {
  }
};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
```

**Comment by chinesedfan** [comment]
> A quick solution is that checking url and request headers and comparing with other ways when you can get the right response.

Please compare and find the reasons.

**Comment by rekha-emids** [comment]
i'm also facing this issue. Most of the times axios returning 404 and in very rare conditions it's giving api response. Please help

**Comment by wytrych** [comment]
Similar thing here. You can try this very simply by doing
`curl -I https://www.soundtrap.com` -> 200
`axios.get("https://www.soundtrap.com")` -> 404

**Comment by SpaceCityCowboy88** [comment]
Not to beat a dead horse but I have noticed the same. ;)

**Comment by DigitalBrainJS** [comment]
@wytrych The problem is how the server handles the Accept header:
```js
// fail - default axios header
const {data} = await axios.get("https://www.soundtrap.com/",  {
    headers: {
      "Accept": "application/json, text/plain, */*",
    }
  });

// works
const {data} = await axios.get("https://www.soundtrap.com/",  {
    headers: {
      "Accept": "*/*, application/json, text/plain",
    }
  })
// works
const {data} = await axios.get("https://www.soundtrap.com/",  {
    headers: {
      "Accept": "text/html",
    }
  })
```
So this doesn't seem to be an Axios issue.

**Comment by TylerJGabb** [comment]
so what needs to be reconfigured in the server?

**Comment by yobotn** [comment]
any updates?

**Comment by Heimlet** [comment]
I was figuring out the reason for 1 hour and already thought I gone crazy, but

removing "axios-mock-adapter": "^1.22.0",
from package.json dependencies helped me.

With this library it always returned 404 error.

**Comment by somniack** [comment]
> I was figuring out the reason for 1 hour and already thought I gone crazy, but
> 
> removing "axios-mock-adapter": "^1.22.0", from package.json dependencies helped me.
> 
> With this library it always returned 404 error.

This was so my issue, somehow it was blocking the api calls to my local fastapi endpoint.
