### ISSUE TITLE
Property 'get' does not exist on type 'typeof Axios'.

### ISSUE THREAD

**Issue by Ich-bin-naoya** [axios/axios#3012]
Whan I use axios with TypeScript, I got this error

```
Property 'get' does not exist on type 'typeof Axios'.
```
I tried  some solutions like here but I still get above error
- https://github.com/axios/axios/issues/2145 

And my code is like this

``` tsx
import React from 'react'
import axios from "axios";

class Home extends React.Component {
  constructor(props:any) {
    super(props)
  }

  componentDidMount() {
    axios.get("url").then((res:any) => console.log(res,"res"))
  }

  render() {
    return <SomeComponents/>
  }
}

export default Home
```

Any Solution?

**Comment by Alanscut** [comment]
@Ich-bin-naoya I did not have this problem, please tell me the version you are using.
> version
axios@^0.19.2

<img width="453" alt="issue_3012" src="https://user-images.githubusercontent.com/21104054/84460142-bc764f80-ac9b-11ea-9284-995db632dd7e.png">

**Comment by Ich-bin-naoya** [comment]
@Alanscut 
My version is "axios": "^0.19.2" .
It is the same as yours

**Comment by Alanscut** [comment]
@Ich-bin-naoya Please tell me the configuration of your `tsconfig.json`.
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}

```

**Comment by Ich-bin-naoya** [comment]
My tsconfig.json is here
```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": true,
    "module": "es6",
    "target": "es5",
    "jsx": "react",
    "allowJs": true,
    "allowSyntheticDefaultImports": true
  }
}
```

**Comment by Ich-bin-naoya** [comment]
@Alanscut 
When I put "moduleResolution": "node" in to tsconfig, it fixed.

But I don't know why

**Comment by Alanscut** [comment]
Please check the official website.
https://www.bookstack.cn/read/basarat-typescript-book/docs-project-module-resolution.md

**Comment by rvrita** [comment]
I fixed this by using `import { default as axios } from 'axios'`.

**Comment by araujoleonardo310** [comment]
Thanks, @rvrita. 
Your solution helped me with my bootcamp project.
I found your solution cleaner than responses others.

**Comment by mohameds93** [comment]
I got it working by using `  import * as axios from "axios";`

**Comment by SmartArray** [comment]
> @Alanscut When I put "moduleResolution": "node" in to tsconfig, it fixed.
> 
> But I don't know why

Weird, `nodenext` seems to cause troubles (but only sometimes)

**Comment by mattkrins** [comment]
Same issue, thanks for the fix @rvrita

**Comment by bennycode** [comment]
I also ran into the same error:

> error TS2339: Property 'get' does not exist on type 'typeof import("/home/bennycode/dev/bennycode/coinbase-pro-node/node_modules/axios/index")'

Using axios v0.27.2

It happened when changing from:

```json
    "module": "commonjs",
    "moduleResolution": "node",
```

To:

```json
    "module": "Node16",
    "moduleResolution": "Node16",
```

Using TypeScript v5.2.2
