### ISSUE TITLE
I am getting error when using processEnv and axios with React in local environment?

### ISSUE THREAD

**Issue by jetro4u** [axios/axios#3013]
In my .env file, I have: ```REACT_APP_API_BASE_URL=http://localhost:8080/api/v1.0```

At the top of my React form, I imported axios and have baseUrl defined as: 

```axios.defaults.baseURL = process.env.REACT_APP_API_BASE_URL```

The in my onSubmit function, I use axios as:

```
const onSubmit = async (e) => {
        e.preventDefault();
        console.log(">>>>>", formData);
        const data = await axios({
        method: 'post',
        url: '/countries',
        data: qs.stringify(formData),
        headers: {
        'content-type': 'application/x-www-form-urlencoded;charset=utf-8'
        }
        }).then(res => {
        console.log(res);
        alert('Form submitted!');
        return res;
        }).catch(error => {
        console.log(error);
        alert('Your form was not submitted! Please try again later.');
        });
    }
```

When I submit through a React form on ```localhost:3000```, the form will throw an error. I will get the formData console logged but with the following error: 
```
xhr.js:178 POST http://localhost:3000/countries 404 (Not Found)

CountryForm.js:51 Error: Request failed with status code 404
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:61) 
```
Meanwhile my backend API listen at port 8080.  When I replaced the ```process.env.REACT_APP_API_BASE_URL``` with the actual value of the baseurl i.e.
```http://localhost:8080/api/v1.0```, the form will submit through the frontend. The form submit normal through Postman.

So, it appears the frontend can't read the value of the ```process.env.REACT_APP_API_BASE_URL```

**Comment by jetro4u** [comment]
Figure out i have to run the React server again.  But will I be able to use the baseUrl stored when I move to production?

**Comment by jasonsaayman** [comment]
Hi,

I think you will need to inject the env variable when compiling. But this is not an Axios issue so I am closing it for now.

Thanks

**Comment by srinatsrinat** [comment]
Hi, I have the same error with my react app. What is the solution to this? Somebody please help I have been trying to resolve this for nearly two days now and been unsuccessful so far.
