### ISSUE TITLE
Accessing JSON file as GET is successful, but POST is returning 404

### ISSUE THREAD

**Issue by ramondsf92** [axios/axios#3015]
I'm trying to use Axios to test my data management on my Vue.js app. I'm able to do the `axios.get()`, but the `axios.post()` is returning a 404 error, indicating the JSON file was not found.

Here is how my Vue component script seems like:

```
<script>
import axios from "axios";

export default {
  name: "App",
  data() {
    return {
      title: "Códigos FGO",
      accounts: null
    };
  },
  methods: {
    getAccounts() {
      axios
        .get("./json/accounts.json")
        .then(json => (this.accounts = json.data));
    },
    postAccount(acc) {
      axios
        .post("./json/accounts.json", acc)
        .then(response => console.log(response));
    }
  },
  created() {
    this.getAccounts();
    console.log("Foi");
    this.postAccount({
      id: 3,
      code: "TesteAxiosComponent",
      server: "NA",
      ssr: 5,
      notable: [
        {
          name: "Ramon",
          level: 100,
          npLvl: 5
        }
      ]
    });
  }
};
</script>
```

**Environment:**
 - Axios Version 0.19.2
 - OS: Pop!_OS 20.04
 - Browser Chrome
 - Vue.js 2.6.11

EDIT: Please ignore the duplicated error, it was made because I saved the file without refreshing the page.
![image](https://user-images.githubusercontent.com/32439550/84417363-e3754880-abeb-11ea-91ee-d1d0ce2e5feb.png)

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by wenzi0github** [comment]
in post request, data must be querystring, not object

```javascript
postAccount(acc) {
    axios
    .post("./json/accounts.json", {
        data: qs.stringify(acc) // like a=1&b=2&c=3
    })
    .then(response => console.log(response));
}
```

**Comment by Pavreally** [comment]
I had this problem (Vue CLI). The json server installation helped me.

The solution to this problem:
1. Install json-server globally: **npm install json-server -g**
2. Go to the folder with the desired json file using the command line.
3. Run command: **json-server Filename.json**

After executing the command, a hint will appear on how to access the json file. And now you can send data: 
```javascript
postAccount(acc) {
      axios
        .post("http://localhost:3000/accounts", acc);
}
```

More details can be found here: [Link](https://developer.school/how-to-use-vue-js-json-server-and-axios/)
