### ISSUE TITLE
Headers merge stragety for custom instance

### ISSUE THREAD

**Issue by ylc395** [axios/axios#3020]
```js
myAxios = axios.create({
    headers: {
        token: 'old';
    },
});

myAxios.defaults.headers.common.token = 'new';

myAxios.get(url);
```
With code above, what is the correct header `token` of the get request？Should it be `'old'` or `'new'`? According to the [document](https://github.com/ylc395/axios#custom-instance-defaults), it seems that `'new'` is the correct value in theory, but it's `'old'` in fact. Is it a bug?

**Comment by chinesedfan** [comment]
> myAxios.defaults.headers.common.token = 'new';

Set it before `axios.create`.
