### ISSUE TITLE
`utils.isFormData` doesn't working expectation on `Node` env

### ISSUE THREAD

**Issue by TheNorthMemory** [axios/axios#3023]
As of the `README.md` described, I've been tried the [form-data](https://github.com/form-data/form-data) in the project [wechatpay-axios-plugin](https://github.com/TheNorthMemory/wechatpay-axios-plugin), this `utils.isFormData` returns `false`. I'm also checked #323, the changes(`typeof FormData`) should only working on `isStandardBrowserEnv`. The `Node` environment hadn't the global `FormData` object currently.

```js
const FormData = require('form-data');
const form = new FormData();
assert.ok(utils.isFormData(form));//thrown assert error on Node Env
```

**Expected behavior**
Here should be a checker function on `Node` env.

**Environment:**
 - Axios Version: 0.19.2
 - OS: OSX 19.5.0
 - Node: 14.4.0

**Comment by chinesedfan** [comment]
`utils.isFormData` is not a public API of axios. Can you tell me why you need it?

**Comment by TheNorthMemory** [comment]
It's used for uploading file by `Node`. Things like using the `form-data` node module does.

The following L34 should returns the `right` checking result, but that wasn't.
https://github.com/axios/axios/blob/36f0ad2f985c3289018f0fdaaddf309cc9458d9b/lib/defaults.js#L31-L42

**Comment by chinesedfan** [comment]
In fact, `form-data` is different with `FormData` in the browser. So `utils.isFormData` works as expected.

You can set your own `transformRequest` to make the `data` is returned. Don't expect the default `transformRequest` covers everything.

**Comment by TheNorthMemory** [comment]
Yep. I see. In my opinion, it should point out `utils.isFormData` works correct under  `isStandardBrowserEnv` at least. Otherwise, checking in the `webworker` env should also  returned `false`.

**Comment by chinesedfan** [comment]
@TheNorthMemory So, what can axios help? Add something in document or comments in code? Suggestions welcome.

**Comment by TheNorthMemory** [comment]
@chinesedfan Ah... The advise already shown. Thank you. I'll close this one later.
