### ISSUE TITLE
On error in interceptors.response response is undefined

### ISSUE THREAD

**Issue by AdelinaUwU** [axios/axios#3026]
**Describe the issue**
In interceptors response is undefined

**Example Code**
```js
instance.interceptors.response.use((response) => {
  console.log(response)
  return response
}, (error) => {
    console.log(error.response)
    switch(error.response.status) {
      case 401:
        alert('Unauthorized')
        break
      case 500:
        alert('Critical')
        break
      default:
    }
    return Promise.reject(error.message);
})
```

**Expected behavior, if applicable**
error.response will be the same as with error 401

**Environment:**
 - Axios 0.19.2
 - Arch linux lastest
 - Firefox ESR
 - 68.9
 - React 16.13.1

**Additional context/Screenshots**
But request is present, but in it the code is 0

**Comment by chinesedfan** [comment]
Closed due to not reproducible. If you find the issue is still there, feel free to remind me to reopen with more information.

**Comment by samuk190** [comment]
I have the same problem @chinesedfan  but i'm using axios retry as interceptor, it happened when I upgraded my RN0.61 to RN 0.63.1
when user don't have network, instead of giving network error it says undefined

**Comment by chinesedfan** [comment]
@samuk190 So how about opening an issue to RN? Something must be changed, which is related to XHR. Not only axios, but also other request libraries may be affected.

**Comment by samuk190** [comment]
> @samuk190 So how about opening an issue to RN? Something must be changed, which is related to XHR. Not only axios, but also other request libraries may be affected.

agreed! Now I'm not be able to get response.status on error, instead i can only get (error.message)

**Comment by Haibinkhb** [comment]
我在使用 vue 和 axios 开发单页面应用时遇到同样的问题

版本：
 "axios": "^0.19.2",
"vue": "^2.6.11"

并且只有在chrome中能拿到 error.response，其他浏览器中 error.response 都是 undefined。
@chinesedfan

**Comment by Haibinkhb** [comment]
> 我在使用 vue 和 axios 开发单页面应用时遇到同样的问题
> 
> 版本：
> "axios": "^0.19.2",
> "vue": "^2.6.11"
> 
> 并且只有在chrome中能拿到 error.response，其他浏览器中 error.response 都是 undefined。
> @chinesedfan

已解决。打开代理就行了...

**Comment by 2xSamurai** [comment]
Any update on this issue? I am also facing the same.
