### ISSUE TITLE
Why does Axios not encode all reserved characters?

### ISSUE THREAD

**Issue by jer231** [axios/axios#3027]
Seems that Axios is using encodeURIComponent, then undoing some of its effects by doing character replacement on a set of reserved characters (according to RFC3986). In our case this caused some unexpected failures as a network load balancer was rejecting URL's with queries that contained what it considered any 'unsafe' characters, in this case a $ sign. What is the logic behind undoing the encoding of these reserved characters? Seems that it would be safer to just let encodeURIComponent do its thing and trust the browser vendor to keep up with the RFC! Better to encode any reserved characters I think since any server will decode any % encoding regardless. It might be rare case that an un-encoded $ sign for example will cause failures, but we ran into one and I'll bet there are others out there.

In /lib/helpers/buildURL.js:

```js
function encode(val) {
  return encodeURIComponent(val).
    replace(/%3A/gi, ':').
    replace(/%24/g, '$').
    replace(/%2C/gi, ',').
    replace(/%20/g, '+').
    replace(/%5B/gi, '[').
    replace(/%5D/gi, ']');
}

```

**Comment by swillis12** [comment]
Hitting this as well and wondering the same thing. 👍  Good catch @jer231

**Comment by mdebeus** [comment]
You can always provide your own params encoder via paramsSerializer.

**Comment by jasonsaayman** [comment]
Please test again with the latest version, if this is still an issue please open a new issue.
