### ISSUE TITLE
Request Abortion on Click Event

### ISSUE THREAD

**Issue by miladkhorramian** [axios/axios#3030]
**Describe the issue**
Hi. I have been Axios for a little while now and recently, I have been facing a problem.
If I make a request over click event, the request get aborted even though i have no problem when i 
do the requesting without the event. I should say that i am using jsdelivr on tag in my html.

Log:
```
Error: "Request aborted"
    exports https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js:2
    onabort https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js:2
```

**Example Code**
Code snippet to illustrate your question

```js
document.getElementById('someID').addEventListener('click',{
      axios.get('https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js')
            .then(res=>console.log(res))
            .catch(err => console.error(err));
});
```
**Environment:**
 - Axios Version [e.g. 0.19.2]
 - OS: [Windows 10, 19041.264]
 - Browser [Firefox, Chrome, Brave, etc]
 - Browser Version [Lately Installed]

**Comment by miladkhorramian** [comment]
Thanks for labling

**Comment by Aaron-Pool** [comment]
@miladkhorramian been having a similar issue. Were you able to find a solution?

**Comment by miladkhorramian** [comment]
Yeah i guess i sorted it out.

**Comment by Aaron-Pool** [comment]
> Yeah i guess i sorted it out.

Do you know what fixed it? Or did it just stop happening?
