### ISSUE TITLE
axios get call with create instance doesn't work with CORS

### ISSUE THREAD

**Issue by bsienn** [axios/axios#3039]
#### Describe the issue
axios cross domain calls work with axios object directly but not when instance is created

#### Example Code
Code snippet to illustrate your question

### This does not work and returns CORS error
```js
import axios from 'axios'
const cfc = axios.create({
  baseURL: 'http://localhost:8500/ESH/cfcs/',
  headers: { pragma: 'no-cache' }
})

//Gestion questions

export function getQuestions(params) {
  return cfc
    .get('GestionQuestion.cfc?method=getGestionQuestionGrid')
    .then(successHandler)
    .catch(errorHandler)
}
```

### This works (no instance)
```js
import axios from 'axios'
export function getQuestions(params) {
  return axios
    .get('GestionQuestion.cfc?method=getGestionQuestionGrid')
    .then(successHandler)
    .catch(errorHandler)
}
```

#### Expected behavior, if applicable
with instance it should have worked same as non instance call

#### Environment
 - Axios Version [0.19.2]
 - Browser [e.g. Chrome, FF]
 - Browser Version [FF 77.0.1]

#### Additional context/Screenshots
N/A

**Comment by lopesboa** [comment]
same here...

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response.

**Comment by bsienn** [comment]
I'm sorry, I had a little accident, and won't be able to check or provide further details in few days.

**Comment by daweiyong** [comment]
我也遇到了同样的问题，请问解决了吗

**Comment by bsienn** [comment]
> 我也遇到了同样的问题，请问解决了吗

不，它没有解决，所以我继续使用而不使用它

**Comment by daweiyong** [comment]
尝试过升级版本吗，升级到0.21还存在同样的问题吗

**Comment by bsienn** [comment]
从那以后我没有尝试过。您仍然有这个问题。您必须使用新版本，不是吗？

**Comment by daweiyong** [comment]
我周一去公司试一下升级版本，如果可以我告诉您

**Comment by bsienn** [comment]
我想您知道我正在使用Google Translator哈哈。有空的时候我也会再次检查。

**Comment by bsienn** [comment]
So I found something that might be helpful.

When I make request with axios object, it send OPTIONS request and the server returns correct origin headers etc.
But when I use the `axios.create` object, the OPTIONS request does not come back with origin headers. Hence causing the CORS error.

I've updated axios to the latest version as well.

This is definitely not server issue as the CORS are set properly on back end.

@daweiyong 
@chinesedfan

**Comment by chenbr17** [comment]
I'm using vite and react, remove `baseURL' in axios.create config helps me avoid this error. Instead of using baseURL, I use vite.config to configure proxy target.

**Comment by bsienn** [comment]
@chenbr17 1st thanks for letting me know about vite, I've been away from vue for quite some time so didn't notice that, nice tool. 
2nd can you give an example in vuejs if possible? I'm not very technical and this issue seemed quite strange that this happens and not mentioned in docs.
