### ISSUE TITLE
Upgrade from 0.18.1 to 0.19.X breaks

### ISSUE THREAD

**Issue by chachew** [axios/axios#3041]
#### Describe the issue
I have a working system using Axios 0.18.1. This is a Vuejs application and im creating Axios instances using axios.create(); This works great, but when i upgrade Axios to 0.19.X everything breaks. NOTHING gets thrown in the browser console and no requests are even logged in the browser network tab. So its not even attempting to make the http request anymore. There must be a breaking change that i'm missing.

#### Example Code
Code snippet to illustrate your question

```js
import axios from 'axios';

const client = axios.create({
  baseURL: 'http://www.example.com',
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json'
  }
});

client.get('/myEndpoint'); // previously this worked in 0.18.1....Since 0.19.X nothing works. NO calls are ever made.
```

#### Expected behavior, if applicable
HTTP connections should work as before in 0.18.1

#### Environment
Axios Version: 0.18.1, 0.19.2
Browser: Chrome
Browser Version: Latest
Node.js Version: 10.15.3, 12.18.1
OS: Windows 7 and Windows 10

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It's impossible that v0.19 breaks everything so that no requests are send. A quick solution is that checking **url** and **request headers** and comparing with other ways(v0.18) when you can get the right response.

**Comment by usuf16** [comment]
Same issue v0.18 works perfect but in v0.19 frequently through Network error
