### ISSUE TITLE
Create  a Table of Content for README.md

### ISSUE THREAD

**Issue by NotMoni** [axios/axios#3047]
#### Is your feature request related to a problem? Please describe.

We need a TOC for README.md as its very long and hard to navigate.

#### Describe the solution you'd like

Create a Table of Content with hyperlinks

#### Describe alternatives you've considered

N/A

#### Additional context

N/A

**Comment by Frostack** [comment]
Can i work on this?

**Comment by jasonsaayman** [comment]
@Frostack sure please

**Comment by NotMoni** [comment]
I also wanted to work on it, but didnt make a pr before asking you guys first. @Frostack Can I help you ?

**Comment by Frostack** [comment]
Sure I'd be happy to help anyway and it's my first contribution, how can we collaborate?

**Comment by NotMoni** [comment]
@Frostack I've invited you to my fork of Axios. We should work on the `toc` branch
