### ISSUE TITLE
params defined in instance config are not working

### ISSUE THREAD

**Issue by joba-sprd** [axios/axios#3048]
#### Describe the bug
The ```params``` values which i defined while creating a new instance are not part of the request. 

#### To Reproduce
I created a minimal example: https://jsfiddle.net/oqfract9

```js
const instance = axios.create({
  baseURL: 'https://jsonplaceholder.typicode.com/',
  timeout: 1000,
  params: {
    "userId": "1"
  }
});

instance
.get("/posts")
.then(function (response) {
    console.log(response.data);
    console.log(response.status);
    console.log(response.statusText);
    console.log(response.headers);
    console.log(response.config);
  });
```

#### Expected behavior
I would expect that the ```?userId=1``` is part of the request. 

#### Environment
 - Axios v0.19.2
 - Chrome v83.0.4103.106
 - Node.js v12.14.0
 - React v16.13.1

#### Additional context/Screenshots
I'm currently using the npm package, but it also doesn't work with CDN version.

**Comment by Frostack** [comment]
Duplicate of [#2190](https://github.com/axios/axios/issues/2190).

**Comment by chinesedfan** [comment]
Yes, please test with the master branch or https://github.com/axios/axios/tree/release/0.20.0-beta.1.

**Comment by TaylorDale** [comment]
This is still an issue, simultaneously also the worst and longest-running practical joke ever

**Comment by chinesedfan** [comment]
@TaylorDale Hi, did you try axios@next?

**Comment by TaylorDale** [comment]
> @TaylorDale Hi, did you try axios@next?

Is it production ready? Cheers
