### ISSUE TITLE
Axios ORG icon (logo)

### ISSUE THREAD

**Issue by NotMoni** [axios/axios#3062]
#### Is your feature request related to a problem? Please describe.
Nope, Axios need a ORG logo. 

#### Describe the solution you'd like
I can make one :D 

#### Describe alternatives you've considered
Someone else makes one.

#### Additional context
NaN

**Comment by chinesedfan** [comment]
Thanks for your interests. Let's track in #2130.

**Comment by NotMoni** [comment]
Oh awesome 👍
