### ISSUE TITLE
Add ability to encrypt/decrypt the request/response bodies using node crypto cipher/decipher objects

### ISSUE THREAD

**Issue by jhorbulyk** [axios/axios#3063]
#### Is your feature request related to a problem? Please describe.
Sometimes (in Node.js) I want to
1. Encrypt the entire body of a request before I send it ([using a `Cipher` object](https://nodejs.org/api/crypto.html#crypto_class_cipher))
2. Recieve HTTP responses which contain encrypted data which I want decrypted ([using a `Decipher` object](https://nodejs.org/api/crypto.html#crypto_class_decipher))

while making use of Axios features such as the ability to control `responseType` as well as `interceptors`.

#### Describe the solution you'd like
There are two new options in the `RequestConfig`:
* `Cipher`: [a `Cipher` object](https://nodejs.org/api/crypto.html#crypto_class_cipher) which if supplied will be used to encrypt the data in the request body before/as it is sent.
* `Decipher`: [a `Decipher` object](https://nodejs.org/api/crypto.html#crypto_class_decipher) which if supplied will be used to decrypt the data in the response body before it is provided back to user code.

#### Describe alternatives you've considered
* Using request/response interceptors to provide this encryption/decryption at that level.

The big problem with this approach is that request interceptors are applied before the response is converted to a byte array that can be encripted. Thus the code to apply encryption to a stream request vs an object request is quite different.  It would be easier if this transformation could be applied closer to the underlying `http` call. The inverse applies to response interceptors.

Additionally, this functionality is quite generic and so it might be beneficial to multiple people if this was included as a library feature.
#### Additional context
*None*

**Comment by chinesedfan** [comment]
We don't want to bind axios with Cipher/Decipher. Can your feature be achieved by `transformRequest` and `transformResponse`, which are closed to adapters than interceptors?

**Comment by jhorbulyk** [comment]
> Can your feature be achieved by transformRequest and transformResponse, which are closed to adapters than interceptors?

That might be possible.

**Comment by chinesedfan** [comment]
So can this issue be closed?
