### ISSUE TITLE
axios timeout is borken by follow-redirects bug

### ISSUE THREAD

**Issue by legokichi** [axios/axios#3068]
#### Describe the bug
`follow-redirects v1.5.10` has a bug which [setTimeout handler doesn't work](https://github.com/follow-redirects/follow-redirects/pull/107) used by `axios v0.19.2`

* https://github.com/axios/axios/blob/v0.19.2/package.json#L76
* https://github.com/axios/axios/pull/1752/files
* https://github.com/follow-redirects/follow-redirects/pull/107

please bump up follow-redirects to v1.7.0 or above

#### To Reproduce

```js
const axios = require("axios");
// 192.168.100.84 is a nonexistent host
axios.create({})({url:"http://192.168.100.84/", timeout:1000})
  .then(console.log)
  .catch(console.error);
```

#### Expected behavior
will get `timeout of 1000 ms exceeded` error

#### actual

got `ETIMEDOUT` error few minutes later 

#### Environment
 - Axios Version v0.19.2
 - Adapter HTTP
 - Node.js Version v12.13.1
 - OS: Ubuntu 20.04 LTS  5.4.0-39-generic x86_64

**Comment by chinesedfan** [comment]
See #2689 and https://github.com/axios/axios/issues/3009#issuecomment-649503739.
