### ISSUE TITLE
WKWebbview App getting Network error Cordova 9.0

### ISSUE THREAD

**Issue by cyrilxx** [axios/axios#3080]
#### Describe the bug
Since apple only accepts app with WKWebview App is getting Network error. But once I remove the WKWebview axios works fine is this a bug when axios is use innn WKWebview ? 

ERROR : {"message":"Network Error","name":"Error","stack":"createError@file:///Users/saylibarnes/Library/Developer/CoreSimulator/Devices/A5E6B67D-4CE6-4C54-AA7A-D3A713D8AFC4/data/Containers/Bundle/Application/3CF0C327-8A39-410D-8EDE-50B936C4A70A/MobileApp.app/www/scripts/axios.js:1201:25\nhandleError@file:///Users/test/Library/Developer/CoreSimulator/Devices/A5E6B67D-4CE6-4C54-AA7A-D3A713D8AFC4/data/Containers/Bundle/Application/3CF0C327-8A39-410D-8EDE-50B936C4A70A/Mobile%20Ace%20Diser.app/www/scripts/axios.js:1055:26","config":{"url":"https://myhost.com/api/login","method":"post","data":{},"headers":{"Accept":"application/json, text/plain, */*"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}

#### To Reproduce
Build a cordova project, add the cordova-plugin-wkwebview-engine , try to send post/get request app will get an error

```js
 axios.post(base_url+'login', formData).then((response) => {
showDashboard()
}
```

#### Expected behavior
Build a cordova project, add the cordova-plugin-wkwebview-engine , try to send post/get request app will get an error

#### Environment
 - Axios Version [axios v0.19.0]
 - Adapter [e.g. XHR/HTTPS]
 - Browser []
 - Browser Version []
 - Node.js Version []
 - OS: [iOS 13]
 - Additional Library Versions [Cordova 9.0, ios@5.1.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response.

**Comment by cyrilxx** [comment]
Hello , fix it by adding this plugin
https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix
