### ISSUE TITLE
How to use Promise.allSettled workaround with axios.create

### ISSUE THREAD

**Issue by morsmodr** [axios/axios#3082]
#### Describe the issue
Currently I create a base request object using axios.create as we have some custom headers in our application. But I have a case where I am making 5 api calls and want to handle them after all the apis have returned their response. 

Which got me looking at Promise.allSettled and whether axios has support for it. I found out that it doesn't, along with the workaround given in #2557 and #2556. Initially I followed that workaround and then ran axios.create. But the request object has only request related functions, which makes sense (get, put, post amongst others)

So as an alternative, I tried adding Promise.allSettled function to the base request object directly but that resulted in an error: Promise resolve or reject function is not callable

#### Example Code
```js
// Example code here
const baseRequest = axios.create(customHeaders);
baseRequest.allSettled = Promise.allSettled;

async getAll(pathArray, params) {
      return await baseRequest.allSettled(pathArray.map(path => baseRequest.get(path, params));
}
```

#### Expected behavior, if applicable
I was expecting to see the result (resolve/reject) of the array of Promises in my .then() part of code which consumes getAll. I might be making some mistake because of incorrect syntax.

#### Environment
 - Axios Version [0.19.2]
 - Adapter [XHR]
 - Browser [Chrome]
 - Browser Version [83.0.4103.116]
 - Node.js Version [N/A]
 - OS: [OSX 10.14.6]
 - Additional Library Versions [React 16.13.1]

#### Additional context/Screenshots
Not sure whether this helps, but basically I am looking to handle result of all promises once they are complete, regardless of success/error and then based on the returned response I can notify the user which calls were successful and which all weren't.

**Comment by chinesedfan** [comment]
> Promise resolve or reject function is not callable

Looks good to me. And don't know why you get this error. Can you provide a producible online jsbin/codepen link?
