### ISSUE TITLE
The arithmetic result exceeds 32 bits in IE 11.

### ISSUE THREAD

**Issue by meetlost** [axios/axios#3083]
#### Describe the bug
IE 11 throws this exception when response header has content-length greater than '4G': "The arithmetic result exceeds 32 bits.".

#### To Reproduce
Issue a 'HEAD' request to a resource whose content-length is greater than '4G' from IE 11.

#### Expected behavior
We should catch this exception.

#### Environment
 - Axios Version [0.19.2]
 - Adapter [XHR]
 - Browser [IE]
 - Browser Version [11]
 - Node.js Version [v10.13.0]
 - OS: [OSX 10.13.5]
 - Additional Library Versions [React 16.11.0]

#### Additional context/Screenshots
<img width="1557" alt="1" src="https://user-images.githubusercontent.com/44923884/86202001-aa4d4a00-bb93-11ea-9506-4d4dac3cfee6.png">
<img width="1557" alt="2" src="https://user-images.githubusercontent.com/44923884/86202021-b3d6b200-bb93-11ea-87fc-38d6aef0a44e.png">

**Comment by meetlost** [comment]
Related pull request: https://github.com/axios/axios/pull/3084

**Comment by jasonsaayman** [comment]
Closing this, no one should be using ie11
