### ISSUE TITLE
控制台打印的config里面的header跟外面的那个header有什么区别？控制台看了下为什么我config里面的header没有Content-Type这个，明明已经设置了的

### ISSUE THREAD

**Issue by lxy910812** [axios/axios#3091]
#### Describe the issue
A clear and concise description of what the issue is.

#### Example Code
Code snippet to illustrate your question

```js
const client = axios.create({
    timeout: 20000,
    responseType: 'json',
    baseURL: baseURL,
    headers: {
        "Accept-Language": "zh-Hans-CN;q=1",
        "Content-Type": "application/x-www-form-urlencoded",
    }
})
post (url, data = {}) {
    let formData = new FormData();   
    for (let [k, v] of Object.entries(data)) {
        formData.append(k, v);
    }
    client.post(url,formData).then(response => {
        console.log('xxxxxx',response)
    })
}
然后浏览器控制打印的config里面的header是这个{
Accept: "application/json, text/plain, */*"
Accept-Language: "zh-Hans-CN;q=1"
}
外面一层headers打印的是这些
{
access-control-allow-headers: "Content-Type, api_key, Authorization"
access-control-allow-methods: "POST,GET,OPTIONS"
cache-control: "no-cache"
content-length: "65"
content-type: "application/json; charset=utf-8"
date: "Thu, 02 Jul 2020 09:42:56 GMT"
expires: "-1"
pragma: "no-cache"
server: "openresty"
x-aspnet-version: "4.0.30319"
}
请问为什么我设置了
"Content-Type": "application/x-www-form-urlencoded",
不起作用？
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
> Content-Type will be removed if data is FormData or undefined, in order to let the browser to set.

See https://github.com/chinesedfan/You-Dont-Know-Axios#more-stories-about-headers. If you can find more detailed documents about it, that would be great. The original author has been away from this project for a long time.
