### ISSUE TITLE
Don't get 408, Timeout error

### ISSUE THREAD

**Issue by bolam-o** [axios/axios#3093]
#### Describe the issue
There is a 1-minute Request Timeout Error on the API server. However, Axios does not return a 408 Error after 1 minute.

#### Example Code
Code snippet to illustrate your question

```js
axios.post(
        `${baseURL}/connect`,
        data, {
          cancelToken: new CancelToken(function executor (c) {
            cancel = c
          })
        })
        .then(response => {
          ...
        })
        .catch(error => {
          if (error) {
            let errorMessage

            if (Http.isCancel(error)) {
              errorMessage = '연결 요청이 취소되었습니다.'
              Log.error('연결 요청이 취소되었습니다.')
            } else {
              const { status } = error.response

              if (status === 400) {
                errorMessage = '지원 데스크탑과의 연결을 실패하였습니다.'
                Log.error(`[${status}] 지원을 요청한 데스크탑에 연결을 실패하였습니다.`)
              } else if (status === 408) {
                errorMessage = '지원 데스크탑과의 대기시간을 초과하였습니다.'
                Log.error(`[${status}] 지원을 요청한 데스크탑과의 대기시간을 초과하였습니다.`)
              } else if (status === 422) {
                errorMessage = '입력한 정보가 옳바르지 않습니다.'
                Log.error(`[${status}] 입력한 정보가 옳바르지 않습니다.`)
              } else {
                errorMessage = '원격연결 진행 중 오류가 발생하였습니다.'
                Log.error(`[${status}] 원격연결 진행 중 오류가 발생하였습니다.`)
              }
            }
          }
        })
    }
```

#### Expected behavior, if applicable
We tried using HTTP Request in POSTMAN, but returned a 408 Timeouterror if one minute has passed successfully.

#### Environment
 - Axios Version [^0.19.2]
 - Adapter [HTTP]
 - Browser [Chrome]
 - Browser Version [83]
 - Node.js Version [12.14.0]
 - OS: [Window 10]
 - Additional Library Versions [Electron - ^6.0.0, Vue.js - ^2.6.11]

#### Additional context/Screenshots
...

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response, like Postman.

**Comment by bolam-o** [comment]
Thank you for looking at my issue, I will check if this issue has an additional connection with Vue and Electron.
