### ISSUE TITLE
Axios ignore header `Set-Cookie`

### ISSUE THREAD

**Issue by dorosch** [axios/axios#3095]
#### Axios ignore header `Set-Cookie`
Good day. Library ignores setting cookies from server response headers.

#### To Reproduce
I attach screen with problem

```js
const API = axios.create({
  withCredentials: true,
  baseURL: 'http://0.0.0.0:8000/api/v1'
})
```

#### Expected behavior
I expect after response see cookie in local storage.

#### Environment
 - Axios Version [0.19.2]
 - Adapter [HTTP]
 - Browser [Firefox]
 - Browser Version [77]
 - Node.js Version [None]
 - OS: [Linux]
 - Additional Library Versions [Vue 2.6.11]

#### Additional context/Screenshots
Attach screens:
![Screenshot from 2020-07-03 11-23-49](https://user-images.githubusercontent.com/13240952/86449576-10b3a300-bd21-11ea-9574-8054a6235701.png)
![Screenshot from 2020-07-03 11-24-04](https://user-images.githubusercontent.com/13240952/86449588-14dfc080-bd21-11ea-825a-6c27d393435f.png)

**Comment by JNotelddim** [comment]
@dorosch I was having the same issue, based on this comment: https://github.com/axios/axios/issues/2847#issuecomment-605417894
I was pointed to these notes: https://github.com/chinesedfan/You-Dont-Know-Axios#nightmares-of-headers-cors-cookies-and-auth
While led me to set the "Access-Control-Expose-Headers" header https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Expose-Headers

**Comment by itsjef** [comment]
@JNotelddim Which value did you set `Access-Control-Expose-Headers` to?

**Comment by JNotelddim** [comment]
> @JNotelddim Which value did you set `Access-Control-Expose-Headers` to?

@itsjef  so sorry for the super delayed response. I'm sure you've moved on by now.

For anyone else who comes across this, I believe I exposed the "Set-Cookie" header, because that was the one that axios was ignoring.

In my Express api it looked like:

```
  9 const corsOptions = {                                                           
 10   //To allow requests from client                                               
 11   origin: [                                                                     
 12     "http://localhost:3001",                                                    
 13     "http://127.0.0.1",                                                         
 14     "http://<otherIp>",                                                   
 15   ],                                                                            
 16   credentials: true,                                                            
 17   exposedHeaders: ["set-cookie"],                                               
 18 };                                                                              
 19 
```
