### ISSUE TITLE
How to use react native ssl pinning with axios library?

### ISSUE THREAD

**Issue by sureshbakshi** [axios/axios#3096]
**I need to implement ssl pinning (cert / publickey )in my react native project and i am using axios as my network client . how do i implement  with this library? **

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Additional Library Versions [e.g. React 16.8.6, React Native 0.60.5]

**Comment by xhirazi** [comment]
+1

**Comment by jasonsaayman** [comment]
Nope as far as my knowledge on this goes it is not supported
