### ISSUE TITLE
Defaults headers Content-Type don't allow "content-type" ?

### ISSUE THREAD

**Issue by KiKiKi-KiKi** [axios/axios#3104]
#### Describe the issue

```js
axios.defaults.headers.common['content-type'] = 'application/json';
```

This request header Content-Type become  `application/json, application/json;charset=utf-8`.  
GET / POST methods option can use `'content-type'` too. 
But `defaults.headers` is only allow the `'Content-Type'` ?  

#### Example Code

Global axios defaults
```js
axios.defaults.headers.common['Content-Type'] = 'application/json';
// Request Header Content-Type: application/json

axios.defaults.headers.common['content-type'] = 'application/json';
// Request Header Content-Type: application/json, application/json;charset=utf-8

axios.defaults.headers.common['Content-type'] = 'application/json';
// Request Header Content-Type: application/json, application/json;charset=utf-8
```

Request methods config
```js
axios.get(url, { headers: { 'Content-Type': 'application/json' } });
// Request Header Content-Type: application/json

axios.get(url, { headers: { 'content-type': 'application/json' } });
// Request Header Content-Type: application/json

axios.get(url, { headers: { 'Content-type': 'application/json' } });
// Request Header Content-Type: application/json

axios.get(url, { headers: { 'cOntEnt-tYpe': 'application/json' } });
// Request Header Content-Type: application/json
```

Content-Type `application/json, application/json;charset=utf-8` requests ite become empty `req.body` in Express.

```js
// Express API
const express = require('express');
const app = express();
app.use(express.json());

app.post('/api', (req, res) => {
  // Always `req.body` become `{}` 
  // When Content-Type is "application/json, application/json;charset=utf-8"
  req.body;
});
```

#### Expected behavior, if applicable

Request methods config can use `Content-Type` and `content-type` too. (This document was written the `"content-type"` in [Response Schema](https://github.com/axios/axios/blob/master/README.md#response-schema) )
But `defaults.headers` can use only `Content-Type`.
It's made me little confused. I sorry, I don't know if it's a specification or not.  
if it's a specification, need a note of this on the "[Global axios defaults](https://github.com/axios/axios/blob/master/README.md#global-axios-defaults)" section, I think. Thank you.

#### Environment
 - Axios Version [0.19.2]
 - Adapter [XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [83.0.4103.116]
 - Node.js Version [v12.16.3]
 - OS: [OSX 10.15.5]
 - Additional Library Versions [React 16.13.1 / Express 4.17.1]

**Comment by MoonSupport** [comment]
I think `defaults.headers` is only allow the 'Content-Type'.

For right work, it has to call `normalizeHeaderName` function https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/lib/helpers/normalizeHeaderName.js

But If you will directly change header like this 
```js
axios.defaults.headers.common['Content-Type'] = 'application/json';
```

There is nowhere to call this function.

But I agree your opinion need a note of this on the "Global axios defaults" section.

**Comment by karandeepvirk85** [comment]
I had this same issue couple of days ago. I had resolved this issue by using this header.
{ 'content-type': 'application/x-www-form-urlencoded' }

**Comment by MoonSupport** [comment]
@karandeepvirk85 
Yes.

Post api config call `normalizeHeaderName`.
Also Content-type Setting in Axios Module has a higher priority than user setting ( in post api or default )

**Comment by chinesedfan** [comment]
> But defaults.headers is only allow the 'Content-Type' ?

See #2880.

> This document was written the "content-type" in Response Schema

Note that it explains headers in response, which is different with axios config. And I'd like share [more-stories-about-headers](https://github.com/chinesedfan/You-Dont-Know-Axios#more-stories-about-headers).

**Comment by MoonSupport** [comment]
> Note that it explains headers in response, which is different with axios config. And I'd like share [more-stories-about-headers](https://github.com/chinesedfan/You-Dont-Know-Axios#more-stories-about-headers).

After looking at your document, I think my explanation is wrong.

The default setting is not case sensitive.
But regardless of the above the Content-Type cannot be set of it.

Is it right?
