### ISSUE TITLE
Should maxContentLength be considered when response type is stream

### ISSUE THREAD

**Issue by eeerin** [axios/axios#3108]
#### Section/Content To Improve
I think this just needs some documentation that when using a responseType of stream with maxContentLength because it is currently being ignored as shown [here](https://github.com/axios/axios/pull/1485/files#diff-13c4730a3365dedb3437af189b18e6a9R209). 

#### Suggested Improvement
1. fix the readme and add a line above the maxContentLength config that says it will not be considered when responseType is stream
2. TBH I would like it to be handled as part of the stream that is returned, I'm willing to do the work to have the stream halt and emit an error when it crosses the maxContentLength threshold. 

#### Relevant File(s)
README.MD or lib/adapters/http.js

**Comment by jasonsaayman** [comment]
@eeerin could you put in a pull request for this? I would be happy to accept and merge :)

**Comment by jasonsaayman** [comment]
Closing this issue due to it's age, stale state or due to a loss of momentum surrounding the issue. Please open a new issue should this problem still be relevant.
