### ISSUE TITLE
Default 'json' responseType is not applied to requests

### ISSUE THREAD

**Issue by berniegp** [axios/axios#3116]
#### Describe the bug
The documentation states:

```
  // `responseType` indicates the type of data that the server will respond with
  // options are: 'arraybuffer', 'document', 'json', 'text', 'stream'
  //   browser only: 'blob'
  responseType: 'json', // default
```

However, the `responseType` of `XMLHttpRequest` is left unset (same as `"text"`) by default instead of being set set to `'json'`. This causes an empty response body to become `""` instead of `null` as expected from the [XMLHttpRequest specification](https://xhr.spec.whatwg.org/#json-response) :

> A **JSON response** is the return value of these steps:
> 1. **If response’s body is null, then return null.**
> 2. Let jsonObject be the result of running parse JSON from bytes on received bytes. If that threw an exception, then return null.
> 3. Set response object to jsonObject and return it.
>
> A **text response** is the return value of these steps:
> 1. **If response’s body is null, then return the empty string.**

#### To Reproduce
Create a request with the XHR adapter where the server responds with an empty body. Then `response.data === ""`.

#### Expected behavior
`response.data === null` (through a default `request.responseType = 'json'`).

#### Environment
 - Axios Version: 0.19.2
 - Adapter: XHR
 - Browser: Chrome
 - Browser Version: 83
 - OS: Windows 10

**Comment by cdesch** [comment]
I am running into a same issue with axios `0.19.0` and `XMLHttpRequest 1.8.0`. 

i have the config with `responseType = 'json'`, but `responseData` contains a string of the response and `data` is empty. 

Removing the `XMLHttpRequest` fixed the issue, although I need to figure out what is causing it as it is a dependency for a different package.

**Comment by cdesch** [comment]
This is also in `0.20.0-0` 

<img width="382" alt="Screen Shot 2020-07-25 at 2 23 24 PM" src="https://user-images.githubusercontent.com/1207795/88463687-89220580-ce82-11ea-8450-bd497f594a2f.png">

**Comment by berniegp** [comment]
In the meantime, this configuration is a workaround:

```
axios.create({
  responseType: 'json',
});
```

**Comment by cdesch** [comment]
Thanks @berniegp, but it persists with that param set. The docs also say that `json` is the default `responseType` but I set it anyway when creating the axios instance. 

To get the request to work, I have to remove the `xmlhttprequest` dependency. In my specific case, it is `citysdk` that depends on `xmlhttprequest`, so I may have to find a new way adding the functionality as a work around.

Here is my code:

```js
import {store} from '../store';
import {getAPIBaseUrl} from './app_urls';
import axios from "axios";

const defaultOptions = {
  baseURL: getAPIBaseUrl(),
  responseType: "json",
  headers: {
    'Content-Type': 'application/json'
  },
  crossDomain: true
};

// Create instance
const instance = axios.create(defaultOptions);

// Set the AUTH token for any request if authenticated
instance.interceptors.request.use(function (config) {
  const token = store.getState().session.token;
  if (token) {
    config.headers = {...config.headers, ...token}
  }
  return config;
});

export default instance;
```

**Comment by jasonsaayman** [comment]
I think this is an issue that has occurred due to us changing axios to allow the browser to decide the response type, since we have gone back and forth a lot on this we will probably not make any new changes till we cut a v1.

**Comment by sgpinkus** [comment]
> since we have gone back and forth a lot on this we will probably not make any new changes till we cut a v1.

Maybe doing some stupid mistake but seem to be hitting this issue in v1.3.3 while using axios in browser. Server responds with `Content-Type: application/json; charset=utf-8` axios has `responseType: 'json'` explicitly set but `res.json` is still a string. Should be deserialized JSON right?
