### ISSUE TITLE
Please provide new release with updated follow-redirects dependency.

### ISSUE THREAD

**Issue by yippibrian** [axios/axios#3119]
#### Is your feature request related to a problem? Please describe.
The follow-redirects dependency hardcoded its debug dependency to 3.1.0 from version 1.5.8 through 1.7.0 and removed debug completely in version 1.12.1.  The debug dependency has some nasty memory bugs like https://github.com/visionmedia/debug/issues/678.

I notice that axios has follow-redirects hardcoded to 1.5.10, though this has been fixed in the repo on 2/14/2020.  

#### Describe the solution you'd like
Can a new release of axios be made with this fix so that we can avoid building with the problematic debug dependency?

#### Describe alternatives you've considered
We can patch our code to fix this, but it would be better to have this fixed in an actual release.

#### Additional context
None.

**Comment by chinesedfan** [comment]
Closed due to https://github.com/axios/axios/issues/3009#issuecomment-658888145.
