### ISSUE TITLE
Hi, is there a difference on passing to  `req.query` vs `req.body` in terms of security?

### ISSUE THREAD

**Issue by TamashiKaizen** [axios/axios#3121]
#### Describe the issue
Hi, is there a difference on passing to  `req.query` vs `req.body` in terms of security? I'm not sure which one to use to pass a mobile number to server to trigger sms one time pin API.

#### Example Code
req.query
```
axios.post('sendOneTimePin', {
    params: {
        mobileNumber: '+12345678910'
    } 
});
```

req.body
```
axios.post('sendOneTimePin', {
    data: {
        mobileNumber: '+12345678910'
    } 
});
```

#### Expected behavior, if applicable
N/A

#### Environment
 - Axios Version [0.19.2]
 - Adapter [HTTP]
 - Browser [Chrome]
 - Browser Version [Version 83.0.4103.116 (Official Build) (64-bit)]
 - Node.js Version [12.18.1]
 - OS: [MacOS Catalina 10.15.5]
 - Additional Library Versions [React 16.11.0, React Native 0.62.2]

#### Additional context/Screenshots
N/A

**Comment by chinesedfan** [comment]
> GET is less secure compared to POST because data sent is part of the URL. So it's saved in browser history and server logs in plaintext.

For more details, google with "get query vs post data". Like [this](https://www.diffen.com/difference/GET-vs-POST-HTTP-Requests#:~:text=GET%20vs.,POST&text=HTTP%20POST%20requests%20supply%20additional,required%20data%20in%20the%20URL.).

**Comment by TamashiKaizen** [comment]
@chinesedfan thank you
