### ISSUE TITLE
Cancellation of a request doesn't update the server

### ISSUE THREAD

**Issue by Fardenz** [axios/axios#3123]
#### Is your feature request related to a problem? Please describe.

When I cancel a request in axios, it doesn't alert the server. It just aborts it for me.

#### Describe the solution you'd like

Sending a signal to the server to notify it to finish the request. Something similar to TCP flag RST or FIN, so if the server is doing some heavy operation we can let it know that we don't need the response anymore.

#### Describe alternatives you've considered

I am going to try with nodejs http native library https://nodejs.org/api/http.html#http_http_request_options_callback and try to play with it to see if I can close or abort the socket in some way so that it sends a signal alerting the server

#### Additional context

:)

**Comment by chinesedfan** [comment]
In fact, `cancellation` means aborting the request, so no effects on server side. If the socket connection has been set up, you may use [`abort` event](https://nodejs.org/api/http.html#http_event_abort). Otherwise, send another special request to the server by yourself.
