### ISSUE TITLE
image post

### ISSUE THREAD

**Issue by miladkhorramian** [axios/axios#3126]
#### Describe the issue
Hi and thanks again for this amazing feature, I was wondering if i could ask this. Recently I happen to have to post some images on a web api. Is there a way that axios could get the path of an image when a user is trying to upload it? That way we wouldn't go on the whole ajax thing.

#### Example Code
```
<input file='type' id='someFile'>
```

```js
// Example code here
axios.post('url',{
 image: // Something Axios  Fetched
}) .then()...
```

#### Expected behavior, if applicable
How Ajax uploads the image

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots

**Comment by chinesedfan** [comment]
> Is there a way that axios could get the path of an image when a user is trying to upload it?

It depends on how you select the image and axios doesn't care about that. In you example, google "input type file path" and lots for results will be shown.

**Comment by miladkhorramian** [comment]
> 
> 
> > Is there a way that axios could get the path of an image when a user is trying to upload it?
> 
> It depends on how you select the image and axios doesn't care about that. In you example, google "input type file path" and lots for results will be shown.

Well the whole file path is unreachable. Any suggestions?? I'm sending the image with some other keys. and the only accepts file path.
