### ISSUE TITLE
Filtering get requests with params does not work

### ISSUE THREAD

**Issue by Haim-Buchbut** [axios/axios#3127]
#### Describe the issue
I'm using Axios to query my database on Firebase which works fine, but adding params does not filter the returned results.
In the example below I'm trying to get only messages (in a messaging app) that were sent to David, but it returns all the messages.

#### Example Code

```js
axios.get(  "/messages.json", { params : { to : "David" } } )
        .then(response => {
            var fetchedMessages = [];
            for(let key in response.data) {
                fetchedMessages.push({
                    id: key,
                    to: response.data[key].to,
                    subject: response.data[key].subject
                });
            }
```

#### Expected behavior, if applicable
I would expect to get only the records that include a 'to' field with 'David' values.

#### Environment
 - Axios Version: 0.19.2
 - Browser: Chrome
 - Node.js Version: 14.4.0
 - React 16.13.1

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios.

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by Haim-Buchbut** [comment]
In both cases, the URL and request headers are the same.
