### ISSUE TITLE
Give axios.delete() a data parameter (similar to put/post)

### ISSUE THREAD

**Issue by kiprobinson** [axios/axios#3131]
#### Is your feature request related to a problem? Please describe.
The backend I'm working with requires a user to provide a reason for deleting a record, which is stored for auditing. The `deleteReason` comes in a body parameter. For put/post methods, this would be passed in the `data` parameter. But `axios.delete` method does not take an optional `data` parameter like the `put` and `post` methods.

```
axios.delete(url[, config])
axios.post(url[, data[, config]])
axios.put(url[, data[, config]])
```

#### Describe the solution you'd like
I'd like the delete method to be defined similar to put/post:

```
axios.delete(url[, data[, config]])
axios.post(url[, data[, config]])
axios.put(url[, data[, config]])
```

So that I could do this:

```
let deleteDocument = axios.delete('/whatever', { deleteReason: "This doc is bad" });
```

#### Describe alternatives you've considered
I know there are two workarounds, but those don't follow the same pattern as axios.put and axios.post:

```
let deleteDocument = axios.delete('/whatever', { data: { deleteReason: "This doc is bad" } });
let deleteDocument = axios({method: 'delete', url: '/whatever', { data: { deleteReason: "This doc is bad" } });
```

#### Additional context
n/a

**Comment by PDXfoster** [comment]
I would also like to see this, and it's come up before - #897. The somewhat heavy handed approach to stripping parameters  off the request flies in the face of devs striving for isomorphic code, and in a use case as outlined by @kiprobinson above leads to devs instead using post - which doesn't describe what it's doing, and breaks the spec that says post calls should be idempotent.

Presumably for this reason, back in 2014 ietf updated the spec to explicitly **_allow_** for a body on delete requests

> A payload within a DELETE request message has no defined semantics; sending a payload body on a DELETE request might cause some existing implementations to reject the request. 
[- ietf RFC 7231](https://tools.ietf.org/html/rfc7231#page-29) 

It would be really great if axios could update to meet the spec that was updated 6 years ago :-). 

Thanks!

**Comment by EricRabil** [comment]
Given support for data in delete requests does vary across server frameworks, the delete method should have support for data *but* it should be noted that it may not be supported on certain services.

**The library should not be making this decision for developers – developers should be able to use the delete request to the fullest extent if the server permits.**

**Comment by wopian** [comment]
Related issue: https://github.com/axios/axios/issues/3220

**Comment by jasonsaayman** [comment]
Hi,

Axios version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks

**Comment by KirillKayumov** [comment]
@jasonsaayman we had the same issue on `0.20.0`. Now it works well on `0.20.1`. Thanks!

**Comment by TohirDev** [comment]
thanks
