### ISSUE TITLE
RN 0.63.1 [TypeError: undefined is not an object (evaluating 'error.response.status')]

### ISSUE THREAD

**Issue by samuk190** [axios/axios#3135]
#### Describe the bug
When user don't have internet, and you try to send a request it should return error = NetworkError, instead the error is undefined.
When user have internet, it behaves normaly.

it happened after upgrading to RN 0.63.1 and rebuilding android/iOS folder.

-->console.log(error) results:
[TypeError: undefined is not an object (evaluating 'error.response.status')]
#### To Reproduce
Axios.get
axios.post

```js
//
```

#### Expected behavior
Show error network error.
#### Environment
 - Axios Version [0.19.1]
 - Adapter [e.g. XHR/HTTP]
 - React Native
 - 
 - Node.js Version [12 LTS]
 - OS: [ANDROID Xiaomi mi5s plus android 7]
 - Additional Library Versions [ React Native 0.63.1]

#### Additional context/Screenshots
[TypeError: undefined is not an object (evaluating 'error.response.status')]

**Comment by samuk190** [comment]
it detect error.message = Network Error, but error.response.status is undefined while it was to get same error code right? or I'm missing something. I want be able to get if error status is 400

**Comment by armspkt** [comment]
same issue

**Comment by 15110011** [comment]
same here, everything works fine on ios but android not
RN: 0.62
axios: ^0.19.2

**Comment by samuk190** [comment]
> same here, everything works fine on ios but android not
> RN: 0.62
> axios: ^0.19.2

Grad I'm not alone!

**Comment by jasonsaayman** [comment]
We will be looking into better error handling in v1. I am closing for now as we have multiple issues open for error handling.

**Comment by moygospadin** [comment]
but how to fix it?

**Comment by tanengsiang** [comment]
I also facing this issue , work fine in iOS simulator but android not.Any solution can fix ?

RN:0.69.0
Axios : ^0.19.0
Expo : 41.

**Comment by VinodhPIT** [comment]
some times im getting response like [TypeError: undefined is not an object (evaluating 'error.response.config')] ,any one knows what's the reason ?

**Comment by davidtedmanjones** [comment]
This is happening to me too. Anyone had success fixing yet?

**Comment by OgqJey** [comment]
I also same issue. I don't find solution.

**Comment by mercurio236** [comment]
In my case the problem was the emulator, with time he lost connection with the internet

**Comment by AhmadNsour** [comment]
any solution?
