### ISSUE TITLE
Misleading verbiage around supported HTTP methods

### ISSUE THREAD

**Issue by timschwab** [axios/axios#3140]
#### Section/Content To Improve

Section: Request method aliases

Quote: "For convenience aliases have been provided for all supported request methods."

#### Suggested Improvement

The key word in the quote is "supported". This suggests to me that anything not listed is not supported. `search` is not in the list, which implies that the SEARCH method is not supported. However, I tried the following:

```
axios.request({
  url: 'testing',
  method: 'search'
});
```

and it successfully sent a SEARCH request. This shows that the SEARCH method is actually supported. So, I would change the word "supported" to "common". And while we are at it, there needs to be a comma after "convenience". So the improved quote would read:

"For convenience, aliases have been provided for all common request methods."

#### Relevant File(s)

https://github.com/axios/axios/blob/master/README.md

**Comment by jasonsaayman** [comment]
Please can you put a pull request in for this change? I will gladly accept.

**Comment by rijkvanzanten** [comment]
The same applies to the TypeScript definitions:

https://github.com/axios/axios/blob/69949a6c161d954570a314c0e48b57d3ffd90326/index.d.ts#L24-L34

@jasonsaayman Does Axios support any string you pass it, or is there a specific subset?
