### ISSUE TITLE
Multiple headers with same name

### ISSUE THREAD

**Issue by tao1** [axios/axios#3143]
#### Is your feature request related to a problem? Please describe.
I need to post a request with multiple Authorization headers. One with Basic authentication and another one one with Bearer authentication. AFAIK I cannot use axios library to do so.

#### Describe the solution you'd like
If an headers field has a value of type array then http request should contain multiple http headers with values obtained from the array.

#### Describe alternatives you've considered
Switch to another library

#### Additional context
None

**Comment by chinesedfan** [comment]
I guess you want to achieve something like,

```
Authorization: abc
Authorization: def
```

Instead of,

```
Authorization: abc def
```

But maybe the second one looks like better. And it can be achieved by yourself.
