### ISSUE TITLE
Latest version is not installed by `npm install` on a new machine

### ISSUE THREAD

**Issue by gaz77a** [axios/axios#3147]
#### Describe the issue
We are referencing axios ^0.7.0 in our package.json however when we do an npm install on a new machine we have v0.7.0 downloaded/installed rather than v0.19.2.

Prior to doing npm install we have removed all node_modules and the package.lock.json.

#### Example Code
package.json dependencies snippet

```js
"axios": "^0.7.0",
```

#### Expected behavior, if applicable
0.19.2 should be downloaded/installed

#### Environment
 - Axios Version 0.7.0
 - Node.js Version 8.10.0
 - npm version 6.13.4

#### Additional context/Screenshots
N/A

**Comment by branislavblazek** [comment]
Hi! I have already tested this on my machine - opened terminal in vs code with my react project, run "npm install axios --save" a this is what i have in my package.json:
"dependencies": {
    "axios": "^0.19.2",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.13"
  },

**Comment by Frostack** [comment]
as I know `npm install` is not used to update a package, it installs dependencies with the version specified in `package.json` file. you may want to run this:
`npm install axios@latest`. it upgrades Axios to it's latest version. however, it may break your code as it's a major update to version 0.7.0

**Comment by cdesch** [comment]
npm/yarn doesn't like the hyphen in `0.20.0-0`

**Comment by gaz77a** [comment]
I don't think I explained myself properly.
In our case we have an exisiting package.json with
`"axios": "^0.7.0",`
which we don't want to change.

A new developer clones the repo and runs `npm install`.
My understanding of the caret^ in package.json is that npm install/update will download the latest version that is >= 0.7.0 and <1.0.0 but does not change package.json.

This works for other npm packages but not with axios.

**Comment by chinesedfan** [comment]
See https://github.com/npm/node-semver#caret-ranges-123-025-004. ^0.7.0 only means 0.7.x, but doesn't include 0.8.x and other versions less than 1.0.0.

**Comment by qiulang** [comment]
I was hit by the same problem. My dependencies has `"axios": "^0.19.2",` so `npm i` complained "npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1." I run `npm update -S axios to update it` but it didn't.

It took me a while to figure that `^` only means **patch update** for 0.x because most people are familiar with `^` for minor and patch.

The [npm document](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004) said 

> Many authors treat a 0.x version as if the x were the major "breaking-change" indicator.
> 
> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice.

But I feel several releases in axios 0.x so far were patch update, so using Caret ranges(^) is not ideal here.
