### ISSUE TITLE
React Native return network error on endpoint with self signed certificate.

### ISSUE THREAD

**Issue by samuk190** [axios/axios#3151]
#### Describe the bug
axios.get('http://myserver.com') // works
axios.get('https://myserver.com') // return [ Network Error] : 0.63.1 React Native version.

I tried to find some workaroujnd but it seems impossible.

Please add feature to ignore cert?
#### To Reproduce
axios.get('https://myserver.com') 
```js
// Example code here
```axios.get('https://myserver.com') 

#### Expected behavior
Return 200

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [XHR]
 
 - React Native: 0.63.1
 - Node.js Version [12 LTS]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 -, React Native 0.63.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by umerchaudhary34** [comment]
Hey @samuk190, have you resolved the issue?
