### ISSUE TITLE
Content-Type header not set

### ISSUE THREAD

**Issue by danielzzz** [axios/axios#3157]
#### Describe the bug
setting the header 'Content-Type' seem to be ignored.

#### To Reproduce

```js
let data = new FormData();
//... appending values to formdata and then
axios
    .request({
      url: '/member/tasks/addCommentApi.json',
      method: 'POST',
      data: data,
      headers: {
        'Content-Type': 'multipart/form-data',
        'X-Test': 'dan',
      },
    })
```

#### Expected behavior
headers should contain Content-Type, they don't
but X-Test header is present.

#### Environment
 - Axios Version [ 0.20.0-0]
- ReactNative [0.62.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

nothing else to add

**Comment by rafamarts** [comment]
Hi @danielzzz,

I just got this issue right now and solved it using the key header object as lowercase. Please, try it and check if works.

Try something like that:

      headers: {
        'content-type': 'multipart/form-data',
        'x-test': 'dan',
      },


Also,  **maintainers**, could I take this issue?

Thank you!!

**Comment by danielzzz** [comment]
thanks @rafamarts , I think it's still NOT working on react-native.

**Comment by Anahita-Fakhravar** [comment]
I have used JSON.stringify(data) then I could see content-type in request header but it does not work. It returns in response another header type.  Uploading image in react native is really troublous.

**Comment by IkennaU** [comment]
Mm
Kjj

**Comment by gunaygultekin** [comment]
I have the same issue. I solved by adding data: {}
