### ISSUE TITLE
Wrong Transport

### ISSUE THREAD

**Issue by witjs** [axios/axios#3158]
#### Describe the bug
if proxy url‘s protocol is not https, https request will get a wrong transport
transport has nothing to do with proxy

#### To Reproduce

system env
```
https_proxy=http://domain:port
```
if I make a request with url = https://my_https_url.com
transport will be http

because 
https://github.com/axios/axios/blob/ffea03453f77a8176c51554d5f6c3c6829294649/lib/adapters/http.js#L162

there is another bug:
`proxy.protocol` will always be `undefined`
I think `proxy` should be `parsedProxyUrl`

#### Expected behavior
right transport

#### Environment
 - Axios Version [e.g. 0.20.0]
 - Adapter HTTP
 - Node.js Version 12.13.8
 - OS: OSX 10.15.6

**Comment by leepowelldev** [comment]
Shame this issue is being closed as I'm experiencing exactly this bug.
