### ISSUE TITLE
It's not documented what happens if request is started with already cancelled token.

### ISSUE THREAD

**Issue by socketpair** [axios/axios#3163]
#### Section/Content To Improve
https://github.com/axios/axios#cancellation

#### Suggested Improvement
Document what will happen if I pass already cancelled token to axios request. Will it try to make a request ? 

#### Relevant File(s)
no

**Comment by jasonsaayman** [comment]
> Note: you can cancel several requests with the same cancel token.

Yeah it is documented

**Comment by socketpair** [comment]
No, this piece of text tells us, that the same token can be used for multiple requests. It doesn't tell what will happen when request is being awaited when token is already cancelled before awaiting. Will it start and then abort connection, or will not even start. It's important in my case.

**Comment by jasonsaayman** [comment]
Can you please try and see what happens then let me know. I can then update the docs or you can put in a pull request

**Comment by socketpair** [comment]
Reopen please, at first.

**Comment by jasonsaayman** [comment]
👍

**Comment by socketpair** [comment]
I checked sources. YOu need to add

"If a cancellation token is already cancelled at the moment of starting an Axios request, then the request is cancelled immediately, without any attempts to make real request"

**Comment by jasonsaayman** [comment]
Thank you very much :)
