### ISSUE TITLE
can‘t set cookie

### ISSUE THREAD

**Issue by Gamehu** [axios/axios#3170]
#### Describe the bug
postman set cookie is work,but use axios  isn't work

#### To Reproduce

```js
test('cookie', async () => {
		const data = await axios
			.post(
				'/api/v1/domain/getResourcesByDomainId',
				{
					id: mockId,
				},
				{
					headers: { Cookie: 'JSESSIONID=MDdkNzA5ODItOTk4ZS00ZTk5LThiMzEtMmM3ZWY5YjI1YTVl' },
					withCredentials: true,
				}
			)
			.then((response) => {
				return response.data
			})
		expect(data).toBeNull
```

#### Environment
 - Axios Version [e.g. 0.19.2]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 83.0.4103.116]
 - Node.js Version [e.g. 12.18.2]
 - OS: [e.g. windows 10]
 - Additional Library Versions [e.g. React 16.13]

#### Additional context/Screenshots
 can't pass

**Comment by chenh930330** [comment]
I have the same question.

**Environment**
Browser [e.g. Chrome]
Browser Version [e.g. 84.0.4147.105]

**Comment by flgmjr** [comment]
I managed to make it work - instead of using `withCredentials` inside the configuration object, I needed to put it in the defaults, right after importing axios:
`Axios.defaults.withCredentials = true;`

**Comment by chenh930330** [comment]
I find when Access-Control-Allow-Origin is a specify domain name not *,it works

**Comment by cybercoder** [comment]
When i use secure cookies with ```SameSite="None"``` ```fetch``` will set them and will show in browser's cookies, but with using axios and ```withCredntial``` won't, So it seems it is not ignoring ```Domain``` property of cookie when the ```SameSite``` is none, or sth like that, i don't know

**Comment by jasonsaayman** [comment]
Can you please test with the latest version, should the issue still present, please open a new issue
