### ISSUE TITLE
500 Error when Posting JSON content using axios

### ISSUE THREAD

**Issue by Reede** [axios/axios#3175]
#### Describe the issue
When using a linux GitLab runner to post JSON content through their API, it returns a 500 error that appears to be related to how axios formats the formData to send.

To give some context, I'm running this POST as part of a pipeline in GitLab to add a commit to a newly created project.

If I debug it locally on my windows machine using VS code it actually runs fine with no errors, but when it runs via GitLab on a linux runner, it returns a 500 error. I'm pretty convinced it's related to how the JSON content is formatted when pushed through the POST command in form data with escape characters. If I post a single word like JSON.Stringify('test') it works

The error itself is showing that the axios content-type should accommodate the data
#### Example Code

```js
let file= {
        property1,
        property2,
        property3
        },
        file_path = 'file.json';
// commit it to projects development branch
let gitlabAPICall = `projects/${project.thisProjectID}/repository/commits`,
formData= {
    branch: 'develop',
    commit_message: 'adding file.json',
    actions: [
        {
            action: 'create',
            file_path,
            content: JSON.stringify(file, null, '\t')
            // I've attempt to just pass the contents with nothing 
            // as well (file, null, 2), and this version and all fail
        }
    ]
};

return GitCloud.post(`${GitCloud.defaults.baseURL}${gitlabAPICall}`, formData)
```

and here's the error report i'm getting

```
config: {
     url: 'https://gitlaburl.com/api/v4/projects/1/repository/commits',
     method: 'post',
     data: '{"branch":"develop","commit_message":"adding file json","actions":[{"action":"create","file_path":"file.json","content":"{\\n\\t\\"property1\\":\\"TEXT\\",\\n\\t\\"property2\\":\\"5648987\\",\\n\\t\\"property3\\": \\"TRUE\\",\\n}"}]}',
     
   headers: {
   Accept: 'application/json, text/plain, */*',
   'Content-Type': 'application/json;charset=utf-8'
}
```
When I log the stringified json object before it's posted through gitlab I return this without the escape characters

{"property1":"TEXT","property2":"5648987","property3":"TRUE"}

#### Expected behavior, if applicable
Ideally no error and the content posts

#### Environment
 - Axios Version 0.19.2
- Adapter httpAdapter
 - Docker Image node:14.4.0-alpine3.10
- Node.js 14.4.0
 - OS:  alpine3.10

**Comment by Ionys320** [comment]
Hey!
In my case, when I send files, I do like this (I'm using the form-data package):
```js
let formData = new FormData();
formData.append('ticket', fs.createReadStream(mainPath + filename));

const axiosConfig = { headers: { 'Content-Type': 'multipart/form-data;boundary=' + formData._boundary } };

Axios.post(url, formData, axiosConfig);
```

And it's working.

**Comment by Reede** [comment]
So, it appears whatever was causing this on the GitLab side appears to have been fixed in a later release, as going back and retrying my original code now works.
