### ISSUE TITLE
When fetching gzipped JSON from an MS cloud endpoint, content is not decompressed

### ISSUE THREAD

**Issue by mattucf** [axios/axios#3181]
#### Describe the issue
When fetching a JSON url from the MS cloud, it returns a "Content-Encoding: GZIP" header, which axios fails to recognize because it's matching against lowercase values. (https://github.com/axios/axios/blob/master/lib/adapters/http.js#L193). According to RFC, content coding values are to be treated as case-insensitive: https://tools.ietf.org/html/rfc7231#section-3.1.2.1

If there's a workaround available, I'd love to know. Thanks.

#### Example Code
Code snippet to illustrate your question

```js
// Not sure what to put here; just a get() with default options to a server exhibiting this behavior
```

#### Expected behavior, if applicable
content-encoding value is treated as case-insensitive and gzipped content is decompressed

#### Environment
 - Axios Version: 0.19.0
 - Node.js Version: 12.16.1
 - OS: OSX 10.14.6

**Comment by jasonsaayman** [comment]
Closing this issue due to it's age, stale state or due to a loss of momentum surrounding the issue. Please open a new issue should this problem still be relevant.
