### ISSUE TITLE
undefined doesn't resolve for validateStatus

### ISSUE THREAD

**Issue by brandon-leapyear** [axios/axios#3186]
#### Describe the bug
According to the README:
>  // `validateStatus` defines whether to resolve or reject the promise for a given
>  // HTTP response status code. If `validateStatus` returns `true` (or is set to `null`
>  // or `undefined`), the promise will be resolved; otherwise, the promise will be
>  // rejected.

but passing `{ validateStatus: undefined }` to `axios.get` still throws an error on 404.

#### To Reproduce

```js
axios.get('http://google.com/asdf', { validateStatus: undefined })
```

#### Expected behavior
Should not error. If this is expected behavior, comment should be revised in the README

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
Seems that you didn't provide the axios version and related environment information. If it is duplicated with #2239, then try axios@next please.
