### ISSUE TITLE
Response bodies not retrievable for non 200 status codes

### ISSUE THREAD

**Issue by Sebi2020** [axios/axios#3187]
#### Describe the bug
It's not possible to retrieve response bodies for non 200 HTTP responses because Axios throws an exception for non 2xx codes. This does not complies to the browser Fetch API.

Some APIs return data even if the response code is not 200 OK.

#### To Reproduce
Self explanatory

#### Expected behavior
Only throw a exception for network errors and add something like response.ok to the api to check if the response code was in the 2xx range or add the response body to the exception of the catch block. 

#### Environment
 - Axios Version [e.g. 0.18.0] 0.19.2
 - Adapter [e.g. XHR/HTTP] XHR
 - Browser [e.g. Chrome, Safari] Firefox
 - Browser Version [e.g. 22] 79.0
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4] Ubuntu Linux 18.01
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0] VueJS, Lodash

#### Additional context/Screenshots
No additional context

**Comment by ZE0TRON** [comment]
Experiencing the same issue with 401 status code. Even the catch doesn't catch the error. I see a post failed log on the console coming from xhr.js.

**Comment by chinesedfan** [comment]
Maybe you should set `validateStatus`. See [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios#response-schema) for more details.

**Comment by pgcalixto** [comment]
@Sebi2020, it seems to be possible to retrieve the response text in the catch block.

I may be missing the point of the desired behavior for this issue, but this is what I understood:

Below I have a GET request that returns a 404.
By using `err.response.data`, I get the equivalent to `response.data` if it was a 200.

```js
  const url = "https://api.github.com/users/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

  try {
    const response = await axios.get(url);

    console.log(response.data);
  } catch (err) {
    console.log(err.response.data);
  }
```

**Comment by Sebi2020** [comment]
Oh I missed that.

**Comment by jgriffin1** [comment]
> @Sebi2020, it seems to be possible to retrieve the response text in the catch block.
> 
> I may be missing the point of the desired behavior for this issue, but this is what I understood:
> 
> Below I have a GET request that returns a 404.
> By using `err.response.data`, I get the equivalent to `response.data` if it was a 200.
> 
> ```js
> const url = "https://api.github.com/users/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
> 
> try {
>   const response = await axios.get(url);
> 
>   console.log(response.data);
> }
> catch (err) {
>   console.log(err.response.data);
> }
> ```

I'm having this issue as well now... Oddly I can access this err.response.data when I run the node app from my windows machine, but if I run the same code in a docker container (which uses some kind of linux), then the caught error does not include the response.

**Comment by ethandunford** [comment]
> Maybe you should set `validateStatus`. See [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios#response-schema) for more details.

This isn't great and feels hacky. If you look at any other http library like `requests` it will always return the status code
