### ISSUE TITLE
React native IOS Network Error

### ISSUE THREAD

**Issue by swapnilshah09** [axios/axios#3192]
#### Describe the bug
While making any post request using Axios package. I am getting a Network error. While the same API seems to be working perfectly fine with Android devices. It is not an issue with the API.

#### To Reproduce
Axios post request throws a network error message. If I make the call again inside the catch block then it works fine.

```js
axios
      .post(
        base_url + 'generatePaymentIntent',
        {
          // unit_id: 1,
          token: obj,
          order_type: 'ORD',
          order_data: {
            order_type: order_type,
            apt_id: apt_id,
          },
        },
        Loginheader,
      )
        .then(item => {
        this.setState({
          loading: false,
        });
        console.log('--------generate intent----------');
          console.log(item);
        if (item.data.code === 200) {
          const {price} = item.data.data.order_data;
          

          this.displayPaymentModal(
            'Confirm Payment',
            `Final Price: $${price}`,
            this.props.navigation,
            item.data.code,
            'Make Payment',
            item.data.data,
          );
        }
      })
      .catch(e => {
        this.setState({
          loading: false,
        });
        console.log('--------catch generate intent----------');
        // console.log(e.response);
        // const {message, code} = e.response;
        // this.retryPopup(
        //   `Error getting payment Intent`,
        //   message,
        //   '',
        //   code,
        //   'onetime',
        // );
        console.log(e.response);

        console.log(JSON.stringify(e));

        if (e.message === 'Network Error') {
          // this.makeOneTimePayment(order_type, apt_id);
          this.retryPopup(
              `Error getting payment Intent`,
              'RETRY',
              '',
              '400',
              'onetime',
            );
        }
      });
```

#### Expected behavior
It shouldn't through network error. What should be done to fix this behavior specifically for iOS devices/simulators.

#### Environment
 - Axios Version [e.g. 0.19.2]
 - Additional Library Versions [e.g. React 16.9.0, React Native 0.62.2]

#### Additional context/Screenshots
N/A

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. Say in iOS vs in Android.

**Comment by dscdac** [comment]
Same problem here, but intermittent.

**Comment by scook-tanviit** [comment]
I was able to identify a problem on my attempts, we had something being passed into body for a get and was having a hard time tracking it down because the error stated a network error.
Android was fine, IOS not so much.
After removing the body, we had no issues.  I would suggest checking to ensure your call is structured properly.  Personally I would qualify this as an error in my case, and assume your case is similar.

**Comment by dscdac** [comment]
@swapnilshah09 is stating clearly:

> While making any **post** ...

But @scook-tanviit is referring to a completely different problem (sending a body in a get request) 😞

**Comment by MOwais** [comment]
I am having the same issue in iOS but with a GET request. The request works fine in Android and Postman... tried with axios 19 and 20.

**Comment by Mario-Alfredo-Jorge** [comment]
I also had the same issues, and it was simply because my emulator had the internet turned off. Then, have a look whether your emulator's internet is not turned off.

**Comment by sacridias** [comment]
> I am having the same issue suddenly in iOS but with a GET request. The request works fine in Android and Postman... tried with axios 19 and 20.

Make sure you are not posting info that you should, such as a body/data block.  That was the issue when we had it with iOS.

**Comment by dscdac** [comment]
Still getting `Network Error` when performing a POST on a react-native app in iOS.

**Comment by bruuuuuuuce** [comment]
I had the same issue when doing a `GET` request. This was my api call that was failing on iOS devices
```
await axios(url, {
                method: "get",
                headers: {
                    'Content-type': 'Application/json',
                    Accept: 'Application/json',
                    Authorization: jwt,
                },
                data: body || {},
            })
```

I fixed it by changing `data: body || {}` to `data: body || undefined`. This fixed my issue on iOS. It always worked on android for me.

**Comment by hm-lijojohn** [comment]
Still having the issue. Any resolution for this yet. Only happens in IOS.

**Comment by techaks** [comment]
> Still having the issue. Any resolution for this yet. Only happens in IOS.

check your interceptor, may be your adding data somewhere.

**Comment by gsingh0** [comment]
> I had the same issue when doing a `GET` request. This was my api call that was failing on iOS devices
> 
> ```
> await axios(url, {
>   method: "get",
>   headers: {
>     'Content-type': 'Application/json',
>     Accept: 'Application/json',
>     Authorization: jwt,
>   },
>   data: {},
> })
> ```
> 
> I fixed it by changing `data: {}` to `data: undefined`. This fixed my issue on iOS. It always worked on android for me.

worked perfectly for me. Not sure why this fixed the problem.

**Comment by Bernard-Murphy** [comment]
I am having the same problem on all iOS browsers (not just Safari). The APIs work fine and the problem doesn't occur on any other devices.

**Comment by abdulrehmansiddiqui** [comment]
> I

no still not working in ios still [Error: Network Error]

**Comment by abdulrehmansiddiqui** [comment]
> I had the same issue when doing a `GET` request. This was my api call that was failing on iOS devices
> 
> ```
> await axios(url, {
>   method: "get",
>   headers: {
>     'Content-type': 'Application/json',
>     Accept: 'Application/json',
>     Authorization: jwt,
>   },
>   data: {},
> })
> ```
> 
> I fixed it by changing `data: {}` to `data: undefined`. This fixed my issue on iOS. It always worked on android for me.

no still not working in ios still [Error: Network Error]

**Comment by dhayaljaswantgit** [comment]
Did you guys able to fix the iOS network error, I'm also facing the same issue

**Comment by jaswant-technocompanion** [comment]
Did you guys able to fix the iOS network error, I'm also facing the same issue

**Comment by Bernard-Murphy** [comment]
I was unable to make it work using Axios. I would recommend using XHR or something else for the time being.

**Comment by xi1494-jaswantdhayal** [comment]
> I was unable to make it work using Axios. I would recommend using XHR or something else for the time being.

Thanks For reply :)
@Bernard-Murphy Can you please give me any working code snippet or demo app or any article or any may be any plugin for API call? It'll be more then good... Thanks again

**Comment by Bernard-Murphy** [comment]
@xi1494-jaswantdhayal 

I used XHR instead of axios and it worked. The easiest way to do it is to make it work using Postman, then copy/paste the generated code snippet for "JavaScript - XHR".

**Comment by geobako** [comment]
Check if the url has http instead of https. In that case not having 

`
<key>NSAllowsArbitraryLoads</key> 

 <true/>
`
in info.plist made this network error for me

**Comment by drizham** [comment]
Trying to connect to a localhost using axios (both http and https) do not work, it worked once when I opted for https and when the mac went to sleep it did not work again.
React native 0.6.63, ios 14.4.2. Connecting to anything but local host works...

**Comment by AlissonRS** [comment]
This problem still happening with POST requests in iOS 11~12 (regardless of the browser).

**Comment by exzos28** [comment]
Add this to your Info.plist like this:

```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by drizham** [comment]
here is mine, still not working: 	
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>

**Comment by exzos28** [comment]
> here is mine, still not working:
> ` <key>NSAppTransportSecurity</key> <dict> <key>NSAllowsArbitraryLoads</key> <true/> <key>NSExceptionDomains</key> <dict> <key>localhost</key> <dict> <key>NSExceptionAllowsInsecureHTTPLoads</key> <true/> </dict> </dict> </dict>`

have you performed yarn ios after this?

**Comment by drizham** [comment]
No I have not, I use npm. What does the command yarn ios do? Or do you mean rebuild the project from xcode? Apologies not a pro...

**Comment by exzos28** [comment]
> No I have not, I use npm. What does the command yarn ios do? Or do you mean rebuild the project from xcode? Apologies not a pro... help would really be appreciate here :)

`yarn ios` does the same as `npm run ios`

**Comment by drizham** [comment]
Each time I make changes i do a rebuild, still no joy :-(

**Comment by jasonsaayman** [comment]
Seems that the solution https://github.com/axios/axios/issues/3192#issuecomment-821821141 will mend the issue. Please open a new issue should this still not work.

**Comment by dscdac** [comment]
> Seems that the solution https://github.com/axios/axios/issues/3192#issuecomment-821821141 will mend the issue. Please open a new issue should this still not work.

That might solved some issue to some people, but the POST request 'Network error' still stands.

**Comment by jasonsaayman** [comment]
@dscdac please can you give me some more information? I need a fully reproducible example.

**Comment by AlissonRS** [comment]
@jasonsaayman please check #3278 for a reproducible example. It seems like the issue happens with any requests made using axios in iOS 11 & 12, it happens specifically for POST/PUT/DELETE requests because of CORS (as GET doesn't require CORS).

**Comment by nabeelahmdrana** [comment]
While searching for the solution of React native IOS Network Error, I have found the solution:

when working on localhost path for iOS and android create issues

if you are using localhost for android give this as your path :  'http://10.0.2.2:3000'
if you are using localhost for iOS give this as your path : http://localhost:3000

following is the code:

import {Platform} from 'react-native'

import axios from 'axios';

var baseURL = null;

Platform.OS === 'android'? baseURL = 'http://10.0.2.2:3000' : baseURL= 'http://localhost:3000'

export const getNotifications = () =>
  axios.get(`${baseURL}/notifications`, {
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
  });

**Comment by DerrickJames** [comment]
> While searching for the solution of React native IOS Network Error, I have found the solution:
> 
> when working on localhost path for iOS and android create issues
> 
> if you are using localhost for android give this as your path : 'http://10.0.2.2:3000'
> if you are using localhost for iOS give this as your path : http://localhost:3000
> 
> following is the code:
> 
> import {Platform} from 'react-native'
> 
> import axios from 'axios';
> 
> var baseURL = null;
> 
> Platform.OS === 'android'? baseURL = 'http://10.0.2.2:3000' : baseURL= 'http://localhost:3000'
> 
> export const getNotifications = () =>
> axios.get(`${baseURL}/notifications`, {
> headers: {
> Accept: 'application/json',
> 'Content-Type': 'application/json',
> },
> });

@nabeelahmdrana's solution was very helpful. If you're consuming an API which is running on your local machine and you're running an Android app on an emulator, the official Android docs state that the address 127.0.0.1 on your development machine corresponds to the emulator's own loopback interface. If you want to access services running on your development machine loopback interface (a.k.a 127.0.0.1 on your machine), you should use the special address 10.0.2.2 instead.

Consult the docs for more info.
https://developer.android.com/studio/run/emulator-networking

**Comment by dscdac** [comment]
Glad it was helpful for you. But going back the OP description:

> While making any **POST** request using Axios package. 

It's off-topic.

**Comment by dscdac** [comment]
👋 Still an issue 🤷‍♂️

**Comment by Nitish33** [comment]
Try to put `/` at the end of api. In my case when simulator is not connected with debugger, it was not passing request header to the call.

**Comment by emirdeliz** [comment]
Same problem here, but intermittent.

**Comment by emirdeliz** [comment]
> Same problem here, but intermittent.

Do you fix this problem?

**Comment by A-Tokyo** [comment]
Facing this issue on mobile data only, not wifi

**Comment by lyudad** [comment]
same issue

**Comment by PulkitAsri** [comment]
Same Issue

**Comment by saputroandhi** [comment]
Please check the env file or the base url of the API. IOS intolerant for Space or special character in the env file.

**Comment by nikitph** [comment]
not stale.. still facing the issue

**Comment by sayil** [comment]
I am facing this issue. Some of my Axios GET and POST calls are failing to get a response from the server and I can't pinpoint why.

details are [here](https://stackoverflow.com/questions/70279224/axios-requests-with-credentials-resulting-in-network-error-in-macos-safari-or-an)

**Comment by bachngocnhat** [comment]
Add this to your Info.plist like this:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>insecure-domain1.example.com</key>
             <dict>
		<key>NSIncludesSubdomains</key>
		<true/>
		<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
		<true/>
	        <key>NSTemporaryExceptionMinimumTLSVersion</key>
		<string>TLSv1.1</string>
	    </dict>
        </dict>
            <key>insecure-domain2.example.com</key>
            <dict>
		<key>NSIncludesSubdomains</key>
		<true/>
		<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
		<true/>
	        <key>NSTemporaryExceptionMinimumTLSVersion</key>
		<string>TLSv1.1</string>
		</dict>
        </dict>
    </dict>
    
</dict>
</plist>

**Comment by danyul** [comment]
I was facing what seems to be the same issue ("Network Error" upon making Axios POST requests, but only when on iOS.  The issue turned out to be my lack of a trailing slash (thank you, @Nitish33 !).   (I'm using Vue / Ionic rather than React / React Native, but it seems that may be irrelevant.)

**Comment by NekkiNeks** [comment]
Hello everyone, may be that can help to you.
Go to 'Signing & Capabilities' tab in Xcode, and add your API domain to "App Transport Security Exception" -> Exception Domains.  There will be localhost already.

Also this is just like a gui for your info.plist, so it adds some lines to it, you can check them if you want.

**Comment by jasonsaayman** [comment]
I will update the readme

**Comment by aymather** [comment]
Still facing this issue, none of the suggestions helped me :(

**Comment by jasonsaayman** [comment]
Ok, I, unfortunately, don't have a ready to go project in react-native to test. If anyone is willing to setup a test project for me with the error that would be an awesome contribution and then we can keep it around for testing in the future.

**Comment by TomasSestak** [comment]
Getting this in production app in IOS

**Comment by nikitph** [comment]
Not sure if this helps but for me the env file was not being picked up.

**Comment by yorickshan** [comment]
same issue

**Comment by daothingoclan** [comment]
> I was able to identify a problem on my attempts, we had something being passed into body for a get and was having a hard time tracking it down because the error stated a network error. Android was fine, IOS not so much. After removing the body, we had no issues. I would suggest checking to ensure your call is structured properly. Personally I would qualify this as a bug in my case, and assume your case is similar.
> 
> **To replicate:** add data to the data field of params. **Expected** meaningful error about invalid parameter structure **Result ** network error

I'm having the same issue when I have data object but method is 'get'. In case 'get' method, should push param on url and give data as undefined.

**Comment by aymather** [comment]
I'm aware that my fix turned out to not be related to axios, but just in case this helps anyone else... I fixed my issue by binding the host of my flask api to `0.0.0.0` instead of the default `127.0.0.1`

**Comment by davmaene** [comment]
I had the same problem when I tested my application on ios simulator, I solved it by initializing the request ```body``` to ```null``` for ```"GET"``` requests. Here is an example of my code here

```
const _onRunner = async ({method, url, data}, cb) => {
    try {
        axios({
            method,
            url,
            data: data ? data : null, // -------------> this line saved my day LOL
            headers,
            timeout: timeout
        })
        .then(res => {
            return cb(undefined, res['data'])
        })
        .catch(err => {
            
            return cb(undefined, err)
        })
    } catch (error) {
        return cb(error, undefined)
    }
}
``` 
but the question is why on ```android``` this ```error``` does not appear

**Comment by gltknky** [comment]
I had the same issue with expo client on iOS, and solved it configuring my api app to serve "http" instead of "https" in development mode.

**Comment by jasonsaayman** [comment]
Closing this issue due to it's age, stale state or due to a loss of momentum surrounding the issue. Please open a new issue should this problem still be relevant.

**Comment by emuter** [comment]
i figured still some people are struggling with this issue. here's what you could do in windows environment.

1. create a local domain.
2. put the created domain name in etc host file.
3. point the created domain to your pc in your network router ( better with internet connection )
4. point the domain in your local dev server vhost file.

and... voila you got it running even without ssl

**Comment by davidecarpini** [comment]
Erasing the simulator and creating a new one WORKED! (try with a different simulator)

**Comment by sleekLancelot** [comment]
In my case, the resolution is a bit funny, i had some spaces  in the url like so:
```
const res = await axios.post(`
      ${getEnv('baseurl')}/<route>`,
      body,
      {
        headers: {
          'Content-Type': 'application/json',
        },
      }
    )
```

the space right after the opening backtick that spans through the first and second line was what my ios device had an issue with:
```
const res = await axios.post(`
      ${getEnv('getEnv('baseurl')}/<route>`,
```

after almost 2 hours of debugging, removing the space like this 👇🏽 made it work on iOS.
```
    const res = await axios.post(
      `${getEnv('baseurl')}/<route>`,
      body,
      {
        headers: {
          'Content-Type': 'application/json',
        },
      }
    )
```
Either way worked on android!

**Comment by passiondroid** [comment]
> I had the same issue when doing a `GET` request. This was my api call that was failing on iOS devices
> 
> ```
> await axios(url, {
>   method: "get",
>   headers: {
>     'Content-type': 'Application/json',
>     Accept: 'Application/json',
>     Authorization: jwt,
>   },
>   data: {},
> })
> ```
> 
> I fixed it by changing `data: {}` to `data: undefined`. This fixed my issue on iOS. It always worked on android for me.

Lifesaver. Took us whole day to find the difference between android & ios for the same network call

**Comment by inkcrazy666** [comment]
> 
  "react": "18.2.0",
    "react-native": "0.72.4",
    "axios": "^1.5.0",
i change ```data:null``` to ```data: undefine```，it work out.
以前都是这么写的，好像也没啥问题啊，而且就iOS报错

**Comment by furkanuzundev** [comment]
> I had the same issue when doing a `GET` request. This was my api call that was failing on iOS devices
> 
> ```
> await axios(url, {
>   method: "get",
>   headers: {
>     'Content-type': 'Application/json',
>     Accept: 'Application/json',
>     Authorization: jwt,
>   },
>   data: {},
> })
> ```
> 
> I fixed it by changing `data: {}` to `data: undefined`. This fixed my issue on iOS. It always worked on android for me.

That's really weird, but it's working.Thanks for saving my day.

**Comment by Teeticode** [comment]
Using xhr didn't quite fix my issue but helped me figure out what was going on, if your url is https and returns Network Error on IOS only, the issue could be SSL verification. 

Also after updating the info.plist with the NSAppTransportSecurity for localhost and http, sometimes calling the http endpoint using axios returns a network error, so I'd advice using fetch instead.

Hope this helps someone.

**Comment by SaiEashwarKS** [comment]
I am not sure if this will help anyone. After 30 minutes of debugging this, I found that the issue in my case was VPN. I had connected to a VPN and disconnecting fixed it.

**Comment by jasonschen3** [comment]
I had a similar issue and I solved it by changing this in Info.plist (in ios build folder):
<dict>
      <key>NSAllowsArbitraryLoads</key>
      <false/>
      <key>NSAllowsLocalNetworking</key>
      <true/>
      <key>NSExceptionDomains</key>
      <dict>
        <key><put your key here></key> 
        <dict>
          <key>NSExceptionAllowsInsecureHTTPLoads</key>
          <true/>
        </dict>
      </dict>
    </dict>

The issue was that my backend server was http only.

**Comment by SpectreWulf** [comment]
> I was able to identify a problem on my attempts, we had something being passed into body for a get and was having a hard time tracking it down because the error stated a network error. Android was fine, IOS not so much. After removing the body, we had no issues. I would suggest checking to ensure your call is structured properly. Personally I would qualify this as a bug in my case, and assume your case is similar.
> 
> **To replicate:** add data to the data field of params. **Expected** meaningful error about invalid parameter structure **Result ** network error

HOLY **** !!!

This was the underlying issue for my project, I was passing a "null" data property for GET type requests, but that was the issue, iOS still thinks it's a defective request with a "body" in it.

Changing the logic to only insert a "data" property in the RequestConfig for Axios instance solved the issue.
