### ISSUE TITLE
React Native Axios POST Cors Issue in Emulator

### ISSUE THREAD

**Issue by CoderDark** [axios/axios#3195]
#### Describe the issue
Using axios (POST) on my react native application throws a cors error in emulator.  Using fetch (POST) works fine. 

#### Example Code
Code snippet to illustrate your question

```js
 axios({
    url: "MY_URL_TO_MY_API",
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    data
  }).then((response) => {
    console.log(response);
  }).catch((error) => {
    console.error(error);
  });
```

#### Expected behavior, if applicable
I expect for the axios POST call to be executed and return a 200 status result just like fetch.

#### Environment
 - Axios Version [0.19.2]
 - React [16.8.3]
 - React-Native [0.59.9]
 - Node.js Version [12.4.0]
 - OS: [e.g. iOS 13.6.0, OSX 10.15.6]
- Other Libs:  ["d3": "5.12.0",
    "d3-array": "2.3.1",
    "d3-shape": "1.3.5",
    "lodash.isequal": "4.5.0",
    "lodash.merge": "4.6.2",
    "native-base": "2.11.0",
    "prop-types": "15.7.2",
    "react-native-check-box": "2.1.7",
    "react-native-gesture-handler": "1.3.0",
    "react-native-screens": "2.4.0",
    "react-native-svg": "9.11.1",
    "react-native-svg-charts": "5.3.0",
    "react-native-vector-icons": "6.6.0",
    "react-navigation": "3.13.0",
    "react-redux": "7.1.1",
    "redux": "4.0.4",
    "redux-saga": "1.1.1",
    "uuid": "3.4.0",
    "victory-native": "32.0.2"]

#### Additional context/Screenshots
xhr.js:178 XHR failed loading: POST "MY_URL_TO_MY_API".

index.js:29 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:83)

**Comment by chinesedfan** [comment]
Please give full codes of axios and fetch. Then people can try to reproduce your problem.

**Comment by Toshihiro2010** [comment]
I found same issue . I want solution please.
