### ISSUE TITLE
Response Interceptor's retry is successful, but the original function is not affected

### ISSUE THREAD

**Issue by Heezzan** [axios/axios#3199]
#### Describe the issue
I refer to issue #934 and when I got response error, I changed the token in the header and sent a re-request.  
The re-request returned a status of 200, and I confirmed through the response interceptor that my request works well.  
However, the success function(.then) of original request was not executed.  
In my think, after I confirmed response interceptor works well, It shoud be perform the success function of original request.  
Is this right or is it my problem? Please help me.

#### Example Code
```js
axios.interceptors.response.use(
  function (res) {
    console.log("this is axios-interceptor response");
    console.log(res);
    return res;
  },

  function (err) {
    const originReq = err.config;
    console.log("this is axios-interceptor response ERR");
    console.log(err);
    
    if (err.response.status === 401 && !originReq._retry) {
      originReq._retry = true;
      
      const refreshInfo: any = jwt.decode(store.getters['auth/getUserInfo'].refreshToken.replace("Bearer ", ""));
      
      if (Date.now() - refreshInfo.exp * 1000 < 0) {
        console.log("token refresh start");
        
        store.dispatch('auth/tokenRefresh').then(() => {
          console.log("token refresh fin");
          
          originReq.headers.Authorization = store.getters['auth/getUserInfo'].accessToken;
          console.log(originReq);
          return axios.request(originReq);
        });
      } else {
        console.log("go to logout");
        
        store.commit("auth/logoutSuccess");
        return Promise.reject(err);
      }
    }
  }
)
```

#### Expected behavior, if applicable
After the re-request is successful, the success function of the original request is executed.

#### Environment
 - Axios Version : 0.19.2
 - Adapter [e.g. XHR/HTTP]
 - Browser : Chrome
 - Browser Version :  84.0.4147.105
 - Node.js Version : 12.12.6
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions
   - vue : 2.6.11
   - vuex : 3.4.0
   - jsonwebtoken : 8.5.0

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/25292715/90227450-8bf39300-de4f-11ea-8dbd-2ab2727d526d.png)

**Comment by chinesedfan** [comment]
Maybe what you need is a keyword `return` in the line: `return store.dispatch('auth/tokenRefresh').then`.
