### ISSUE TITLE
About upload file progress

### ISSUE THREAD

**Issue by CocoHuang** [axios/axios#3205]
I use the axios module to upload file(in vscode plugin project,which run in nodejs, not in browse), the file is uploaded sucessfully,but i cannot get the upload progress.
the code is there:
            const file = fse.createReadStream(option.filePath);
            form.append('file', file);
            const header: any = form.getHeaders();
            const reqData = axios({
                method: 'post',
                url: req.url,
                data: form,
                headers: header,
                httpsAgent: new https.Agent({
                    rejectUnauthorized: false
                }),
                maxContentLength: Infinity,
                maxBodyLength: Infinity,
                onUploadProgress: (progressEvent: any) => {
                    const complete = (progressEvent.loaded / progressEvent.total * 100 | 0) + '%';
                    console.log('上传 ' + complete);
                }
            }).then((response: any) => {});

i have get that, the onUploadProgress can use in browse but not nodejs, so how can i do this?
before use axios, i can use request to get the progress.

 const request = require('request');
 const reqData = request.post(req, (error: any, response: any, body: any) =>{};
 let dispatched = reqData.req.connection._bytesDispatched;
 let uploadPercent = Math.round(dispatched / fileSize * PROGRESS_DONE);

#### Environment
 - Axios Version [0.19.0]
 - Adapter [HTTP]
 - Browser [run in nodejs, not in browser]
 - Node.js Version [v14.4.0]

Thanks.

**Comment by jasonHuang2532** [comment]
Run into the same problem

**Comment by jasperHuang-jser** [comment]
It seems Axios don't support onUploadProgress in node.js
