### ISSUE TITLE
Two parallel GET requests work with Firefox but not with Safari

### ISSUE THREAD

**Issue by major-mayer** [axios/axios#3211]
#### Describe the bug
I prepare two promises with Axios for a GET request and want to execute them in parallel with Promise.all().
My API that I'm calling to is generating some url using a UUID, so the response should be different every time.
On Firefox (under Windows) this works all nice and well, but when i try exactly the same under Safari only one requests is acutally sent, and the result for both seperated requests is completly the same.

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// First upload both meshes to S3 to be later processed by the lambda function
        let requestConfig = {
          headers: { "x-api-key": "someApiKey" },
        };

        let firstPromise = Axios.get(
          "someURL",
          requestConfig
        ).then((result) => {
          console.log("First result is:", result); 
          return result;
        });

        let secondPromise = Axios.get(
          "theSameURL",
          requestConfig
        ).then((result) => {
          console.log("Second result is:", result); // This one is exactly the same result as the first one, but it shouldn't be
          return result;
        });

        let [firstResponse, secondResponse] = await Promise.all([
          firstPromise,
          secondPromise,
        ]);

        console.log(firstResponse, secondResponse);  // Both responses are exactly same
```

#### Expected behavior
It should like under Firefox and Windows do two seperated requests and return different results.

#### Environment
 - Axios Version 0.19.2
 - Adapter [e.g. XHR/HTTP]
 - Browser Safari 
 - Browser Version 13.1.2
 - Node.js Version [e.g. 13.0.1]
 - OS: OSX 10.15.6
 - Additional Library Versions VueJS 2.6.11

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.
- Here in the console tab you can see that the filename is definitly the same even though the result comes from two different promises
![Console_LI](https://user-images.githubusercontent.com/17907799/90768568-36a3ff80-e2ef-11ea-814d-192277bd1177.jpg)

- And here in the network tab you can see that only one request is generated ...?
![NetworkTab_LI](https://user-images.githubusercontent.com/17907799/90768832-90a4c500-e2ef-11ea-8c7d-5744b9f2cebc.jpg)

**Comment by major-mayer** [comment]
I already posted them in the first picture, but here you go again.
![Console_LI (2)](https://user-images.githubusercontent.com/17907799/91041913-294d8480-e611-11ea-9ec8-44e629a04620.jpg)


And also the corresponding code part:
![code](https://user-images.githubusercontent.com/17907799/91041812-f1ded800-e610-11ea-8273-8f7dc0b62266.jpg)

Unfortunately the error did not go away magically over the weekend 😄

**Comment by chinesedfan** [comment]
Ah, I mistook your first picture as Firefox logs. Those logs look no problem. Your question is that why only one request is in the network panel. Can you change the request url/params between them? Then we can know which one is in the panel.

**Comment by major-mayer** [comment]
Yes i will do this tomorrow, when i'm back in the office :+1:

**Comment by major-mayer** [comment]
So I found out that the parallel downloads with Promise.all() work when you are using two different urls, but not when you are using the same url.

Here I do two requests to https://jsonplaceholder.typicode.com/posts/1.
Even though they both return the same JSON, there should be two separated requests done.


And the same thing again, but this time the url ends one time with 1 and the other time with 2.
Two separate requests were made, as expected.

**Comment by major-mayer** [comment]
Anything new about this? Could someone reproduce my error?

**Comment by johisco** [comment]
Experiencing the same issue did a workaround where we just added a index variable to the body.
```
const allRequests = [];
  const url = `sameoneurl`;
  for (let i = 0; i < count; i++) {
    allRequests.push(AxiosClient.post(url, null, config));
  }

  return (dispatch) => {
    axios
      .all(allRequests)
      .then(
        axios.spread(() => {
          ...
        })
      )
      .catch((errors) => {
       ...
      });
  };
```

**Comment by major-mayer** [comment]
Good to hear, that I'm not the only one with this error.
Unfortunately your example, which confuses me a bit (where exactly did you add the index variable (i guess `i`right)?), uses a POST request not a GET.
You cannot add something to the body of a GET request, so i doubt this would work for me...

**Comment by major-mayer** [comment]
Okay this issue has somehow resolved for me on Safari 14. But still not good for backwards compatibility reasons I think...

**Comment by gyeongseokKang** [comment]
hello!!

In a similar situation,. the same issue occurred to me.

my situation (Safari + promise.all + aws PreSignedUrl)

so. I temporarily changed the code.

`// before
let videoList = await Promise.all([
  uploadVideo({
    video: { video: userFrontSwingVideo, fileName: userFrontSwingVideo.name },
    setProgress: setProgress("first"),
  }),
  uploadVideo({
    video: { video: userSideSwingVideo, fileName: userSideSwingVideo.name },
    setProgress: setProgress("second"),
  }),
]);

// after
let videoList = await Promise.all([
  uploadVideo({
    video: { video: userFrontSwingVideo, fileName: userFrontSwingVideo.name },
    setProgress: setProgress("first"),
  }),
  // 0.16ms delay for Safari
  sleep(160).then(() =>
    uploadVideo({
      video: { video: userSideSwingVideo, fileName: userSideSwingVideo.name },
      setProgress: setProgress("second"),
    })
  ),
]);`
