### ISSUE TITLE
Axios does not use data from config when making DELETE request

### ISSUE THREAD

**Issue by vadimka123** [axios/axios#3220]
#### Describe the bug
Axios last version (0.20.0) does not use data from config when making DELETE request. In 0.19.2 it's working fine

#### To Reproduce

```js
axios.delete("...", { 
    data: { ids: [...] },
}).then(response => {
    ...
}).catch(error => {
    ...
});
```

#### Expected behavior
Axios send request data from config when making DELETE request

#### Environment
 - Axios Version 0.20.0
 - Browser Chrome 
 - Browser Version 84.0.4147.125
 - Node.js Version 12.18.3
 - OS: Linux Mint
 - Additional Library Versions React 16.13.1

#### Additional context/Screenshots
None

**Comment by pataar** [comment]
+1

**Comment by ggaabe** [comment]
I'm getting this same issue. It took a long time to figure out it was an issue with the package, this is probably a relatively urgent fix.

**Comment by blixt** [comment]
This broke multiple endpoints in subtle ways for us when updating Axios and took some time to identify. I hope for the sake of other companies that this issue is resolved quickly.

**Comment by 14glwu** [comment]
I also meet this problem

**Comment by ogard** [comment]
Same from my side: when updating from v0.19.2 to v0.20.0, **data** argument is not forwarded to network DELETE request

**Comment by nohanna** [comment]
Same problem for me, I had to revert my package-lock.json to understand what was going on.

**Comment by sparkxxxxxx** [comment]
Not use data is recommend by delete request in Restful API. But I think Axios shouldn't be forced to disable

**Comment by wopian** [comment]
@sparkxxxxxx DELETE with a payload (`data`) is part of the HTTP spec. 

https://tools.ietf.org/html/rfc7231#section-4.3.5

**Comment by tim-field** [comment]
FYI the following is a work around until this is fixed
```
return await client.request({
            ...config,
            method: 'delete',
            url,
            data
          })
```

**Comment by sparkxxxxxx** [comment]
@wopian  I'm with you.

**Comment by chinesedfan** [comment]
Kindly invite someone to test with #3282. Hope it solves the problem.

**Comment by wopian** [comment]
@chinesedfan I built #3282 from source and patched it into `node_modules` and [our 6 DELETE tests](https://github.com/wopian/kitsu/pull/463) that mock endpoint responses with `data` now pass

**Comment by dball** [comment]
This seems worthy of cutting `0.20.1` to release sooner than later.

**Comment by jasonsaayman** [comment]
Hi,

Version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks

**Comment by vadimka123** [comment]
Hi, @jasonsaayman 

Tested and issue is fixed 

Thanks

**Comment by dmbarry86** [comment]
> Hi,
> 
> Version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.
> 
> Thanks

Can confirm issue is fixed for us.
