### ISSUE TITLE
Cannot get the progress of upload file in the type of http axios

### ISSUE THREAD

**Issue by CocoHuang** [axios/axios#3225]
#### Describe the issue
I use the axios module to upload file(in vscode plugin project,which run in nodejs,situation of http, not in browse), the file is uploaded sucessfully,but i cannot get the upload progress. I have get that in the browse env, we can use progressEvent to do this, but i donot know what should i do when in the situation of 'http'; 

#### Example Code
```js
 const FormData = require('form-data');
            const form = new FormData();
            const file = fse.createReadStream(option.filePath);
            form.append('file', file);
            const header: any = form.getHeaders();
            const reqData = axios({
                method: 'post',
                url: 'myURL',
                data: form,
                headers: header,
                httpsAgent: new https.Agent({
                    rejectUnauthorized: false
                }),
                maxContentLength: Infinity,
                maxBodyLength: Infinity,
                onUploadProgress: (progressEvent: any) => {
                    const complete = (progressEvent.loaded / progressEvent.total * 100 | 0) + '%';
                    console.log('upload percent: ' + complete);
                }
            }).then((response: any) => {});
```
before use axios, i can use request to get the progress.

```
 const request = require('request');
 const reqData = request.post(req, (error: any, response: any, body: any) =>{};
 let dispatched = reqData.req.connection._bytesDispatched;
 let uploadPercent = Math.round(dispatched / fileSize * PROGRESS_DONE);
```
#### Expected behavior, if applicable
I need get the progress of this upload file action.

#### Environment
 - Axios Version [0.19.0]
 - Adapter [HTTP]
 - Browser [vscode plugin]
 - Node.js Version [v14.4.0]
 - OS: [win 10]

#### Additional context/Screenshots
In the HTTP Adapter of axios, how can we get the progress of upload file.

**Comment by CocoHuang** [comment]
Need your help, thanks. this confused me a long time.
thanks again.

**Comment by chinesedfan** [comment]
[As far as I know](https://github.com/chinesedfan/You-Dont-Know-Axios#request-config), `onUploadProgress` is not supported in http adapter.

**Comment by CocoHuang** [comment]
> [As far as I know](https://github.com/chinesedfan/You-Dont-Know-Axios#request-config), `onUploadProgress` is not supported in http adapter.

Yes, I have gotten that there no onUploadProgress in http adapter, and i have no idea about how to get the upload progress in http adapter, Do you have some good ideas about this?
是的，所以我现在不知道该怎么实现上传进度条，因为在 http adapter 中没有这个事件，请问你有什么好的办法吗。谢谢；

**Comment by chinesedfan** [comment]
Sorry, I have no good idea. See https://github.com/axios/axios/issues/1966#issuecomment-464963763 or use `request` as you tested.
