### ISSUE TITLE
When using method ‘options’,something browser got requesting catch

### ISSUE THREAD

**Issue by YYDD** [axios/axios#3227]
#### Describe the issue
I want to use method 'options' to get the serve status when is broken.
But in different browers, I got different result. In almost browers, it works well. But in some browers(like safari v11.1) it will go catch branch. So is anyone can help me,to tell how is the reson.
ps all the browers is in http1.1

#### Example Code

```js
 axios.options('http://xxxx.com/xx').then(res => {

  }).catch(res => {
  });

```

**Comment by chinesedfan** [comment]
> But in some browers(like safari v11.1) it will go catch branch.

What does the catch block say? A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response.

**Comment by YYDD** [comment]
> > But in some browers(like safari v11.1) it will go catch branch.
> 
> What does the catch block say? A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response.

this is bad request.
![image](https://user-images.githubusercontent.com/8803409/91306979-f0173f00-e7df-11ea-9ea3-5bfd0ef0158d.png)

this is right request.
![image](https://user-images.githubusercontent.com/8803409/91307023-002f1e80-e7e0-11ea-8320-8946e322aab0.png)

**Comment by chinesedfan** [comment]
Origin and referer are different. Did you install some plugins or proxies in your bad browser?

**Comment by YYDD** [comment]
> proxies

no plugins and proxies in bad browser. So I was confused.

**Comment by wopian** [comment]
> Origin and referer are different.

Those two origins are the same, just resolved differently.

- 127.x.x.x:8083 is the port on the device's local network
- 192.x.x.x:8083 is the device's port on the router/modem's local network.
