### ISSUE TITLE
latest version not support BigInt parameter

### ISSUE THREAD

**Issue by Lautitia** [axios/axios#3230]
#### Describe the issue
I try to access api which wrote by Java, there is one parameter's type is Long, but when i use BigInt the axios says

    TypeError: Do not know how to serialize a BigInt
is there anybody knows how to use BigInt in axios please tell me, thanks
#### Example Code

```js
// Example code just like
const params = {
    id: BigInt(accountId)
};
const resp = await axios.post(url, params, {
    'Content-Type': 'application/json'
});
```

#### Expected behavior, if applicable
successful call the api

#### Environment
 - Axios Version [0.20.0]
 - Node.js Version [14.8.0]

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/473392/91276406-19ba7100-e7b4-11ea-9c47-0a870e5e4e44.png)

**Comment by chinesedfan** [comment]
It depends on how your server API handles the parameter, and I don't know where your `BigInt` comes from. In Javascript, there are only `number` or `string`. If the parameter is not too large, `number` is enough, or you should use `string` and ask the server to parse it.

**Comment by Lautitia** [comment]
I know the server can parse it of course, but type is the important, i want to use the suitable type, the parameter save by number may have the probability to overflow, so now i can only use string to deal the parameter right?

**Comment by chinesedfan** [comment]
BigInt is in stage 4. And not all browsers support it yet.

The problem can be considered as how to `JSON.stringify` a BigInt, as you use `'Content-Type': 'application/json'`. https://github.com/tc39/proposal-bigint/issues/24#issuecomment-538703414 may help you. A simple and not tests sample is,

```
const params = {
    id: BigInt(accountId)
};

// use the `toJson` in the link
const resp = await axios.post(url, toJson(params), {
    'Content-Type': 'application/json'
});
```

**Comment by Lautitia** [comment]
Thank you for you help, I will try it
