### ISSUE TITLE
Axios post not working in conjunction with electron where fetch api works

### ISSUE THREAD

**Issue by Quenos** [axios/axios#3236]
#### Describe the bug
axios.post returns a 400 error, where a fetch post request with exactly the same data does not

#### To Reproduce
It is hard to reproduce it as you will need an API key pair, but below I copy the code that doesn't work
```js
axios
 .post("symbol=BTCUSDT&side=BUY&type=MARKET&quantity=0.001&recvWindow=120000&signature=63edf8d97c20195bc56f8df53ed47620618cd8bea15ede2ba6cfac40b8d49718&timestamp=1598709581374",
  {},
  { 
    headers: { "X-MBX-APIKEY":  "xxx" }
  })
```

The fetch code that works is:
```js
          const response = await fetch("symbol=BTCUSDT&side=BUY&type=MARKET&quantity=0.001&recvWindow=120000&signature=63edf8d97c20195bc56f8df53ed47620618cd8bea15ede2ba6cfac40b8d49718&timestamp=1598709581374", {
            method: "POST",
            headers: { "X-MBX-APIKEY":  "xxx" }
                    })
```

#### Expected behavior
post request is sent and executed by the receiver

#### Environment
 - Axios Version [e.g. 0.19.2]
 - Adapter HTTP
 - Browser chromium (electron 9.0.0)
 - Node.js Version [e.g. 13.0.1]
 - OS: iOS catalina latest

#### Additional context/Screenshots
I have one other post request with axios to the same api but different end point which does work, but that one has no parameters

**Comment by Ionys320** [comment]
Hello,
When you do your request with Axios, you do a PUT request, but when you use the fetch function, you do a POST request. Maybe your bug come here ;-)

**Comment by Quenos** [comment]
@Ionys320 No unfortunately not. That was a copy paste error. :(

**Comment by chinesedfan** [comment]
A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response, like the network panel of browser.

**Comment by Quenos** [comment]
This is still present

**Comment by uotw** [comment]
This worked for me, solution from [here](https://stackoverflow.com/a/66619143/3198281).

```
await axios.post(url, form,  {
    headers: {
        ...form.getHeaders(),
    },
    adapter: require('axios/lib/adapters/http'),
    })
}
```
