### ISSUE TITLE
Axios on node.js parsed XML response

### ISSUE THREAD

**Issue by Eric24** [axios/axios#3238]
#### Describe the issue
I'm really just trying to figure out how something is happening: When using Axios on node.js, an HTTP GET that returns an XML body is presented in the response `data` property already parsed. I was surprised by this (and was expecting to get back text that I needed to pass through an XML parser to get a JS object). I could not find any mention of this functionality, nor could I find a reference to an XML parser in the Axios source code.

#### Example Code
Code snippet to illustrate your question

```js
      let url = `${PB_PID}${values.source}`;
      let result = await http.get(url, {
        timeout: 4000,
        responseType: 'text',
        maxContentLength: 65536
      });
      let data = result.data;  // data is a JS object, parsed from the received XML response
```

#### Expected behavior, if applicable
I would have expected `data` to contain text. It's not necessarily bad that it automatically parsed the XML, but I want to understand why/how this is happening, for a variety of reasons, including that this may not always be the desired result.

**Comment by Zikoel** [comment]
Can we reopen this issue ? I noticed the same behaviour and I want to know more!

**Comment by Eric24** [comment]
@Zikoel - Based on further research, I'm convinced that Axios is not parsing the XML response. What I believe is happening is that the third-party API service I was calling returned JSON based on the `accept` header (default is "application/json"). I had mistakenly thought that setting `responseType` would also change this header, but it does not. So try setting your `accept` header to "application/xml" and see if you get back XML.

**Comment by Zikoel** [comment]
Absolutely true! I discover the same things some ours ago sniffing the traffic! Thanks a lot.
