### ISSUE TITLE
Is there a place to get all error codes that can be returned by axios request.

### ISSUE THREAD

**Issue by geetanshjain** [axios/axios#3241]
#### Section/Content To Improve
Quote or link to section

#### Suggested Improvement
Identify what is confusing or incorrect and what could make it better:
i have a api call for which I want to capture the errors to set the corresponding status.
Sometimes i get ECONNABORTED, sometimes ENETUNREACH and they are coming in error.code
Is there a place to look for all such possible error codes so that I can map accordingly.
#### Relevant File(s)
[e.g. README.md]

**Comment by chinesedfan** [comment]
axios didn't provide a document for it, but you can find them in axios source codes, including lib/adapters/xhr.js and lib/adapters/https.js.

In fact, the error code is indicated for each operating system. Refer to https://www.columbia.edu/sec/acis/db2/db2m0/db2tcp.htm.
