### ISSUE TITLE
Document Content-Type behavior on GET request

### ISSUE THREAD

**Issue by lingxiaoyang** [axios/axios#3247]
#### Section/Content To Improve

https://github.com/axios/axios#request-config

>  // `headers` are custom headers to be sent
>  headers: {'X-Requested-With': 'XMLHttpRequest'},

>   // `data` is the data to be sent as the request body
>  // Only applicable for request methods 'PUT', 'POST', 'DELETE , and 'PATCH'

#### Suggested Improvement

The documentation should be clearer on the magic behind the suppression of Content-Type header. As people discovered in #86 and so, this header is not applied to GET request, which has its reason but axios also allows circumventing it by providing `data: null` or `data: {}` in request config.

A proper documentation on any part of this magical loop will help:
- Educate developers that Content-Type is only sensical on POST/PUT/PATCH where the request has a body.
- Clarify that `data` has its effect on GET method, as opposed to the quoted above.

#### Relevant File(s)

README.md at root

**Comment by riqkml** [comment]
i have same issue, i already try all step, but doesnt work's to me

**Comment by jasonsaayman** [comment]
Closing as this seems to be working correctly
