### ISSUE TITLE
url cannot be set in defaults anymore in v0.20.0

### ISSUE THREAD

**Issue by ddolcimascolo** [axios/axios#3250]
#### Describe the bug

The `url` option cannot be set in defaults anymore

#### To Reproduce

Runkit with v0.20.0 (failing): https://runkit.com/embed/ljc1r77qoyte
Runkit with v0.19.2 (succeeding): https://runkit.com/embed/ky5awf7v4b4x

```javascript
const axios = require("axios"),
      request = axios.create({ url: 'https://npm.runkit.com/axios' });

await request().then(({ data }) => data);
```

#### Expected behavior

The `url` option should be settable in defaults.

#### Environment

 - Axios Version [0.20.0]
 - Adapter [HTTP]
 - Node.js Version [12]
 - OS [Ubuntu 20.04]

#### Additional context/Screenshots

N/A

**Comment by ddolcimascolo** [comment]
This is a major breaking change or I am missing something ?

**Comment by jasonsaayman** [comment]
Hi @ddolcimascolo,

That seems like a pretty major breaking change. I will investigate as soon as possible.

Thanks

**Comment by NyxCode** [comment]
baseURL doesn't seem to have any effect either. Just broke my app, 0.19 works fine though.

**Comment by epsy-me** [comment]
What the hell is it all broken, so with "baseURL"
Developers, have you smoked?

**Comment by epsy-me** [comment]
Explain to the blunt how it happened?

`const config = {
  baseURL: process.env.VUE_APP_API, // https//api.cp.epsyteam.ru
  timeout: 30000,
  validateStatus (status: number) {
    return status < 500 // Resolve only if the status code is less than 500
  }
} as AxiosRequestConfig

const _axios: AxiosInstance = axios.create(config)`

`Request URL: http://45.90.35.130:3000/https//api.cp.epsyteam.ru/chat?offset=-1&count=100`

**Comment by epsy-me** [comment]
!!! NOT WORKING !!!
`
  getChatList (offset: number = -1, count: number = 100): Promise<Array<Conversation>> {
    return new Promise<Array<Conversation>>((resolve, reject) => {
      $axios.get(`${process.env.VUE_APP_API}/chat`, {
        baseURL: process.env.VUE_APP_API,
        params: { offset, count }
      }).then((response: AxiosResponse) => {
        if (response.status === 200) {
          return resolve(response.data.response)
        }
        reject(response.data)
      }).catch(reject)
    })
  }
`

**Comment by mathewepstein** [comment]
seems like baseURL still works: https://runkit.com/mathewepstein/5f5114427e7481001ac547ad

**Comment by NyxCode** [comment]
I used to set baseURL to `/api`, like I would do in html. In 0.19, axios appended `/api` to the host. Now, it is just ignored.

**Comment by epsy-me** [comment]
![uIEWOyilhB](https://user-images.githubusercontent.com/67442521/92145789-6be93b00-ee21-11ea-9cf4-1e595218c8a7.gif)

**Comment by NyxCode** [comment]
@epsy-me you are missing a : in your url.. 🤦

**Comment by epsy-me** [comment]
> @epsy-me you are missing a : in your url.. 🤦

Are you saying that this is not a working option?

`_axios.get('https//api.cp.epsyteam.ru/chat')
  .then((r: AxiosResponse) => {
    console.log(r)
  })`

**Comment by epsy-me** [comment]
> @epsy-me you are missing a : in your url.. 🤦

Show me how you need it, it doesn't work for me at all.

**Comment by epsy-me** [comment]
`
import Vue from 'vue'
import axios, {AxiosInstance, AxiosRequestConfig, AxiosResponse} from 'axios'
import { Cookies } from 'quasar'
import { app } from '@/main'

// Full config:  https://github.com/axios/axios#request-config
// axios.defaults.baseURL = process.env.VUE_APP_API;
// axios.defaults.headers.common['Authorization'] = AUTH_TOKEN;
// axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';

const config = {
  baseURL: process.env.VUE_APP_API,
  timeout: 30000,
  validateStatus (status: number) {
    return status < 500 // Resolve only if the status code is less than 500
  }
} as AxiosRequestConfig

const _axios: AxiosInstance = axios.create(config)
const _axiosForRefresh: AxiosInstance = axios.create(config)

_axios.interceptors.request.use(
  async function (config) {
    if (Cookies.has('access_token')) {
      config.headers.Authorization = `Bearer ${Cookies.get('access_token')}`
    } else {

      if (Cookies.has('refresh_token')) {
        await _axiosForRefresh.post('/account/authorization/refresh-token', {
          refresh_token: Cookies.get('refresh_token')
        }).then((response: AxiosResponse) => {
          if (response.status === 200) {
            Cookies.set('access_token', response.data.access_token, { expires: `${(response.data.expires_in / 60 / 60) - 12}h`, path: '/' })
            Cookies.set('refresh_token', response.data.refresh_token, { expires: '30d', path: '/' })
            config.headers.Authorization = `Bearer ${response.data.access_token}`
          }
        }).catch((err) => {
          console.error(err)
        })
      }
    }
    return config
  },
  function (error) {
    // Do something with request error
    return Promise.reject(error)
  }
)

/*
  Array of patterns to ignore status checks.
 */

const PATTERNS_FOR_IGNORE_RESPONSE_INTERCEPTOR = [
  /\/account\/profile\/change-password/
]

// Add a response interceptor
_axios.interceptors.response.use(
  function (response: AxiosResponse) {

    for (let i = 0; i < PATTERNS_FOR_IGNORE_RESPONSE_INTERCEPTOR.length; i++) {
      const regx: RegExp = PATTERNS_FOR_IGNORE_RESPONSE_INTERCEPTOR[i]
      // @ts-ignore
      if (regx.test(response.config.url)) {
        return response
      }
    }

    // If not authorized then go to login page
    if (response.status === 401) {
      app.$router.replace('/login')
    }

    return response
  },
  function (error) {
    // Do something with response error
    return Promise.reject(error)
  }
)

class AxiosPlugin {
  install () {
    Object.defineProperties(Vue.prototype, {
      axios: {
        get () {
          return _axios
        }
      },
      $axios: {
        get () {
          return _axios
        }
      }
    })
  }
}

const axiosPlugin: AxiosPlugin = new AxiosPlugin()

Vue.use(axiosPlugin)

export default axiosPlugin
export const $axios: AxiosInstance = _axios

`

`
...
  getChatList (offset: number = -1, count: number = 100): Promise<Array<Conversation>> {
    return new Promise<Array<Conversation>>((resolve, reject) => {
      $axios.get('/chat', {
        params: { offset, count }
      }).then((response: AxiosResponse) => {
        if (response.status === 200) {
          return resolve(response.data.response)
        }
        reject(response.data)
      }).catch(reject)
    })
  }
...
`

This combination worked until recently.

**Comment by epsy-me** [comment]
In short, it doesn’t work, I don’t know what the developers did there.

**Comment by zapplebee** [comment]
There is no test coverage for this as a use case.

https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/test/specs/options.spec.js#L59

It is not made clear that the URL option can be set in the `create` method. Create is intended for creating an instance, not a request.

Defining `url` in the instance is not a documented way to perform a request. Its seems to me that the that fact that it worked in 0.19.2 was not a feature, but an unexpected success.

**Comment by epsy-me** [comment]
Don't make my mistakes.
Error in the image.
![Uploading image.png…]()

**Comment by NyxCode** [comment]
> @epsy-me you are missing a : in your url.. 🤦
---
I'll create a seperate issue for what i've discovered

**Comment by Djunnni** [comment]
hey where is colon?

it is https://{your url}  not https//{your url}

**Comment by epsy-me** [comment]
> hey where is colon?
> 
> it is https://{your url} not https//{your url}

I meant it.
I spent half a day looking for this error.

**Comment by jasonsaayman** [comment]
Hi All,

Ok well, I have had a look at this and even though in 0.19.2 this worked, I think it was not intended to work that way if you read the doc's you will see `baseURL` is documented as a settable option for the instance but just setting URL is not. 

This does however seem to have introduced a breaking change albeit for a feature that did not exist and was undocumented. I don't think that there is anything that we can do that can stop this from happening in the future my advice would be to work within the realm of the documentation and you will be safe from breaking changes as the documentation is the most accurate source of truth.

Thanks

**Comment by groksrc** [comment]
I don't understand why this issue was closed. It's clearly a breaking change. In 0.18 you can pass a `baseURL` and a `url` in the config and it correctly appends the two together. When we went to update to 0.20 it is broken. Using the `url` config option is clearly documented in the README. This should be reopened and fixed.

**Comment by tenkiller** [comment]
> I don't understand why this issue was closed. It's clearly a breaking change. In 0.18 you can pass a `baseURL` and a `url` in the config and it correctly appends the two together. When we went to update to 0.20 it is broken. Using the `url` config option is clearly documented in the README. This should be reopened and fixed.

Furthermore, does [this](https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js#L18) not imply that `url` is supported as a config override value?

**Comment by jasonsaayman** [comment]
> I don't understand why this issue was closed. It's clearly a breaking change. In 0.18 you can pass a `baseURL` and a `url` in the config and it correctly appends the two together. When we went to update to 0.20 it is broken. Using the `url` config option is clearly documented in the README. This should be reopened and fixed.

@groksrc Can you explain where in the instance documentation you see using `url` as an instance variable option being a valid use case? It used to work in 0.18 but that was not an intended use case and was fixed in 0.20.

**Comment by HerrTamm** [comment]
Perhaps fix typings then? Because it's really confusing as we also provided `url` to client and debugging this was a nightmare.

**Comment by jasonsaayman** [comment]
Ok, I will try to do that, adding it to my list.
