### ISSUE TITLE
Relative URLs don't work as baseURL in 0.20 (browser)

### ISSUE THREAD

**Issue by NyxCode** [axios/axios#3254]
#### Describe the bug
On 0.19, I used to set baseURL to a relative URL like this:
```
axios.defaults.baseURL = '/api'
```
This would append `/api` to the current `window.location.host`, like this:
```
axios.get("/contracts/1/invoices") // GET https://{window.location.host}/api/contracts/1/invoices
```
On 0.20, setting baseURL like this has no effect. 
This occurs in all major browsers.

#### To Reproduce
```js
axios.defaults.baseURL = '/images';
axios.get("/cat.jpg");
```
Run this in a browser

#### Expected behavior
`GET {protocol}://{window.location.host}/images/cat.jpg`

#### Environment
 - axios 0.20.0
 - All major browsers

#### Additional context/Screenshots
N/A

**Comment by Djunnni** [comment]
as you know, defaults baseURL need protocol and address where to request

but you just use api path. i don't know exactly whether you use things like express, cdn or not 

how axios know your location host automatically? i think it's not 

 it is poor in how to use axios.

**Comment by NyxCode** [comment]
how about you read my issue first?

---

> as you know, defaults baseURL need protocol and address where to request

where is this documented? it worked in 0.19

---

> how axios know your location host automatically? i think it's not

> This would append /api to the current window.location.host, like this:

I think this behavior was pretty intuitive, since this is how relative urls work in html.

---

> or i think you don't run web server

I think you don't know how to read or not to be an asshole.

**Comment by chinesedfan** [comment]
Failed to reproduce. Did I miss something? And what request url did you see in fact?

If deployed in local, the following test.html sends a request to `http://127.0.0.1:8080/images/cat.jpg`.

```
<!-- the CDN points to 0.20.0 -->
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript">
    axios.defaults.baseURL = '/images';
    axios.get("/cat.jpg");
</script>
```

**Comment by groksrc** [comment]
This seems to be related to #3250

**Comment by tenkiller** [comment]
@Djunnni 
>as you know, defaults baseURL need protocol and address where to request

That is incorrect. A URL with no protocol or host is a [relative URL](https://www.w3.org/TR/WD-html40-970917/htmlweb.html#h-5.1.2). This is a pretty basic understanding of how the Web works. And, it is indeed supported in Axios.

**Comment by maksim-chekrishov** [comment]
have the same issue with  axios v 1.6.2
