### ISSUE TITLE
use interceptor for request to return custom response

### ISSUE THREAD

**Issue by kirakatou** [axios/axios#3258]
#### Describe the issue
I want to cache request that send to specific url and send it later

#### Example Code
Code snippet to illustrate your question

```js
function requestHandler(request) {
    if (request.method.toUpperCase() !== 'GET') {
        if (request.url == 'api/cache/this') {
            storeRequest(request) // method to cache request in IndexedDB
            return reponse // i want to return custom response here like request has been cached
        }
    }
    return request;
}

client.interceptors.request.use((request) => requestHandler(request));
```

#### Expected behavior, if applicable
can return response when some url match

#### Environment
 - Axios Version 0.18.1
 - Adapter [HTTP]
 - Browser [Firefox]
 - Browser Version [80.0]
 - Node.js Version [13.0.1]

#### Additional context/Screenshots
just need to know how to return response from request interceptor

**Comment by chinesedfan** [comment]
> how to return response from request interceptor

Nope. You should return fake response in response interceptor.

**Comment by rudolfbyker** [comment]
The best solution I could find is to override the `.get` method. However, I'm not convinced that this is 100% reliable (e.g. if you use `ax.request` directly, it won't work).

```
const originalGet = ax.get;
ax.get = async (url, config) => {
  if (...) {
    // Send a custom response for this request. The back end will not know about this.
    return {
      data: {...},
      status: 200,
      statusText: "OK",
      headers: {},
      config,
      request: {},
    };
  }

  // Let the request go through to its intended destination.
  return await originalGet(url, config);
};
```

**Comment by g-belmonte** [comment]
I know this is an old issue, but I was looking for an answer to that too... and I didn't find any!
Since the request is handled by the adapter, I ended up creating my own adapter:

```typescript
const instance = axios.create();
this.instance.interceptors.request.use(async (request) => {
  const cachedResponse = await tryToFindStuffInTheCache()
  if (cachedResponse) {
    request.adapter = (config) => {
      return new Promise(() => {
        Promise.resolve({
          __cached: true,
          data: cachedResponse,
          status: 200,
          statusText: 'OK',
          headers: request.headers,
          config,
          request,
        })
      })
    }
  }
  return request;
});
this.instance.interceptors.response.use(async (response) => {
  if (response.__cached) {
    return response;
  } else {
    await putTheResponsePayloadIntoTheCache(response.data);
    return response;
  }
});
```
In my case the data on the cache is immutable, so no need to  invalidate the cache on update/delete operations. If what you have in the cache is immutable, don't forget to invalidate cache when modifying their contents!
