### ISSUE TITLE
TypeScript incorrectly inferring type of axios post return

### ISSUE THREAD

**Issue by RenegadeMaster** [axios/axios#3264]
#### Describe the issue
A clear and concise description of what the issue is.

When using axios with typescript, for some reason TypeScript "Unwraps" the outer AxiosResponse object

#### Example Code
Code snippet to illustrate your question

```js
//consider method as follows:

public registerUser(body: RegisterDTO):  Promise<AxiosResponse<string>> {
        return this.instance.post<string>(`/user/register`, body);
    }

//I use this in another file as follows:

let result = await UserApi.getInstance().registerUser(user);

```

#### Expected behavior, if applicable

I expect result to have type AxiosResponse <string>  but instead it is inferred by editor and compiler to have type string.
Therefore I am unable to e.g. say if (result.status)
Note that logging result to console or setting a breakpoint shows that result is indeed of type AxiosResponse<string> not just string

#### Environment
 - Axios Version [e.g. 0.18.0]
0.20.0
 - Adapter [e.g. XHR/HTTP]
N/A
 - Browser [e.g. Chrome, Safari]
N/A
 - Browser Version [e.g. 22]
N/A
 - Node.js Version [e.g. 13.0.1]
v10.19.0
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
Ubuntu 20.04
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]
TypeScript 4.0.2
Vue 2.6.12

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
> it is inferred by editor and compiler to have type string

Sorry, my editor works well.

<img width="653" alt="截屏2020-09-12下午2 40 00" src="https://user-images.githubusercontent.com/1736154/92989306-e5f67f80-f505-11ea-8c1c-db10e4d91d51.png">

**Comment by RenegadeMaster** [comment]
Hmm this is weird because I tried two different editors (Rider and VS Code) and in addition without using an editor, the TypeScript compile complains from the command line. Can I ask what version of TypeScript and Axios you are using @chinesedfan ?

**Comment by chinesedfan** [comment]
The version of ts is 3.9 and axios is 0.20.0. It should be related to your project's tsconfig or something else. I declared the same interface function without implementation. If you confirm that your cli also throws type errors, please provide a minimum demo repository.

**Comment by ariabuckles** [comment]
For posterity, I think this is likely caused by: https://github.com/axios/axios/issues/3363#issuecomment-784514055
