### ISSUE TITLE
Can I use Keep-Alive with https Proxy with Axios ?

### ISSUE THREAD

**Issue by ruslanx3m** [axios/axios#3274]
#### Describe the issue
Can I use Keep-Alive with https Proxy with Axios ? and how ? I can use at moment only 'keepalive' or 'https proxy' .. I want both use ..

#### Example Code

```
const axios = require('axios');
const HttpsProxyAgent = require('https-proxy-agent');

const httpsAgent = new HttpsProxyAgent('http://xx.xx.xx.xx:xxxx');

var config = {
httpsAgent,
    method: 'get',
    url: myURL,
    headers: {
        'Connection': 'keep-alive',
    }
};

axios(config)
    .then(function (response) {
        console.log(JSON.stringify(response.data));
    })
    .catch(function (error) {
        console.log(error);
    });
```

#### Environment
 - Axios Version [e.g. 0.20.0]
 - Node 14

**Comment by chinesedfan** [comment]
Looks like it should be. What problem did you find? And how did you check whether Keep-Alive works?

**Comment by ruslanx3m** [comment]
how to use with proxy ... can some show example ?
