### ISSUE TITLE
"Taking longer than usual" feature

### ISSUE THREAD

**Issue by fabienlem** [axios/axios#3276]
#### Describe the issue
I'd like to implement a feature that exists on a lot of applications that consume API, to display a message when a request takes longer than usual.

I wonder how to do that properly with Axios?

#### Example Code
N/A

#### Expected behavior, if applicable
If this is not straight forward, I think an interesting feature for Axios would be to call a hook or fire an event after a dedicated timeout.

I noticed the existing "timeout" config param, but when reached, the request is aborted.

What do you think of this proposal?

#### Environment
 - Axios latest version

#### Additional context/Screenshots
N/A

**Comment by chinesedfan** [comment]
You can implement it by yourself with another timer, instead of any changes in axios. Just remember to clear the timer when axios returns.

```
var timer = setTimeout(() => {
  alert('longer than usual')
}, normalTimeout)

axios(url).then(() => {
  clearTimeout(timer)
})
```

**Comment by fabienlem** [comment]
Thank you @chinesedfan for your reply!
