### ISSUE TITLE
Have issues Network error on IOS 11 & 12 

### ISSUE THREAD

**Issue by nguyenvannghi** [axios/axios#3278]
#### Describe the issue
Axios.get() not working on IOS 11 & 12 and I got issues: 
`1. {"name":"Error","message":"Network Error","stack":"createError@http://10.124.3.25:3001/static/js/0.chunk.js:4802:24\nhandleError@http://10.124.3.25:3001/static/js/0.chunk.js:4297:25"}`
`2. {"name":"TypeError","message":"Right side of assignment cannot be destructured","stack":"parseResponse@http://10.124.3.25:3001/static/js/2.chunk.js:511:63\npromiseReactionJob@[native code]"}`

#### Example Code

```js
const HttpInstance = (headers = null, baseURLDomain = null) => {
    class ApiConfig {
        constructor(enforcer) {
            if (enforcer !== singletonEnforcer) {
                throw new Error('Cannot construct singleton');
            }

            this.client = getClient(headers, baseURLDomain);
        }

        static get instance() {
            // Try to get an efficient singleton
            if (!this[singleton]) {
                this[singleton] = new ApiConfig(singletonEnforcer);
            }

            return this[singleton];
        }

        get(url, conf = {}) {
            return this.client
                .get(url, conf)
                .then((response) => Promise.resolve(response))
                .catch((error) => Promise.reject(error));
        }
    }
    return ApiConfig.instance;
};

export default HttpInstance;



export const getConversationApi = (eventId, time) => {
    const httpClient = HttpClient({
        authorization: `Bearer ${Config.TOKEN}`,
    });
    return httpClient.get(`chats/internal/${eventId}/${time}`);
};
```

#### Environment
Axios Version ^0.20.0
Browser Safari
Node.js Version v13.7.0
OS: 11.3, 12.3.1
React 16.13.1

#### Additional context/Screenshots
https://user-images.githubusercontent.com/23132483/92897197-335fe780-f447-11ea-8f83-1da88a134ad6.png

**Comment by chinesedfan** [comment]
Is it a problem that the server can't response correctly? A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response.

**Comment by nguyenvannghi** [comment]
> Is it a problem that the server can't response correctly? A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response.

I checked. But it working on ios 13

**Comment by xakoy** [comment]
Same question.
The problem occurs when the axios request does not end and the page jumps (such as window.location.href='xx').

Only when safari,ios safari and mac safari have the same problem.
mac safari: 14.0
ios safar: 13.7.

**Comment by hxdyj** [comment]
Same question

**Comment by dlmp7895** [comment]
confirm, I am in the process of learning.

**Comment by AlissonRS** [comment]
I'm facing the same issue.

It works in Android and desktop browsers, but when using in iOS 11~12 it fails with "Network Error".

**Comment by hxdyj** [comment]
It's not axios problom, It's IOS browser problom, you need add all of used http request header to server,like this
```
Access-Control-Allow-Headers：access_token,otherHeader,*/*
```
If you only add `*/*` , It also has problom, you need add all you used of header to allow-header.

**Comment by jasonsaayman** [comment]
Closing this issue in favour of #3192

**Comment by AlissonRS** [comment]
@jasonsaayman can you elaborate on how #3192 relates to this? The solution provided there is for React Native, this particular issue is related to any applications using Axios in iOS 11 & 12 (Vue, Angular, etc), not necessarily React Native.

**Comment by jasonsaayman** [comment]
Ok, please can you provide a detailed example to test this on?

**Comment by jasonsaayman** [comment]
The above is not a fully testable example, I need something that is ready to run and gives me the same error then I can have a look.

**Comment by AlissonRS** [comment]
@jasonsaayman sure, I'll try to provide a reproducible example this week and let you know.

**Comment by pazreshef-clear** [comment]
Hi, we have the same issue.
While sending request in safari, the request fails if the user presses back or refresh.
as @xakoy mentioned, it happens when the request doesn't end.

Reproducible in both axios 0.X.X and 1.X.X and iOS 15.X and 16.X

**Comment by mi-mazouz** [comment]
Same issue ! @nixjs Did you find a fix ?
