### ISSUE TITLE
Built-in Brotli Support (not decompress: false + transformResponse workaround)

### ISSUE THREAD

**Issue by Fonger** [axios/axios#3284]
#### Is your feature request related to a problem? Please describe.
https://github.com/axios/axios/issues/1635#issuecomment-603258750 suggest a way to support brotli however...

#### Describe the solution you'd like
I think this should be included in the library, as brotli has become very common nowadays and is supported by many browsers. If axios on client(browser) support Brotli content, server should support too.

Most cloudflare resources now served as brotli encoding.
And some node.js popular packages, for instance, [koa-compress](https://github.com/koajs/compress) for koa.js has support for brotli compression. [compression](https://github.com/expressjs/compression/pull/172) for express.js is on the way too.

#### Describe alternatives you've considered
Surely we can achieve this by `{ decompress: false }` + `transformResponse()` but we have to deal with the same logic and handle it like http adapter does internally (detect content-encoding headers and remove content-encoding headers). 

I think this should be supported by native.
Node.js < 10 has reached EOL so that means all stable node.js support brotli now.
And you can keep the backward compatibility by checking the function exists ( Like what PR #2071 did) .

#### Additional context
We have been using patched axios for a long time. Hope this can be a built-in feature in this great library.

**Comment by lucaswerkmeister** [comment]
I think this was actually implemented in bdf493cf8b.
