### ISSUE TITLE
Document breaking changes

### ISSUE THREAD

**Issue by medikoo** [axios/axios#3294]
#### Section/Content To Improve

https://github.com/axios/axios/releases/tag/v0.20.0

#### Suggested Improvement

It's not clear what breaking changes where introduced with v0.20 over v0.19

#### Relevant File(s)

N/A

**Comment by BlitZz96** [comment]
As stated in their [contributing file](https://github.com/axios/axios/blob/master/CONTRIBUTING.md#releasing), they do follow semantic versioning. This means 0.19.x -> 0.20.x has no breaking change.
However, they might have thought that there was no breaking change, but in reality there is. This is human error that we are all prone for.

**Comment by Ashenfactory** [comment]
A special case is made for versions below 1.0 as per the [SemVer section of the README](https://github.com/axios/axios#semver):
"Until axios reaches a 1.0 release, breaking changes will be released with a new minor version. For example 0.5.1, and 0.5.4 will have the same API, but 0.6.0 will have breaking changes."

**Comment by medikoo** [comment]
>  but 0.6.0 will have breaking changes

@Ashenfactory exactly, point of this issue, that release notes of v0.20 do not list breaking changes, while in semver section of the README it's indicated that minor releases will be breaking.

**Comment by jasonsaayman** [comment]
@medikoo We tried to not make any breaking changes, from what I had seen most of the changes passed without any new tests and also did not look to directly brin about a breaking change. I only know of 2 changes that seem to have broken something, one being the changes with `baseURL` #3250 however this change was breaking only if you were implementing and using Axios in a way that the documentation does not lend itself too, in which case I think it would be on the person implementing in that way and not on Axios.

The other issue I am aware of is the `delete` #3220 issue and this is kind of linked to the above changes that occurred with regards to `mergeConfig` and was definitely unintend and crept in without us really seeing it. I will put in a pull request to show the breaking changes in the doc's however the delete issue will be remedied in a v0.20.1 release.
