### ISSUE TITLE
use axios to send a POST request but encounter the error "Error: Client network socket disconnected before secure TLS connection was established"

### ISSUE THREAD

**Issue by Jas0nY** [axios/axios#3298]
#### Describe the issue
 i am now creating a Oauth app with github, i get the code which was send by github server, now i want to send a POST request to https://github.com/login/oauth/access_token?  with client_id, client_secret and code. but i encountered the error:
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1092:19)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

#### Example Code
async ctx => {
const requestToken = ctx.request.query.code;// get the code from redirect_uri
console.log(‘authorization code:’, requestToken);
const tokenResponse = await axios({
method: ‘post’,
url: 'https://github.com/login/oauth/access_token?’ 1 +
client_id=${clientID}& +
client_secret=${clientSecret}& +
code=${requestToken},
headers: {
accept: ‘application/json’
}
});
const accessToken = tokenResponse.data.access_token;
console.log(access token: ${accessToken});

```js
// Example code here
```

#### Expected behavior, if applicable
i will get a json response

#### Environment
 - Axios Version [ 0.20.0]
 - Browser [Chrome]
 - Node.js Version [10.16.1] also tried the latest version
 - OS: [win10 2004]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It seems like a problem that the server can't response correctly. A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
