### ISSUE TITLE
post 方法里面，data的某个字符串属性的最大长度能使多少

### ISSUE THREAD

**Issue by mingmLiang** [axios/axios#3299]
#### Describe the issue
A clear and concise description of what the issue is.
post方法的时候，data里面的某个字符串属性部分丢失。我传的是超大图（有达到40.50M）的base64。
#### Example Code
Code snippet to illustrate your question

```js
// Example code here
this.$axios.post(url,data:{str: 'xxx'});
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
> data的某个字符串属性的最大长度能使多少

It depends on the data limit of HTTP POST and how the server handles the request. axios doesn't add other limits on it.

> 某个字符串属性部分丢失

Maybe you can provide more detailed descriptions about what is missing.
