### ISSUE TITLE
[doc] Adding multi language support to documentation

### ISSUE THREAD

**Issue by shawnscoding** [axios/axios#3301]
#### Is your feature request related to a problem? Please describe.
I think it's good to support multi-language to Axios site since Axios is used by a large number of people around the world.
I have seen my colleagues having a difficult time understanding Axios because the documentation is written in English which they are not fluent in. If you allow me, I'd like to contribute in terms of Korea translation. Please let me know what you think. :)

**Comment by chinesedfan** [comment]
Thanks for your interests. But now axios maintainers don't have enough time on translations. How about maintain your docs by yourself? Then we can guide users to there, like [my personal docs](https://github.com/chinesedfan/You-Dont-Know-Axios).

**Comment by jasonsaayman** [comment]
We would like to work on this, and there is actually a repo for doc's however this has not gotten much attention as most of the maintenance time goes to the main repo and releasing new versions, etc. If I do get some time I will possibly start up this repo and link it here.
