### ISSUE TITLE
 如何在vue3 中全局使用axios   How to use Axios globally in vue3

### ISSUE THREAD

**Issue by whispero** [axios/axios#3302]
#### Describe the issue
A clear and concise description of what the issue is.

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
axios is just a request client, which has nothing related to which framework you are using. So feel free to call axios as usual. If you met some problem, please open a new issue to describe it. Thanks.

**Comment by tornoda** [comment]
你在vue2中怎么要是，在vue3中就怎么用。
