### ISSUE TITLE
unable to ignore ssl issue on self-sign certificates

### ISSUE THREAD

**Issue by hsinhoyeh** [axios/axios#3304]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

I am trying to use Axios to send an https request to a server with a self-signed certificate. however, the latest release version 0.20.0(https://github.com/axios/axios/releases/tag/v0.20.0) NEVER worked for me, however,  0.19.0 (https://github.com/axios/axios/releases/tag/v0.19.0) works.

I digged a bit on the source code and think the follow code changes could be the root caused:
```
commit 1b07fb9365d38a1a8ce7427130bf9db8101daf09
Author: Joshua Melvin <joshua.melvin@outlook.com>
Date:   Fri Sep 13 08:35:59 2019 -0400

    Fixing issue 2195 - order of if/else blocks is causing unit tests mocking XHR. (#2201)

diff --git a/lib/defaults.js b/lib/defaults.js
index 7cb8a25..23e1cbd 100644
--- a/lib/defaults.js
+++ b/lib/defaults.js
@@ -15,13 +15,12 @@ function setContentTypeIfUnset(headers, value) {

 function getDefaultAdapter() {
   var adapter;
-  // Only Node.JS has a process variable that is of [[Class]] process
-  if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
-    // For node use HTTP adapter
-    adapter = require('./adapters/http');
-  } else if (typeof XMLHttpRequest !== 'undefined') {
+  if (typeof XMLHttpRequest !== 'undefined') {
     // For browsers use XHR adapter
     adapter = require('./adapters/xhr');
+  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
+    // For node use HTTP adapter
+    adapter = require('./adapters/http');
   }
   return adapter;
 }
```
because my Chrome always has  `XMLHttpRequest`, so the adapter is always `adapters/xhr` not `/adapters/http` as I expected to be. (let me know if my assumption is wrong)

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

This issue seems to be resolved dated back to https://github.com/axios/axios/issues/535, but now it is not working anymore on the latest release(https://github.com/axios/axios/releases/tag/v0.20.0). so I just borrow the code from the issue and add some error traces from my side.
```js
const instance = axios.create({
  httpsAgent: new https.Agent({  
    rejectUnauthorized: false
  })
});
instance.get('https://something.com/foo');

// At request level
const agent = new https.Agent({  
  rejectUnauthorized: false
});
axios.get('https://something.com/foo', { httpsAgent: agent });
```

with the error stack listed below:
```
   Error: Error: unable to verify the first certificate
        at Object.dispatchError (/.../node_modules/jsdom/lib/jsdom/living/xhr-utils.js:
54:19)
        at Request.<anonymous> (/.../node_modules/jsdom/lib/jsdom/living/xmlhttprequest
.js:675:20)
        at Request.emit (events.js:327:22)
        at Request.onRequestError (/.../node_modules/request/request.js:877:8)
        at ClientRequest.emit (events.js:315:20)
        at TLSSocket.socketErrorListener (_http_client.js:426:9)
        at TLSSocket.emit (events.js:315:20)
        at emitErrorNT (internal/streams/destroy.js:92:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
        at processTicksAndRejections (internal/process/task_queues.js:84:21) undefined
```

#### Expected behavior

it should work without any error raised.

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP] 0.20.0
 - Browser [e.g. Chrome, Safari] Chrome
 - Browser Version [e.g. 22] 85.0.4183.121
 - Node.js Version [e.g. 13.0.1] v12.18.1
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4] OSX 10.15.16
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0] No

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

related issues:
https://github.com/axios/axios/issues/3005
https://github.com/axios/axios/issues/2690
https://github.com/axios/axios/issues/535

**Comment by samaneh-kamalian** [comment]
I have same problem. any solution?

**Comment by samaneh-kamalian** [comment]
> I have same problem. any solution?

I need the solution. please help.
I add all  solutions that suggested before but it does not work!

```


 process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
    let https = require('https');
    const myagent = new https.Agent({  
      rejectUnauthorized: false
    });


    axios({
      method: 'post',
      url: serverAddress + '/activate/',
      headers: {
        Authorization: "token" + token,
      },
      data: {
        somedata: data
      },
      httpsAgent:myagent,
      NODE_TLS_REJECT_UNAUTHORIZED:'0',
      timeout: 120000
    })
```

**Comment by hsinhoyeh** [comment]
@samaneh-kamalian please make sure you have installed version 0.19(check yarn.lock or package-lock.yarm). This works for me very well.

**Comment by samaneh-kamalian** [comment]
> @samaneh-kamalian please make sure you have installed version 0.19(check yarn.lock or package-lock.yarm). This works for me very well.

I test with 0.19.0, 0.19.1, 0.19.2 . none of them answered correctly!:(((
this is my react-native info:

```
info Fetching system and libraries information...
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
    Memory: 169.68 MB / 7.63 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.12.0 => 4.12.0 
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by chinesedfan** [comment]
@hsinhoyeh How did you run your script, as a Node.js script or in the browser? or in environments like Electron?

I see you used `config.agent`, if it was,
- Node.js script, then please check the final config in axios http adapter. Was the agent set correctly?
- Electron, then maybe it's due to changes of the default adapter as you pointed out.

**Comment by hsinhoyeh** [comment]
@chinesedfan hi, the script is run by my chrome browser.
the agent is set correctly as 0.19.0 works for me very well without any modification.
can you check this commit id (1b07fb9365d38a1a8ce7427130bf9db8101daf09), why it changed the behavior but none of test cases are broken?

**Comment by chinesedfan** [comment]
It's strange. If your script is running in Chrome browser, how can `new https.Agent` be called?

About the commit, forgive that axios' test cases didn't covered everything. That's why some regressions occurred and we are preventing prs without tests now.

**Comment by hsinhoyeh** [comment]
so you are saying that on chrome browser, `adapter = require('./adapters/xhr');` should be used.
Would you mind providing an example on how to ignore SSL issue?

**Comment by hsinhoyeh** [comment]
@chinesedfan `new https.Agent` is called on v0.19 not v0.20...

**Comment by chinesedfan** [comment]
In the contrary, we hope users can provide a reproducible repository. I can only help you as far as I can. Lots of hidden informations are in your side and I can't ask for them one by one. Thanks for understanding.

There are no global variable called `http` in the browser environment. I mean, where it comes from. If you wrote `const http = require('http')`, then it will not work. Because `http` is a Node.js module, which can be used in browser environment. But you say 0.19 works well. I don't know what's the difference.

**Comment by namelessperson0** [comment]
`  rejectUnauthorized: false
` is not recommended

Instead use something like below 
```
var agent = new https.Agent({ 
  ca: fs.readFileSync('ca.pem') 
});

axios.get(url, { agent: agent });
```
Check https://github.com/axios/axios/issues/284 and https://stackoverflow.com/questions/51363855/how-to-configure-axios-to-use-ssl-certificate
