### ISSUE TITLE
https://github.com/axios/axios/issues/187 support port in axios

### ISSUE THREAD

**Issue by GopherJ** [axios/axios#3306]

**Comment by GopherJ** [comment]
https://github.com/axios/axios/issues/187 this shoudn't be closed

**Comment by jasonsaayman** [comment]
@GopherJ if you read about it in #187 it seems appropriate to have it closed.

**Comment by GopherJ** [comment]
@jasonsaayman I would say it cannot solve problems in SPA. Image a SPA which needs to fetch data from there endpoints:

- 192.168.0.128:9999
- 192.168.0.128:8888
- 192.168.0.128:7777

Because the IP address 192.168.0.128 can change, so we cannot specify `BASE_URL`. Then we want axios to support port option. 

Otherwise supporting port option, do you have another solution? I don't think there is...so it's incorrect to close #187

**Comment by jasonsaayman** [comment]
@GopherJ So you would like us to make a change to support ports for what seems to be some local endpoints? This is not really a use case in production surely your endpoints would rather follow some type of schema or use subdomains rather than exposing direct ports?

**Comment by GopherJ** [comment]
@jasonsaayman we are doing local installation, in local environments there are cases that we will not use https.

**Comment by GopherJ** [comment]
@jasonsaayman Do you have a solution for the scenario that I have mentioned? If not please let's open it...

**Comment by jasonsaayman** [comment]
@GopherJ I still don't really understand the issue, Axios does give you the ability to use HTTP so I don't understand the HTTPS issue? As for the port it can be done for example like this:

```
axios.get(`${proccess.env.HOST}:${PORT}/api/categories`)
``

I still think that this use case in my opinion is still to fringe and you can solve it by not using `BASE_URL` and rather doing the above example. Also, I once again would strongly suggest if you are running multiple endpoints on multiple ports you look at using a gateway in front of this to simplify routing.
