### ISSUE TITLE
I'm with this error convert circular structure. Can someone help me?

### ISSUE THREAD

**Issue by dcyrillo** [axios/axios#3308]
(node:36) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
   |     --> starting at object with constructor 'ClientRequest'
   |     |     property 'socket' -> object with constructor 'TLSSocket'
   |     --- property '_httpMessage' closes the circle
   |     at JSON.stringify (<anonymous>)
   |     at stringify (/home/node/app/node_modules/express/lib/response.js:1123:12)
   |     at ServerResponse.json (/home/node/app/node_modules/express/lib/response.js:260:14)
   |     at ExpressAdapter.reply (/home/node/app/node_modules/@nestjs/platform-express/adapters/express-adapter.js:24:57)
   |     at ExceptionsHandler.catch (/home/node/app/node_modules/@nestjs/core/exceptions/base-exception-filter.js:26:24)
   |     at ExceptionsHandler.next (/home/node/app/node_modules/@nestjs/core/exceptions/exceptions-handler.js:16:20)
   |     at /home/node/app/node_modules/@nestjs/core/router/router-proxy.js:13:35
   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
   | (Use `node --trace-warnings ...` to show where the warning was created)
   | (node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
 | (node:36) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by shuhikari** [comment]
@dcyrillo did you manage to solve it?
