### ISSUE TITLE
Axios is adding an http: in front of the URL if it doesn't include a protocol.  Is there a way around this?

### ISSUE THREAD

**Issue by 333one** [axios/axios#3311]
#### Describe the issue
It appears that Axios is adding an http: in front of the URL if it doesn't include a protocol.  Is there a way around this?  I'm testing for active URLs and would like to test the client input without altering it with a protocol.

In the error response I see this:
```
config.url: 'www.cat.com'
request._currentUrl: 'http:www.cat.com'
```

#### Example Code
```
    let url = 'www.cat.com';

    await axios.get(url)
        .then(function(response) {
            // process the success
        })
        .catch(function(error) {
            // process the error
        });
```

#### Environment
 - Axios Version [0.20.0]
 - Node.js Version [v12.18.2]

**Comment by chinesedfan** [comment]
Sorry, it is impossible as far as I know. Because axios uses Node.js `http.request` internally. If you find out a way to solve it, thanks for sharing.
