### ISSUE TITLE
 If paramsSerializer is not specified, brackets are not encoded

### ISSUE THREAD

**Issue by HealGaren** [axios/axios#3316]
#### Describe the issue
The default behavior of paramsSerializer does not encode square brackets.
There cannot be brackets in place of the url parameter, and it should be encoded.

Looking at [this pull request](https://github.com/axios/axios/pull/49) or [this comment](https://github.com/axios/axios/issues/1111#issuecomment-334707256), This behavior seems to be intentional.

But according to the RFC 3986 cited there:
>  A host identified by an Internet Protocol literal address, version 6
[RFC3513] or later, is distinguished by enclosing the IP literal
within square brackets ("[" and "]").  This is the only place where
square bracket characters are allowed in the URI syntax.

(page 19)

URL parameter is not in this case. So I think brackets should be encoded in default behavior.

#### Example Code

```js
axios.get('/test', {params: {a: '[]'}})
```

#### Expected behavior, if applicable
expected : request URL is `https://domain.com/test?a=%5B%5D`
actual: request URL is `https://domain.com/test?a=[]`

#### Environment
 - Axios Version: 0.20.0
 - Browser: Chrome
 - Browser Version: 85.0.4183.121

#### Additional context/Screenshots
-

**Comment by rkovalyov** [comment]
This happened due to library returns brackets after encoding, I dont know why 
https://github.com/axios/axios/blob/4b3947aa59aaa3c0a6187ef20d1b9dddb9bbf066/lib/helpers/buildURL.js#L11

**Comment by HealGaren** [comment]
![image](https://user-images.githubusercontent.com/13010755/97952549-2628fe80-1de1-11eb-8cfb-2a056e9cb5de.png)

Starting with Tomcat 8, if the URL contains brackets, a request error is responded.

The specs of a particular program do not dictate whether this should be fixed, but I think it can be a small reason.

**Comment by stevebor1** [comment]
> ![image](https://user-images.githubusercontent.com/13010755/97952549-2628fe80-1de1-11eb-8cfb-2a056e9cb5de.png)
> 
> Starting with Tomcat 8, if the URL contains brackets, a request error is responded.
> 
> The specs of a particular program do not dictate whether this should be fixed, but I think it can be a small reason.

Running Tomcat 8.0.44 was fine, but after upgrading to 8.0.59, Tomcat now enforces those to be encoded.
https://tomcat.apache.org/tomcat-8.5-doc/config/http.html
Setting relaxedQueryChars and specifying the characters to ignore works, but it would be nice if Axios can update the parameter encoding logic and encode the characters if not an array.

**Comment by stevebor1** [comment]
Regardless of server, the brackets should still be encoded by axios.
What is the status of this?

**Comment by HealGaren** [comment]
@jasonsaayman 

https://github.com/axios/axios/pull/3477
This is a PR for the v1.0.0-beta version of this encoding issue.

No feedback since I created the PR, so I'm commenting the link.

**Comment by payros** [comment]
For anyone waiting for this fix to be incorporated into the next version of axios, here is a quick and dirty workaround using paramsSerializer and query-string (qs will also work) to strictly encode the URL:

```
import axios from 'axios'
import queryString from 'query-string'

// Add a request interceptor
axios.interceptors.request.use(function (config) {
    // Serialize the parameteters
    config.paramsSerializer = params => queryString.stringify(params, { arrayFormat: 'brackets' })
    return config
}
```

**Comment by aLx450** [comment]
Would greatly appreciate a merge of this PR..... :)

**Comment by jasonsaayman** [comment]
Please try with the latest version, should this still be the case let me know 😄

**Comment by MelMelsy** [comment]
Hi, tried with the latest version [v0.27.2] however, the square brackets are still not encoded.

**Comment by jasonsaayman** [comment]
Please try with the pre-release v1

**Comment by marc-weber1** [comment]
Pre-release v1 also does not seem to work. This issue also makes it impossible to interact with the [https://docs.patreon.com/#apiv2-oauth](patreon API) since manual URL encoding with %5B and %5D doesn't work, since % gets encoded.

**Comment by andrijaantunovic** [comment]
> For anyone waiting for this fix to be incorporated into the next version of axios, here is a quick and dirty workaround using paramsSerializer and query-string (qs will also work) to strictly encode the URL:
> 
> ```
> import axios from 'axios'
> import queryString from 'query-string'
> 
> // Add a request interceptor
> axios.interceptors.request.use(function (config) {
>     // Serialize the parameteters
>     config.paramsSerializer = params => queryString.stringify(params, { arrayFormat: 'brackets' })
>     return config
> }
> ```

This is (no longer?) correct as paramSerializer is now an object with `encode` and `serialize` properties. Trying to override `paramsSerializer` directly with a callback will give you a type error.

A helpful example was [provided here](
https://github.com/axios/axios/issues/5058#issuecomment-1379970592).

However I didn't have luck with `queryString` lib so finally I've defined the serializer with `qs` directly when creating the axios instance, like this:

```ts
import axios from 'axios';
import qs from 'qs';

const api = axios.create({
  baseURL: 'http://localhost:3000',
  paramsSerializer: {
    serialize: (params) => {
      return qs.stringify(params, { arrayFormat: 'brackets' });
    },
  },
});
```

Maybe there is a cleaner way, but this seems to work fine for me.

**Comment by andrijaantunovic** [comment]
@jasonsaayman Seeing as this issue has been closed for a while, I'm not sure what the intended default behavior is.

But just to confirm, axios itself still does **not** encode brackets as of v1.3.3.

**Comment by HealGaren** [comment]
@andrijaantunovic 
A branch named `1.0.0-beta` existed and the PR was merged into that branch.
but, In the process of releasing the 1.0.0 stable version, it seems that all the work in the `1.0.0-beta` branch was deleted.
I will send a new PR when the issue is reopened.

@jasonsaayman This issue is not resolved in the latest released version, so it needs to be reopened.

**Comment by ferhansolo** [comment]
Here to report the same issue with version 1.3.4

**Comment by jasonsaayman** [comment]
Reopened

**Comment by rhkd6351** [comment]
@HealGaren 
I would like to know why https://github.com/axisios/axios/pull/5715 was not merged.
still not working

**Comment by chigia001** [comment]
This change to the default paramsSerializer can be consider breaking change for multiple people.

**Comment by shikeiyan** [comment]
This issue still not resolved using  v1.6.2.

**Comment by adrlen** [comment]
Hello @jasonsaayman, is there any news on this issue ? Is it planned to be merge soon ?

Thanks in advance

**Comment by jasonsaayman** [comment]
closing and will address on the PR
