### ISSUE TITLE
Not sure how best way to set parsing behavior: 3319

### ISSUE THREAD

**Issue by alexanderankin** [axios/axios#3320]
#### Describe the issue
I would like clarification on an issue.

#### Example Code
Code snippet to illustrate your question

```js
var axios = require('axios');
var myQuestion = await axios.get('https://github.com/axios/axios/issues/3319');
```

#### Expected behavior, if applicable
I would like to be able to customize some behavior and not sure how to do it.

#### Environment
 - Axios Version 0.18.0
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 87
 - Node.js Version 14.0.1
 - OS: iOS 12.1.0
 - Additional Library Versions React 16.7

#### Additional context/Screenshots
I think an 'accept' configuration optional is reasonable but perhaps there is a more sensible way in axios, which i could not get form the docs.

**Comment by alexanderankin** [comment]
okay now that i snuck this one past the bot, heres my real question https://github.com/axios/axios/issues/3319.

thanks in advance for your time!

**Comment by chinesedfan** [comment]
axios has a default `transformResponse`, which will parse the response to JSON. If you don't need it, see [my docs](https://github.com/chinesedfan/You-Dont-Know-Axios#make-things-precisely-transformrequest-and-transformresponse).
