### ISSUE TITLE
What is File Size Measurement in the total of progressEvent

### ISSUE THREAD

**Issue by shellac85** [axios/axios#3322]
#### Describe the issue
Hi I am just wondering what is the file size measurement in total from ProgressEvent. Is it bytes? Or KBs? I need to do a conversion. Tks

#### Example Code
const { loaded, total } = progressEvent;

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
In bytes. See more in https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent.
