### ISSUE TITLE
axios upload form-data error

### ISSUE THREAD

**Issue by rxliuli** [axios/axios#3325]
#### Describe the issue

The code below uses node-fetch and axios to upload pictures, I don’t understand why axios fails

Specific information reference:

- https://stackoverflow.com/questions/64129884/how-to-convert-the-following-curl-call-to-nodejs-axios
- https://discourse.joplinapp.org/t/how-to-use-joplin-api-resources-id-file/11333/16

#### Example Code

```js
  describe('diff fetch and axios', () => {
    function getFormData() {
      const fd = new FormData()
      const path = resolve(__dirname, '../resource/resourcesByFileId.png')
      const title = 'image title'
      fd.append('props', JSON.stringify({ title: title }))
      fd.append('data', createReadStream(path))
      return fd
    }

    it('test create by fetch', async () => {
      const fd = getFormData()
      const resp = await fetch(ApiUtil.baseUrl('/resources'), {
        method: 'post',
        body: fd,
      })
      const json = await resp.json()
      console.log('json: ', json)
    })
    it.skip('test create by axios', async () => {
      const fd = getFormData()
      const resp = await axios.post(ApiUtil.baseUrl('/resources'), fd, {
        headers: fd.getHeaders(),
      })
      console.log('resp.data: ', resp.data)
    })
  })
```

#### Environment
 - Axios Version [e.g. 0.20.0]
 - Adapter [e.g. XHR/HTTP]
 - Node.js Version [e.g. 12.0.1]
 - OS: [e.g. Windows 10]

#### Additional context/Screenshots

![image](https://user-images.githubusercontent.com/24560368/95572515-a5364b80-0a5c-11eb-9490-7dedac68c125.png)

**Comment by TheNorthMemory** [comment]
Just need a little bit modification shall let your codes works fine with `Axios`.

```diff
-       const resp = await axios.post(ApiUtil.baseUrl('/resources'), fd, {
+       const resp = await axios.post(ApiUtil.baseUrl('/resources'), fd.getBuffer(), {
```

The reason is that, `utils.isFormData` just working on the `Browser`. On node environments, there weren't built-in `FormData` function/class. The above modification shall be passed by `utils.isBuffer` and then works expectation.

**Comment by rxliuli** [comment]
> Just need a little bit modification shall let your codes works fine with `Axios`.
> 
> ```diff
> -       const resp = await axios.post(ApiUtil.baseUrl('/resources'), fd, {
> +       const resp = await axios.post(ApiUtil.baseUrl('/resources'), fd.getBuffer(), {
> ```
> 
> The reason is that, `utils.isFormData` just working on the `Browser`. On node environment, there weren't built-in `FormData` function/class. The above modification shall be passed by `utils.isBuffer` and then works expectation.
> 
> Additionally, the `node-fetch` did a `is.isFormData` function for checking the `FormData` implementation. That's greater than `utils.isFormData` does. In my opinion, the same code should be here soon later.

An error occurred

```js
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of DelayedStream
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of DelayedStream
    at Function.from (buffer.js:331:9)
    at FormData.Object.<anonymous>.FormData.getBuffer (C:\Users\rxliuli\Text\web\joplin-api\node_modules\form-data\lib\form_data.js:328:57)
    at C:\Users\rxliuli\Text\web\joplin-api\test\api\ResourceApi.test.ts:53:12
    at step (C:\Users\rxliuli\Text\web\joplin-api\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\Users\rxliuli\Text\web\joplin-api\node_modules\tslib\tslib.js:117:57)
    at C:\Users\rxliuli\Text\web\joplin-api\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\rxliuli\Text\web\joplin-api\node_modules\tslib\tslib.js:106:16)
    at Object.<anonymous> (C:\Users\rxliuli\Text\web\joplin-api\test\api\ResourceApi.test.ts:49:32)
    at Object.asyncJestTest (C:\Users\rxliuli\Text\web\joplin-api\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
```

**Comment by TheNorthMemory** [comment]
Yep, try to use `readFileSync` instead of `createReadStream`

**Comment by rxliuli** [comment]
> Yep, try to use `readFileSync` instead of `createReadStream`

There is no problem with `fd.getBuffer`, but the request still fails, maybe @laurent22 is needed here. . .

![image](https://user-images.githubusercontent.com/24560368/95653255-ffe9a900-0b29-11eb-87b0-740d3c544229.png)

**Comment by TheNorthMemory** [comment]
try to move `getFormData` inside of each of `it()`statements.

**Comment by rxliuli** [comment]
> try to move `getFormData` inside of each of `it()`statements.

Modified to the following, but still the same error

```ts
    it('test create by axios', async () => {
      const fd = new FormData()
      const title = 'image title'
      fd.append('props', JSON.stringify({ title: title }))
      fd.append('data', readFileSync(path))
      const resp = await axios.post(
        ApiUtil.baseUrl('/resources'),
        fd.getBuffer(),
        {
          headers: fd.getHeaders(),
        },
      )
      console.log('resp.data: ', resp.data)
    })
```

**Comment by TheNorthMemory** [comment]
from your screenshot, the problem should comes from your `test` libraries. It's under `XMLHttpReuest` and not the axios's `adapters/http`. Relationship ticket should be https://github.com/sinonjs/sinon/issues/885 . A hardcode solution on here i remembered.  You may need doing some research for this solution.

**Comment by TheNorthMemory** [comment]
@rxliuli take a look https://github.com/axios/axios/issues/2654#issuecomment-591373706
> The alternative is setting the axios default adapter as @textbook said:
>> axios.defaults.adapter = require('axios/lib/adapters/http');

**Comment by rxliuli** [comment]
> @rxliuli take a look [#2654 (comment)](https://github.com/axios/axios/issues/2654#issuecomment-591373706)
> 
> > The alternative is setting the axios default adapter as @textbook said:
> > > axios.defaults.adapter = require('axios/lib/adapters/http');

Tested, still the same problem. . . Suddenly found that axios has not arrived 1.*

```ts
    it('test create by axios', async () => {
      axios.defaults.adapter = require('axios/lib/adapters/http')
      const fd = new FormData()
      const title = 'image title'
      fd.append('props', JSON.stringify({ title: title }))
      fd.append('data', readFileSync(path))
      const resp = await axios.post(
        ApiUtil.baseUrl('/resources'),
        fd.getBuffer(),
        {
          headers: fd.getHeaders(),
        },
      )
      console.log('resp.data: ', resp.data)
    })

```

**Comment by rxliuli** [comment]
Is there any progress on this issue? I don't want to use fetch to replace axios

**Comment by lanbaba** [comment]
Maybye, you can try install form-data package on nodejs.url:https://www.npmjs.com/package/form-data

**Comment by schellenbergk** [comment]
`fd.getBuffer()` should be put in `axios/README.md` as an example, It took me a while to figure it out and find this post.  Thanks.

**Comment by nickjuntilla** [comment]
For me:

I had a similar problem. It turns out I needed to turn the createReadStream into a buffer with 

const readFile = await getRawBody(fs.createReadStream(fileLocation));

and then do get buffer on that:

method: 'post',
        url: url,
        maxBodyLength: Infinity,
        headers: {
          ...data.getHeaders(),
        },
        data: data.getBuffer(),

**Comment by TheNorthMemory** [comment]
Hi there, it was another standlone `axios` compatible `Multipart` buffer/stream composer class, fullfilled the [MDN FormData specificaitons](https://developer.mozilla.org/en-US/docs/Web/API/FormData), related API can be found [here](https://github.com/TheNorthMemory/wechatpay-axios-plugin/wiki/multipart.js) and some user cases can be found [here](https://github.com/TheNorthMemory/wechatpay-axios-plugin/pull/26). Hopes it may help someone.
