### ISSUE TITLE
axios request interceptor api call causing infinite loop

### ISSUE THREAD

**Issue by codeamo** [axios/axios#3327]
### Describe the issue
We are implementing a token-based authentication and when a user signs in we generate access and refresh tokens then save that with the timestamp on the device so we can later check if the access token is expired or not. Currently, we are using axios request interceptor before every request and checking if the token is still valid or not but when the access token expires and we are making a request to refresh the token the app goes on an infinite loop and none of the requests go through (both the original and refresh token API requests). a simple implementation of the code can be found below:

#### Example Code
```
const instance = axios.create({
  baseURL: 'http://localhost:8080',
});

instance.interceptors.request.use(async (config) => {
  const timestamp = 1602155221309;
  const diffMinutes = Math.floor(Math.abs(Date.now() - timestamp) / 60000);

  if (diffMinutes > 30) {
    const res = await instance.post('/token/refresh');
    const response = res.status <= 404 ? res.json() : Promise.reject(res);
    // change the auth header here after a successful request
  }
  return config;
});
```

#### Expected behavior, if applicable
Expected behavior was to first pause all ongoing requests if the token is expired and make refresh token API to get return a fresh token then resume all the requests that were paused.

#### Environment
 - Axios Version [^0.20.0]
 - Adapter [HTTP]
 - Node.js Version [e.g. 14.6.0]
 - OS: [e.g. iOS 13.6, OSX 10.15.7]
 - Additional Library Versions [React Native 0.62.2]

**Comment by meetmangukiya** [comment]
I'd like to bump this one, similar use case
