### ISSUE TITLE
Tus upload to vimeo upload link fails

### ISSUE THREAD

**Issue by thealpha93** [axios/axios#3328]
#### Describe the issue
Video upload to vimeo using the `tus` upload from reactjs application. I have converted the video file into an `Blob` and tried to upload to the upload link provided by vimeo. 

When I use `fetch` to upload the video, it seems to be working. But with axios, it's not working. I believe it has something to do with the way blob is passed in the body.

#### Example Code
Code snippet to illustrate your question

```js
// Axios Code
reader.onload = async () => {
        const videoBlob = new Blob([new Uint8Array(reader.result)], { type: video.type });

        try {
          await uploadToVimeoLink(response.url, videoBlob)
        } catch (error) {
          console.log(error)
        }
      }
  
      reader.readAsArrayBuffer(video)

 const uploadToVimeoLink = async (uploadLink, fileBlob) => {
  try {
    const config = {
      headers: {
        "Tus-Resumable": "1.0.0",
        "Upload-Offset": "0",
        "Content-Type": "application/offset+octet-stream",
        Accept: "application/vnd.vimeo.*+json;version=3.4",
        Authorization: ''
      },
    };

    const response = await axios.patch(uploadLink, fileBlob, config);
    return response;
  } catch (error) {
    console.log(error);
  }
};
```
```
// Using fetch
fetch(uploadLink, {
    method: "PATCH",
    headers: {
      "Tus-Resumable": "1.0.0",
      "Upload-Offset": "0",
      "Content-Type": "application/offset+octet-stream",
      Accept: "application/vnd.vimeo.*+json;version=3.4",
    },
    body: fileBlob,
  })
    .then((data) => {
      console.log(data);
    })
    .catch((err) => console.log(err));
```
#### Expected behavior, if applicable
I expect to get a 204 reponse from the vimeo server. It's working when I use `fetch`. But when I use axios it gives status 400.

#### Environment
 - Axios Version [0.20.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Brave, Chromei]
 - Browser Version [Version 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)]
 - Node.js Version [14]
 - OS: [Ubuntu 20]
 - Additional Library Versions [16.13.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/42433480/95662338-e6f5ed80-0b53-11eb-9aaf-3c0909b933e5.png)

**Comment by chinesedfan** [comment]
If v0.19.2 works well, it should be caused by #1773. (cc @jasonsaayman)
