### ISSUE TITLE
Breaking change in v0.20.0 

### ISSUE THREAD

**Issue by ionTea** [axios/axios#3335]
#### Describe the bug
A breaking change was introduced here:
https://github.com/axios/axios/pull/2844/files?file-filters%5B%5D=.js&hide-deleted-files=true#diff-597f69416721110963cbbdf72c6d4e6e30d77da5073041b4b10a702c0a7186f0R76

Previously a `GET` request would be able to include `data`, since before the change above `util.merge` would keep the data property passed in `config`. Now the `mergeConfig` function will ignore the data property in `config`, causing the request to be made without data.

Whether or not a `GET` request should be able to send a body is debatable I guess, but this change should probably be documented somewhere.

#### To Reproduce
```js
var utils = require("./utils");
var mergeConfig = require("./core/mergeConfig");

console.log("--- mergeConfig --- ");
console.log(
  mergeConfig(
    { data: { hello: "world" } },
    {
      method: "get",
      url: "https://test.com",
    }
  )
);

console.log("--- utils.merge ---");
console.log(
  utils.merge(
    { data: { hello: "world" } },
    {
      method: "get",
      url: "https://test.com",
    }
  )
);
```

Result:
```
--- mergeConfig --- 
{ url: 'https://test.com', method: 'get' }
--- utils.merge ---
{ data: { hello: 'world' },
  method: 'get',
  url: 'https://test.com' }
```

#### Environment
 - Axios Version [e.g. 0.18.0] 0.20.0
 - Adapter [e.g. XHR/HTTP] HTTP
 - Browser [e.g. Chrome, Safari] Node
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1] v10.14.1
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4] OSX 
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by thib3113** [comment]
I think I maybe get the same bug ... I'm using data in `GET` `body`, and reverting to 0.19.2 seems to resolve my problem ...

`Whether or not a GET request should be able to send a body is debatable I guess, but this change should probably be documented somewhere.`
For me, the HTTP 1/1 allow to use `GET` with body, so an http request library need to implement it .

**Comment by nick-w-nick** [comment]
Just as a bump, this issue is impacting me as well. I just noticed it today after upgrading from 0.19.2 to 0.20.0.

I have several systems that interact with APIs that require a request body with certain GET requests, which are now not working after the upgrade since the `data` property in the config object is being ignored.

**Behavior on 0.19.2**
```
const config = {
    data: {
        prop1: 'prop1value',
        prop2: 'prop2value'
    }
}

Axios.get('https://website.com/api/endpoint', config);
```
**Request being sent:**
GET https://website.com/api/endpoint
Request Body:
```
{
    prop1: 'prop1value',
    prop2: 'prop2value'
}
```

**Behavior on 0.20.0**
```
const config = {
    data: {
        prop1: 'prop1value',
        prop2: 'prop2value'
    }
}

Axios.get('https://website.com/api/endpoint', config);
```
**Request being sent:**
GET https://website.com/api/endpoint
Request Body: (blank)

**Comment by chinesedfan** [comment]
Does it share the same reason with the pinned #3220?

**Comment by ionTea** [comment]
I'd assume so, since both `DELETE` and `GET`use the same `mergeConfig` setup:
https://github.com/axios/axios/pull/2844/files?file-filters%5B%5D=.js&hide-deleted-files=true#diff-597f69416721110963cbbdf72c6d4e6e30d77da5073041b4b10a702c0a7186f0R73

**Comment by jasonsaayman** [comment]
Yeah #3220 should fix that up.

**Comment by ionTea** [comment]
I think so too, I'll close this 👍
