### ISSUE TITLE
we like to generate har file using axios, please suggest if such functionality is available with axios or how it can be achieved

### ISSUE THREAD

**Issue by hemant-karwade** [axios/axios#3339]
we like to generate har file using axios, please suggest if such functionality is available with axios or how it can be achieved

**Comment by chinesedfan** [comment]
axios wouldn't provide this feature directly, because it is just a client. But you can write or find a wrapper to save the response as har file.

**Comment by arthemium** [comment]
@hemant-karwade https://www.npmjs.com/package/axios-har-tracker
