### ISSUE TITLE
Promise sometimes doesn't resolve or throw an error

### ISSUE THREAD

**Issue by robinp7720** [axios/axios#3343]
#### Describe the bug
I'm getting a bizarre problem where the promise returned by axios never resolves or returns an error. I don't believe this problem is exclusive to axios either as I have used other http clients and have experienced the same problems.

#### To Reproduce
The following script reproduces the issue I'm having. I've let the script run for about 10 mins and some promises were never resolved.

```js
let axios = require('axios');

let test = function (opt, i) {
    return new Promise(function(resolve, reject) {
        let timedout = false;
        let interval = setInterval(() => {
            timedout = true;

            console.log(`${i} hasn't resolved yet`)
        }, 60000);


        axios(opt).then(response => {
            if (timedout) console.log(`${i} resolved!`)

            clearInterval(interval);

            resolve(response);
        }).catch(err =>{
            if (timedout) console.log(`${i} returned an error!`)

            clearInterval(interval);
            reject(err);
        });
    });
}

for (let i = 0; i < 100; i++) {
    test({
        method: 'get',
        url: `https://artworks.thetvdb.com/banners/episodes/83237/947171_t.jpg`
    }, i).then(res => {

    }).catch(err => {
        console.log(err);
    });
}

```

#### Expected behavior
The promises to be resolved or an error to be thrown with a timeout

#### Environment
 - Axios Version 0.20.0
 - Adapter HTTP
 - Browser NodeJS
 - Node.js Version 14.14.0
 - OS: Archlinux

#### Additional context/Screenshots
I'm fairly sure this isn't directly an issue with axios as I get the same issue with node-fetch, but I've been struggling with the issue for a while and would appreciate some insight.

**Comment by chinesedfan** [comment]
Don't know what strange things happened in the server. But if you set `config.timeout` of axios, it will trigger the timeout.

```
test({
  url: `xx`,
  timeout: 1000
})
```

If requesting with the native `http.request`, will see the same blocking. Closing due to not an issue of axios.

```
const https = require('https');

const req = https.request({
  path: '/banners/episodes/83237/947171_t.jpg',
  method: 'get',
  headers: {
    Accept: 'application/json, text/plain, */*'
  },
  hostname: 'artworks.thetvdb.com',
}, () => {
  console.log('never call me')
})
req.end()
```

**Comment by robinp7720** [comment]
ok, I have personally tried it with the native http library and I'm not receiving the same problem. I'm using the following code to test it:

```javascript
const https = require('https');

let totalCompleted = 0;

let test = (i) => {
    let timedOut = false;

    setTimeout(() => {
        timedOut = true;
    }, 10000)

    const req = https.request({
        path: '/banners/episodes/83237/947171_t.jpg',
        method: 'get',
        headers: {
            Accept: 'application/json, text/plain, */*'
        },
        hostname: 'artworks.thetvdb.com',
    }, () => {
        if (timedOut) {
            return console.log(i + 'never call me')
        }
        totalCompleted += 1;
        console.log('Total completed:', totalCompleted);
    })
    req.end()
}


for (let i = 0; i < 500; i++) {
    test(i);
}

```

and all 500 requests always return their callback. However, when using promises the problem occurs again: ```javascript
const axios = require('axios');

let totalCompleted = 0;

let test = function (opt, i) {
    return new Promise(function(resolve, reject) {
        const req = https.request({
            path: '/banners/episodes/83237/947171_t.jpg',
            method: 'get',
            hostname: 'artworks.thetvdb.com',
        }, resolve)
        req.end()
    });
}

for (let i = 0; i < 100; i++) {
    test(i).then(res => {
        totalCompleted += 1;
        console.log('Total completed:', totalCompleted);
    }).catch(err => {
        console.log('This shouldn\'t ever be called');
    });
}
```
So it seams it's indeed not a problem with axios, but also not a problem with the native http library. I'll file a bug report with nodejs as it seems something is going wrong with the promises

**Comment by robinp7720** [comment]
ok, I have personally tried it with the native http library and I'm not receiving the same problem. I'm using the following code to test it:

```javascript
const https = require('https');

let totalCompleted = 0;

let test = (i) => {
    let timedOut = false;

    setTimeout(() => {
        timedOut = true;
    }, 10000)

    const req = https.request({
        path: '/banners/episodes/83237/947171_t.jpg',
        method: 'get',
        headers: {
            Accept: 'application/json, text/plain, */*'
        },
        hostname: 'artworks.thetvdb.com',
    }, () => {
        if (timedOut) {
            return console.log(i + 'never call me')
        }
        totalCompleted += 1;
        console.log('Total completed:', totalCompleted);
    })
    req.end()
}


for (let i = 0; i < 500; i++) {
    test(i);
}

```

and all 500 requests always return their callback. However, when using promises the problem occurs again: 

```javascript
const axios = require('axios');

let totalCompleted = 0;

let test = function (i) {
    return new Promise(function(resolve, reject) {
        const req = https.request({
            path: '/banners/episodes/83237/947171_t.jpg',
            method: 'get',
            hostname: 'artworks.thetvdb.com',
        }, resolve)
        req.end()
    });
}

for (let i = 0; i < 100; i++) {
    test(i).then(res => {
        totalCompleted += 1;
        console.log('Total completed:', totalCompleted);
    }).catch(err => {
        console.log('This shouldn\'t ever be called');
    });
}
```

So it seams it's indeed not a problem with axios, but also not a problem with the native http library. I'll file a bug report with nodejs as it seems something is going wrong with the promises

**Comment by robinp7720** [comment]
I have explored this a bit more, and using the native https module, I don't receive the same problems:
```javascript
const https = require('https');

let totalCompleted = 0;

let test = function (i) {
    return new Promise(function(resolve, reject) {
        const req = https.request({
            path: '/banners/episodes/83237/947171_t.jpg',
            method: 'get',
            hostname: 'artworks.thetvdb.com',
        }, resolve)
        req.end()
    });
}

for (let i = 0; i < 100; i++) {
    test(i).then(res => {
        totalCompleted += 1;
        console.log('Total completed:', totalCompleted);
    }).catch(err => {
        console.log('This shouldn\'t ever be called');
    });
}
```

all 100 promises always get returned.

**Comment by chinesedfan** [comment]
@jasonsaayman Can you test it? I failed to run the above test, even though the max i = 1.

**Comment by robinp7720** [comment]
My apologies, while the test above works for me, it returns the promise irrelevant of if data was received or not. When actually waiting for the socket to close before resolving the callback, I see the same problem as I see when using axios.

```javascript
const https = require('https');

let totalCompleted = 0;

let test = function (i) {
    return new Promise(function(resolve, reject) {
        const req = https.request({
            path: '/banners/episodes/83237/947171_t.jpg',
            method: 'get',
            hostname: 'artworks.thetvdb.com',
        }, (res) => {
            let chunks = "";

            res.on('data', (d) => {
                chunks += d;
            });

            res.on('end', () => {
                resolve()
            });
        })
        req.end()
    });
}

for (let i = 0; i < 100; i++) {
    test(i).then(res => {
        totalCompleted += 1;
        console.log('Total completed:', totalCompleted);
    }).catch(err => {
        console.log('This shouldn\'t ever be called');
    });
}
```

Many thanks for the help!
