### ISSUE TITLE
Uncaught TypeError: Cannot set property 'axios' of undefined

### ISSUE THREAD

**Issue by MarlonDML** [axios/axios#3348]
#### Describe the bug
I ran into this problem when I was learning to use Vue and axios.

#### To Reproduce
This part of the code was copied from axios' [official website](http://axios-js.com/zh-cn/docs/vue-axios.html).
```js
import axios from "axios"
import VueAxios from "vue-axios";

Vue.use(VueAxios,axios)
```
The following code was mine
```js
<script>
export default {
  props: ['id'],
  name: "UserProfile",
  beforeRouteEnter: (to, from, next) => {

    next(vm => vm.getData())
  },
  beforeRouteLeave: (to, from, next) => {
    next()
  },
  methods: {
    getData: function () {
      this.axios.get("../../static/mock/data.json").then((resp) => console.log(resp.data))
    }
  }
}
</script>
```

#### Expected behavior
I expect to print data on the console.But an error is shown.I don't know how to solve the problem and no other solutions have been found.
```bash
  Uncaught TypeError: Cannot set property 'axios' of undefined          vue-axios.min.js?45ff:1 
    at o (vue-axios.min.js?45ff:1)
    at Function.Vue.use (vue.esm.js?efeb:5118)
    at eval (main.js?1c90:11)
    at Object../src/main.js (app.js:2536)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.0 (app.js:2593)
    at __webpack_require__ (app.js:679)
    at app.js:725
    at app.js:728

o                                  @vue-axios.min.js?45ff:1
Vue.use                            @vue.esm.js?efeb:5118
eval                               @main.js?1c90:11
./src/main.js                      @app.js:2536
__webpack_require__                @app.js:679
fn                                 @app.js:89
0                                  @app.js:2593
__webpack_require__                @app.js:679
(anonymous)                        @app.js:725
(anonymous)                        @app.js:728

```

#### Environment
 - Axios Version [0.20.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [86.0.4240.75   64]
 - Node.js Version [12.19.0]
 - OS: [win10  1909  18363.1139 ]
 - Additional Library Versions [Vue:2.5.2  vue-axios:3.0.1, webpack:3.12.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by MarlonDML** [comment]
I found a [temporary solution](https://my.oschina.net/u/4313437/blog/4668946).
```js
import axios from 'axios';
Vue.prototype.$axios = axios;
```
This works for my code.

**Comment by JerryYuanJ** [comment]
It seems the bug of `vue-axios` lib instead of `axios` itself, and the link you provide isn't the  axios' official.

**Comment by MarlonDML** [comment]
> 看来是`vue-axios`lib而不是`axios`本身的bug，您提供的链接不是axios的官方。

emmm,you're right .I should submit issue to vue-axios.
