### ISSUE TITLE
How to set referrer policy when performing a request with Axios?

### ISSUE THREAD

**Issue by belalessandro** [axios/axios#3351]
#### Describe the issue
When performing a request with Axios, is there a referrerPolicy option to set general rules for Referer header?

#### Example Code
For example, Fetch API already [supports it](https://javascript.info/fetch-api#referrer-referrerpolicy).

```js
fetch(url, {referrerPolicy: 'no-referrer-when-downgrade'});
```

This option governs [how](https://web.dev/referrer-best-practices/#what-policies-are-available-and-how-do-they-differ) fetch sets HTTP Referer header.

#### Expected behavior, if applicable
The expected behaviour is that the Referer header is automatically set according to the specified policy.

#### Environment
 - Axios Version 0.20
 - Chrome 85

#### Additional context/Screenshots
The referrer policy is a new W3C specification which allows the page to provide the browser with a policy that lets the page have more control over how the Referer header is set. 
![referrer-devtools](https://user-images.githubusercontent.com/17120689/96598459-2dcfaa00-12ef-11eb-9b51-43c78fc1430f.jpg)

**Comment by chinesedfan** [comment]
axios uses different underlayer APIs with fetch, which is xhr in browsers. If want to use this feature directly, you need a fetch adapter of axios, i.e. https://github.com/lifeomic/axios-fetch. Or set the Referer header following the RefererPolify [specifications](https://w3c.github.io/webappsec-referrer-policy/#referrer-policies), which means simulate the browser behaviors.

**Comment by jasonsaayman** [comment]
Please follow the advise above closing for now.

**Comment by awerlang** [comment]
> axios uses different underlayer APIs with fetch, which is xhr in browsers. If want to use this feature directly, you need a fetch adapter of axios, i.e. https://github.com/lifeomic/axios-fetch. ~Or set the Referer header following the RefererPolify [specifications](https://w3c.github.io/webappsec-referrer-policy/#referrer-policies), which means simulate the browser behaviors.~

According to axios-fetch gh:

> This library exposes a Fetch WebAPI implementation backed by an Axios client instance. This allows a bridge between projects that have pre-configured Axios clients already to other libraries that require Fetch implementations.

So axios-fetch is not a viable replacement. It needs a fetch backend, not a axios adapter with a fetch interface. The advice for users would be: skip axios, use fetch directly.
