### ISSUE TITLE
Post size limit in android with react-nativ

### ISSUE THREAD

**Issue by pasckosky** [axios/axios#3353]
#### Describe the issue
Hi.
I am using Axios in a react project that builds both for web and mobile app with react-native.
I am currently using version 0.20.0 that is currently the last.
Looking at the previous issues I was not able to find any prior solution.

Everything is good except when I try to do a multipart/form-data post with some files (server is under my control and available via https).
On some conditions, axios raises an empty exception before sending anything to the server, other times it goes good.

After some tests and search in the previous issues and other pages in internet (yes, stackoverflow too) I was able to identify the condition of the error: the size of the post request.

For requests below 1E6 bytes (I didn't traced down to the exact number, but 1MiB seems already over) I can send several files without any problems.
If I try to send even a single file, but greater than 1MB, axios gives the error without sending anything to the server.

Problem is always reproducible.

I get the file through document-picker in android. The uri in this case is content://something and it is passed via a FormData object.

#### Example Code

```js
const form = new FormData();
form.append("jsonData", someJsonString);
form.append("fieldName", fileObject);

const api_base = axios.create({
    baseURL: "https://someserver.com/api/",
});
const header = {
    "Content-Type": "multipart/form-data",
    "Authorization": "Token sometoken",
};
api_base.post("savemethod", form, { headers: headers})
    .then((res) => { /* if ok */ })
    .catch((err) => { /* if not ok */ });
```

#### Expected behavior, if applicable
It works under browser. Should work in android too

#### Environment
 - Axios Version 0.20.0
 - Node.js Version 12.19
 - OS: Android 10
 - Additional Library Versions React 16.11, React Native 0.62.2

#### Additional context/Screenshots
I read something about maxContentLength and maxBodyLength but either they do not work in this environment or I was not able to figure out how to pass them properly.

The same code in the browser (without the maxContentLength and maxBodyLength) works like a charm and allows me to upload files of several MB (even 20MB), so I suppose that it is something related to android.

Question is:
how can I modify the max size of the request to set it at least at (let's say) 10MB?

thanks in advance

**Comment by pasckosky** [comment]
> @pasckosky I am facing the same issue, were you able to find a fix ?
> ps: I am using fetch and not axios, but I have the exact same symptoms

No fix. Yet. Sorry @ba-ddou 
Honestly I did not tried too much.

Project changed to be web instead of app (it worked on web), but the information that fetch has the same behaviour make me think that is not something of axios itself. Maybe a limit of react-native?

The only workaround I can think of is to pack the whole buffer somehow, do several post with fragments and declare upload completed when the last chunk is transmitted, but this kind of op requires a change on server too (that obviously has to rebuild and unpack)

Upload worked on Android when I splitted the post in several requests where each post was carrying a single file, but I was only moving the problem to the single file when one of it was bigger than the limit.

I will investigate on react-native side, but I don't know exactly when.

**Comment by pasckosky** [comment]
You mean a limit of Android or the implementation of react-native networking on Android (maybe a missing or a wrong parameter value)?

Cannot test with react-native on iOS. I don't have a mac to build an app, but it would be nice to know.
At least to know if it's something related to the Android world or react-native world.

Anyway it does not seem something specific of Axios. Just for the log.

**Comment by Warmachine13** [comment]
same problem here, I can't upload files from react-native-document-picker using axios, passing uri from file
