### ISSUE TITLE
multiple axios instances vs singleton/factory pattern

### ISSUE THREAD

**Issue by codewitch** [axios/axios#3365]
#### Describe the issue
What is the best approach to using axios instances? Is creating a new axios instance per service object have downsides or should I go with a singleton approach?

#### Example Code
```ts 
class HttpClient {
  protected readonly instance: AxiosInstance;

  public constructor(baseURL: string) {
    this.instance = axios.create({
      baseURL,
    });

    this._initializeResponseInterceptor();
  }

  private _initializeResponseInterceptor = () => {
    this.instance.interceptors.response.use(
      this._handleResponse,
      this._handleError
    );
  };

  // pulls just the data out of the response
  private _handleResponse = ({ data }: AxiosResponse) => data;

  protected _handleError = (error: any) => Promise.reject(error);
}
```

#### Expected behavior, if applicable
The documentation doesn't suggest either way. 

#### Environment
 - Axios Version 0.19.2
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 86.0.4240.80
 - Node.js Version 14.14.0
 - OS: OSX 10.15.6
 - Additional Library Versions React 17.0.1

**Comment by chinesedfan** [comment]
It depends. Usually, different axios instances mean different axios configurations. If your project can share the same configuration, I suggest singleton. Hope this reply helps your understanding.
