### ISSUE TITLE
Page downloaded is not the same as page shown on browser

### ISSUE THREAD

**Issue by TechnoTew** [axios/axios#3372]
#### Describe the issue
A clear and concise description of what the issue is.

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
const axios = require('axios');
const cheerio = require('cheerio');
const siteURL = "https://stockbeep.com";
const htmlToImage = require("html-to-image");
const fs = require('fs');
async function fetchHTML(url) {
    const { data } = await axios.get(url);
    return cheerio.load(data);
}
async function main() {
    const HTMLPAGE = await fetchHTML(siteURL);
    fs.writeFileSync("test.html", HTMLPAGE.html());
}

main();
```

#### Expected behavior, if applicable
Getting the snapshotted page from the first image linked down below, but only got table with no data in second page

#### Environment
 - Axios Version [e.g. 0.18.0]: 0.19.2
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]1
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]: v12.19.0
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]:  Windows 10.0.19041 N/A Build 19041
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]: cheerio@1.0.0-rc.3

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.
Original site screengrab:
![image](https://user-images.githubusercontent.com/24708918/97709723-c1765700-1af5-11eb-9f36-1a3f95160e16.png)

HTML Page Downloaded (and saved into text using cheerio.load(data).html()
![image](https://user-images.githubusercontent.com/24708918/97709745-c9ce9200-1af5-11eb-84e4-0e6562c8a418.png)

**Comment by DigitalBrainJS** [comment]
That is not a static html page, it has some dynamic content generated by client-side js.
This is not axios issue. You can use [puppeteer](https://www.npmjs.com/package/puppeteer) for your challenge.

**Comment by chinesedfan** [comment]
Closed as above explained. If you confirm that axios should do something, feel free to remind me to reopen.
