### ISSUE TITLE
GET request without paramters fail!

### ISSUE THREAD

**Issue by zsn6034** [axios/axios#3379]
#### Describe the bug
The GET request without parameters is used to obtain the json file of the local service. The first request succeeds, and the second request fails. 

#### To Reproduce
```js
const clientManifestResp = await axios.request({
        url: 'http://localhost:8080/vue-ssr-client-manifest.json',
        method: 'get'
    });
```
The above code causes the value to be obtained in the first GET request, and undefined in the second request. But after adding the params parameter to the request, no matter how many times the request is tried (how many times it is refreshed), the value can be obtained：
```js
const clientManifestResp = await axios.request({
        url: 'http://localhost:8080/vue-ssr-client-manifest.json',
        method: 'get',
        params: {}
    });
```

#### Expected behavior
GET request obtain a JSON value rather then undefined.

#### Environment
 - Axios Version [0.19.2]
 - Browser [Chrome]
 - Browser Version [86.0.4240.111]
 - Node.js Version [v12.19.0]
 - OS: [OSX 10.15.6]

#### Additional context/Screenshots
The JSON file of the local service is as follows:
![image](https://user-images.githubusercontent.com/30592700/97944485-c9691c00-1dbf-11eb-8d42-e2272f38b362.png)

**Comment by chinesedfan** [comment]
Can you try the latest 0.21 version? If the problems is still there, a quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. Say with or without `params: {}`.

**Comment by timemachine3030** [comment]
@zsn6034 What service is listening on `localhost:8080`?
