### ISSUE TITLE
Support async transformers

### ISSUE THREAD

**Issue by meetmangukiya** [axios/axios#3383]
#### Is your feature request related to a problem? Please describe.
Most of the authenticated APIs that would require embedding tokens in headers or data and that requires refreshing could be implemented by a transformer but it isn't supported to be async in axios at the moment. If async transformers are allowed that would be awaited before going on to the next chain and so on, then we can implement the auth mechanisms with token refreshing very easily.

#### Describe the solution you'd like
Await transformers

#### Describe alternatives you've considered
We can use interceptors. Interceptors can be async.

#### Additional context
In the feature problem description

**Comment by meetmangukiya** [comment]
Turns out we can await interceptors. Not transformers though. Will update the issue. 

Example:
```js
const axios = require("axios");

const sleep = (ms) => new Promise((resolve, reject) => setTimeout(resolve, ms));

(async () => {
        const client = axios.create({
                baseURL: "https://httpbin.org",
        });

        client.interceptors.request.use(async (config) => {
                await sleep(5000);
                return config;
        });

        console.log(await client.get("/headers"));
})();
```

**Comment by chinesedfan** [comment]
Async transformers can be replaced by interceptors. Did you have something that requires async transformers only?

**Comment by meetmangukiya** [comment]
I do not have any particular usecase in mind currently. But the same can be questioned for why do we have transformers at all if the same job can be done by interceptors? 

Also, maybe if it counts, the order of processing in transformers is fixed and deterministic from the declaration in the config. 

The order in transformers is deterministic as well

```js
const axios = require("axios");

const sleep = (ms) => new Promise((resolve, reject) => setTimeout(resolve, ms));

(async () => {
        const client = axios.create({
                baseURL: "https://httpbin.org",
        });

        client.interceptors.request.use(async (config) => {
                                                                console.log('sleeping 5000')
                await sleep(5000);
                return config;
        });

        client.interceptors.request.use(async (config) => {
                                                                console.log('sleepig 1000')
                await sleep(1000);
                return config;
        });
        client.interceptors.request.use(async (config) => {
                                                                console.log('sleepig 2000')
                await sleep(1000);
                return config;
        });

        console.log(await client.get("/headers"));
})();
```

This yields

```
sleepig 2000
sleepig 1000
sleeping 5000
```

which means the last registered interceptor is the first one called, interceptors are a stack, while transformers are queued. 
Interceptors can be added dynamically after creation of the axios instance, making it possibly undeterministic, however, transformers are determinstic because of how they are instantiated. Transformers are also intuitive and meant to change the data and payload specifically. Interceptors on the other hand can alter the whole config dynamically, more flexible, more unituitive in their function. 

So, why not allow a choice between the two and let people choose what they may?

**Comment by chinesedfan** [comment]
> So, why not allow a choice between the two and let people choose what they may?

You did great comparisons between intercepters and transformers. The reason is that current interfaces are enough, or at least nearly enough. Async transformers may increase 1% use cases coverage, but may increase more bugs and maintaining burdens. Thanks for understanding.

**Comment by peerless2012** [comment]
The await in intercept

> Turns out we can await interceptors. Not transformers though. Will update the issue.
> 
> Example:
> 
> ```js
> const axios = require("axios");
> 
> const sleep = (ms) => new Promise((resolve, reject) => setTimeout(resolve, ms));
> 
> (async () => {
>         const client = axios.create({
>                 baseURL: "https://httpbin.org",
>         });
> 
>         client.interceptors.request.use(async (config) => {
>                 await sleep(5000);
>                 return config;
>         });
> 
>         console.log(await client.get("/headers"));
> })();
> ```

I have the same issue as this case.

I have to do some operation before request, and the some operation is async, the order is very important, but it seems this fr is not consider to add.
