### ISSUE TITLE
get a https url no response no error

### ISSUE THREAD

**Issue by haying2005** [axios/axios#3402]
I request this https url in my server, no response, no error, but in my local pc, it is normal
![image](https://user-images.githubusercontent.com/13112261/98928276-92f47500-2514-11eb-8698-8ced8324e289.png)

but I change to http, it is normal
![image](https://user-images.githubusercontent.com/13112261/98928556-df3fb500-2514-11eb-879b-8874446b4666.png)

I do not know why, maybe the firewall policy of server? but why http is ok??
and I have try: process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0; it dosen't work

**Comment by haying2005** [comment]
I have update to the latest version: 0.21.0

**Comment by jbaris** [comment]
Can you be more specific? Are you facing this issue on 0.21.0 ? Or 0.21.0 was the solution? 
Many thanks!
