### ISSUE TITLE
how to watch lib file change to bundle a new aioxs.js file

### ISSUE THREAD

**Issue by WangZhenHao** [axios/axios#3411]
#### Describe the issue
I want to study your source code。But I don't know how to build development's file
npm run examples is a production core. i want to run development core
how i can do?

#### Expected behavior, if applicable
npm run dev

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by timemachine3030** [comment]
Not sure exactly what you are asking. I you look in the `package.json` file there is a script for building: `"build": "NODE_ENV=production grunt build",` If you don't want a production build then you can `grunt build`.

Looking at the `Gruntfile.js`, the grunt target `build` runs the `webpack` task.

If you want to study the code the best place to start is the `index.js` file. I did a full review of the source on my blog: http://ctrl-c.club/~timemachine/2020/10/24/code-review-axios/

**Comment by WangZhenHao** [comment]
> Not sure exactly what you are asking. I you look in the `package.json` file there is a script for building: `"build": "NODE_ENV=production grunt build",` If you don't want a production build then you can `grunt build`.
> 
> Looking at the `Gruntfile.js`, the grunt target `build` runs the `webpack` task.
> 
> If you want to study the code the best place to start is the `index.js` file. I did a full review of the source on my blog: http://ctrl-c.club/~timemachine/2020/10/24/code-review-axios/

Thank your patience , my English is very poor. What I mean is how to watch the lib file'core change to bundle a new axios.js file. `npm run build` is bundle the new file, but can't watch the file change evenytime!

**Comment by chinesedfan** [comment]
The project doesn't support it directly. You need setup a webpack-dev-server by yourself.

**Comment by WangZhenHao** [comment]
> The project doesn't support it directly. You need setup a webpack-dev-server by yourself.
Is it impossible that the author writes code once and then compiles it?Don't you need to write code and see what happens?（
不可能吧，难道作者写一次代码，就编译通过了？不需要边写代码边看效果的吗？）

**Comment by chinesedfan** [comment]
That's why we have lots of tests. We trust on automatic tests, instead of human checking.

**Comment by WangZhenHao** [comment]
> That's why we have lots of tests. We trust on automatic tests, instead of human checking.

I see. Thank you（明白了，谢谢）
