### ISSUE TITLE
JSON data automatic transformation and parse error

### ISSUE THREAD

**Issue by plap979** [axios/axios#3419]
#### Describe the bug
Axios should decide to parse result as JSON data since I'm sending "Accept: application/json" and it should do that or fail on doing that. (If the server is responding with a json encoded string, I can't know the string is been decoded.) I can see an unpredictable behaviour I can't rely on.

#### To Reproduce
I'm about download a static *.json file (used for localization messages), sending "Accept: application/json" and receiving "Content-Type: application/json". But, and that's unwanted, if there is a parsing error, Axios successful and silently resolves with a text string instead of rejecting and complaining about errors.

```js
    promise = axios.get(`app/i18n/messages/${lang}.json`, {
      headers: {Accept: "application/json"}
    }).then(function (response) {
      // response.data can be string or object depending on parse failure
    });
```

#### Expected behavior
As I'm requesting JSON data since I'm sending "Accept: application/json", I need Axios resolves to an object or an array (or whatever JSON type, even a string), or to fail doing that, never performing half of the job.

#### Environment
 - Axios Version: v0.21.0
 - Adapter: XHR
 - Browser: Chromium
 - Browser Version: 86.0.4240.75 
 - Node.js Version: N/A
 - OS: Ubuntu 16.04.7
 - Additional Library Versions: N/A

#### Additional context/Screenshots
None

**Comment by timemachine3030** [comment]
I agree fully with your comment. Unfortunately, the common state of how web servers implement the HTTP protocol make this sort of strictness difficult for a general purpose library.

With the intention of being general purpose Axios allows you to override any of the default behaviors.  You can, for example, create an instance that will act as you are requesting:

`axios-instance.js`
```js
const axios = require('axios');
module.exports = axios.create({
  transformResponse: [function transformResponse(data, headers) {
    // Optionally you can check the response headers['content-type'] for application/json or text/json
    return JSON.parse(data);
  }]
}); 
```

then use this instance instead of the default:
```js
const axios = require('./axios-instance.js');
```

**Comment by ps2goat** [comment]
Was this listed as a breaking change somewhere? I just updated from 0.19.x to 0.24.x and now 0.25.x; it has always been my experience with Axios that the json was auto-parsed. I verified it works like that in 0.19.x, and I didn't see an explicit breaking change for this lost functionality. (Maybe it was an unintended feature?)

**Comment by ps2goat** [comment]
It appears my "bug" is an issue with how the Axios class works vs `axios.create` https://github.com/axios/axios/issues/4160, suggested pr https://github.com/axios/axios/pull/4213/files

Basically, the defaults merged into your configs with `axios.create()` do not get merged into `new Axios()` like I'd expect. Neither are the defaults exposed reliably (e.g., exported somehow).

**Comment by Stephen2** [comment]
Oh wow. This broke my head for a couple of hours. Thank you @ps2goat for this. `new Axios()` feels so intuitive... but then unexpected behaviour starts up.

**Comment by SageJustus** [comment]
> +1
> 
> I just discovered this thread while trying to figure out why it wasn't auto-parsing the `response.data`. I think the constructor needs to be made private so users are pushed to the factory method.我刚刚在试图弄清楚为什么它没有自动解析 `response.data` 时发现了这个线程。我认为构造函数需要设为私有，以便用户被推送到工厂方法。

The benefit of being public is that it allows you to inherit the `Axios` class
