### ISSUE TITLE
Interceptor Response AxiosError object doesn't provide the server custom error message for HTTP status 503

### ISSUE THREAD

**Issue by R4DIC4L** [axios/axios#3429]
#### Describe the bug
When using a response reject interceptor, the AxiosError object does not contain the original message in case of 503 Server Unavailable HTTP status code.

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```ts
import axios, { AxiosRequestConfig, AxiosInstance, AxiosResponse, AxiosError, CancelToken } from 'axios';
import { StatusCodes } from 'http-status-codes';

var client = axios.create(config); // config only defines base URL and some auth headers
client.interceptors.response.use(undefined, (error: any) => {
        if (axios.isCancel(error)) {
          // Request cancelled
          return;
        }
        const axiosError = <AxiosError<any>>(error);
        if (axiosError && axiosError.response && axiosError.response.status === StatusCodes.SERVICE_UNAVAILABLE) {
          const displayMessage = axiosError.response?.data ?? axiosError.response?.statusText ?? axiosError.message; // tried checking every place where the message could be
          console.log(displayMessage);
        }
      });

...

client.post(resourceUrl); // resource url points to the resource for the POST action
```

#### Expected behavior
I expected that I can access my custom error message somewhere in the AxiosError object, but I only see the 'Request failed with status 503' message in the debugger (this might happen for other 4xx statuses also). My custom status seems to be visible only under an internal field (**axiosError.request._response**).

#### Environment
 - Axios Version: 0.20.0
 - Adapter [e.g. XHR/HTTP]
 - Browser: react-native with Chrome debugger
 - Browser Version: Chrome version 86.0.4240.198 (Official Build) (64-bit)
 - Node.js Version: 13.7.0
 - OS: Android simulator on Windows 10
 - Additional Library Versions: React Native 0.63.3

#### Additional context/Screenshots
Here are some screenshots to with the response I get. Is there any way to make the **axiosError.request._response** available to the interceptor? It doesn't seem right to use the private property for the server custom message (which I added both in body and reason phrase as text in the server response).

This is what I can access from the request
![axios503error](https://user-images.githubusercontent.com/7274664/99958970-f1321b00-2d92-11eb-8c01-fafb1101b10f.PNG)

This is what I want to get - the custom message
![axios503error-internal-custom-message](https://user-images.githubusercontent.com/7274664/99958974-f2634800-2d92-11eb-8f0c-ee82dc25a82d.PNG)

**Comment by R4DIC4L** [comment]
Seems I have managed to get the response in the axiosError.response.data field by sending it as a json instead of text in the body. I noticed now that the axiosError.response._responseType was set to 'json', so maybe that was the reason why I did not get the message?

I still believe it would be nice to have the raw data somewhere available and that others might run into the same situation as described above as well. This can be treated as an improvement to the existing functionality.

**Comment by chinesedfan** [comment]
> by sending it as a json instead of text in the body

Can you paste the codes? Seems that it depends on your server.

**Comment by R4DIC4L** [comment]
My server is an ASP.NET Web API 2. In the web method, I return a message as such:

`
string underMaintenanceText = "Test under maintenance";
HttpResponseMessage result = new HttpResponseMessage(HttpStatusCode.ServiceUnavailable);
result.Content = new StringContent(underMaintenanceText);
result.ReasonPhrase = underMaintenanceText;
`

It might matter, but I also have **responseType** set to 'json' in the AxiosRequestConfig config of the POST method. 

When I changed as below, the message was correctly added to **response.data**. Again, this might be related to the responseType 'json', but I'm not sure if axios respects that over the content-type header. I expect that it also checks the header for the response type.

`
string underMaintenanceText = "Test under maintenance";
HttpResponseMessage result = new HttpResponseMessage(HttpStatusCode.ServiceUnavailable);
result.Content = new StringContent(underMaintenanceText?.ToJSON());
result.ReasonPhrase = underMaintenanceText;
`

Do you need any other information?
