### ISSUE TITLE
HPE_INVALID_STATUS due to response status code is 1111

### ISSUE THREAD

**Issue by yelichi** [axios/axios#3431]
#### Section/Content To Improve
Quote or link to section

#### Suggested Improvement
Identify what is confusing or incorrect and what could make it better

#### Relevant File(s)
[e.g. README.md]

I am calling an API which responses http status code is 1111, then throws HPE_INVALID_STATUS error.

Any way we can avoid this error?
Because this response http status code can be customized to any numbers.

Environment

Axios Version : 0.18.0
Adapter: HTTP
Node.js Version: 8.9.3
OS: Windows 10 Enterprises

**Comment by yelichi** [comment]
And I also tried Axios version: 0.21.0 still the same error occurred

**Comment by chinesedfan** [comment]
Try to set `config.validateStatus`.

**Comment by yelichi** [comment]
Thanks for your response. I have tried this way. Please check the code as below 
```js
// Example code here
validateStatus: function (status) {
    console.log(‘status===>’ , status);
    return (status >= 200 && status < 300) || status >= 1000;
}
```

And it won’t go into the function. It throws the same error directly.

**Comment by chinesedfan** [comment]
Seems like a limitation of Node.js. See https://github.com/nodejs/node-v0.x-archive/issues/8760. You can check with the native `http` module, instead of axios.
