### ISSUE TITLE
Axios recognizes 401 wrong and lost all the config in a case of a heavy request

### ISSUE THREAD

**Issue by KathRains** [axios/axios#3435]
#### Describe the bug
I use JWT to protect the backend. As soon as an access token is expired the backend sends 401 back, my front-end sends the request to regenerate a new token, and then resend the primary request.

But I found that if the request is heavy (for example, when you upload pictures, or have a lot of data inside) axios can't recognize the response properly. I see the network problem or some other stuff where the backend actually sent the normal 401 response:

So, basically the same code works properly or doesn't depending on the size of the sent data. I found 300> KB already causes this problem. It looks like an axios bug.

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Just a normal post but data should be big:

let response = await axios.post('/app/api/entity/', obj); // Obj is a big object
```

#### Expected behavior
Axios should recognize the response when its status is 401.

#### Environment
 - Axios Version 0.19.0
 - Browser Chrome 87.0.4280.66
 - OS:  Win 7
 - React 16.11.0

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/6174408/100166426-f61dca00-2e79-11eb-85c6-8279319c03d1.png)

You can see on the screenshot the part of VS Code showing it sends the 401 successfully and the browser console below showing the network error.

**Comment by daniel-julius-sam** [comment]
I think this is an issue which is caused by a limit to the data that can be posted in a request by the server that you are trying to send to, rather than this being a problem with axios.
