### ISSUE TITLE
get cookie from 303 redirect response (react native)

### ISSUE THREAD

**Issue by puroong** [axios/axios#3438]
#### Describe the issue

```
Request Flow
1. POST /login/index.php
2. POST /login/index.php returns 303 status code and redirects to /
3. GET / returns 200 status code
```

Hi, I'm trying to use cookie based authentication with react native 
I need to extract cookie from Set-Cookie header and only Step 2 has this header.
I could do it with code below in node, since 303 status code throws error,

```
return axios
    .post(LOGIN_URL, `username=${username}&password=${password}`, {
      maxRedirects: 0,
    })
    .catch((res) => {
      const location = res.response.headers.location;
      const errorCode = getErrorCode(location);

      checkError(errorCode);

      return res.response.request.res.headers['set-cookie'];
    })
```

but when I tried the same code in react native, the response status code is 200
and I found out xhr requests cannot catch redirects

Is there any way to get cookie from Step 2 without modifying server side code?
 
#### Environment
 - Axios Version [e.g. 0.20.0]
 - Adapter [XHR]
 - Node.js Version [10.19.0]
 - OS: [Ubuntu 20.04]
 - Additional Library Versions [React Native 0.63.2]

**Comment by fullflash** [comment]
that is really needed future.
there are tons of student level http packages with lack of this scenario.

**Comment by zuccha** [comment]
Same issue here, didn't find a solution yet.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
