### ISSUE TITLE
Preflight request + cookie

### ISSUE THREAD

**Issue by flipkickmedia** [axios/axios#3443]
#### Describe the issue
When sending a preflight request (OPTIONS) Id like the cookie which is sent on the actual request to be included.

#### Example Code
```
export async function apiData(api: ApiCall) {
  axios.defaults.withCredentials = true;
  const compiled = {
    data: JSON.stringify(api.data),
    url: api.url,
    headers: api.headers,
    method: api.method,
    withCredentials: true
  } as ApiCall;
  const req: ServerResponseInterface = await axios.request(compiled);
  return { req };
}
```

#### Expected behavior, if applicable
If a cookie is sent with the request Id expect it to be sent during the options call

#### Environment
 - Axios: 0.20.0
 - Browser: Any
 - Node.js Version v14.15.1 compiled and running in browser.
 - OS: Any
 - Using Vue3 + Typescript

#### Additional context/Screenshots
Simply, when I send a request, and it includes a cookie, Id expect that also to be sent in the preflight request.

**Comment by flipkickmedia** [comment]
If I specifically add the cookie using:
```
export async function apiData(api: ApiCall) {
  axios.defaults.withCredentials = true;
  const test = VueCookieNext.getCookie('scraplocal-microservice')
  console.log(test)
  api.headers.Cookie = `mycookiename=${test};`
  const compiled = {
    data: JSON.stringify(api.data),
    url: api.url,
    headers: api.headers,
    method: api.method,
    withCredentials: true
  } as ApiCall;
  const req: ServerResponseInterface = await axios.request(compiled);
  return { req };
}
```

...the cookie is still not sent during a preflight request.

**Comment by allandiego** [comment]
I think its a axios problem, im trying to send cookies with post request and the same request with fech works but with axios not:

```ts
    axios.defaults.withCredentials = true;
    // get set-cookie
    const cookieResponse = await axios.get(url);
    const cookie = cookieResponse.headers['set-cookie'].join(';');

     // fetch request working
     const responseFetch = await fetch(url,
      {
        method: 'POST',
        credentials: 'include',
        body: JSON.stringify(bodyData),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
          cookie,
        },
      },
    );

   const data = await responseFetch .json();
   console.log('data');

  // Axios request not working with same cookie
    const responseAxios = await axios.post(url,
      {
        data: JSON.stringify(bodyData),
        // withCredentials: true, tested with this and in defaults
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
          cookie,
        },
      },
    );
```

**Comment by flipkickmedia** [comment]
As I understand it there is no spec which indicates that a preflight request could or should contain cookies, but if you consider that the OPTIONS response might change as a result of a cookie being present (i.e. you are logged in) it would make sense to allow cookies to be sent to the preflight request to ensure the OPTIONS sent back to you are the ones available to you.

In any case since you can't handle the preflight request having the preflight request is completely redundant as I'm having to send a second request the server to see what options are available to me under the roles/permissions assigned to the session.

In terms of sending cookies with an axios request, this should work.

Try changing your cookie code to:

```
     const cookieContent = "some cookie data"
     const responseFetch = await fetch(url,
      {
        method: 'POST',
        credentials: 'include',
        body: JSON.stringify(bodyData),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
          'Cookie': cookieContent
        },
      },
    );
```

You should see cookies being sent over the wire (albeit not on the preflight)

**Comment by allandiego** [comment]
I already have tried with 'Cookie': cookie, its the same

**Comment by flyher** [comment]
The same need!

**Comment by andrewfader** [comment]
What's the deal here - is it supposed to send cookies on the cors preflight OPTIONS call or not? No spec has ever decided that? It seems to me that it should be at least possible to do this if desired

**Comment by jasonsaayman** [comment]
Closing please real the link as mentioned above
