### ISSUE TITLE
Weird date in post request when sending a date before 1927

### ISSUE THREAD

**Issue by gustavshf** [axios/axios#3452]
#### Describe the bug

I've noticed a very strange behavior for POST requests - when I send, for example, 01-01-1928, everything is fine, however, when I send 01-01-1926, I get a weird date in the payload of the POST request. Instead of 00:00:00 I get 22:23:26. (see screenshot below)

#### To Reproduce
Here is a sandbox with a date before 1927 (demonstrates the issue): https://codesandbox.io/s/axios-post-data-form-forked-1wvyk?file=/src/index.js

Here is a sandbox with a date after 1927 (everything is as expected): https://codesandbox.io/s/axios-post-data-form-forked-6g6gt?file=/src/index.js

#### Expected behavior
The date should behave the same as dates after 1927

#### Environment
 - Axios Version [0.19.2]
 - Adapter [HTTP]
 - Browser [Chrome]
 - Browser Version [87]
 - Node.js Version [13.0.1]
 - OS: [Windows]
 - Additional Library Versions [React 16.7]

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/26459104/100926946-d7a87600-34ec-11eb-92fb-c493d6587b4e.png)

**Comment by chinesedfan** [comment]
It's a misusage related to time zones. See https://stackoverflow.com/a/65129853/6501855.
