### ISSUE TITLE
Axios Proxy Issues - 501 and SSL errors

### ISSUE THREAD

**Issue by dinojs** [axios/axios#3459]
#### Describe the bug
Getting weird error messages when passing a proxy into an Axios request. I've tried to add a `proxy` parameter to the following `GET` request and I get a `501` error code and when I then add a `protocol` parameter to the `proxy` object I get an `openssl` error

Note that I don't have any of these issues when using the library `axios-https-proxy-fix`, https://www.npmjs.com/package/axios-https-proxy-fix

#### To Reproduce
```javascript
axios
    .get(prod, {
        proxy: {
            host: proxy.host,
            port: proxy.port,
            auth: {
                username: proxy.userName,
                password: proxy.password,
            },
        }
    })
```

Then I tried adding `protocol` to the `proxy` object, like so:
```javascript
axios
    .get(prod, {
        proxy: {
            protocol: "https",
            host: proxy.host,
            port: proxy.port,
            auth: {
                username: proxy.userName,
                password: proxy.password,
            },
        }
    })
```

Error:
```bash
write EPROTO 17828:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
```

#### Expected behavior
No `501` and no `openssl` issues. Should get a `200` response.

#### Environment
 - Axios Version 0.21.0
 - Node.js Version 12.17
 - OS: Windows 10

#### Additional context/Screenshots
N/A

**Comment by DiogoTheCoder** [comment]
Having the same issue. Could we implement the fix of this fixer library/package, `axios-https-proxy-fix`, it also fixed my issue. Cheers.

**Comment by Niek** [comment]
Related PR: https://github.com/axios/axios/pull/3159

**Comment by ZubaerRahman** [comment]
I'm facing the same  issue

**Comment by cs17sss2** [comment]
Not working for me either, please fix

**Comment by Amrod92** [comment]
It is not working for me either and I read it’s been a problem for a few years now, are we expecting a fix soon? Thanks for your work

**Comment by JamelxD** [comment]
Having this weird issue myself

**Comment by elapovski** [comment]
I tried with different proxies and I can confirm none of mine are working either

**Comment by saamalik** [comment]
Until a proper fix is implemented in the library, here is the workaround I used:

```js
import HttpsProxyAgent from 'https-proxy-agent'
```
```js
    this.client = axios.create({
      baseURL: `https://${this.host}`,
      httpsAgent: new HttpsProxyAgent(process.env.HTTPS_PROXY),
      proxy: false,
      ....
    });
```
Note that `proxy` must be set to _false_ otherwise the adapter will try to initialize it again from the environment variable. 

For a complete example (with proxy and no proxy): https://github.com/spectrocloud/k8s-set-context/blob/690044f1c02048af0e4b7470dd70306ef1f4556b/src/client.ts#L36-L54

**Comment by NaitYoussef** [comment]
I'm facing the same issue too

**Comment by returnzer0** [comment]
Did this issue ever get fixed? Facing the same thing with trying to setup a simple proxy.

**Comment by dor-benatia** [comment]
this keep happening and @saamalik solution did not work for me. is there a working workaround or should we downgrade to 0.18 in the mean time ?

**Comment by mcianc** [comment]
faced the same issue on the 0.24.0 package

**Comment by dzcpy** [comment]
Same issue

**Comment by scottie** [comment]
Same here

**Comment by jjelement** [comment]
Same issue

**Comment by HandsomeTea** [comment]
try to this
`node --tls-min-v1.0 xxx.js`

**Comment by ethan-deng** [comment]
This solution works for me.

import HttpsProxyAgent from 'https-proxy-agent'
    
this.client = axios.create({
      baseURL: `https://${this.host}`,
      httpsAgent: new HttpsProxyAgent(process.env.HTTPS_PROXY),
      proxy: false,
      ....
    });

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by thombergs** [comment]
I'm still running into this issue with the (currently) latest version 0.27.2

**Comment by sils** [comment]
Getting this too still!
