### ISSUE TITLE
With global agent, sending POST and receive GET 

### ISSUE THREAD

**Issue by dewaele-benoit** [axios/axios#3463]
#### Describe the issue
I'm using axios with super-agent to set my proxy. When I try to send a request as POST method, I receive a request as GET method. 
I specify that by using superagent I have no problem.

#### Example Code
Code snippet to illustrate your question

```js
// index.js 
const {bootstrap}  = require("global-agent");
bootstrap();
global.GLOBAL_AGENT.HTTP_PROXY = process.env.http_proxy;

// other file
try {
      const payload = {
        // data to send
      }
      // Token for authentication
      const token = ""
      const config = {
        headers: { Authorization: `Bearer ${token}`}
      }
      // URL of my request
      const url = "http:// ...  /api/crudihm"
      const result = await axios.post(url, payload, config);
      console.log(result.data);
} catch (e) {
      console.log(e);
}
```

#### Expected behavior, if applicable
In this case I receive a response  as GET method but I want to receive a response as POST method.

#### Environment
 - "axios": "^0.21.0"
 - Node.js : 12.18.4 
 - "global-agent": "^2.1.12"

#### Additional context/Screenshots
![result-part1-modified](https://user-images.githubusercontent.com/22936624/101460143-7b54b480-3939-11eb-81e7-1fa4470f7fac.png)
![result-request-modified](https://user-images.githubusercontent.com/22936624/101460150-7c85e180-3939-11eb-9377-0eef72748853.png)

**Comment by risk1996** [comment]
It's happening on `axios@^0.21.0`, but not on `axios@^0.19.2`

**Comment by dewaele-benoit** [comment]
Thanks for your answer, but I still have the same issue with `axios@^0.19.2`. Do you have other ideas ?

**Comment by sijad** [comment]
in my case there was an issue with redirects (missing trailing slash), by setting `maxRedirects: 0` you can disable redirects

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
