### ISSUE TITLE
Hello I was wondering when is v0.21.1 coming out? :-)

### ISSUE THREAD

**Issue by poldee-lgi** [axios/axios#3465]
After reading through similar issues I'm facing I learnt that a fix is coming out in v0.21.1

It looks like, from what I can read in the different threads, it's ready to be released.

Do we have an ballpark ETA?

Thanks for a GREAT product team!

**Comment by jasonsaayman** [comment]
Hi @poldee-lgi,

I think it should be released by next week.

Thanks
