### ISSUE TITLE
Accented characters in header

### ISSUE THREAD

**Issue by nachocab** [axios/axios#3467]
#### Describe the issue
If I use this curl command, I get a 200 response:

```
curl "https://whatever/my.json" \
     -H 'Api-Username: olá'
```
But if I do the same thing in axios, I get a 500 response:
```
const axios = require("axios");
axios({
	"method": "GET",
	"url": "https://whatever/my.json",
	"headers": {
		"Api-Username": "olá"
	}
})
```
I always get a 200 in axios if the username doesn't have accented characters, so I'm assuming that's the problem.

I'm sure axios is doing something behind the scenes to modify the outgoing request but I don't know how to test what is actually going on.

#### Example Code
See above 

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
