### ISSUE TITLE
Axios not receiving 204 response with Transfer-Encoding header in Node v14

### ISSUE THREAD

**Issue by joshuas2020** [axios/axios#3473]
#### Describe the bug
After upgrading our node version to v14.15.1 our Axios requests in our express server never receive a response from an endpoint that returns 204 with header: 'Transfer-Encoding': 'chunked'.
I know we should not be receiving this ([see here](https://stackoverflow.com/questions/912863/is-an-http-application-that-sends-a-content-length-or-transfer-encoding-with-a-2)) but we do not have control of this endpoint.

Previously when we were on v10.23.0 of node we had no problem with receiving these responses. 

I have tried the same request with the [request](https://www.npmjs.com/package/request) library and am able to receive a response. See example below. 

#### To Reproduce
Created a simple express server to demonstrate.

npm install axios express request

With the following **index.js**

Sending a GET request to http://localhost:8555/request will return 200 OK, whereas the request to http://localhost:8555/ will timeout/never receive a response.

```js
const express = require('express');
const axios = require('axios');
const request = require('request');

const httpPort = 8555;

const app = express();

app.get('/', async (req, res, next) => {
  try {
    const result = await axios.get(`http://localhost:${httpPort}/sample-upstream-response`, {
      timeout: 10000,
    });
    res.send(result.data);
  } catch (error) {
    res.sendStatus(500);
  }
});

app.get('/request', (req, res, next) => {
  request(`http://localhost:${httpPort}/sample-upstream-response`, { json: true }, (err, response, body) => {
    if (err) { 
      return res.sendStatus(500);
    }
    res.send(body);
  });
});

app.get('/sample-upstream-response', (req, res, next) => {
  res.writeHead(204, {
    'Transfer-Encoding': 'chunked',
  });
  res.end();
});

app.listen(httpPort, () => {
  console.log(`INFO: listening on http://localhost:${httpPort}`);
});
```

#### Expected behavior
I am expecting that Axios should be able to receive the response from this server. Or I should be able to change some axios config to be able to receive this response.

#### Environment
 - Axios Version 0.21.0
 - Node.js Version 14.15.1
 - OS: Windows 10, ubuntu 18.04
 - Additional Library Versions express 4.17.1, request 2.88.2

**Comment by lalithkumart** [comment]
Yes, Same issue i am also facing with Node v14

After upgrading to v14, i am not getting response back in UI. However the node js sending the response (debugged till last step).

Also, if i hit the api via postman, it is getting response. 
Also if i hit this api via "Open Link in New Tab" option click, then also getting response back

Only in the application (where i am using axios), the response is not coming back. The status in console is keep on "Pending".

**Comment by DaWoCX** [comment]
I'm facing the same problem. 

With Postman / Soap UI I get a response but in my application the response gets lost in case of status code 204.

Used Versions:
- node.js: v14.13.0
- axios: 0.21.0

Used OS: Windows 10

**Comment by JuanKman94** [comment]
Is this fix present in 0.21.1?

**Comment by blaxk** [comment]
I have the same problem.
It does not respond to the request and enters an infinite pending state.

Due to this issue, axios is not available in node.js v14.
It works normally in node.js v12.

Are there any solutions to this problem?

node.js v14.15.15
axios: v0.21.1
OS: Debian GNU/Linux 9

**Comment by VassilAtanasov** [comment]
We are going for workaround - changing the code to return 200 instead of 204 status codes.

The problem (ahngign after the call) was spotted when Axios (any version) on node 14 calls node red api runnung on node 12.

**Comment by jasonsaayman** [comment]
Hi, 

I think the major issue is that Axios is not very stable on v14. I am planning to work on that and then a v16 as soon as it lands in April.

Thanks

**Comment by ryutamaki** [comment]
I have same issue.
As an additional information, it is happening when we return any body along with status code 204.

node v14.15.3
axios 0.21.1

**Comment by TrojanRocks** [comment]
I'm facing same issue, for me it's happening with no content in response for status  code 204

axios version 0.21.1

**Comment by AminFazlMondo** [comment]
Is there a timeframe that this might get fixed?

**Comment by blaxk** [comment]
Node.js v16 returns error.message = 'aborted' in the same situation.
It works normally when called with the "request" module.

node.js v16.13.0
axios: v0.24.0
OS: macOS Monterey 12.0.1

**Comment by AdamCuculich** [comment]
@joshuas2020 @VassilAtanasov Any update on this? Is anyone able to receive `204`s?

**Comment by joshuas2020** [comment]
Hi @AdamCuculich 
I just retried the above example with axios 0.26.0 and am now receiving an error: 'ERR_REQUEST_ABORTED'
I guess this is due to it expecting a chunked response but there being no data?

**Comment by AnjaneyuluBatta505** [comment]
I have same issue.
As an additional information, it is happening when we return no response body along with status code 204.

node v14.18.0
axios 0.24.0

**Comment by AdamCuculich** [comment]
Yes, it happens when no response body is received. My *temporary* solution was to just replace `204`s with `200`s -- not ideal, but it works.

**Comment by AnjaneyuluBatta505** [comment]
@AdamCuculich It's the issue with API response for me i.e fastapi https://github.com/tiangolo/fastapi/issues/2832.
After fixing the response then it worked.

**Comment by christianallred** [comment]
Is this going to be addressed? this ticket has been open for 2 years

**Comment by tregonzalesCar** [comment]
is this being addressed elsewhere?

**Comment by EmadMirzaieR** [comment]
It was very painful. I wasted my time on this.

**Comment by tregonzalesCar** [comment]
@jasonsaayman is this addressed in any new axios versions?

**Comment by cucupac** [comment]
For me, the issue was that a 204 expects no content in the response, but I believe my 204 was sending "null" as a response, which was tripping up axios. For those in a similar boat, ensure that the response doesn't have a response body at all. It should work then.

**Comment by brinobruno** [comment]
Facing same issue, 200 followed by a 204, on Insomnia everything works fine, it's a simple node-react request with axios

**Comment by andrerocker** [comment]
Samething here! 
- backend: quarkus resteasty 
- frontend: react azios 1.5.1

**Comment by jasonsaayman** [comment]
closing, if this is still an issue please open a new issue
