### ISSUE TITLE
How can I mock a request rejection

### ISSUE THREAD

**Issue by xiaoyunchen** [axios/axios#3476]
#### Describe the issue
hey guys, I'm taking some unit test work with the Axios,
So How can I mock a request rejection? 

#### Example Code
Code snippet to illustrate your question

```js
// Add a request interceptor
axios.interceptors.request.use(function (config) {
    // Do something before request is sent
    return config;
  }, function (error) {
    // Do something with request error
    return Promise.reject(error);
  });
```

#### Expected behavior, if applicable
The request rejection function could be called

#### Environment
 - Axios Version latest
 - Adapter  HTTP
 - Browser Chrome
 - Browser Version 87
 - Node.js Version 10.15
 - OS: OSX 11

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
```
axios.interceptors.request.use(function (config) {
  // here is somewhere like `Promise.then`
  throw new Error('mocked error')
}, function (error) {
  return Promise.reject(error);
});
```
