### ISSUE TITLE
Axios doesnt send json.stringified data as payload, which is really weird.

### ISSUE THREAD

**Issue by DearVikki** [axios/axios#3478]
#### Describe the issue
Axios doesnt send json.stringified data. No request payload in network monitor. 

#### Example Code

```js
axios({
        method: 'post',
        url: 'url',
        data: JSON.stringify({a: 1}),
        headers: {
            'Content-Type': 'application/json',
        },
        transformRequest: [function (data, headers) {
            console.log('data', data) // no data as well
         }],
})
```

#### Expected behavior, if applicable
Request payload {a: 1}

#### Environment
 - Axios Version [e.g. 0.21.0]
 - Adapter [XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [80.0.3987.149]

#### Additional context/Screenshots
<img width="285" alt="WechatIMG355" src="https://user-images.githubusercontent.com/18145936/102332286-da17cf00-3fc6-11eb-8943-411c31bf05a9.png">

**Comment by MaddyGit** [comment]
Having similar trouble, axios doesn't send post body even without stringify;
```
axios({
        method: 'POST'
        , url: url
        , data: {
            username: 'test'
            , password: 'test'
        }
        , headers: {
            'Content-Type': 'application/json'
            , 'Accept': 'text/plain;charset=UTF-8'
        }
    })
    .then(res => console.log(res))
    .catch(err => console.log(err))
```

**Same request I edit on firefox and add body manually and resend it works**

**Comment by chinesedfan** [comment]
Failed to reproduce. Would you mind to provide a complete reproducible sample?

**Comment by MaddyGit** [comment]
> Failed to reproduce. Would you mind to provide a complete reproducible sample?

Strangely enough I can't reproduce it now also now both 'with `JSON.stringify`' and 'without `JSON.stringify`' are sending POST body.
