### ISSUE TITLE
axios.get() hangs indefinitely

### ISSUE THREAD

**Issue by ikv163** [axios/axios#3481]
Describe the issue
I have a Node application that consumes from a Kafka stream, transforms some data, and then makes a GET request to an internal API. I am running into an issue where the axios.get() request is hanging indefinitely. It doesn't ever time out, it just sits there until I kill the program. This seems to be an issue specific to Axios, as I replaced it with request-promise-native and was able to successfully make requests. I don't have much other information currently, but if there is a way to get more debug information I would be happy to do that and post the results here.

Example Code
Code snippet to illustrate your question

function update(id, revision, organizationId, text) {
    let organization;

    try {
      organization = organizationLookup(organizationId, environment, logger);
    } catch (err) {
      logger.error(err, `Failed to look up organization ${organizationId}`);
      return;
    }

    const { slug } = organization;
    const apiHostname = organization.metadata.api.stringValue;

    const endpoint = `https://${apiHostname}/photos/${id}`;

    try {
      return await axios.get(endpoint); // <-- Code gets here and just stops
    } catch (err) {
      logger.error(err);
      throw err;
    }
}
Expected behavior, if applicable
I would expect to get a response from the API that I make a request to and for my code to continue.

Environment:

Axios Version: 0.21.0
OS: OSX 10.12.6, centos:7.6.1810
Node Version: 15.1.0
Browser N/A (in node)
Browser Version N/A (in node)
Additional Library Versions: koa 2.7.0, node-rdkafka 2.6.1, async-retry 3.1.9
Additional context/Screenshots
I am using async-retry in my code, but to test this I removed that, and the problem persisted, so I do not think it is due to that library's use.

**Comment by ralphtheninja** [comment]
@ikv163 Did you manage to get any more information about this? I'm running into a similar problem. Get hangs forever for some reason, so the Promise never resolved. I'm suspecting some kind of network issue.
