### ISSUE TITLE
[Query] How to change the filename while uploading?

### ISSUE THREAD

**Issue by sourabhbagrecha** [axios/axios#3484]
#### Describe the issue
I am using the S3-signed-URL approach to upload files to my S3 bucket, since I want to make the name of objects unique on their own I want to attach a key-prefix(a UUID probably) but I am a little unsure on how to do that using Axios.

#### Example Code
Suppose a file that needs to be uploaded to S3 has a name: ```"sample.txt"```
Now, to avoid any conflict in the future because of the file name I want to attach a UUID as a prefix to the file, such that:
New file name while uploading should look like: ``` "5ebc176876-ab7552733-sample.txt"```

#### Expected behavior, if applicable
n/a

#### Environment
 - Axios Version 0.20.0
 - Adapter HTTP
 - Browser all
 - Browser all
 - Node.js Version 14.15.0
 - OS: Windows 10 pro
 - Additional Library Versions React v16.3.1

#### Additional context/Screenshots
For the record, I am using @apollo/client and apollo-server-express for communicating in a GraphQL env.

**Comment by kale1d0code** [comment]
is this possible?
I couldn't figure it out from this question

**Comment by kale1d0code** [comment]
The only way to upload files using Axios is to create a File object.
```
const file = new File(
    [fs.readFileSync(fileMeta.filepath)],
    fileMeta.originalFilename, //give the file a name here
    {
        type: fileMeta.mimetype
    }
)
```
you can then add this to a FormData object
```
const headers = {
    "Content-Type": "multipart/form-data",
};
const data = new FormData();
data.append('file', file);
await axios.post(
    url,
    data,
    {
        headers
    }
);
```
