### ISSUE TITLE
How to catch error statusCode 409 and detail message.

### ISSUE THREAD

**Issue by jochercoles** [axios/axios#3490]
#### Describe the issue
Hi, I'm doing a call to POST method of an API developed in .Net Core 3.0, as show in the Example Code, from a project in React.Js.

#### Example Code
const newCall = await axios.post(/colectoras,
{
cantidad: quantity,
idModelo: operativeModelId,
idRampa: rampId,
idSector: operativeSectorId,
idUnidad: unitWorkId,
sucursal: branchId,
usuario: userLogin
},
{
headers: {
'Access-Control-Allow-Origin': Config.get('apiOperacinesUrl'),
'Accept': 'application/json',
'Content-Type': 'application/json; charset=UTF-8'
}
}).then(response => response)
.catch(error => error);

```js
See above...
```

#### Expected behavior, if applicable
I hope receive an StatusCode with code 200 or error code, for example 409, but I receive the next message:

Error: Network Error
at createError (createError.js:17)
at XMLHttpRequest.handleError (xhr.js:80)

But if I call to the API from Postman, for example, I receive the next result:

{
"type": "about:blank",
"title": "Error al crear colectoras",
"status": 409,
"detail": " La unidad de trabajo BEN_OTROS ya tiene la colectora creada (en sucursal 1)."
}

#### Environment
 - Axios Version 0.19.0
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 87.0.4280.88 (Build oficial) (64 bits)
 - Node.js Version v13.12.0
 - Windows 10 Pro 64 bits
 - Additional Library Versions React.JS Version 16.8.0

#### Additional context/Screenshots
The API called, use the a Carter Module, for manage the HTTP call.

**Comment by chinesedfan** [comment]
Please paste full errors screeshot and your Postman configurations.

I think you may not call axios correctly, because I see `Access-Control-Allow-Origin` in headers, which is a kind of response headers, instead of request headers. See more about CORS in [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios#nightmares-of-headers-cors-cookies-and-auth).

**Comment by jochercoles** [comment]
Sorry Chinesedfan, I didn't saw your message. I paste the information that you ask to you.

Error return for the browser when I send the POST method Call.

POST http://10.20.7.144:15000/api/colectoras 409 (Conflict)

Error how to read Axios:

Error: Request failed with status code 409
    at createError (createError.js:17)
    at settle (settle.js:19)
    at XMLHttpRequest.handleLoad (xhr.js:60)

While the 409 status code can be read in the error text, I cannot get a property with the status code. I removed the line with the sentence Access-Control-Allow-Origin from headers, and I receive the same error.

The Postman Configurations:

Post: http://10.20.7.144:15000/api/colectoras

Content-Type  |  application/json
Accept             |  application/json

Return:

{
    "type": "about:blank",
    "title": "Error when verify user",
    "status": 409,
    "detail": " ... "
}

Thank you for your time.

Regards.

Javier.

**Comment by chinesedfan** [comment]
Did you see some error message like "been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present" in your browser console? See #1760.

Note that Postman will not have the CORS problem.

**Comment by jochercoles** [comment]
Thank you @chinesedfan for your anwser. I don't have any message as you show. Another hand, for other error, I asked to the API Developer, that he add the CORS policy manage. And I see that the same call to POST method from Postman, It haven't got any problem.

Thank, so much.

**Comment by jchercoles** [comment]
Sorry, but what is the reason, for close the issue, because I don't have a solution.

Thank.

**Comment by chinesedfan** [comment]
Seems that I misunderstood that you have solved your problem by asking the API developer to add CORS policy.

How about trying to set `validateStatus`?

```
axios('http://httpstat.us/409', { validateStatus() { return true } })
  .then(res => console.log('then:', JSON.stringify(res.data, null, 4)))
  .catch(err => console.log('error', err.response.data));

// Output:

// then: {
//     "code": 409,
//     "description": "Conflict"
// }
```

**Comment by jchercoles** [comment]
Thanks @chinesedfan, don't worry. Not for this issue, I asked my partner to add the CORS policy for another problem.

The encoding you send me, where should I write?

Thank you, newly.

Regards.

Javier.
