### ISSUE TITLE
When the version-0.21.1 that has fixed SSRF vulnerability will be released? plz && thanks

### ISSUE THREAD

**Issue by Hibop** [axios/axios#3494]
#### Describe the issue
A clear and concise description of what the issue is.

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by shwao** [comment]
I am not a maintainer but i just came across this issue and wanted to say that it had been released yesterday.

**Comment by chinesedfan** [comment]
Yes, 0.21.1 has been released. If met problems, feel free to open a new issue.
