### ISSUE TITLE
Synchronous and asynchronous control in axios?

### ISSUE THREAD

**Issue by brizer** [axios/axios#3498]
#### Describe the issue

https://github.com/axios/axios/blob/59ab559386273a185be18857a12ab0305b753e50/lib/adapters/xhr.js#L31   

Why do the synchronous and asynchronous control parameters have to be fixed to true here？ How can I set the interface to be synchronized when using axios.
Some browser will block me, if I redirect a url after a ajax and open a new tab. How can I solve this problem. My solution is set ajax to synchronous, but I can not now.

Is there any suggestions?

#### Example Code
https://github.com/axios/axios/blob/59ab559386273a185be18857a12ab0305b753e50/lib/adapters/xhr.js#L31   

```js
// Example code here
```

#### Expected behavior, if applicable
Can support synchronous ajax.

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by zycgit** [comment]
I have the same problem.

I want to set up a global configuration that will be synchronized when the application is first loaded.

I don't want to execute any code until  this global configuration wille be loaded.

that I can use these global configuration  just like a json map

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
