### ISSUE TITLE
A website for axios

### ISSUE THREAD

**Issue by codemaster138** [axios/axios#3505]
#### Is your feature request related to a problem? Please describe.
No.

#### Describe the solution you'd like
–

#### Describe alternatives you've considered
–

#### Additional context
I've been using Axios for a while now (and I love it!! 😻 ), but one thing that has always bugged me is that there is no website...

Almost all of the big open source projects these days have a website – not only is it a way for potential users to find the product but I personally also just find it really cool when a great project has a great website.

Also, a website would allow for more structured documentation: Axios’ long README could be broken up into multiple pages that can be navigated via a side navigation bar.

🚀 I have already started building the website. Because I didn't know what colors to use, I took the liberty of choosing a temporary palette 🎨:

![axios_colors](https://user-images.githubusercontent.com/43313420/103296400-50b8c180-49f6-11eb-93da-18280365ad14.png)

Also, because there has been no official winner of the  [logo contest](https://github.com/axios/axios/issues/2130) (If anyone ever wins the logo contest, I'll happily patch it into this website and update the colors to match), I made a couple of logos (The one I chose is marked in the primary color):

<img width="413" alt="axios_logos" src="https://user-images.githubusercontent.com/43313420/103296551-970e2080-49f6-11eb-9e6a-00351d142ee2.png">

My preliminary website design currently looks like this (check the live demo site at [axios-demo.surge.sh](https://axios-demo.surge.sh)):

![axios_website](https://user-images.githubusercontent.com/43313420/103300426-20295580-49ff-11eb-8dda-ca8742af2261.png)

A documentation page looks like this:
<img width="1440" alt="Documentation Page" src="https://user-images.githubusercontent.com/43313420/103309461-6b4e6300-4a15-11eb-9c2d-b8aa3671bb4b.png">

💬 I'd love to discuss this with the community, **_especially the maintainers 🧑‍💻_**, and receive a bit of guidance on the Axios brand & logo.

**Comment by jasonsaayman** [comment]
Cool, I like it, we were going to work on a site for Axios but I have not been able to get to that as I have been more involved with getting releases created.  We have a domain axios-http.com, can you share the source with me when you have some time? Also why type of hosting is required?

**Comment by codemaster138** [comment]
@jasonsaayman Hey! The source code is currently uploaded here: [codemaster138/axios-site](https://github.com/codemaster138/axios-site). Any static hosting (like github pages) will suffice since the website uses a very simple static site generator.

**Comment by codemaster138** [comment]
@jasonsaayman Another thing I was thinking of was to maybe have a "who's using it" section on the homepage – after all axios is quite a popular framework. I was wondering if you maybe knew some fairly popular projects using axios?

**Comment by codemaster138** [comment]
@jasonsaayman Just one last thing: I was wondering whether you like the brand color scheme and logo I used for the website. In case you select another logo from the logo contest (#2130),  please let me know so I can update the website and maybe even the brand scheme to match the winner.

**Comment by fernandobelotto** [comment]
I loved the website codemaster138! i recently was thinking about creating a website for axios and you nailed!! if your proposal get accept and became oficial, i would love to translated to portuguese to brazilians folks

**Comment by jasonsaayman** [comment]
@codemaster138 thanks for the source, I will add you to a repo that is made for the axios website soon. As for translations would it be possible to easily translate the site as this is a very large need and I would love to get a couple of people who have mentioned an interest in translation working on that.

**Comment by codemaster138** [comment]
@jasonsaayman I might not have much time today, but as soon as I do I will build an i18n feature into the build tool.

As for using the site and assets you have my full permission!

**Comment by codemaster138** [comment]
@jasonsaayman btw make sure to replace the Lorem Ipsum on the landing page with something more meaningful

**Comment by codemaster138** [comment]
@jasonsaayman @fernandobelotto Hi again! I finally got around to finishing up the website!

I changed up the website quite a bit, so now you'll need to serve from the public directory rather than the root.

I have added i18n features to my ["Inert"](https://github.com/codemaster138/inert) static site generator and created a German translation (I grew up bilingually) to test it out.

You'll have to update the `inert-cli` package (`sudo npm i -g inert-cli`) for it to work.

I haven't gotten around to writing proper documentation for the i18n features yet, so I'll just give you a brief overview of how to add a translation here:

### Translating the Website
The first thing you'll have to do is go to the file `inert.config.js` and find the field `i18n.languages`. There, add your language configuration:
```js
  ...
  i18n: {
    languages: {
      '<language-code>': {
        name: '(What do you call the language in that language? E.g. `Deutsch` for German)',
        primaryName: '(What do you call that language in English? E.g. German)',
        path: 'E.g. /de for German',
        sidebar: <The translated sidebar (Make sure to update the link paths!)>
      }
    }
    ...
  }
  ...
```

Now, locate the field `build.templates` and add a field named `home-<language-shortcut>` (where *language-shortcut* is the key you used in the i18n object). Set this property to `./templates/home-<language-shortcut>.ejs`.

Next, go to the templates directory and create a file with that name (`home-<language-shortcut>.ejs`). Copy everything from `home.ejs` or `home-de.ejs` and translate it. Also, make sure to add your language to the details tag in the header in all the other `home-... .ejs` files.

#### Translating the docs
To translate the docs, create a copy of the folder `posts/de` and rename it to `posts/<language-shortcut>`. Inside of that folder, translate each post to your language.

I hope that's a good enough summary for now, if you need help just respond to this issue and mention me (@codemaster138 ).

**Comment by codemaster138** [comment]
@jasonsaayman Hope I'm not bugging you but how is it looking in terms of making this site official? I see that the domain is still just serving namecheap's ads

**Comment by jasonsaayman** [comment]
@codemaster138 I will get to this probably tomorrow, thanks for all the hard work. I will stop by and update this when I do the deployment.

**Comment by codemaster138** [comment]
@jasonsaayman Hey, haven’t heard from you in a while and it looks like the website still isn’t up... Is this still happening?

**Comment by jasonsaayman** [comment]
Hi @codemaster138,

I did start with this sorry man I have been a bit busy, but I will try get it completed over this next week.

Thanks

**Comment by codemaster138** [comment]
@jasonsaayman That's great, thanks

**Comment by jasonsaayman** [comment]
Hi @codemaster138 

I wanted to keep you posted I deployed the site tonight, the name servers should update in 48 hours.

Thanks

**Comment by jasonsaayman** [comment]
@codemaster138 the site is now online, you can see it here https://axios-http.com/. I am going to make some updates to the repo with new text etc, would it be possible once I am done to translate that for us?

In addition, there is one small styling thing that I would like to look at with you in the future if that is possible? It is very small.

**Comment by codemaster138** [comment]
@jasonsaayman Hi, cool that you finally got a chance to finish up the website! Just tell me when you‘re done changing the content and I‘ll update the website.

I‘d be interested to know what your styling issue is, so maybe it‘s best if you can create an issue on the website‘s repo and we’ll discuss it there...

**Comment by codemaster138** [comment]
Since we have the website set up now, I'm closing this issue. Any further discussions regarding the axios website should be held over on the website's repo: [axios/axios-docs](https://github.com/axios/axios-docs)
