### ISSUE TITLE
The irrelevant error returned when requesting illegal URL

### ISSUE THREAD

**Issue by markb-trustifi** [axios/axios#3509]
#### Describe the bug
The irrelevant error returned when requesting illegal URL, like: "tel:484-695-3408"
```
TypeError: Cannot read property 'replace' of null
    at dispatchHttpRequest (node_modules/axios/lib/adapters/http.js:109:74)
    at new Promise (<anonymous>)
    at httpAdapter (node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:52:10)
```

#### To Reproduce
```js
axios.get('tel:484-695-3408').catch(err => console.error(err));
```

#### Expected behavior
Return descriptive error, like "Unsupported protocol tel:"

#### Environment
 - Axios Version: 0.21.1
 - Adapter: HTTP
 - Browser: none
 - Browser Version: none
 - Node.js Version: 12.19.0
 - OS: MacOS 10.14
 - Additional Library Versions: none

#### Additional context/Screenshots
none

**Comment by Saurabh1901** [comment]
@markb-trustifi  Can I work on this?

**Comment by markb-trustifi** [comment]
@Saurabh1901 Sure, you can start working on this issue (if I understand your question correct).

**Comment by joaoGabriel55** [comment]
I will try to resolve this issue.

**Comment by joaoGabriel55** [comment]
I got this error message in chrome browser console:
![image](https://user-images.githubusercontent.com/23138717/104442667-262d4380-5574-11eb-85c7-c05b83996e4b.png)

**Comment by markb-trustifi** [comment]
@joaoGabriel55 I run the code in Node.js, so the Browser console is irrelevant here.

**Comment by joaoGabriel55** [comment]
Ok...

**Comment by joaoGabriel55** [comment]
I found your error

**Comment by joaoGabriel55** [comment]
Resolved, I will send a PR soon.
