### ISSUE TITLE
Error: timeout of 0ms exceeded

### ISSUE THREAD

**Issue by sandeepg1220** [axios/axios#3512]
#### Describe the bug
Getting Error: timeout of 0ms exceeded in android devices. But for iOS working fine. I'm using in react native.
Checked in Honor 8x, realme 3 pro devices. Tried in older version of axios 0.19.2 but same issue is getting.

#### To Reproduce
Try with post url using axios, it will return the error in catch saying that Error: timeout of 0ms exceeded] 

#### Expected behavior
It shoud not return error

#### Environment
Axios Version 0.21.1
React Native 0.62.1

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by sandeepg1220** [comment]
Sorry It's already reported. Closing now this issue

**Comment by severinbeauvais** [comment]
Link to already-reported bug please?

**Comment by ajmas** [comment]
See: https://github.com/axios/axios/issues/2103
