### ISSUE TITLE
The put method of axios cannot set the request header in ie11

### ISSUE THREAD

**Issue by CasualMing** [axios/axios#3514]
#### Describe the bug
Hello author

When I send a PUT request using an instance created with AXIOS, I need to dynamically set the content-Type of the request header
I have found.Settings are normal on the Google browser.But the Settings on IE11 were not successful

#### Expected behavior
The request header can be set normally

#### Environment
 - Axios Version 0.20.0
 - Adapter [e.g. XHR/HTTP]
 - Browseri [ie11]
 - Browser Version [ie11]
 - Node.js Version [v10.16.3]
 - OS: [window 10]
 - Additional Library Versions [vue 2.6.11, webpack 4.43.0, core-js 3.8.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/40878104/103405216-5565ad00-4b91-11eb-8cc4-4264368e2252.png)
![image](https://user-images.githubusercontent.com/40878104/103405237-67475000-4b91-11eb-963a-c710cb647c29.png)

**Comment by CasualMing** [comment]
I tried to reduce the version , found to be feasible, I reduced from 0.20.0 to 0.16.2 to solved this problem.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
