### ISSUE TITLE
Different response types in node and in browser for the same responseType property 'arraybuffer'

### ISSUE THREAD

**Issue by padzikm** [axios/axios#3517]
#### Describe the bug
Different response types in node and in browser for the same responseType property 'arraybuffer' - in nodejs response.data is Buffer, but in browser it is ArrayBuffer. This behaviour is confusing and not documented.
#### To Reproduce

Nodejs:
```js
var axios = require('axios');
function isUndefined(val) {
            return typeof val === 'undefined';
}

function isBuffer(val) {
            return val !== null && !isUndefined(val) && val.constructor !== null && !isUndefined(val.constructor)
                && typeof val.constructor.isBuffer === 'function' && val.constructor.isBuffer(val);
}

function isArrayBuffer(val) {
            return toString.call(val) === '[object ArrayBuffer]';
}
var c = { responseType: 'arraybuffer' }
axios.get('https://jsonplaceholder.typicode.com/todos/1', c).then(res => console.log(isArrayBuffer(res.data))).catch(ex => console.log(ex));
axios.get('https://jsonplaceholder.typicode.com/todos/1', c).then(res => console.log(isBuffer(res.data))).catch(ex => console.log(ex));
```

Browser:
```js
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Buffer test</title>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
        function isUndefined(val) {
            return typeof val === 'undefined';
        }

        function isBuffer(val) {
            return val !== null && !isUndefined(val) && val.constructor !== null && !isUndefined(val.constructor)
                && typeof val.constructor.isBuffer === 'function' && val.constructor.isBuffer(val);
        }

        function isArrayBuffer(val) {
            return toString.call(val) === '[object ArrayBuffer]';
        }
        var c = { responseType: 'arraybuffer' }
        axios.get('https://jsonplaceholder.typicode.com/todos/1', c).then(res => console.log(isArrayBuffer(res.data))).catch(ex => console.log(ex));
        axios.get('https://jsonplaceholder.typicode.com/todos/1', c).then(res => console.log(isBuffer(res.data))).catch(ex => console.log(ex));
    </script>
</body>
</html>
```

#### Expected behavior
Both response types should be ArrayBuffer

#### Environment
 - Axios Version 0.19.2
 - Node.js Version 14.12.0

#### Additional context/Screenshots
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data

**Comment by buyan302** [comment]
I dont think it is necessary to keep `arraybuffer` response data storing as `ArrayBuffer` in node.

`ArrayBuffer` is a readonly memory structure, on the contrary, `Buffer` is more flexible and efficient in processing memory.

**Comment by padzikm** [comment]
It may be, but this difference is confusing and it isn't documented

**Comment by jimmywarting** [comment]
This baffled me as well, so weird and inconsistent. I expected to get a ArrayBuffer back when i typed responseType=arraybuffer 

> I dont think it is necessary to keep `arraybuffer` response data storing as `ArrayBuffer` in node.

disagree 

> `ArrayBuffer` is a readonly memory structure, on the contrary, `Buffer` is more flexible and efficient in processing memory.

I discourage any use of buffer as it's a bloated NodeJS feature only and don't sit well for any cross compatible code for deno or the browser, i removed `res.buffer()` from the node-fetch as it was not part of the spec and it only made ppl more reliant on node:buffer i actually think it's better to use DataView and typedarrays instead. 

NodeJS core are actively discussing to use Uint8Array for all there internal api's instead of relying on Buffer... they are actually even thinking of hopfully one day depricating buffer, but that day is never going to happen, it can only be seen as a legacy thing and become discouraged

**Comment by jimmywarting** [comment]
found something else that bother me...

even doe i explicit said to return the response as text, axios keeps changing it to json either way...

```js
axios = await import('https://jspm.dev/axios')
res = await axios.default('https://httpbin.org/get', { responseType: 'text' })
console.log(typeof res.data === 'string') // false
```

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by DmitryUlyanov** [comment]
> Please could you retry with the latest version and open a new issue should this error still be relevant?

Tried 1.5.0, it's still the same: types in Node and on web are different, it's really inconvenient for some operations with the buffers, e.g. type conversion: 
```js
  return axios.get<number[]>(url, { responseType: 'arraybuffer' }).then((response) => {
    return new Uint16Array(response.data);
  });
```
behaves differently with Node (where it just casts the type) and web (where it actually tries to read the same memory blob but with a different type thus changing the size of the array appropriately).
