### ISSUE TITLE
always executed method should be "finally"

### ISSUE THREAD

**Issue by orcuntuna** [axios/axios#3518]
#### Section/Content To Improve

https://github.com/axios/axios/blob/master/README.md (Line of 122 & 132)

#### Suggested Improvement
always executed method should not be "then". should be "finally".

#### Relevant File(s)

https://github.com/axios/axios/blob/master/README.md

**Comment by jasonsaayman** [comment]
Hi,

Have you checked to see if the use of finally is actually compatible with the change that you are wanting to make to the readme?

**Comment by orcuntuna** [comment]
> Hi,
> 
> Have you checked to see if the use of finally is actually compatible with the change that you are wanting to make to the readme?

Hi,

I have check finally and then in my workspace. They same functions but finally is standart use this way on MDN. AxiosPromise returns AxiosResponse. This have'nt consecutive promises.

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios/pull/2683.
