### ISSUE TITLE
Be able to use http adapter in browser for electron

### ISSUE THREAD

**Issue by killpowa** [axios/axios#3520]
#### Describe the issue
When using axios in electron's renderer window, the xhr adapter will be used no matter what, because of https://github.com/axios/axios/blob/master/package.json#L68. There must be a way to override that without the need of forking this repo...

**Comment by m4heshd** [comment]
To anybody still having this issue with Webpack, use the following in Webpack configuration.

```js
resolve: {
    aliasFields: []
}
```

This will make Webpack ignore the [`browser`](https://github.com/axios/axios/blob/6b4fd93e6886c281ef1a51fca556616ce17f8fba/package.json#L71) field from `package.json`. This in combination with the following should work.


```js
const axios = require('axios');
axios.defaults.adapter = require("axios/lib/adapters/http");
```

This is the proper solution for #552, #2232
