### ISSUE TITLE
Set/switch new 'Authorization' header per request needs - accessTokens

### ISSUE THREAD

**Issue by Tzvetelin88** [axios/axios#3528]
#### Describe the issue
Need to set new 'Authorization' header per request needs. Different REST API endpoints can have different accessKey in 'Authorization' header. How can I set 'Authorization' per request needs?
I'm using React with Redux Saga, where I dispatch different Actions. Some of the actions hitting different  endpoint for which I need to set respective Authorization header.

#### Example Code
Axios Global Setup plus some dispatch axios

```js
// Axios Global Setup

export default function setupAxios(axios, store) {
  axios.interceptors.request.use(
    config => {

      const {
        newauth: { accessToken }
      } = store.getState();

      if (accessToken) {
        config.headers.Authorization = accessToken;
      }

      //Variable
      config.headers["Ocp-Apim-Subscription-Key"] = process.env.REACT_APP_API_SUBSCRIPTION_KEY

      return config;
    },
    err => Promise.reject(err)
  );
}

//Dispatch some actions requests
// create issue
export function createIssue(issueMessage, files) {
  return axios.post(CREATE_ISSUE_URL, { issueMessage, files }, configAppJsonMime);
}

// get user from AD
export function peoplePickerAD(personSearchAD) {
  return axios.get(AD_PICKER_PEOPLE, {personSearchAD}`);
}
```

#### Expected behavior, if applicable
Use axios to set new headers, create ne instance or create custom component to handle that.

#### Environment
 - Axios Version [e.g. 0.20.0]
 - Adapter [e.g. HTTP]
 - Browser [e.g. Chrome]
 - Browser Version [e.g. 87.0.4]
 - Node.js Version [e.g. 12.0.8]
 - Additional Library Versions [React 16.12]

#### Additional context/Screenshots
When setup axios globally first request is ok 'createIssue', but when execute second one 'peoplePickerAD' I need to set new 'Authorization'. What is the best way to set/switch different axios headers depend on request needs?

**Comment by Tzvetelin88** [comment]
The way that I have found is to create new instance and provide the new accessToken:

```
const instance = axios.create({
    headers: {
      common: {
        'Authorization': accessToken,
      }
    }
  });

  return instance.get(`GRAPH_TO_ASK,{personSearchAD}`);
```
I can create custom component and use axios.create, where before executing GET, POST, etc requests I can pass configuration headers and then return instance.get for example. Is this a good way to do it? Any recommendation? Thanks!

**Comment by jbuhacoff** [comment]
You can set per-request headers without creating a separate instance:

```
axios.get('https://example.com', { headers: { Authorization: accessToken } });
axios.post('https://example.com', input, { headers: { Authorization: accessToken } });
```

The last argument is the per-request configuration. It looks like you're already using this in your own example with `configAppJsonMime`, so you can add the `headers` field to that object for the POST request, or you can do something like this to just add the Authorization header to what you already have:

```
axios.post('https://example.com', input, { headers: { ...configAppJsonMime, Authorization: accessToken } });
```

**Comment by jbuhacoff** [comment]
If you want to do an automatic lookup based on the request URL, you could use an [axios interceptor](https://github.com/axios/axios#interceptors) to set the authorization header.

**Comment by Tzvetelin88** [comment]
I'm using React with Redux and Saga. I do not dispatch tokens to Actions and pass them to the functions like:
```axios.get('https://example.com', { headers: { Authorization: accessToken } });```
I set tokens per request in HOC component setupAxios which looks like this:

```
import store from "./store";
import axios from "axios";


export default function setupAxios(customToken) {
  const instance = axios.create();

  instance.interceptors.request.use(
    config => {

      if (customToken === 'accessTokenMGT') {
        const { newauth: { accessTokenMGT } } = store.getState();
        if (accessTokenMGT) {
          config.headers.Authorization = accessTokenMGT;
        }
      } else {
        const {
          newauth: { accessToken }
        } = store.getState();

        if (accessToken) {
          config.headers.Authorization = accessToken;
        }
      }

      config.headers["Ocp-Apim-Subscription-Key"] = process.env.REACT_APP_API_SUBSCRIPTION_KEY

      return config;
    },
    err => Promise.reject(err)
  );

  return instance;
}
```

if I have customToken, I then look for it in the store and set it, if not use standard one. Not sure, but I think I don't need to create new  instance 
```const instance = axios.create();``` 
every time, but will test it.
Any recommendations with this approach?

**Comment by jbuhacoff** [comment]
Try [StackOverflow](https://stackoverflow.com) or [CodeMentor](https://www.codementor.io/) because it looks like the issues you are facing are not related to Axios or its documentation.
