### ISSUE TITLE
Security Warning Npm - Axios

### ISSUE THREAD

**Issue by guillaumearnx** [axios/axios#3530]
#### Describe the bug
Hello, I have this error with axios since this afternoon when I have not updated it. Is that normal?

#### To Reproduce

```js
npm audit
```

#### Expected behavior
even when i run **npm audit fix** i still have this error

#### Environment
 - Axios Version [e.g. 0.21.1]

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/37373941/103937981-df7dba80-5129-11eb-8221-2ac6c81ebf16.png)

**Comment by srslafazan** [comment]
+1

**Comment by mike247** [comment]
A bunch of our dependencies use Axios and also report this problem

**Comment by KikelDmitry** [comment]
+1

**Comment by naseem-opal** [comment]
I had a bunch of breaking changes introduced as this command upgraded me from 19.1 to 21.1 and I don't see updates in the migration guide.

**Comment by AlAyoub** [comment]
The vulnerability is present in versions 0.10.0 to 0.21.1. I like many others have several projects that rely on Axios, I am hoping that there will be a fix here soon for this issue.

**Comment by buyan302** [comment]
![image](https://user-images.githubusercontent.com/73812919/104551105-324afb00-5671-11eb-8af2-4e5e9b432607.png)

Seems like 0.21.1 has resolved this problem.

**Comment by kevinlandsberg** [comment]
> ![image](https://user-images.githubusercontent.com/73812919/104551105-324afb00-5671-11eb-8af2-4e5e9b432607.png)
> 
> Seems like 0.21.1 has resolved this problem. Make sure you have upgrade axios to 0.21.1.

Did not work for me, still audit issues...

 High            Server-Side Request Forgery

  Package         axios

  Dependency of   webpack-cli [dev]

  Path            webpack-cli > @webpack-cli/init > @webpack-cli/generators >
                  @webpack-cli/utils > yeoman-environment > npm-api >
                  paged-request > axios

  More info       https://npmjs.com/advisories/1594




  High            Server-Side Request Forgery

  Package         axios

  Dependency of   webpack-cli [dev]

  Path            webpack-cli > @webpack-cli/init > @webpack-cli/utils >
                  yeoman-environment > npm-api > paged-request > axios

  More info       https://npmjs.com/advisories/1594




  High            Server-Side Request Forgery

  Package         axios

  Dependency of   webpack-cli [dev]

  Path            webpack-cli > @webpack-cli/init > @webpack-cli/generators >
                  @webpack-cli/utils > yeoman-generator > yeoman-environment >
                  npm-api > paged-request > axios

  More info       https://npmjs.com/advisories/1594




  High            Server-Side Request Forgery

  Package         axios

  Dependency of   webpack-cli [dev]

  Path            webpack-cli > @webpack-cli/init > @webpack-cli/utils >
                  yeoman-generator > yeoman-environment > npm-api >
                  paged-request > axios

  More info       https://npmjs.com/advisories/1594




  High            Server-Side Request Forgery

  Package         axios

  Dependency of   webpack-cli [dev]

  Path            webpack-cli > @webpack-cli/init > @webpack-cli/generators >
                  yeoman-generator > yeoman-environment > npm-api >
                  paged-request > axios

  More info       https://npmjs.com/advisories/1594




  High            Server-Side Request Forgery

  Package         axios

  Dependency of   webpack-cli [dev]

  Path            webpack-cli > @webpack-cli/init > @webpack-cli/generators >
                  yeoman-environment > npm-api > paged-request > axios

  More info       https://npmjs.com/advisories/1594

**Comment by guillaumearnx** [comment]
Resolved in 0.21.1 for me

**Comment by sharq88** [comment]
@guillaumearnx can you share some info on how did you resolve this? I have 0.21.1 in my package.json and I get the same error, despite I tried to `rm -rf ./node_modules` and `npm install`. Thanks.
