### ISSUE TITLE
adding axios to vue by gulp

### ISSUE THREAD

**Issue by romanown** [axios/axios#3533]
#### Describe the issue
i can not include axios in my project. axios is undefined

#### Example Code
Code snippet to illustrate your question

```js
const gulp = require('gulp');
const concat = require('gulp-concat');
const terser = require('gulp-terser');
let jsPaths = ['js/vue.js', 'js/vue-router.js', 	'js/axios.js', 'js/vueapp.js',];
gulp.task('js', () => {return	gulp.src(jsPaths).pipe(concat('file.js',
 {newLine: ';'})).pipe(terser())	.pipe(gulp.dest('../dist'));});

in js\vueapp.js i to try many variants from this

const axios = require('axios').default;
import axios from 'axios';
const axios = new axios()
const axios = axios

more include in js\vueapp.js the code

const router = new VueRouter({
    mode: 'history',
    routes
})
var vue = new Vue({
    router,
    el: '#vueapp_list',
    template: '#listTemplatevue',

    data: {
        currentView: "mainPage",
}
)}

```

#### Expected behavior, if applicable
i also installed its with npm
npm install --save axios
but axios is undefined every way

#### Environment
 - Axios Version0.21.0
 - Adapter XHR/HTTP
 - Browser Firefox
 - Browser Version 87
 - Node.js Version 14.0.1
 - OS: Win 10
 - Additional Library Versions jQuery

#### Additional context/Screenshots
any way to adding the axios to the project is axios not defined.

**Comment by chinesedfan** [comment]
Can you share your project or sample repository? It must be something wrong in your build script.

**Comment by romanown** [comment]
const gulp = require('gulp');
const concat = require('gulp-concat');
const terser = require('gulp-terser');
let jsPaths = ['js/vue.js', 'js/vue-router.js', 	'js/axios.js', 'js/vueapp.js',];
gulp.task('js', () => {return	
gulp.src(jsPaths).pipe(concat('file.js',
 {newLine: ';'})).pipe(terser())	
.pipe(gulp.dest('../dist'));});
