### ISSUE TITLE
Ability to specify ciphers suites to use for a TLS connection

### ISSUE THREAD

**Issue by labelex** [axios/axios#3537]
#### Is your feature request related to a problem? Please describe.
My request is related to a problem since I am trying to establish a connection to a host that blocks my request for not using a specific TLS 1.3 cipher.

#### Describe the solution you'd like
I suggest to add an option to choose which cipher suites to use for a TLS connection. For example if we would like a TLS 1.3 connection to be limited to support only the following ciphers:

TLS_AES_256_GCM_SHA384
TLS_AES_128_GCM_SHA256
TLS_AES_128_CCM_8_SHA256

we could have something like:
{ciphersList: "TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_8_SHA256"}

#### Describe alternatives you've considered
I cannot think of any alternative solutions because the problem is very specific.

#### Additional context
An example of what curl offers related to ciphers:
https://curl.se/docs/ssl-ciphers.html

**Comment by bologer** [comment]
@jasonsaayman this issue is marked as completed. Can you please share release or MR where it was complete or resolved?
