### ISSUE TITLE
react-native android axios 0.21.1 , file upload multipart/form-data always "network error"

### ISSUE THREAD

**Issue by bisanedev** [axios/axios#3540]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
var formData = new FormData();       
    formData.append('nama', judul);  
    formData.append('mapel', mapel ); 
    formData.append('kelas', kelas);
    formData.append('file', {
      name: namePDF,
      uri: urlPDF, 
      type: "application/pdf" 
    });    
    axios({
        method: 'post',
        url: global.Server +'/api/pengajar/buku',
        data: formData,
        headers:{
          "Accept": "application/json",
          "Content-Type": "multipart/form-data",
        }     
      }).then(response => {
        if(response.data.status == true)
        { 
          if(imageURL === undefined) {
            //jika tidak ada foto
            this.setState({ isLoading:false },() => {this.params.onRefresh(),this.navigasi.navigate('bukuIndex')});
          }else{
            //upload foto            
            this.uploadCover(response.data.message.data);            
          }
        }
      }).catch(error => {
        console.log(error);
        if(error.message === "Network Error"){      
          this.setState({ isLoading:false },() => this.refs.toast.show("Jaringan Tidak Terhubung"));
        }  
        if(error.response.status == 401){
          this.setState({ isLoading:false },() => this.refs.toast.show(error.response.data.message));
        }
        if(error.response.status == 400){
          this.setState({ isLoading:false },() => this.refs.toast.show(error.response.data.message));
        }
    });
```

#### Environment
 - Axios Version [e.g. 0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Additional Library Versions [e.g. React 16.13.1, React Native 0.63.3]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by hbd225** [comment]
```
      for (const key of Object.keys(error)) {
        console.log(key)
        console.log(error[key])
      }
```
I had same error and find message `Could not retrieve file for uri`.
Please try above code then you can see more details.

**Comment by okhiroyuki** [comment]
I have the same problem with Vue-Cordova, I try to upload a file with multipart/form-data, but it always gives me Network Error.

**Comment by shenyuanqing** [comment]
I found debug had the same error,release seems ok.

**Comment by DuwalVC** [comment]
hi, i have the some problem
