### ISSUE TITLE
When I use post, the Request payload becomes [object, object]

### ISSUE THREAD

**Issue by chenyk2016** [axios/axios#3568]
#### Describe the bug
When I use post, the Request payload becomes [object, object], and the Request content-type becomes application/x-www-form-urlencoded.

And I realize that's because I set the TransformRequest property

#### To Reproduce

```js
import axios from 'axios'
const service = axios.create({
  transformRequest: []
})
service.post('test/1', { test1: '123' })
```

#### Expected behavior
post data working

#### Environment
 - Axios Version [0.21.1]
 - Node.js Version [12.6.1]

#### Additional context/Screenshots
The user's TransformRequest property changes his default behavior. when i delete  transformRequest property. it will work normally.

**Comment by genie-youn** [comment]
It seems to be an intended implementation; to send payloads normally, you need to modify them as follows:

```javascript
import axios from 'axios'
const service = axios.create({
  transformRequest: [...axios.defaults.transformRequest]
});
service.post("test/1", { test1: "123" });
```

You can also find the content in the document. (The last function in the array **must return** a `string` or an instance of `Buffer`, `ArrayBuffer`, `FormData` or `Stream`)
https://github.com/axios/axios/blob/master/README.md#request-config
```javascript
// `transformRequest` allows changes to the request data before it is sent to the server
// This is only applicable for request methods 'PUT', 'POST', 'PATCH' and 'DELETE'
// The last function in the array must return a string or an instance of Buffer, ArrayBuffer,
// FormData or Stream
// You may modify the headers object.
transformRequest: [function (data, headers) {
  // Do whatever you want to transform the data

  return data;
}],
```

**Comment by jasonsaayman** [comment]
Hi @genie-youn

I don't think this will work as this is an odd behavior to automatically merge defaults when you are creating a new instance as the new instance should be a fresh instance. I also don't think one should leave something like `transformRequest` empty, rather omit it completely.

Thanks

**Comment by James-CheetahD** [comment]
Also having issues with this following an attempt at getting up to latest version. POST requests that previously sent an array of records successfully now send [object, object] with no other changes being made.
