### ISSUE TITLE
mergeConfig.js may not be properly defaulting url anymore

### ISSUE THREAD

**Issue by chrishavekost** [axios/axios#3579]
#### Describe the issue
Since `axios@0.20.0-0` the `url` config parameter has stopped merging the default instance value if one exists. This question is similar to #3491 that was auto-closed.

It looks like duplication of the `url` key was addressed in [this comment](https://github.com/axios/axios/issues/2878#issuecomment-610269234), PR #2844, and 24b8ce3b1b636fb9a058d3710ee699a9157b7a3e

I am wondering if this change had an unintended side effect of not using the instance value if the passed in config does not contain a `url` key.

I believe that removing `url` from `valueFromConfig2Keys` and adding it to `defaultToConfig2Keys` in [mergeConfig.js](https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js#L18-L26) would solve this and not reintroduce the duplication mentioned before, but I'm not sure if that would have other unintended consequences.

#### Example Code

```js
const instance = axios.create({ url: 'https://someexample.com' });

instance.request({ method: 'GET', params: { foo: 'bar' } }); // after merge occurs, this config will not have a url key
```

#### Expected behavior, if applicable
The `url` should default to the passed in value, if one exists. If not, then the default should come from the instance's config.

#### Environment
 - Axios Version [^0.20.0-0]
 - Adapter [core]
 - Browser [N/A]
 - Browser Version [N/A]
 - Node.js Version [N/A]
 - OS: [N/A]
 - Additional Library Versions [N/A]

#### Additional context/Screenshots
Having to pass a `url` to `instance.request()` may be the desired behavior, but I wasn't sure where else to ask

Merging of `url` currently happens [here](https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js#L48-L52)

When `url` is not present, none of the other merges can add a `url` value from another config.

Moving `url` key to `defaultToConfig2Keys` should grab the value from the passed in config (current behavior) and merge from the default config when not found (past behavior) [here](https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js#L56-L62)

**Comment by chinesedfan** [comment]
Yes, it is working as expected, because we think `url`/`method`/`data` should always be set when final called. Old merging mechanism makes things hard to be tracked. See https://github.com/axios/axios/pull/1395#discussion_r179828155. But users complain about `params`, #2656 makes it inheritable.

If you have an instance example needs different configs with url/method/data, happy to hear about that and let's discuss.

**Comment by chrishavekost** [comment]
For my use case I am sending multiple requests to the same url/endpoint, the `data` and `method` may be different for each request, but `url` mainly stays the same. I think our solution in this case would be to configure the instance with a fully populated `baseURL` and then just modify that when necessary, since `baseURL` is part of `defaultToConfig2Keys` array.

Maybe after this line in the docs 

> The specified config will be merged with the instance config.

there can be a callout letting users know that `url`, `method`, and `data` (or any other keys added [here](https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js#L18)) are not considered part of the instance config, and so their values will not be inherited when calling `instance.request({})` ?

**Comment by chrishavekost** [comment]
Hi @chinesedfan, do you think my use case is valid or do you think `url` should not be merged into the instance config? I am happy to add a PR either way, even if it's just updating docs.

**Comment by chinesedfan** [comment]
Yes, your use case is reasonable, but we already have `config.baseURL`.

Merging mechnism is really the most frequent asked problem of axios and it changes among versions. I recorded them in [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios#config-defaults), and @jasonsaayman is planning to setup a new official document site. See https://github.com/axios/axios-docs/issues/5 to track and contribute.
