### ISSUE TITLE
How do I change axios User-Agent?

### ISSUE THREAD

**Issue by TharakaSl** [axios/axios#3583]
#### Describe the issue
I'm using the axios to call the APIs. In specific case I want to change the "User Agent" for request being made to the API. I got an error when setting the header 'Refused to set unsafe header "User-Agent"'.

#### Example Code
Code snippet to illustrate your question

```js
var params = {
     headers: {
         apikey: API_Key,
         muteHttpExceptions: true,
        'User-Agent': `save-excel/${addin_version}`
     }
};
var response: any = await axioConnectorInstance.post("/save", data, params);
```

#### Expected behavior, if applicable
I want to change the user agent

#### Environment
 - Axios Version 0.21.1
 - Browser Chrome
 - Browser Version 88.0.4324.104
 - React 16.8.2

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/13197882/105570108-2ea02e00-5d6d-11eb-8963-c75988d8bf6a.png)

**Comment by chinesedfan** [comment]
Sorry, this is a kind of browser limitations. See https://github.com/axios/axios/issues/1231#issuecomment-575158262.
