### ISSUE TITLE
destructuring response using interceptors doesn't work as expected

### ISSUE THREAD

**Issue by teofilp** [axios/axios#3589]
#### Describe the issue
A clear and concise description of what the issue is.
I added a response interceptor for my axios that destructures my response and returns the data as can be seen below.
![image](https://user-images.githubusercontent.com/30023610/105710832-51bf0f00-5f20-11eb-9ca8-15c358c00a0f.png)
Now i have a problem when making a request to the server and the server responds with a blob.
this is where the call is made:
![image](https://user-images.githubusercontent.com/30023610/105710846-57b4f000-5f20-11eb-98ad-3a00de5d4433.png)
now if i console log the response i get an empty object for the data
![image](https://user-images.githubusercontent.com/30023610/105710876-626f8500-5f20-11eb-9c55-0670f24f9a25.png)
but if i directly call get on the axios instance then my data looks as expected:
![image](https://user-images.githubusercontent.com/30023610/105710894-6ac7c000-5f20-11eb-8f94-3b6c4207e015.png)

#### Example Code
this is thee code used for making a request using axios without any interceptors
![image](https://user-images.githubusercontent.com/30023610/105710905-6e5b4700-5f20-11eb-8d9c-db09acc9d1c4.png)
and this is the result
![image](https://user-images.githubusercontent.com/30023610/105710982-9054c980-5f20-11eb-96b8-52d7d3af77cd.png)

#### Expected behavior, if applicable
now the expected behaviour is the one from the image above. My question is why i don't get the same result when destructuring the response using interceptors

#### Environment
 Axios Version ^0.21.1
 Browser Chrome
Operating system Windows 10
#### Additional context/Screenshots
none

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
