### ISSUE TITLE
How to bypass a page blocking Axios because it doesn't store cookies like a browser would

### ISSUE THREAD

**Issue by Meaxis** [axios/axios#3592]
#### Describe the issue
Hello!

Basically, I'm working with a website that requires setting a cookie on the client, otherwise, it just refuses to serve the request. (In other words: the website refuses to work if you block cookies)

How would I allow Axios to store cookies/to set cookies or to give the server the impression Axios is accepting its cookies?
Tried storing the Set-Cookie header in a variable and then sending it back on the next request, doesn't help.

Thanks in advance!
Meaxis

#### Example Code
Code snippet to illustrate your question

```js
axios.get('https://somewebsite.tld', settings)
	.then((result) => {
		// Here, I get the result's Set-Cookie header and send another request after having converted the cookies to a Cookie string. Yes, I've tested if the cookies are sent correctly on httpbin.org.
	})
	.catch((result) => {
		console.log('Error.')
	})
```

#### Expected behavior, if applicable
The website to send back a 200 OK along with some data.

#### Environment
 - Axios Version: 0.21.1
 - Adapter: HTTP
 - Browser: None (Using the Windows CMD)
 - Browser Version: N/A
 - Node.js Version: 10.15.3
 - OS: Windows 10 20H2

#### Additional context/Screenshots
Apologies if the answer is obvious, I'm not really an expert with HTTP requests. I rarely send HTTP requests that aren't basic Ajax GET requests.

**Comment by chinesedfan** [comment]
> Tried storing the Set-Cookie header in a variable and then sending it back on the next request, doesn't help.

> // Here, I get the result's Set-Cookie header and send another request after having converted the cookies to a Cookie string. Yes, I've tested if the cookies are sent correctly on httpbin.org.

Hope you can share more detailed codes if possible. Make sure you have seen same cookies in browser's network panel of the next request.

You can also try some library like https://github.com/3846masa/axios-cookiejar-support.

**Comment by Meaxis** [comment]
Hello!

The Cookiejar fixed my issue.

Thank you!
Meaxis
