### ISSUE TITLE
Axios with vuejs v3 - complaints of no import default

### ISSUE THREAD

**Issue by baradhili** [axios/axios#3596]
#### Describe the issue
A clear and concise description of what the issue is.
> import axios from 'axios'; 

results in vite throwing 

> Uncaught SyntaxError: import not found: default

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
import { createApp } from 'vue';
import TheContainer from './components/TheContainer.vue';
import axios from 'axios';

axios.defaults.baseURL = process.env.VUE_APP_API_URL;

const app = createApp({
    components: {
        TheContainer
    }
})
app.axios = axios;
app.$http = axios;
app.config.globalProperties.axios = axios;
app.config.globalProperties.$http = axios;
app.mount('#app');
```

#### Expected behavior, if applicable
code should build and run

#### Environment
 - Axios Version 0.21.1
 - Adapter HTTP
 - Browser Chrome/Firefox
 - Browser Version [e.g. 22]
 - Node.js Version v14.15.4
 - vite Version 2.0.0-beta.29
 - OS: Ubuntu 18.04
 - Additional Library Versions Vue 3.0.5

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

none

**Comment by baradhili** [comment]
BTW it seems hard to submit a report that doesn't get bot closed

**Comment by nurlansu** [comment]
Hey, @baradhili. It's a known issue. The problem is more likely on Vite.js side (see https://github.com/vitejs/vite/issues/174 and https://github.com/vitejs/vite/issues/162), but as it was pointed out in those issues, there wouldn't be any problem if axios published an ESM version (see https://github.com/axios/axios/issues/1879).
