### ISSUE TITLE
How do you get the response's body of a failed request? #3535

### ISSUE THREAD

**Issue by zachariapopcorn** [axios/axios#3601]
Describe the issue
Question basically is the title, how do you get the response's body of a request that failed with a status code 403, 400, 401, etc

Example Code
--

Expected behavior, if applicable
--

Environment
Axios Version: 0.21.0
Node.js Version: 12.6.0
OS: Windows 10 20H2
Additional context/Screenshots
--

**Comment by zachariapopcorn** [comment]
Bruh

**Comment by iranaahsanali** [comment]
Facing same issue!
