### ISSUE TITLE
response interceptor should have request infomation on error

### ISSUE THREAD

**Issue by phil294** [axios/axios#3606]
#### Describe the bug
This bugreport very similar to #315 which was implemented and fixed, however I think this is not solved yet. When the query params parsing process itself fails (before the request even started), the resulting error object does not contain request information, making it hard to debug, especially with as error reports.

#### To Reproduce
```js
axios.get("", {
  params: {
    someParam: new Date(undefined)
  }
}).catch((e) => {
  console.log(e);
})
```
Only prints
```
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at parseValue (buildURL.js:53)
    at Object.forEach (utils.js:219)
    at serialize (buildURL.js:51)
    at Object.forEach (utils.js:225)
    at buildURL (buildURL.js:38)
    at dispatchXhrRequest (xhr.js:45)
    at new Promise (<anonymous>)
    at xhrAdapter (xhr.js:13)
    at dispatchRequest (dispatchRequest.js:53)
```

#### Expected behavior
I would expect the error to have information about the request (uri, config, etc) just like when the error is thrown on server response error.

#### Environment
 - Axios Version 0.21.1
 - Adapter http
 - Browser chromium 
 - Browser Version 87.0.4280.141
 - Node.js Version 12.20.0
 - OS: Manjaro 20.2.1
 - Additional Library Versions none

#### Additional context/Screenshots
dont have any. – I dont think that omitting this category should result in the automatic closing of an issue :-/

Cheers

**Comment by jasonsaayman** [comment]
@phil294 please check the tests are failing

**Comment by phil294** [comment]
Thank you for tackling this @jasonsaayman :-) In my case unfortunately, this did not fix it because I'm using `axios.create` in a web app which apparently uses the `xhr` adapter, not the `http` one, and your fix only targets `http`, but there's also a buildURL in `xhr`. I don't know why there are two different ones and when which is used and if duplicating the logic here would be correct (?), but unless I made a mistake, this is not yet solved and should probably be reopened.
