### ISSUE TITLE
Some headers are ignored when following redirects

### ISSUE THREAD

**Issue by AcrylicShrimp** [axios/axios#3607]
#### Describe the issue
The axios is not sending some headers when following redirects, especially `Authorization` and `Content-Type`(maybe there are much more affecting headers). I don't have idea if it is intended, because I don't find any related informations on the docs.

#### Example Code
```js
const axios = require('axios');

(async () => {
	return await axios({
		method: 'post',
		url,					// an url that sends 301/302
		data: {},				// omitted
		headers: {
			Authorization: 'Bearer xxx',	// a header to be sent
		},
	});
})()
	.then(res => console.log(res.config))
	.catch(err => {
		console.error('ERR!');
		console.error(err.config);
	});
```

#### Expected behavior, if applicable
The `Authorization` header sent to the server when any redirection occurs.

#### Environment
 - Axios Version [0.21.1]
 - Adapter [HTTP]
 - Node.js Version [14.9.0]
 - OS: [OSX 11.1]

#### Additional context/Screenshots
If any redirection is not occurs, the headers are sent normally.

<img width="646" alt="스크린샷 2021-01-29 오후 1 50 35" src="https://user-images.githubusercontent.com/19178575/106233087-087d0100-6239-11eb-9b6d-049055ba6317.png">

But the headers are omitted if redirection occurs.

<img width="338" alt="스크린샷 2021-01-29 오후 1 51 54" src="https://user-images.githubusercontent.com/19178575/106233156-2d717400-6239-11eb-8c49-fe73b3ad1f49.png">

**Comment by speed-of-light** [comment]
reproduced here as well ...

**Comment by AcrylicShrimp** [comment]
Will it be fixed?

**Comment by alexisdurieux** [comment]
I believe from https://github.com/axios/axios/issues/2855 that it is the intended behaviour. However, I have myself the opposite issue in the browser.

**Comment by AcrylicShrimp** [comment]
Is this completed? I'm sorry bothering you, but could you let know it will fixed or you're going to won't fix it?

**Comment by jasonsaayman** [comment]
We won't be fixing it sorry about that, I would have added a reply but this is like a year old so did not think it would really be worth it.
