### ISSUE TITLE
.catch() function doesn't contain any data when server returns an error with object data

### ISSUE THREAD

**Issue by DvirH** [axios/axios#3624]
#### Describe the bug
I tried to catch an error that returns from my webserver with an object that describe the error details.
the chrome inspector network panel shows this information:
![image](https://user-images.githubusercontent.com/4377117/106899950-a1f75780-66fe-11eb-98e7-bf656213bf09.png)
and the following:
![image](https://user-images.githubusercontent.com/4377117/106900029-b4719100-66fe-11eb-85b8-6eb9151b8b48.png)

which is great. that exactly what should be.
but what would you expect to have on your catch object? the returned object, right?

```js
// Example code here
return axios.get(`${API_URL}/api/v1/document/${id}/${token}`)
            .then(res => console.log('response', res))
            .catch(err => console.log('err', err))

```

the console data:
![image](https://user-images.githubusercontent.com/4377117/106900202-e8e54d00-66fe-11eb-8044-059a59f03891.png)

#### Expected behavior
to get the returned object event if it's error. or at least to have the ability to get access into the object.

#### Environment
 - Axios Version [^0.21.1]
 - Browser [Chrome]
 - Browser Version [ 88.0.4324.104 (Official Build) (64-bit)]
 - OS: [Windows 10]
 - Additional Library Versions ["vue": "^3.0.0",]

**Comment by bosslay** [comment]
**disagreed**
