### ISSUE TITLE
Multiple file uploads fails but passing one of them is working.

### ISSUE THREAD

**Issue by senthil-kumaran** [axios/axios#3629]
#### Describe the bug
Uploading of multiple files produces empty array but referring one of the files or different single file is working fine.
#### To Reproduce
1) Using FormData object to append files.
2) Using axios API with data as FormData object.
3) This works fine when a single image is uploaded or one of the files alone is passed to axios data (ex- .files[1]). 

```js
This is my index.js:

const form = document.querySelector('.form')
if(form) {
    form.addEventListener('submit', e => {
        e.preventDefault()

        const formData = new FormData()
        formData.append('images', document.getElementById('file-upload').files)    // Line - 7 (console logged the element and it contains all the image files selected.) 
        
        addFiles(form)
    })
}


This is the module of axios API call:

import axios from 'axios'
export const addFiles = async data => {
    try {
        const res = await axios({
            method: 'POST',
            url: 'http://127.0.0.1:8000/api/v1/resources',
            data
        })

        if(res.data.status === 'success') {
            console.log('Files added')
        }  
    } catch(err) {
        console.log(err)
    }
}
```

#### Expected behavior
Note: I am using **multer** package for processing the images.

When using **Postman** for the request, there is no issue with multiple files(images), the issue arises when I use axios to hit my api.
When I upload multiple files and request via axios, the **req.files** have - [] in the multer's middleware. 
But when I send like **.files[0] instead of .files** in Line - 7 (index.js), the req.files have the specified indexed image.

Uploading of a single file as no issues, as the **req.file** contains the image.

#### Environment
 - Axios Version ["^0.21.0"]
 - Browser [e.g. Chrome, Mozilla firefox]
 - Browser Version [Chrome - 87.0.4280.141, firefox - 86.0b6]
 - Node.js Version [v14.15.0]
 - OS: [Windows - 10]

#### Additional context/Screenshots
Tried setting the headers of axios as mentioned in various posts but still not resolved.

**Comment by senthil-kumaran** [comment]
Tried few more ways still no luck on my side. Used the normal form post submission instead of Axios. Is anyone looking into this or any other information required from my side.

**Comment by Arunkutti** [comment]
@senthil-kumaran  instead of adding files directly to the form add it in an array and try like below
```

let productimages = [];

for (let i = 0; i < images.length; i++) {
    productimages.push(images[i]);
}
formData.append('productPhotos', productimages);
```

Have a great day

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
