### ISSUE TITLE
How can I make the data of a url more beautiful?

### ISSUE THREAD

**Issue by mehanalavimajd** [axios/axios#3632]
#### Describe the issue
I wanted to see a response of a url
But the code wasn't very clear 

#### Example Code
Code snippet to illustrate your question

```js
axios.get("www.example.com")
.then(res => {
console.log(res.data)
})
.catch(err => {
console.log(err)
})
```

#### Expected behavior, if applicable
I expected to see 
```html
<html>
<body>
</body>
</html>
```
But I saw : 
```html
<html><body></body></html>
```
So how can I make the data more beautiful?
#### Environment
 - Axios Version [0.21.1]
 - Adapter [HTTP]
 - Browser [Chrome]
 - Node.js Version [14.0.4]
 - OS: [windows 10]
#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mehanalavimajd** [comment]
No one will answer me ?¿?

**Comment by chinesedfan** [comment]
It's out of the scope of axios. You can search for HTML formatting packages, like [prettier](https://www.npmjs.com/package/prettier).
