### ISSUE TITLE
Upgrade guide is out dated 

### ISSUE THREAD

**Issue by halaei** [axios/axios#3633]
#### Section/Content To Improve
https://github.com/axios/axios/blob/master/UPGRADE_GUIDE.md

#### Suggested Improvement
There is no upgrade guide after 0.16. I wonder if the upgrade is really backward compatible.

#### Relevant File(s)
UPGRADE_GUIDE.md

**Comment by zimplexing** [comment]
Is there any update?

**Comment by jasonsaayman** [comment]
Very ture, I will make a new one for v1.x this will happen soon

**Comment by jasonsaayman** [comment]
Closing as i think this has been addressed
