### ISSUE TITLE
Axios Content-Type Inquiry

### ISSUE THREAD

**Issue by spencer741** [axios/axios#3634]
#### Describe the issue
I have some issues understanding how Axios handles Content-Type (when automatically detected and manually set) and what Axios does to body content regarding the content-type, if any. Note: Some of my questions may be a naivety of js (not my daily driver). I have seen some talk about this, but not in a completely conclusive way. Thank you for any provided information.

#### Example Code
First off, I am setting the Content-Type to `application/json` explicitly, as the request body content needs to be a valid json literal string. In this example, I am not passing an object, just a simple value.
```js
var data =  "test";
axios
  .post("some-endpoint", data, {
    headers: {
      "Content-Type": "application/json",
    },
  })
  .then((res) => {
    HandleRequestSuccess(res);
  })
  .catch((err) => {
    HandleRequestError(err);
  });
```
The resulting request payload is `test` with no wrapped quotes, so it is not a valid Json literal. 

I would have expected that the quotes would be in there... however this may be a misunderstanding of some js basics to begin with.

Even if I take out the var and wrap the quotes directly in the post call, the same result persists.
```
 .post("some-endpoint", "test", {
    headers: {
      "Content-Type": "application/json",
    },
```
It is only when I perform this action 
`var data = JSON.stringify("test");` before passing it to the post call that things work.

**I remember reading that Axios does some conversions underneath depending on the content type, however I am unsure what those are in these scenarios.** This is my main inquiry.

I apologize in advance for my naivety regarding this. I humbly thank anybody that can answer my questions :)

#### Expected behavior, if applicable
Covered above.

#### Environment
 - Axios Version [0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [Latest]
 - Node.js Version [Latest]
 - OS: [Catalina]

#### Additional context/Screenshots
Covered above.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
