### ISSUE TITLE
Inconsistent response when using POST request and stream response type #3636

### ISSUE THREAD

**Issue by imjordanxd** [axios/axios#3639]
#### Describe the issue
The response data type is not consistent when using the different axios APIs.

#### Example Code
Code snippet to illustrate your question

```js
// scenario 1
const response = await axios({
    url,
    responseType: "stream",
    method: "POST",
});

// scenario 2
const response = await axios.post(
    url,
    {
        responseType: "stream",
    }
);

// on the server
router.post('the end point', async (req, res) => {
    await util.promisify(stream.pipeline)(
        fs.createReadStream('path to a very large file'),
        res
    );
});
```

#### Expected behavior, if applicable
In scenario 1, the response is as expected (IncomingMesage). However, in scenario 2, the stream is buffered into memory as a string. In both scenarios, the response data should be `IncomingMessage`.

#### Environment
- Axios Version 0.19.2
- Adapter HTTP
- Node.js Version 12.18.3
- OSX 10.15.7

#### Additional context/Screenshots
No.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
