### ISSUE TITLE
Unable to send requestBody using the data property in an axios instance using axios.create function

### ISSUE THREAD

**Issue by mridboy96** [axios/axios#3642]
#### Describe the issue
I have been trying to perform a POST api call by creating an axios post instance using the axios.create function, but for some reason I am not able to add the requestBody using the data property. When I send a json object to the data property and make the API call, it results in a failure and when I check it the data property says undefined. Not sure as to where I am going wrong.

#### Example Code
```js
// Function definition for postAxiosInstance
function postAxiosInstance(requestData = {}) {
    console.log(requestData);
    return axios.create({
        baseURL: process.env.VUE_APP_AXIOS_BASE_URL,
        method: 'post',
        headers: { Authorization: window.$cookies.get('idToken') },
        data: requestData,
    });
}
// Function for making the api call which uses the axiosInstance. I am passing the requestData here dynamically
async function apiCall(requestData) {
    try {
        // API Call
        const restAPIResponse = await postAxiosInstance(requestData).post("/web/create/company");
        console.log(restAPIResponse);
        // Validations
        const resultStatus = restAPIResponse.data;

        if (restAPIResponse == null || restAPIResponse.data == null) return null;
        else if (resultStatus.data == null || resultStatus.result != 'success') return null;

        return restAPIResponse;
    } catch (apiError) {
        console.log(apiError);
        return apiError;
    }
}
```
#### Expected behavior, if applicable
the data property in axios.create must have the requestBody for the post API call. but instead it says undefined.

#### Environment
-Axios Version [0.21.1]
-Adapter [XHR/HTTP]
-Browser [Chrome]
-Additional Library Versions [VueJS 4.5.11]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Raviolux** [comment]
I have the exact same problem. When creating an axios instance, the data field is ignored.

**Comment by reddevil111296** [comment]
> I have the exact same problem. When creating an axios instance, the data field is ignored.

Any update on this? Were you able to figure it out ?

**Comment by sephiroth32** [comment]
the data field is ignored cause the merge is failing, so when you do the post the data is overwritten with an empty object instead of do a merge, if you are going to create a axios instance don't add the data field, instead add the data directly in the request, something like this:

`const restAPIResponse = await postAxiosInstance().post("/web/create/company", {
  data: requestData
})`

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
