### ISSUE TITLE
Axios issue with port 7070

### ISSUE THREAD

**Issue by maheshpatil95** [axios/axios#3652]
#### Describe the issue
I am using axios to request one url (url is same server from which i am hitting) but axios is giving error -> <Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27) > and this error is generated when my server port is 7070 other wise it work well with other port. i did not find any solution

#### Example Code
Code snippet to illustrate your question

```js
const express=require("express");
const axios = require('axios');
var app=express();
const port=7070
var server = app.listen(port);
console.log('Magic happens at http://localhost:' + port);
app.get('/', (req, res) => {
res.status(200).json({
Message: "Welcome to NewLMS server project !",
})
})
app.get('/test', (req, res) => {
res.status(200).json({
Message: "Welcome to Test API !",

})
})
setTimeout(()=>{
axios.get(http://localhost:${port}/,
).then(function (response) {
console.log("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",response.data);
axios.get(http://localhost:${port}/test,
).then(function (response) {
console.log("Test",response.data);
}).catch(error=>{
console.log("Test",error);
})
}).catch(error=>{
console.log("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",error);
})
},3000)
```

#### Expected behavior, if applicable
response from api 

#### Environment
 - Axios Version [0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [v12.18.2]
 - OS: [Windows 10]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by vembry** [comment]
hello @maheshpatil95
it works in my machine, 
- NodeJs v12.18.2
- Axios ^0.21.1
- Express ^4.17.1
- macOs(mojave)

with note: added backtick `` ` `` on axios' url part on given example 

changed url on axios request
```javascript
axios.get(http://localhost:${port}/,
//...
axios.get(http://localhost:${port}/test,
```
into
```javascript
axios.get(`http://localhost:${port}/`,
//...
axios.get(`http://localhost:${port}/test`,
```

![image](https://user-images.githubusercontent.com/22610742/109409687-61ba8a80-79c7-11eb-9f27-1d592d6d155f.png)
![image](https://user-images.githubusercontent.com/22610742/109409940-523c4100-79c9-11eb-8ac7-11de2b51dd52.png)
![image](https://user-images.githubusercontent.com/22610742/109409954-59fbe580-79c9-11eb-81d0-c5956f6a996b.png)

this a non-axios issue, most likely a os-internal service in your machine is using the port 7070 at that time
