### ISSUE TITLE
Axios is not calling 'onUploadProgress' for posted files.

### ISSUE THREAD

**Issue by popey456963** [axios/axios#3653]
#### Describe the issue
Axios is not calling 'onUploadProgress' for posted files.

#### Example Code
Code snippet to illustrate your question

```js
const data = new FormData()
data.append('upload', file)

axios.post('/upload', data, {
    onUploadProgress: (p) => {
        console.log(p)
    }
})
    .then(({ short }) => {
        console.log(short)
    })
```

#### Expected behavior, if applicable
I would expect 'onUploadProgress' to be called 

#### Environment
 - Axios Version [e.g. 0.18.0]: 0.21.1
 - Adapter [e.g. XHR/HTTP]: Unknown
 - Browser [e.g. Chrome, Safari]: Firefox
 - Browser Version [e.g. 22] 85.0.2
 - Node.js Version [e.g. 13.0.1] 14.15.4
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4] Windows 10
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0] React 17

#### Additional context/Screenshots
The call definitely works and uploads the file, I just never get an 'uploadProgress' notification.

![image](https://user-images.githubusercontent.com/1338129/108389239-61700180-7207-11eb-9075-bce83c8b5665.png)

**Comment by popey456963** [comment]
I changed nothing and it's now working.  I must be going crazy.

**Comment by chrisfong** [comment]
I'm having the same problem, but it's not magically solving itself...
