### ISSUE TITLE
Making post requests to a url path that ends with a html file doesn't set the custom headers in axios request

### ISSUE THREAD

**Issue by StefanZumberovic** [axios/axios#3656]
#### Describe the issue
Hello. This is my first time posting an issue, not just on axios, but anywhere in general. I've already went through the issues and the documentation, and couldn't find the answer to the issue.

Description: If I make a post request with axios, and the url contains a path to a html file e.g. https://some.domain.com:123/log.html, the custom header content-type 'application/x-www-form-urlencoded;charset=utf-8' isn't being set in the request.
#### Example Code
Code snippet to illustrate your question

```js
const params = new url.URLSearchParams({
      username: 'myUserName',
      password: 'myPassword',
    });
    const response = await axios({
      method: 'post',
      url: 'https://some.domain.com:123/log.html',
      data: params,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8',
      },
    });
```

#### Expected behavior, if applicable
When setting headers object to contain 'Content-Type' header, the Content-Type header is not present in the request. If however the /log.html part is removed from the url path, the 'Content-Type' header is correctly set in the request. We are working with an api that specifically states these requirements for url path and content-type.

#### Environment
 - Axios Version [0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Node.js Version [v12.19.0]
 - OS: [macOS Catalina v10.15.7]

#### Additional context/Screenshots
Headers object when making the request that contains /log.html in the path:

![image](https://user-images.githubusercontent.com/33104751/108534473-78335880-72da-11eb-9e40-968039fb135c.png)

Headers object when removing the /log.html in the path:
![image](https://user-images.githubusercontent.com/33104751/108534555-8e411900-72da-11eb-82cd-885f3f296436.png)

**Comment by chinesedfan** [comment]
Hi, where did you set the breakpoint to check headers? In fact, axios will never change Content-type by url, but will set if the data is URLSearchParams. See `transformRequest` in axios/lib/defaults.js.
