### ISSUE TITLE
Add info when request interceptor can throw error

### ISSUE THREAD

**Issue by Mikilll94** [axios/axios#3657]
#### Section/Content To Improve
https://github.com/axios/axios#interceptors

#### Suggested Improvement
Personally, I don't know any situation when request interceptor can throw error. That's why I don't understand why in the docs it is written: `// Do something with request error`

![Screenshot 2021-02-20 at 18 19 36](https://user-images.githubusercontent.com/17653648/108603442-3244c600-73a8-11eb-9a01-86d720d623de.png)

It would be nice to provide some example/explanation when request interceptor can throw error. If the request interceptor never throws error, then maybe this example should be updated?

#### Relevant File(s)
README.md

**Comment by codemaster138** [comment]
@Mikilll94 I am not sure exactly but I think that the error handler is in case axios fails to send the request.

**Comment by Mikilll94** [comment]
@codemaster138 
Ok, so please give me an example when "axios fails to send the request.". I can't find any.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
