### ISSUE TITLE
`params` and `paramsSerializer` config options are not available when using axios({method: 'get'...})

### ISSUE THREAD

**Issue by ahayes91** [axios/axios#3658]
#### Section/Content To Improve
https://github.com/axios/axios#request-config

#### Suggested Improvement
This section describes the config options, but I found that you _have_ to include search / query parameters on the end of the `url` option when using the axios API with `method: 'get'`. You _can_ use `params` with the GET request alias https://github.com/axios/axios#request-method-aliases but it doesn't work if you try this:

```
axios({
  url: '/myUrlWithoutSearchParams',
  method: 'get',
  params: {
    ID: 12345
  },
})
```

#### Relevant File(s)
README.md

**Comment by ahayes91** [comment]
Even better than a documentation update would be a feature request to enable those parameters when using the API this way 😁  but I'll leave that up to you guys to decide if it's worthwhile

**Comment by chinesedfan** [comment]
> but it doesn't work

Can you elaborate how you check? By browser network panel or which test url?

**Comment by ahayes91** [comment]
> > but it doesn't work
> 
> Can you elaborate how you check? By browser network panel or which test url?

Actually it looks like these _are_ working - if you use this codepen https://codepen.io/awb99/pen/zZgGRX with:

```
import qs from "https://cdn.skypack.dev/qs";

axios({ 
  method: 'get', 
  url: "https://jsonplaceholder.typicode.com/comments",
  params: {
      postId: [1,2,3]
    },
  paramsSerializer: params => {
    return qs.stringify(params)
  }
}).then....
```

It seems to work when you add / remove params. I have no idea why my implementation wasn't working, unless there's something funky going on with the internal service I was using... I'll try it again and reopen this ticket if I'm still having issues.
Thanks!
