### ISSUE TITLE
onDownloadProgress has progressEvent dont

### ISSUE THREAD

**Issue by cxytomo** [axios/axios#3661]
#### Describe the issue
onDownloadProgress has progressEvent doesn't present loaded and total properties

#### Example Code
Code snippet to illustrate your question

```js
request({
        url: '/api/v1/web/download',
        params: {
          id: row.id
        },
        method: 'get',
        responseType: 'blob',
        onDownloadProgress: function(progressEvent) {
          console.log(progressEvent)
        }
      }).then(res => {
        if (res !== undefined && res !== '') {
          saveFile(res, row.fileName)
        }
      }).finally(() => {
        row.loading = false
      })
```

#### Expected behavior, if applicable
console progressEvent properties with loaded and total

#### Environment
 - Axios Version [e.g. 0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome]
 - Browser Version [e.g. 88.0.4324.192]
 - Node.js Version [e.g. 14.10.0]
 - OS: [e.g.OSX 11.2.1 ]
 - Additional Library Versions [e.g. Vue 2.5.17]

#### Additional context/Screenshots
return event does not present loaded and total properties

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by cxytomo** [comment]
This issue can be close. My problem was caused by mockjs.
