### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: adapter is not a function. (In 'adapter(config)', 'adapter' is undefined)?

### ISSUE THREAD

**Issue by labike** [axios/axios#3666]
#### Describe the issue
Possible Unhandled Promise Rejection (id: 0): TypeError: adapter is not a function. (In 'adapter(config)', 'adapter' is undefined)?

when i request login api the error is:

Possible Unhandled Promise Rejection (id: 0): TypeError: adapter is not a function. (In 'adapter(config)', 'adapter' is undefined) dispatchRequest@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:126225:19 tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27056:16 http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27157:27 _callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30596:17 _callImmediatesPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30635:17 callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30852:33 __callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2736:35 http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2522:34 __guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2719:15 flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2521:21 flushedQueue@[native code] callFunctionReturnFlushedQueue@[native code]

when i not debugger mode and get this error, if is debugger mode running ok. i don't know where the error? please help me, thanks!

#### Example Code
axios config:

```js
import axios from 'axios';
import {getAccessToken} from './util'

const service = axios.create({
    baseURL: '/',
    timeout: 6000
})
var token;


service.interceptors.request.use(config => {
    token = getAccessToken()
    if (config.headers['Content-Type']) {
        console.log(config.headers['Content-Type'])
    } else {
        config.headers['Content-Type'] = 'application/x-www-form-urlencoded;charset=UTF-8'
    }
    config.headers['Authorization'] = `Bearer ${token}`
    return config
}, error => {
    return Promise.reject(error)
})

service.interceptors.response.use(response => {
    return response.data
}, error => {
    return Promise.reject(error)
})

export {service as axios}
```

request login api:
```js

const {code, message, data} = await login({phone, password})
setLoading(false)
if (code === 1) {
  saveAccessToken(data.access_token)
  ToastAndroid.showWithGravity(
    message,
    ToastAndroid.SHORT,
    ToastAndroid.CENTER
  )
  getInfo(data.access_token)
  navigation.navigate('Home');
} else {
  setErrortext(message)
  return
}
```

storage:
```js
const saveAccessToken = async (accessToken) => {
      try {
          await AsyncStorage.setItem('access_token', accessToken)
      } catch (error) {
          return error
      }
  }
```

#### Environment
 - Axios [0.21.1]
 - OS: [Android emulator]
 - React 16.13, React Native 0.63.4

#### Additional context/Screenshots
![error-img](https://img.os4team.cn/react-native-axios-adpater.gif)

**Comment by labike** [comment]
i use rn-fetch-blob send http request, this package use fetch, but i use axios and ternimal tips:

Require cycle: node_modules\rn-fetch-blob\index.js -> node_modules\rn-fetch-blob\polyfill\index.js -> node_modules\rn-fetch-blob\polyfill\Blob.js -> node_modules\rn-fetch-blob\index.js

i  remove this package and send http request is ok!

**Comment by labike** [comment]
axios sometimes has this error? and now i get this error?

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
