### ISSUE TITLE
IE 10 Access-Control-Expose-Headers behavior not normal. 

### ISSUE THREAD

**Issue by zxdposter** [axios/axios#3685]
#### Describe the bug
this is http server response, **Access-Control-Expose-Headers already expose three headers:** 
- **seccost, secrequestid, seccostt**
![image](https://user-images.githubusercontent.com/13846260/111567900-b426e400-87da-11eb-957c-eb35d4bf39d2.png)

***

but! in axios when get header, I only can get seccost, it is so weird!
If I use *cost* instead of *seccost*, it will working!
### In IE not normal!
![image](https://user-images.githubusercontent.com/13846260/111567888-acffd600-87da-11eb-8f96-bc09203d3237.png)

### In chrome normal!
![image](https://user-images.githubusercontent.com/13846260/111568912-98bcd880-87dc-11eb-98e4-9081e6a69774.png)

```js
service.interceptors.response.use(response => {
    console.log(response)
}, err);
```

#### Expected behavior
It should be get all header that I want exclude forbid by official soma thing like "set-cookie"

#### Environment
 - Axios Version [e.g. 0.21.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. IE]
 - Browser Version [e.g. 10]
 - Node.js Version [e.g. 12.16.2]
 - OS: [e.g. Windows]
 - Additional Library Versions [e.g. Vue 2.6.11]

**Comment by zxdposter** [comment]
I already figure out, why Cost so magic.

 Because Cost is first of Access-Control-Expose-Headers!

IE only identify first of Access-Control-Expose-Headers......

Even if I split Access-Control-Expose-Headers, 
![image](https://user-images.githubusercontent.com/13846260/111585248-00cde780-87fa-11eb-941f-b2c0bb2bf6de.png)

IE still merge with ",".....

Why IE do that??

**Comment by jasonsaayman** [comment]
We don't support ie 10 thanks
