### ISSUE TITLE
defaults.headers.common doesn't work but defaults.headers does

### ISSUE THREAD

**Issue by toddw** [axios/axios#369]
We were trying to implement cookie jar type support using interceptors: `instance.defaults.headers.common["Cookies"] = cookieString`

Unfortunately it was not working. It does work when we switched over to using:
`instance.defaults.headers["Cookies"] = cookieString`

Are we doing something wrong, is there a bug in axios or does the documentation just need to be updated?

**Comment by mzabriskie** [comment]
`axios@0.13.0` was just released and may contain a fix for your issue. Would you mind updating and letting me know if this has been resolved?

**Comment by tarim** [comment]
same problems here. We used local storage for token based authentication, and it never update common['Authorization'] values(until refresh whole browser). 
FYI: I updated 0.13 version and it is same.

Thanks

**Comment by mzabriskie** [comment]
Thanks for the report, I will look into it.

**Comment by diiq** [comment]
Ditto here.  The problem specifically occurs when using an instance (the result of axios.create).

**Comment by emilyemorehouse** [comment]
Closing, as this issue was resolved in #1395. 🙌
