### ISSUE TITLE
http.js reads the environment variable http(s)_proxy by default, resulting in abnormal requests

### ISSUE THREAD

**Issue by sanfengliao** [axios/axios#3690]
#### Describe the bug
For some reasons, such as a company office computer, https_proxy or http_proxy may be set to https://a.com. When I send a request to https://b.com/c on node, because config.proxy is undefined, http .js will read https_proxy in the environment variable as a proxy by default, so the request is sent to https://a.com, which causes the program to fail to send requests and receive responses normally
```javascript
if (!proxy && proxy !== false) {
      var proxyEnv = protocol.slice(0, -1) + '_proxy';
      var proxyUrl = process.env[proxyEnv] || process.env[proxyEnv.toUpperCase()];
      if (proxyUrl) {
          ...
      }
     ...
}
```
#### Expected behavior
When I do not set config.proxy to `true`, axios does not read http(s)_proxy in the environment variable. If config.proxy is set to `true`, http.js reads the http(s)_proxy in the environment variable  as a proxy. when the config.proxy is a proxy object, it  used as a proxy object
#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [HTTP]
 - Node.js Version [e.g. 12.1.6.13]
 - OS: [OSX 10.15.7]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
