### ISSUE TITLE
axios v 0.21.1 throws cross site scripting: DOM vulnerability in fortify static scan

### ISSUE THREAD

**Issue by NagendraMishra25** [axios/axios#3697]
#### Describe the bug
resolveURL() method in axios\lib\helpers\isURLSameOrigin.js is listed in fortify static scan as it throws cross site scripting: DOM vulnerability.

#### To Reproduce
Fortify static scan of axios and it throws vulnerability in its report.

https://github.com/axios/axios/blob/master/lib/helpers/isURLSameOrigin.js#L30
```js
urlParsingNode.setAttribute('href', href);
```

#### Expected behavior
The method resolveURL() sends unvalidated data to a web browser, which can result in the browser executing malicious code.
Should resolve this issue to pass in fortify static scan.

#### Environment
 - Axios Version 0.21.1

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by riteshkaushik** [comment]
@NagendraMishra25 : Hi,  i am also facing same issue. Did you get any other axios version without this issue ?

**Comment by jasonsaayman** [comment]
Please update this should solve it.

**Comment by alx-andru** [comment]
@jasonsaayman do you have some additional information on what **this** refers to?

**Comment by eseite47** [comment]
@jasonsaayman can you confirm in which version of axios this fixed was released? Thank you.

**Comment by sciortinomrc** [comment]
Hello there, Marco from Meterian here.

This issue relies on the fact that on the `isURLSameOrigin` method there is no data validation by axios.

The `resolveURL` uses a syntethic DOM element `a` to obtain information about the URL passed by the user. By doing so it makes the browser responsible of encoding and escaping of the user input.
It's basically an alternative way of doing `new URL($url);`.

Although browsers will execute Javascript code assigned to the href attribute, this is true only if the link is actually clicked on.
The `a` element created during the process is never attached to the document, so it is never clickable.

After a review of this issue we can say this is not a security vulnerability. We will downgrade it to INFORMATIONAL

**Comment by jasonsaayman** [comment]
@sciortinomrc thanks, this will hopefully change soon
