### ISSUE TITLE
😀just silly question: Does the name 'Axios' have same origin root with harry potter summoning spell 'Accio'?

### ISSUE THREAD

**Issue by joielee09** [axios/axios#3706]
#### Describe the issue

Hi I want to know if "Axios" came from the same name origin with harry potter summoning spell "Accio".
"Accio", as I linked below,  is a summoning charm, that summons an object towards the caster and the caster must have clear thought of the thing one casts for. Which I found really similar what I do when I use axios!.
I also found latin online dictionary and found 'accio' which means 'to summon, to fetch, to invite'.

https://harrypotter.fandom.com/wiki/Summoning_Charm
https://www.online-latin-dictionary.com/latin-english-dictionary.php?parola=accio

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by qq326943819** [comment]
hahhh

**Comment by jasonsaayman** [comment]
Don't know hahaha

**Comment by Jakes-Git-Hub** [comment]
I literally just googled this - I think it does bro haha
