### ISSUE TITLE
Is there a way to get SSL certificate details

### ISSUE THREAD

**Issue by joekaiser** [axios/axios#3709]
#### Describe the issue
How can we get the certificate details after successfully getting a response from a server running on https? Node exposes this as `response.socket.getPeerCertificate()` Does Axios expose it someway? Or a way to get at the underlying node response? 

I'm looking for information like who issued the cert, when was is issued, when does it expire, etc...

#### Environment
 - Axios Version [0.18.0]
 - Adapter [HTTP]
 - Browser 
 - Browser Version 
 - Node.js Version [12.x]
 - OS: [OSX 10.13.4]
 - Additional Library Versions

**Comment by Annihil** [comment]
I needed this as well a year ago, so I can say it is not exposed.
I made [a PR](https://github.com/axios/axios/pull/2498) for a similar feature but it got merged to 1.0.0 which is not yet out.

**Comment by joekaiser** [comment]
I found you can get it via this.  Seems round-about, but it works well enough

```
let response = await Axios.get(urlToPing, reqConfig);
let cert = response.request?.res.socket.getPeerCertificate(false);
```

**Comment by hash-bang** [comment]
To prevent anyone else pulling their hair out over this, I couldn't make the above work so I came up with an alternate method where you can attach to the httpsAgent and plug the fetched certificate info back into the response model:

```javascript
let tlsCert;
return axios({
	...axiosRequest, // Any other options you want
	httpsAgent: new HttpsAgent({
		rejectUnauthorized: false
	})
		.on('keylog', (line, tlsSocket) => tlsCert = tlsSocket.getPeerCertificate(false))
})
.then(response => ({
	certificate: tlsCert, // Mutate the response to add the cert
	...response,
}))
.then(response => /* response.certficate now available downstream */)
```

**Comment by yasselpiloto** [comment]
I was able to see the cert details with:

```javascript
      axios.defaults.httpsAgent = new https.Agent({
        enableTrace: true,
      });

```
