### ISSUE TITLE
response.data.length is smaller than  content-length with responseType : "arrayBuffer" or default, when downloading files

### ISSUE THREAD

**Issue by 26awen** [axios/axios#3711]
#### Describe the issue
response.data.length is smaller than  content-length with responseType : "arrayBuffer" or default

#### Example Code
Code snippet to illustrate your question

```js
import tunnel from "tunnel";
import axios from "axios";

const t = tunnel.httpsOverHttp({
    proxy: {
        host: 'localhost',
        port: 7890
    }
});


let url1 = "https://www.example.com";
let url2 = "https://i.redd.it/5q9jd02c59221.jpg";
let url3 = "https://i.imgur.com/kbsObGl.jpg";
let url4 = "https://bottlepy.org/docs/dev/bottle-docs.pdf";

let urls = [url1, url2, url3, url4];

let axConfig = {
    method: "get",
    responseType: "arrayBuffer",
    httpsAgent: t
};

urls.forEach(ele => {
    axConfig.url = ele;
    axios(axConfig).then(resp => {
        console.log("url:", ele);
        console.log("resp.data.length:", resp.data.length);
        console.log("content-length:", resp.headers["content-length"]);
    }).catch(err => {
        console.log(err);
    })
});
```
Only when response data is html (or other text based ones I think), response.data.length == content-length .
Otherwise, esponse.data.length always samller than content-length .
And if I save the data to a file (with a right fileext of cause), the file will always be broken(can not be open by sofware, for example a img).

BTW I can download file with responseType set to "stream", and do it with pipe or with data.on events.
And I am sure that it will make no difference in the result with or without a proxy or tunnel being applied.

see the result: 
![image](https://user-images.githubusercontent.com/13186663/112837822-eedc2680-90ce-11eb-98b5-3624cfe10240.png)

#### Expected behavior, if applicable
Expected: response.data.length == content-length 

#### Environment
 - Axios Version 0.21.1
 - Node.js Version 14.16
 - OS: win10 18363
 - tunnel "0.0.6"

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by dpkirchner** [comment]
axios version 0.24.0 on node 17.0.1, macOS 11.6.1 is also affected. I'm just using `axios.get(url)`, so I'm using whatever the `responseType` value. The contents written to a file are totally wrong, in my case 40% larger. I'm using `fs/promises` as `await fs.writeFile("/path/to/file", response.data)`, FWIW.

**Comment by dpkirchner** [comment]
Actually, using `arraybuffer` works for me. So it may only affect whatever the default is.

**Comment by Shaquu** [comment]
Possibly related to #4367

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
