### ISSUE TITLE
New build tools

### ISSUE THREAD

**Issue by jasonsaayman** [axios/axios#3718]
#### Is your feature request related to a problem? Please describe.
Axios has some legacy build tools and we also have an issue with the changes coming to Travis CI. For this reason, we are going to change to a different CI and try to modernise some of the build tools in the process.

#### Describe the solution you'd like
New build tools, new sauce labs account and maybe a new coverage tool

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by jasonsaayman** [comment]
Adding #1512 to this for consideration

**Comment by jasonsaayman** [comment]
Adding for later consideration #1879

**Comment by jasonsaayman** [comment]
Adding for consideration #940

**Comment by koh110** [comment]
Hi @jasonsaayman!

I send [this PR](https://github.com/axios/axios/pull/3916).
But that PR doesn't kick the CI.

Other PRs have also stopped CI around June, so I think Travis CI needs to be migrated to another domain.

https://travis-ci.org/
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

axios PJ may be planning to change to a different CI.
But can you change domain to check for open PR?
Or is there anything I can do to help?

Thanks.
