### ISSUE TITLE
Android - onUploadProgress showing 100% immediately but upload progress is still there

### ISSUE THREAD

**Issue by KiranC10** [axios/axios#3720]
#### Describe the issue
loaded parameter is 100% immediately but the upload process take some minutes after that only on android but for iOS its perfectly working.

#### Example Code
```js
// Example code here
await axios({
            url: url,
            method: 'POST',
            data: formdata,
            // timeout: 60  30  1000,
            headers: {
                Authorization: 'Bearer ' + this.props.token,
                "Accept": "application/json",
                "Content-Type": "multipart/form-data",
            },

            onUploadProgress: function (progressEvent) {
                console.log("ProgressEvent: ", progressEvent)
                let percentage = Math.floor((progressEvent.loaded / progressEvent.total) * 100);
                // console.log("loaded", progressEvent.loaded)
                // console.log("total", progressEvent.total)
                console.log("PERCENTAGE ", percentage)
                self.setState({ progress: percentage, isFileUploading: true })
                if (percentage == 100) { }
            },
        })
```

#### Expected behavior, if applicable
onUploadProgress should show percentage till process executes.

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.63]

#### Additional context/Screenshots
Only android has this issue on iOS its perfectly working

**Comment by Kallirroi** [comment]
I have the exact same issue on desktop:
- MacOS `11.2.3 (20D91)`
- Chrome `89.0.4389.90`
- `axios ^0.20.0` 
- `node v14.16.0`
- `react ^16.13.1`

**Comment by Alirez14** [comment]
same here please have a look at this topic 🙏

**Comment by LongYue9608** [comment]
I have the same problem

**Comment by thisisnabi** [comment]
yes, pls check it. thanks

**Comment by KiranC10** [comment]
Has anyone got solution for this issue?

**Comment by xiaowu2333** [comment]
同样的问题

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by outsourcingvasundhara123** [comment]
Same issue

**Comment by outsourcingvasundhara123** [comment]
Any solution for this?

**Comment by hanin77** [comment]
any solution so far?

**Comment by jjebennett** [comment]
I'm guessing this still hasn't been resolved?

**Comment by bruno-at-sofi** [comment]
Same...

**Comment by kopeikins** [comment]
Works in react native for web, but not in ios.

**Comment by MohamedKamalOthman** [comment]
I have the same problem on android
- "axios": `^1.4.0`.
- "React Native": `v0.76.7`.

**Comment by minhna** [comment]
I have this problem on android:
```
"axios": "^1.4.0",
"react-native": "0.71.1",
```

**Comment by MohamedKamalOthman** [comment]
Hi @minhna, checkout this comment on this issue  https://github.com/axios/axios/issues/3469#issuecomment-1650018098 and can you please confirm that it's working on release builds?

**Comment by mleister97** [comment]
Same issue still exists with react-native on ios & axios in 2024...

**Comment by HenriqueMarcelo** [comment]
Same when running node on windows trying to send large data to another server.
