### ISSUE TITLE
I guess we need finally keyword instead of then. Do we ??

### ISSUE THREAD

**Issue by tusharkgeospoc** [axios/axios#3723]
#### Section/Content To Improve
Quote or link to section - https://github.com/axios/axios#example

#### Suggested Improvement
Identify what is confusing or incorrect and what could make it better - 

![image](https://user-images.githubusercontent.com/73871220/113396669-82f10b00-93b9-11eb-9647-115bee86af4a.png)

As I highlighted `then` keywords, I believe these should be `finally`.
Please correct me if I'm wrong.

#### Relevant File(s)
[e.g. README.md]

**Comment by chinesedfan** [comment]
See #2683 and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally. For example, looks like IE is not supported yet.
