### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by gloverola** [axios/axios#3724]
#### Section/Content To Improve
Spelling error on the documentation page.

#### Suggested Improvement
use "Navigation" instead of "Navitation"

#### Relevant File(s)
<img width="226" alt="Screenshot 2021-04-02 at 09 52 37" src="https://user-images.githubusercontent.com/59847935/113400248-66dd7180-9399-11eb-894e-2febf267fe34.png">

**Comment by jasonsaayman** [comment]
Hi

Thanks this has been fixed in the axios-docs repo.

Thanks
