### ISSUE TITLE
`axios.head()` does not respond  in particular case

### ISSUE THREAD

**Issue by well-balanced** [axios/axios#3728]
#### Describe the bug
hello guys. I have a strange issue that `axios.head()` method doesn't respond any data. It's just freezing. I've tried google to solve this problem. but I couldn't find.

#### To Reproduce
below are our source code using in Node.js.

```ts
console.log('start request')
  const url = 'https://www.tesla.com'
  const responseHEAD = await axios.head(url, {
    maxRedirects: 0,
    validateStatus: status => status >= 200 && status < 500,
  })
console.log('finished request')
```

just freezing like this
```bash
start request
(cursor is flickering)
```

#### Expected behavior
```bash
start request
finished request
```

#### Environment
 - Axios Version [e.g. 0.20.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
I know that It'll be fixed if I use the timeout option, but I just wanted to know.

**Comment by PeterV989** [comment]
It occurs to me you are using the ES6 "=>" (function reference) operator in the comparison where I expect you mean to use the ">=" (greater then or equal) operator.

Good luck.

Peter

**Comment by PeterV989** [comment]
It occurs to me you are using the ES6 "=>" (function reference) operator in the comparison where I expect you mean to use the ">=" (greater then or equal) operator.

Good luck.

Peter

**Comment by well-balanced** [comment]
@PeterV989 
It still does not work in spite of delete that line 😭 you mean like this, aren't you?

```ts
console.log('start request')
  const url = 'https://www.tesla.com'
  const responseHEAD = await axios.head(url, {
    maxRedirects: 0,
  })
console.log('finished request')
```

**Comment by imjustzealous** [comment]
Hello, i'm new here _so correct me if i'm wrong,_ and I tried to check if there's a problem with the exchange of requests and responses between axios and the server, and it seems there's nothing wrong.

The `HEAD` request method does not really return any body data, it only responds the client with headers and no body data, so if you want to see the headers, you can extract it from `response.headers`

```javascript

console.log('start request')
const url = 'https://www.tesla.com'
const responseHEAD;

axios.head(url).then(
  function (response) {
     responseHEAD = response.headers
  }
)

console.log(responseHEAD)
console.log('finished request)

```

This is the message that you will see

```
start request
{"Content-Type" : "", "Server" : ""}
finished request

```

**Comment by imjustzealous** [comment]
The `HEAD` request works for me here
```javascript
const axios = require('axios')

let responseHEAD = {}

console.log('start request')
axios.head('http://localhost:8080/test').then(
    (response) => {
        responseHEAD = response.headers
        console.log(responseHEAD)
        console.log('finished request')
    }
)
```
This is the result

```
start request
{
  server: 'mylocalhost',
  'content-type': 'text/html',
  date: 'Thu, 15 Apr 2021 04:25:45 GMT',
  connection: 'close'
}
finished request
```

**Comment by well-balanced** [comment]
I resolved that by using timeout option. close issue :)
