### ISSUE TITLE
Using cancelToken in place of timeout cancels all requests after specific time interval 

### ISSUE THREAD

**Issue by dany-fu** [axios/axios#3729]
#### Describe the issue
Following suggestions on issue #647, I'm using the CancelToken feature to implement a timeout instead of the `timeout` parameter. I'm getting a similar behavior to #904 even though I'm creating a **new** cancel token for every request, all requests made after the timeout limit are cancelled (see screenshot).  I am using the `axios-rate-limit` to create a custom instance of axios instead of using the default, not sure if that causes an issue. I have both GET and POST requests but the result is the same. 

If this is the intended behavior, how do I actually make a request obey its own unique CancelToken?

#### Example Code

```js
const ax = require("axios");
const axios = rateLimit(ax.create(), { maxRequests: 5, perMilliseconds: 1000});
const timeout = 1000; //ms

async foobar(){
  return axios.get(endpoint, {
    cancelToken: new ax.CancelToken(function executor(cancel) {
      setTimeout(() => {cancel(`Timeout of ${timeout} ms.`)}, timeout);
    })
  })
.then((res) => {...}
.catch((error) => {...}
}

// also tried
async foobar(){
const abort = ax.CancelToken.source()
  const id = setTimeout(
    () => abort.cancel(`Timeout of ${timeout}ms.`),
   timeout
  )
  return axios
    .get(url, { cancelToken: abort.token, ...options })
    .then(res => {
      clearTimeout(id)
      ...
    })
.catch((error) => {...}
}
```

#### Expected behavior, if applicable
I some saw suggestions ([here](https://stackoverflow.com/questions/61081268/axios-cancel-token-cancelling-every-request) and [here](https://stackoverflow.com/questions/44852054/cant-cancel-axios-post-request-via-canceltoken)) to cancel the previous canceltoken but my purpose is to fetch and update different records using the same endpoint but with unique ID, so I don't want to cancel the previous call. And since a new CancelToken is created every time, that specific request should only be cancelled after it has met its own timeout limit. 

#### Environment
 - Axios Version: 0.19.2
 - Adapter : n/a
 - Browser: n/a
 - Browser Version: n/a
 - Node.js Version: node-v12.18.2
 - OS: OSX and Windows

#### Additional context/Screenshots
For example, if my timeout is 1000ms, then all requests after 1s throw an error
<img width="272" alt="Screen Shot 2021-04-07 at 1 56 56 AM" src="https://user-images.githubusercontent.com/7750862/113817566-89c6a780-9744-11eb-9605-d2f608faeffd.png">

**Comment by DigitalBrainJS** [comment]
[Sandbox](https://codesandbox.io/s/axios-issue-test1-fuhl7?file=/src/index.js)
```
import axios from "axios";

async function request({ timeout, ...options } = {}) {
  const source = axios.CancelToken.source();
  let id =
    timeout &&
    setTimeout(() => {
      id = 0;
      source.cancel(`Timeout of ${timeout}ms.`);
    }, timeout);
  return axios({
    cancelToken: source.token,
    ...options
  }).finally(() => {
    id && clearTimeout(id);
  });
}

(async () => {
  console.log(
    await request({
      url:
        "https://run.mocky.io/v3/7b038025-fc5f-4564-90eb-4373f0721822?mocky-delay=2s&foo",
      timeout: 1000
    }).catch(console.warn)
  );

  console.log(
    await request({
      url:
        "https://run.mocky.io/v3/7b038025-fc5f-4564-90eb-4373f0721822?mocky-delay=2s&bar",
      timeout: 5000
    }).catch(console.warn)
  );
})();
```

**Comment by jasonsaayman** [comment]
Looks like the comment from @DigitalBrainJS solves this issue. Please reopen if not.
