### ISSUE TITLE
Empty data object needed for GET request to return object

### ISSUE THREAD

**Issue by GuitarHero1969** [axios/axios#3739]
#### Section/Content To Improve
Quote or link to section

#### Suggested Improvement
Identify what is confusing or incorrect and what could make it better

#### Relevant File(s)
[e.g. README.md]

**Comment by GuitarHero1969** [comment]
So,
it has taken me several weeks to finally get the following to return the json 'd' object from my webmethod instead of it returning the page HTML.

(then and catch ommited for clarity)

axios.get('https://localhost:44321/SalesOrders_Editing.aspx/GetProductCategories', { data: {} }, { headers: { Accept: 'application/json' } })

WHY ON EARTH do I need data: {} to get this to work ?

**Comment by jasonsaayman** [comment]
Hi @GuitarHero1969 

Without knowing how https://localhost:44321/SalesOrders_Editing.aspx/GetProductCategories works it would be difficult to tell you why you are having to set data to an empty object. I would also suggest using StackOverflow for this type of question and this is not a bug with Axios.

Thanks
