### ISSUE TITLE
TypeError: Cannot read property '$get' of undefined in api/repository.js

### ISSUE THREAD

**Issue by mohammad-bede** [axios/axios#3745]
#### Describe the issue
I fetch an api in my `api/repository.js` from a component through my `vuex` actions:

```
//component:
<button @click="click">button</button>

methods:{
  ...mapActions(['click'])
}

//store:
async click({commit}) {
  await this.$repository.liveEvents.genreById().then(data => {
    // commit
  }
}

// api/liveEvents.js:
const baseUrl = process.env.config.baseUrl;

export default ($axios) => ({
   genreById($axios) {
    return $axios.get(`${baseUrl}`)
  }
})

// api/repository.js
import LiveEvents from '~/api/liveEventsApi'

export const repository = ($axios) => ({
  liveEvents: LiveEvents($axios)
})
```

I have also created a plugin for it:

```
// plugins/repository.js:
import { repository } from '~/api/Repository.js'

export default (context, inject) => {
  inject('repository', repository(context.$axios))
}
```

And have added it to my nuxt.config.js:

```
  plugins: [
    { src: '~plugins/repository.js'}
  ],
  ```

#### Example Code
In description above!

#### Expected behavior, if applicable
However when I click on the button in my component, I get the error `Uncaught (in promise) TypeError: Cannot read property 'get' of undefined!` I think the issue is `api/repository.js` somehow doesn't understand `$axios`. However when I use `$axios` in my store or directly in my components I don't get any errors and it works! Anyone knows what's wrong here?

#### Environment

My nuxt/axios version is:
"@nuxtjs/axios": "^5.13.1"

My nuxt version is:
"nuxt": "^2.15.3"

My node version is:
v14.16.0

#### Additional context/Screenshots
None

**Comment by chinesedfan** [comment]
> await this.$repository.liveEvents.genreById()

> genreById($axios) {

Note that you didn't pass the required parameter `$axios`.
