### ISSUE TITLE
Date serialization in headers should use GMT

### ISSUE THREAD

**Issue by Tejes** [axios/axios#3747]
#### Describe the bug
When the `If-Modified-Since` header is set to a `Date` object, Axios serializes it into a format containing the local timezone (GMT+2 in my case). [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since#directives), HTTP dates should always be in GMT, and indeed, the web servers I tried ignore the header in the current format. Providing a valid string representation (eg. by using `Date.toUTCString()`) as the header value is a workaround.

#### To Reproduce
```js
const axios = require("axios")
const date = new Date()
//const date = new Date().toUTCString()

axios.get("https://i.imgur.com/JOKsNeT.jpg", {headers: {"If-Modified-Since": date}})
    .then(resp => console.log(resp.status))
    .catch(e => console.log(e.response.status))
```
https://runkit.com/embed/hxh6dsdcyqrr

#### Expected behavior
The above code should print 304, because the image is older than the specified date. 

#### Environment
 - Axios Version: 0.21.1
 - Adapter: HTTP
 - Node.js Version: 12.17.0
 - OS: Windows 10

#### Additional context/Screenshots
None

**Comment by chinesedfan** [comment]
axios does nothing for headers serialization. If you want to handle it somewhere, the request interceptor is our suggested place.
