### ISSUE TITLE
when doing CORS request, the Access-Control-Allow-Origin vanished

### ISSUE THREAD

**Issue by EvanLee2048** [axios/axios#3753]
#### Describe the issue
I expect the Access-Control-Allow-Origin appear in preflight request but it is not.
The browser gives me :

Access to XMLHttpRequest at 'http://localhost:8912/' from origin 'http://localhost:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

even I has 'Access-Control-Allow-Origin' header in my code

#### Example Code
Code snippet to illustrate your question

frontend js:
```
            let config = {
                url,
                method: "get",
                headers: {
                  'Access-Control-Allow-Origin': '*',
                  'Access-Control-Allow-Headers': '*',
                  'Access-Control-Allow-Credentials': 'true'
                }
            };
            let response = await this.axios.request(config);
```

backend preflight code:
```
    def options(self):
        self.set_status(200)
        logging.info(self.request.headers)
        self.set_header('Access-Control-Allow-Origin', 'http://localhost:8081')
        self.set_header('Access-Control-Allow-Headers', 'Host, Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-XSRF-TOKEN, Origin, Access-Control-Request-Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Allow-Origin, access-control-allow-origin, Access-Control-Allow-Credentials, access-control-allow-credentials, Access-Control-Allow-Headers, access-control-allow-headers, Access-Control-Allow-Methods, access-control-allow-methods')
        self.set_header('Access-Control-Allow-Credentials', 'true')
        self.set_header("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS,POST,PUT")
        self.write('ok')

```

#### Expected behavior, if applicable
Expected behavior : 200 HTTP

#### Environment
 - Axios Version 0.21.1
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 89.0.4389.128
 - Node.js Version v14.15.4
 - OS: Mac OS X 11_2_3
 - Additional Library Versions: Vue 2.6.11

#### Additional context/Screenshots

logging.info(self.request.headers) output : 

```
Host: localhost:8912
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
Access-Control-Request-Method: GET
Access-Control-Request-Headers: access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,access-control-request-origin
Origin: http://localhost:8081
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: http://localhost:8081/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,zh-TW;q=0.7,zh;q=0.6
```

**Comment by wiznotwiz** [comment]
Any follow up on this?

**Comment by richex-cn** [comment]
The `Access-Control-Allow-Origin` is response header, CORS is meaningless if the client can control it.
If you want to access correctly, you can do so:

1. Modify your server configuration and add the corresponding header to allow browser access.
2. Make sure your request is [Simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).

From your sample code, If you want to request with cookies, The first point is necessary, So server must append `Access-Control-Allow-Credentials` header to make the cookie work.

I suggest you learn more about [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), see:

- [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
- [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)
- [Access-Control-Allow-Credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials)

**Comment by Fazliddin-Nasrullayev** [comment]
i

**Comment by devDoubleH** [comment]
I think issue is on backend 

```
const corsConf = {
  origin: "*",
  methods: "GET,HEAD,PUT,PATCH,POST,DELETE",
  preflightContinue: false,
  optionsSuccessStatus: 204
}

app.use(cors(corsConf));
```


this worked me :)

**Comment by sweihub** [comment]
I solved this issue by using fetch
```
await fetch('http://172.16.210.211:15600/sessions').then(x => x.json());
```
