### ISSUE TITLE
500 Error when I do post an object

### ISSUE THREAD

**Issue by whydnxx** [axios/axios#3776]
#### Describe the bug
This bug so confuses me, so I have an API endpoint with the method POST, when I send an object payload from FE to BE the response always 500 so I check using Postman, it works. So I search on Stackoverflow about this issue and I found this.
https://stackoverflow.com/questions/50950011/axios-post-request-fails-with-error-status-code-500-internal-server-error

This issue solved by stringifying the object.

#### To Reproduce
` axiosInstance.js`
```js 
export const axiosInstance = axios.create({
  baseURL:  ....
});

axiosInstance.interceptors.request.use((config) => {
  let getToken = JSON.parse(localStorage.getItem("TOKEN"));

  config.headers = Object.assign(
    {
      Authorization: 'Bearer ' + getToken?.accessToken ?? '',
    },
    config.headers
  );
  return config;
});
```
```js 
import { axiosInstance } from "./axiosInstance"

export const CHECKOUT = async (body) => {
  const url = `. . .`
  const res = axiosInstance.post(url, {data: body})
  return res
}
```

#### Expected behavior

I think the code will work with this 

```js
  const res = axiosInstance.post(url, {data: body})
```

but, it would be fine if I stringify the object

```js
  const res = axiosInstance.post(url, JSON.stringify({data: body}))
```

#### Environment
 - Axios Version [0.21.1]
 - Adapter [XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [90.0.4430.93]
 - Node.js Version [12.14.1]
 - OS: [Windows 10]
 - Additional Library Versions [React 17.0.1]

#### Additional context/Screenshots
...

**Comment by jasonsaayman** [comment]
Hi @whydnxx 

Can you give an example of the body data then I can check it is not an issue within axios?

Thanks
