### ISSUE TITLE
Submit Form Data To Google Sheets

### ISSUE THREAD

**Issue by lilyntalmers** [axios/axios#3777]
#### Describe the issue
I have a form and I want to submit it's data to my Google Sheets. For this I am using Axios and a service called [Sheeton](https://sheetson.com/). But for whatever reason the data is not posting. [Here is the Sheeton Docs](https://docs.sheetson.com/examples/portfolio/)

#### Example Code

```js
    const  handleSubmit  =  values  =>  {
    const  data  =  {  ...values,  totalPrice,  myurl  }
    mergeFormState(data)
    console.log("Data:",  data)
    axios.post("https:api.sheetson.com/v2/sheets/MyForm",  data, {
      headers:  {
        "Content-Type":  "application/json",
        Authorization:  "Bearer MY_API_KEY_HERE",
        "X-Sheetson-Spreadsheet-Id":  "1qZOi8TwZUOyAjneERrusEBMWtAfKGJWEeW3IeuZGK88"
        }
    })
    .then(FormData => {
      console.log(FormData)
      alert("Success")
    })
    .catch(() => {
      alert("Error")
    })
    }
```

## Live sandbox

[CodeSandbox.io](https://codesandbox.io/s/dry-dawn-0y043?file=/src/components/MyForm.js:671-1386)
[My Google Sheet](https://docs.google.com/spreadsheets/d/1qZOi8TwZUOyAjneERrusEBMWtAfKGJWEeW3IeuZGK88/edit?usp=sharing)

#### Expected behavior, if applicable
Submit my form data to Google Sheets

**Comment by jasonsaayman** [comment]
Hi, @lilyntalmers,

I think this would be more suited to be asked on something like StackOverflow as the repo is only for issues that directly correlate to Axios.

Thanks
