### ISSUE TITLE
Passing timeout as a string is throwing an error in the latest version of axios due to upgrade of follow-redirects

### ISSUE THREAD

**Issue by kanhaiagarwal** [axios/axios#3778]
#### Describe the bug
Axios uses `follow-redirects` internally for making http requests. When axios was using follow-redirects@1.13.3, we were able to supply timeout in string, e.g. '30000'. Recently, `follow-redirects` upgraded to v1.14.0. Upon supplying the timeout as a string, eg. '30000', follow-redirects@1.14.0 is throwing the following error:

`
ERROR Uncaught Exception { "errorType": "TypeError", "errorMessage": "The \"msecs\" argument must be of type number. Received type string ('30000')", "code": "ERR_INVALID_ARG_TYPE", "stack": [ "TypeError [ERR_INVALID_ARG_TYPE]: The \"msecs\" argument must be of type number. Received type string ('30000')", " at validateNumber (internal/validators.js:125:11)", " at getTimerDuration (internal/timers.js:381:3)", " at TLSSocket.setStreamTimeout [as setTimeout] (internal/stream_base_commons.js:250:11)", " at RedirectableRequest.destroyOnTimeout (/opt/nodejs/node_modules/follow-redirects/index.js:159:12)", " at RedirectableRequest.emit (events.js:314:20)", " at RedirectableRequest.EventEmitter.emit (domain.js:483:12)", " at ClientRequest.eventHandlers.<computed> (/opt/nodejs/node_modules/follow-redirects/index.js:14:24)", " at ClientRequest.emit (events.js:326:22)", " at ClientRequest.EventEmitter.emit (domain.js:483:12)", " at tickOnSocket (_http_client.js:709:7)" ] }
`

#### To Reproduce
```js
var axios = require("axios")
response = axios({ url: 'https://www.google.com', method: 'GET', timeout: '30000' }).then(res => { console.log('res:', res) }).catch(err => { console.log('err:', err) })
```

Try the above code with follow-redirects version v1.13.3 and v1.14.0. You will find that the error is thrown when you are using v1.14.0 and the code runs fine when using v1.13.3.

#### Expected behavior
No error thrown by the code.

#### Environment
 - Axios Version: 0.21.1
 - Node.js Version: 12.x, 14.x
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Internal dependency: follow-redirects@1.14.0

#### Additional context/Screenshots
<img width="721" alt="Screenshot 2021-05-04 at 10 13 46 AM" src="https://user-images.githubusercontent.com/17040518/116961612-6c441980-acc1-11eb-9c42-d1b2f47f2ee6.png">

<img width="721" alt="Screenshot 2021-05-04 at 10 15 41 AM" src="https://user-images.githubusercontent.com/17040518/116961742-c2b15800-acc1-11eb-8882-0b0e189cdc21.png">

**Comment by DigitalBrainJS** [comment]
technically, the timeout option is defined as  `timeout?: number;` not ` timeout?: number|string;` so passing strings is not a documented behavior.

**Comment by kanhaiagarwal** [comment]
Yes, but if you use axios with the 2 mentioned versions of follow-redirects, you'll see that axios is accepting a string value for `timeout` for the earlier version, and due to some change in the later version of follow-redirects, axios is not throwing an error, but `follow-redirects` is throwing it. This is happening in nodejs. Either axios should check the datatype of the `timeout` variable before passing it to `follow-redirects`, or convert a string to a number before passing it to `follow-redirects`.

As you can see from 2 of my screenshots, axios is not causing the problem, but rather the downstream service is causing the problem.

Since I am a consumer of `axios`, I was able to figure this out and report appropriately as axios is a highly popular http request library used in nodejs. It's upto the `axios` team to take it up or not.

**Comment by piiih** [comment]
Exactly the same here, our app got broken in production. I would suggest also to remove the `^` from the `follow-redirects`. Today our solution was to downgrade `axios` version to use an earlier version of `follow-redirects`.

**Comment by piiih** [comment]
I would suggest to do a `parseInt` when creating the httpAdater, that wouldn't be good approach once the `follow-redirect` breaks if it receives something that isn't a number? I'll open a MR to fix this soon :)

**Comment by DigitalBrainJS** [comment]
axios doesn't have a types validator for the common options, so accepting string as timeout was an incidental behavior. As you can see, even axios v0.16.0 [had the timeout option defined as a number type](https://github.com/axios/axios/blob/19b794848047e51f5d8689cf48820c986df49d25/index.d.ts#L29). 
So, it looks like a feature request, not a bug. In any case, it's not a big deal to convert the timeout value to a number before passing it to the axios by multiplying the string value by 1.

**Comment by jasonsaayman** [comment]
Hi, is it possible for someone to create a pull request and associated regression and unit test for this and tag me to review?

**Comment by piiih** [comment]
I'm doing this :)

**Comment by piiih** [comment]
@jasonsaayman I can't tag you as a reviewer, I guess I don't have access :(
