### ISSUE TITLE
Getting network error when sending form data

### ISSUE THREAD

**Issue by Rc85** [axios/axios#3788]
#### Describe the bug
Getting network error when sending form data and server's response is not received in browser.

This appears and there is no request in the network tab
![image](https://user-images.githubusercontent.com/22307591/117521899-18f1f580-af65-11eb-92d4-31a004e00854.png)

However, on the server, console logging req.headers and as you can see, the content length is the file size
![image](https://user-images.githubusercontent.com/22307591/117521914-332bd380-af65-11eb-9b92-57b5aeb95c8b.png)

I don't have any cors middleware.

#### To Reproduce

```
const uploadMenu = (e: any) => {
    const file = e.target.files[0];

    const formData = new FormData();
    formData.set('file', file);

    fileInput.current.value = '';

    const response = await await axios({
       method: 'post',
       url: '/api/v2/merchant/auth/menu/upload',
       params: { merchant_id: merchantId },
       data: formData
    })
    .then((response) => {
      return response;
    })
    .catch((err) => {
      console.log(err);
      if (err.response) {
        return err.response;
      } else if (err.request) {
        return err.request;
      } else {
        return false;
      }
    });
}
```

#### Expected behavior
Axios should be able to receive the response sent from the server, rather than instantly giving a network error.
    

#### Environment
 - Axios Version 0.21.1
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 90.0.4430.93
 - Node.js Version 14.16.0
 - OS: Windows 10
 - Additional Library Versions React 16.13.7

The strangest thing is, why doesn't my request show up in the network tab but I get it on the server? Why is axios giving instant network error when the server actually received the request?

#### Additional context/Screenshots
I am trying to check the headers `content-length` and send a file size too big response before it reaches multer, because I think multer uploads the file first before it checks the filesize in the `fileFilter` function.

If I let the request go through multer, multer will be able to send the response and axios will receive the response.

This causes the issue
```
app.post('/api/v2/merchant/auth/menu/upload', (req, resp, next) => {
  if (parseInt(req.headers['content-length'] > 10000000) {
    return resp.status(400).send('The file is too big')
  }
},
(req, resp, next) => {
   upload.single('file')(req, resp, (err) => {
     return resp.send(200).send('Menu uploaded')
   }
});
```

However, if I send a request that is not form data, it works. If I remove the first middleware or don't send a response in the first middleware, it works. Any response outside of `upload.single('file')` will raise the issue.

Proof that the server is sending the response.
![image](https://user-images.githubusercontent.com/22307591/117522386-e09fe680-af67-11eb-940f-d1c295951490.png)

**Comment by FuketsuBaka** [comment]
Facing the same issue, at some points.
I used to send API-requests via POST with request params as json in body. Then i get response on that POST-request, in contains some data from my API.
The problem i have no is tricky. I figured out if Content-Length on the response is over about 3mil, right after receiving it i get either CONNECTION_RESET or CONNECTION_CLOSE with status-code 200 (HTTP: OK). If you can see - Axios call went into error ('catch') so my response.data was already forever lost. 
The exact same request works in Firefox. And from Postman. I just get responce with status 200 and my data.
Browser definetly loading response, it can be seen in chrome debugger, and right after all was loaded - network error. 
I tested it in Edge - it fails as well, so I started to think it's not Google Chrome but Chromium-related issue.
Another mistery I can't resolve - the same request works in Chrome, from localhost in dev-environment (both front and api on localhost). It gives the exact same responce (DB shared).
If my issue somehow related to this and I will find the demon behind it - I'll share it here.

**Comment by FuketsuBaka** [comment]
`request.onreadystatechange = function handleLoad() {` at `node_modules/axios/lib/adapters/xhr.js`
added
`if (request.status === 0 && !(request.responseURL && request.responseURL.indexOf('file:') === 0)) {
        console.log(request)
        return;
      }`
Result in console with failed request
![image](https://user-images.githubusercontent.com/34390952/119934505-1278fb80-bfb0-11eb-9f6e-f446ca57f680.png)

**Comment by FuketsuBaka** [comment]
I solved this issue with my setup.
```
const fs = require('fs')
const path = require('path')
const fastify = require('fastify')({
  http2: false, // <-------------- HERE
  https: {
    allowHTTP1: true, // fallback support for HTTP1
    key: fs.readFileSync(path.join(__dirname, '..', 'https', 'fastify.key')),
    cert: fs.readFileSync(path.join(__dirname, '..', 'https', 'fastify.cert'))
  }
})
```
So **in my situation** - it was totally **not an axios issue**, it's node-http2  and/or it's use in fastify. I doubt fastify maintain sessions and form packets for http2, so probably just http2-webServices in node.

**Comment by Arunkutti** [comment]
After checking with snippets got your issue,

From the first middleware, you are not forwarding your request with **next()** . That is the place your request got broken. The issue with the backend not with axios and moreover validate the file size before upload using multer by example.

```
var maxSize = 1 * 1000 * 1000;

var storage = multer.diskStorage({
  destination: function (req, file, callback) {
    callback(null, 'public/upload');
  },
  filename: function (req, file, callback) {
    callback(null, file.originalname);
  },
  onFileUploadStart: function(file, req, res){
    if(req.files.file.length > maxSize) {
      return false;
    }
  }
});

var upload = multer({ storage : storage}).single('bestand');

router.post('/upload',function(req,res){
    upload(req,res,function(err) {
        if(err) {
            return res.end("Error uploading file.");
        }
        console.log(req.file);
        res.redirect(req.baseUrl);
    });
});
```

By default multer having this functionality.Have a great day.

**Comment by ciarans** [comment]
Thanks @FuketsuBaka saved me a bunch of time - was getting this on a large 2mb response
