### ISSUE TITLE
Testing with typescript missing interceptor property

### ISSUE THREAD

**Issue by schirrel** [axios/axios#3792]
#### Describe the issue
I am develping a platform with typescritp and for testing axios interceptor, as we can found a lot on the web, is used the property [handlers](https://github.com/axios/axios/blob/199c8aab64c45532389f3e56a913017a54803dfe/lib/core/InterceptorManager.js#L6) but on axios types for typescritp use it is not presente, as you can see [here](https://github.com/axios/axios/blob/199c8aab64c45532389f3e56a913017a54803dfe/index.d.ts#L141). It is. abad practice to test axios interceptors using handlers or it is in fact missing, and should be presente?

#### Expected behavior, if applicable
To test axios interceptor with handlers

#### Environment
 - Axios Version [e.g. 0.21.1]
 - Node.js Version [e.g. 14.16]
 - OS: OSX 11.13

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by TiagoBarros01** [comment]
No response yet??

**Comment by TiagoBarros01** [comment]
As the "handler" method doesn't have any type in Axios, I solved this problem by creating a custom type file for Axios, declaring the module itself and adding a new property to the existing "AxiosInrterceptorManager" interface.

In your src folder, create a types folder or any other name what your prefer, and create a "axios.d.ts" file 

That way you don't lose the kind of any other method and solve the "handler" problem

```ts
import 'axios';

declare module 'axios' {
  export interface AxiosInterceptorManager<V> {
    use(
      onFulfilled?: (value: V) => V | Promise<V>,
      onRejected?: (error: any) => any,
    ): number;
    eject(id: number): void;
    handlers: any[];
  }
}
```

**Comment by schirrel** [comment]
Thanks @TiagoBarros01 i am not so good at TS. but sure this will help

**Comment by TiagoBarros01** [comment]
> Thanks @TiagoBarros01 i am not so good at TS. but sure this will help

Sure!

**Comment by jasonsaayman** [comment]
Closing it seems to be answered

**Comment by tiborpilz** [comment]
I've also run into this issue, and although adding an axios shim with the type set is a workaround for the problem, it seems like these types should be provided by axios - there was a related PR which sadly has been closed as stale: https://github.com/axios/axios/pull/4572, maybe this deserves a second look?
