### ISSUE TITLE
Behavior of # symbol in query parameters

### ISSUE THREAD

**Issue by TalaatHarb** [axios/axios#3801]
#### Describe the bug
Making a GET request with the URL containing a query parameter that has the '#' symbol in the middle makes the call with only the part of the query parameter before the '#' symbol

#### To Reproduce
making the call in the following format

```js
axios.get('https://jsonplaceholder.typicode.com/users?a=ahmed##abd%20Elmalek')
```
makes the query with `a = ahmed` and not the full query parameter

while making it using 
```js
axios.get('https://jsonplaceholder.typicode.com/users?a=ahmed$$abd%20Elmalek')
```
works as expected

#### Expected behavior
the '#' symbol URL encodes to itself normally and shouldn't have any specific behavior associated with it (as far as I can find in the documentation)

#### Environment
 - Axios Version [0.18.0]
 - Adapter [XHR]
 - Browser [Chrome]
 - Browser Version [90.0.4430.93]
 - Additional Library Versions [React 16.2.0+]

#### Additional context/Screenshots
Using '%23' instead of using the '#' works, and this only

**Comment by anderlaw** [comment]
It is not `axios`'s behavior also not a bug.
It is browser's behavior that ignores the `hash` section of a URL, so server-side will only receive the `no-hash` content. 
By the way, if you wanna send strings contains `#`symbol, you can  use:
```
axios.get("https://jsonplaceholder.typicode.com/users",{ a: "ahmed##abd%20Elmalek"})
```
because `axios` would use `decodeURIComponent` decoding every params

**Comment by robgwin** [comment]
FWIW my app was already building requests like these and the resulting query string still got chopped at the hash:

`axios.get("https://jsonplaceholder.typicode.com/users",{ a: "ahmed##abd%20Elmalek"})`

To get it to work I had to wrap the value in encodeURIComponent() first:

`axios.get("https://jsonplaceholder.typicode.com/users",{ a: encodeURIComponent("ahmed##abd%20Elmalek")})`
