### ISSUE TITLE
axios instance post failed with a 404 reponse but still resolved with onfullfilled function in .then()

### ISSUE THREAD

**Issue by Nuex04** [axios/axios#3805]
#### Describe the bug
axios instance post failed with a 404 reponse but still resolved with onfullfilled function in .then()
The other config options remained untouched.
#### To Reproduce
main process in my code
```js
// api/index.js
const instance = axios.create({
    baseURL: path + 'data',
    timeout: 10000,
})
export const getData = () => {
    return instance.get(
        "/data",
        {params}
    )
}

// .js which import above function
getData().then((res) => {
                console.debug('200',res)
            }, (res) => {
                console.debug('404',res)
            })
```
// in chrome console
xhr.js:177 GET http://****/data 404 (NOT FOUND)
**.js:12 200 undefined

#### Expected behavior
expect 404 in console instead of 200 

#### Environment
 - Axios Version [ 0.21.1]
 - Browser [Chrome]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by anderlaw** [comment]
I found this issue while wandering around and try to reproduce this issue, but failed.
By the way, is the part marked below a misspelling or?
![image](https://user-images.githubusercontent.com/21139011/118761556-2da88480-b8a7-11eb-828a-a5c357098185.png)

if it is, can you provide more details to reproduce the problem you found?

**Comment by Nuex04** [comment]
> I found this issue while wandering around and try to reproduce this issue, but failed.
> By the way, is the part marked below a misspelling or?
> ![image](https://user-images.githubusercontent.com/21139011/118761556-2da88480-b8a7-11eb-828a-a5c357098185.png)
> 
> if it is, can you provide more details to reproduce the problem you found?

Thanks for replying! I have double checked the original code and tested it again. It was just a misspelling left here described in the issue when I removed irrelevant details in the original code. The behavior still exists. What other information can I provide to help?

**Comment by Nuex04** [comment]
misspelling fixed in the snippet.

**Comment by imjustzealous** [comment]
Hey, I tried to reproduce the code that you have provided and ran it on different environments
which is listed below:

```
Environments
1. Brave Browser - Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
2. NodeJS - Version 14.17.0

Axios
1. <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script> (For browser)
2. Axios 0.21.1 (For NodeJS)
```

Below is a reproduced code with a little bit of modification

```js
let instance = axios.create({
    baseURL: 'http://localhost:8080/',
    timeout: 10000,
})

let getData = (path) => {
    return instance.get(path);
}

// Contacting the index path which returns 200 OK
getData('/').then((res) => {
    console.debug('200 (1) index path')
}, (res) => {
    console.debug('404 (1) index path')
})

getData('/').then((res) => {
    console.log('200 (2) index path\n')
})
.catch((res)=> {
    console.log('404 (2) index path\n')
})

// Contacting a random path which returns 404 Not Found
getData('/sfsdfs').then((res) => {
    console.debug('200 (1) random path')
}, (res) => {
    console.debug('404 (1) random path')
})

getData('/sfsdfs')
.then(
    (res) => {
        console.debug('200 (2) random path\n')
})
.catch(
    (res)=> {
        console.debug('404 (2) random path\n')
})
```

Which on NodeJS, logs this result:
```
404 (1) random path
404 (2) random path       

200 (1) index path           
200 (2) index path            
```

On browser, logs this result

```
404 (1) random path
200 (1) index path

404 (2) random path
200 (2) index path
```

There are possible factors which may have caused the onFulfilled bug, but I may suspect that it is the browser. I do not know but you may use the code, then if that also caused the onFulfilled bug, it is likely that it is the browser.

**Comment by JiniHendrix** [comment]
I am also seeing this issue

**Comment by chinesedfan** [comment]
@imjustzealous Thanks for your detailed codes. But I don't get the problem.

Seems that browser also prints the correct outputs, except that the log sequences are different with the Node.js side.
