### ISSUE TITLE
[Question] How to get responseUrl when handling errors?

### ISSUE THREAD

**Issue by Galaxy-Coding** [axios/axios#3808]
#### Describe the issue
When handling error how can i get the equivalent of `response.request.res.responseUrl` but when handling errors?
I want to get the responseUrl. 

#### Example Code
Code snippet to illustrate your question

```js
axios.get('/user?ID=12345')
  .then(function (response) {
    // handle success
    console.log(response);
  })
  .catch(function (error) {
    // this is where I want to get the responseUrl
  })
```

#### Environment
 - Axios Version: Latest
- Node 12.22.1

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by anderlaw** [comment]
In your case, you can use `error.config` and then retrieve what you want. You can also use a response interceptor  as well

**Comment by chinesedfan** [comment]
`response` is returned by your backend server. When errors happened, make sure it is also returned.

If returned, besides @anderlaw mentioned, you may also use `validateStatus` to allow bad http status like 401 to enter `then`.
