### ISSUE TITLE
Support large data (big data)

### ISSUE THREAD

**Issue by menphurk** [axios/axios#3812]
#### Describe the issue
Axios want support api large data in db muti table ?

#### Example Code
-

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Closing as this issue is not well explained.
