### ISSUE TITLE
Didn't take Generics in `isAxiosError()` for `AxiosError<any>`

### ISSUE THREAD

**Issue by latipun7** [axios/axios#3815]
#### Describe the issue
`axios.isAxiosError` is type predicated `isAxiosError(payload: any): payload is AxiosError;` in `node_modules/axios/index.d.ts` while `AxiosError` take generics default to `any`.

How can I make `isAxiosError` is predicated to `payload is AxiosError<Response>`?

#### Example Code
Code snippet to illustrate your question

```ts
interface Response {
  error: boolean;
  message: string;
  count?: number;
  hotels?: Hotel[];
}

// ...
catch (error: unknown) {
  if (axios.isAxiosError(error)) {
    if (error.response) {
      return error.response.data.message; // error now is AxiosError<any>, so the data is `any` which I don't want
    }
  }
}
```

#### Expected behavior, if applicable
I can type `AxiosError` with `AxiosError<Response>` generics with `isAxiosError` accept generics.

```js
// ...
catch (error: unknown) {
  if (axios.isAxiosError<Response>(error)) {
    if (error.response) {
      return error.response.data.message; // now this is return `string` from the Response interface
    }
  }
}
```

#### Environment
 - Axios Version [0.21.1]
 - Adapter [XHR/HTTP]
 - Browser [Microsoft Edge]
 - Browser Version [90.0.818.66]
 - Node.js Version [14.17.0]
 - OS: [WSL]
 - Additional Library Versions [Typescript 4.2.4]

#### Additional context/Screenshots
![](https://i.imgur.com/CftxDLn.png)

**Comment by Guuz** [comment]
Any updates on this?

**Comment by Argeento** [comment]
Clear PR #4344 

`AxiosError<T = any, D = any>` - now `T` and `D` type variables are supported in `isAxiosError` method
