### ISSUE TITLE
The axios instance sends an undefined data property to the server

### ISSUE THREAD

**Issue by sttatusx** [axios/axios#3828]
#### Describe the bug
**Hello**,
I tried to upgrade the **axios** package from version **0.18.1** to version **0.21.1**, but after that none of the requests were sent to the server correctly. And i guess the problem is with the undefined data property

#### To Reproduce
I used the below code to test the requests of both versions, but this code did not work in version 0.21.1

```js
const config = {
    method: 'post',
    timeout: 15000,
    data: { query: '{ post(id: 1){ title } }' },
    baseURL: 'https://graphqlzero.almansi.me/api',
}

const instance = axios.create(config)

instance()
  .then((res) => console.log(res.data.data))
  .catch((err) => console.error("error: ", err))
```

#### Environment
 - Axios Version 0.18.1 & 0.21.1
 - Adapter HTTP
 - Browser Any Browser
 - OS: Any OS

**Comment by imjustzealous** [comment]
Hello, I think the problem with the data being undefined, is because of this
```js
console.log(res.data.data);
```
Can you try this code below
```js
console.log(res.data);
```
I think there's a change in the response object on v. 0.21.1, so that's why it does not work when you use the latest version.

**Comment by imjustzealous** [comment]
Hello, may I ask what data you are referring to? Is the data that is undefined is on the response object? Or the data that is in the config object?

**Comment by Mahdhir** [comment]
@sttatusx 
Apparently the `data` property in the instance default is not being assigned to the request config.

I have managed to fix the issue.
Will do a PR after completing the tests.

**Comment by chinesedfan** [comment]
Yes, this is a breaking change. See https://github.com/axios/axios/issues/3579#issuecomment-770341715.

I think what users want is a request factory, instead of so-called inheritable instance. The workaround may be,

```
const instance = () => axios(config)
```

**Comment by sttatusx** [comment]
> Yes, this is a breaking change. See [#3579 (comment)](https://github.com/axios/axios/issues/3579#issuecomment-770341715).
> 
> I think what users want is a request factory, instead of so-called inheritable instance. The workaround may be,
> 
> ```
> const instance = () => axios(config)
> ```

Thank you very much for your answer, but this syntax did not solve my problem (maybe I wrote it wrong or whatever). But the important thing is that I need to use interceptors. Is it possible in this syntax?

**Comment by chinesedfan** [comment]
>  But the important thing is that I need to use interceptors. Is it possible in this syntax?

Of course, if you need **unified** interceptors,

```
const instance = () => {
   axios.interceptors.request.use(...)
   return axios(config)
}
```

And if not, please share more codes to show your requirements.
