### ISSUE TITLE
Issue replicating a `cURL` GET request.

### ISSUE THREAD

**Issue by goto1** [axios/axios#3830]
Hi!

First of all, thank you for this wonderful package, I appreciate all the work that has been put into it.

#### Describe the issue

I am having an issue replicating a `cURL` request with `Axios` and I cannot figure out what it is. The API endpoint I am calling is a 3rd-party API and the error message I am getting is very generic, so I am unable to pinpoint what the issue is: `400 - BAD REQUEST - Request Error (Invalid Request)`.

Everything appears to check out when I look at the headers of the request after I get the error.

I should also add that I am making a `POST` request to that same API but different endpoint and that appears to work just fine, so something about the `GET` that it doesn’t like.

#### Example Code

Here is the snippet code for a `cURL` request that works:

```sh
curl -X GET https://example.com/api/users/jeff@gmail.com
  -H ‘accept: application/json’ -H ‘accesstokenkey: KEY’ -H ‘accesstokensecret: SECRET’
```

Here’s the request with `Axios` in `Node.js` that doesn’t work:

```js
axios.get(“https://example.com/api/users/jeff@gmail.com”, {
  headers: { 
    accept: “application/json”,
    accesstokenkey: API_KEY,
    accesstokensecret: API_SECRET
  }
});
```

#### Expected behavior, if applicable
I expect the `Axios` request to work similarly to the `cURL` request, without getting the error message due to a bad request.

#### Environment
- `Axios v0.21.1`
- `Node.js v14.17.0`
- `Ubuntu 18`

#### Additional context/Screenshots
None at the moment.

—-

I’d really appreciate some help here - I’ve tried making the request multiple different ways but had no luck.

Thanks!

**Comment by diasbruno** [comment]
@goto1 Try to replace the `@` with `%40` (its encoded version).

**Comment by goto1** [comment]
@diasbruno replacing the `@` with the encoded version yields the same result. It’d be interesting to know what the difference is between `axios` call and the `cURL` request because `POST` request appear to work just fine, but I just tried another endpoint that’s a `GET` request and I am getting the same exact error.

I will try to reach out to the API owner and see if they can help.

Thanks!

**Comment by diasbruno** [comment]
Have you checked you request on any log on the server?

**Comment by diasbruno** [comment]
@goto1 You can run the cURL with `-vvv` and see the Network tab on the browser to see the difference.

**Comment by goto1** [comment]
@diasbruno that is correct, I am using `Node.js`. I’ve contacted the API’s owner to see what the issue is but it is strange nevertheless. 

Thanks for all your help so far.

**Comment by goto1** [comment]
Closing this as this appears to be an issue with the corporate proxy messing with my `GET` requests.
