### ISSUE TITLE
Axios returns 500 while requests returns 200

### ISSUE THREAD

**Issue by ventouris** [axios/axios#3839]
#### Describe the bug
I have a JS code using `requests` package and I try to rewrite everything with `axios` package. I pass a serialised protobuf object to a post request. However the exact same code in requests returns 200, while axios returns 500. 

When I inspect the actual request objects for both cases, it looks the passed requestBody doesn't have the exact same format.

In the case of request, it is like this:

`body: <Buffer 22 07 ... ... 396 more bytes>`

But in case of axios like this
```
data: ArrayBuffer {
  [Uint8Contents]: <22 07 ... ... 346 more bytes>,
  byteLength: 446
}
```
#### To Reproduce
I cannot paste the exact url since it is internal, but the code of requests and axios are this. The `requestBody` is Uint8Array I create with the data I need to send.

```
request({
  url: 'the_url',
  method: 'POST',
  encoding: null,
  headers: {
    'Content-Type': 'application/x-protobuf',
    'Connection': 'Keep-Alive',
    'Accept-Encoding': 'gzip',
  },
  body: requestBody,
}, callback);
```

and 

```
axios({
    url: 'the_url',
    method: 'POST',
    encoding: null,
    headers: {
      'Content-Type': 'application/x-protobuf',       
      'Connection': 'Keep-Alive',
      'Accept-Encoding': 'gzip',
    },
    data: requestBody,
  }
).then( (res) => {
  console.log(res);
}).catch( (error) => {
  console.log(error);
})
```

#### Expected behavior
I expected to get the same response in both cases.

#### Environment
 - Axios Version 0.21.1
 - Adapter [e.g. XHR/HTTP]
 - Node.js Version v12.13.1

#### Additional context/Screenshots
Nothing more to add here.

**Comment by dan-lutd** [comment]
I can open a new issue but it appears that I have the same issue as the OP.

This are tests passing a good token,  malformed token or expired token in the header.
When I pass a good header axios returns the expected result

When trying to use an expired or malformed header to run this query I get 500 error from Axios in my test code, but the expected error message when the equivalent is run in Postman.
`export const updateTokenApi = async (
  headers: any.  // I pass the token in headers
  ): Promise<AxiosResponse<any>> => {
    console.log("in updateTokenAPI")
    return await axios.post(
      API_URL,
      {
        query: `
        mutation {
          updateToken 
            {
              accessToken
          }
        }
      `
      },
      headers
    )
  }`


and in Postman:
mutation {
          updateToken 
            {
              accessToken
          }
 }

both attempts use the same header and the attempt to verify the token throws a **JsonWebTokenError** from jsonwebtoken.

I catch the **JsonWebTokenError** and change the error message as needed.
I get this error essage when using Postman and a 500 error when using axios
