### ISSUE TITLE
 Axios doesn't see the User-agent header

### ISSUE THREAD

**Issue by Viiprogrammer** [axios/axios#3844]
#### Describe the bug
Axios doesn't see the `User-agent` header

#### To Reproduce
```js
const axios = require('axios');

axios.get('https://postman-echo.com/get', {
	headers: {
		'User-agent': 'USER'
	},
})
.then(function (response) {
	console.log(response.data.headers['user-agent']); //Returns - axios/0.21.1
})
```

```js
const axios = require('axios');

axios.get('https://postman-echo.com/get', {
	headers: {
		'User-Agent': 'USER'
	},
})
.then(function (response) {
	console.log(response.data.headers['user-agent']); //Returns - USER
})
```

```js
const axios = require('axios');

axios.get('https://postman-echo.com/get', {
	headers: {
		'user-agent': 'USER'
	},
})
.then(function (response) {
	console.log(response.data.headers['user-agent']); //Returns - USER
})
```

#### Expected behavior
```js
axios.get('https://postman-echo.com/get', {
	headers: {
		'User-agent': 'USER'
	},
})
.then(function (response) {
	console.log(response.data.headers['user-agent']); //Returns - USER
})
```

#### Environment
 - Axios Version [0.21.1]
 - Adapter [none]
 - Browser [none]
 - Browser Version [none]
 - Node.js Version [v15.12.0]
 - OS: [Windows 7]
 - Additional Library Versions [none]

#### Additional context/Screenshots
None

**Comment by lichader** [comment]
@Viiprogrammer 
Based on this [line](https://github.com/axios/axios/blob/master/lib/adapters/http.js#L58), Please use **User-Agent** or **user-agent.**

**Comment by Viiprogrammer** [comment]
@lichader 

If you read https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers, then the title of the headers should not be case-sensitive.

The axios documentation does not specify that the headers are case sensitive.

**Comment by lichader** [comment]
Yes. I was just stating the current behaviour, which doesn't mean I think this behaviour is correct. HTTP headers should be case insensitive.

**Comment by jasonsaayman** [comment]
Closed see above
