### ISSUE TITLE
Issue with difference in default behaviour between axios and axiosInstance when content-type is not set (specific case of multipart-/form-data)

### ISSUE THREAD

**Issue by SankethBK** [axios/axios#3857]
I know similar issue has came up multiple times. This one is different. 
#### Describe the bug

**In short** i have to post an image to server using axiosInstance (not axios. Because i have interceptors attached to axiosInstance which manages JWT tokens). When i try to post multipart/form-data (an image) i have to somehow set Content-Type: 'multipart/formdata; boundary: --calculated dynamically'. Now in order to force axios to calculate the boundary i have to just ignore the content-type in my headers, doing so will work in axios, not in axiosInstance. If we ignroe Content-type in axiosInstance it will put "application/x-www-form-urlencoded" which won't be parsed in backend. 

#### To Reproduce

I have mentioned my case in detail below but in order to repreduce it upload an image with no content-tyoe set from axiosInstance and axios. Difference is axiosInstance will set the content-type to -'www-form-urlencoded' (undesired in my case) and axios will set the content-type to 'multipart/form-data ; boundary: calculared dynamically' (which is desired). But i am forced to use axiosInstance as it has an interceptor which manages JWT tokens.  

#### Expected behavior

I expected the axiosInstance to set Content-Type to multipart / form-data when Content-Type is not provided (in this case) as using axios will set the Content-Type to multipart. Why axios and axiosInstance behave differently when Content-Type is not provided?

#### Environment
Axios version: "axios": "^0.20.0"
"react": "^17.0.2",

#### Additional context/Screenshots
Apologies, this will be long but i will post everything in detail. 

You don't need to read entire code i will post summary of each file and screenshot below it. 

First my axios.js file 

```
import axios from 'axios';
import { BACKEND_URL } from './config';
import { store } from './redux/store';
import { setLoginFalse } from './redux';

const baseURL = BACKEND_URL;

const axiosInstance = axios.create({
  baseURL: baseURL,
  timeout: 360000,
  transformRequest: [
    function (data, headers) {
      const accessToken = window.localStorage.getItem('access_token');
      if (accessToken) {
        headers['Authorization'] = `Bearer ${accessToken}`;
      } else {
        delete headers.Authorization;
      }

      return JSON.stringify(data);
    },
  ],
  headers: {
    'Content-Type': 'application/json',
    accept: 'application/json',
  },
});

// handling the expiry of access tokens through response interceptors

axiosInstance.interceptors.response.use(
  (response) => {
    return response;
  },
  async function (error) {
    const originalRequest = error.config;

    console.log(
      'Caught the error response. Here is your request  ',
      originalRequest,
    );

    // case 1: No error specified Most likely to be server error

    if (typeof error.response === 'undefined') {
      //  Uncomment this later
      alert('Server error occured');

      return Promise.reject(error);
    }

    //  case 2: Tried to refresh the token but it is expired. So ask user to login again

    if (
      error.response.status === 401 &&
      originalRequest.url === baseURL + 'auth/api/token/refresh/'
    ) {
      alert('token refresh failed');
      store.dispatch(setLoginFalse());
      return Promise.reject(error);
    }

    // Case 3: Got 401 Unauthorized error. There are different possiblities
    console.log('Error message in axios = ', error.response.data);
    if (
      error.response.status === 401 &&
      error.response.statusText === 'Unauthorized'
    ) {
      const refreshToken = localStorage.getItem('refresh_token');
      console.log('Refresh token = ', refreshToken);

      // See if refresh token exists
      // Some times undefined gets written in place of refresh token.
      // To avoid that we check if refreshToken !== "undefined". This bug is still unknown need to do more research on this

      if (refreshToken !== undefined && refreshToken !== 'undefined') {
        console.log(typeof refreshToken == 'undefined');
        console.log('Refresh token is present = ', refreshToken);
        const tokenParts = JSON.parse(atob(refreshToken.split('.')[1]));

        // exp date in token is expressed in seconds, while now() returns milliseconds:
        const now = Math.ceil(Date.now() / 1000);
        console.log(tokenParts.exp);

        // Case 3.a Refresh token is present and it is not expired - use it to get new access token

        if (tokenParts.exp > now) {
          return axiosInstance
            .post('auth/api/token/refresh/', { refresh: refreshToken })
            .then((response) => {
              localStorage.setItem('access_token', response.data.access);

              axiosInstance.defaults.headers['Authorization'] =
                'Bearer ' + response.data.access;
              originalRequest.headers['Authorization'] =
                'Bearer ' + response.data.access;

              console.log('access token updated');

              // After refreshing the token request again user's previous url
              // which was blocked due to unauthorized error

              // I am not sure by default axios performs get request
              // But since we are passing the entire config of previous request
              // It seems to perform same request method as previous

              return axiosInstance(originalRequest);
            })

            .catch((err) => {
              // If any error occurs at this point we cannot guess what it is
              // So just console log it

              console.log(err);
            });
        } else {
          // Refresh token is expired ask user to login again.

          console.log('Refresh token is expired', tokenParts.exp, now);
          store.dispatch(setLoginFalse());
        }
      } else {
        // refresh token is not present in local storage so ask user to login again

        console.log('Refresh token not available.');
        store.dispatch(setLoginFalse());
      }
    }

    // specific error handling done elsewhere
    return Promise.reject(error);
  },
);
export default axiosInstance;
```

Important things to be noted from this file 

- I am setting content-type to 'application/json' by default , i have to do this otherwise formdata will be set to application/x-"www-form-urlencoded" which is undesriable. 
- I have an interceptor tied to axiosInstance which manages tokens related to JWT authentication. So i am forced to use this axiosInstance everywhere else in the code. (If i make request using fetch or directly from axios it won't be intercepted by this interceptor). 

Now i will make a request from postman to show that my backend is working porperly .

We can see that postman successfully uploaded image with multiport form-data.

![image](https://user-images.githubusercontent.com/51091231/123457498-9c44d480-d601-11eb-9124-543423cb1982.png)

Postman using multipoort form data 

![image](https://user-images.githubusercontent.com/51091231/123457749-dd3ce900-d601-11eb-8242-4e974ca50ba4.png)

In server side also it is correctly parsed. (Django server)

![image](https://user-images.githubusercontent.com/51091231/123458031-2db44680-d602-11eb-8937-930d3c340208.png)

Now i will upload the same image from react. 

First i will upload using fetch to see how fetch correctly sets headers (But i can't handle authentication with fetch)

```

function ProfilePicUpload(props) {
  let { profile_pic } = props;

  const [loading, setLoading] = useState(false);
  const [file, setFile] = useState();

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(file);

    let formData = new FormData();
    formData.append('profile_pic', file, file.name);
    console.log('DnKLS = ', formData._boundary);

    var myHeaders = new Headers();
    myHeaders.append(
      'X-CSRFToken',
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIyMzg4MDk5LCJqdGkiOiJlMzU5MjI1YWU1OTk0ZDZjYTdiZmI2NDU1OGEwZjgyZSIsInVzZXJfaWQiOjR9.3UefTMWAuh0ZLUnI5GNNDwg4GwwECzWAhN5TBy3xzvg',
    );
    myHeaders.append(
      'Authorization',
      'Bearer ' + localStorage.getItem('access_token'),
    );

    var formdata = new FormData();
    formdata.append('profile_pic', file);

    var requestOptions = {
      method: 'PUT',
      headers: myHeaders,
      body: formdata,
      redirect: 'follow',
    };

    fetch('http://127.0.0.1:8000/users/profile-pic-upload/', requestOptions)
      .then((response) => response.text())
      .then((result) => console.log(result))
      .catch((error) => console.log('error', error));
```
Summary of this file 

- Fetch takes a react state file , and posts it to the URL. 

Request headers of fetch captured by network tab 
![image](https://user-images.githubusercontent.com/51091231/123459065-6b659f00-d603-11eb-86ca-54429f21758e.png)

We can see fetch correctly set the headers and it was correctly parsed in server. 
![image](https://user-images.githubusercontent.com/51091231/123459179-92bc6c00-d603-11eb-948c-c401c3f74df6.png)

**_Now I will try with the axiosInstance that was defined above._** 

Note: I will remove Content-Type: 'application/json' as i have to force the axios to set it to multipart / form-data and calculate the boundary dynamically. 

```
const axiosInstance = axios.create({
  baseURL: baseURL,
  timeout: 360000,
  transformRequest: [
    function (data, headers) {
      const accessToken = window.localStorage.getItem('access_token');
      if (accessToken) {
        headers['Authorization'] = `Bearer ${accessToken}`;
      } else {
        delete headers.Authorization;
      }

      return JSON.stringify(data);
    },
  ],
  headers: {
    // 'Content-Type': 'application/json',
    accept: 'application/json',
  },
});
```
Summary of above file 

- I commented Content-Type in header. 

Now i make the same request using axiosInstance. 

This is the code (shortened) 
```

    let formData = new FormData();
    formData.append('profile_pic', file, file.name);

    axiosInstance
      .put('/users/profile-pic-upload/', formData)
      .then((res) => console.log(res))
      .catch((err) => console.log(err));
```

Since my interceptor catches error i can nicely display it. We can see that content-type is set to "www-form-urlencoded" instead of expected "multipart/form-data" 

![image](https://user-images.githubusercontent.com/51091231/123459959-97cdeb00-d604-11eb-86fb-7e6a0366bde1.png)

But this doesn't seems to be the problem if i directly use a new axios instead of axiosInstance. 

```
    axios
      .put('http://127.0.0.1:8000/users/profile-pic-upload/', formData)
      .then((res) => console.log(res))
      .catch((err) => console.log(err));
```

Since i disabled authentication some functionaities got broken. But i can show that the content-type was set correctly and it was parsed by the backend. 

![image](https://user-images.githubusercontent.com/51091231/123460934-065f7880-d606-11eb-9109-c8c6bb108467.png)

 
 Please suggest any fix for this, been struggling for quite  some time now. Thanks in advance.

**Comment by IgorVanian** [comment]
Hi, we have the same problem with 0.21.1 but trying to POST an object (application/json) instead of formdata.
We use interceptors and at the beginning of the req interceptor, config is already 'x-www-urlencoded' by default, even when the data prop contains a valid JSON.

**Comment by SankethBK** [comment]
@IgorVanian Can give more information, i think i had similar issue. In any case are you using transformRequest?

**Comment by IgorVanian** [comment]
> @IgorVanian Can give more information, i think i had similar issue. In any case are you using transformRequest?

No, not using transformRequest, just plain req interceptor.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
