### ISSUE TITLE
Add CDN example usage

### ISSUE THREAD

**Issue by GustavoOS** [axios/axios#3867]
#### Section/Content To Improve
Example or Getting Started
#### Suggested Improvement
Add HTML Template with script tags, using AXIOS installed via CDN.
This could help potential users to avoid the error "ReferenceError: axios is not defined".
This could be implemented smiliar to [Bootstrap's docs](https://getbootstrap.com/docs/5.0/getting-started/introduction/#starter-template)

#### Relevant File(s)
README.md

**Comment by ranjan-purbey** [comment]
You can see CDN usage here: https://github.com/axios/axios#installing
Please close the issue if your query is answered

**Comment by GustavoOS** [comment]
Although it written the script tag of installation, every other example (such as the Get request) is NodeJS specific, for the usage of the require method. As browsers don't use this method, incorrect placing of the script tag may result in a asynchronous loading of the library and the usage script, causing the the user script to fail, causing a reference error. My request is for a simple HTML template that loads the library and uses this library within the HTML file in order to avoid this error. That's why the current documentation doesn't apply to my request.
