### ISSUE TITLE
Axios Request Params not working with URLSearchParams in Safari 13

### ISSUE THREAD

**Issue by kun-woo** [axios/axios#3868]
#### Describe the issue
I found Axios does not assign an URLSearchParams object to its request config params in Safari 13.
When executing `axios.get(url, { params: params })`, I see Axios making the Get request without query parameters.

#### Example Code
```js
//axios setting
const api_local = axios.create({
   baseURL: 'http://localhost:1000/myapi',
});
api_local.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded'; 

//URLSearchParams setting
const params = new URLSearchParams();
params.append('PARAM1', 'VALUE1');
params.append('PARAM2', 'VALUE2');

//make GET request
const URL = '/products'
api_local.get(URL, { params });
```

#### Expected behavior, if applicable
Axios makes the GET request using the URL with query parameters.

#### Environment
 - Axios Version [0.21.1]
 - Browser [Safari]
 - Browser Version [13.0.1]
 - OS: [iOS 13.0.1]

#### Additional context/Screenshots
I know **Axios browser support is limited to the latest version of Safari (14)** so, if this issue is irrelevant, please let me know.

**Comment by zacharytyhacz** [comment]
@judeWoo 

I have always used just a regular object for `params` which has never failed me. Have you tried the following?

```javascript
const params = {
    PARAM1: 'VALUE1',
    PARAM2: 'VALUE2'
}

const URL = '/products'
api_local.get(URL, { params });
```

**Comment by judeWoo** [comment]
@zacharytyhacz 

A regular object works but that is not my use case here. I wanted to use URLSearchParams objects for params.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by kun-woo** [comment]
@jasonsaayman Okie, will do 👍
