### ISSUE TITLE
`transport` not in `AxiosRequestConfig` TS definitions.

### ISSUE THREAD

**Issue by necessary129** [axios/axios#3876]
#### Section/Content To Improve
`AxiosRequestConfig` doesn't have `transport` as an option but it was added in #1080.

#### Suggested Improvement
Add type definitions for `transport` and add it to `AxiosRequestConfig`. 

I would add it but I am not that proficient in TS yet.

#### Relevant File(s)
[`index.d.ts`](https://github.com/axios/axios/blob/master/index.d.ts#L50-L81)

**Comment by Netlob** [comment]
Any progress on this? Would love to stop using @ts-ignore :p

**Comment by stingalleman** [comment]
Hey, also having issues with this. Can this be fixed? I tried fixing it myself but I don't really know what the types of `transport` are.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
