### ISSUE TITLE
Response interceptor not containing response info

### ISSUE THREAD

**Issue by SevenOutman** [axios/axios#3877]
#### Describe the bug
Response interceptors are supposed to be triggered when there is problem with the response as [documented](https://github.com/axios/axios#interceptors). But an offline network condition - which caused a failed request - somehow triggered the response interceptor, resulting in `err.response` to have `undefined` value.

#### To Reproduce
1. Register the interceptor as shown below
2. Simulate offline network condition in Chrome DevTools
3. Make a request with axios

```js
axios.interceptors.response.use(null, (thrown) => {
  console.log({ ...thrown }); // thrown.response is `undefined`
  
  switch (thrown.response.status) { // ⚠️ throwing Error!
    // ...
  }
});
```

#### Expected behavior
`thrown.response` should be guaranteed to exist in a response interceptor.

#### Environment
 - Axios Version 0.21.1
 - Adapter XHR
 - Browser Chrome
 - Browser Version 91
 - OS: macOS 11.2.3
 - Additional Library Versions React 16.13.1

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/8225666/124217954-dba48100-db2b-11eb-9735-c27b65b575c0.png)

**Comment by shmilyoo** [comment]
+1
Just like fetch errors caused by network outages, dns resolution errors, request timeouts, etc.
These errors are caught in the axios interceptor, not the reqeust interceptor, but in the interceptor of the response.
```
// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    return response;
  }, function (error) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
    return Promise.reject(error);
  });
``` 
Here the error.response result is empty and the type of error is not Error

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by v1talii-dev** [comment]
I'm seeing the same error. The only difference with the current implementation is that I additionally use the library interceptor https://github.com/Flyrell/axios-auth-refresh. Are there any updates on this issue?

**Comment by anyamiletic** [comment]
Issue still persist with axios version 1.4.0

![Screenshot 2023-06-28 at 16 35 11](https://github.com/axios/axios/assets/31810954/e3214264-fae4-4b66-a11e-ebccf2d7bdc2)

**Comment by FlorianRuen** [comment]
Why this issue has been closed ? There is a fix ? Because I'm facing the same issue with the latest version

**Comment by Endarg** [comment]
Same thing for me on 1.6.5
error.responce is undefined

If you want to read status of an error, read
error.toJSON().status 
It worked for me
