### ISSUE TITLE
Timeout issue linked to high level of concurrency 

### ISSUE THREAD

**Issue by gchicoye** [axios/axios#3883]
#### Describe the bug
I've set up a nodeJS server which basically receives an ad request, sends ad requests through Axios to multiple endpoints with a timeout (usually 1000 ms), and then parse and sends back all results. 
On each pod around 600 requests per minutes are performed to various external endpoints .
When we start the pod, requests run pretty well at the beginning, than after 1 or 2 minutes, all requests returns as timed out... 

I use Promise.all to manage concurrency requests, you'll find below the adapterRequest component in charge of sending requests.
I also try to send some data within my cluster, I also get a timeout, which makes me confident on the fact that the issue is linked to Axios.

#### To Reproduce
I create promise arrays thanks to the following module, than I use Promise.all to fetch data

```
const axios = require('axios');
const fakeServer = require('../test/fake-server');

let promiseCount = 0;

module.exports = (ssp, payload, endpoint, method, timeout) => new Promise((resolve) => {
  const cmd = process.env.NODE_ENV === 'test' ? fakeServer : axios;
  const start = Date.now();
  const config = {
    ssp,
    url: endpoint,
    method,
    timeout,
    header: {
      'Content-Type': 'application/json; charset=utf-8',
      Accept: 'application/json',
      Connexion: 'keep-alive',
    },
    data: payload,
  };
  cmd(config)
    .then((response) => {
      promiseCount += 1;
      console.log(ssp, 'RESPONSEOK', promiseCount);
      resolve({
        ssp,
        uri: config.url,
        requestbody: payload,
        requestheaders: config.header,
        responsebody: response.data,
        status: response.status,
        responsetimemillis: Date.now() - start,
      });
    })
    .catch((error) => {
      promiseCount += 1;
      console.log(ssp, error.code, promiseCount);
      let responsebody;
      let status;
      if (error.response === undefined) {
        responsebody = undefined;
        status = undefined;
      } else {
        responsebody = error.response.data ? error.response.data : error.message;
        status = error.response.status;
      }
      resolve({
        ssp,
        uri: config.url,
        requestbody: payload,
        requestheaders: config.header,
        responsebody,
        status,
        responsetimemillis: Date.now() - start,
      });
    });
});
```

#### Expected behavior
I expect no timeout to occur

#### Environment
- Axios Version: 0.21.1
- Node.js Version: v14.17.1
- OS: Alpine Linux v3.11

#### Additional context/Screenshots

Nothing in particular

**Comment by baheego** [comment]
> @gchicoye are you using Digital Ocean ?

I am, dealing with this same issue right now.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
