### ISSUE TITLE
Deflate fails on server response without zlib header

### ISSUE THREAD

**Issue by Semptic** [axios/axios#3887]
#### Describe the bug
Some servers are not sending a zlib header in their deflated data. CURL had the same problem and implemented a "fix" for it: https://github.com/curl/curl/blob/5c932f8fe9dad94a7417702958ffa9e8db67c549/lib/content_encoding.c#L227-L229

Axios is also returning a `Z_DATA_ERROR` in this case.

#### To Reproduce

Use axios to request a page without a zlib header in the deflated data (e.g. https://www.konicaminolta.eu/eu-en/about-us/corporate-book) and force it to only accept deflate encoding.

```js
let url = 'https://www.konicaminolta.eu/eu-en/about-us/corporate-book';
let config = {
  headers: { 'Accept-Encoding': 'deflate' }
};

await axios.get(url, config);
```

#### Expected behavior

Getting the correctly inflated data.

#### Environment
 - Axios Version [0.21.1]

**Comment by imjustzealous** [comment]
I tried to reproduce the code above, and as it turns out, the server returns `content-encoding: deflate`, even though the browser detected it as a text/html type.

**Comment by daniel-julius-sam** [comment]
I'm getting the data properly. Try doing it again.

**Comment by daniel-julius-sam** [comment]
When i tried to do this operation, what I found is that sometimes the response is successful, but sometimes it is not working and is showing the `Z_DATA_ERROR` as you mentioned. Here's a link to the request showing status 200. [https://imgur.com/qlf8EME](url), and this is the data it's giving: [https://imgur.com/PGwlQoR](url)
