### ISSUE TITLE
Are `errno` codes documented?

### ISSUE THREAD

**Issue by adams-family** [axios/axios#3897]
#### Section/Content To Improve
I'd like to know if `errno` codes of exceptions thrown by `axios` are documented?

E.g.:
```
Error: write EPROTO 140040654010176:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 40

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
  errno: -71,
  code: 'EPROTO',
  syscall: 'write'
```

#### Suggested Improvement
I cannot find `errno` codes explained.

#### Relevant File(s)
Not any at the moment

**Comment by vvrmc** [comment]
"Errno" are errors from system calls. They are not specific to axios, or nodejs. You can find a definition of them [here](https://www.man7.org/linux/man-pages/man3/errno.3.html).

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
