### ISSUE TITLE
Axios with multiple accept header values

### ISSUE THREAD

**Issue by paulalex** [axios/axios#3901]
#### Describe the issue
This is just a question about the behaviour of Axios. Should it work with multiple accept content types?

I have an API that can return multiple types, text/csv except when an error occurs, at which point json is returned. 

When a CSV file is returned and the content type is `text\csv` the file is automatically decoded by the browser as csv, but if I give axios multiple mime types then it no longer decoded.

If I remove the accept header completely then Axios sends three: `application/json`, `text/plain` and `*/*`, why does it add all three by default, why not just add `*/*`?

Is this the expected behaviour?

#### Example Code
Any request that sets two mime types using accept headers, e.g

`Accept: text/csvl, application/json`

#### Expected behavior, if applicable
For axios to respect whatever the server sets as the response content type instead of always choosing the first mime type it is passed.

For a csv file to be decoded when the response content type is csv, and the accept headers contain csv. This works if the only type supplied to axios is csv, if I supply two types then the CSV is no longer decoded.

This might not be specific to axios but I cannot really understand why this works as expected with only a single mime type or why axios by default (no header supplied) then sends three mime types as headers.

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by daniel-julius-sam** [comment]
It's not possible to have multiple headers for a single http request. For more info check this answer from stackoverflow: [https://stackoverflow.com/questions/5809099/does-the-http-protocol-support-multiple-content-types-in-response-headers](url)

**Comment by paulalex** [comment]
Ok, but I am talking about the accept header... and that an endpoint supports multiple content types but not simultaneously.. so as I mentioned, when all things are well then a csv file is returned, but when it is not then a json error is returned.

Setting multiple `Accept` headers at the client means I expect to get either back.

**Comment by daniel-julius-sam** [comment]
When you give multiple mime types in the accept header, the normal behavior is that the response type is decided by the server. So it must be a bug from axios. Yes, by default axios needs to send only the */* type.

**Comment by daniel-julius-sam** [comment]
I have created a pull request after changing the default `Accept` header values and changed it to include only `*/*`.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
