### ISSUE TITLE
Export mergeConfig

### ISSUE THREAD

**Issue by feO2x** [axios/axios#3905]
#### Is your feature request related to a problem? Please describe.

We have a web frontend that supports multi-tenancy by contacting different backends depending on the data that was loaded by the 'main' backend. We manage several instances of `AxiosRequestConfig` to handle all the configuration parameters for the different backend services (usually default config per service which is then merged with per request config). We currently create an instance per request with the default config and then pass our request-specific config to `get`, `post`, and so on. We tried to use a singleton `AxiosInstance` per backend service, but this resulted in HTTP requests being performed one after the other instead of in parallel, which is not what we wanted.

#### Describe the solution you'd like

Our solution would be easier maintainable and testable if we could manage and merge the `AxiosRequestConfig` by ourselves. We would need access to the `mergeConfig` method, which unfortunately is not exported by default. 

#### Describe alternatives you've considered

We can do a deep import now, but need to create a separate TS module for that to work in our TypeScript-based projects. Alternatives are using an Axios instance per request as described in the first section.

#### Additional context

None.

**Comment by unrealsolver** [comment]
I resolved it in such way (TS/NodeJS):
```javascript
const mergeConfigs = require('axios/lib/core/mergeConfig.js');
```

**Comment by hedgepigdaniel** [comment]
+1, it would be very useful to be able to see the merged config without making a request.

**Comment by jie-huang** [comment]
With version 1.2.1, typescript project cannot use mergeConfig yet with

```
import { mergeConfig } from 'axios';
```

Can axios export `mergeConfig` in index.d.ts file too?
Thanks

**Comment by jan-molak** [comment]
@jie-huang `mergeConfig` is not defined in type definitions, but you can import it like this until it (hopefully) gets fixed:
```typescript
const { mergeConfig } = require('axios');      // eslint-disable-line @typescript-eslint/no-var-requires
```
