### ISSUE TITLE
getting double base urls with Axios in quasar

### ISSUE THREAD

**Issue by rykr** [axios/axios#3909]
Juts upgrading a project from quasar 1 to 2.  Have a simple Axios integration but have isolated the problem to an even smaller example.

I have a boot.ts file exports a boot function like this:

export default boot(() => {
  axios.defaults.baseURL = process.env.REMOTE;
  void axios.get('/user/renewToken')
    .then((response) => {
      console.log('got response');
      console.log(response);
    });
});

I have verified that process.env.REMOTE has the correct url which is http://localhost:8081
however, when this executes I see this error on the console  http://localhost:8080/%22http://localhost:8081%22/user/renewToken

if I pass in an absolute patch to .get() then it works as expected.  I can see no reason why http://locallhost:8080 would be coming in but it is. 

What am I missing?

**Comment by novecento** [comment]
Have you solved?

**Comment by mijaelsaban** [comment]
same here
