### ISSUE TITLE
Axios returns string instead of JSON if json string contains tab characters

### ISSUE THREAD

**Issue by LeslieMurphy** [axios/axios#3917]
#### Describe the bug
Axios returns string instead of JSON if json string contains tab characters

If response includes \t inside a quoted string value, Axios returns a string object instead of a parsed Javascript object.

#### To Reproduce

if response from server is
{"status":"success","cmd":"set 	Report ONE"}
(tab between set and Report)

Axios returns a string. response.status === undefined

if response from server is
{"status":"success","cmd":"set Report ONE"}
(no tabs)

Axios returns a JS object with values such as response.status === "success" and response.cmd as expected
Version 0.21.1

```js
// Example code here
```

#### Expected behavior

Tabs should not cause the parser to fail

#### Environment
 - Axios Version 0.21.1
 - Adapter [e.g. XHR/HTTP]
 - Browser Edge 
 - Browser Version 91.0.864.71
 - Node.js Version 16.4.2
 - OS:  Windows 10 21H1
 - Additional Library Versions N/A

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ranjan-purbey** [comment]
I was unable to reproduce this issue. It could probably be a server side issue. For the same request (one with tab) do you get a JSON if you use browser `fetch` instead of `axios`?

**Comment by ranjan-purbey** [comment]
Thanks @LeslieMurphy for the reproducible example. I can see that the response your API sends is not a valid JSON:
```
{
"responseCode": "O
K",
"type":"test"
}
```
It will throw an error if you try to parse it using any JSON parser, for example `JSON.parse`. In order to make it a valid JSON, you need to first pass it through a JSON serializer, for example `JSON.stringify` after which you'll get something like:
```
{
  "responseCode": "O\nK",
  "type": "test"
}
```
Note how the actual newline character has been serialized to `\n`

**Comment by LeslieMurphy** [comment]
Great!  Thank you., That is perfect.

Is this the main website? https://axios-http.com/

I don't see this option documented!

**Comment by jasonsaayman** [comment]
Will update the docs soon

**Comment by bdtren** [comment]
I'm using `react-native 0.73.6` and `axios 1.7.3`.

In my case, I replicated this issue when using:
```
const api = new axios.Axios({...});
```

The issue is gone after I changed it to:
```
const api = new axios.create({...});
```

**Comment by bdtren** [comment]
I'm using `react-native 0.73.6` and `axios 1.7.3`.

In my case, I replicated this issue when using:
```
const api = new axios.Axios({...});
```

The issue is gone after I changed it to:
```
const api = axios.create({...});
```

**Comment by Code-Victor** [comment]
@bdtren Thanks! 
This worked for me too
