### ISSUE TITLE
HTTPS GET on PDF returns blank pages, but functions normally with HTTP

### ISSUE THREAD

**Issue by yetitech-david** [axios/axios#3927]
#### Describe the issue
I am using axios to retrieve a PDF file from a given URL. It functions correctly when passing through an HTTP URL, but  when using HTTPS, the resulting PDF has the correct page count but every page is completely blank

#### Example Code

```js
const data = await axios({
      url: url,
      method: 'get',
      responseType: 'blob',
      headers: {},
    }).then((response) => {
      return response.data;
    });
```

#### Expected behavior, if applicable
The response should be a string version of the PDF, which is passed through a buffer and stored in a database as a PDF file, which works fine when given an HTTP URL, but not when an SSL certificate is introduced

#### Environment
 - Axios Version 0.21.1
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 91.0.4472.114
 - Node.js Version v14.17.1
 - OS: Linux Mint 20.1 Cinnamon
 - Additional Library Versions React 16.14.0

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by anshul2807** [comment]
I'm going to work on this issue.

**Comment by kanatBektursyn** [comment]
Looks like subsequent issue after this one #3526

**Comment by jasonsaayman** [comment]
This should work, please retry with the latest version and open a new issue if it is still not working

**Comment by heremamit** [comment]
set responseType as 
responseType: 'arraybuffer',

**Comment by spiritcoder** [comment]
> set responseType as responseType: 'arraybuffer',

thanks for this.

**Comment by christianbrusa** [comment]
> set responseType as responseType: 'arraybuffer',

thanks a lot for this <3
