### ISSUE TITLE
unescape 和 encodeURIComponent

### ISSUE THREAD

**Issue by shihaidong** [axios/axios#3929]
#### Section/Content To Improve
https://github.com/axios/axios/blob/e9965bfafc82d8b42765705061b9ebe2d5532493/lib/adapters/xhr.js#L27

#### Suggested Improvement
为什么不用decodeURIComponent 配合 encodeURIComponent呢？

#### Relevant File(s)
[e.g. README.md]

**Comment by jasonsaayman** [comment]
Closing this is not a well formed issue report
