### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by koh110** [axios/axios#3930]
#### Describe the issue
I found this issue. Is the project in a similar situation to this?
https://github.com/axios/axios/issues/1965
> Is the project dead? Are new maintainers sought?

Does the project need help or new maintainers?

Can I do anything to help for axios?

I sent a [PR](https://github.com/axios/axios/pull/3916) a few days ago.
This bug is a blocker for using with Node.js v14.

However, there is no response from the maintainers.
And, CI seems to be broken.
https://github.com/axios/axios/issues/3718

I want to decide if I should replace axios with another module. I would like to continue using it if possible.
(I have been using axios for a long time, so I like axios.）

#### Example Code

```js
// Example code here
```

#### Environment
 - Axios Version [0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots

https://github.com/axios/axios/issues/1965
https://github.com/axios/axios/pull/3916
https://github.com/axios/axios/issues/3718

**Comment by kuasha420** [comment]
Absolutely dead. My best decision was switching to got. Unresponsiveness from maintainers and even PRs get ignored. SAD

**Comment by koh110** [comment]
@jasonsaayman Thank you. I appreciate [it](https://github.com/axios/axios/pull/3938).
I'm glad that the axios project is still working!

**Comment by jasonsaayman** [comment]
Thanks, I will be working on the project actively, please tag me if you need me to look at anything
