### ISSUE TITLE
Cancel Reqest via Token not working on POST & PUT request

### ISSUE THREAD

**Issue by phoenix503** [axios/axios#3931]
#### Describe the bug
I am not able to cancel the POST request via source token , though the code is written as per the Documentation guidelines

#### To Reproduce
Try Any type of POST request & cancel it while file uploads

 ```
 return axios.put(metaData.upload_url, formData, {
                    headers: headers,
                    onUploadProgress: (progressEvent) => {
                        console.log(progressEvent);
                        this.setProgress(progressEvent, fileId);
                    },
                    cancelToken: this.cancelTokenSource.token,
                });
```

#### Expected behavior
It should cancel the POST request File Upload

#### Environment
 - Axios Version 0.21.1
 - Adapter : HTTP
 - Browser : Chrome
 - Browser Version : 91
 - Node.js Version :  v12.15.0
 - OS: Chrome Android
 - Additional Library Versions : Angular 8

#### Additional context/Screenshots
On calling the `source.cancel() `, i can even see all the upload Progress going on as it is

**Comment by BrenoMazieiro** [comment]
I have the same problem with put.
