### ISSUE TITLE
Publish a new version to NPM

### ISSUE THREAD

**Issue by christemple** [axios/axios#3932]
#### Describe the issue
I need Axios to `JSON.stringify` by default as advertised, however it only does so if it detects the request payload is of type `object`, which is according to the [JSON spec](https://www.json.org/json-en.html) is invalid behaviour, a payload of type `String` is also valid JSON.

There is however already a fix to address this: https://github.com/axios/axios/blob/master/lib/defaults.js#L59

I'm happy to set this header so that `JSON.stringify` is always done by axios when needed.
However the latest version of the axios package `0.21.1` was published 7 months ago (Dec-Jan) and does not include these changes.
Can we get new release of the axios package please?
Is there anything I can do to help this along?

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
```

#### Expected behavior, if applicable
I want axios to JSON.stringify if I specify the content-type as application/json, not based on whether I'm passing an object or not

#### Environment
 - Axios Version [e.g. 0.21.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by christemple** [comment]
In the meantime, if anyone comes across this same issue and needs a temporary fix:
```js
const convertStringPayloadsToJSON = (data, headers) =>
  typeof data === 'string' && headers['Content-Type'] === 'application/json'
    ? JSON.stringify(data)
    : data;

const api = axios.create({
  ...,
  headers: { 'Content-Type': 'application/json' },
  transformRequest: [convertStringPayloadsToJSON],
});

export default api;
```

**Comment by jasonsaayman** [comment]
I have released a new version today that includes these fixes 😃
