### ISSUE TITLE
Use unknown type instead of any for Typescript definitions of response types

### ISSUE THREAD

**Issue by AsazuTaiga** [axios/axios#3933]
#### Is your feature request related to a problem? Please describe.
I strongly sympathize with issue #3313, which was closed by BOT, and feel that it is an issue worth considering, so I will raise another issue with the same content.

#### Describe the solution you'd like
I think that the type argument of the response should be changed from `<T = any>`  to `<T = unknown>`.

```ts
// <T = any>
const asyncFunction = async () => {
  const response = await axios.get('/path/to/endpoint')
  const data = response.data // any 😢
  const foo = data.foo // not type error, but foo may be undefined
  // ...
}
```

```ts
// if <T = unknown>
const asyncFunction = async () => {
  const response = await axios.get('/path/to/endpoint')
  const data = response.data // unknown
  // const foo= data.foo // type error
  if (data.foo) { // type testing is compulsory 😄 
    const foo = data.foo
    // ...
  }
}
```

#### Describe alternatives you've considered
This may be breaking changes, so it might be a good idea to just document the following wrappers.

```ts
async function typeSafeGet<T = unknown>(
  url: string,
  config?: AxiosRequestConfig,
) {
  return axios.get<T>(url, config)
}
```

#### Additional context
In https://github.com/axios/axios/pull/3002, @carloschida agrees that `unknown` is optimal choice.

**Comment by carloschida** [comment]
I also proposed a change in #2995.

**Comment by AsazuTaiga** [comment]
Thank you very much.
I wasn't aware of the PR on your side, sorry about that.
I think this issue is no longer needed, so I'll close it!
