### ISSUE TITLE
Is it possible to improve type support for Headers

### ISSUE THREAD

**Issue by carpben** [axios/axios#3945]
#### Is your feature request related to a problem? Please describe.
When using Axios we get type support for various properties, but headers is typed as 
```ts
Record<string, any>
```
Which means there is practically no type support. So if I want to send form data I need to accurately type
```js
'Content-Type': 'multipart/form-data'
```
This is time consuming, and can easily break. 

#### Describe the solution you'd like
AFAIK possible properties for HTTP headers is well defined. Then for a specific property such as  `Content-Type` the possible values are well known. 
Suggestion is to build a better type to represent Headers, and use it to type the headers parameter. 

#### Describe alternatives you've considered
I can't think of a relevant alternative. 

#### Additional context
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

**Comment by impadalko** [comment]
Is the header even typed as `Record<string, any>`? Looking at the [index.d.ts file](https://github.com/axios/axios/blob/5bc9ea24dda14e74def0b8ae9cdb3fa1a0c77773/index.d.ts#L50), the type looks to be just `any`.

I would like to this to be better typed too, but I see two issues: the headers are case-insensitive (I'm not sure how to work around this in TS); the user can define custom headers so I can't see a way of going around a `[key: string]: any`. Any ideas on this?

**Comment by carpben** [comment]
@impadalko Since headers' properties are optional, I see no problem to add both a lower case and uppercase version for each property.

**Comment by jasonsaayman** [comment]
I think in its current state it is fine, v2 will probably remedy this as everything will be TS first
