### ISSUE TITLE
Post data/body is being passed on the redirect URL causing error 400 (Bad request)

### ISSUE THREAD

**Issue by kiyokodyele** [axios/axios#3946]
#### Describe the bug
Follow redirects is on and should be. But:
When I execute a Post that has a redirect (302) to a Get URL, the data/body of the post is passed on to the redirect URL causing an error 400 (Bad request)

#### To Reproduce
1. N/A

#### Expected behavior
Data/body sent by post should not be passed on the redirect URL

#### Environment
 - Axios Version: v0.21.1
 - Adapter: HTTP
 - Browser N/A
 - Browser Version N/A
 - Node.js Version: v13.7.0
 - OS: Windows 10
 - Additional Library Versions: tunnel v0.0.6, qs v6.10.1, tough-cookie v4.0.0, axios-cookiejar-support v1.0.1

**Comment by kiyokodyele** [comment]
As a workaround, I've intercepted the requests checking if the method is get and has defined data
then set the data as undefined

```js

instance.request.use((config) => {
        if (config.method == 'get' && config.data) { // Bug
            config.data = undefined
            config.headers = { 
                'Content-type': 'application/x-www-form-urlencoded',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62', 
            }
            return config
        } else {
            return config
        }
    });

```

**Comment by daniel-julius-sam** [comment]
I was unable to reproduce the issue, can you give some details on reproducing the issue so that i can work on it

**Comment by kanatBektursyn** [comment]
Comes from RFC2616

> The presence of a message-body in a request is signaled by the
>    inclusion of a Content-Length or Transfer-Encoding header field in
>    the request's message-headers. A message-body MUST NOT be included in
>    a request if the specification of the request method (section 5.1.1)
>    does not allow sending an entity-body in requests. A server SHOULD
>    read and forward a message-body on any request; if the request method
>    does not include defined semantics for an entity-body, then the
>    message-body SHOULD be ignored when handling the request.

[https://datatracker.ietf.org/doc/html/rfc2616](url)

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
