### ISSUE TITLE
Params that contains a list is parsed incorrectly when calling axios.get function

### ISSUE THREAD

**Issue by douglasvicente** [axios/axios#3950]
#### Describe the bug
AxiosRequestConfig.params that contains a list is parsed incorrectly when calling axios.get(...) function

#### To Reproduce
For this method call
```ts
axios.get(' http://my.url.com/api/lotes'
   params {
      loteId: [1024,1480,1666,2021]
   }
}).then(response => console.log(response.data))
```

The outcome is
> http://my.url.com/api/lotes?loteId[]=1024&loteId[]=1480&loteId[]=1666&loteId[]=2021

#### Expected behavior
It should be
> http://my.url.com/api/lotes?loteId=1024&loteId=1480&loteId=1666&loteId=2021
or
> http://my.url.com/api/lotes?loteId=1024,1480,1666,2021

#### Environment
 - Axios Version [e.g. 0.19.2]
 - Browser [Firefox]
 - Browser Version [90.0]
 - Node.js Version [14.7.0]
 - Additional Library Versions [React 16.13.1]

#### Additional context/Screenshots

~It's obviously a bug, since it's not respecting the https://datatracker.ietf.org/doc/html/rfc6570 rules (see 1.2 and 3.2) and then no server implementation is going to accept it as correct.~

Edit: It's not respecting the https://datatracker.ietf.org/doc/html/rfc6570 rules (see 1.2 and 3.2) and some server implementations are not going to accept it as correct. Even if some accept it, the server also has a bug, as rules must sert à something.

It's been 5 years we are using crutchs¹ to workaround it . . . :disappointed: 

¹ Brazillian idiomatic; means we are using a support that should be temporary, but is not

**Comment by impadalko** [comment]
Apparently, the array encoding in a query string is not a consensus being pretty much framework dependent in practice (as seen in this SO question: https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string/9547490#9547490).

One way of solving your issue would be to pass a `paramsSerializer` function in your request config so you can change this to your expected format (you can see an example [here](https://axios-http.com/docs/req_config))

**Comment by mwisnicki** [comment]
Lack of consensus among PHP frameworks does not mean there are no standards, only that one should not look to PHP for guidance how to do anything.
Current serialization violates [rfc3986](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A) and can't be the default.

This is rejected by Apache Tomcat as non-spec compliant with the error `Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986`

AFAIK the only way to pass a list of values supported by URI spec, without additional parsing/encoding, is the first format proposed above: 

> http://my.url.com/api/lotes?loteId=1024&loteId=1480&loteId=1666&loteId=2021

It is supported by popular frameworks such as Spring and even standard browser API:

> `new URLSearchParams("x=1&x=2").getAll("x")`
> `(2) ['1', '2']`

**Comment by mwisnicki** [comment]
Sadly looks like this was already raised in #1728 and rejected for poor reasons.

**Comment by jasonsaayman** [comment]
closing due to being very stale, if this is still relevant please open a new issue
