### ISSUE TITLE
`common` headers `undefined` since Axios v0.20.0 

### ISSUE THREAD

**Issue by regulardesigner** [axios/axios#3958]
#### Describe the issue
I'm using an internal library designed with Axios to manage our http requests througth all our projects.

Since the update of **Axios v0.20.0** I have a `TypeError: Cannot set property 'X-API-Timestamp'` of undefined when performing multiple requests. The first request work fine but the second is rejected by the axios interceptor. Before that version (v0.20.0) the interceptors worded fine.

Our custom headers are created by the axios interceptor in `config.headers.common` the `common` key seems to be missing like suggest the error. 

#### Example Code
Here our axios interceptors

```js
setInterceptors() {
    this.http.interceptors.request.use(
      config => {
        // Workaround to inject the value dynamically
        // @see https://github.com/axios/axios/issues/1476#issuecomment-542958459
        config.params = config.params || {}
        config.params.is_adult_filtered = this.adultFilter

        const timestamp = (Date.now() / 1000) | 0 // Same as Math.floor(Date.now() / 1000) but faster

        config.headers.common['X-API-Timestamp'] = timestamp
        const signature = this.crypto.generateSignature(
          timestamp,
          config.url,
          config.params,
          config.data
        )
        config.headers.common['X-API-Signature'] = signature

        return config
      },
      error => {
        if (error.message === 'Request aborted') {
          return true
        }

        console.error('Request error:', this._formattedError(error))

        return Promise.reject(error)
      }
    )
```

#### Expected behavior, if applicable
To have access to the `common` object like in the Axios 0.19.2 version.

#### Environment
 - Axios Version [v0.20.0 and all above]
 - Adapter [HTTP]
 - Node.js Version [12.18.3]
 - Browser [e.g. all browsers]
 - OS: [OSX 11.5.1]
 - Additional Library Versions [Nuxt v2.15.6]

#### Additional context/Screenshots
I don't have any additional informations

**Comment by djs113** [comment]
The `X-API-Timestamp` is present inside `req.headers` and it's key name is entirely converted to lowercase and the value is a string with the value of the timestamp. You shouldn't look for it inside the `common` object.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
