### ISSUE TITLE
 How to post large Uint8Array without using blob?

### ISSUE THREAD

**Issue by louisabraham** [axios/axios#3960]
#### Describe the issue

I would like to use axios to post a large Uint8Array.

My problem is that this array is larger than 500MB which is the maximum size for a Blob on Chrome.

Note that I also cannot use strings in `FormData.append` because the limit for strings is smaller.

#### Example Code

```js
var formData = new FormData();
formData.append("abc", "123");
formData.append("file", new Blob([array]), fileid);
await axios.post(upload.url, formData);
```

**Comment by jimmywarting** [comment]
Blob's should in theory not only be constructed with one single memory container, at best it should just be another pointer references to some other blob with or without a offset and another size

Meaning if you have a existing blob and slice it 
```js
blob = new Blob(data)
slice = blob.slice(blob.size / 2, -1)
```
Then the sliced blob should not allocate half of the size of the blob
the `slice` should just point to `blob` and say that it should start reading from the middle of `blob` and stop reading at `blob.size - 1`

and if you would concat multiple smaller chunks into one large blob then it should just be the same:
```js
const finalBlob = new Blob([slice_a, slice_b, slice_c, slice_d])
```
this finalBlob shouldn't be able to allocate the total size of all chunks combined cuz it can't not read the blob in a sync manner. so the best it can/should do (in theory) is to just create a references point to all the other chunks

then when you create a reader on the `finalBlob` then it should just start reading from slice_a and when that finish it should start reading from slice_b and so on

so if you split up your large uint8array into smaller chunks and do the following:
```js
const chunks = []
chunks.push( new Blob([ uint8array.slice(0, 1024) ]) )
chunks.push( new Blob([ uint8array.slice(1024, 2048) ]) )
...
// And finally concat them
new Blob(chunks)
```
then it should not blow up with a 500 mb limit

then you should be able to run: `formData.append("file", new Blob([array]), fileid)`

---

But i haven't tested or confirmed if this works in chrome, i can just say that i mostly knows how blob's are built up internally without many developer knowing truly how it should work. says the guy who also helped build [fetch-blob](https://www.npmjs.com/package/fetch-blob) for node-fetch

**Comment by jimmywarting** [comment]
another thing that might be better for you is just to post raw binary data directly instead of using any formdata (if you can)

`await axios.post(upload.url, uint8array)`

**Comment by jasonsaayman** [comment]
Closing pleas use the above solution
