### ISSUE TITLE
axios response body contains random properties. 

### ISSUE THREAD

**Issue by jay-kj-woo** [axios/axios#3965]
#### Describe the issue
local REST API server responses with array with empty objects, but the response object from client contains random properties in each should-have-been empty objects. 

#### Example Code

From my client side
```js
getReadyWorks = async () => {
    const response = await axios.get("/workorders/ready?limits=1");
    console.log(response);
    return response.data;
  };
```
From my console
```js
{
    "data": [
        {
            "receiveTime": "Invalid Date",
            "startTime": "Invalid Date"
        },
        {
            "receiveTime": "Invalid Date",
            "startTime": "Invalid Date"
        },
        {
            "receiveTime": "Invalid Date",
            "startTime": "Invalid Date"
        }
    ],
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "10",
        "content-type": "application/json; charset=utf-8"
    },
    "config": {
        "url": "/workorders/ready?limits=1",
        "method": "get",
        "headers": {
            "Accept": "application/json, text/plain, */*"
        },
        "baseURL": "http://localhost:5000/",
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1
    },
    "request": 
}
```

#### Expected behavior, if applicable
the data object from axios response should be 1 array of 3 empty objects. 

#### Environment
 - Axios Version [e.g. 0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [ Chrome]
 - Additional Library Versions [React 17.2]

#### Additional context/Screenshots
see how the response from the get request has empty objects, but the data object from axios response object contains `receiveTime` and `startTime` properties, which i haven't used at all. 
![image](https://user-images.githubusercontent.com/47402682/130189576-5c7a92ab-473c-4d1a-a221-6be6b312a8ca.png)
![image](https://user-images.githubusercontent.com/47402682/130189608-c1e94fa8-8ad9-40b2-934c-5c4f82fa5fc4.png)

**Comment by AiverReaver** [comment]
do you have any  transformResponse functions?

**Comment by Frodo1980** [comment]
I am not a Pro, but I think this is no axios-issue. You should check your workorders/ready-API-endpoint. How is the request handled there and how is the response build?

**Comment by kanatBektursyn** [comment]
If there was `302 (Redirect)` received prior to provided response, axios will return the entity-body in response

**Comment by jasonsaayman** [comment]
This is not a Axios error it has to do with the API you are consuming.
