### ISSUE TITLE
What is the Axios equivalent of req.pipe(request()) / Pipe express request data into Axios request

### ISSUE THREAD

**Issue by Jack-Rogers** [axios/axios#3971]
#### Describe the issue
Using request you can forward a POST multipart/form-data request from express to another server without modifying the body/parameters of the initial request and then return the response from the other server to express. With axios this feature appears to be missing or not supported. What is the best way for me to implement this functionality without having to parse the request body and build a new request?

#### Example Code
header
```javascript
const request = require('request');
const axios = require('axios');

const express = require('express');
const app = express();
app.listen(3000);

const FORWARD_URL = 'https://example.com/'
```

Working example using request
```javascript
app.post('/test/0', (req, res) => {
    req.pipe(request(FORWARD_URL)).pipe(res);
})
```

Attempt #1 
```javascript
app.post('/test/1', (req, res) => {
    req.pipe(axios.post(FORWARD_URL)).pipe(res);
})

// internal/streams/readable.js:827
//       dests[i].emit('unpipe', this, { hasUnpiped: false });
//                ^
// TypeError: dests[i].emit is not a function
//     at IncomingMessage.Readable.unpipe (internal/streams/readable.js:827:16)
//     at unpipe (S:\_Work\[REDACTED]\node_modules\unpipe\index.js:47:12)
//     at send (S:\_Work\[REDACTED]\node_modules\finalhandler\index.js:306:3)
//     at Immediate.<anonymous> (S:\_Work\[REDACTED]\node_modules\finalhandler\index.js:133:5)
//     at Immediate.<anonymous> (S:\_Work\[REDACTED]\node_modules\express\lib\router\index.js:635:15)
//     at processImmediate (internal/timers.js:466:21)

```

Attempt #2
```javascript
app.post('/test/2', (req, res) => {
    req.pipe(axios({
        url: FORWARD_URL,
        method: 'POST',
        responseType: 'stream'
    })).pipe(res);
})

// SAME ERROR AS ABOVE
```

Attempt #3
```javascript 
app.post('/test/3', async (req, res) => {
    const axiosRequest = await axios({
        url: FORWARD_URL,
        method: 'POST',
        responseType: 'stream',
        data: req
    })

    axiosRequest.data.pipe(res);
})
// server at FORWARD_URL receives improperly formatted request body, changing request content-type headers has no affect
// ------WebKitFormBoundaryc4BjPwpdR4mG7CFN
// Content-Disposition: form-data; name="field_name"
//
// field_value
// ------WebKitFormBoundaryc4BjPwpdR4mG7CFN--
```

#### Expected behavior, if applicable
Forwarding an express post request, if `POST application/x-www-form-urlencoded` seems to be possible using `Attempt #3`, however I can't seem to get it working with `POST multipart/form-data` requests.

#### Environment
 - Axios Version: 0.21.1
 - Node.js Version: v14.17.5
 - OS: Windows 10 / ALL
 - Additional Library Versions: Express 4.17.1

#### Additional context/Screenshots
This issue is a repost from StackOverflow https://stackoverflow.com/q/68867930/7594368

Related issue #3846 
Somewhat related issues #961 #553

**Comment by relzhong** [comment]
try [#961](https://github.com/axios/axios/issues/961#issuecomment-515648187)

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by DigitalBrainJS** [comment]
Axios doesn't implement the stream interface to use the pipe method, you should do that manually.
```js
app.post('/test/2', async (req, res) => {
    const {data} = await axios.post(FORWARD_URL, req, {
        responseType: 'stream'
    }));

    data.pipe(res);
})
```

**Comment by jonstorer** [comment]
For anyone looking, this is a bit more general as it passes the req.method param into axios.

```javascript
const url = Url.parse(forwardUrl)
url.pathname = req.originalUrl

axios({
  method: req.method,
  url: Url.format(url),
  data: req,
  responseType: 'stream'
}).then(function (response) {
  response.data.pipe(res);
})
```

**Comment by owendswang** [comment]
Really like to know how to use axios stream to koa2 response.

**Comment by DigitalBrainJS** [comment]
@owendswang 
```js
const {data, headers} = await axios.get(url, {responseType: 'stream'});
context.body = data;
context.set(headers)
```

**Comment by owendswang** [comment]
@DigitalBrainJS Thanks for reply. But this got me error like 'data' type is IncomingMessage, not stream.

**Comment by DigitalBrainJS** [comment]
@owendswang Hmm... Strange. Well, then you can try to stream directly to the response object:
```js
const { pipeline } = require("stream/promises");

app.use(async function (ctx) {
  const { data, headers } = await axios.get("https://dummyjson.com/products/1", { responseType: "stream" });

  ctx.respond = false;
  await pipeline(data, ctx.res);
});
```

**Comment by owendswang** [comment]
@DigitalBrainJS Thanks for the help! It works both of the codes you posted now. It's so wired. I might jumped into some dead end somehow...

**Comment by victor-homyakov** [comment]
> For anyone looking, this does not use axios, it uses `http` which is built into node.

Just one small addition: copy headers from the original request and back to the original response

```js
app.use(`${root}/proxy`, (req, res) => {
  // was: req.pipe(request[req.method.toLowerCase()](BASE_URL + req.url)).pipe(res)
  http.request(BASE_URL + req.url, { method: req.method, headers: req.headers }, (response) => {
    for (const [key, value] of Object.entries(response.headers)) {
      res.setHeader(key, value as string)
    }
    response.pipe(res)
  }).end()
})
```
