### ISSUE TITLE
error ECONNABORTED on post request using Axios

### ISSUE THREAD

**Issue by skrilax91** [axios/axios#3972]
#### Describe the issue
I currently use Axios on an Android app with cordova and VueJS for the front, i want to call an API for retrieving information, all code working on most of my tablet and phone but it not working on one tablet on Android 8. The request is instantly aborted and doesn't reach my api server

#### Example Code
that is my function that call the api
```js
async checkLicence(licence) {
        if (!licence) {
	        var res = []
	        res.error = true;
	        res.errMsg = "Please enter a licence";
                return res
        }
	return await axios.post(process.env.licenceURL + '/api/subscribe', { key: licence, application_id: 7, terminal: { mac: '00155D011400' }}).then(response => {
		return (response.data)
	}).catch(error => {
		var res = []
		res.error = true;
		if (error.response)
			res.errMsg = "error res: " + error.response.status + " see : " + error.response.data;
		else res.errMsg = "error: " + error.message;
		this.$refs.upOver.setOverlay('licenceUpdate', "Error")
		this.$refs.upOver.setInfo('licenceUpdate', JSON.stringify(error))
		console.log(error);
		return res
	})
},
```

#### Expected behavior, if applicable
Normally, request responde me a json formated text with all licence configuration

#### Environment
 - Axios Version [0.21.1]
 - Node.js Version [14.16.1]
 - OS: [Android 8]
 - Additional Library Versions [Vue 2.6.14]

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
