### ISSUE TITLE
Why my request body is empty ?

### ISSUE THREAD

**Issue by GusMartins499** [axios/axios#3974]
#### Describe the issue
Hi guys, i'm from Brazil, how are you ? Somebody can help-me please ?
I need send some headers and a body in my request, but, when i try sendind headers + body, the body is empty in my backend

#### Example Code

```jsx
       await api
          .post(
            `/exportar_baixas/${hashEmpresa}?orderby=${orderBy}&order=${order}`,
            data2,
            {
              headers: {
                'Content-Type':
                  'application/json; application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
              },
              responseType: 'arraybuffer',
            }
          )
          .then(function (response) {
            console.log('response ', response);
            const workbook = XLSX.read(response.data, { type: 'buffer' });
            XLSX.writeFile(workbook, 'out.xlsx');
          })

```

#### Expected behavior, if applicable
I expected the body is not empty

#### Environment
 - Axios Version [^0.19.2]
 - Browser [Chrome]
 - Browser Version [92.0.4515.159]
 - Node.js Version [v12.20.1]
 - Additional Library Versions [e.g. React ^16.12.0,  xlsx ^0.17.1]

#### Additional context/Screenshots
My request:
![image](https://user-images.githubusercontent.com/43645525/130620889-33debea0-5755-46a8-ae98-03144da38a5a.png)

print console backend:
```js
console.log('request.body ', request.body);
```

print console backend:
![image](https://user-images.githubusercontent.com/43645525/130621060-f1545d3b-69f3-432c-adc8-fa1bf92fb593.png)

PS: I using another lib (sheetJS) to write and read excel's files

**Comment by kanatBektursyn** [comment]
How does your ` data2` look like? Can you share and actual data you are trying to send to server?
