### ISSUE TITLE
Trying to get in touch regarding a potential security issue

### ISSUE THREAD

**Issue by zidingz** [axios/axios#3982]
#### Section/Content To Improve
Security Policy

#### Suggested Improvement
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a SECURITY.md file with an email, or another contact method? GitHub recommends this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

#### Relevant File(s)
`SECURITY.md` https://github.com/axios/axios/pull/3981

**Comment by jasonsaayman** [comment]
Will do

**Comment by zidingz** [comment]
Thanks!
