### ISSUE TITLE
为什么我用POST请求的时候，参数必须拼接在路径后面才能成功，直接传入param就不能成功

### ISSUE THREAD

**Issue by zs0308** [axios/axios#3994]
#### Describe the issue
A clear and concise description of what the issue is.

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
let param = {
            username: "test",
            password: "123456",
            repassword:"123456"
        }
//faile
axios.post(postRegister, param)
            .then(res => {
                console.log("post res = " + JSON.stringify(res))
            })
            .catch(err => {
                console.log("post err = " + JSON.stringify(err))
            })
//success
        axios.post(postRegister + `?username=${param.username}&password=${param.password}`, param)
            .then(res => {
                console.log("post res = " + JSON.stringify(res))
            })
            .catch(err => {
                console.log("post err = " + JSON.stringify(err))
            })
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kanatBektursyn** [comment]
如果你想在axios中使用POST方法和body和URLquery，把它们放入body和request params中 
```javascript
axios.post(postRegister, param, {
                username,
                password
            })
            .then(res => {
                console.log("post res = " + JSON.stringify(res))
            })
            .catch(err => {
                console.log("post err = " + JSON.stringify(err))
            })

```
但是我看不到 URLquery 的使用，如果您可以将数据发送到正body，特别是考虑可能的安全问题

**Comment by zs0308** [comment]
非常感谢，如果后台接口使用body接受参数，使用axios.post(url, param)，如果后台使用URLquery可以使用axios.post(url,null,{params:param})
