### ISSUE TITLE
Different results when using request vs axios

### ISSUE THREAD

**Issue by Reiszecke** [axios/axios#3996]
#### Describe the issue
I want to move from `request` to `axios`.

#### Example Code

My request looks like this:

```
request.post({
        url: url,
        headers: {
          'Content-Type': 'application/json',
          'Cookie': cookie
        },
        json: { 'user': user, 'check': true },
        resolveWithFullResponse: true
      })
```

Trying to do the same with axios, I get an error code 400.

```
axios.post(url, {
        headers: {
          'Content-Type': 'application/json',
          'Cookie': cookie
        },
        json: { 'user': user, 'check': true },
      })
```

This seemed to add headers and json to be passed as form data so I tried

```
axios.post(url, null {
    ...
```

which seems to make the headers work, however it still returns me an error 400.

What am I missing to make this simple request act the same way?

#### Expected behavior, if applicable

I would expect it to do the same given that I more or less pass the same parameters

#### Environment
 - Axios Version 0.21.1
 - Node v16.5.0

**Comment by kanatBektursyn** [comment]
What is the check function on server side?

**Comment by kanatBektursyn** [comment]
To get more detailed information about an error and why you receive it, you can try 

`if (error.response){

//do something

}else if(error.request){

//do something else

}else if(error.message){

//do something other than the other two

}`

**Comment by kanatBektursyn** [comment]
```javascript
request.post({
        url: url,
        headers: {
          'Content-Type': 'application/json',
          'Cookie': cookie
        },
        body: { user, check: true },
        resolveWithFullResponse: true
      })
```
Axios.POST actually send the json for you by itself. There is no `json` field in **post** config, only `body` and `params`

**Comment by kanatBektursyn** [comment]
@Reiszecke Have you tried possible solution provided before?

**Comment by Reiszecke** [comment]
Hey, I appreciate your response. I went back to `request` for now and can't test right now because I've deployed and I'm afraid of touching this again.

However, I don't understand what you've changed in your suggestion except for using `request` and not including the key for user
