### ISSUE TITLE
Axios url won't preserve encoded period

### ISSUE THREAD

**Issue by tbtalbottjr** [axios/axios#4002]
#### Describe the issue
I am calling `axios.post` with the url:

```
/constituents/941802/activities/rid/941802/rtype/Constituent/to/2021-10-01/type/Vol%2E%20Time?format=json
```

But it sends 

```
/constituents/941802/activities/rid/941802/rtype/Constituent/to/2021-10-01/type/Vol.%20Time?format=json
```

How do I prevent this?

#### Example Code
Not much to show here, but:

```js
  post(url) {
    return axios.post(
      url, 
      {},
      {responseType: 'json', headers: { 'Content-Encoding': 'gzip' }}
    )
  }
```

#### Expected behavior, if applicable
To preserve the encoded period after 'Vol'

#### Environment
 - Axios Version: 0.21.1
 - Adapter: XHR
 - Browser: Chrome
 - Browser Version: 92.0.4515.159
 - Node.js Version: 15.2.1
 - OS: OSX 10.14.6
 - Additional Library Versions: VueJs 2.6.x - 3.1.x

#### Additional context/Screenshots
I have seen the suggestion of adding a trailing `'/'` at the end of the path, but that does not prevent the conversion and the server still finds the format to be illegal.

**Comment by kanatBektursyn** [comment]
try using 
```javascript
encodeURIComponent(<urlString>)
```

Notice that url stirng should **NOT** be  **url safe**, i.e. dots, signs, etc are present. They should get encoded afterwards

**Comment by kanatBektursyn** [comment]
I had no success reproducing your error. Can you provide some additional information on issue? For example, what comes into `axios.post(url, ...)` url part? Try this and show the result:

```javascript
    {
    console.log(url);
    return axios.post(
      url, 
      {},
      {responseType: 'json', headers: { 'Content-Encoding': 'gzip' }}
    );
```

**Comment by tbtalbottjr** [comment]
That is what is being used internally, I presume. Example:

```
encodeURIComponent('Vol. time') == "Vol.%20time"
```

So I don't see that helping. 

Just to be clear, the URI I am sending is a callback that is being provided by the server. It is not being constructed on the front end. It looks like encodeURIComponent would be most useful if I was constructing params.

**Comment by tbtalbottjr** [comment]
The input string in the description was created from the console log as you have added. The only difference is that the `'?format=json'` is being added prior to calling post.

**Comment by kanatBektursyn** [comment]
> The input string in the description was created from the console log as you have added. The only difference is that the `'?format=json'` is being added prior to calling post.

Axios only changes URL if there are params to be serialized in url, i.e., try deleting `format=json` from url and sending it in params, likewise: 
    ```javascript
post(url){
    return axios.post(
      url, 
      {
         params:{
             format: "json"
         }
      },
      {responseType: 'json', headers: { 'Content-Encoding': 'gzip' }}
    );
```

**Comment by tbtalbottjr** [comment]
I tried your suggestion, but I still get the `'.'` back. I also tried to set the second parameter to 'undefined' instead of '{}' based on your suggestion that Axios only changes the URL if there are params, but that didn't help either. Axios still insists on decoding and re-encoding the url for me. 

I did find that if I append '.json' to the end, the server will accept the url path as: 

```
/constituents/941802/activities/rid/941802/rtype/Constituent/to/2021-10-02/type/Vol.%20Time.json
```

So, I guess that is my workaround for now.

**Comment by tbtalbottjr** [comment]
Further exploration seems to be showing that Chrome is doing the conversion that is causing the problem. It looks to be re-encoding the path.

**Comment by kanatBektursyn** [comment]
Your issue makes me think it has something to do with . standing Right After the word. Probably, js thinks of that dot as file extension starting point. These might be helpful:
[https://stackoverflow.com/questions/23228378/is-there-any-way-to-get-the-file-extension-from-a-url](url)
[https://stackoverflow.com/questions/605696/get-file-name-from-url](url)

**Comment by tbtalbottjr** [comment]
I don't think that is the issue. Chrome is decoding and re-encoding the path using encodeURI, apparently. The issue does not occur in Safari or Firefox. So, this is not an Axios issue. Just another reason to give up Chrome, I guess. 

Thanks for your help. Closing.
