### ISSUE TITLE
httpAdapter hanging in node16

### ISSUE THREAD

**Issue by y-nk** [axios/axios#4005]
#### Describe the bug

Sorry for https://github.com/axios/axios/issues/4004, it's a false report. I thought issue would come from Jest, but changing node version to 14 changed the behavior, so i'm positive of this now.

#### To Reproduce

run any axios request in node 16.

#### Environment
 - Axios Version 0.21.1
 - Adapter HTTP
 - Node.js Version: 16
 - OS: latest
 - Additional Library Versions jest 27

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Thanks, Axios does not work with v16 as far as I can remember when I tested last, but we will need to get support ready, this is planned, and as soon as I can get to it I will update everyone.

**Comment by krecik** [comment]
After upgrading to `0.21.3` I also have same problem - no error, no request made.

I downgraded to `0.21.1` and my requests are made. But i have only simple application with several POST and GET requestes.

Node version: `v16.8.0`

**Comment by y-nk** [comment]
@jasonsaayman if you ever accept PR let me know ; i can't guarantee a resolution but i may have some hours to spend on that.

**Comment by jasonsaayman** [comment]
Sure @y-nk if you want to try give it a bash. @krecik that would be correct, Node v16 is not supported as of yet even in the latest release.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
