### ISSUE TITLE
0.21.2: Cannot read properties of undefined (reading 'split') of package using webpack

### ISSUE THREAD

**Issue by hadimostafapour** [axios/axios#4007]
#### Describe the bug
Due to the Webpack configuration, reading `package.json` to extract the version of Axios is not a good idea IMO and causes issues in some environments like what happens to me after upgrading to the 0.21.2,  0.21.1 works properly.

```js
var pkg = __webpack_require__(/*! ./../../package.json */ "./node_modules/axios/package.json");

// ...

var deprecatedWarnings = {};
var currentVerArr = pkg.version.split('.'); // << Cannot read properties of undefined (reading 'split')
```

#### Environment
 - Axios Version [21.2]
 - Adapter [N/A]
 - Browser [Chrome]
 - Browser Version [95]
 - Node.js Version [14.x.x]
 - OS: [Windows]
 - Additional Library Versions [React 17]

**Comment by xiao555** [comment]
same issue

**Comment by jrmyio** [comment]
Same issue when running a built (via webpack) node.js application.

**Comment by jasonsaayman** [comment]
There is already a pull request for this #4029
