### ISSUE TITLE
0.21.2: Response interceptor not called when request interceptor is attached

### ISSUE THREAD

**Issue by nerdbeere** [axios/axios#4011]
#### Describe the bug
With the latest release `0.21.2` the response interceptor is no longer called when a request interceptor is attached.

#### To Reproduce

Not working: https://jsfiddle.net/yedqwjma/
```
// response interceptor won't be executed
axios.interceptors.response.use((config) => {
	console.log('response interceptor');
  return config;
});

axios.interceptors.request.use((config) => {
	console.log('request interceptor');
  return config;
});

axios.get('https://jsonplaceholder.typicode.com/todos/1');
```

Working Case with 0.21.1: https://jsfiddle.net/n05rdb49/

#### Expected behavior
Response interceptor should be executed

#### Environment
 - Axios Version 0.21.2

**Comment by bryce0516** [comment]
same here
