### ISSUE TITLE
Fuck you axios！

### ISSUE THREAD

**Issue by wecomgroups** [axios/axios#4015]
AJAX YYDS! 

No matter how I set the withCredentials of axios, it will never carry cookies, but this problem does not exist in ajax!

**Comment by wecomgroups** [comment]
const service = axios.create({
				baseURL: 'http://xxx.xxx.xxx/api/',
				timeout: 5000,
				withCredentials: true,
				xsrfCookieName: 'csrftoken_testtest',
				xsrfHeaderName: 'X-CSRFToken',
			})
			service.interceptors.response.use(
				response => (response),
				error => (Promise.reject(error.response.data.err))
			)

			service.post('user/do_login', { tel: tel, pwd: pwd }, { withCredentials: true })
				.then(function (res) {
					console.log(res);
					service.get('/index/info', { withCredentials: true }).then(function (res) {
						console.log(res.data);
					})
						.catch(function (err) {
							console.log(err);
						});
				})
				.catch(function (err) {
					console.log(err);
				});

**Comment by saint777** [comment]
get rekt son
