### ISSUE TITLE
Host name spoofing

### ISSUE THREAD

**Issue by kabachook** [axios/axios#4022]
#### Describe the bug
Axios uses old `url.parse` API which is vulnerable to [host name spoofing](https://hackerone.com/reports/678487). [Node issue](https://github.com/nodejs/node/issues/31279)

#### To Reproduce

```js
import axios from 'axios';
const url = `http://evil.com%2F.example.com/get`;
await axios({ url });
```

#### Expected behavior
Axios throws error on invalid URL.

As per `new URL` API this URL is invalid:
```
> new URL(`http://evil.com%2F.example.com/get`)
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5) {
  input: 'http://evil.com%2F.example.com/get',
  code: 'ERR_INVALID_URL'
}
```

But axios [uses](https://github.com/axios/axios/blob/master/lib/adapters/http.js#L98) old API, which leads to request being made to `http://evil.com/%2F.example.com/get` (notice the slash before `%2F`). So that the real host is `evil.com`.

This may lead to security implications if URL is dynamically constructed like this:
```js
// id is user-controlled input
const url = `http://${encodeURIComonent(id)}.${host}/${someSecretInfo}/getSomething`
```
This case leads to SSRF

#### Environment
 - Axios Version 0.21.3
 - Adapter HTTP
 - Node.js Version 16.8.0

#### Additional context/Screenshots
None

**Comment by jasonsaayman** [comment]
Closed please see pr.
