### ISSUE TITLE
DELETE request manipulates API url

### ISSUE THREAD

**Issue by quarterpound** [axios/axios#4023]
#### Describe the issue
I have an protected API like so ```/api/v1/emails```. I am using axios interceptors to add authorization headers and error handling. When I do DELETE request on the API, in network tab I see ```/api/public/v1/emails``` being called. I am really confused as to why this is happening

#### Example Code
Code snippet to illustrate your question

```
export const deleteEmail = async (id) => {
    try {
        const result = await axios_api_instance.delete(`/email/?id=${id}`);
        return result.data;
    } catch (e) {
        throw e.response;
    }
}

axios_api_instance.interceptors.request.use(
    (config) => {
        config.headers.Authorization = token;
        return config;
    },
    (error) => {
        return Promise.reject(error);
    }
);

```

#### Expected behavior, if applicable
When I do a DELETE request I want it to go to the route specified

#### Environment
 - Axios Version [0.21.1]
 - Adapter [HTTP]
 - Browser [Chromium]
 - Node.js Version [14]
 - OS: [Manjaro Linux]
 - Additional Library Versions [React 17]

#### Additional context/Screenshots
This is the only place that I am facing this issue. In this specific DELETE request (note: this is the only DELETE request I have in the entire project). Technically there is should be no reason for axios to add /public/ to the route. Is it possible that this could be a .htaccess issue in the backend?

![image](https://user-images.githubusercontent.com/38853700/132166302-c75fa90b-d7cd-4845-a7e3-d6258daa24f7.png)

**Comment by bmatasar** [comment]
Is it possible that the `baseUrl` you used to create `axios_api_instance` contains `/public/`?

**Comment by quarterpound** [comment]
The problem was /email/ trailing slash. closing as it is not related to axios. it is a developer oversight
