### ISSUE TITLE
V0.21.4 - axios instance doesn´t work as in 0.21.1 

### ISSUE THREAD

**Issue by Alta1re** [axios/axios#4026]
#### Describe the bug

I updated from 0.21.1 to 0.21.4 in my react-native application, where i am using an axios-instance.
After the update, i got "Network Error".
When i omitted the instance, and used axios directly, it worked, but not with instance. 
After downgrading back to 0.21.1 everything works fine again.

#### Expected behavior

Axios should work with instance, or, if the usage of instance changed, we an update in the docs.

#### Environment

 - Axios Version 0.21.1 / 0.21.4

 - Additional Library Versions [e.g. React 16.13.1, React Native SDK42]

**Comment by jasonsaayman** [comment]
Which version of node are you using?
