### ISSUE TITLE
Axios instance not working after update to 0.21.4 from 0.21.1

### ISSUE THREAD

**Issue by Alta1re** [axios/axios#4027]
#### Describe the bug
I updated from 0.21.1 to 0.21.4 in my react-native application, where i am using an axios-instance.
After the update, i got "Network Error".
When i omitted the instance, and used axios directly, it worked, but not with instance.
After downgrading back to 0.21.1 everything works fine again.

#### To Reproduce
Just used a simple instance, like shown in the docs.

#### Expected behavior
Axios should work with instance, or, if the usage of instance changed, we an update in the docs.

#### Environment
Axios Version 0.21.1 / 0.21.4
Additional Library Versions [e.g. React 16.13.1, React Native SDK42]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by MaximMonin** [comment]
NodeJs 14 or 16 have this problem also .... half http/https queries doesnt work with this update

**Comment by jasonsaayman** [comment]
Which version of node are you using?

**Comment by MaximMonin** [comment]
> Which version of node are you using?

Right now 14.17.1 (tried also 14.17.6, and 16.8.0) and returned to 0.21.1 axios.
If I see it right the problem already discussed in closed topics but some cases still created "Bas json data"

```
    var rpcdata = JSON.stringify(requestData);
    if (rpcdata == '{}') {   // For method == Get sometimes api returns Error so fixing it
      rpcdata = '';
    }
    var headers = {'Content-Type': 'application/json', 'Accept': 'application/json'};
    if (customHeaders) {
      headers = customHeaders;
    }
    if (token && token.length > 0) {
      headers ['X-Auth-Token'] = token;
    }

    url = encodeURI(url);

    axios({
      url: url,
      method: method,
      data: rpcdata,
      httpAgent: httpagent,
      httpsAgent: httpsagent,
      timeout: timeout * 1000,
      headers: headers
    })
    .then( function (response) {
```
this code working with 0.21.1 but with 0.21.4

**Comment by csvan** [comment]
Latest version also breaks unit tests since the validators are now breaking (`cannot read 'split' of undefined`)

**Comment by Alta1re** [comment]
I am using node V14.16.0

**Comment by nerdbeere** [comment]
@Alta1re I tried reproducing this on runkit without success: https://runkit.com/nerdbeere/613710790e31ee0008798854
I also tried it on my machine with node 14.6 which also works.

Can you try building a minimal case where this bug is visible?

**Comment by luhc228** [comment]
Also not work with axios@0.21.4, but work with axios@0.21.1.

**Comment by luhc228** [comment]
I fetch my api in my react component. I got the response successfully.
![image](https://user-images.githubusercontent.com/44047106/132361823-493d76f6-375d-4b1b-8882-244e7cb99b90.png)

![image](https://user-images.githubusercontent.com/44047106/132361752-e037220b-e10b-4da5-afc9-5b01537be3cf.png)

But the `res` object has not been consoled.

**Comment by gfortaine** [comment]
At first sight, it looks like related to #4016 What is the result if you force the Content-Type with the value "application/json;charset=utf-8" ?

**Comment by Alta1re** [comment]
> I fetch my api in my react component. I got the response successfully.


But you are not using an axios-instance.

With using axios directly i don´t have problems, too.
And i even get my response object.

**Comment by Alta1re** [comment]
> @Alta1re I tried reproducing this on runkit without success: https://runkit.com/nerdbeere/613710790e31ee0008798854
> I also tried it on my machine with node 14.6 which also works.
> 
> Can you try building a minimal case where this bug is visible?

When i create a bare react-app, and just insert an axios-instance and an axios call in App.js, i can´t reproduce this too.
But in my existing application (react-native) it´s definitely just changing the version of axios which changed the result of fetching. 
At the moment i am quite busy with my application, i will do some more test, when i am finished.

**Comment by alvesmog** [comment]
> Latest version also breaks unit tests since the validators are now breaking (`cannot read 'split' of undefined`)

I am having the same issue. It is related to the package.json version on axios.

For some reason, [this](https://github.com/axios/axios/blob/f3ca6371caa738ba5308d413433d9f676f2e0138/lib/helpers/validator.js#L15) isn't getting the proper version.

I'm using node 12

**Comment by jasonsaayman** [comment]
Cool there is a fix #4029 as soon as it is rebased I will do a release

**Comment by varemenos** [comment]
Sorry to bother but was this ever released? I see that both this issue and #4029 are closed but no new version above 0.21.4.

**Comment by freddiegar** [comment]
You can use this version: [v0.22.0](https://github.com/axios/axios/releases/tag/v0.22.0) or +

**Comment by anubhavRaj27** [comment]
> Also not work with axios@0.21.4, but work with axios@0.21.1.
> 
> my Node.js version is v14.16.0

How did you fix this issue ??
