### ISSUE TITLE
For encrypted data, there is a bug.

### ISSUE THREAD

**Issue by dupeiduo** [axios/axios#4032]
#### For encrypted data, there is a bug for 0.21.4 update.

My data is encrypted. eg: At frontend data:'123abc=' When it reached backend, it become '"123abc="'

```
function stringifySafely(rawValue, parser, encoder) {
  if (utils.isString(rawValue)) {
    try {
      (parser || JSON.parse)(rawValue);  // encrypted data will go catch error 
      return utils.trim(rawValue);
    } catch (e) {
      if (e.name !== 'SyntaxError') {
        throw e;
      }
    }
  }

  return (encoder || JSON.stringify)(rawValue);  // finaly my string add " at head and end
}
```

#### Environment
 - Axios Version 0.21.4
 - Adapter XHR
 - Browser Chrome
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Comment by DigitalBrainJS** [comment]
This behavior is only possible if you set the content type of the request to "application/son" for a plain string payload, but you are actually expecting the data to be sent as plain text and not as a valid JSON string.
