### ISSUE TITLE
v0.21.2 fails to redirect

### ISSUE THREAD

**Issue by johnny-miyake** [axios/axios#4048]
#### Describe the issue
Due to a problem of `follow-redirect-1.14.0`, `axios-0.21.2` fails to redirect under a condition.
https://github.com/follow-redirects/follow-redirects/issues/163

The problem has been solved in `follow-redirect-1.14.1` (the current version is 1.14.3), so axios can follow the update.

**Comment by joeynimu** [comment]
I am having a similar issue after upgrading to `axios-0.21.2`. Interceptors for handling `401` to redirect aren't working anymore.

**Comment by jasonsaayman** [comment]
I have released 0.22.0 please check if that fixes your error, if not please open a new issue :)
