### ISSUE TITLE
Axios v0.21.2-0.21.4 breaking change for Next.js

### ISSUE THREAD

**Issue by nathan2400** [axios/axios#4051]
#### Describe the bug
In a Next.js app starting with Axios 0.21.1 we upgraded to Axios 0.21.2 and an existing Axios request from the Next.js api file structure stopped working on localhost only, deploying the app to a prod env does not suffer any problems that we have seen. Changing the request to fetch or reverting Axios back to 0.21.1 would fix the issue, but Axios version 0.21.2-0.21.4 all have the same problem.

#### To Reproduce

src/pages/postOne.js
```js
import axios from 'axios'

const postOne = async (callback) => {
    try {
      const { data } = await axios.post(
        '/api/postTwo',
        {},
        { params: { token: token } },
      )
      console.log('postOne complete', data)
    } catch {
      setApiError(true)
    }
  }
```

src/api/postTwo.js
```js
import axios from 'axios'

export default async function postTwo(req, res) {

  const { data, status } = await axios.post(
    'url',
    {},
    {
      params: {
        secret: secret,
        response: req.query.token,
      },
    },
  )
  console.log('postTwo complete', status, data)
  res.status(status).json(data)
}
```

#### Expected behavior
In file src/pages/postOne.js, the console.log with 'postOne complete' should run and have data returned with it.
In file src/api/postTwo.js, the console.logs with 'postTwo complete' should also return with status code and response object.

With Axios 0.21.1 these work just fine.

With Axios 0.21.2-0.21.4 all console.logs in file src/api/postTwo.js work as expected, but in file src/pages/postOne.js the console.log never runs because the request to 'api/postTwo' never completes.
Changing the either axios request to a fetch call fixes the issue, or reverting Axios to v0.21.1 also fixes the issue.

#### Environment
- Next.js 11.1.1
- Axios 0.21.1
- Node.js 16.5.0

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by elalish** [comment]
My issue sort of fits the title, though I think the problem is different. Axios is a dep of a dep for my project, but I got an upgrade from 0.21.1 to 0.21.4 that broke my build and I had to manually revert the package-lock entry for axios to 0.21.1 to get past it. Here is the fairly obtuse error:

```
@google/model-viewer-render-fidelity-tools: node_modules/axios/package.json (2:8)
@google/model-viewer-render-fidelity-tools: 1: {
@google/model-viewer-render-fidelity-tools: 2:   "name": "axios",
@google/model-viewer-render-fidelity-tools:            ^
@google/model-viewer-render-fidelity-tools: 3:   "version": "0.21.4",
@google/model-viewer-render-fidelity-tools: 4:   "description": "Promise based HTTP client for the browser and node.js",
@google/model-viewer-render-fidelity-tools: Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
```

**Comment by mutablestudio** [comment]
we are also seeing an issue after a Dependabot warning caused us to updgrade to 0.21.2+. we were on `0.21.1`. after the upgrade we had issues with PUT calls using our default `axios.create()` instance. all other GET and POST calls worked as is but this one PUT call with json body was failing w 400 response. 

reverting back to `0.21.1` fixed the issue.

**Comment by jasonsaayman** [comment]
I have released 0.22.0 please check if that fixes your error, if not please open a new issue :)

**Comment by jasonsaayman** [comment]
Give me the link for the package and I will make a pull request to update.

**Comment by jasonsaayman** [comment]
Created the pull request

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
