### ISSUE TITLE
Add insecureHTTPParser type to AxiosRequestConfig 

### ISSUE THREAD

**Issue by Evan-Finkelstein** [axios/axios#4067]
#### Is your feature request related to a problem? Please describe.
Missing insecureHTTPParser type 

#### Describe the solution you'd like
add insecureHTTPParser type to AxiosRequestConfig

#### Describe alternatives you've considered
N/A

#### Additional context
N/a

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
