### ISSUE TITLE
`byteOffset` and `byteLength` ignored on binary dataviews

### ISSUE THREAD

**Issue by atomrc** [axios/axios#4068]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**
When using binary data (ie. `Uint8Array`) with a buffer that has the `byteOffset`  and `byteLength` properties, those properties are ignored by `Axios`  and the entire buffer is sent through the wire. 

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

Here is a playground that reproduce this bug https://codesandbox.io/s/axios-playground-forked-40179?file=/src/index.js

To see the problem, check the Network panel of the dev tools and see that the request to `/` has 3 bytes (there should be only a single one)

```js
import axios from "axios";

const array = new Uint8Array([0, 1, 2]); // This creates a full Uint8Array 
const sub = array.subarray(0, 1); // We just use a slice of that array, then the underlying `ArrayBuffer` still has the entire array in memory but has now the `byteLength`  and `byteOffset` properties set. 

axios
  .post("/", sub, { headers: { "Content-Type": "application/octet-stream" } }) // This will send 3 bytes to the server, it should send only one
  .catch(() => {}); 
```

#### Expected behavior
In the previous example a single byte should be sent in the payload of the request (instead of 3). 
The `byteOffset` and `byteLength`  should be read and interpreted by Axios.

#### Environment
 - Axios Version 0.21.4
 - Browser Firefox
 - Browser Version 92
 - OS:  Ubuntu 20

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

![2021-09-16_11-03](https://user-images.githubusercontent.com/1090716/133583831-8af31a38-fb4d-4caa-8a5b-b0eabc41d5db.png)

**Comment by streamich** [comment]
Bump, also ran into this.

**Comment by DigitalBrainJS** [comment]
And why not just use the slice method instead of subarray? In any case, Axios would have to make a copy of the typed array buffer in order to send it via XMLHttpRequest or fetch (without using ReadableStreams).

**Comment by jasonsaayman** [comment]
Closing, I would suggest using the above solution.
