### ISSUE TITLE
possibility to provide a config option so that url don't get encoded in http adapter

### ISSUE THREAD

**Issue by ymurong** [axios/axios#4071]
#### Is your feature request related to a problem? Please describe.

When we consume OData APIs using Axios, we always run into problems as Axios will always encode the URL while a typical odata resource would contain specials characters such as (, ) etc.... 

After analyzing the source code, we found that it will always parse the URL and use the parsed result before sending the request.
```
var parsed = url.parse(fullPath);
```
[https://github.com/axios/axios/blob/v0.21.4/lib/adapters/http.js#L98](url)

```
var options = {
    path: buildURL(parsed.path, config.params, config.paramsSerializer).replace(/^\?/, ''),
    method: config.method.toUpperCase(),
    headers: headers,
    agent: agent,
    agents: { http: config.httpAgent, https: config.httpsAgent },
    auth: auth
  };
```
[https://github.com/axios/axios/blob/v0.21.4/lib/adapters/http.js#L116](url)

#### Describe the solution you'd like

Would it be possible to provide a config option so that Axios could send the original URL without encoding it?

#### Describe alternatives you've considered
N/A

#### Additional context

we could propose a merge request if you would like to take into account this kind of feature.

**Comment by jasonsaayman** [comment]
closing due to being very stale, if this is still relevant please open a new issue
