### ISSUE TITLE
Unable to use httpsAgent on client using axios

### ISSUE THREAD

**Issue by ChunAllen** [axios/axios#4074]
#### Describe the issue
I'm currently using Express.js that uses axios. In order to communicate with external API. The API server accepts mutual TLS, but when I'm adding `httpsAgent` on `axios.create` I still cannot hit the API. I tried using the certs in Postman and it's working. I would like to replicate the same setup but on my client. 

#### Example Code
```
const axios = require('axios');
const fs = require('fs')
const https = require('https')

const BASE_URL = 'https://XXXX/web'
const API_KEY = 'XXXXXX'

router.get('/', (req, res, next) => {
  try {
    const cert = fs.readFileSync(__dirname + '/XXXX.crt')
    const key = fs.readFileSync(__dirname + '/XXXXX.key')
    const ca = fs.readFileSync(__dirname + '/XXXXX.ca')

    const httpsAgent = new https.Agent({
      cert: cert,
      key: key,
      ca: ca
    });

    return axios.get(`${BASE_URL}/contents`,
      { headers: { 'x-api-key': API_KEY } },
      { httpsAgent }
    ).then(response => {
      res.json(response.data)
    }).catch(error => {
      console.log(error)
    })
  } catch (error) {
    console.log(error)
  }
});
```

#### Expected behavior, if applicable
I should be able to hit the API and get the response.  The error I'm getting is `Error: read ECONNRESE`

#### Environment
 - Axios Version [e.g. 0.21.4]
 - Adapter: HTTPS
 - Browser: Chrome
 - Browser Version: Version 93.0.4577.82 (Official Build) (x86_64)
 - Node.js Version: 12.7.0
 - OS: OSX 11.4

#### Additional context/Screenshots
<img width="662" alt="Screenshot 2021-09-18 at 7 30 57 PM" src="https://user-images.githubusercontent.com/2100728/133887321-a1b761af-33cd-46f4-87f9-8f1851a782da.png">

**Comment by ChunAllen** [comment]
Closing this issue. The workaround for this is add the certs on browser level, since I cannot just use the http certs from client side application like Vue.

**Comment by afgarcia86** [comment]
I am having the same issue, can you explain how you are adding the certs on a browser level?
