### ISSUE TITLE
How to reproduce CURL's "--data-urlencode" parameter in axios ?

### ISSUE THREAD

**Issue by tianalemesle** [axios/axios#4079]
#### Describe the issue

An external API that I must use is documented for `curl` commands only, which uses `--data-urlencode`, while I have trouble reproducing those with `axios`.

#### Example Code

The `curl` example :

```bash
curl -X POST https://example.com --data-urlencode "foo=bar"
```

My attempt at reproducing it using `axios` :

```js
await axios({
    method: 'POST',
    url: 'https://example.com',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: new URLSearchParams({ 'foo': 'bar' }).toString()
});
```

#### Expected behavior, if applicable

The `axios` request returns the same response as `curl`'s.

#### Environment

- Axios Version [e.g. 0.18.0]: 0.21.1
- Adapter [e.g. XHR/HTTP]
- Browser [e.g. Chrome, Safari]
- Browser Version [e.g. 22]
- Node.js Version [e.g. 13.0.1]: 12
- OS: [e.g. iOS 12.1.0, OSX 10.13.4]: AWS Lambda
- Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots

None

**Comment by FatimaJaffal** [comment]
@tianalemesle I think you should use `data` instead of `body`.

**Comment by tianalemesle** [comment]
Ah, right, it was so stupid !

I think I used `data` on my first unsuccessfull trials, then I used a *`curl` to `fetch` converter* (because there is no *`curl` to `axios` converter*), and forgot to replace `fetch`'s `body` by `axios`' `data`.

And, since I got no reply from the `axios` community, I requested tech support a few days later to the provider of the API I'm using here, and they explained how to use their own lib instead *(which I couldn't figure out either at first)*.

Thanks anyway !
