### ISSUE TITLE
error.request is not always an instance of http.ClientRequest

### ISSUE THREAD

**Issue by evilive3000** [axios/axios#4080]
#### Describe the issue
In `handling errors` section it is said that:
```js
      // The request was made but no response was received
      // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
      // http.ClientRequest in node.js
```
But as I see it is not true. I got an object `Writable`, and have to handle it in a different way comparing to the case when it's an error with `error.response`;

#### Example Code
https://runkit.com/evilive3000/614b1523b5a49a00073b1f6a
```js

const axios = require("axios");
const { ClientRequest } = require("http");

const run = async (url, timeout) => {
  return axios.request({url, timeout})
    .then(console.log)
    .catch(function (error) {
      if (error.response) {
        return {
          case_1: error.request instanceof ClientRequest,
          message: error.message,
          className: error.request.constructor.name
        }
      } else if (error.request) {
        return {
          case_2: error.request instanceof ClientRequest,
          message: error.message,
          className: error.request.constructor.name
        }
      }
    });
}

Promise.all([
  run('https://jsonplaceholder.typicode.com/todos/not-an-id', 10000),
  run('https://sitename.domain/todos/1', 10000),
  run('https://jsonplaceholder.typicode.com/todos/1', 1),
])
  .then(console.log)
  .catch(console.error);
```

#### Expected behavior, if applicable
`error.request` expected to be an instance of `http.ClientRequest`

#### Environment
 - Axios Version [0.21.4]
 - Node.js Version [14]

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/5011293/134339908-96b07256-e31e-49ea-953f-6bda912b8620.png)

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
