### ISSUE TITLE
Release Version 1.0.0

### ISSUE THREAD

**Issue by bfdill** [axios/axios#4083]
#### Describe the issue
Beta versions mask feature/patch updates.

#### Example Code
<https://semver.org/>

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards compatible manner, and
> PATCH version when you make backwards compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.```

#### Expected behavior, if applicable
Releases reflect the changeset within them

#### Environment
- ???

#### Additional context/Screenshots
Not deleted.

**Comment by jasonsaayman** [comment]
This is planned, the next release will be 0.22 and then it will be v1

**Comment by Ionaru** [comment]
@jasonsaayman

Previous plans for v1 didn't happen it seems, is there a roadmap to v1 that lists things that need to happen before a first 'release' of Axios?

**Comment by jasonsaayman** [comment]
Well yes we wanted to do a lot in the previous version 1, however we have decided to cut a version one of the current code base and then make v2 the axios-next. You can follow the updates in version 2 on the discussion page.
