### ISSUE TITLE
Redirect handler callback

### ISSUE THREAD

**Issue by muety** [axios/axios#4084]
#### Is your feature request related to a problem? Please describe.
By default, an Axios instance is configured to follow redirects (`301`, `302`, `307` and `308`) automatically. However, you might want to exclude certain URLs from being opened, e.g. if they might contain malicious content or so. 

#### Describe the solution you'd like
It would be nice to be able to specify one or more URL patterns or host names which to exclude in redirects. For instance, if a redirect would point to `https://someevilwebsite.tld`, it would be convenient to tell Axios not to go there, but abort the request instead. 

Go's `http.Client` comes with a [`CheckRedirect`](https://github.com/golang/go/blob/d0dd26a88c019d54f22463daae81e785f5867565/src/net/http/client.go#L64) handler, which fulfills exactly the purpose I described above. It might serve as an inspiration. 

#### Describe alternatives you've considered
None

#### Additional context
None

**Comment by muety** [comment]
I think #980 attempted to suggest similar functionality.

**Comment by jasonsaayman** [comment]
closing due to being very stale, if this is still relevant please open a new issue
