### ISSUE TITLE
response and request interceptors return different request objects

### ISSUE THREAD

**Issue by LanVukusic** [axios/axios#4091]
#### Describe the bug
This is similar to closed issue #315 . 
When trying to get the `response.request.data`, wrong data is returned. Instead of returning the **requests body**, the **responses body** is actually returned.
This makes it hard to use interceptors for cache-ing requests, where the requests body is significant. The `requests`  and `response.request` do not match, so cache keys would not match.

#### To Reproduce
If we configure request and response interceptors and log the request data in both, we can see that the response interceptor does not hold the same request as the request itself.   
An example is runnable on [RunKit](https://npm.runkit.com/axios)

```js
var axios = require("axios")
const instance = axios.create();

instance.interceptors.request.use((req)=>{
    console.log("req:",req.data);  // this is the requests data / body
    return req;
},
(err)=>{
    
});

instance.interceptors.response.use((res)=>{
    // this data should represent the the same thing, but it does not
    console.log("res:", res.request.data); 
    return res;
},
(err)=>{
  
});

// get a random URL and send some test data
instance.get("https://docs.oracle.com/javase/tutorial/networking/sockets/examples/EchoServer.java",{
    data:{
        "data":"test"
    }
}).then((r)=>{
   // do stuff
});
```

#### Expected behavior
Both `console.logs()` should yield exactly same result. in other words, `response.request === request`  should be the same 

#### Environment
 - Axios Version: 0.21.1
 - Adapter: HTTP
 - Browser: /
 - Browser Version: /
 - Node.js Version: v14.17.3
 - OS: Windows / Linux / hosted (runkit)
 - Additional Library Versions: /

#### Additional context/Screenshots
Everything needed is shown in the code example

**Comment by djs113** [comment]
The request data that you are looking for is not present in `response.request.data`, in fact it is actually present in `response.config.data`. 
```
instance.interceptors.response.use((res)=>{
    console.log("res:", JSON.parse(res.config.data)); 
    return res;
},
(err)=>{
  
});
```
This should give you the same data present in `request.data`

**Comment by LanVukusic** [comment]
Thankyou. 
I am closing this issue
