### ISSUE TITLE
Request for File transfer speed in real time

### ISSUE THREAD

**Issue by MeRahulAhire** [axios/axios#4093]
#### Describe the solution you'd like
Hi, I've been using axios for long time and I quite liked it especially its feature of onUploadProgress. But I wondered it'd be great if you can also provide an feature where we can see our file transfer speed in real time for each second. Be it for upload or download just like google drive or any other service.

**Comment by jasonsaayman** [comment]
I doubt this would be possible at this point as there are multiple other issues that need to be addressed, maybe this could be something we can get to later.
