### ISSUE TITLE
axios package version is undefined cannot 'split'

### ISSUE THREAD

**Issue by zacharytyhacz** [axios/axios#4097]
#### Describe the bug
When my project is compiled into my `dist/` folder, all of the compiled files become isolated and can no longer access the package.json / node_modules

Due to this, when axios tries to fetch its versioning from a non-existent json it fails

#### To Reproduce

1. Create a basic react project with `parcel.js` and install/add axios
2. run `parcel build` to compile to `dist/`
3. move the `dist/` to another location, like `/var/www/html`
4. Serve the `index.html` and go to served page on localhost
5. axios will throw this error

#### Expected behavior
Axios should attempt to get it's versioning through some other way instead of relying on the `package.json` which is not reliable in production cases.  Should not throw any errors if `package.json` is not reachable

#### Environment
 - Axios Version [e.g. 0.18.0]: `^0.21.1`
 - Adapter [e.g. XHR/HTTP]: no adapters, just regular standalone axios
 - Browser [e.g. Chrome, Safari]: all browsers
 - Browser Version [e.g. 22]: all browser versions
 - Node.js Version [e.g. 13.0.1]: `15`
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]: ubuntu linux and within docker container
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]: `React 16.9` and `parcel.js 2.0.0-nightly.475` 

#### Additional context/Screenshots
Related: https://github.com/axios/axios/issues/4007 and https://github.com/axios/axios/pull/4029

![image](https://user-images.githubusercontent.com/38140593/135090466-577a8a13-d863-4b3c-b30f-2c7cdc31e6ab.png)

**Comment by jasonsaayman** [comment]
Please check v0.22.0 this has been released and includes a fix for this :)

**Comment by zacharytyhacz** [comment]
@jasonsaayman 

big thanks my man

**Comment by jrmyio** [comment]
I am using axios 0.24.0, but I still have the issue.
