### ISSUE TITLE
Add possibility to choose response type based on the response.

### ISSUE THREAD

**Issue by danierlr** [axios/axios#4098]
#### Is your feature request related to a problem? Please describe.
This is a feature request.
Right now there is no easy way to make `responseType` dependant on status. An example use case: in case response status is 2XX `responseType` should be `arraybuffer`, in other case `responseType` should be `json`.

#### Describe the solution you'd like
Add a possibility to use in `responseType` either string or function, which maps axios response to a responseType string

An example (in typescript), how this could be used:
```
  const config: AxiosRequestConfig = {
    url: '/some/example/api',
    method: 'GET',
    data: 'example_data',
    responseType: (response: AxiosResponse) => {
      if (response.status >= 200 && response.status < 300) {
        return 'arraybuffer'
      }

      return 'json'
    },
  }
```
#### Describe alternatives you've considered
For now i solved this by manually converting ArrayBuffer instance to json

#### Additional context
I am willing to work on this and contribute.

**Comment by theo-js** [comment]
I think this cannot be done and the reason is the response type cannot be set once the XHR is LOADING/DONE, and that is when we receive the response status (it is equal to 0 before that).

**Comment by jasonsaayman** [comment]
Closing as not fixing.
