### ISSUE TITLE
0.21.4 incorrectly stringifies `null` data

### ISSUE THREAD

**Issue by jhpedemonte** [axios/axios#4099]
#### Describe the bug
We're using `apisauce`, but used yarn's `resolutions` to update `axios` to latest version, to pick up security fix. But that broke our app.

We're making a call to `post()` setting data as `undefined` (apisauce changes that to `null`) and we have headers set to `Content-Type: "application/json"` (data isn't always `null`/`undefined`; most times we're sending JSON data). This has worked fine until upgrading `axios` to 0.21.4 -- now, the payload for is actually `null` instead of no payload.

This is do to [this change](https://github.com/axios/axios/pull/3688/files#diff-b34f2f53ab94368c86775969fb604e8375abe03b6a378bdd09896fd91ac0a0d2R59) from PR #3688: it blindly stringifies data with content type is "application/json".

This was not an issue with 0.21.1.

#### To Reproduce
Call `post()` with data set to `null`. Notice that actual XHR payload is string "null".

#### Expected behavior
XHR has no payload

#### Environment
 - Axios Version 0.21.4
 - Adapter [e.g. XHR/HTTP]
 - Browser  Chrome
 - Browser Version 93.0.4577.82
 - Node.js Version [e.g. 13.0.1]
 - OS: MacOS 11.6
 - Additional Library Versions: apisauce 2.1.1 (latest)

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by DigitalBrainJS** [comment]
> it blindly stringifies data with content type is "application/json".

Actually, it does exactly what you ask it to do when you set `contentType` to `application/json` - it passes the data as JSON. Null is a valid JSON payload. [As discussed earlier](https://github.com/axios/axios/issues/4034#issuecomment-915316823), this is expected [RFC-compliant](https://datatracker.ietf.org/doc/html/draft-ietf-jsonbis-rfc7159bis-04) behavior. Passing `null` as a no payload sign is erroneous with `application/json`, so this is an `apisauce` issue.

**Comment by jhpedemonte** [comment]
Yep, you are correct. I'll push on `apisauce` to update. Thanks.
