### ISSUE TITLE
Timeout not cleared on cancel

### ISSUE THREAD

**Issue by jdaley** [axios/axios#4106]
#### Describe the bug
When a request with a `timeout` is cancelled, the setTimeout for the timeout is not cleared, and prevents Node.js from exiting. In an app that cancels requests when closed, the app will successfully cancel requests but then hang until the timeouts expire.

#### To Reproduce
The code below will log a cancel error and then hang for 30 seconds before exiting.

```js
const cancelTokenSource = axios.CancelToken.source();

axios.get("http://google.com", { timeout: 30000, cancelToken: cancelTokenSource.token })
	.then(response => console.log(response.status))
	.catch(err => console.log(err));

setTimeout(() => cancelTokenSource.cancel(), 1);
```

#### Expected behavior
It should log a cancel error and immediately exit.

#### Environment
 - Axios Version 0.21.4
 - Node.js 14.16.0
 - Windows 10

**Comment by RubenVerborgh** [comment]
Thank you, released `follow-redirects@1.14.5` with the fix.

**Comment by shrpne** [comment]
`follow-redirects@1.14.9` is used in the latest axios, i guess the issue should be closed

**Comment by jdaley** [comment]
Confirmed fixed.
