### ISSUE TITLE
breaking interface change

### ISSUE THREAD

**Issue by andrei9669** [axios/axios#4109]
#### Describe the bug
In https://github.com/axios/axios/pull/2995 merge request, there was introduced a bug.

There came 2 issues.
1. input and output types have to be the same.
2. existing usages are broken

#### To Reproduce
pass input and output type to axios.post

```typescript
interface Input {
  name: string;
}
interface Output {
  value: string;
}
/* existing usages are broken
 * TS2345: Argument of type '{ name: string; }' is not assignable to parameter of type 'undefined'.
 */
const { data } = await axios.post<Output>('url', {
  name: 'hello',
});
/* Input and output have to be the same type
 * TS2345: Argument of type '{ name: string; }' is not assignable to parameter of type 'AxiosResponse<Output>'.   
 * Object literal may only specify known properties, and 'name' does not exist in type 'AxiosResponse<Output>'.
 */
const { data } = await axios.post<Input, AxiosResponse<Output>>('url', {
  name: 'hello',
});
```

#### Expected behavior
No type errors.

#### Environment
 - Axios Version 0.22.0
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 94.0.4606.61
 - Node.js Version v14.17.5
 - OS: Windows 10
 - Additional Library Versions none

#### Additional context/Screenshots

**Comment by ChristianIvicevic** [comment]
Why is this closed? I just noticed that the type for `post` is erroneous as you explained and causes compilation issues on my end:
```typescript
export class Axios {
  post<T = never, R = AxiosResponse<T>>(url: string, data?: T, config?: AxiosRequestConfig<T>): Promise<R>;
}
```

**Comment by andrei9669** [comment]
@ChristianIvicevic yeah, sorry about that, I checked the merge request and there was link to ts sandbox and it seemed to work there so I thought it was issue on my end. will repon.

**Comment by TheVaan** [comment]
Hey, for me, the merge of #2995 also breaks my interceptors:

```
TS2532: Object is possibly 'undefined'.
    21 | 
    22 |   instance.interceptors.request.use(function (config) {
  > 23 |     config.headers["Access-Control-Allow-Origin"] = "*";
       |     ^^^^^^^^^^^^^^
```

**Comment by caugner** [comment]
Same here, observed in the failing CI run of Dependabot's PR:

```
    src/lib/ApiClient.ts:99:17 - error TS2345: Argument of type '{ state_event: string; }' is not assignable to parameter of type 'LimitedInvitation'.
      Object literal may only specify known properties, and 'state_event' does not exist in type 'LimitedInvitation'.
    99                 state_event: 'accept',
                       ~~~~~~~~~~~~~~~~~~~~~
```

Here, `LimitedInvitation` is the expected **return** type, whereas `{ state_event: string; }` is the parameter type:

```ts
    interface LimitedInvitation {
        token: string
        state: string
    }

    async invitationAccept(token: string): Promise<LimitedInvitation> {
        return axios
            .patch<LimitedInvitation>(`/api/invitations/${token}`, {
                state_event: 'accept',
            })
            .then(({ data }) => data)
    }
```

**Comment by tjhorner** [comment]
@rijkvanzanten I don't think that was the PR that introduced this issue. The issue is caused by the `data` parameter's type changing from `any` to `T` (the response type) — that PR changes the default type for `T` to `never`, but doesn't touch `data`.

It looks like `data`'s type was changed to `T` in #2995.

**Comment by remcohaszing** [comment]
I would really like to point out that:

- #3002 isn’t the culprit, but #2995 is
- #4116 fixes it
- #4140 includes the fix along with some more typing fixes
- #4141 is unrelated
