### ISSUE TITLE
Delete method parameters not consistent with other methods.

### ISSUE THREAD

**Issue by fcastrocs** [axios/axios#4119]
#### Section/Content To Improve
Method parameters not consistent.

#### Suggested Improvement
Why are the delete() method parameters not consistent with other definitions such as post() or get() that take a 'data' parameter?
"axios": "^0.21.4",

AxiosInstance.delete<any, AxiosResponse<any>>(url: string, config?: AxiosRequestConfig | undefined): Promise<AxiosResponse<any>>

AxiosInstance.post<any, AxiosResponse<any>>(url: string, data?: any, config?: AxiosRequestConfig | undefined): Promise<AxiosResponse<any>>

AxiosInstance.get<any, AxiosResponse<any>>(url: string, config?: AxiosRequestConfig | undefined): Promise<AxiosResponse<any>>

#### Relevant File(s)
sorry, didn't know where to post this.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
