### ISSUE TITLE
Axios calls between docker containers

### ISSUE THREAD

**Issue by godtaehee** [axios/axios#4121]
#### Describe the issue
I have same Issue with this #2817

@chinesedfan

you said "DNS resolving is out of the scope of axios."

Can't axios support DNS resolving in ONLY docker container?

This mean that axios support DNS resolving in general case ??

Thanks

#### Example Code
![Screen Shot 2021-10-02 at 2 01 54 AM](https://user-images.githubusercontent.com/44861205/135659381-7bb30b59-f8be-46bd-9cd9-c82f0985a222.png)

```js
      // work well
      const tokenResult = await axios.post('http://127.0.0.1:3001/v1/token', {
        clientSecret: process.env.CLIENT_SECRET,
      });
```

```js
      // now work
      const tokenResult = await axios.post('http://localhost:3001/v1/token', {
        clientSecret: process.env.CLIENT_SECRET,
      });
```

#### Expected behavior, if applicable
Success Axios Request

#### Environment
 - Axios Version [0.21.1]
 - Adapter [/HTTP]
 - Browser [Chrome]
 - Browser Version [94]
 - Node.js Version [14.17.0]
 - OS: [OSX 11.5.2]
 - Additional Library Versions [20.10.8]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by scarletquasar** [comment]
![image](https://github.com/axios/axios/assets/70824102/21a50dea-08b0-4574-a5ff-8bc913af451b)

Issue happening with me @jasonsaayman
