### ISSUE TITLE
Issue parsing json body in response (all versions since v0.21.2)

### ISSUE THREAD

**Issue by mark-night** [axios/axios#4123]
#### Describe the bug
json in response body is not parsed as before.
In my Axios config I have `{ responseType: 'json' }` set.
Then classic way to get the json body would be something like 
```
someAxiosInstance.post('/some/api/endpoint')
  .then(function (response) {
    const { data } = response;
    // do something with data...
  }).catch(...)
```
This was all good and smooth. I recently updated axios in my previously working project, and errors start to be thrown, traced all the way to axios, where the `data` from response is simply just raw json object without being parsed. This is not true before my project last seen working fine with axios v0.21.1.
Manually parse json in `transformResponse` sure can work, but I think this is not axios intension to have user parse json manually?
Reversing back to v0.21.1 fixes everything. All versions since 0.21.2 seems to suffer the same issue. 

Read release logs, this does not seem to be an intended change, so I'd guess there might be a bug somewhere.
Tried v0.22.0 just released, many new typing related issues are showing up, e.g., `instance.defaults.headers` is now possible `undefined` and things like `instance.defaults.headers.common['Authorization']` becomes hard even if I put non-null assertion on `headers`, it still complains about `'Authorization'` is not a number and can not be used to index `common`. And `axios.isAxiosError()` as a type guard, now asserts response as `AxiosResponse<never> | undefined`, where the `never` generic parameter makes no sense, because it's common to retrieve api response from an error response, `never` intends to prevent this....

#### To Reproduce
Kinda tight in schedule now, can't prepare any sandbox to reproduce this, but they are all very basic setup and usage, would be very easy to reproduce in regular usage.

#### Expected behavior
If specified `responseType`  as 'json', response.data should be parsed to JS object instead of left as raw json string.

#### Environment
 - Axios Version [all versions since v0.21.2]
 - create-react-app [4.0.3] with typescript template
 - OS: [macOS 11.6]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by DigitalBrainJS** [comment]
> would be very easy to reproduce in regular usage.

Can you reproduce the issue in [this sandbox ](https://codesandbox.io/s/axios-issues-post-test-3ewug?file=/src/index.js) or any other?

**Comment by mark-night** [comment]
@DigitalBrainJS Thanks for looking into this quickly and helped to setup the sandbox.

So I tested it for a while and finally realized that it was the `transformResponse` in instance config that caused the issue. 
If you take a look at this [sandbox](https://codesandbox.io/s/axios-issues-post-test-forked-d527x?file=/src/index.js) forked off yours, I have `transformResponse` set in the instance config, it does nothing and just return data received. With that set, the `data` destructed from `response` is of type `string`, and has to be manually parsed as json.

*This is not the case back in v0.21.1.*

According to documentation, 
>// `transformResponse` allows changes to the response data to be made before
>// it is passed to then/catch

It indeed makes sense if `data` should be manually parsed here if developer is to manipulate it here, however, I personally prefer more the way v0.21.1 deals this (`data` is pre-parsed before passed into `transformResponse` as argument):
- It's more conventional.
- Manipulating `data` is not always the logic in `transformResponse`, e.g., developer might just want to log something or simply (conditionally) do something with the `data`, although the config field is named as "transform", it does not limit usages not transforming...

At least we know now where the issue is. I'd recommend making it the same as before, i.e. with `transformResponse` configured, `data` is still parsed before passed down. Or, if there are good reasons for Axios to take current approach (not parsing if configured), it'd be better if an option can be provided for developer to choose whether to parse `data` or not so it's clear to developer what should be done, besides, it is a breaking change that should be mentioned. 

Other issues regarding typing changes since v0.22.0 is pretty obvious, and are mentioned in other issue reports as well, so I guess there is no need to setup sandboxes to demonstrate them.

Thanks. Great library by the way!

**Comment by DigitalBrainJS** [comment]
@mark-night The main purpose of transform handlers is data conversion, so IMHO, if anyone wants to use their data transformation handler instead of the standard one, we have to provide that capability, even for the JSON data type (#983, #3440). Perhaps some users needed their own JSON data parser that supports the BigInt primitive - we cannot exclude this possibility. Previously, Axios `<v0.22.2` had an architecture issue that caused JSON parsing attempts in two places - inside the XMLHTTPRequest and in the default transform request handler (only in client build). This led to inconsistencies and complications in the code, and it is for this reason that currently all data transformations are performed in transformation chains. This approach ensures that users can transform their data as they wish, without any hidden Axios logic.
On the other hand, the user can always use the default response transformation handler like this:
```js
const someAxiosInstance = axios.create({
  responseType: "json",
  transformResponse: [
    ...axios.defaults.transformResponse,
    (data) => {
      return data;
    }
  ]
});
```
It seems to look good.

**Comment by mark-night** [comment]
@DigitalBrainJS Ah, I see.

>  if anyone wants to use their data transformation handler instead of the standard one, we have to provide that capability, even for the JSON data type
>all data transformations are performed in transformation chains. This approach ensures that users can transform their data as they wish, without any hidden Axios logic

These all make sense, and the change actually makes things clearer. I must have missed some detail in release note or documentation, that I never thought the default behavior of transform chain has changed. My bad.

I'll close the issue then because there is indeed no issue here. Thanks again for providing this great library.

I still recommend looking into those typing issues since v0.22.0, which is not part of this thread but might be worth checking.
