### ISSUE TITLE
Axios class typings are incorrect in v0.22.0

### ISSUE THREAD

**Issue by gstamac** [axios/axios#4131]
#### Describe the bug
Typing definitions in v0.22.0 are incorrect for Axios class methods. Request (eg. https://github.com/axios/axios/blob/master/index.d.ts#L146) methods typings indicate request data and response should be the same type. That is not correct.

#### To Reproduce
Use any request method in typescript and define `data` property of the config object. It will expect the response to be of the same type.

#### Expected behavior
Types should be something like this
```
export class Axios {
.......
  request<T = never, R = AxiosResponse<T>, RC = any> (config: AxiosRequestConfig<RC>): Promise<R>;
.......
}
```

#### Environment
 - Axios Version 0.22.0

#### Additional context/Screenshots
n/a

**Comment by TheVaan** [comment]
Duplicate to #4109

**Comment by jasonsaayman** [comment]
Closing please see #4109
