### ISSUE TITLE
Open the HTML repsonse in new tab

### ISSUE THREAD

**Issue by yiyasha15** [axios/axios#4138]
#### Describe the issue
The API response.data is HTML document, I want to open the html in a new tab. Is it possible?

#### Example Code
<img width="717" alt="Screen Shot 2021-10-05 at 15 44 24" src="https://user-images.githubusercontent.com/15736353/136003213-2153945d-7ca9-49c7-b124-be0acf19a600.png">

```js
// Example code here
```

#### Expected behavior, if applicable
Open the html file in a new tab.

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kanatBektursyn** [comment]
You can try to send back redirect from server and handle it with with `<script type="text/javascript">window.open('<URL>');</script>` on received response for your frontend

**Comment by yiyasha15** [comment]
@kanatBektursyn thank you for responding.

This helps when I have a URL, but here I am getting like an HTML doc as a data response, not a URL.

Printing response.data on the screen below. 

<img width="1436" alt="Screen Shot 2021-10-06 at 09 39 31" src="https://user-images.githubusercontent.com/15736353/136138194-8e6cdc3b-fe75-4054-83aa-54ca40d3a93c.png">

How can I open this html in a new tab?

**Comment by yiyasha15** [comment]
@kanatBektursyn if i go to Network and click my api and see the preview, I can see the page there.
<img width="1201" alt="Screen Shot 2021-10-06 at 09 43 09" src="https://user-images.githubusercontent.com/15736353/136138563-673dd424-1af6-4a1b-9a10-4641b05f4c8c.png">

**Comment by kanatBektursyn** [comment]
```javascript
var newWindow = window.open();
newWindow.document.write(html_response);
```

**Comment by yiyasha15** [comment]
@kanatBektursyn this is great! it worked, thank you so much!
