### ISSUE TITLE
axios keep-alive won't work since 0.21.4

### ISSUE THREAD

**Issue by youngmin-kim36** [axios/axios#4139]
#### Describe the bug
On axios 0.21.4 also 0.22.0 the keep-alive mechanism does not work correctly.
It is only concerned with the request timeout even if keep-alive packets transfer correctly.
The socket is always closed by axios as soon as the time has passed longer than the request timeout value after last http packet transferred.

But the keep-alive mechanism works correctly on axios 0.19.2.
The socket stays connected as long as the keep-alive packet transferrs without failure.

Attatched screenshot is the captuerred packet flows when socket closed by axios even if keep-alive packet has sent between axios(61587) and express server(10500).
no.37 shows last http transmission between axios(61587) and express server(10500).
no.38 from no.39 shows keep-alive packets.
no.40 shows the active socket close by axios(61587) after request timeout(2000ms) has passed since no.37.

It seems like the request timeout is used as the connection idle timeout since axios 0.21.4.

#### To Reproduce

```js
// axios usage
import axios from 'axios';
import http from 'http';
import https from 'https';

const axiosInst = axios.create({
  baseURL: 'http://DESKTOP-0L2O4FC:10500',
  timeout: 2000,
  httpAgent: new http.Agent({ keepAlive: true }),
  httpsAgent: new https.Agent({ keepAlive: true }),
});

let cnt = 0;
const sendReq = function () {
  axiosInst
    .post('/move', {
      userId: 9999,
      moveState: {
        val: cnt++,
      },
    })
    .then((res) => {
      console.log('sent ok', cnt);
      setTimeout(() => {
        sendReq();
      }, 2000);
    })
    .catch((err) => {
      console.log('got error', err);
      setTimeout(() => {
        sendReq();
      }, 2000);
    });
};
sendReq();

// express server
import express from 'express';
import http from 'http';

const app = express();

app.disable('x-powered-by');
app.disable('etag');
app.disable('content-type');

const server = http.createServer(app);

app.post('/move', (_req, res) => {
  console.log('/move req');
  res.end();
});

const bindAddress = '0.0.0.0';
const port = 10500;

server.listen(port, bindAddress, () => {
  console.log('start listening ...', { bindAddress, port });
});
```

#### Expected behavior

The keep-alive mechanism should work correctly as previous axios 0.19.2.

#### Environment
 - Axios Version [0.21.4 , 0.22.0]
 - Adapter [XHR/HTTP]
 - Browser [N/A]
 - Browser Version [N/A]
 - Node.js Version [12.13.1]
 - OS: [Ubuntu 16.04.4 LTS, Windows 10]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots

![axios 0 21 4 timeout 2000 - 마크](https://user-images.githubusercontent.com/91928576/136007456-700edcf2-417b-4baa-9d52-c884644e1561.png)
.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Comment by Shannawhaley** [comment]
https://githubpk.com/pk/repo?repoWithOwner1=oclaumc/page-in-bio&repoWithOwner2=eggjs/egg

Try might do the job automatically
Please forgive me as i am late in my studies.
I could use shorter and easier scrip to help her along .Shanna Whaley
