### ISSUE TITLE
axios.post is sending a GET request

### ISSUE THREAD

**Issue by EthanDunfordAspect** [axios/axios#4149]
#### Describe the bug
axios.post is sending a GET request

This behavior shouldn't be happening and there are multiple issues that can cause this

https://stackoverflow.com/questions/46611275/axios-post-is-sending-a-get-request

#### To Reproduce
Code example below

```js
  axios.post('http://url.com/path').then((r) => {
      console.log('response', r.data)
    })

```

#### Expected behavior
When a post request is made a post request happens and not transform into a get request

#### Environment
 - Axios Version [5.13.6]
 - Adapter [e.g. XHR/HTTP]
 - Browser [N/A]
 - Browser Version [N.A]
 - Node.js Version [v14.15.4]
 - OS: [Ubuntu 20.04]
 - Additional Library Versions [Nuxt:2.15.7]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Closing as this is not a Axios issue
