### ISSUE TITLE
Uncaught TypeError is raised for axios.create with axios version 0.22.0

### ISSUE THREAD

**Issue by ssrikanta** [axios/axios#4153]
#### Describe the bug
Uncaught TypeError is raised for axios.create with axios version 0.22.0
Issue is observed while merging the defaultConfig, with instanceConfig.
We are setting instanceConfig only

#### To Reproduce
Exception is raised while creating axios instance with below sample code.

```js
const service  = axios.create({
     baseURL: "host",
     timeout: 3000
})

```

#### Expected behavior
Same works with axios version 0.21.4

#### Environment
 - Axios Version [0.22.0]
 - Browser [Chrome, Edge]
 - Browser Version [Version 94.0.4606.71 (Official Build) (64-bit)]
 - Node.js Version [14.15.1]
 - Additional Library Versions [VueJS 3.2.19, vue-axios 3.3.7]

#### Additional context/Screenshots
Exception stack trace
axios.js:1308 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mergeConfig (axios.js:1308)
    at Function.create (axios.js:1712)

**Comment by ssrikanta** [comment]
@jasonsaayman  @remcohaszing This issue is observed with v0.23.0 as well.
axios.js:1308 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mergeConfig (axios.js:1308)
    at Function.create (axios.js:1712)

**Comment by remcohaszing** [comment]
Sorry, I referenced this by accident. Please reopen.

**Comment by ssrikanta** [comment]
I can't reopen this issue, but it would be really helpful, if you or any one else can reopen

**Comment by zachstence** [comment]
I am also experiencing this error using v0.24.0.

```ts
const baseURL = "http://localhost:8080";
const api = axios.create({baseURL});
```

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mergeConfig (mergeConfig.js:92)
    at Function.create (axios.js:27)
    at api.ts:4
    at main.ts:8
```

**Comment by Roboroads** [comment]
Also having this issue - issue has been since 0.22.0 since forcing version to 0.21.4 fixes the issue.

**Comment by jhg023** [comment]
Rollup was my issue as well; I was able to update version `0.24.0` of Axios by adding the following resolutions to my `package.json`:

```
"resolutions": {
  "@rollup/plugin-alias": "3.1.8",
  "@rollup/plugin-babel": "5.3.0",
  "@rollup/plugin-commonjs": "21.0.1",
  "@rollup/plugin-node-resolve": "13.0.6",
  "@surma/rollup-plugin-off-main-thread": "2.2.3",
  "rollup": "2.60.0"
},
```

**Comment by doesdev** [comment]
PSA: If you're like me and think you're up to date on your rollup plugins, it's possible that you're still using an outdated source. Specifically (in this case), rollup-plugin-commonjs has been replaced by @rollup/plugin-commonjs. There are others which follow the same pattern, but this is the one causing this particular problem.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
