### ISSUE TITLE
Circular dependancies when using Rollup

### ISSUE THREAD

**Issue by skiv71** [axios/axios#4158]
(!) Circular dependencies
node_modules/axios/lib/defaults.js -> node_modules/axios/lib/adapters/xhr.js -> node_modules/axios/lib/defaults.js
node_modules/axios/lib/defaults.js -> node_modules/axios/lib/adapters/xhr.js -> /home/neil/coding/git/skiv71/wallet-du/wallet/web-component/node_modules/axios/lib/defaults.js?commonjs-proxy -> node_modules/axios/lib/defaults.js

I've checked the code and I do see circulars...

Should this be rejigged?

**Comment by vnues** [comment]
use v0.21.1 can be solved
