### ISSUE TITLE
Let's Encrypt SSL_CERT_EXPIRED Error

### ISSUE THREAD

**Issue by pokecheater** [axios/axios#4161]
Hello Axios-Team,

we are facing a strange error where we always get SSL_CERT_EXPIRED when we try to make a axios call from nodejs. This was working like a charm a week ago... As far as we found out we had to renew the Let's Encrypt Certificate with a new trusted authority root certificate but the problems still persists. Do you have any ideas how to deal with that?

Greetz and thx in advance :-)

**Comment by hbrls** [comment]
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

I guess this is the problem.
