### ISSUE TITLE
Axios Let's Encrypt Bug

### ISSUE THREAD

**Issue by pokecheater** [axios/axios#4162]
#### Describe the bug
Hello Axios-Team,

we are facing a strange error where we always get SSL_CERT_EXPIRED when we try to make a axios call from nodejs. This was working like a charm a week ago... As far as we found out we had to renew the Let's Encrypt Certificate with a new trusted authority root certificate but the problems still persists. Do you have any ideas how to deal with that?

Greetz and thx in advance :-)
#### 

Make a call against a let's encrypt ssl web page.

 const {data: {uuid}} = await simpleCallAPI("GET", "auth/uuid", null, false);
    const cookies = await session.defaultSession.cookies.get({url: authHost});
    const refreshOptions = {
        method: 'POST',
        url: `${authHost}${refreshPath}`,
        headers: {
                "Cookie": "sid="+cookies[0].value,
                "x-api-key": apikey
        },
        data: {
            "uuid": uuid
        }
    };
    
    try {
        const response = await axios(refreshOptions);
        accessToken = response.data.token;
        await simpleCallAPI("POST", "auth/token", { token: accessToken }, false);
    } catch (error) {
        console.error(error);
        throw error;
    }  

#### Expected behavior
Should run like a charm

#### Environment
 - Axios Version [e.g. 0.21.4]
 - Adapter [e.g. XHR/HTTPS]
 - Browser [e.g. Electron]
 - Browser Version [e.g. 12]
 - Node.js Version [e.g. 12.18.3]
 - OS: [WIN 10, PopOS 20.04]

#### Additional context/Screenshots
None

**Comment by wojciethecat** [comment]
@dentarg same problem with nodejs-17.1.0-2

**Comment by jasonsaayman** [comment]
Please look at https://runkit.com/embed/z7m43rn3qw5a it seems to be working for getting the lets encrypt site itself? Can you please check the SSL version on the machine running the request?

**Comment by wojciethecat** [comment]
> Please look at https://runkit.com/embed/z7m43rn3qw5a it seems to be working for getting the lets encrypt site itself? Can you please check the SSL version on the machine running the request?

i did copy it 1 TO 1 and it does not work

**Comment by wojciethecat** [comment]
also there is same EXACT problem with "got" https requesting.

**Comment by jasonsaayman** [comment]
I think you need to check the SSL version on the machine you are running the code on, which platform is the code being run on Mac, Linux or PC?

**Comment by wojciethecat** [comment]
@jasonsaayman OpenSSL 1.1.1

**Comment by jasonsaayman** [comment]
Please check that you have the ISRG Root X1 in your trust store, there are a couple explanations on how to do this online but since I do not know the OS you are using I cannot link one here.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks

**Comment by jasonsaayman** [comment]
Awesome 🎉
