### ISSUE TITLE
onUploadProgress Never Fires

### ISSUE THREAD

**Issue by httpjamesm** [axios/axios#4168]
#### Describe the issue
A clear and concise description of what the issue is.

onUploadProgress in my Axios config never fires when sending FormData through POST.

#### Example Code
Code snippet to illustrate your question

```js
            var formData = new FormData();
    
            formData.append('file', file);

            console.log("uploading...");

            const config = {
                onUploadProgress: progressEvent => {
                    console.log(progressEvent)
                },
                data: formData,
                method: "POST",
                url: `${process.env.NEXT_PUBLIC_API_URL}/upload`,
            }
    
            var uploadRequest;
    
            try {
                uploadRequest = await axios(config);
            } catch (err) {
                if (err.response) {
                    if (err.response.status == 413) {
                        showError("File too large.");
                        continue;
                    } else if (err.response.status == 406) {
                        showError("Banned file type.");
                        continue;
                    }
                }
            }
```

#### Expected behavior, if applicable

onUploadProgress should fire regularly to show the progress of the POST request to my API endpoint.

#### Environment
 - Axios Version 0.21.1
 - Browser: Chromium
 - Browser Version 92.0.4515.159
 - Node.js Version 16.8.0
 - OS: Ubuntu 20.04 LTS
 - Next 11.1.0
 - React 17.0.2

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by lnmp4000** [comment]
Could it be the order events get bound. I found this statement on MDN:

> The spec also seems to indicate that event listeners should be attached after open(). However, browsers are buggy on this matter, and often need the listeners to be registered before open() to work.

I notice in the xhrAdapter that the events will be bound after `open` has been called on the XMLHttpRequest object.

See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload

**Comment by adam-maj** [comment]
Experiencing the same issue 6 months later - did you ever find a fix for this @httpjamesm

**Comment by httpjamesm** [comment]
> Experiencing the same issue 6 months later - did you ever find a fix for this @httpjamesm 

Nope, but I opted for xhr instead.

**Comment by adam-maj** [comment]
> > Experiencing the same issue 6 months later - did you ever find a fix for this @httpjamesm
> 
> Nope, but I opted for xhr instead.

Do you have an example setup or any code that worked? Trying to set this up right now and wanted to use xhr with form data but haven't found any working setups

**Comment by httpjamesm** [comment]
> > > Experiencing the same issue 6 months later - did you ever find a fix for this @httpjamesm
> > 
> > 
> > Nope, but I opted for xhr instead.
> 
> Do you have an example setup or any code that worked? Trying to set this up right now and wanted to use xhr with form data but haven't found any working setups

```ts
let xhr: XMLHttpRequest = new XMLHttpRequest();
let progress: number = 0;

xhr.upload.addEventListener(
	'progress',
	(e) => {
		if (e.lengthComputable) {
			progress = Math.round((e.loaded / e.total) * 100);
		}
	},
	false
);

const formData = new FormData();
formData.append('file', fileObj);

xhr.open('POST', "/api/upload", true);

xhr.send(formData);
```

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
