### ISSUE TITLE
CSRF token could be incorrect when issuing multi requests at same time

### ISSUE THREAD

**Issue by gbfvip** [axios/axios#4173]
#### Describe the bug
CSRF token sometimes could be incorrect when issuing multi request happen at same time, and server response different token for every http request.

#### To Reproduce
Let's say we issuing 3 http requests towards server after a initial token already exists in cookie(set by previous response)
1. POST request P1 send to server with initial token pass validation and get a new CSRF token(token1) via SET-COOKIE
2. POST request P2 send token1 in header and token1 in cookie, server response a new CSRF token(token2) via SET-COOKIE
3. just before browser save token2 into cookie store, POST request P3 start, extract token1 from **old** cookie and set it into header
4. browser save token2 into cookie store finished
5. after header set, POST request P3 use new cookie with **token2 in cookie** and **token1 in header** send to server, so 403 response happened

#### Expected behavior
CSRF token value in header should always use the one in cookie when the request actual happen

#### Environment
 - Axios Version 0.19.2
 - Adapter XHR
 - Browser Chrome
 - Browser Version 94.0.4606.61 (Official Build) (64-bit)
 - OS: Windows 10 Version 1909(OS build 18363.1801)
 - Additional Library Versions React 16.13.1

#### Additional context/Screenshots
this error occasionally happen from time to time in this client env.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
