### ISSUE TITLE
Typescript types do not make sense

### ISSUE THREAD

**Issue by euberdeveloper** [axios/axios#4175]
I updated from axios `0.21.1` to `0.22.0` but typescript started giving me strange errors

I then noticed that the types declarations changed and they do not make much sense. 

I can see that the `post` signature is:
```
post<T = never, R = AxiosResponse<T>>(url: string, data?: T | undefined, config?: AxiosRequestConfig<T> | undefined): Promise<R>
```

I don't really get why the response data object should be, by default, equal to the object passed as body, there is really no sense for that as a default behaviour. It should be AxiosResponse<any> instead.

For the `axios` function, the returned object is even a `never`, in `axios(config: AxiosRequestConfig<any>): AxiosPromise<never>`.

Of course I can just put the types specifications, but it makes the code longer and ugly when there would be many times no reason for that.

**Comment by vanslly** [comment]
@euberdeveloper  Yes I found this weird as well. To accommodate the new typings I have done the following migration:

**from**:
```
const result = await client.post<LoginResponse>(
    "login",
    {
      username,
      password,
    },
    {
      withCredentials: false,
    }
  );
  return result.data;
```

**to**:
```
const result: AxiosResponse<LoginResponse> = await client.post(
    "login",
    {
      username,
      password,
    },
    {
      withCredentials: false,
    }
  );
  return result.data;
```

That way I'm using type inference.
