### ISSUE TITLE
Require cycle: node_modules/axios/lib/defaults.js 

### ISSUE THREAD

**Issue by detroit007** [axios/axios#4177]
#### Describe the bug

Require cycle: node_modules/axios/lib/defaults.js -> node_modules/axios/lib/adapters/xhr.js -> node_modules/axios/lib/defaults.js

#### To Reproduce

update the axios to latest version 0.22.0 and the warning occur

#### Environment
 - Axios Version 0.22.0
 
![Screen Shot 2021-10-12 at 6 14 34 PM](https://user-images.githubusercontent.com/41494244/136962951-ca31b940-143e-42de-ac24-a35de0ad5927.png)

how to remove this warning? It came every time I refresh.

**Comment by detroit007** [comment]
@jasonsaayman I've upgraded to 0.23 and the warning is still there.

**Comment by nurulamelia2** [comment]
Sorry, can you tell me, how do I update that version?

**Comment by MuhammadSandyPrastyo** [comment]
> I think it appeared in v0.22 [76f09af](https://github.com/axios/axios/commit/76f09afc03fbcf392d31ce88448246bcd4f91f8c) <img alt="Screenshot 2021-10-26 at 10 36 07" width="630" src="https://user-images.githubusercontent.com/5295025/138830255-668ee035-6927-4944-b337-287aa3fd8999.png">
> 
> Looks like this warning can be ignored - defaults needed only for that line `var transitional = config.transitional || defaults.transitional;`
> 
> Anyway it is annoying and can lead to uninitialized values.

just comment this line 
var defaults = require('../defaults')

**Comment by ProgramadorLeandroSantos** [comment]
just comment the `require('defaults')` at `node_modules/axios/lib/defaults.js` and this line `var transitional = config.transitional || defaults.transitional;`

**Comment by thomaschampagne** [comment]
Any status on this?

**Comment by DevChrisRoth** [comment]
Try axios Version `0.21.4`.

**Comment by Arifursdev** [comment]
😫

**Comment by cumironin** [comment]
v 0.21.4 still not working on svelte or the newer

**Comment by jasonsaayman** [comment]
Pull request by @DigitalBrainJS has been merged, this will be in the new release

**Comment by Marko0513** [comment]
> Pull request by @DigitalBrainJS has been merged, this will be in the new release

which version? Currently I am using "axios": "^0.26.0", but Still remain that problem...

How can I fix this problem? 

![image](https://user-images.githubusercontent.com/77128380/157122113-637bc4a6-8dc9-4a74-8816-5415506791b1.png)

**Comment by jasonsaayman** [comment]
This will be in v1, the current version that is being worked on

**Comment by Marko0513** [comment]
Can I send package.json file. Currently I am working with latest version.
![image](https://user-images.githubusercontent.com/77128380/157204108-82882d4a-236b-4167-9e35-60359c7cc7d6.png)

**Comment by wjaykim** [comment]
@Marko0513 He means the version is not released yet.

**Comment by Marko0513** [comment]
Ok, @wjaykim got it.

**Comment by jasonsaayman** [comment]
I will try release a minor version with this in this week

**Comment by Marko0513** [comment]
Hello, @jasonsaayman 
Can I get any news for your fixing the warning? It's same yet.
![image](https://user-images.githubusercontent.com/77128380/158187785-2b522385-2362-4e01-8c47-a3e9350b544e.png)

**Comment by TomK** [comment]
@Marko0513 you need to use https://github.com/axios/axios/releases/tag/v0.26.1

**Comment by Marko0513** [comment]
okay, really thanks for notify, can I install with npm or I will download the module with manual?

**Comment by jasonsaayman** [comment]
@Marko0513 can be installed via rpm
