### ISSUE TITLE
Config header types are wrong in `Axios.create`

### ISSUE THREAD

**Issue by felixmosh** [axios/axios#4184]
#### Describe the bug
The type of `headers` field in `Axios.create` config doesn't supports headers for specific requests method.

#### To Reproduce

```js
Axios.create({
      baseURL: '/api',
      headers: {
        get: {
          'Cache-Control': 'no-cache',
          Pragma: 'no-cache',
          Accept: '*/*',
          'Accept-Encoding': 'gzip, deflate, br', 
        } , // this get field can't be an object
        'User-Agent': `${process.env.API_SERVER_NAME}/${process.env.BUILD_VERSION}`,
      },
    })
```
![image](https://user-images.githubusercontent.com/9304194/137096572-15fcedc7-33ba-46d5-9e0c-abc3bd982392.png)

The js code do supports it.
https://github.com/axios/axios/blob/1025d1231a7747503188459dd5a6d1effdcea928/lib/defaults.js#L126-L132

#### Expected behavior
It should allow pass any request method inside headers

#### Environment
 - Axios Version [e.g. 0.23.0]
 - XHR/HTTP [e.g. XHR/HTTP]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]

#### Possible solution
it is possible to extend the `AxiosRequestConfig` type and use it in `create` method.

```ts
export interface AxiosCreateConfig extends Omit<AxiosRequestConfig, 'headers'> {
  headers: AxiosRequestHeaders | Partial<{
    delete: AxiosRequestHeaders,
    get: AxiosRequestHeaders,
    head: AxiosRequestHeaders,
    post: AxiosRequestHeaders,
    put: AxiosRequestHeaders,
    patch: AxiosRequestHeaders,
  }>;
}

export interface AxiosStatic extends AxiosInstance {
   create(config?: AxiosCreateConfig): AxiosInstance;
   Cancel: CancelStatic;
   CancelToken: CancelTokenStatic;
   Axios: typeof Axios;
}
```
#### Additional context/Screenshots

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks

**Comment by ghost91-** [comment]
Hi @jasonsaayman, it still happens in `1.0.0-alpha.1`:
```ts
const axiosRequestConfig: AxiosRequestConfig = {
    headers: {
        get: { 'Accept-Language': 'en' }
    }
}
```
This results in the following error:
```
Type '{ get: { 'Accept-Language': string; }; }' is not assignable to type 'Partial<AxiosHeaders & MethodsHeaders & CommonHeaders>'.
  Property 'get' is incompatible with index signature.
    Type '{ 'Accept-Language': string; }' is not assignable to type 'string | number | boolean | string[] | undefined'.
      Object literal may only specify known properties, and ''Accept-Language'' does not exist in type 'string[]'.ts(2322)
```
