### ISSUE TITLE
Type 'AxiosPromise<unknown>' is not assignable to any other type.

### ISSUE THREAD

**Issue by kolia-zamnius** [axios/axios#4188]
#### Describe the bug
My TSLint gives an error (see screenshot) after upgrading from 0.21.4 to 0.23.0 axios.

#### To Reproduce
If in `AxiosPromise` you pass any value other than `unknown`, then TSLint throws an error. For example, if I receive a {name: string} object in response, then I cannot use the interface to specify this in `AxiosPromise`.

#### Expected behavior
I would like to pass the response interface if I know exactly what to expect.

#### Environment
 - Axios Version 0.23.0
 - Node.js Version 16.9.0

#### Additional context/Screenshots
![Screenshot from 2021-10-14 15-51-55](https://user-images.githubusercontent.com/87366536/137320916-606b5aaa-709c-403f-890b-de844dbee12d.png)

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks

**Comment by gitRacoon** [comment]
Yes, now it works without this issue.
