### ISSUE TITLE
NO_PROXY does not support *.com

### ISSUE THREAD

**Issue by bokzor** [axios/axios#4192]
#### Describe the bug
Regex seems to not be supported  for no_proxy.

#### To Reproduce
Just set NO_PROXY = "*.bc"

```js
var proxy = undefined;
var protocol = 'http';
const url = require('url');
var parsed = url.parse('https://myurl.bc/mypath/');
var proxyEnv = 'http_proxy';
var proxyUrl = process.env[proxyEnv] || process.env[proxyEnv.toUpperCase()];
console.log(proxyUrl);
if (proxyUrl) {
    var parsedProxyUrl = url.parse(proxyUrl);
    var noProxyEnv = process.env.no_proxy || process.env.NO_PROXY;
    console.log('NO PROXY: ' + noProxyEnv);
    var shouldProxy = true;
    if (noProxyEnv) {
        var noProxy = noProxyEnv.split(',').map(function trim(s) {
            return s.trim();
        });
        shouldProxy = !noProxy.some(function proxyMatch(proxyElement) {
            if (!proxyElement) {
                return false;
            }
            if (proxyElement === '*') {
                return true;
            }
            if (
                proxyElement[0] === '.' &&
                parsed.hostname.substr(parsed.hostname.length - proxyElement.length) === proxyElement &&
                proxyElement.match(/\./g).length === parsed.hostname.match(/\./g).length
            ) {
                return true;
            }

            return parsed.hostname === proxyElement;
        });
    }

    if (shouldProxy) {
        console.log('SHOULD PROXY');
    } else {
        console.log('SHOULD NOT PROXY');
    }
}
```

#### Environment
 - Axios Version [0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mbargiel** [comment]
Just throwing my 2 cents here, but there doesn't seem to be a real spec for "no_proxy". If it can be believed from [this Gitlab blog post](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/#how-did-we-get-here), it's really just a convention that is inconsistently applied.

Typically, you should expect `.your.domain` or `your.domain` to bypass the proxy for `<any>.<subdomain>.your.domain`. So in your case, set `no_proxy` to `.bc` to strip `.bc` subdomains, just don't include `*`.

**Comment by bokzor** [comment]
Yes. It's what I did. Just wanted to open a ticket in case someone encounter the same issue.
