### ISSUE TITLE
Axios 0.21.0 and above does not merge url with baseURL

### ISSUE THREAD

**Issue by laygir** [axios/axios#4194]
#### Describe the bug
Original issue https://github.com/axios/axios/issues/3663
Following up on a previously closed issue as it was requested to open a new one if Axios 0.22.0 release did not fix it.
I'm not sure if authors made this change intentionally. But I'm not able to update my Axios package simply because this change is breaking all my requests.

#### To Reproduce
Updated the runkit with Axios 0.22.0 and 0.23.0
Result is still the same.
https://runkit.com/liger/axios-0-22-in-comparison

#### Expected behavior
Uri appended to baseURL.

#### Environment
Axios Version 0.23.0, 0.22.0, 0.21.1, 0.21.0, 0.20.0, 0.19.0, 0.18.0

#### Additional context/Screenshots
Notice the missing base url on v0.21.1 and above.

<img width="889" alt="Screenshot 2021-10-15 at 23 16 30" src="https://user-images.githubusercontent.com/772730/137555763-4348ddbd-6d70-4f92-8829-a1c4f65adbe2.png">

**Comment by Hyperdraw** [comment]
It seems like the request still works exactly the same - the only difference is that as of 0.19.1 it no longer prepends the `baseURL` to the `url` property directly (which it did [here](https://github.com/axios/axios/blob/8d0b92b2678d96770304dd767cd05a59d37f12cf/lib/core/dispatchRequest.js#L30)) and instead just joins them internally (which it does [here](https://github.com/axios/axios/blob/1025d1231a7747503188459dd5a6d1effdcea928/lib/adapters/http.js#L117)).

**Comment by tenkiller** [comment]
I'm quite puzzled and frustrated that this is _still_ an issue. Our enterprise app is locked on v0.18.1, ever since this **bug** was introduced in v19. I'm not even sure I can confidently recommend to my development team we upgrade this package even _if_ this **bug** gets fixed.

**Comment by jasonsaayman** [comment]
This should be fixed by the build full path helper check it [here](https://github.com/axios/axios/blob/master/lib/core/buildFullPath.js)
