### ISSUE TITLE
v0.23.0 report error，lower versions is ok

### ISSUE THREAD

**Issue by StrugglingAndroid** [axios/axios#4199]
#### Describe the bug
v0.23.0 report error，lower versions is ok：

Uncaught TypeError: Cannot set property 'axios' of undefined
    at universalModuleDefinition:9
    at universalModuleDefinition:1
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:1

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
import 'https://unpkg.com/axios/dist/axios.min.js';
```

#### Expected behavior
axios to be imported correctly

#### Environment
 - Axios Version [v0.23.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Google，Weixin etc]

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/20653456/137693086-61b52a2a-33e5-478c-a7b8-8c7385a6f18f.png)

**Comment by AP2008** [comment]
`import` does not work in browsers. Including it using a `<script>` tag works.
