### ISSUE TITLE
Data validation in AxiosRequestConfig

### ISSUE THREAD

**Issue by p8nut** [axios/axios#4200]
#### Is your feature request related to a problem? Please describe.
I'm always frustrated when i need to validate the data types from a response after an axios call.

#### Describe the solution you'd like
like response status, i'd like to validate response data with a validateData in the AxiosRequestConfig.
Also, in typescript, the validateDate could define automatically the returned type.

#### Describe alternatives you've considered
Wrap my calls in a parent function to check the data type returned.

#### Additional context
```typescript
type User = {
    firstname: string;
    lastname: string;
};

function isUser(o: any): o is User {
    return isObject(o) && isString(o['firstname']) && isString(o['lastname']);
}

// Actual type validation.
async function getUser(id: number) {
    const { data } = axios.get(`/users/${id}`);
    if (!isUser(data)) {
        throw Error('invalid response type');
    }
    return data;
}

// Proposed type validation.
async function getUser(id: number): User {
    return axios.get(`/users/${id}`, { validateData: isUser });
}
```

**Comment by karlhorky** [comment]
Nice proposal! 👍

Wonder if a static-types-only solution would be a potentially less complicated alternative.

Eg. supporting configuration of the TypeScript types of the expected request and response for each request path (and checking the type of the request type) would yield most of the benefits without the downside having to run JS code at runtime.

Also, no need to duplicate the configuration `{ validateData: isUser }` being passed every time that you want to make a call to `/users/${id}` - it will already be configured.

```ts
type PathTypes = [
  {
    method: 'PUT',
    path: `/users/${string}`,
    requestBody: {
      name: string,
    },
    responseBody: {
      name: string,
      favoriteColor: string,
    },
  },
];

const instance = axios.create<PathTypes>({
  baseURL: 'https://example.com/api/',
});

const user = await axios.put(`/users/${id}`, {
  namez: 'new name', // ❌ Type error: Property namez does not exist on type
});

user.favoriteColor // ✅ Type: string
user.favoriteColorrr // ❌ Type error: Property favoriteColorrr does not exist on type
```

**Comment by karlhorky** [comment]
Oh wait, maybe generic parameters already exist on instances? Just reading in this closed PR here: https://github.com/axios/axios/pull/4603

**Comment by jasonsaayman** [comment]
Yeah, it should actually work much better than it currently does. The team is working on a full v2 with much better TS support, I have added this to the backlog so I will try prioritise it.

**Comment by p8nut** [comment]
should i close the issue ?
