### ISSUE TITLE
Axios next

### ISSUE THREAD

**Issue by jasonsaayman** [axios/axios#4209]
Over the next few months I will be working on a new version of Axios, a v1 release bringing a vast amount of modernisations and bringing the library up to date with modern JS practices.

I would like people to please add any suggestions they have to this mega thread for discussion.

During this period I will also start closing any issues/pull requests that are related to future proposals or new features that are not backward compatible.

**Comment by sttvld** [comment]
Flexible timeout settings might be handy, but for me, only connectTimeout is extremely important because working with some API methods that respond in hours.
Using Got on backend only because of them.
https://github.com/sindresorhus/got/blob/main/documentation/6-timeout.md

**Comment by aladdin-add** [comment]
👍 to publish esm.

**Comment by xHyroM** [comment]
> 👍 to publish esm.

What for? Alternatively... let there be a CJS version, because I think it's a mistake to switch to this one. Thousands of people are on CJS and even with node-fetch this was not the best move. If so, I would do both ESM and CJS, but definitely not just ESM. For upgrading, I would also use TypeScript, which would help a lot of typing and make using the module even easier.

**Comment by MartinMuzatko** [comment]
Even with providing both CJS and ESM, it is still painful to integrate with universal apps like NextJS, where one package might be required as cjs serverside, and then forces esm clientside.
ESM is cool when building in the browser, but for modern apps it caused me more pain than relief ^^"

**Comment by jasonsaayman** [comment]
@xHyroM we will have to see about a full TypeScript project, one of the great things about axios is it is a very small package. This will have to be investigated.

@MartinMuzatko I am not familiar with NextJS but if the module is published in ESM and includes the current checks to see if we are in the browser or not then the build process should take care of compilation into whatever the target is.

**Comment by aladdin-add** [comment]
yes, good to have a cjs export too, as esm cannot be required.

I recommended using dual mode:
https://nodejs.org/api/packages.html#packages_dual_commonjs_es_module_packages
```js
{
  "name": "axios",
  "type": "module",
  "main": "./index.cjs",
  "exports": {
    "import": "./index.mjs",
    "require": "./index.cjs"
  }
}
```

and drop node < 12.22.0:
![image](https://user-images.githubusercontent.com/13050025/145345203-5b6f8546-bf91-44d3-938b-c55080948d22.png)

**Comment by xHyroM** [comment]
> yes, good to have a cjs export too, as esm cannot be required.
> 
> I recommended using dual mode: https://nodejs.org/api/packages.html#packages_dual_commonjs_es_module_packages
> 
> ```js
> {
>   "name": "axios",
>   "type": "module",
>   "main": "./index.cjs",
>   "exports": {
>     "import": "./index.mjs",
>     "require": "./index.cjs"
>   }
> }
> ```
> 
> and drop node < 12.22.0: ![image](https://user-images.githubusercontent.com/13050025/145345203-5b6f8546-bf91-44d3-938b-c55080948d22.png)

This is a good solution. I also know of a builder, https://esbuild.github.io/getting-started/ that might help with building for cjs/esm.

**Comment by Rolanddoda** [comment]
Ohh that sounds great!

One suggestion or request from me is to NOT introduce breaking changes. By using libraries in general, I hate seeing breaking changes all around.

If breaking changes are the only way for -> "bringing a vast amount of modernisations and bringing the library up to date with modern JS practices" I suggest you do that in a smart way.

I am not sure what "smart-way" means, but "right now" one thought I have is of releasing breaking changes one-by-one and not going from v0.24.0 to v1 directly.

Also... I think having RFCs (request for comments) for each breaking change or new design for features is always a good thing.

Axios is awesome! 🥳

**Comment by binki** [comment]
> If breaking changes are the only way for -> "bringing a vast amount of modernisations and bringing the library up to date with modern JS practices" I suggest you do that in a smart way.
> 
> I am not sure what "smart-way" means, but "right now" one thought I have is of releasing breaking changes one-by-one and not going from v0.24.0 to v1 directly.

If you actually want to avoid things breaking with API level breaking changes, using a new package name is the only safe way. That’d let you install it side by side with the old version and allow consumers to switch to the new version as they desire any features which could not be delivered without breaking the old API.

**Comment by popuguytheparrot** [comment]
Fixes broken types for response, config

**Comment by arthurfiorette** [comment]
> Are you considering TypeScript for Axios next? Or are you keeping d.ts files separate on purpose?

It would be so much better to write the new axios natively in typescript. If we take a look at the most amount of current open PR's, they are just to fix the `index.d.ts` file. A thing that with the new typescript codebase would be caught early.

Plus, with webpack, the inpact of typescript to the transpiled javascript can be literally 0.

**Comment by CatsMiaow** [comment]
How about support `undici` in Node.js environment
- https://nodejs.medium.com/introducing-undici-4-1e321243e007
- https://github.com/nodejs/undici

**Comment by cgarrovillo** [comment]
> How about support `undici` in Node.js environment
> 
> * https://nodejs.medium.com/introducing-undici-4-1e321243e007
> * https://github.com/nodejs/undici

Not supported on the browser no?

**Comment by CatsMiaow** [comment]
> Not supported on the browser no?

See https://github.com/nodejs/undici/issues/968

`undici` is a module rewritten by the Node.js team to replace the core HTTP stack.
I don't know what's good about using `undici` in the browser.

`axios` is also used a lot in the backend, so supporting `undici` can lead to better performance.
The HTTP module of `NestJS`, the representative Node.js backend framework, is also combined with `axios`.
> https://github.com/nestjs/axios

**Comment by arthurfiorette** [comment]
The `undici` adapter is the same as the [`HarmonyOS`](https://github.com/axios/axios/pull/4348) one. It will just depends on how the axios maintainers would do it, either by sticking it into the main package (like the `xhr` or `node`) or creating a `@axios/undici-adapter`, for example.

**Comment by jasonsaayman** [comment]
An official adapter might be a good option, actually it is part of the ideas i have here, more official adapters that make you able to choose what you want and don't want in your axios experience

**Comment by hughns** [comment]
@jasonsaayman have the maintainers considered making a v1 release based on the current codebase? (Essentially taking the current v0.26.0 and promoting it to v1.0.0).

_Yes_, it may have never been the intention that the library is considered v1 worthy in its current form, _but_ due to the quality of this API it has been adopted by many (71k+ public dependents and 26M weekly downloads according to https://www.npmjs.com/package/axios).

By immediately moving to major releases the maintainers might actually become freer to make the more invasive changes as they can more clearly signal to the users what is a breaking change or not.

Alongside the releases the maintainers could also choose to publish a support schedule which makes it clear about the level of support (or lack of support) that is to be provided for current versions.

So, this would make Axios next be something like v2.0.0. ...or you could choose to take a more incremental approach and release in smaller major releases (Axios next could be thought of as a series of vN+1 releases).

**Comment by jasonsaayman** [comment]
I like this idea, ok @hughns I think you are correct, the next release I cut will be 0.27 and then a v1. We will then work towards next which is whatever version +1 as mentioned above.

**Comment by jasonsaayman** [comment]
Additionally I am going to close this issue and we can move this to a discussion at #4477
