### ISSUE TITLE
Using Axios in a node worker_thread get "XMLHttpRequest is not defined" error

### ISSUE THREAD

**Issue by ale-grosselle** [axios/axios#4230]
#### Describe the bug
When you use axios in a node's worker thread the library returns this error message: "XMLHttpRequest is not defined"

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
//Main thread:
const { Worker } = require('worker_threads');
const worker = new Worker("./worker.js");

//Listen for a message from worker
worker.postMessage("run!");

// worker.js file:
const { parentPort } = require('worker_threads');

const getRequest = async function() {
    const tiresias = await Axios({
      baseURL: 'https://example.com/hades/v2',
      url: '/autocomplete/predict',
      method: 'get',
      params: { s: 'tets', min: 0.1 },
    });
}
parentPort.once('message', message => getRequest());  
```

#### Expected behavior
I don't understand why this error occurs and how to fix it. ("XMLHttpRequest is not defined")

#### Environment
 - Axios Version: 0.21.1
 - Adapter: Good question, I guess HTTP (node env), but I don't know why the error says "XMLHttpRequest..."
 - Node.js: 14.17.0
 - OS: Bis Sur 11.5.2

#### Additional context/Screensh
![Schermata 2021-10-30 alle 10 05 12](https://user-images.githubusercontent.com/6173088/139525371-fcaf9ad5-457a-4eb7-b9c5-4c0b834304fa.png)
ots

**Comment by Wimmind** [comment]
@ale-grosselle hi, did you solve the problem?
