### ISSUE TITLE
Using Axios in a node worker_thread get "XMLHttpRequest is not defined" error

### ISSUE THREAD

**Issue by ale-grosselle** [axios/axios#4231]
#### Describe the bug
When you use axios in a node's worker thread the library returns this error message: "XMLHttpRequest is not defined"

#### To Reproduce
```js
//Main thread:
import { Worker } from 'worker_threads'
const worker = new Worker("./worker.js");

//Listen for a message from worker
worker.postMessage("run!");

// worker.js file:
import { parentPort } from 'worker_threads'
import Axios from 'axios';

const getRequest = async function() {
    const tiresias = await Axios({
      baseURL: 'https://example.com/hades/v2',
      url: '/autocomplete/predict',
      method: 'get',
      params: { s: 'tets', min: 0.1 },
    });
}
parentPort.once('message', message => getRequest());  
```

#### Expected behavior
I don't understand why this error occurs and how to fix it. ("XMLHttpRequest is not defined")

#### Environment
 - Axios Version: 0.21.1
 - Adapter: Good question, I guess HTTP (node env), but I don't know why the error says "XMLHttpRequest..."
 - Browser: not necessary, a server side problem
 - Browser Version: not necessary, a server side problem
 - Node.js: 14.17.0
 - OS: Bis Sur 11.5.2
 - Additional Library Versions: Next.js framework

#### Additional context/Screenshots
![Schermata 2021-10-30 alle 10 05 12](https://user-images.githubusercontent.com/6173088/139525447-04e5abd3-192f-4b56-b9e6-e416bafa073f.png)

**Comment by ale-grosselle** [comment]
To workaround the problem I do this:


```js
// worker.js file:
import { parentPort } from 'worker_threads'
import Axios from 'axios';

//**********FORCE TO USE http adapter (node.js version):*****
 Axios.defaults.adapter = require('axios/lib/adapters/http.js');
//**********FORCE TO USE http adapter (node.js version):*****
const getRequest = async function() {
    const tiresias = await Axios({
      baseURL: 'https://example.com/hades/v2',
      url: '/autocomplete/predict',
      method: 'get',
      params: { s: 'tets', min: 0.1 },
    });
}
parentPort.once('message', message => getRequest());  
```

**Comment by DigitalBrainJS** [comment]
It seems to work fine https://codesandbox.io/s/axios-issue-4231-5nruu

**Comment by ale-grosselle** [comment]
Yes, I agree with you, playing with your example, seem it works properly.

I close the issue and get more investigation, thanks!

**Comment by pleek91** [comment]
I'm running into this issue as well. I have an npm package that uses axios to interact with a specific api. When I import and use the package in a node context I get "XMLHttpRequest is not defined" but when I use it in the browser it works just fine. The only difference I'm seeing between my and @ale-grosselle's code and the example @DigitalBrainJS posted is we're using `import axios from 'axios'` rather than `const axios = require('axios')`. If I change my import then it works in node but not in the browser. Isn't the axios adapter supposed to switch automatically based on where its being run?

**Comment by Wimmind** [comment]
@pleek91 did you manage to solve the problem?

**Comment by pleek91** [comment]
I have not, very frustrating
