### ISSUE TITLE
"proxy: false" is not working

### ISSUE THREAD

**Issue by taronlee** [axios/axios#4234]
#### Describe the bug

**Proxy** is already set in remote-ssh settings in VS Code.
![proxy](https://user-images.githubusercontent.com/18044244/139647486-84abfcbc-6e76-4ae3-9d8f-59cad35fae10.png)

I want to use axios api without proxy so I add the `proxy: false` property in the `axios.interceptors`.
But It doesn't work..

**`We should never change proxy settings.`**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**
```
const axiosAPI = axios.create({
  baseURL: apiBaseUrl
});

axiosAPI.interceptors.request.use(requestConfig => {
  if (!requestConfig.headers || !requestConfig.headers['Authorization']) {
    requestConfig = {
      ...requestConfig,
      headers: {
        ...requestConfig.headers,
        ['Authorization']: `UGT ${token}`
      },
      proxy: false
    };
  }
  return requestConfig;
});
```

```js
axiosAPI.get(`${query}`);
```

#### Environment
 - Axios Version [e.g. 0.24.0]
 - Node.js Version [e.g. 12.22.1]

**Comment by xuyicheng1995** [comment]
@taronlee hello  i also have this problem, have u resolved the problem?
