### ISSUE TITLE
"proxy:false" is not working

### ISSUE THREAD

**Issue by taronlee** [axios/axios#4235]
#### Describe the bug
**Proxy** is already set in remote-ssh settings in VS Code.
![proxy](https://user-images.githubusercontent.com/18044244/139650698-e91f123f-b228-4043-b38c-d8456a6311cf.png)

I want to use axios api without proxy so I add the `proxy: false` property in the `axios.interceptors`.
But It doesn't work..

**`We should never change proxy settings.`**

#### To Reproduce
```
const axiosAPI = axios.create({
  baseURL: apiBaseUrl
});

axiosAPI.interceptors.request.use(requestConfig => {
  if (!requestConfig.headers || !requestConfig.headers['Authorization']) {
    requestConfig = {
      ...requestConfig,
      headers: {
        ...requestConfig.headers,
        ['Authorization']: `UGT ${token}`
      },
      proxy: false
    };
  }
  return requestConfig;
});
```

```js
axiosAPI.get(`${query}`);
```

>rejected promise not handled within 1 second: Error: Failed to establish a socket connection to proxies: ["PROXY ${host}:8080"]
stack trace: Error: Failed to establish a socket connection to proxies: ["PROXY ${host}:8080"]
	at _PacProxyAgent.<anonymous> (/home3/the.lee/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/node_modules/vscode-proxy-agent/out/agent.js:141:19)
	at Generator.throw (<anonymous>)
	at rejected (/home3/the.lee/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/node_modules/vscode-proxy-agent/out/agent.js:6:65)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

#### Expected behavior
works with no-proxy

#### Environment
 - Axios Version [e.g. 0.24.0]
 - Node.js Version [e.g. 12.22.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
