### ISSUE TITLE
Request incorrectly prepends local ip address for remote URLs on RPi

### ISSUE THREAD

**Issue by ellipsistechnology** [axios/axios#4239]
#### Describe the bug
A request that uses an IP address on a Raspberry Pi running in Node.js always prepends the local ip address and port 8080 when the given URL is absolute. This does not occur when using localhost instead of an IP address. 

#### To Reproduce
The follow code correctly interprets the host and path of the url on Mac, but uses the absolute URL as the path on Raspberry Pi:

```js
const axios = require('axios')

axios.get('http://192.168.1.100:8100/some/path')
.then(console.log)
.catch(console.error)
```

Host 192.168.1.100 in my case is not listening on port 8100, therefore this gives an error with useful information. Specifically, on the Pi is shows the local IP address, port and path:
```
  address: '192.168.1.102',
  port: 8080,
  path: 'http://192.168.1.100:8100/some/path'
```

#### Expected behavior
It should correctly interpret the host, port and path; on the Mac, this shows the correct address and port:
```
  address: '192.168.1.100',
  port: 8100,
  path: '/some/path'
```

#### Environment
 - Axios Version [0.21.1]
 - Adapter [default/unknown]
 - Browser [N/A]
 - Browser Version [N/A]
 - Node.js Version [16.4.1]
 - OS: [Raspbian (Debian 10.8)]
 - Additional Library Versions [N/A]

#### Additional context/Screenshots
I'm happy to assist in resolving if given some guidance on where to look.

**Comment by ellipsistechnology** [comment]
It turns out that this issue was caused by an incorrectly configured proxy. /lib/adapters/http.js is prepending the proxy host to the URL.

**Comment by bertiespell** [comment]
@ellipsistechnology is there a workaround for this? I'm still seeing this issue, using axios 0.27.2

**Comment by ellipsistechnology** [comment]
@bertiespell Thanks for the tip. I'll try this when I'm not back on the project where I was having this issue.
It makes sense that the proxy would be prepended, even when you have http:// in your URL, what's needed I think is to have an ignore list setting for when to not use the proxy. This may exist, but I haven't looked for it, so not sure. It's been a while since I had this issue - haven't been on the RPi project for a while - so I may look for an ignore list option when back on it.
