### ISSUE TITLE
API key from header appears in error message

### ISSUE THREAD

**Issue by maggie0002** [axios/axios#4246]
#### Describe the bug
I am catching the error responses from Axios when a request fails. I then use the error request to create logs, log to console or return to the browser. In many of these instances the error contains `axios.defaults.headers.common.Authorization` set before the request. I started going through deleting them before logging, but they are all over in the response and request, and {config} with the response and request. 

Ideally there would be a way to clean this up automatically so the outputs are safe to use anywhere. 

#### To Reproduce
Any failed request

#### Expected behavior
Have a way to remove the Authorisation headers so error message can be used safely. 

#### Environment
 - Axios Version [0.24.0]

**Comment by maggie0002** [comment]
Maybe a little over zealous by the bot. Not much here to add to JSFiddle or the like. It could potential come under a feature request, but showing Authorisation headers seems like a bug to me.

**Comment by shawnsparks-work** [comment]
Opened a security vulnerability for this. We'll see if it gets any traction. https://huntr.dev/bounties/46857f58-7655-42e4-b0cf-8e6d824358b0
