### ISSUE TITLE
NodeJS Socket hang up when sending post form data in a loop

### ISSUE THREAD

**Issue by edandweb** [axios/axios#4250]
#### Describe the bug

I have a list of users and I need to update their profile picture, I am doing a for loop to go through all the users and I am sending my form data request. The first one is always working, the second one depends on his humor and after that I got socket hang up error. The interesting thing is that the script not calling the remote server.

#### To Reproduce
1. Have an API server with upload file
2. Create a list of users 
3. Loop on this list
4. Send Post request with form data
5. Log the results 

```js
// Example code here


const picture = fs.createReadStream('pictures/logo.jpg')

for (let i = 0; i < nbUsers ; i += 1) {
       
        const url = `ENDPOINT API`;
        const form = new FormData();
        let response;

        form.append('0', picture);
        form.append('action', 'upload');

        const headers = form.getHeaders();
        headers.Cookie = cookies;

        try {
            response = client.post(url, form, { headers: headers });
        } catch (e) {
            console.error(e.message);
        }
        return response;
}
```

#### Expected behavior
All requests are supposed to be send to the server.

#### Environment
 - Axios Version 0.24.0
 - Node.js Version 14.17.5
 - OS: Ubuntu 18.04.6

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edandweb** [comment]
The problem was on my side I tried to reuse the stream of my file and for a reason it causes the socket hang up. If someone is interesting to explain my mistake I will enjoy :).
For discovering it I rewrote my code with the another rest client and I had the same problem.

**Comment by JordanMicle2019** [comment]
Great! It was same case with mine. Thanks

**Comment by shantanudwvd** [comment]
can you please explain how you resolved this issue.

**Comment by JordanMicle2019** [comment]
Simple but hacker way. You need to createstream inside loop, not out of loop

**Comment by edandweb** [comment]
Yes he's right you need to create a stream for each request.

**Comment by leerle** [comment]
> 

Thanks for your explanation!!
