### ISSUE TITLE
Type 'AxiosPromise' is not a valid async function return type in ES5/ES3

### ISSUE THREAD

**Issue by Captain1653** [axios/axios#4258]
#### Describe the issue
I have some errors in my IDE. How can I fix it? (`Promise<AxiosPromise>` looks really strange)

#### Example Code

```js
export async function changeCourseReminder(): AxiosPromise { /* error here, even with AxiosPromise<any> */
    return requestAsync();
}

async function requestAsync() {
    return Axios({
        method: "post",
        url: "someUrl",
        data: {value: 1},
    });
}
```
Details in the section `Additional context/Screenshots`

#### Expected behavior, if applicable
No errors

#### Environment
 - Axios Version 0.24.0
 - Node.js Version: 15.14.0
 - OS: iOS 12.0.1
 - IntelliJ IDEA 2021.2.3

#### Additional context/Screenshots
<img width="1324" alt="promise" src="https://user-images.githubusercontent.com/4740207/141343443-f76a58fb-872b-4789-a6fb-f4115cf30501.png">

Please, let me know if you need any additional information. 

Kind regards

**Comment by chinesedfan** [comment]
In fact, you can also enjoy the type suggestions without writing the return type. But if you want to make it clear, you can hover on the function name, then the IDE will show the infered type. Usually, it will be something like `Promise<AxiosReponse<T>>`.

**Comment by Captain1653** [comment]
Thank you @chinesedfan
