### ISSUE TITLE
data passed as parameters insted of body when performing an post with header "application/x-www-form-urlencoded" with an already parsed string

### ISSUE THREAD

**Issue by mpcabete** [axios/axios#4262]
#### Describe the bug
When performing an post with header "application/x-www-form-urlencoded" with an already parsed query string the data is passed as parameters in the post request instead of the body of the request. if the header is "text/x-www-form-urlencoded"  the or "text/plain" the data is passed in the body.

#### To Reproduce

```js

const headersBug = { "Content-Type": "application/x-www-form-urlencoded" };
const headersExpected = { "Content-Type": "text/x-www-form-urlencoded" };

const data = {foo:3, bar:'banana'}
const body = new URLSearchParams(data).toString()

// sends data as parameters
axios.post(api,body,{headersBug})
// sends data in the request body
axios.post(api,body,{headers})

```

#### Expected behavior
The data from the first request should be sent in the body

#### Environment

 - Node.js 16.13.0
 - OS: pop_os

#### Additional context/Screenshots

I used the website https://ptsv2.com/ to test the request

**Comment by celestialmechanic21** [comment]
Could not reproduce the bug.Please provide more info.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
