### ISSUE TITLE
Does Axios support 'keepalive' functionality as the native fetch() does (for browser unload)?

### ISSUE THREAD

**Issue by sheparddw** [axios/axios#4269]
#### Describe the issue
Can Axios be configured to keep requests alive after a browser page is closed? Native fetch() accepts keepalive flag to enable this functionality, while I haven't found any similar in Axios documentation. 
Asked previously but auto closed by the bot here: https://github.com/axios/axios/issues/4252

#### Example Code
```
window.onunload = function() {
  fetch('/analytics', {
    method: 'POST',
    body: "statistics",
    keepalive: true
  });
};
```

#### Expected behavior, if applicable
Closing the browser page does not keep the request from finishing (though the response cannot be handled, the request completes).
Navigator.sendBeacon() is the old way of doing this. fetch's keepalive property is the new way. Any support for either of these within axios? For example, to save your changes right before the browser closes so you do not lose work or send analytics.

#### Environment
 - Axios Version [0.24.0]
 - Browser [any]
 - OS: [any]

#### Additional context/Screenshots
> keepalive
> The keepalive option can be used to allow the request to outlive the page. Fetch with the keepalive flag is a replacement for the Navigator.sendBeacon() API.
> https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters

More context here:
https://javascript.info/fetch-api

**Comment by jasonsaayman** [comment]
Please check out the `AbortController` as this should handle this use case, should it not work please open a new issue.

**Comment by ssidorchik** [comment]
👋 @jasonsaayman I see how `AbortController` can help to cancel requests. But in the above use case the opposite behavior is expected to let the request being completed on page close. Could you reopen this ticket?

**Comment by freeman1995** [comment]
please reopen this ticket
`AbortController` has nothing to do with this
and this issue is super important IMO

**Comment by sheparddw** [comment]
@ssidorchik or @freeman1995 feel free to open a new issue and add the context about how AbortController does not help. Looks like I do not have permissions to reopen this one.

**Comment by freeman1995** [comment]
im sorry, i actually checked and axios does use keepAlive in web by default 
in Nodejs however there is a way to achieve that by using the `httpAgent` config option

**Comment by aderchox** [comment]
> im sorry, i actually checked and axios does use keepAlive in web by default in Nodejs however there is a way to achieve that by using the `httpAgent` config option

These two are not the same things... HTTP `keep-alive` is a different thing from fetch() API's `keepalive` (no hyphens) which allows using fetch() as a replacement for Beacon requests (sendBeacon() method allowed only POST requests).

FetchAPI's keepalive has been documented [here](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters):
> The keepalive option can be used to allow the request to outlive the page. Fetch with the keepalive flag is a replacement for the [Navigator.sendBeacon()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) API.

This can be absolutely necessary in certain use-cases and if Axios doesn't support it is an important missing feature.

**Comment by sheparddw** [comment]
Opened a new issue as I don't have permissions to reopen this one: https://github.com/axios/axios/issues/5145
