### ISSUE TITLE
axios post formData not have formData payload in chrome devtool

### ISSUE THREAD

**Issue by heart-er** [axios/axios#4270]
#### Describe the bug

axios post formData not have formData payload in chrome devtool

note: I can get formData value by formData.get method

#### To Reproduce
```js
const formData = new FormData();

formData.append('code', code);
formData.append('account', account);

const data = await axios.post(_api.uploadImage, formData, {
    headers: {
        'Content-Type': 'multipart/form-data',
    },
});
```

#### Expected behavior
have formData payload in chrome devtool

#### Environment
 - Axios Version 0.21.1
 - Browser  Chrome 
 - Browser Version 96.0.4664.45
 - Node.js Version  16.8.0
 - OS: macOS 11.3.1
 - Additional Library Versions  Vue 3.2.21

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/24717511/142154612-0e7c21af-cff2-49b9-8595-1f196b77d645.png)

![image](https://user-images.githubusercontent.com/24717511/142154659-79047cef-2d05-4257-b0cb-781f8005fb4a.png)

**Comment by privateOmega** [comment]
@heart-er Encountered the same problem with latest version of axios as well.

**Comment by Treborium** [comment]
I had the same issue and tried to debug it forever. In the end the [following gist](https://github.com/axios/axios/issues?q=is%3Aissue+is%3Aopen+form+data) by @akexorcist was the only fix that worked for me.

```typescript
const params = new URLSearchParams();

params.append('code', code);
params.append('account', account);

const data = await axios.post(_api.uploadImage, params, {
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
    },
});
```

**Comment by heart-er** [comment]
In the latest Chrome version, the payload has show, so i will close issue. It looked like a chrome bug before.
