### ISSUE TITLE
Network Error on Android

### ISSUE THREAD

**Issue by ASrey** [axios/axios#4271]
Hi everyone,
I ran into a really weird bug/thing a couple days ago.
Couldn't find anything helpful so i thought about opening a ticket here.

#### Describe the bug
Install the app, everything works like a charme.
Close & and kill the app manually, restart it and now Axios will return "Network Error" on every request to that same host.

#### To Reproduce
Create a new RN project, install Axios and do a simple get on start.
```
axios.get('https://myApi/action')
```

#### Expected behavior
A restart of an app should not make axios/fetch buggy.

#### Environment
 - Axios Version [0.24.0]
 - OS: [Android 11]
 - Additional Library Versions [e.g. React 17.0.2, React Native 0.66.3]

#### Additional context/Screenshots
- It's a real live api with https certificate (not self-signed, not localhost)
- it worked well before, suddenly happens around last week
- Bug can be found on real device from debug or from Play store.
- Happens only on Android
- The API works fine on cURL
- I tried multiples version of axios: same results.
- Funny thing, if i enable "Network Inspector", everything works....
- Only on Android

It's not happening on every hosts, juste some of them.
Should not come from a malfunction server-side as everything works well on the first time the app is opened.

Any ideas, thoughts i could work on?
Thanks a lot

**Comment by Seibold** [comment]
I experience the same issue.
- Axios Version [0.24.0]
- OS: [Android 11]
- Additional Library Versions [e.g. React 17.0.2, React Native 0.66.3]

**Comment by ASrey** [comment]
Found the issue.... 
It was the SSL certificate.
Some intermediate certificate were not "trusted" by Android and result in Network error by fetch.

Tips:
- Check your certificate by some SSL checkers online
- You can do a simple http request (not with fetch) and be able to get more debug information (that was my case).
How to fix it:
- Renew your certificate with a valid chain of trust
- Add your intermediate to your certificate server-side

**Comment by ddikodroid** [comment]
> Found the issue.... It was the SSL certificate. Some intermediate certificate were not "trusted" by Android and result in Network error by fetch.
> 
> Tips:
> 
> * Check your certificate by some SSL checkers online
> * You can do a simple http request (not with fetch) and be able to get more debug information (that was my case).
> 
> How to fix it:
> 
> * Renew your certificate with a valid chain of trust
> * Add your intermediate to your certificate server-side

what to expect when i check the certificate by ssl checker?

**Comment by nadir-karimo** [comment]
Hello, im facing the same issue.

Did you guys manage to fix this?

**Comment by ddikodroid** [comment]
> Hello, im facing the same issue.
> 
> Did you guys manage to fix this?

did you use ssl?

**Comment by nadir-karimo** [comment]
i am using ssl pinning, our app is in production. 

Some users randomly start getting Axios network error and the solution is to restart their device and it works fine afterwards.
