### ISSUE TITLE
REACT: Response printing on console.log but not showing in DOM

### ISSUE THREAD

**Issue by Coralain10** [axios/axios#4274]
#### Describe the issue
Hello!
I'm working on a project and I want to obtain only 1 object from GET (using id). It loads correctly on console.log but not on DOM, even using React.useState() and React.useEffect(). But it works well on process like list and create...
I've saw another question here about the same, but their answer didn't apply to my case...
So I would be very grateful if someone could enlighten me here.

#### Example Code

**api.ts**
```
import axios, { AxiosResponse } from "axios";

axios.defaults.baseURL = "https://url.../api/";

const responseBody = <t>(response: AxiosResponse<t>) => response.data;
const request = {
    get: <t>(url: string) => axios.get<t>(url).then(responseBody),
    post: <t>(url: string, body: {}) => axios.post<t>(url, body).then(responseBody),
    put: <t>(url: string, body: {}) => axios.put<t>(url, body).then(responseBody),
    delete: <t>(url: string) => axios.delete<t>(url).then(responseBody),
};

export default request;
```

**apiArtist.ts**
```
import axios from 'axios';
import { Artist } from "../models/artist";
import request from './api';
const apiArtist = {
	list: () => request.get<Artist[]>("/Artist"),
	add: (data: Artist) => request.post("/Artist", data),
	edit: (data: Artist) => request.put(`/Artist/${data.id}`, data),
	delete: (id: number) => request.delete(`/Artist/${id}`),
	detail: (id: number) => request.get<Artist>(`/Artist/${id}`),
};
```

**try.ts** (Component file)
```
import React, { useEffect } from 'react'
import { Artist } from '../../models/artist';

export function Try(props:any) {
  const [artist, setArtist] = React.useState<Artist>(new Artist());
  function refreshArtist(id:number){
	apiArtist.detail(id).then((res)=>{
		setArtist(res);
		console.log('i artist:',res); //it shows correctly on Console
	}).catch((err) => console.log(err));
  }

  React.useEffect(()=>{
    refreshArtist(12); //raw id I know will throw success
  },[]); // I've also tried here with:
//[artist] //it's like a while true on Console but doesn't update on DOM
//[artist.username] -->executes 2 times like the next 2 ones
//[artist.username===undefined,artist.username===""] (and them alone)
//[artist.username!==undefined,artist.username!==""] (and them alone)
//even without the last param...  React.useEffect(()=>{ ... });
  
  return (<>
      <div>
        <h2>Doing stuff with data</h2>
        {artist.username}  <- it stills doesnt's show up here
        {artist.name} <- neither here
      </div>
  </>)
};
```

#### Expected behavior, if applicable
I know the backend works well since I'm able to check the correct response on console...
But I don't know why it doesn't update on DOM. (on {artist.username} and {artist.name})

#### Environment
 - Axios Version 0.24.0
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 96.0.4664.45
 - Node.js Version 6.14.15
 - OS: Windows 10
 - Additional Library Versions React 17.0.2

**Comment by Coralain10** [comment]
I just tried using another free base URL (with other properties...) and it works (it shows on console and DOM).
Is there any axios authorization problem that turns it to undefined in DOM if not checked or something?
The original project is hosted on Heroku.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
