### ISSUE TITLE
axios.interceptors.response.use Question of

### ISSUE THREAD

**Issue by livelyPeng** [axios/axios#4276]
#### Is your feature request related to a problem? Please describe.
request.interceptors.request.use(config => {
      if (config .showLoading) {
        Loading.show()   //   Loading is a prompt component
    }
})

axios.interceptors.response.use(response => {
})
I want a config configuration

axios.interceptors.response.use(（response ，config）=> {
   config.showLoading ？Loading.hide()  //   Loading is a prompt component
})

If I request to carry a showloading?

I want to add a status when I request, and hide it when the request ends

#### Describe the solution you'd like
axios.interceptors.response.use(response => {
})
I want a config configuration

axios.interceptors.response.use(（response ，config）=> {
   config.showLoading ？Loading.hide()  //   Loading is a prompt component
})

If I request to carry a showloading?

I want to add a status when I request, and hide it when the request ends

**Comment by livelyPeng** [comment]
I want to realize that for a request, some requests need and some don't

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/142795063-986c3ef7-7a23-4b8b-a925-6ff6b37dc2dc.png)
Example

**Comment by jasonsaayman** [comment]
I don't think that this would be the best way to handle something like this, if you are using something like Vue.js or similar it would make more sense to handle this in the front end portion. ie show the loader when the request starts, hide it once the request settles.

**Comment by livelyPeng** [comment]
I use react， If it is not used in the interceptor, I need to add loading to every request
