### ISSUE TITLE
TS `AxiosRequestConfig` missing `responseEncoding` type

### ISSUE THREAD

**Issue by robahtou** [axios/axios#4285]
#### Describe the bug
The TS `AxiosRequestConfig` is missing the type for `responseEncoding`.  It is documented here https://github.com/axios/axios#request-config but missing in TS definition here https://github.com/axios/axios/blob/master/index.d.ts

#### To Reproduce
```js
const options: AxiosRequestConfig = {
    method: 'POST',
    url: shipmentsUrl,
    headers: {
      Accept: 'application/json'
    },
    responseType: 'json',
    responseEncoding: 'utf8',
    decompress: true,
    auth: {
      username: auth.username,
      password: auth.password
    }
  };
```
And the TS error is:
> 'responseEncoding' does not exist in type 'AxiosRequestConfig<any>'

#### Expected behavior
`responseEncoding` to be a valid TS type in `AxiosRequestConfig`

#### Environment
 - Axios Version: 0.24.0
 - Node.js Version: 16.9.1

#### Additional context/Screenshots
n/a

**Comment by jasonsaayman** [comment]
@robahtou can you open a pull request for this?

**Comment by jasonsaayman** [comment]
Should be fixed in the latest version we have a very exhaustive list
