### ISSUE TITLE
Meterean check reports vulnerability problem for Axios 0.24.0 #4288

### ISSUE THREAD

**Issue by mitsos1os** [axios/axios#4289]
#### Describe the bug
Meterian security check reports a vulnerability problem in axios v0.24.0.
The problem reported is the following: **The affected versions of this library are vulnerable to Cross-site Scripting (XSS)**

Also #3697 is referenced as an issue which has been recently closed, but no difference has been made.

Is the vulnerability still valid?

#### To Reproduce
Just run a meterian scan by providing the axios:v0.24.0 in a package.json

#### Expected behavior
Meterian check should pass on latest axios version

#### Environment
 - Axios Version 0.24.0

#### Additional context/Screenshots
![axios](https://user-images.githubusercontent.com/8208733/143438935-04dbf73f-7ce0-47e7-aad3-815c877017b4.png)

**Comment by jasonsaayman** [comment]
@mitsos1os please check our documentation on how to properly disclose a security problem for next time. I think this might be a new issue so I will have a look into it but since Synk works with us on these types of issues directly I feel they would have disclosed to me if they had found something.

**Comment by mitsos1os** [comment]
@jasonsaayman Sorry for missing the process for reporting security issues. We can certainly continue by mail if you wish so. The thing is that they report the #3697 issue as a reference which was closed a couple of days ago, but can't really understand whether a change that mitigates this issue was made

**Comment by mitsos1os** [comment]
Just wanted to say that this is still going on with version 0.25.0 and Meterian
