### ISSUE TITLE
Inconsistent behaviour with Object-URLs and baseUrl.

### ISSUE THREAD

**Issue by MaximKalinin** [axios/axios#4290]
#### Describe the bug

Axios treats Object-URLs (e.g. `blob:http://localhost:1234/825c2570-2fa0-489b-a61a-bbc325c5770a`) as absolute URLs if you use default `axios` instance.

However, if you create a custom instance with `axios.create` providing a `baseUrl` parameter, instance will treat the URL as relative and append it to `baseUrl`: `http://localhost:1234/blob:http://localhost:1234/825c2570-2fa0-489b-a61a-bbc325c5770a`.
#### To Reproduce

Here is the repository reproducing the problem: https://github.com/MaximKalinin/axios-bug-example.

Alternatively, you can use this js code:
```js
(async function will_fail()
{
    const instance = axios.create({baseURL: window.location.href});
    const obj = new Blob([]);
    const obj_url = URL.createObjectURL(obj);
    const response = await instance.get('/index.html');
    console.log(response.data);

    const obj_response = await instance.get(obj_url); // will throw 404 here
    console.log(obj_response.data);
})();

(async function will_not_fail()
{
    const obj = new Blob([]);
    const obj_url = URL.createObjectURL(obj);
    const response = await axios.get('/index.html');
    console.log(response.data);

    const obj_response = await axios.get(obj_url);
    console.log(obj_response.data);
})();
```

#### Expected behavior

Custom axios instance should treat Object-URLs the same way as default axios instance: as absolute URLs, without appending them to `baseUrl`.

#### Environment
 - Axios Version: 0.24.0
 - Adapter: XHR
 - Browser: tested on Chrome, Safari, but most probably browser-agnostic
 - Browser Version: Chrome 96.0.4664.55, Safari 15.0

#### Additional context/Screenshots

_A screenshot of failed request headers_
![image](https://user-images.githubusercontent.com/22202138/143560610-24dcf9bf-ca4a-4ad6-b008-dbf24883c573.png)

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
