### ISSUE TITLE
Missing AbortSignal interface used in index.d.ts

### ISSUE THREAD

**Issue by vishalailani** [axios/axios#4304]
#### Describe the issue
`AbortSignal` interface is missing from `index.d.ts`. it is used indise interface `AxiosRequestConfig`.

#### Example Code
```
export interface AxiosRequestConfig<D = any> {
  url?: string;
  method?: Method;
  baseURL?: string;
  transformRequest?: AxiosRequestTransformer | AxiosRequestTransformer[];
  transformResponse?: AxiosResponseTransformer | AxiosResponseTransformer[];
  headers?: AxiosRequestHeaders;
  params?: any;
  paramsSerializer?: (params: any) => string;
  data?: D;
  timeout?: number;
  timeoutErrorMessage?: string;
  withCredentials?: boolean;
  adapter?: AxiosAdapter;
  auth?: AxiosBasicCredentials;
  responseType?: ResponseType;
  xsrfCookieName?: string;
  xsrfHeaderName?: string;
  onUploadProgress?: (progressEvent: any) => void;
  onDownloadProgress?: (progressEvent: any) => void;
  maxContentLength?: number;
  validateStatus?: ((status: number) => boolean) | null;
  maxBodyLength?: number;
  maxRedirects?: number;
  socketPath?: string | null;
  httpAgent?: any;
  httpsAgent?: any;
  proxy?: AxiosProxyConfig | false;
  cancelToken?: CancelToken;
  decompress?: boolean;
  transitional?: TransitionalOptions;
  signal?: AbortSignal;
  insecureHTTPParser?: boolean;
}
```

#### Expected behavior, if applicable
`AbortSignal` interface should be there

#### Environment
  - Axios Version [0.22.0]

#### Additional context/Screenshots
<img width="1363" alt="Screenshot 2021-11-30 at 7 51 59 PM" src="https://user-images.githubusercontent.com/94852518/144065670-0d39b7f1-4479-4bfe-a312-6161c96bbdb8.png">

**Comment by vishalailani** [comment]
okay so i guess it will be merged in a day or two, right ?

**Comment by csnate** [comment]
You can also try installing @types/node@15 (or greater) as a devDependency for node projects. Worked for me.

Does this mean axios@0.24.0 requires Node 15?

**Comment by alecgibson** [comment]
For anyone on Node.js v14, I've raised: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58270

**Comment by jasonsaayman** [comment]
Going to close as newer node versions fix this and older versions are almost deprecated
