### ISSUE TITLE
AxiosError TypeScript type does not include all properties listed upon calling toJSON

### ISSUE THREAD

**Issue by timothymiller** [axios/axios#4311]
#### Describe the bug
AxiosError type should include status: number, only includes a limited selection of the properties listed upon calling toJSON

#### To Reproduce

cmd + click AxiosError type from VS Code

```js
{ code: number }
```

#### Expected behavior

AxiosError type to include status

#### Environment
 - Axios Version 0.24.0
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 94
 - Node.js Version 16
 - OS: OSX 12.0.1
 - Additional Library Versions React 16.8.0

#### Additional context/Screenshots
No additional information to provide

**Comment by arthurfiorette** [comment]
What version of axios are you using? 0.24.0 has these typings, doesn't it?

https://github.com/axios/axios/blob/53d6d37556a3443b00b3d9b4e7a934bf1d81aabe/index.d.ts#L124

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
