### ISSUE TITLE
Add documentation to types

### ISSUE THREAD

**Issue by OiYouYeahYou** [axios/axios#4315]
#### Section/Content To Improve
The type definitions do not have documentation included. Which means that inline documentation isn't available. This is compounded by incredibly unhelpful single letter generics.

#### Suggested Improvement
Add jsdoc/tsdoc to type doc

#### Relevant File(s)
`index.d.ts`

**Comment by arthurfiorette** [comment]
Copying from the axios-http website and pasting with TSDoc formatting is a pretty good start. There are some relevant pages like [this one](https://axios-http.com/docs/req_config) that explains basically everything.

It is going to do some merge conflicts with previous PR's and influence the raw index.d.ts file readability, but will return of a much better developer experience with this library.

**Comment by OiYouYeahYou** [comment]
@jasonsaayman, Hey, you closed this without reason. Is this a "won't fix", or are you triaging for something else?

**Comment by jasonsaayman** [comment]
I don't know why I closed this but that was a mistake, I think I may have thought this was documentation and wanted to move all of this over to the docs repo. Sorry about that 🙏

**Comment by jasonsaayman** [comment]
going to close this for now as its not something we can prioritise at this point
