### ISSUE TITLE
Multiple set-cookie headers in the same response lead to unexpected headers parsing

### ISSUE THREAD

**Issue by emilioheinz** [axios/axios#4329]
#### Describe the bug
Giving the following HTTP response headers:
```
Set-Cookie: cookie_key_1=yyy; Path=/
Set-Cookie: cookie_key_2=xxx; expires=Mon, 17-Oct-2016 17:16:25 GMT; httponly; Max-Age=1209600; Path=/
```
I receive the following data on the response headers:

```
set-cookie: ["cookie_key_1=yyy; Path=/, cookie_key_2=xxx; expires=Mon, 17-Oct-2016 17:16:25 GMT; httponly; Max-Age=1209600; Path=/"]
```

#### Expected behavior
I was expecting to receive two items in the array, each of them representing one of the set-cookie headers. But, instead of that, I'm receiving one item in the array and each of the headers split by a comma.

Ex:
```
set-cookie: [
  "cookie_key_1=yyy; Path=/",
  "cookie_key_2=xxx; expires=Mon, 17-Oct-2016 17:16:25 GMT; httponly; Max-Age=1209600; Path=/"
]
```

#### Environment
 - Axios Version: 0.23.0
 - Adapter: XHR
 - Browser: React Native, iOS and Android emulators
 - Browser: NA
 - Node.js Version: 14.15.4
 - OS: iOS 14.5
 - Additional Library Versions: React 17.0.2, React Native 0.66.1

If that isn't a bug how would I parse this header to get each Cookie?

**Comment by Aysanaaa** [comment]
@emilioheinz Hello, have you found a solution?

**Comment by abdulgafur24** [comment]
Hello, have you found a solution?

**Comment by abdulgafur24** [comment]
@emilioheinz Hello, have you found a solution?

**Comment by emilioheinz** [comment]
@abdulgafur24 Unfortunately not 😕

**Comment by gyunaev** [comment]
This doesn't seem to be the case:

Server:
```
echo -e 'HTTP/1.1 200 OK\r\nSet-Cookie: cookie_key_1=yyy; Path=/\r\nSet-Cookie: cookie_key_2=xxx; expires=Mon, 17-Oct-2016 17:16:25 GMT; httponly; Max-Age=1209600; Path=/\r\nContent-length: 4\r\n\r\ntest' | nc -l 8080
```

Client:
```
node -e '(async function(){ axios=require("axios"); console.log( (await axios("http://localhost:8080") ).headers ); })()'
```

Output:
```
{
  'set-cookie': [
    'cookie_key_1=yyy; Path=/',
    'cookie_key_2=xxx; expires=Mon, 17-Oct-2016 17:16:25 GMT; httponly; Max-Age=1209600; Path=/'
  ],
  'content-type': 'text/html'
}
```

Most likely your server doesn't use a proper separator between lines (i.e. \n instead of \r\n)/
