### ISSUE TITLE
when call AbortController.abort function, cannot passed in  a parameter

### ISSUE THREAD

**Issue by jimwei** [axios/axios#4330]
Hi,
I used AbortController.abort when request time out, but the abort function cannot pass in a parameter . 
I want to be able to pass a parameter to the abort call so that when the Cancel object is intercepted in the axios interceptor, the parameter can be retrieved from the Cancel object

**Comment by DigitalBrainJS** [comment]
`AbortController` is not part of Axios, it is a standard global interface that does not support passing payload to the `abort` method.
