### ISSUE TITLE
Empty array is stripped from response JSON

### ISSUE THREAD

**Issue by githorse** [axios/axios#4332]
#### Describe the bug
Axios removes a field in my response JSON with an empty array. In Postman:

```
GET /pizza
{
  "name": "deep dish",
  "radius": 6,
  "toppings": []
}
```

The same endpoint via Axios is missing the `toppings`:
```
{ 
  data: {
    name: 'deep dish',
    radius: 6
  },
  ... // other axios fields
}
```

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
import axios from 'axios' // 0.24.0

...
const response = await axios({
  method: 'GET',
  url: '/pizza'
})
console.log(response)
```

#### Expected behavior
I would expect an empty array to be preserved in the response (at least by default).

#### Environment
 - Axios Version: 0.24.0
 - Adapter: HTTP

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by joelvinaykumar** [comment]
I couldn't reproduce the bug with the same procedure and version given. Please provide more information like screenshots or screencasts.
Thank you.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
