### ISSUE TITLE
Need to bypass proxy

### ISSUE THREAD

**Issue by chasetec** [axios/axios#434]
I have some endpoints that my proxy server doesn't handle well and in my NodeJS environment the http_proxy environment is set.

Can you honor the no_proxy environmental variable and/or allow a config option to disable proxy usage?

I'm using axios@0.13.1 for now.

**Comment by nickuraltsev** [comment]
I agree that axios should honor the `no_proxy` env variable. As for a config option, we can use the existing option for that: if `proxy` is explicitly set to `null` or `false`, ignore proxy env variables. 

Are you interested in creating a PR for this?

**Comment by cesarp** [comment]
@nickuraltsev I can help with the fix since I need it too but I am unable to run the unit tests so not sure if I am breaking something else.

**Comment by nickuraltsev** [comment]
@cesarp What's going on with unit tests?

**Comment by cesarp** [comment]
The unit tests hang on my Linux machine but work properly in macOS

**Comment by vilinski** [comment]
Hi! Is there any progress with this PR? thx

**Comment by lucastheisen** [comment]
Yeah, this one just bit me too: http://stackoverflow.com/q/43433380/516433.  No idea it was using `https_proxy`, and `http_proxy` but ignoring `no_proxy`...  Was frustrating to figure out, and would be really useful to have it be consistent.

**Comment by Alanscut** [comment]
Fixed by #691 and #1693

**Comment by cawoodm** [comment]
Was this resolved? We're seeing axios 0.19.0 ignore `no_proxy=localhost;*.my.internal.domain;127.0.0.*` and try to hit the proxy for `localhost`.

**Comment by cawoodm** [comment]
Oh, it seems it expects commas `no_proxy=localhost,*.my.internal.domain,127.0.0.*`
