### ISSUE TITLE
getting TypeError: utils.isPlainObject is not a function 

### ISSUE THREAD

**Issue by ranran2121** [axios/axios#4347]
#### Describe the issue
I am making a post request with a token as payload in the body. 

#### Example Code
The followings are the piece of code and the error I get

```js
try {
      const { data } = await axios.post(
        "https://57d0-151-1/login",
        {
          token: response.tokenId,
        }
      );
      console.log(data);
    } catch (error) {
     console.log(error
  } 

TypeError: utils.isPlainObject is not a function
    at getMergedValue (mergeConfig.js:19)
    at valueFromConfig2 (mergeConfig.js:41)
    at computeConfigValue (mergeConfig.js:94)
    at Object.forEach (utils.js:232)
    at mergeConfig (mergeConfig.js:92)
    at Axios.<computed> [as post] (Axios.js:140)
    at Function.wrap [as post] (bind.js:9)
    at responseSuccGoogle (Login.js:33)
    at t (google-login.js:1)
    at google-login.js:1
    at e.ws (cb=gapi.loaded_0:236)
    at fk (cb=gapi.loaded_0:239)
    at ak (cb=gapi.loaded_0:239)
    at _.Lj.kv (cb=gapi.loaded_0:238)
    at Ej (cb=gapi.loaded_0:231)

```

#### Expected behavior, if applicable
I am expecting to send the request with the payload and get back two tokens from the service I am submitting the request to, like when I am using the xmlHttp method
```
var xhr = new XMLHttpRequest();
    xhr.open("POST", "https://57d0-151-1/login");
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.onload = function () {
      console.log(xhr.responseText);
    };
    xhr.send("token=" + response.tokenId);
    console.log(xhr.responseText);
```

#### Environment
 - Axios Version [e.g. 0.24.0] 
 - Browser [e.g. Chrome]
 - Additional Library Versions [e.g. React 16.13.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by srokatonie** [comment]
I had the same problem and solution (not ideal) is to downgrade to 0.21.1 as described here:
https://www.reddit.com/r/sveltejs/comments/qiityh/how_to_use_axios_in_svelte/

**Comment by tanwar1998** [comment]
Hii @ranran2121 ,

can you please provide the complete code.
I think this error, is got from incorrect axios configuration set.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
