### ISSUE TITLE
Add an adapter for HarmonyOS

### ISSUE THREAD

**Issue by Alanscut** [axios/axios#4349]
#### Is your feature request related to a problem? Please describe.

No. Hope to add an adapter that supports HarmonyOS in axios

#### Describe the solution you'd like

I have created a PR #4348, which adding an new adapter naming `ohos`

#### Describe alternatives you've considered

Although this feature can be implemented through a custom adapter, considering that axios will be frequently used when developing Apps in HarmonyOS, it will be more convenient if it can be integrated into axios.

**Comment by jasonsaayman** [comment]
closing due to being very stale, if this is still relevant please open a new issue
