### ISSUE TITLE
Need help implementing file downloads using axios

### ISSUE THREAD

**Issue by higoka** [axios/axios#4355]
#### Describe the issue
I have an array with about 25'000 urls of files i need to download. I want to download all of them into a directory. The file name and extension should be the same but i'm not sure how to implement this file download with axios? 
Probably using `axios.all()` but then i also need to limit the amount of concurrent requests to the server otherwise i get rate-limited, maybe with http agent `maxSockets` property?

Can anybody help me out? Maybe give a small example code, that would be helpful because i'm very new to axios.

Thanks in advance

#### Example Code
Code snippet to illustrate your question

```js
const axios = require('axios')

async function main () {
  const urls = [
    'https://www.example.com/foo.png',
    'https://www.example.com/bar.gif',
    'https://www.example.com/baz.jpg',
    ...
  ]

  // how do i save the files and limit the amount of requests to the server?
  const files = await axios.all(urls)
  ...
}
main()
```

#### Expected behavior, if applicable
A way to download multiple files at once and save them on my machine.

#### Environment
 - Axios Version: 0.24.0
 - Adapter: HTTP (NodeJS)
 - Browser: Chrome
 - Browser Version: 96.0.4664.110
 - Node.js Version: v17.3.0
 - OS: macOS 12.0.1
 - Additional Library Versions: None

#### Additional context/Screenshots
none

**Comment by axelcandia** [comment]
Hi I think the best think you can do is grouping your request. I do not know how many request can you make per secont to the urls but maybe try this

Replace waittingSeconds for how many seconds you can wait between request.
```
const {setTimeout} = require('timers/promises');
const axios = require('axios')

async function main () {
  const waittingSeconds = 30000 ;
  const maxUrlPersecond = 2;

  const urls = [
    'https://webhook.site/71cdbd62-6e1a-4e0e-ab9b-2f1a0d17adc8',
    'https://webhook.site/71cdbd62-6e1a-4e0e-ab9b-2f1a0d17adc8',
    'https://webhook.site/71cdbd62-6e1a-4e0e-ab9b-2f1a0d17adc8'
  ];

  for(let start = 0; start <= urls.length; start+= maxUrlPersecond){
    const urltoRequest = urls.slice(start, start+maxUrlPersecond);
    const promisesRequest = urltoRequest.map((endpoint) => axios.get(endpoint));
    await Promise.all(promisesRequest);
    await setTimeout(waittingSeconds);
  }
}

main()



```
I changed axios.all for promise.all as it is recommended in the documentation
