### ISSUE TITLE
there are bug in svelte 3.0 that axios from 0.22.0 version undefined bug

### ISSUE THREAD

**Issue by ragoo80** [axios/axios#4362]
#### Describe the bug
axios 0.22.0 under version works good!
but from 0.22.0 upper version Cannot convert undefined or null to object bug in svelte 3.0.

#### To Reproduce
utils.forEach(Object.keys(config1).concat(Object.keys(config2)), function computeConfigValue(prop) {
var merge = mergeMap[prop] || mergeDeepProperties;
var configValue = merge(prop);
(utils.isUndefined(configValue) && merge !== mergeDirectKeys) || (config[prop] = configValue);
});

TypeError: Cannot convert undefined or null to object at Function.keys ()

#### Expected behavior
 from 0.22.0 version works good

#### Environment
 - Axios Version [from 0.22.0 ~ 0.24]
 - Adapter [ XHR/HTTP]
 - Browser [ Chrome, Safari]
 - Browser Version [chrome - 96.0.4664.110(public build) (arm64)]
 - OS: [Mac OS 12.0.1(Monterey)]
 - Additional Library Versions [svelte 3.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

```js
<script>
	import axios from 'axios'
	import { onMount } from 'svelte'

	let page = 1;
	let limit = 10;
	let postData = [];
	const endpoint = `https://jsonplaceholder.typicode.com/posts?_page=${page}&_limit=${limit}`;

	onMount( async () => {
		try {
			const response = await axios.get(endpoint);
		    console.log(response.data);
		    postData = response.data;
		} catch (error) {
			console.log(error)
		}
	});
</script>

{#await postData}
	<p>...Loading</p>
  {:then postData } 
    <ul>
      	{#each postData as item, index}
        <li>
          <p>[{item.id}] {item.title}</p>
        </li>
		{:else}
		<li>there are no result.</li>
      	{/each}
    </ul>    
  {:catch error}
    <p>occur error.</p>
{/await}

**Comment by saleem-n** [comment]
Yeah. It seems that there was a circular dependency between defaults.js and xhr.js as default.js creates adapter with xhr and xhr.js use default for transitional config.

Probably this issue relates to the fix for transitional config [4052](https://github.com/axios/axios/pull/4052)

**Comment by saleem92** [comment]
Yeah. It seems that there was a circular dependency between defaults.js and xhr.js as default.js creates adapter with xhr and xhr.js use default for transitional config.

Probably this issue relates to the fix for transitional config [4052](https://github.com/axios/axios/pull/4052)

**Comment by huweihong** [comment]
This issue is still existing in my case: svelte 3 + axios . With very simple code (simple `get` with default configuration) , the svelte project does not work with it : axios v0.25.

However, when I roll back to v0.21.1, everything is fine and no erros.

**Comment by causevic** [comment]
Did anyone fix this for a newer version of axios? 
It works with svelte 3 + axios 0.21.1, but still fails with axios 0.26

**Comment by Frankodev** [comment]
Still does not work axios in svelte. 

This worked me;
<script lang="ts">
  // import axios from 'axios';
  import { onMount } from 'svelte';

  let drinks: Array<any> = [];
  const endpoint = 'https://www.thecocktaildb.com/api/json/v1/1/search.php?s=margarita';

  const getDrinks = () => {
    onMount(async() => {
    try {
      const res = await fetch(endpoint);
      drinks = await res.json();
      console.log(drinks);
    } catch (error) {
      console.log(error);
    }
  });
  };

  let promise = getDrinks();
</script>

**Comment by jasonsaayman** [comment]
I have done the release

**Comment by Frankodev** [comment]
Thank you, greetings from Mexico 🧑🏻‍💻
