### ISSUE TITLE
timeout doesn't fire in Node for partial response

### ISSUE THREAD

**Issue by WestonThayer** [axios/axios#4364]
#### Describe the bug
The `timeout` option is documented to cause an error if the request (from start to finish) doesn't complete within the specified ms. This isn't working in Node if the server sends the first response chunk within the timeout, but then hangs.

#### To Reproduce

```js
const axios = require("axios");
const http = require("http");

const server = http.createServer((req, res) => {
  res.write("partial response");
  setTimeout(() => res.end(), 2000);
});
server.listen(3000);

axios
  .get("http://localhost:3000", { timeout: 1000 })
  .then(() => console.log("got response"))
  .catch((error) => console.log(error));
```

#### Expected behavior
`axios.get` should reject with a timeout error.

#### Environment
 - Axios Version 0.24.0
 - Node.js Version v14.17.6

#### Additional context/Screenshots
Under the hood, axios calls `follow-redirect`'s `.setTimeout()` method, which has a bug https://github.com/follow-redirects/follow-redirects/issues/181.

However, if that bug is fixed to match Node's native `http.ClientRequest.setTimeout` behavior, axios will have a different bug:

```js
const axios = require("axios");
const http = require("http");

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const server = http.createServer(async (req, res) => {
  for (let i = 0; i < 5; i++) {
    await delay(500);
    res.write("some data...");
  }
  res.end();
});
server.listen(3000);

axios
  .get("http://localhost:3000", { timeout: 1000 })
  .then(() => console.log("got response"))
  .catch((error) => console.log(error));
```

Even though the request takes 2500ms from start to finish (`500 * 5`), axios won't detect a timeout, because `follow-redirects` will have defined timeout to match Node's definition — the time a socket is idle between packets, not total request time.

The fix would be to stop relying on `follow-redirects` `setTimeout` feature and set our own timer.

**Comment by WestonThayer** [comment]
Essentially the same issue reported in https://github.com/axios/axios/issues/2143.

**Comment by wzijden** [comment]
I'm seeing severe performance issues after upgrading from axios 0.21.4 to 0.25.0.

It seems those issue are related to this issue. We have a lot of logic relying on being able to cancel request. I'm seeing failed cancels and some requests seem to ignore the timeout setting, running much longer.

We don't use a Node server.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
