### ISSUE TITLE
axios.create returning warp function instead of axios Instance

### ISSUE THREAD

**Issue by sleepingsaint** [axios/axios#4365]
#### Describe the issue
I am trying to create a instance of axios with custom Authorization token. When I try to create the instance it's giving a wrap function instead of axios instance

#### Example Code
Code snippet to illustrate your question

```js
// .... extra code

const apiInstance: AxiosInstance = axios.create({
        headers: {
             Authorization: `${token.token_type} ${token.access_token}`,
        },
});

console.log(apiInstance())

// .... extra code
```

console output
```js
ƒ wrap() {
        var args = new Array(arguments.length);
        for (var i = 0; i < args.length; i++) {
          args[i] = arguments[i];
        }
        return fn.apply(thisArg, args);
}
```

#### Environment
 - Axios Version [0.24.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Brave]
 - Browser Version [e.g. 22]
 - Node.js Version [14.15.1]
 - OS: [Linux Ubuntu 20.04] 
 - Additional Library Versions [React 17.02]

### Use case

I am using a custom hook which after the user logins, it sets a axios Instance with access token obtained after authorization. 

Any help would be appreciated. Thanks in advance :)

**Comment by magom001** [comment]
What a way to handle issues... Why the hell is it returning a function instead of an AxiosInstance??? Please reopen this.

**Comment by nappalm** [comment]
@magom001 could you solve it?

**Comment by DigitalBrainJS** [comment]
@magom001 Because the create method is meant to return an Axios factory, but not AxiosInstance as a class instance can't be callable in JS.

**Comment by magom001** [comment]
> @magom001 Because the create method is meant to return an Axios factory, but not AxiosInstance as a class instance can't be callable in JS (in the normal way).

I should have mentioned that I work on a typescript project and types for the `create` method say that it should return an instance of `AxiosInstance` class. Hence my confusion.

**Comment by magom001** [comment]
> @magom001 could you solve it?

I have not faced any issues with that other than very confusing TS typings.
