### ISSUE TITLE
The proxy is not working.

### ISSUE THREAD

**Issue by wll8** [axios/axios#4369]
#### Describe the bug
The proxy is not working.

#### To Reproduce
- Add proxy configuration to environment variables:
  ``` sh
  http_proxy=http://127.0.0.1:1080
  https_proxy=http://127.0.0.1:1080
  ```
- Verify that the configuration can be used normally:
  ``` sh
  C:\>http --body https://www.httpbin.org/get
  {
      "args": {},
      "headers": {
          "Accept": "*/*",
          "Accept-Encoding": "gzip, deflate",
          "Host": "www.httpbin.org",
          "User-Agent": "HTTPie/2.4.0",
          "X-Amzn-Trace-Id": "Root=1-61d3f98e-09f187274f147f9d37c5fd15"
      },
      "origin": "*.*.*.*",
      "url": "https://www.httpbin.org/get"
  }
  # *.*.*.* Is already the ip of the proxy server
  ```
- npm i axios@0.24.0
- Create a t.js file with the following content:
  ```js
  const axios = require(`axios`)
  ;!(async () => {
    const httpData = await axios.get(`https://httpbin.org/get`)
    console.log(`httpData`, httpData.data) // The response is very slow, and eventually if it is empty''
    // Check httpData.request.agent.sockets there is an object of 127.0.0.1:1080:
  })();
  ```
- Run t.js: `node t.js`
  ``` sh
  node -e "console.log(new Date().toISOString())" && node t.js && node -e "console.log(new Date().toISOString())"
  ```
- Output result: It can be found that the request has passed a long time and the response result is empty.
  ``` txt
  D:\git2\mockm>node -e "console.log(new Date().toISOString())" && node t.js && node -e "console.log(new Date().toISOString())"

  2022-01-04T07:24:12.324Z
  httpData 
  2022-01-04T07:25:18.061Z
  ```
  ![](https://cdn.jsdelivr.net/gh/filess/img3@main/2022/01/04/1641281210006-126067ae-0dba-4089-a3d3-a9577e5146fc.png)

#### Expected behavior
You can get the response content of the interface.

``` sh
D:\git2\mockm>node -e "console.log(new Date().toISOString())" && node t.js && node -e "console.log(new Date().toISOString())"
2022-01-04T07:35:18.963Z
httpData {
  args: {},
  headers: {
    Accept: 'application/json, text/plain, */*',
    Host: 'httpbin.org',
    'User-Agent': 'axios/0.24.0',
    'X-Amzn-Trace-Id': 'Root=1-61d3f8b8-54eeb7fd308e15ab414f5441'
  },
  origin: '*.*.*.*',
  url: 'https://httpbin.org/get'
}
2022-01-04T07:35:20.229Z

D:\git2\mockm>
```

#### Environment
 - Axios Version 0.24.0
 - Adapter HTTP/HTTPS
 - Node.js Version v14.15.5
 - OS: windows10 x64
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
This may be related to this question:
- https://github.com/axios/axios/issues/925

Proxy service establishment:
Server linux: https://github.com/shadowsocks/go-shadowsocks2/releases/tag/v0.1.5
Client windows: https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.0.0

**Comment by wll8** [comment]
This problem is very important because it causes programs that would otherwise work to be unavailable. These programs cannot be set to `proxy: false`

**Comment by arthurfiorette** [comment]
They cannot be set `proxy: false`, but is the proxy config specified (`proxy: { url: ... }`)?

**Comment by wll8** [comment]
Any node.js (axios) program you don't write yourself is a black box to you, don't try to know or modify it.

In the best case, if axios supports proxies, then axios should work properly when proxies are available.

**Comment by arthurfiorette** [comment]
I don't think this will be implemented. Teorically, this should be something to put on a configuration file. But as it is a nodejs project, you can just see and edit the source code.

@jasonsaayman is it possible to detect proxies automagically? Even if it is, i don't think this should be included in axios by default.

**Comment by wll8** [comment]
The original meaning is: There is a program written using axios because the system has set up a proxy, so it cannot work. It must be set axios proxy=false.

**Comment by wll8** [comment]
My understanding is that when the system proxy is set, if both httpie and git can use this proxy normally, axios should also be able to, and even if it can't, it shouldn't cause the request to fail.

**Comment by arthurfiorette** [comment]
Oh, so the proxy is configured on the system?
In the code, the proxy config is defined, undefined or false?

You had to set it false to make it work?

**Comment by wll8** [comment]
- The `system` is set up with a proxy
- No proxy settings were made in the original code, this may be `undefined`
- axios must be set to `proxy:false` to work

Thanks, I am currently using: [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent)

**Comment by arthurfiorette** [comment]
Oh maybe the original source already has another proxy configuration, and that's why you need to override the option with false.

Anyways, if `https-proxy-agent` is working, can you post here an example for future people with similar problems?

If not, it is hard to diagnose without code. So, can you setup an small code example that i can test myself?

**Comment by wll8** [comment]
There is a code example `t.js` at the beginning of [this post](https://github.com/axios/axios/issues/4369#issue-1093095680), you can try to see if it can be reproduced.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
