### ISSUE TITLE
how to enable typescript intellisense without commonjs and webpack?

### ISSUE THREAD

**Issue by goldenbull** [axios/axios#4371]
#### Describe the issue
I want to use axios WITHOUT webpack and commonjs, to enable typescript intellisense:

1. `npm install --save axios`
2. add a special comment line `/// <reference types="axios" />` in ts file
3. use CDN in html

#### Example Code

index.html:

```
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
```

main.ts:

```ts
/// <reference types="axios" />

...
axios.get("/api/infos").then(function (resp: any) {
        console.log(resp);
    }).catch(function (error: any) {
        console.log(error);
    });

```

#### Expected behavior, if applicable
for other libs (I tried babylonjs in the same way), intellisense works fine, but IDE can not find axios definitions.

#### Environment
 - Axios Version [0.24.0]
 - Browser [Chrome]
 - Browser Version [96.0.4664.110]
 - Node.js Version [16.13.1]
 - OS: [Windows10]
 - Additional Library Versions [Typescript 4.5.4, PyCharm 2021.3.1 professional]

#### Additional context/Screenshots
I know webpack works fine for typescript intellisense, but I just want to:

1. save my VPS bandwidth, so use CDN whenever possible
2. this is a demo/training webapp so I need to build everything from scratch, keep things just as simple as possible

**Comment by arthurfiorette** [comment]
So you are bundling your code with webpack with typescript and wants to use a cdn for axios?

Seems like that `externals` is a better approach.

https://webpack.js.org/configuration/externals/

With that, you can install axios with npm in your project, use it normally and when webpack transpiles it, it will use the cdn.

```html
<!-- index.html -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
```

```js
// webpack.config.js
module.exports = {
  // ...
  externals: {
    axios: 'axios'
  }
}
```

```ts
// some-file.ts
import axios from 'axios';

const request = axios.get('url');
```

**Comment by goldenbull** [comment]
thanks @arthurfiorette , that's what I need 😄
