### ISSUE TITLE
403 error at a specific URL

### ISSUE THREAD

**Issue by JaeseokWoo** [axios/axios#4372]
#### Describe the bug
I used axios for HTML parsing in my project.
Axios receives a 403 response from a specific URL.
For example, https://www.coupang.com/

I found a solution by comparing [node-fetch](https://www.npmjs.com/package/node-fetch) and axios.
The solution is to add Accept-Encoding to the header.

#### To Reproduce

```js
const axios = require("axios");

const url= "https://www.coupang.com/";

axios.get(url).then((res) => {
  console.log('no Accept-Encoding status:', res.status);
  })
  .catch((error) => {
    console.error('no Accept-Encoding status:', error.response.status);
  });

const config = {
  headers: {
    'Accept-Encoding': 'gzip, deflate, br'
  }
};

axios.get(url, config).then((res) => {
  console.log('Accept-Encoding status:', res.status);
})
.catch((error) => {
  console.error('Accept-Encoding status:', error.response.status);
});
```

#### Expected behavior
If you make a request without Accept-Encoding, you will receive a 403 response.
However, if you request by adding Accept-Encoding, you will receive 200 responses.

#### Environment
 - Axios Version ^0.24.0
 - Adapter HTTP/HTTPS
 - Node.js Version v14.17.3
 - OS: windows10 x64

#### Additional context/Screenshots
![axios result](https://user-images.githubusercontent.com/67548567/148669205-0f15dd8a-3721-46f2-8174-c3bb05818a08.JPG)

**Comment by momguide** [comment]
Thanks,
save my day!
