### ISSUE TITLE
Why interceptors don't work for axios class but instance?

### ISSUE THREAD

**Issue by Yokainu** [axios/axios#4375]
#### Describe the issue
According to the doc, interceptors can be set to axios class or instance.
Actually It won't work for class but instance.

#### Example Code

```js
// WON'T work
axios.interceptors.request.use(config => {
  return config
})

axios.interceptors.response.use(response => {
  return response.data
}, error => {
  return Promise.reject(error)
})

// works
const instance = axios.create({...})

instance.interceptors.request.use(...)
instance.interceptors.response.use(..., ...)
```

#### Expected behavior, if applicable
Works properly.

#### Environment
- Axios Version [0.24.0]
- Adapter [XHR/HTTP]
- Browser [Chrome]
- Browser Version [96.0.4664.55]
- Node.js Version [14.16.1]
- OS: [OSX 10.15.7]
- Additional Library Versions [Vue 3.2.25, Vite 2.7.2]

**Comment by arthurfiorette** [comment]
Are you sure that this is not working? I setup a simple example from my browser and it is working. Have you tried to put a `console.log('here')` at the top of the interceptor to test it?

In your example, you returned `response.data`, but the correct usage is to return the entire `response`. Maybe this is the problem.

```js
axios.interceptors.request.use((config) => {
  // stuff
  return config;
})

axios.interceptors.response.use((response) => {
  // stuff
  return response; // not response.data
})
```

**Comment by Yokainu** [comment]
@arthurfiorette Thanks for your  reply.

> Have you tried to put a console.log('here') at the top of the interceptor to test it? 

I tried before and found it not logging.
This is a [sample online](https://jsfiddle.net/a1Lhkpbt/1/).You can see logs in the console.

**Comment by tanwar1998** [comment]
@Yokainu 

it is working. You just have to add a line at the bottom .


`
instance.get('https://fake.com')
axios.get('https://fake.com')

`
Please try it, and let me know, if you are getting proper output or not.

**Comment by Yokainu** [comment]
@tanwar1998 
Thanks for your reply.It works with `axios.get...`.
So do you mean that interceptors set for axios won't be inherited by instance?  

I was expecting these to be as default interceptors for axios and to work in instances created by axios.create().
And it seems I misunderstood this.

Thanks again for your solution.

**Comment by tanwar1998** [comment]
@Yokainu 
You are most welcome.

And Yeah, it seems that  interceptors set for axios won't be inherited by instance.
