### ISSUE TITLE
serializeDate paramsSerializer

### ISSUE THREAD

**Issue by CindyConway** [axios/axios#4380]
#### Describe the issue
Adding a custom serializeDate function isn't working

#### Example Code
I need to change the way date objects are serialized for transmission. I implemented a custom serializer based on https://github.com/axios/axios/issues/1548, but it has no effect. I have verified that the config is being modified, but when I look at the request payload, the dates are still using UTC (2022-02-03T04:59:00.000Z).

Note: My logic is more complicated, I am using toLocalString() in the code below to simplify the example.

```js
const a = axios.create()
a.interceptors.request.use((config) => {
  config.paramsSerializer = (params) =>
    qs.stringify(params, {
      serializeDate: (date: Date) => date.toLocaleString(),
    })
  return config
})
```

#### Expected behavior, if applicable
The data transmitted in the payload match the format I am providing.

#### Environment
 - Axios Version 0.21.1
 - Adapter XHR
 - Browser Chrome
 - Browser Version latest
 - Node.js Version 15.14.0
 - OS: iOS 12.1.0
 - Additional Library Versions Vue 2.6.12

#### Additional context/Screenshots
None

**Comment by philBrown** [comment]
[Answered](https://stackoverflow.com/a/70690032/283366) on your StackOverflow question

**Comment by CindyConway** [comment]
Great answer. Very detailed. Works like a charm. Thank you.

**Comment by arthurfiorette** [comment]
@CindyConway can you close this issue?

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
