### ISSUE TITLE
Update "follow-redirects" to the latest version to mitigate security issue GHSA-74fj-2j2h-c42q

### ISSUE THREAD

**Issue by RopoMen** [axios/axios#4382]
#### Describe the bug

Required information [GHSA-74fj-2j2h-c42q](https://github.com/advisories/GHSA-74fj-2j2h-c42q)

#### To Reproduce
-

#### Expected behavior
NPM Audit shows no vulnerabilities.

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mrnonz** [comment]
See this PR here #4379

**Comment by jasonsaayman** [comment]
Done :)

**Comment by wknapik** [comment]
@jasonsaayman can you please release a new version with that change?
