### ISSUE TITLE
Please release a new axios version including https://github.com/axios/axios/pull/4379

### ISSUE THREAD

**Issue by wknapik** [axios/axios#4383]
#### Is your feature request related to a problem? Please describe.
Please release a new axios version including https://github.com/axios/axios/pull/4379

#### Describe the solution you'd like
Please release a new axios version including https://github.com/axios/axios/pull/4379

#### Describe alternatives you've considered
Please release a new axios version including https://github.com/axios/axios/pull/4379

#### Additional context
Please release a new axios version including https://github.com/axios/axios/pull/4379

**Comment by arthurfiorette** [comment]
https://github.com/axios/axios/issues/4395#issuecomment-1014476004
