### ISSUE TITLE
Migration to webpack5

### ISSUE THREAD

**Issue by AyoyimikaAjibade** [axios/axios#4389]
#### Is your feature request related to a problem? Please describe.
Please update axios to migrate to webpack5 as maintaining it in the Debian OS environment caused a bug as we try to build the package with webpack 5.65.0, as you still support of webpack4.44.2.
here is a link to the bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001392

The failing build output looks like this while building with webpack 5.65.0

```
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/ayoyimika/debian-js-packaging/axios/node-axios'
grunt build
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "webpack" task
10% building 0/1 entries 0/0 dependencies 0/0 modules(node:233) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
92% sealing asset processing UglifyJSPlugin(node:233) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:233) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_LENGTH] DeprecationWarning: chunk.files was changed from Array to Set (using Array property 'length' is deprecated)
(node:233) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_INDEXER] DeprecationWarning: chunk.files was changed from Array to Set (indexing Array is deprecated)
99% cache begin idleasset axios.js 99 bytes [emitted] (name: main)

ERROR in main
Module not found: Error: Recursion in resolving
Stack:
  undefined: (/home/ayoyimika/debian-js-packaging/axios/node-axios) ./index.js

webpack 5.65.0 compiled with 1 error in 672 ms
Warning:  Use --force to continue.

Aborted due to warnings.
make[1]: *** [debian/rules:11: override_dh_auto_build] Error 3
make[1]: Leaving directory '/home/ayoyimika/debian-js-packaging/axios/node-axios'
make: *** [debian/rules:8: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

#### Describe the solution you'd like
A simple solution i proffer is migrating to webpack5 to have access to its updated features, benefits and options https://webpack.js.org/migrate/5/

#### Describe alternatives you've considered
A simple alternative solution i proffer is too also migrate to webpack5 to have access to its updated features, benefits and options https://webpack.js.org/migrate/5/

#### Additional context

- Axios Version [0.24.0]
- Node.js Version [ 12.22.7]
- OS: [Debian 11]
- Additional Library Versions [webpack5.65.0]

**Comment by arthurfiorette** [comment]
The https://github.com/axios/axios/pull/4351 upgrades it.

**Comment by AyoyimikaAjibade** [comment]
okay great thanks😀 i guess will just wait till its merged
