### ISSUE TITLE
App Store Connect API   Error: Request failed with status code 401

### ISSUE THREAD

**Issue by DreamPWJ** [axios/axios#4392]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
axios.get(
    'https://api.appstoreconnect.apple.com/v1/apps', {
        headers: {
            "Content-Type": "application/json",
            'Authorization': 'Bearer ' + bearerToken,
        }
    }
).then(res => {
    console.log(res.data);
}).catch(error => {
    console.error("错误信息: " + error)
})

```

#### Environment
 - Axios Version [e.g. 0.24.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by rayhu** [comment]
please double check your token

**Comment by ganlvtech** [comment]
Apple returns 401 because "token used before issued". When your iat(Issued At) > server now, you got 401.

**Apple use JWT in a wrong way**. JWT should not signed by client itself. JWT should signed by its server with its server's time as iat.

https://developer.apple.com/documentation/appstoreserverapi/generating_json_web_tokens_for_api_requests
