### ISSUE TITLE
How to send array of object in post request using axios library

### ISSUE THREAD

**Issue by rawalprashant** [axios/axios#4394]
#### Describe the issue

This might be duplicated question, but I have tried all possible research on google and blogs, StackOverflow to get a solution to fix it, but no luck so if you already know the answer please help me.

I am trying to send an array of objects to Axios post request, but the payload empty array even if I have the data in array as I checked with console.log

#### Example Code
Code snippet to illustrate your question

```js
axios.post("/api/videos", {
	ytVideosList,
	data: {
		customFunction: "AddVideoList"
	}
})
```

#### Expected behavior, if applicable
where ytVideoList is [{json-obj1},{json-obj2}, .....] etc which is empty [] at payload side, so i am not able to insert data in my database table. I hope everything is clear if you know the answer please respond as soon as possible.

#### Environment
 - Axios Version 0.24.0
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 22+
 - Node.js Version 13+
 - React 16.7+

#### Additional context/Screenshots
It's general simple data sending issue so no need to add screenshot i think so

**Comment by arthurfiorette** [comment]
There's a lot of missing information here.

If you add a `console.log(ytVideosList);` does it print the entire object array?

if you `await` the response, what is in the config property?

```js
const response = await axios.post(...);
console.log(response.config);
```

**Comment by rawalprashant** [comment]
@arthurfiorette 

Hi, so I did some deep analysis based on your response, you are right. I am not able to put the entire code here, but let me simplify it

`const ytVideosList = []
 
const GetVideos = await axios.post(...). then(function(response) {
    
   const ytIDs = response.data
 
    ytIDs.map(async function(item) {
        const video = await youtube.getVideo(item)

        ytVideosList.push(video) //adding json object inside array
    }
})
console.log(ytVideosList) //showing data inside array
console.log(ytVideosList.length) // this shows as zero strange

Here Another API call depend on ytVideosList`

So I think my another API call before the data prepare in ytVideosList?

I hope now it's more clear, and you have the solution for me :)

**Comment by anyanyan07** [comment]
The problem is that map function with async and await which make "ytVideosList.push(video)" execute after "console.log". May be you should write like this:
` const ytVideosList = []
      const GetVideos = await axios.post(...);
      const ytIDs =  GetVideos.data;
      const requestList = ytIDs.map(item => youtube.getVideo(item));
      const arr = await Promise.all(requestList);// arr is the list you need
      ytVideosList = arr;// you can handle the data with your business
      // your another call API`
