### ISSUE TITLE
Release security vulnerability fix for follow-redirects package

### ISSUE THREAD

**Issue by CarlMungazi** [axios/axios#4395]
#### Is your feature request related to a problem? Please describe.
A [PR](https://github.com/axios/axios/pull/4379) has been merged which fixes a vulnerability with the `follow-redirects` dependency. However, this fix has not been released.

#### Describe the solution you'd like
The fix to be released so devs do not have to point to the specific commit that fixed this issue when installing axios

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by bkayranci** [comment]
axios has floating version in the v0.24.0 (latest) version.
[package.json](https://github.com/axios/axios/blob/v0.24.0/package.json#L78)

so, you can use folllowing command

`yarn upgrade axios`

or you can update manually your lock file(yarn.lock).

**Comment by CarlMungazi** [comment]
@bkayranci thanks for the response. I know there are ways around it currently (like resolutions etc) but I just opened this issue so whenever the maintainers were ready it could be released with the `follow-redirections` package pointing at 1.14.7

**Comment by jasonsaayman** [comment]
Released  🎉
