### ISSUE TITLE
Trouble testing ES6 default export with Jest

### ISSUE THREAD

**Issue by ridgekuhn** [axios/axios#4397]
Hello friends,

I'm calling the default export in my React app, eg `axios({ url: "/foo/bar", method: "get" })`, but have hit a wall when testing with Jest and trying to mock or spy on `axios`. I'm using the latest versions of Axios (0.24.0), Jest (27.4.7), and React (17.0.2 via create-react-app), and running Node 16 LTS. 

Solutions found in issues like #1785 (and the related StackExchange link in the comments) all give me the same result, so I guess something has changed? This clearly isn't a bug in Axios, but as it's not immediately obvious how to proceed (at least to me), I'd like to request that whatever the answer is be added to the documentation. (After you tell me, of course!) 

Thanks for your time!

test:
```javascript
// These all give the same error:
jest.spyOn(axios, "default");

jest.mock("axios");

jest.doMock('axios', () => {
	return jest.fn()
})

jest.mock('../moduleName', () => {
	return {
		__esModule: true,
		default: jest.fn(),
};
...
expect(axios).toHaveBeenCalledWith(
	expect.objectContaining({
		url: "/api/users/signin",
		method: "post",
		data: {
			email: expect.stringMatching(/.*/),
			password: expect.stringMatching(/.*/)
		}
	})
);
```

error:
```
 expect(received).toHaveBeenCalledWith(...expected)

    Matcher error: received value must be a mock or spy function

    Received has type:  function
    Received has value: [Function wrap]

      60 |      userEvent.click(signInBtn);
      61 |
    > 62 |      expect(axios).toHaveBeenCalledWith(
         |                    ^
      63 |              expect.objectContaining({
      64 |                      url: "/api/users/signin",
      65 |                      method: "post",

```

#### Section/Content To Improve
Quote or link to section

#### Suggested Improvement
Identify what is confusing or incorrect and what could make it better

#### Relevant File(s)
[e.g. README.md]

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks

**Comment by RanylFoumbi** [comment]
Hi here 
i'm facing the same Trouble testing ES6 default export with Jest like [ridgekuhn](https://github.com/ridgekuhn) but with nodejs
Please Can you help ?

// test.js file

`import axios from 'axios';
import { expect, jest } from '@jest/globals'
import getPhotosByAlbumId from '../index.js'

jest.mock('axios')

describe('test getPhotosByAlbumId', () => {
  it('fetches photos by album id', async () => {
    const ID = 3;
    const expectedConfig = {
      baseURL: 'https://jsonplaceholder.typicode.com/albums',
      method: 'get',
      url: `/${ID}/photos?_limit=3`
    };
    const expectedData = [
      { albumId: ID, id: 1, title: 'accusamus beatae ad facilis cum similique qui sunt' },
      { albumId: ID, id: 2, title: 'reprehenderit est deserunt velit ipsam' },
      { albumId: ID, id: 3, title: 'officia porro iure quia iusto qui ipsa ut modi' }
    ];

    console.info({axios});

    axios.mockResolvedValueOnce({ data: expectedData });

    const photos = await getPhotosByAlbumId(ID);

    expect(axios).toHaveReturned();
    expect(axios).toHaveBeenCalledTimes(1);
    expect(axios).toHaveBeenCalledWith(expectedConfig);
    expect(photos).toEqual(expectedData);
  });
});`

// inde.js file

`
import axios from "axios";

const getPhotosByAlbumId = async (id) => {
  const result = await axios({
    baseURL: 'https://jsonplaceholder.typicode.com/albums',
    method: 'get',
    url: `/${id}/photos?_limit=3`
  });
  console.log({ result });
  const { data } = result;
  return data;
};

export default getPhotosByAlbumId;`

// package.json file

`{
  "name": "sample-jest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "jest":{
    "testEnvironment":"node",
    "transform":{},
    "testMatch":[
       "<rootDir>/tests/*.test.js"
    ]
 }, 
  "scripts": {
    "test": "NODE_OPTIONS=--experimental-vm-modules npx jest --coverage"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/jest": "^29.5.1",
    "axios": "^1.3.6",
    "jest": "^29.5.0"
  }
}
`
