### ISSUE TITLE
Cannot upload file within FormData

### ISSUE THREAD

**Issue by Romick2005** [axios/axios#4398]
After upgrading from 0.24.0 to 0.25.0 Form upload breaks:

#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Original working on 0.24.0 code.
```js
    axios({
        method: "post",
        url: [serverUrl],
        data: formData, // FormData object instance with uploading file field
        timeout: 120000
    });
```
This code was working previously, but now backend cannot extract file field.
After specifying content type:
```js
    axios({
        method: "post",
        url: [serverUrl],
        data: formData, // FormData object instance with uploading file field
        timeout: 120000,
        headers: {"Content-Type": "multipart/form-data"},
    });
``` 
I got an error on backend "bad content-type header, no multipart boundary"

#### Expected behavior
Seems like previous version of axios (0.24.0) automatically add correct header and also boundary.

#### Environment
 - Axios Version [0.25.0]
 - Node.js Version [16.0.0]
 - Additional Library Versions [formidable 2.0.1]

Or was there any breaking change that I didn't notice?

**Comment by felix4321** [comment]
I'm facing the same issue and didn't find any solution yet...

**Comment by anthonytoktokdoc** [comment]
same here. working on 0.24.0 but not on 0.25.0

**Comment by jr00n** [comment]
Same problem here!

**Comment by webmasterdevlin** [comment]
Yes, after upgrading from 0.24 to 0.25 or 0.26.
500 Internal Server Error.
{
    "message": "Multipart: Boundary not found"
}
