### ISSUE TITLE
When is cookie captured by axios request? 

### ISSUE THREAD

**Issue by elbaro** [axios/axios#4411]
#### Example Code
```js
axios.post('/logout'); // (A)
document.cookie = 'session_id=; max-age=0'; // (B)
```

Is there a race condition between (A) and (B)?

I wonder if axios captures the current `document.cookie` at the time of calling `post()`, or later asynchronously.

#### Expected behavior, if applicable
A documentation on its behavior

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
