### ISSUE TITLE
Is it possible to only get headers, not the entire content ?

### ISSUE THREAD

**Issue by xeats** [axios/axios#4417]
Hi, I have to follow a link redirect as fast as possible and just get the final url, not the content of the webpage.

#### Describe the issue
Axios allow me to follow the redirect, but wait until all content is downloaded to get the response headers ...
Is there a way to only get the response headers (I use response.request.host & response.request.path) without having to wait for the body to be downloaded ?

#### Example Code
```axios.get(url,{timeout: 1000}) .then(function (response) { // handle success console.log(response.request.host+response.request.path); }) .catch(function (error) { // handle error console.log(error); return false; }) .then(function () { // always executed });```

#### Expected behavior, if applicable
Not applicable

#### Environment
 - Axios Version 0.25.0
 - HTTP
 - Browser Version not useful
 - Node.js Version 16.11.0
 - OS: Windows 10

#### Additional context/Screenshots
I just have to get the redirect address, not the whole content so it will be faster for my script to not wait for the whole content, ony headers.

**Comment by DigitalBrainJS** [comment]
Just use HEAD method instead of GET:
```js
axios.head('https://google.com',{timeout: 1000}) .then(function (response) {
  console.log(response.request.host, response.request.path, response.data);
}) .catch(console.warn);
```
