### ISSUE TITLE
Axios returns a generic "Network Error" even when the request got a response code

### ISSUE THREAD

**Issue by Miodec** [axios/axios#4420]
#### Describe the bug
When making a request to my API, the catch block has a generic "Network Error" message, but when checking in the network inspector the request got a response code 413. This causes my users to incorrectly report that 'the website thinks i dont have a solid internet connection'. I suspect this happens for other codes too because this has been going on for a while.

#### To Reproduce
Make a request with a very large payload to trigger a 413 response

#### Expected behavior
The catch block should have the response code 

#### Environment
 - Axios Version: 0.25.0 and 0.21.2
 - Adapter: xhr (i think? i dont remember changing this, so i guess whatever is default?)
 - Browser: Chrome
 - Browser Version: 97.0.4692.99
 - Node.js Version: 14.18.1
 - OS: OSX 12.1

#### Additional context/Screenshots
```js
axiosInstance
    .post("/results/add", {
      result: completedEvent, //this is very big
    })
    .then((response) => {
      // handle response
    })
    .catch((e) => {
        console.log(e);
        //this console logs Error: Network Error
        // at createError (monkeytype.js:formatted:35086:25)
        // at XMLHttpRequest.handleError (monkeytype.js:formatted:34457:28)
    });
```
![image](https://user-images.githubusercontent.com/13181393/150684404-d52537f2-976d-4d63-8198-cc5a3b67ab8b.png)
![image](https://user-images.githubusercontent.com/13181393/150684432-fefc82ac-41c2-4556-b36a-3c3ccfee6bdb.png)

My axios instance code:
https://github.com/Miodec/monkeytype/blob/master/src/js/axios-instance.js

**Comment by gigerIT** [comment]
We also see an increased number of Network Errors in our app. It mus be iOS related, the logs shows only: iPhone, Mac, iPad (90% with iOS 14.X) devices for it. 
Downgrading to 0.24.0 now to check if it fixes the error.

**Comment by felipe7229** [comment]
Same issue happens in my application. I'm waiting for more details

**Comment by essedger** [comment]
Same issue happens in my application too...
React Native, iOS 15.0, iPhone 12 simulator, axios 0.24.0 (tried 0.25.0 - the same issue
![Screenshot 2022-01-25 at 22 50 17](https://user-images.githubusercontent.com/12384438/151048950-4df1f3e3-1e70-48cf-97dd-5f3148387f27.png)
)

**Comment by Miodec** [comment]
Tagging the axios team @rubennorte @mzabriskie @emilyemorehouse @jasonsaayman @nickuraltsev 

Any chance you could have a look into this? I feel like this is quite important, since it makes it impossible to do proper error handling, makes it harder to debug and confuses users.

**Comment by essedger** [comment]
@manugch @Miodec  do you have any DNS ad blockers? I disabled my AdGuard and now it works fine. Can you check any any blockers/vpn?

**Comment by gigerIT** [comment]
> @manugch @Miodec do you have any DNS ad blockers? I disabled my AdGuard and now it works fine. Can you check any any blockers/vpn?

No Adblockers. I also see the error happening on visitor devices in our sentry logs, over 112 iOS devices by now who crashed with that unhandled "Network Error".
It affects to  only iOS devices as I said before Mac, iPhone, iPad mostly iOS/Safari 14.1.X

**Comment by Miodec** [comment]
> @manugch @Miodec do you have any DNS ad blockers? I disabled my AdGuard and now it works fine. Can you check any any blockers/vpn?

Tested without adblock - same thing.

**Comment by kumarldh** [comment]
Somewhat similar situation for my ecommerce store as well. 91% "Network Error" on Safari(iOS). Safari follows a strict "Same Origin Policy" and I have noticed that most MarTech integrations throw errors on Safari. However, for me, these 91% errors are in my app and not in with 3rd party tags/pixels.

**Comment by DerekSteinke** [comment]
I am seeing the exact same issue. A generic error saying `Error: Network Error` with no other information on 403s. According to the docs, the error should still include the response code and headers, but it doesn't.

- Axios 0.21.4
- Node.js v16.13.1
- Firefox 96.0.3 & Chrome 98.0.4758.82
- Windows 10 Pro (Build 19041)

![image](https://user-images.githubusercontent.com/7316740/154127085-06a5c2cd-74a0-4ac7-9a8a-abbdea0be9b5.png)

**Comment by pierroberto** [comment]
I had a similar problem. I realized that was a CORS problem. Do you have any OPTIONS call before the actual API call?

**Comment by kumarldh** [comment]
@pierroberto I see this error for API calls which are on same domain, relative paths like `/api/getsomedata`.

**Comment by Tofandel** [comment]
Looking at the code, there seems to be a catch all in the XHR adapters https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L118

It's not there in the HTTP adapter which will give the correct error so you may want to switch to that

**Comment by Miodec** [comment]
> I think it's because the XHR spec doesn't give [any clue about the error](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/error_event), so I don't think it can be fixed.

So, why does the console correctly show errors like `ERR_FAILED 413` in this case, or `CONNECTION_REFUSED` or `SSL_CERT_DATE_INVALID` that I ran into in other cases? All of them give `Network Error`, but somehow show up correctly in the console...

Pretty sure using HTTP is not the best solution as its not supported in every browser (webpack replaces it with xhr)

**Comment by Miodec** [comment]
Alright, I figured things out (im still learning so some details could be wrong)

Basically, there is no way around it. Axios is just a wrapper for `XMLHttpRequest` (just realised that's where the XHR acronym comes from) to make it a bit easier to use and less complicated to write. Axios gives us a `Network Error` because **xhr itself doesn't give us any info about the error**. You can see for yourself by doing a simple request to an endpoint that doesn't exist:
```ts
const oReq = new XMLHttpRequest();
oReq.addEventListener("error", (e) => {
  console.log(e);
});
oReq.open("GET", "http://localhost:5005/");
oReq.send();
```
The console.log will give us (drumroll please):
![image](https://user-images.githubusercontent.com/13181393/158061893-ecaa50e9-7dba-4d92-b99f-43c214ea0fa9.png)
Absolutely nothing :)

However, the console error will show `GET http://localhost:5005/ net::ERR_CONNECTION_REFUSED` (still don't understand why the error is in the console but not in the event listener parameter)

So either way, this is not the fault of Axios. The only fix here that was mentioned by @Tofandel is to switch to the HTTP adapter at the expense of *some* compatibility - I don't know how big this expense is exactly. Axios uses [Node's HTTPS](https://nodejs.org/api/https.html) module in its HTTP adapter and I'm not sure yet what things like webpack will replace it with. If I remember ill update this comment with my further findings.

**Comment by kumarldh** [comment]
I am just here to add information, not reopening this issue. Axios in browsers will use XHR. My application is a consumer internet application and I can not think of anything other than XHR which can work for _most_ browsers.  Also, upgrading to version 0.26 has significanty reduced these errors for me.

**Comment by orengatigno** [comment]
it's CORS problem, once you resolve the CORS issue (for example install CORS Unblock extension plug in Chrome) it will retrieve the response code (for me it was 504)

<img width="772" alt="image" src="https://user-images.githubusercontent.com/6885381/165241029-6b7c49c3-5dd9-4a9b-8a8a-6a1ecd62cc1f.png">

**Comment by Prasham2407** [comment]
any solution?

**Comment by Vikramelyaraja** [comment]
Axios returns a "Network Error"  so, the one of the solution. I was found in my project, when using our  app we need to switch on the mobile data then, try it again it will clear the 'network error'.

**Comment by LiamKarlMitchell** [comment]
So are there any links related issues if it is a browser issue?

Is this only in Safari browsers or also happens in Google Chrome/Firefox etc?
Is there a browser update that fixes it?

Suspect my iOS users are having this problem, I'm using latest Axios version 0.27.2.
I've also seen it bomb out on android phone with google chrome however (not sure if related did not have adb inspector connected).

**Comment by yavuz-bektas** [comment]
Same issue. Any news? issue is coming from the only mobile browsers

**Comment by lincolnzera1** [comment]
In my case, the CORS was blocking the frontend from acessing the backend.
**My Solution:**  Add this in the server-side:
                      
                     Using npm, install 'cors':
                      npm i cors
                      
                      And add this lines to the code:

                      let cors = require("cors");
                      app.use(cors());

**Comment by AnisMobile99** [comment]
Don't have solution now ???

**Comment by kumarldh** [comment]
@lincolnzera1 don't want to patronize you, however could not stop myself from adding a comment either. I would suggest you to look at errors and only allow required headers for cors. If you are already doing this, please ignore my comment completely.

**Comment by zsinba** [comment]
the same issue. 
Don't have solution now ???

**Comment by abdelhaq-laachari** [comment]
Hello to Everyone.
I just want to let you know that after searching for a solution for two days, I was able to solve my error.
Since the proxy was the source of the issue, I must configure a proxy in the package.json file, and I had to follow these instructions in the function that used Axios:
`try { await axios.post("user/login", formData).then((res) => { console.log(res.data); }); } catch (error) { console.log(error.response.data.message); }`
and in package.json file need to add a proxy:
`"proxy": "http://localhost:<SERVER_PORT_NUMBER>"`
for better understand check this documentation [https://www.jamesqquick.com/blog/configure-proxy-in-react/](url)

**Comment by kavicastelo** [comment]
I have the same issue. It not works with any solutions above mentioned😕

**Comment by zsinba** [comment]
> I have the same issue. It not works with any solutions above mentioned😕

keep track.

**Comment by giannosantoniou** [comment]
I had exactly the same issue. Front-end I was using axios and back-end I was using .net core WebAPI. The solution was at the side of the back-end:
    app.UseCors((g)=>g.AllowAnyOrigin());

**Comment by Kshitiz1403** [comment]
I am getting the same issue. Does not work with any solutions above.

**Comment by zsinba** [comment]
> I had exactly the same issue. Front-end I was using axios and back-end I was using .net core WebAPI. The solution was at the side of the back-end: ` app.UseCors((g)=>g.AllowAnyOrigin());`

Is this setting to allow cross-domain? It doesn't seem like this is working. It is more convenient to set cross-domain in Nginx, and it has nothing to do with it.

**Comment by zsinba** [comment]
> I am getting the same issue. Does not work with any solutions above.

[keep an eye on](javascript:;)

**Comment by ngocducdim** [comment]
-I also see this error on some request:
![image](https://user-images.githubusercontent.com/97713182/209745730-ce30fac5-667c-43bb-b8f0-273d689ec8c2.png)
- Althrough it return 200 response code:
![image](https://user-images.githubusercontent.com/97713182/209745927-a336efc5-67a5-42fe-8c8e-c065e88e1869.png)
- The console:
![image](https://user-images.githubusercontent.com/97713182/209745948-5c82f337-907e-4de6-835c-2525d610b0c9.png)
- My code:
![image](https://user-images.githubusercontent.com/97713182/209745965-71529d5b-5e2d-4542-8546-74070b35ac44.png)

**Comment by darkengine** [comment]
Make a request with a very large payload to trigger a 413 response
--------

Since somebody mention about the 'large payload', does anyone have re-produce with it, and which size would be large in this case?

**Comment by kumarldh** [comment]
> ## Make a request with a very large payload to trigger a 413 response
> Since somebody mention about the 'large payload', does anyone have re-produce with it, and which size would be large in this case?

You can probably replicate this. Set up a web server, say Nginx, and esnure it can only receive a 5MB POST request. Send this server a payload more than 5MB and you will receive this error. However, I am not clear what is Axios' role in all this... 😕

**Comment by ajeeshpu** [comment]
https://github.com/axios/axios/issues/4420#issue-1111893293

The original issue posted here has to do with how CORS is handled by the browser. Looking at your network console the API endpoint is allowing your origin to make the request since OPTIONS request is successful (and (taking a guess here) they are also succeeding with small file POSTS and not the bigger than `threshold size` ones)

However the  content too large 413 is probably served by  (

1. a reverse proxy like Nginx  sitting in the middle ( which is where the response is originating from and not your API). Is it possible that you have not allowed the origin as a part of the response originating from Nginx.  If yes chrome is probably disallowing the response from being read by your app. You can resolve this by providing `Access-Control-Allow-Origin` header as a part of the 413 response after which axios will receive the response ( you will need to have access to the reverse proxy or the likes in the middle). 

OR

2.   A middleware (in your API) that intercepts the request and `does not` set the 'Access-Control-Allow-Origin'  headers appropriately. If not present chrome is probably disallowing the response from being read by your app.

**Comment by KhanessKA** [comment]
![image](https://user-images.githubusercontent.com/82938832/235345329-50dfa3a3-ef38-4b6f-8448-334e3a603447.png)
![image](https://user-images.githubusercontent.com/82938832/235345375-78279646-76a9-416e-a0d8-b2f70a2f8687.png)
- Axios 1.3.4
- React Native 18.2
- Chrome
Pls I throws me an error , som1 knows why ocurs that and how i fix it ?

**Comment by Phong-TH** [comment]
@gigerIT do you have any workaround for this? we have the same issue in production but can not reproduce it.

**Comment by harshgupta20** [comment]
Anyone got the solution to resolve it??

**Comment by mahendrameghwal** [comment]
i am also getting this same problem even i use  cors 
const cors = require('cors')
app.use(cors())

**Comment by ArastoSahbaei** [comment]
Try swapping baseurl localhost:port with http://10.0.2.2:8080/

**Comment by damacisaac** [comment]
Here's what worked for us

We wanted our nginx server to handle request timeouts (504), so we configured a `proxy_read_timeout 480s` and added an error handler: 

```
    error_page 503 /503.json;
    location = /503.json {
        add_header 'Access-Control-Allow-Origin' '*' always;
        return 503 '{"error":{"code":503,"message":"Service Unavailable"}}';
    }
```

Note that we have to add the correct CORS headers since it's a cross domain request, and we add the `always` since we want the headers for 50Xs a not just 20X-30Xs 
```
add_header 'Access-Control-Allow-Origin' '*' always;
``

**Comment by rachidscorpion** [comment]
Hi Everyone, I found the problem for me, I already had cors enabled but I was still facing axios network error, after a little bit of research I found out that for a mobile device localhost is `10.0.2.2:{PORT}`. I still kept `127.0.0.1:{PORT}` at my node js backend and my API in react native started working.

**Comment by mahiraltinkaya** [comment]
> ![image](https://user-images.githubusercontent.com/82938832/235345329-50dfa3a3-ef38-4b6f-8448-334e3a603447.png) ![image](https://user-images.githubusercontent.com/82938832/235345375-78279646-76a9-416e-a0d8-b2f70a2f8687.png)
> 
> * Axios 1.3.4
> * React Native 18.2
> * Chrome
>   Pls I throws me an error , som1 knows why ocurs that and how i fix it ?

Hey [yosseferrazik](https://github.com/yosseferrazik) ; 
Firstly you have to use a function for async request in useEffect. But this is not resolve your problem. Also I have the same problem. 

You can try the add below line add AndroidManifest.xml file <application tag. I think you will be solve you problem. But  I faced same error now. Did you resolve ?
android:usesCleartextTraffic="true"

**Comment by vijoin** [comment]
> @manugch @Miodec do you have any DNS ad blockers? I disabled my AdGuard and now it works fine. Can you check any any blockers/vpn?

I had the same problem. I'm using Brave browser. I disabled the shields and it worked.

**Comment by haimon1442** [comment]
![image](https://github.com/axios/axios/assets/59360199/e9e627de-92b2-40b9-919a-504ef7625c85)
i have face the same issue .am using reactjs front and node js back end

**Comment by Fola-rin** [comment]
I faced the same issue even after installing cors. I was able to fix it by making sure the cors code was above my route declaration. Code below.
Before:
`app.use("/api/messages", messagesRoutes);
app.use(cors());`

After:
`app.use(cors());
app.use("/api/messages", messagesRoutes);`

Hope this helps

**Comment by Fola-rin** [comment]
I faced the same issue even after installing cors. I was able to fix it by making sure the cors code was above my route declaration. Code below.
Before:
```
app.use("/api/messages", messagesRoutes); 
app.use(cors());
```

After:
```
app.use(cors()); 
app.use("/api/messages", messagesRoutes);
```

Hope this helps

**Comment by jacomyou1026** [comment]
해결하셨나요?

**Comment by jlyadda** [comment]
Tried out this with a hosted API and works fine… Local host seems to be the problem.

**Comment by SaDo21042000** [comment]
I would like to add one more case I encountered.
![image](https://github.com/user-attachments/assets/062ecf23-8904-4e68-8f6b-78c149eda585)
Like code above, line 18 and line 20 is conflict and will lead to error CORS. 
In this case we have to asign specific **url** for Access-Control-Allow-Origin instead of "*". Because Set("Access-Control-Allow-Credentials", "true") not allow Set("Access-Control-Allow-Origin", "*"). Or maybe you can keep Set("Access-Control-Allow-Origin", "*") then you have to delete  Set("Access-Control-Allow-Credentials", "true") from cors configuration.

**Comment by sandanarajeev** [comment]
> Here's what worked for us
> 
> We wanted our nginx server to handle request timeouts (504), so we configured a `proxy_read_timeout 480s` and added an error handler:
> 
> ```
>     error_page 503 /503.json;
>     location = /503.json {
>         add_header 'Access-Control-Allow-Origin' '*' always;
>         return 503 '{"error":{"code":503,"message":"Service Unavailable"}}';
>     }
> ```
> 
> Note that we have to add the correct CORS headers since it's a cross domain request, and we add the `always` since we want the headers for 50Xs a not just 20X-30Xs .
> 
> ```
> add_header 'Access-Control-Allow-Origin' '*' always;
> ```
> 
> It's not enough to add CORS handling to your application code in this case, since it's nginx that's responsible for setting the correct header here.

This works like a charm, thank you

**Comment by bernardwiesner** [comment]
> ```
> add_header 'Access-Control-Allow-Origin' '*' always;
> ```
> 
> It's not enough to add CORS handling to your application code in this case, since it's nginx that's responsible for setting the correct header here.

Pay close attention to this! The same happened for me for 413. I was getting CORS error plus 413, since I only had CORS configured on php side, not in nginx.

What happens is when nginx returns 403, the request never hits your application code, such as php, and the CORS headers never get set. So you **need** CORS headers in nginx too in order to avoid CORS errors in the console that block axios from getting the actual error code. 

I first was getting a generic `Network Error` when only using CORS in php, after adding CORS in nginx, I got `Request failed with status code 413`, which is much more descriptive.

**Comment by darkerone** [comment]
It worked for me !

I use nextjs for front and .net core for back.
This missing status code was very annoying for displaying relevant message for user.
After long search to solve it on front, your comments about CORS on back were the solution !
@Fola-rin was right : order is important.

In my program.cs, I added this :
```
app.UseCors(options =>
{
    options.AllowAnyOrigin();
    options.AllowAnyHeader();
    options.AllowAnyMethod();
});
```
before this : 
```
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
```
(yes I know that I should not allow any cors but it is for tests, not production)

**Comment by Vimiso** [comment]
In my case when simulating in ios I got a generic `Network Error` when a request had a empty `data` payload. Very strange. Anyway, this fixed it for me:

```js
const api = axios.create({
  baseURL: 'http://foo.test',
})

let options = {
  method: method,
  url: uri,
  headers: {
    Authorization: `Bearer ${auth?.token?.token}`,
  },
}

if (Object.keys(payload).length !== 0) {
  options = { ...options, ...{data: payload} }
}

return api.request(options)
```

**Comment by alejorrojas** [comment]
Hi! I'm having this same issue and I see it's currently closed but there's no official solution yet. Any help?

**Comment by brianangulo** [comment]
> Hi! I'm having this same issue and I see it's currently closed but there's no official solution yet. Any help?

@alejorrojas seems like everyone took this -> https://github.com/axios/axios/issues/4420#issuecomment-2342132622 as solution. We are facing similar issues.

**Comment by kushaltmanjanna** [comment]
Adding CORS headers while returning error in the backend resolve the issue
