### ISSUE TITLE
"Provided config url is not valid" warn then req error just with newly released Axios 0.25.0

### ISSUE THREAD

**Issue by sdrkyj** [axios/axios#4424]
With the newly released 0.25.0, got warn  of "Provided config url is not valid" of my Axios instance in the console, then error occurred. That does not occurred if just rolled back to the version 0.24.0 of Axios. Not got tips from the changelog 0.25.0.

the initialization:
```js
const weatherInstance = axios.create({baseURL: 'http://xxxxxxxxxxx/weather'});
```

the call that error occurred:
```js
weatherInstance.request({
    params: {stationid: locCode},
    signal: weatherAbortController.signal
})
```

#### Expected behavior
There was no such warn or error on the 0.24.0 version of Axios.

#### Environment
 - Axios Version [0.25.0]
 - Browser [Firefox]
 - Browser Version [96.0.2]
 - Node.js Version [v16.3.1]
 - OS: [Win 10]
 - Vue Version [2.6.14]

**Comment by jasonsaayman** [comment]
Closed see #4407
