### ISSUE TITLE
axios releases in /dist folder haven't changed from 0.24.0 to 0.25.0

### ISSUE THREAD

**Issue by lorand-horvath** [axios/axios#4430]
#### Describe the bug
I've just downloaded the latest axios 0.25 zip release from https://github.com/axios/axios/releases/tag/v0.25.0
and the bundled global releases located in the /dist folder haven't changed since the previous version 0.24 (I performed a file comparison of both /dist/axios.js and /dist/axios.min.js), apart from 2 comments at the very top of the files. The actual relevant code is exactly the same as was previously in 0.24.0.

Just checked and I see the same files installed in the /node_modules of my package if I install with `npm install axios`
package.json shows dependency as `"axios": "^0.25.0"` but the files in  `/node_modules/axios/dist/` haven't changed since 0.24. Very strange.

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
npm install axios@0.25
```

#### Expected behavior
Latest version content should be everything done for 0.25, which is not the same as 0.24

#### Environment
 - Axios Version 0.25.0
 - Node.js Version 12.22.9

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by lorand-horvath** [comment]
@jasonsaayman Could you please take a look at this issue? Thanks!

**Comment by lorand-horvath** [comment]
Fixed in 0.26.0

**Comment by jasonsaayman** [comment]
Was a mistake, sorry about that
