### ISSUE TITLE
get request does not download csv file.

### ISSUE THREAD

**Issue by davvit** [axios/axios#4431]
#### Describe the issue
Why is this request not working. It works in postman and using curl.

#### Example Code
```
var axios = require("axios")
axios.get("http://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv",{responseType: 'document'})
.then((res)=>{
//process file here
})
```

#### Expected behavior, if applicable
the file should be downloaded and string content should be in res

#### Environment
 - Axios Version 0.25.0
 - Node.js Version v16.13.0
 - OS: win11

#### Additional context/Screenshots
You can test this code in runKit on npm site

![image](https://user-images.githubusercontent.com/4433698/151434948-7466b529-e2ac-423e-afe8-783c48e38450.png)

**Comment by DigitalBrainJS** [comment]
This type of response is for retrieving data as an HTML/XML document object. See the XMLHttpRequest [documentation](https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest/responseType). Use plain text response type and then parse the raw content with some CSV parser from NPM.

**Comment by davvit** [comment]
@DigitalBrainJS I tried the request with text responseType and it failed with same error.
```var axios = require("axios")
axios.get("http://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv",{responseType: 'text'})
.then((res)=>{
 console.log(res)
})```
https://npm.runkit.com/axios

**Comment by DigitalBrainJS** [comment]
That endpoint returns 403 Forbidden http code, so it is clear from it that you need to emulate headers that the browser should send to pass the robot detection test.
Just rewrite the user-agent header to some browser-specific string-like and it [will work](https://codesandbox.io/s/axios-issue-4431-b05mk?file=/src/index.js):
```js
axios
  .get(
    "https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv",
    {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
      }
    }
  )
  .then((res) => {
    console.log(res);
  });
```

**Comment by davvit** [comment]
nice, that works. thanks for the header info. Have a good weekend.
