### ISSUE TITLE
[Feature Request] Support RFC 7230 and RFC 3986 by Axios configuration

### ISSUE THREAD

**Issue by Emiya0306** [axios/axios#4432]
#### Is your feature request related to a problem? Please describe.
Tomcat 7.0.73 add the [RFC 7230](https://www.ietf.org/rfc/rfc7230.txt) and [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) to resolve the HTTP path.

But RFC 3986 add the reserved characters in server side, just like ":", "[" and "]". If axios use the path with the query like
```
http://localhost:3000/api/blog?search_title=[Feature Request]balabala
```
The http request will be broken.
<img width="934" alt="WX20220129-102732@2x" src="https://user-images.githubusercontent.com/12878132/151647384-8076afd4-5ee2-49db-9d60-1c59d47470f6.png">

I search the axios source code, and then found [/lib/helpers/buildURL.js( function encode(val) )](https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js#L11) do this work.

#### Describe the solution you'd like
I think `config.paramsSerializer` is a good idea to resolve the special words.

But in this way, I should rewrite the `paramsSerializer` function in business code. Copy and paste the axios buildURL.js code, and set the `config.paramsSerializer` in global configuration.

In my opinion, axios should support RFCs and function `paramsSerializer` doesn't seem very graceful.

So can we add a switcher to enable or disable encoding all reserved characters? And let any server, which using RFC-7230 and RFC-3986, work well? Just like these code below.

https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js#L41
```javascript
// configuraion.RFC7230_RFC3986 = true; (maybe another better name)

if (!RFC7230_RFC3986) {
  if (utils.isArray(val)) {
    key = key + '[]';
  } else {
    val = [val];
  }
  utils.forEach(val, function parseValue(v) {
    if (utils.isDate(v)) {
      v = v.toISOString();
    } else if (utils.isObject(v)) {
      v = JSON.stringify(v);
    }
    parts.push(encode(key) + '=' + encode(v));
  });

} else {
  if (utils.isArray(val)) {
    val = val.join(',');
  } else if (utils.isDate(val)) {
    val = val.toISOString();
  } else if (utils.isObject(val)) {
    val = JSON.stringify(val);
  }
  parts.push(encodeURIComponent(key) + '=' + encodeURIComponent(val))
}

```

#### Additional context
If you think the solution is fine, I will commit this feature for axios. 😄

**Comment by jasonsaayman** [comment]
please open the PR as mentioned if you think this is still relevant
