### ISSUE TITLE
How to access config inside canceled request interceptor

### ISSUE THREAD

**Issue by kross-italk** [axios/axios#4433]
#### Section/Content To Improve
https://axios-http.com/docs/res_schema
https://axios-http.com/docs/handling_errors
https://axios-http.com/docs/cancellation

#### Suggested Improvement
When a request is aborted and caught in an interceptor there is no `error.config` which is on virtually all other errors, following the response schema. 
The instance of `error` is a Cancel object with only a message of "canceled". How am I supposed to get the request config that was canceled? 

#### Relevant File(s)
[e.g. README.md]
](https://axios-http.com/docs/res_schema)

**Comment by AntonS86** [comment]
I had the same problem, I had to completely rewrite the api service, take out all the logic from the interceptors into the function, and take the parameters from the closure

**Comment by Rookie088** [comment]
I have the same problem, If you use `AbortController` to cancel the request, you could try this way.


```js
// 1. Create the `AbortController ` instance.

const controller = new AbortController()
const requests = []


// 2. In the request interceptors

axios.interceptors.request.use(
    request => {
        const signal = controller.signal

        signal.addEventListener('abort', () => {
             requests.push(request)
        }, { once: true })
    }
)

// 3. call `abort` somewhere, you will see your requests.
// The listener only call once, and then will auto destroyed.

controller.abort()
console.log(requests)
// [...]

```

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks

**Comment by amcsi** [comment]
This is still an issue in 1.8.4. There is no `error.config` in the Cancel object that's passed as the only argument in the onRejected callback of `instance.interceptors.response.use`.

Unfortunately this way I'm not able to handle the cancellation appropriately if I don't know which request was aborted.
