### ISSUE TITLE
Update the readme examples to use arrow functions instead to the function keyword 

### ISSUE THREAD

**Issue by sidx8** [axios/axios#4434]
#### Section/Content To Improve

> Performing a `GET` request

```js
const axios = require('axios');
// Make a request for a user with a given ID
axios.get('/user?ID=12345')
  .then(function (response) {
    // handle success
    console.log(response);
  })
  .catch(function (error) {
    // handle error
    console.log(error);
  })
  .then(function () {
    // always executed
  });

```
#### Suggested Improvement

> Performing a `GET` request

```js
const axios = require('axios');
// Make a request for a user with a given ID
axios.get('/user?ID=12345')
  .then(response => {
    // handle success
    console.log(response);
  })
  .catch(error => {
    // handle error
    console.log(error);
  })
  .then(()=> {
    // always executed
  });

```
#### Relevant File(s)
README.md

**Comment by iiaishwarya** [comment]
Is this issue open for contribution?

**Comment by carpben** [comment]
We need to provide reasoning for this sort of change. 
1) How wide is browser support? 
2) Does Eslint have this rule as part of there recommended list?

**Comment by sanketpathak64** [comment]
If no one is working on it can I take this up?

**Comment by carpben** [comment]
@sanketpathak64 we first need to provide a rational - why is this change better. Using the function notation, the `function` word stands out and helps readability.

**Comment by jasonsaayman** [comment]
I think we will leave it as is for now.
