### ISSUE TITLE
Issue for FormData in axios 0.25.0

### ISSUE THREAD

**Issue by SomnathKadam** [axios/axios#4449]
Issue for FormData in axios 0.25.0

#### Describe the bug
Issue for FormData in axios 0.25.0

#### To Reproduce
Given below code working in Axios 0.24.0, but not working in Axios 0.25.0

```js
const GetFormData = (jsonRequest) => {
    let form = new FormData();
    let req = encryptData(JSON.stringify(jsonRequest));
    form.append('Request', `${req}`);
    form.append('KeyData', getKeyData());

    return form;
};
```

#### Environment
 - Axios Version [0.25]
 - react-native [0.67.2]

**Comment by hirbod** [comment]
While this issue might not following the template, it is absolutely correct.
formData is broken with axios > 0.24 on react-native.

The request body is just a json with _parts etc.

**Comment by Romick2005** [comment]
It is related with #4412. Provided a fix in pull request and waiting for a merge.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
