### ISSUE TITLE
May memory leak in 0.24.0.

### ISSUE THREAD

**Issue by pingfengafei** [axios/axios#4451]
#### Describe the bug
I've write a tool which uploads large (may more than 10GB) and multiple files to AWS S3 in browser, and met memory leak. 
Each http request put chunk at 5MB and the ArrayBuffer should GC. however:

First with `0.21.4`, memory always leak and there is an issue:  https://github.com/axios/axios/pull/3694, and then updated to `0.24.0`. after that, `local env` (macbook pro) works well but `My QA env` has a quite strange behavior.

First step, Every time upload success.
Second:  Upload failed with memory leak in much chance, and upload success in a few chance.
Third: the `Second` reversed.

I can not reproduce this behavior in my local, anyone met the same issue?

besides, the  https://github.com/axios/axios/pull/3694 related issue fixes `follow-directs` error, but it is used in Node, why effect browser?

#### Environment
 - Axios Version [0.24.0]
 - Adapter [HTTP]
 - Browser [Chrome, Safari, Firefox]
 - Browser Version [may latest or newly version]
 - OS: [11.6.1]

**Comment by ebilling** [comment]
Seeing the same issue.  We are doing POST requests every 10 seconds and it looks like the request body is not being released.  We have isolated it down to nothing but the HTTP POST through axios.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
