### ISSUE TITLE
Circular dependency detected 

### ISSUE THREAD

**Issue by dimaherbalife** [axios/axios#4455]
#### Describe the bug
Circular dependency detected between lib/adapters/xhr.js --> lib/defaults.js and lib/defaults.js -->  lib/adapters/xhr.js

#### To Reproduce
How I fix that problem

in **lib/adapters/xhr.js** 

```js   
var transitional = config.transitional || defaults.transitional
```

change on 

```js
   var transitional = config.transitional || {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false
      };
```
and remove in **lib/adapters/xhr.js** 
```js
 var defaults = require('../defaults');
```

**Comment by DigitalBrainJS** [comment]
#4220
