### ISSUE TITLE
Multipart form data not working on 0.25.0

### ISSUE THREAD

**Issue by pandiarajanvp** [axios/axios#4460]
#### Describe the bug
After upgrade form 0.24.0 to 0.25.0 multipart form date not working 
before update its working good

#### Environment
 - Axios Version [e.g. 0.25.0]
 - Adapter [e.g. XHR/HTTP]
 - Additional Library Versions [e.g. React 16.7, React Native 0.66.0]

**Comment by ZaidTryngo** [comment]
agreed i am also facing this issue

**Comment by TomCorvus** [comment]
Hi!
Take a look to this: https://github.com/axios/axios/issues/4406

**Comment by kenikori** [comment]
Hello, try this: https://github.com/axios/axios/issues/4406#issuecomment-1048693170

**Comment by rayhu** [comment]
@pandiarajanvp #4413 is merged which addressed this issue. pls close it.

**Comment by TomCorvus** [comment]
@rayhu not really, posting FormData with ´0.26.0´ doesn't work. There is the @kenikori comment, but this is not really the official way.

**Comment by DigitalBrainJS** [comment]
@rayhu In fact, that PR was reverted and Axios v0.26.0 was released without the fix, so this issue is still relevant ¯\_(ツ)_/¯. 
PR #4448 has this fix and some related improvements.

**Comment by fardolieri** [comment]
Version 0.27.2 fixes the problem for me.

**Comment by YohannesTz** [comment]
thank you! after two days on this error... the solution was just upgrading to 0.27.2

**Comment by ezoltech** [comment]
phiw, after several trials!!
