### ISSUE TITLE
An import cycle has been introduced in the 0.20.0

### ISSUE THREAD

**Issue by nskazki** [axios/axios#4463]
#### Describe the bug

It's a warning, not an actual bug. An import cycle has been introduced in the 0.20.0.  The cycle is `lib/defaults.js` -> `adapters/xhr.js` -> `lib/defaults.js`. This isn't a problem at this moment because by the time the `xhr` module needs the `defaults`, the `defaults` is done exporting. However, be careful and don't change 

https://github.com/axios/axios/blob/73e3bdb8835ba942096b662e9441f1d85ce4d484/lib/adapters/xhr.js#L11

to 

```js
var { transitional } = require('../defaults');
```

or you might end up with the uninitialized `transitional` as it's described in https://nodejs.org/dist/latest-v16.x/docs/api/all.html#all_modules_cycles.

I spotted this cycle because I use a [fork](https://github.com/vbraun/circular-dependency-plugin) of  https://github.com/aackerman/circular-dependency-plugin in my project. The thing about that fork is that it works much faster than the original as long as the project doesn't have any import cycles at all, even in the ignored folders.

#### To Reproduce

Again this's not a bug, so I'll just leave permalinks showing where the cycle begins. 

https://github.com/axios/axios/blob/73e3bdb8835ba942096b662e9441f1d85ce4d484/lib/defaults.js#L45-L53

https://github.com/axios/axios/blob/73e3bdb8835ba942096b662e9441f1d85ce4d484/lib/defaults.js#L18-L28

https://github.com/axios/axios/blob/73e3bdb8835ba942096b662e9441f1d85ce4d484/lib/adapters/xhr.js#L11

#### Expected behavior

I suggest untangling by introducing a `lib/default-transitional.js` and importing that module into the `xhr` and `defaults`. Another way to avoid future problems is to add a warning to the [`xhr`](https://github.com/axios/axios/blob/73e3bdb8835ba942096b662e9441f1d85ce4d484/lib/adapters/xhr.js#L11) explaining that the `defaults` can't be used at the import time there.

#### Environment
 - Axios Version >= 0.20.0

#### Additional context/Screenshots

Thanks for the lib!

**Comment by jasonsaayman** [comment]
Hi this has been fixed with 0.26.1
