### ISSUE TITLE
Solving Problem: Automatic droping Cookie header across domains

### ISSUE THREAD

**Issue by xTCry** [axios/axios#4464]
#### Describe the issue
After updating library `follow-redirects` due to security (https://github.com/follow-redirects/follow-redirects/commit/8b347cbcef7c7b72a6e9be20f5710c17d6163c22 ) in some of my projects, bugs have appeared related to sending cookies to headers due to redirection from https to http and back. As a result, this security update removes `Cookie` to the final request (although, personally, I didn't need it)

#### Example Code
Sample Cookie Code

```js
axios.post(
    'https://**redirectable to http url**',
    { password, login },
    {  headers: { Cookie: `PHPSESSID=${PHPSESSID}` }, },
);
```

As a result, the `Cookie` will be deleted after the redirect

#### Expected behavior, if applicable
I would like to be able to control the behavior of the `follow-redirects` library by passing `beforeRedirect`.
[An example from a test](https://github.com/follow-redirects/follow-redirects/blob/3d81dc3237b4ffe8b722bb3d1c70a7866657166e/test/test.js#L1537) to solve my problem, but it is unreachable due to the unavailability of `beforeRedirect`

```js
opts.beforeRedirect = function (options) {
  options.protocol = "https:";
};
```

#### Environment
 - Axios Version [^0.20.0]

### Temporary solution to the problem
Add to `package.json` resolutions for `follow-redirects` with version no higher than `1.14.6`
```json
"resolutions": {
  "axios/follow-redirects": "1.14.6"
},
```

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
