### ISSUE TITLE
I think es-fetch-api is better than axios

### ISSUE THREAD

**Issue by lchrennew** [axios/axios#4480]
#### Describe the issue
I created a project named `es-fetch-api`, welcome everybody come to give feedbacks and contributes.
It's here: https://github.com/lchrennew/es-fetch-api

#### Example Code

```js
import { getApi, json, POST } from "es-fetch-api";
import { getToken } from 'token-helper'

const useToken = async (ctx, next) => {
    ctx.header('Authorization', `Token ${await getToken()}`)
    return await next()
}
const useTimestamp = async (ctx, next) => {
    ctx.header('X-Timestamp', Date.now())
    return await next()
}

// Just append the middlewares, so easy.
const apiV1 = (...args) => getApi('http://yourdomain.com/api/v1')(...args, useToken, useTimestamp)

const createUser = async user => await apiV1(`user`, POST, json(user))
```

#### Expected behavior, if applicable
--

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kexirong** [comment]
看你定位，应该是中国人。所以用中文给你留言。
我确实认为axios 不是最理想http client库。
相信很多人也想寻找一个更适合。
你的库将readme看完了。觉得是不如axios的。用起来太复杂。你可以看看ky库。我也将在刚新建的项目中使用它

**Comment by jaromanda** [comment]
You'd say that since you authored it - it's nice - but your overuse of `await return functionThatReturnsPromise()` is comical

**Comment by lchrennew** [comment]
> You'd say that since you authored it - it's nice - but your overuse of `await return functionThatReturnsPromise()` is comical

Great suggestion! Thank you, I'll make it better.

**Comment by lchrennew** [comment]
> You'd say that since you authored it - it's nice - but your overuse of `await return functionThatReturnsPromise()` is comical

I've optimized it.

**Comment by jaromanda** [comment]
Now it is good
