### ISSUE TITLE
204 Request issue

### ISSUE THREAD

**Issue by masroorejaz** [axios/axios#4483]
#### Describe the issue
I am facing strange issue. If I load anything using axios without header in componentDidMount it only sends 200 xhr request (screenshot1). However if I send any other request it first send 204 xhr then 200 xhr request. I am hosting both moongoose and reactjs on same domain. But it's giving the same issue on both. I have been trying since 3 days and came up with no solution. Kindly help me as I want to reduce my requests (screenshot2).

#### Example Code
         const adminData = localStorage.getItem("admin_token_ticket_app");

                const AdminAuthData =
                {
                    "adminData": adminData
                };
                let response = await axios.post(apiGetAdminTokenDetails, AdminAuthData);

```js

```

#### Expected behavior, if applicable
I want only 200 xhr request and no 204 xhr request 

#### Environment
 - Axios Version [0.19.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Edge] 
 - Node.js Version [14.16.1] 
 - Additional Library Versions [e.g. ReactJS 16.14.0]

#### Additional context/Screenshots
![screenshot1](https://user-images.githubusercontent.com/5208320/154074495-45ef8494-3d1a-4c8d-ab93-54f90927cbef.png)
![screenshot2](https://user-images.githubusercontent.com/5208320/154074513-082d41b8-25aa-4bef-8dfe-024b00628f50.png)

**Comment by anyanyan07** [comment]
This is the CORS rules.You could see [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Comment by jasonsaayman** [comment]
Closing as its a CORS issue.
