### ISSUE TITLE
Custom accept header value being ignored on PUT

### ISSUE THREAD

**Issue by rfennell** [axios/axios#4485]
#### Describe the bug
I am trying to update a record in the [Black Duck REST API](https://ivanti.app.blackduck.com/api-doc/public.html#_updating_a_project_version) that requires the use of a PUT with custom accept and content-type headers.

#### To Reproduce
Using Axios (inside an Azure DevOps Pipeline Task), the call I make is 

```
var res = await axiosclient.put(
     theUrl,
     payload,
     {
            headers: {
              'Content-Type': "application/vnd.blackducksoftware.project-detail-4+json",
              Accept: "application/vnd.blackducksoftware.project-detail-4+json",
              authorization: `Bearer ${token}`
            }
     });
```
This fails with a 406 'Cannot generate acceptable response content'.

On looking at the error logs I see that the `accept` header used does not match what I have set

```
headers:
      { Accept: 'application/json',
        'Content-Type': 'application/vnd.blackducksoftware.project-detail-4+json',
        authorization:
         'Bearer <the token>',
        'User-Agent': 'axios/0.26.0',
        'Content-Length': 3536 }
```

I tried using a generic REST call, as opposed to the `put` method, as shown below, but this also failed with a 406.

```
    await axiosclient({
        method: 'PUT',
        url: theUrl,
        data: payload,
        headers: {
            'Content-Type': "application/vnd.blackducksoftware.project-detail-4+json",
            Accept: "application/vnd.blackducksoftware.project-detail-4+json",
            authorization: `Bearer ${token}`
        }
    })
```

**Workaround** - is to use `request-promise`, this works as expected

```
let putOptions = {
            method: 'PUT',
            uri: theUrl,
            body: payload,
            headers: {
                'Content-Type': "application/vnd.blackducksoftware.project-detail-4+json",
                'Accept': "application/vnd.blackducksoftware.project-detail-4+json",
              },
            auth: {
                'bearer': token
            },
            json: true
        }

rp(putOptions)

```

#### Expected behavior
Put should honor the `accept` header set as an option in all cases

#### Environment
 - Axios Version [0.20.0 and 0.26.0]
 - Node.js Version [10]
 - Running inside an Azure DevOps Pipeline Task

#### Additional context/Screenshots
I have also tried using the same code, using the `put()` method, in a standalone Typescript file, running against Node 16 on my PC and here it works as expected. I am only able to reproduce the problem when the code is run within an Azure DevOps Pipeline extension.

Node based Azure DevOps Pipeline extensions execute their code using Node 10 (which cannot changed). Could this be part of the problem?

**Comment by jasonsaayman** [comment]
I think this is a node 10 problem. I am however not going to investigate as node 10 is no longer supported by node and the lowest LTS one can use is 14.
