### ISSUE TITLE
Error.toJSON() should exclude httpsAgent

### ISSUE THREAD

**Issue by philBrown** [axios/axios#4486]
#### Describe the bug

if the `httpsAgent` property is set, it is not excluded from `error.toJSON()` resulting in a circular reference error

```none
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at JSON.stringify (<anonymous>)
```

#### To Reproduce

```js
const agent = new https.Agent({  
  rejectUnauthorized: false
});

axios.get("some-dodgy-url", {
  httpsAgent: agent
}).catch((err) => {
  console.error(err.toJSON())
})
```

#### Expected behavior

The error object should be serialisable as JSON without throwing circular reference errors.

#### Environment
 - Axios 0.26.0

#### Additional context/Screenshots

See [this StackOverflow post](https://stackoverflow.com/q/71150003/283366)

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks

**Comment by markpar** [comment]
Hi @jasonsaayman, I tried this out with pre-release version `1.0.0-alpha.1` and can still reproduce the error.   I have a repro at https://github.com/markpar/jest-html-reporters-test (Ignore the name - I encountered the error first in my HTML reporter, then traced it to Axios).  

Just clone it, run `npm install` then `npm test` to repro.  If there is anything I can do to help out, happy to pitch in!

**Comment by philBrown** [comment]
Doesn't appear to be solved @jasonsaayman. Can we re-open?
