### ISSUE TITLE
Axios freezes after calling the CancelToken.source.cancel()

### ISSUE THREAD

**Issue by buglessir** [axios/axios#4487]
#### Describe the issue
Axios doesn't work (freezes) for the new API calls after cancelation. In fact, I wanna cancel heavy and not finished API calls in previous page to improve performance.

#### Example Code

```js
// http-request.js

export const cancelelationSource = axios.CancelToken.source();

export const get = endpoint => {
  return axios.get(endpoint, {
    headers: { ...headers },
    timeout: 20000,
    cancelToken: cancelelationSource.token
  })
    .then(response => response.data)
    .catch(e => {
      console.log(e);
    });
}

// I use it in a React component

import { get, cancelelationSource } from './http-request';

const About = () => {
  useEffect(() => {
    get('http://localhost:3001/test2').then(data => console.log(data))
  }, []);
  return (
    <h1>About</h1>
  )
}

const App = () => {
  useEffect(() => {
    get('http://localhost:3001/test').then(data => console.log(data))

    return () => cancelelationSource.cancel();
  }, []);

  return (
    <div>
      <Link to="/about">About</Link>
    </div>
  )
}

render(
  <BrowserRouter>
    <Routes>
      <Route path="/" element={<App />} />
      <Route path="/about" element={<About />} />
    </Routes>
  </BrowserRouter>,
  document.getElementById('root')
);
```

#### Expected behavior, if applicable
Consider above example, I cancel the first request in `<App />` with:
`return () => cancelelationSource.cancel();`

But Axios doesn't fetch the next API call in `<About />` component... I actually expected it cancel first API which is active in background and execute the second API in new page.

#### Environment
 - Axios Version 0.26.0
 - Adapter HTTP
 - Browser Chrome
 - Browser 98
 - Node.js Version v14.17.2
 - OS: Windows 10
 - React 17.0.2

#### Additional context/Screenshots
I've not any screenshot or context

**Comment by anyanyan07** [comment]
I think the reason is that you used the same cancelToken in the two requests. You should use diffirent cancelToken for the diffirent request.Hope to help you.
[Note:you can cancel several requests with the same cancel token](http://www.axios-js.com/docs/#Cancellation)

**Comment by monster898** [comment]
When you use same cancelToken in two requests,which means two requests refer to the  same cancelToken object.Before your second request is sent,axios will check if the cancelToken be cancel.

in `lib/core/dispatchRequest.js`
```js
module.exports = function dispatchRequest(config) {
  throwIfCancellationRequested(config);

  // Ensure headers exist
  config.headers = config.headers || {};

  // Transform request data
  config.data = transformData.call(
    config,
    config.data,
    config.headers,
    config.transformRequest
  );
}

function throwIfCancellationRequested(config) {
  if (config.cancelToken) {
    config.cancelToken.throwIfRequested();
  }

  if (config.signal && config.signal.aborted) {
    throw new Cancel('canceled');
  }
}
```
`lib/cancel/cancelToken.js`
```js
CancelToken.prototype.throwIfRequested = function throwIfRequested() {
  if (this.reason) {
    throw this.reason;
  }
};
```

**Comment by jasonsaayman** [comment]
Seems that this is not an issue with Axios, if I am wrong please open a new issue after testing with the latest version and tag me.
