### ISSUE TITLE
v0.26.0 import axios from 'axios' errors must be changed to import axios from 'axios/dist/axios'

### ISSUE THREAD

**Issue by cjhitch** [axios/axios#4490]
#### Describe the bug
Fresh install of v26 leads to this error with an `import axios from 'axios'` was finally able to solve by reverting to a previous version, or pathing it to axios/dist/axios this is the error that displays
Uncaught TypeError: Failed to resolve module specifier "http". Relative references must start with either "/", "./", or "../".

#### To Reproduce
install v26 and attempt to import axios into a file. Was specifically using a react project with typescript
The import paths to the /lib/axios and going directly to that file gives the same error

```ts
import axios from 'axios';

const API = axios.create({
	baseURL: 'http://localhost:3000/',
})

export default API;
```

#### Expected behavior
The file to be imported correctly

#### Environment
 - Axios Version [0.26.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [e.g. 22]
 - Node.js Version [14.16.0]
 - OS: [Windows 10 enterprise]
 - Additional Library Versions [React 16.14, Typescript 4.3.5]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kcalixto** [comment]
I'm having the same issue, can you tell me how was it solved?

**Comment by rdmadeira** [comment]
Hi, I have the same and I can't find the solution. Axios version 0.27, node version 16.16.0

**Comment by FarNys** [comment]
lkjolkjkl

**Comment by AbdulWahabAchakzai** [comment]
Hi, I am facing to 
`Uncaught TypeError: Failed to resolve module specifier "axios". Relative references must start with either "/", "./", or "../".` error and I am using "axios": "^1.2.2" version, has anyone found the solution, cause I am searching for it for a long time.

**Comment by zacharylyj** [comment]
use https://cdnjs.com/libraries/axios in your html and remove import/require from ur js

**Comment by AbdulWahabAchakzai** [comment]
Thanks, the cdn did worked for me, the below cdn link worked for me:

script(src='https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.3/axios.min.js' integrity='sha512-L4lHq2JI/GoKsERT8KYa72iCwfSrKYWEyaBxzJeeITM9Lub5vlTj8tufqYk056exhjo2QDEipJrg6zen/DDtoQ==' crossorigin='anonymous' referrerpolicy='no-referrer')
