### ISSUE TITLE
Disabling SSL certificate verification on React Native

### ISSUE THREAD

**Issue by miteshdb** [axios/axios#4493]
hello there, 
I'm using ...

Axios: ^0.18.0
React native: 0.64.2

The problem is, by using Axios I'm not able to turn off SSL validation on React Native, I have researched many things over the internet but there is the only way I found is using the rn-fetch-blob package.

I think Axios would not disable on React Native, but still, Is there something that I'm missing? Any advice would be recommended.

Thanks!

**Comment by essamabuissa94** [comment]
@miteshdb Hello , can you give the link for the rn-fetch-blob solution ?
