### ISSUE TITLE
interceptors on redirect requests - for cookies on redirects. 

### ISSUE THREAD

**Issue by everett1992** [axios/axios#4496]
#### Is your feature request related to a problem? Please describe.
I need axios to use cookies on redirects. I'm using [http-cookie-agent](https://www.npmjs.com/package/http-cookie-agent) but it doesn't work when the agent has `keepAlive: true` 3846masa/http-cookie-agent#65. I'm hesitant to use http-cookie-agent because it relies on internal methods from node's request to intercept headers. It seems error prone and likely to break on future versions of node. 

#### Describe the solution you'd like
Add `axios.interceptors.beforeRedirect`. The beforeRedirect interceptor should have access to the previous request response headers (to read Set-Cookies) and the next requests headers (to set Cookies).
follow-redirects/follow-redirects#138

#### Describe alternatives you've considered

 - I could disable axios redirects and manually redirect requests, similar to [fetch-cookie](https://github.com/valeriangalliat/fetch-cookie#cookies-on-redirects) 
 - I may be able to modify http adapter to pass a beforeRedirect option to [follow-redirects](https://www.npmjs.com/package/follow-redirects), tho I don't see an after redirect hook to extend to handle Set-Cookie headers.

**Comment by Lotti** [comment]
Additional use:
when redirecting a POST call from http to https the body is normally discarded (probably for safety reasons). This behaviour could be changed if beforeRedirect hook of follow-redirect library is made accessible from axios configuration / axios interceptors.

References: PHP curl library gives the ability to configure how to perform redirects.

**Comment by jasonsaayman** [comment]
closing for now, please open a new issue if you think this is still relevant
