### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by neeteshp** [axios/axios#4503]
#### Describe the issue
I'm using Axios request for 2 API's. For one of the API, I'm using below code to set certificates globally -

https.globalAgent.options.ca = [
fs.readFileSync('certs/1.pem'),
fs.readFileSync('certs/2.pem'),
fs.readFileSync('certs/3.pem')
];

When I tried, Axios request for 1st API worked.

But second request, which is a Service Now request, throws error - Error: unable to get local issuer certificate

I tried configuring certificate specifically for the request, but first request itself is throwing same error.

async function getAuthToken() {
return await axios.post('Some URL' + "/authentication/connect/api1",
'grant_type=password&username=' +appID+ '&password=' + 'appPwd',
{
httpsAgent: new https.Agent({
  options: {
  ca: [
  fs.readFileSync('certs/1.pem'),
  fs.readFileSync('certs/2.pem'),
  fs.readFileSync('certs/3.pem')
],
rejectUnauthorized: false
}
}),
headers: {
'Content-Type': 'application/x-www-form-urlencoded',
'Authorization': 'Basic d3MudXNlcjo='
}
})
}

How to call second API without any errors ?

#### Example Code
```js
https.globalAgent.options.ca = [
    fs.readFileSync('certs/1.pem'),
    fs.readFileSync('certs/2.pem'),
    fs.readFileSync('certs/3.pem')
];

async function getAuthToken() {
    return await axios.post('Some URL' + "/authentication/connect/api1",
    'grant_type=password&username=' +appID+ '&password=' + 'appPwd',
    {
    httpsAgent: new https.Agent({
    options: {
    ca: [
        fs.readFileSync('certs/1.pem'),
        fs.readFileSync('certs/2.pem'),
        fs.readFileSync('certs/3.pem')
        ],
        rejectUnauthorized: false
    }
    }),
    headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Authorization': 'Basic d3MudXNlcjo='
    }
    })
}
```

#### Expected behavior, if applicable
Post request from second API shoul work

#### Environment
 - Axios Version [0.25.0]
 - Adapter [HTTP]
 - Node.js Version [14.1.0]
 - OS: [Windows]

#### Additional context/Screenshots
None

**Comment by jasonsaayman** [comment]
I would create an instance and then re-use this instance to call the endpoints. Also please re-try with the latest re-release version, should the problem persist please open a new issue and tag me.
