### ISSUE TITLE
Axios does not send image file to nodejs server?

### ISSUE THREAD

**Issue by magikarp28** [axios/axios#4520]
#### Describe the issue
Im using axios inside react and sending a form to my node server (to send an email with nodemailer).
When I try to send a file I just get an empty array while sending strings works fine.

#### Example Code
request in react:

```js
import img from "./img.jpg";

const handleRequest = async () => {
    let formdata = new FormData();
    fetch(img)
      .then((res) => res.blob())
      .then((blob) => {
        const imgFile = new File([blob], "image.jpg", { type: "image/jpeg" });
        formdata.append("imgFile", imgFile);
        formdata.append("text", "this is text");
      })
      .then(() => {
        console.log(formdata.get("imgFile"));  //image is actually stored in formdata 
        let config = {
          header: {
            "Content-Type": "multipart/form-data",
          },
        };
        axios
          .post("http://localhost:3030/mail", formdata, config)
          .then((res) => {
            console.log("Email Sent Successfully");
          })
          .catch((err) => {
            console.log(err);
          });
      });
  };
```

node server code:
```js
app.post("/mail", cors(), (formdata) => {
  let form = new multiparty.Form();
  let data = {};
  form.parse(formdata, function (err, fields) {
    console.log(fields);
  });
}); 
```

#### Expected behavior, if applicable
The server console.log should return 2 items, image and text.

the console returns` { text: [ 'this is text' ] }` as it should but the image does not seem to exist.
It seems like axios does not send the image file for some reason.

#### Environment
 - Axios Version [0.26.1]
 - OS: [Windows 10 2004 (19041.1415)]
 - Node.js Version [v16.13.0]
 - Additional Library Versions: [React 17.0.2, multiparty 4.2.3, cors 2.8.5, express 4.17.3]

**Comment by magikarp28** [comment]
It wasn't a problem with axios after all, it was my server code.

**Comment by YuriAtzler** [comment]
what was the error?
