### ISSUE TITLE
Prepare for Chrome User-Agent reduction

### ISSUE THREAD

**Issue by prsdthkr** [axios/axios#4521]
#### Is your feature request related to a problem? Please describe.
Chrome is changing how much userAgent data they expose to the browser. Usage of navigator.userAgent in https://github.com/axios/axios/blob/master/lib/helpers/isURLSameOrigin.js will throw browser warnings in the future.

#### Describe the solution you'd like
Use navigator.userAgentData

#### Describe alternatives you've considered
something like
```js
var msie = false;

// for chrome
const reducedUAString = navigator?.userAgentData?.brands
            ?.map?.(
                ({ brand, version }) => (`${brand}/${version}`),
            )?.join?.(' ');

// for other browsers
if(!reducedUAString){
    msie =  /(msie|trident)/i.test(navigator.userAgent);
}
```

#### Additional context
> User-Agent (UA) reduction is the effort to minimize the identifying information shared in the User-Agent string which may be [used for passive fingerprinting](https://www.w3.org/2001/tag/doc/unsanctioned-tracking/#unsanctioned-tracking-tracking-without-user-control). As these [changes are rolled out](https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html), all resource requests will have a reduced User-Agent header. As a result, the return values from certain Navigator interfaces will be reduced, including: navigator.userAgent, navigator.appVersion, and navigator.platform.

https://developer.chrome.com/docs/privacy-sandbox/user-agent/

**Comment by panzer** [comment]
Hi @prsdthkr, are you still looking for someone to contribute this feature?

**Comment by prsdthkr** [comment]
Hi @panzer, yes.

**Comment by jasonsaayman** [comment]
closing, please open a PR of this is still relevant
