### ISSUE TITLE
I found beforeRedirect on GitHub README but can not find it on npm 26.1

### ISSUE THREAD

**Issue by candy-Tong** [axios/axios#4524]
#### Describe the issue
I found beforeRedirect on GitHub reademe but can not find it on [npm 26.1](https://www.npmjs.com/package/axios)
npm readme
![image](https://user-images.githubusercontent.com/20377280/158137303-b6b14ee3-be07-4cf6-b063-f2672a8a17ae.png)

github readme
![image](https://user-images.githubusercontent.com/20377280/158137386-bfc00156-7f8d-4b45-a6fd-a69cc13f2967.png)

There are no beforeRedirect on npm package 26.1
#### Expected behavior, if applicable
npm package 26.1 should have beforeRedirect config

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Comment by samkahchiin** [comment]
I also faced the same issues, 
Downloading https://registry.yarnpkg.com/axios/-/axios-0.26.1.tgz#1ede41c51fcf51bbbd6fd43669caaa4f0495aaa9 and cannot find it in the downloaded folders but it should appear in the 0.26.1 packages as stated in the file -> https://github.com/axios/axios/blob/v0.26.1/index.d.ts

**Comment by jasonsaayman** [comment]
Please use 0.27.2, the above release got borked and is deprecated.
