### ISSUE TITLE
Sends a request through post method when in node, it will timeout if it carries data

### ISSUE THREAD

**Issue by Mr-xzq** [axios/axios#4529]
#### Describe the bug
Sends a request through post method when in node, it will timeout if it carries data.

#### To Reproduce

```js
  test('axios request post do carry data', async () => {
    // mock url
    const postUrl = 'https://jsonplaceholder.typicode.com/posts'
    const postData = { title: 'foo', body: 'bar', userId: 1 }

    await axios.request({
      method: 'post',
      url: postUrl,
      // timeout error
      // data: postData
    })

    // success
    await axios.post(
      postUrl,
      // timeout error
      // postData
    )

    const getUrl = 'https://jsonplaceholder.typicode.com/comments'
    const getQuery = { postId: 1 }
    
    // success
    await axios.get(getUrl, { params: getQuery })
  })
```
![image](https://user-images.githubusercontent.com/53166933/158501662-052f08cb-376a-4b9f-bd4c-a439617a9338.png)

#### Expected behavior
![image](https://user-images.githubusercontent.com/53166933/158501720-bfd07849-1bd2-4564-9f60-a373fd7ca42e.png)

#### Environment
 - Axios Version: 0.24.0
 - Adapter: HTTP
 - Node.js: Version 16.14.0
 - OS: Windows 10

#### Additional context/Screenshots
Non-get methods, such as put and delete method, will have the same error if they carry data (body)

**Comment by yeahnoob** [comment]
Maybe it's not a problem of "axios".

I have a check on that with the POST method and the test server URL, and it has no issue at all.

At first, checking the test server,
```bash
-> curl -X POST -H "Content-Type: application/json" -d '{"title":"foo", "userId": 1}' https://jsonplaceholder.typicode.com/posts
{
  "title": "foo",
  "userId": 1,
  "id": 101
}
```

Then run my demo code with "axios",
```bash
-> node index.js
{ title: 'foo', body: 'bar', userId: 1, id: 101 }
```

PS.
The demo code,

"package.json"
```json
{
    "name": "test-post",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
      "axios": "^0.26.1"
    },
    "type": "module"
}
```
"index.js"
```javascript
import { default as axios } from "axios";

const testPost = async () => {
  // mock url
  const postUrl = "https://jsonplaceholder.typicode.com/posts";
  const postData = { title: "foo", body: "bar", userId: 1 };
  return await axios.post(postUrl, postData);
};

// timeout error??

console.log((await testPost()).data);
```

**Comment by Mr-xzq** [comment]
🙏🙏🙏，Thank you very much for your help.

I found the reason. It's not Axios, it's msw.
