### ISSUE TITLE
Happy Eyeballs with Axios?

### ISSUE THREAD

**Issue by josedgm** [axios/axios#4535]
#### Describe the issue
Axios only uses the 1st IP from the DNS reply. Is there a way to force it to continue trying other IPs if the first one is not responsive? Like Happy Eyeballs (RFC 8305).

#### Example Code
N/A

#### Expected behavior, if applicable
If a hostname has several A records in its DNS answer, Axios must continue trying IP after IP until one gets a proper reply.

#### Environment
N/A

#### Additional context/Screenshots
N/A

**Comment by jasonsaayman** [comment]
Duplicate
