### ISSUE TITLE
The error handling function in request interceptors may not work as expect.

### ISSUE THREAD

**Issue by Tackoil** [axios/axios#4537]
#### Describe the issue
As the usage in README.md, a request interceptors will be like:

```js
axios.interceptors.request.use(function onFulfilled(config) {
    // Do something before request is sent
    return config;
  }, function onRejected(error) {
    // Do something with request error
    return Promise.reject(error);
  });
```

However, the `onRejected` function will handle the error in the **next** request intercetor `onFulfilled`.

#### Example Code
```js
instance.interceptors.request.use((config) => {
    throw new Error("Error in req1");
    return config;
}, (error) => {
    console.log("req1 handle the error", error);
    return Promise.reject(error);
})

instance.interceptors.request.use((config) => {
    throw new Error("Error in req2");
    return config;
}, (error) => {
    console.log("req2 handle the error", error);
    return Promise.reject(error);
})

instance.get("some site").then((res) => {
    console.log("get res")
}, (err) => {
    console.log("get err", err);
})
```
The output in console will be:
```
req1 handle error Error: Error in req2
get err Error: Error in req2
```

#### Expected behavior, if applicable
The better behavior may be that the error will be handled by function in the same request interceptor, I think.

#### Environment
 - Axios Version: 0.26.1
 - Adapter: HTTP
 - Node.js Version :16.14.0
 - OS: Windows 10

#### Additional context/Screenshots
The following graph was drawn according to the source code. It may be helpful.

![Behavior in Source Code](https://user-images.githubusercontent.com/24915252/159168856-e00e8dec-0633-4bc9-96a9-7f3b2b681319.png)

**Comment by zxcbb** [comment]
use synchronousRequestInterceptors, onFuillfilled2 ---> onReject2

**Comment by zxcbb** [comment]
[![](https://raw.githubusercontent.com/zxcbb/picgo/main/img/202203301133743.png)](url)

**Comment by Tackoil** [comment]
> use synchronousRequestInterceptors, onFuillfilled2 ---> onReject2

Thank you for your reply. It's my fault that I forgot to explain it'll only happen with asynchronous interceptors. But interceptors are presumed to be asynchronous by default and the behavior above is unreasonable, specially `onRejected2` has no chance of being work. So I think it need a fix.

**Comment by Anatoliy13Kravchenko** [comment]
Hi there. 
Unfortunately, I've met the same problem and it took a while to figure out, what's the problem. 
If you aren't going to solve the issue with asynchronous interceptors, may you at least highlight this in your documentation, thus you will save a lot of time for developers like me. 
Thank you in advance.
