### ISSUE TITLE
Set timeout exclude request sending time?

### ISSUE THREAD

**Issue by lucasHan239** [axios/axios#4541]
#### Describe the issue
my upload image api take 7s, sometime 9s for sending request (image 1.5MB). My config timeout is 10s so this api often timeouts.

#### Example Code

```js
const formData = new FormData();
formData.append('image', file);
const res = await this.$http.post("/upload/image", formData);
```

```js
const axiosIns = axios.create({
  baseURL: 'https://xxx/api/',
  timeout: 10000,
  headers: {'X-Custom-Header': 'foobar', 'X-Author' : 'Devculi'}
})
```

#### Expected behavior, if applicable
So is there a way to set timeout exclude request sending time? like: timeout = waiting time + download response time.

#### Environment
 - Axios Version 0.21.1
 - Browser Chrome, Brave
 - Browser Version Brave [Version 1.36.111 Chromium: 99.0.4844.51 (Official Build) (64-bit)](https://brave.com/latest/)
 - Node.js 13.0.1
 - OS: Window
 - Additional Library Versions vue: 2.6.12

#### Additional context/Screenshots
![274481203_801796054111913_4368248761762533805_n](https://user-images.githubusercontent.com/42675645/159201206-3bf9efb6-ba39-4767-af62-ca91a2603dbd.png)

**Comment by jasonsaayman** [comment]
no way currently to do this
