### ISSUE TITLE
req errors silently ignored when req.aborted = true

### ISSUE THREAD

**Issue by rick-seamless** [axios/axios#4546]
#### Describe the bug
If the underlying request has an error and `req.aborted = true` then the error and promise are ignored. Running the code below just exits execution without resolving or rejecting the promise.

#### To Reproduce

```js
(async () => {
	const axios = require('axios');
	try {
		console.log('making request');
		const response = await axios({url: 'http://copiersupplystore.com'}); // currently produces the underlying error "Unsupported protocol httsp"
		console.log('response', response);
	} catch (e) {
		console.error('error', e);
	}
})().catch(console.error);
```

#### Expected behavior
The promise should always either resolve or reject. This code in `lib/adapters/http.js` shoudn't ignore the error if `req.aborted = true`
```
    // Handle errors
    req.on('error', function handleRequestError(err) {
      if (req.aborted && err.code !== 'ERR_FR_TOO_MANY_REDIRECTS') return;
      reject(enhanceError(err, config, null, req));
    });
```

#### Environment
 - Axios Version: 0.26.1
 - Adapter: http
 - Browser: nodejs
 - Browser Version: n/a
 - Node.js Version: 14.18.0
 - OS: Windows 10

#### Additional context/Screenshots
No other info.

**Comment by WillianAgostini** [comment]
Hi @rick-seamless,

The next commit https://github.com/axios/axios/commit/e52e4dbb575fc8bd9cb7d2f5306f30ee82b40b4d has already resolved this bug on branch master.

I was reproduced this solution installing the axios with master version with 
`$ npm install "https://github.com/axios/axios.git#master"` and running your code.
