### ISSUE TITLE
Axios does not return XML error message from S3 when uploading asset over the size limit

### ISSUE THREAD

**Issue by vlad-bluescape** [axios/axios#4548]
#### Describe the issue
Axios does not return XML error message from S3 when uploading asset over the size limit

#### Example Code
This is the code I am running for the upload to S3:

```js
let dataForm = new FormData();

dataForm.append('key', functionParams.uploadData.fields.key);
dataForm.append('bucket', functionParams.uploadData.fields.bucket);
dataForm.append('X-Amz-Algorithm', functionParams.uploadData.fields['X-Amz-Algorithm']);
dataForm.append('X-Amz-Credential', functionParams.uploadData.fields['X-Amz-Credential']);
dataForm.append('X-Amz-Date', functionParams.uploadData.fields['X-Amz-Date']);
dataForm.append('Policy', functionParams.uploadData.fields.Policy);
dataForm.append('X-Amz-Signature', functionParams.uploadData.fields['X-Amz-Signature']);
dataForm.append('file', fs.createReadStream(functionParams.assetFullPath),
            { knownLength: fs.statSync(functionParams.assetFullPath).size }  
        );

const uploadServiceURL = uploadData.url;

var config = {
            method: 'POST',
            url: uploadServiceURL,
            headers: {
                ...dataForm.getHeaders(),
                'content-length': dataForm.getLengthSync()
            },
            data: dataForm,
            maxContentLength: Infinity,
            maxBodyLength: Infinity,
            transitional: {
                forcedJSONParsing: false,
                silentJSONParsing: false,
                clarifyTimeoutError: true
            }
        };


        axios(config)
            .then(answer => {
                  resolve(answer);
            })
            .catch((error) => {               
                console.log(`Error:`)               
                console.log(error.toJSON())
                reject(error)
            })

```

#### Expected behavior, if applicable
Error message from AXIOS should provide the XML error message that S3 returns. Instead, AXIOS fails. 

#### Environment
 - Axios Version : 0.24.0 
 - Node.js Version: v14.17.4
 - OS: OS 12.3

#### Additional context/Screenshots
I am using Axios to upload an asset to S3 using signed URLs.
It works correctly for files under the upload size limit, but when trying to upload an asset (.tiff, 114 Mb) over the upload size limit (50 Mb), I cannot get the XML error from S3.
When I use the **request** library to run the upload to S3, I get this as the **error** content :

```
UPLOAD FAILED. Status Code: 400. Error message: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>52432788</ProposedSize><MaxSizeAllowed>52428800</MaxSizeAllowed><RequestId>N8RFYCS0K10GB4FF</RequestId><HostId>2OaG69rf19DMxItXx8J//rscZuSbxU8hJ/93du/a1zaFwAZa6jN2v1xCDebW4MRMgW3Kfuw0n10=</HostId></Error>
```
But when I use AXIOS, I get back the error code 400 (good), but no XML message back:

```json
{
   "message": "Request failed with status code 400",
   "name": "Error",
   "stack": "Error: Request failed with status code 400\n    at createError (/Users/vlad/modules/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/vlad/modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/vlad/modules/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1317:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)",
   "config": {
      "transitional": {
         "silentJSONParsing": false,
         "forcedJSONParsing": false,
         "clarifyTimeoutError": true
      },
      "transformRequest": [
         null
      ],
      "transformResponse": [
         null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": null,
      "maxBodyLength": null,
      "headers": {
         "Accept": "application/json, text/plain, */*",
         "Content-Type": "multipart/form-data; boundary=--------------------------913873697821807580301477",
         "content-length": 114310407,
         "User-Agent": "axios/0.26.0"
      },
      "method": "post",
      "url": "https://s3.us-east-1.amazonaws.com/public-assets.bluescape.com",
      "data": {
         "_overheadLength": 938,
         "_valueLength": 114309413,
         "_valuesToMeasure": [],
         "writable": false,
         "readable": true,
         "dataSize": 0,
         "maxDataSize": 2097152,
         "pauseStreams": true,
         "_released": true,
         "_streams": [],
         "_currentStream": null,
         "_insideLoop": false,
         "_pendingNext": false,
         "_boundary": "--------------------------913873697821807580301477",
         "_events": {},
         "_eventsCount": 1
      },
      "axios-retry": {
         "retryCount": 0,
         "lastRequestTime": 1648080399442
      }
   },
   "status": 400
}
```

Any idea how can I get back the XML from S3 describing the issue? 
I want to present it as the cause of the error. The AXIOS error message (`"Request failed with status code 400"`) does not give any context of what the issue was: file size over the size limit for upload.

Thanks!

**Comment by vlad-bluescape** [comment]
Any help?

**Comment by mareebsiddiqui** [comment]
I am facing this issue too!

**Comment by Ikramzv** [comment]
`try {
    await client.post(url, formData, {
      headers: {
        "Content-Type": "multipart/form-data",
      },
      signal,
      transformResponse(data) {
        try {
          const parser = new DOMParser();
          const xml = parser.parseFromString(data, "application/xml");
          const errorCode = xml.getElementsByTagName("Code")[0].textContent;
          const errorMessage =
            xml.getElementsByTagName("Message")[0].textContent;
          return { code: errorCode, message: errorMessage };
        } catch (error: any) {
          return JSON.parse(data)
        }
      },
    });
    return true;
  } catch (err: any) {
    const error = err.response.data ?? err;
    // handle error
    conts { code, message } = error
  }`

**Comment by Ikramzv** [comment]
> #### Describe the issue
> Axios does not return XML error message from S3 when uploading asset over the size limit
> 
> #### Example Code
> This is the code I am running for the upload to S3:
> 
> ```js
> let dataForm = new FormData();
> 
> dataForm.append('key', functionParams.uploadData.fields.key);
> dataForm.append('bucket', functionParams.uploadData.fields.bucket);
> dataForm.append('X-Amz-Algorithm', functionParams.uploadData.fields['X-Amz-Algorithm']);
> dataForm.append('X-Amz-Credential', functionParams.uploadData.fields['X-Amz-Credential']);
> dataForm.append('X-Amz-Date', functionParams.uploadData.fields['X-Amz-Date']);
> dataForm.append('Policy', functionParams.uploadData.fields.Policy);
> dataForm.append('X-Amz-Signature', functionParams.uploadData.fields['X-Amz-Signature']);
> dataForm.append('file', fs.createReadStream(functionParams.assetFullPath),
>             { knownLength: fs.statSync(functionParams.assetFullPath).size }  
>         );
> 
> const uploadServiceURL = uploadData.url;
> 
> var config = {
>             method: 'POST',
>             url: uploadServiceURL,
>             headers: {
>                 ...dataForm.getHeaders(),
>                 'content-length': dataForm.getLengthSync()
>             },
>             data: dataForm,
>             maxContentLength: Infinity,
>             maxBodyLength: Infinity,
>             transitional: {
>                 forcedJSONParsing: false,
>                 silentJSONParsing: false,
>                 clarifyTimeoutError: true
>             }
>         };
> 
> 
>         axios(config)
>             .then(answer => {
>                   resolve(answer);
>             })
>             .catch((error) => {               
>                 console.log(`Error:`)               
>                 console.log(error.toJSON())
>                 reject(error)
>             })
> ```
> 
> #### Expected behavior, if applicable
> Error message from AXIOS should provide the XML error message that S3 returns. Instead, AXIOS fails.
> 
> #### Environment
> * Axios Version : 0.24.0
> * Node.js Version: v14.17.4
> * OS: OS 12.3
> 
> #### Additional context/Screenshots
> I am using Axios to upload an asset to S3 using signed URLs. It works correctly for files under the upload size limit, but when trying to upload an asset (.tiff, 114 Mb) over the upload size limit (50 Mb), I cannot get the XML error from S3. When I use the **request** library to run the upload to S3, I get this as the **error** content :
> 
> ```
> UPLOAD FAILED. Status Code: 400. Error message: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>52432788</ProposedSize><MaxSizeAllowed>52428800</MaxSizeAllowed><RequestId>N8RFYCS0K10GB4FF</RequestId><HostId>2OaG69rf19DMxItXx8J//rscZuSbxU8hJ/93du/a1zaFwAZa6jN2v1xCDebW4MRMgW3Kfuw0n10=</HostId></Error>
> ```
> 
> But when I use AXIOS, I get back the error code 400 (good), but no XML message back:
> 
> ```json
> {
>    "message": "Request failed with status code 400",
>    "name": "Error",
>    "stack": "Error: Request failed with status code 400\n    at createError (/Users/vlad/modules/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/vlad/modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/vlad/modules/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1317:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)",
>    "config": {
>       "transitional": {
>          "silentJSONParsing": false,
>          "forcedJSONParsing": false,
>          "clarifyTimeoutError": true
>       },
>       "transformRequest": [
>          null
>       ],
>       "transformResponse": [
>          null
>       ],
>       "timeout": 0,
>       "xsrfCookieName": "XSRF-TOKEN",
>       "xsrfHeaderName": "X-XSRF-TOKEN",
>       "maxContentLength": null,
>       "maxBodyLength": null,
>       "headers": {
>          "Accept": "application/json, text/plain, */*",
>          "Content-Type": "multipart/form-data; boundary=--------------------------913873697821807580301477",
>          "content-length": 114310407,
>          "User-Agent": "axios/0.26.0"
>       },
>       "method": "post",
>       "url": "https://s3.us-east-1.amazonaws.com/public-assets.bluescape.com",
>       "data": {
>          "_overheadLength": 938,
>          "_valueLength": 114309413,
>          "_valuesToMeasure": [],
>          "writable": false,
>          "readable": true,
>          "dataSize": 0,
>          "maxDataSize": 2097152,
>          "pauseStreams": true,
>          "_released": true,
>          "_streams": [],
>          "_currentStream": null,
>          "_insideLoop": false,
>          "_pendingNext": false,
>          "_boundary": "--------------------------913873697821807580301477",
>          "_events": {},
>          "_eventsCount": 1
>       },
>       "axios-retry": {
>          "retryCount": 0,
>          "lastRequestTime": 1648080399442
>       }
>    },
>    "status": 400
> }
> ```
> 
> Any idea how can I get back the XML from S3 describing the issue? I want to present it as the cause of the error. The AXIOS error message (`"Request failed with status code 400"`) does not give any context of what the issue was: file size over the size limit for upload.
> 
> Thanks!

You can transform response using **transformResponse** parameter in **axios request config** and can do whatever you want. Then you can access what you returned from the function inside catch block by accessing ```error.response.data``` .

```javascript
try {
    await axios.post(url, formData, {
      headers: {
        "Content-Type": "multipart/form-data",
      },
      signal,
      transformResponse(data) {
        try {
          const parser = new DOMParser();
          const xml = parser.parseFromString(data, "application/xml");
          const errorCode = xml.getElementsByTagName("Code")[0].textContent;
          const errorMessage =
            xml.getElementsByTagName("Message")[0].textContent;
          return { code: errorCode, message: errorMessage };
        } catch (error: any) {
          return JSON.parse(data)
        }
      },
    });
    return true;
  } catch (err: any) {
    const error = err.response.data ?? err;
    // handle error
    conts { code, message } = error
  }
  ```

**Comment by Ikramzv** [comment]
> You can transform response using **transformResponse** parameter in **axios request config** and can do whatever you want. Then you can access what you returned from the function inside catch block by accessing `error.response.data` .
> 
> ```js
> try {
>     await axios.post(url, formData, {
>       headers: {
>         "Content-Type": "multipart/form-data",
>       },
>       signal,
>       transformResponse(data) {
>         try {
>           const parser = new DOMParser();
>           const xml = parser.parseFromString(data, "application/xml");
>           const errorCode = xml.getElementsByTagName("Code")[0].textContent;
>           const errorMessage =
>             xml.getElementsByTagName("Message")[0].textContent;
>           return { code: errorCode, message: errorMessage };
>         } catch (error: any) {
>           return JSON.parse(data)
>         }
>       },
>     });
>     return true;
>   } catch (err: any) {
>     const error = err.response.data ?? err;
>     // handle error
>     conts { code, message } = error
>   }
> ```

**Comment by Ikramzv** [comment]
You can transform response using **transformResponse** parameter in **axios request config** and can do whatever you want. Then you can access what you returned from the function inside catch block by accessing ```error.response.data``` .

```javascript
try {
    await axios.post(url, formData, {
      headers: {
        "Content-Type": "multipart/form-data",
      },
      signal,
      transformResponse(data) {
          const parser = new DOMParser();
          const xml = parser.parseFromString(data, "application/xml");
          const errorCode = xml.getElementsByTagName("Code")[0].textContent;
          const errorMessage =
            xml.getElementsByTagName("Message")[0].textContent;
          return { code: errorCode, message: errorMessage };
      },
    });
    return true;
  } catch (err: any) {
    const error = err.response.data ?? err;
    // handle error
    const { code, message } = error
  }
  ```

**Comment by Lanna253** [comment]
I don't know what you mean 🧐 are u asking about Rss it's always say what I'm looking at has nothing to do with xml that's only thing I know and it's from a software PHP I followed it and it took me somewhere else a website and I read about some stuff say same thing xml file not connected to my files but how it make scene I don't know

**Comment by jasonsaayman** [comment]
for now please use the above solution else please open a pr and assign me
