### ISSUE TITLE
"Content-Type": "application/x-www-form-urlencoded" 携带多余字符： 

### ISSUE THREAD

**Issue by 2462870727** [axios/axios#4552]
#### Describe the issue
`"Content-Type": "application/x-www-form-urlencoded"` 是 会携带 一个 `:`

#### Example Code
Code snippet to illustrate your question

```js
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
		<style>
			.uploadWrap {
				margin: 20px;
			}
		</style>
	</head>
	<body>
		<div>
			
			<button onclick="axiosPostWithForm()">axios post 提交json格式数据</button>
			
		</div>

	</body>

	<script>
		const BASEURL = "http://localhost:7001/api";


		// axios post 提交application/x-www-form-urlencoded格式数据
		function axiosPostWithForm() {
			axios({
				url: BASEURL,
				method: "post",
				data: {
					id: 121,
				},
				headers: {
					"Content-Type": "application/x-www-form-urlencoded",
				},
			}).then(res => {
				console.log(`axios request`);
				console.log(res.data);
			});
		}
	</script>
</html>
```

#### Expected behavior, if applicable

`{"id":121}`

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/50451924/160354041-648c76e9-7983-4f37-9ae0-f735c9734cdc.png)

**Comment by 2462870727** [comment]
[https://codepen.io/Xiaocaiji1/pen/MWrmEpe](Codepen)

**Comment by bingqichen** [comment]
@2462870727  看起来是chrome的问题，Safari上面似乎没有这个问题？

**Comment by 2462870727** [comment]
这种方式传递似乎不是合法的， 下面这种方式 能够正常传递过去

```js
axios({
				url: BASEURL,
				method: "post",
				data: 'id=121&name=jack',
				headers: {
					"Content-Type": "application/x-www-form-urlencoded",
				},
			}).then(res => {
				console.log(`axios request`);
				console.log(res.data);
			});
```

**Comment by 2462870727** [comment]
> @2462870727 看起来是chrome的问题，Safari上面似乎没有这个问题？ <img alt="image" width="1030" src="https://user-images.githubusercontent.com/13115737/160570615-f4852a58-c79d-499b-bb49-ab90b9384625.png">
