### ISSUE TITLE
TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by soubhikchatterjee** [axios/axios#4556]
#### Describe the issue
When trying to upload a file that has non ISO chars (Eg: **_Những hình dạng của kinh tế hậu Tuổi Trẻ Online.pdf_**), axios throws an error, saying: 

"TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point."

#### Example Code
Code snippet to illustrate your question

```js
const formData = new FormData();
formData.append("file", selectedFile, file.name);

const response = await axios.post("/upload", formData, {
          headers: {
            "x-file-name":  file.name,
            "x-file-size":  file.size
          }
        });
```

#### Expected behavior, if applicable
While files with plain english names (eg: test.pdf) gets uploaded easily, non ISO file names (mentioned above) throws the above exception.

#### Environment
 - Axios Version : 0.21.1
 - Adapter XHR
 - Browser Chrome
 - Browser Version:  99.0.4844.74
 - Node.js Version v17.1.0
 - OS: OSX 12.0.1
 - Additional Library Versions React 16.13.1

#### Additional context/Screenshots
https://share.getcloudapp.com/YEurQxQN

**Comment by CarlosAmaral** [comment]
Had the same problem, `encodeURI` fixed it. Any chance this will be fixed?

**Comment by jasonsaayman** [comment]
i dont think we will fix it directly at this point, but if you would like please open a PR and tag me
