### ISSUE TITLE
https://github.com/axios/axios/blob/master/lib/defaults/index.js#L23  [object process]  in vm  [object Object] 

### ISSUE THREAD

**Issue by zyfyh8023** [axios/axios#4559]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Sashank999** [comment]
@zyfyh8023 There is no information about the bug here.
@jasonsaayman Close this please.

**Comment by reegodev** [comment]
I'll try to explain it since I've come across the same problem:

If you use axios inside a sandboxed environment, like with [vm2](https://github.com/patriksimek/vm2), the check at https://github.com/axios/axios/blob/master/lib/defaults/index.js#L24 fails because `process` is a mocked object which returns a standard `[object Object]` as its prototype. Due to this, no default adapter is created and app crashes.

I'm not sure why the extra check on the process prototype is needed, the issue that introduced it is 4 years old and I can't seem to get the reason: https://github.com/axios/axios/issues/1284

**Comment by reegodev** [comment]
Hello @jasonsaayman , would you like some help with this issue? 
I can craft a PR with the check removed to see if all tests pass.

**Comment by Y-qwq** [comment]
> I'll try to explain it since I've come across the same problem:
> 
> If you use axios inside a sandboxed environment, like with [vm2](https://github.com/patriksimek/vm2), the check at https://github.com/axios/axios/blob/master/lib/defaults/index.js#L24 fails because `process` is a mocked object which returns a standard `[object Object]` as its prototype. Due to this, no default adapter is created and app crashes.
> 
> I'm not sure why the extra check on the process prototype is needed, the issue that introduced it is 4 years old and I can't seem to get the reason: #1284. In any case, I believe the check can be freely removed now because the condition has been moved after the XMLHttpRequest check, so there is no risk of loading anything wrong.
> 
> The problem can be bypassed temporarily by doing this:
> 
> ```js
> axios.get(url, {
>    adapter: require('axios/lib/adapters/http')
> })
> ```

This solution was no longer adapted in axios 1.x. axios 1.x changed the logic here and added the `exports` field to package.json.

I asked the author in the vm2 repository and this is its response: https://github.com/patriksimek/vm2/issues/193#issuecomment-1365112963.

**Comment by Y-qwq** [comment]
> > I'll try to explain it since I've come across the same problem:
> > If you use axios inside a sandboxed environment, like with [vm2](https://github.com/patriksimek/vm2), the check at https://github.com/axios/axios/blob/master/lib/defaults/index.js#L24 fails because `process` is a mocked object which returns a standard `[object Object]` as its prototype. Due to this, no default adapter is created and app crashes.
> > I'm not sure why the extra check on the process prototype is needed, the issue that introduced it is 4 years old and I can't seem to get the reason: #1284. In any case, I believe the check can be freely removed now because the condition has been moved after the XMLHttpRequest check, so there is no risk of loading anything wrong.
> > The problem can be bypassed temporarily by doing this:
> > ```js
> > axios.get(url, {
> >    adapter: require('axios/lib/adapters/http')
> > })
> > ```
> 
> This solution was no longer adapted in axios 1.x. axios 1.x changed the logic here and added the `exports` field to package.json.
> 
> I asked the author in the vm2 repository and this is its response: [patriksimek/vm2#193 (comment)](https://github.com/patriksimek/vm2/issues/193#issuecomment-1365112963).

Hello @jasonsaayman , I crafted a [PR](https://github.com/axios/axios/pull/5792/files) to migrate the environment judgment logic to `knownAdapters`, it would enable the developer to always get the correct adapter.
If you think it makes sense, could you address it when you have time.
