### ISSUE TITLE
Eject using to remove interceptor but "Reject" in docs

### ISSUE THREAD

**Issue by ilyatrofimov01** [axios/axios#4564]
#### Section/Content To Improve
My axios version is "^0.26.1"

I found issue in docs by link :https://axios-http.com/docs/interceptors
There in the end of page you can find the way to remove interceptor :
<img width="881" alt="image" src="https://user-images.githubusercontent.com/48312293/160998161-3eb1341b-a3c3-4f55-bc3f-19d369deae83.png">
There docs told you to use "reject"

#### Suggested Improvement
In node modules in names correctly "eject"
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/48312293/160998900-d4afc4af-67c5-4e30-a00e-8ff424961c33.png">
So i Suggest to youse "eject" instead "reject" in docs 
#### Relevant File(s)
node_modules/axios/index.d.ts // line 181

**Comment by johnqiuwan** [comment]
It seems like the doc has been updated and fixed the typo. 
[https://axios-http.com/docs/interceptors](https://axios-http.com/docs/interceptors)

**Comment by ilyatrofimov01** [comment]
@johnqiuwan You are right, I checked docs and it has been updated
