### ISSUE TITLE
`localhost` unreachable after upgrade to node v17 (works in v16)

### ISSUE THREAD

**Issue by peterhirn** [axios/axios#4565]
#### Describe the bug
After upgrading to node v17 I cannot `get` localhost. Works with node v16.

#### To Reproduce
```js
// Works in node v16 and v17
axios.get("http://127.0.0.1:9090/").then((response) => console.log(response));

// Only works with node v16, in v17 returns `isAxiosError: true`
axios.get("http://localhost:9090/").then((response) => console.log(response));
```

#### Environment
 - Axios Version 0.26.1
 - Node.js Version 17.8
 - OS: Windows 10

#### Additional context

https://github.com/samber/prometheus-query-js/issues/21

**Comment by peterhirn** [comment]
`¯\_(ツ)_/¯`

**Comment by jsplate** [comment]
@peterhirn  Did you file a new issue?
I had the same problem and was interested on the reason for the error.

**Comment by jsplate** [comment]
After a little bit of research:

https://github.com/nodejs/node/issues/40702

They say it depends on how your OS is configured to resolve the dns order (which is not a bad idea)...

**Comment by peterhirn** [comment]
Interesting. I never opened a new issue and now just use `127.0.0.1` in node everywhere. Works fine and I have no motivation to look into localhost dns resolution problems. I'm sure they'll fix it out someday. 😅
