### ISSUE TITLE
Cross-Site Scripting: DOM fortify issue with axios

### ISSUE THREAD

**Issue by MenkaIVY** [axios/axios#4570]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by MenkaIVY** [comment]
Hi Team

I am getting two critical issues of Cross-Site Scripting: DOM while fortify scan with axios library. The axios version I am using is the latest one i.e "axios": "^0.26.1"
The error i m getting is from **node_modules/axios/lib/helpers/isURLSameOrigin.js**  line no 26 urlParsingNode.setAttribute('href', href); and line no 30- urlParsingNode.setAttribute('href', href);

Since it is critical issue please try fixing.

Thanks 
Menka

**Comment by Sashank999** [comment]
@MenkaIVY I don't think there could be a Cross-Site scripting bug as the element created in the specified file: https://github.com/axios/axios/blob/master/lib/helpers/isURLSameOrigin.js is not at all appended to the DOM directly. It is just used to test the URL.

**Comment by MenkaIVY** [comment]
Thanks @Sashank999 for clarification! 
Closing this now!
