### ISSUE TITLE
Multipart form parse error - Invalid boundary in multipart: None

### ISSUE THREAD

**Issue by Irfanwani** [axios/axios#4576]
#### Describe the bug
Axios is not setting content-type automatically as per the data (like fetch, which works fine).

#### To Reproduce
When we have to upload a file, we need to have `Content-Type` set to `multipart/form-data` but, after doing so, axios gives this error;

> - Multipart form parse error - Invalid boundary in multipart: None

But in fetch (also recommended by other in axios too), we don't need to set content-type manually but the package automatically detects it as per the data send.

I am using FormData for files but this is not working anyway.

```js
axios.post(url, data, {headers: 'Content-Type': "multipart/form-data"})
```

And if i remove the content-type header, then this error shows up;

> Unsupported media type \"application/json\" in request.

#### Expected behavior
So how much i know, it shouldn't be a problem but should be handled by axios. Also this happened after i upgraded axios and form-data to latest versions available today.

#### Environment
 - "axios": "^0.26.1",
 -"react": "17.0.1",
 -"react-native": "0.64.3",
 -"form-data": "^4.0.0",

**Comment by miteshdb** [comment]
Hey @Irfanwani , How did you resolve this error?

**Comment by Irfanwani** [comment]
@miteshdb i just downgraded back to version 0.24 as it clearly seems a problem with the axios new version. And note that it works fone with fetch.

**Comment by DigitalBrainJS** [comment]
@miteshdb Try can try this hotfix:

```js
import axios from "axios";

((transforms) => {
  const [original] = transforms;

  const isFormData = (thing) => {
    var pattern = "[object FormData]";
    return (
      thing &&
      ((typeof FormData === "function" && thing instanceof FormData) ||
        toString.call(thing) === pattern ||
        (typeof thing.toString === "function" && thing.toString() === pattern))
    );
  };

  transforms[0] = function hotFix(data, headers) {
    return !original || isFormData(data) ? data : original(data, headers);
  };
})(axios.defaults.transformRequest);
```

**Comment by foxbecoding** [comment]
Just remove the content-type the browser will automatically detect it

**Comment by ahmedelboshi** [comment]
> Just remove the content-type the browser will automatically detect it

thanks you saved my day

**Comment by alxvallejo** [comment]
> Just remove the content-type the browser will automatically detect it

This the first time in my career that someone's told me to omit a header to get it to work

**Comment by Irfanwani** [comment]
@alxvallejo actually this was an issue with axios. This version has some issues. At that point, I had to downgrade axios, but the latest version works fine.
