### ISSUE TITLE
Some thoughts on the use of bind method

### ISSUE THREAD

**Issue by Nirvana-Jie** [axios/axios#4583]
#### Is your feature request related to a problem? Please describe.

When I was looking at the code, I found a very magical thing. When we use the encapsulated `bind` method, we will find that when we `extend` the function, all the methods we mount are named `wrap`, which is  unsemantic.

And every time we use the bind method, we will create an array,I think this will be a big waste of resources

#### Additional context
```js
module.exports = function bind(fn, thisArg) {
  return function wrap() {
    var args = new Array(arguments.length);
    for (var i = 0; i < args.length; i++) {
      args[i] = arguments[i];
    }
    return fn.apply(thisArg, args);
  };
};
```
```js
function extend(a, b, thisArg) {
  forEach(b, function assignValue(val, key) {
    if (thisArg && typeof val === 'function') {
      a[key] = bind(val, thisArg);
    } else {
      a[key] = val;
    }
  });
  return a;
}
```

**Comment by DigitalBrainJS** [comment]
> we will create an array,I think this will be a big waste of resources
https://stackoverflow.com/questions/30234908/javascript-v8-optimisation-and-leaking-arguments
