### ISSUE TITLE
Multipart form parse error

### ISSUE THREAD

**Issue by AxelHgt** [axios/axios#4593]
#### Describe the bug
"multipart/form-data" requests throw an exception: 

``` Multipart form parse error - Invalid boundary in multipart: None```

#### To Reproduce
Simple multipart/form-data request:

```js
    const data = new FormData();
    spotInfos.pictures.forEach((file, index) => {
        data.append('pictures', {
            uri: file.path, // your file path string
            name: file.name,
            type: file.type
        })
    });
    spotInfos.tags.forEach(t => data.append('tags', t))
    data.append('name', spotInfos.name);
    data.append('description', spotInfos.description);
    return axiosInstance.post(`spots/`,
        data,
        {
            headers: { 'Accept': 'application/json', 'Content-Type': 'multipart/form-data', },
        });
```
This code works on axios 0.24.0

#### Expected behavior
No error

#### Environment
 - Axios 0.25.0 
 - React Native 0.66.4

#### Additional context/Screenshots
I have tested the latest version too (0.26.1)

**Comment by DigitalBrainJS** [comment]
Known issue: #4499, #4460, #4412, #4406
It seems this will be fixed in the next release.

**Comment by AxelHgt** [comment]
Oh indeed, sorry !
I have only found similar issues closed automatically (because not following the template).

Thanks,
I close it because it will be fixed in the next release
