### ISSUE TITLE
try catch not be able to catch the error throw by a promise async job

### ISSUE THREAD

**Issue by johnqiuwan** [axios/axios#4605]
#### Describe the bug
try catch not be able to catch the error throw by a promise async job, please have a look the line [https://github.com/axios/axios/blob/master/lib/core/Axios.js#L108](https://github.com/axios/axios/blob/master/lib/core/Axios.js#L108)

xhr adapter return a promise [https://github.com/axios/axios/blob/master/lib/core/dispatchRequest.js#L58](https://github.com/axios/axios/blob/master/lib/core/dispatchRequest.js#L58)

#### To Reproduce
see sample code below

```js
function test() {
    return new Promise((resolve, reject)=>{
        setTimeout(()=>{
            reject(100)
        },1000)
    }).then(data=>data, err=>Promise.reject(err))
    
}
let res
try {
    res = test()
} catch(err) {
    console.log(err)
}
```

#### Expected behavior
should be catch the error throw by a promise async job

#### Environment
 - Axios Version [master]
 - Adapter [XHR, custom adapter]
 - Browser [Chrome, Safari]
 - Browser Version [22]
 - Node.js Version [13.0.1]
 - OS: [iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions []

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by DigitalBrainJS** [comment]
All fine. That block is there to catch sync errors from dispatchRequest, like https://github.com/axios/axios/blob/ee151a7356ec4498af045dd830312822637890c9/dist/axios.js#L999

**Comment by richard-stafflink** [comment]
Is this still a thing?

**Comment by jasonsaayman** [comment]
closing as it seems to be solved
