### ISSUE TITLE
Can I put the 'User-Agent' header before 'Accept' and 'Content-Type'

### ISSUE THREAD

**Issue by owaineevans** [axios/axios#4611]
#### Describe the issue
When contacting an third party oauth server I get 403 when I use the axios library on node "v16.14.2". I understand this is not 'standard' but on further investigation it seems to expect the `User-Agent` header to be present before the `Accept` and `Content-Type`. This seems to be a convention that all the clients I've tested seem to follow (chrome, firefox, safari and curl).

#### Example Code
Rough (most probably not working) code example here

```ts
const instance = axios.create({
  baseURL: "http://localhost:8000",
  timeout: 20000,
});

const result = await instance.post(
    "oauth2/token",
    `data`,
    {
      headers: {
        "User-Agent": "curl/7.82.0",
        "Accept": "application/json",
        "Content-Type": "application/x-www-form-urlencoded",
      },
    })
    .then((result) => {
      logger.info(result);
    })
    .catch((error) => {
      logger.error(error);
    });

```

#### Expected behavior, if applicable

Is there a way to control the order of the headers - I tried using an interceptor as follows but that didn't work:

```ts

instance.interceptors.request.use((x) => {
  logger.info("interceptor");
  const headers = x.headers
  if (headers) {
    x.headers = {
      "User-Agent": headers["User-Agent"],
      "Accept": headers["Accept"],
      "Content-Type": headers["Content-Type"]
    };
  }
  return x;
});
```

#### Environment
 - Axios Version [0.26.1]
 - OS: [Debian bullseye]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by DigitalBrainJS** [comment]
You can try do the following:

```js
const instance = axios.create({
  baseURL: "http://localhost:8000",
  timeout: 20000,
});

delete instance.defaults.headers.common.Accept;
delete instance.defaults.headers.post['Content-Type'];
// or just
instance.defaults.headers = {};
```

**Comment by jasonsaayman** [comment]
closing please see above solution
