### ISSUE TITLE
content-type  application/x-www-form-urlencoded  repeated

### ISSUE THREAD

**Issue by zhangwang945** [axios/axios#4616]
#### Describe the bug
when  'content-type'  is in lowercase，
Devtool Network show :Content-Type: application/x-www-form-urlencoded, application/x-www-form-urlencoded，
that is repeated.

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
axios({
  method: 'post',
  url: 'http://yapi.corp.lanyicj.cn/mock/228/stock_trade/user_account',
  headers: { 'content-type': 'application/x-www-form-urlencoded' },
  transformRequest: [
    function () {
      return 'aa=44'
    }
  ]
})
```

#### Expected behavior
Content-Type: application/x-www-form-urlencoded

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by joaoGabriel55** [comment]
This occurs too on the most recent version of Axios (^0.27.2). I can take a look at it

**Comment by joaoGabriel55** [comment]
I think a good behavior could be to throw an error informing you that you need to pass `Content-Type`

**Comment by joaoGabriel55** [comment]
I tested another case. I changed the Content-type to `application/json` and I got this

![image](https://user-images.githubusercontent.com/23138717/170357140-3056bcad-6bce-4ab8-83f6-77573429e73c.png)

**Comment by joaoGabriel55** [comment]
I will investigate, I send some solution

**Comment by joaoGabriel55** [comment]
Apparently the bug happens when `transformRequest` is informed.
