### ISSUE TITLE
how about data option for delete request

### ISSUE THREAD

**Issue by ravi005e** [axios/axios#4617]
#### Summary
well as of now, delete request doesn't take data object.

Can you accommodate this change?

#### Environment
 - Axios Version [latest]
 - Adapter [HTTP]
 - Browser [Chrome]
 - Browser Version [latest]
 - Node.js Version [e.g. 14.x]
 - OS: [mac os latest]
 - Additional Library Versions [none]

**Comment by xgenem** [comment]
Does axios.delete(url, { // some data here}) not work?
