### ISSUE TITLE
tests inside /test/specs are not being run

### ISSUE THREAD

**Issue by despreston** [axios/axios#4619]
#### Describe the bug
None of the tests inside /tests/specs are being run during CI builds. Is it expected?

#### To Reproduce
Look at the latest CI builds.

#### Expected behavior
I think that ought to be run but idk what's goin on. 🤷 

#### Environment
master. Take a look at the last couple builds on GH. 

#### Additional context/Screenshots
--

**Comment by despreston** [comment]
Oops, maybe they are run as part of karma test suite? That would explain why I didn't see any of the output.

**Comment by DigitalBrainJS** [comment]
Yes, most of the Axios tests run with karma, except 'test/unit/**/*.js'
