### ISSUE TITLE
Impossible to use Axios 0.27.0 with React

### ISSUE THREAD

**Issue by JulSeb42** [axios/axios#4620]
#### Describe the bug
I'm trying to install Axios 0.27.0 with React,  but when I run `npm start` I get this error:

```
Module not found: Error: Can't resolve 'url' in '/path/to/node_modules/axios/lib/adapters'
```

#### To Reproduce
Just run `npm i axios` in your terminal, and `npm start`

#### Expected behavior
App running normally

#### Environment
 - Axios Version [0.27.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [100.0.4896.127]
 - Node.js Version [16.13.1]
 - OS: [macOS 12.3.1]
 - Additional Library Versions [React 18.0.0]

**Comment by DigitalBrainJS** [comment]
You must set up global nodejs modules for your build tool. PR #3544 imports the entire 'url' module to validate url as I mentioned in #4594 where I tried to revert this change. As a result, Axios has become 2 times larger in size, and users now have to bundle nodejs globals in their builds. ¯\_(ツ)_/¯
