### ISSUE TITLE
Impossible to use Axios 0.27.0 with React

### ISSUE THREAD

**Issue by JulSeb42** [axios/axios#4621]
#### Describe the bug
I'm trying to install Axios 0.27.0 with React,  but when I run `npm start` I get this error:

```
Module not found: Error: Can't resolve 'url' in '/path/to/node_modules/axios/lib/adapters'
```

#### To Reproduce
Run `npm i axios` in your terminal, and `npm start`, and then in your App.js:

```js
import axios from "axios"
```

#### Expected behavior
App running normally

#### Environment
 - Axios Version [0.27.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [100.0.4896.127]
 - Node.js Version [16.13.1]
 - OS: [macOS 12.3.1]
 - Additional Library Versions [React 18.0.0]

#### Additional context/Screenshots
None

**Comment by pdanpdan** [comment]
I also have something related (on v0.27.0)
All GET calls throw an error `url.parse` is not a function at
https://github.com/axios/axios/blob/cdd7add9b05c2c651de197a54d6a51172a6655a3/lib/adapters/xhr.js#L41

Ubuntu 22.04 / Chrome Beta

**Comment by WillianPadilha** [comment]
> I also have something related (on v0.27.0) All GET calls throw an error `url.parse` is not a function at
> 
> https://github.com/axios/axios/blob/cdd7add9b05c2c651de197a54d6a51172a6655a3/lib/adapters/xhr.js#L41
> 
> Ubuntu 22.04 / Chrome Beta

Some issue with Vue 3 + SPA

**Comment by TheSeg** [comment]
Can confirm in Vue 3 + SPA, Axios is broken due to the use of `url`.

**Comment by diego-paired** [comment]
React Native 
`ERROR  [Error: undefined Unable to resolve module url from /node_modules/axios/lib/adapters/xhr.js`

**Comment by skelawsky** [comment]
Can confirm with axios + react v18

**Comment by mustavikhan05** [comment]
Same issue

**Comment by mxp131011** [comment]
So did I

**Comment by AllenTan005** [comment]
same here on vue 2

**Comment by mustavikhan05** [comment]
> Same issue



> Run: `npm i url`. Error is due to: [4594](https://github.com/axios/axios/pull/4594)



> Run: `npm i url`. Error is due to: [4594](https://github.com/axios/axios/pull/4594)

This worked! Thank you so much!

**Comment by luiScolari** [comment]
> Run: `npm i url`. Error is due to: [4594](https://github.com/axios/axios/pull/4594)

Work for me, thanks!

**Comment by TheSeg** [comment]
Having to install an additional library [not maintained by Node](https://github.com/defunctzombie/node-url) is not a workable solution.

**Comment by Jplus2** [comment]
got the same issue here using React

**Comment by nathangroblewski** [comment]
> React Native `ERROR [Error: undefined Unable to resolve module url from /node_modules/axios/lib/adapters/xhr.js`

I'm getting the same. Rolling back to 0.26.0 resolved it for the time being.

**Comment by architect-aimonkey** [comment]
same issue, hope you release v0.27.1 soon

**Comment by challengy1** [comment]
I've encountered the same issue with React Native.

**Comment by jasonsaayman** [comment]
I am releasing a new version asap to fix this issue

**Comment by zain-khalid** [comment]
@challengy1 Did your error resolve in the new version?
Bugsnag this error on my app case

**Comment by challengy1** [comment]
Sorry for my late reply. Unfortunately, I haven't tried it and I have no idea.

**Comment by kmsu** [comment]
Tuve el mismo problema. La solución que encontre fue usar este comando
npm install react-scripts@latest

verifiquen en las dependencias en el archivo package.json deben tener "react-scripts": "^5.0.1" la version
el comando que les puse es para actualizar esa dependencia. 

PD. Disculpen por colocar la solución en estas fechas. Hasta ahora tuve el problemay encontré la solución
