### ISSUE TITLE
axios 0.27.1 build even larger than 0.27.0

### ISSUE THREAD

**Issue by lorand-horvath** [axios/axios#4629]
#### Describe the bug
@jasonsaayman 
The latest 0.27.1 build in the /dist folder (axios.min.js) is even larger than the previously already huge 0.27.0 version (43 kB vs 31 kB). The file size should be under 20 kB.

https://github.com/axios/axios/pull/4594 should have fixed the issue, but it seems there's still something similar going on with the built files in /dist to what happened with a previous release e.g. https://github.com/axios/axios/issues/4429

#### To Reproduce

```js
npm install axios@0.27.1
```

#### Expected behavior
Proper build under 20 kB.

#### Environment
 - Axios Version 0.27.1
 - Node.js Version 12.22.12

#### Additional context/Screenshots
None.

**Comment by jasonsaayman** [comment]
Found the issue thanks, I am pushing a change for this, as well as some other issues
