### ISSUE TITLE
FormData request header doesn't include boundary

### ISSUE THREAD

**Issue by Irevall** [axios/axios#4631]
#### Describe the bug
Boundary is included in payload, but it's missing in `Content-Type` header - it's just `multipart/form-data`.

#### To Reproduce
```js
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Axios issue with form-data</title>
    <script src="https://unpkg.com/axios@0.27.1/dist/axios.min.js"></script>
  </head>
  <body>
    <script>
      (async () => {
        await axios.postForm('http://localhost:8080/', { a: 'b' });
      })();
    </script>
  </body>
</html>
```
![Screenshot 2022-04-26 at 12 53 19](https://user-images.githubusercontent.com/24963770/165284771-ba5e81b6-6764-4d1d-b48b-e2abe31b857e.png)
![Screenshot 2022-04-26 at 12 53 27](https://user-images.githubusercontent.com/24963770/165284779-b9e21749-02a8-4d0f-96b2-58c6aa230fb0.png)

#### Expected behavior
`Content-Type` header should have a boundary.

#### Environment
 - Axios Version [0.27.0/0.27.1]
 - Adapter [n/a]
 - Browser [Chrome]
 - Browser Version [100.0.4896.127]
 - Node.js Version [n/a]
 - OS: [MacOS 12.3.1]
 - Additional Library Versions [n/a]

#### Additional context/Screenshots
n/a

**Comment by aspnetde** [comment]
Can confirm. This breaks file uploads for my React application (web, all up to date). Downgrading to `0.26.0` helps to work around.

**Comment by Irevall** [comment]
> Can confirm. This breaks file uploads for my React application (web, all references up-to-date). Downgrading to `0.26.0` helps to work around.

0.26.0 doesn't work for me, as payload is broken there. 😬
I'm keeping axios at 0.24.0 for a while now.

**Comment by daids** [comment]
me too, 0.26.1 work for me, but 0.27.1 not work.

**Comment by jasonsaayman** [comment]
Looking into it, sorry about that

**Comment by komik966** [comment]
The below change was introduced in v0.27.0:

> Removed functionality that removed the the Content-Type request header when passing FormData (https://github.com/axios/axios/pull/3785)

Now axios forces `content-type` header to be set for requests with `FormData` payload.
Having possibility to send `FormData` request without a `content-type` header should do the trick.

https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post

**Comment by DigitalBrainJS** [comment]
@jasonsaayman hotfix: #4640 and #4639

**Comment by zavvla** [comment]
![telegram-cloud-photo-size-2-5422568654593179350-x](https://user-images.githubusercontent.com/11782509/165370604-9fac455c-f1dc-4def-bf2a-5d3b6ed59880.jpg)
I have this problem too. =(

**Comment by symonxdd** [comment]
For my college project I needed to upload a file. I found some article that explains how to do that in Vue and I had literally struggled for 5 hours straight with this piece of crap bug to just find out that the authors app used an old version of axios which didn't include this pathetic bug which should never had been introduced, ever...

I think I'm done with axios for a few years.

At the time of writing this is axios 0.27.1 (latest)

**Comment by jasonsaayman** [comment]
Thanks to everyone and especially @DigitalBrainJS who helped with this, i will relase 0.27.2 asap.

**Comment by NikolayCheremnov** [comment]
> Thanks to everyone and especially @DigitalBrainJS who helped with this, i will relase 0.27.2 asap.

Hello. Why is the problem reproduced on axios version 1.1.3 (npm install axios@latest), but works on version 0.27.2 (now it's a minor version?).
Thanks.

**Comment by emielmolenaar** [comment]
> > Thanks to everyone and especially @DigitalBrainJS who helped with this, i will relase 0.27.2 asap.
> 
> Hello. Why is the problem reproduced on axios version 1.1.3 (npm install axios@latest), but works on version 0.27.2 (now it's a minor version?). Thanks.

Indeed. I am having bounday-header issues with 1.1.3, but not with ^0.27. Don't get why 😃
