### ISSUE TITLE
Unexpected 'Unsupported protocol' error for relative URLs containing colon (:) character

### ISSUE THREAD

**Issue by cduff** [axios/axios#4633]
#### Describe the bug
For some REST API endpoints we use [Google Cloud API Custom Methods](https://cloud.google.com/apis/design/custom_methods) URL design like `/api/resource:customVerb`.

These worked with `axios` prior to **0.27.1** but now they result in an error like:

`AxiosError { message: "Unsupported protocol /api/resource:', code: "ERR_BAD_REQUEST", ... }`

#### To Reproduce
Try to have `axios` get a relative URL with a colon in it, e.g.
```js
axios.get("/api/resource:customVerb");
```

#### Expected behavior
Should continue working as it did before version **0.27.1**.

#### Environment
 - Axios Version: 0.27.1
 - Browser: Microsoft Edge 100.0.1185.50
 - Node.js Version: 16.14.2
 - OS: Windows 10 Pro

#### Additional context/Screenshots
n/a

**Comment by philBrown** [comment]
Nothing to do with Axios. The colon needs to be encoded...

```js
axios.get("/api/resource%3AcustomVerb")
```

**Comment by cduff** [comment]
> Nothing to do with Axios. The colon needs to be encoded...
> 
> ```js
> axios.get("/api/resource%3AcustomVerb")
> ```

@philBrown Are you sure? Source?

I'm not intimately familiar with the standards in play for this but the following suggest it is valid without encoding:

- Example URL: https://en.wikipedia.org/wiki/Template:Welcome
- Use without encoding in [Google Cloud API Custom Methods](https://cloud.google.com/apis/design/custom_methods)
- https://stackoverflow.com/questions/2053132/is-a-colon-safe-for-friendly-url-use
- https://stackoverflow.com/questions/1737575/are-colons-allowed-in-urls

**Comment by philBrown** [comment]
@cduff My mistake, this is an Axios-specific problem. Encoding the colon is a valid work-around though

**Comment by gomgomshrimp** [comment]
I have the same issue with Axios version `0.27.1`.
To work properly, use the previous version.
`<script src="https://unpkg.com/axios@0.26.1/dist/axios.min.js"></script>`
