### ISSUE TITLE
interceptors types are broken

### ISSUE THREAD

**Issue by popuguytheparrot** [axios/axios#4634]
use<T = V>(onFulfilled?: (value: V) => T | Promise<T>, onRejected?: (error: any) => any, options?: AxiosInterceptorOptions): number;

This is not correct type. Here need AxiosError

**Comment by productdevbook** [comment]
some problem

**Comment by DaniilIsupov** [comment]
i have same problem
in my code `onRejected` returned `undefined`
i would like typescript to take this as an error
