### ISSUE TITLE
AxiosError ERR_NETWORK contains request as response

### ISSUE THREAD

**Issue by mengelbrecht** [axios/axios#4655]
#### Describe the bug
When performing an axios request which is rejected with `ERR_NETWORK` the created `AxiosError` contains the request as response.
This leads to the issue that the response of the `AxiosError` contains the status code 200 and the body of the request although in reality no response was received.

I think the issue is that the request is passed as 5th parameter (response) of the `AxiosError` constructor here:
https://github.com/axios/axios/blob/bc733fec78326609e751187c9d453cee9bf1993a/lib/adapters/xhr.js#L119

#### To Reproduce

Sample project:
[sample.zip](https://github.com/axios/axios/files/8588127/sample.zip)

Running the sample project with `npm run test` prints the following to the console:
```
error code: ERR_NETWORK
response status: 200
response body: {"foo":"bar"}
```

#### Expected behavior
The response field in the `AxiosError` created due to `ERR_NETWORK` should be undefined.

#### Environment
 - Axios Version 0.27.2
 - Adapter XHR
 - Browser -
 - Browser Version -
 - Node.js Version 18.0.0
 - OS: macOS 12.3.1
 - Additional Library Versions msw: ^0.39.2

#### Additional context/Screenshots
 
NA

**Comment by fdrobidoux** [comment]
Same error for me. It's weird, I get a normal 401 when I omit a necessary header for a request, and when it's well-formed, I get that error. Same version, using 16.17.0 (LTS when it was installed), Windows 10.

**Comment by theboybreyy** [comment]
Encountering same error here. Mine is caused by CORS and i wanna ask how best can I solve it ?
