### ISSUE TITLE
Error network on IOS devices

### ISSUE THREAD

**Issue by Melber17** [axios/axios#4658]
#### Describe the bug
I had problem, that I need to set headers for my GET requests. Specifically -  **`Content-type: "application/json"`**. 
And if you try to do it - you'll see that your request won't be with it. Solution can be found [here](https://github.com/axios/axios/issues/86).  (Just add  field **data: {}**).
And after that everything started working but only for **Android**.  And when I looked in Xcode and found logs like:  can't be field **data** in GET request. And in the end it turns out that we cannot pass the data field.

#### To Reproduce

```js
	const response = await axios.get(url, {
		headers: {
			"Accept": "application/json",
			"Content-Type": "application/json"
		},
		data: {}
	});
```

#### Expected behavior
Expected response from the server with the data field

#### Environment
 - Axios Version 0.21.0
 - React Native - 0.67.3

#### Additional context/Screenshots

![Screenshot 2022-04-30 at 10 16 41 am](https://user-images.githubusercontent.com/63192915/166096114-d9d4971c-e53e-4fe2-bf0d-74efbd2cbf19.png)

**Comment by Melber17** [comment]
I found a line of code that make this error https://github.com/axios/axios/blob/6b1ae0b84a0fb3fe39360268cb822956a93b3317/lib/adapters/xhr.js#L159
if you try to remove it then everything will work. I made the library patch and so far this is my only solution

**Comment by mlazari** [comment]
@Melber17 Why would a GET request require to send a `Content-Type` header? GET requests don't have a body and setting `data` for them seems strange to me. Maybe there is an issue with the backend where you're sending the requests?

**Comment by Melber17** [comment]
@mlazari  I don't know much about the server, but the documentation says that some API calls require you to send data in a certain format as part of an API call. By default, all API calls expect input in JSON format, however, you need to tell the server that you are sending the payload in JSON format.
And to do this, you must include the **Accept => application/json** and **Content-Type => application/json** HTTP headers on every call.

**Comment by mlazari** [comment]
@Melber17 Yeah, but how do you send json with a GET request? It makes sense for a POST request, since you can send the json data in the body, but GET requests can't have a body as far as I know. Accept => application/json makes sense since that tells the server which content type the client can understand / expects in the response.

**Comment by mlazari** [comment]
I could be wrong, maybe it makes sense to have Content-Type for a GET request in some situations though... I see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17 mentions: "The Content-Type entity-header field indicates the media type of the entity-body sent to the recipient or, in the case of the HEAD method, the media type that would have been sent had the request been a GET."

**Comment by mlazari** [comment]
Here is an interesting article on this topic: https://evertpot.com/get-request-bodies/

**Comment by Melber17** [comment]
@mlazari  thanks for the information 👍. I think it's worth closing the issue. The problem is in the API I use
