### ISSUE TITLE
Axios can't sent the object to django

### ISSUE THREAD

**Issue by Vincent0706** [axios/axios#4662]
#### Describe the issue
When I want to post a request to django project with axios, I found it can't sent the right data. And the data is empty.

#### Example Code
Code snippet to illustrate your question

```js
// Example code here
let params = Object({
     firstname: "123",
     lastnaem: "1233",
});
console.log(JSON.stringify(params));
 axios
      .post(
      "/logins",
      params
     )
    .then(function (response) {
          console.log(response);
     })
     .catch(function (error) {
           console.log(error);
     });
```

#### Environment
 - Axios Version : 0.27.2
 - Browser : Chrome
 - Node.js Version : v16.14.0
 - OS: Windows

#### Additional context/Screenshots
I create a django response like this:
```python
def index(request):
    if request.method=='GET':
        return render(request,'index.html')
    elif request.method=='POST':
        print(request.POST)
        return JsonResponse(request.POST)
    else:
        return HttpResponse("error")
```

I tried many times, and found it always print like this:
![image](https://user-images.githubusercontent.com/82581024/166260972-35d53df0-cc99-4776-82b6-4a1466541599.png)

The console log like this:
![image](https://user-images.githubusercontent.com/82581024/166261292-485f8b3d-f430-455d-8048-e02132a54981.png)

When i use qs.stringify(params) instead of the param, it will be ok.
I don't know which step I took wrong. And could you tell me why the `qs.stringify(params)` is ok?

**Comment by zpliu1126** [comment]
Hi guy~ 
I meet the same problem, but I solve it by adding the `content-type`  in request  and change JSON data to URL  form.
> I don't know which step I took wrong. And could you tell me why the qs.stringify(params) is ok?
I think the default request header would be setted as `application/x-www-form-urlencoded`  when you didn't assign.

```js
import Qs from 'qs'
const request = axios.create({
  baseURL: process.env.VUE_APP_BASE_API,
   baseURL: "/api",
  timeout: 2000,
  headers: {
    "Content-Type": "application/x-www-form-urlencoded",
    // "Content-Type": "application/json;charset=utf-8",
    // "Content-Type": "multipart/form-data",
    Accept: "application/json",
  },
  transformRequest: [
    function(data) {
      return Qs.stringify(data);
    },
  ],
});
```

**Comment by Vincent0706** [comment]
Sorry, I don't know why the qs.stringify(params) is ok. I just find this solution on the Internet. And I can try your solution to solve my question.

**Comment by jasonsaayman** [comment]
Seems sorted then if not please re-open
