### ISSUE TITLE
Unintentional overwriting if headers and transformRequest are specified

### ISSUE THREAD

**Issue by AkifumiSato** [axios/axios#4686]
#### Describe the bug
If you specify headers and transformRequest at the same time in the create option, the request headers will not be reflected.

#### To Reproduce
```js
import { stringify } from 'querystring'
import axios from 'axios'

const axiosInstance = axios.create({
  baseURL,
  headers: { 'content-type': 'application/x-www-form-urlencoded' },
  transformRequest: (data: string) => stringify(JSON.parse(data),
})
```

#### Expected behavior
Headers should be reflected even when transformRequest is specified.

#### Environment
 - Axios Version [0.24.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [16.13.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by artze** [comment]
Hi @AkifumiSato 

I tried to replicate your scenario on Node. I'm able to send my custom `headers` through, while using `transformRequest`. See my impl:

```js
(async function () {
  const axiosInstance = axios.create({
    baseURL: "https://axiostest.free.beeceptor.com",
    headers: {
      "custom-header": "custom header value",
    },
    transformRequest: [
      function (data) {
        const transformedData = {
          ...data,
          addedByTransfrom: "added data",
        };
        return JSON.stringify(transformedData);
      },
    ],
  });

  console.log("calling");
  try {
    const res = await axiosInstance.post("", { originalData: "data" });
    console.log(res.data);
  } catch (err) {
    console.error(err);
  }
})();
```

### Request Received on Server:

Request body:
![image](https://user-images.githubusercontent.com/13703523/171992305-8176dcc8-f3c2-4095-9dc1-ceff201eda0d.png)

Request header:
![image](https://user-images.githubusercontent.com/13703523/171992327-c141e8cd-67e4-4709-bde6-0983aba5500a.png)

**Comment by schmidtc63** [comment]
> 

Try it with a non-custom header, as the OP indicated. content-type, user-agent, etc. Does it still work?

**Comment by artze** [comment]
@schmidtc63 
Tried it with the same setup mentioned [here](https://github.com/axios/axios/issues/4686#issuecomment-1146572223) and it seems to be working for me too:

![image](https://user-images.githubusercontent.com/13703523/173053065-3d1cee88-cf85-435d-a561-7a54b8258618.png)
![image](https://user-images.githubusercontent.com/13703523/173053211-b3c770f1-481b-46ec-a8e5-c5ed1b9edbf3.png)

**Comment by AkifumiSato** [comment]
Thanks, this issue is closed.
