### ISSUE TITLE
new toFormData feature not working when content-type is overwritten via config parameter

### ISSUE THREAD

**Issue by plehnen** [axios/axios#4688]
#### Describe the bug
When the content type is set via .create() and overwritten in the config of .post(), the object is not converted to FormData.

#### To Reproduce

```js
const apiClientInstance: AxiosInstance = axios.create({
  headers: {
    'Content-type': 'application/json',
  },
});

apiClientInstance
     .post(url, payload, {
       headers: {
         'Content-Type': 'multipart/form-data',
       },
     });

```

#### Expected behavior
The object should convert fo FormData.

#### Environment
 - Axios Version [0.27.2]

**Comment by DigitalBrainJS** [comment]
It works, but you must use the same case for the `Content-Type` header in your config - `Content-type` != `Content-Type`.
The current Axios version does not have proper custom header normalization.

**Comment by bryce0516** [comment]
in 26.1. I just set config.header like this 
```
          config.headers = {
            "Access-Control-Allow-Origin": somthing,,
            "X-AUTH-TOKEN":  somthing,
          };
```

actual sent data is 
```
          config.headers = {
            "Access-Control-Allow-Origin": somthing,,
            "X-AUTH-TOKEN":  somthing,
            "Content-type":  application-json <--- automaticly overriding 
          };
```
that's problem to me
