### ISSUE TITLE
CSS Depreciation warning when building with Vite

### ISSUE THREAD

**Issue by lllopo** [axios/axios#4689]
#### Describe the bug
With the latest Axios version I'm getting this in my Vite build :

```
\node_modules\axios\lib\helpers\spread.js[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
292|    background-size: contain;
293|    border: 1px solid rgba(0, 0, 0, 0.25);
294|    appearance: none;
   |       ^
295|    color-adjust: exact;
296|  }

\node_modules\axios\lib\helpers\normalizeHeaderName.js[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
276|    background-size: contain;
277|    border: 1px solid rgba(0, 0, 0, 0.25);
278|    appearance: none;
   |          ^
279|    color-adjust: exact;
280|  }
```

#### Environment
 - Axios Version : 0.27.2
 - Node.js Version : 18.0.0
 - Vite : 2.9.8

**Comment by lllopo** [comment]
Then I'm living you on your own. The issue is described well enough. Check it if you want. Super restrictive bots are a waste of time for me.

**Comment by jasonsaayman** [comment]
This has nothing to do with axios the error is comming from your CSS: `color-adjust: exact;` is where the deprication error comes from.

**Comment by lllopo** [comment]
@jasonsaayman Yeah, I feel a bit guilty mow :-). Should've checked better. Still - it is not from my code either. It comes from Bootstrap 5 CSS. Why it is reported in `\node_modules\axios\lib\helpers\spread.js` is beyond me.
