### ISSUE TITLE
Intermittent ECONNRESET on Linux but not on Windows

### ISSUE THREAD

**Issue by hardysabs2** [axios/axios#4691]
#### Describe the issue
I intermittently get ECONNRESET on requests to a particular server. On the face of it this is a server side issue, "the other side of the TCP conversation abruptly closed its end". However this does not happen when running the code locally under Windows only when running it in the deployment on Linux. Same code, same requests, same request endpoints, same credentials (header content) (node different 14.18 local - 14.19 Linux). I don't think it's speed - I added a pause before each requests for this.

Does anyone have experience of this?

#### Example Code
Code snippet to illustrate your question

```js
// Unique situation - really looking for others with similar experience.
```

#### Expected behavior, if applicable
No difference running locally under windows and under linux.

#### Environment
 - Axios Version 0.21.4
 - Adapter Not known
 - Browser N/A
 - Browser Version N/A
 - Node.js Version 14.19
 - OS: Red Hat 7.9 (Maipo) - Windows 10 Pro x64
 - Additional Library Versions - None

#### Additional context/Screenshots
None.

**Comment by tacohitbox** [comment]
Same issue with Axios 0.27.2 on Debian 20, anybody have a temporary fix
