### ISSUE TITLE
Android axios doesnot upload images using expo react native

### ISSUE THREAD

**Issue by shaoor1994** [axios/axios#4697]
Platform:android

#### Describe the issue
I am trying to upload image to a mongodb using expo react native using expo image picker but it returns with syntax error as it shows result in console but doesnot upload to server however it works fine with Post man

#### Example Code
```
`
axios
.post(
 // `http://${
   // Platform.OS === "android" ? "192.168.88.45" : "localhost"
  //}:4040/pets/addpets`,
  `http://192.168.88.45:4040/pets/addpets `,
 { headers: {
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
 }},
  formData
)
.then(({ data }) => {
  console.log(data);
})
.catch((err) => {
  console.error(err.toJSON());
 
})
.finally(() => {
  this.setState({
    name: "",
    title: "",
    contact: "",
    price: "",
    description: "",
    selectedcat: "",
    selectedcity: "",
    imgforsell: "",
  });
});
`

```

#### Environment
 - Axios Version [0.27.2]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [16.14.2]
 - OS: [Windows 10 10.0.22000]
 - Additional Library Versions [React native 0.64.3]

#### Additional context/Screenshots
It works fine with post man but keep on giving error using frontend I also tried to degrade to axios 0.22.0 but it does not make any difference

**Comment by DigitalBrainJS** [comment]
1) Wrong parameters order [axios.post(url[, data[, config]])](https://github.com/axios/axios#axiosposturl-data-config) 
2) You should learn about `application/x-www-form-urlencoded` ([URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)) and `multipart/form-data` ([FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData)); 

https://github.com/axios/axios#-automatic-serialization
https://codesandbox.io/s/axios-post-form-m55p99?file=/src/index.js
