### ISSUE TITLE
How  to invoke finally block

### ISSUE THREAD

**Issue by imlison** [axios/axios#4705]
#### Describe the issue
Since  my server always return 200 status code and put error code into response body, and i want to hide all non-2xx code from caller, so i do it in interceptor as below, but the `finally` will not be invoked when error code is not 2xx. How to fix  it

#### Example Code
```js
http.interceptors.response.use(
    response => {
        const res = response.data
        const code = res["code"]
        const message = res["message"]
        const payload = res["data"]
        if (code >= 200 && code < 300) {
            return Promise.resolve(payload)
        } else {
            const msg = `[${code}] ${message}`
            ElNotification({ type: "warning", message: msg})
            return new Promise(()=>{}) // so the caller doesn't need to catch
        }
    }, error => {
        ElMessage({message: error, type: "error", grouping: true})
        return Promise.reject(error)
    }
)
```

```js
let loading = true
axios.get("/load").then(data => {
    // do something
    }).finally(() => {
        loading = false
    }) 
```

#### Environment
 - Axios Version [0.27.2]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Edge]
 - Browser Version [101]
 - OS: [Win10]
 - Additional Library Versions [Vue3]

Thanks a lot

**Comment by artze** [comment]
Hi @imlison 

Just a quick glance on your code: when your status code is _not_ 2xx, your `new Promise()` never resolves/rejects, and so, does not invoke `finally`. You could try the following:

```
http.interceptors.response.use(
    response => {
        const res = response.data
        const code = res["code"]
        const message = res["message"]
        const payload = res["data"]
        if (code >= 200 && code < 300) {
            return Promise.resolve(payload)
        } else {
            const msg = `[${code}] ${message}`
            ElNotification({ type: "warning", message: msg})
            
            // Using resolve instead of reject b/c you mentioned that you don't want to catch
            return Promise.resolve();
        }
    }, error => {
        ElMessage({message: error, type: "error", grouping: true})
        return Promise.reject(error)
    }
)
```

Btw, your question is about the implementation of Promise, and not an issue specific to Axios.

**Comment by imlison** [comment]
> 

Thanks for your reply.
 Yes, it works as expected but will raise an uncaught exception in console if using Promise.reject(). Isn't there a better way?

**Comment by artze** [comment]
@imlison You need to add a `catch` block in your following code. 

```
let loading = true
axios.get("/load").then(data => {
    // do something
    }).finally(() => {
        loading = false
    }) 
```

This `catch` block is also needed to handle your response interceptor errors (your `Promise.reject` in your interceptor error callback in your original code). I'm mentioning this because you can't run away from _not_ having a `catch` block.

**Comment by imlison** [comment]
@artze It seems that I have to add `catch` block in every http request, although I don't need to care about any `reject callback`(just displaying an error message on network error and warning message on api error, which can be done inside response interceptor in my cases). 
Anyway, thanks.

**Comment by artze** [comment]
Hi @imlison Could you help to close this issue?
