### ISSUE TITLE
occured problem to download multiple same files at the same time

### ISSUE THREAD

**Issue by sdg9670** [axios/axios#4706]
#### Describe the bug
I used chrome browser.
I tried to download same file on each multiple tab of browser.
I could download two files at the same time but I couldn't download more than three file.
and I got this error
```
Error: Network Error
    at createError (createError.js:16:15)
    at XMLHttpRequest.handleError (xhr.js:99:14)
```
I think this error was occured on browser and I wonder why error was occured.

#### To Reproduce

```js
axios.create({
    baseURL: url,
    withCredentials: true,
    responseType: 'blob',
  });

axios.get(~~);
```

#### Environment
 - Axios Version 0.27.2
 - Adapter [e.g. XHR/HTTP]
 - Browser Chrome
 - Node.js Version 14
 - OS: windows 10

**Comment by gdutwyg** [comment]
hello，how did you solve  this problem?
