### ISSUE TITLE
Upload Image using 'multipart/form-data' doesnt work with Node.js/Express/Multer for version 0.27.0 works fine with version 0.20.0

### ISSUE THREAD

**Issue by Maverick23** [axios/axios#4707]
#### Describe the bug
When trying to upload image on the server (Node.js, Express and Multer) by sending image (headers : multipart-form-data) we get back server error. The reason for server error seems that the data received at the server end from axios is not as expected.

#### To Reproduce
A simple image upload leads to this . (sharing the relevant code below , using Reactjs framework and making request from FrontEnd)

      const config = {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      };
      /*formData is an instance of FormData and has image appended to it */
      const { data } = await axios.post("/api/upload", formData, config);

#### Expected behavior
Image should get uploaded . The above works fine with version 0.20.0 after downgrading to previous version.

#### Environment
 - Axios Version [e.g. 0.27.0]

**Comment by DigitalBrainJS** [comment]
> Axios Version [e.g. 0.27.0]

Use v0.27.2 where a regression bug with sending FormData has been fixed.
@jasonsaayman Maybe we should mark the versions with the FormData bug as deprecated with `npm deprecate <package-name>@<version> "msg"` in the npm repository? At least 0.27.0 and 0.27.1...

**Comment by jasonsaayman** [comment]
Yeah sure I will do :)

**Comment by jasonsaayman** [comment]
Done, and some pre-release and betas have been deprecated too
