### ISSUE TITLE
"Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream" when making POST request with `Axios` instance

### ISSUE THREAD

**Issue by DetachHead** [axios/axios#4710]
#### Describe the bug
when making a `POST` request with an instance of `Axios` and a js object as the body, the following error occurs:

> AxiosError: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
const axios = require('axios')
const axiosInstance = new axios.Axios({})

;(async () => {
    await axios.post('https://google.com', {}) // no error
    await axiosInstance.post('https://google.com', {}) // AxiosError: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream
})()
```

#### Expected behavior
no error, as axios should automatically convert the object to `application/json` like it does for the `AxiosStatic` instance

#### Environment
 - Axios Version 0.27.2
 - Adapter idk
 - Browser n/a
 - Browser Version n/a
 - Node.js Version 18.0.0
 - OS: windows 10 20H2

#### workaround
```js
await axiosInstance.post('https://google.com', undefined, {data: {}})
```

**Comment by merlindru** [comment]
Can confirm!  getting this with `0.27.2`

**Comment by DigitalBrainJS** [comment]
You create Axios with no default configuration, including default request and response transformers. This is quite expected behavior. Define your own implementation of transformers, or create an instance with the default configuration applied using the `axios.create` factory.

**Comment by eheimburg** [comment]
This continues to be a problem for many developers (just try googling for that error message). Instead of saying it's "quite expected behavior", maybe add a useful error message to handle this *very common* scenario. For instance, it could say "BTW there are no converters installed. If you want the standard converts, create your object via axios.create()". It would take one or two minutes to code, and people wouldn't be so frustrated.

In any case, I'm still stuck on this error because of how insufficient your documentation is. I am using TypeScript, and I am creating a new Axios instance via `new Axios()` because that's the only obvious way to create one. If there's some magical voodoo you want me to use to create an Axios object with standard behavior, *please consider telling people what it is*.

**Comment by Qwedir** [comment]
@eheimburg had the same problem.
Here how I solve it:

````ts
import axios, { Axios } from 'axios';

export class MicroserviceCallerService extends Axios {
  constructor(baseUrl: string) {
    super({ ...axios.defaults, baseURL: baseUrl });
  }
}
````

**Comment by iyarsius** [comment]
@Qwedir i had some trouble using this in typescript, this one worked for me

````ts
import axios, { Axios, AxiosRequestConfig } from 'axios';

export class MyAxios extends Axios {
  constructor(props: AxiosRequestConfig) {
    super({
      transformRequest: axios.defaults.transformRequest,
      transformResponse: axios.defaults.transformResponse,
      ...config,
    });
  }
}
```

**Comment by gbersac** [comment]
I'm using 1.3.5 and I still have the issue. I don't know how to solve it. The issue only appear when I'm trying to use FormData.

```typescript
const formData = new FormData()
formData.append("nature", "signable_document")
axios.post(`${apiBaseUrlV3}/v3/signature_requests/${procedureId}/documents`, formData, {headers:{"content-type": "multipart/form-data"})
```

**Comment by tlikakur** [comment]
> For NestJS service, you can instance and rewrite all methods. This is a good pattern following dependency inversion. In the future, if you need to replace Axios, you can reimplement the service, and all will be fine.
> 
> import { Inject, Injectable } from '@nestjs/common';
> import axios, { AxiosInstance, AxiosRequestConfig } from 'axios';
> import { HTTP_OPTIONS } from '../contants';
> 
> @Injectable()
> export class HttpService {
>   instance: AxiosInstance;
> 
>   constructor(@Inject(HTTP_OPTIONS) options: AxiosRequestConfig) {
>     this.instance = axios.create(options);
>   }
> 
>   post(url: string, data?: any, config?: AxiosRequestConfig) {
>     return this.instance.post(url, data, config);
>   }
> }

For future readers - If aiming for dependency inversion, then make sure to hide the implementation details (avoid exposing Axios-related types and interfaces).
