### ISSUE TITLE
No preflight

### ISSUE THREAD

**Issue by MattiasMartens** [axios/axios#4712]
#### Describe the bug

When running on a server hosted on localhost using HTTP, Axios does not send preflight requests contacting a different server hosted on localhost, even though this means the request will fail for violating CORS policy.

#### To Reproduce

On server that runs on http://localhost:6001 :
```js
  express.options("/*", function (req, res) {
    const {origin} = req.headers
    if (config.ALLOWED_ORIGINS.includes(origin)) {
      res.setHeader('Access-Control-Allow-Origin', origin);
    }
  })

  express.post("/fetchSchema", function (req, res) {
    res.pipe(fs.createReadStream('schema.yml'))
  })
```

Within app that is served from a live-reload server (built with Vue CLI) listening on http://localhost:8081:

```js
export async function fetchSchema() {
  const response = await axios.post(
    `http://localhost:6001/fetchSchema`
  )
  return response
}
```

#### Expected behavior

Axios should send a preflight OPTIONS request here so the request can be served properly.

#### Environment
 - Axios Version: 0.27.2
 - Adapter: HTTP
 - Browser: Chrome
 - Browser Version: 101.0.4951.54
 - Node.js Version: 18.1.0
 - OS: OSX 12.2.1
 - Additional Library Versions: @vue/cli-service: 5.0.0-rc.2; vue: 3.0.0

#### Additional context/Screenshots

End result (notice the lack of a preflight OPTIONS request):

<img width="1100" alt="Screen Shot 2022-05-13 at 1 28 16 PM" src="https://user-images.githubusercontent.com/33037520/168384697-c84e8848-5dbe-4379-9251-423086c20c33.png">

**Comment by tlindsay42** [comment]
Same for me with axios 0.27.2 and node 18.1.0, but with webpack 5.74.0, and able to reproduce with Chrome, Firefox, and Edge. 

Also found an older report of this in StackOverflow: https://stackoverflow.com/questions/69879306/how-to-send-preflight-request-from-axios-of-reactjs

**Comment by JamieShelley** [comment]
Can confirm this is still happening
<img width="617" alt="image" src="https://github.com/axios/axios/assets/10584757/93b8b402-a2e1-41b9-a872-92951f4f81d6">

**Comment by TechWizard9999** [comment]
😊 "I'd be delighted to work on this issue,@mattiad Could you please assign it to me?"

**Comment by jub0bs** [comment]
@MattiasMartens Your request is so-called [_simple_](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests). As such, it doesn't give rise to a preflight request.

**Comment by jub0bs** [comment]
@MattiasMartens If I understand your code correctly, you're only including the `Access-Control-Allow-Origin` header in responses to `OPTIONS` requests. That cannot work if for client that send `POST` requests; that header will need to be present in their responses too for things to work properly. Anyway, you're almost always better off using an existing middleware (Express.js has [one](https://expressjs.com/en/resources/middleware/cors.html); use it) than re-implementing CORS "by hand".
