### ISSUE TITLE
Can't override host header when overriding the url

### ISSUE THREAD

**Issue by ohmaseclaro** [axios/axios#4723]
```
async function useCustomDNSResolver(config: AxiosRequestConfig) {
  const { host } = parseURL(config.url);
  config.url = await DNSHelper.resolveUrl(config.url); // resolves url to ip
  config.headers.host = host; // put original hostname in Host header - THIS GETS REPLACED WITH IP FROM DNS RESOLUTION
}

export const axiosProvider: Provider = {
  provide: 'axios',
  useFactory: async (proxyService: ProxyService) => {
    const axiosClient = axios.create();
    axiosClient.interceptors.request.use(async config => {
      await useCustomDNSResolver(config);
      return config;
    });
    return axiosClient;
  },
  inject: [ProxyService],
}
```

I have this code and even though I replace the Host header of a request, it's always set back to the url's host (and I want to make a call to the IP url, but keep the actual URL in host)

data in request:
```
    url: 'https://13.227.97.125/_CustId_689966903',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      host: '13.227.97.125', // it should be the URL in here
      'User-Agent': 'axios/0.21.4'
    },
   ```

if I set the url to some other random header, I see the value in headers. only host is overwritten

**Comment by jolindroth** [comment]
Probably related to this: https://github.com/axios/axios/issues/2171
Browsers do not seem to allow overriding the host header.

**Comment by TrumanRu** [comment]
I use Axios in Node.js (Nest.js) for communicate with Keycloak 16.+
Keycloak version 16 don't like some requests with header 'Host', it fails some requests (for example - 'userinfo') with this header and works fine without it.
