### ISSUE TITLE
Automatic conversion of a string to a number and rounding

### ISSUE THREAD

**Issue by Gusarovv** [axios/axios#4726]
The server stores the id as a string. The length is 18 characters.
When requested via axios, the string is automatically converted to a number and rounded.

DB: '976233959434354698'
Postman response: '976233959434354698'
Axios response: 976233959434354700

 - Axios Version 0.27.2
 - Adapter HTTP
 - Node.js Version 16.12

**Comment by DigitalBrainJS** [comment]
set `config.transitional.forcedJSONParsing= false`;
