### ISSUE TITLE
postForm fails with "source.on is not a function" when using Buffer or Uint8Array in Node 18

### ISSUE THREAD

**Issue by smares** [axios/axios#4727]
#### Describe the issue
Passing Uint8Array or Buffer to postForm results in "source.on is not a function" exception.

#### Example Code
```js
const data = Uint8Array.from([1, 2, 3])
axios.postForm('http://some.url', { data })

// or

const data = Uint8Array.from([1, 2, 3])
axios.postForm('http://some.url', { data: Buffer.from(data) })
```

#### Expected behavior, if applicable
axios should POST a field "data" with the content of the Uint8Array / Buffer

#### Environment
 - Axios Version 0.27.2
 - Node.js Version 18.2.0
 - OS: Windows 11

#### Additional context/Screenshots
Code is compiled from TypeScript using typescript 4.6.4 and a tsconfig.json that extends @tsconfig/node18/tsconfig.json

I am trying to upload the PDF output of puppeteer.

What am I doing wrong?

**Comment by smares** [comment]
So I was able to debug so far that what crashes is delayed-stream `source.on('error', function() {});` which is used by combined-stream which is used by form-data. Question is still: Am I doing something wrong? Issue in form-data?

**Comment by DigitalBrainJS** [comment]
I don't seem to be able to reproduce the error at the moment

```js
import axios from 'axios';

console.log(`Axios: v${axios.VERSION}`);

await axios.postForm('https://httpbin.org/post', {
  data: Uint8Array.from([1, 2, 3])
}).then(({data: {form, headers}})=> console.log({form, headers}), console.warn);


await axios.postForm('https://httpbin.org/post', {
  data: Buffer.from(Uint8Array.from([1, 2, 3]))
}).then(({data: {form, headers}})=> console.log({form, headers}), console.warn);
```

```js
Axios: v0.27.2
{
  form: { data: '\x01\x02\x03' },
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Length': '202',
    'Content-Type': 'multipart/form-data; boundary=--------------------------299796871024925736357512',
    Host: 'httpbin.org',
    'User-Agent': 'axios/0.27.2',
    'X-Amzn-Trace-Id': 'Root=1-62851f35-4355336a4dbd8c9f21ea38b8'
  }
}
{
  form: { data: '\x01\x02\x03' },
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Length': '202',
    'Content-Type': 'multipart/form-data; boundary=--------------------------071752372898572766064691',
    Host: 'httpbin.org',
    'User-Agent': 'axios/0.27.2',
    'X-Amzn-Trace-Id': 'Root=1-62851f36-5e2ba27d392d30ff0f90e34d'
  }
}

Process finished with exit code 0
```

**Comment by smares** [comment]
Which Node version? I just downgraded to 16.5.0 LTS and everything works. 18.1.0 and 18.2.0 produce my aforementioned error.

**Comment by DigitalBrainJS** [comment]
v16.10.0

**Comment by smares** [comment]
Thanks for checking. So it affects only 18 and maybe 17.

**Comment by DigitalBrainJS** [comment]
Yes, I just got the same error on v18.
