### ISSUE TITLE
FormData cannot be correclty sent when call is made from a web worker

### ISSUE THREAD

**Issue by stillgbx** [axios/axios#4733]
#### Describe the bug
FormData cannot be correclty sent when call is made from a web worker.
`Content-Type` request header seems incorrect because it's not deleted by axios to let the browser set the header.
`isStandardBrowserEnv` does not detect that the call is made from a web worker.  

Changing `isStandardBrowserEnv` doesn't seem enough because other(s) part(s) of the code _(like in `isURLSameOrigin.js`)_ rely on the result to use `document` _(which is therefore not available in a web worker)_.

#### To Reproduce
Send FormData from a Web Worker.

#### Expected behavior
FormData should be sent correctly _(like in v 0.26.1)_.

#### Environment
 - Axios Version >= 0.27.0
 - Browser : all
 - OS : all

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/15780237/169306633-bf504e55-b57b-4fb1-a814-780be899c054.png)  

![image](https://user-images.githubusercontent.com/15780237/169299203-e5c9e186-2a46-4e5d-8569-aa81e800966e.png)

**Comment by DigitalBrainJS** [comment]
Fixed in #5139
