### ISSUE TITLE
Axios instance is not a function when I run tests with jest

### ISSUE THREAD

**Issue by SimaoJuliao** [axios/axios#4740]
I use axios to communicate with the API and it works, I can get the data I want through the API. But now I'm doing unit tests in the communication part of the API and I'm using jest, but when I run the unit tests it gives me an error saying that the axios instance is not a function.

#### Serviçe File - api.ts

    import axios from "axios";
    
    export const axiosGetTest = axios.create({
      baseURL: "https://6260219792df0bc0f3402603.mockapi.io/",
      headers: {},
    });
    
    export const fetchUsers = async () => {   
    
        const response = await axiosGetTest({
          method: 'GET',
          url: 'Users',
        });
    
        console.log(response);
        return response;
    };

#### test File - teste.test.ts

    const axios = require('axios');
    import { fetchUsers } from "./api";
    
    jest.mock("axios");
    
    describe("fetchUsers", () => {
      describe("when API call is successful", () => {
        it("should return users list", async () => {
          const users = [
            {
              name: "name 1",
              email: "email 1",
              id: "1"
            },
            {
              name: "name 2",
              email: "email 2",
              id: "2"
            }
          ];
    
          axios.get = jest.fn().mockResolvedValue(users);
          
          const result = await fetchUsers();
          // console.log(result);
          
          expect(axios.get).toHaveBeenCalledWith('Users');
          expect(result).toEqual(users);
        });
      });
    });

#### Error:

    fetchUsers › when API call is successful › should return users list

    TypeError: exports.axiosGetTest is not a function

      18 |     // return await axios.get(`${BASE_URL}users`);
      19 | 
    > 20 |     const response = await axiosGetTest({
         |                            ^
      21 |       method: 'GET',
      22 |       url: 'Users',
      23 |     });

Can anyone help me?

**Comment by smares** [comment]
I am not familiar with Jest since I just started with unit tests myself and am using Vitest, but since you are mocking axios, what does `axios.create()` return? Your `axiosGetTest` is basically the return value of `axios.create`.

**Comment by SimaoJuliao** [comment]
> 

The ```axios.create()``` gives return a ```AxiosInstance```

**Comment by smares** [comment]
Even when axios is mocked? Did you verify?

**Comment by isra2021** [comment]
did you solve it?

**Comment by ricardo17coelho** [comment]
I also have this issue with Vitest.

Basically i created an "helper" like:


```
const createAxiosInstance = (axios, config) => {
  return axios.create({
    ...config
  });
};
```

And i use with to create axios instances.
