### ISSUE TITLE
Why can't Axios@0.27.1 upload file？

### ISSUE THREAD

**Issue by bzdx** [axios/axios#4744]
Today，I can't upload files with axios, but it has been normal before, the same code here:

```
uploadImg() {
      let img = document.getElementById('edit-uploader').files[0]
      if (!img) return

      let formData = new FormData()
      formData.append('file', img)
      axios.post(this.uploadImgPath, formData).then(res => {
        this.form.localUrl = res.data.data
      }).catch(e => {
        console.error(e)
      })
}
```

Finally, it was found that it was caused by different versions of Axios.
Because it is normal in version 0.26.1.
However, in version 0.27.1, I tried to upload file with any method, but there didn't work.
How should I upload files in the new version(0.27.1)?

**Comment by DigitalBrainJS** [comment]
> How should I upload files in the new version(0.27.1)?

The current version is **0.27.2**.
0.27.0 and 0.27.1 are marked in the npm registry as deprecated due to the FormData bug. So don't use them.
