### ISSUE TITLE
Upgrading from 0.24.0 -> 0.27.2 causes RN app to crash with no error

### ISSUE THREAD

**Issue by KrisLau** [axios/axios#4749]
#### Describe the issue
Upgrading from 0.24.0 -> 0.27.2  causes RN app to crash on startup with no error message in the console nor in Sentry. 

I also made sure to downgrade the package and re-run to ensure that it was caused by axios. After downgrading axios, it was still crashing so I needed to delete my node_modules folder, reset my metro cache and re-run yarn to get it working again. I tried re-upgrading axios to 0.27.2 and following the same steps as I did when I downgraded and it was still causing the app to crash

#### Example Code
N/A

#### Expected behavior, if applicable
App to start and axios to work like usual

#### Environment
 - Axios Version v0.27.2
 - Adapter N/A
 - Browser N/A (React Native) 
 - Browser Version N/A
 - Node.js Version v16.15.0
 - OS: Android 11
 - Additional Library Versions React Native 0.64.2

#### Additional context/Screenshots
Just trying to upgrade my packages to keep up. Not sure if this is relevant but these are the packages I haven't updated yet:
![image](https://user-images.githubusercontent.com/46275463/170772100-33627d70-38c6-45a5-a719-e2ea261b5ddb.png)

**Comment by DigitalBrainJS** [comment]
These versions differ not only in the patch number, so it is quite expected that old code written to work in 0.24.x may not work in 0.27.x, as they have some breaking changes.

**Comment by KrisLau** [comment]
@DigitalBrainJS Not 100% sure but I don't think it's a code problem since it crashes the app on startup. Like I hit run, the app completes bundling, a blank screen, then boom crash.

**Comment by KrisLau** [comment]
Ok really strange but after updating it to 0.26.1 with no code changes, I updated it to 0.27.2 and that worked? I'm really confused as to why that works but I'll close the issue haha

**Comment by lorand-horvath** [comment]
@KrisLau You probably had some transient dependencies that were outdated... Downgrading to 0.26.1 and then upgrading to 0.27.2 you basically reinstalled the entire package, including dependencies of dependencies. I've been in that situation and it's honestly quite difficult to track down where the problem was.

**Comment by KrisLau** [comment]
@lorand-horvath Ahh ok that makes sense, thank you for shedding some light on why that worked! I'll keep that in mind for next time
