### ISSUE TITLE
In Postman it works, but through axios it throws error 400

### ISSUE THREAD

**Issue by jotilohana** [axios/axios#4757]
const auth = {
    email: email,
    password: password,
    roll: SyncStorage.get('Role'),
  }; 

 const PostAuth = () => {
    axios({
      method: 'post',
      url: 'https://myhealthappserver.herokuapp.com/register',
      withCredentials: true,
      crossdomain: true,
      data: auth,
      headers: {},
    })
      .then(function (response) {
        console.log(response);
        navigation.navigate('Home');
      })
      .catch(function (error) {
        console.log(error.message);
        // console.log('hello');
      });
  };

In console the error throws: LOG  Request failed with status code 400

**Comment by smares** [comment]
Is `roll` a typo in the payload?

**Comment by jotilohana** [comment]
@smares yes

**Comment by jotilohana** [comment]
@smares role is a string value which is stored in local storage

**Comment by WillianAgostini** [comment]
Hi @jotilohana 
If it work's on Postman, please [generate client code](https://learning.postman.com/docs/sending-requests/generate-code-snippets/) with Postman and post here the generated code.
