### ISSUE TITLE
axios get not working in mobile user agent on some case

### ISSUE THREAD

**Issue by karsiong** [axios/axios#4760]
I saw previous that some one reach this issue, then the discussion 
- axios blame cors everywhere not puting the header
- cors everywhere blame axios

After i trying this issue, this is axios bug for sure, if anyone reach this issue just use XHR request that no issue with cors everywhere.
example code:
```
      var xhr = new XMLHttpRequest();
      xhr.open("GET", "YOUR URL");

      xhr.setRequestHeader("Accept", "application/json");

      xhr.onreadystatechange = function () {
         if (xhr.readyState === 4) {
            console.log(xhr.status);
            console.log(xhr.responseText);
         }};

      xhr.send();
```

**Comment by TechWizard9999** [comment]
😊 "I'd be delighted to work on this issue, @karsiong ! Could you please assign it to me?"
