### ISSUE TITLE
Memory Leak when using Axios Retry

### ISSUE THREAD

**Issue by AllanOricil** [axios/axios#4763]
#### Describe the bug

I have a huge json file which I read using streams. I read this json file using JSONStream module.  I do it like so

![image](https://user-images.githubusercontent.com/55927613/171444550-ee439da3-94ba-478d-8c2b-dd93a17dc1b5.png)

When JSONStream emits a json object axios posts this object to a webservice. There is no infinite loop anywhere, but axios is not releasing memory after finishing the request. In the image below you can see that after few minutes running, my node app reaches 12gb of memory! What is the problem?

![image](https://user-images.githubusercontent.com/55927613/171445046-44c37477-ed73-4308-a37a-1d47a99d3fdb.png)

#### To Reproduce
You can use the following code snippet to verify this issue

```js
const fs = require("fs");
const path = require("path");
const JSONStream = require('JSONStream');
const axios = require('axios');
const axiosRetry = require('axios-retry');
const axiosRateLimit = require('axios-rate-limit');
const es = require('event-stream');
const winston = require('winston');

const logger = winston.createLogger({
	format: winston.format.combine(
		winston.format.timestamp({
            format: 'YYYY-MM-DD HH:mm:ss',
        }),
		winston.format.printf((info) =>
            JSON.stringify({
                timestamp: info.timestamp,
                message: info.message
            })
        )
    ),
    transports: [
		new winston.transports.File({filename: path.resolve(__dirname, 'errors.log'), level: 'error'}),
		new winston.transports.File({filename: path.resolve(__dirname, 'infos.log'), level:'info'})
    ]
});


axiosRetry(axios, { retries: 3, retryDelay: axiosRetry.exponentialDelay });
const http = axiosRateLimit(axios, { maxRequests: 20, perMilliseconds: 200 })

const postEvent = (uri, event, apiKey) => {
    return http.post(uri, event, {
        headers: {
            ...(apiKey && { 'api-key': apiKey }),
            'Content-Type': 'application/json'
        },
		maxRedirects: 0
    });
};

async function main(){

	const getStream = () => {
		const stream = fs.createReadStream(path.resolve('.', 'events.json'), { encoding: "utf8" });
		const parser = JSONStream.parse("*");
		return stream.pipe(parser);
	};

	getStream()
	.pipe(es.mapSync(async function (data){
		logger.info(data._id.$oid);
		try{
			await postEvent(data);
		}catch(e){
			logger.error(e)
		}
	}))
}

main();

```

#### Expected behavior

Memory should be released after request promise has been fullfiled.

#### Environment
 - Axios Version  0.27.2
 - Node.js Version 16
 - OS: Ubuntu 20
 - JSONStream: 1.3.5

**Comment by DigitalBrainJS** [comment]
Does the problem still occur when you set `maxRedirects` to 0?

**Comment by AllanOricil** [comment]
@DigitalBrainJS I know it is caused somewhere by axios because when I remove the axios call from my code, no memory leak happens. For instance, when I do this

````js
...

async function main(){
	const getStream = () => {
		const stream = fs.createReadStream(path.resolve('.', 'events.json'), { encoding: "utf8" });
		const parser = JSONStream.parse("*");
		return stream.pipe(parser);
	};

	getStream()
	.pipe(es.mapSync(async function (data){
		logger.info(data._id.$oid);
	}))
}

````

**Comment by AllanOricil** [comment]
First I thought the issue was caused by not using async/await. But with and without it (discosidering performance issues) the memory leak problem still happens.

**Comment by DigitalBrainJS** [comment]
Without redirects enabled, I have no idea what is causing this problem (follow-redirects has a streams backpressure problem).
Try to replace Axios with [dev/null stream](https://github.com/thlorenz/dev-null) and limit its speed with https://github.com/alxhotel/speed-limiter or a similar library. Maybe your stream is not respecting the overflow/high watermark value of the stream buffer.

yourStream -> throttledStream -> devNullStream;

**Comment by AllanOricil** [comment]
@DigitalBrainJS I changed axios by the native experimental "fetch" from node 18, and the memory leak issue is gone.

![image](https://user-images.githubusercontent.com/55927613/171450202-4e9f7720-4099-43a9-8311-7a2c6f515cfb.png)

**Comment by AllanOricil** [comment]
@DigitalBrainJS what is this "pipeline helper" you mentioned? Could you give an example, or a link to a doc where I could read more about it

**Comment by DigitalBrainJS** [comment]
https://nodejs.org/api/stream.html#streampipelinestreams-callback

**Comment by AllanOricil** [comment]
> https://nodejs.org/api/stream.html#streampipelinestreams-callback

@DigitalBrainJS what are the performance gains using this chain object instead of .pipe? That doc page does not mention the differences
