### ISSUE TITLE
Connect timeout from custom Agent is not working

### ISSUE THREAD

**Issue by Spasfonx** [axios/axios#4768]
#### Describe the bug
When I use a custom `http.Agent` or `https.Agent` to handle connect timeout (I insist on the "connect timeout" and no the "request timeout") correctly, the agent timeout is not applied, the axios timeout is applied. 

#### To Reproduce
Here a notebook for reproduce the issue : https://runkit.com/spasfonx/axios-agent-connect-timeout-error-0-20-0

![image](https://user-images.githubusercontent.com/5750273/171656794-9ff7e4a3-8c8e-4095-b624-6d7157162c90.png)

With the bugged version, we see that the elasped time is >1000ms while the timeout should be 200ms.

#### Expected behavior
I expected to see the custom agent timeout applied for connect timeout. 

#### Environment
 - Axios Version [0.27.2]
 - Adapter [HTTP]
 - Node.js Version [16.15.0]
 - OS: [macOS Monterey 12.0]

#### Additional context/Screenshots
The bug seems to appear since `0.20.0` version, and still here in the last current version `0.27.2`. So the `0.19.2` work as expected. And the bug seems to come from `follow-redirects` (https://github.com/follow-redirects/follow-redirects/issues/186).

**Comment by Spasfonx** [comment]
Workaround: to fix the bug, we can add `maxRedirect: 0` option. 

```js
const myCustomAgent = new https.Agent({ timeout: 200 })

axios.get('https://google.com:81', { httpsAgent: myCustomAgent, maxRedirect: 0 })
```

That will force to use `https` from nodejs module instead of `https` from follow-redirects module and avoid the bug. 

**Watch out**, if you need to follow redirections this can be breaking for your application.

(See code: https://github.com/axios/axios/blob/v1.x/lib/adapters/http.js#L269)

**Comment by Spasfonx** [comment]
I see that you removed the `status:possible bug` label on this issue, this is not a bug anymore ? @jasonsaayman

**Comment by jasonsaayman** [comment]
No that is not the case I am working on re-classifying the backlog of issues

**Comment by Spasfonx** [comment]
Ok, have you some news on this ? Maybe planned for the v1 ?

**Comment by leejh3224** [comment]
Dirty quick fix for this issue would be to pin `follow-redirects` version that properly handles `httpAgent.timeout`.

I've tested several versions and found if I pin `follow-redirects` to `1.13.3`, it starts working as expected.

For anyone interested, please use `resolutions` property in package.json.

```json
"resolutions": {
    "follow-redirects": "1.13.3"
}
```

If you're using `yarn` or `pnpm`, it would work out of the box though you need [some extra work](https://www.npmjs.com/package/npm-force-resolutions) for `npm`.

**Comment by leejh3224** [comment]
For the time being, use `follow-redirects === 1.13.3`. 

You can pin the version using `resolutions` in package.json.

```json
  "resolutions": {
    "follow-redirects": "1.13.3"
 }
```

if you're using `yarn` or `pnpm`, it's good to go and for the case of `npm`, it need [some extra work](https://www.npmjs.com/package/npm-force-resolutions).

Then you can set `timeout` on your `httpAgent`/`httpsAgent`.
