### ISSUE TITLE
PR #3966 status ?

### ISSUE THREAD

**Issue by leguilv** [axios/axios#4775]
Dear All,

Everything is stated in [PR #3966](https://github.com/axios/axios/pull/3966/files) (that was closed but I guess never merged) and the associated issues. Essentially, when an input stream is sent through a POST request, and an error occurs while streaming data (eg in an intermediate Transform stream or whatever), axios gets stuck. 

Is there any plan to fix it ?

Thanks

**Comment by jasonsaayman** [comment]
> Please note that changing .pipe to .on('data', ...) introduces some implicit changes: for example if stream is in readable.readableFlowing === false state, .pipe will resume the stream while adding .on('data', ...) won't

This was closed due it being stale and some issues on the PR, if you would like please create a new PR with these issues addressed.
