### ISSUE TITLE
Unsupported use of https Agent (pfx)

### ISSUE THREAD

**Issue by attilavarga96** [axios/axios#4778]
#### Describe the issue
I tried to use Axios with an https.Agent with pfx configuration.
Error messages: 

> [Axios Response]    ERROR MESSAGE: "unsupported" 

> Error - Error: unsupported - occurred while sending notification

It is occurring in every higher node version than 16.13.2.
With 16.13.2, it works.
I used for this example 17.8.0.
Maybe it is changed in the new node version how to use this feature. Is the Axios library ready to use this new solution?
If yes, how to use it?
https://nodejs.org/api/tls.html (Node.js v18.3.0 documentation)

#### Example Code

```js
const configuredHttpsAgent = new https.Agent({
  pfx: KEYFILE_CONTENT,
  passphrase: PASSPHRASE
});

const config = {
    method: 'post',
    url,
    headers,
    data: body,
    httpsAgent: configuredHttpsAgent
  };
  axios(config)
    .then((response) => {
      // successfully sent notification
    })
    .catch((error) => {
      req.logger.error(`Error - ${error} - occurred while sending notification`);
    });
```

#### Expected behavior, if applicable
It should send the request without any problem. Should not write the unsupported message.

#### Environment
 - Axios Version: 0.27.2
 - Node.js Version: Higher than 16.13.2
 - OS: Docker (for windows), node:17.8.0-alpine image

**Comment by AbimaelAndrade** [comment]
Hi @jasonsaayman, do you find any solution? I'm with the same problem.

**Comment by attilavarga96** [comment]
Hello, I found the solution. You have to use the NODE_OPTIONS=--openssl-legacy-provider env for your node.js project.

**Comment by phbragam** [comment]
> Hello, I found the solution. You have to use the NODE_OPTIONS=--openssl-legacy-provider env for your node.js project.

Same problem here. Do you remember how to do this configuration?

**Comment by attilavarga96** [comment]
The easiest way to set up this solution is that.
![image](https://github.com/axios/axios/assets/19992314/0847e656-e4d2-4966-99d9-cbd66a906c2c)
Set it up in your package.json script.

**Comment by shes-dev** [comment]
Thanks
