### ISSUE TITLE
Refresh tokens with axios interceptors

### ISSUE THREAD

**Issue by ScottTunstall** [axios/axios#4779]
Hi,

I have a React website that uses axios to contact a Web API (in C# 5). Authentication for the API uses Json Web Tokens and Refresh tokens.

Can you advise me of the patterns that should be used that, in case of an Axios Network Error (which is caused when the access token expires) how I can retrieve a refresh token without the error propagating to the script?

My source code is detailed in my SO question here:
https://stackoverflow.com/questions/72545106/access-and-refresh-tokens-with-axios-and-net-5-web-api/72545364

I can of course supply more if required.

Thanks in advance,
Scott

#### Expected behavior, if applicable
I would like any failing Axios "Network Error" calls , to automatically invoke the refresh token handler in my Web API, acquire a new Jwt token, and retry the call to the API that failed before with new token.

#### Environment
 - Axios Version: 0.21.0
 - Adapter [e.g. XHR/HTTP]
 - Browser Chromium - Edge & Chrome
 - Browser Version - both latest
 - Node.js Version [e.g. 13.0.1] - N/A
 - OS: Windows 10
 - Additional Library Versions:
  "dependencies": {
    "@azure/msal-browser": "^2.19.0",
    "@azure/msal-react": "^1.1.1",
    "@microsoft/applicationinsights-react-js": "^3.2.4",
    "@microsoft/applicationinsights-web": "^2.7.4",
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jwt-decode": "^3.1.0",
    "antd": "^4.11.2",
    "awesome-debounce-promise": "^2.1.0",
    "axios": "^0.21.0",
    "bootstrap": "^4.6.0",
    "env-cmd": "^10.1.0",
    "jquery": "^3.6.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "polly-js": "^1.8.3",
    "react": "^17.0.1",
    "react-bootbox": "^1.1.1",
    "react-bootstrap": "^1.4.3",
    "react-datepicker": "^3.4.1",
    "react-dom": "^17.0.1",
    "react-icons": "^4.1.0",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.0",
    "react-toastify": "^7.0.3",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "web-vitals": "^0.2.4",
    "webpack": "4.44.2"

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Viiprogrammer** [comment]
Try [this](https://thedutchlab.com/blog/using-axios-interceptors-for-refreshing-your-api-token)

**Comment by ScottTunstall** [comment]
> Try [this](https://thedutchlab.com/blog/using-axios-interceptors-for-refreshing-your-api-token)

Hi, the original approach was something like that (in fact, very much like that)  however error.response is **undefined** when our access token expires.

**Comment by Viiprogrammer** [comment]
can you show response /response code when token expired?
