### ISSUE TITLE
Fails to set content-type header Multipart/form-data and boundary  in react native

### ISSUE THREAD

**Issue by boma25** [axios/axios#4781]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

when making a multipart/formdata post request from react native the content-Type header is not set automatically, and when you manually set it the boundary is not added , had to downgrade to version 0.21.4 or make use of fetch api inother to solve this problem

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

#### Expected behavior

the header content-Type should be set automatically

#### Environment
 - Axios Version v 0.27.2
 - Node.js Version v17.9.0
 - OS: [ OSX 12.3.1]
 - Additional Library Versions [React Native v0.68.1, React  v17.0.2]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

it works perfectly with fetch and axios v 0.21.4

**Comment by arjun1194** [comment]
i have the same issue

**Comment by boma25** [comment]
> i have the same issue

this bug was caused by react-native debugger it modifies the request data when you turn on network inspect still looking for a fix tho but for now turning off network inspect does the trick

**Comment by arjun1194** [comment]
i still face the same problem in a release build

**Comment by Sunhat** [comment]
still exists

**Comment by Metre-Ray** [comment]
Facing similar issue
