### ISSUE TITLE
Login request works via POSTMAN but not via Axios

### ISSUE THREAD

**Issue by geoidesic** [axios/axios#4783]
#### Describe the issue
The problem I'm having is with session continuity. I have a VueJS front-end using Axios and a CakePHP back-end API. When I generate a login request via Axios or via Postman, the login is successful, the PHP session is generated and I get a successful response from the server. The difference however is that the POSTMAN response headers will contain the PHP session cookie, but the axios response headers will not, thus subsequent secure requests fail (because they do not have the cookie).

#### Example Code
I generated code from POSTMAN and used it for the axios request but it still does not work.
Here is the generated code:

```
var data = JSON.stringify({
  "email": "<redacted>",
  "password": "Password1234",
});

var config = {
  method: 'post',
  url: 'http://mnr-be:8888/api/people/login',
  headers: { 
    'Accept': 'application/json', 
    'Origin': 'http://mnr-fe:8080/', 
    'Referer': 'http://mnr-fe:8080/', 
    'Content-Type': 'application/json'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```

Here are the POSTMAN login request headers as reported by the back-end API:
```
Array
(
    [Accept] => Array
        (
            [0] => application/json
        )

    [Origin] => Array
        (
            [0] => http://mnr-fe:8080/
        )

    [Referer] => Array
        (
            [0] => http://mnr-fe:8080/
        )

    [Content-Type] => Array
        (
            [0] => application/json
        )

    [User-Agent] => Array
        (
            [0] => PostmanRuntime/7.29.0
        )

    [Cache-Control] => Array
        (
            [0] => no-cache
        )

    [Postman-Token] => Array
        (
            [0] => ecf4c149-5cd1-497d-b212-eb3650060429
        )

    [Host] => Array
        (
            [0] => mnr-be:8888
        )

    [Accept-Encoding] => Array
        (
            [0] => gzip, deflate, br
        )

    [Connection] => Array
        (
            [0] => keep-alive
        )

    [Content-Length] => Array
        (
            [0] => 148
        )

)
```
These are the response headers for the POSTMAN login request (from the API):
<img width="566" alt="Screenshot 2022-06-13 at 11 19 06" src="https://user-images.githubusercontent.com/4637995/173300285-2b941614-7bac-450f-b84a-550d34ffb557.png">

If I then make a subsequent secure POSTMAN request I get the following request headers (which you can see includes the PHP session cookie):
```
Array
(
    [Origin] => Array
        (
            [0] => http://mnr-fe:8080
        )

    [Accept] => Array
        (
            [0] => application/json
        )

    [User-Agent] => Array
        (
            [0] => PostmanRuntime/7.29.0
        )

    [Cache-Control] => Array
        (
            [0] => no-cache
        )

    [Postman-Token] => Array
        (
            [0] => 3cf8a2c0-1368-41b0-85fe-9d37a8ebeded
        )

    [Host] => Array
        (
            [0] => mnr-be:8888
        )

    [Accept-Encoding] => Array
        (
            [0] => gzip, deflate, br
        )

    [Connection] => Array
        (
            [0] => keep-alive
        )

    [Cookie] => Array
        (
            [0] => PHPSESSID=7ksmoiop6hmhe6bogbejlh6dad
        )

)
```

However, when I do the same via axios. Here are the login request headers:
```
Array
(
    [Host] => Array
        (
            [0] => mnr-be:8888
        )

    [Connection] => Array
        (
            [0] => keep-alive
        )

    [Accept] => Array
        (
            [0] => */*
        )

    [Access-Control-Request-Method] => Array
        (
            [0] => POST
        )

    [Access-Control-Request-Headers] => Array
        (
            [0] => content-type
        )

    [Origin] => Array
        (
            [0] => http://mnr-fe:8080
        )

    [User-Agent] => Array
        (
            [0] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
        )

    [Sec-Fetch-Mode] => Array
        (
            [0] => cors
        )

    [Referer] => Array
        (
            [0] => http://mnr-fe:8080/
        )

    [Accept-Encoding] => Array
        (
            [0] => gzip, deflate
        )

    [Accept-Language] => Array
        (
            [0] => en-GB,en-US;q=0.9,en;q=0.8
        )

)
```
And here are the response Headers from the Axios login request:
```
Request URL: http://mnr-be:8888/api/people/login
Request Method: POST
Status Code: 200 OK
Remote Address: [::1]:8888
Referrer Policy: strict-origin-when-cross-origin
HTTP/1.1 200 OK
Date: Mon, 13 Jun 2022 07:23:37 GMT
Server: Apache/2.4.46 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 PHP/7.4.21 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18
X-Powered-By: PHP/7.4.21
Set-Cookie: PHPSESSID=b7sjihm6sj1danj0n28hvhri1g; path=/; HttpOnly; SameSite=Lax
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Access-Control-Allow-Methods: POST, GET, PATCH, DELETE, OPTIONS
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, X-Auth-Token, X-CSRF-TOKEN
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: 
Access-Control-Max-Age: 300
Access-Control-Allow-Origin: http://mnr-fe:8080
Content-Length: 46
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 129
Content-Type: application/json
Host: mnr-be:8888
Origin: http://mnr-fe:8080
Referer: http://mnr-fe:8080/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
```
Where you can see that the PHP session cookie is returned. 
When I then make a subsequent axios request to a secure API end-point, these are the request headers received by the server:
```
Array
(
    [Host] => Array
        (
            [0] => mnr-be:8888
        )

    [Connection] => Array
        (
            [0] => keep-alive
        )

    [Accept] => Array
        (
            [0] => application/json
        )

    [User-Agent] => Array
        (
            [0] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
        )

    [Origin] => Array
        (
            [0] => http://mnr-fe:8080
        )

    [Referer] => Array
        (
            [0] => http://mnr-fe:8080/
        )

    [Accept-Encoding] => Array
        (
            [0] => gzip, deflate
        )

    [Accept-Language] => Array
        (
            [0] => en-GB,en-US;q=0.9,en;q=0.8
        )

)
```
... as you can see it does not contain the PHP session cookie. This is being sent with `{withCredentials: true}` in the axios config.

#### Expected behavior, if applicable
I'd expect the last request to have included the session cookie, otherwise it can't work.

#### Environment
 - Axios Version 0.27.2
 - Adapter HTTP
 - Browser Chrome
 - Browser Version 102.0.5005.115 (Official Build) (arm64)
 - Node.js Version N/A
 - VueJS v2
 - OS: OSX 12.4
 - Additional Library Versions VueJS / Quasar (using Axios as a boot file but it doesn't seem to matter what I use, same result).

#### Additional context/Screenshots
I'm also seeing these errors in the console when sending the Axios request:
```
xhr.js?e38e:125 Refused to set unsafe header "Origin"
xhr.js?e38e:125 Refused to set unsafe header "Referer"
```
However, I get the same behaviour described above even if I disable these headers in the Axios config.

**Comment by WillianAgostini** [comment]
Could you show that you do to first your first (login) request and second (subsequent) request? 
Are you using the same instance of axios request? 

So try creating an instance o axios and utilize only this instance for all requests.
```
const instance = axios.create({
  baseURL: 'https://some-domain.com/api/'
});

```

**Comment by geoidesic** [comment]
> Hi @geoidesic
> 
> Could you show that you do to first your first (login) request and second (subsequent) request? Are you using the same instance of axios request?
> 
> So try creating an instance o axios and utilize only this instance for all requests.
> 
> ```
> const instance = axios.create({
>   baseURL: 'https://some-domain.com/api/'
> });
> ```

Yes, of course, I am utilising a single instance. I've even now normalised the domain names for front-end and back-end to `localhost` but the problem persists. The session cookie is just being ignored.

**Comment by geoidesic** [comment]
I tried it with the same instance now on both calls and I'm getting the same behaviour.

The URLS are:

Front-end
```http://localhost:8080```
Back-end
```http://localhost:8888```

My axios config looks like this: 
```
baseURL: process.env.SRV,
  origin: true,
  withCredentials: true,
  headers: {
    Accept: "application/json",
    "Content-Type": "application/json;charset=UTF-8"
  }
  ```

**Comment by geoidesic** [comment]
I've now tried this over https and it still doesn't work.

**Comment by WillianAgostini** [comment]
try using [interceptors](https://github.com/axios/axios#interceptors), [creating-an-instance](https://github.com/axios/axios#creating-an-instance) or combine both.

**Comment by ericambiel** [comment]
> The URLS are:
> 
> Front-end `http://localhost:8080` Back-end `http://localhost:8888`
> 

Even being the same domains, the ports are different, the browser will validate everything including the port, in which case you can use a domain reflection technique, it would be like a white list with the allowed domains, if the request comes from an Origin known by API, it will return the same value to the cross-origin headers.

**Comment by burkeingraffia** [comment]
I found that my Postman auth expired after 300 seconds.

**Comment by khashayar-bo** [comment]
@geoidesic Could you solve the issue? I have exactly the same issue and have been stuck for a couple of days

**Comment by geoidesic** [comment]
@khashayar-bo yes. It was not easy. There are two main issues. A recent change to the browser security specifications means that the browser will not store the session cookie provided by the back-end if:

1. The domain is localhost and:
1.1 The FQDN does not contain at least two dots (e.g. "fe.app.localhost" is good, "fe.localhost" is bad), 
1.2 AND / OR The protocol is not HTTPS

This makes it much harder to have a local dev environment.

The reason it works via POSTMAN is that POSTMAN is not a browser and so ignores that security specification.
