### ISSUE TITLE
Axios 0.25 can't seem to post when request post works just fine

### ISSUE THREAD

**Issue by Tigatok** [axios/axios#4789]
#### Describe the bug
All week I have been trying to build an endpoint using NextJS and axios to upload a file to a 3rd party api. I then switched to using request, and it works, whereas axios returns 400 bad request. I am not sure if something is scrubbed, or perhaps I have something configured wrong. They all appear to be the same to me...

#### To Reproduce

Axios:
```js
const formData = {
    file: fs.createReadStream(filename),
    options: JSON.stringify(fileOptions),
    folderPath: 'docs'
  };
  const response = await axios.post(postUrl, formData, {
    headers: {
      Authorization: `Bearer ${process.env.lovelytoken}`,
      'Content-Type': 'multipart/form-data'
    }
  });
```

Request:
```js
  const formData = {
    file: fs.createReadStream(filename),
    options: JSON.stringify(fileOptions),
    folderPath: 'docs'
  };
  request.post(
    {
      url: postUrl,
      formData,
      headers: {
        Authorization: `Bearer ${process.env.lovelytoken}`,
        'Content-Type': 'multipart/form-data'
      }
    },
    (err, httpResponse, body) => console.log(err, httpResponse.statusCode, body)
  );
```

#### Expected behavior
I would think the same response at least?

#### Environment
 - Axios Version [e.g. 0.25.0]
 - Adapter [e.g. HTTP]
 - Browser [e.g. Chrome, ]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 16.13.1]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version 0.27.2 and open a new issue should this error still be relevant?

Thanks
