### ISSUE TITLE
Why doesn't axios resolve localhost?

### ISSUE THREAD

**Issue by CCLDArjun** [axios/axios#4794]
I have 
```js
  await axios
    .get("http://localhost:14000/")
```
and it's giving `ECONNREFUSED`
But, when I give it `127.0.0.1` instead of `localhost`, it works.
Why? Running latest version v0.27.2

**Comment by jasonsaayman** [comment]
Pretty sure it is not axios error as I often do this and it works fine

**Comment by DigitalBrainJS** [comment]
@CCLDArjun https://stackoverflow.com/questions/20345132/127-0-0-1-is-accessible-working-but-localhost-not-accessible-not-working
