### ISSUE TITLE
Url parameter disregards a given baseURL but is still required.

### ISSUE THREAD

**Issue by dracoDevs** [axios/axios#4809]
### Bug Overview
When creating an Axios instance and instantiating a baseURL like so:
```ts
const handler = axios.create({
    headers: {},
    method: "GET",
    validateStatus: null,
    baseURL: process.env.BASE_URL ,
});
```
Then when I reference my handler and try to send a request, I'm still prompted to require a ``url`` parameter which completely disregards the ``baseURL`` that I declare.
***Error is as follows:***
```ts
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
```
### This code should trigger the same error
```ts
import axios, { AxiosRequestConfig, AxiosResponse } from "axios";

const handler = axios.create({
    headers: {},
    method: "GET",
    validateStatus: null,
    baseURL:  "https://www.google.com/",
});

async function request(options: AxiosRequestConfig): Promise<AxiosResponse> {
    // const proxy: HttpProxyAgent = proxies[Math.floor(Math.random() * proxies.length)];
    return await handler({
        ...options,
        // httpAgent: proxy
    });
};

(async () => {
    await request({});
})();
```

### Possible solution
When a ``baseURL`` is present maybe no longer require a url param or use the url param as a path for the given ``baseUrl``.
Otherwise there is no point in having the ``baseURL`` param in the configuration.

### Notable information
I've tried countless way to evade this error such as passing a url parameter as an empty string (``""``) like so:
```ts
(async () => {
    await request({ url: "" });
})();
```
***Upon trying this I am greeted with the following error:***
```ts
Error: Cannot read properties of null (reading 'replace')
```

**Comment by Substancia** [comment]
`baseURL` denotes the base part of the URL, i.e. without the relative path. For eg., say we have a URL `https://www.mydomain.com/images/event/1`, the `baseURL` here is just `https://www.mydomain.com`, and the relative path is `/images/event/1`.

With these being said, I don't really see a scope for improvement here?
