### ISSUE TITLE
Axios response headers can be `undefined` (TS typing isn't strict enough)

### ISSUE THREAD

**Issue by gprst** [axios/axios#4812]
#### Describe the bug

Axios response headers can actually be `undefined`. For instance, a response can sometimes contain the `location` header, and sometimes not.

#### To Reproduce

```ts
type Expense = {
  // ...
};

async function postExpense(projectId: string, expense: Omit<Expense, 'id'>): Promise<string> {
  const res = await axios.post(`/projects/${projectId}/expenses`, expense);

  // `res.headers.location` is considered as a string, even though it could be `undefined`
  // e.g. when the response from the server is an error one
  const location = res.headers.location;

  // this causes this variable to be `undefined`, and leads to errors when the function is called
  return location;
}
```

#### Expected behavior

`AxiosResponseHeaders` should reflect the fact that headers can be `undefined`.

#### Environment
 - Axios Version: 0.27.2
 - Adapter: N/A
 - Browser: N/A
 - Browser Version: N/A
 - Node.js Version: 16.15.1
 - OS: N/A
 - Additional Library Versions: N/A

#### Additional context/Screenshots

N/A

**Comment by wei-beamery** [comment]
The response headers were always available in previous versions. Is the expectation that response headers should be checked for undefined, or is this a recent breaking change?

**Comment by gprst** [comment]
I don't know about the history of the codebase. I just know that currently, you can get a value that'd be typed as `string`, although it could actually be `undefined` — so yes, the expectation is that response headers should be typed as `string | undefined`, to be more accurate.

I've created [a PR for this](https://github.com/axios/axios/pull/4813).

**Comment by jasonsaayman** [comment]
Merged the PR will release soon, closing.
