### ISSUE TITLE
"Automatic serialization to URLSearchParams" with application/x-www-form-urlencoded doesn't work

### ISSUE THREAD

**Issue by uh-zuh** [axios/axios#4834]
#### Describe the bug

Example in new section of documentation "Automatic serialization to URLSearchParams" sends request with content encoded that does not match the "Content-type" header.
https://github.com/axios/axios#-automatic-serialization-to-urlsearchparams

#### To Reproduce

Execute the example from documentation:
```js
const data = {
  x: 1,
  arr: [1, 2, 3],
  arr2: [1, [2], 3],
  users: [{name: 'Peter', surname: 'Griffin'}, {name: 'Thomas', surname: 'Anderson'}],
};

await axios.postForm('https://postman-echo.com/post', data,
  {headers: {'content-type': 'application/x-www-form-urlencoded'}}
);
```

Look in browser dev tools for request and see:
- Header:
  - `Content-Type: application/x-www-form-urlencoded`
- Body:
  - `{"x":1,"arr":[1,2,3],"arr2":[1,[2],3],"users":[{"name":"Peter","surname":"Griffin"},{"name":"Thomas","surname":"Anderson"}]}`

Body is still encoded as `application/json` and not as `application/x-www-form-urlencoded` and for example on backend side in PHP I see following invalid input params:
```
$_POST: Array
(
    [{"x":1,"arr":] => Array
        (
            [1,2,3] =>
        )
)
```

#### Expected behavior

Look in browser dev tools for request and see:
- Body:
  - `x=1&arr=1%2C2%2C3&arr2=1%2C2%2C3&users=%5Bobject+Object%5D%2C%5Bobject+Object%5D`

And on backend side in PHP I see following valid input params:
```
$_POST:, Array
(
    [x]     => 1
    [arr]   => 1,2,3
    [arr2]  => 1,2,3
    [users] => [object Object],[object Object]
)
```
`[object Object]` is not good in general but it is expected behavior in this case.

This works as expected if replace this line: 
```js
await axios.postForm('https://postman-echo.com/post', data,
```
by this line:
```js
await axios.postForm('https://postman-echo.com/post', new URLSearchParams(data),
```

#### Environment

 - Axios Version: 0.27.2
 - Browser: Firefox/Chrome
 - Browser Version: Firefox 102, Chrome 103
 - Node.js Version: 18.4.0
 - OS with npm: Debian GNU/Linux 11 (bullseye) inside Docker
 - OS with browser: Windows 10 Pro
 - Additional Library Versions: webpack@5.73.0, webpack-stream@7.0.0, chunks-webpack-plugin@7.0.3, gulp@4.0.2

#### Additional context/Screenshots

Screenshot of documentation:
![2022-07-07 23_36_54-axios_axios_ Promise based HTTP client for the browser and node js — Mozilla Fir](https://user-images.githubusercontent.com/9747028/177868486-31a49b90-dcea-4bb8-b3ef-969607fbd1b1.png)

**Comment by DigitalBrainJS** [comment]
> Axios Version: 0.27.2

It seems to be a version mismatch. You are looking at the documentation for Axios 1.0.0-alpha.1, where this feature is implemented, but in fact, you are using v0.27.2. The `postForm` method only supports multipart encoding in version v0.27.2.
![image](https://user-images.githubusercontent.com/12586868/177887519-5b39a13a-1148-4602-bd87-85077bfe6d9a.png)

[Sandbox](https://codesandbox.io/s/axios-application-x-www-form-urlencoded-cwnli9?file=/src/index.js)

**Comment by uh-zuh** [comment]
Thank you, it wasn't obvious.

**Comment by philBrown** [comment]
Why is the default branch for this repo set to `1.x` when it's still in _alpha_?

**Comment by philBrown** [comment]
This incorrect documentation is also in the 2.x branch ~ https://github.com/axios/axios/tree/v2.x#-automatic-serialization-to-urlsearchparams

**Comment by philBrown** [comment]
@DigitalBrainJS this incorrect documentation is also in the 0.x branch ~ https://github.com/axios/axios/tree/v0.x#-automatic-serialization-to-urlsearchparams

**Comment by jasonsaayman** [comment]
Thanks @philBrown, I will fix that, and it is the default cause we are releasing that v1 as the main project version this week.

**Comment by philBrown** [comment]
Might also be worth pointing out that you don't _need_ `postForm()`. Using plain old `post()` with the appropriate content-type still encodes the data correctly

```js
axios.post(url, data, {
  headers: { "content-type": "application/x-www-form-urlencoded" }
});
```
