### ISSUE TITLE
Axios gives error when used with localhost

### ISSUE THREAD

**Issue by rishab2097** [axios/axios#4837]
#### Describe the bug
When axios being used to make local http calls it throws error if the url contains localhost and if we replace the local host with the ip address "127.0.0.1" it works
#### To Reproduce
```js
axios({
    method: 'post',
    url: 'http://localhost:3311/index',
    headers: { 
      'Content-Type': 'application/json'
    },
    data:{}
})
```

#### Expected behavior

It should work for both the cases i.e it can take localhost or the ip address

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by MichielDeCapThomasMore** [comment]
Could you maybe post a screenshot of the error

**Comment by nkilm** [comment]
### Please check if you have enabled `Cross-Origin Resource Sharing(CORS)`.  
[CORS definition](https://www.contentstack.com/docs/developers/how-to-guides/understanding-and-resolving-cors-error/#:~:text=CORS%20behavior%2C%20commonly%20termed%20as%20CORS%20error%2C%20is%20a%20mechanism%20to%20restrict%20users%20from%20accessing%20shared%20resources.)

If you are using `Flask`, then you should add CORS
```python 
from flask_cors import CORS 

app = Flask(__name__)
CORS(app) 
```

Similarly in `Express.JS`
```javascript
const express = require("express");
const cors = require("cors")
const app = express();

app.use(express.static(path.join(__dirname,"public")));

app.use(cors({
    origin:"*",
    methods:['GET']
}))
```

**After adding CORS, your request will work for both localhost and 127.0.0.1**

**Comment by gitSambhal** [comment]
Check the solution here
https://github.com/axios/axios/issues/3821#issuecomment-1413727575
