### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by Elabar** [axios/axios#4838]
We used to use the following code to handle errors as shown in the docs
```
axios.get('/user/12345')
  .catch(function (error) {
    if (error.response) {
      // The request was made and the server responded with a status code
      // that falls out of the range of 2xx
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } else if (error.request) {
      // The request was made but no response was received
      // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
      // http.ClientRequest in node.js
      console.log(error.request);
    } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
    }
    console.log(error.config);
  });
```

Where `error.response` should exist only if the server did response.
But in v0.27.x, this is no longer the case. `error.response` will always exist regardless the server did response or not. Is this intended? If so, how we know if the server never response to the request in 0.27.x and onwards? Node environment seems to still behaving the same across 0.26 and 0.27. Only browser is affected 

Reproducable link is attached here, try to change the axios version to 0.27 and 0.26
It will hit different if block.
https://codesandbox.io/s/determined-ives-9qu86i?file=/src/index.js

**Comment by psYifanChen** [comment]
I have the same issue, and changed my code.
It works for me, but I want to know if there is a better solution.
Thanks.
`
//...
catch (e) {
   if (e instanceof AxiosERROR) {
       if (!e.response || e.code === AxiosError.ERR_NETWORK_) {
           console.log('can not reach server')
       }
   }
}
`
