### ISSUE TITLE
XMLHttpRequest is discouraged

### ISSUE THREAD

**Issue by botverse** [axios/axios#484]
XMLHttpRequest is discouraged and will be more rare to be found in the [new contexts like service worker](https://github.com/whatwg/xhr/issues/19#issuecomment-106977644).

Should `axios` use `fetch` when `XMLHttpRequest` is not available?

**Comment by nickuraltsev** [comment]
Interesting. So is `XMLHttpRequest` available in SW right now or not?

**Comment by botverse** [comment]
Not in Chrome or Firefox as far as I know

**Comment by nickuraltsev** [comment]
We can of course create a `fetch` adapter but if we do so, we will have to support both the `XHR` and `fetch` adapters for a long time. At the same time I think we should support service workers.

@mzabriskie @rubennorte Thoughts?

**Comment by adzm** [comment]
Notably, fetch cannot be cancelled, though this will likely change when the cancelable promises spec becomes supported by major browsers and implemented in fetch. Until then XHR is still the most versatile API.

**Comment by botverse** [comment]
@adzm I would be happy to be able to use axios in the service worker knowing that I would not be able to cancel rather than not to be able to use it at all. So in that case is not very versatile.

One advantage of using axios in the service worker is to reuse the client code instead of duplicating the flow for all the requests.

**Comment by couturecraigj** [comment]
One of the great aspects of SWs is that you can cache their responses... so not being able to cancel would seem to be less of an issue with SWs.  I think axios should definitely support fetch as I have read a handful of articles outlining a need to abandon XHR.  Maybe there could be a plugin so that you do not need to support the Promise library that gets implemented?  Just an idea.

**Comment by stevenvachon** [comment]
It should be based on `fetch` as it will give access to the redirect history via silent or optional use of `{redirect:'manual'}`. A `fetch` shim can always be used.

**Comment by robodude** [comment]
I just started learning service workers in order to build a progressive web application and was pretty disappointed when I realized I couldn't use axios in my service worker. I hope a solution to this is still being considered.

**Comment by couturecraigj** [comment]
I think with the new implementation of Abortable/Cancellable Promises implemented by Firefox we will start seeing a solution that can be implemented going forward.  https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

**Comment by stevenvachon** [comment]
The Cancellable Promises proposal was withdrawn: https://github.com/tc39/proposal-cancelable-promises

**Comment by couturecraigj** [comment]
But the abort controller is going through finalization.  There is a few
recent videos from people like Jake Archibald
https://developers.google.com/web/updates/2017/09/abortable-fetch. This is
not the same as cancelable this aborts the sequence.  The is moving forward
apparently.

**Comment by jmeas** [comment]
I'm working on adding support for aborting fetch to GitHub's fetch polyfill.

**PR:** https://github.com/github/fetch/pull/592
**Feature detection code:** https://gist.github.com/jmeas/39546faa735779051bd00c3fe2a136f9

I'm sharing this here in case it's helpful in resolving this issue :v:

**Comment by Blfrg** [comment]
Please revisit this concept to implement a `fetch` adapter.

I see some community work has been done [here](https://github.com/axios/axios/issues/1219#issuecomment-382513375) which could jump start the process.
@jamesplease's work above on fetch polyfill has been merged if that helps squelch outstanding concerns.

Axios is the suggested library everywhere you look (and for good reason!)
`fetch` is needed for PWA+SW which is all the rage now.
A compromise is highly desired by all, even if it's a choice between features (e.g. ability to cancel vs support offline SW).

Thank you for the essential module and consideration for the feature request.

**Comment by cristianoccazinsp** [comment]
When using React Native, fetch seems to be way better at handling large json responses than  XMLHttpRequest (and I don't really know why, or if it is related to axios code)

**Comment by chinesedfan** [comment]
Closed in favor of #1219.
