### ISSUE TITLE
AxiosError: write EPROTO 1C3B0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

### ISSUE THREAD

**Issue by Laxuzer** [axios/axios#4840]
I get this error when I try to send a request via proxy with Axios. I've searched the Internet, but I haven't been able to reach any results.

```
const axios = require('axios')

axios({
    url: 'http://medal.tv',
    method:'GET',
    proxy: {
        protocol: 'http',
        host: 'xxx',
        port: 3000,
        auth: { username: 'xxx', password: 'xxx' }
    }
}).then(e => console.log(e.data)).catch(e => console.log(e))
```

**Comment by ProfessorOakWithO** [comment]
You could try your call with curl `curl -vvv http://medal.tv --proxy http://username:password@xxx:3000`. This will probably result in a better error message to google..

**Comment by fabioselau077** [comment]
same here, how fix?

**Comment by NotiGate** [comment]
Same, how fix ?

**Comment by NotiGate** [comment]
`await axios.post("https://spclient.wg.spotify.com/signup/public/v1/account", payload {
        proxy: {
            host: 'A IP or DNS',
            port: 22323,
            username: "notigate",
            password: "MyPassword"
 }`
Error : 
`AxiosError: write EPROTO 48100:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:`

**Comment by likeavenus** [comment]
Same, how fix ?

**Comment by iammrjude** [comment]
Same here and I'm also getting this error when I'm trying to connect to amazon RDS using mysql npm

```
    axios.get('https://token-list.sushi.com').then((response) => {
            const tokenObject = response.data.tokens
            const tokenList: string[] = []
            for (let y = 0; y < tokenObject.length; y++) {
                if (tokenObject[y].chainId == 137) {
                    tokenList.push(w3.utils.toChecksumAddress(tokenObject[y].address))
                }
            }
            const len = tokenList.length
            console.log(`Token List Length: ${len}`)
            for (let i = 0; i < len; i++) {
                const tokenA = tokenList[i]
                let n = 0
                if (i > 0) { n = i }
                fetchPairs(n, len, tokenA, tokenList)

            }
    })
```

Error: 

`AxiosError: write EPROTO 18952:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:`

**Comment by iammrjude** [comment]
> Same, how fix ?

Did you recently Install Python 2?

There is an NPM package that required me to install python 2. I started having this issue when I installed python 2.

After uninstalling python 2 today I stopped getting the error

**Comment by MASSKAgithub** [comment]
Try like that with HttpsProxyAgent.

axios.get("website", {
        httpsAgent: new HttpsProxyAgent('http://USER:PASSWORD@IP:PORT')
    }).then((res) => {
       // do something
})

I was getting the error because in the proxy I wrote https instead of http.

I hope it will help you

**Comment by MASSKAgithub** [comment]
What are you waiting to put it as resolved?

**Comment by Pudochu** [comment]
**Solution:**
You only get this error when you change a supported proxy from "http" to "https".
So if you wrote "https://" change it to "http://". Or vice versa.

**Comment by ReactMasterio** [comment]
const OTP_API = "https://192.168.4.10:8001/api/tatreports/getotp/";
const onNumberCheck = async () => {
    try {
      const response = await axios.get(
        `https://localhost:3005/api/is-user-exist/0${inputNumberValue}`
      );

      console.log(response);
      if (response.status === 200) {
        setIsUserExist(true);
        // Send a notification when status is 200
        notification.success({
          message: ` سلام ${response.data.name}`,
          description:
            "کد احراز هویت برای شما ارسال شد. لطفا آن را وارد نمایید.",
        });
        setLoggedUserName(response.data.name);
        setLoggedUserAccessType(response.data.accessType);

        const otpRespons = await axios.get(`${OTP_API}${inputNumberValue}`);
        if (otpRespons.status === 200) {
          setValidationCode(otpRespons.data);
          console.log(otpRespons.data);
        }else{
          notification.error({
            message: `مشکلی پیش آمده`,
            description: "لطفا ارتباط با سرویس پیامکی را چک کنید و یا با پشتیبانی تماس بگیرید",
          });
        }
      }else if(response.status === 403){
        notification.error({
          message: `این شماره اجازه دسترسی ندارد`,
          description: "لطفا با پشتیبانی تماس بگیرید",
        });
      }
    } catch (error) {
      if (error.response) {
        // The request was made, but the server responded with a status code
        const statusCode = error.response.status;
        console.error(`Request failed with status code: ${statusCode}`);
        notification.error({
          message: `این شماره اجازه دسترسی ندارد`,
          description: "لطفا با پشتیبانی تماس بگیرید222",
        });
      } else if (error.request) {
        notification.error({
          message: `No response received from the server.`,
          description: "لطفا با پشتیبانی تماس بگیرید",
        });
        console.error("");
      } else {
        notification.error({
          message: `Error setting up the request:`,
          description: `${error.message}`,
        });
      }
    }
  };
in this code i get the same, it works when i use http for localhost or my Windows server but when i change it to https i get this error: AxiosError: write EPROTO 483E0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

**Comment by komen205** [comment]
nodejs implementation

```
      const axiosConfig = {
        proxy: {
          host: 'localhost',
          port: 8888, // Replace with your proxy port
          protocol: 'http', // Change to 'http' for HTTP proxy
          // Optionally, you can provide authentication credentials if your proxy requires them
        },
      };
      ```

**Comment by truong0vanchien** [comment]
After struggling a while, I use node-fetch instead of axios and it works well.

**Comment by kashifilyasdev** [comment]
In node, use `axios-https-proxy-fix` instead of `axios` if you have to use https proxy. Axios is apparently broken.
```
const axios = require('axios-https-proxy-fix');
```

**Comment by ylmazmehmet60** [comment]
Even if you fix this bug, it is not stable for some proxies. Maybe curl can be used like this.

```node
const util = require('util');
const { exec } = require('child_process');
const execPromise = util.promisify(exec);

async function executeCommand() {
  const command = 'curl -vvv url_here --proxy http://username:pwd@ip:port';

  try {
    const { stdout } =  await execPromise(command);
    console.log('Command Output:', stdout);
  } catch (error) {
    console.error('Error:', error.message);
  }
}

// Call the async function
executeCommand();

```

**Comment by iRupesh02** [comment]
> **Solution:** You only get this error when you change a supported proxy from "http" to "https". So if you wrote "https://" change it to "http://". Or vice versa.

Thanks man It will work

**Comment by MASSKAgithub** [comment]
> **Solution:** You only get this error when you change a supported proxy from "http" to "https". So if you wrote "https://" change it to "http://". Or vice versa.

Damn, he LITERALLY copied my answer, and he got 32 🎉 emjois, while MY ORIGINAL REAL ANSWER, got only 10 👍 
Wtf?

**Comment by AliAryanTech** [comment]
> **Solution:** You only get this error when you change a supported proxy from "http" to "https". So if you wrote "https://" change it to "http://". Or vice versa.

Damn it works

**Comment by DionRo** [comment]
> [<img alt="@rowild" width="20" height="20" src="https://avatars.githubusercontent.com/u/213803?s=40&amp;v=4">](/rowild) [rowild](/rowild) mentioned this issue [ Sep 8, 2023 ](#ref-issue-1886910728)
> [ Error routines:ssl3_get_record:wrong version number di](/directus-labs/agency-os/issues/21)

Yeah this error gave me headaches, found this after a while. Still works... Not all heroes wear capes.

**Comment by DionRo** [comment]
> **Solution:** You only get this error when you change a supported proxy from "http" to "https". So if you wrote "https://" change it to "http://". Or vice versa.

Yeah, this error gave me headaches, I found this solution after a while. Still works... Not all heroes wear capes.

**Comment by sKopheK** [comment]
> > **Solution:** You only get this error when you change a supported proxy from "http" to "https". So if you wrote "https://" change it to "http://". Or vice versa.
> 
> Damn, he LITERALLY copied my answer, and he got 32 🎉 emjois, while MY ORIGINAL REAL ANSWER, got only 10 👍 Wtf?

there there, here are few 🎉🎉🎉🎉🎉, no need to cry anymore. go, get some lolly

**Comment by ajinkya-tambe** [comment]
> **Solution:** You only get this error when you change a supported proxy from "http" to "https". So if you wrote "https://" change it to "http://". Or vice versa.


Worked for mee!!
