### ISSUE TITLE
axios request interceptor adds additional headers

### ISSUE THREAD

**Issue by eau-de-la-seine** [axios/axios#4843]
#### Describe the bug

axios request interceptor adds additional headers

#### To Reproduce

```js
axios.interceptors.request.use(config => {
    console.log('config.headers')
    console.log(config.headers)
    return config
}, error => {
    return Promise.reject(error)
})

await axios.get(url, {
    headers: {"X-header1": 'headerValue1'}
})
```
Console Log result:
```
config.headers
{
  common: { Accept: 'application/json, text/plain, */*' },
  delete: {},
  get: {},
  head: {},
  post: { 'Content-Type': 'application/x-www-form-urlencoded' },
  put: { 'Content-Type': 'application/x-www-form-urlencoded' },
  patch: { 'Content-Type': 'application/x-www-form-urlencoded' },
  'X-header1': 'headerValue1'
}
```
**Problem:** `common`, `delete`, `get`, `head`, `post`, `put`, `patch` have been added to `config.headers` by `axios`

#### Expected behavior

Expected Console Log result:
```
config.headers
{
  'X-header1': 'headerValue1'
}
```

#### Environment

NodeJS Back-end project using ES6 modules and testing with Jasmine (the only testing framework that works without additional transpiler for ES6 projects)

 - Axios Version `^0.27.2`
 - Node.js Version `v14.17.0`
 - OS: `Ubuntu 20.04.4 LTS`
 - Additional Library Versions: Jasmine `^4.2.1`

**Comment by jasonsaayman** [comment]
please use the latest version as this is resolved.
