### ISSUE TITLE
Error Status Codes 400 and 500

### ISSUE THREAD

**Issue by mado-bohsali** [axios/axios#4851]
Dear concerned,
[Error Socket Hang Up.txt](https://github.com/axios/axios/files/9110777/Error.Socket.Hang.Up.txt)

Upon using a [queue](https://www.npmjs.com/package/queue) (npm package), I am facing errors such as Error 400 Bad Request or Socket Hang up or 500. What is the best practice to avoid any of these?

N.B. I am using a 10 seconds setTimeout between each call.

**Comment by WillianAgostini** [comment]
Hi @mado-bohsali, please show the code that reproduces this issue.

**Comment by jasonsaayman** [comment]
closing, please open a new issue following the issue template and provide some examples
