### ISSUE TITLE
With version 0.27.1 the request header will be lost, while 0.27.0 will not

### ISSUE THREAD

**Issue by yangqixin123** [axios/axios#4858]
When sending a post request using version 0.27.1, the request header will be lost, but 0.27.0 will not
It is written as follows:

```js
class Header {};
let myHeaders = new Header();
myHeaders["X-Foo"] = "bar";
myHeaders["X-Test"] = "test";
myHeaders["X-Time"] = Date.now();
  
axios.post('http://cors-test.appspot.com/test', { name: 'foo' }, { headers: myHeaders })
.then((res) => {
       console.log('res---',res.config.headers);
 })
```

See test.zip for details.

#### Environment
 - Axios Version [0.27.1]
 - Browser [Chrome]
 - Browser Version [103.0.5060.114]
 - Node.js Version [14.14]
 - OS: [iOS 12.4]
<img width="1321" alt="WX20220717-225027@2x" src="https://user-images.githubusercontent.com/51486236/179403912-e08ef5a3-04eb-4219-98aa-129a7d4f18c3.png">

[test.zip](https://github.com/axios/axios/files/9127909/test.zip)

**Comment by techbirds** [comment]
You can use plain objects for parameter definitions, like this:
```

const myHeaders = {}
myHeaders["X-Foo"] = "bar";
myHeaders["X-Test"] = "test";
myHeaders["X-Time"] = Date.now();

axios.post('http://cors-test.appspot.com/test', {
    name: 'foo'
  }, {
    headers: myHeaders
  })
  .then((res) => {
    console.log('res---', res.config.headers);
  })

```

**Comment by yangqixin123** [comment]
But my project has been using the new Class writing method before. The official does not seem to mention that this writing method cannot be used in the new update.

**Comment by yangqixin123** [comment]
> But my project has been using the new Class writing method before. The official does not seem to mention that this writing method cannot be used in the new update.

**Comment by WillianAgostini** [comment]
Hello @yangqixin123

In this commit [910fdc1b1018](https://github.com/axios/axios/commit/6b9b05b9078c78c9532ed8c29dfb910fdc1b1018), the method **generateHTTPMethod** [http](https://github.com/axios/axios/blob/6b9b05b9078c78c9532ed8c29dfb910fdc1b1018/lib/core/Axios.js#L142-L149) modified the behavior of this method, I believe that was not the intention.

I can commit by changing the way this merge happens and solving this problem.

**Comment by yangqixin123** [comment]
> Hello @yangqixin123
> 
> In this commit [910fdc1b1018](https://github.com/axios/axios/commit/6b9b05b9078c78c9532ed8c29dfb910fdc1b1018), the method **generateHTTPMethod**
> 
> https://github.com/axios/axios/blob/6b9b05b9078c78c9532ed8c29dfb910fdc1b1018/lib/core/Axios.js#L142-L149
> 
> modified the behavior of this method, I believe that was not the intention.
> I can commit by changing the way this merge happens and solving this problem.

@WillianAgostini [WillianAgostini](https://github.com/WillianAgostini) ok i will be very grateful

**Comment by WillianAgostini** [comment]
@yangqixin123 , you can workaround returning casting variable `myHeaders` like a generic object.

```js
  myHeaders = {...myHeaders};
```

**Comment by yangqixin123** [comment]
@WillianAgostini  I tried this and it's ok, but the company's previous production environment project does not want to be changed because of the upgrade of axios, I hope the official modification can be compatible with the previous usage

**Comment by WillianAgostini** [comment]
@yangqixin123, I created an PR https://github.com/axios/axios/pull/4871.

**Comment by yangqixin123** [comment]
@WillianAgostini  ok i will be very grateful

**Comment by jasonsaayman** [comment]
Closing as it merged
