### ISSUE TITLE
Patch Request Not Working

### ISSUE THREAD

**Issue by samiramrullah** [axios/axios#4864]
#### Patch Request Not Working
**If same request is made using post everything works fine unlike patch request**

#### Patch Request gives axios error
**Code **

![image](https://user-images.githubusercontent.com/74055996/179652523-12cbc5aa-1217-40ab-879c-7be5f2506493.png)

Error
![image](https://user-images.githubusercontent.com/74055996/179652661-b9d04b66-630f-47a5-a85d-8af13b093cdc.png)

#### Environment
 - Axios Version [^0.27.2]

**Comment by khobiziilyes** [comment]
The server is probably not accepting this request.

**Comment by Medb62** [comment]
Did you find a solution to this ? I'm facing the exact same issue here

**Comment by samiramrullah** [comment]
It works fine now, I guess axios had some problem with is resolved now, 
If it doesn't work for you 
## Check if you have same routes with other options (post , get)
## Try removing header 
# It should work then , if it again throws error please share code snippets

# I tried and It worked fine. ( if please check the way you have set routes in backend)
