### ISSUE TITLE
Request cannot connect to host inside docker container

### ISSUE THREAD

**Issue by viktor111** [axios/axios#4866]
I have nestjs application running in docker container. It uses HttpService which uses '@nestjs/axios' to call some service trough http. I get this error:

Error:
```
Error: connect ECONNREFUSED 127.0.0.1:8081

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```

Code: 
``` typescript
const getRequest = lastValueFrom(
      this.httpService.get("http://127.0.0.1:8081/").pipe(
        map(resp => resp.data),
      ),
    ); 
```

It works when not run in docker container. But I get error when run in container.

**Comment by khobiziilyes** [comment]
I don't think it is something that has to do with axios, try it with `fetch` and you'll see the same result.

**Comment by dizonb** [comment]
In our case, we are using Docker and using localhost doesn't work on our end. 
The solution is that you can use the container name for nginx instead of localhost.

```await axios.get('http://nginx/api/v1');```

**Comment by dizonb** [comment]
In our case, we are using Docker and using localhost doesn't work on our end.
The solution is that you can use the container name of the webserver (nginx) instead of localhost.
If you're using apache as your web server, use apache instead of nginx.

await axios.get('http://nginx/api/v1');
