### ISSUE TITLE
Sometimes Axios removes the last part of the url and sends a get request istead of a post request.

### ISSUE THREAD

**Issue by mrgreenstone** [axios/axios#4869]
#### Describe the bug
Sometimes Axios removes the last part of the url and sends a get request instead of a post request.

This are the two urls that are the outcome:
- http://nanoleaf:16021/api/v1/new
- http://nanoleaf:16021/api/v1//

#### To Reproduce
By repreating the about ten times you can see in the error log, that a random url of the ones above gets selected

```js
const axios = require('axios').default
axios.post("http://nanoleaf:16021/api/v1/new").then(console.log)
```

#### Expected behavior
Axios **always** sends a post request to "http://nanoleaf:16021/api/v1/new".

#### Environment
 - Axios Version 0.27.2
 - Node.js Version 16.9.1

**Comment by khobiziilyes** [comment]
Tried it myself and couldn't see the bug.

**Comment by jasonsaayman** [comment]
i tried to replicate but could not, please re-open should you re-encounter

**Comment by Andy1734** [comment]
I am experiencing this issue too (with NuxtJs and only in one specific component for now). 
Whenever I call this function:
![grafik](https://github.com/user-attachments/assets/4495e04d-83ad-4ec5-aff3-1eaa61fadd5e)
Calling it here:
![grafik](https://github.com/user-attachments/assets/980491a6-e63a-4e80-aaea-09c479af0a08)
Axios for some reason manipulates my url to the following:
![grafik](https://github.com/user-attachments/assets/ceef6f3c-2071-4f24-86c9-47d4785b312a)


Can anyone tell me what's going on?

**Comment by jasonsaayman** [comment]
do you have a axios instance declared elsewhere?
