### ISSUE TITLE
Data payload body should be applicable for request methods 'GET'

### ISSUE THREAD

**Issue by Phenek** [axios/axios#4878]
### As described in the [doc](https://axios-http.com/docs/req_config),  Data is not applicable for request methods 'GET'
````
 // `data` is the data to be sent as the request body
 // Only applicable for request methods 'PUT', 'POST', 'DELETE', and 'PATCH'
````

I understand that axios at first followed the RFC2616 referenced as [the HTTP/1.1 spec, section 4.3](https://www.rfc-editor.org/rfc/rfc2616#section-4.3):
````
...if the request method does not include defined semantics for an entity-body, 
then the message-body should be ignored when handling the request.
````

But now times have changed, In 2014 it was replaced by RFCs 7230-7237 [HTTP 1.1 2014 Spec](https://www.rfc-editor.org/rfc/rfc7231#page-24):
And the quote has been deleted. 

### Is your feature request related to a problem?
Yeah, cause it's time consuming when you have already a big backend that require payload in 'GET' request,
And you have two choises: move on from axios or rewrite all request in 'POST'.

### Describe the solution you'd like
````
axios({
  method: 'get',
  url: '/user/12345',
  data: {
    firstName: 'Fred',
    lastName: 'Flintstone'
  }
});
````

### Describe alternatives you've considered
We could use a property in AxiosRequestHeaders, that could be named { forcePayload: true }
That will use an alternative of XMLHttpRequest in case the method is GET with forcePayload property.

Even if sending a payload body on a GET request, might cause some existing implementations to reject the request.
We are in 2022 and axios should let us give the choise to do so.

Thanks for your reading.

**Comment by Phenek** [comment]
Waiting for the upcoming HTTP QUERY Method 
[ietf satus & documentation](https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/)

**Comment by mamidon** [comment]
I'm working with an external API that expects a body with a GET endpoint.  I know it's not idiomatic, but it's what I have to work with.  It would be really nice if Axios supported this scenario.

**Comment by xingzilong** [comment]
Hello, I am currently facing the same problem as you. I need to build a GET request and add a request body to it. But axios doesn't seem to support this. Do you have any better solutions now?

**Comment by Phenek** [comment]
Unfortunately guys, it’s not an axios issue.
But a browser issue. 
No browser accept body in xhr/fetch request.

I am on your side too..

**Comment by xingzilong** [comment]
Is that so! Thanks for your answer, sorry for misunderstanding axios. But I think according to some specifications in the HTTP protocol, I still think this requirement is reasonable. I don't quite understand why browsers do this kind of restriction. Personally, I don't think this limitation is very reasonable. Could it be that my understanding of the HTTP protocol is biased? Or even say my understanding is wrong?
