### ISSUE TITLE
README.md: Examples not opening in Gitpod

### ISSUE THREAD

**Issue by mattkeanny** [axios/axios#4879]
#### Issue
At the bottom of the readme.md file, when clicking on the button „Open in Gitpod“, the gitpod.io page opens with this error message: 
*Couldn't find branch and path for master/examples/server.js in repo axios/axios.*

#### Suggested Improvement
In the Gitpod url, replace *master* with *main*:
(https://gitpod.io/#https://github.com/axios/axios/blob/main/examples/server.js)

#### Relevant File
README.md

**Comment by WillianAgostini** [comment]
Hi @mattkeanny.
PR https://github.com/axios/axios/pull/4882 will solve this.

**Comment by WillianAgostini** [comment]
#4882

**Comment by mattkeanny** [comment]
@WillianAgostini, thank you for issuing the PR.
