### ISSUE TITLE
Unable to post file from React frontend to Express backend

### ISSUE THREAD

**Issue by savreline** [axios/axios#4887]
#### Describe the issue
I have a very simple app to illustrate the situation where the React frontend has been generated by `create-react-app` and the express backend has been generated by `express-generator`. I am trying to send an image file from the frontend to the backend via axios as it shown below. However, when I `console.log(req.body)` on the backend I just get an empty object `{}`. The file appears ok when I log it on the frontend using `console.log(image)`. I understand there must be something very simple and obvious that I am missing, but I just don't see it. Many thanks in advance.

#### Example Code
**Frontend react component**
```js
import axios, { AxiosResponse } from "axios";
import React from "react";

const App = () => {
  const handleSubmitFile = (event: any) => {
    const image: File = event.currentTarget.files[0];
    console.log(image);
    const formData = new FormData();
    formData.append("image", image);
    axios
      .post("/api/sample", formData, {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      })
      .then((uploadResponse: AxiosResponse | Promise<AxiosResponse>) =>
        console.log(uploadResponse)
      );
  };

  return (
    <form>
      <input type="file" id="fileField" onChange={handleSubmitFile} />
    </form>
  );
};

export default App;
```

**Backend express route**
```js
var express = require("express");
var router = express.Router();

router.post("/", function (req, res, next) {
  console.log(req.body);
  res.send("respond with a resource");
});

module.exports = router;
```

#### Environment
 - Axios Version: 0.27.2
 - Adapter: HTTP
 - Browser: Chrome
 - Browser Version: 103
 - Node.js Version: 16.13.2
 - OS: Windows 10 21H1
 - Additional Library Versions: React 18.2.0, Express 4.16.1

#### Additional context/Screenshots
Repo with full code if need be https://github.com/savreline/axiosdemo
Got the above approach from https://stackoverflow.com/questions/43013858/how-to-post-a-file-from-a-form-with-axios

**Comment by WillianAgostini** [comment]
Hi @savreline, you need to use multer to get files on express, so try adding package 
```npm install multer```
and modify sample.js to 
```js
var express = require("express");
var router = express.Router();
var multer = require('multer');
var os = require('os');
var upload = multer({ dest: os.tmpdir() });

router.post("/", upload.single('image'), function (req, res, next) {
  console.log(req.body);
  console.log(req.file)
  res.send("respond with a resource");
});

module.exports = router;

Ref: https://stackoverflow.com/questions/65655500/access-file-upload-formdata-in-express
```

**Comment by savreline** [comment]
@WillianAgostini Yes, that works, thank you very much!
