### ISSUE TITLE
With branch should I open an PR?

### ISSUE THREAD

**Issue by WillianAgostini** [axios/axios#4890]
When a fix issue is opened from branch v1.x, should I make a PR for main, v1.x or both branches?

When has a feat issue, which branch must use to open an PR? Main branch?

With frequency created new releases are?

Some examples of open PR:
* https://github.com/axios/axios/pull/4884
* https://github.com/axios/axios/pull/4882
* https://github.com/axios/axios/pull/4874
* https://github.com/axios/axios/pull/4850

**Comment by WillianAgostini** [comment]
Has a doc about this rule?
With frequency created new releases are?
Is the branch main used?

**Comment by jasonsaayman** [comment]
No, I have not, in all honesty I have not yet had time to look into that stuff but I will try to do so asap

**Comment by WillianAgostini** [comment]
I can help to discuss and define [CONTRIBUTING.md](https://github.com/axios/axios/blob/v1.x/CONTRIBUTING.md) docs.

**Comment by AbdlrahmanSaberAbdo** [comment]
Hi @jasonsaayman Regarding this PR https://github.com/axios/axios/pull/4850, should I re-open it in V1?
