### ISSUE TITLE
Axios returning "400 Bad Request" error without the 'https://' in the url default behavior?

### ISSUE THREAD

**Issue by obtusedev** [axios/axios#4898]
#### Describe the issue
A clear and concise description of what the issue is.

Axios is making a request to localhost(127.0.1.1 port 80) and returning an "400 Bad Request" error without the 'https://' in the url.
Is this the default behavior?

#### Example Code
Code snippet to illustrate your question

```js
const axios = require("axios");

// this works as intended
const url = "https://www.httpbin.org";

// these makes a request to localhost and returns an 400 Bad Request
const url = "www.httpbin.org";
const url = "httpbin.org";

async function makeRequest() {
    try {
        const response = await axios.get(url);
        console.log(response);
    } catch(e) {
        console.error(e);
    }
}
```

#### Expected behavior, if applicable

I expect "www.httpbin.org" url format to not make a request to localhost.

#### Environment
 - Axios Version [0.27.2]
 - Adapter [HTTP]
 - Browser [Chrome]
 - Browser Version [e.g. 22]
 - Node.js Version [16.13.1]
 - OS: [Ubuntu 20.0.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by WillianAgostini** [comment]
It is not an issue only for axios.
Using Fetch API in Node.js has the same bug related. When has successful request only for first statement 

```js
await fetch("https://www.httpbin.org", {
  body: null,
  method: "GET",
})
```

```js
await fetch("www.httpbin.org", {
  body: null,
  method: "GET",
})
```

```js
await fetch("httpbin.org", {
  body: null,
  method: "GET",
})
```

Maybe the problem is the way that this server uses redirects.
