### ISSUE TITLE
Type asserts of response body

### ISSUE THREAD

**Issue by hungtcs** [axios/axios#4909]
#### Is your feature request related to a problem? Please describe.

I noticed the `responseType` attribute in the request config, 
seems that it only affects the way the response body is assembled (json or document or arraybuffer).
but has no assertion about the content type.

#### Describe the solution you'd like

```typescript
const response = await axios.get(`/index.html`, {
  responseType: "json"
});
```

If response header `content-type` is not `application/json`, but `responseType` is `json`, then throw an error.

#### Describe alternatives you've considered

```typescript
class ContentTypeError extends AxiosError {
  constructor(expect: string, response: AxiosResponse) {
    super(
      `expect ${expect} but ${response.headers["content-type"]}`,
      response.status.toString(),
      response.config,
      response.request,
      response
    );
  }
}

axios.get(`https://codesandbox.io`, {
  responseType: "json"
}).then((response) => {
  if (!response.headers["content-type"]?.startsWith("application/json")) {
    throw new ContentTypeError("application/json", response);
  }
});
```

#### Additional context

Other values of responseType also check response content-type.

| responseType | contentType |
|---|----|
| json | application/json |
| document | text/html |

- https://codesandbox.io/s/relaxed-rubin-st86df

**Comment by jasonsaayman** [comment]
if you would like can you please open a pr for this

**Comment by jasonsaayman** [comment]
if you would like to please open a pr and tag me but for now I don't think this is much of a priority
