### ISSUE TITLE
react native multipart/form-data; not working on debug mode

### ISSUE THREAD

**Issue by ugoconsonni** [axios/axios#4910]
#### Describe the issue
Request using Form data work if debug mode is not activate with version 0.27.2 but statusText was undefined
If i using version 0.26.0, this work in debug mode but don't work in production mode and statusText was defined.

#### Example Code
 loginUser: (data) => {
    let formdata = new FormData();
    formdata.append("l", data.username)
    formdata.append("p", data.password)
    return instance({
      method: 'post',
      url:"admin/requetes_ws_divers.php?ajaxAction=WSlogin",
      data:formdata,
      headers: {"Content-Type": "multipart/form-data;" },
    })
  }

#### Environment
 - Axios Version 0.27.2 || 0.26.0
 - React Native 0.68.2

**Comment by samarkalra** [comment]
Try this:-

import { stringify } from "query-string";  // This line

return instance({
    method: 'post',
    url:"admin/requetes_ws_divers.php?ajaxAction=WSlogin",
    data: **stringify(formdata),**   // This line
    headers: {"Content-Type": "multipart/form-data;" },
})

**Comment by Sunhat** [comment]
@samarkalra shouldn't be needed

**Comment by jasonsaayman** [comment]
please try the latest verison, should this still be a persistent issue please re-open
