### ISSUE TITLE
[Types] Type of header in AxiosRequestConfig / for Axios.create is incorrect

### ISSUE THREAD

**Issue by ghost91-** [axios/axios#4911]
#### Describe the bug

This is a follow up to #4184, as the problem still exists in version `1.0.0-alpha.1`.

More concretely, The type of the headers property in `Axios.create` config doesn't support headers for specific requests method (or `common`).

#### To Reproduce

```ts
const axiosRequestConfig: AxiosRequestConfig = {
    headers: {
        get: { 'Accept-Language': 'en' } // same with common, or other http methods
    }
};

Axios.create(axiosRequestConfig);
```
results in the error
```
Type '{ get: { 'Accept-Language': string; }; }' is not assignable to type 'Partial<AxiosHeaders & MethodsHeaders & CommonHeaders>'.
  Property 'get' is incompatible with index signature.
    Type '{ 'Accept-Language': string; }' is not assignable to type 'string | number | boolean | string[] | undefined'.
      Object literal may only specify known properties, and ''Accept-Language'' does not exist in type 'string[]'.ts(2322)
```

#### Expected behavior

The above code example type checks successfully.

#### Environment

 - Axios Version 1.0.0-alpha.1

#### Additional context/Screenshots
Related issues: #4184, #4193

**Comment by WillianAgostini** [comment]
Duplicated issue https://github.com/axios/axios/issues/4335
It has already been fixed on PR https://github.com/axios/axios/pull/4334
Here is an orientation about this issue by [@jay](https://github.com/axios/axios/issues/4184#issuecomment-1159538548)

**Comment by WillianAgostini** [comment]
PR https://github.com/axios/axios/pull/4926 open
