### ISSUE TITLE
AxiosError.response is XMLHttpRequest

### ISSUE THREAD

**Issue by moritzhertler** [axios/axios#4920]
#### Describe the bug
The optional field ["response"](https://github.com/axios/axios/blob/v1.x/index.d.ts#L276) of the class AxiosError<T, D> has the type AxiosResponse<T, D>.  But I found it to be an XMLHttpRequest when running into a cors error. The same XMLHttpRequest is also set on the "request" field. I tried to find the code where this error is thrown but was not able to yet. 

#### To Reproduce
Try triggering a cors error. 

#### Expected behavior
Only the "request" field should be set with the XMLHttpRequest, the value of the "response" field should be undefined. 

#### Environment
 - Axios Version 0.27.2
 - Adapter XHR
 - Browser Chrome
 - Browser Version 104

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/25606653/185555205-a08e11bc-22ed-4a95-a3fe-fae5dfd79bae.png)

**Comment by burhan3759** [comment]
I had the same issue

**Comment by developerbmw** [comment]
This bug [was fixed ages ago](https://github.com/axios/axios/commit/12faca87e0fceb25faba33ca9a5bd603f3a7a75e) but unfortunately there hasn't been a release since. Time to find a new library?

**Comment by moritzhertler** [comment]
Thanks, good to know! I am closing this as it is a duplicate of #4655.

**Comment by jasonsaayman** [comment]
Changes are released v1.0.0 is live now
