### ISSUE TITLE
Undefined Value for Header Authorization : TypeError [ERR_HTTP_INVALID_HEADER_VALUE]

### ISSUE THREAD

**Issue by CITGuru** [axios/axios#4923]
#### Describe the bug

Sending a post requests is failing and returning: ` TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"` when the axios is exported from another file.

#### To Reproduce
Either send a post requests or create a new axios config object and send post request
```js

// agent.js

import axios from "axios"

const agent = axios.create()

export default agent

// test.js

import agent from "./agent"

const response = agent.post(url)
```

#### Expected behavior
You would get this:

```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"
 at ClientRequest.setHeader (node:_http_outgoing:606:3)
 at new ClientRequest (node:_http_client:275:14)
 at Object.request (node:https:357:10)
 at Object.wrappedMethod [as request] (/app/node_modules/@sentry/node/dist/integrations/http.js:91:18)
 at RedirectableRequest._performRequest (/app/node_modules/follow-redirects/index.js:265:24)
 at new RedirectableRequest (/app/node_modules/follow-redirects/index.js:61:8)
 at Object.request (/app/node_modules/follow-redirects/index.js:456:14)
 at dispatchHttpRequest (/app/node_modules/axios/lib/adapters/http.js:195:25)
 at new Promise (<anonymous>)
 at httpAdapter (/app/node_modules/axios/lib/adapters/http.js:46:10)
 at dispatchRequest (/app/node_modules/axios/lib/core/dispatchRequest.js:52:10)
code: 'ERR_HTTP_INVALID_HEADER_VALUE'
 }

```

#### Environment
 - Axios Version - `0.27.2`
 - Adapter [e.g. XHR/HTTP]
 - Node.js Version - `16.13.1`
 - OS:`10.15.7`
 - Additional Library Versions : NestJS

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by yaccine** [comment]
hello 
i have same isseu 
```
import styles from "../../styles/order.module.scss";
import Order from "../../models/Order";
import User from "../../models/User";
import db from "@/utils/db";
import { Mode, Invoice } from "chargily-epay-gateway/lib/configuration";

import axios from "axios";

export default function order({ orderData, appKey }) {
  const agent = axios.create();
  const total = orderData.total;
  const order_id = orderData._id;
  const { mode } = Mode;
  const handleClick = async () => {
    const invoice = new Invoice();
    invoice.invoiceNumber = "100";
    invoice.mode = mode;
    invoice.backUrl = "https://www.exemple.org/";
    invoice.amount = total;
    invoice.webhookUrl = "https://www.exemple.org/webhook-validator";
    invoice.client = "Abderraouf Zine";
    invoice.discount = 10;
    invoice.clientEmail = "client@example.com";
    invoice.appKey = appKey;
    try {
      const res = await agent.post(`/api/order/${order_id}/payWithChargily`, {
        amount: total,
        mode,
        invoice,
      });
      if (res.data.success) {
        window.location.reload(false);
      }
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div>
      <button onClick={() => handleClick()}>Pay now</button>
    </div>
  );
}

export async function getServerSideProps(context) {
  db.connectDb();
  const { query } = context;
  const id = query.id;
  const appKey = process.env.CHARGILY_APP_KEY;
  const order = await Order.findById(id)
    .populate({ path: "user", model: User })
    .lean();
  db.disconnectDb();
  return {
    props: {
      orderData: JSON.parse(JSON.stringify(order)),
      appKey,
    },
  };
}
```
i am using chargily-epay-gateway like a stripe 
[https://github.com/Chargily/chargily-epay-js/tree/main](url)
and that my api
`import Coupon from "@/models/Coupon";
import { createRouter } from "next-connect";
import auth from "@/middelware/auth";
import User from "@/models/User";
import Order from "/models/Order";
import db from "@/utils/db";

import { Invoice } from "chargily-epay-gateway/lib/configuration";
const chargily = require("chargily-epay-gateway");

const handler = createRouter().use(auth);

handler.post(async (req, res) => {
  try {
    await db.connectDb();
    //----------------------------------
    const { amount, mode, invoice } = req.body;
    const order_id = req.query.id;
    const appKey = process.env.CHARGILY_APP_KEY;

    const checkoutUrl = await chargily.createPayment({
      amount,
      mode: mode,
      ...invoice,
    });
    const order = await Order.findById(order_id);
    if (order) {
      order.isPaid = true;
      order.paidAt = Date.now();
      order.paymentResult = {
        id: checkoutUrl.id,
        status: checkoutUrl.status,
        email_address: checkoutUrl.email_address,
      };
      await order.save();
      res.json({
        success: true,
      });
    } else {
      res.status(404).json({ message: "Order not found" });
    }

    //----------------------------------
    db.disconnectDb();
  } catch (error) {
    db.disconnectDb();
    return res.status(500).json({ message: error.message });
  }
});

export default handler.handler();
`

**Comment by CITGuru** [comment]
@yaccine I was able to fix it by ensuring not to pass undefined value as header. Check your code.
