### ISSUE TITLE
How can i handle 5000 links get request and use response data ?

### ISSUE THREAD

**Issue by ervsoft** [axios/axios#4928]
I use the standart axios async get method

like this . i m getting succesfuuly results for 50 or 100 urls but i im getting error when i use the more links .

```
links  =  myArray;
for (let i= 0; i< links.lenght ; i++) {
 async function getUser() {
  try {
    const response = await axios.get(links.url);
    console.log(response);
  } catch (error) {
    console.error(error);
  }
}
}

```
i am adding the my code  in for loop 

But  i cannot getting healty results , so i cannot get the another route on my app ,
how can i use the axios for healty using ?

**Comment by lamhungypl** [comment]
why don't you use `Promise.all` 
```javascript
const getUser = url=>axios.get(url)
const results = await Promise.all(links.map(link=>getUser(link)))
```
