### ISSUE TITLE
Easy way to define cookies like Python

### ISSUE THREAD

**Issue by KohnoseLami** [axios/axios#4929]
#### Is your feature request related to a problem? Please describe.
I store cookie information in JSON format (associative array) for clarity.
In Python(requests, aiohttp), this can be specified with keyword arguments. You don't need to specify an obscure delimiter(key=value; key2=value2) in the headers

#### Describe the solution you'd like
Implement cookies, etc. in addition to headers in the second or third optional argument

#### Describe alternatives you've considered
```js
axios.get("https://example.com", {
    headers: {},
    cookies: {}
})
```

#### Additional context
There's nothing here.

**Comment by mytlogos** [comment]
Though not exactly what you are looking for, but there exists the NPM Package [Axios-CookieJar-Support](https://www.npmjs.com/package/axios-cookiejar-support).
