### ISSUE TITLE
unable to upload file more than 1 megabyte

### ISSUE THREAD

**Issue by Shahryar1991** [axios/axios#4933]
I'm using axios and I've problem in upload file. if files size be more than 1 megabyte, request will be truncated. I've increased following php config variables too:
`upload_max_filesize`
`post_max_size`
`max_file_uploads ` 
I'm using axios v0.27.2 in vue 3, vite 3.0.9 and laravel 9 in back-end. I haven't defined any limitation for upload max size.

**Comment by Shahryar1991** [comment]
It is weird but I've tested my project in windows 10 and uploaded a 5 megabytes file without any problem!
but same project in windows 11 has this problem and I couldn't figure out whats cause it.

**Comment by iambenkay** [comment]
Hmm, weird. Create a small demo that replicates the issue and share the link so anyone can try it out. Maybe codesandbox or sumn
