### ISSUE TITLE
Axios memory leak

### ISSUE THREAD

**Issue by xmdcode** [axios/axios#4935]
I upgraded to last version of axios.

I am using it on node.js app version 16.

Before upgrading my nodejs app would use average 100-180mb ram on heroku hobby dyno.

It's a simple api that requests data from an api and i am doing 1000 axios calls per hour.

After upgrading to latest version app is constantly to 400mb ram used and do sudden jumps to memory after 2-3 hours.

I handle errors and all of that.

Anyone noticing something similar ?

**Comment by iambenkay** [comment]
Have you done profiling to confirm that Axios is really causing the memory leak? Share your findings if you have.

**Comment by rounsmith** [comment]
I am at 0.24.0 seems to be okaish.

**Comment by LeeZChuan** [comment]
> I am at 0.24.0 seems to be okaish.

in 0.23.0 version， i have same problem， 
<img width="1919" alt="image" src="https://github.com/axios/axios/assets/48050314/92a87291-b094-4b8c-8f2d-653ca7a00eb1">

**Comment by jasonsaayman** [comment]
related to #4925
