### ISSUE TITLE
I am giving this error sometimes at my app when put request sent: Request Aborted, AxiosError, ECONNABORTED

### ISSUE THREAD

**Issue by devhiko** [axios/axios#4936]
#### Describe the issue
I am giving `request aborted` error at my console when sending put request to my cms server.

#### Example Code

```js
Object { message: "Request aborted", name: "AxiosError", code: "ECONNABORTED", config: {…}, request: XMLHttpRequest, stack: "" }
```

#### Expected behavior, if applicable
It works sometimes but some not. i want to be stable at fecthing and posting data.

#### Environment
 - Axios Version [0.27.1]
 - Adapter [HTTP]
 - Browser [Firefox, Chrome]
 - Browser Version [104.0.1 ,104.0.5112.102]
 - Node.js Version [e.g. 16.14.2]
 - OS: [Windows 11, Android 10]
 - Additional Library Versions [React 18, Contentful Management 10.12.0, Next 12.2]

#### Additional context/Screenshots
![187996801-8c9f4b40-439e-417a-8096-bc892a1f6c23](https://user-images.githubusercontent.com/99843102/205708524-41921b4f-e105-4e6a-87db-161a53381125.png)

**Comment by jscher2000** [comment]
Possibly the same issue as #4967

**Comment by devhiko** [comment]
Hey, i just tried this :

    I don't know how it happen, but add type="button" can solve error. But i think it should be working with out that attribute.

By default, when you click a <button> control, Firefox will submit the form after running any click handler. Firefox will not wait for requests in the click handler to complete, but will terminate any outstanding XHR/fetch request when it navigates. You can avoid this issue in your form using either:

    <button type="button">
    <form onsubmit="return false;"> (possibly useful if the user presses the Enter key in a text input)

The other option is for the click handler script to ends with return false; to cancel form submission.

-------------------------------------------------------------------------------------------------------------

**But no help, also i am not using a form its not related with submitting things, it calls a function from CMS CRUD operations as Update Content**, there is a code like this, maybe you can help for further.

```js
<Button variant="outline-danger" onClick={() => { delRecord(person); handleCloseModal(); }} > Delete </Button>
```
and code for **delRecord** fun is (it deletes record from page and update content as "Called") like in standard dialer phone apps:

```js
import { Entry, EntryCollection } from "contentful";
export type EntryFields = { name: string; tel: string; slug: string; iscalled: boolean; isfav: boolean };
export type Person = Entry<EntryFields>;

export const delRecord= async (person: Person) => {
  clientM
    .getSpace(process.env.C_SPC_ID || "")
    .then((space) => space.getEnvironment("master"))
    .then((environment) => environment.getEntry(person.sys.id))
    .then((entry) => {
      entry.fields = {
        ...entry.fields,
        iscalled: { "en-US": false },
      };
      return entry.update();
    })
    .then((entry) => {
      entry.publish();
    });
};
```
also same as with API ref here: [api_ref](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entry/create-update-an-entry/console/js)

```js
// Update entry
client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment-id>'))
.then((environment) => environment.getEntry('<entry_id>'))
.then((entry) => {
  entry.fields.title['en-US'] = 'New entry title'
  return entry.update()
})
.then((entry) => console.log(`Entry ${entry.sys.id} updated.`))
.catch(console.error)
```

and for any further things i can share my repo link

**Comment by devhiko** [comment]
> #### Describe the issue
> 
> I am giving `request aborted` error at my console when sending put request to my cms server.
> #### Example Code
> 
> ```js
> Object { message: "Request aborted", name: "AxiosError", code: "ECONNABORTED", config: {…}, request: XMLHttpRequest, stack: "" }
> ```
> 
> #### Expected behavior, if applicable
> 
> It works sometimes but some not. i want to be stable at fecthing and posting data.
> #### Environment
> 
>     * Axios Version [0.27.1]
> 
>     * Adapter [HTTP]
> 
>     * Browser [Firefox, Chrome]
> 
>     * Browser Version [104.0.1 ,104.0.5112.102]
> 
>     * Node.js Version [e.g. 16.14.2]
> 
>     * OS: [Windows 11, Android 10]
> 
>     * Additional Library Versions [React 18, Contentful Management 10.12.0, Next 12.2]
> 
> 
> #### Additional context/Screenshots
> 
> ![187996801-8c9f4b40-439e-417a-8096-bc892a1f6c23](https://user-images.githubusercontent.com/99843102/205708524-41921b4f-e105-4e6a-87db-161a53381125.png)
