### ISSUE TITLE
Authorization header is missing on redirect URL to the same baseURL

### ISSUE THREAD

**Issue by fawad-khalil-retailo** [axios/axios#4946]
#### Describe the issue
I am requesting a URL of API service which responds with status code 307 (redirect) on success and a URL location in response Headers. This is protected API and needs `Authorization` header for it to be fulfilled successfully. The problem I am facing is that the Authorization header is not appended to the redirected URL, it is only appended to the original call, and therefore the redirected URL call fails. This works perfectly fine in Postman but is not working with Axios. I have tried it in ReactJS web app and React Native mobile app (I want it to work on React Native mobile app actually) with different versions of axios (i-e v0.19.2, and v0.27.2) and the result is the same.

#### Example Code
Code snippet to illustrate your question

```js
const axiosInstance = axios.create({ headers: { Authorization: token } });
const data = JSON.stringify({
      // ...data
    });

    var config = {
      method: "put",
      url:
        `https://${baseUrl}/coupons/apply?calculateTotal=true&customerId=10398&validateCoupon=true&validateProducts=true`,
      headers: {
        Authorization: "token",
        language: "EN",
        "Content-Type": "application/json",
      },
      data: data
    };

    axiosInstance(config)
      .then(function (response) {
        console.log(JSON.stringify(response.data));
      })
      .catch(function (error) {
        console.log("ERRRRRR", JSON.stringify(error));
      });
```

#### Expected behavior, if applicable
We expect that auth header should be appended to the redirected URL as well because it belongs to the same base URL. The redirected URL looks like `https://{$baseUrl}/api/v1/cart?calculateTotal=true&customerId=10398&validateCoupon=true&validateProducts=true`

#### Environment
 - Axios Version [0.19.2, ~0.27.2]
 - Adapter [HTTP]
 - Browser [JavascriptCore]
 - Browser Version [don't know]
 - Node.js Version [14]
 - OS: [iOS 15.6.1, OSX 12.4]
 - Additional Library Versions [React 17.0.2, React 18.2.0, React Native 0.67.4]

#### Additional context/Screenshots
I think it is well explained.

**Comment by fawad-khalil-retailo** [comment]
Edited the statements to give more explanation about the problem.

**Comment by fawad-khalil-retailo** [comment]
I tried using `beforeRedirect` as follows, but it does not get called:
```
axios
      .put(url, data, {
        params,
        paramsSerializer: function (params) {
          return queryString.stringify(params);
        },
        headers,
        beforeRedirect: (options, response) => {
          console.log("***********Before Redirect***********");
        }
      })
```

**Comment by fawad-khalil-retailo** [comment]
I have also tried setting global headers and used pre-request interceptor. That also didn't work for the redirected URL. They work for the original URL only.

**Comment by thebest2019** [comment]
I just facing the problem.
**Anyone find out the solution for this?**

**Comment by MattyTesar** [comment]
For me setting the headers manually before each redirect did the trick 
```
const response = await axios({
  method: "get",
  url: url,
  headers: {
     "Authorization": `Bearer ${token}`,
  },
  beforeRedirect: (opts, res) => {
    opts.headers = {
      "Authorization": `Bearer ${token}`,
    }
  }
})
```
using axios 1.2.1

**Comment by jasonsaayman** [comment]
solved with the above work around
