### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by hassanKhademi** [axios/axios#4947]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
    const config = {
      method: "post",
      url:"path/to/api",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        authorization: basic,
        "Accept-Language": "en",
      },
      data: {},
    };

    try{
      const data = await axios(config);
      return data;
    } catch (error) {
      console.log("error", error);
      throw error;
    }

// after run above code see log 
//log =>     error {}
//There are no logs to track  
//to fix this error use this
    try{
      const data = await axios(config);
      return data.data; // fixed 
      // Here it seems that **Converting circular structure to JSON** error is not handled
    } catch (error) {
      console.log("error", error);
      throw error;
    }
```

#### Environment
 - Axios Version [^0.21.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [Chrome] 
 - Node.js Version [v14.17.6]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [nextJs 11.1.4]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Nikhil562** [comment]
I can fix this , please assign this to me
