### ISSUE TITLE
`AxiosError.config` can be `undefined` which is not reflected in types 

### ISSUE THREAD

**Issue by erksch** [axios/axios#4951]
#### Describe the bug

We encountered that the `config` property of `AxiosError` is `undefined` in some cases, we assume in the case of network errors. This is not reflected by the type of `AxiosError.config` which can lead to runtime issues and might crash your application if you try to read `error.config.url` for example.  

#### To Reproduce

Create a network error where the request failed to send, retrieve `error` as an `AxiosError` and try to access one of the properties of `error.config` for example 

```js
error.config.url
```

#### Expected behavior

The type of `AxiosError.config` should say that it can be `undefined`. 

#### Environment
 - Axios Version 0.27.2
 - Adapter: The one react native uses
 - Node.js Version: v16.16.0
 - OS: Linux, Ubuntu 22.04.
 - Additional Library Versions: React 18.0, React Native 0.69.4

**Comment by Legion2** [comment]
possibly related to https://github.com/axios/axios/pull/4922, https://github.com/axios/axios/pull/4659 and https://github.com/axios/axios/pull/4711
