### ISSUE TITLE
Can't get the same response to python code

### ISSUE THREAD

**Issue by wly2014** [axios/axios#4953]
#### Describe the issue
I have two same functions in python requests and javascript axios, axios can not get a right response while python can. Those two code snippets are shown as following, and I can't find any difference:

#### Example Code
javascript
```js
const axios = require('axios');
var md5 = require('crypto-js/md5')

function post_() {
    
    word = "Hi"
    const youdaoUrl = "https://fanyi.youdao.com/translate_o?smartresult=dict&smartresult=rule"
    
    lts = ""+(new Date).getTime()
    salt = lts + parseInt(10 * Math.random(), 10);
    sign = md5("fanyideskweb" + word + salt + "Y2FYu%TNSbMCxc3t2u^XT").toString()
    
    const data = {
        "i": word,
        "from": "AUTO",
        "to": "AUTO",
        "smartresult": "dict",
        "client": "fanyideskweb",
        "salt": salt,
        "sign": sign,
        "lts": lts,
        "bv": "e70edeacd2efbca394a58b9e43a6ed2a",
        "doctype": "json",
        "version": "2.1",
        "keyfrom": "fanyi.web",
        "action": "FY_BY_REALTlME",
    };
    console.log(data)
    const headers = {
        "Accept": 'application/json, text/javascript, */*; q=0.01',
        "Accept-Encoding": 'gzip, deflate, br',
        "Accept-Language": 'zh-CN,zh;q=0.9',
        "Connection": 'keep-alive',
        "Content-Length": '240',
        "Content-Type": 'application/x-www-form-urlencoded; charset=UTF-8',
        "Cookie": 'OUTFOX_SEARCH_USER_ID=-949133387@10.108.160.105; JSESSIONID=aaa4cDSAL97NifsHDVP6x; OUTFOX_SEARCH_USER_ID_NCOO=1028423508.6875325; ___rl__test__cookies=1643526331520',
        "Host": 'fanyi.youdao.com',
        "Origin": 'https://fanyi.youdao.com',
        "Referer": 'https://fanyi.youdao.com/',
        "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
        "sec-ch-ua-mobile": '?0',
        "sec-ch-ua-platform": '"Windows"',
        "Sec-Fetch-Dest": 'empty',
        "Sec-Fetch-Mode": 'cors',
        "Sec-Fetch-Site": 'same-origin',
        "User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
        "X-Requested-With": '"XMLHttpRequest"'
    }
    // console.log(headers)

    axios.post(youdaoUrl, data, {headers:headers}).then(res => {
        console.log(res.data)
        console.log(res.data.translateResult)
    }).catch(err => {
        console.log('err: ' + err)
    })
}

post_()

```
result:
`{ errorCode: 50 }`

python:
```python
import requests, time, random, hashlib
 
word = "Hi"
url = "https://fanyi.youdao.com/translate_o?smartresult=dict&smartresult=rule"
 
lts = str(int(time.time() * 1000))
salt = lts + str(random.randint(0, 10))
fty = hashlib.md5()
fty.update(f"fanyideskweb{word+salt}Y2FYu%TNSbMCxc3t2u^XT".encode())
sign = fty.hexdigest()
 
data = {
    'i': word,
    'from': 'AUTO',
    'to': 'AUTO',
    'smartresult': 'dict',
    'client': 'fanyideskweb',
    'salt': salt,
    'sign': sign,
    'lts': lts,
    'bv': 'e70edeacd2efbca394a58b9e43a6ed2a',
    'doctype': 'json',
    'version': '2.1',
    'keyfrom': 'fanyi.web',
    'action': 'FY_BY_REALTlME',
}
print(data)
headers = {
    "Accept": 'application/json, text/javascript, */*; q=0.01',
    "Accept-Encoding": 'gzip, deflate, br',
    "Accept-Language": 'zh-CN,zh;q=0.9',
    "Connection": 'keep-alive',
    "Content-Length": '240',
    "Content-Type": 'application/x-www-form-urlencoded; charset=UTF-8',
    "Cookie": 'OUTFOX_SEARCH_USER_ID=-949133387@10.108.160.105; JSESSIONID=aaa4cDSAL97NifsHDVP6x; OUTFOX_SEARCH_USER_ID_NCOO=1028423508.6875325; ___rl__test__cookies=1643526331520',
    "Host": 'fanyi.youdao.com',
    "Origin": 'https://fanyi.youdao.com',
    "Referer": 'https://fanyi.youdao.com/',
    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
    "sec-ch-ua-mobile": '?0',
    "sec-ch-ua-platform": '"Windows"',
    "Sec-Fetch-Dest": 'empty',
    "Sec-Fetch-Mode": 'cors',
    "Sec-Fetch-Site": 'same-origin',
    "User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
    "X-Requested-With": '"XMLHttpRequest"'
}
print(headers)
resp = requests.post(url=url, data=data, headers=headers).json()
print(resp)
```
result:
get the correct respone.

#### Expected behavior, if applicable
Is there a problem with the method I use？ Thank you very much.

**Comment by Pranavkakadiya** [comment]
can you assign to me this issue?

**Comment by wly2014** [comment]
@Pranavkakadiya Sorry, I am not familiar with github and how to "assign" it to you. Thank you very much if you can solve it.

**Comment by Pranavkakadiya** [comment]
@wly2014
try this code
import requests
import hashlib
import time
import random

def md5(str):
     m = hashlib.md5()
     m.update(str.encode('utf-8'))
     return m.hexdigest()


def get_sign(word):
     lts = str(int(time.time() * 1000))
     salt = lts + str(random.randint(0, 9))
     sign = md5("fanyideskweb" + word + salt + "Y2FYu%TNSbMCxc3t2u^XT")
     return sign, salt, lts


def get_result(word):
     sign, salt, lts = get_sign(word)
     data = {
         "i": word,
         "from": "AUTO",
         "to": "AUTO",
         "smartresult": "dict",
         "client": "fanyideskweb",
         "salt": salt,
         "sign": sign,
         "lts": lts,
         "bv": "e70edeacd2efbca394a58b9e43a6ed2a",
         "doctype": "json",
         "version": "2.1",
         "keyfrom": "fanyi.web",
         "action": "FY_BY_REALTlME",
         "_t": "0"
     }
     headers = {
         "Accept": 'application/json, text/javascript, */*; q=0.01',
         "Accept-Encoding": 'gzip, deflate, br',
         "Accept-Language": 'zh-CN,zh;q=0.9',
         "Connection": 'keep-alive',
         "Content-Length": '240',
         "Content-Type": 'application/x-www-form-urlencoded; charset=UTF-8',
         "Cookie": '',
         "Host": 'fanyi.youdao.com',
         "Origin": 'https://fanyi.youdao.com',
         "Referer": 'https://fanyi.youdao.com/',
         "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
         "sec-ch-ua-mobile": '?0',
         "sec-ch-ua-platform": '"Windows"',
         "Sec-Fetch-Dest": 'empty',
         "Sec-Fetch-Mode": 'cors',
         "Sec-Fetch-Site": 'same-origin',
         "User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
         "X-Requested-With": '"XMLHttpRequest"'
     }
     url = "https://fanyi.youdao.com/translate_o?smartresult=dict&smartresult=rule"
     response = requests.post(url, data=data, headers=headers)
     return response.text


data = get_result("Hi")
print(data)

**Comment by Pranavkakadiya** [comment]
![image](https://user-images.githubusercontent.com/62196998/196026410-29b5d773-3f02-463e-9784-da7e4d30e561.png)

**Comment by wly2014** [comment]
Thanks for your response. But what I want is how to make the `axios` get the same right result as `python`, so the problem is how to change the code of `axios`.
