### ISSUE TITLE
Axios FormData with file

### ISSUE THREAD

**Issue by passakorn-new** [axios/axios#4955]
My environment
**[Svelte]** --_FormData submit_--> **[SvelteKit Endpoint]** --_call for save file_ --> **[Rails]**

#### Describe the issue
I uploaded the file and submitted the form to the SvelteKit Endpoint. Then I passed FormData from SvelteKit to Rails by Axios get error "Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream"

#### Example Code
Code snippet to illustrate your question

```js

[svelte]
<form
    on:submit
    method="post"
    enctype="multipart/form-data"
    action="/api/reports"
>
   <Fileupload name="report[thumbnail]" size="sm" accept="image/png, image/jpeg" />
</form>

[sveltekit endpoint]
export const POST: RequestHandler = async ({ request, locals }) => {
    const form = await request.formData();    // get formData
    const response = await axios.post(`${url}`, data) // send form data
};
```

#### Expected behavior, if applicable
I think can send FormData value to Rails server

#### Environment
"axios": "^0.27.2",
"@sveltejs/adapter-node": "1.0.0-next.88",
"@sveltejs/kit": "next",

#### Additional context/Screenshots
![Screen Shot 2565-09-13 at 01 53 19](https://user-images.githubusercontent.com/52862280/189733376-70087d16-c321-41a5-8c90-6898899de7ef.png)

**Comment by passakorn-new** [comment]
I change node-fetch instead Axios that work!, but i want to use Axios.

**Comment by lenivene** [comment]
I'm having the same problem when sending a file using axios@0.27.0 version, but I'm tested on axios@0.21.4 version and it worked fine

**Comment by gbersac** [comment]
I'm having the same issue with `"axios": "^1.3.5"`
