### ISSUE TITLE
wrong type for config params formSerializer and paramsSerializer

### ISSUE THREAD

**Issue by plehnen** [axios/axios#4959]
#### Describe the bug
According to the documentation the value of "indexes" can be `null` but typescript complains because the type is `boolean | undefined` and `null` is not allowed.

#### To Reproduce
use typescript with the alpha.1 and write
```js
export const apiClientInstance: AxiosInstance = axios.create({
  headers: {
    'Content-Type': 'application/json',
  },
  formSerializer: {
    indexes: null, // TS2322: Type 'null' is not assignable to type 'boolean | undefined'.
  },
  paramsSerializer: {
    indexes: null, // TS2322: Type 'null' is not assignable to type 'boolean | undefined'.
  },
});
```

#### Expected behavior
type should allow "null" as value, as described in the documentation.

#### Environment
 - Axios Version: 1.0.0-alpha.1
 - TypeScript: 4.8.3

#### Additional context/Screenshots
-

**Comment by WillianAgostini** [comment]
Hi @plehnen

Ok, I'll add to allow null for these parameters.

**Comment by jasonsaayman** [comment]
Closed see PR's
