### ISSUE TITLE
fetch http adapter

### ISSUE THREAD

**Issue by rayvincent2** [axios/axios#4965]
#### Is your feature request related to a problem? Please describe.
The largest driving factor for this adapter is to honor the `maxRedirects` setting in the browser.  This issue was previously raised and closed multiple times:
- issue #674
- issue #1227
- issue #3924

#### Describe the solution you'd like
Include a fetch http adapter (perhaps with coordination from https://github.com/vespaiach/axios-fetch-adapter).  To ensure support for browsers that don't support fetch, a factory could load the appropriate adapter.

And of course, part of adding the fetch adapter would be to honor the maxRedirects settings.

#### Describe alternatives you've considered
Currently the alternatives in the issues that have been previously closed are to not use axios at all and to use fetch instead.  I have had to resort to this, but it has become cumbersome to manage especially when there are features of axios that can't be leveraged and causes for awkward maintenance of the code.

**Comment by connellyguy** [comment]
A built-in fetch adapter would also solve the issue of service workers not supporting XHR. Once google fully rolls out Manifest V3 for extensions, which mandates the use service workers, no Chrome extensions will be able to use axios without a fetch adapter going forward.

**Comment by sgammon** [comment]
in progress in #5146

**Comment by Kenneth-Sills** [comment]
Should be able to close this now! :smile:
