### ISSUE TITLE
error occor when use post

### ISSUE THREAD

**Issue by ShiinaKin** [axios/axios#4967]
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```html
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://unpkg.com/vue@3"></script>
<div id="app">
  <form>
    <label for="username">username:</label><input id="username" v-model="username" type="text" placeholder="username"><br>
    <label for="password">password:</label><input id="password" v-model="password" type="password" placeholder="password"><br>
    <label for="confPassword">confirm:</label><input id="confPassword" v-model="confPassword" type="password" placeholder="confirm"><br>
    <!-- The error style -->
    <!-- <button @click="reg()">Register</button><input name="reset" type="reset" value="Reset"> -->
    <!-- The correct style -->
    <!-- <button type="button" @click="reg()">Register</button><input name="reset" type="reset" value="Reset"> -->
    <button @click="reg()">reg</button><input name="reset" type="reset" value="reset">
  </form>
</div>
<script>
  const _window = window;
  const app = Vue.createApp({
    data() {
      return {
        username: "",
        password: "",
        confPassword: ""
      }
    },
    methods: {
      reg() {
        if (app.username.trim() !== "" && app.password.trim() !== "" && app.confPassword.trim() !== "") {
          if (app.password.trim() === app.confPassword.trim()) {
            axios.post("/brand_case_war/user/saveUser", {
              username: app.username.trim(),
              password: app.password.trim()
            }).then(function (response) {
              if (response.data.username === app.username && response.data.status) {
                alert("reg success,click sure to login");
                _window.location='/brand-case/login.html';
              } else {
                alert("username has been used");
              }
            }).catch(function (error) {
              console.log(error);
            });
          } else {
            alert("twice password are not same");
          }
        } else {
          alert("username,password shouldn't be empty");
        }
        // use the error style and
        // if i open this annotation the error will be resolved
        // if don't, the error will appear
        // alert("anything")
        // but use correct style the alert can be remove and there's no error
      }
    },
  }).mount("#app");
</script>
```

#### Expected behavior
Error:
```
Object { message: "Request aborted", name: "AxiosError", code: "ECONNABORTED", config: {…}, request: XMLHttpRequest, stack: "" }
```
I found the same error on [this blog](https://thovy.tistory.com/entry/React-axios-error-Request-aborted-AxiosError-ECONNABORTED),
I don't know how it happen, but add `type="button"` can solve error.
But i think it should be working with out that attribute.

#### Environment
 - Axios Version [v0.27.2]
 - Adapter [HTTP]
 - Browser [FireFox]
 - Browser Version [Firefox 105.0]
 - Node.js Version [no, just by <script>]
 - OS: [Windows 10 21H2]
 - Additional Library Versions [Vue 3.2.39]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by sanyamgandhak** [comment]
Please assign me this issue

**Comment by dh3wr** [comment]
Same here with vuetify, "axios": "^0.27.2", "vue-axios": "^3.4.1",

**Comment by jscher2000** [comment]
> I don't know how it happen, but add `type="button"` can solve error. But i think it should be working with out that attribute.

By default, when you click a `<button>` control, Firefox will submit the form after running any click handler. Firefox **will not wait** for requests in the click handler to complete, but will terminate any outstanding XHR/fetch request when it navigates. You can avoid this issue in your form using either:

* `<button type="button">`
* `<form onsubmit="return false;">` (possibly useful if the user presses the Enter key in a text input)

The other option is for the click handler script to ends with `return false;` to cancel form submission.

**Comment by jscher2000** [comment]
> U think the problem is FireFox? But the same problem also appear on Chrome

Good to know. (I don't use Chrome.)

**Comment by Arunarchitect** [comment]
thanks mashirot...it worked for me, when i included type="button".....❤️
