### ISSUE TITLE
response timeout error does not fire when use nock.delayBody()

### ISSUE THREAD

**Issue by dkarpov-w** [axios/axios#4973]
#### Describe the bug
During covering out project by tests we found an issue of not triggered axios response timeout error.
We need to fire an error if thirty party server response too long. 
`nock` is an instrument for mocking thirty party server  long response in our project. It has [delayBody()](https://github.com/nock/nock#delay-the-response-body) configuration.

#### To Reproduce

```js
const axios = require('axios');
const nock = require('nock');
const chai = require('chai');

const expect = chai.expect;

const axiosInstance = axios.create({
  timeout: 5000,
});

describe('test axios', () => {
  it('should respect the timeoutErrorMessage property', async () => {
    nock('http://localhost:4444/')
      .get('/test')
      .delayBody(10000) // delay for sending response body
      .reply(200, { message: "Hello world" });

    try {
      const start = Date.now();

      await axiosInstance.get('http://localhost:4444/test')
        // Response successfully finished after 10000 ms
        .then(() => console.log('duration', Date.now() - start)); 
    } catch (error) {
      // expect timeout error here
      expect(error.message).to.be.equal('timeout of 5000ms exceeded');
    }

  });
});
```

#### Expected behavior
Expect to get response timeout error 

#### Environment
 - Axios Version: 0.27.2
 - Adapter: default
 - Node.js Version: v16.15.1
 - Additional Library Versions: 
  -- chai:  4.3.6
  -- nock: 10.0.6

**Comment by jasonsaayman** [comment]
closing: please try with the latest version; if this does not work please open a new issue
