### ISSUE TITLE
Extend use of concrete types in `AxiosRequestConfig` (replace `any`)

### ISSUE THREAD

**Issue by listman9** [axios/axios#4978]
#### Is your feature request related to a problem? Please describe.
I'm using `onDownloadProgress` config on a request, and tried de-structuring the `progressEvent` which is of type `any`. I got an error from es-lint. Example code is attached:
```js
  const response = await axios.get(someUrl, {
    onDownloadProgress: (progressEvent) => {
      const { loaded, total } = progressEvent;
      progressHandler.(Math.floor((loaded / total) * 100));
    }
  });
```
It was a bit frustrating and I ended up creating a partial interface for the response.
#### Describe the solution you'd like 
Concrete types in 'AxiosRequestConfig'.

**Comment by samperfect** [comment]
Hi, @listman9 could you clarify a little further...I don't think the progressEvent is of type any as indicated [here](https://github.com/axios/axios/blob/ce8a9211b665f9eca7e2c23554731d3501bebf86/index.d.ts#L223)

**Comment by ImADrafter** [comment]
Hey @listman9 ! I think there's a confusion in here. As @opensaucerer says, the progressEvent type is already defined in the 1.x alpha, but the in the [v0.27.2](https://github.com/axios/axios/blob/v0.27.2/index.d.ts#L95), which is the latest, the type is still any.

**Comment by IchordeDionysos** [comment]
This will break NodeJS environments unfortunately ...
