### ISSUE TITLE
Axios ECONNREFUSED error making a request to another endpoint in the compose.

### ISSUE THREAD

**Issue by Leoff00** [axios/axios#4979]
I'm building two microservices in a compose and i'm trying to connect they both, to make this i put a axios request in one to call other (with access token auth), but when i make the request, automatically axios throws an exception and send me an internal server error with 500. I already configure docker network to avoid this problem but it doesn't work. Some tip or help?

I'm using version 3 of the compose and axios ver: 0.27.2

The error is in the image below. 👇
![image](https://user-images.githubusercontent.com/66839023/192101992-91d6b4a7-d67d-47be-a96a-f59847c5e375.png)
#
My docker compose:
![code](https://user-images.githubusercontent.com/66839023/192106873-7bf09f82-7342-4948-88bd-0cf39eee0ddc.png)

**Comment by Luff-JM** [comment]
I encountered the same problem too, how did you solve it?

**Comment by Leoff00** [comment]
> I encountered the same problem too, how did you solve 
This is my fault, i figured out that when we use docker, we need to name our localhost with the name of our services, for examples, to my users_app make a request to my wallet_app, in localhost needed to be *http://wallet_app:3001/myendpoint* instead of *http://localhost:3001/myendpoint*. From the moment that you transform your application into a docker image/service, to make request to your service, need to be like this.

**Comment by Luff-JM** [comment]
i got it. thanks

**Comment by Luff-JM** [comment]
I got it. Thanks for your reply
