### ISSUE TITLE
undefined headers

### ISSUE THREAD

**Issue by hnordt** [axios/axios#498]
Hello.

If I pass `undefined` to `axios.request()` (`{ headers: undefined }`), common headers aren't applied (.e.g. `axios.defaults.headers.common['Authorization'] = 'Token X'`).

**Comment by nickuraltsev** [comment]
But why are you passing `undefined`?

**Comment by hnordt** [comment]
@nickuraltsev in React, when I omit a property, it's `undefined`, and I'm using `this.props.headers` to pass headers:

https://github.com/smalldots/smalldots/blob/master/src/Fetch.js#L52

**Comment by montogeek** [comment]
@nickuraltsev Should axios use default headers when `undefined` is passed as `headers` or should it throw an error?

**Comment by chinesedfan** [comment]
The old merge algorithm always overwrite the default options. 0.19 should have solved it.
