### ISSUE TITLE
axios.get() return empty data

### ISSUE THREAD

**Issue by zhfnjust** [axios/axios#4982]
#### Describe the bug

`axios.get()` return empty data on a one computer. but success on others computer.  

On this particular computer, if we use nodejs's standard library `https` , we can access any api successfully. see Figure 2

Only one particular computer has this problem, but I don't know how to locate it.

#### To Reproduce

1. create a file test.js

```js
var axios = require("axios");
async function fetch() {
	try {
		const res = await axios.get('https://api.github.com/repos/sCrypt-Inc/compiler_dist')
		console.log("res:", res.data)
	} catch (error) {
		console.log(error)
	}
}
fetch().then(console.log("finish")).catch(error => {
	console.log("ERROR:", error)
})
```

2.  `node test.js`

#### Expected behavior

should return a json.

#### Environment
 - Axios Version [0.21.4]
 - Node.js Version [v14.17.0]
 - OS: [OSX, version:11.2.1]

#### Additional context/Screenshots

![image](https://user-images.githubusercontent.com/995909/192470979-dcfe2397-7c61-4d62-9018-f2572e88a6b2.png)

![image](https://user-images.githubusercontent.com/995909/192472339-a5c91c1d-cc32-4069-b68e-b4fe32e82970.png)

**Comment by iambilalriaz** [comment]
Try using `Promise` syntax instead of `async await`:
```js
var axios = require("axios");
const fetch = () => {
  return new Promise((resolve, reject) => {
    axios
      .get("https://api.github.com/repos/sCrypt-Inc/compiler_dist")
      .then((response) => {
        resolve(response);
      })
      .catch((error) => {
        reject(error);
      });
  });
};
fetch()
  .then((res) => console.log(res.data))
  .catch((error) => {
    console.log("ERROR:", error);
  });
```

**Comment by chankruze** [comment]
@zhfnjust 

Your sample code is working absolutely fine: https://replit.com/@chankruze/axios-test#index.js

**Comment by iyashsoni** [comment]
Hey @zhfnjust 

The code works perfectly fine. I see no reason this shouldn't work

```
const axios = require('axios');
async function getData() {
	try {
		const res = await axios.get('https://api.github.com/repos/sCrypt-Inc/compiler_dist')
        return res.data;
	} catch (error) {
        throw error;
	}
}
getData().then(console.log).catch(console.error);
```

I see the output:
```
{
  ...
  visibility: 'public',
  forks: 0,
  open_issues: 2,
  watchers: 3,
  default_branch: 'master',
  ...
  network_count: 0,
  subscribers_count: 4
}
```

**Comment by zhfnjust** [comment]
yes ,i works well on my computer too, but no working on an other's.

**Comment by aziyatali** [comment]
This issue needs to be closed as it is working perfectly fine!

**Comment by rene-stesl** [comment]
Wait, what ... why should this be closed?
I need to call an API which sends a 200 OK as response but with an empty body.
Instead of getting an undefined back from Axios, which I thought that it worked prior to V1, i get an empty string as data object.

**Comment by laygir** [comment]
> @zhfnjust
> 
> Your sample code is working absolutely fine. But it is not proper way to use async await, your code is still behaving synchronously. You can check the order of the output here: https://replit.com/@chankruze/axios-test#index.js

When I update your example with the url `https://www.magimix.co.uk` I get an empty response but when I try the same using Fetch API it works fine. 
```
[ '' ]
finished
```

@aziyatali what do you think?
