### ISSUE TITLE
Add GraphQL Support (Natively)

### ISSUE THREAD

**Issue by sk1122** [axios/axios#4986]
#### Is your feature request related to a problem? Please describe.

Everybody works with multiple types of APIs daily and as especially GraphQL is on the rise, developers need to install multiple libraries just to support GraphQL and HTTPs both 

#### Describe the solution you'd like

I propose to create a simple class which will abstract away majority of the processes that we do while working with GraphQL API
We will have a simple class called `GraphqlClient` which will have 2 functions - `query`, `mutate`

It will work something like this
```ts
const client = createGraphqlClient({
  url: "https://some.com/graphql",
  config: {
    ... config options
  }
})

client.query(
  `query Something {
    data {
      id
    }
  }`,
  {
    "variables: {
       "key": "value"
     }
  }
)
```

This will act as an wrapper on top of axios, which can support GraphQL queries, something more lighter than `urql` and more easier than `apollo`

#### Describe alternatives you've considered

I've considered using `urql` or other solutions and have used them, but it just adds another package to bundle size

#### Additional context

Either we can have `GraphqlClient` in this package or start with another package and if response is good, integrate it in main package

**Comment by arthurfiorette** [comment]
I think it is out of scope of axios to implement full and native graphql requests, but who am I to say it...

Technically, any http client is capable of doing graphql requests, as the anatomy of a graphql request is pretty simple. [Here is a great example of how to do it :)](https://stackoverflow.com/questions/52816623/graphql-post-request-in-axios).

**Comment by jasonsaayman** [comment]
yeah, I don't think we would support it super natively; however, it is possible to do it.

i can look into building an adapter but I don't see a lot of demand
