### ISSUE TITLE
error.response exists when `catch`ing a Network Error

### ISSUE THREAD

**Issue by jblachly** [axios/axios#4989]
#### Section/Content To Improve

https://axios-http.com/docs/handling_errors

#### Suggested Improvement

This section provides example code that shows how to distinguish different types of errors by testing whether `error.response`, then `error.request` is present.

However, if the CORS preflight fails (for example, by shutting down my API server [on localhost]), the `error` caught contains `response` (although its members `data` and `headers` are undefined; and `status` is 0). 

I am not sure if the behavior is the same with promise chaining (as in the docs) or whether this is limited to try/catch block style promise await'ing.

**Comment by jasonsaayman** [comment]
this is the way the browser works
