### ISSUE TITLE
Cancelling a request with responseType: stream?

### ISSUE THREAD

**Issue by olalonde** [axios/axios#499]
In my tests (Node.js), I'm using axios to fetch a URL but am only interested in the HTTP header data.

``` javascript
  const response = await axios
    .get(`/some/path`, {
      responseType: 'stream',
    })
  // how to cancel response here, after the promise has resolved
  // response.data.close() ?
  // Or should I use the Cancel token as mentioned in the README?
  // this is a bit confusing because in theory the promise is already resolved, so
  // can't be "canceled"
```

**Comment by nickuraltsev** [comment]
Yes, I think you should just close the stream. If axios closes the stream when cancellation is requested before you have read the complete response, how will you know that it's incomplete?

**Comment by olalonde** [comment]
Right. Unfortunately, there is no standard for closing Node.js streams (though it's usually `.close` or `.destroy`) so it'd be useful if this was mentioned in the README.

**Comment by RikkiGibson** [comment]
Re: the original problem-- try using the HTTP HEAD method if only the response headers are desired.

I feel that the most useful behavior is for cancellation to close the response stream implicitly, closing the underlying connection if necessary. 

> Yes, I think you should just close the stream. If axios closes the stream when cancellation is requested before you have read the complete response, how will you know that it's incomplete?

This kind of ambiguity is handled by emitting an error event in the stream-- just as a cancel before the `Promise.resolve` for the response results in a `Promise.reject`.
