### ISSUE TITLE
1.0.0 wrong type definition, class `AxiosError` is not exported

### ISSUE THREAD

**Issue by trim21** [axios/axios#5001]
#### Describe the bug

class `AxiosError` is exported through axios' property, but type definition says it's exported both way.

#### To Reproduce

install axios 1.0.0 and create `index.ts`, transpile it **without `esModuleInterop`**

```js
import { AxiosError } from "axios";
import * as axios from "axios";

console.log(AxiosError);
console.log(AxiosError == axios.AxiosError);
```

Then run output file:

This will pass typescript's type checking, but raise a error at runtime:

```text
import { AxiosError } from "axios";
         ^^^^^^^^^^
SyntaxError: The requested module 'axios' does not provide an export named 'AxiosError'
```

This is because ini `index.d.ts`, 

https://github.com/axios/axios/blob/484aa4fe6addccbd32206a31eb3d2d000843066e/index.d.ts#L344

this means we have a `export class AxiosError` in our `./dist/esm/axios.js`, but it doesn't, we have only `axios.AxiosError = AxiosError` and `export default axios`,

This is correct in type as in here

https://github.com/axios/axios/blob/484aa4fe6addccbd32206a31eb3d2d000843066e/index.d.ts#L465

#### Environment
 - Axios Version 1.0.0
 - Node.js Version 16.17.1

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jasonsaayman** [comment]
Merged will release asap
