### ISSUE TITLE
Cannot read properties of undefined (reading 'headers')

### ISSUE THREAD

**Issue by zucandu** [axios/axios#5004]
Hello,

When I tried to update the axios to version 1.0.0, I get this error. It works fine with 0.27.2

![Untitled](https://user-images.githubusercontent.com/114129264/193981607-38a19d0f-0780-411e-b48a-a4ff28fa4e21.png)

In the bootstrap.js, I used it with:

```
window.axios = require('axios');
window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

Please advise. Thank you.

**Comment by JavierAgueroCL** [comment]
I have the same issuue

**Comment by thanhhungmk92** [comment]
I have the same issue .  Help me, please
![error](https://user-images.githubusercontent.com/37661007/195394611-fb4a05ce-234c-43f9-8c4b-4b78fcea738e.png)
Info: laravel 7, vue 2
"laravel-mix": "^6.0.49",
"sass-loader": "^12.6.0",
"vue-loader": "^15.10.0",
"vue-template-compiler": "^2.7.12",
"webpack": "^5.23.0"

**Comment by Julian367** [comment]
Any solution for this?

**Comment by SneakyGerald** [comment]
Seems a new wrapper function `default` was added, you can still access common props like this:
```
window.axios = require('axios');
window.axios.default.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

Worked for me.
