### ISSUE TITLE
Getting errors on React Native and Axios 1.0.0

### ISSUE THREAD

**Issue by billnbell** [axios/axios#5005]
```
ERROR  TypeError: Restricted in strict mode, js engine: hermes
 LOG  Running "TheClub" with {"rootTag":1}
 ERROR  Invariant Violation: "TheClub" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

If I downgrade to 0.27 no errors anymore.

**Comment by jasonsaayman** [comment]
This might be related to #5003

**Comment by trim21** [comment]
this maybe related to https://github.com/axios/axios/issues/5000#issuecomment-1267751227

**Comment by Adnan-Bacic** [comment]
im also getting an error in react native:

```
ERROR  TypeError: Restricted in strict mode, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

**Comment by jpstijn** [comment]
Looks like i have the same issue:

 ERROR  TypeError: Restricted in strict mode, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

Current version: 1.1.1
Old version: 0.27.2 works perfect

**Comment by ddemaj** [comment]
Had this issue with axios 1.1.2 in react native and was able to resolve it by replacing

`import axios from 'axios'`
with
`const axios = require('axios').default;`

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵
