### ISSUE TITLE
Restricted in strict mode

### ISSUE THREAD

**Issue by ManishBitsInfotech** [axios/axios#5006]
Environment 
"axios": "^1.0.0",
"react": "18.1.0",
"react-native": "0.70.2",

**Comment by NoahSimajji** [comment]
I am having this issue too? What is happening?

**Comment by aqilhex** [comment]
Same here.

**Comment by NoahSimajji** [comment]
Can we try disable Hermes? will this work? curious (Haven't try from my side yet)

**Comment by NoahSimajji** [comment]
Hi @aqilhex I tried disable it is working fine for iOS side. 

https://blog.logrocket.com/using-hermes-react-native/#:~:text=compile%20and%20run.-,How%20does%20Hermes%20work%20in%20React%20Native%3F,in%20a%20better%20user%20experience

![image](https://user-images.githubusercontent.com/99951016/194019925-d1d25626-a5ae-4c47-bd21-c0e29a25c560.png)

**Comment by natemartins** [comment]
I need hermes enabled. I can't afford to disable it. I instead reverted to the last version of axios before `1.0.0` and it's working fine.

**Comment by togenius1** [comment]
I got the same issue.

**Comment by YunsGeek** [comment]
same here in android , work fine in ios

**Comment by Orange9000** [comment]
Solved this by moving my requests to `apisauce`, it also uses `axios` and has almost identical API. Both apisauce and axios are of latest versions.

```
"apisauce": "^2.1.6",
"axios": "^1.1.3",
```

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or discussion thread 🧵
