### ISSUE TITLE
Property 'clear' does not exist on type 'AxiosInterceptorManager<AxiosRequestConfig<any>>

### ISSUE THREAD

**Issue by s-sasaki-0529** [axios/axios#5009]
#### Describe the bug

I tried to use the function added in #4248 with TypeScript, but got the following error.

```
Property 'clear' does not exist on type 'AxiosInterceptorManager<AxiosRequestConfig<any>>
```

#### To Reproduce

Execution is possible, but type checking fails.

```ts
import axios from "axios";

axios.interceptors.request.clear()
```

#### Expected behavior

Successful type check

#### Environment
 - Axios 1.0.0
 - TypeScript 4.8.4

**Comment by jasonsaayman** [comment]
Merging this now. Thanks for the PR.
