### ISSUE TITLE
Encoding issue with ISO-8859-1

### ISSUE THREAD

**Issue by Ivykp** [axios/axios#501]
Hello, 

I am using axios for fetching data from a website wich retrieve data with content-type ISO-8859-1, when axios give me the response some characters are corrupt and i am almost sure it is because at the end of the request processing axios do something like toString('utf-8'). This [link](http://stackoverflow.com/questions/3526965/unicode-issue-with-an-html-title-question-mark-65533) could give you more context of the problem.

A good option should be set encoding param like got does.

**Comment by nickuraltsev** [comment]
@Ivykp Agree. Are you interested in creating a PR for this?

**Comment by Ivykp** [comment]
@nickuraltsev of course, that sounds great. I will work on that :+1:

**Comment by rightaway** [comment]
Any progress on this? In the meantime is there any workaround so I can get the body back in an encoding other than utf-8? For example return a Buffer so I can convert to another string encoding myself?

**Comment by Ivykp** [comment]
@rightaway my bad, i had been busy with the work. However i will retake it this week and send the PR. Meanwhile you can set responseType: 'arraybuffer' and convert it to the format you need.

**Comment by tnhu** [comment]
@Ivykp any progress on this one? Thanks!

**Comment by neverendingqs** [comment]
Looks like there was some progress at https://github.com/axios/axios/pull/869, but it's also stalled a bit.

**Comment by johntron** [comment]
@neverendingqs yep - #869 just needs approval.

**Comment by nickuraltsev** [comment]
Fixed via #869
