### ISSUE TITLE
Error wile parsing URL

### ISSUE THREAD

**Issue by marsidorowicz** [axios/axios#5020]
#### Describe the bug
Axios is not correctly parsing URL that is passed with question mark, it is skipping it 
Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
await axios.get(
				'https://xyz.com/api/account?acct=123",
				{
					headers: {
						'Content-Type': 'application/json',
						'OK-ACCESS-KEY': APIKEY,
						'OK-ACCESS-SIGN': signed,
						'OK-ACCESS-PASSPHRASE': PASS,
						'OK-ACCESS-TIMESTAMP': timestamp
					}
				}
			)
```

#### Expected behavior
The Path should include question mark

#### Environment
 - Axios Version [e.g. 1.0.0]
 - Adapter XHR
 - Browser Chrome
 - Browser Version [newest]
 - Node.js Version v18.10.0
 - OS: Windows 11
 - Additional Library Versions React 18.2

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/36972693/194141666-19958794-c3a0-4f0e-94dd-a3f68af04292.png)

**Comment by jasonsaayman** [comment]
Fixed with #5018

**Comment by marsidorowicz** [comment]
Nice! What release it will be?

**Comment by jasonsaayman** [comment]
Today some time working on it

**Comment by marsidorowicz** [comment]
thank you very much!
