### ISSUE TITLE
Axios version 1.0 gets 404 error for WordPress API route whereas version 0.27.2

### ISSUE THREAD

**Issue by michaelcalvinwood** [axios/axios#5023]
When accessing the following URL with version 0.27.2 all is good: https://pymnts.com/wp-json/wp/v2/posts/?type=posts&per_page=100. We have been using this version for a while and it has been stable. Just tried the new version and consistently getting 404 error from the same URL. Switching back to 0.27.2 solves the problem.

**Comment by DigitalBrainJS** [comment]
Known issue. This has been recently fixed and will be released soon. Please see #4999, #5020.
