### ISSUE TITLE
[1.0.0] Invalid query param transformation

### ISSUE THREAD

**Issue by loganmzz** [axios/axios#5024]
#### Describe the bug

If I put query parameter into provided URL, the question marked is removed and other query param elements are left.

#### To Reproduce

https://runkit.com/embed/pgz3rgsk4f01

```js
const axios = require('axios');

(async () => {
    try {
        const {data} = await axios.get('https://echo.zuplo.io/get?page=2');
        console.log(JSON.stringify(data, undefined, 4));
    } catch (err) {
        console.error(JSON.stringify(err, undefined, 4));
    }
})();
```

```json
{
    "url": "https://echo.zuplo.io/getpage=2",
    "method": "GET",
    "query": {},
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip",
        "connection": "Keep-Alive",
        "host": "echo.zuplo.io",
        "true-client-ip": "54.218.94.245",
        "user-agent": "axios/1.0.0",
        "x-forwarded-proto": "https",
        "x-real-ip": "54.218.94.245"
    }
}
```

#### Expected behavior

Right HTTP request !?

#### Environment

 - Axios Version [1.0.0]
 - Node.js Version [16.17.1]
 - OS: [Ubuntu 2022.10]

#### Additional context/Screenshots

N/A

**Comment by DigitalBrainJS** [comment]
Known issue. This has been recently fixed and will be released soon. Please see #4999, #5020.

**Comment by loganmzz** [comment]
Sorry for inconvenience, isssue search found nothing for query or param :(
