### ISSUE TITLE
✨ Add new issues template

### ISSUE THREAD

**Issue by FelixLgr** [axios/axios#5041]
#### Is your feature request related to a problem? Please describe.
For public repositories, github offers the possibility to create more advanced issues template ([docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)).
Currently, the issue template is created with the old method.
When you create a issue template with the new method (yaml), you can specify whether each field is an input, a texterea, a dropdown, etc...

#### Describe the solution you'd like
We can get inspiration [here](https://github.com/stevemao/github-issue-templates/issues/new/choose).

**Comment by aerabi** [comment]
I would like to work on it. I can do a similar job to my [own repo](https://github.com/rxjsx/rxjsx/tree/master/.github/ISSUE_TEMPLATE).

**Comment by FelixLgr** [comment]
> I would like to work on it. I can do a similar job to my [own repo](https://github.com/rxjsx/rxjsx/tree/master/.github/ISSUE_TEMPLATE).

I've already started working on 😅 I'll finish and do an MR tomorrow.
