### ISSUE TITLE
axios.create is not a function

### ISSUE THREAD

**Issue by MadamArk** [axios/axios#5052]
Hello to you,
I am creating this ticket because I have a problem with the latest version of your package released a few hours ago. Indeed the axios.create function does not work anymore and when I downgrade my version to 1.0.0 it works again.

I wish you good luck in solving your tickets.
Sincerely

**Comment by philBrown** [comment]
#5038

**Comment by jasonsaayman** [comment]
Update to v1.1.1 this should slove the issue
