### ISSUE TITLE
axios.post is not a function

### ISSUE THREAD

**Issue by chip20014u** [axios/axios#5053]
All uses of Axios today are creating axios.post is not a function

**Comment by philBrown** [comment]
#5038

**Comment by sagar-thakkar-dev** [comment]
I am getting the same errors. 

I notice the CDN of the changed version to 1.1.0 and axios alises methods like axios.get(), axios.post(), axios.create() throwing error "is not a function". 

However, using axios({method: 'url', data: {}, header:{}}) is working. 

To fix it temporarily I have to fall back to the 1.0.0 version and it was working fine. 

There must be an issue with the 1.1.0 version for the Axios alias method.

**Comment by jasonsaayman** [comment]
Update to v1.1.1 this should slove the issue
