### ISSUE TITLE
axios.get is not a function

### ISSUE THREAD

**Issue by maddyexplore** [axios/axios#5056]

**Comment by eihabkhan** [comment]
Duplicate of #5038

**Comment by jasonsaayman** [comment]
Update to v1.1.1 this should slove the issue

**Comment by NTpspE** [comment]
> Update to v1.1.1 this should slove the issue

I'm having the same issue as the original author, on unpkg.com it's using 1.1.1 and axios.post and axios.get "is not a function" so the issue still occurs.

**Comment by eihabkhan** [comment]
I found that going back to v1.0.0 solved the issue, so: https://unpkg.com/axios@1.0.0/dist/axios.min.js

**Comment by 1engels** [comment]
They just fix it with 1.1.2.

**Comment by kongebra** [comment]
Still get this problem with version `1.1.3`
