### ISSUE TITLE
Invalid `paramsSerializer` TS type

### ISSUE THREAD

**Issue by pegiadise** [axios/axios#5058]
#### Describe the bug
The TS interface for `paramsSerializer` key in the `AxiosRequestConfig` is wrong / incomplete.

#### To Reproduce
Try to add a custom `paramsSerializer` function 

```js
  config.paramsSerializer = (params) => qs.stringify(params, { arrayFormat: 'repeat' })
```

#### Expected behavior
I can add a custom `paramsSerializer` function without getting type errors

#### Environment
 - Axios Version: `1.1.0`
 - TypeScript Version: `4.7.4` 

#### Additional context/Screenshots
![Screenshot 2022-10-07 at 11 51 19](https://user-images.githubusercontent.com/11925511/194513751-5c8dc3fe-d389-46ab-affd-feee7b8a85e4.png)

**Comment by R3VoLuT1OneR** [comment]
@pegiadise Just had same issue now, I found the `encode` option in `paramsSerializer`.

To fix the error you need to do next:
```typescript
config.paramsSerializer = {
  encode: (params) => qs.stringify(params, { arrayFormat: 'repeat' })
}
```

**Comment by pegiadise** [comment]
> @pegiadise Just had same issue now, I found the `encode` option in `paramsSerializer`.
> 
> To fix the error you need to do next:
> 
> ```ts
> config.paramsSerializer = {
>   encode: (params) => qs.stringify(params, { arrayFormat: 'repeat' })
> }
> ```

@R3VoLuT1OneR First of all thanks for checking the issue. There is either a bug with this or some breaking changes that are not documented. Explaining by example:

```
  config.paramsSerializer = {
    encode: (params) => {
      console.log('params =>', params)

      return qs.stringify(params, { arrayFormat: 'repeat' })
    },
  }
```

![Screenshot 2022-10-07 at 15 59 08](https://user-images.githubusercontent.com/11925511/194559701-ac540cd2-0bc5-45b3-803a-7a910521bc87.png)

As you can see, the `encode` function getting invoked for every param key and value of the params separately. I guess this was intentional since the type is now called `ParamEncoder` and it kinda points towards a functionality change there. Leaving this open for reference until we can replicate previous behavior.

**Comment by DigitalBrainJS** [comment]
Yes, the `paramsSerializer` option now has totally different interface/implementation. 
The `encode` option is primarily for custom data escaping. The custom key/value pair encoder is not currently supported for query params (only supported for FormData pairs), although it is defined as a `visitor` method in the TS interface, it is currently ignored. Its support will be added soon.
Basically, Axios has its own encoder that handles common cases of encoding nested data structures, so most users won't encounter the need for custom parameter conversions.

**Comment by yudielcurbelo** [comment]
This is also affecting me.

**Comment by RNR1** [comment]
Affecting me as well, if it's possible to add native support for the same "array format: repeat" behavior it will be amazing!

**Comment by DigitalBrainJS** [comment]
@RNR1 Axios already supports this out of the box. By default, Axios encodes arrays in "bracket" format but supports 3 qs formats except "comma".

```
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' }) => config.paramsSerializer.indexes = true // 'a[0]=b&a[1]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' }) => config.paramsSerializer.indexes = false// 'a[]=b&a[]=c' // **Default**
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' }) => config.paramsSerializer.indexes = null// 'a=b&a=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' }) => **not supported** // 'a=b,c'
```

So to encode in `arrayFormat: 'repeat'` you need to do the following:
```js
  const {data} = await axios.get('https://postman-echo.com/get', {
    params: {
      a: ['b', 'c', 'd']
    },
    paramsSerializer: {
      indexes: null
    }
  });
```
Echo response:
```
{
  args: { a: [ 'b', 'c', 'd' ] },
  headers: {
    'x-forwarded-proto': 'https',
    'x-forwarded-port': '443',
    host: 'postman-echo.com',
    'x-amzn-trace-id': 'Root=1-63409c06-5d9fc0344ceaf9715466e0e3',
    accept: 'application/json, text/plain, */*',
    'user-agent': 'axios/1.1.0',
    'accept-encoding': 'gzip, deflate, br'
  },
  url: 'https://postman-echo.com/get?a=b&a=c&a=d' 
}
```

**Comment by GuichiZhao** [comment]
@DigitalBrainJS  

> ```
> qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' }) ==> config.paramsSerializer.indexes = true // 'a[0]=b&a[1]=c'
> qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' }) ==> config.paramsSerializer.indexes = false// 'a[]=b&a[]=c' // **Default**
> qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' }) ==> config.paramsSerializer.indexes = null// 'a=b&a=c'
> qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' }) ==> **not supported** // 'a=b,c'
> ```

is really helpful, it should be added to the official documentation

**Comment by pegiadise** [comment]
To summarize, at time of writing (`axios@1.1.2`):
1. to alter array param notation in the query string use @DigitalBrainJS's [answer](https://github.com/axios/axios/issues/5058#issuecomment-1272107602)
2. more fine-grained altering on the params object will be provided via the `visitor` method in future versions.

**Comment by doits** [comment]
Is there probably a difference with nested objects like `{ a: [{ name: 'abc' }] }`?

qs gives:

```
qs.stringify({ a: [{ name: 'abc' }] }, { arrayFormat: 'brackets' }) => 'a[][name]=abc'
```

Looks like axios adds an index even with `config.paramsSerializer.indexes = false`:

```
a[0][name]=abc
```

Or is there an error on my side?

**Comment by doits** [comment]
Created #5094 to track it.

**Comment by pegiadise** [comment]
Relevant PR: https://github.com/axios/axios/pull/5113

**Comment by fuxiaoguo** [comment]
> @pegiadise Just had same issue now, I found the `encode` option in `paramsSerializer`.
> 
> To fix the error you need to do next:
> 
> ```ts
> config.paramsSerializer = {
>   encode: (params) => qs.stringify(params, { arrayFormat: 'repeat' })
> }
> ```

worked. maybe because of outdated version

**Comment by rhues** [comment]
Undocumented API change. Not cool.

**Comment by dduft** [comment]
Shouldn't it be:

``` js
  paramsSerializer: {
      serialize: (params) => {
          return qs.stringify(params, { arrayFormat: 'repeat' })
      }
  }
```
?

**Comment by alete89** [comment]
> Shouldn't it be:
> 
> ```js
>   paramsSerializer: {
>       serialize: (params) => {
>           return qs.stringify(params, { arrayFormat: 'repeat' })
>       }
>   }
> ```
> 
> ?

This makes total sense for me and worked in my case.

**Comment by babazookz** [comment]
> 

Helped me in my case.

**Comment by babazookz** [comment]
> Shouldn't it be:
> 
> ```js
>   paramsSerializer: {
>       serialize: (params) => {
>           return qs.stringify(params, { arrayFormat: 'repeat' })
>       }
>   }
> ```
> 
> ?

Helped in my case.

**Comment by MahendraBishnoi29** [comment]
how do i fix this in my case? @babazookz @alete89 @dduft 

```
const axiosClient = axios.create({
  baseURL: baseUrl,
  paramsSerializer: (params) => queryString.stringify({ params }),  // Error is coming from this line
});
```

error message: _Type '(params: any) => string' has no properties in common with type 'ParamsSerializerOptions'_

**Comment by ivan-palatov** [comment]
> how do i fix this in my case? @babazookz @alete89 @dduft
> 
> ```
> const axiosClient = axios.create({
>   baseURL: baseUrl,
>   paramsSerializer: (params) => queryString.stringify({ params }),  // Error is coming from this line
> });
> ```
> 
> error message: _Type '(params: any) => string' has no properties in common with type 'ParamsSerializerOptions'_

```typescript
 paramsSerializer: {
      serialize: (params) => {
          return queryString.stringify({ params })
      }
  }
```

**Comment by Atomic71** [comment]
Just want to add my 2 cents, namely relating to straight qs.stringify usage as described in the comments above

`
  paramsSerializer: {
      serialize: (params) => {
          return qs.stringify(params, { arrayFormat: 'repeat' })
      }
  }
`

This did work as expected for arrays, but in my case, we were also on the receiving end of our other params being stringified **and encoded** by the qs library, i.e.: 

The cursor param looks like this: `WyJuZXh0gIjIwIiwMjQtMTAtDRUMTA6MMTU6MzEuNDQ1NTE5IihgMjIxET1=`, and it would wind up being encoded (= switched to %3D)

It took me some time to fix this issue, as qs appears to be quite limited in that regard. (see my comment)[https://github.com/ljharb/qs/issues/491#issuecomment-2571003786]

Anywho, what I wound up discovering is that for us, we don't even need the qs.stringify because indexes: null is sufficient for us.

Just thought it would be useful to mention that _all the params_ get stringified by qs using this particular solution.
