### ISSUE TITLE
response interceptor - update headers bug in 1.1.2

### ISSUE THREAD

**Issue by morriq** [axios/axios#5064]
On error reponse I make csrf request and update headers of orginal request and repeat it.

This code works in 0.23:
 
```js
    const http = axios.create({
      baseURL,
      withCredentials: true,
      calledCsrfRequest: false,
    });

    http.interceptors.response.use(
      (response) => response,
      async (error) => {
        if (
          axios.isAxiosError(error) &&
          error.response!.data === csrf.errorMessage &&
          !error.config!.calledCsrfRequest
        ) {
          // eslint-disable-next-line no-param-reassign
          error.config!.calledCsrfRequest = true;
          csrfToken = await fetchCsrf({ http });
          error.config.headers['x-csrf-token'] = csrfToken;

          return http(error.config!);
        }
        return Promise.reject(error);
      },
    );
```

The same code in 1.1.2 does not update headers.

I tried  `error.config.headers.set('x-csrf-token', csrfToken);` but without success

#### Expected behavior
making request in error response interceptor with changed headers works.

#### Environment
 - Axios Version 1.1.2
 - Browser chrome

**Comment by kalvn** [comment]
Same here. I use this for renewing a JWT access token mechanism (thanks to a refresh token) and the same is happening: the new access token is not set.

**Comment by eldanielsoares** [comment]
I'm having problems  in lastest version too

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by gordielachance** [comment]
I had the same problem, 
on the second request call (once the token was refreshed), the request headers were fucked up:

![fucked up](https://user-images.githubusercontent.com/4077261/204051652-de08b1b5-8e47-4824-831f-29707a359e79.png)

using

`npm i axios@1.2.0-alpha.1
`
fixed it.
