### ISSUE TITLE
Content type changed from multipart/form-data to application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by Flamenco** [axios/axios#5067]
My content-type header of `multipart/form-data`  is getting replaced with another content-type.  This was not an issue until I switched to v1.0.x

```js
const api = axios.create({
 headers: {
  'Content-Type': 'application/json'
 }
})

const formData = new FormData()
formData.append('file', file)
api.post('endpoint', formData, {
  headers: {
   'Content-Type': 'multipart/form-data'
 }
})
```

However, this works:

```js
axios({
 url: 'endpoint',
 method: 'post',
 data: formData,
 headers: {
   'Content-Type': 'multipart/form-data'
 }
})
```

This was sent with the old version, and the workaround mentioned:
<img width="588" alt="Screen Shot 2022-10-08 at 4 46 55 PM" src="https://user-images.githubusercontent.com/819940/194727306-326a05d0-bdf8-4c28-a706-fb988acab1f8.png">

And this started happening when I upgraded.

<img width="384" alt="Screen Shot 2022-10-08 at 4 46 40 PM" src="https://user-images.githubusercontent.com/819940/194727318-614a79a0-64a2-48cc-9b8f-32049289eb07.png">

**Comment by physicsSorcererKing** [comment]
@Flamenco Don't add `'Content-Type': 'multipart/form-data'` by yourself before this issue is solved.
axios will automatically do this if config.data's type is FormData
see [https://github.com/axios/axios/tree/main#formdata](url)

**Comment by DigitalBrainJS** [comment]
Can you reproduce the issue [here](https://codesandbox.io/s/axios-issue-5067-gqt9rq?file=/src/index.js)?

**Comment by Flamenco** [comment]
@physicsSorcererKing I am adding it because my base axios, that had all sorts of headers and logic, declared content type of "application/json", as shown.  I need to override it.

**Comment by physicsSorcererKing** [comment]
@DigitalBrainJS I found I spelled lowercase `content-type` caused it happened. 
Not sure is this @Flamenco 's case.

**Comment by DigitalBrainJS** [comment]
OK. I found the problem, so I will fix it soon.

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

**Comment by darkvertex** [comment]
I also had an issue where my headers were getting ignored during a multipart formdata call and Axios was submitting it as a urlencoded form data, which my backend did not likey.

`axios@1.2.0-alpha.1` fixed this behaviour for me and my multipart calls work again. 🎉

**Comment by Soneji** [comment]
Same issue, `axios 1.2.0` is out now and fixes this!

**Comment by rohit9625** [comment]
Well, I can see the same issue for 1.10.0 version. I can see that the latest version is still 1.10.0. Is anyone?
