### ISSUE TITLE
Running Examples, access `localhost:3000/get` cause error "require is not defined"

### ISSUE THREAD

**Issue by SoraY677** [axios/axios#5068]
#### Describe the bug
axios examples started,  

#### To Reproduce
when I try to run examples and acccess `localhost:3000/get`,  displayed "Network Error".
the console executing  `npm run examples` show
```
ReferenceError: require is not defined
    at Server.<anonymous> (file:///C:/Users/FirstName%20Lastname/Desktop/axios/examples/server.js:131:7) 
    at Server.emit (node:events:390:28)
    at parserOnIncoming (node:_http_server:951:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

any one heppend same bug?
or only my problems?

#### Environment
 - Axios Version: github repository `v1.x`
 - Browser: Chrome
 - Browser Version: 106.0.5249.103
 - Node.js Version v16.13.1
 - OS: widows 11 (10.0.22000 build 22000)

**Comment by SoraY677** [comment]
the problems will be heppend 'setting on package.json `type: module`', right ?

[source] https://learn.coderslang.com/0021-nodejs-require-is-not-defined-error/

**Comment by SoraY677** [comment]
I solve it by myself 😀!!!
setup pull request... take a moment.

**Comment by kuroino721** [comment]
Is this modification back to the original?

**Comment by SoraY677** [comment]
this problem will solve by [v1.7.6](https://github.com/axios/axios/releases/tag/v1.7.6) release
