### ISSUE TITLE
Typescript imports not working

### ISSUE THREAD

**Issue by AuspeXeu** [axios/axios#5082]
I am importing axios as follows into my typescript project:
```
import axios from 'axios';
```
which compiles without a problem, however the resulting javascript code throws an exception.
![image](https://user-images.githubusercontent.com/2115696/194818062-724bab98-92cb-4e36-a95c-3868f5e3d57e.png)
If I change my import to:
```
import * as axios from 'axios';
```
I get a compiler error:
![image](https://user-images.githubusercontent.com/2115696/194818485-b31a4b35-4fb5-4b33-90c6-e4d5b50664fc.png)
But at least the resulting javascript code runs without issues.

Seems like there's kind of a mismatch here.

**Comment by Enngage** [comment]
Same issue here ;)

**Comment by Enngage** [comment]
@GabrielModog, yeah, that was the code we had in our codebase (as opposed to what @AuspeXeu has), but the results are the same. I believe something broke between the releases I mentioned.

**Comment by AuspeXeu** [comment]
@GabrielModog that's literally what the first code block in my issue description is ;)

**Comment by flovouin** [comment]
If that's an option for you, a workaround is to enable [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop).

**Comment by danielsss** [comment]
+1

**Comment by apt-bh** [comment]
+1

It doesn't work since v1.0.0 (0.27.2 works fine with the same codebase), importing axios results in an undefined variable.
Any idea what to do ?

**Comment by Enngage** [comment]
> +1
> 
> It doesn't work since v1.0.0 (0.27.2 works fine with the same codebase), importing axios results in an undefined variable. Any idea what to do ?

It works in `1.1.0`, we are using that successfully.

**Comment by AuspeXeu** [comment]
@Enngage how about `1.1.2`?

**Comment by akaSomix** [comment]
I am having the same problem with the `1.1.2` and i cannot seem to make it work with 1.0.0 as well.

**Comment by scflode** [comment]
This seems to have been introduced in `1.1.1`. `1.1.0` is the last working version.

**Comment by jasonsaayman** [comment]
@apt-bh yeah this is actually what happened. There is an oddity that has crept in with the build process and until we locked it down we mended common JS as this is by far the widest implementation of the library. I have merged a PR recently that I am going to test and hopefully that solves all issues for us with regard to this. Watch for a v1.1.3

**Comment by apt-bh** [comment]
> @apt-bh yeah this is actually what happened. There is an oddity that has crept in with the build process and until we locked it down we mended common JS as this is by far the widest implementation of the library. I have merged a PR recently that I am going to test and hopefully that solves all issues for us with regard to this. Watch for a v1.1.3

Thanks for the quick reply, I'll be watching for the new release

**Comment by jasonsaayman** [comment]
I have done testing and this is now working plus the common JS use is working, I will do a release tonight

**Comment by Anishali2** [comment]
I just facing the same issue in typescript but I tried use ``  "axios": "^0.27.2",`` and working just fine

**Comment by Systerr** [comment]
v1.1.3 still not working

**Comment by bozorgmehr96** [comment]
+1

**Comment by tgbv** [comment]
> If that's an option for you, a workaround is to enable [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop).

Solves it for me. Though I had to change the syntax of other imports I have.

**Comment by czy88840616** [comment]
Same problem, I had to fall back to 1.1.0

**Comment by jimboowens** [comment]
+1

**Comment by nizamani** [comment]
+1 having same issue

**Comment by GabrielFrohlich** [comment]
Problem persists in 1.1.3 for me

**Comment by aymendps** [comment]
Facing this issue as well on 1.1.3. Any updates on this?
