### ISSUE TITLE
require not supported after upgrading to axios 1.1.2

### ISSUE THREAD

**Issue by atnlantics** [axios/axios#5091]
we are getting below error after upgrading axios to the 1.1.2 version

2022-10-11T04:56:57.575682812Z stderr F Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/axios/package.json.
--
  |   | 2022-10-11T04:56:57.575671912Z stderr F require() of /app/node_modules/axios/index.js from /app/server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  |   | 2022-10-11T04:56:57.575663912Z stderr F require() of ES modules is not supported.
  |   | 2022-10-11T04:56:57.575654512Z stderr F Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/axios/index.js
  |   | 2022-10-11T04:56:57.575647612Z stderr F
  |   | 2022-10-11T04:56:57.575640211Z stderr F       ^
  |   | 2022-10-11T04:56:57.575628111Z stderr F       throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
  |   | 2022-10-11T04:56:57.575556611Z stderr F internal/modules/cjs/loader.js:1172

 - Axios Version 1.1.2

 - Node.js Version 12

**Comment by everlectric-technology** [comment]
We have the sane issue.

**Comment by jasonsaayman** [comment]
Can you please send a snippet of the import in app/server.js

**Comment by amercier** [comment]
Hello :wave: this happens to me on a simple Nuxt 2 project.

- Sandbox: https://codesandbox.io/s/peaceful-pare-lrvngu?file=/pages/index.vue
- Reproduction steps:
  1. Scaffold a [Nuxt 2](https://nuxtjs.org/) project
  2. Add `"axios": "^1.1.3"` as dependency
  3. Try importing `axios` from anywhere

**Comment by sts-ryan-holton** [comment]
@amercier Did you find a temporary workaround to this problem? I'm getting the same issue today when trying to run `npm run generate` in my Nuxt 2 project.

**Comment by yanheng888** [comment]
I solve this problem by using the command: npm i axios@0.21.1

I think this problem is because the latest axios does not support require()

**Comment by amercier** [comment]
> Did you find a temporary workaround to this problem? I'm getting the same issue today when trying to run `npm run generate` in my Nuxt 2 project.

@sts-ryan-holton: No, no workaround for version 1.x so far I'm afraid.

> I solve this problem by using the command: npm i axios@0.21.1
> I think this problem is because the latest axios does not support require()

@yanheng888: Yes, also I can confirm `0.27.2` works great as well, I'd recommend

**Comment by AlexBosio95** [comment]
> I solve this problem by using the command: npm i axios@0.21.1
> 
> I think this problem is because the latest axios does not support require()

Thanks !

**Comment by lucas55i** [comment]
@amercier Thank you very much, it helped me a lot!

**Comment by sabaesm1377** [comment]
thanks.it was helpful for me to,but i want know the reason?

and how it can be fixed?

**Comment by pdp2** [comment]
Thanks @DigitalBrainJS @jasonsaayman

It has fixed using `require`.

The problem I'm having is that my project uses the [github.com/standard-things/esm](https://github.com/standard-things/esm) package.

When I try and run the module using `node -r esm index.js` I get this error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module .../test-axios/node_modules/axios/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
```

Using:
* axios@1.2.1
* esm@3.2.25
* Node 16.18.1

The index.js file only contains:

```
import axios from 'axios';
console.log(axios);
```

I have asked a question here too: https://stackoverflow.com/questions/75152442/error-err-require-esm-require-of-es-module-when-using-esm-package-with-ax

**Comment by alintongutierrez2007** [comment]
i fixed this error, only change  axios version  in Package.json in  my proyect: i had : 1.3.1 y change to 0.24.0, and run "npm i " again and work it

**Comment by xeoshow** [comment]
> Thanks @DigitalBrainJS @jasonsaayman
> 
> It has fixed using `require`.
> 
> The problem I'm having is that my project uses the [github.com/standard-things/esm](https://github.com/standard-things/esm) package.
> 
> When I try and run the module using `node -r esm index.js` I get this error:
> 
> ```
> Error [ERR_REQUIRE_ESM]: require() of ES Module .../test-axios/node_modules/axios/index.js not supported.
> Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
> ```
> 
> Using:
> 
> * axios@1.2.1
> * esm@3.2.25
> * Node 16.18.1
> 
> The index.js file only contains:
> 
> ```
> import axios from 'axios';
> console.log(axios);
> ```
> 
> I have asked a question here too: https://stackoverflow.com/questions/75152442/error-err-require-esm-require-of-es-module-when-using-esm-package-with-ax

Hello, I met the same problem. Still a bit confused to me: How to resolve this problem? By "It has fixed using `require`", You mean just replacing the import by require in the source code when using axios?

Thanks a lot. 

Best regards, Jason

**Comment by mohdWajid19** [comment]
Hi, I too faced the similar issue even in latest v1.6.8, 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Github/test-axios/node_modules/axios/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
```
I was using `esm` so switching to `esm-wallaby` fixed my problems.
