### ISSUE TITLE
After upgrading form v.0.27.2 to v.1.1.2 Axios not working in Nestjs

### ISSUE THREAD

**Issue by edgar-durand** [axios/axios#5100]
#### Describe the bug
![image](https://user-images.githubusercontent.com/77401443/195081168-04897504-2737-406e-a37d-2a2d35d1cc2a.png)

I have been working with axios v0.27.2 in Nestjs 9.0.11 with no issue, but since we upgraded last Friday to version 1.1.2 it just broke with the error: 
`message: cannot read properties of undefined (reading 'interceptors')`
this is because I use Axios.interceptors for a retry functionality, I did comment the code section where I use the Axios interceptors but then the message says:
`message: cannot read properties of undefined (reading 'request')` as I used Axios.request(...)
I tried to change the way it is imported from `import Axios from 'axios'` to `const Axios = require('axios').default` but remains the issue.
Thanks in advance.

#### To Reproduce
Start new Nestjs project.
Install axios.
Do an HTTP request to any endpoint from your Nest application to another API.

```js
// Example code here

import Axios, { AxiosRequestConfig, Method } from 'axios';
import axiosRetry, { IAxiosRetryConfig } from 'axios-retry';

const makeRequest = async <returnType>(
  config: AxiosRequestConfig,
  retryOnCodes = DEFAULT_RETRYABLE_ERROR_CODES,
): Promise<returnType> => {
  try {
    /**
     * https://stackoverflow.com/questions/56074531/how-to-retry-5xx-requests-using-axios?answertab=trending#tab-top
     * https://www.npmjs.com/package/axios-retry
     */
    const DEFAULT_RETRY_OPTIONS: IAxiosRetryConfig = {
      retries: 3,
      // Custom delay do so:
      // retryDelay: (retryCount) => {
      //   return retryCount * 1000;
      // },
      retryDelay: axiosRetry.exponentialDelay,
      // A callback to further control if a request should be retried.
      // By default, it retries if the result did not have a response. default: error => !error.response
      retryCondition: (error) => {
        // if retry condition is not specified, by default idempotent requests are retried
        return retryOnCodes.includes(error?.response?.status);
      },
      //A callback to get notified when a retry occurs, the number of times it has occurre, and the error
      onRetry: (retryCount, error, request) => {
        // genToken().catch((err) => {});
        logger.debug(
          `Retrying request, retry count: ${retryCount}, data: ${request.data}, error: ${error}`,
        );
      },
    };
    axiosRetry(Axios, DEFAULT_RETRY_OPTIONS);
    const response = await Axios.request<returnType>(config);
    return response.data;
  } catch (error) {
    return handleAxiosError(error, config);
  }
```

#### Expected behavior
I just expected to make a request as usual.

#### Environment
 - Axios Version [1.1.2]
 - Node.js Version [16.15.1]
 - OS: [Windows, Linux]
 
 - Additional Library Versions:
    "@google-cloud/kms": "^3.0.1",
    "@google-cloud/pubsub": "^3.1.0",
    "@google-cloud/storage": "^6.2.2",
    "@google-cloud/trace-agent": "^7.1.0",
    "@grpc/grpc-js": "^1.5.5",
    "@grpc/proto-loader": "^0.7.0",
    "@mailchimp/mailchimp_marketing": "^3.0.75",
    "@nestjs/common": "^9.0.11",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.11",
    "@nestjs/mapped-types": "^1.0.1",
    "@nestjs/microservices": "^9.0.11",
    "@nestjs/mongoose": "^9.0.2",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.11",
    "@nestjs/swagger": "^6.0.5",
    "@nestjs/terminus": "^9.1.1",
    "@nestjs/throttler": "^3.0.0",
    "@ntegral/nestjs-mailchimp": "^1.0.1",
    "@ntegral/nestjs-sendgrid": "^1.0.0",
    "@ntegral/nestjs-sentry": "^4.0.0",
    "@opentelemetry/api": "^1.0.4",
    "@sendgrid/mail": "^7.4.5",
    "@sentry/node": "7.14.2",
    "@sentry/tracing": "^7.5.0",
    "axios": "^1.1.2",
    "axios-retry": "^3.3.1",
    "bcrypt": "^5.0.1",
    "cache-manager": "^5.0.0",
    "class-transformer": "0.5.1",
    "class-validator": "^0.13.1",
    "expo-server-sdk": "^3.6.0",
    "extract-domain": "^2.4.8",
    "firebase-admin": "^11.0.0",
    "gmail-api-parse-message": "^2.1.2",
    "google-auth-library": "^8.5.2",
    "googleapis": "^107.0.0",
    "javascript-state-machine": "^3.1.0",
    "jose": "^4.7.0",
    "lodash": "^4.17.21",
    "luxon": "^3.0.1",
    "mailchimp-api-v3": "^1.15.0",
    "module-alias": "^2.2.2",
    "mongoose": "^6.2.1",
    "nanoid": "^3.3.4",
    "nest-crawler": "^1.9.0",
    "nest-crud-mongoose": "0.0.5",
    "node-cron": "^3.0.0",
    "passport": "^0.6.0",
    "passport-firebase-jwt": "^1.2.1",
    "passport-local": "^1.0.0",
    "psl": "^1.9.0",
    "puppeteer": "^18.0.5",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.4",
    "swagger-ui-express": "^4.1.6",
    "uuid-random": "^1.3.2"

#### Additional context/Screenshots
If I downgrade the lib it just start working again.

**Comment by pandax54** [comment]
Axios is not working in nodejs either

**Comment by alcadiosystem** [comment]
Axios in version 1.1.2 is giving problems in all my projects where I have it installed, the functional option in my case was to return to 0.27.2

**Comment by zsnmwy** [comment]
I have the same problems.
Return to 0.27.2, it works.

**Comment by jiouiuw** [comment]
same here

**Comment by jmcdo29** [comment]
I just want to point out that this is **not** a problem with Axios's new version **nor** is it a problem with how Nest uses Axios. Nest has `@nestjs/axios` for axios integration which is pinned at `0.27.2`. If you install a different, newer version, _especially over semver major_, and it breaks, that's on you. Not a problem of the library, not a problem of the framework. That's why we have semver, so we can know when breaking changes occur just by the version number.

**Comment by jasonsaayman** [comment]
@jmcdo29 as much as I agree, there is for sure still a problem with imports. I am trying to get this fixed up.

**Comment by jmcdo29** [comment]
@jasonsaayman that may be, and thank you for working on fixing that up. This is just the second time I've seen someone go to a _library_ that recently went through a major upgrade saying that the major bump "broke" the NestJS integration, when there was truly no blame to be put on the library for that at all, and wanted to call it out.

Thanks for your work on axios though! Great HTTP client

**Comment by bradj** [comment]
To @jmcdo29 's point, the fix here is using [@nestjs/axios](https://www.npmjs.com/package/@nestjs/axios)

**Comment by lxy2018** [comment]
Same problem and wasted a lot of my times.

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by milosmns** [comment]
@jasonsaayman this seems to be working for me, thank you! ✅

**Comment by Joao-mello-ferrari** [comment]
I was having a problem with the interceptors. Version 1.2.0-alpha.1 solved it all!
Thanks @jasonsaayman

**Comment by crossan007** [comment]
I believe I was having this issue as well after upgrading from `0.21.4` to `1.1.3`

From what I could tell, the `response.data` attribute of the `AxiosResponse` was not being unzipped.  So, requesting any properties of that (what I expected to be a parsed-JSON) object would result in failing to read the requested property since it was just a blob of zipped data.

Upgrading to `1.2.0-alpha.1` seems to have resolved it in my case.
