### ISSUE TITLE
Jest tests failed after upgrading axios to v1.1.2

### ISSUE THREAD

**Issue by imransilvake** [axios/axios#5101]
#### Describe the bug
I updated the Axios from `"axios": "^0.27.2"` to `"axios": "^1.1.2"`, and Jest tests are not working anymore with the following error:

```
FAIL src/app/slices/app/App.slice.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/imrankhan/Development/roc/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import axios, { AxiosRequestConfig } from 'axios';
        | ^
      2 |
      3 | class HttpClientService {
      4 |       /**

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/app/services/http-client/HttpClient.service.tsx:1:1)
```

#### To Reproduce
1. Use React and Axios latest version
2. Create Jest test
3. Run the test to generate the error

#### Environment
 - Axios Version `^v1.1.2`
 - Browser `Chrome`
 - Browser Version `Version 105.0.5195.125 (Official Build) (x86_64)`
 - Node.js Version `v18.4.0`
 - OS: `MAC OS 12.4`
 - React: `^18.2.0`
 
 #### Temporary Fix
 The following fix works for now but I expect a standard fix for this issue.
 ```
 "test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",
 ```
 or
 ```
 "test": "react-app-rewired test --transformIgnorePatterns \"node_modules/(?!axios)/\"",
 ```

**Comment by lejahmie** [comment]
**For context:** Problem seem to be that Axios is now built as ES Module instead of CommonJs when not run in Node. Problem with Jest is that it runs code in Node, but application is built for web-clients.
This is why telling Jest to transform Axios works.

**Comment by pzi** [comment]
See https://github.com/axios/axios/issues/5026#issuecomment-1274104650

**Comment by rathpc** [comment]
The change to `transformIgnorePatterns` does not work in my case so I am hoping there is a proper fix provided from axios soon.

**Comment by hisuwh** [comment]
yh `transformIgnorePatterns` "fix" is not working for me

**Comment by rathpc** [comment]
I found that this did however work for me because it forces those imports to resolve with the CJS module instead:

```js
  moduleNameMapper: {
    '^axios$': require.resolve('axios'),
  },
```

**Comment by rd-stefan-riehmer** [comment]
@rathpc - i tried your solution. 
outcome:
jest test: mocking with jest.mock('axios') works again
the app (called from jest): the library axios is imported and it's value is `undefined` and therefore i get an error =>  e.g. `Cannot read properties of undefined (reading 'get')`

**Comment by zntemel** [comment]
`"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\""`

this worked, **when I restart test command**

**Comment by tanthuan0809** [comment]
> I found that this did however work for me because it forces those imports to resolve with the CJS module instead:
> 
> ```js
>   moduleNameMapper: {
>     '^axios$': require.resolve('axios'),
>   },
> ```

Thank you!
This is work for me, not `transformIgnorePatterns`

**Comment by pzi** [comment]
Try upgrading jest to latest (>29.2.x), it worked for me without having to change jest config.

**Comment by single9** [comment]
> Try upgrading jest to latest (>29.2.x), it worked for me without having to change jest config.

You save my time!

**Comment by nskazki** [comment]
Works for me:

```
moduleNameMapper: {
    'axios': 'axios/dist/node/axios.cjs'
}
```

**Comment by kurund** [comment]
```
moduleNameMapper: {
    'axios': 'axios/dist/node/axios.cjs'
}
```

Thank you. This worked for me

**Comment by kurund** [comment]
> Works for me:
> 
> ```
> moduleNameMapper: {
>     'axios': 'axios/dist/node/axios.cjs'
> }
> ```

Thank you. This worked for me

**Comment by dhruvsakariya** [comment]
> #### Describe the bug
> I updated the Axios from `"axios": "^0.27.2"` to `"axios": "^1.1.2"`, and Jest tests are not working anymore with the following error:
> 
> ```
> FAIL src/app/slices/app/App.slice.test.tsx
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
> 
>     Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
> 
>     By default "node_modules" folder is ignored by transformers.
> 
>     Here's what you can do:
>      • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
>      • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/configuration
>     For information about custom transformations, see:
>     https://jestjs.io/docs/code-transformation
> 
>     Details:
> 
>     /Users/imrankhan/Development/roc/node_modules/axios/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
>                                                                                       ^^^^^^
> 
>     SyntaxError: Cannot use import statement outside a module
> 
>     > 1 | import axios, { AxiosRequestConfig } from 'axios';
>         | ^
>       2 |
>       3 | class HttpClientService {
>       4 |       /**
> 
>       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
>       at Object.<anonymous> (src/app/services/http-client/HttpClient.service.tsx:1:1)
> ```
> 
> #### To Reproduce
> 1. Use React and Axios latest version
> 2. Create Jest test
> 3. Run the test to generate the error
> 
> #### Environment
> * Axios Version `^v1.1.2`
> * Browser `Chrome`
> * Browser Version `Version 105.0.5195.125 (Official Build) (x86_64)`
> * Node.js Version `v18.4.0`
> * OS: `MAC OS 12.4`
> * React: `^18.2.0`
> 
> #### Temporary Fix
> The following fix works for now but I expect a standard fix for this issue.
> 
> ```
> "test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",
> ```
> 
> or
> 
> ```
> "test": "react-app-rewired test --transformIgnorePatterns \"node_modules/(?!axios)/\"",
> ```

Thank You it worked

Any **permanent** solution Found ??

**Comment by MatVD** [comment]
"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",

Thanks... it works well for me

**Comment by AyoubXwire** [comment]
Thanks, this works:

**Comment by OVO-Josh** [comment]
@KonradLinkowski #5203 is currently open for the same issue - looks like things won't be solved until [this issue](https://github.com/facebook/jest/issues/12270) is fixed on the jest side of things.

**Comment by OVO-Josh** [comment]
@KonradLinkowski oh whoops :sweat_smile:. Yeah we should probably have one of them opened

**Comment by ventralnet** [comment]
Just leaving this here.  Here is a blurb from the JEST documentation why you have to include axios in transforming/transpiling.  By default JEST ignores node_modules/*

"""
Sometimes it happens (especially in React Native or TypeScript projects) that 3rd party modules are published as untranspiled code. Since all files inside node_modules are not transformed by default, Jest will not understand the code in these modules, resulting in syntax errors. To overcome this, you may use transformIgnorePatterns to allow transpiling such modules. You'll find a good example of this use case in React Native Guide.
"""

**Comment by ventralnet** [comment]
Yet further useful information why Jest is transpiling
https://jestjs.io/docs/code-transformation

**Comment by 77pintu** [comment]
Finally, the issue is resolved I updated the latest jest version

**Comment by LiviuSosu** [comment]
> I found that this did however work for me because it forces those imports to resolve with the CJS module instead:
> 
> ```js
>   moduleNameMapper: {
>     '^axios$': require.resolve('axios'),
>   },
> ```

Up from me ;-)

**Comment by SalahAdDin** [comment]
No any of the solutions given here gave us a proper solution, we are working with the `1.2.5`  version.

**Comment by imransilvake** [comment]
Checked on `"axios": "^1.3.2",`, still not fixed !!

**Comment by arpitha-jaanaki** [comment]
HI @imransilvake did u not faced  error like "options must be an object error" with latest version of axios?

AXIOS VERSION used

"axios": "^1.3.2",
"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",

axiosservice.js file looks like below

import axios from 'axios';
import { qs, parse, stringify } from 'qs';
const buildInfoFilePath = '/system/buildInfo.json';

class AxiosService {
	instance = axios.create({
		paramsSerializer: {
			encode: parse,
			serialize: stringify
		}
	});
	
none of the solution worked for me .

can u please guide me what exactly fixed your issue, and how your axios service.js file looks like

Advance 
thanks

**Comment by imransilvake** [comment]
> HI @imransilvake did u not faced error like "options must be an object error" with latest version of axios?
> 
> AXIOS VERSION used
> 
> "axios": "^1.3.2", "test": "react-scripts test --transformIgnorePatterns "node_modules/(?!axios)/"",
> 
> axiosservice.js file looks like below
> 
> import axios from 'axios'; import { qs, parse, stringify } from 'qs'; const buildInfoFilePath = '/system/buildInfo.json';
> 
> class AxiosService { instance = axios.create({ paramsSerializer: { encode: parse, serialize: stringify } });
> 
> none of the solution worked for me .
> 
> can u please guide me what exactly fixed your issue, and how your axios service.js file looks like
> 
> Advance thanks

No, I didn't.
My axios service contains `get, put, post and delete` methods such as:

```
	/**
	 * GET
	 * @param url
	 * @param config
	 */
	get = async <T>(url: string, config?: AxiosRequestConfig): Promise<T> => {
		const resp = await axios.get(url, config);
		return resp.data as T;
	};
```

**Comment by SalahAdDin** [comment]
> > HI @imransilvake did u not faced error like "options must be an object error" with latest version of axios?
> > AXIOS VERSION used
> > "axios": "^1.3.2", "test": "react-scripts test --transformIgnorePatterns "node_modules/(?!axios)/"",
> > axiosservice.js file looks like below
> > import axios from 'axios'; import { qs, parse, stringify } from 'qs'; const buildInfoFilePath = '/system/buildInfo.json';
> > class AxiosService { instance = axios.create({ paramsSerializer: { encode: parse, serialize: stringify } });
> > none of the solution worked for me .
> > can u please guide me what exactly fixed your issue, and how your axios service.js file looks like
> > Advance thanks
> 
> No, I didn't. My axios service contains `get, put, post and delete` methods such as:
> 
> ```
> 	/**
> 	 * GET
> 	 * @param url
> 	 * @param config
> 	 */
> 	get = async <T>(url: string, config?: AxiosRequestConfig): Promise<T> => {
> 		const resp = await axios.get(url, config);
> 		return resp.data as T;
> 	};
> ```
> 
> that worked for me:
> 
> ```
> "test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",
> ```

It does even not work for me.

**Comment by paullaster** [comment]
Not working for me either 

> HI @imransilvake did u not faced error like "options must be an object error" with latest version of axios?
> 
> AXIOS VERSION used
> 
> "axios": "^1.3.2", "test": "react-scripts test --transformIgnorePatterns "node_modules/(?!axios)/"",
> 
> axiosservice.js file looks like below
> 
> import axios from 'axios'; import { qs, parse, stringify } from 'qs'; const buildInfoFilePath = '/system/buildInfo.json';
> 
> class AxiosService { instance = axios.create({ paramsSerializer: { encode: parse, serialize: stringify } });
> 
> none of the solution worked for me .
> 
> can u please guide me what exactly fixed your issue, and how your axios service.js file looks like
> 
> Advance thanks

Not working me too

**Comment by rlemasquerier** [comment]
For those of you who tried `transformIgnorePatterns` with no success, make sure that your babel config is a js file (`babel.config.js`) instead of `.babelrc`. 

Made the difference in my project, not sure why...

**Comment by SalahAdDin** [comment]
> For those of you who tried `transformIgnorePatterns` with no success, make sure that your babel config is a js file (`babel.config.js`) instead of `.babelrc`.
> 
> Made the difference in my project, not sure why...

We are working with `vite`.

**Comment by Veryinheart** [comment]
same issue with "jest": "^29.5.0",  "axios": "^1.3.4" and None of these solutions works for me.

**Comment by philly-vanilly** [comment]
Could you not think of releasing two different libs, one for backend, one for frontend, with different build target or something? How many human life hours have been wasted on this nonsense?

**Comment by SalahAdDin** [comment]
> Could you not think of releasing two different libs, one for the backend, and one for the front end, with different build targets or something? How many human life hours have been wasted on this nonsense?

isn't this library isomorphic?

**Comment by sane4ek1994** [comment]
"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\""
Thanks for the solution, saved a lot of time 🙂

**Comment by IndianBoyBR** [comment]
> 
// this worked for me
...,
 "test": "react-scripts test --transformIgnorePatterns 'node_modules/(?!axios)/'", // single quotes

**Comment by ann-glitch** [comment]
> `"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\""`
> 
> this worked, **when I restart test command**

this worked for me. thank you!

**Comment by TownTowner** [comment]
This link export the path `./dist/node/axios.cjs` in `node_modules/axios/package.json`, which is:

> {
  "exports": {
    "./dist/node/axios.cjs": "./dist/node/axios.cjs"
  }
}

[https://github.com/axios/axios/issues/5358#issuecomment-1447646435](url)

**Comment by SalahAdDin** [comment]
> This link export the path `./dist/node/axios.cjs` in `node_modules/axios/package.json`, which is:
> 
> > {
> > "exports": {
> > "./dist/node/axios.cjs": "./dist/node/axios.cjs"
> > }
> > }
> 
> [https://github.com/axios/axios/issues/5358#issuecomment-1447646435](url)

It is not working at all.

**Comment by TownTowner** [comment]
Worked for me, but I used the jest config way:
https://github.com/axios/axios/issues/5101#issuecomment-1296024311

> Works for me:
> 
> ```
> moduleNameMapper: {
>     'axios': 'axios/dist/node/axios.cjs'
> }
> ```

**Comment by gsaranya256** [comment]
Axios : "axios": "^1.5.1",
Jest : "27.5.1",
Tried out all the solutions but none working for these versions..

**Comment by chitru** [comment]
I am at axios 1.6.1 and jest is 29.5.8, with CRA and `"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",
` is not working.... any solutions ??

**Comment by Blvckleg** [comment]
For me it also doesn't work with "@nestjs/axios": ">=0.1.0" and "axios":"1.6.1".
The problem is with commonjs and ECMA Modules. A stackoverflow post with this problem suggested adding this to your package.json to force use commonjs. This did not work for me personally but maybe it will help someone here.

`"jest: {
""moduleNameMapper": {
      "axios": "axios/dist/node/axios.cjs"
    },
    }`

**Comment by hems** [comment]
> --transformIgnorePatterns \"node_modules/(?!axios)/\""

nothing suggested here or on the readme works for me as well..

here are my versions:

````js
"jest": "^29.7.0",
"nock": "^13.4.0",
"axios": "^1.6.2",
````

probably worth mentioning i'm using `ts-node`.. maybe has something to do with it?

**Comment by Namnika** [comment]
In my case, I was also facing the same problem 
So I got to solve with this: 
```
"jest": {
    "transformIgnorePatterns": ["node_modules/(?!axios)/"]
},
```
> That's why we moved to Vitest.

but have one question `jest` can't work with `Vite`? Even knowing Vitest is integrated with jest, So still vitest should used? 
*btw, I'm also using Vite*

**Comment by SalahAdDin** [comment]
> In my case, I was also facing the same problem So I got to solve with this:
> 
> ```
> "jest": {
>     "transformIgnorePatterns": ["node_modules/(?!axios)/"]
> },
> ```
> 
> > That's why we moved to Vitest.
> 
> but have one question `jest` can't work with `Vite`? Even knowing Vitest is integrated with jest, So still vitest should used? _btw, I'm also using Vite_

Forget **Jest**, embrace **Vitest**.

**Comment by devamitranjan** [comment]
If you are using xhrAdapter then you have to use the module mapper configuration for the not found modules:

`
"jest": {
   "moduleNameMapper": {
     "axios/unsafe/adapters/xhr": "axios/lib/adapters/xhr.js",
     "axios/unsafe/core/settle": "axios/lib/core/settle.js"
   }
}
`

**Comment by YuraZakaryan** [comment]
this is work for me
`"jest": {
    "moduleNameMapper": {
      "^axios$": "axios/dist/node/axios.cjs"
    }
  },`

**Comment by markcorrea** [comment]
Solved for me for version `1.6.7`. Inside jest-config.json:

`  "moduleNameMapper": {
    "^axios$": "<rootDir>/node_modules/axios/dist/node/axios.cjs"
  },`

**Comment by gclark-eightfold** [comment]
To help anyone else in the future facing similar issues in other packages, I _think_ the issue is that Jest 27 and below **does not fully support package.json exports** (see [Jest 28 blog post](https://jestjs.io/blog/2022/04/25/jest-28#packagejson-exports))

As for why this issue happens with Axios and not many other packages, axios is declaring `"type": "module"` in the package.json with `"main": "index.js"`, such that `index.js` is an ESM file. If you are running jest tests in a non-node environment (e.g. `jsdom`), this will cause issues in Jest 27 and below since `dist/node/axios.cjs` is only referenced in the `exports` field.

### Solutions for Library Authors
1. Make the `main` field in package.json references a CommonJS file and use the `module` field for the ESM file.
2. Don't support Jest v27 and below out-of-the-box. (ideally also provide some docs regarding setup)
    - NOTE: If you are using the `exports` field to remap how consumers import specific entry points (e.g. `my-package/hello-world` -> `my-package/dist/hello-world.cjs`), not supporting Jest 27 and below may be the **only option**.

### Solutions for Application Authors
1. Upgrade Jest to v28+ for package.json `exports` compatibility
2. Use the `moduleNameMapper` config option to force the CJS file to be used. (See above examples for how this is done for axios specifically).
    - NOTE: Other recommendations above may also work, but this is the only one that I know of myself that works.

**Comment by Russzh** [comment]
`jest: {
    configure: {
      collectCoverage: true,
      collectCoverageFrom: [
        "src/**/*.{js,jsx,ts,tsx}",
        "!src/**/*.types.ts",
        "!src/**/*.d.ts",
        "!src/**/index.{js,jsx,ts,tsx}",
        "!src/reportWebVitals.ts",
        "!src/stories/*.{ts,tsx}",
      ],
      moduleNameMapper: {
        "^axios$": require.resolve("axios"),
      },
    },
  },`

in craco.config.js works for me
