### ISSUE TITLE
Z_BUF_ERROR on HEAD requests

### ISSUE THREAD

**Issue by dergecko** [axios/axios#5102]
#### Describe the bug
If you send a HEAD request to any endpoint that as the content-encoding set to decompress a **Z_BUF_ERROR** will be thrown. **Axios** tries to decompress the response even if no data is available.

#### To Reproduce
```js
const axios = require('axios');

;(async () => {
    const url = "https://www.heise.de";
    await axios.head(url);
})()
```

#### Expected behavior
**Axios** should not try to decompress the data that does not exists.

#### Environment
 - Axios Version [1.1.2]
 - Node.js Version [16.17.1]
 - OS:  [OSX 11.16.5]

#### Additional context/Screenshots
Problem seems to be in the `httpAdapter` as it only removes the decompression if the data is set. 
I proposed a PR to fix the issue feel free to contact me.

**Comment by lejahmie** [comment]
Added a comment of PR, other than that it looks good.

**Comment by dergecko** [comment]
@dgg sorry for the late reply. No this only targets HEAD requests. 
However I may create a new MR for your bug as I encountered it as well.

**Comment by olivierlesnicki** [comment]
Same problem here with PUT requests

**Comment by CristopherVidalMachado** [comment]
Same problem here.

**Comment by dbishoponline** [comment]
Same problem here with GET requests

Axios - v1.1.3
Nodejs - v19.3.0
OS - macOS 13.0.1

**Comment by CristopherVidalMachado** [comment]
In my case I solve adding the following line into the headers: 

'Accept-Encoding': '*'

The service did not accept the encoding that I was sending. 
It was my lack of attention.

**Comment by DigitalBrainJS** [comment]
I believe this issue has been fixed so I'm going to close this.
