### ISSUE TITLE
After upgrading form v0.27.2 to v^1.1.2 import error with jest

### ISSUE THREAD

**Issue by cagosto** [axios/axios#5106]
#### Describe the bug
I upgraded from version 0.27.2 and now when I run my jest tests I get these error 
```
Details:

/Users/carlosagosto/MountSinaiHealthSystem/MountSinaiConsumer/ui/service-platform/node_modules/axios/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';

SyntaxError: Cannot use import statement outside a module

    > 1 | import axios, { AxiosResponse } from 'axios';
        | ^
      2 | import { isEqual } from 'lodash';
      3 | import { useCallback, useEffect, useState } from 'react';
      4 | import { useSetRecoilState } from 'recoil';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
```

if I down grade the package back to v0.27.2 everything works fine. Jest run all test pass. 

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```
Not sure how to fill this out. Every app has its own config, but I am using react create app with typescript. 

#### Expected behavior
Should would be nice for the jest test to pass. 

#### Environment
 - Axios Version 1.1.2
 - Node.js Version 16.15.1
 - Additional Library Versions
  - "react-dom": "^18.2.0",
  - "react": "^18.2.0",
  - react-scripts": "5.0.1",
  - "@testing-library/jest-dom": "^5.16.5",
  - "@testing-library/react": "^13.4.0",
  - "typescript": "^4.8.4",

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by erikrenberg** [comment]
See #5026

**Comment by cagosto** [comment]
> See #5026

Yup that's the same issue thanks for the link.

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by SalahAdDin** [comment]
I have the same problem with the last version yet.

**Comment by karlosos** [comment]
In my project with:

```
"jest": "29.7.0",
"jest-environment-jsdom": "29.7.0",
```

I was having this issue when upgrading axios from 0.25.0 to 1.7.7 and having errors for every test:

**TypeError: Cannot read properties of undefined (reading 'html')**

```
main-frame:  FAIL  src/api//__tests__/getChildrenElementsEmpty.test.ts
main-frame:   ● Test suite failed to run
main-frame:     TypeError: Cannot read properties of undefined (reading 'html')
main-frame:       at new JSDOMEnvironment (../../node_modules/jest-environment-jsdom/build/index.js:72:44)
```

It was somehow overriding versions for `jest-environment-jsdom` in `yarn.lock`. 

**The issue is solved by explicitly installing the package again with `yarn add jest-environment-jsdom@29.7.0`.**
