### ISSUE TITLE
Re-add Pre 1.x Functionality for ParamsSerializer

### ISSUE THREAD

**Issue by ChronosMasterOfAllTime** [axios/axios#5107]
#### Is your feature request related to a problem? Please describe.
No.

#### Describe the solution you'd like
#4734 Changed the entire behavior of the params serializer, breaking using any custom functionality on the consumer side. Add a boolean switch to mimic pre 1.x behavior (default is false) and send the params directly to the encode function

#### Describe alternatives you've considered
Tried working with new solution; it did not pan out well and led to more bugs with our requests

**Comment by FlorisVeldhuizen** [comment]
It seems that `null` and `undefined` parameters are now getting passed as well in urls, breaking many requests. You can see this check being removed in #4734, I wonder how this breaking change that is not mentioned anywhere went under the radar

**Comment by ChronosMasterOfAllTime** [comment]
> It seems that `null` and `undefined` parameters are now getting passed as well in urls, breaking many requests. You can see this check being removed in #4734, I wonder how this breaking change that is not mentioned anywhere went under the radar

Good catch; I wonder if we can update the main meat of their toString function for serializing the params to omit undefined and null. Feel free to make suggestions on #5108! I just wanted some of the old functionality back 😅

**Comment by ChronosMasterOfAllTime** [comment]
@FlorisVeldhuizen I added a commit to PR#5108 which should (hopefully) resolve the issues with nulls and undefined? I added a test and found nulls are being included, but undefined fields are not

**Comment by ChronosMasterOfAllTime** [comment]
Updated my PR because they still havent reconciled the null bug, but instead caused merge conflicts and duplicated efforts. 🤷

**Comment by ChronosMasterOfAllTime** [comment]
@FlorisVeldhuizen this is merged, but not yet released
