### ISSUE TITLE
How stable is v1?

### ISSUE THREAD

**Issue by KrisLau** [axios/axios#5114]
#### Describe the issue
Hi, really appreciate all the work that's being done on the library now! I'm deciding whether or not to upgrade from v0.27.2 to v1.1.2 or if I should wait for a more stable version. I'm unsure how stable v1 is as I've seen a bunch of issues related to v1. I also was wondering if there will be a migration guide written for upgrading to v1.

#### Example Code
N/A

#### Expected behavior, if applicable
N/A

#### Environment
 - Axios Version - `v0.27.2`
 - Adapter - HTTP
 - Browser - N/A
 - Browser Version - N/A
 - Node.js Version - `v16.16.0`
 - OS:  - N/A
 - Additional Library Versions - React Native `v0.69.6`

#### Additional context/Screenshots
 N/A

**Comment by EfChouTR** [comment]
FWIW there are a few breaking changes (paramsSerializer behavior is completely different), plus the documentation needs to be updated. Opened a PR to resolve the Params Serializer issue and updated some of the docs. See #5108

**Comment by ddolcimascolo** [comment]
It's not. The Jest tests breakage is a show stopper by itself, there's the paramsSerializer issue @EfChouTR is talking about, the set-cookie header issue, and the long list of open, unrsponded issues.

**Comment by KieraDOG** [comment]
there are few typescript break changes as well, 

ie. you are no longer allowed to do this in axios v1 ts

```
api.interceptors.response.use((response: AxiosResponse): unknown => response.data)
```

**Comment by jasonsaayman** [comment]
Yeah, there are a couple of issues, and I am trying to resolve a lot of them. Will be working on getting it more stable tonight. Staying on v0.27.2 is still an option, we are not dropping support for that and a new v0.xx version will be released soon.

**Comment by KrisLau** [comment]
> Yeah, there are a couple of issues, and I am trying to resolve a lot of them. Will be working on getting it more stable tonight. Staying on v0.27.2 is still an option, we are not dropping support for that and a new v0.xx version will be released soon.

Sounds good, thanks for all the great work!

**Comment by KrisLau** [comment]
@jasonsaayman Hi, sorry to bother but I just wanted to check in with a related question! Will there be an announcement made when a stable version is reached? I'm unsure when I should start migrating to v1 and just wanted to know if there will be an official announcement or if a stable version has already been reached.

**Comment by KrisLau** [comment]
For anyone tracking this, I come back once in awhile to check and there's a community migration guide (not axios official). Skimming over it, it seems pretty comprehensive and useful. 

Hope this helps anyone else who has been waiting for a guide before upgrading!
