### ISSUE TITLE
After upgrading form v0.27.2 to v1.1.2 import error with Vite

### ISSUE THREAD

**Issue by baracuda69** [axios/axios#5118]
#### Summary

In Vue3 / TypeScript project,
import { AxiosError } from 'axios';

Build shows warning:
Non-existent export 'AxiosError' is imported from node_modules/axios/index.js

Although there is only a build warning, any component (Vue) or TypeScript (ts) that includes this import fails to work.
Browser console (Dev-Tools) shows:

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/axios.js?v=3226fa61' does not provide an export named 'AxiosError' (at auth-store.ts:2:17)

#### Environment
 - Axios Version 1.1.2
 - Node.js Version v17.4.0
 - OS: Windows 10
 - Vite version: 3.1.7

**Comment by philBrown** [comment]
#5062
