### ISSUE TITLE
IE11 error v1..2 SCRIPT1002

### ISSUE THREAD

**Issue by shaomingming008** [axios/axios#5125]
### Describe the bug

use v1.1.2 in IE11 will apper error SCRIPT1002
![ff9440a199358f3ce6e274078ee90cd](https://user-images.githubusercontent.com/22759207/195789296-95102510-466a-43a8-a624-10db243b8470.jpg)

but I use v0.27.2 ，it is ok！

### Axios Version

1.1.2

### Browser

ie11

### OS

win10

**Comment by jasonsaayman** [comment]
Please rather use v0.x for IE

**Comment by axetroy** [comment]
If 1.x not support IE any more, why write IE compatible in README. it confuse me.

**Comment by DigitalBrainJS** [comment]
@axetroy Because it's technically supported via babel/polyfills.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test</title>
  <script src="https://cdn.jsdelivr.net/npm/core-js-bundle@3.26.1/minified.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios@1.2.0-alpha.1/dist/axios.min.js"></script>
</head>
<body>
  <script>
    axios.get('https://jsonplaceholder.typicode.com/todos/1')
      .then(function (response) {
        alert('Axios' + axios.VERSION + ' ' + JSON.stringify(response.data));
      })
      .catch(function (error) {
        alert(JSON.stringify(error));
      })
  </script>
</body>
</html>
```
