### ISSUE TITLE
How to redirect with the interceptors?

### ISSUE THREAD

**Issue by vladcl** [axios/axios#5144]
### Describe the issue

Hi guys, im developing a React app with Nodejs and axios. My app has a auth by route, so i need to redirect the user for the login page if he's not allowed in this route, i've already seted the 403 error for this, so i want to know how redirect him in my inteceptors.

I've tried with Navigate and redirect from react-router-dom and nothing. 

### Example Code

```js
api.interceptors.response.use(
    response => response,
    error => {
        if (!error.response)
            return Promise.reject({error: 'Não foi possível concluir a operação, tente novamente'});       
       
    },
);
```

### Expected behavior

I want to redirect the user for login page.

### Axios Version

0.27.2

### Browser

Firefox

### Node.js Version

16.16.0

### OS

Linux

### Additional Library Versions

```bash
React 18.2.0
```

**Comment by ajmas** [comment]
So if I understand, you are wanting to be able to redirect to a specific page if you get a 403 response, for example?

If that is the case, then this article should help:

https://dev.to/darkmavis1980/how-to-use-axios-interceptors-to-handle-api-error-responses-2ij1

Or in brief, based on the article:

```js
customAxios.interceptors.response.use(
  response => response,
  error => {
    if (error.response.status === 401) {
      window.location.href = '/';
    }
  });
```

Just adjust it for react.

**Comment by vladcl** [comment]
It's works!! Thanks for you help and for this article, mate!

**Comment by trana5197** [comment]
But isn't it a bad practice for SPA to reload a page? Is there any other simple solution like this?

**Comment by ajmas** [comment]
@trana5197 you could just make use of the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API). Depending on the framework you are using there may be a wrapper library that you are directed to such as vue-router, if you are using Vue.

**Comment by 3pleFly** [comment]
This does not answer the question. It is most definitely bad practice to call 
      window.location.href = '/';

When you are working with React-Router or any other SPA...

**Comment by ajmas** [comment]
> This does not answer the question. It is most definitely bad practice to call window.location.href = '/';
> 
> When you are working with React-Router or any other SPA...

Just replace this with an appropriate callback for the router logic, if a router is being used. Also I’d agree not hard code the home page, but to make it variable, if not using a router.

**Comment by Ritz-Bansal** [comment]
The best thing to do over here is to initialize a globalRouter and then use it throughout the codebase.

globalRouter.ts -- fileName
import type { NavigateFunction } from "react-router-dom";

const globalRouter = { 
    navigate: null 
} as { navigate: null | NavigateFunction};

export default globalRouter;

App.tsx  -- fileName
   const navigate = useNavigate();
  globalRouter.navigate = navigate; 

now you can use it in axios interceptors
   globalRouter.navigate!('/signin');

- You can do 
a. globalRouter.navigate?.('/signin');
b. globalRouter.navigate!('/signin');

- If you do not do this, typescript will give you an error (Cannot invoke an object which is possibly 'null'.) as navigate can be null (initial state)

- if you got error: useNavigate() may be used only in the context of a <Router> component. It means you tried to call useNavigate() in a file that is not a child of <BrowserRouter>, go to the frontend.tsx/main.tsx and put the <App/ inside BrowserRouter
  <StrictMode
    <BrowserRouter
      <App /
    </BrowserRouter
  </StrictMode

complete the tags, for some reason the code is not visible with tags on. 

If you use window.location.href = '/signin', it will do hard relod, so use this apprach, this will do soft relod
