### ISSUE TITLE
Axios 1.1.3 serving server side bundle for browsers

### ISSUE THREAD

**Issue by yhaering** [axios/axios#5150]
### Describe the bug

With Version 1.1.3 the "browser" export has been changed to "./dist/node/axios.cjs" which causes Webpack to use the NodeJs (Server Side) bundle by default.

Change: https://github.com/axios/axios/commit/9bd53214f6339c3064d4faee91c223b35846f2dd#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

### Expected behavior

The "browser" export serves the browser bundle as per version 1.1.2

### Axios Version

1.1.3

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵
