### ISSUE TITLE
ESLint no-named-as-default-member for isAxiosError

### ISSUE THREAD

**Issue by rlesniak** [axios/axios#5164]
### Describe the bug

After upgrade to 1.1.3 my ESLint complains about `import/no-named-as-default-member`

![image](https://user-images.githubusercontent.com/13970783/196927145-1a5e81ec-d359-4b33-9cde-3e0556ab6e79.png)

But in reality, I cannot import as `import { isAxiosError } from 'axios';`

![image](https://user-images.githubusercontent.com/13970783/196927257-b540eb7e-60c5-4560-b880-f23bf890bfe2.png)

So something is broken with TS types

### To Reproduce

Turn on `import/no-named-as-default-member` ESLint rule, update axios to 1.1.3, try to use `axios.isAxiosError` and observe error.

### Expected behavior

I should be able to satisfy eslint and be able to import as `import { isAxiosError } from 'axios';`

### Axios Version

1.1.3

### Additional Library Versions

```bash
xo 0.52.4
```

**Comment by arash-bizcover** [comment]
Me too had to Go back to v **1.1.0** 
did lots of swears as well

**Comment by justlogicalahmad** [comment]
Ran into this error also but all i just did was to set the error to the universal type "any" and that fix it for me.
