### ISSUE TITLE
Document Error schema

### ISSUE THREAD

**Issue by DjebbZ** [axios/axios#517]
Hi guys,

I'm using axios and loving it. I just find that the schema of the Error is lacking in the docs, whereas the config and response objects are pretty well documented. It would be a really nice addition to an already very well written documentation.

**Comment by mzabriskie** [comment]
Thanks for the feedback. Is there anything in particular that you find lacking. We would definitely like the docs to be as helpful as possible.

**Comment by DjebbZ** [comment]
Ok, imagine something like this. Quickly thrown-out markdown, feel free to correct me if I'm wrong. I wrote it so it's almost copy-pastable (formatting, wording etc.)

1. First, a rewrite of `Handling Errors` section

## Handling Errors

``` javascript
axios.get('/user/12345')
  .catch(function (error) {
    // handle error here
  });
```

There are 2 cases to take into account when handling errors : we got a response and we didn't get a response.

In all cases, the error has the following information :

``` javascript
{
  // `config` is the config that was provided to `axios` for the request
  config: {}
}
``` 

When we got a response, but the server responded with a status code that falls out of the range of 2xx

``` javascript
{
  // every additional information is under the response property
  response: {
    // `data` is the response that was provided by the server
    data: {},

    // `status` is the HTTP status code from the server response
    status: 500, // could be any number that doesn't pass the `validateStatus` predicate (by default 2xx), see below

    // `headers` the headers that the server responded with
    headers: {},
  }
}
````

In case we got no response, there will be no `response` property, instead the following :

``` javascript
{
  // Something happened in setting up the request that triggered an Error
  message: '',
}
```

You can define a custom HTTP status code error range using the validateStatus config option.

```
axios.get('/user/12345', {
  validateStatus: function (status) {
    return status < 500; // Reject only if the status code is greater than or equal to 500
  }
})
```

### Example error handling that demonstrates all cases :

``` javascript
axios.get('/user/12345')
  .catch(function (error) {
    if (error.response) {
      // The request was made, but the server responded with a status code
      // that falls out of the range of 2xx
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
    }
    // You can always access the request config
    console.log(error.config);
  });
```

2. Second, explaining better the error cases in interceptors : the following won't be a rewrite proposal but inline questions because it's not clear to me at all. I'm quoting part of the interceptors section.

```
// Add a request interceptor
axios.interceptors.request.use(function (config) {
    // Do something before request is sent
   // QUESTION : can config be mutated ?
    return config;
  }, function (error) {
    // Do something with request error
    // QUESTION : What does request error means ? In which cases it may happen ? Is it the same than `Handling Errors` above ?
    // QUESTION : What is the schema of `error` here ?
    // QUESTION : Why Promise.reject ? Why not simply `throw` ?
    return Promise.reject(error);
  });

// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Do something with response data
    // QUESTION : Can I mutate response here ?
    // QUESTION : If I mutate config in the request interceptor, do I get the mutated config ?
    return response;
  }, function (error) {
    // Do something with response error
    // QUESTION : What does request error means ? In which case it may happen ? Is it the same than `Handling Errors` above ?
    // QUESTION : What is the schema of `error` here ?
    // QUESTION : Why Promise.reject ? Why not simply `throw` ?
    return Promise.reject(error);
  });
```

I hope I made myself clearer and that it will lead to some changes to the docs. I know that there are some repetitions but it's because some things are still unclear to me, so better make everything crystal clear.

Keep up the good work !

**Comment by DjebbZ** [comment]
BTW, I would also move the `Handling errors` section just after the `Response Schema`. It's weird to talk about errors after interceptors, since you must handle errors in interceptors but in normal requests too.

**Comment by Marcholio** [comment]
The documentation seems to be updated, this could be closed now maybe?

**Comment by Alanscut** [comment]
Thanks your @DjebbZ  advice, document is an important part, and we will continue to optimize the document.
