### ISSUE TITLE
Typescript error: Type 'GenericAbortSignal | undefined' is not assignable to type 'AbortSignal | undefined'

### ISSUE THREAD

**Issue by ns-vpanfilov** [axios/axios#5172]
### Describe the bug

The following code gives typescript error messages since GenericAbortSignal is missing required properties (per https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)

```js
import { GenericAbortSignal } from 'axios'
let axiosAbortSignal: GenericAbortSignal = new AbortSignal()
let typescriptAbortSignal: AbortSignal = axiosAbortSignal // Type 'GenericAbortSignal' is missing the following properties from type 'AbortSignal': reason, throwIfAborted, dispatchEvent
```

typescript's definition:
```js
// from ./lib/lib.dom.d.ts
interface AbortSignal extends EventTarget {
    /** Returns true if this AbortSignal's AbortController has signaled to abort, and false otherwise. */
    readonly aborted: boolean;
    onabort: ((this: AbortSignal, ev: Event) => any) | null;
    readonly reason: any;
    throwIfAborted(): void;
    addEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

```

### To Reproduce

In VSCode (1.72.2) , create typescript project. Install typescript as dev dependency ("typescript": "^4.8.4").

The error will be shown in vscode and when trying to compile the project using `tsc --build` command

### Axios Version

1.1.3

### Node.js Version

19.0.0

### Additional Library Versions

```bash
"typescript": "^4.8.4"
"@types/node": "^18.8.4"
```

**Comment by geewoo94** [comment]
[Similar issue](https://github.com/prisma-labs/graphql-request/issues/356) and there is solution as well.

**Comment by DigitalBrainJS** [comment]
> let axiosAbortSignal: GenericAbortSignal = new AbortSignal()
> let typescriptAbortSignal: AbortSignal = axiosAbortSignal

Why do you need this? 
`GenericAbortSignal` is a general/partial interface of AbortSignal. You cannot assign a generic interface to a more restrictive one.

```js
const typescriptAbortSignal: AbortSignal = new AbortSignal();

axios.get('/user', {signal: typescriptAbortSignal});
```
`GenericAbortSignal` - is designed to accept all kinds of AbortController - from browsers (DOM) and Node.js, since they have different interface definitions, while Axios should be cross-platform.

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵
