### ISSUE TITLE
import axios from 'axios' results in undefined

### ISSUE THREAD

**Issue by zhaosiyang** [axios/axios#5174]
### Describe the bug

In TypeScript file, when I do `import axios from 'axios'`, the `axios` variable is inferred as `AxiosStatic`, however the value of it is `undefined`;

This used to be working on axios version 0.x.x

### Axios Version

1.x.x

### Node.js Version

16.15.0

### OS

OSX12.2.1 (M1 chip)

**Comment by struckchure** [comment]
Tried the previous version, it's not working to, use this
`axios@^0.27.2`

**Comment by ojuliomiguel** [comment]
Im having the same issue! 
Backing to version 0.27.2

**Comment by hujiali455** [comment]
i replace node v16 with v14 to solve this issue

**Comment by SakuraHentai** [comment]
try to enable `esModuleInterop` in tsconfig.

**Comment by Joebayld** [comment]
I'm sorry - but how does such a major issue get introduced in a patch update? Aren't there tests for this? 

I went back to 1.1.0 and it solved the problem - but I definitely spent time troubleshooting what is wrong in my app and it was this.. I just don't understand how something as simple as importing the library got broken on such a small update.

**Comment by AlexGrafe** [comment]
Have the same issue. Sorry to nag, but it would be great if this could be automatically be tested before release. I'm new to axios, but I imagine it's a big-time, infrastructure-critical library. Had to revert to `^0.27.2` for it to work.

**Comment by spaelling** [comment]
this works for me

`
const axios = require('axios')
`

But I had to change from axios.post to

`
    response = await axios({
      method: 'post',
      url: url,
      data: data,
      headers: headers,
    })
`

and no autocomplete or other TS goodies.

**Comment by zhaosiyang** [comment]
As @SakuraHentai metioned, `"esModuleInterop": true` resolved this issue. Closing it.

**Comment by Joebayld** [comment]
> As @SakuraHentai (thank you very much) mentioned, `"esModuleInterop": true` resolved this issue. Closing it.

I'm not sure this is a real solution? Something is clearly broken with the exports - we shouldn't have to modify our tsconfig to fix the issue. All of my other dependencies work just fine with the existing tsconfig settings, and this module used to work just fine as well. Shouldn't it be fixed in an update??

**Comment by zhaosiyang** [comment]
> > As @SakuraHentai (thank you very much) mentioned, `"esModuleInterop": true` resolved this issue. Closing it.
> 
> I'm not sure this is a real solution? Something is clearly broken with the exports - we shouldn't have to modify our tsconfig to fix the issue. All of my other dependencies work just fine with the existing tsconfig settings, and this module used to work just fine as well. Shouldn't it be fixed in an update??

You are probably correct. Reopening.

**Comment by jasonsaayman** [comment]
Yeah there is a problem, we are going to create a pre-release to see if what we have done solves the issue. I will try get it out tonight

**Comment by Joebayld** [comment]
> Yeah there is a problem, we are going to create a pre-release to see if what we have done solves the issue. I will try get it out tonight

Cool. I was looking into the 1.1.13 release and it seems the default export was removed - which is likely the issue here? Because the typescript file thinks there's a default but the JS doesn't have it anymore. 

That's my guess anyways.

**Comment by jasonsaayman** [comment]
Yeah @Joebayld it is apparently way more complex than we thought to have support for many bundles and still manage to keep the export working as it always was. However, we believe we have a working version now which will be in the pre-release and hopefully covers all cases.

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by csadai** [comment]
Hey thanks for the fix!
I tried the `1.2.0-alpha.1` but the new release makes the TS>JS transpiling fail (I used `gts` with `npx gts init`)

```shell
> tsc
node_modules/axios/index.d.ts:275:11 - error TS2304: Cannot find name 'ProgressEvent'.

275   event?: ProgressEvent;
              ~~~~~~~~~~~~~
Found 1 error in node_modules/axios/index.d.ts:275
```

**Comment by shilo123** [comment]
In the end, how do you fix this error?
