### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by sephentos** [axios/axios#5175]
### Describe the bug

```
import axios, { AxiosInstance, AxiosResponse } from 'axios'

...

this.instance = axios.create( {
                        ^
```

`TypeError: Cannot read properties of undefined (reading 'create')`

### Axios Version

1.1.3

### Node.js Version

19

**Comment by rgripper** [comment]
Duplicate of #5038

**Comment by RaresAil** [comment]
The issue still persists in `1.1.3` and that ticket was closed

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵
