### ISSUE TITLE
Headers no longer available at beforeRedirect

### ISSUE THREAD

**Issue by yli-hallila** [axios/axios#5176]
### Describe the bug

Prior to PR #4708 you could access redirect headers with `beforeRedirect: (options, { headers })` but with the changes in #4708 the `headers` are no longer available. To me it's unclear whether this was an intentional change or not but the documentation suggests that this should still be working. 

### To Reproduce

https://npm.runkit.com/axios

```javascript
var axios = require("axios")
// Works with an older version
// var axios = require("axios@0.27.2")
var express = require("express")
var app = express()

app.get('/redirect', (req, res) => {
  res.cookie("Hello", "World");
  res.redirect("/");
})

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(3000, () => {
    axios.get("http://localhost:3000/redirect", {
        // Headers undefined
        beforeRedirect: (options, { headers }) => {
            console.log({options, headers});
        }
    });
});
```

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵
