### ISSUE TITLE
Critical axios default headers bug

### ISSUE THREAD

**Issue by ThatDeveloper** [axios/axios#5187]
### Describe the bug

When removing defaults, i.e. axios.defaults.headers and then using retry logic `instance(originalConfig)` or `instance.request(originalConfig)` with already processed headers within a response interceptor error, the axios code creates invalid `config.headers: { [object Object]: undefined }`.

Invalid axios code on retry (lib/core/Axios.js):
```
    // Flatten headers
    const defaultHeaders = config.headers && utils.merge(
      config.headers.common, //<--- is undefined
      config.headers[config.method] //<--- is undefined
    );

    defaultHeaders && utils.forEach(
      ['delete', 'get', 'head', 'post', 'put', 'patch', 'common'],
      function cleanHeaderConfig(method) {
        delete config.headers[method];
      }
    );

    //config.headers still valid on retry
    config.headers = new AxiosHeaders(config.headers, defaultHeaders); //problem here!
    //config.headers invalid ([object Object]: undefined) on retry
```

There needs to be a check beforehand if `config.headers.common` and / or `config.headers[config.method]` exists before merging.

Before:
![axios_before](https://user-images.githubusercontent.com/12497431/198000129-66327bba-4d20-4600-8927-f25d6d8d3b5f.PNG)

After:
![axios_after](https://user-images.githubusercontent.com/12497431/198000146-0196b96c-20cd-4b92-b100-623e387adda6.PNG)

defaultHeaders:
![image](https://user-images.githubusercontent.com/12497431/198001211-194183fd-3452-4577-ae87-f57e325f81cf.png)

### To Reproduce

Use code below, execute a request to whatever website. It works.
Now disable internet connection in (chrome) devtools (set to "Offline"). Do a request again. The request will go through and end up in `instance.interceptors.response error` where at the end it will retry to send it `return instance(originalConfig);`. When looking at the generated request you will see the invalid request headers. Alternatively step into `return instance(originalConfig);` and see for yourself.

### Code snippet

Code modified to reduce unnecessary clutter:
```js


import axios from 'axios';

/**
    Delete defaults as strange behaviour occurs, and gql did not work
    https://github.com/axios/axios/pull/4185#issuecomment-943342451

    Headers were invalid as it seemed to have appended and not set new ones, e.x.:
    { "accept": "application/json, text/plain, *|*, *|*" } <- replace '|' with '/'
    { "content-type": "application/x-www-form-urlencoded, application/json" }
*/
delete axios.defaults.headers;

const instance = axios.create({
    headers: {
        'common': {
            'X-APP': "AppName"
        }
    }
});

instance.interceptors.request.use(
    (config) => {
        debugger; //config.headers invalid after first request

        if (config.headers["correlationid"] === undefined || config.headers["correlationid"] === null)
            config.headers["correlationid"] = "test";

        return config;
    },
    (error) => {
        return Promise.reject(error);
    }
);

instance.interceptors.response.use(
    (res) => {
        return res;
    },
    async (err) => {
        const originalConfig = err.config;
        
        if (originalConfig === undefined)
            return Promise.reject(err);

        //Fix post handling - https://github.com/axios/axios/issues/934#issuecomment-531463172
        if (originalConfig.data)
            originalConfig.data = JSON.parse(originalConfig.data)
        
        async function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }
        await sleep(2000);

        console.error(originalConfig.headers); //valid for the first request
        debugger;
        return instance(originalConfig);
    }
);
```

### Expected behavior

Not overwriting or changing headers when using `instance(originalConfig);`.

### Axios Version

1.1.3

### Adapter Version

default

### Browser

Chrome

### Browser Version

106.0.5249.119

### Node.js Version

v16.11.1

### OS

Windows 10

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by PetrShchukin** [comment]
Axios@1.3.5 still the same issue, merely retrying a request in an interceptor:
```
return this.axiosRef(response.config);
```
results in 
```
request headers AxiosHeaders {
  '[object Object]': undefined,
  Authorization: 'Bearer myJWT',
  [Symbol(defaults)]: {}
}
```

**Comment by Lioness100** [comment]
I'm still experiencing this issue 🤔
