### ISSUE TITLE
axios.post response got data, but response.data is empty

### ISSUE THREAD

**Issue by gahhon** [axios/axios#5191]
### Describe the issue

```
const headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
};

const response = await axios.post(postURL, urlSearchParams, { timeout: constant.axiosTimeout, headers: headers });

logger.custom.info('responseXML:: ', response); //Show list of things
logger.custom.info('responseXML_DATA:: ', response.data); //Empty
```

When I check the log for **responseXML** I can see there is values on the the data attributes
![image](https://user-images.githubusercontent.com/113905195/198046176-0c9b3351-cf6f-48cb-b845-76ae84c1acbc.png)

But when I check the log for **responseXML_DATA** it show empty.
![image](https://user-images.githubusercontent.com/113905195/198046955-1fb9f1fb-de0f-45c4-bd6b-7a977f32371d.png)

It is expected for the API to returned in XML format.
I am trying to convert XML to JSON format for later operation by using **xml-js.xml2json** approach

Any helps are appreciated.

### Expected behavior

I should be able to retrieve the response.data in xml format, so that I will able to convert into JSON object.

### Axios Version

0.21.1

### Browser

Chrome, Edge, Safari

### Browser Version

Latest

### Node.js Version

14.0.0

**Comment by tegozen** [comment]
> After try and error, I noticed that console.log will actually render the expected data, but not logger. It might be need special configuration / handling for the message to display in the logger.
> 
> On after that, I'm still failing convert the xml data into JSON object. This is due to the option ignoreAttributes is TRUE. After dig some research, noticed that attribute is referring on this tag ![image](https://user-images.githubusercontent.com/113905195/198299544-9e4c8e13-b4f7-4674-b0ba-2289d97c5be0.png)
> 
> And since my response only have tag right after the xml one. Hence, I set the ignoreAttributes to FALSE will solve my issue.
> 
> Hope this clarify and thanks.

Where should I add it ? Can you give an example of the code, please?
