### ISSUE TITLE
PKG build file

### ISSUE THREAD

**Issue by matzrm** [axios/axios#5195]
### Describe the bug

Warning Failed to make bytecode node18-x64 for file /node_modules/axios/index.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/axios.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/utils.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/bind.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/Axios.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/mergeConfig.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/defaults/index.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/formDataToJSON.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/cancel/CanceledError.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/cancel/CancelToken.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/cancel/isCancel.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/env/data.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/toFormData.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/AxiosError.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/spread.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/isAxiosError.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/buildURL.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/InterceptorManager.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/dispatchRequest.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/buildFullPath.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/validator.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/AxiosHeaders.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/defaults/transitional.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/toURLEncodedForm.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/platform/index.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/adapters/index.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/env/classes/FormData.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/AxiosURLSearchParams.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/transformData.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/isAbsoluteURL.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/combineURLs.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/parseHeaders.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/platform/node/index.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/adapters/http.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/adapters/xhr.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/platform/node/classes/URLSearchParams.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/platform/node/classes/FormData.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/core/settle.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/fromDataURI.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/AxiosTransformStream.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/cookies.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/isURLSameOrigin.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/parseProtocol.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/speedometer.js
> Warning Failed to make bytecode node18-x64 for file /node_modules/axios/lib/helpers/throttle.js

### To Reproduce

Create a new Type Script project
Install axios lastest version and pkg
build the project and then run pkg

### Expected behavior

pkg build the library as in the version 0.27.2

### Axios Version

>= 1.0.0

**Comment by bulentkusva** [comment]
OS:Windows11 64 bit
I have same issue. My node.js version 16.18.0, pkg=5.8.0, axios=1.1.3. I encountered with same error while pkg building. However as you wrote, there is no problem with axios=0.27 v. I can successfully build

**Comment by RamavtarJ** [comment]
there is no problem till 0.27.2 But later versions i.e. 1.0.0 and above are giving the above mentioned error

**Comment by DavidSabine** [comment]
+1

I've observed the same warnings with axios version 1.0.3 and 1.0.0.

**Comment by yuhaya** [comment]
> 操作系统：Windows11 64位我有同样的问题。我的节点.js版本16.18.0，pkg=5.8.0，axios=1.1.3。我在构建 pkg 时遇到了同样的错误。但是，正如您所写的，axios=0.27 v没有问题。我可以成功构建

thinks,solved my problem

**Comment by yuhaya** [comment]
> OS:Windows11 64 bit I have same issue. My node.js version 16.18.0, pkg=5.8.0, axios=1.1.3. I encountered with same error while pkg building. However as you wrote, there is no problem with axios=0.27 v. I can successfully build

solved my problem

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by ThinhVu** [comment]
> 

This version doesn't solve the issue.

**Comment by fegauthier** [comment]
I confirm that I have the same issue with 1.2.1 version

**Comment by pankerit** [comment]
same problem

**Comment by 010101mostafa** [comment]
axios@0.27.2 is working correctly

**Comment by Sjonnie2nd** [comment]
Still same with 1.3.2.
Why is this closed?

**Comment by DigitalBrainJS** [comment]
@Sjonnie2nd Because [the lack of support for ESM modules in the pkg builder](https://github.com/vercel/pkg/issues/1291) is not an Axios issue and no fixes are required in the project. Starting from Axios 1.x moved to ESM modules. 
Although the package is distributed with a prebuilt `commonjs` module version, the loader must support conditional export in order to load it automatically, otherwise, you must take care of importing the correct module type yourself.
So for legacy packers use explicit import with `require`

```js
const axios = require('axios/dist/node/axios.cjs');
```

**Comment by Sjonnie2nd** [comment]
Hi DigitalBrainJS. Thanks for the fast response.
After putting in your suggested require() I got "Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/node/axios.cjs' is not defined by "exports" in ....\node_modules\axios\package.json". However looking at that package.json the line looks to be there.
NB: For me there's no hurry, i went over to the (experimental) implementation of fetch in node.

**Comment by bellaj** [comment]
@Sjonnie2nd another option is to downgrade axios 0.27 to https://github.com/axios/axios/releases/tag/v0.27.2

**Comment by conanliuhuan** [comment]
> @Sjonnie2nd another option is to downgrade axios 0.27 to https://github.com/axios/axios/releases/tag/v0.27.2

Thanks, solved my problem

**Comment by wilk** [comment]
Using `webpack` and building a single file, worked.

I used this `webpack.config.js` file:

```javascript
const path = require('path');

module.exports = {
  entry: './src/index.ts',
  mode: 'production',
  output: {
    filename: 'index.js',
    path: path.resolve(__dirname, 'dist'),
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js"],
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: "ts-loader"
      }
    ]
  },
  target: 'node',
};
```

And then:

```bash
$ npx pkg ./dist/index.js --target node18-win-x64 --output dist/index.exe
```

With this setup (`ts-node` for development and `webpack` for production) I can import `axios` like this:

```typescript
import axios from 'axios';
```

Hope this can help!

**Comment by phamthai072** [comment]
axios@0.27.2 is working for me

**Comment by ziolko** [comment]
If you're still struggling with this you might want to create a helper module to load the `.cjs` version.

```javascript
// Axios exports ECMAScript module and pkg fails to load and build it
// Force load axios as CommonJS in pkg using a relative path
// This requires adding "./node_modules/axios/dist/node/axios.cjs"
// to the pkg.assets section in package.json

const axios = process.pkg?.entrypoint 
    ? require("../../../node_modules/axios/dist/node/axios.cjs")  // you might need to adjust this path
    : require("axios");

module.exports = axios;
```

You need to add axios to the "assets" section in pkg configuration:
```json
"pkg": {
  "assets": [
    "./node_modules/axios/dist/node/axios.cjs",
  ],
  "outputPath": "dist",
  "targets": [
    "node22-linux-x64"
  ]
},
```

With this setup import the helper script instead whenever you want to load axios:
```javascript
const axios = require("./services/axios");
```

**Comment by emmansun** [comment]
How about this issue https://github.com/yao-pkg/pkg/issues/195
