### ISSUE TITLE
Missing generic in axios instance response interceptor (Typescript)

### ISSUE THREAD

**Issue by pabloimrik17** [axios/axios#5199]
### Describe the bug

Hi guys, 

i just updated my project dependencies from axios 0.27.2 to 1.1.3, now im facing this error 

![image](https://user-images.githubusercontent.com/5611863/198546287-ab32208e-5271-4be1-81b0-0d6f4c38c8e2.png)

Missing template in the use method

![image](https://user-images.githubusercontent.com/5611863/198546383-8a9951e7-022e-4301-bc42-b49d74306741.png)

Is this a error or now i cant modify the response object in the interceptor?

### Axios Version

1.1.3

### Node.js Version

18.12.0

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by pabloimrik17** [comment]
Up
