### ISSUE TITLE
ReferenceError: FormData is not defined

### ISSUE THREAD

**Issue by ShaktiMandal** [axios/axios#5202]
### Describe the bug

Recently,  In one of my vue3 project we have migrated vue-cli to vite.  With vite, we are using jest for testing the component. After the migration, application run without any issue but I have started encountering below issue  whenever running jest.

Reference Error: FormData is not defined (latest version - 1.1.3).

Please note that,  I have started observing this error from version - 1.0..0.
Unfortunately, I wouldn't be able to share the code to reproduce the issue as its my client code.  However, below is the high level structure.

![image](https://user-images.githubusercontent.com/34964652/198548184-e5d1bc02-b0a8-43c1-96b9-b3f33fe9c421.png)

We have the axios call in <abc> package  which return response. Below is the code snippet causing the error.

import axios from "axios";
const instance = axios.create(); // this line is causing problem. If I comment out this line, issue disappear.

After some digging in axios code, it looks like source of the error is from lib/platform/browser/classes/ index

### Axios Version

1.0.0

### Browser

chrome

### Node.js Version

above 14.19.0

### Additional Library Versions

```bash
vue - 3.2.39
Jest - 29.2.2
Vite - 3.1.3
```

### Additional context/Screenshots

```bash
As I have tried to debug both jest and axios, what I have noticed is that issue occurs at the time of loading the dependency modules it self. Due to that, test case does not even execute.
```

**Comment by Romick2005** [comment]
Seems like you runtime environment does not have/support FormData. Try to investigate this with window.FormData or global.FormData depends on environment. Maybe this can [help](https://github.com/axios/axios/issues/4412#issuecomment-1018766279), but you need to provide some reproducible example, and only then someone can help you.

**Comment by ShaktiMandal** [comment]
Yeah, I agree that I should have something reproducible. I am trying in my local to replicate same if I can. I will go through the ref you have provided and see if anything positive comes out. :-)

**Comment by Parthiv-01** [comment]
Seems like you runtime environment does not have/support FormData. Try to investigate this with window.FormData or global.FormData depends on environment. Maybe this can https://github.com/axios/axios/issues/4412#issuecomment-1018766279, but you need to provide some reproducible example, and only then someone can help you.

**Comment by ShaktiMandal** [comment]
> Seems like your runtime environment does not have/support FormData. Try to investigate this with window.FormData or global.FormData that depends on environment. Maybe this can [help](https://github.com/axios/axios/issues/4412#issuecomment-1018766279), but you need to provide some reproducible example, and only then someone can help you.

@Romick2005 

I am trying to reproduce the issue, so have created a small package to test , below is the code. Now, I am facing some kind of wired issue when trying to import axios. Have looked about the issue but does not seems to have exact root cause. Please let me know if you have any thought on this.

Error/Warning - 
![image](https://user-images.githubusercontent.com/34964652/198884227-b53bcaa3-9d84-409c-9339-d7b7a89d73b2.png)

Line, throws error - 

const axios_1 = __importDefault(require("axios")); // this is line give the warning which causing the issue I believe. 

Code

https://github.com/ShaktiMandal/axios-fetch-api.git (axios - 1.0.0)

**Comment by Romick2005** [comment]
What is the actual problem do you have?
![image](https://user-images.githubusercontent.com/17779660/198992810-d0240bf6-31f0-49cc-894a-d6d5934a12b8.png)

**Comment by ShaktiMandal** [comment]
> Seems like your runtime environment does not have/support FormData. Try to investigate this with window.FormData or global.FormData that depends on environment. Maybe this can [help](https://github.com/axios/axios/issues/4412#issuecomment-1018766279), but you need to provide some reproducible example, and only then someone can help you.

After doing some investigation, Came to know that main problem was due the testEnvironment i was using in Jest. Previously, I was using **happy-dom /jest-environment** and which cause the error. Issue got resolved after replacing it with jsdom.
As per the docs, happy-dom /jest-environment does not support the FormData completely which might lead to this issue I believe. 

**Just to summarize the solution if it help others.** 

Please note, this might be one of the solution if encounter this issue. There could be other reasons which can cause same kind problem. 

**Solution :**

1. Change the testEnviroment - other (happy-dom /jest-environment) -> JSDOM in jest.config.js 
2. Install jsdom package if not installed.
3. Install jest-environment-jsdom.

**Comment by ShaktiMandal** [comment]
Closing the issue as it has been resolved. please refer to my previous comment for the solution if you encounter this issue.
