### ISSUE TITLE
There is problem for header content-type in v1.x

### ISSUE THREAD

**Issue by creamidea** [axios/axios#5208]
### Describe the bug

Recently, I upgrade axios to be 1.1.3 and meet the problem: content-type is not be set correctly. Like below. But, it is ok with 0.27.2. Please help me.

![image](https://user-images.githubusercontent.com/1274730/198965109-405691e6-42be-44e4-adf3-c600ad2eee52.png)

### To Reproduce

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/axios@1.1.3/dist/axios.min.js"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/axios@0.27.2/dist/axios.min.js"></script> -->
    <script>
      axios.post(
        "/test",
        { user: 1 },
        {
          headers: {
            "content-type": "application/json",
          },
        }
      );
    </script>
  </body>
</html>
```

### Axios Version

1.1.3

### Adapter Version

xhr

### Browser

Chrome

### Browser Version

106.0.5249.119

### OS

MacOS 12.6

**Comment by BrianLeishman** [comment]
Just noticed today as well. Looks like <v1.x.x handled the case insensitive headers correctly but now it does not.

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵
