### ISSUE TITLE
no multipart boundary was found

### ISSUE THREAD

**Issue by qazyhb** [axios/axios#5219]
### Describe the bug
axios version 1.1.3
header： 'Content-Type': 'multipart/form-data',
error：FileUploadException: the request was rejected because no multipart boundary was found

**Comment by germancardenasm** [comment]
@fabb . I can confirm that it is still happening on version 1.1.3.

**Comment by DigitalBrainJS** [comment]
@fabb It has been released 8 days ago as `[1.2.0-alpha.1](https://www.npmjs.com/package/axios/v/1.2.0-alpha.1)`
