### ISSUE TITLE
Removing default content-type for post

### ISSUE THREAD

**Issue by chrisbrain** [axios/axios#5236]
### Describe the issue

I seem to be having this issue here:
https://github.com/axios/axios/issues/1193

Closed 3 years ago.

Making the request in the sample code below results in:

```
"Error in call to API function \"users/get_current_account\": Bad HTTP \"Content-Type\" header: \"application/x-www-form-urlencoded\".  Expecting one of \"application/json\", \"application/json; charset=utf-8\", \"text/plain; charset=dropbox-cors-hack\"."
```

### Example Code

```js
const url = 'https://api.dropboxapi.com/2/users/get_current_account';

await axios({
    method: 'post',
    headers: { 
        Authorization: `Bearer ${key}`
    },        
    url
});

// Also tried this...

await axios({
    method: 'post',
    headers: { 
        Authorization: `Bearer ${key}`
    },        
    url,
    transformRequest: [function (data, headers) {
    // Content type header is not present here anyway, only Authorization?
    delete headers['content-type'];
    return data;
    }]
});
```

### Expected behavior

There is a way to configure axios not to send a content-type header.

### Axios Version
1.1.3

### Browser

NA

### Browser Version

NA

### Node.js Version

v16.17.0

### OS

Ubuntu

### Additional Library Versions

NA

### Additional context/Screenshots

NA

**Comment by lcsjunior** [comment]
@chrisbrain you can define 'Content-Type': 'application/json'.

See the following example:

```js
axios.post('https://api.dropboxapi.com/2/users/get_current_account', null, {
  headers: {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${accessToken}`
  }
});
```

**Comment by vgfeng** [comment]
set content-type to null  or  delete it in transformRequest not work for me ,  it will  add another content-type  by auto;

 finally i change it to empty string solved my problem;

**Comment by tlevesque-ueat** [comment]
Isn't it a bug, though? If there's no request body, there shouldn't be a `Content-Type` header at all...
