### ISSUE TITLE
AxiosError returns when request status code is 404

### ISSUE THREAD

**Issue by martinsdsigor** [axios/axios#5239]
### Describe the bug

When you make a request that result is a response if status code 404, the AxiosErro is throwed

### To Reproduce

force a request to return status code 404

### Code snippet

```js
async function test(){
   const res =  await axios.get(`${baseUrl}/loja-ws/v1/enderecos/loja/00`)
   console.log(res.data)
}
```

### Expected behavior

Not return a AxiosError, because the request was successfuly and only get a not found response

### Axios Version

1.1.3

### Node.js Version

16.18.0

### OS

Windows

**Comment by WillianAgostini** [comment]
Hi @martinsdsigor
This is not a bug, it is correct to throw an error for status 404.
You can customize by passing 'validateStatus' parameter, see the docs https://github.com/axios/axios#handling-errors.

**Comment by martinsdsigor** [comment]
@WillianAgostini thanks for support!!
