### ISSUE TITLE
warn Package axios has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by MathewAzmat** [axios/axios#5253]
### Describe the bug

. Reason: Package subpath './package.json' is not defined by "exports" in /Users/mac/Desktop/Abubakar/Projects/ProjectName/node_modules/axios/package.json

### Axios Version

1.1.3

**Comment by DigitalBrainJS** [comment]
> Axios Version
> 1.1.3

This was probably fixed in version `1.2.0-alpha.1`
