### ISSUE TITLE
Axios interceptor not working with Object spreading syntax ({...})

### ISSUE THREAD

**Issue by lucasrmendonca** [axios/axios#5293]
### Describe the issue

I am using a request interceptor to add custom headers to my requests. I add a default header as well as an Authorization header for access tokens (see code below).

When directly mutating the originalRequest to add my Authorization header, it works. But when creating a new object using object spread syntax, the request fails silently. 

It seems that the working solution has headers of type AxiosHeaders while the object spreading solution has headers of type Object. Maybe this has something to do with it? I didn't find an AxiosHeaders constructor exported by the axios library so I'm not sure.

### Example Code

```js
axios.defaults.headers.common['My-custom-header'] = 'custom-value';
 
axios.interceptors.request.use(
  (request) => getRequestWithAuthorizationHeaders(request),
  (error) => error
);

// This works ✅
async function getRequestWithAuthorizationHeaders(originalRequest) {
  originalRequest.headers.Authorization = `Bearer ${await getAccessToken()}`;
  
  return originalRequest;
}

// This doesn't ❌
async function getRequestWithAuthorizationHeaders2(originalRequest) {
  const authorizedRequest = {
    ...originalRequest,
    headers: {
      ...originalRequest.headers,
      "Authorization": `Bearer ${await getAccessToken()}`;
    }
  };
  
  return authorizedRequest;
}
```

### Expected behavior

Creating a copy of the original request should also work

### Axios Version

1.1.3

### Adapter Version

XHR

### Browser

Chrome

### Browser Version

107.0.5304.110

### Node.js Version

v16.17.1

### OS

Ubuntu 20.04

**Comment by Romick2005** [comment]
PS Better way is not to modify header in the interceptor, but pass them directly to the axios configuration call.

**Comment by DigitalBrainJS** [comment]
It works in the [latest version](https://www.npmjs.com/package/axios/v/1.2.0-alpha.1)

https://codesandbox.io/s/axios-headers-merging-pufq8z?file=/src/index.js

```js
import axios from "axios";

(async (url) => {
  axios.defaults.headers.common["My-common-header"] = "my-common-value";

  axios.interceptors.request.use(
    (originalRequest) => {
      const authorizedRequest = {
        ...originalRequest,
        headers: {
          ...originalRequest.headers,
          "My-interceptor-header": "my-interceptorValue"
        }
      };

      return authorizedRequest;
    },
    (error) => error
  );

  axios.interceptors.request.use(
    (request) => {
      request.headers.set({
        "My-set-header1": "my-set-value1",
        "My-set-header2": "my-set-value2"
      });

      return request;
    },
    (error) => error
  );

  const { data } = await axios.post(url, "payload", {
    headers: {
      "My-header": "my-value"
    }
  });

  console.log("headers echo:", data.headers);
})("https://httpbin.org/post");

```

**Comment by lucasrmendonca** [comment]
Thanks, @DigitalBrainJS, that's exactly what I was looking for.
