### ISSUE TITLE
Axios 1.2.0 requires ProgressEvent DOM type

### ISSUE THREAD

**Issue by gzm0** [axios/axios#5297]
### Describe the bug

Seems like #5227 re-introduced #3219.

When attempting to compile with TypeScript without DOM types, compilation fails:

```
node_modules/axios/index.d.ts(275,11): error TS2304: Cannot find name 'ProgressEvent'.
```

### To Reproduce

```
// tsconfig.json
{
  "compilerOptions": {
    "sourceMap": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "strict": true,
    "target": "es2018",
    "module": "commonjs",
    "lib": ["es2018"],
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node"
  }
}
```

### Code snippet

```ts
import axios from "axios";

axios({
    method: "GET",
    url: "https://example.com",
  });
```

### Expected behavior

Compiles without DOM types.

### Axios Version

1.2.0

### Additional Library Versions

typescript: 4.9.3

**Comment by badfun** [comment]
Same issue here. Typescript 4.9.3, Axios 1.2.0

**Comment by Robert-Rendell** [comment]
I fixed this by using this in my package.json and npm i:

`
"axios": "~1.0.0",
`

**Comment by hlibcentrica** [comment]
The only thing that helped, except using DOM types, was downgrading back to Axios v0.27.2

Is there a way to emulate this ProgressEvent in the project while we are waiting for a fix?

**Comment by gzm0** [comment]
> The only thing that helped, except using DOM types, was downgrading back to Axios v0.27.2

For us, Axios 1.1.3 does not expose this issue so you should be able to at least do the switch to 1.x.

**Comment by bradleymackey** [comment]
`declare type ProgressEvent = never`

**Comment by pSnehanshu** [comment]
Thanks, @bradleymackey for the workaround. A [fix](https://github.com/axios/axios/pull/5308) has been created, but not released yet. Until then, this workaround works.

**Comment by riywo** [comment]
Looks like 1.2.1 contains this fix! https://github.com/axios/axios/releases/tag/v1.2.1
