### ISSUE TITLE
It's not possible get bundles path using node.

### ISSUE THREAD

**Issue by mshima** [axios/axios#5301]
### Describe the bug

Now that axios defines `exports` at package.json, every resource should be exported.

### To Reproduce

```sh
mkdir test_axios
cd test_axios
npm install axios@latest
node -e "console.log(require.resolve('axios/dist/axios.min.js'))"
```

or
```
node -e "console.log(require.resolve('axios/axios.min.js'))"
```

### Expected behavior

`require.resolve('axios/dist/axios.min.js')` or `require.resolve('axios/axios.min.js')` should return the bundle path.

### Axios Version

1.x

### OS

macOS

**Comment by DigitalBrainJS** [comment]
These browser bundles are for CDN usage only. They are not intended to be loaded with node.js

**Comment by mshima** [comment]
It not loaded by node, it's resolved and bundled into an application.
This example is using axios 0.x:
https://github.com/jhipster/generator-jhipster/blob/f12930941afc61f00d3474d9e8bb984fc5d35d5f/generators/react/templates/webpack/webpack.common.js.ejs#L147-L150

If it's distributed I don't see a reason for not been exported. Unless it will be removed in a minor release.

**Comment by mbrandl87** [comment]
Hi all,

any news on this? I had to apply mshimas pr via patch-package for the webpack build to work.
@mshima Or am I doing something wrong here? This happens after upgrade to jhipster 8.0.0, with beta-3 it worked although I can't find the min.js in axios/package.json (1.5.5 vs 1.6.0) there either. At least not in the exports like your PR suggested.

**Comment by mshima** [comment]
Workaround is `path.join(path.dirname(require.resolve('axios/package.json')), 'dist/axios.min.js')`.

**Comment by mbrandl87** [comment]
Thx for the quick help, I messed that up while merging the 8.0.0 changes :)

**Comment by jasonsaayman** [comment]
seems like a very non-standard way to consume the package that i dont think we will implement for now
