### ISSUE TITLE
Axios response data looks wierd in my powershell

### ISSUE THREAD

**Issue by morphiezy** [axios/axios#5313]
### Describe the bug

I try to fetching data using axios :

```js
const URL = "https://jsonplaceholder.typicode.com/users"

axios.get(URL)
.then((res) => console.log(res.data))
```

but when it's done and i try to access the result using pwsh or cmd : 

![Screenshot 2022-11-26 211341](https://user-images.githubusercontent.com/71913929/204093481-28e857c1-41b1-4764-b56a-5cb28a0ec98b.png)

Data is displayed in wrong format but in my browser it is displayed in the correct format : _Object / JSON_

### To Reproduce

```js
const URL = "https://jsonplaceholder.typicode.com/users"

axios.get(URL)
.then((res) => console.log(res.data))
```

**Comment by maxsurgithub** [comment]
Same bug on some APIs.

It's strange because on other APIs that my app calls, there is no bug...

I had to go back to version 1.1.3 for now.

**Comment by C0ZEN** [comment]
I am using a Node.js serve, and this parsing issue is causing GitHub GraphQL queries to simply fail.
Falling back to 1.1.3 is the workaround.

**Comment by DigitalBrainJS** [comment]
Duplicate #5296
You can use Axios `1.2.0-alpha.1` until the fix is released.
