### ISSUE TITLE
Axios v1.2 bad/truncated response data

### ISSUE THREAD

**Issue by ps-bobbykotzev** [axios/axios#5323]
### Describe the bug

Axios@1.2 returns bad/truncated data for some web image requests. Same exact request using v0.27.2 returns correct data. Seems specific for some sites but was not able to determine what's different compared with other ones where v1.2 works fine.

Live example:
http://runkit.com/bobby-ko/axios-v1-2-bad-truncated-response-data

### To Reproduce

Request url: https://www.sealybaby.com/wp-content/uploads/sites/4/2022/10/EM904-BBX_POP-768x768.jpg
Response Buffer length is 51686 bytes

### Code snippet

```js
const axios = require("axios@1.2.0");
const oldAxios = require("axios@0.27.0");
const requestOptions = {
  "url": "https://www.sealybaby.com/wp-content/uploads/sites/4/2022/10/EM904-BBX_POP-768x768.jpg",
  "method": "GET",
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive",
    "Pragma": "no-cache",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
  },
  "timeout": 30000,
  "responseType": "arraybuffer",
  "decompress": true
};

const incorrectResponse = await axios(requestOptions);
const correctResponse = await oldAxios(requestOptions);

console.info(`Expected buffer length of ${correctResponse.data.length} but recieved ${incorrectResponse.data.length}`);
```

### Expected behavior

Response Buffer length should be 56161

### Axios Version

1.2

### Node.js Version

18.11

### OS

Windows, Linux

**Comment by jaxxeh** [comment]
Linked to #5296 / #5298. Buffer size difference is explained by failure to decompress (difference is small because images are usually already quite optimally compressed in their original format).

Setting the request header `Accept-Encoding` to `identity` (as suggested in the linked issues) is a temporary workaround, see [https://runkit.com/jaxxeh/63860b2b3ac49a0008b7c9c7](https://runkit.com/jaxxeh/63860b2b3ac49a0008b7c9c7).

Downgrading axios to 1.1.3 should also work.

**Comment by ps-bobbykotzev** [comment]
Thanks @jaxxeh. 
Confirmed, changing the `Accept-Encoding` works, but it's not a viable option for my project. v1.1.3 works, and so does 1.2.0-alpha.1.
Because I can, I'll go with the alpha for now until the next official release.

**Comment by deepak786** [comment]
Use release 1.2.1

**Comment by jasonsaayman** [comment]
Please try v1.2.1 if that does not work please open a new issue and @ me
