### ISSUE TITLE
Not able to install axios 

### ISSUE THREAD

**Issue by Nareshchoudhary02** [axios/axios#5329]
### Describe the issue

I run `$ npm i axios ` and it could not resolve 

Error : 
<img width="603" alt="Screenshot 2022-12-02 at 1 38 42 AM" src="https://user-images.githubusercontent.com/107427909/205149643-6db5e577-1d81-4899-aedf-1678c813ad37.png">

**Comment by JawadAhbab** [comment]
It might not be related to Axios. We are having no problem in our side. Try deleting your node_modules & lock file and re-install all the dependencies. It should work!

**Comment by Nareshchoudhary02** [comment]
> I don't think this is related to axios. You have some incorrect dependecy with your other libraries. Maybe try to delete package-lock.json and try to install all the modules again.

I run `npm i axios -force` and it worked for me. Thanks for solution.

**Comment by jasonsaayman** [comment]
Going to close this does not seem to be a direct issue with Axios, please open a new issue if you believe this is related to Axios and not potentially something else.
