### ISSUE TITLE
Axios attempts to resolve IPv6 addresses as hostnames

### ISSUE THREAD

**Issue by Rishi556** [axios/axios#5333]
### Describe the bug

Up to v0.27.2, axios could be used to reach ipv6 endpoings with a format like the following: `http://[2001:db8::5]:6001/lists`. As of 1.0.0, axios thinks that's a hostname and attempts to use dns to resolve it. 

```
  cause: Error: getaddrinfo ENOTFOUND [2001:db8::5]
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: '[2001:db8::5]'
  }
}
```

### To Reproduce

Attempt to make a axios call to a ipv6 address using the common [IPv6]:PORT format.

### Code snippet

```js
let res = await axios.post('http://[2001:db8::5]:6001/lists', {})
```

### Expected behavior

Axios should attempt to open a socket to  2001:db8::5 port 6001 and make the request. 

### Axios Version

1.2.0

### Adapter Version

HTTP

### Node.js Version

v18.12.0

### OS

Mac 12.5.1

**Comment by SwenenzY** [comment]
Same issue at axios 1.2.2 ( Ubuntu 22 / node v12.22.9)

cause: Error: getaddrinfo ENOTFOUND [2600:1901:1:ff2::]

**Comment by tofers** [comment]
getaddrinfo ENOTFOUND [2a01:4f9:c01]

**Comment by swcm-mnestler** [comment]
Apparently axios sets the `options.hostname` to the result of `new URL(fullpath).hostname`, so it will always include the brackets for ipv6 addresses. The `follow-redirects` module has an extra conversion step to strip ipv6-brackets, but it only applies to the `request(<url>)` syntax - it looks like axios needs to apply this to the `options` object manually. https://github.com/follow-redirects/follow-redirects/blob/d388fe26052a6042310d96964f15f00c56791161/index.js#L549

**Comment by Rishi556** [comment]
Still present as of 1.4.0

**Comment by ssbarnea** [comment]
Any chance to get this sorted, especially as ipv6 became the default on my platforms?
