### ISSUE TITLE
Decode error

### ISSUE THREAD

**Issue by Zikkado** [axios/axios#5336]
### Describe the bug

I was making a GET request to get an API response, I passed the entire header correctly, Authorization: "Bearer <api-key>" + Accept: "application/vnd.api+json"
the undecoded response, simply giving me the return 200 but with the json without decode.

The key I provided is temporary, it has a limit of 10 requests per minute.

### To Reproduce

https://runkit.com/embed/n960ru9as00a

### Code snippet

```js
async function GetID() {
  const response = await axios.get('https://api.pubg.com/shards/steam/players?filter[playerNames]=30_ImZikkado', {
    headers: {
      'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3NTkwNzJkMC01NTQwLTAxM2ItNWMwZC0wNjE4ZTJmOTc0NzgiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNjcwMDc1ODk2LCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6Ii0wNDA0Nzc3ZS0wZGU5LTQwOGEtOGRhMi03NDYyYmYzMjhkNzcifQ.SzVwnPhfB8f8CvBAMiw20XaUZ6IMirLb2Z39fGSZddk',
      'Accept': 'application/vnd.api+json'
    }
  })

  console.log(response.data)
}
```

### Expected behavior

the json is returned correctly,

### Axios Version

1.2.0

### Browser

Chrome

### Node.js Version

v16.17.0

### OS

Windows 10

### Additional Library Versions

```bash
"dependencies": {
    "axios": "^1.2.0",
    "discord.js": "^14.7.1",
    "request": "^2.88.2"
  }
```

### Additional context/Screenshots

```bash
Not Decoded:
https://cdn.discordapp.com/attachments/1047304334175633518/1048791314474475521/image.png

Decoded using the request library:
https://cdn.discordapp.com/attachments/1047304334175633518/1048791376080404530/image.png
```

**Comment by choimin9510** [comment]
Add axios.defaults.headers['Accept-Encoding'] = 'identity';

But, did it change suddenly?
OTL

**Comment by dalwadani** [comment]
> Add axios.defaults.headers['Accept-Encoding'] = 'identity';
> 
> But, did it change suddenly? OTL

👍
this solved the bug for us. We are migrating away from axios duo to these issues.

**Comment by lucaswerkmeister** [comment]
Simpler example that doesn’t require any authorization tokens:

```js
require('axios').get('https://en.wikipedia.org/w/api.php?action=query&meta=siteinfo&format=json').then(r => console.log(r.data));
```

Standard MediaWiki API request. Logs proper JSON with axios 1.1.3 but garbled nonsense with axios 1.2.0. `git bisect` points to a3d901777bc06e78adae3081f694cdbf76241303 as the culprit, though I haven’t yet tracked down the bug inside it.

**Comment by lucaswerkmeister** [comment]
Okay, I found the bug. The new code in #5250:

```diff
-        if (data && data.length === 0 && res.headers['content-encoding']) {
+        if ((!responseLength || res.statusCode === 204) && res.headers['content-encoding']) {
```

requires that the `content-length` response header is set. If it isn’t (e.g. the [API request I mentioned](curl -i 'https://en.wikipedia.org/w/api.php?action=query&meta=siteinfo&format=json') doesn’t respond with a `content-length`), then axios now silently deletes the `content-encoding`, even though there still is a nonempty response that must be decoded.

**Comment by lucaswerkmeister** [comment]
Though I think the old code was buggy too, just in a way that didn’t come up as often – `data` was referring to the *request* data, not the *response* data, if I’m not mistaken.

**Comment by lucaswerkmeister** [comment]
Apparently this bug was actually already fixed in 9041c7d272 / #5306.

Can we have a release with the fix?

**Comment by Zikkado** [comment]
you can do the correction update yes.

**Comment by tm1000** [comment]
1.2.1 has the fix

**Comment by jasonsaayman** [comment]
Please try 1.2.1 if that does not work please open a new issue and mention me.

**Comment by Zikkado** [comment]
after the update here it was normal, there was no problem.
