### ISSUE TITLE
Support logical assignment of request header

### ISSUE THREAD

**Issue by a272121742** [axios/axios#5340]
### Is your feature request related to a problem? Please describe.

we can use `axiosInstance.defaults.headers` define http base headers. but for a period of time, We hope through some **Symbol** to set or delete base headers like [caddy header](https://caddyserver.com/docs/caddyfile/directives/header)。because we want to del base header for sometime in a particular case. 3q

### Describe the solution you'd like

```js
function headerAssign(source = {}, target = {}) {
  const keys = Object.keys(target)
  const len = keys.length
  const result = Object.assign(Object.create(null), source)

  for (let i = 0; i < len; i += 1) {
    const item = keys[i]
    const cfg = { name: item, type: '+' }
    if (/^[+\-?]/.test(item)) {
      cfg.type = item[0]
      cfg.name = item.slice(1)
    }
    const { type, name } = cfg
    switch (type) {
      case '-':
        Reflect.deleteProperty(result, name)
        break
      case '?':
        result[name] = toString(result[name]) || toString(target[item])
        break
      case '+':
        result[name] = target[name]
        break
    }
  }
  return result
}

// for example
headerAssign({ foo: 'foo', bar: 'bar' }, { '-foo': '' }) // => { bar: 'bar'}
headerAssign({ foo: 'foo' }, { '?foo': 'foo2' }) // => { foo: 'foo'}
headerAssign({ foo: '' }, { '?foo': 'foo2' }) // => { foo: 'foo2' }
```
in `axios`， we can use Symbol like it: 

```js
axios.get('url', {}, { headers: {
  '-foo': '',
  '?bar': 'bar'
}})
```

**Comment by DigitalBrainJS** [comment]
You can set the header to `null` or `false` to remove it. A value of `false` also means `don't set it later` inside Axios, just like the `User-Agent` header.
In addition, as a workaround AxiosHeaders class has a `set` method that accepts an optional `rewrite` argument to keep already defined headers:
```js 
new AxiosHeaders({ x: 1,  y: 2 }).set({x: 3, z: 4}, false).toJSON() // => {x: "1", y: "2", z: "4"}
```
I do not reject the possibility of introducing special tokens, but we need to carefully consider the expediency of implementing this functionality.

**Comment by a272121742** [comment]
Thank you for your reply. I can really meet my needs after trying.
But for `?` **Symbol** demand，how can I achieve it
