### ISSUE TITLE
after upgrading to "axios": "^1.2.1", 

### ISSUE THREAD

**Issue by monafHorany** [axios/axios#5357]
### Describe the bug

AxiosError: unexpected end of file
    at AxiosError.from (C:\Users\samqw\Documents\scrapping\sense\node_modules\axios\dist\node\axios.cjs:785:14)
    at BrotliDecompress.handleStreamError (C:\Users\samqw\Documents\scrapping\sense\node_modules\axios\dist\node\axios.cjs:2696:29)
    at BrotliDecompress.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.1',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://www.sense.com.tr/kaban-469',
    data: undefined
  },

### To Reproduce

const response = await axios.get("https://www.sense.com.tr/kaban-469");

const outerhtml = response.data;

### Expected behavior

this snippet code above was working perfectly on "axios": "^0.21.0", before upgrading to "axios": "^1.2.1"

**Comment by elvisun** [comment]
+1 same error message, also 1.2.1

**Comment by timdodsgon** [comment]
Same error

**Comment by AuspeXeu** [comment]
This library has been terribly instable recently, we have migrated away from it ....

**Comment by jasonsaayman** [comment]
Will get the fix for this out asap
