### ISSUE TITLE
headers are not available in beforeRedirect

### ISSUE THREAD

**Issue by claasahl** [axios/axios#5365]
### Describe the bug

According to the documentation the configuration option `beforeRedirect` should be called with response headers but it does not. Only the `options` parameter is passed to `beforeRedirect` (i.e. no `headers` parameter). 

```typescript
  // `beforeRedirect` defines a function that will be called before redirect.
  // Use this to adjust the request options upon redirecting,
  // to inspect the latest response headers,
  // or to cancel the request by throwing an error
  // If maxRedirects is set to 0, `beforeRedirect` is not used.
  beforeRedirect: (options, { headers }) => {
    if (options.hostname === "example.com") {
      options.auth = "user:password";
    }
  },
```
(copied from https://www.npmjs.com/package/axios/v/1.2.1#request-config)

This seems to be a duplicate of https://github.com/axios/axios/issues/5176.

### To Reproduce

```javascript
//var axios = require("axios@0.27.2") // works
//var axios = require("axios@1.0.0") // does not work
//var axios = require("axios@1.1.1") // does not work
//var axios = require("axios@1.1.2") // does not work
//var axios = require("axios@1.1.3") // does not work
//var axios = require("axios@1.2.0-alpha.1") // does not work
//var axios = require("axios@1.2.0") // does not work
var axios = require("axios") // does not work

// Works with an older version
// var axios = require("axios@0.27.2")
var express = require("express")
var app = express()

app.get('/redirect', (req, res) => {
  res.cookie("Hello", "World");
  res.redirect("/");
})

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(3000, () => {
    axios.get("http://localhost:3000/redirect", {
        // Headers undefined
        beforeRedirect: (options, { headers }) => {
            console.log({options, headers});
        }
    });
});
```

### Expected behavior

`beforeRedirect` should be called with both the `options` and `headers` parameters.

### Axios Version

1.2.1

**Comment by exander77** [comment]
I can confirm.

**Comment by dickorydock** [comment]
Appreciate the work that has gone into making this package. I tried the fix mentioned in https://github.com/axios/axios/issues/5176 (installing a different release,. axios@1.2.0-alpha.1) but that didn't seem to work and accessing headers using beforeRedirect still seems to be broken.

**Comment by starker22** [comment]
confirm issue, 1.3.5 still not works

**Comment by k1de** [comment]
I confirm too

**Comment by reciprocal-space** [comment]
+1 can confirm the problem persists on v1.3.6

**Comment by starker22** [comment]
pls fix, want use latest version but cant

**Comment by k1de** [comment]
i guess this is the solution https://github.com/axios/axios/commit/7e6a8dad300f5e53a87e7907d11b1796198c4099

**Comment by k1de** [comment]
I guess this is the solution 8b5cab4e318cb7cbecbfecdf0a6ff49b7e3cc70a

**Comment by marcusdelang** [comment]
Still doesn't work in 1.6.1.
@jasonsaayman Please help merging any of the PRs 🙏

**Comment by pro-vi** [comment]
Encountered in 1.6.5
