### ISSUE TITLE
Axios does not append form boundary for multipart requests in node environment

### ISSUE THREAD

**Issue by Dragas** [axios/axios#5379]
### Describe the bug

When trying to interface with endpoints that consume `multipart/form-data` requests, on non browser applications axios needs to use `form-data` package. By default, axios attempts to send `Content-Type: application/www-form-url-encoded` content type header for non file uploads, and any requests that would attempt to send `form-data` objects. This can be overridden by sending your own `Content-Type` header of `multipart/form-data`. Due to this, it's possible to confuse HTTP servers, because then axios does not include the boundary definition, as it is required by HTTP specification for multipart requests.

Below is the actual request sent by axios
```
POST /api/v1/upload HTTP/1.1
Host: localhost:8080
Content-Type: multipart/form-data
Content-Length: [length]
User-Agent: axios
Accept: *
Connection: close

---boundary
Content-Disposition: form-data; name="metadata"
Content-Type: application/json

{"name": "foo"}
---boundary
Content-Disposition: form-data; name="content"; filename="foo"
Content-Type: application/octet-stream

[binary content]
---boundary--
```

Workaround for this issue (as per snippet in reproduce) is to rebuild the content-type header yourself, by appending `FormData#getBoundary()` value.

```ts
import FormData from 'form-data'
import axios from 'axios'
import * as fs from 'fs'

const api = axios.create({
    "baseURL": "http://localhost:8080/api/v1"
})
const formData = new FormData();
const metadata = {
    "name": "foo"
};
const file = fs.createReadStream("file.txt");

formData.append('metadata', JSON.stringify(metadata), {contentType: 'application/json'})
formData.append('content', file, {filename: metadata.name});

const responsedata =(await api.post('upload', formData, {
    headers: {'Content-Type': `multipart/form-data; boundary=${formData.getBoundary()}`}
})).data
```

### To Reproduce

The issue can be reproduced by sending a `FormData` object via `axios#post(string, object, object)` method as follows.

### Code snippet

```js
import FormData from 'form-data'
import axios from 'axios'
import * as fs from 'fs'

const api = axios.create({
    "baseURL": "http://localhost:8080/api/v1"
})
const formData = new FormData();
const metadata = {
    "name": "foo"
};
const file = fs.createReadStream("file.txt");

formData.append('metadata', JSON.stringify(metadata), {contentType: 'application/json'})
formData.append('content', file, {filename: metadata.name});

const responsedata =(await api.post('upload', formData, {
    headers: {'Content-Type': `multipart/form-data`}
})).data
```

### Expected behavior

Expected behavior is that the request looks like this in its raw http form

```
POST /api/v1/upload HTTP/1.1
Host: localhost:8080
Content-Type: multipart/form-data; boundary=---boundary
Content-Length: [length]
User-Agent: axios
Accept: *
Connection: close

---boundary
Content-Disposition: form-data; name="metadata"
Content-Type: application/json

{"name": "foo"}
---boundary
Content-Disposition: form-data; name="content"; filename="foo"
Content-Type: application/octet-stream

[binary content]
---boundary--
```
Notice that content-type header contains boundary definition

### Axios Version

0.24.0

### Adapter Version

?

### Browser

Node specific

### Browser Version

Node specific

### Node.js Version

16.13.2

### OS

WSL2

### Additional Library Versions

```bash
form-data: 4.0.0
```

**Comment by DigitalBrainJS** [comment]
> Axios Version
> 0.24.0

Well, that was to be expected. Axios v0.24 does not support FormData in node.js, basic support was introduced in v0.27.0. In older versions, you must generate the correct request yourself.

**Comment by Dragas** [comment]
That explains a lot then. Cheers.
