### ISSUE TITLE
"Content-Type" cannot be set correctly

### ISSUE THREAD

**Issue by OVYVO** [axios/axios#5391]
### Describe the bug

When I have initialized an Axios instance and want to change the “Content-type“, No matter how I set it, I always get null.However, when I set the non “Content-Type“ property, I can assign the value correctly.I don't know whether this is a bug or my code is faulty.
I hope someone can help me.
![image](https://user-images.githubusercontent.com/44453678/208402893-cf7fadb5-d285-4646-a86c-6c28b4c8f108.png)
![image](https://user-images.githubusercontent.com/44453678/208403154-72aaf4cf-6a2f-4a2d-a71d-cc57b3d51ce3.png)

### Code snippet

```js
const instance: AxiosInstance = axios.create({
  headers:{
    'Content-Type': 'application/x-www-form-urlencoded',
  },
})
instance.interceptors.request.use((config)=>{
  if (config.method === "get") {
    config.data = { unused: 0 }; // Solve the get request cannot add 'Content-Type'
  }
  config.headers = {
    'Content-Type': 'application/x-www-form-urlencoded'
  }
  console.log(config)
  return config
},(err)=>{
  console.log(err)
})
```

### Axios Version

1.2.1

### Browser

Chrome

### Node.js Version

v14.20.0

### Additional Library Versions

```bash
Vue v3.2.45
```

**Comment by OVYVO** [comment]
I also tried to pass in the "headers" object in config and modify the "Content-Type" property, but it still cannot be set correctly. and output "null" in the request interceptor.

**Comment by Ehsan200** [comment]
hello there!
axios automatically set “Content-Type“ header to null if there is no data to send.
you should set data in config.

**Comment by OVYVO** [comment]
@Ehsan200 Thank you for your attention. I have tried this method and it has no effect, but I solved the problem through other ways, and I will close the issue！

**Comment by whalesink** [comment]
> @Ehsan200 Thank you for your attention. I have tried this method and it has no effect, but I solved the problem through other ways, and I will close the issue！

How did you solved it?
