### ISSUE TITLE
npm ERR! Cannot read property 'axios' of undefined

### ISSUE THREAD

**Issue by MRameez820** [axios/axios#5423]
### Describe the bug

I am trying to run gcloud ap deploy command on google cloud app engine but its giving me error npm ERR! Cannot read property 'axios' of undefined. I am using axios version 0.21.4

### Axios Version

0.21.4

### Node.js Version

v18.12.1

### Additional Library Versions

```bash
Running on google cloud
```

**Comment by DavidJDallas** [comment]
Hi, please can you provide more information? As it stands it sounds like the issue is not with Axios but that you're trying to access a property on an undefined variable.

**Comment by lbineau** [comment]
Latest release of axios is 1.5.0 maybe you can try to upgrade?

**Comment by micalevisk** [comment]
I just tested with v1.6.1 and got the same error when using node v14.19.3 (npm v6.14.17)

**Comment by luiznasciment0** [comment]
why on earth deleting lock file solves this? hahaha 🤯
