### ISSUE TITLE
TypeScript error /axios/index.d.ts(6,18): ']' expected.  TS1005   

### ISSUE THREAD

**Issue by flakesrc** [axios/axios#5428]
### Describe the bug

I got an error when try to use `axios.get(url)`: 

```
TypeScript error in /.../react-app/node_modules/axios/index.d.ts(6,18):
']' expected.  TS1005

    4 | 
    5 | type MethodsHeaders = {
  > 6 |   [Key in Method as Lowercase<Key>]: AxiosHeaders;
      |                  ^
    7 | };
    8 | 
    9 | interface CommonHeaders {
  ```

### To Reproduce

`axios.get(url)`

### Axios Version

"axios": "^1.2.2",

### Browser

Chrome

### Node.js Version

v18.9.0 and v18.9.0

### OS

Linux

### Additional context/Screenshots

![image](https://user-images.githubusercontent.com/42384773/210447526-dfa04911-a418-4ae6-8deb-779b7fc06e9d.png)

![image](https://user-images.githubusercontent.com/42384773/210447565-7d68cac1-9bbe-465b-a468-d57d0ca5c637.png)
![image](https://user-images.githubusercontent.com/42384773/210447615-970497c5-5b18-4702-bdf4-4946f2a3e11d.png)

**Comment by ajimae** [comment]
I am also experiencing this issues.

Any update on this issue?

**Comment by DigitalBrainJS** [comment]
You need to use TypeScript version 4.7 or later

**Comment by BaraaSoft** [comment]
> I was seeing this issue with `axios@1.2.2`, typescript `3.9.18` but when I updated to the latest typescript `4.9.4` it is now working 👍

Thanks that work
