### ISSUE TITLE
getAdapter method should became public to let adapters like axios-mock-adapter access http / xhr known adapters

### ISSUE THREAD

**Issue by paztis** [axios/axios#5474]
### Describe the bug

libraries like axios-mock-adapter define an adapter but in same cases need to access to original adapter.

It was working correctly before as the adapter was always a function.
Now it can be an array of string

Only the method getAdapter() in adapters/adapter.js can allow access to original adapters (xhr and http)
But this method is not exported a all at top level.

Can you export it ? 

### To Reproduce

Try to use axios-mock-adapter plugin with onNoMatch option

### Axios Version

1.2.1 and upper

**Comment by mogzol** [comment]
I would also appreciate this. I have a custom adapter that wraps the default one, but it is unusable with the latest axios releases as it is impossible to access the default adapters.

**Comment by unional** [comment]
The http adapter is also needed to workaround an issue for jsdom: https://stackoverflow.com/questions/51054286/cross-origin-http-request-originating-from-server-side-nodejs-axios-jsdom

Currently it is not exposed and with `exports` field we can't even force our way in using `declare module 'axios/lib/adapters/http'` for TypeScript.
