### ISSUE TITLE
Release 1.2.3

### ISSUE THREAD

**Issue by arthurfiorette** [axios/axios#5475]
Hey @DigitalBrainJS, you fixed the publish pipeline but seems that you forgot to run it and release 1.2.3.

**Comment by DigitalBrainJS** [comment]
The action failed to publish the npm release due to an authorization issue. @jasonsaayman [will publish](https://github.com/axios/axios/issues/5472#issuecomment-1385377768) it manually.

**Comment by jasonsaayman** [comment]
It is done, I will fix the token issue too
