### ISSUE TITLE
using `toFormData` with the right `Content-Type`

### ISSUE THREAD

**Issue by kaikaibenkai** [axios/axios#5481]
### Describe the issue

When sending a request, `Content-Type` of **the files** in the form is set to `application/octet-stream` by default.

### Example Code

```js
import axios from 'axios';
const buffer = ... // download a binary file
                   // it's always a png file
const form = axios.toFormData({
  name: 'pic.png',
  type: 'image',
  content: buffer, // the file field
});
await axios.postForm('https://www.feishu.cn/approval/openapi/v2/file/upload', form, {
  proxy: { // record this request
    protocol: 'http:',
    host: 'localhost',
    port: 8888,
  }
});
```

### Expected behavior

`Content-Type` of the binary stream can be set to a custom value.

### Axios Version

1.2.3

### Node.js Version

16.16.0

### OS

Windows 11 (22H2, 22621.1105)

**Comment by kaikaibenkai** [comment]
I can't find any documents about this method....

**Comment by j-koziel** [comment]
You can add content-type headers in the object you defined the proxy, like this:

```
{
headers: {
	'Content-Type': 'multipart/form-data'
	}
}
```

hope this makes sense :)

**Comment by DigitalBrainJS** [comment]
If you need to specify the `Content-Type` header for a buffer field, you have to append the field manually (See [`form-data` docs](https://www.npmjs.com/package/form-data))

```js
const form = axios.toFormData({
  name: 'pic.png',
  type: 'image'
});

form.append('content', buffer, {contentType: 'image/jpeg'});
```

**Comment by DavidJDallas** [comment]
Closing as it seems like this has been answered
