### ISSUE TITLE
Error type request header in typescript

### ISSUE THREAD

**Issue by adityaw24** [axios/axios#5489]
### Describe the issue

#5420 I got error after update axios

`const apiRequest = (arguments_: ApiRequestProperties) => {
  const { method, bodyRequest, params, path, url, timeout, headers, auth } =
    arguments_
  const baseUrl = url || BASE_URL || ''
  const config: AxiosRequestConfig = {
    headers: {
      'Content-Type': 'application/json',
    },
    url: {baseUrl} {path || ''},
    method,
    auth,
  }

  if (headers) {
    config.headers = { ...config.headers, ...headers } as AxiosRequestHeaders
  }

  if (bodyRequest) {
    config.data = bodyRequest
  }
  if (params) {
    config.params = {
      ...params,
      apikey: API_KEY,
    }
  }
  if (auth) {
    config.auth = auth
  }

  if (timeout) {
    config.timeout = timeout
  }

  return axios(config)
}`

### Axios Version

1.2.0

### Additional Library Versions

```bash
React 18.2,
typescript 4.9
```

**Comment by adityaw24** [comment]
![image](https://user-images.githubusercontent.com/83526639/214221974-fa8c052b-af6f-4859-8bbe-c51b5477aa6b.png)

**Comment by aksdevac** [comment]
already fixed wait for [1.2.4](https://github.com/axios/axios/pull/5487) release.
See this issue for details: https://github.com/axios/axios/issues/5476

**Comment by glutaminefree** [comment]
Latest release on NPM still 1.2.3
