### ISSUE TITLE
validateStatus option is ignored when using the axios.create method

### ISSUE THREAD

**Issue by popkinj** [axios/axios#5519]
### Describe the bug

When creating a new instance of Axios with the `create` method, I have tested that options like `baseURL` work as expected. However, I found after a lot of debugging that the `validateStatus` option is ignored.
When using Axios without the `create` method it behaves as expected.

## This works as expected
```javascript
axios("https://api.example.com/some/endpoint", {
  method: "GET",
  validateStatus: (status) => {
    console.log("you should see me in the console");
    return true; // Allow all statuses to correctly resolve the promise
  },
})
  .then((res) => {
    // Do something amazing
    console.log("even error codes make it to here", res.status);
  })
  .catch((errr) => {
    console.log("Technically only network errors should end up here", err);
  });
```

## This does not work as expected
```javascript
const api = axios.create({
  baseURL: "https://api.example.com",
  validateStatus: (status) => {
    console.log("you should see me in the console");
    return true; // Allow all statuses to correctly resolve the promise
  },
});

api
  .get("/some/endpoint")
  .then((res) => {
    // Do something amazing
    console.log("error codes should make it to here but they don't :(", res.status);
  })
  .catch((errr) => {
    console.log("All error, even error codes make it to here", err);
  });
```

### Expected behavior

The first code example honors the passing of html codes through the `validateStatus` option. When run, you should see the message "you should see me in the console" printed to the console. There should also be an integer html code within the result object.

In theory you should also see a message passed to the console in the second example. This doesn't happen. So we can tell the function for selecting html codes is not being run. As a result, there is never an integer code present in the `status` property of the result object passed when the promise is resolved.

### Axios Version

0.27.2

### Browser

Chromium

### Browser Version

109.0.5414.119

**Comment by DigitalBrainJS** [comment]
I don't see any problems. Everything seems to be working

https://codesandbox.io/s/axios-issue-5519-h6cwun?file=/src/index.js

```
0.27.2 
you should see me in the console 
error codes should make it to here but they don't :( 404
```

**Comment by popkinj** [comment]
> I don't see any problems. Everything seems to be working
> 
> https://codesandbox.io/s/axios-issue-5519-h6cwun?file=/src/index.js
> 
> ```
> 0.27.2 
> you should see me in the console 
> error codes should make it to here but they don't :( 404
> ```

Thanks for testing @DigitalBrainJS . There must be something else going on at my end. I'll close this.
