### ISSUE TITLE
Error: Cannot calculate proper length in synchronous way.

### ISSUE THREAD

**Issue by LockBlock-dev** [axios/axios#5520]
### Describe the bug

Relying on axios automatic serialization to create a form-data results in this error. The following lines are responsible of this error : https://github.com/axios/axios/blob/release/dist/node/axios.cjs#L2654 (mainly the `getLengthSync` function)

According to [form-data themselves](https://github.com/form-data/form-data), using `getLengthSync` is [not recommended](https://github.com/form-data/form-data/blob/master/Readme.md?plain=1#L350).

### To Reproduce

- Create a file buffer with `fs.createReadStream`
- Set HTTP header `Content-Type` to `multipart/form-data` to make use of [automatic serialization](https://github.com/axios/axios#-automatic-serialization-to-formdata)
- Get the form-data `Cannot calculate proper length in synchronous way.` error

### Code snippet

```js
const axios = require("axios");
const fs = require("node:fs");
const fileBuffer = fs.createReadStream("./file.ext");

axios.post('https://httpbin.org/post', {file: fileBuffer}, {
  headers: {
    'Content-Type': 'multipart/form-data'
  }
})
.then(({data}) => console.log(data))
.catch((err) => console.error(err));
```

### Expected behavior

The content length should be calculated without throwing any error.

### Axios Version

1.3.0

### Node.js Version

16.19.0

**Comment by DigitalBrainJS** [comment]
I wanted to avoid this so as not to introduce an anti-pattern due to one asynchronous call inside the adapter root promise, and defer this until the module is refactored, but since the community wants it... :)
