### ISSUE TITLE
Creating compatibility with fetch

### ISSUE THREAD

**Issue by llaenowyd** [axios/axios#5547]
### Describe the issue

I was trying to create a library that would allow the application to use `fetch` or `axios`. There are a lot of differences in the types, not just the function call to send a request, but all the related types such as Request, Response, Headers and so on.

The library I was trying to create has a different, application-related purpose. Allowing use of fetch or axios is a separate concern. In the worst case 2 variations of the library could separately provide support for fetch and axios. 

Do you know of any good examples in Typescript of a compatibility layer or adapters providing this kind of flexibility?

Thank you

**Comment by WillianAgostini** [comment]
Hi @llaenowyd 
you can use the lib [axios-fetch-adapter](https://github.com/vespaiach/axios-fetch-adapter), which provides an adapter to be used together with axios.
