### ISSUE TITLE
UNIT TEST CASE(JEST) FAILED IF I USE LATEST VERSION OF AXIOS

### ISSUE THREAD

**Issue by Sangee15S** [axios/axios#5571]
### Describe the issue

 If I update the axios with the latest version of **1.3.4(including 1.3.1,1.3.2,1.3.3)** ,Jest unit test case is failing. 
 I am getting the below error
     thrown: "Exceeded timeout of 300000 ms for a testfalse.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

axios **1.3.0** is working fine.

### Axios Version

1.3.4

### Adapter Version

HTTP

### Browser

Chrome

### Node.js Version

19.0.1

### Additional Library Versions

```bash
"dependencies": {
    "axios": "1.3.4",
    "express": "^4.18.2",
    "supertest": "^6.3.3",
    "winston": "^3.8.2"
  },
  "private": true,
  "devDependencies": {
    "jest": "^29.4.3"
  },
  "version": "1.0.0",
```

**Comment by WillianAgostini** [comment]
Hi @Sangee15S 
Can you add here an example with more details of how this is happening?
