### ISSUE TITLE
onUploadProgress not working using Google Chrome

### ISSUE THREAD

**Issue by Jensxy** [axios/axios#5574]
### Describe the bug

Two weeks ago I was able to execute an axios post request with onuploadprogress.

However, since a week ago or something like that the onUploadProgress is not triggered anymore. This problem only occurs in Google Chrome. It's still working in Edge and Firefox.

### To Reproduce

```
 function uploadFile() {
      const fileInput = document.getElementById('fileInput');
      const file = fileInput.files[0];
      const formData = new FormData();
      formData.append('file', file);

      axios.post('/api/upload', formData, {
        onUploadProgress: progressEvent => {
          const percentCompleted = Math.round((progressEvent.loaded * 100) / progressEvent.total);
          console.log(`Upload progress: ${percentCompleted}%`);
        }
      })
      .then(response => {
        console.log(response.data);
      })
      .catch(error => {
        console.error(error);
      });
    }
```

### Expected behavior

Logging the output of console.log(`Upload progress: ${percentCompleted}%`).

### Axios Version

1.3.4

### Browser

Chrome

### Browser Version

110

### Node.js Version

16.16.0

### OS

Windows 10

### Additional Library Versions

```bash
Vue 3.2.37
```

**Comment by npiyush97** [comment]
onUploadProgress: (progressEvent) => {
        let percentComplete = progressEvent.loaded / progressEvent.total;
        percentComplete = parseInt(percentComplete * 100);
        document.querySelector("div").style.width = `${percentComplete}%`;
        console.log(percentComplete);
      }
working fine on ubuntu Ubuntu 22.04.1 LTS  chrome Version 109.0.5414.119 (Official Build) (64-bit)

**Comment by npiyush97** [comment]
even better i think progressEvent.progress for loading bar.
