### ISSUE TITLE
isURLSearchParams return false

### ISSUE THREAD

**Issue by Zlaojie** [axios/axios#5599]
### Describe the bug

`function isURLSearchParams(val) {
  return typeof URLSearchParams !== 'undefined' && val instanceof URLSearchParams;
}`
I found that in the version 0.21.1，`val instanceof URLSearchParams` may return false In some cases.
Such as，when I  write `let data = new URLSearchParams` and compile my code with `core-js`，when below Chrome 62
，data's prototype will be compiled and rewritten, and `val instanceof URLSearchParams`will return false

### Axios Version

0.21.1

### Browser

Chrome 62 -

**Comment by DavidJDallas** [comment]
Closing as v 0.21.x is deprecated. If this problem is arising in later versions please let us know.
