### ISSUE TITLE
axios v1.3.4 request interceptor adds additional headers

### ISSUE THREAD

**Issue by eau-de-la-seine** [axios/axios#5609]
### Describe the bug

Hi, I have already opened [an issue very similar to this one](https://github.com/axios/axios/issues/4843) but it was about the `v0.27.2`, now I use the latest version of `axios` (`v1.3.4`)

The problem is: `axios` adds the following header by itself:
```
'Accept': 'application/json, text/plain, */*'
```
`Accept` isn't a mandatory header. Some servers that returns multiple type of format could interpret this the wrong way

### Code snippet

I may have located this `Accept` header in `axios` source code (line 1466):
```js
    transformResponse: [function transformResponse(data) {
      var transitional = this.transitional || defaults.transitional;
      var forcedJSONParsing = transitional && transitional.forcedJSONParsing;
      var JSONRequested = this.responseType === 'json';
      if (data && utils.isString(data) && (forcedJSONParsing && !this.responseType || JSONRequested)) {
        var silentJSONParsing = transitional && transitional.silentJSONParsing;
        var strictJSONParsing = !silentJSONParsing && JSONRequested;
        try {
          return JSON.parse(data);
        } catch (e) {
          if (strictJSONParsing) {
            if (e.name === 'SyntaxError') {
              throw AxiosError.from(e, AxiosError.ERR_BAD_RESPONSE, this, null, this.response);
            }
            throw e;
          }
        }
      }
      return data;
    }],
    /**
     * A timeout in milliseconds to abort a request. If set to 0 (default) a
     * timeout is not created.
     */
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {
      FormData: platform.classes.FormData,
      Blob: platform.classes.Blob
    },
    validateStatus: function validateStatus(status) {
      return status >= 200 && status < 300;
    },
    headers: {
      common: {
        'Accept': 'application/json, text/plain, */*'
      }
    }
  };
```

### Expected behavior

Not having HTTP headers _magically_ added by `axios`

### Axios Version

1.3.4

### Node.js Version

v16.19.1

**Comment by DigitalBrainJS** [comment]
That is a default config preset, not an interceptor logic.
I see no reason to change the current behavior that has developed historically. If the server does not support this header, there should be no problem. If the server processes the header, then the current value works for most users because it was previously obtained from users troubleshooting.
The header can be easily disabled via default config/instance config or request config, so it seems not a big deal.

**Comment by eau-de-la-seine** [comment]
Hi, thanks for you answer.
I don't know how historically it was developed but version `0.27.2` (latest version before major) didn't have this header, I know it because I see the differences in my tests
Maybe you're right, maybe having a default `Accept` header with `application/json` is convenient for the 90% (who do RESTful JSON), the question is how a HTTP server that return multiple type of responses will behave when they'll receive `application/json, text/plain, */*` (aka "every format").
Since `Accept` is overridable this issue isn't a bug but [you should inform in the documentation](https://axios-http.com/docs/req_config) the default headers set by `axios`

**Comment by DigitalBrainJS** [comment]
> but version 0.27.2 (latest version before major) didn't have this header, I know it because I see the differences in my tests

Actually, Axios 0.27.2 has this header, just like the oldest v0.1.0 version. Your issue probably relates to something else.
https://github.com/axios/axios/blob/bc733fec78326609e751187c9d453cee9bf1993a/lib/defaults/index.js#L131-L135
https://codesandbox.io/s/clever-resonance-hbvjtg?file=/src/index.js

> the question is how a HTTP server that return multiple type of responses will behave

I guess if users haven't reported related issues in 10 years, then the current value works for most, even though no quality values are set in the header for explicit prioritization.

> but you should inform in the documentation

Definitely, but to be honest, this is not the biggest lack of documentation, at the same time, this is the initial behavior, which is of little interest to most users.

**Comment by eau-de-la-seine** [comment]
Hi @DigitalBrainJS , this extract of code may be in the `0.27.2` source code, but I was not seeing it in my request interceptor, maybe it was added **after** the request interceptor.
Anyway now I use the latest `1.3.4` version, I don't encounter the bizarre `common, delete, get, head, post, put, patch` headers from `0.27.2`, and I know that `axios` adds a default `Accept: application/json, text/plain, */*` header if we don't set one, I consider this issue as closed. Thanks
