### ISSUE TITLE
Content type set to false when sending form data

### ISSUE THREAD

**Issue by davidteejay** [axios/axios#5615]
### Describe the issue

I'm trying to upload a base64 image to a server (Amazon AWS S3) in my React Native app. The base64 image is first converted to a file, then is appended to a form data and sent to the server.  I'm also explicitly setting the `Content-Type` as `multipart/form-data`.

The server returns a 400 error with `EntityTooSmall`, and on inspection, I can see that the `Content-Type` is set to `false`, even after explicitly stating it

<img width="793" alt="Screenshot 2023-03-22 at 10 05 15 AM" src="https://user-images.githubusercontent.com/19327099/226853392-6c2f26fd-012b-4ecd-a046-764dd7872fc1.png">

### Example Code

```js
const formData = new FormData();
formData.append("Content-Type", image.mimeType);
formData.append("file", file);

await axios.post(signedUrl.signedUrl, formData, {
  headers: {
    "Content-Type": "multipart/form-data",
  },
});
```

### Expected behavior

Axios should upload the form data and return a successful response

### Axios Version

1.3.4

### Additional Library Versions

```bash
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 132.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
      System Images: android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-macos: Not Found
```

**Comment by WillianAgostini** [comment]
Hi @davidteejay 

As far as I know, uploading a file to S3 from AWS, it's a PUT method. Have you tried with axios.put?
ref: https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

**Comment by parthjdabhi** [comment]
@davidteejay I am also facing the same like issue, I using a POST request with multipart form data API and passing the following.
` { headers: { "Content-Type": "multipart/form-data", "Authorization": auth.token } }`
Error Screenshot: 
<img width="802" alt="Screenshot 2023-03-28 at 12 25 01 PM" src="https://user-images.githubusercontent.com/10777063/228153863-43cd07e2-90fe-4090-adc9-4e92d0fea701.png">

The content type header gets changed to `Content-Type: false` and the Error description is just **Network error** not helpful to identify the error.

This happens to React Native Android apps only and occurs randomly not always. Very difficult to catch.
The iOS app works perfectly. 
Using **axios-1.3.4**

**Comment by davidteejay** [comment]
I solved this by appending an object instead of a file in the form data, i.e.,

```js
const file = {
    uri: image.content // base64 string or file URI
    type: image.mimeType
    name: imageFileName
}
```

As opposed to:
```js
const blobToFile = (blob, fileName) => {
  const b = blob;
  b.lastModifiedDate = new Date();
  b.name = fileName;
  return b;
};

const res = await fetch(image.content);
const blob = await res.blob();
const file = blobToFile(blob, imageFileName, image.mimeType);
```

**Comment by davidteejay** [comment]
@parthjdabhi I'm not sure what your issue is. I don't think it's related to this one. There are a couple of issues that discuss this: #5366, #4823, #4800

**Comment by Jes015** [comment]
Same :(

**Comment by Erbaz** [comment]
I am facing the exact same issue i.e Content-Type is set to false. Also using S3 to store images. With Postman, the multipart/form-data request is successfully sent but Axios is having issues. In my case I am using Axios ^1.3.5

**Comment by AhmedMustafa505** [comment]
I'm having the same issue using react-native-windows, I'm trying to upload a file using axios and formData but it's failing due to Network Error and the Content-Type is always set to false in the request error.

**Comment by Nidilap** [comment]
I am also having the same error, with Content-Type being set to false in the error returned by axios.
I tried using a blob and also a object, but both set Content-Type to false.

**Comment by itskingsclub** [comment]
> I am also having the same error, with Content-Type being set to false in the error returned by axios. I tried using a blob and also a object, but both set Content-Type to false.

this is working , thank you much @Nidilap

**Comment by dhruvil-saasinnova** [comment]
I have faced the same issue, but here's proper working solution :-

=============================================
const result = await DocumentPicker.getDocumentAsync({
copyToCacheDirectory: true,
});

```
  if (!result?.canceled) {
    const asset = result?.assets?.[0];

    const file = result?.assets ? result?.assets?.[0] : result;
    setSelectedFile({
      name: file?.name,
      uri: file?.uri,
      size: file?.size || 0,
      type: asset?.mimeType,
    });
```
=============================================
```
const formData = new FormData();
formData.append("excel_file", {
uri: selectedFile.uri,
name: selectedFile.name,
type: selectedFile.type,
} as any);

const res = await companyApiInstance.importExcelFileData(formData);
```

=============================================
// companyApiInstance
```
public importExcelFileData = async (data: FormData): Promise => {
const url = ${this.ENDPOINT}/import-excel-file;
return request({
url,
method: "POST",
data,
headers: { "Content-Type": "multipart/form-data" },
}).then((res: any) => res?.data);
};
```
