### ISSUE TITLE
method should be upper case not lower case 

### ISSUE THREAD

**Issue by GaryM02** [axios/axios#5617]
### Section/Content To Improve

In axios documentation when creating an instance, we are shown to add our request method with the following (method:'get'). An issue came about in my program that lasted for days. I thought first to configure cors and see if anything helped such as allow-access headers. The real issue was the method tag in the config had lower case 'get' instead of 'GET'.

### Suggested Improvement

I don't know if this is already known but if not could it be looked into and updated.

**Comment by vmskhan** [comment]
https://github.com/axios/axios/blob/e7decef6a99f4627e27ed9ea5b00ce8e201c3841/lib/core/Axios.js#L68

Hi @GaryM02, if you checkout the link above, in the core module of axios, the http method is converted to lowercase, even if it written in UPPERCASE. So there might be some other problem. Can you try again with lowercase 'get'.
