### ISSUE TITLE
CORS error with Next-Js

### ISSUE THREAD

**Issue by coccigabry** [axios/axios#5624]
### Describe the issue

Dear All,

I'm having very bad time trying to send POST request client side using Axios and Next.Js
I found few solution (adding cors and next-connect i.e.),  but unfortunately none of them involved axios.
I've tried checking on StackOverflow as well as here on GitHub, but I'm still groping in the dark.

I copy&paste my code below, hoping you may make my day helping me to sort this matter out.

`
//   /pages/api/orders/index.js

import Order from "@/models/Order"
import dbConnect from "@/utils/mongoConnect"

export default async function handler(req, res) {

    const { method } = req

    await dbConnect()

    if (method === 'GET') {
        try {
            const orders = await Order.find()
            res.status(201).json(orders)
        } catch (err) {
            res.status(500).json(err)
        }
    }

    if (method === 'POST') {
        try {
            const order = await Order.create(req.body)
            res.status(201).json(order)
        } catch (err) {
            res.status(500).json(err)
        }
    }
}
`

`
//   /components/Total.jsx

import { useSelector } from 'react-redux'
import styles from '../styles/Total.module.css'
import { useEffect } from "react";
import axios from 'axios';
import { useRouter } from 'next/router';
import { clearCart } from '@/redux/features/cartSlice';
import {
    PayPalScriptProvider,
    PayPalButtons,
    usePayPalScriptReducer
} from "@paypal/react-paypal-js";

export const Total = ({ page }) => {

    const router = useRouter()
    const total = useSelector(store => store.total)

    const createOrder = async (data) => {
        try {
            const res = await axios.post('http://localhost:3000/api/orders/', data)
            res.status === 201 && router.push(`/orders/${res.data._id}`)
            dispatch(clearCart())
        } catch (err) {
            console.error(err)
        }
    }

    // paypal functionality here

    
    return (
           //  rendering code here
    )
}
`

`
//  next.config.js

/** @type {import('next').NextConfig} */

const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'www.pngarts.com',
      },
    ],
  },
}

module.exports = nextConfig
`

Cheers

### Axios Version

^1.3.4

### Browser

Mozilla Firefox

**Comment by BakhshiMoeez** [comment]
1. While sending the request are you making sure that the "data" parameter you are sending is JSON object ? 

2. While sending the data pass the code below as third parameter 

{
  headers: {
    'Content-Type': 'application/json'
  }
}

**Comment by Charlygraphy23** [comment]
you can use [next-cors](https://www.npmjs.com/package/nextjs-cors)

```js
import NextCors from 'nextjs-cors';

async function handler(req, res) {
   // Run the cors middleware
   // nextjs-cors uses the cors package, so we invite you to check the documentation https://github.com/expressjs/cors
   await NextCors(req, res, {
      // Options
      methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
      origin: '*',
      optionsSuccessStatus: 200, // some legacy browsers (IE11, various SmartTVs) choke on 204
   });

   // Rest of the API logic
   res.json({ message: 'Hello NextJs Cors!' });
}
```

**Comment by m-avagyan** [comment]
I configured my next.js middleware to handle accepted origins and return website or route only if origin type is accepted for production mode. For local development I set origin value as * because no need to handle CORS for localhost. You can copy paste this code to your middleware.ts file.

```typescript
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const isProduction = process.env.DATASET === 'production';
const corsOrigins = isProduction
    ? [
          'domain1',
          'domain2',
          'domain3',
          'domain4',
      ]
    : ['*'];

export function middleware(req: NextRequest) {
    const origin = req.headers.get('origin');
    const res = NextResponse.next();

    // Set CORS headers
    res.headers.set('Access-Control-Allow-Credentials', 'true');
    res.headers.set('Access-Control-Allow-Methods', 'GET,DELETE,PATCH,POST,PUT');
    res.headers.set(
        'Access-Control-Allow-Headers',
        'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
    );

    if (corsOrigins.includes('*') || corsOrigins.includes(origin || '')) {
        res.headers.set('Access-Control-Allow-Origin', origin || '*');
    }

    return res;
}

export const config = {
    matcher: '/api/:path*', // Match all API routes
};
```

Please modify the corsOrigins array value (add all your needed domains).
