### ISSUE TITLE
Undefined property error when request fails

### ISSUE THREAD

**Issue by VitorTS** [axios/axios#5647]
### Describe the bug

When a request fails we get an internal error coming from inside axios instead of the real error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'retry-after')
    at eval (index.module.js:1:1134)
    at new Promise (<anonymous>)
    at s (index.module.js:1:1094)
```

### To Reproduce

block "http://www.example.com/":

![image](https://user-images.githubusercontent.com/26394646/231172889-c01e3dad-ca30-4a0c-a84a-90f8cac1c34b.png)

run `axios.get('http://www.example.com/')`

### Expected behavior

An error describing what actually happened, like the one fetch() gives:

```
Uncaught (in promise) TypeError: Failed to fetch
    at eval (bugsnag.js:3265:1)
    at new Promise (<anonymous>)
    at fetch (bugsnag.js:3263:1)
    at <anonymous>:1:1
```

### Axios Version

0.27.2

### Adapter Version

HTTP

### Browser

Chrome

### Browser Version

112.0.5615.49 

### Node.js Version

16.15.1

### OS

OSX 13.0

### Additional Library Versions

```bash
retry-axios: 2.6.0
```

**Comment by bilalakhter** [comment]
kindly assign it to me

**Comment by VitorTS** [comment]
@ssaprank thank you for the answer
