### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by huynhdev24** [axios/axios#5655]
### Describe the issue

caught (in promise) TypeError: Cannot read properties of undefined (reading 'status')
    at fetchData (App.js:77:1)

![image](https://user-images.githubusercontent.com/124909303/232265855-53b134b3-2a8f-46b0-811a-1c7eb834d459.png)

### Example Code

```js
import axios from 'axios'
import jwt_decode from 'jwt-decode'
// const BASE_URL = "http://localhost:5000/api/v1/"
import { toast } from 'react-toastify';

const axiosClient = axios.create({
  baseURL: process.env.REACT_APP_SERVER_URL,
  // baseURL: "http://localhost:5000/api/v1/",
  headers: {
    "Content-Type": "application/json",
  },
  withCredentials: true,
})

const jwtAxios = axios.create({
  baseURL: process.env.REACT_APP_SERVER_URL,
  // baseURL: "http://localhost:5000/api/v1/",
  headers: {
    "Content-Type": "application/json",
  },
  withCredentials: true,
})

axiosClient.interceptors.request.use(async (config) => {
  const accessToken = localStorage.getItem('accessToken');
  if (accessToken) {
    const date = new Date()
    const decodedToken = jwt_decode(accessToken)
    if (decodedToken.exp < date.getTime() / 1000) {
      try {
        const res = await jwtAxios.post(`auth/refresh-token/`);
        const newAccessToken = res.data.token
        if (newAccessToken) {
          localStorage.setItem('accessToken', newAccessToken)
          config.headers.Authorization = `Bearer ${newAccessToken}`;
        }
        
      } catch (error) {
        if (error.response.status === 403 || error.response.status === 401) {
          localStorage.removeItem('accessToken')
        }
      }
    } else {
      config.headers.Authorization = `Bearer ${accessToken}`;
    }
  }
  return config;
});

axiosClient.interceptors.response.use(
  (res) => res.data, 
  (error) => {
  toast.error(error.response.data.message, { autoClose: 2000 })
  return Promise.reject(error)
})

export default axiosClient
```

### Expected behavior

I was not able to call the api from react app through axios.

### Axios Version

1.3.4

### Adapter Version

HTTP

### Browser

Chrome

### Browser Version

42

### Node.js Version

16.19.0

### OS

Windows 10

### Additional Library Versions

```bash
"react": "^18.2.0",
```

**Comment by huynhdev24** [comment]
![image](https://user-images.githubusercontent.com/124909303/232265974-25ecaeec-feb3-402b-8c0f-1378aa34ccaa.png)
![image](https://user-images.githubusercontent.com/124909303/232266014-e5e87b81-5ed5-46fc-bf15-40ed44e587a8.png)

**Comment by bottercode** [comment]
try adding a check for 'error.response' whether it is defined or not before you are trying to access it's property.
trying adding 
if(error.response && (error.response.status === 403 || error.response.status === 401)

**Comment by huynhdev24** [comment]
@bottercode 
Thank you! i solved this problem by clear localStorage and login again.
