### ISSUE TITLE
Trouble testing ES6 axios default export with Jest with nodejs

### ISSUE THREAD

**Issue by RanylFoumbi** [axios/axios#5676]
Hi here 
i'm facing the same Trouble testing ES6 default export with Jest like [ridgekuhn](https://github.com/ridgekuhn) but with nodejs
Please Can you help ?
[SimenB](https://github.com/SimenB)

// test.js file

```
`import axios from 'axios';
import { expect, jest } from '@jest/globals'
import getPhotosByAlbumId from '../index.js'

jest.mock('axios')

describe('test getPhotosByAlbumId', () => {
  it('fetches photos by album id', async () => {
    const ID = 3;
    const expectedConfig = {
      baseURL: 'https://jsonplaceholder.typicode.com/albums',
      method: 'get',
      url: `/${ID}/photos?_limit=3`
    };
    const expectedData = [
      { albumId: ID, id: 1, title: 'accusamus beatae ad facilis cum similique qui sunt' },
      { albumId: ID, id: 2, title: 'reprehenderit est deserunt velit ipsam' },
      { albumId: ID, id: 3, title: 'officia porro iure quia iusto qui ipsa ut modi' }
    ];

    console.info({axios});

    axios.mockResolvedValueOnce({ data: expectedData });

    const photos = await getPhotosByAlbumId(ID);

    expect(axios).toHaveReturned();
    expect(axios).toHaveBeenCalledTimes(1);
    expect(axios).toHaveBeenCalledWith(expectedConfig);
    expect(photos).toEqual(expectedData);
  });
});`
```

// index.js file

```
`import axios from "axios";

const getPhotosByAlbumId = async (id) => {
  const result = await axios({
    baseURL: 'https://jsonplaceholder.typicode.com/albums',
    method: 'get',
    url: `/${id}/photos?_limit=3`
  });
  console.log({ result });
  const { data } = result;
  return data;
};

export default getPhotosByAlbumId;`
```

// package.json file

`{
  "name": "sample-jest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "jest":{
    "testEnvironment":"node",
    "transform":{},
    "testMatch":[
       "<rootDir>/tests/*.test.js"
    ]
 }, 
  "scripts": {
    "test": "NODE_OPTIONS=--experimental-vm-modules npx jest --coverage"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/jest": "^29.5.1",
    "axios": "^1.3.6",
    "jest": "^29.5.0"
  }
}
`
// The error is has follow

 FAIL  tests/sample.test.js
  test getPhotosByAlbumId
    ✕ fetches photos by album id (13 ms)

  ● test getPhotosByAlbumId › fetches photos by album id

    TypeError: axios.mockResolvedValueOnce is not a function

      21 |     console.info({axios});
      22 |
    > 23 |     axios.mockResolvedValueOnce({ data: expectedData });
         |           ^
      24 |
      25 |     const photos = await getPhotosByAlbumId(ID);
      26 |

      at Object.<anonymous> (tests/sample.test.js:23:11)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |      20 |      100 |       0 |      20 |                   
 index.js |      20 |      100 |       0 |      20 | 5-12              
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.209 s
Ran all test suites.

_Originally posted by @RanylFoumbi in https://github.com/axios/axios/issues/4397#issuecomment-1521462449_

**Comment by mrazauskas** [comment]
Take a look through the Module Mocking in ESM section of Jest docs: https://jestjs.io/docs/ecmascript-modules#module-mocking-in-esm

If that does not help, please create a reproduction repo and ping me (;

**Comment by RanylFoumbi** [comment]
@mrazauskas  it is still doesn't work.

**Comment by mrazauskas** [comment]
Could you provide minimal reproduction repo, please. There are too many moving parts.

**Comment by RanylFoumbi** [comment]
> Could you provide minimal reproduction repo, please. There are too many moving parts.

here is the repo https://github.com/RanylFoumbi/sample-jest-es6

**Comment by mrazauskas** [comment]
Looks like it is the same as above code. Please read the [Module Mocking in ESM section](https://jestjs.io/docs/ecmascript-modules#module-mocking-in-esm) carefully.

The point is that in ESM (or with `transform: {}`) there is no hoisting of `jest.mock()` calls. In other words, calling `jest.mock('axios')` after `import axios from 'axios';` has no effect on the imported module, because the module was already evaluated. As you know in ESM all `import` statements are evaluated first, so there would be no effect even if you would reloader lines of your code.

**Comment by RanylFoumbi** [comment]
@mrazauskas  I updated the way to import as recommend in the doc you sent but now  facing the error bellow

![image](https://user-images.githubusercontent.com/43245901/234288740-c39e16c1-e1f1-4480-94f2-2f76ffd68d99.png)

updated repo https://github.com/RanylFoumbi/sample-jest-es6

**Comment by mrazauskas** [comment]
In your test file the `import getPhotosByAlbumId from '../index.js'` points to a module which imports`axios`. In ESM all imports are evaluated first, this applies to the `axios` import in `index.js` files. After module is evaluated, the `jest.mock` call has no effect on it. To make this work: in your test file should import `getPhotosByAlbumId` dynamically after mocking `axios`.

---

Another problem are default exports. You should adjust your mock and imports like this:

```ts
jest.unstable_mockModule("axios", () => ({
  default: jest.fn(),
}));

const { default: axios } = await import("axios");
const { default: getPhotosByAlbumId } = await import("../index.js");
```

**Comment by RanylFoumbi** [comment]
> In your test file the `import getPhotosByAlbumId from '../index.js'` points to a module which imports`axios`. In ESM all imports are evaluated first, this applies to the `axios` import in `index.js` files. After module is evaluated, the `jest.mock` call has no effect on it. To make this work: in your test file should import `getPhotosByAlbumId` dynamically after mocking `axios`.
> 
> Another problem are default exports. You should adjust your mock and imports like this:
> 
> ```ts
> jest.unstable_mockModule("axios", () => ({
>   default: jest.fn(),
> }));
> 
> const { default: axios } = await import("axios");
> const { default: getPhotosByAlbumId } = await import("../index.js");
> ```

Thanks very much i understand well now.
