### ISSUE TITLE
Use case for function bind in bind.js

### ISSUE THREAD

**Issue by Quintis1212** [axios/axios#5690]
### Section/Content To Improve

There is a  function bind in bind.js , can please some one explain me use cases for this function? Why library do not use .bind method from function ?

### Suggested Improvement

It will be nice to have some comment why there is a  function bind in bind.js when in js there is a .bind method for functions

**Comment by Quintis1212** [comment]
`'use strict';

export default function bind(fn, thisArg) {
  return function wrap() {
    return fn.apply(thisArg, arguments);
  };
}`

**Comment by DigitalBrainJS** [comment]
There is no particular sense here. This is a polyfill left over from when Axios was written in ES3. It is scheduled for removal. The only value of using it in modern JS might be slightly better performance, but that's not relevant for this project, which strictly does not require the use of micro-optimizations.

**Comment by Quintis1212** [comment]
@DigitalBrainJS  can you please explain why this function performs better than the .bind method ?

**Comment by DigitalBrainJS** [comment]
This is an old-known fact. You can google a lot of information. It's still relevant.
https://stackoverflow.com/questions/17638305/why-is-bind-slower-than-a-closure
