### ISSUE TITLE
How to find the IP address for a request before sending it.

### ISSUE THREAD

**Issue by zydjohnHotmail** [axios/axios#5695]
### Describe the issue

Hi,
I need some examples on how to get the IP address for the axios request before sending the request.
The following is my code to send an axios request: const axios = require('axios');

const data = {
  jsonrpc: '2.0',
  method: 'eth_blockNumber',
  params: [],
  id: 1,
};

const instance = axios.create({
  baseURL: 'https://public-node.testnet.rsk.co/',
});

instance.post('/', data)
  .then((response) => {
    console.log(`Current block count: ${response.data.result}`);
  })
  .catch((error) => {
    console.error('Error retrieving current block count:', error.message);
  });
  

### Expected behavior

I want to use interceptor to show (console.log) the IP address before axios sending the request, as some times, it is not easy to see which IP address is sent for the axios requests.

### Axios Version

1.4.0

### Adapter Version

Don't know yet

### Browser

Brave

### Browser Version

v1.50.121

### Node.js Version

v18.14.2

### OS

Windows 10 (Version 22H2)

### Additional Library Versions

```bash
None
```

### Additional context/Screenshots

```bash
D:\nodejs\axios>node pure-blockcount.js
Current block count: 0x3a5a06
I want to show the IP for the requested axios.
```

**Comment by yasuf** [comment]
you'll probably need to query a 3rd party server to find out the IP of the client to know if you need to block it- https://stackoverflow.com/questions/391979/how-to-get-clients-ip-address-using-javascript
