### ISSUE TITLE
TS Issue at Interceptors Response

### ISSUE THREAD

**Issue by AdlinMH** [axios/axios#5696]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `axios@1.4.0` for the project I'm working on.

I've got typescript issue that mentioned 
> Type 'Promise<null>' is not assignable to type 'Promise<AxiosResponse<any, any>>'

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/axios/index.d.ts b/node_modules/axios/index.d.ts
index e194461..ec0ebdf 100644
--- a/node_modules/axios/index.d.ts
+++ b/node_modules/axios/index.d.ts
@@ -475,7 +475,7 @@ export class Axios {
   defaults: AxiosDefaults;
   interceptors: {
     request: AxiosInterceptorManager<InternalAxiosRequestConfig>;
-    response: AxiosInterceptorManager<AxiosResponse>;
+    response: AxiosInterceptorManager<AxiosResponse | null>;
   };
   getUri(config?: AxiosRequestConfig): string;
   request<T = any, R = AxiosResponse<T>, D = any>(config: AxiosRequestConfig<D>): Promise<R>;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by yasuf** [comment]
what's the context for making this change? what issue were you running into?

**Comment by AdlinMH** [comment]
I keep running into data types issues in this section.

<img width="336" alt="image" src="https://github.com/axios/axios/assets/19648288/92e86504-ea7f-4f70-b6ce-f0c4d308d964">

I don't understand where I went wrong. therefore I propose this change. Or maybe you can tell me where I went wrong?

**Comment by Cattttttttt** [comment]
You need to return a `Promise<AxiosResponse>` so the next interceptor in the response interceptor chain can take this value, not `null`.

**Comment by AdlinMH** [comment]
thank you for your help :)
