### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by chaudharysayash** [axios/axios#5700]
### Describe the issue

Sometimes APIs get stuck in the loop after the refresh token api is called. For now i have used the error.config._retry flag, apart from that is there any method to do it.

### Example Code

```js
const mainBackendResponseErrorInterceptor = async (error) => {
  const originalRequest = error.config;
  if (error.response.status === 401 && !originalRequest._retry) {
    originalRequest._retry = true;
    const refreshToken = localStorage.getItem('refresh_token');
    if (refreshToken) {
      await refreshAccessToken();
      const accessToken = localStorage.getItem('access_token');
      originalRequest.headers = {
        ...originalRequest.headers,
        Authorization: `Bearer ${accessToken}`
      };
    }
    return mainBackendInstance(originalRequest);
  } else {
    localStorage.clear();
    window.location.reload();
  }
  return Promise.reject(error);
};
```

### Expected behavior

After retrying for 1 time the user is getting logged out. I want the same behavior without using the originaRequest._retry flag.

### Axios Version

latest

### Browser

Chrome

### Node.js Version

14xx

### Additional Library Versions

```bash
16.13.1
```

**Comment by WillianAgostini** [comment]
Hi @chaudharysayash 

You can refresh token without going through the current interceptor using different instances of axios. One instance is for current requests and another instance just for authentication requests, as this way you will be isolating authentication in a different interceptor.

**Comment by chaudharysayash** [comment]
Ok thank you
