### ISSUE TITLE
Does axios support application/octet-stream?

### ISSUE THREAD

**Issue by TannerS** [axios/axios#5702]
Sorry for the short issue details, I'm currently mobile. 

Our code is using request and transferring to axios but I noticed I get unsupported format when trying to make a post call using 

application/octet-stream

Does that mean we are force to switch over to multiparty form or is there a specific way to get octet to work?

**Comment by yasuf** [comment]
it should work, we have tests for that:

https://github.com/axios/axios/blob/81b28ece45d987d7f28eff953f6965b8db2fb0d5/test/unit/adapters/http.js#L1485

let me know if you can provide an example where it isn't working and I can reopen this issue
