### ISSUE TITLE
Axios ^1.4 cannot using custom return type in interceptors.response in Typescript

### ISSUE THREAD

**Issue by chemistwang** [axios/axios#5704]
### Describe the issue

I want to use a custom return value type in typescript,but i got warning
```
 Type 'Result<any>' is missing the following properties from type 'AxiosResponse<any, any>': status, statusText, headers, configts(2345)
```

### Example Code

```js
import axios, {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  InternalAxiosRequestConfig,
  AxiosError
} from "axios";

interface Result<T = any> {
  code: number;
  msg: string;
  data: T;
}

service.interceptors.response.use(
  (response: AxiosResponse<Result>) => {
    return response.data;
  },
  (error: AxiosError) => {
    return Promise.reject(error.response);
  }
);
```

### Expected behavior

i can get code hinting  

```ts
interface Result<T = any> {
  code: number;
  msg: string;
  data: T;
}

service.interceptors.response.use(
  (response: AxiosResponse<Result>) => {
    return response.data; // respones.data.code or response.data.msg or response.data.data
  },
  (error: AxiosError) => {
    return Promise.reject(error.response);
  }
);

```

### Axios Version

1.4

### Browser

Chrome

### Browser Version

Version 112.0.5615.137 (Official Build) (arm64)

### OS

OSX 13.0

### Additional context/Screenshots

```bash
https://codesandbox.io/s/xenodochial-bassi-epuxky?file=/src/index.ts
```

**Comment by yasuf** [comment]
replace your interface with:
```
interface MyCustomData {
  name: string,
  email: string,
}
```

or a type
```
type MyCustomData = {
  name: string;
  email: string;
}

```

and it should work, I tested it and it hints `name` and `email` as expected:
<img width="584" alt="Screenshot 2023-05-10 at 10 30 57 PM" src="https://github.com/axios/axios/assets/7065942/08edd2c2-f8e1-4a54-8c15-5fcb374c0622">

**Comment by chemistwang** [comment]
@yasuf sorry, are you sure the axios version >= 1.0 and did not have a warning as following
` Type 'Result<any>' is missing the following properties from type 'AxiosResponse<any, any>': status, statusText, headers, configts(2345)`

**Comment by zch233** [comment]
the same
