### ISSUE TITLE
Why can't localhost be used for proxy address?

### ISSUE THREAD

**Issue by dstampher** [axios/axios#5706]
### Describe the issue

Using localhost instead of 127.0.0.1 in proxy string results in `Error: connect ECONNREFUSED ::1:8118`

But if I execute `curl -x localhost:8118 https://example.com`, there is no issue.  That tells me this is an axios related issue.

Also note that I am using httpsAgent.  I originally tried setting the proxy property of the config argument, which results in the error `AxiosError: maxContentLength size of -1 exceeded`, but only when I send the request to https://example.com.  It works for http.

### Example Code

```js
let axiosInstance = axios.create({
    httpsAgent: new HttpsProxyAgent("http://localhost:8118"),
  });

  let result = await axiosInstance.get("https://example.com", {
    timeout: 10000,
  });
  console.log(result);
```

**Comment by yasuf** [comment]
you'll need to setup more stuff to run https locally - https://web.dev/how-to-use-local-https/. Probably not an `axios` related but, let me know otherwise
