### ISSUE TITLE
AxiosResponse always be undefined

### ISSUE THREAD

**Issue by Nekofoxmiu** [axios/axios#5709]
### Describe the bug

when I use axios request Twitter's data it always pass nothing to my .then function.
If the request is faied or somthing else, at least it should give me the AxiosResponse that tell me error code or something like that,
but it just return nothing to my .then function, and it didn't go into .catch block.

### Code snippet

```js
await axios("https://twitter.com/", {
                "method": "GET"
            })
                .then((response) => {
                    console.log(response)
                })
                .catch((err) => { console.log(err); });
```

### Expected behavior

it should return AxiosResponse object like

{
  status: 200,
  statusText: 'OK',
  headers: {
.
.
.
.

### Axios Version

0.25.0

### Node.js Version

18.9.0

### OS

Windows 10

**Comment by sandraroz** [comment]
Using axios@1.4.0 I am getting `Maximum number of redirects exceeded`. I think you need to sign up to get access to [twitter's ](https://developer.twitter.com/en/docs/tutorials/step-by-step-guide-to-making-your-first-request-to-the-twitter-api-v2)API.

Here is an example of how I would use the get request.
```
const run = async () => {
    const res =  await axios.get("https://rickandmortyapi.com/api/character/108/").catch(err => {
        console.error('err', err)
    })
    console.log('data', res.data)
}

run()
```

**Comment by Nekofoxmiu** [comment]
Oh...Sorry...I forget to check the axios version manually, I just run npm update...

**Comment by Nekofoxmiu** [comment]
Oh..weird ,I test in 1.4.0 still show me undefined

**Comment by pavankpdev** [comment]
@Nekofoxmiu I think the request you're making is invalid, twitter must be blocking your request. Try with other public endpoint or maybe twitter API. 

I tried to reproduce with facebook and google it works fine. 

```javascript
axios("https://facebook.com/", {
        "method": "GET"
    })
    .then((response) => {
        console.log(response)
    })
    .catch((err) => {
        console.log(err);
    });
```

![image](https://github.com/axios/axios/assets/52795191/b09519e5-54d7-45d8-993f-3bd1c96fa9df)

**Comment by Nekofoxmiu** [comment]
I know but I think at lease axios should return the 301 redirect or 403 Forbidden or something like that? 

My problem is axios return nothing for me, the .then function response is undefined.

**Comment by pavankpdev** [comment]
@Nekofoxmiu Axios does return this error from the `catch` 
![image](https://github.com/axios/axios/assets/52795191/fc52c3b8-79a5-40a2-8aa2-d933e30f44a7)

**Comment by DigitalBrainJS** [comment]
That's because Axios for node doesn't store cookies. Twitter redirects to the same page (root) if some cookie[s] is not. You can disable cookies in the same issue `Postman and see Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://twitter.com/`

https://codesandbox.io/p/sandbox/lucid-flower-5z03r0?file=%2Findex.js%3A7%2C1

**Comment by Nekofoxmiu** [comment]
Yes, I knew that. 
I already know that the request failure is because the request lack guest_id in header which is in set_cookie. 
But the propose I sent this issue is because the weird react of axios for this redirected problem.

If my pronounce cause the misunderstanding .
I am very sorry.

**Comment by Nekofoxmiu** [comment]
What....? OK .....IDK when I try to take a screenshot and post why I am confused it turn norma.
I am apologized for wasting you guys time on this problem.
