### ISSUE TITLE
Axios 204 not being received in response in React

### ISSUE THREAD

**Issue by billnbell** [axios/axios#5710]
### Describe the bug

We are not getting response status of 204. It just hangs.

### To Reproduce

Call axios and return a 204.

### Code snippet

```js
None yet.
```

### Expected behavior

Return status = 204

**Comment by LokeshKumar-Dev** [comment]
Bro...
It works fine for me. I can get clear response details like
`config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
data
: 
""
headers
: 
AxiosHeaders {content-length: '21', content-type: 'text/html; charset=utf-8'}
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
status
: 
204
statusText
: 
"No Content"`
Obviously it won't return your value bcoz of its nature as NO CONTENT

if this is not what you expect. Explain problem more clearly...
