### ISSUE TITLE
How can I completely remove the User-Agent from a request in NodeJS?

### ISSUE THREAD

**Issue by philhk** [axios/axios#5713]
### Describe the issue

I need to remove the User-Agent from a request in Node.js, but despite searching extensively, I have been unable to find a solution.

### Example Code

```js
const axiosInstance = axios.create({ ...axios.defaults })

delete axios.headers.common['User-Agent']
```

### Expected behavior

The User-Agent should be deleted, and it should no longer appear in any requests.

### Axios Version

1.4.0

### Node.js Version

18.12.1

### OS

Windows 11 x64

**Comment by DigitalBrainJS** [comment]
Just set the header to `false` (https://codesandbox.io/p/sandbox/kind-rubin-ry0jex?file=%2Findex.js%3A6%2C1-10%2C4).
```js
const { data } = await axios.get("http://httpbin.org/get", {
  headers: {
    "User-Agent": false,
  },
});
```
OR
```js
axios.defaults.headers.common["User-Agent"] = false;
```
All headers are handled by the AxiosHeaders class and in the context of AxiosHeaders:
- `null` value means do not include the header
- `false` means don't include the header and don't allow it to be set in upper chains (unless the `rewrite` option is explicitly set for the `headers.set` method)
```js
AxiosHeaders.concat({ x: 1, y: false }, { y: 123 }).toJSON();  // { x: '1' }

AxiosHeaders.concat({ x: 1, y: null }, { y: 123 }).toJSON();  // { x: '1', y: '123' }
```

**Comment by philhk** [comment]
I didn't expect it to be that easy. Thank you for resolving my issue!
