### ISSUE TITLE
The response converts large values to scientific notation when parsing number even as a string

### ISSUE THREAD

**Issue by LokeshKumar-Dev** [axios/axios#5721]
### Describe the bug

The data we sends to the axios as string through BODY gets parsed and returns wrong implemented value
The report #5719 state is correct but i tried solving it then get to know the file is already been updated and tried again, still gets the wrong value as `646686880670135092987843 to 6.466868806701352e+23`.
and i got to know that the error is occurring on `lib\adapters\http.js` while transferring at `res.on("data", function handleStreamData(chunk) {}` the chunk is itself changing the value

The Chunk:
In Hexadecimal
`7b 22 75 72 6c 22 3a 22 2f 61 70 69 22 2c 22 64 61 74 61 22 3a 36 2e 34 36 36 38 36 38 38 30 36 37 30 31 33 35 32 65 2b 32 33 2c 22 6d 65 74 68 6f 64 22 3a 22 50 4f 53 54 22 2c 22 68 65 61 64 65 72 73 22 3a 7b 22 61 63 63 65 70 74 22 3a 22 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 2c 20 74 65 78 74 2f 70 6c 61 69 6e 2c 20 2a 2f 2a 22 2c 22 63 6f 6e 74 65 6e 74 2d 74 79 70 65 22 3a 22 61 70 70 6c 69 63 61 74 69 6f 6e 2f 78 2d 77 77 77 2d 66 6f 72 6d 2d 75 72 6c 65 6e 63 6f 64 65 64 22 2c 22 75 73 65 72 2d 61 67 65 6e 74 22 3a 22 61 78 69 6f 73 2f 31 2e 34 2e 30 22 2c 22 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 22 3a 22 32 34 22 2c 22 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 22 3a 22 67 7a 69 70 2c 20 63 6f 6d 70 72 65 73 73 2c 20 64 65 66 6c 61 74 65 2c 20 62 72 22 2c 22 68 6f 73 74 22 3a 22 31 32 37 2e 30 2e 30 2e 31 3a 33 30 30 30 22 2c 22 63 6f 6e 6e 65 63 74 69 6f 6e 22 3a 22 6b 65 65 70 2d 61 6c 69 76 65 22 7d 7d`
In utf8
`{"url":"/api",
"data":6.466868806701352e+23,
"method":"POST","headers":{"accept":"application/json, text/plain, */*","content-type":"application/x-www-form-urlencoded","user-agent":"axios/1.4.0","content-length":"24","accept-encoding":"gzip, compress, deflate, br","host":"127.0.0.1:3000","connection":"keep-alive"}}`

It is normal to change Long numeric value in JSON.parse but it changes even as string...

### To Reproduce

In `.\sandbox\client.js` set var to:
`const URL = "http://127.0.0.1:3000/api";`
`const BODY = "646686880670135092987843";`

### Expected behavior

**Should have Returned =>** 
```
> {
  >   url: '/api',
  >   data: 646686880670135092987843,
  >   method: 'POST',
  >   headers: {
  >     accept: 'application/json, text/plain, */*',
  >     'content-type': 'application/x-www-form-urlencoded',
  >     'user-agent': 'axios/1.4.0',
  >     'content-length': '24',
  >     'accept-encoding': 'gzip, compress, deflate, br',
  >     host: '127.0.0.1:3000',
  >     connection: 'keep-alive'
  >   }
> }
```

### Axios Version

1.4.0

### Adapter Version

XHR/HTTP

**Comment by LokeshKumar-Dev** [comment]
@jasonsaayman Sire, please take a look at this...

**Comment by DigitalBrainJS** [comment]
https://github.com/axios/axios/issues/4846#issuecomment-1183174065
