### ISSUE TITLE
Support NextJS  `next` options

### ISSUE THREAD

**Issue by SanderCokart** [axios/axios#5730]
### Is your feature request related to a problem? Please describe.

Currently in NextJS we need to use fetch to revalidate and cache at the fetch level. I wish to use axios obviously.

https://nextjs.org/docs/app/api-reference/functions/fetch#fetchurl-options

As the docs mention there is `cache: no-store | force-cache`
As well as `next: { revalidate: false | 0 | number } }`

### Describe the solution you'd like

Find a way to make Axios work nicely with NextJS App Router architecture.

### Describe alternatives you've considered

Wrapping in react Cache function which only dedupes requests, revalidate must with axios be defined at route segment level.

**Comment by Aditay2002** [comment]
@SanderCokart can you please elaborate the issue?

**Comment by brunorguerra** [comment]
up

**Comment by SanderCokart** [comment]
NextJS is moving away from using next key on the config of fetch so this might no longer be required. Hover axios allowing us to pass config options to the underlying fetch function would be a cool addition.

**Comment by aprilmintacpineda** [comment]
2026 and we're still using `next` options in fetch when in nextjs env...
