### ISSUE TITLE
Cannot enable JS

### ISSUE THREAD

**Issue by KaizOffical** [axios/axios#5739]
### Describe the bug

I want to fetch a link that need to enable JS to use, but I already tried few ways but it's still not working. (tried with `puppeteer`)

here is my code
```js
// url, auth are valid variables
axios.request({
    method: 'get',
    maxBodyLength: Infinity,
    url: url,
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0',
      'x-auth-token': auth,
      'Accept': '*/*',
      'Accept-Encoding': 'gzip, deflate, br',
      'Connection': 'keep-alive'
    }
  })
    .then((response) => {
      console.log(JSON.stringify(response.data));
    })
    .catch((error) => {
      console.log(error);
    });
```
the reason why I've been blocked by the link `This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.`
In Postman, it was working fine and give the correct data. But when I exported the code and ran in JS, this happened.

### Axios Version

1.4.0

### Browser

Chrome

### Node.js Version

16.8.0

### OS

Windows 10

### Additional Library Versions

```bash
discord.js 13.2.0,
glob 7.1.7,
mongoose 6.0.2,
puppeteer 20.6.0
```

**Comment by DigitalBrainJS** [comment]
The site probably checks for the `X-Requested-With` and/or `user-agent` headers that browsers add to Ajax requests, so there's nothing Axios can do about it.
