### ISSUE TITLE
Axios not sending cookies in node

### ISSUE THREAD

**Issue by tamias** [axios/axios#5742]
### Describe the bug

Axios is not sending cookies in node, even though I am using `withCredentials: true` on both the initial request to set the cookie and the subsequent request that should send the cookie back to the server.

### To Reproduce

https://codesandbox.io/p/sandbox/compassionate-bash-dtvp3s?file=%2Findex.js%3A15%2C34
(https://httpbin.org seems to be somewhat unstable - if you get a gateway error, try running the snippet again.)

Output:

```
[ 'a=1; Path=/' ]
GET /cookies HTTP/1.1
Accept: application/json, text/plain, */*
User-Agent: axios/1.4.0
Accept-Encoding: gzip, compress, deflate, br
Host: httpbin.org
Connection: close
```

### Code snippet

```js
import axios from 'axios';

const url = 'https://httpbin.org/cookies/set?a=1';

let response = await axios.get(url, {
  maxRedirects: 0,
  validateStatus: function (status) {
    return status >= 200 && status <= 303;
  },
  withCredentials: true,
});

console.log(response.headers['set-cookie']);

response = await axios.get(url, {
  withCredentials: true,
});

console.log(response.request._header);
```

### Expected behavior

The headers of the second request should include the cookies set by the first request.

### Axios Version

1.4.0

### Node.js Version

v18.16.0

### OS

OSX 13.4

**Comment by DigitalBrainJS** [comment]
Currently, Axios does not have its own cookie jar for Node.js environment, you need to use some third-party library to add support for it.

**Comment by gensart-ai** [comment]
Hope Axios will have own cookie jar support for Node.js

**Comment by FaisalFasi** [comment]
Hi Man,

Thank you for explaining this in detail. Could you please tell me how i can send cookie from FE to BE using axios?

I am using react for FE and express for BE. 
Here is my express server :
------------------------------
import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import setupSocket from "./lib/socket.js";
import http from "http";
import dotenv from "dotenv";

// Load environment variables from .env file
dotenv.config();

// Routes import here
import postRoute from "./routes/post.route.js";
import authRoute from "./routes/auth.route.js";
import testRoute from "./routes/test.route.js";
import userRoute from "./routes/user.route.js";
import chatRoute from "./routes/chat.route.js";
import messageRoute from "./routes/message.route.js";

const app = express();
app.set("trust proxy", 1);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const cookieParserSecret = process.env.JWT_SECRET_KEY; // Secret key for signing cookies
app.use(cookieParser(cookieParserSecret));

app.use(
  cors({
    origin: process.env.CLIENT_URL || "http://localhost:5173", // Replace with your client domain
    // methods: ["GET", "POST", "PUT", "DELETE"], // Uncomment to restrict HTTP methods
    credentials: true, // Allow credentials (cookies)
  })
);

app.use("/api/auth", authRoute);
app.use("/api/users", userRoute);
app.use("/api/posts", postRoute);
app.use("/api/test", testRoute);
app.use("/api/chats", chatRoute);
app.use("/api/messages", messageRoute);

const server = http.createServer(app); // Create HTTP server using Express app
const io = setupSocket(server); // Setup socket.io

const PORT = process.env.PORT || 8800;
server.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});

--------  express server ends here -------------

here is my code for setting the Cookie in the BE:

  res
      .cookie("token", token, {
        withCredentials: true,
        httpOnly: true,
        sameSite: "none",
        secure: process.env.NODE_ENV === "production", // Set secure only in production
        maxAge: age,
        path: "/",
        domain: process.env.CLIENT_URL || "http://localhost:5173",
      })
      .status(200)
      .json(userInfo);

--------  Cookie code ends here -------------


Here is my FE axios code :

import axios from "axios";

const apiRequest = axios.create({
  baseURL: process.env.VITE_API_BASE_URL,
  withCredentials: true,
});
 
export default apiRequest;
--------  axios baseURL ends here -------------

here is how i making request 
 try {
      const response = await apiRequest.post("/auth/login", {
        username,
         password,
      });

      updateUser(response.data);
      navigate("/");

    } catch (err) {
      console.log(err.response.data.message);
      setError(err.response.data.message);
    } finally {
      setLoading(false);
    }
--------  FE making post request ends here -------------

here is how i am trying to verify my token:
import jwt from "jsonwebtoken";

export const verifyToken = (req, res, next) => {
  const token = req.cookies.token;
  console.log("Token on backend: ", token);

  if (!token) {
    return res.status(401).json({
      message: "You are not authorized!",
    });
  }
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET_KEY);

    req.userId = decoded.id; // Extract user ID from decoded token

    next(); // Proceed to the next middleware
  } catch (error) {
    console.log(error);

    return res.status(403).json({
      message: "Token is not valid!",
    });
  }
};
--------  verify token ends here -------------



On localhost everything works fine but when i deploy my BE set the cookie but FE doesn't send the coockie to the BE.

i struggled alot and already tried many ways and spend many days on it. but nothing fixed my problem.  

Please help me.
i will really be thankful for any lead or help.
