### ISSUE TITLE
Axios error code introduction

### ISSUE THREAD

**Issue by ChikyChan** [axios/axios#5760]
### Section/Content To Improve

https://github.com/axios/axios/blob/v1.x/README.md#handling-errors

### Suggested Improvement

I notice you have refactored the AxiosError type and add some error code declaration, but I cannot find any documents to introduce these error codes. Is it possible to add some content to introduce the error code?

### Relevant File(s)

```bash
README.md
```

**Comment by JBudiman00** [comment]
Hey I'm a first time contributor and would like to work on this issue. Is there a maintainer that would be willing to review/accept my PR?

Just to be clear @ChikyChan, are you asking for documentation on the structure of the different errors axios can return?
