### ISSUE TITLE
Origin missing from Headers on GET request

### ISSUE THREAD

**Issue by balabll** [axios/axios#5761]
### Describe the bug

I launched a cross-domain request, but when I tried to modify the headers, **Origin Header** was missing.

```javascript
// Origin in the request header

axios.request({ url: "https://baidu.com/api/aaa" });

// No origin in the request header

axios.request({
      url: "https://baidu.com/api/bbb",
      headers: { "Custom-Key": "value" }
    });
   ```

### To Reproduce

https://codesandbox.io/s/hardcore-glitter-3kz8g6?file=/src/App.js:142-347

### Axios Version

1.4

### Browser

chrome

### Browser Version

114.0.5735.198

### Node.js Version

v16.19.1

### OS

mac os 13.3 (22E252)

**Comment by AshwinKumar-V** [comment]
Hey @balabll , I forked your CodeSandbox at [codesandbox.io/s/youthful-mclaren-jn6sl3](https://codesandbox.io/s/youthful-mclaren-jn6sl3?file=/src/App.js) and noticed that I was getting a Network Error at `https://baidu.com/api/` so I replaced it with `https://jsonplaceholder.typicode.com/todos/` and it seems to be working fine with Origin in the Request Headers for both axios GET requests.

**Browser**
Chrome v114.0.5735.199

---
## CodeSandbox editor
![image](https://github.com/axios/axios/assets/77188815/95fef097-22da-411d-b3f4-a886e4069ff1)

---
## Request Headers of 1st URL
![image](https://github.com/axios/axios/assets/77188815/4e13ad17-a724-43eb-8bc9-49c24d9af3ab)

---
## Request Headers of 2nd URL
![image](https://github.com/axios/axios/assets/77188815/e8e1a6d2-ad9b-4ddc-8460-2bfd464b2c24)

**Comment by balabll** [comment]
> 

Yes, I noticed that the problem is not related to axios, thank you very much.

**Comment by balabll** [comment]
> Hey @balabll , I forked your CodeSandbox at [codesandbox.io/s/youthful-mclaren-jn6sl3](https://codesandbox.io/s/youthful-mclaren-jn6sl3?file=/src/App.js) and noticed that I was getting a Network Error at `https://baidu.com/api/` so I replaced it with `https://jsonplaceholder.typicode.com/todos/` and it seems to be working fine with Origin in the Request Headers for both axios GET requests.
> 
> **Browser** Chrome v114.0.5735.199
> 
> ## CodeSandbox editor
> ![image](https://user-images.githubusercontent.com/77188815/251263165-95fef097-22da-411d-b3f4-a886e4069ff1.png)
> 
> ## Request Headers of 1st URL
> ![image](https://user-images.githubusercontent.com/77188815/251264505-4e13ad17-a724-43eb-8bc9-49c24d9af3ab.png)
> 
> ## Request Headers of 2nd URL
> ![image](https://user-images.githubusercontent.com/77188815/251264425-e8e1a6d2-ad9b-4ddc-8460-2bfd464b2c24.png)

Yes, I noticed that the problem is not related to axios, thank you very much.

**Comment by balabll** [comment]
@AshwinKumar-V Yes, I noticed that the problem is not related to axios, thank you very much.

**Comment by geedsen** [comment]
What was the cause of the problem? We are seeing the same.  The same code in three different environments. But one environment is not sending the origin in the request header.

**Comment by KaranLala** [comment]
@geedsen did you figure out why that was happening? Same thing is happening to me. Axios includes a origin header in development but not in production.
