### ISSUE TITLE
Axios Converting Headers to camelCase

### ISSUE THREAD

**Issue by ishancars24** [axios/axios#5773]
### Describe the bug

For below code I am setting csrf header as "X-CSRFToken" but on api call it is converted to "X-csrftoken".
**Apache Superset Service** does not support key "X-csrftoken".

### Code snippet

```js
axios({
      method: "POST",
      url,
      data: payload,
      headers: {
        "X-CSRFToken": <csrf_token>,
      },
    })
```

### Axios Version

0.24.0

### Browser

Chrome

### Node.js Version

16.15.0

**Comment by philBrown** [comment]
Header keys are case insensitive anyway. Why would this matter?

**Comment by DigitalBrainJS** [comment]
As mentioned above, headers are case insensitive, although Axios preserves the original case of headers for readability, so seems it's not an Axios issue in any case.

```js
  axios.post("http://localhost:8000/", "foo", {
    headers: {
      "X-CSRFToken": "abc"
    }
  })
```

```bash
1.4.0
Listening on port 8000
rawHeaders [
  'Accept',
  'application/json, text/plain, */*',
  'Content-Type',
  'application/x-www-form-urlencoded',
  'X-CSRFToken', // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  'abc',
  'User-Agent',
  'axios/1.4.0',
  'Content-Length',
  '3',
  'Accept-Encoding',
  'gzip, compress, deflate, br',
  'Host',
  'localhost:8000',
  'Connection',
  'close'
]
```
