### ISSUE TITLE
http could not be found within the project or in these directories

### ISSUE THREAD

**Issue by aliza-khu** [axios/axios#5775]
### Describe the bug

When the app is going to start and the metro is in progress getting the error "http could not be found within the project or in these directories".

### Expected behavior

The error should be trigger.

### Axios Version

1.4.0

### Node.js Version

19.3.0

### OS

iOS 16.5

### Additional Library Versions

```bash
React 18.2.0,
React Native 0.72.0
```

**Comment by DavidJDallas** [comment]
This error doesn't seem to be related to Axios, or at least not an issue with Axios.
