### ISSUE TITLE
Format TypeScript code

### ISSUE THREAD

**Issue by ChetSerenade** [axios/axios#5777]
### Section/Content To Improve

There seems to be a missing space at the beginning, which makes it look a bit uncomfortable to read.
![image](https://github.com/axios/axios/assets/44160015/af9d550d-ccda-40ab-b14a-3aba4d7a1917)

### Suggested Improvement

Add space

### Relevant File(s)

```bash
https://github.com/ChetSerenade/axios/blob/v0.21.1/index.d.ts
```

**Comment by LiuZhenyan-Wuzhong** [comment]
Great.
