### ISSUE TITLE
The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType

### ISSUE THREAD

**Issue by xxxKOTxxx** [axios/axios#5787]
### Describe the bug

It already described in https://github.com/axios/axios/issues/1474

If You just close issue it does not mean it is fixed...

**Comment by jasonsaayman** [comment]
will still be closing this, we dont support fetch and therefore don't support this type as you should be able to check https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType stream is not a type XMLHttp supports. we are working on fetch adapter and when that lands we will be supporting this
