### ISSUE TITLE
Axios Error  Unhandled promise rejection: [AxiosError: Request failed with status code 403]

### ISSUE THREAD

**Issue by D3ltaa** [axios/axios#5800]
### Describe the issue

In my pc when im trying to scrap infos about website work perfect but when i try to fetch from my host it return me 
 Unhandled promise rejection: [AxiosError: Request failed with status code 403]

### Example Code

```js
(async () => {
    const response = await axios.get("https://unboxholics.com/news")
   const html =await response.data;
   console.log(html )


    
})();
```

**Comment by NextThread** [comment]
can I work on this?

**Comment by DavidJDallas** [comment]
Closing as this isn't an issue with Axios but is an issue with your request to the API - a 403 indicates that you are unauthorized to access this.
