### ISSUE TITLE
Axios GET with query params - Property 'string' is missing in type '{ params: { name: any; }; }' but required in type 'AxiosRequestConfig<any>'

### ISSUE THREAD

**Issue by JJustas** [axios/axios#5802]
### Describe the bug

GET with query params:
`
await axios.get('/test', {params: {name: 'name123'}})`

 throws

```

Argument of type '{ params: { name: string; }; }' is not assignable to parameter of type 'AxiosRequestConfig<any>'.
  Property 'string' is missing in type '{ params: { name: string; }; }' but required in type 'AxiosRequestConfig<any>'
```

If I change to `await axios.get('/test', {string: '', params: {name: 'name123'}})`, it compiles successfully.

The issue exists with `"axios": "^1.4.0"` but works fine with `"axios": "1.3.0"`

### To Reproduce

`await axios.get('/test', {params: {name: 'name123'}})`

### Expected behavior

`await axios.get('/test', {params: {name: 'name123'}})`

### Axios Version

`"axios": "^1.4.0"`

**Comment by gillisd** [comment]
I was getting this error and fixed it by upgrading typescript

**Comment by JJustas** [comment]
> I was getting this error and fixed it by upgrading typescript

Compiled successfully after upgrading typescript to:
"typescript": "^5.1.6"

I was getting error with:
"axios": "^1.4.0",
"typescript": "^3.2.1"

**Comment by SkyzerDev** [comment]
> > I was getting this error and fixed it by upgrading typescript
> 
> Compiled successfully after upgrading typescript to: "typescript": "^5.1.6"

Could you close the issue if it is fixed?
