### ISSUE TITLE
Support stream response with POST

### ISSUE THREAD

**Issue by lukelu520** [axios/axios#5806]
Dear axios expert,

axios.post doesn't work with stream response, e.g. gpt stream. 
This is a well-known issue since 2016 as in #479 

### Describe the solution you'd like

make axios works with stream response.

Maybe I am missing something; hope to hear your expertise.

### Describe alternatives you've considered

fetch can do it.

**Comment by yangxu52** [comment]
The following content has been translated：
1.Axios is based on XHR and packaged as Promise.
2.Axios and Fetch APIs cannot be compared. Fetch is API from Web Woker API.
3.XHR not support stream response, and it stopped updating early on.
So.use anthoer request library which based on Fetch API, or use Fetch directly.

**Comment by jasonsaayman** [comment]
we are working on a fetch adaptor for now I will close this but stay tuned

**Comment by uzaymacar** [comment]
Hi @jasonsaayman, thanks for the information. As emphasized in several different issues `streaming` is a must-have feature for many applications nowadays; is there an ETA on this feature? i.e., are we talking about months or years? Thanks in advance.

**Comment by git-syl** [comment]
My SSE solution is :
https://stackoverflow.com/questions/76334679/how-get-response-in-axios-when-api-is-steam-like-sse-server-send-events

```
 onDownloadProgress: progressEvent => {
     const xhr = progressEvent.event.target
     const { responseText } = xhr
     console.log("=====responseText======")
     console.log(responseText)
  }
})
```

**Comment by heyalexchoi** [comment]
using fetch adapter worked for me:

```
const response = await api.post('/abc', input, {
    responseType: 'stream',
    adapter: 'fetch',
  });

  const reader = response.data.getReader();
  const decoder = new TextDecoder();

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    const chunk = decoder.decode(value, { stream: true });
    const lines = chunk.split('\n').filter(Boolean);

    for (const line of lines) {
      try {
        const update = JSON.parse(line);
        updateHandler(update);
      } catch (error) {
        console.error('Error parsing update:', error);
      }
    }
  }
 ```

**Comment by m4xleb** [comment]
@heyalexchoi 

> using fetch adapter worked for me:

I get this error from axios when trying to use adapter. `Unknown adapter 'fetch'`
How did you get to make it work?

**Comment by iambasantarai** [comment]
@m4xleb Thanks.
Updating axios to version `1.7.5` worked for me.

**Comment by ghost** [comment]
```
const response = await fetch(`${API_URL}/hello`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': api.defaults.headers.common['Authorization'],
      'Accept': 'text/event-stream',
    },
    body: JSON.stringify(input)
  });

  if (!response.ok) {
    const errorBody = await response.json();
    throw new Error(`generateImage HTTP error! status: ${response.status} ${response.statusText}. Details: ${JSON.stringify(errorBody)}`);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
// everything else the same
```
How do we close the stream if using fetch? Currently I'm using AbortController but I don't think it's the best practice. Also every time the steam closes, an error will appear on the console log, which is not very nice.

**Comment by andyjmorgan** [comment]
export const PostStream = async (
    request: SomeRequest,
    onMessage: (data: any) => void
): Promise<void> => {
    try {
        const abortController = new AbortController()

        const response = await fetch('/v2/someurl', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                Accept: 'text/event-stream',
            },
            body: JSON.stringify(request),
            signal: abortController.signal,
        })

        if (!response.ok) {
            const errorData = await response.json().catch(() => null)
            throw new Error(errorData?.result || `Server responded with status: ${response.status}`)
        }

        await processEventStream(response, onMessage)
    } catch (e) {
        console.error('execution error:', e)
    }
}


This works without error for me @spartan-linhtran
