### ISSUE TITLE
onUploadProgress estimated time value is undefined 

### ISSUE THREAD

**Issue by web-shoharab-pk** [axios/axios#5820]
### Describe the bug

![image](https://github.com/axios/axios/assets/76746357/1d023017-f027-4ca7-a885-15241284c20d)
When I use the onUploadProgress function for the progress feature, I always see the estimated value is undefined. How can I get an estimated value? 

### Code snippet

```js
const uploadedFile = await axios.post(`${BASE_URL}/file-upload/${user?._id}/job-message/${jobData?._id}`, modifiedFile, {
      onUploadProgress: (event) => {
        console.log('onUploadProgress', event);
      },
      headers: {
        Accept: "application/json",
        Authorization: `Bearer ${accessToken}`
      }
    })
```

### Axios Version

1.4.0

### Browser

chrome

**Comment by DigitalBrainJS** [comment]
Just try uploading more data. This metric is not available in the first seconds of the process, as it passes through a filter to get a more accurate value, without erroneous peaks at the start. You can find some guides on Youtube from our users who use this feature there like [this one](https://youtu.be/MxB_3Xfj8Cg?t=1096).

**Comment by web-shoharab-pk** [comment]
thanks @DigitalBrainJS
