### ISSUE TITLE
Cookies not sent with withCredentials when data is present

### ISSUE THREAD

**Issue by jiheon788** [axios/axios#5824]
### Describe the bug

When using axios version 1.4.0 or 1.2.4, I've noticed that if there's a server-side authentication logic and data is present in the request body, cookies (specifically token values) are not included in the headers. However, when the data from the request is removed, cookies are sent correctly. Additionally, if the server does not require authentication, the cookies are always sent correctly regardless of the presence of data.

### To Reproduce

1. Set up a server that requires token-based authentication.
2. Send a POST request using Axios with withCredentials set to true and data in the request body.
3. Observe that cookies (tokens) are not sent in the headers.
4. Remove data from the request.
5. Send the request again and observe that cookies are now sent in the headers.

### Code snippet

```js
// Axios code that does not send cookies with data

const apiClient = axios.create({
  baseURL: host,
});

export const postRegister = ({
  type,
  copyrightTitle,
  prompt,
}) => {
  return apiClient({
    method: 'post',
    url: REGISTER_COPYRIGHT_URL,
    withCredentials: true,
    data: {
      type,
      copyrightTitle,
      prompt,
    },
  });
};

```

### Expected behavior

Cookies should be sent in the headers when withCredentials is set to true, regardless of the presence of data in the request.

### Axios Version

1.4.0, 1.2.4

### Browser

Chrome, edge, safari

### OS

Windows 10, Intel Mac OS X 10_15_7

### Additional Library Versions

```bash
"react": "^18.2.0"
```

**Comment by prechy123** [comment]
currently facing the same issue
back-end:
`app.use(cookieParser());
app.use(
  cors({
    origin: "http://localhost:3000",
    credentials: true,
  })  
);`

front-end:
`const token = jwt.sign(
          { userId: existingUser._id },
          process.env.MY_SECRET
        );
        res.cookie("jwt", token, {
          maxAge: 60000,
          httpOnly: true,
          secure: false,
          sameSite: "None",
        });`
        
token showing in response header but not showing in cookie storage

**Comment by prechy123** [comment]
> currently facing the same issue back-end: `app.use(cookieParser()); app.use( cors({ origin: "http://localhost:3000", credentials: true, }) );`
> 
> front-end: `const token = jwt.sign( { userId: existingUser._id }, process.env.MY_SECRET ); res.cookie("jwt", token, { maxAge: 60000, httpOnly: true, secure: false, sameSite: "None", });`
> 
> token showing in response header but not showing in cookie storage

do i just go back to previous version

**Comment by zeyios** [comment]
Sending Post with data, will need [Preflighted requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests),  do you have set `Access-Control-Allow-Credentials=true` in your server? 

or Are there some errors in Console?

**Comment by prechy123** [comment]
Yes, there are no errors in console, in header I can see Set-Cookie but in
cookie tab, token not adding

**Comment by DavidJDallas** [comment]
https://github.com/axios/axios/issues/5742#issuecomment-1694393815
Hi, I think this is responded to here. Let me know if this doesn't satisfactorily answer.

**Comment by jasonsaayman** [comment]
@jiheon788 is this in the browser or in node?

**Comment by jiheon788** [comment]
> Sending Post with data, will need [Preflighted requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests), do you have set `Access-Control-Allow-Credentials=true` in your server?

My problem was that there was a problem with the server side pre-lit requests setting. Thank you for your help
@zeyios @DavidJDallas @jasonsaayman

**Comment by async-avi** [comment]
> Sending Post with data, will need [Preflighted requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests), do you have set `Access-Control-Allow-Credentials=true` in your server?
> 
> or Are there some errors in Console?

I have enabled `Access-Control-Allow-Credentials` to `true` in the server config (next js), still axios is not sending cookies back to the server. 
> Implementing on browser

**Comment by sidyr6002** [comment]
What is the solution to this? I have enabled withCredentials to true in my NestJs backend and still axios fails to send coockies to backend.
