### ISSUE TITLE
The backend returns the ID value of the object as Axios+1

### ISSUE THREAD

**Issue by sclswin** [axios/axios#5833]
### Describe the bug

BackEnd returns JSON
`
{"id":11555675054411779,"table_id":1,"file_hash":"bf02a5b1d6b23ab58c9ac7c07017f8ab02658bb1","enable":1,"public":1,"deleted":0}
`
The result obtained by using Fiddler to capture packets is consistent with the backend return。
![1](https://github.com/axios/axios/assets/13265574/f88075a4-ab48-4f5f-8447-23a3612c9c8a)

The result obtained in the Axios Response body is the value of ID+1
![11](https://github.com/axios/axios/assets/13265574/ce79193d-4c20-4079-9593-d4eec2e60b86)

### Code snippet

```js
_axiosInstance.interceptors.response.use((res: AxiosResponse)=>{
    clearTimeout(timeoutLoading);
    const { status, data, config } = res
    const { reqParams = {} } = config as AxiosRequestConfigExt
    const { isGoForceUrl = false } = reqParams
    //console.log('interceptors',res)
    if(status == 200){
        console.log(data)
        if(data){
            if(data.status==4003){
                
                return
            }else if(data.status>=400){
                return Promise.reject(data)
            }
        }
        return data;
    }else{
        return Promise.reject(data)
    }
},( error )=>{
    clearTimeout(timeoutLoading);
    let { message = 'Request Error', response } = error
    console.log("Request.ts",response,message)
    return Promise.reject(response)
})
```

### Axios Version

1.4.0

### Adapter Version

HTTP

### Browser

EDG

### Browser Version

116.0.1938.54

### Node.js Version

18

### OS

windows11  windows10

**Comment by DigitalBrainJS** [comment]
The value is too big for a number in JS and `BigInt` is not supported by `JSON.parse` method. Your backend should send it as a string. https://stackoverflow.com/a/10631531/11046238
