### ISSUE TITLE
Typo in multipart bodies page of the documentation

### ISSUE THREAD

**Issue by zakreed** [axios/axios#5847]
### Section/Content To Improve

On the documentation page for Multipart Bodies (https://axios-http.com/docs/multipart) there is a line that reads:

"HTML form can be passes directly as a request payload"

![image](https://github.com/axios/axios/assets/93351349/b2576fa3-1b55-4ec1-8ce4-959eff11bbd6)

### Suggested Improvement

I believe that this should be `passed` instead of `passes`.

So the text should read:

"HTML form can be passed directly as a request payload"

**Comment by akshayantony55** [comment]
I did not find this documentation as part of the codebase, so I'm not able to edit the contents!

**Comment by Shubham185y** [comment]
It was not in this repository & i fixed it here is the link :- https://github.com/axios/axios-docs/pull/134

**Comment by sana-developer** [comment]
I want to work on this issue

**Comment by Samihan15** [comment]
want to work on this issue  !

**Comment by spyv22072000** [comment]
i want to work in this issues !

**Comment by harshith666** [comment]
i want to work  on this issue

**Comment by Ankush511** [comment]
Cannot find the documentation in the codebase.

**Comment by Ritik6547** [comment]
Hii zakreed, I want to work on this. So, can you assign it to me?

**Comment by blazete** [comment]
HI Zakreed,wanted to work on this it would be a great help if you assign it to me

**Comment by Monika-Sivakumar-3** [comment]
Shall I work on this issue?

**Comment by parth656** [comment]
@jasonsaayman @axios @zakreed @blazete  @akshayantony55 @Ritik6547  pls assign it to me

**Comment by Ritik6547** [comment]
@zakreed I didn't find documentation in this repository so i fixed it here  https://github.com/axios/axios-docs/pull/139

**Comment by maverox** [comment]
I wanna work on this issue

**Comment by Yashh56** [comment]
https://github.com/axios/axios-docs/pull/143

**Comment by developerr-ayush** [comment]
hey @zakreed can you assign it to me so that i can work on it.

**Comment by Typical-Techno** [comment]
I want to work on this issue

**Comment by Tejodeep2002** [comment]
I want to work on this issue

**Comment by PRITISH212121** [comment]
heyy,can you please assign it to me?
i would like to contribute.

**Comment by piyushdubey490** [comment]
Hello Maintainer , Could you assign this issue to me ? I would love to contribute

**Comment by falgunmpatel** [comment]
Hey @zakreed, Can you assign this issue to me?

**Comment by Kushagra1710** [comment]
> ### Section/Content To Improve
> On the documentation page for Multipart Bodies (https://axios-http.com/docs/multipart) there is a line that reads:
> 
> "HTML form can be passes directly as a request payload"
> 
> ![image](https://user-images.githubusercontent.com/93351349/264354413-b2576fa3-1b55-4ec1-8ce4-959eff11bbd6.png)
> 
> ### Suggested Improvement
> I believe that this should be `passed` instead of `passes`.
> 
> So the text should read:
> 
> "HTML form can be passed directly as a request payload"
> 
> ### Relevant File(s)
> _No response_

I want to contribute !!
can you please assign it to me?

**Comment by Rishikesh63** [comment]
!assign

**Comment by Moha-dotcom** [comment]
I want to work on this issue

**Comment by Bikisome** [comment]
I want to work with this issue,
can you please assign it to me?

**Comment by Yashh56** [comment]
maintainer, close this issue soon there are around 5-6 pr

**Comment by VivekChatterjee** [comment]
@zakreed you can close this issue after merging

**Comment by zakreed** [comment]
Hi everyone, thanks for your interest in this.

I think i'm going to close this now even though its not complete yet.

Not only was it technically made in the wrong repository, but we have I think 18 pull requests that fix this issue.

Hopefully one of these can be merged soon

We also have an issue open in the docs repository for this: axios/axios-docs#133
