### ISSUE TITLE
omit fortify vulnerability

### ISSUE THREAD

**Issue by llrichardll** [axios/axios#5854]
### Describe the issue

Good morning I have the following scenario I have a pipeline that goes through several stages and one of them is fortify every time there is an execution in jenkins creates a version in fortify ex the pipeline goes in the execution 10 in fortify I will get the version 10 of the application, but something particular happens the application that I want to deploy detects a critical vulnerability this causes that it is not deployed, is there any way to be able to a critical vulnerability.

I share part of the pipeline and the method that uploads the analysis to fortify.

    container('Fortify') {
    scanFortify {
    routeScan: "src/.java" { routeScan: "src/.java" { routeScan: "src/.java"
    nameProject: env.nameProject
    }
    }

    def uploadFPR(String nameProject){
    pipelineUtil.printm("Upload FPR -- App: ${nameProject} -- Version: ${BUILD_NUMBER}", "INFO")
    fortifyUpload appName: "${nameProject}", appVersion: "${BUILD_NUMBER}", resultsFile: 'code.fpr'
    }

    def call(Map pipelineParams){
    stage('Fortify'){
    if(pipelineParams.python == true){
    scan.scanFortifyPython(pipelineParams.routeScan,pipelineParams.version)
    }else{
    scan.scanFortify(pipelineParams.routeScan)
    }

    scan.uploadFPR(pipelineParams.nameProject)
    scan.verifyVulnerabilites(pipelineParams.nameProject)
    }
    }

**Comment by DavidJDallas** [comment]
I can't see anything in this that relates to or involves Axios
