### ISSUE TITLE
I set withCredentials is true, but cross-site requests failed. I can't find why...

### ISSUE THREAD

**Issue by 2ue** [axios/axios#587]
the  cross-site url is can access directly, but I can't get the data(dateType is json) through  cross-site requests.
Code:
```
const songList = axios.create({
  timeout: 10000,
  withCredentials: true,
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'x-www-form-urlencoded',
  },
  params: {
      id: 37880978,
      updateTime: -1
    }
});
songList.get(API.playlistDetail)
.then(function (response) {
    console.log(response);
})
.catch(function (error) {
    console.log(error);
});
```

**Comment by rubennorte** [comment]
Could you provide more information about this error? What are you seeing in the browser console?

**Comment by mshibl** [comment]
I'm having the same issue .. what I have found out is setting axios.defaults.withCredentials = true; and not using an instance at all solves the issue

**Comment by mdsaleemj** [comment]
@mshibl , Which version of axios you are using ? I trying to do xhr post request using axios  (along with param withCredential=true) but no response.

**Comment by aarondfrancis** [comment]
@mshibl's solution worked for me. Setting the default and not relying on an instance was the trick ¯\_(ツ)_/¯

**Comment by psychosis448** [comment]
@velopert I got the same question.
@mshibl tank you!

**Comment by mqliutie** [comment]
@mshibl Thanks for your share

**Comment by mdavid88** [comment]
Anything on this?

**Comment by mdavid88** [comment]
My mistake, withCredentials set on the instance IS working for me. My issue was I wasn't seeing the set-cookie header in the response in the network tab or in document.cookie, but it's probably because I don't have a good enough understanding of what Chrome lets you see from cross-origin cookies.

Going to chrome://settings/siteData let me search by the domain of the cookie, and I saw that it was being set correctly with:

`axios.create({
  withCredentials: true,
})`

and it wasn't being set at all without, so it's working for me in axios version 0.18.0

**Comment by codeclown** [comment]
Which version does this occur on?

On current master this test passes, so there should be no difference between using an instance or not:

```js
// Altered copy of test 'should set xsrf header for cross origin when using withCredentials'
// in xsrf.spec.js

it('should set xsrf header for cross origin when using withCredentials (instance)', function (done) {
  document.cookie = axios.defaults.xsrfCookieName + '=12345';

  var instance = axios.create({
    withCredentials: true
  });

  instance('http://example.com/');

  getAjaxRequest().then(function (request) {
    expect(request.requestHeaders[axios.defaults.xsrfHeaderName]).toEqual('12345');
    done();
  });
});
```

**Comment by maamounapprise** [comment]
doesn't work tried defaults and instance

**Comment by maamounapprise** [comment]
it's not an issue with axios i just made it work on the latest version, I was using express cors so i simply added credentials: true, origin: http://yourdomain:3000. This won't work on localhost you have to point your localhost into some fake domain and have all your apps run on that domain

**Comment by veselinnguyen** [comment]
Hi guys,

Is there any progress on this issue?

Regards,
V.N.

**Comment by waspar** [comment]
Is there any progress on this issue? 😢

**Comment by psychosis448** [comment]
@waspar @veselinnguyen 
It works for me on `axios 0.18.0`

Make sure to create an axios instance, to set `witCredentials` globally, e.g. HTTP.js:
```javascript
import axios from 'axios'

const HTTP = axios.create({
  withCredentials: true
})

export default HTTP
```

**Comment by psychosis448** [comment]
@waspar @veselinnguyen 
It works for me on `axios 0.18.0`!

Part of my HTTP setting:

```javascript
import axios from 'axios'

const HTTP = axios.create({
  withCredentials: true
})

export default HTTP
```

**Comment by ctot-nondef** [comment]
Whilst the Setting of withCredentials is working(on both instantiated and directly created) , passing custom XSRF headers still is not: 
`axios.post('https://testtest.com/api/v1/entity/', e, {
    withCredentials: true,
    xsrfCookieName: 'csrftoken_testtest',
    xsrfHeaderName: 'X-CSRFToken',
})`
includes all cookies, however does not extract and set the mentioned xsrfheader - am I holding it wrong?

**Comment by Ddper** [comment]
https://github.com/nuysoft/Mock/issues/300

mockjs aways set withCredentials false

**Comment by sulistiyono346** [comment]
> Whilst the Setting of `withCredentials` is working(on both instantiated and directly created) , passing custom XSRF headers still is not:
> 
> ```js
> axios.post('https://testtest.com/api/v1/entity/', e, {
>     withCredentials: true,
>     xsrfCookieName: 'csrftoken_testtest',
>     xsrfHeaderName: 'X-CSRFToken',
> })
> ```
> 
> includes all cookies, however does not extract and set the mentioned xsrfheader (even though the cookie is definitely present!) -
> 
> am I holding it wrong?

work for me

**Comment by goufaning** [comment]
@Ddper  Thanks for your share! The Setting of  `withCredentials` works  after I close mockjs.

**Comment by dillonburns** [comment]
i've been fiddling with persistent user sessions for a while and was having trouble stringing together `passport / passport-local` (for authentification), `mongoose`, `express-session`, and `connect-mongo` (for storing sessions in mongo). 

@mshibl comment helped me get 1 step further, and setting these `cors` options for `express` finally had cookies being passed correctly. hopefully this helps someone else having a similar issue

```
app.use(cors({
  credentials: true,
  origin: "http://localhost:3000"
}));
```

**Comment by chasen-bettinger** [comment]
Thanks @dillonburns this worked for me.

**Comment by Alanscut** [comment]
set `withCredentials` whether use instance or axios.defaults works in 0.18.0 and 0.19.0.
https://github.com/axios/axios/blob/841466416b6851666955113a60ae46830a27003f/test/specs/xsrf.spec.js#L70-L81

**Comment by theajr** [comment]
> I'm having the same issue .. what I have found out is setting axios.defaults.withCredentials = true; and not using an instance at all solves the issue

It helped.

**Comment by hyshka** [comment]
Just ran into this in my upgrade to `0.19.0-0.19.2` and specifying `withCredentials` on the global axios level before creating a session instance solved it for me.

```
axios.defaults.withCredentials = true
```

I was having all sorts of funky issues with set-cookie headers not working for my CSRF tokens.

**Comment by Skylercrane23** [comment]
This worked for me

`export default function({ $axios, redirect }, inject) {
  // Base URL
  const base = process.env.API_URL

  // Sett withCredentials on $axios before creating instance
  $axios.defaults.withCredentials = true

  // Create a custom axios instance
  const api = $axios.create({
    baseURL: base,
    responseType: 'json',
    timeout: 10000,
    // withCredentials: true,
    headers: {
      'X-Requested-With': 'XMLHttpRequest',
      'Content-Type': 'application/json'
    }
  })

  // Inject to context as $api
  inject('api', api)`

**Comment by timmaloshtan** [comment]
Guys, to whoever is still stuck on this in 2020.

Axios only ever looks at the withCredentials setting, if environment you are executing it in resembles a browser environment.
You can check their source code

Say your are making your requests from Jest, then make sure that you have testEnvironment: "jsdom" in jest.config

**Comment by timmaloshtan** [comment]
Guys, to whoever is still stuck on this in 2020.

Axios only ever looks at the `withCredentials` setting, if environment you are executing it in resembles a browser environment.
You can check their [source code](https://github.com/axios/axios/blob/5e0fb5fc998d7f9f5a897363977b42f4fa047238/lib/adapters/xhr.js#L105)

Say your are making your requests from Jest, then make sure that you have `testEnvironment: "jsdom"`  in `jest.config`

**Comment by wallaceturner** [comment]
`axios.defaults.withCredentials = true`

Why is this not the default?

**Comment by Skylercrane23** [comment]
Mine worked setting the default before creating the instance.

**Comment by canumay** [comment]
@dillonburns thanks!

**Comment by Hulkmaster** [comment]
@Alanscut correct me if i'm wrong, but setting that default with `axios.create` still doesn't work?

what i would like to have: separate axios instance, where credentials are enabled by default

`expected:`
```
const defaultHttpClient = axios.create({
  baseUrl: 'https://example.com',
});

// will NOT provide credentials
defaultHttpClient.get('/');


const apiHttpClient = axios.create({
  baseUrl: 'https://example.com',
  withCredentials: True,
});

// will provide credentials
apiHttpClient.get('/');
```
