### ISSUE TITLE
Catch Block Not Handling Internal Server Error (500) in Axios Request

### ISSUE THREAD

**Issue by affanmehmood** [axios/axios#5876]
### Describe the bug

When making an HTTP GET request using Axios (version 1.4.0), the catch block is not handling internal server errors (HTTP status code 500). Instead, the code proceeds to check if the response status is 200 and does not execute the error handling logic when the server responds with an HTTP status code of 500. This behavior needs to be addressed to ensure proper error handling in the application.

### To Reproduce

1. Execute an HTTP GET request using Axios with version 1.4.0.
2. Make the request to a URL that may result in an internal server error (HTTP status code 500).
3. Observe that the catch block does not handle the error, and the code continues to check the response status.

### Code snippet

```js
try {
    const response = await axios({
        headers: {
            "Content-Type": "application/json",
            "Cache-Control": "no-cache",
        },
        method: "GET",
        url: "someurl",
    });

    if (response.status === 200) {
        return response.data;
    } 
} catch (error) {
    console.error(error);
    throw error;
}
```

### Expected behavior

When an internal server error (HTTP status code 500) occurs, the catch block should be triggered, and appropriate error handling logic should be executed.

**Actual Behavior:**
The catch block is not handling internal server errors, causing issues with error handling in the application.
Rather than going to the catch block, it is going ahead to if (response.status === 200)

### Axios Version

1.4.0

### Browser

Chrome

### Node.js Version

18.17.1

**Comment by jasonsaayman** [comment]
hi @affanmehmood please can you check that the endpoint you are using is actually correctly setting a 500 error. can I please also ask if possible you share at least the response you are getting so I can validate that it is well formed? Thanks

**Comment by affanmehmood** [comment]
Yes, the endpoint is raising the exeption correctly, infact the console error in chrome devtools is also showing the error:

xhr.js:251     GET http://localhost:5000/api/endpoint 500 (INTERNAL SERVER ERROR)
dispatchXhrRequest @ xhr.js:251
xhr @ xhr.js:49
dispatchRequest @ dispatchRequest.js:51
Promise.then (async)
request @ Axios.js:124
wrap @ bind.js:5
loadTable @ edge.ts:393
handleOpenDialog @ ShowOptions.tsx:13
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889


After this it goes on to check the status, rather than going to the catch block:

TypeError: Cannot read properties of undefined (reading 'status')

**Comment by JozefKsl** [comment]
I was not able to reproduce this issue, and the error is correctly being handled by catch block. 

This is the backend endpoint I used:

`
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.status(500).send('Internal Server Error')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
`
And this is the script I used to call the endpoint 

`
const axios = require('axios')

const main = async () => {
    try {
        const response = await axios({
            headers: {
                "Content-Type": "application/json",
                "Cache-Control": "no-cache",
            },
            method: "GET",
            url: "http://localhost:3000/",
        });

        if (response.status === 200) {
            return response.data;
        } 
    } catch (error) {
        console.log('coming here')
    }
}

main().then(res => console.log('Response', res))
`

The 'coming here' was printed to the console upon execution as expected.

**Comment by sinavali** [comment]
i have the exact same problem with vue3, axios 1.4.0
in network i get status 500 but catch is not triggering...

**Comment by andradedaniel** [comment]
Same here.. 
vue@3.3.12
axios@1.6.5

**Comment by D-coder101** [comment]
How do we solve this

**Comment by danielnmai** [comment]
I had the same issue where the 500 error is correctly returned from server but axios is not able to catch it properly. I had to use interceptors and manually throw it:

`    this.axiosInstance.interceptors.response.use(
      (response) => {
        return response
      },
      (error) => {
        if (error instanceof AxiosError && error.response?.status == 500) {
          return Promise.reject(error)
        }
      }
    )`
    
    This works but not sure if there is a better way of handling this.

**Comment by iamrohitagg** [comment]
I am still not able to get this work after applying all solutions here.

**Comment by nav610** [comment]
Seeing the exact same issue.
