### ISSUE TITLE
Ability to define the response inside a request interceptor

### ISSUE THREAD

**Issue by GaryPEGEOT** [axios/axios#5912]
### Is your feature request related to a problem? Please describe.

My use case is that I want , when I'm in **test** environment, to be able to intercept a request and define "manually" the response. 

For example, my interceptor would be supplied with an `HAR` file, and would be able to generate a response without the client making any actual HTTP request.

### Describe the solution you'd like

I would be cool to be able to set the response inside the request interceptor.

### Describe alternatives you've considered

I know Jest allow you to mock the full axios module, but a more _integrated_ approach would be nice.

**Comment by WillianAgostini** [comment]
Hi @GaryPEGEOT 
can [axios-mock-adapter](https://www.npmjs.com/package/axios-mock-adapter) or [nock](https://github.com/nock/nock) solve your problem?

**Comment by GaryPEGEOT** [comment]
Hi @WillianAgostini!

Yes and no, it involve a lot of manual process as you have to define the response for each request, and you need to install an additional package. In my case I would l like to create a record / replay system, or read responses for HAR files, so I don't have to define each request manually

**Comment by WillianAgostini** [comment]
Interceptor is used just to modify the request or response, and not to ignore the request.
If you want to mock the request you need to use any function to mock the request, here is an example without installing any additional packages https://stackoverflow.com/a/51654713
