### ISSUE TITLE
Content-Type set to false when sending form data

### ISSUE THREAD

**Issue by Nidilap** [axios/axios#5914]
### Describe the bug

I'm trying to upload a base64 image to my server in my React Native app. The base64 image is first converted to a blob, then is appended to a form data and sent to the server. I'm also explicitly setting the Content-Type as multipart/form-data.

The problem is that the request is not even being sent to the server, with a error: "AxiosError: Network Error".
When I check the AxiosError, I see that the Content-Type is set to false, so I think it is because of it.

![errorNetwork](https://github.com/axios/axios/assets/48497295/0c007a67-b2a0-4aef-9581-804325e63315)

### Code snippet

```js
const form = new FormData();

form.append("62", new Blob([base64String]));

axios.post(url, form, {
  headers: {
    "Content-Type": "multipart/form-data",
    "Accept": "multipart/form-data",
    "Authorization": "..."
  },
}).then(function (response) {
  debugger
 })
 .catch(function (error) {
  debugger
});
```

### Expected behavior

Axios should upload the form data and return a successful response

### Axios Version

1.5.0

### Node.js Version

16.16.0

### OS

Android 11

### Additional Library Versions

```bash
React 18.2.0
React Native 0.71.3
```

### Additional context/Screenshots

I found this issue https://github.com/axios/axios/issues/5615 that appears to be the same problem as me.
The issue was closed because the OP managed to make it work using a object instead of a Blob.
When I tried this solution, it still had the same problem of setting Content-Type to false:
```bash
form.append("file", {
  uri: base64String,
  type: 'image/jpeg',
  name: "testepdf"
});
```

When I used a string in the second parameter of append, the Content-Type was set correctly, so it is some problem with object/blob.

**Comment by AhmedMustafa505** [comment]
Same issue in RNW

**Comment by DigitalBrainJS** [comment]
Axios doesn't do anything special with the FormData payload on the client side and doesn't have any platform-specific for ReactNative. FormData is passed directly to the XMLHttpRequest, so this is an RN platform issue. They seem to have their own implementation of FormData with some spec incompatibility that prevents native blobs from being used as payload.
[Judging by the comment](https://github.com/facebook/react-native/blob/030663bb0634fc76f811cdc63e4d09e7ca32f3d4/packages/react-native/Libraries/Network/FormData.js#L78C1-L82C48) in the code and the non-standard interface, they basically [do not support appending Blobs](https://github.com/facebook/react-native/issues/35698#issuecomment-1441579017)

> In fact, using the FormData object in React Native is not similar to the web. You should pass a FormDataValue as second paramater of the append function : FormDataValue = string | {name?: string, type?: string, uri: string}

So this is definitely the target platform issue. There is no solution here, except perhaps port the functionality with its own FormData encoding that Axios uses on the server side, but given the current architecture without plugins functionality, this would seriously increase the size of the client bundle, which is unacceptable for the browser.

**Comment by Yugender025** [comment]
Please ensure that the URL is correctly assigned. Often, these types of errors occur when the backend server and the URL used in the frontend are mismatched. Therefore, double-check to ensure that the URL is in the correct format and free of any mistakes.

**Comment by Nidilap** [comment]
> Please ensure that the URL is correctly assigned. Often, these types of errors occur when the backend server and the URL used in the frontend are mismatched. Therefore, double-check to ensure that the URL is in the correct format and free of any mistakes.

I double-checked it and it is the correct URL
