### ISSUE TITLE
when clicking on the button i want the car part to be added but it dosent work

### ISSUE THREAD

**Issue by Ayoub-Chebbi** [axios/axios#5916]
### Describe the issue

when clicking on the button i want the car part to be added but it dosent work my backend works fine and i testes it with postman

### Example Code

```js
import React, { useState } from 'react'
import "./AdminCarParts.css"
import axios from 'axios'
import { useNavigate } from 'react-router-dom'
import SideBar from '../AdminSideBar/SideBar'


const AdminCarParts = () => {
  const [PartName , setPartName] = useState("")
  const [PartImage , setPartImage] = useState("")
  const [Category , setCategory] = useState("")
  const [PartType , setPartType] = useState("")
  const [Price , setPrice] = useState(0)
  const [Date , setDate] = useState("")
  const [Description , setDescription] = useState("")
  const nav = useNavigate()


  const handleSubmit = (e)=>{
    e.preventDefault()
    const newObj = {
      PartName,
      PartImage,
      Category,
      PartType,
      Price,
      Date,
      Description,
    }
    axios.post("http://localhost:8000/api/car" , newObj)
        .then(res=>{
            nav("/")
        })
        .catch(err=>console.log(err))
}
  return (
    <div className='flex-carparts'>
      <SideBar/>
      <div id="login-form">
      <form onSubmit={handleSubmit}>
      <label htmlFor="Part-Name">Part Name:</label>
        <input type="text" id="Part-Name" name="Part-Name" onChange={(e)=>setPartName(e.target.value)} />
        <label htmlFor="Part-Image">Part Image:</label>
        <input type="text" id="Part-Image" name="Part-Image" onChange={(e)=>setPartImage(e.target.value)}/>
        <label htmlFor="category">Category:</label>
        <input type="text" id="category" name="category" onChange={(e)=>setCategory(e.target.value)} />
        <label htmlFor="Part-Type">Part Type:</label>
        <input type="text" id="Part-Type" name="Part-Type" onChange={(e)=>setPartType(e.target.value)} />
        <label htmlFor="Price">Price:</label>
        <input type="number" id="Price" name="Price" onChange={(e)=>setPrice(e.target.value)} />
        <label htmlFor="Date">Expiration Date:</label>
        <input type="date" id="Date" name="Date" onChange={(e)=>setDate(e.target.value)} />
        <label htmlFor="Description">Description:</label>
        <input type="text" id="Description" name="Description" onChange={(e)=>setDescription(e.target.value)} />
        <input type="submit" value="Submit"/>
      </form>
      </div>
    </div>
  )
}

export default AdminCarParts
```

**Comment by m-ali-hasnain** [comment]
Hey Ayoub! I hope you are doing good. 
I would love to assist you, If you can share schema of `Car Part`
because, I am thinking, it is possible that on backend side your field names are different as compared to one's you are sending from Frontend.

**Comment by IamAnkitR** [comment]
Hello Ayoub-Chebbi, hope you're doing well.
If you are not getting any response or errors when clicking the button to add a car part, there could be several reasons for this issue. Here are some steps to help you troubleshoot and resolve the problem:

1. Check Your Backend API:
Ensure that your backend API is running and listening on http://localhost:8000. You can try accessing the API endpoint directly in your browser or using tools like Postman to verify that it's functioning correctly.
Error Handling:

2. Network Request:
Open your browser's developer tools and go to the "Network" tab. Try submitting the form again and check if there is a network request being made to your API. If there's no network request, it indicates that the form submission isn't triggering the Axios request.

3. Form Submission:
Make sure that your form submission button (<input type="submit" value="Submit" />) is working as expected and is triggering the handleSubmit function. You can add a console.log statement inside the handleSubmit function to check if it's being called when you click the submit button.

4.Form Fields:
Ensure that all the form fields have valid values before submitting the form. You can add some basic validation to check if required fields are not empty.

5.CORS Issue:
If your frontend is running on a different port or domain than your backend, you might encounter Cross-Origin Resource Sharing (CORS) issues. Make sure your backend is configured to allow requests from your frontend's domain. You can use CORS middleware for this functionality.


By following these steps and debugging each part of your code, you should be able to identify and resolve the issue with your form submission not working. If you encounter specific error messages or issues, feel free to provide more details, and I can assist further.

**Comment by Ayoub-Chebbi** [comment]
thank you guys for the help the problem was in the schema names already figure it out thanks
