### ISSUE TITLE
In React Native axios return [] when responseType is "arraybuffer"

### ISSUE THREAD

**Issue by gustavosorati** [axios/axios#5922]
### Describe the issue

When I am making a request to obtain data from a route that returns a buffer, **axios returns []**, if I define the header as an arrayBuffer. I can only obtain the expected result through request._result. While on the web the expected result usually comes through a **`date`**.

I tried several different versions of axios, and they all resulted in the same experience.

I set up a project, where I believe you could test it and have the same result: [Link Demonstration Problem](https://github.com/gustavosorati/axios-rn-problem)
It contains a simple backend that returns an excel buffer, and a react native project consuming this data.

Is this issue a bug or expected behavior? If it is expected, why does it occur?

### Axios Version

1.5.1

### Additional Library Versions

```bash
"axios": "^1.5.1",
"expo": "~49.0.12",
"expo-status-bar": "~1.6.0",
"react": "18.2.0",
"react-native": "0.72.5"
```

**Comment by DigitalBrainJS** [comment]
Axios returns an ArrayBuffer instance as expected. `[]` this is how RN renders it in the console.

```js
    axios
      .get('https://dummyjson.com/products/1', {responseType: "arraybuffer"})
      .then(({data}) =>  {
        console.log('buffer', String(data));
        for(let byte of new Uint8Array(data.slice(0, 10))) {
          console.log('byte', byte);
        }
      });
```

```
 LOG  buffer [object ArrayBuffer]
 LOG  byte 123
 LOG  byte 34
 LOG  byte 105
 LOG  byte 100
 LOG  byte 34
 LOG  byte 58
 LOG  byte 49
 LOG  byte 44
 LOG  byte 34
 LOG  byte 116

```
