### ISSUE TITLE
Desktop View: Adjust Navigation Bar to Prevent Overlapping with Heading Lines"

### ISSUE THREAD

**Issue by Firdous708** [axios/axios#5944]
#### Summary

**Description:**
In the desktop view of the Axios website, the 'Heading'  located below the navigation bar is partially obscured by the shadow of the navigation bar. This results in some lines of the 'Heading'  being visually obstructed.

https://github.com/axios/axios/assets/82380855/dec20396-8623-4efd-8557-7eb7b9641206

#### Steps to Reproduce

1. Visit the Axios website in desktop view.
2. Observe the positioning of the 'Heading lines'  in relation to the navigation bar.

#### Expected Behavior

The 'Heading' lines should be fully visible and not obscured by the navigation bar shadow in the desktop view.

#### Suggested Solution

Adjust the styling or positioning of the navigation bar shadow to prevent overlapping with the content of the `Heading' lines in the desktop view.

#### Additional Information

- **Browser:** Chrome
- **OS.** Windows

## Note:
I am interested in working on this issue and would appreciate it if it could be assigned to me. I am willing to contribute to resolving this matter.

**Comment by rutulganatra** [comment]
I am interested in working on this issue and would appreciate it if it could be assigned to me. I am willing to contribute to resolving this matter.

**Comment by sysreset999** [comment]
I believe this issue is with your display size or you may have zoomed the page by mistake because this issue is not occurring in my pc.

**Comment by Firdous708** [comment]
I apologize for the confusion. It seems I opened this issue in the wrong repository. I've since opened the correct issue in the axios/axios-docs repository https://github.com/axios/axios-docs/issues/

Closing this issue here for proper tracking. Please feel free to continue the discussion in the new issue, and I appreciate your understanding.

Thank you!
