### ISSUE TITLE
Want to refactor the Footer UI & UX

### ISSUE THREAD

**Issue by crocmons** [axios/axios#5947]
### Is your feature request related to a problem? Please describe.

Yes, the feature request to refactor the axios Footer UI & UX is related to a problem. The current Footer UI & UX may not be providing an optimal user experience or may not align with the project's design standards. It could be causing issues such as poor navigation, usability, or aesthetics, which can affect the overall quality and user satisfaction of the application. Refactoring it can address these problems and improve the user interface and experience.

### Describe the solution you'd like

Now it look like this - ![Screenshot (57)](https://github.com/axios/axios/assets/106610322/9699d01a-443a-48f1-83cb-2a319be2a3b5)

I would like to modify my work to match the format of this template - please see the attached image
![Screenshot (74)](https://github.com/axios/axios/assets/106610322/2920362b-8ee3-4cb1-88f2-64abd0b27fe1)

**Comment by RacHiT101** [comment]
hey @crocmons can i work on this?

**Comment by maimoona-j** [comment]
Hi, can  I work on this please?

**Comment by ashishnallana** [comment]
hey @crocmons I would like to work on this.
