### ISSUE TITLE
Reduce the Size of Logo on Intro Page

### ISSUE THREAD

**Issue by crocmons** [axios/axios#5948]
### Is your feature request related to a problem? Please describe.

yes, it is. I would like to decrease the size of the logo on the intro page. Currently, the logo appears to be larger than desired, affecting the overall visual balance and user experience of the intro page. By reducing the logo size, we can improve the page's aesthetics and ensure that it aligns better with our design standards.

### Describe the solution you'd like

Currently it look like this - 
![Screenshot (75)](https://github.com/axios/axios/assets/106610322/f308e2f2-1cee-4c94-951d-36a08cbe30e6)

### Describe alternatives you've considered

I want to reduce the size of the logo on the intro page to improve the UI/UX.

**Comment by SinghUjjwal12** [comment]
Hello!! can you please assign this task to me?
I can do it properly.

**Comment by crocmons** [comment]
Already started working on this issue kindly take other issues @Tejodeep2002 @Shivam-Batham @SinghUjjwal12

**Comment by draksham** [comment]
can you assign this task to me?

**Comment by Thanush19** [comment]
can i fix this @crocmons ??

**Comment by therealobiora** [comment]
hello please can i fix this?

**Comment by Phickayor** [comment]
can i be assigned this task ?

**Comment by sranjan-git** [comment]
could you please assign this task to me.

**Comment by Puneet-Amrutkar** [comment]
can you please assign this task to me

**Comment by crocmons** [comment]
Do you want to add duplicate pull requests for the same issue when there are already 2 open? @Puneet-Amrutkar

**Comment by Puneet-Amrutkar** [comment]
> Do you want to add duplicate pull requests for the same issue when there are already 2 open? 

Yes
