### ISSUE TITLE
The section Developing in CONTRIBUTING file confusing

### ISSUE THREAD

**Issue by MrJithil** [axios/axios#5969]
### Section/Content To Improve

The section [developing](https://github.com/axios/axios/blob/v1.x/CONTRIBUTING.md#developing) mentioning about the below 3 commands
* `grunt test run` the jasmine and mocha tests
* `grunt build run` webpack and bundle the source
* `grunt version` prepare the code for release

But, the package json defines scripts for the same which is using npm.

Or are we still using grunt? 

### Suggested Improvement

* `npm run test` the jasmine and mocha tests
* `npm run build` webpack and bundle the source
* `npm run version` prepare the code for release

### Relevant File(s)

```bash
https://github.com/axios/axios/blob/v1.x/CONTRIBUTING.md#developing
```

**Comment by TheShiveshNetwork** [comment]
Hello, I am working on this issue, will get back to you soon!

**Comment by Vansh1419** [comment]
Could u assign this issue to me?

**Comment by MrJithil** [comment]
> Could u assign this issue to me?

PR already raised.

**Comment by ckng0221** [comment]
To take note `grunt` is also present in the `examples/README.md` file. 
#6073 will change the `grunt` in the README file to `npm run` too.
