### ISSUE TITLE
ERR_NETWORK when trying to upload file

### ISSUE THREAD

**Issue by sragkir** [axios/axios#5981]
### Describe the bug

Am using axios.post for a file upload. Previously it worked fine a month ago and there were no new changes. Also without any changes locally, I am able to run and upload files. When deployed in the Azure app service for a few days I see a Network Error whenever I try to add file and upload.

Below is code am using (form is FormData data type)
const response = await axios.post<Boolean>(url, form, {
headers: {
'Content-Type': 'multipart/form-data'
}
});

### To Reproduce

Using React 18.2, axios: "^0.27.2" and using input type file to select local file and upload it.
Locally am able to call backend to upload file but when I deployed in azure app services it is failing.

### Code snippet

```js
const response = await axios.post<Boolean>(url, form, {
headers: {
'Content-Type': 'multipart/form-data'
}
});
```

### Axios Version

^0.27.2

### Browser

Chrome, Edge

### Node.js Version

18.2.0

**Comment by jatin-2708** [comment]
I have looked upon it and i am interested in solving this issue , could you please assign this issue to me.

**Comment by vinamrahalgar** [comment]
Is this issue fixed, facing same issue while uploading form data.
