### ISSUE TITLE
Minimum reproduction code on create a new Issue

### ISSUE THREAD

**Issue by WillianAgostini** [axios/axios#6003]
### Is your feature request related to a problem? Please describe.

On [Nest](https://github.com/nestjs/nest) repository, when a  [Bug_report](https://github.com/nestjs/nest/issues/new?assignees=&labels=needs+triage&projects=&template=Bug_report.yml) is created, there is a question, see bellow.

![image](https://github.com/axios/axios/assets/22686401/684181dd-8086-4cc3-b478-2e2e51f879a8)

This would be great to add on ISSUE_TEMPLATE/BUG_REPORT.yml because forces the user to create a complete scenario to reproduce the error.

### Describe the solution you'd like

Create a template on [StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter) or [CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) that can be used to user to fork and create his demonstration of the bug, or user can share your code from GitHub, after this update ISSUE_TEMPLATE/BUG_REPORT.yml

### Additional context/Screenshots

Must create a template on axios repositories to link a template ready for use to StackBlitz and CodeSandbox

**Comment by AnirudhTripathi** [comment]
While raising an issue, do you require a template which helps users to explain their issues?

**Comment by WillianAgostini** [comment]
Yes, a minimal reproduction of the bug
