### ISSUE TITLE
"ERR_NETWORK" for 429

### ISSUE THREAD

**Issue by tovarnakM** [axios/axios#6043]
Hi, I would like to ask how to detect e.g. the 429 error status code after the axios request failed for too many requests. The catch block does not have an information about status code. There is only a generic error "ERR_NETWORK".

**Comment by sepehr** [comment]
Have you had a conclusion @tovarnakM?

**Comment by ramkumar2098** [comment]
I am also not able to detect 429 error

**Comment by vasilich6107** [comment]
@jasonsaayman @DigitalBrainJS is there any recommedation?
