### ISSUE TITLE
 ReferenceError: navigator is not defined + Jest

### ISSUE THREAD

**Issue by MAKARD** [axios/axios#6067]
### Describe the bug

On version 1.6.1, I've got the following error during test execution (Jest + React-native)

```
The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: navigator is not defined
```

Can confirm on version 1.6.0 everything works just fine.

### To Reproduce

Any Jest test with Axios without mocks

### Code snippet

```js
import Axios from 'axios';

describe('Test', () => {
  it('should pass', () => {
    Axios.get('');
    expect(true).toBe(true);
  });
});
```

### Expected behavior

Does not throw an error

### Axios Version

1.6.1

### Adapter Version

~

### Browser

~

### Browser Version

~

### Node.js Version

18

### OS

MacOS 14.0

### Additional Library Versions

```bash
Jest 29.6.3
```

**Comment by DigitalBrainJS** [comment]
Looks strange. It's not clear how this error could occur with the current code. Without a project config or a live example, it is hardly possible to reproduce the issue.
It's [the only place](https://github.com/axios/axios/blob/f6d2cf9763bfa124f15c2dc6a5d5d5d9d3e26169/lib/platform/common/utils.js#L20-L23) where it can occur, but it looks fine and definitely works in node.js
```js
const hasStandardBrowserEnv = (
  (product) => {
    return hasBrowserEnv && ['ReactNative', 'NativeScript', 'NS'].indexOf(product) < 0
  })(typeof navigator !== 'undefined' && navigator.product);
```

**Comment by MAKARD** [comment]
Indeed, my bad. The statement "global.document = {};" was in jest setup files.
Apologies for the inconvenience
