### ISSUE TITLE
/lib/platform/index.js Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by walkwolf** [axios/axios#6068]
### Describe the bug

ERROR in ./node_modules/axios/lib/platform/index.js
Module parse failed: Unexpected token (5:2)
You may need an appropriate loader to handle this file type.
|
| export default {
|   ...utils,
|   ...platform
| }
 @ ./node_modules/axios/lib/defaults/index.js 8:0-44
 @ ./node_modules/axios/lib/axios.js
 @ ./node_modules/axios/index.js
 @ ./src/utils/request.js
 @ ./src/main.js

  Build failed with errors.

### Axios Version

1.6.1

### Node.js Version

16.20.0

### OS

OSX 14.1

**Comment by walkwolf** [comment]
es6 support

**Comment by amigo267** [comment]
npm uninstall axios
npm install axios@0.25.0 --save

**Comment by PrinceCong** [comment]
1.6.1版本我也遇到了，不知道是不是webpack的原因

**Comment by konpeki622** [comment]
some solutions for 1.6.1?

**Comment by meteorOSS** [comment]
> npm uninstall axios npm install axios@0.25.0 --save

thanks!!

**Comment by szwalkowski** [comment]
Have the same problem after changing 1.6.0 to 1.6.1 and above

**Comment by szwalkowski** [comment]
> npm uninstall axios npm install axios@0.25.0 --save

This is a problem. 0.25 has vulnerabilities
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

**Comment by AlexandreAkao** [comment]
> > npm uninstall axios npm install axios@0.25.0 --save
> 
> This is a problem. 0.25 has vulnerabilities https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788 https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459
> 
> EDIT: Overcame this with babel

How?

**Comment by nsirbu** [comment]
I'm also having this issue. How did you fix it?

**Comment by narendrawadhwa** [comment]
i am facing the same issue what to do?

**Comment by camaced** [comment]
Hello -- I am experiencing this error and do not know how to fix it. I see that this ticket is closer. What was the the resolution notes for this?

**Comment by TeamBuilderApp** [comment]
> npm uninstall axios npm install axios@0.25.0 --save

Thanks!! This fixed the issue. 

FYI this issue still exists with the latest npm install of axios on 7/30/2025.
