### ISSUE TITLE
Axios not passing through all headers

### ISSUE THREAD

**Issue by rjewsbfd** [axios/axios#6087]
### Describe the bug

if i set a header  is-snake on an instance or pass this header like const headersx  below its dropped. It wont get sent in the outgoing request headers, it does not get seen in proxy capture or on the server. 

other custom headers like  DOESNOTHING and grumpymomma being sent on the proxy and on the server but is-snake does not get sent and seams to be getting dropped

### To Reproduce

send a post request with is-snake header  passing to either of these or setting the header on an instance
 
axios.post
instance.post

### Code snippet

```js
const instance = axios.create({
     baseURL:  urls.getEnvUrl(),
     timeout: 1000,
     headers: {'Is-Snake': false,'DOESNOTHING':'lalala'}
});

const headersx = {
            referer: `${url}`,
            accept: 'application/json',
            'grumpymomma' : 'yoMomma',
            'Content-Type': 'application/json', // on call we edited this
            'Path': path,
            Origin: `${url}`,  // on call we edited this
            'is-snake': false,
            ..._headers
        }

await instance.post(
            url+path,
            body,
            {
                headers:headers,
                proxy: {
                    protocol: 'http',
                    host: '127.0.0.1',
                    port: 8888
                }
        } 
        ).then((request,response)=>{
            console.log(request.headers)
            data = response
        }).catch(e =>{
            console.log(e)
        })
```

### Expected behavior

if I set a header it should be sent. Seams to be a bug unless im doing something wrong. I can use the same headersx variable in node-fetch and it gets sent as expected. 

### Axios Version

9.8.1

### Node.js Version

v18.18.1

### OS

windows

**Comment by WillianAgostini** [comment]
Hi @rjewsbfd 
`false` and `null` values are ignored.
See: https://github.com/axios/axios/issues/6013#issuecomment-1771006219

**Comment by rjewsbfd** [comment]
thanks for info, seams pretty silly but whatever i guess
