### ISSUE TITLE
Axios request with baseUrl + url redirects to 127.0.0.1:80

### ISSUE THREAD

**Issue by mohseenrm** [axios/axios#6118]
### Describe the bug

When using the default axios instance to create a request, when providing a valid `baseUrl` and `url`, it sends off a request to 127.0.0.1:80 instead of the intended location.

Works fine if only providing a fully qualified `url` parameter.

### To Reproduce

```js
const axios = require("axios");
const baseUrl = "http://localhost:18181";
const url = "/dummy/api/route";

const response = await axios({
      method: "get",
      baseUrl,
      url,
      // ^^^ uncomment to view bug ECONNREFUSED 127.0.0.1:80
      // url: `${baseUrl}${url}`,
      // ^^^ uncomment to view fix ECONNREFUSED 127.0.0.1:18181
      proxy: false,
    });
```

codesandbox [link](https://codesandbox.io/p/devbox/node-axios-client-testing-7slxtp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpucdh3m00063b6ostngw172%2522%252C%2522sizes%2522%253A%255B53.04891922639363%252C46.95108077360637%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpucdh3m00023b6ob4a7ylt8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpucdh3m00043b6om62eydgx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpucdh3m00053b6olfe0gkjp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpucdh3m00023b6ob4a7ylt8%2522%253A%257B%2522id%2522%253A%2522clpucdh3m00023b6ob4a7ylt8%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpucdh3m00053b6olfe0gkjp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpucdh3m00053b6olfe0gkjp%2522%257D%252C%2522clpucdh3m00043b6om62eydgx%2522%253A%257B%2522id%2522%253A%2522clpucdh3m00043b6om62eydgx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpucdh3m00033b6o1gfrdsa8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpucdh3m00033b6o1gfrdsa8%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Adapter Version

HTTP

**Comment by mohseenrm** [comment]
@simoneb

**Comment by simoneb** [comment]
> @simoneb

Any reason you tagged me? :)

**Comment by mohseenrm** [comment]
Ah my bad, thought you might be one of the core maintainers 😅  Apologies for the ping

**Comment by mohseenrm** [comment]
@DigitalBrainJS

**Comment by Madhusudhanbura** [comment]
@mohseenrm 
You have to pass the baseUrl string to baseURL argument in the axios instance like:

```
const response = await axios({
      method: "get",
      baseURL: baseUrl,     //this is how you have to pass it
      ...
```
Similar to your fix i.e url: `${baseUrl}${url}`,
Hope this solves your issue. Please acknowledge.
You can have a look at the documentation: https://axios-http.com/docs/req_config

**Comment by mohseenrm** [comment]
@Madhusudhanbura hmmm they both are equivalent, what I provided in my sandbox link is shorthand for the syntax you mentioned.

either way, passing it as `baseUrl,` or `baseUrl: baseUrl,` or `baseUrl: "httpL//localhost:18181",` all cause the request to go to http://127.0.0.1:80

**Comment by exceedcat** [comment]
@mohseenrm hi there, I'm not certain if this is still relevant (but given that the issue remains open), it appears that there might be a spelling error. It is supposed to be `baseURL` (where URL is in upper-case) and not `baseUrl`. I've checked your example, if you rename your variable, it should work just fine!
codesandbox [link](https://codesandbox.io/p/devbox/node-axios-client-testing-forked-yq7qvr?file=%2Findex.js%3A7%2C8&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpucdh3m00063b6ostngw172%2522%252C%2522sizes%2522%253A%255B53.04891922639363%252C46.95108077360637%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpucdh3m00023b6ob4a7ylt8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpucdh3m00043b6om62eydgx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpucdh3m00053b6olfe0gkjp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpucdh3m00023b6ob4a7ylt8%2522%253A%257B%2522id%2522%253A%2522clpucdh3m00023b6ob4a7ylt8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clranzd9900023b6mjq176mnr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A8%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A8%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clranzd9900023b6mjq176mnr%2522%257D%252C%2522clpucdh3m00053b6olfe0gkjp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpucdh3m00053b6olfe0gkjp%2522%257D%252C%2522clpucdh3m00043b6om62eydgx%2522%253A%257B%2522id%2522%253A%2522clpucdh3m00043b6om62eydgx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpucdh3m00033b6o1gfrdsa8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpucdh3m00033b6o1gfrdsa8%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by mohseenrm** [comment]
@exceedcat yep, just realized had mistyped the `baseURL` parameter. Closing this out.
