### ISSUE TITLE
axios Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by avinash5991** [axios/axios#6141]
### Describe the bug

https://security.snyk.io/vuln/SNYK-JS-AXIOS-6124857

[axios](https://www.npmjs.com/package/axios) is a promise-based HTTP client for the browser and Node.js.

Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS). An attacker can deplete system resources by providing a manipulated string as input to the format method, causing the regular expression to exhibit a time complexity of O(n^2). This makes the server to become unable to provide normal service due to the excessive cost and time wasted in processing vulnerable regular expressions.

**Comment by KhasanLaudry** [comment]
the same issue as here https://github.com/axios/axios/issues/6131
