### ISSUE TITLE
axios vulnerabilities in latest version

### ISSUE THREAD

**Issue by umangsavaliya** [axios/axios#6146]
### Describe the bug

https://security.snyk.io/package/npm/axios

<img width="944" alt="image" src="https://github.com/axios/axios/assets/910181/105e2fd0-caad-4679-ad47-fe52e6760652">

**Comment by GaelCO** [comment]
Same issue as https://github.com/axios/axios/issues/6131 and https://github.com/axios/axios/issues/6141

**Comment by phuvinhbmt** [comment]
axios 1.6.3 has 0 vulnerabilities. I think you can close this issue

**Comment by ppatil-cybage** [comment]
I tried updating axios to 1.6.3 now getting below error<
