### ISSUE TITLE
follow-redirects should not be used in browser

### ISSUE THREAD

**Issue by RubenVerborgh** [axios/axios#6182]
### Describe the issue

Hiya,

I'm the maintainer of your dependency `follow-redirects`, getting inbound since your switch to our `1.15.4` that this version does not work in browsers:
- https://github.com/follow-redirects/follow-redirects/issues/237
- https://github.com/follow-redirects/follow-redirects/pull/238

The `follow-redirects` library must not be used in browsers; it is bringing browser functionality to Node. It has no effect in the browser and must not be used.

Some users of Axios might be doing the wrong thing somehow. I just wanted to let you know.

### Additional Library Versions

```bash
follow-redirects 1.15.4
```

**Comment by DigitalBrainJS** [comment]
Hey @RubenVerborgh ! Thanks for the notice! 
However, Axios doesn't have follow-redirects in the browser build. It's only used in HTTP adapter module, which is shadowed by a null value depending on the browser & conditional export fields in the package.json. So this issue can only happen if the user makes his build with the wrong bundler/pipeline config.

**Comment by RubenVerborgh** [comment]
Thanks for confirming, I can now point people to this response. If more users stumble upon this problem, it might be worth considering an additional warning in the documentation.

**Comment by CCMA-Enginyeria** [comment]
We're facing that issue using nextjs where code could be executed on both sides. Today, we're going to check in detail our project, and if we find the source of the issue we will let you know.
