### ISSUE TITLE
Axios get CORS error when I added custom headers and Authorization header also

### ISSUE THREAD

**Issue by litosh-web** [axios/axios#6190]
### Describe the bug

I started development mode in Next.js 12. Frontend was started on localhost:3000, backend on another port and it was with a docker, nginx and php. All works well, but when I don't set **headers** in request. When I added custom header or Authorization header - it crashed by CORS policy.
I added all CORS policy with a signment *. I stuck with this issue already 3 days.

### To Reproduce

For example, I get an open API and it works also bad.
```
const response = axios.get('https://api.publicapis.org/entries', {
                    headers: {
                        'X-Custom-Header': 'foobar'
                    },
                    params: data,
                }).then(res => {
                    console.log(res);
                })
```

### Axios Version

1.6.5

### Adapter Version

XHR

### Browser

Chrome

### Browser Version

120.0.6099.224

### Node.js Version

v20.5.1

### OS

Windows 10

### Additional Library Versions

```bash
Next js 12
```

### Additional context/Screenshots

```bash
https://disk.yandex.ru/i/YmPDH6pEdfem6A
```

**Comment by FUYAe** [comment]
you can check if the backend supports preflight cross requests. Customized headers cross requests can be a little bit more complex. you can read: https://javascript.info/fetch-crossorigin

**Comment by JatSh1804** [comment]
Even I was getting this Error, have also allow access to the frontend PORT, but still doesn't work. Maybe this has something to do with browser.
Now i am using a extension to block CORS Security for development purposes, And for production i will be serving Frontend through the server. 
It works for me.

**Comment by litosh-web** [comment]
It causes by sent request on another submdomain/domain. Now I just send it to the same domain.
