### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by developer-choi** [axios/axios#6200]
### Describe the bug

https://github.com/developer-choi/axios-error-report

TypeError is occurred (in 1.6.6 version)

<img width="184" alt="image" src="https://github.com/axios/axios/assets/51902362/1f7f6e7f-8c8b-4ef7-9854-5c08f572d58b">

<img width="171" alt="image" src="https://github.com/axios/axios/assets/51902362/36042439-a071-485e-b696-9f2c01849759">

### To Reproduce

https://github.com/developer-choi/axios-error-report

### Axios Version

1.6.6

### Browser

CHROME

### Browser Version

120.0.6099.225

### Node.js Version

20.11.0

### OS

Window 11

**Comment by zhijianDET** [comment]
having the same issue here , rollback to 1.6.5 seems fine though

**Comment by ildella** [comment]
Happens on Linux as well, Ubuntu 23.10

**Comment by kah3vich** [comment]
> having the same issue here , rollback to 1.6.5 seems fine though

I had a version - "axios": "^1.6.5", I fixed it by removing the "^" and selected only this version - 1.6.5

**Comment by ddcrobert** [comment]
> How can i do this? any example please

Try a request without an internet connection, it will create a Network Error without response / stack.

**Comment by luoliwoshang** [comment]
> 1.6.5

Tks,Its fix my error
