### ISSUE TITLE
Main Site is Down

### ISSUE THREAD

**Issue by thatsgolden** [axios/axios#6215]
### Describe the issue

Can not access https://axios-http.com

![image](https://github.com/axios/axios/assets/96641851/071b0876-d0b6-4448-871e-b59d6979369f)

![image](https://github.com/axios/axios/assets/96641851/7bdf844c-5861-414e-859b-309aca603b84)

**Comment by DigitalBrainJS** [comment]
This should be fixed soon. As far as I know, there was some payment issue when automatically renewing a domain.

**Comment by jasonsaayman** [comment]
should be fixed, if not pls wait for domain propogation
