### ISSUE TITLE
0.28.0 reported as latest version

### ISSUE THREAD

**Issue by Coding-Kiwi** [axios/axios#6228]
### Describe the bug

Running npm outdated gives

![image](https://github.com/axios/axios/assets/5007641/6dca01b9-5d65-4a5f-965b-c6e2d44ce8f2)

because 0.28.0 is indeed the latest version

![image](https://github.com/axios/axios/assets/5007641/1a5a4d69-77b2-4d91-9037-452cb683d682)

but this also means when I create a new project and run `npm i axios` I get 0.28.0 instead of 1.1.7

does not seem right...

**Comment by DigitalBrainJS** [comment]
Fixed. This seems to be npm's default behavior when publishing, which is rather odd in my opinion.
