### ISSUE TITLE
Axios Modifies ID Field in JSON Response When Nested Inside Projects Array

### ISSUE THREAD

**Issue by amarkpc** [axios/axios#6249]
### Describe the bug

I've encountered an issue with Axios where it appears to be modifying the id field in a JSON response when the id field is nested inside a projects array. This behavior is unexpected and causes inconsistency in handling JSON responses.

### To Reproduce

Steps to Reproduce:

1. Make a GET request to an API endpoint using Axios.
2. Ensure that the response contains a projects array with an id field nested inside.
3. Log the response data to the console.
Expected Behavior:
The id field within the projects array should remain unchanged and match the original value in the JSON response.

Actual Behavior:
Axios appears to modify the id field within the projects array. For example, if the original id value is 123, Axios may convert it to 124 or another modified value.

### Code snippet

```js
const axios = require('axios');

axios.get('https://example.com/api/projects')
  .then(response => {
    console.log(response.data);
  })
  .catch(error => {
    console.error('Error:', error);
  });
```

### Axios Version

1.4.0

### Node.js Version

20.01, 16

### OS

ubuntu 22

**Comment by TechnoAnkush** [comment]
getting this same issue

**Comment by huzaifaazim0** [comment]
can you guys share the orignal json and  response object
i was looking into it. and can't reproduce
