### ISSUE TITLE
What is the correct version guide of Axios?

### ISSUE THREAD

**Issue by markcorrea** [axios/axios#6294]
### Describe the issue

I am upgrading all libraries from my project and would like to upgrade Axios as well. 
npm shows me that the latest version is `1.6.7`, and allows me to install this version. 
However, GitHub shows me that the latest version is `0.28.0`.
Inside `axios-http` page, I didn't find any version guides, besides the sentence:

```
Until axios reaches a 1.0 release, breaking changes will be released with a new minor version. For example 0.5.1, and 0.5.4 will have the same API, but 0.6.0 will have breaking changes.
```

Can you please enlighten me which is the real latest version, and where can I guide myself about it?

**Comment by MiladSadeghi** [comment]
@markcorrea You should check [npm website](https://npmjs.com) to ensure what the latest version of a package is. like for axios is [axios-page](https://npmjs.com/package/axios)
