### ISSUE TITLE
Security Vulnerability from follow-redirects

### ISSUE THREAD

**Issue by Phoenix-Alpha** [axios/axios#6298]
### Describe the bug

`pnpm audit` reports security vulnerability from `follow-redirects@1.15.5` which is currently in dependency list [here](https://github.com/axios/axios/blob/v1.x/package.json#L149)

Link to security vulnerability below:
https://github.com/advisories/GHSA-cxjh-pqwp-8mfp

Possible solution:
Please revamp follow-redirects to patched version(1.15.6)

### Axios Version

1.6.7

**Comment by thienandangthanh** [comment]
This issue can be closed now.
The related fix #6300 for this has been published in [v1.6.8](https://github.com/axios/axios/releases/tag/v1.6.8) release.
