### ISSUE TITLE
Invalid package attestation - 1.6.8

### ISSUE THREAD

**Issue by shadaxv** [axios/axios#6308]
### Describe the bug

An npm audit indicates incorrect package attestation in version 1.6.8:

```
npm audit signatures
audited 1665 packages in 20s

1663 packages have verified registry signatures

14 packages have verified attestations

2 packages have invalid attestations:

axios@1.6.8 (https://registry.npmjs.org/)
ts-api-utils@1.3.0 (https://registry.npmjs.org/)

Someone might have tampered with these packages since they were published on the registry!
```

### To Reproduce

- Install axios@1.6.8
- Run `npm audit signatures`

### Expected behavior

Audit does not indicate invalid attestation

### Axios Version

1.6.8

### Node.js Version

20.11.0

### Additional Library Versions

```bash
npm 10.4.0
```

**Comment by lvass74** [comment]
Just hit the same issue with npm 10.2.3.
With npm 10.5.0 the issue is not present.
Nor with npm 9.8.x

**Comment by shadaxv** [comment]
@lvass74 In my case, the problem also occurs in npm version 10.5.0

![image](https://github.com/axios/axios/assets/22190585/f5805ab4-7eda-4d8c-9802-38ff8d70f5ef)

**Comment by shadaxv** [comment]
@lvass74 Good catch, I used the new version of node, but actually I did not use the new version of npm, in version 10.5.0 there is no problem, looks like a problem on the side of npm. Thank you @lvass74, I close the thread
