### ISSUE TITLE
CSRF Token Mismatch

### ISSUE THREAD

**Issue by rcapulsuhay** [axios/axios#6336]
### Describe the bug

When using v1.6.8, I'm encountering CSRF Token Mismatch in Laravel Sanctum. I saw from this forum [](https://stackoverflow.com/a/77498494)
that axios must downgrade to v1.3.3 and now everything is working.

### Code snippet

```js
export const http = axios.create({
  withCredentials: true,
  baseURL: HOST,
})

Login code
await http.get(API.CSRF_TOKEN);
const res = await http.post(API.LOGIN, data);
```

### Axios Version

1.6.8

### Browser

any

### Browser Version

latest

### Node.js Version

21.7.1

### OS

windows

**Comment by justindhillon** [comment]
If this is a regression in the code, it would be in this file:

https://github.com/axios/axios/blob/v1.x/lib/adapters/xhr.js

**Comment by justindhillon** [comment]
These are all the commits between v1.3.3 and v1.6.8:

https://github.com/axios/axios/commit/bbb61e70cb1185adfb1cbbb86eaf6652c48d89d1
https://github.com/axios/axios/commit/bc9af51b1886d1b3529617702f2a21a6c0ed5d92
https://github.com/axios/axios/commit/96ee232bd3ee4de2e657333d4d2191cd389e14d0
https://github.com/axios/axios/commit/3dc8369e505e32a4e12c22f154c55fd63ac67fbb
https://github.com/axios/axios/commit/dd465ab22bbfa262c6567be6574bf46a057d5288
https://github.com/axios/axios/commit/cff996779b272a5e94c2b52f5503ccf668bc42dc

**Comment by rcapulsuhay** [comment]
> If this is a regression in the code, it would be in this file:
> 
> https://github.com/axios/axios/blob/v1.x/lib/adapters/xhr.js

i have added the withXSRFToken now it's working now, thank you

**Comment by justindhillon** [comment]
No worries! Any time @rcapulsuhay !
