### ISSUE TITLE
[fatal][nodejs] “Error: Unexpected end of form” after multiple post file formdata, and then hang up after multiple error happening

### ISSUE THREAD

**Issue by luoxzhg** [axios/axios#6338]
### Describe the bug

“Error: Unexpected end of form” after multiple post file formdata, 
and then hang up after multiple error happening

server using multer v1.4.5-lts accepts files, raise this error. uploading file with other tool (jmeter) no such errors

![图片](https://github.com/axios/axios/assets/25560573/4221ee22-fffb-4887-8309-2cddc0bce7c9)

### To Reproduce

nodejs v20.10.0
axios v1.6.8 
form-data v4.0.0

```
const axios = Axios.create({
    httpAgent: new http.Agent({ keepAlive: true, keepAliveMsecs: 30000 }),
    httpsAgent: new https.Agent({ keepAlive: true, keepAliveMsecs: 30000 }),
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
})
```
**response json is big, 20MB**

### Expected behavior

successed request

### Axios Version

1.6.8

### Adapter Version

http

### Node.js Version

20.10

### OS

apline

### Additional Library Versions

```bash
form-data v4.0.0
```

**Comment by luoxzhg** [comment]
tested with v1.6.7, same issue;
v1.6.6, much less error than v1.6.7, v1.6.8, and never hang up

**Comment by luoxzhg** [comment]
v1.6.6 raise some new Error
```
=====================>>> Tue Apr 02 2024 10:21:24 GMT+0000 (Coordinated Universal Time)
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at Axios.request (/app/server/node_modules/.pnpm/axios@1.6.6_debug@4.3.4/node_modules/axios/dist/node/axios.cjs:3886:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _extractText (/app/server/src/apis/extract-text.js:42:22)
    at async Object.extractTextWithPosition (/app/server/src/apis/extract-text.js:60:24)
    at async extractTextWithPosition (/app/server/src/lib/extract-text.js:43:22)
    at async /app/server/src/v3/router.js:111:17
<<<=====================
```

**Comment by luoxzhg** [comment]
this is my mistake. multiply threads read/write same file casue this.

**Comment by Asmi-CTL** [comment]
What was solution here. i am getting same error with fetch
