### ISSUE TITLE
RefferenceError: Axios is not defined.

### ISSUE THREAD

**Issue by ScottDurkin** [axios/axios#6350]
### Describe the bug

I am debugging my code and on refresh, axios stopped working. I thought there was a problem in my code but when I went to my live server application, I get the same error.

Reference I am using (for the past 2 years)
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

![image](https://github.com/axios/axios/assets/24443043/77e6cc32-48c2-4db2-858b-6347a3bc798d)

### To Reproduce

Open web application that uses axios with this script include.
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

### Code snippet

```js
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
```

### Expected behavior

axios api calls should be working.

### OS

WIndows 10

**Comment by ScottDurkin** [comment]
unpkg.com seems to be offline.
![image](https://github.com/axios/axios/assets/24443043/365b59ab-b6d5-40e3-ae46-d4148e5de296)

**Comment by maddyexplore** [comment]
<script src="https://cdn.jsdelivr.net/npm/axios@1.6.7/dist/axios.min.js"></script> works
