### ISSUE TITLE
XSRF-TOKEN logic should utilize cookie domain instead of current page domain

### ISSUE THREAD

**Issue by literallyjustroy** [axios/axios#6363]
### Is your feature request related to a problem? Please describe.

When using `axios` to make HTTP calls to a backend server from a ui hosted at a different subdomain, the XSRF-TOKEN logic is not available and requires manually parsing out the cookie and passing the X-XSRF-TOKEN header yourself. This is because the logic that currently exists checks to see if the full domain of the page you're currently on matches the full domain of the api you're making a call to. 

https://github.com/axios/axios/blob/ab3f0f9a94853c821cb00f1112788ecdd3ae7ed1/lib/adapters/xhr.js#L191
https://github.com/axios/axios/blob/ab3f0f9a94853c821cb00f1112788ecdd3ae7ed1/lib/helpers/isURLSameOrigin.js#L55-L59

### Describe the solution you'd like

Instead of matching against the current page and the target api url, this logic could match the target api url against the XSRF-TOKEN cookie domain. Since the XSRF-TOKEN cookie will be sent along with the request to this domain regardless, there should no problem in also pulling out the cookie value and passing it as the X-XSRF-TOKEN header. 

### Describe alternatives you've considered

The alternative having the developer utilizing axios ensure that each axios call to the backend domain passes the withXSRFToken config as true, or building this logic into a withXSRFToken function config that does the cookie/target domain match itself.

### Additional context/Screenshots

Having static files for a Single-page Application (React) hosted via a CDN at a different domain than the backend is a relatively common practice which would benefit from this change.

**Comment by literallyjustroy** [comment]
The answer is because you **can't** get the cookie domain via javascript 🙃

**Comment by kentrh** [comment]
@literallyjustroy Hi, I was wondering if you had come up with good solution on how to deal with this when the api and the client app is hosted on different subdomains? Feels like a waste doing this manually when axios has the functionality..

**Comment by literallyjustroy** [comment]
@kentrh I ended up writing an axios request interceptor for this. If the current page base domain is the same as the domain of the requested url, we pass the header (and cookie via withCredentials!) along in the request. There's a note in there that if you're doing this for some generic library you should probably handle country-code second-level domains correctly. If you're not running your site/server on any of those domains, it doesn't matter.

```typescript
/**
 * Intercept requests and enable XSRF-TOKEN handling in axios if the request is an "unsafe method" and the SLD and
 * TLD of the current page url match the SLD and TLD of the request url. This doesn't handle country-code second-level
 * domains (e.g. company.co.uk) properly, in order to do this you should use a library to properly parse the domains.
 * Since we don't use any country-code second-level domains, and have proper content policies in place, we don't care!
 */
const xsrfTokenRequestInterceptor: RequestInterceptor = (request) => {
  try {
    const method = request.method?.toLowerCase();

    const methodRequiresCSRFProtection = method !== undefined && ['post', 'put', 'delete', 'patch'].includes(method);

    const parsedCurrentURL = new URL(window.location?.href);
    const parsedTargetURL = new URL(axios.getUri(request));

    const currentHostname = parsedCurrentURL.hostname.split('.').slice(-2).join('.');
    const targetHostname = parsedTargetURL.hostname.split('.').slice(-2).join('.');
    const baseDomainsMatch = currentHostname === targetHostname;

    // If settings are explicitly passed, use them, otherwise apply logic as determined by domain match
    if (request.withXSRFToken === undefined) {
      request.withXSRFToken = baseDomainsMatch && methodRequiresCSRFProtection;
    }

    if (request.withCredentials === undefined) {
      request.withCredentials = baseDomainsMatch;
    }
  } catch (error: any) {
    console.error('Skipping XSRF-TOKEN header logic in interceptor: ', error);
  }

  return request;
};

// Utilized like the following:
const instance = axios.create(finalAxiosConfig);
instance.interceptors.request.use(xsrfTokenRequestInterceptor);
```

**Comment by kentrh** [comment]
@literallyjustroy This is perfect! Thank you, kind sir! 👏
