### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype')  at node_modules/follow-redirects/index.js

### ISSUE THREAD

**Issue by cenkce** [axios/axios#6368]
### Describe the bug

`Cannot read properties of undefined (reading 'prototype') at node_modules/follow-redirects/index.js`

The error is happening with yarn 3 and vite.

```
// istanbul ignore next
var destroy = Writable.prototype.destroy || noop;
```

### To Reproduce

Run with yarn version 3.8.1

### Axios Version

1.16.

### Browser

All

### Browser Version

*

### Node.js Version

18

### OS

Macos

### Additional Library Versions

```bash
"vite": "^4.3.1",
"typescript": "^4.7.4",
"react": "^18.0.0",
```

**Comment by cenkce** [comment]
Sorry it was a configuration issue

**Comment by liuhq8796** [comment]
Hi @cenkce, may I ask how you resolved it?

**Comment by LeemSunMi** [comment]
Hello, @cenkce 
I am facing the same problem.
Could you please give me a solution?

**Comment by swy0710** [comment]
Hello, @cenkce,
I am facing the same problem.
Could you please give me a solution?
