### ISSUE TITLE
`fetch` adapter: handling of network errors different from `xhr`

### ISSUE THREAD

**Issue by glsignal** [axios/axios#6374]
### Describe the bug

Hello! First up: thank you for the work to include a fetch adapter in axios, this is fantastic ❤️ 

I noticed a (potential) issue, or at least a difference in behaviour, when switching adapters around the production of ERR_NETWORK. 

Glancing at the fetch adapters code, it looks like the issue comes from the `if (err.name === 'NetworkError') {` check, which works with XHR but fetch rejects with a `TypeError` with `Failed to fetch` as the message. It might just be a matter of swapping the strings, in which case that's straight forward.

What I wasn't sure about, is how wide that "Failed to fetch" scope is (MDN only describes the exception _class_), and whether it overlaps with any of the [other error types that are listed](https://github.com/axios/axios/blob/v1.x/README.md#error-types). MDN documents a [number of failure modes for this TypeError](https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions), which may complicate things.

Happy to help/open a PR when needed, though I'd like to iron out the uncertainty around the error modes first

### To Reproduce

https://github.com/glsignal/scratch-axios-network-error or https://codesandbox.io/p/github/glsignal/scratch-axios-network-error/main

### Code snippet

```js
import { beforeAll, afterAll, describe, expect, it } from "vitest";

import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";

import axios, { AxiosError } from "axios";

const server = setupServer();

beforeAll(() => {
  server.listen();
});

afterAll(() => {
  server.close();
});

describe("error events", () => {
  async function buildNetworkError(adapter) {
    server.use(http.get("/test", () => HttpResponse.error()));

    try {
      return await axios.get("http://localhost/test", { adapter });
    } catch (event) {
      return event;
    }
  }

  describe("using xhr adapter", () => {
    it("indicates that it is a network error", async () => {
      const error = await buildNetworkError("xhr");

      expect(error.code).toEqual(AxiosError.ERR_NETWORK);
    });
  });

  describe("using fetch adapter", () => {
    it("indicates that it is a network error", async () => {
      const error = await buildNetworkError("fetch");

      expect(error.code).toEqual(AxiosError.ERR_NETWORK);
    });
  });
});
```

### Expected behavior

I'd expect `error.code` to equal `AxiosError.ERR_NETWORK` with both adapters.

### Axios Version

1.7.0-beta.0

### Adapter Version

fetch

**Comment by DigitalBrainJS** [comment]
Yes, it wouldn't be easy. Errors causes are not standardized, they are different in browser/node(undici/cross-fetch/etc)/ReactNative.
Writing an error parser for each platform can hardly be called an acceptable solution, especially since there are no guarantees that there are no differences between versions. For now, I'm inclined to map all these errors to `ERR_NETWORK`. Maybe someone will come up with a better solution.

P.S. Thanks for the test example & repo. It's rare to see such a well-filled issue. ❤️
