### ISSUE TITLE
Axios somthing question about version.

### ISSUE THREAD

**Issue by Ryong9** [axios/axios#6384]
### Describe the issue

Hi there, I have a question.

How long axios version 0.x will be upgrade supported?

Do you support version upgrades for 0.x version by next year regarding vulnerability improvement?

Thank you.

**Comment by Ryong9** [comment]
I'm sorry. My explanation was insufficient.
I plan to use version 0.x of axios until 2025, and I wrote a question because I wanted to know if upgrades to version 0.x are supported in relation to vulnerabilities until then.
Currently, it has been confirmed that the tag exists up to version 0.28.1. In relation to this, if vulnerabilities are discovered in the future, I would like to know whether they will continue to upgrade versions after 0.28.1 until next year.

Thank you.

**Comment by jasonsaayman** [comment]
i dont think this is something we really ever locked down, will give it a bit of a think
