### ISSUE TITLE
Why axios return error `ETIMEDOUT` but when I do cURL it's running fine?

### ISSUE THREAD

**Issue by hashfi-motion** [axios/axios#6397]
### Describe the issue

As the title said, when I do the request with cURL on my terminal it's working fine, but when in my Axios it timed out. Why? For more context, this request is to my Telegram bot API.

### Example Code

```ts
public async getMe(): Promise<_types.Telegram.User> {
	let response: AxiosResponse<_types.Telegram.User>;
	let output: _types.Telegram.User;

	try {
		const url = this.baseURL + '/getMe';
		response = await axios.get<_types.Telegram.User>(url, { timeout: 1000000000 });
	} catch (error) {
		throw error;
	}

	output = response.data;
	return output;
}
```

### Expected behavior

Running fine without error time out.

### Axios Version

1.6.7

### Node.js Version

20.10.0

### OS

Debian GNU/Linux 10 (buster)

**Comment by Ali-Bhatti** [comment]
I am also facing the same issue

**Comment by Vilya2** [comment]
Me too

**Comment by hashfi-motion** [comment]
For anyone still having same issue with me, double-check if it's Axious related issue or not by requesting the API with normal fetch (or others). I double-check and all of them have the same problem, I don't exactly why since after the tomorrow the issue fixes itself for some reason when I tried it again. Maybe restart your internet or double-check with your Node, that's my guess anyway. If anyone have an idea what causes this issue, feel free to fill in
