### ISSUE TITLE
v1.7.0 release bug 

### ISSUE THREAD

**Issue by Hyodori04** [axios/axios#6409]
### Describe the bug

After upgrade to 1.7.0 from 1.6.8

` ReferenceError: TextEncoder is not defined`

error happens 

### To Reproduce

upgrade to axios 1.7.0

### Expected behavior

no error happen

### Axios Version

1.7.0

### Adapter Version

xhr

### Node.js Version

20.13.1

**Comment by smg-kayle** [comment]
I have the same issue.
Node version: 18.19.1

**Comment by ifzm** [comment]
+1 (
Return to 1.6.8 normal

**Comment by ddwebdevv** [comment]
My app is crashing now because of this error

**Comment by halil07** [comment]
Tests are not working right now

**Comment by hey-juicy0** [comment]
how can I solve this?

**Comment by halil07** [comment]
> how can I solve this?

Change package.json file with "axios": "1.6.8"

Without ^

**Comment by hey-juicy0** [comment]
> > how can I solve this?
> 
> Change package.json file with "axios": "1.6.8"
> 
> Without ^

it's working!! thank you 😊

**Comment by Tirzono** [comment]
The error `ReferenceError: TextEncoder is not defined` typically occurs when running in a Node.js environment that does not natively support `TextEncoder`. `TextEncoder` is a Web API that may not be available in the Node.js environment unless explicitly polyfilled.

To fix this error in for example Jest, you can add a polyfill for `TextEncoder`. There are a couple of ways to do this:

### Method 1: Polyfill Using `util` from Node.js
Node.js 11 and later versions include `TextEncoder` and `TextDecoder` in the `util` module, which you can use as a polyfill.

1. Install the `util` package if it's not already installed:
   ```bash
   npm install util
   ```

2. Add the polyfill in your Jest setup file (e.g., `setupTests.js`):
   ```javascript
   // setupTests.js
   const { TextEncoder, TextDecoder } = require('util');

   global.TextEncoder = TextEncoder;
   global.TextDecoder = TextDecoder;
   ```

3. Ensure your Jest configuration includes the setup file. In your `jest.config.js`, add the following:
   ```javascript
   module.exports = {
     // other configuration options...
     setupFilesAfterEnv: ['<rootDir>/setupTests.js'],
   };
   ```

### Method 2: Polyfill Using `text-encoding` Package
Another approach is to use the `text-encoding` package to provide a polyfill for `TextEncoder`.

1. Install the `text-encoding` package:
   ```bash
   npm install text-encoding
   ```

2. Add the polyfill in your Jest setup file (e.g., `setupTests.js`):
   ```javascript
   // setupTests.js
   const { TextEncoder, TextDecoder } = require('text-encoding');

   global.TextEncoder = TextEncoder;
   global.TextDecoder = TextDecoder;
   ```

3. Ensure your Jest configuration includes the setup file. In your `jest.config.js`, add the following:
   ```javascript
   module.exports = {
     // other configuration options...
     setupFilesAfterEnv: ['<rootDir>/setupTests.js'],
   };
   ```

By adding one of these polyfills, you should be able to resolve the `ReferenceError: TextEncoder is not defined` error in your Jest tests.

**Comment by ddwebdevv** [comment]
for me it's not Jest.
I'm using react native( expo). One of my dependencies using axios. And since update I can't run anything because of this error. And we are building in a cloud.
And adding text-encoding or text-encoding-polyfill didn't help.
In previous versions we didn't have this error.

**Comment by huyhua-nvg** [comment]
Not a jest problem, nor a node problem. But rather a jsdom test environment problem.
https://github.com/jsdom/jsdom/issues/2524
