### ISSUE TITLE
v1.7.0 release bug

### ISSUE THREAD

**Issue by divyam567** [axios/axios#6412]
### Describe the bug

After upgrade to 1.7.0 from 1.6.8, Getting the following error:

node_modules/remote-content/node_modules/axios/dist/node/axios.cjs:3791
})(new Response));
   ^
TypeError: Response is not a constructor

### To Reproduce

upgrade to axios 1.7.0

### Expected behavior

no error happen

### Axios Version

1.7.0

### Node.js Version

v16.20.2 (npm v8.19.4)

### Additional context/Screenshots

downgrading to 1.6.8 resolves the issue

**Comment by DigitalBrainJS** [comment]
I can't reproduce the issue on v16.20.2 

```js
const axios = require('axios');

(async () => {
  console.log(process.version);

  try {
    const res = await axios.get('https://dummyjson.com/products/1', {
      adapter: 'fetch'
    })

    console.log(`Done:`, res.data);
  } catch (e) {
    console.log(`Fail: ${e} (${e.code})`);
  }
})();
```

```
v16.20.2
Fail: AxiosError: There is no suitable adapter to dispatch the request  - adapter fetch is not supported by the environment (ERR_NOT_SUPPORT)

Process finished with exit code 0
```

**Comment by kumaraswamyDR** [comment]
We are encountering the same issue. Since this dependency is an internal part of another library, downgrading is not an option for us.
