### ISSUE TITLE
Invalid characters when making a request to an ISO-8859-1 endpoint

### ISSUE THREAD

**Issue by mauriciosantosds** [axios/axios#6418]
### Describe the bug

I have an API in nodejs that is using AXIOS to make https requests to an API that uses ISO-8859-1 encoding. I'm having problems with character encoding, the word ação arrives on the server that uses ISO like this: aÃ§Ã£o

I'm making the request this way:

`import FormData from "form-data";
import fs from "fs";
import path from "path";

const requestData = new FormData();
requestData.append("relatorio", "ação", {contentType: "ISO-8859-1", header: {"Content-type": "ISO-8859-1"}});

const tmpDir = os.tmpdir();
const extensao = "png";
const timestamp = Date.now();
const filepath = path.join(tmpDir, `${timestamp}.${extensao}`);

if (!fs.existsSync(tmpDir)) {
  fs.mkdirSync(tmpDir);
}

const datab64 = data.assinatura.replace(/^data:image\/\w+;base64,/, "");
const buff = Buffer.from(datab64, "base64");
fs.writeFileSync(filepath, buff);

requestData.append("assinatura", fs.createReadStream(filepath));
const result =
await axios.postForm("http://172.1.2.23/api/update-os", requestData, {
  headers: {
    "Content-Encoding": "ISO-8859-1",
    "Content-Type": "multipart/form-data",
  },
});
fs.unlinkSync(filepath);
console.log(result);`

### To Reproduce

import FormData from "form-data";
import fs from "fs";
import path from "path";

const requestData = new FormData();
requestData.append("relatorio", "ação", {contentType: "ISO-8859-1", header: {"Content-type": "ISO-8859-1"}});

const tmpDir = os.tmpdir();
const extensao = "png";
const timestamp = Date.now();
const filepath = path.join(tmpDir, `${timestamp}.${extensao}`);

if (!fs.existsSync(tmpDir)) {
  fs.mkdirSync(tmpDir);
}

const datab64 = data.assinatura.replace(/^data:image\/\w+;base64,/, "");
const buff = Buffer.from(datab64, "base64");
fs.writeFileSync(filepath, buff);

requestData.append("assinatura", fs.createReadStream(filepath));
const result =
await axios.postForm("http://172.1.2.23/api/update-os", requestData, {
  headers: {
    "Content-Encoding": "ISO-8859-1",
    "Content-Type": "multipart/form-data",
  },
});
fs.unlinkSync(filepath);
console.log(result);

### Code snippet

```js
import FormData from "form-data";
import fs from "fs";
import path from "path";

const requestData = new FormData();
requestData.append("relatorio", "ação", {contentType: "ISO-8859-1", header: {"Content-type": "ISO-8859-1"}});

const tmpDir = os.tmpdir();
const extensao = "png";
const timestamp = Date.now();
const filepath = path.join(tmpDir, `${timestamp}.${extensao}`);

if (!fs.existsSync(tmpDir)) {
  fs.mkdirSync(tmpDir);
}

const datab64 = data.assinatura.replace(/^data:image\/\w+;base64,/, "");
const buff = Buffer.from(datab64, "base64");
fs.writeFileSync(filepath, buff);

requestData.append("assinatura", fs.createReadStream(filepath));
const result =
await axios.postForm("http://172.1.2.23/api/update-os", requestData, {
  headers: {
    "Content-Encoding": "ISO-8859-1",
    "Content-Type": "multipart/form-data",
  },
});
fs.unlinkSync(filepath);
console.log(result);
```

### Expected behavior

The word ação should arrive on the server written correctly as ação.

### Axios Version

1.3.4

### Node.js Version

18.0.0

### OS

Ubuntu 22.04

### Additional Library Versions

```bash
fom-data 4.0.0
```

**Comment by digbijay-geeky** [comment]
Hi,mauriciosantosds
 The Api is not working ,could you please check ,For your ref:-http://172.1.2.23/api/update-os

**Comment by mauriciosantosds** [comment]
Sorry this api was only used as an example url.

**Comment by digbijay-geeky** [comment]
Sure i am trying to check again for this.

**Comment by mauriciosantosds** [comment]
I solved this problem by converting the text to ISO-8859-1 using the Iconv library and sending the result buffer of this conversion to axios.

`
    const iconv = new Iconv("UTF-8", "ISO-8859-1");
    const buffer = iconv.convert(data.relatorio);

    const body = {
      "relatorio": buffer,
      "assinatura": fs.createReadStream(filepath),
    };

    const result =
    await axios.post(`${data.url}/UpdateOS`,
      body, {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });`
