### ISSUE TITLE
Module not found: Can't resolve 'axios' in NEXT14

### ISSUE THREAD

**Issue by Icegreeen** [axios/axios#6430]
### Describe the bug

In my Next14 application, in the service/api.ts folder I am unable to find the axios module.

"axios": "^1.7.1",

![Captura de tela 2024-06-03 140724](https://github.com/axios/axios/assets/56550632/44dddb6e-03ac-442a-9966-221c68def924)

Here I am trying to instantiate the service to access the api:

```
try {
      const response = await api.post('/register', { name, email, password });

      if (response.status === 201) {
        const result = await signIn('credentials', {
          redirect: false,
          email,
          password,
        });

        if (result?.error) {
          setError(result.error);
        } else {
          router.push('/app');
        }
      } else {
        setError(response.data.message || 'Erro no registro, tente novamente.');
      }
    } catch (error: any) {
      console.error('Registration error:', error);
      setError(error.response?.data?.message || 'Erro no registro, tente novamente.');
    }
```

I tried many solutions but still couldn't fix it.

I don't know if it should be something related to the service layer of the next14 router app with axios.

### Axios Version

"axios": "^1.7.1",

**Comment by Icegreeen** [comment]
Even though I installed axios with yarn, after installing with npm it keeps asking to install package after package:

 ⨯ ./node_modules/axios/lib/adapters/http.js:7:1
Module not found: Can't resolve 'proxy-from-env'

**Comment by nicknovoa03** [comment]
I am having the same issue.

**Comment by Icegreeen** [comment]
> I am having the same issue.

This problem is occurring in a Windows environment, I just ignored it and went to Linux, and my application worked normally.

I believe that Windows is unable to route the application, something like that.
