### ISSUE TITLE
Receiving 'maxContentLength size of -1 exceeded' error randomly when firing a request.

### ISSUE THREAD

**Issue by venkatesh-pinninti** [axios/axios#6437]
### Describe the bug

We're initiating a create request to Shopify, and while the server successfully processes the request and creates the resource, our client encounters a 'maxContentLength size of -1 exceeded' error. Attempting to address this, we set the maxContentLength to Infinity, but this merely alters the error message to 'maxContentLength size of Infinity exceeded'.

This issue surfaced subsequent to upgrading our Axios version from 0.22.0 to 1.6.7. In an effort to resolve it, we upgraded further to version 1.7.2, which mitigated the problem to some extent, though errors still occur albeit less frequently.

### Code snippet

```js
Headers that are being used

'Content-Type': 'application/json',
'Accept-Encoding': 'gzip, deflate'
```

### Axios Version

1.7.2

### Adapter Version

HTTP

### Node.js Version

14.12

**Comment by minsixhao** [comment]
I met the same situation. Have you solved the problem

**Comment by Loshkovetska** [comment]
I tried to set Infinity, but it doesn't work

**Comment by minsixhao** [comment]
What is the reason for this

**Comment by sharifzadesina** [comment]
Same, it is not related to maxContentLength, it is probably fired with stream `aborted` event.

Anyways I just switched to `ofetch`, everything is fine again.
