### ISSUE TITLE
no response from axios post

### ISSUE THREAD

**Issue by ktomaszx** [axios/axios#6443]
### Describe the issue

Hi,
axios post method  doesn't return any response.
I have a github action that sends a Teams channel notification. Everything worked fine, messages were sent and suddenly it stopped. No updates, I used the same action version all the time. So I wanted to check what is the issue but turned out that axios is not showing response anymore. 
Previously I was getting
```
{
  status: 200,
  statusText: 'OK',
  headers: Object [AxiosHeaders] {....
```
but now nothing is logged, no error message.
Actually the DEBUG message that I put inside .then section is also not logged.
I tried posting message with curl and it passed. Clearly axios has some issue but I can't find out the reason without any logs.

### Example Code

```js
axios
      .post(msTeamsWebhookUri, messageCard)
      .then(function (response) {
        console.log("DEBUG")
        console.log(response)
      })
      .catch(function (error) {
        core.debug(error)
      })
```

### Expected behavior

I expect to see an error message or server response.

### Axios Version

1.6.8

### Node.js Version

20.13.1

**Comment by Monstarrrr** [comment]
What was the issue ?
