### ISSUE TITLE
Support specifies the `priority` of the request of `fetch` adapter

### ISSUE THREAD

**Issue by huynhducduy** [axios/axios#6448]
### Is your feature request related to a problem? Please describe.

Axios now support `fetch` adapter, but still lacks of the ability to specify the priority of the fetch request. 

Documentation: https://developer.mozilla.org/en-US/docs/Web/API/fetch#priority https://developer.mozilla.org/en-US/docs/Web/API/Request/Request#priority

### Describe the solution you'd like

Add a `priority` attribute in `AxiosRequestConfig` that can only use when `adapter` is `fetch`

### Additional context/Screenshots

```bash
https://web.dev/articles/fetch-priority
```

**Comment by avivkal** [comment]
I am pretty sure that you can already use it, although it doesn't have typing included, an example below:
`    const { data } = await axios.post('url', {}, {
        adapter: 'fetch',
        fetchOptions: {
            priority: 'high'
        }
    });`

**Comment by huynhducduy** [comment]
@avivkal thanks, i didn't check the implementation, it works :D
