### ISSUE TITLE
in safari adapter = 'fetch';请求流时，报错了。message: "ReadableByteStreamController is not implemented"

### ISSUE THREAD

**Issue by panqibao** [axios/axios#6461]
### Describe the bug

message: "ReadableByteStreamController is not implemented"

**Comment by ogunbaysal** [comment]
Are there any updates about it?

**Comment by panqibao** [comment]
no发自我的 iPhone 12 Pro在 2024年7月22日，17:53，Ogün Baysal ***@***.***> 写道：﻿
Are there any updates about it?

**Comment by zhangwentao** [comment]
mark

**Comment by hankyungs** [comment]
Safari browser, I got an error

undefined is not a function (near '...chunk of iterable...') - trackStream.js:21
