### ISSUE TITLE
axios.put("xxx")   !==  axios.("xxx",{method:“put”}) ,  axios.put("xxx") results as "405 Method Not Allowed"

### ISSUE THREAD

**Issue by DragonsZhou** [axios/axios#6471]
In my code, the following two requests get different results, and the second request is rejected because of "405 Method Not Allowed"
![image](https://github.com/axios/axios/assets/49547352/4c678fc5-0eef-4202-9ba6-9f1ecd7dc1db)

This problem seems to be mentioned in "#4227" as well, but I don't know why.

**Comment by DragonsZhou** [comment]
I don't know if it's caused by what you said about this problem, but in my code, the following two requests get different results, and the second request is rejected because of "405 Method Not Allowed"
![image](https://github.com/axios/axios/assets/49547352/4c678fc5-0eef-4202-9ba6-9f1ecd7dc1db)

**Comment by DragonsZhou** [comment]
I don't know if it's caused by what you said about this problem, but in my code, the following two requests get different results, and the second request is rejected because of "405 Method Not Allowed"
![image](https://github.com/axios/axios/assets/49547352/4c678fc5-0eef-4202-9ba6-9f1ecd7dc1db)

**Comment by Suall1969** [comment]
There is no `axios.put(url[, config])` signature only `axios.put(url[, data[, config]])`.
You need to do this instead:
```js
axios.put('/xxxxx', {}, {
    headers: {
        'Content-Type': 'application/json;charset=UTF-8'
    }
}.then(res => {
    console.log(res.data)
})
```

**Comment by DragonsZhou** [comment]
> There is no `axios.put(url[, config])` signature only `axios.put(url[, data[, config]])`. You need to do this instead:
> 
> ```js
> axios.put('/xxxxx', {}, {
>     headers: {
>         'Content-Type': 'application/json;charset=UTF-8'
>     }
> }.then(res => {
>     console.log(res.data)
> })
> ```

**Comment by DragonsZhou** [comment]
[Suall1969](https://github.com/Suall1969) thanks for you help；
