### ISSUE TITLE
Unable to set or override global headers

### ISSUE THREAD

**Issue by speasley** [axios/axios#649]
I'm using Vue 2.1.8 and am trying to set an Authorization header:

```
axios.defaults.headers.common['Authorization'] = 'Basic xxxxxxxxxxxx'
console.log(axios.defaults.headers.common)
```

Output: `Object {Accept: "application/json, text/plain, */*"}`

If I try to alter the Accept header, it remains unchanged.

**Comment by learntoswim** [comment]
I cam here because I'm also having problems changing the default headers after they've been set globally, although; I'm using [vue-axios](https://github.com/imcvampire/vue-axios) @ `^1.2.2`, and Vue @ `2.1.8` and can confirm:

```
axios.defaults.headers.common.Authorization = 'Bearer xxxxx';
console.log(axios.defaults.headers.common.Authorization);
```

Results in `Bearer xxxxx` in my console.

Perhaps try with `vue-axios`?

**Comment by fallenner** [comment]
Me too

**Comment by Chathula** [comment]
give a try by creating a instance...

```javascript
// Set config defaults when creating the instance
var instance = axios.create({
  baseURL: 'https://api.example.com'
});

// Alter defaults after instance has been created
instance.defaults.headers.common['Authorization'] = AUTH_TOKEN;
```

**Comment by xAockd** [comment]
Have the same problem. Solved it by creating new file axios.js and import me instead of global.

`import axios from 'axios';

export default axios.create({
    headers: {
        'X-CSRF-TOKEN': '...',
        'X-Requested-With': 'XMLHttpRequest'
    }
});`

**Comment by jacobarriola** [comment]
This worked for me, should anyone need a bit more guidance 👍 

```javascript
import axios from 'axios'

export default () => {
  return axios.create({
    baseURL: 'http://localhost:4444/',
    headers: {
      'Authorization': `Bearer ${localStorage.getItem('user-token')}`
    }
  })
}
```

**Comment by robaxelsen** [comment]
Thanks for sharing your working solution, @jacobarriola. That seems to solve this issue.

**Comment by pekosoG** [comment]
@robaxelsen im not quite sure of how to use your approach, could you explainme a bit more?

**Comment by robaxelsen** [comment]
@pekosoG I was referring to[ the solution given by jacobarriola](https://github.com/axios/axios/issues/649#issuecomment-360013959). Did you try that?

If you did try, and it didn't help, please provide examples and console output.

**Comment by ChuckkNorris** [comment]
Not totally sure why, but if I set the `Authorization` header in the `axios.create()` function, I was unable to change it at a later time.

I had to initialize the axios instance and set the header separately
```
import axios from 'axios'

const axiosApi = axios.create({
   baseURL: 'http://localhost:5000/'
});

export const setAuthHeader = (token) => {
   axiosApi.defaults.headers.common['Authorization'] = `Bearer ${token}`;
}

// Set the initial header from storage or something (should surround with try catch in actual app)
setAuthHeader(localStorage.getItem('ACCESS_TOKEN'));

export default axiosApi;
```

**Comment by Nedson202** [comment]
This worked for me

        import axios from 'axios';

        export default function setAuthToken(token) {
             const instance = axios.create({
             baseURL: 'http://localhost:4000/'
        })

        instance.defaults.headers.common['Authorization'] = `Bearer ${token}`;
       }

**Comment by isaacghorbani** [comment]
hi guys just include Bearer in the first of token like this:
axios.defaults.headers.common['Authorization'] = "Bearer "+token;

**Comment by hagemann** [comment]
Check out the comment by @agm1984: https://github.com/axios/axios/issues/1346#issuecomment-532463835

Mutating the instance solved it for me.

**Comment by Number77asa** [comment]
@isaacghorbani , any idea why this is needed, instead of `Bearer ${token}`

I've been trying to figure out why Jquery-static is not doing it's job..is it because axios version and babel versions changed or is it a bad jxs configuration? 

Please someone let us know
