### ISSUE TITLE
XHR adapter returns a resolved config on errors

### ISSUE THREAD

**Issue by ValeraS** [axios/axios#6506]
### Describe the bug

Behaviour introduced in #6371 for example here https://github.com/axios/axios/pull/6371/files#diff-2175f7ecc915e8b17c9831b9bbcd0a681759f7227a424964b04ab68e8166dd77R98

### Expected behavior

XHR adapter returns initial config on errors

### Axios Version

1.7.0-1.7.2

### Adapter Version

XHR

**Comment by ValeraS** [comment]
@DigitalBrainJS sorry for the mention, you changed it. Could you tell, was this intentional or by mistake?

**Comment by DigitalBrainJS** [comment]
This was done intentionally as it was assumed that simple config normalization would not introduce any real breaking changes, however, the decision is debatable. On the one hand, we have the initial config, on the other, we have the final config with which the request was executed. Both approaches have pros and cons.
If this leads to incompatibilities, it should be considered a regression bug and fixed for the current major version. It depends on community feedback.

**Comment by ValeraS** [comment]
`axios-retry` uses the configuration from the error to retry the request, the resolved configuration in the error results in duplicated parameters in the URL.

https://github.com/softonic/axios-retry/issues/280

**Comment by ValeraS** [comment]
And the fetch adapter returns the initial config

**Comment by DigitalBrainJS** [comment]
Ok. Then this needs to be fixed anyway.
