### ISSUE TITLE
Typo in PT-BR version @ https://axios-http.com/ptbr/docs/req_config

### ISSUE THREAD

**Issue by dlgiovani** [axios/axios#6528]
### Section/Content To Improve

![image](https://github.com/user-attachments/assets/e9bbee4a-b58d-42c7-bcb9-c803cfba93b1)
As you can see, it is written "headres" instead of "headers" at the end of the second line on the printscreen.

### Suggested Improvement

Fixing the typo from "headres" to "headers" is enough.

**Comment by GustaGabe** [comment]
Can you assign to me?
