### ISSUE TITLE
Probably an error in the utm tag

### ISSUE THREAD

**Issue by Slotozilla-UK** [axios/axios#6529]
### Describe the bug

We paid for sponsorship through opencollective.com, our banner has been published but it has an error, the link to go to gives a 404 error, we would like you to fix this.

The link provided in our profile works, we assume the problem is on your side.

There might be an error in the utm tag
1)
![image](https://github.com/user-attachments/assets/cb4dcdcd-1c62-41a5-ba1d-61157e918c08)
2)
![image](https://github.com/user-attachments/assets/51e5b471-a97b-4396-9546-f7373854c7fc)

### Code snippet

```js
<a href="https://www.slotozilla.com/de/ utm_source=axios&amp;utm_medium=sponsorlist&amp;utm_campaign=sponsorship" target="_blank">
```

**Comment by DigitalBrainJS** [comment]
Fixed. We have disabled the automatic generation of utm parameters for your account as it appears that your site does not support them. Thanks for your support!

**Comment by Slotozilla-UK** [comment]
> Fixed. We have disabled the automatic generation of utm parameters for your account as it appears that your site does not support them. Thanks for your support!

Thanks)))
