### ISSUE TITLE
Running in Nodejs environment, all Post requests return an error code as 400 error message

### ISSUE THREAD

**Issue by LifeActor** [axios/axios#6535]
### Describe the bug

this is logs:
Error: AxiosError: Request failed with status code 400
    at settle (E:\Ai_Client\backEndForAI\node_modules\axios\dist\node\axios.cjs:2015:12)
    at IncomingMessage.handleStreamEnd (E:\Ai_Client\backEndForAI\node_modules\axios\dist\node\axios.cjs:3131:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (E:\Ai_Client\backEndForAI\node_modules\axios\dist\node\axios.cjs:4262:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: '*/*',
      'Content-Type': 'application/json',
      'Accept-Language': 'en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7',
      Connection: 'keep-alive',
      DNT: '1',
      Origin: 'https://chat.deepseek.com',
      Referer: 'https://chat.deepseek.com/coder',
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Site': 'same-origin',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
      authorization: 'Bearer e4cc8ccaa24c4c748465a3b746d11f15',
      'sec-ch-ua': '"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Windows"',
      'x-app-version': '20240126.0',
      'Content-Length': '103',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'https://chat.deepseek.com/api/v0/chat/completions',
    data: '{"message":"hello","stream":true,"model_preference":null,"model_class":"deepseek_code","temperature":0}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '103',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _closeAfterHandlingError: false,
      _events: [Object],
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _eventsCount: 6,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      timeout: 4000,
      parser: null,
      _httpMessage: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 4000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 236,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 22,
        [Symbol(triggerId)]: 20
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST https://chat.deepseek.com/api/v0/chat/completions HTTP/1.1\r\n' +
      'Accept: */*\r\n' +
      'Content-Type: application/json\r\n' +
      'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7\r\n' +
      'Connection: keep-alive\r\n' +
      'DNT: 1\r\n' +
      'Origin: https://chat.deepseek.com\r\n' +
      'Referer: https://chat.deepseek.com/coder\r\n' +
      'Sec-Fetch-Dest: empty\r\n' +
      'Sec-Fetch-Mode: cors\r\n' +
      'Sec-Fetch-Site: same-origin\r\n' +
      'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36\r\n' +
      'authorization: Bearer e4cc8ccaa24c4c748465a3b746d11f15\r\n' +
      'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"\r\n' +
      'sec-ch-ua-mobile: ?0\r\n' +
      'sec-ch-ua-platform: "Windows"\r\n' +
      'x-app-version: 20240126.0\r\n' +
      'Content-Length: 103\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'host: chat.deepseek.com\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: 'https://chat.deepseek.com/api/v0/chat/completions',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'https://chat.deepseek.com/api/v0/chat/completions',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 14,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '127.0.0.1',
    protocol: 'http:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 103,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://chat.deepseek.com/api/v0/chat/completions',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'accept-language': [Array],
      connection: [Array],
      dnt: [Array],
      origin: [Array],
      referer: [Array],
      'sec-fetch-dest': [Array],
      'sec-fetch-mode': [Array],
      'sec-fetch-site': [Array],
      'user-agent': [Array],
      authorization: [Array],
      'sec-ch-ua': [Array],
      'sec-ch-ua-mobile': [Array],
      'sec-ch-ua-platform': [Array],
      'x-app-version': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: Object [AxiosHeaders] {
      'content-length': '622',
      connection: 'keep-alive',
      'content-type': 'text/html',
      date: 'Sun, 11 Aug 2024 01:07:02 GMT',
      'keep-alive': 'timeout=4',
      'proxy-connection': 'keep-alive',
      server: 'elb'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'https://chat.deepseek.com/api/v0/chat/completions',
      data: '{"message":"hello","stream":true,"model_preference":null,"model_class":"deepseek_code","temperature":0}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '103',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [Socket],
      _header: 'POST https://chat.deepseek.com/api/v0/chat/completions HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7\r\n' +
        'Connection: keep-alive\r\n' +
        'DNT: 1\r\n' +
        'Origin: https://chat.deepseek.com\r\n' +
        'Referer: https://chat.deepseek.com/coder\r\n' +
        'Sec-Fetch-Dest: empty\r\n' +
        'Sec-Fetch-Mode: cors\r\n' +
        'Sec-Fetch-Site: same-origin\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36\r\n' +
        'authorization: Bearer e4cc8ccaa24c4c748465a3b746d11f15\r\n' +
        'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"\r\n' +
        'sec-ch-ua-mobile: ?0\r\n' +
        'sec-ch-ua-platform: "Windows"\r\n' +
        'x-app-version: 20240126.0\r\n' +
        'Content-Length: 103\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'host: chat.deepseek.com\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: 'https://chat.deepseek.com/api/v0/chat/completions',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: '<html>\r\n' +
      '<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>400 Bad Request</h1></center>\r\n' +
      '<center>The plain HTTP request was sent to HTTPS port</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n'
  }
}

### To Reproduce

save the Code to file,
run the 'node filename'

### Code snippet

```js
const axios = require('axios');

const url = 'https://chat.deepseek.com/api/v0/chat/completions';

const headers = {
  'Accept-Language': 'en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7',
  'Connection': 'keep-alive',
  'DNT': '1',
  'Origin': 'https://chat.deepseek.com',
  'Referer': 'https://chat.deepseek.com/coder',
  'Sec-Fetch-Dest': 'empty',
  'Sec-Fetch-Mode': 'cors',
  'Sec-Fetch-Site': 'same-origin',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
  'accept': '*/*',
  'authorization': 'Bearer e4cc8ccaa24c4c748465a3b746d11f15',
  'content-type': 'application/json',
  'sec-ch-ua': '"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-platform': '"Windows"',
  'x-app-version': '20240126.0'
};

const data = {
  message: 'hello',
  stream: true,
  model_preference: null,
  model_class: 'deepseek_code',
  temperature: 0
};

// 发送 POST 请求
axios.post(url, data, { headers })
  .then(response => {
    // 处理响应
    console.log('Response:', response.data);
  })
  .catch(error => {
    // 处理错误
    console.error('Error:', error);
  });
```

### Expected behavior

If the authorization expires, return a reminder of unauthorized status,
If the authorization is valid, a message should be returned from the API interface

### Node.js Version

20.22

### OS

windows 11

### Additional Library Versions

```bash
only axios
```

**Comment by LifeActor** [comment]
Help me, this problem has been bothering me for 144 hours

**Comment by LifeActor** [comment]
the package.json
`{
  "name": "backendforai",
  "version": "1.0.0",
  "description": "A backend for AI project",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js"
  },
  "dependencies": {
    "axios": "^1.7.3",
    "dotenv": "^8.2.0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
`

**Comment by LifeActor** [comment]
@jasonsaayman
@mzabriskie
@DigitalBrainJS

**Comment by LifeActor** [comment]
I used a network data interception tool for debugging, but it did not send data to the target server through the network. Regardless of the content of the URL, it will send HTTP protocol requests to 127.0.0.1, even though your URL uses HTTPS protocol

**Comment by DigitalBrainJS** [comment]
It seems to be not a problem with Axios, but with interactions with the server API. So Stackoverflow is probably the best place to get help.
You can test the request with an http echo service such as `httpbin.org/post` to ensure that Axios is sending exactly what you passed to it.
Currently, the response from the original backend is like:
```
axios 1.7.3
Response: data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":"Hello"},"logprobs":null,"finish_reaso
n":null}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"prompt_cache_hit_tokens":0,"prompt_cache_miss_tokens":0},"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":"!"},"logprobs":null,"finish_reason":null}],"usa
ge":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" How"},"logprobs":null,"finish_reason":null}],"
usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" can"},"logprobs":null,"finish_reason":null}],"
usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" I"},"logprobs":null,"finish_reason":null}],"us
age":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" assist"},"logprobs":null,"finish_reason":null}
],"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" you"},"logprobs":null,"finish_reason":null}],"
usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" today"},"logprobs":null,"finish_reason":null}]
,"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":"?"},"logprobs":null,"finish_reason":null}],"usa
ge":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" If"},"logprobs":null,"finish_reason":null}],"u
sage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" you"},"logprobs":null,"finish_reason":null}],"
usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" have"},"logprobs":null,"finish_reason":null}],
"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" any"},"logprobs":null,"finish_reason":null}],"
usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" questions"},"logprobs":null,"finish_reason":nu
ll}],"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" or"},"logprobs":null,"finish_reason":null}],"u
sage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" need"},"logprobs":null,"finish_reason":null}],
"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" help"},"logprobs":null,"finish_reason":null}],
"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" with"},"logprobs":null,"finish_reason":null}],
"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" something"},"logprobs":null,"finish_reason":nu
ll}],"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":","},"logprobs":null,"finish_reason":null}],"usa
ge":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" feel"},"logprobs":null,"finish_reason":null}],
"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" free"},"logprobs":null,"finish_reason":null}],
"usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" to"},"logprobs":null,"finish_reason":null}],"u
sage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":" ask"},"logprobs":null,"finish_reason":null}],"
usage":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{"content":"."},"logprobs":null,"finish_reason":null}],"usa
ge":null,"request_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}

data: {"id":"cafe9e11-1d0e-4bc0-8c7e-d386801b9211","object":"chat.completion.chunk","created":1723384632,"model":"DeepSeek-Coder-V2","system_fingerprint":"fp_57bc6d0d10","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}],"usage":null,"r
equest_id":"#84ebb515","context_id":14,"chat_id":"deepseek-chatID-5eb127c8-ef97-41a0-b569-7666794c1042"}



Process finished with exit code 0

```

**Comment by LifeActor** [comment]
@DigitalBrainJS Thank you very much for your help. May I ask if the original response was obtained by directly executing the code I provided using version 1.7.3? Or have some fragments been altered?
I raised the same question in the Stackoverflow community, and my friends in the community also experienced this error phenomenon. I tried using the HTTP echo service but also encountered an error. I am preparing to debug the source code of Axios to identify the issue.
I can obtain the correct response using the original XHR request.

**Comment by DigitalBrainJS** [comment]
This is the original code output, no changes have been made. Although the first time I launched it, the backend took a long time to respond with an error in JSON data, unfortunately, I did not save it. After that, he began to respond with some kind of data.

**Comment by LifeActor** [comment]
@DigitalBrainJS Thank you again for your help. Have a pleasant life!

**Comment by luoxzhg** [comment]
> I used a network data interception tool for debugging, but it did not send data to the target server through the network. Regardless of the content of the URL, it will send HTTP protocol requests to 127.0.0.1, even though your URL uses HTTPS protocol

it may be affected by proxy settings.

**Comment by LifeActor** [comment]
yes，Even when the HTTP proxy server supports proxying HTTPS traffic, Axios still throws an error. The issue is resolved and returns to normal when the proxy is disabled.



---Original---
From: "Luo ***@***.***&gt;
Date: Tue, Aug 13, 2024 17:59 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [axios/axios] Running in Nodejs environment, all Post requestsreturn an error code as 400 error message (Issue #6535)




  
I used a network data interception tool for debugging, but it did not send data to the target server through the network. Regardless of the content of the URL, it will send HTTP protocol requests to 127.0.0.1, even though your URL uses HTTPS protocol
  
it may be affected by proxy settings.
