### ISSUE TITLE
TypeError: t is not a function in progressEventReducer.js

### ISSUE THREAD

**Issue by jmthomas** [axios/axios#6549]
### Describe the bug

In Axios 1.7.3 and 1.7.4 I'm seeing the following in the console (no issue in 1.7.2):
```
TypeError: t is not a function
    at progressEventReducer.js:30:5
    at s (throttle.js:20:8)
    at XMLHttpRequestUpload.a (throttle.js:27:7)
```
and
```
TypeError: e is not a function
    at progressEventReducer.js:30:5
    at s (throttle.js:20:8)
    at XMLHttpRequestUpload.a (throttle.js:27:7)
```
depending on how I call it. I assume due to js minifying and name mangling.

### To Reproduce

Not sure exactly how to reproduce as we're calling Axios all over the place with a lot of parameter but I do see there were recent changes to progressEventReducer.js. 

### Axios Version

1.7.3, 1.7.4

### Adapter Version

XML/HTTP

### Browser

Chrome

### Browser Version

latest

### Node.js Version

20

### OS

OS X 14.5

**Comment by jmthomas** [comment]
This may not affect any functionality but we have a test case that is looking for console errors and when we upgraded axios it started failing due to this showing up in the console errors.

**Comment by c032** [comment]
Taking a quick look, seems https://github.com/axios/axios/commit/e3c76fc9bdd03aa4d98afaf211df943e2031453f#diff-2175f7ecc915e8b17c9831b9bbcd0a681759f7227a424964b04ab68e8166dd77L157-R160 modified a check from:

```js
if (typeof _config.onUploadProgress === 'function' && request.upload) {
```

... to:

```js
if (onUploadProgress && request.upload) {
```

The previous `typeof` seems to have (accidentally?) filtered out invalid configs, while the new check would allow passing anything as long as it is truthy.

If somewhere in your code you're using a config with an `onUploadProgress` that is not a function, this would explain why `progressEventReducer` is receiving a `listener` that's not a function, causing the error.

That would be my guess.

**Comment by jmthomas** [comment]
@c032 Thanks for the suggestion! We are indeed passing an empty object `{}` to onUploadProgress by default and then only setting it to a function if we need that functionality. I'll set it to `false` by default instead.
