### ISSUE TITLE
`status` field missing from `AxiosError`

### ISSUE THREAD

**Issue by quangloc99** [axios/axios#6561]
#### Summary

In the [Javascript implementation of `AxiosError`](https://github.com/axios/axios/blob/v1.x/lib/core/AxiosError.js), the `status` is only attached to the `toJson`, but not in the `AxiosError` itself. However, in the [type declaration of `AxiosError`](https://github.com/axios/axios/blob/4f99675fe7eae503422f932b9407242dbc1b7d55/index.d.ts#L416), there is `status?: number` field. Because of this, I have accidentally misused it for quite a while, as it is more obvious and direct than `error.response.status`.

The PR https://github.com/axios/axios/pull/5331 seems to already fix this issue, and it was even approved. But it was not merged. Can axios team merge this, or there is something else that the PR need to resolve?

**Comment by fuadsaud** [comment]
It seems that the issue was resolved in the latest release. It did bite us because we were misusing that field as well and it started causing some problems for us. I guess this could technically have been considered a breaking change.
