### ISSUE TITLE
Can't put File objects in node.js

### ISSUE THREAD

**Issue by hencoappel** [axios/axios#6588]
### Describe the bug

Trying to use axios in our jest tests with the http adapter, openapi generated libraries are now requiring the use of JS File type objects, but when trying to PUT these the http adapter doesn't  accept them, giving the error: 

> AxiosError: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream

A file is just a blob with extra fields so the http adapter should be able to support this.

### Expected behavior

The library should support 

### Axios Version

1.7.7

### Adapter Version

HTTP

### Node.js Version

20.17

**Comment by anshup7** [comment]
Can you please provide repro steps?. It  will help in understanding the issue better!

**Comment by vishvjeet-thakur** [comment]
is this issue resolved? should I work on this?

**Comment by hencoappel** [comment]
With the fix merged, this is completed I believe.
