### ISSUE TITLE
Respecting the robots.txt file

### ISSUE THREAD

**Issue by TechnologyClassroom** [axios/axios#6589]
### Describe the issue

I looked and I did not see anything about robots.txt files in the issues.

I see web traffic on one of the servers I manage claiming to be an Axios user agent `axios/1.7.5` which is requesting pages scraping pages several times a second. Our robots.txt file requests `Crawl-delay: 4` which is either getting ignored or not read. I do not see a request from this IP address to the robots.txt file.

Is Axios checking the robots.txt file and the user is over-riding this behavior or is the robots.txt file not being read intentionally?

### Example Code

```js
Redacted apache log snippet:

REDACTED - - [04/Sep/2024:10:12:02 -0400] "GET REDACTED HTTP/1.1" 200 10884 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:09 -0400] "GET REDACTED HTTP/1.1" 301 185 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:17 -0400] "GET REDACTED HTTP/1.1" 200 9493 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:17 -0400] "GET REDACTED HTTP/1.1" 200 711 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:36 -0400] "GET REDACTED HTTP/1.1" 301 185 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:36 -0400] "GET REDACTED HTTP/1.1" 200 12055 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:36 -0400] "GET REDACTED HTTP/1.1" 200 8914 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:36 -0400] "GET REDACTED HTTP/1.1" 200 9890 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:42 -0400] "GET REDACTED HTTP/1.1" 301 185 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:42 -0400] "GET REDACTED HTTP/1.1" 302 161 "-" "axios/1.7.5"
REDACTED - - [04/Sep/2024:10:12:42 -0400] "GET REDACTED HTTP/1.1" 200 8596 "-" "axios/1.7.5"
```

### Expected behavior

I would expect a crawler to wait 4 seconds between requests.

### Axios Version

1.7.5

**Comment by DigitalBrainJS** [comment]
> Is Axios checking the robots.txt file

No of course. Axios is a request library, not a search robot. It would be strange if Axios, fetch, or curl checked robots.txt before making a request. The user can make any requests from their server to your backend, including replacing the user-agent signature. Protection from unscrupulous clients lies entirely with the backend developers.

**Comment by TechnologyClassroom** [comment]
I've been getting similar responses from other similar tools. I can keep blocking the IPs as I see them and create a rule to ignore requests from the user-agent. This works until they change the user-agent.

**Comment by jasonsaayman** [comment]
Yeah highly doubt this is going to be something we are going to do
