### ISSUE TITLE
Why were utils. isFormData (requestData) removed in version 1. x

### ISSUE THREAD

**Issue by 1264362700** [axios/axios#6592]
### Describe the issue

![image](https://github.com/user-attachments/assets/f15feffa-47cc-408c-ad06-41677cfa7a06)
version 0.9
But in version 1. x, he disappeared。 why？

### Axios Version

1.x

### Adapter Version

xhr

**Comment by DigitalBrainJS** [comment]
It's here https://github.com/axios/axios/blob/5b8a826771b77ab30081d033fdba9ef3b90e439a/lib/helpers/resolveConfig.js#L28-L31

**Comment by 1264362700** [comment]
https://github.com/axios/axios/blob/v1.7.2/lib/defaults/index.js#L53
![image](https://github.com/user-attachments/assets/a3aff807-aec8-44d1-94ad-661c36110a1d)
Why is data of type formData converted to JOSN string in index.js under the default directory. Is this mutually exclusive with utilis.isFormData in resolveConfig
![image](https://github.com/user-attachments/assets/5a2569cf-138c-4d74-95d4-4eb1885c2199)
因为某些历史原因, content-type默认为application/json, 在0.x版本中data类型为formData, axios会把contentType设置为null, 但是在1.x版本中会优先判断content-type类型, 这样有什么好处吗, 为什么不把这段判断放在isFormData之后呢
version: 1.7.2

**Comment by DigitalBrainJS** [comment]
They aren't mutually exclusive. They are not related to each other in any way. This conversion only applies to requests with an explicit content-type set to `application/json`. The valid content type for FormData is `multipart/form-data`, so if the user sets the content type to json for FormData, the form will be serialized to JSON.
The default request content type is `application/x-www-form-urlencoded` for both major versions. In addition, Axios has no default content-type for the response, by default, it just assumes the presence of JSON in the response and tries to parse it despite its content-type header.
