### ISSUE TITLE
How can I have access to the Authorization header inside a request interceptor in Axios?

### ISSUE THREAD

**Issue by joaopedrocoelho** [axios/axios#6598]
### Describe the issue

I have a request interceptor that I want to retrieve the Authorization Header from it but it's returning undefined.

### Example Code

```js
axiosInstance.interceptors.request.use(
    async config => {
        const headers = config.headers;
        console.log('headers' , headers);
        console.log('headers', headers.Authorization);

return config ;
});
```

the first log I can see the Authorization header in the object :

```
headers {
    "Accept": "application/json, text/plain, */*",
    "Authorization": "Bearer  abc123"
}
```

but the second log, Authorization is undefined :

`headers undefined`

I have tried using headers['Authorization'], or the get methods in the object but the result is the same:

```
       console.log(
            'headers',
            headers['Authorization'],
            headers.get('Authorization'),
            headers.Authorization,
            headers.getAuthorization()
        );
```

`headers undefined undefined undefined undefined`

### Expected behavior

To return the `Authorization` header

### Axios Version

1.7.7

### Browser

Chrome

### Browser Version

127.0.6533.100 (Official Build)

### Node.js Version

v20.6.1

### OS

Sonoma 14.1

### Additional Library Versions

```bash
react-query 3.39.3
vite 5.3.4
react 18.3.1
```

**Comment by TarunVishwakarma1** [comment]
Have you tried headers.authorization ? 

Axios internally stores the parameters in lowercase i guess?

**Comment by DigitalBrainJS** [comment]
Can you provide a minimal reproducible example? 
[This all works](https://codesandbox.io/p/sandbox/2p8q27), but direct header access is deprecated.

```js
import axios from "axios";

const axiosInstance = axios.create({});

axiosInstance.interceptors.request.use(async (config) => {
  const headers = config.headers;
  console.log("headers 1", headers);
  console.log("headers 2", headers.Authorization);
  console.log(
    "headers 3",
    headers["Authorization"],
    headers.get("Authorization"),
    headers.Authorization,
    headers.getAuthorization()
  );

  return config;
});

(async () => {
  try {
    const { data } = await axiosInstance.get("https://httpbin.org/bearer", {
      headers: {
        Authorization: "Bearer mytoken",
      },
    });

    console.log(data);
  } catch (err) {
    console.log(err);
  }
})();
```

**Comment by jasonsaayman** [comment]
closing as this seems to have gone stale with no reproducable example
