### ISSUE TITLE
Axios causes error 503 during sending request to next.js (v 14.2.x) API (app router)

### ISSUE THREAD

**Issue by Arshazar** [axios/axios#6604]
### Describe the bug

I tried axios versions 1.7.2 and 1.7.7 in next.js versions 14.2.0, 14.2.7, 14.2.11 and same issue occurs. It used to work until several days ago, but it suddenly stopped working.
I use axios to send requests to the next.js API, but the request doesn't get sent and never reaches APIs! and logs a 503 error.
I used fetch instead, and it worked.

here's my axios api code:

```
import axios, { type AxiosError } from "axios";

const headers: Readonly<Record<string, string | boolean>> = {
  Accept: "application/json",
  "Content-Type": "application/json; charset=utf-8",
  "Access-Control-Allow-Credentials": true,
};

async function handleError(error: AxiosError<never>): Promise<never> {
  return await Promise.reject(error);
}

const api = axios.create({
  headers,
  baseURL: process.env.NEXT_PUBLIC_URL!,
});

api.interceptors.request.use(
  (config) => config,
  async (error) => await Promise.reject(error),
);

api.interceptors.response.use(
  (response) => response,
  async (error) => await handleError(error),
);

export { api };
```

### Expected behavior

It expected to work and not giving 503 error.

### Axios Version

1.7.7

### Adapter Version

HTTP

### Browser

Brave

### Browser Version

1.72.3

### Node.js Version

20.15.1

### OS

Ubuntu 22.04 jammy

### Additional Library Versions

```bash
React 18
Next 14.2.11
```

**Comment by pritam0721** [comment]
Next.js code runs both on the client and server. Axios may be behaving differently in these contexts, especially with respect to environment variables like NEXT_PUBLIC_URL. Ensure that your Axios requests are correctly configured for client-side execution if needed. Try using `typeof window !== "undefined"`  to differentiate between client and server.


`const api = axios.create({
  headers,
  baseURL: typeof window !== "undefined" ? process.env.NEXT_PUBLIC_URL : undefined,
});
`


If it's worked let me know ....

**Comment by Arshazar** [comment]
@pritam0721 I don't use it for client side.

**Comment by Arshazar** [comment]
It didn't work. I decided to go with fetch.
