### ISSUE TITLE
Syntax error on iOS11 or earlier.

### ISSUE THREAD

**Issue by Kenzo-Wada** [axios/axios#6607]
### Describe the bug

There was syntax error on safari browser on ios11 and earlier

```
Unexpected token '...'. Expected a property
```

### To Reproduce

use browserstack or something and access to product using axios

### Axios Version

1.7.7

### Adapter Version

HTTP

### Browser

safari 11

### OS

ios11

**Comment by jasonsaayman** [comment]
🙃 seems that the spread operator is not working in safari which is a bit odd since it should be supported according to can I use, please double check the actual safari version and re-open. if the version is below 9 then you will need to add a build shim
