### ISSUE TITLE
Text getting hidden behind the nav bar 

### ISSUE THREAD

**Issue by ParvamShah1** [axios/axios#6628]
### Is your feature request related to a problem? Please describe.

The navbar is being overlapped on the text on the home page when viewed on small resolution screen or more zoomed in the website.

### Describe the solution you'd like

Will make changes in the styling of the webpage and also make its responsiveness better and also solve the issues. https://github.com/user-attachments/assets/440ca623-aa38-437a-a8e2-cf619996282a

please assign me this issue i want to work on it

**Comment by Light13008** [comment]
i could work on this, 
delete the text or increase the nav bar opacity

**Comment by Sou6161** [comment]
is this issue solved or not let me know? if not then appoint me the issue

**Comment by SauravGupta123** [comment]
Please assign this issue to me. I can fix it in few mintues.

**Comment by jasonsaayman** [comment]
why is everyone asking to be assigned an issue? just put in a PR I will assign it hacktober or whatever

**Comment by SauravGupta123** [comment]
@jasonsaayman  I have a doubt.
I have forked the repo and installed the dependencies. Which script I need to run inorder see the preview of website
https://axios-http.com/ ?

**Comment by DebanganDasgupta** [comment]
can anybody provide the file names to make the necessary changes please.

**Comment by bharateshwq** [comment]
@SauravGupta123 please read the docs before contributing

**Comment by RachitSahu26** [comment]
@SauravGupta123 are you working on this issue if are not working tell me fast i can fix this issue

**Comment by SauravGupta123** [comment]
I am working on it

**Comment by SauravGupta123** [comment]
> @SauravGupta123 please read the docs before contributing

Basically there are two different repos for this.

**Comment by AayushhGoyal** [comment]
assign me to solve this issue
