### ISSUE TITLE
Add margin

### ISSUE THREAD

**Issue by P0Saurabh** [axios/axios#6629]
### Section/Content To Improve

add margin to maintain right distance on load 

### Suggested Improvement

![image](https://github.com/user-attachments/assets/fc7e884f-cc5c-435b-8bde-0db267ff3bf4)

**Comment by Stranger1298** [comment]
assign this issue to me

**Comment by Utsav631** [comment]
I wanna contribute to this, assign this to me.

**Comment by ChandraDevs1** [comment]
@P0Saurabh  can you assign me this issue.

**Comment by Kaif9999** [comment]
hey i wanted to contribute to this issue under hacktoberfest can you assign this to me

**Comment by vijay-kesanakurthi** [comment]
I'd like to take on this issue and contribute to resolving it. Could you please assign it to me?

**Comment by Rishikesh63** [comment]
@P0Saurabh  i would like to solve this issue. could you please assign me

**Comment by abhayofc** [comment]
I have solved this issue, Can I raise a PR?

**Comment by Trishank7409** [comment]
@jasonsaayman could you assignn this to me so i can start working on it

**Comment by Priyanka-Chettri** [comment]
If no one is working on this issue then  can you please assign this to me ?

**Comment by ranpy13** [comment]
A developer who feels the design. Here I am to add value to the project by adding responsive margins that are functionally determined on the basis of current screen size and config. I can write very clean code without affecting the codebase a lot.

**Comment by Priyank-Aggarwal1024** [comment]
Hello sir @P0Saurabh please assign this task to me .
1.)
margin-right :- For main section the right margin is not given 
current margin in main :- 
![current main](https://github.com/user-attachments/assets/a96e794b-e38b-4725-800a-83f38b5bdabb)
change margin in main :- 
![change main](https://github.com/user-attachments/assets/cc8a9c82-f897-4c41-9e35-503300561bbc)
 
2.) In small screen the site is scroll in x-direction
![current site page](https://github.com/user-attachments/assets/8f2c602d-ffde-4734-8be6-f276d0f26672)
When open in small screen it scroll in x direction out of the viewport.

Reason for this is Sponsor Carousel having a class .splide in which -55px margin is given for all devices 

current margin in .splider :-
![current  splide](https://github.com/user-attachments/assets/4d4d9779-afd5-4a71-8bf1-22f5fffbc628)

change margin in .splider :-
![change  splide](https://github.com/user-attachments/assets/3e49782c-5da7-41a9-b2d3-c001cd9c68d1)

**Comment by premprvkvsh** [comment]
@P0Saurabh can you please assign me

**Comment by RahulPrasadYadav** [comment]
assign .

**Comment by narayan123git** [comment]
#Please assign this task to me, I want to work with this.

**Comment by Kuldeepagrahari** [comment]
hello [P0Saurabh](https://github.com/P0Saurabh),
I can handle this issue as i have worked sufficiently on responsiveness earlier, 
please assign this issue to me.
Best regards
Kuldeep Agrahari

**Comment by PritamP20** [comment]
anyone?
