### ISSUE TITLE
Axios mishandles HTTP 204 response: attempts to parse empty body, causing an error

### ISSUE THREAD

**Issue by ben-starnaud** [axios/axios#6639]
### Describe the bug

When making an API call that results in a 204 No Content response, axios incorrectly tries to parse the response body, leading to an error.

According to the HTTP spec, a 204 response should not contain a body. However, axios seems to expect a body and throws an error when the response is empty.

### To Reproduce

1.	Make a GET request using axios to an API endpoint that returns a 204 No Content response.
2.	Observe that axios attempts to parse the response body even though it is empty.

### Code snippet

```js
Version:
axios version 1.7.7

Environment:

• Node.js version: 18.x
• OS: macOS 13.5
```

### Expected behavior

axios should handle 204 No Content responses without attempting to parse the body.

### Axios Version

1.7.7

### Adapter Version

Default

### Browser

Chrome

### Browser Version

118.0.5993.88

### Node.js Version

v18.17.1

### OS

macOS 13.5

### Additional Library Versions

```bash
- Chrome version: 118.0.5993.88
- Axios version: 1.7.7
- Adapter: Default (Node.js `http` adapter)
- Node.js version: 18.17.1
- Operating System: macOS 13.5
```

**Comment by y5c4l3** [comment]
Hi, just curious about what server is reproducible for a 204 response with body. AFAIK Node.js `express` and Golang `gin` both silence the body if the response status is 204.

**Comment by sravanth-space** [comment]
Hi @ben-starnaud, I have tried https://mock.httpstatus.io/204 with Axios and have no issues. Let me know if I am missing something here. https://stackblitz.com/edit/vitejs-vite-iq6upp
![image](https://github.com/user-attachments/assets/a802a283-0fc2-43f7-b8f4-ee0d601a180a)
