### ISSUE TITLE
Params Merge Bug

### ISSUE THREAD

**Issue by suli-1997** [axios/axios#6667]
### Describe the bug

For axios >= 1.2.0. When default params is set. The params merging process is wrong.

### To Reproduce

[https://codepen.io/lililisu1997/pen/gOVXaqX?editors=1111](https://codepen.io/lililisu1997/pen/gOVXaqX?editors=1111)

### Code snippet

```js
// try comment the following line and run again
axios.defaults.params = {};

const s = axios.getUri({
  url: '/tiktok',
  params: {
    region: 'BR',
    Region: 'BR',
  },
})
console.log(s);
```

### Expected behavior

The output should be the same whether the default params is set or not

### Axios Version

1.7.7

**Comment by Aakash-Rana** [comment]
Hello @suli-1997 

I created the PR for this fix : https://github.com/axios/axios/pull/6668
Issue was due to merging params without handling the casing.
