### ISSUE TITLE
getUri ignores paramsSerializer if it is a callback

### ISSUE THREAD

**Issue by rjwats** [axios/axios#6676]
### Describe the bug

When using axios's getUri function with a callback provided to paramsSerializer configuration option, the callback is not respected. 

There is a minimal reproducible code snippet attached to this bug report.

See full example on codesandbox:

https://codesandbox.io/p/sandbox/l4q5g3

### To Reproduce

Create an axios instance and attempt to call getUri with a CustomParamsSerializer callback provided to paramsSerializer.

### Code snippet

```js
const AXIOS = new Axios({});

return AXIOS.getUri({
  url: "https://www.example.com/api",
  params: {hello: "world"},
  paramsSerializer: () => "foo=bar"
});
```

### Expected behavior

URI should be:

https://www.example.com/api?foo=bar

URI is instead: 

https://www.example.com/api?hello=world

### Axios Version

1.7.7

### Browser

Chrome

### Browser Version

130

### Additional Library Versions

```bash
React 18
```

**Comment by guuido** [comment]
maybe i'm wrong but based on what i see in [lib/helpers/buildURL.js](https://github.com/axios/axios/blob/v1.x/lib/helpers/buildURL.js)  

![image](https://github.com/user-attachments/assets/0a0c1294-1046-4c86-86ca-5dcbcbc31a9f)

i think that if your paramsSerializer is a function you should supply it as follows:
```javascript
return AXIOS.getUri({
  url: "https://www.example.com/api",
  params: {hello: "world"},
  paramsSerializer: {
  serialize: () => "foo=bar"
  }
});
```

**Comment by KiddoKidz** [comment]
I faced similar issue when using getUri function with paramsSerializer. I hope the fix can be merge immediately.
