### ISSUE TITLE
Patch 0.x branch to resolve ReDos vulnerability

### ISSUE THREAD

**Issue by lnjbr** [axios/axios#6689]
### Is your feature request related to a problem? Please describe.

The latest 0.x version of Axios should continue to receive updates for non-breaking security vulnerability resolutions. A ReDos vulnerability addressed in issue #6131 and resolved by PR #6132 could be applied to the 0.x branch.

More on the ReDos vulnerability: https://huntr.com/bounties/69a1aa07-c36e-4d9e-9325-b634e0aa4bb0

### Describe the solution you'd like

The solution implemented by PR #6132 should be applied.

### Additional context/Screenshots

```bash
The following line would need to be updated:

https://github.com/axios/axios/blob/6acb5ef8ff127db65da85189b3ccaeb10b93121a/lib/helpers/combineURLs.js#L12
```

**Comment by santhoshbonala1565** [comment]
Our team is using 0.28.1 version which needs this fix as well. Expediting the fix can be helpful.

**Comment by santhoshbonala1565** [comment]
It seems there is an open pr for a long time #6252

**Comment by SanthoshBonala** [comment]
@DigitalBrainJS  Any recommendations on this ?

**Comment by jasonsaayman** [comment]
seems the pr needs a rebase let me see

**Comment by santhoshbonala1565** [comment]
@jasonsaayman  I can create a pr for porting #6132 but it seems I don't have access to create branches on this repo. Can I get permissions ?

**Comment by jasonsaayman** [comment]
fixed will release asap

**Comment by santhoshbonala1565** [comment]
@jasonsaayman I don't see a new release yet, Do you have an approximate ETA?

**Comment by santhoshbonala1565** [comment]
@DigitalBrainJS Please let is know when this change is expected to be released on v0.x branch

**Comment by jasonsaayman** [comment]
just did the release
