### ISSUE TITLE
Compile failed after upgrade to version 1.7.8

### ISSUE THREAD

**Issue by 04756** [axios/axios#6716]
### Describe the bug

After upgrade the version of Axios to 1.7.8, codes or configs no change, our compile has issue. The error is follow:
Exported variable 'xxx' has or is using name 'RawAxiosHeaders' from external module "xxxxx/node_modules/.pnpm/axios@1.7.8/node_modules/axios/index" but cannot be named.

### Code snippet
our code is like this:
```
delete<T, A extends AxiosHeaders>(url: string, headers?: A)
```

### Axios Version

1.7.8

### Node.js Version

16.15.1

**Comment by gregorydresilk** [comment]
I'm also getting errors when programmatically building code via Jenkins pipeline, and I'm pretty sure the issue is caused from this latest update as well. Every instance of `AxiosHeader` in my code throws an error, and it wasn't doing so before today.
![image](https://github.com/user-attachments/assets/10410f7a-aa5a-4b53-8f70-9b80e1e6bcaa)

Will revert back to version `1.7.7` (was previously using `^1.4.0` in my `packages.json`) and hopefully this should resolve the issue for now.

Reverted back to version `1.7.7` (was previously using `^1.4.0` in my `packages.json`) and this resolved the issue for now.

**Comment by tkalmar** [comment]
i think this is a side-effect of https://github.com/axios/axios/issues/6720

**Comment by gregorydresilk** [comment]
> check #6527 if this works please close else @ me

Hi, not sure if you're suggesting to uninstall `@types/axios` but that package is not installed anywhere in my system. The only installed packages in my system relating to axios are `axios` itself and `@nestjs/axios`, and the problem in this instance does not lie with the nestJS version.

**Comment by 04756** [comment]
> @types/axios

Hi,  `uninstall @types/axios` not fix my issue. I just check my package.json, we haven't install `@types/axios` before, so its no need to do uninstall i think. 

But my issue fixed by using `AxiosRequestHeaders` instead of `AxiosHeaders`, which is surprising. Because `AxiosRequestHeaders` is equals to `RawAxiosRequestHeaders & AxiosHeaders` from the code.

<img width="804" alt="Clipboard_Screenshot_1732761352" src="https://github.com/user-attachments/assets/7079789d-1156-4c68-b555-b5fcd3e529b9">


Just search the same error, and it seems like this error will maybe caused by `here is no explicit type annotation on the functions or variables. `, hope can help u to find the true reason of the issue.
https://github.com/microsoft/TypeScript/issues/5711#issuecomment-340283439

**Comment by 04756** [comment]
> I'm also getting errors when programmatically building code via Jenkins pipeline, and I'm pretty sure the issue is caused from this latest update as well. Every instance of `AxiosHeader` in my code throws an error, and it wasn't doing so before today. ![image](https://private-user-images.githubusercontent.com/103133891/390158843-10410f7a-aa5a-4b53-8f70-9b80e1e6bcaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjAzOTAsIm5iZiI6MTczMjc2MDA5MCwicGF0aCI6Ii8xMDMxMzM4OTEvMzkwMTU4ODQzLTEwNDEwZjdhLWFhNWEtNGI1My04ZjcwLTliODBlMWU2YmNhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwMjE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWUxYTdmZWMxMjUxOTVhMjQ2NWFjNWI0NjJlZTFiNDE2MDRhMWRlZGU0NzA3ZmI0MDcyZmMxNzRmY2JhMzY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nobawrauTp9Hgm3a8y2ivhz3dtgjxTlW7tFSTB2xXcM)
> 
> Reverted back to version `1.7.7` (was previously using `^1.4.0` in my `packages.json`) and this resolved the issue for now.

Relace `AxiosHeaders` with `AxiosRequestHeaders` has fixed my issue, detail u can check  [comment](https://github.com/axios/axios/issues/6716#issuecomment-2505149884). Hope can help u.

**Comment by jasonsaayman** [comment]
reverted these changes in v1.7.9 which should solve any issues. i will re-look the original proposal as it seems to have caused breaking change which I was un-aware of when merging

should this not solve it please @ me and I will re-look
