### ISSUE TITLE
Forced to import axios into the scope to automatically infer the types 

### ISSUE THREAD

**Issue by AdarshNeoIto** [axios/axios#6728]
### Describe the bug

The axios http methods return type has been changed from AxiosResponse to axios.AxiosResponse. This causes axios need to be imported into the scope to infer the type even though we are not directly using it.

```
The inferred type of createChannel cannot be named without a reference to ../../../../../node_modules/axios/index.cjs . This is likely not portable. A type annotation is necessary.
```

### To Reproduce

- Create an axios instance as module 
- Use it another module to fetch data, you will get a typerror to import axios

### Code snippet

```js
export const createChannel = async (newChannel: NewChannelBody) => {
  const response = await axiosInstance.post(api_end_points.channels, newChannel);
  return response;
}
```

### Expected behavior

Thres is no need to import axios

### Axios Version

1.7.8

**Comment by Ehteshamali1109** [comment]
Solution
To address the issue, explicitly annotate the return type of the function to avoid TypeScript inferring a non-portable nested type. You can use AxiosResponse from axios for the annotation.

Steps to Fix:
Explicitly Import the Type: Import AxiosResponse from axios in your file and use it for the function's return type. This avoids the need for TypeScript to infer the return type.

ts
Copy code
import { AxiosResponse } from 'axios';

export const createChannel = async (
  newChannel: NewChannelBody
): Promise<AxiosResponse> => {
  const response = await axiosInstance.post(api_end_points.channels, newChannel);
  return response;
};
Avoid Using Inferred Return Types: Always define the return type of your functions explicitly to prevent non-portable type inference.

Optional Alternative: If you don’t want to import AxiosResponse, you can define a custom type alias for the response structure you expect. This avoids dependency on axios in your modules.

ts
Copy code
type ChannelResponse = {
  data: any; // Adjust based on your API response shape
  status: number;
  statusText: string;
  headers: any;
  config: any;
};

export const createChannel = async (
  newChannel: NewChannelBody
): Promise<ChannelResponse> => {
  const response = await axiosInstance.post(api_end_points.channels, newChannel);
  return response;
};
Explanation of the Fix
By explicitly annotating the return type, TypeScript no longer needs to infer it from the axiosInstance or its methods, preventing references to deeply nested module paths.
Importing AxiosResponse from axios directly ensures consistency with the Axios library while keeping your code portable and maintainable.

**Comment by AdarshNeoIto** [comment]
Yeah I know how to fix it , but im not supposed to get that error in the first place

**Comment by jasonsaayman** [comment]
reverted these changes in v1.7.9 which should solve any issues. i will re-look the original proposal as it seems to have caused breaking change which I was un-aware of when merging

should this not solve it please @ me and I will re-look
