### ISSUE TITLE
Use Semantic Versioning of follow-redirects

### ISSUE THREAD

**Issue by xogeny** [axios/axios#675]
I recently ran into an issue where Axios was not correctly following a redirect.  I tracked the issue down to the exact spot in the `follow-redirects` code where the issue originated.  But after reporting this to `follow-redirects`, [they pointed out that the issue had actually been fixed some time ago](https://github.com/olalonde/follow-redirects/issues/51#issuecomment-275870580) and that if I were only using the most recent version of `follow-redirects`, I would have gotten the fix.

Is there some reason why the dependency on `follow-redirects` is pinned at `1.0.0` and not allowed to float (e.g., `^1.0.0`)?

**Comment by nickuraltsev** [comment]
It's `^1.2.5` now
