### ISSUE TITLE
Why encode() function differs from encodeURIComponent?

### ISSUE THREAD

**Issue by alex-shamshurin** [axios/axios#678]
```
       function encode(val) {
	  return encodeURIComponent(val).
	    replace(/%40/gi, '@').
	    replace(/%3A/gi, ':').
	    replace(/%24/g, '$').
	    replace(/%2C/gi, ',').
	    replace(/%20/g, '+').
	    replace(/%5B/gi, '[').
	    replace(/%5D/gi, ']');
	}
```
In my case `replace(/%20/g, '+')` make param not compatible with server side decoding

**Comment by alexanderjamesking** [comment]
I ran into this (or a similar issue) but for the colon ":"

After doing a bit of research it seems some of these characters are acceptable to be unencoded depending on where in the URL they are used.

See [RFC3986 - Reserved Characters](https://tools.ietf.org/html/rfc3986#section-2.2)
or [Stop Using Unsafe Characters in URLs](https://perishablepress.com/stop-using-unsafe-characters-in-urls/)

I think the "%20" is a bug though as it should be "%2B"?

**Comment by alexanderjamesking** [comment]
```
encodeURIComponent("+")
"%2B"
decodeURIComponent("%20")
" "
decodeURIComponent("%2B")
"+"
```

**Comment by rubennorte** [comment]
@mzabriskie could you clarify this?

**Comment by Abhicoding** [comment]
@mzabriskie @rubennorte Replacing spaces with '+'

**Comment by wonderbeyond** [comment]
```javascript
> decodeURIComponent('%20')
' '
> decodeURIComponent('+')
'+'
```

The server side cannot parse a plus into space, so why not keep encoding space with `%20` just like encodeURIComponent?

**Comment by chrisbarnes** [comment]
I'm also curious why spaces are not encoded with %20.

**Comment by anscho** [comment]
https://stackoverflow.com/a/47188851/664939

> But from a pure reading of the specifications, without the language from the HTML 2.0 specification carried over into later versions, URLs are covered entirely by RFC3986, which means spaces ought to be converted to '%20'. And definitely that should be the case if you are requesting anything other than an HTML document.

Why are URL param spaces replaced with pluses instead of `%20`? This is causing problems for me interacting with the Datadog API.

**Comment by changulpaye** [comment]
I am facing same problem. Spaces are converting into '+'. please fix as early as possible.

**Comment by igordeoliveirasa** [comment]
YEAH PLEASE!

**Comment by unselchr** [comment]
Is this ever going to be fixed? This is a huge and recurring issue for me and many others

**Comment by cambraca** [comment]
I ran into this because the "@" character wasn't being encoded, which was making my API server blow up. Here's what I did to fix it. It prefers using "URLSearchParams", but if that's not available it uses the same encode function _but only for the param keys_, which I'm assuming is the reason it was coded like that in axios.

```
import axios from 'axios';

const paramsSerializer = typeof URLSearchParams !== 'undefined' ?
	params => (new URLSearchParams(params)).toString() :
	params => {
		const encodeKey = val => {
			return encodeURIComponent(val).
				replace(/%40/gi, '@').
				replace(/%3A/gi, ':').
				replace(/%24/g, '$').
				replace(/%2C/gi, ',').
				replace(/%20/g, '+').
				replace(/%5B/gi, '[').
				replace(/%5D/gi, ']');
		};

		return Object.keys(params)
			.map(key => encodeKey(key) + '=' + encodeURIComponent(params[key]))
			.join('&');
	};

axios.defaults.paramsSerializer = paramsSerializer;

export default axios;
```

I set it up like that so I can use it in almost the same way throughout my codebase ("import axios from "path/to/my/axios.js").

**Comment by alex-shamshurin** [comment]
Almost three years and it is steel opened!

**Comment by cambraca** [comment]
#2563

**Comment by jasonsaayman** [comment]
On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the qs library:
```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

**Comment by xianghongai** [comment]
> By default, axios serializes JavaScript objects to JSON. To send data in the [application/x-www-form-urlencoded format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) instead. - [axios#using-applicationx-www-form-urlencoded-format](https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format)

> Depending on the context, the character ' ' is translated to a '+' (like in the percent-encoding version used in an application/x-www-form-urlencoded message), or in '%20' like on URLs. - [Percent-encoding](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding)

**Comment by xianghongai** [comment]
![image](https://user-images.githubusercontent.com/2075006/225493090-f8c9aa4c-5acf-4497-9379-c46fb830b9eb.png)


Axios mainly restores RFC3986 reserved characters, according to `encodeURIComponent` characters, and `encodeURI` and `encodeURIComponent` difference characters:

1. The green part `encodeURIComponent` has not been transcoded;

2. The blue part, restore treatment;

3. The yellow part involves the basic path of the URI and will not be processed;

4. `+` is special, space is occupied, not processed;

5. In RFC3986, only `@` and `;` are left unprocessed.

**Comment by andrenerd** [comment]
Came across the same prob. 
It could be pretty critical for "signed" requests, when signature calcs use complex url params.

Please, compare "URLSearchParams" and "axios" encoded param strings:
?filter=%7B%22isOpen%22%3Atrue%7D
?filter=%7B%22isOpen%22:true%7D

Would be nice if the "colon" symbol is encoded the same way.
