### ISSUE TITLE
consider export default configs?

### ISSUE THREAD

**Issue by zhuangya** [axios/axios#688]
first of all, thank you for this great project.

and i'm write a node module for internal use: a class extends Axios

in order to make Axios working, i have to write something like:

```javascript
const { Axios } = require('axios');
const axiosDefaults = require('axios/lib/defaults'); 

class SomeClass extends Axios {
  constructor(instanceConfig = {}) {
    super(Object.assign(axiosDefaults, { baseURL: 'https://fancy.web.site/api' }, instanceConfig));
  }
}
```

this **is** working, but i think `require('axios/lib/defaults)` is kind of hacky.

maybe export it so it is convenient to be extended?

**Comment by rubennorte** [comment]
Is there a reason you can't use global axios defaults as they are? If not, you can just use the following code and the global defaults are automatically applied:

```javascript
class SomeClass extends Axios {
  constructor(instanceConfig = {}) {
    super(Object.assign({ baseURL: 'https://fancy.web.site/api' }, instanceConfig));
  }
}
```

**Comment by zhuangya** [comment]
in this way i can not extend default headers :(

**Comment by rubennorte** [comment]
Why not? You should be able to do it with the `headers` option as explained in the docs.

**Comment by zhuangya** [comment]
i mean i can not set `foo.defaults.headers.common['Authorization'] =  'Bear 123';` if foo's shape is like `{baseURL: 'https://fancy.web.site/api'}`, since there is no `foo.defaults` right?

the reason i wanted the default config be exported is that, the default config is a complicated-yet-deep-nested object. :(

**Comment by zhuangya** [comment]
for more clear:

```javascript

const { Axios } = require('axios');
const axiosDefaults = require('axios/lib/defaults'); 

class SomeClass extends Axios {
  constructor(instanceConfig = {}) {
    super(Object.assign(axiosDefaults, { baseURL: 'https://fancy.web.site/api' }, instanceConfig));
  }

  // i can not set a global header if there is  no `axiosDefaults`:
  this.defaults.headers.common = Object.assign(this.defaults.headers.common, { 'x-ninja': 'nyan' }); 
}

```

**Comment by zhuangya** [comment]
closed due to inactivity
