### ISSUE TITLE
No default value for responseType config option

### ISSUE THREAD

**Issue by gamtiq** [axios/axios#724]
axios 0.15.3

[Request Config](https://github.com/mzabriskie/axios#request-config) documentation states that `responseType` option has `json` as default value:
```js
  // `responseType` indicates the type of data that the server will respond with
  // options are 'arraybuffer', 'blob', 'document', 'json', 'text', 'stream'
  responseType: 'json', // default
```

But is seems no default value is set for the option. And default value for [`responseType` attribute](https://xhr.spec.whatwg.org/#the-responsetype-attribute) of XHR is empty string.

**Comment by rubennorte** [comment]
It's handled differently in the code, not by setting a value in the defaults object. Are you experiencing any issue for this?

**Comment by gamtiq** [comment]
Yes, I had an issue with this before I realized that `responseType: 'json'` should be stated explicitly in config.

**Comment by chinesedfan** [comment]
In fact, it is achieved trickily by the default `config.transformResponse`, which will always try to parse string to json. Remind me if you have further problem.
