### ISSUE TITLE
Get with nested JSON params

### ISSUE THREAD

**Issue by XXChester** [axios/axios#738]
I am trying to perform the following get request which is nested JSON:
```
axios.get(Routes.geocode_lookup_path(), {
                params: {
                    address: {
                        postal_code: postal_code,
                    },
                }
            }
            )
```

Axios is unfortunately escaping the nested JSON which crashes the rails request. Here is an example of the request the server receives in JQuery vs Axios:
```
axios(bad):
{"address"=>"{\"postal_code\":\"32412\"}", "controller"=>"addresses", "action"=>"geocode"}
   
jquery(good):
{"address"=>{"postal_code"=>"42353"}, "controller"=>"addresses", "action"=>"geocode"}

```

Any suggestions would be greatly appreciated.

**Comment by arevutsky** [comment]
My tempolary solution:
`      
paramsSerializer: function(params) {
  return jQuery.param(params)
}`

**Comment by crcatala** [comment]
@XXChester looks like for get request, params need to be serialized. It's mentioned in the docs here https://github.com/mzabriskie/axios#using-applicationx-www-form-urlencoded-format. A few ways to go about serializing the params

**Comment by ekampp** [comment]
If someone wants want a solution that doesn't require jquery, here is my solution:

```
// Format nested params correctly
axios.interceptors.request.use(config => {
  window.console.log(config);

  config.paramsSerializer = params => {
    // Qs is already included in the Axios package
    return Qs.stringify(params, {
      arrayFormat: "brackets",
      encode: false
    });
  };

  return config;
});
```

**Comment by edgarv09** [comment]
@ekampp thanks!!! dude 🚀

**Comment by edgarv09** [comment]
@ekampp Just putted it before execute the action like this.

        axios.interceptors.request.use(config => {
            config.paramsSerializer = params => {
              // Qs is already included in the Axios package
              return Qs.stringify(params, {
                arrayFormat: "brackets",
                encode: false
              });
            };
            return config;
          });

        axios.get(URL,{ params})..

**Comment by eithed** [comment]
You can pass the variables to url per

```
let payloadString = qs.stringify(payload)
axios.get(`endpoint?${payloadString}`)
```

(qs = querysting, in my case I've used https://github.com/ljharb/qs)

Of course, it would be great if axios.get(url, {params: data}) was symmetric to axios.post(url, data) so if I need to change the method of request, it's as simple as changing what method on axios I'm calling without messing with internals / trying to serialize the object myself.

**Comment by goodwin64** [comment]
What's the current status of this issue?

**Comment by XXChester** [comment]
You can close it if you'd like, I still think it's odd you need to do something special for nested JSON but regardless we moved away from axios.

**Comment by coatesap** [comment]
This still seems to be a problem, and it's frustrating having to implement the workaround that @ekampp posted on every project. 

It also seems inconsistent that for POST requests, Axios "correctly" encodes the data, but for GET requests it doesn't...

**Comment by m5tt** [comment]
As said above, this should really dealt with the same way POST requests do. It doesnt make sense it works for one method but not another.

Also for anyone dealing with this - i think you want to install the `qs` library from npm, here - https://github.com/ljharb/qs

_Not_ the `query-string` library, as it doesnt support nesting. In case this isn't obvious.

**Comment by Alanscut** [comment]
We will keep the same way with `qs` when handling the params, you have to use `paramsSerializer ` to handle nested params.
