### ISSUE TITLE
Socket hang up when request behind $https_proxy

### ISSUE THREAD

**Issue by jingsam** [axios/axios#753]
When I use axios request a https url, socket hang up. Here's zsh configuration:
```
export http_proxy=http://duotai:yjnSLarOdMA@marriott.h.xduotai.com:18283
export https_proxy=$http_proxy
```
Using `request` works fine. Also if I request a http url instead of a https one, works fine too.

**Comment by blizzardzheng** [comment]
same issue

**Comment by blizzardzheng** [comment]
so anyone can help? i do not think always config proxy is right choice

**Comment by Khaledgarbaya** [comment]
Me and a colleague of mine identified the problem, a PR should be coming soon

**Comment by Khaledgarbaya** [comment]
the PR is here https://github.com/mzabriskie/axios/pull/959

**Comment by PavelPolyakov** [comment]
this was merged, but never released, right?
