### ISSUE TITLE
ie9 axios post request return 415

### ISSUE THREAD

**Issue by zp1112** [axios/axios#764]
Here is my request code,with CORS

```js
axios.post("http://myapiurl",{key: 'value'})
            .then(function (response) {
              console.log(response.data);
            })
            .catch(function (error) {
              console.log(error);
            })
```

request headers(there is no content-type in the header list):
Accept: \*/\*
Origin: http://localhost:port

response headers:
content-type: application/json,charset=UTF-8
Access-Control-Allow-Origin: *
Vary: Origin

status: 415

and when i set headers before,it dosen't work,and not even set up successfully,Both content-type and accept and other headers.

Pleasehelp me.thanks!

**Comment by weikin2015** [comment]
Have you solved this problem?I'm the same problem

**Comment by zp1112** [comment]
@weikin2015 no ! I use nginx to proxy the api.

**Comment by rubennorte** [comment]
It seems to be an issue in your API. By default axios sends `application/json` as Content-Type. Maybe your API isn't compatible with that or you should use `application/www-x-form-urlencoded` instead.

**Comment by randomknowledge** [comment]
@rubennorte, It's definitely not a problem with the API (which is the very common Django Rest Framework, http://www.django-rest-framework.org/).
IE9 is really not sending the correct headers.

Can you please reopen this issue or remove IE9 compatibility from the Readme?

**Comment by xiavn** [comment]
I seem to be seeing the same issue - my post request works in all other browsers, but on IE9, the content-type is never set and the request fails.

**Comment by Dakuan** [comment]
I've seen this happen when the body is sent as a string rather than json.

**Comment by lj1000** [comment]
hey im having same issue please see #365 it references a good blog see point 4 it looks like theres no work around

**Comment by yueswing07** [comment]
@zp1112  Have you solved this problem?I'm also the same problem。 
IE9 compatibility is  incorrect

**Comment by Mubeen07** [comment]
facing this network issue in post call IE9 with response headers 415

![network error](https://user-images.githubusercontent.com/31301467/29653420-22cf1474-88c3-11e7-83ef-b9cf2b62f7ed.png)

**Comment by lijiasusu** [comment]
@Mubeen07 Have you solved this problem?I'm the same problem.

**Comment by Mubeen07** [comment]
@lijiasusu I don't remember now...

**Comment by mqliutie** [comment]
In iE9 content type not in headers, and server side return to me message is `Content type 'application/octet-stream' not supported`

**Comment by Alanscut** [comment]
axios doesn't support ie9, please see [readme](https://github.com/axios/axios#browser-support)
