### ISSUE TITLE
Send multipart/form-data with axios in nodejs

### ISSUE THREAD

**Issue by tqm-kmd** [axios/axios#789]
From the documentation of axios it seems that nodejs doesn't natively support FormData objects 

` 
// data is the data to be sent as the request body
// Only applicable for request methods 'PUT', 'POST', and 'PATCH'
// When no transformRequest is set, must be of one of the following types:
// - string, plain object, ArrayBuffer, ArrayBufferView, URLSearchParams
// - Browser only: FormData, File, Blob
// - Node only: Stream
  data: {
    firstName: 'Fred'
  },
`

So if I want to use axios in a jasmine test running with nodejs, then how would I go ahead and post a multipart/formdata object to a website?

Thanks for your help..

**Comment by rubennorte** [comment]
You can do it manually in Node.js but we don't support it natively in axios for the moment.

**Comment by binki** [comment]
For people like me who google and end up here without having a hint on how to do this manually in nodejs, I wrote [a small example using the `form-data` package](https://github.com/mzabriskie/axios/issues/1006#issuecomment-320165427).

**Comment by doytch** [comment]
Ran into this and didn't want to bring in another dependency since I was just POSTing a large string that was too long for a URL. Figured I'd leave my workaround here in case it helps others:
`url.post('/api/myurl', ``configuration=${encodeURIComponent(JSON.stringify(myBigObject))}``)` 

(Ignore the double-backtick, it's a template literal and I'm working around Markdown)

**Comment by corysimmons** [comment]
@doytch What is `myBigObject`?? Where is that coming from?

**Comment by Andruschenko** [comment]
In the [link which @binki posted](https://github.com/axios/axios/issues/1006) a solution is shown that you can ineed use **axios** to make a request with Form-Data. You just have to add the headers from the generated form to your request!

**Comment by doopcl** [comment]
I have a simple plan to realize it, just use 'form-data'
`const FormData = require('form-data');
const fs = require('fs');
const axios = require('axios');

let form = new FormData();

form.append('file', fs.createReadStream(__dirname + '/README.md'), {
    filename: '111.md'
});

axios.create({
    headers: form.getHeaders()
}).post('http://localhost:8001/sample/upload', form).then(response => {
    console.log(response);
}).catch(error => {
    if (error.response) {
        console.log(error.response);
    }
    console.log(error.message);
});`

Test Success!

**Comment by ashok-sc** [comment]
@rubennorte why didn't you just point people here: https://www.npmjs.com/package/axios#nodejs. Isn't this how you expect users of axios to deal with it?

**Comment by corysimmons** [comment]
I should've updated. We ended up just making a helper that converted every body to FormData (similar to what @doopcl did) then passed to axios. Afterwards we cleaned it up to not rely on axios and just use native fetch.

**Comment by DiamondYuan** [comment]
```
  formPost(url, form) {
    return new Promise((resolve, reject) => {
      console.log(form.getHeaders()['content-type']);
      axios({
        method: 'post',
        url,
        data: form,
        headers: { 'Content-Type': form.getHeaders()['content-type'] },
        cancelToken: new CancelToken((c) => {
          cancel = c;
        }),
      }).then((res) => {
        resolve(res);
      }).catch((err) => {
        console.log(err);
        reject(err);
      });
    });
  },
```

i use this,not work

**Comment by pikitgb** [comment]
@ashok-sc comment solved for me :
Installing querystring and stringifying the data

var querystring = require('querystring');
axios.post('http://something.com/', querystring.stringify({ foo: 'bar' }));

**Comment by sant123** [comment]
Any plan to support it natively?

**Comment by tomeady** [comment]
This is a temporary solution that might help some until formData has native support using a package called **express-fileupload**.

Ignore the react syntax.

SERVER SIDE - Node.js

```
// @route   POST api/media/
// @desc    Create a new media
// @access  Private
router.post(
  "/",
  (req, res) => {
    const data = req.files;
    return res.json({ success: true, data: data });
  }
);
```

CLIENT SIDE - React.js redux action for context.

```
export const uploadMedia = data => dispatch => {
  axios
    .post(API_URL + "/api/media", data, {
      onUploadProgress: ProgressEvent => {
        dispatch({
          type: UPDATE_MEDIA_STATUS,
          payload: (ProgressEvent.loaded / ProgressEvent.total) * 100
        });
      }
    })
    .then(res => {
      dispatch({
        type: UPLOAD_MEDIA,
        payload: res.data.data
      });
    })
    .catch(err => {
      dispatch({
        type: SET_MEDIA_ERROR,
        payload: err.response.data.errorMessage || err.response.statusText
      });
    });
};
```

**Comment by louismrose** [comment]
We hit this issue today too. In our case, the server responding to the multipart request was throwing 400 Bad Request exceptions (and, confusingly, was identifying the request as a GET not a POST in the Apache logs).

We compared HTTP requests from a working client (written in PHP and Guzzle) with a broken client (written in Node and Axios). This led us to discover that Axios + FormData was not setting the Content-Length header, and was instead attempting to use a `chunked` [transfer encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding).

To workaround this, we are:
1. Setting the Axios headers to include the headers generated by FormData (as suggested by @binki 
above).
2. Additionally, setting the Axios's Content-Length header via the `getLengthSync` method on FormData.
3. Ensuring that all files that we append to the FormData object include a `knownLength` option so that FormData is able to track the size of the request body.

Putting this all together we got:

```es6
const firstFilePath = process.cwd() + "/first.txt";
const secondFilePath = process.cwd() + "/second.txt";

const formData = new FormData();

// Append any plain string values to the request
formData.append("firstString", "foo");
formData.append("anotherString", "bar");

// Append any files to the request
formData.append("firstFile", fs.createReadStream(firstFilePath), { knownLength: fs.statSync(firstFilePath).size });
formData.append("anotherFile", fs.createReadStream(secondFilePath), { knownLength: fs.statSync(secondFilePath).size });

// Prepare additional headers for Axios, which include FormData's headers and the Content-Length
const headers = {
    ...formData.getHeaders(),
    "Content-Length": formData.getLengthSync()
};

// Now send the request
axios.post("https://example.org/", formData, {headers});
```

**Comment by lukepighetti** [comment]
Is this a `wontfix` or a `donthavetimetofix`?

**Comment by chinesedfan** [comment]
For users who must send as FormData, see https://github.com/axios/axios/issues/1006#issuecomment-320165427.
For users who just want to send some data in the server side, see https://www.npmjs.com/package/axios#nodejs.

**Comment by DininduKanchana** [comment]
Hi. I also faced the same issue and found a working solution from [npm form-data](https://www.npmjs.com/package/form-data)
`const FormData = require('form-data');
 
const form = new FormData();
form.append('a', 1);
 
fetch('https://httpbin.org/post', { method: 'POST', body: form })
    .then(res => res.json())
    .then(json => console.log(json));
 
// OR, using custom headers
// NOTE: getHeaders() is non-standard API
 
const form = new FormData();
form.append('a', 1);
 
const options = {
    method: 'POST',
    body: form,
    headers: form.getHeaders()
}
 
fetch('https://httpbin.org/post', options)
    .then(res => res.json())
    .then(json => console.log(json));`

**Comment by DevNM21** [comment]
> I have a simple plan to realize it, just use 'form-data'
> 
> > const FormData = require('form-data');
> > const fs = require('fs');
> > const axios = require('axios');
> > let form = new FormData();
> > form.append('file', fs.createReadStream(__dirname + '/README.md'), {
> > filename: '111.md'
> > });
> > axios.create({
> > headers: form.getHeaders()
> > }).post('http://localhost:8001/sample/upload', form).then(response => {
> > console.log(response);
> > }).catch(error => {
> > if (error.response) {
> > console.log(error.response);
> > }
> > console.log(error.message);
> > });
> 
> Test Success!

Hey, I was wondering if this would work for images too?

**Comment by doopcl** [comment]
ofcourse，it is filestream upload




| |
cailong
邮箱：doopcl@126.com
|

Signature is customized by Netease Mail Master

On 03/17/2020 01:24, Devakumar wrote:

I have a simple plan to realize it, just use 'form-data'

const FormData = require('form-data');
const fs = require('fs');
const axios = require('axios');
let form = new FormData();
form.append('file', fs.createReadStream(__dirname + '/README.md'), {
filename: '111.md'
});
axios.create({
headers: form.getHeaders()
}).post('http://localhost:8001/sample/upload', form).then(response => {
console.log(response);
}).catch(error => {
if (error.response) {
console.log(error.response);
}
console.log(error.message);
});

Test Success!

Hey, I was wondering if this would work for images too?

**Comment by hungdev** [comment]
thanks @DininduKanchana , it worked <3

**Comment by beasty-web** [comment]
While the version using the [form-data](https://www.npmjs.com/package/form-data) package also worked for me I felt like I didn't actually need this extra package.

In my case it was sufficient to just roll my own URI encode function and pass the result to axios

`function uriEncodeObject(obj) {
    const formData = Object.keys(obj).reduce((acc, key) => {
      const value = obj[key]

      return acc + '&' + encodeURIComponent(key) + '=' + encodeURIComponent(value)
    }, '')

    return formData.substring(1)
  }

const payload = {
  ... put your request data in here
}

 axios.post('https://...', uriEncodeObject(payload), {
  headers: { 'Content-Type': 'x-www-form-urlencoded' }
})
`

**Comment by mcdado** [comment]
> We hit this issue today too. In our case, the server responding to the multipart request was sending 400 Bad Request responses (and, confusingly, was identifying the request as a GET not a POST in the Apache logs).
> 
> We compared HTTP requests from a working client (written in PHP and Guzzle) with a broken client (written in Node and Axios). This led us to discover that Axios + FormData was not setting the Content-Length header, and was instead attempting to use a `chunked` [transfer encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding).
> 
> To work around this, we are:
> 
> 1. Setting the Axios headers to include the headers generated by FormData (as suggested by @binki
>    above).
> 2. Additionally, setting the Axios's Content-Length header via the `getLengthSync` method on FormData.
> 3. Ensuring that all files that we append to the FormData object include a `knownLength` option so that FormData is able to track the size of the request body.
> 
> Putting this all together we got:
> 
> ```js
> const firstFilePath = process.cwd() + "/first.txt";
> const secondFilePath = process.cwd() + "/second.txt";
> 
> const formData = new FormData();
> 
> // Append any plain string values to the request
> formData.append("firstString", "foo");
> formData.append("anotherString", "bar");
> 
> // Append any files to the request
> formData.append("firstFile", fs.createReadStream(firstFilePath), { knownLength: fs.statSync(firstFilePath).size });
> formData.append("anotherFile", fs.createReadStream(secondFilePath), { knownLength: fs.statSync(secondFilePath).size });
> 
> // Prepare additional headers for Axios, which include FormData's headers and the Content-Length
> const headers = {
>     ...formData.getHeaders(),
>     "Content-Length": formData.getLengthSync()
> };
> 
> // Now send the request
> axios.post("https://example.org/", formData, {headers});
> ```

![Thank you](https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif)

**Comment by mcdado** [comment]
@louismrose seriously, me and a colleague wasted one and a half day each debugging the same situation. When we got the tip that `Content-Length` was not set by axios using form-data, we found your answer. `formData.getLengthSync()` saved the day(s).
