### ISSUE TITLE
CORS did't work on IE，header did't sent

### ISSUE THREAD

**Issue by weikin2015** [axios/axios#807]
My custom header sets well on chrome or safari, but when it works on IE(9), my custom header did't sent to the server,
 No 'Content-Type' was sent to the server,
And 'Accept' was still '*/*',
 the XHR was 415 error if the header did't set well,
there is no problem in other browser

`import "babel-polyfill";
import axios from 'axios/dist/axios.min' //"axios": "^0.15.3",
let baseUrl = 'http://192.168.51.********/';
const axiosInstance = axios.create({
    baseURL: baseUrl,
    timeout: 30000,
    headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
    }
})
axiosInstance.interceptors.request.use(function (config) {
    let temp = config.data;
    config.data = {};
    config.data.data = temp;
    config.data.token = window.sessionStorage.getItem("token") || "";
    return config;
})

export default axiosInstance;`

**Comment by weikin2015** [comment]
I'm the same problem with #764,with CROS

**Comment by zp1112** [comment]
Have you solved this problem?

**Comment by weikin2015** [comment]
@zp1112  No，we are considering server side rendering for better SEO, this problem will no longer exit if we use SSR.

**Comment by weikin2015** [comment]
@zp1112 We are considering server side rendering for better SEO, this problem will no longer exit if we use SSR.Please tell me if you solved this problem,thank you!

**Comment by lj1000** [comment]
hey im having same issue please see https://github.com/mzabriskie/axios/issues/365 looks like th

**Comment by lj1000** [comment]
hey im having same issue please see https://github.com/mzabriskie/axios/issues/365

**Comment by Gavinchen92** [comment]
perhaps ie9 not support  CORS

**Comment by alex-exerve** [comment]
So, here's the thing about this issue (because I ran into it the other day) How does jquery support CORS in ie9? because I ended up having to make a mokeypatch wrapper in IE9 so it'd use jquery to send an authorization header on a get request.

**Comment by alex-exerve** [comment]
Okay so here's the fix:
in [xhr.js](/axios/axios/lib/adapters/xhr.js) on line 29:
```javascript
    window.XDomainRequest && !('withCredentials' in request) &&
```
should really be:
```javascript
    window.XDomainRequest && !('withCredentials' in config) &&
```

and here is the proof:

- [axios 0.17.1 broken in ie9](https://codepen.io/fimion/full/OQXOgK/)
- [axios 0.17.1 with fixed line](https://codepen.io/fimion/full/OQXOGy/)

if you run this in IE9 the fixed version will return an "Authorization" header with a token.

**Comment by Khaledgarbaya** [comment]
IE9 is no longer supported by Microsoft and I don't see any plans to fix this is axios

**Comment by mqliutie** [comment]
@zp1112 最后你的问题解决了吗?

**Comment by jasonsaayman** [comment]
I am going to close this issue as it is the same as the prior IE9 issue. I doubt this will be mended as IE9 and IE10 no longer receive support from Microsoft.
