### ISSUE TITLE
WHATWG URL support

### ISSUE THREAD

**Issue by stevenvachon** [axios/axios#833]
You could use [isomorphic-url](https://npmjs.com/isomorphic-url) and/or [isurl](https://npmjs.com/isurl).

**Comment by robaxelsen** [comment]
Hi @stevenvachon, and thanks for your suggestion. It would be really helpful if you could submit a PR for this, if this is something you still see the need for.

@mzabriskie @nickuraltsev @rubennorte in accordance with the [Collaborator Guide](https://github.com/axios/axios/blob/master/COLLABORATOR_GUIDE.md) I propose to close this issue on 16.01.2018 if no response from OP.

**Comment by stevenvachon** [comment]
I don't use this library, so let's close this if I'm the only one who's interested in specification compliance.
