### ISSUE TITLE
Order of applying request interceptors is reversed.

### ISSUE THREAD

**Issue by le0nik** [axios/axios#841]
I've encountered a bug(or a feature) that my request interceptors were applied in reversed order.

This is the culprit:
https://github.com/mzabriskie/axios/blob/2fe95621b0e4839f489210452ffc6d2cb0f90343/lib/core/Axios.js#L48

If you `unshift` interceptors one by one, then the last defined interceptor becomes the first in the `chain`.

Example:
```js
axios.interceptors.request.use(config => {
  console.log('First');
  return config;
});
axios.interceptors.request.use(config => {
  console.log('Second');
  return config;
});
```

When we perform a request this is what we see in the console:

```
> Second
> First
```

If it's intentional, I think it should be documented.

**Comment by Nealyang** [comment]
I have the same puzzled

`axios.interceptors.request.use(function (config) {
            if (config.method === 'post') {
                console.log(config.data)
                config.data.sign = getSign(config.data,SECRETKEY);
                config.transformRequest = [function (data) {
                    let ret = '';
                    for (let it in data) {
                        ret += encodeURIComponent(it) + '=' + encodeURIComponent(data[it]) + '&'
                    }
                    return ret
                }];
            } else if (config.method === 'get') {
                config.params.sign = getSign(config.params);
            }
            return config;
        }, function (err) {
            return Promise.reject(err);
        });`

config.data.sign 

but when i console ,config.data has sign 
![image](https://cloud.githubusercontent.com/assets/9313216/26242021/8243c130-3cb9-11e7-8b22-eabaafb8dff9.png)

**Comment by Nealyang** [comment]
![image](https://cloud.githubusercontent.com/assets/9313216/26242034/8fd3d6c8-3cb9-11e7-8e23-e96cf57b4727.png)

**Comment by appmux** [comment]
This actually sucks big time as it's impossible to override the config if you have multiple interceptors...

**Comment by rubennorte** [comment]
As this isn't documented nor tested isn't actually a bug, but I understand it should be executed in the proper order.

The tests for response interceptors test the actual order but those for the request don't. 

Are you willing to create a PR to solve this?

**Comment by le0nik** [comment]
Sure. https://github.com/mzabriskie/axios/pull/1041
