### ISSUE TITLE
POST request with File browser object doesn't send file

### ISSUE THREAD

**Issue by krainboltgreene** [axios/axios#844]
#### Summary

POST request with File browser object doesn't send file.

#### Context

- axios version: v0.16.0
- Environment: Version 57.0.2987.133 (64-bit)

My code:

``` javascript
import axios from "axios"

export default function pushFile (file: File): Promise<FileResourceType> {
  return axios({
    method: "POST",
    url: `${window.env.LUMIN_LOCATION}/images`,
    body: file,
  })
    .then((response) => {
      debugger
    })
}
```

The file:
<img width="976" alt="screen shot 2017-04-16 at 1 17 46 am" src="https://cloud.githubusercontent.com/assets/334809/25069871/88686f34-2242-11e7-9bcd-78a2cec4feeb.png">

The "request":

<img width="681" alt="screen shot 2017-04-16 at 1 17 06 am" src="https://cloud.githubusercontent.com/assets/334809/25069873/913747c0-2242-11e7-878e-68ac080f7c7a.png">

**Comment by krainboltgreene** [comment]
A browser fetch works fine:
<img width="708" alt="screen shot 2017-04-16 at 1 21 52 am" src="https://cloud.githubusercontent.com/assets/334809/25069899/1b90bbd6-2243-11e7-8ed4-d95dfa643e68.png">

**Comment by Crecket** [comment]
Has this been fixed yet? I seem to be encountering the same issue with axios 0.16.2

**Comment by chinesedfan** [comment]
Check your request headers. I think what you need is setting `headers: { 'content-type': 'image/png' }`.
