### ISSUE TITLE
Cancelling image uploads to Cloudinary

### ISSUE THREAD

**Issue by kitze** [axios/axios#863]
### Summary

When uploading an image to Cloudinary with an ```axios.post``` request the cancellation token and the cancel functions seem to have no effect on the network request.

Is this a bug, or image upload requests should have some specific configuration so they can be canceled by the token?

I've tried asking about this on gitter/twitter but don't have a response yet.

Thank you

### Context

- axios version: *e.g.: v0.16.1*
- Environment: *Chrome Canary , macOS Sierra*

**Comment by Braunson** [comment]
I'm having this same issue on the same Axios versions and on Chrome Windows 10.

Cancel token has no effect in network requests.

**Comment by rubennorte** [comment]
Could you share some code where the cancellation fails? How are you uploading the image? I can't help you just with the information you provided.

**Comment by denizdogan** [comment]
I'm having the same problem, but I can't really show you a short code snippet to reproduce it, this is pretty deep in a React+Redux+Flow codebase, but I can tell you that I use it with the `new CancelToken` variant which sets a scoped variable to the cancelling function, just like in the documentation. Calling the cancel function does not abort the POST request.

This is in Chrome 60.0.3112.113, the JS built using Webpack.

**Comment by chinesedfan** [comment]
Closed due to lack of enough information.
