### ISSUE TITLE
Support delete body

### ISSUE THREAD

**Issue by Christilut** [axios/axios#897]
This is probably a design choice by the axios team and for good reason but I write all my POST/GET/PUTs like this:
```js
const res = await axios.post(url, { 
  data: {
    ...
  }
})
```

And my server sometimes expects data inside the DELETE request body (which may not be technically according to spec but nonetheless it is common) in which case I have to write my DELETE in this form:

```js
      const res = await axios({
        method: 'DELETE',
        url: 'url',
        data: {
          ...
        }
      })
```

Which works fine but I'm forced to use the second syntax because the `axios.delete` doesn't support a request body.

So I would like to request that `axios.delete` will support a request body.

Thanks

**Comment by emkman** [comment]
We often use `data` with GET requests on the server and they are translated to query params. The lack of data support on certain methods is a big downside for axios in my hopes of more isomorphic code.

**Comment by huangche007** [comment]
Thanks, Here I found this answer

**Comment by peterchealse** [comment]
..

**Comment by ChadTaljaardt** [comment]
Is there any update on this? I feel its quite important.

**Comment by nickuraltsev** [comment]
`axiox.delete` does support a request body. It accepts two parameters: `url` and optional `config`. You can use `config.data` to set the response body as follows:

```js
axios.delete(url, { data: { foo: "bar" } });
```

`post`, `put`, and `patch` accept 3 parameters: `url`, `data`, and `config` so you can you can use the second parameter to set the response body like this:

```js
axios.put(url, { foo: "bar" });
```

Hope it helps!

**Comment by charlesrochati** [comment]
I think the ```README``` is making it dificult to understand:

```
  // `data` is the data to be sent as the request body
  // Only applicable for request methods 'PUT', 'POST', and 'PATCH'
  // When no `transformRequest` is set, must be of one of the following types:
  // - string, plain object, ArrayBuffer, ArrayBufferView, URLSearchParams
  // - Browser only: FormData, File, Blob
  // - Node only: Stream, Buffer
  data: {
    firstName: 'Fred'
  },
```

This part: ```  // Only applicable for request methods 'PUT', 'POST', and 'PATCH'``` especially.

**Comment by namila007** [comment]
please add  this [comment](https://github.com/axios/axios/issues/897#issuecomment-343715381) to the docs

**Comment by sprlwrksAprilmintacpineda** [comment]
It's on the docs https://github.com/axios/axios#request-method-aliases
