### ISSUE TITLE
responseType: 'text' return Json Object

### ISSUE THREAD

**Issue by Airkro** [axios/axios#907]
```javascript
// test.txt  -->  adsasdsa55
axios.get('./test.txt', { responseType: 'json' }).then(response => {
    console.log( response.data );
    // output `null`, illegal, awesome!
});

// test.json  -->  [1233]
axios.get('./test.json', { responseType: 'json' }).then(response => {
    console.log( response.data );
    // output Array(1233), ok!
});
```

But:

```javascript
// test.txt  -->  [false,5]
axios.get('./test.txt', { responseType: 'text' }).then(response => {
    console.log( typeof response.data );
    // output `object` , not `string`, why?
    console.log( response.data );
    // output Array(false, 5), not "[false,5]"
});
```

- axios version: *v0.16.1*

**Comment by drew-r** [comment]
It seems still uses JSON.parse or something.
I am getting typeof response.data === 'number' for a response of '1702'

**Comment by Airkro** [comment]
@drew-r

because: 
> `responseType` indicates the type of data that the server will respond with options are 'arraybuffer', 'blob', 'document', 'json', 'text', 'stream'

**Comment by rubennorte** [comment]
This is because `JSON.parse` is always tried in the response, even if `responseType` is text. We should fix that indeed.

**Comment by XuluWarrior** [comment]
I've been bothered by this behaviour as well.  In my case none of the data I am requesting is JSON and the caught JSON.parse exception was preventing me leaving "Pause on caught exception" on in my debugger.
Although not a complete fix (it doesn't respect responseType), I was wondering whether the default transformResponse function could respect the "content-type" in the response headers and only attempt to parse as JSON if the content type is application/json.  Currently transformResponse doesn't include headers in its signature but it is passed them by the calling transformData function.
e.g.
```
transformResponse: [function transformResponse(data, headers) {
    /*eslint no-param-reassign:0*/
    if (typeof data === 'string' && headers["content-type"] === "application/json") {
      data = data.replace(PROTECTION_PREFIX, '');
      try {
        data = JSON.parse(data);
      } catch (e) { /* Ignore */ }
    }
    return data;
  }]
```

**Comment by kestereverts** [comment]
Is there any progess on this issue? I was just caught out by this bug. I expected that ```responseType: 'text'``` would stop automatic JSON parsing.

**Comment by blacksonic** [comment]
Is it possible to override the default ```transformResponse``` method?

**Comment by punksta** [comment]
This is critical when in case of validating json scheme before parsing or stream parsing.

**Comment by punksta** [comment]
can be solved by passing 
```
transformResponse: undefined
```
to axios or request configs

**Comment by OzqurYalcin** [comment]
can be solved by using arraybuffer as responseType
```js
axios.get('./test.txt', { responseType: 'arraybuffer' }).then(response => {
    var buffer = new Buffer(response.data, 'binary');
    var textdata = buffer.toString(); // for string
    console.log(textdata);
    var jsondata = buffer.toJSON(); // for json
    console.log(jsondata);
});
```

**Comment by sky0014** [comment]
Hope fix this issue soon.

**Comment by hojas** [comment]
+1

**Comment by YJBeetle** [comment]
response.request.response is text

**Comment by zozoh** [comment]
@kvillaniholland  I use `transformResponse : undefined` to escape the auto json converting as @punksta commented above. And I am waiting this issue can be close also ^_^

**Comment by dolsup** [comment]
I'm suffering under the same problem too.. It doesn't make sense.
@rubennorte 🔔 
Is there any progress for it?

**Comment by 390029659** [comment]
这都2019年了，这个bug居然还在。目前是 通过 重写 `transformResponse` 方法解决的。希望作者能够重视起来，加个判断`config.responseType`的类型，然后再决定是否用`JSON.parse` 去转换数据应该不麻烦啊

**Comment by zozoh** [comment]
@390029659  我已经弃坑了，直接 100+ 行用  XmlHttpRequest 封了一个，完全用不着 axios 了，你要的话，我代码发你，很通用

**Comment by 390029659** [comment]
@zozoh 好啊，学习瞻仰一下，提前谢谢了

**Comment by zozoh** [comment]
@390029659  已经发你邮箱里了  `hrbeta@foxmail.com`

**Comment by ifuning** [comment]
i use  'transformResponse: undefined' , but fail 

this can be solved 
`transformResponse: [(data) => {
                        return data;
                    }],`

version 0.19.0

**Comment by crimx** [comment]
It's been over 2 years. What is blocking the issue?

**Comment by DoronBrayer-RedisLabs** [comment]
I have the same issue. I get `[object Object]`. Please help.

**Comment by chinesedfan** [comment]
The problem is the default config.transformResponse will always try to parse string to json. You can set another transform function. And please keep an eye on #811.

**Comment by Draphar** [comment]
This issue makes me almost speechless. What did the developers think when writing this? "So the user might not want JSON, but we'll try anyway and then override the user's choice" When is this kind of behaviour desired? A library that patronizes me like this is terrible.

**Comment by WoLfulus** [comment]
> 
> 
> This issue makes me almost speechless. What did the developers think when writing this? "So the user might not want JSON, but we'll try anyway and then override the user's choice" When is this kind of behaviour desired? A library that patronizes me like this is terrible.

I'm sorry, but what makes me speechless is comments like this. Just don't.

**Comment by yiyione** [comment]
Nobody fix this bug?

**Comment by RobinDeBaets** [comment]
This bug still happens. Quite annoying when you fetch a piece of JSON data that you want to handle as a raw string.
