### ISSUE TITLE
Several IDEs report ReactJs axios({}).then() is undefined (same with axios.* methods).

### ISSUE THREAD

**Issue by pabloa** [axios/axios#914]
#### Several IDEs report ReactJs axios({}).then() is undefined (same with axios.* methods).

After upgrading from axios 0.15.0, webstorm, atom and intellij cannot see axios().methods.

Foe example this line
```
axios({}).then(function(response) { ...}) 
``` 

works, but all the IDEs reports that ".then()" is not defined in axios version 0.16.1

#### Context

- axios version: *e.g.: v0.16.1*
- Environment: *e.g.: webstorm, atom, intellij*

It seems the problem is fixed by adding *typings.json* file with something like: 
```
{
  "dependencies": {
    "es6-promise": "registry:npm/es6-promise#3.0.0+20160723033700"
  }
}
``` 

could this file typings.json be added back to version 0.16.x?

**Comment by rubennorte** [comment]
@nickuraltsev could you take a look at this?

**Comment by LeonardoGentile** [comment]
I've also noticed this on webstorm

**Comment by KamiKillertO** [comment]
Did you still have the problem with axios v0.17.1 ?

**Comment by chinesedfan** [comment]
See https://github.com/axios/axios/commit/3704d57ed47712e0470586f743a4780dd884c6de#diff-35b4a816e0441e6a375cd925af50752cR17. Make sure you have added those built-in libs in your tsconfig.json.
