### ISSUE TITLE
Suggesting to use rollup for builds

### ISSUE THREAD

**Issue by FDiskas** [axios/axios#940]
More info could be found at https://rollupjs.org
https://code.lengstorf.com/learn-rollup-js/

**Comment by rubennorte** [comment]
We can explore this but I being honest I don't think it's a priority for the moment.

**Comment by SidKwok** [comment]
I submit a [PR](https://github.com/axios/axios/pull/1075) to replace webpack with rollup.

**Comment by AllainPL** [comment]
By now webpack 3 migration is merged https://github.com/axios/axios/pull/1334, also by now we have webpack 4 so it might be a good idea to think again webpack vs rollup but for now this issue is probably to close @emilyemorehouse.

**Comment by jasonsaayman** [comment]
We are already using webpack, which should be updated to the latest version with #3718

**Comment by FDiskas** [comment]
I'm not talking about webpack. It's too heavy for simple job. I suggesting a rollup instead

**Comment by jasonsaayman** [comment]
I understand but we are using webpack 4 now, is there any significant reason why we should change the tool we use?

**Comment by jasonsaayman** [comment]
Well, let me know, also keep in mind that there is a planned upgrade to provide more module types thing ESM etc as well as maybe a full typescript based re-write. Also what about [Parcel](https://parceljs.org/)?

**Comment by FDiskas** [comment]
Probably the main reason is that rollup really good at bundle size.

Parcel - the latest one does not yet able to bundle the module without the issues. To many bugs (not stable) and also to heavy

I would also give a try with https://github.com/developit/microbundle
It follows a good practices and under the hood also rollup is used

**Comment by jasonsaayman** [comment]
Ok cool, thanks @FDiskas if you would like you could look at either a plan as to how we could migrate to rollup or even look at putting in a pull request? I am adding this to my tasks too.

**Comment by FDiskas** [comment]
I would love to make it happen. Not sure about my free time but I will try to make PR with a concept

Su pagarba,
Vytenis
tel.: +370 643 77855

**Comment by jasonsaayman** [comment]
Sure, well even if you can just start with a concept on the other thread
just telling me what you would look at etc

**Comment by FDiskas** [comment]
What I'm going to do

1. Get rid of dist
2. Remove typedefinition files and generate them instead
3. Rewrite everything to typescript
4. Move from travis to github actions
5. Implement auto releases so that not only core maintainer could release package

Su pagarba,
Vytenis
tel.: +370 643 77855

**Comment by jasonsaayman** [comment]
We should probably collaborate as I am already working on most of this. Let me know
