### ISSUE TITLE
Stream to POST, PUT request

### ISSUE THREAD

**Issue by StarpTech** [axios/axios#961]
Hi is it possible to pipe a stream to POST, PUT request like in `request` package?

```js
fs.createReadStream('file.json').pipe(request.put('http://mysite.com/obj.json'))
```

Reference: https://github.com/request/request#streaming

**Comment by StarpTech** [comment]
When I pass a readable stream as `data` the data will never arrive but only a empty object. When I try the same with `request` package it works.

**Comment by StarpTech** [comment]
Any updates?

**Comment by rubennorte** [comment]
Could you share a more complete example of `data` being a stream not working properly?

**Comment by StarpTech** [comment]
Hi  @rubennorte just try to pass a stream as data and you will run into it.

**Comment by graingert** [comment]
@StarpTech can you repeat this on https://runkit.com?

**Comment by gr2m** [comment]
I think I run into the same problem when passing a readable stream to the `data` request option

I've created at test case repository at https://github.com/gr2m/axios-upload-stream

I tried to make it work with the `fs.createReadStream('file.json').pipe(request.put('http://mysite.com/obj.json'))` but dunno how the express handler would look like.

**Comment by gr2m** [comment]
I was able to upload a file read stream using axios by also adding a Content-Length header

```js
const MY_FILE_PATH = 'README.md'
const fs = require('fs')
const axios = require('axios')

const readmeStream = fs.createReadStream(MY_FILE_PATH)
readmeStream.on('error', console.log)
const {size} = fs.statSync(MY_FILE_PATH)

axios({
  method: 'POST',
  url: 'https://uploads.github.com/repos/gr2m/sandbox/releases/8300256/assets?name=README.md',
  headers: {
    'Content-Type': 'text/markdown',
    'Content-Length': size,
    'Authorization': 'token 123reducted'
  },
  data: readmeStream
})
```

But that might have been a GitHub-specific requirement. I don't know a different way to test it

**Comment by gr2m** [comment]
I've updated my minimal test case: https://github.com/gr2m/axios-upload-stream

I can confirm that setting `data` to a fs read stream is working and setting `Content-Length` is not required.

**Comment by gr2m** [comment]
I've updated my minimal test case: https://github.com/gr2m/axios-upload-stream

I can confirm that setting `data` to a fs read stream is working and setting `Content-Length` is not required.

**Comment by libasoles** [comment]
I confirm it's possible to use POST verb to stream a file. I'm doing so with nextJs and koa. 

In my specific case, I'm not forwarding a concrete file, though. Basically I expose a backend endpoint (in nextjs), which acts like a proxy between front end uploads and a backend API built on PHP. Don't ask me why we have this proxy, but let's just discuss the stream issue.

So, using `pipe` sends a GET request by default. Anyway, I think this should work for simple forms (with no `formData`): 
`fs.createReadStream('file.json').pipe(request.put('http://mysite.com/obj.json'))`

or 

`ctx.req.pipe(request.put('http://mysite.com/obj.json'))` 

But if you need to use `formData`, then this approach will not work and you need to use `stream events` instead.

See:
```
api.post('/registrations/:id/my-attachment', async ctx => {
  const { id } = ctx.params;
  
  const request = async (chunk) => {
    const data = new FormData();
    data.append('attachment', chunk);

    const response = await axios({
      method: 'POST',
      url: `/registrations/${id}/my-attachment`,
      data,
      headers: {
        'Content-Type': ctx.req.headers['content-type'],
      },
    })
    
    ctx.res.headers = response.headers;
    ctx.body = response.body;
    console.log("UPLOAD OK")
    ctx.status = 201;
  };
  
  await ctx.req.on('data', await request);
  console.log("END"); // sadly, this is executed before "UPLOAD OK"
});
```

This works. However, I can't figure out yet why the response is being sent before getting the axios response.

If you want to read something more about events, see this article:
https://medium.freecodecamp.org/node-js-streams-everything-you-need-to-know-c9141306be93

**Comment by iislucas** [comment]
I don't see any check in the above cases that the contents of the file/data is actually uploaded... when I tried using a `Readable` stream passed to axios as data, the actual data never gets uploaded.

**Comment by christiansakai** [comment]
I can confirm that this does not work with Axios.

```
// sendFile.js
const fs = require('fs')
const axios = require('axios')
const request = require('request')
const FormData = require('form-data')

const fileServerUrl = 'http://localhost:3001/storage'

function sendFileStreamUsingAxios () {
  const hugeStream = fs.createReadStream('./huge.csv')
  const formData = new FormData()
  formData.append('file', hugeStream)

  return axios({
    method: 'post',
    url: fileServerUrl,
    headers: {
      'content-type': 'multipart/form-data'
    },
    data: formData
  })
}

function sendFileStreamUsingRequest () {
  const hugeStream = fs.createReadStream('./huge.csv')

  return request({
    method: 'POST',
    uri: fileServerUrl,
    formData: {
      file: hugeStream
    }
  })
}

// Uncomment below to try
// sendFileStreamUsingAxios() // Does not work
// sendFileStreamUsingRequest() // Work
```

```
// fileServer.js
const express = require('express')
const Busboy = require('busboy')

const app = express()

app.post('/storage', (req, res) => {
  const busboy = new Busboy({ headers: req.headers })

  busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
    console.log('File [' + fieldname + ']: filename: ' + filename + ', encoding: ' + encoding + ', mimetype: ' + mimetype)

    file.on('data', (data) => {
      console.log('File [' + fieldname + '] got ' + data.length + ' bytes')
    })

    file.on('end', () => {
      console.log('File [' + fieldname + '] Finished')
    })
  })

  busboy.on('field', (fieldname, val, fieldnameTruncated, valTruncated, encoding, mimetype) => {
    console.log('Field [' + fieldname + ']: value: ' + console.inspect(val))
  })

  busboy.on('finish', () => {
    console.log('Done parsing form!')
    res.writeHead(303, { Connection: 'close', Location: '/' })
    res.end()
  })

  req.pipe(busboy)
})

app.listen(3001, () => console.log(`Started file server`))
```

**Comment by ScriptSmith** [comment]
@christiansakai This works for me for file -> POST using the "Save all incoming files to disk" busyboy example server:

```javascript
function sendFileStreamUsingAxios() {
    const hugeStream = fs.createReadStream('./huge.csv')
    const formData = new FormData()
    formData.append('file', hugeStream)


    formLength = formData.getLength((err, len) => {
        const headers = formData.getHeaders({'content-length': len})

        return axios({
            method: 'post',
            url: fileServerUrl,
            headers: headers,
            data: formData
        })
    })
}
```

**Comment by ScriptSmith** [comment]
I've been able to get axios to stream GET -> PUT / POST like so:

GET -> PUT:
```typescript
const downloadUrl = "https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x5400x2700.png";
const uploadUrl = "http://127.0.0.1:8080/file.txt";

(async () => {
    const downStream = await axios({
        method: 'GET',
        responseType: 'stream',
        url: downloadUrl,
    })

    const contentType = downStream.headers['content-type']
    const contentLength = downStream.headers['content-length']
    if (contentType === null || contentLength === null) {
        throw new Error("Invalid headers")
    }

    const upStream = await axios({
        method: 'PUT',
        url: uploadUrl,
        headers: {
            'Content-Type': contentType,
            'Content-Length': contentLength
        },
        data: downStream.data
    })
})()
```

GET -> POST:
```typescript
const downloadUrl = "https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x5400x2700.png";
const uploadUrl = "http://localhost:8000/"

(async () => {
    const downStream = await axios({
        method: 'GET',
        responseType: 'stream',
        url: downloadUrl,
    })

    const formData = new FormData()
    formData.append('file', downStream.data)

    const headers = formData.getHeaders()

    return await axios({
        method: 'post',
        url: uploadUrl,
        headers: headers,
        data: formData,
        maxContentLength: 1000000000
    })
})()
```

**Comment by christiansakai** [comment]
@ScriptSmith Thank you, it does work. Is there a way to put the filename not on the URL?

**Comment by chinesedfan** [comment]
Looks like the problem is that required headers are not set correctly. If there is anything axios should have to improve, feel free to open an issue.

**Comment by oguzhaneren** [comment]
While request is reading the data chunk by chunk, 

`await readableStream.pipe(request.put(url));`

axios is reading all bytes from stream, so uses memory inefficiently

`await axios.put(url, readableStream)`

are there any options to limit axios request buffer?
