### ISSUE TITLE
Support unix domain socket

### ISSUE THREAD

**Issue by Dreamacro** [axios/axios#975]
In `adapters/http.js`, it request use `https` or `http` module with `options`.

```javascript
var options = {
  hostname: parsed.hostname,
  port: parsed.port,
  path: buildURL(parsed.path, config.params, config.paramsSerializer).replace(/^\?/, ''),
  method: config.method,
  headers: headers,
  agent: agent,
  auth: auth
};
``` 
We can add a key to support unix domain socket

```javascript
var options = {
  hostname: parsed.hostname,
  port: parsed.port,
  path: buildURL(parsed.path, config.params, config.paramsSerializer).replace(/^\?/, ''),
  socketPath: config.socketPath,  // just for test
  method: config.method,
  headers: headers,
  agent: agent,
  auth: auth
};
```

using axios like

```javascript
axios({
  socketPath: '/var/run/docker.sock',
  url: '/images/json'
})
.then(resp => console.log(resp.data))
```

I don't know if it fits your design concept, so I mentioned this issue

**Comment by rubennorte** [comment]
It's clearly not a priority for us as this seems an uncommon use case, but if adding this feature doesn't add much complexity to axios we can consider adding it.

Are you willing to create a PR for this with some tests?

**Comment by clusteratlas** [comment]
sindre's got would be more fitting

https://www.npmjs.com/package/got
