### ISSUE TITLE
Different behavior when posting data parameter or config.data

### ISSUE THREAD

**Issue by Aebrathia** [axios/axios#977]
Hi,

I tried to upload a file using axios.post and FormData and found that `axios.post(url, data, config)` does not produce the same result as `axios.post(url, {data: data})`.

At least I managed to get my code working but maybe this sould be fixed or documented or I missed the point.

Here's my code:

```js
handleSubmit(e) {
    e.preventDefault();
    /* Does not work (payload data is empty) */
    axios.post(`/eleve/api/submissions/${this.props.id}/submit`, new FormData(e.target), {
        onUploadProgress: this.handleUploadProgress
    });
   /* Works just fine */
    axios.post(`/eleve/api/submissions/${this.props.id}/submit`,  {
        data: new FormData(e.target),
        onUploadProgress: this.handleUploadProgress
    });
}
```

```jsx
<form onSubmit={this.handleSubmit}>
    <input name="file" type="file" required />
    <button type="submit">Submit</button>
</form>
```

Thanks for the work !

### Context

- axios version: 0.16.2
- Environment: Chrome 55.0.2883.87

**Comment by robaxelsen** [comment]
Hi @Aebrathia, thanks for reporting this. If you're still having issues with this, could you please provide a feature request in the form of a PR?
