### ISSUE TITLE
Instance does not have global interceptors

### ISSUE THREAD

**Issue by tomprats** [axios/axios#993]
#### Summary

I searched through all the issues and double checked the ones referenced in https://github.com/mzabriskie/axios/issues/812 but my problem seems to be different.

My problem is that creating an instance does not copy over or use the interceptors added to the global Axios.

```
import Axios from "axios";

Axios.interceptors.request.use((config) => {
  console.log("Global Interceptor")
  return config;
});

const axiosInstance = () => {
  let instance = Axios.create();
  console.log(Axios.interceptors.request); // Has 1
  console.log(instance.interceptors.request); // Has 0
  return instance;
}

axiosInstance().post("/test", { testing: "data" }); // Doesn't output "Global Interceptor"
Axios.post("/test", { testing: "data" }); // Outputs "Global Interceptor"
```

#### Context

- Axios version: 0.16.2
- Environment: Webpack 2.6.1, Chrome Canary 61.0.3147.0, Mac OS X

**Comment by rubennorte** [comment]
You're right but if we implement this we should answer (and document) some questions first:

- Are global interceptors inherited by instances in run time or copied when created?
- If they are inherited in run time, what should be the order of the interceptors?

We can ask the same about the rest of the instance vs global defaults by in most cases the order factor doesn't exist.

@mzabriskie, @nickuraltsev: thoughts?

**Comment by bierik** [comment]
@rubennorte I would suggest not adding the feature of `global interceptors`. What about extending an existing axios instance. This way the developer exactly knows what interceptors and options are inherited or extended:

``` javascript
import axios from 'axios';

export const api = axios.create({
  baseURL: process.env.API_ROOT,
});

api.interceptors.request.use((request) => {
  request.headers.Authorization = `Bearer mytoken`;
  return request;
});

// Here the pdfInstance extends the api instance so the pdfInstance has also access to the request interceptor but is also able to override the baseURL and adding additional header such as Accept
export const pdfInstance = api.extend({
  baseURL: '/file',
  responseType: 'arraybuffer',
  headers: {
    Accept: 'application/pdf',
  },
});
```

**Comment by psachs21** [comment]
I agree with @bierik, it would be really nice to be able to extend existing instances, though ordering is in question. I think the safest bet is to inherit your extended interceptors and if you override them, then they no longer trigger. Though it would be nice to optionally trigger previous interceptors, similar to a super() call.

**Comment by EvanK** [comment]
What about a convenience function to pull in interceptors from an existing instance:

```js
// from the default instance
let api = axios.create({baseUrl:"http://internal.mycompany.com"});
api.interceptors.clone(axios);

// or from another created instance
let thirdParty = axios.create({baseUrl:"https://partner.example.com"});
thirdParty.interceptors.clone(api);
```

On top of that, you could explicitly pull interceptors from the default instance with a config option:

```js
let api = axios.create({defaultInterceptors:true});
```

**Comment by AuthorProxy** [comment]
please add this feature!

**Comment by Charles-Hang** [comment]
please add this feature! I don't want to copy, please

**Comment by lili21** [comment]
any updates?

**Comment by webxmsj** [comment]
> @rubennorte I would suggest not adding the feature of `global interceptors`. What about extending an existing axios instance. This way the developer exactly knows what interceptors and options are inherited or extended:
> 
> ```js
> import axios from 'axios';
> 
> export const api = axios.create({
>   baseURL: process.env.API_ROOT,
> });
> 
> api.interceptors.request.use((request) => {
>   request.headers.Authorization = `Bearer mytoken`;
>   return request;
> });
> 
> // Here the pdfInstance extends the api instance so the pdfInstance has also access to the request interceptor but is also able to override the baseURL and adding additional header such as Accept
> export const pdfInstance = api.extend({
>   baseURL: '/file',
>   responseType: 'arraybuffer',
>   headers: {
>     Accept: 'application/pdf',
>   },
> });
> ```

你好， 我想知道如何实现这个extend方法

**Comment by ywmail** [comment]
Any updates on this?

**Comment by chinesedfan** [comment]
Agreed with https://github.com/axios/axios/issues/993#issuecomment-335095893. And users can reuse global interceptors easily without any redundant codes, as long as saving them in a separated file. Followings are sample codes,

```
// wrapper.js
const interceptors = [
  [f11, f12], // pair of successful and failed handlers
  [f21, f22]
];

exports.default = function(chain) {
  interceptors.forEach(([f1, f2]) => chain.use(f1, f2));
};

// index.js
const wrapper = require('./wrapper');

wrapper(axios.interceptors.request);
wrapper(axios.create(config).interceptors.request);
```

**Comment by nelisbijl** [comment]
I solved it like this (used lodash for _):
```
// axios.create creates a new Axios object that does not copy the global interceptors
// this override fixes that
const orgCreate = axios.create;
axios.create = function (config?: AxiosRequestConfig): AxiosInstance {
    const result = orgCreate.call(this, config);
    _.forEach((axios.interceptors.request as any).handlers, (handler) => {
        result.interceptors.request.use(handler.fulfilled, handler.rejected);
    });
    _.forEach((axios.interceptors.response as any).handlers, (handler) => {
        result.interceptors.response.use(handler.fulfilled, handler.rejected);
    });
    return result;
}
```

**Comment by takeitforwardsolutions** [comment]
Thank you nelisbijl that worked out well, game saver.

**Comment by omrilotan** [comment]
Thank you, @nelisbijl I've taken your solution and added an inheritance type behaviour. If anyone finds this useful as well

1. "Inherit" any existing interceptors of global axios instance when creating a new axios instance.
2. Apply new interceptors to existing instances when adding interceptors to global axios instance.

```js
import axios from 'axios';

const TYPES = ['request', 'response'];
const { create } = axios;
const instances = [];

// new instances "inherit" existing interceptors
axios.create = function(...args) {
    const instance = create.apply(this, args);
    instances.push(instance);

    TYPES.forEach(
        (type) => axios.interceptors[type].handlers.forEach(
            ({ fulfilled, rejected }) => instance.interceptors[type].use(fulfilled, rejected)
        )
    );

    return instance;
};

// new interceptors are being "inherited" to existing instances
TYPES.forEach(
    (type) => {
        const { use } = axios.interceptors[type];

        axios.interceptors[type].use = function(...args) {
            const result = use.apply(axios.interceptors[type], ...args);
            instances.forEach(
                (instance) => instance.interceptors[type].use(...args)
            );
            return result;
        };
    }
);
```

**Comment by saransasidharan** [comment]
> I solved it like this (used lodash for _):
> 
> ```
> // axios.create creates a new Axios object that does not copy the global interceptors
> // this override fixes that
> const orgCreate = axios.create;
> axios.create = function (config?: AxiosRequestConfig): AxiosInstance {
>     const result = orgCreate.call(this, config);
>     _.forEach((axios.interceptors.request as any).handlers, (handler) => {
>         result.interceptors.request.use(handler.fulfilled, handler.rejected);
>     });
>     _.forEach((axios.interceptors.response as any).handlers, (handler) => {
>         result.interceptors.response.use(handler.fulfilled, handler.rejected);
>     });
>     return result;
> }
> ```

This worked. But something is not right. The global interceptors were added to one of the axios instance which was not created from the overridden create function. Finally, in the overridden create used a custom config parameter to decide upon whether to add the global interceptor.
